### ISSUE TITLE
Improve MagicNumber to allow use of named local variables

### ISSUE THREAD

**Issue by xenoterracide** [checkstyle/checkstyle#10004]
I feel like I should have an option to allow this with checkstyle

 ```java
    public CliConfiguration build() {
      return new TestCliConfiguration(
        this.name,
        this.classLoader,
        Objects.requireNonNullElse( this.moduleType, "project" ),
        Objects.requireNonNullElse( this.language, "java" ),
        Objects.requireNonNullElseGet( this.project, () -> {
          var numberOfChars = 8;
          return RandomStringUtils.randomAlphabetic( numberOfChars );
        } )
      );
    }
 ```

```
+--- com.puppycrawl.tools:checkstyle:{strictly 8.37} -> 8.37 (c)
```

**Comment by strkkk** [comment]
@xenoterracide please follow issue template

**Comment by xenoterracide** [comment]
@strkkk since this is a feature request, what do you need here?

**Comment by rnveach** [comment]
See https://checkstyle.org/report_issue.html#How_to_request_new_feature_for_existing_functionality.3F

**Comment by xenoterracide** [comment]
I'm not requesting a new check, and I still don't understand what piece of information is missing. guess I don't care, seems reporting issues here is too complicated for me, must be something wrong with me.

**Comment by rnveach** [comment]
It is up to you if you wish to continue with an issue or not.

To us documentation we pointed to seems clear. Let us know how it is not and what we can do to improve it.

> Please provide a clear and detailed description of the problem and describe what you would want to happen instead.
> Imagine that everything is possible and propose name of the new option and its behaviour.

To me, it is not clear what you mean by "named local variables" which is the absolute only thing I have to go on by what you have provided. All variables are given a name, and there is nothing standing out from your small description on what specific functionality / criteria you are looking for. Are you looking for suppression by a specific naming scheme, coding scheme, or .... ? We cannot tell you if it is reasonable or even possible to implement your feature without this information.

It is like you are coming to asking us to build your dream house without giving us specific dimensions, number of floors, style, etc... 

There is various methods to suppress violations seen at https://checkstyle.org/config_filters.html and if your case is too specific to just you and doesn't seem reasonable to everyone, we may point you to use them instead.
