### ISSUE TITLE
SuppressionFilter: new option 'optional' to allow skip SuppressionFilter if config file does not exist

### ISSUE THREAD

**Issue by edog305** [checkstyle/checkstyle#1002]
Our teams use a global checkstyle configuration file to ensure we all meet the same style standards. Some teams want the ability to ignore files specific to their project. Unfortunately, the suppression filter does not allow a non existent suppression filer file to exist. It throws an error. It would be painful to require every team and project branch to have this file.

Is it possible to ignore this error? Or can this be implemented?

Thanks!

**Comment by romani** [comment]
These are nothing is easy as ignoring errors :) .

Before I suggest smth, please describe structure of your project, i need to see why usage of cibfig file is easy for you and suppression file is a problem. If your project is opensource please give me a link to sources.

**Comment by edog305** [comment]
Sorry, it is not open source. We have several projects that use gradle. We have a custom Gradle plugin that pulls down our global checkstyle.xml config file from Artifactory into the config/checkstyle/ directory. Gradle then uses this location when running checkstyle.

A team member came to me and asked if it's possible to ignore specific java files files in checkstyle. After some research, i discovered the Supression Filter. The problem is, if I add the supression filter to the global config, all projects will start failing unless they have the associated suppression filter file. It would be ideal to ignore the FileNotFound exception rather than require every team to have the ignore file.

Thanks!

**Comment by romani** [comment]
can you have global suppression file ?

workaround: each project will suppress violations base on package info of file location (we have bunch of examples of our web site). I my close source projects we use global remotely hosted  configuration (checks + suppressions). If you write suppressions as strict they does not make any problem to other projects.

The only way out is to have special option for file location "optional='true'" that will ignore absence of file. That option will be false by default.

**Comment by edog305** [comment]
That is true. I could use a gobal suppression file every team uses. 

Does "optional='true'" exist for suppression files, or are you saying it could be implemented? That would be the preferable solution.

Thanks for the help.

**Comment by romani** [comment]
> Does "optional='true'" exist for suppression files, or are you saying it could be implemented? 

yes, that is reference to non existing functionality that make sense to implement. You can contribute that functionality if you want it to be done quicker.

**Comment by mkordas** [comment]
Adding this option is a great opportunity to do some refactoring around the code used to load the suppressions, as there are multiple smells there right now. E.g. `FileNotFoundException` is used to control the flow of [loadSuppressions](https://github.com/checkstyle/checkstyle/blob/1bd30555eac039d0486dffb3fc43b7a34117909b/src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionsLoader.java#L137) method.

**Comment by msteiger** [comment]
An alternative might be moving the suppressions into the main config file (suggested in #1051).

**Comment by romani** [comment]
fix is merged.
