### ISSUE TITLE
Restrict usage of org.junit.jupiter.api.Assertions package in tests

### ISSUE THREAD

**Issue by timurt** [checkstyle/checkstyle#10051]
Followed by 
https://github.com/checkstyle/checkstyle/issues/9142

To make changes incrementally and to be sure that no junit assertions are left, it is better to forbid package `org.junit.jupiter.api.Assertions` package in tests 

Scope of this issue
- add import control rule to restrict usage of `org.junit.jupiter.api.Assertions` package
- suppress all existing import control violations

@romani please read and approve

**Comment by shashwatj07** [comment]
> * suppress all existing import control violations

Should I suppress them by file or directory?

**Comment by timurt** [comment]
@shashwatj07 
> Should I suppress them by file or directory?

by file, smth similar to `checkstyle_input_suppressions`

**Comment by romani** [comment]
@timurt , Please do not forget to put label misc on issues on this project, as all other are not functional. Without label build is failing as reminder before release date to resolve all, such label are used to generate release notes
