### ISSUE TITLE
Add links to projects with additional checkstyle checks to site

### ISSUE THREAD

**Issue by strkkk** [checkstyle/checkstyle#10057]
At the moment there are links to related tools (plugins and other integrations) but it can be useful for user to find additional sources of checkstyle check, e.g. sevntu or https://checkstyle-addons.thomasjensen.com/#:~:text=Checkstyle%20Addons%20provides%20additional%20detectors,is%20well%20tested%20and%20stable.

There can be other custom useful checkstyle checks.

Idea came from feedback of one of the users.

**Comment by romani** [comment]
I always welcoming user to register their projects in this 
example - https://groups.google.com/g/checkstyle/c/trotZaE8rJc/m/jcK0aZ6MBwAJ
Just send a PR to add new link to project.

**Comment by strkkk** [comment]
@romani I meant to add there one more section like "Checkstyle extensions", since additional checks are not "tools", it is checkstyle extensions, which seems to be as a bit different thing.
