### ISSUE TITLE
Replace ANTLR2 dependencies in unit test inputs

### ISSUE THREAD

**Issue by nmancus1** [checkstyle/checkstyle#10059]
In support of https://github.com/checkstyle-antlr4/checkstyle-antlr4/issues/6, we should remove all ANTLR2 dependencies from unit test inputs. Since ANTLR2 is used in a few import check inputs, we should replace it's usages with ANTLR4 imports or move the files to non-compilable directories. There's no reason to wait to replace these imports or move these files to non-compilable directories, this would just make for more code to review at the time of ANTLR4 Java grammar project completion.

```bash

➜  checkstyle git:(master) grep -R antlr | grep -v "v4" | grep Input | grep -v "noncompilable"
src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/InputCustomImportOrderSpanMultipleLines.java:import antlr.*; // warn
src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/InputCustomImportOrderSpanMultipleLines.java:import antlr.Token;
src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/InputCustomImportOrderSingleLine.java:import antlr.*;
src/test/java/com/puppycrawl/tools/checkstyle/grammar/AstRegressionTest.java:import antlr.ParserSharedInputState;



```

**Comment by nmancus1** [comment]
We need to keep these particular inputs for these tests, because the unit tests count on imports that do not begin with `com`, `java`, `org`, etc.

**Comment by rnveach** [comment]
It would be better if we could just replace the imports with something else to keep them compilable.

**Comment by strkkk** [comment]
fix is merged
