### ISSUE TITLE
Use cache for maven dependencies to speed up drone io builds

### ISSUE THREAD

**Issue by strkkk** [checkstyle/checkstyle#10065]
Problem: execution of checkstyle build take a lot of time on CI systems, and some of it is spent on downloading dependencies.

Proposed solution: store maven dependencies as s3 cache and download them as a part of preparation for builds. 
Some CI systems has support for this feature, e.g. in [travis](https://docs.travis-ci.com/user/caching/) and [drone](http://plugins.drone.io/drone-plugins/drone-s3-cache/)

UPDATE: we starting to use sourceforge file system for maven repository - https://sourceforge.net/projects/checkstyle/files/drone-io/ , s3 will cost us 15$ a month, wedo not have sponsorship for this
details: https://github.com/checkstyle/checkstyle/pull/10679#discussion_r693565229

**Comment by rnveach** [comment]
I am for speedier builds, but you have to be careful since caches can cause their own issues. How much space are we given and will we need to control it and eventually flush it, etc...

**Comment by strkkk** [comment]
It can be very simple - one cache entry with .m2/repository zipped in one file, it can be updated only when there are changes in pom.xml in master branch.
Usual builds just download this item and unpack it. Even if there are some minor differences (e.g. version update), it will load only diff dependencies, not whole thing.

Space on s3 bucket should not be an issue.

**Comment by romani** [comment]
travis support cache by itself
https://github.com/checkstyle/checkstyle/blob/6c62d23e3e55fc0326eadab3737d80f1f04d335a/.travis.yml#L6-L8

I do not see the same in drone, we can do this for drone.

**Comment by sukolenvo** [comment]
Following plugin may be used for drone: http://plugins.drone.io/drillster/drone-volume-cache/ if its ok to have cache on agent host machine

**Comment by romani** [comment]
@sukolenvo, thanks a lot for hint, can you send PR to make it happen?

**Comment by sukolenvo** [comment]
@romani Sorry, I didn't realise you are using https://cloud.drone.io, seems like it doesn't support trusted mode which is required for the suggested plugin. https://discourse.drone.io/t/linter-untrusted-repositories-cannot-mount-host-volumes/3438/7

**Comment by romani** [comment]
We have s3, we can upload there zip with most dependencies, do you know how to setup cache usage from s3 ? 
Might be few bash commands ...

**Comment by sukolenvo** [comment]
I will prepare `.drone.yml` changes to use http://plugins.drone.io/drone-plugins/drone-s3-cache/ (I think its a preferred solution as saves us from maintaining own scripts), but you will need to configure S3 bucket, user, permissions and create two drone secrets for access key and access secret.

**Comment by strkkk** [comment]
fix is merged, thanks @sukolenvo
