### ISSUE TITLE
Implement input file parser 

### ISSUE THREAD

**Issue by timurt** [checkstyle/checkstyle#10076]
This issue if part of the **Adaptation of Behavior Driven Development ideas for testing of source code validation algorithms**  project. 

New parser should be able to extract:
- Check name or check class #10077
- Configuration properties #10141
- Violation list #10078
- Extract violation message #10079

Input example:
```
/*
ParameterName
applyToPublic = (default)true
applyToProtected = (default)true
applyToPackage = (default)true
applyToPrivate = (default)true
format = "^NO_WAY_MATEY$"


*/

class MyClass {
  public final static int FIRST_CONSTANT1 = 10;
  protected final static int SECOND_CONSTANT2 = 100;
  final static int third_Constant3 = 1000; // violation 'third_Constant3'
  private final static int fourth_Const4 = 50; // violation 
}

```

Parser will be located at `com.puppycrawl.tools.checkstyle.bdd` in `test` folder

@romani @shashwatj07 please have a look

**Comment by romani** [comment]
```
/* ParameterName
applyToPublic = (default)true
applyToProtected = (default)true
applyToPackage = (default)true
applyToPrivate = (default)true
format = "^NO_WAY_MATEY$"


*/
```

no asterist and two extra empty lines to future extension of Check with new property

**Comment by timurt** [comment]
> no asterist and two extra empty lines to future extension of Check with new property

updated as @rnveach suggested:
```
/*
ParameterName
applyToPublic = (default)true
applyToProtected = (default)true
applyToPackage = (default)true
applyToPrivate = (default)true
format = "^NO_WAY_MATEY$"


*/
```

**Comment by shashwatj07** [comment]
From Discord:

> JavadocPackageTest has violation on line 1 only, for some cases. How will such cases be handles when we incorporate bdd?

> Some tests use 2 files. Which file shall we parse for config?

**Comment by timurt** [comment]
> JavadocPackageTest has violation on line 1 only, for some cases. How will such cases be handles when we incorporate bdd?

maybe we can place violation comment right after top comment before package statement?

> Some tests use 2 files. Which file shall we parse for config?

can you provide examples please

**Comment by romani** [comment]
I recommend to skip edge cases for now, validation that requires two files might not need our bdd model of testing.
Our primary target is in Input where violation is visible in scope of few lines or file.

**Comment by romani** [comment]
Main implementation is done. Support for edge cases are happening in issues to support such edge cases
