### ISSUE TITLE
Implement enhanced version of verify with bdd parser

### ISSUE THREAD

**Issue by timurt** [checkstyle/checkstyle#10081]
prerequisite for #10390

This issue if part of the Adaptation of Behavior Driven Development ideas for testing of source code validation algorithms project.

Implement enhanced version of verify with bdd parser, that will be second execution after existing verify method

new method execution flow:
- call `AbstractModuleTestSupport.verify` method
- invoke input parser and extract config and violation
- compare parsed config name, properties and violation list with that were passed to method as arguments
- _call second time `AbstractModuleTestSupport.verify` with parsed configs_ - @romani should we?

**Comment by romani** [comment]
We do not need to execute AbstractModuleTestSupport.verify second time. New verify method focus on new functional only, and only at the end of implementation, it can do this to let easily deprecate old verify method usage in test methods.

**Comment by timurt** [comment]
already implemented

**Comment by timurt** [comment]
**UPD** @shashwatj07 
1. remove `expected` from signature `verifyWithInlineConfigParser`
2. remove `verify(parsedConfig, filePath, expected);`

**Comment by romani** [comment]
@timurt  why we need to remove "expected" array ? 

lets keep it as optional parameter, in case for Check it is critical to validate columns and some cases has few violation on the same line.
It should be optional only if Input file designed in such a way to do not have few violations on the same line. So contributor can choose option he think most suites in exact situation. Most preferable is no multiple violations on same line.
Such approach will help us to migrate smoothly to new concept, and do not be blocked by complicated cases.

ATTENTION: It is fine to stay on old way of expected definition if there is good reason or limitations or ... .
old way of expected is more strict and more precise approach, lets not remove precision if it is already there. We can keep all "expected" arrays in UTs, and be lazy only in new UTs methods or if some refactoring will bother us with updates in all lines/column numbers in such arrays.

**Comment by romani** [comment]
@timurt , please close this Issue, looks like we agreed to keep "expected" and old verify method.
