### ISSUE TITLE
Refactor input files in check tests

### ISSUE THREAD

**Issue by timurt** [checkstyle/checkstyle#10080]
This issue if part of the **Adaptation of Behavior Driven Development ideas for testing of source code validation algorithms** project.

Update of all inputs to have comment with config on top of file.
**Important**: Always keep extra 2 empty lines after last property, to let extend

Example:
Original:
```
package com.puppycrawl.tools.checkstyle.checks.naming.parametername;
import java.io.*;

/* Config:
 *
 * format = "^NO_WAY_MATEY$"
 */

final class MyClass
{
 private final static int fourth_Const4 = 50; // violation 
}
```

Updated:
```
/*
ParameterName
applyToPublic = (default)true
applyToProtected = (default)true
applyToPackage = (default)true
applyToPrivate = (default)true
format = "^NO_WAY_MATEY$"


*/

package com.puppycrawl.tools.checkstyle.checks.naming.parametername;
import java.io.*;

final class MyClass
{
 private final static int fourth_Const4 = 50; // violation 
}
```

**Comment by romani** [comment]
comment should be:
```
/* ParameterName
  applyToPublic = (default)true
  applyToProtected = (default)true
  applyToPackage = (default)true
  applyToPrivate = (default)true
  format = "^NO_WAY_MATEY$"


*/
```

no need in leading asterisk as it is formatting of javadoc.
content of multiline comment should be simple text, first line is name of Check
all other lines are string value that we will stream to jdk Property class loader to parse it.

**Comment by rnveach** [comment]
Very minor thing, but if we are going no asterisk, would it look better for everything to start on the next line and with/without indentation?
````
/*
ParameterName
applyToPublic = (default)true
applyToProtected = (default)true
applyToPackage = (default)true
applyToPrivate = (default)true
format = "^NO_WAY_MATEY$"


*/
````

**Comment by romani** [comment]
I do not mind. But somehow thought of all content on second line as property file content, it might demand to start start content on first column.

**Comment by romani** [comment]
It was huge huge effort of @shashwatj07  to make it happen.
