### ISSUE TITLE
Make coverage 100% for all classes at package com.puppycrawl.tools.checkstyle.checks.design

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#1009]
Assigned to : @Vladlis

that task is good for somebody who want to start contributing to Checkstyle.

http://checkstyle.sourceforge.net/cobertura/index.html
make code coverage 100% for package design - http://checkstyle.sourceforge.net/cobertura/frame-summary-com.puppycrawl.tools.checkstyle.checks.design.html

**Comment by Vladlis** [comment]
done
http://vladlis.github.io/frame-summary-com.puppycrawl.tools.checkstyle.checks.design.html

**Comment by romani** [comment]
https://github.com/checkstyle/checkstyle/blob/master/pom.xml#L761 we still have 3 exclusions there,
I do not see any non merged PR, am I miss smth ?

**Comment by Vladlis** [comment]
@romani, fixed

**Comment by romani** [comment]
merged. Thanks a lot !

**Comment by Vladlis** [comment]
my pleasure
