### ISSUE TITLE
Make coverage 100% for all classes at package com.puppycrawl.tools.checkstyle.checks.regexp

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#1010]
that task is good for somebody who want to start contributing to Checkstyle.

http://checkstyle.sourceforge.net/cobertura/index.html
make code coverage 100% for package - http://checkstyle.sourceforge.net/cobertura/frame-summary-com.puppycrawl.tools.checkstyle.checks.regexp.html

**Comment by romani** [comment]
assigned to @sabaka .

**Comment by sabaka** [comment]
covered
