### ISSUE TITLE
CovariantEqualsCheck doesn't include Enums

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#1011]
I'm not sure if this is a true issue, but I noticed the CovariantEqualsCheck doesn't check Enumeration classes and doesn't accept it as an acceptable token. Enums can have their own equal methods and, to me, it seems like the issue this check looks for can still happen for enumerations.
If this isn't an issue and is on purpose, then what is the reason for ignoring enumerations?

**Comment by romani** [comment]
yes, that is missed - https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/CovariantEqualsCheck.java#L70

**Comment by mkordas** [comment]
I would say that overriding equals method for an enumeration is very bad practice, because enums are singletons and they should be safely compared by reference.

But you are right, let's add enums to the acceptable tokens.

**Comment by rnveach** [comment]
> I would say that overriding equals method for an enumeration is very bad practice

It looks like it is so bad, that they made the equals/hashCode method final so you can't override it.
http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/6-b14/java/lang/Enum.java#Enum.equals%28java.lang.Object%29
For the life of me I don't know why I made an equals method in some of my old enumerations.

Since you can't add in an "equals(Object)" it makes adding it to this check pointless, unless you want to print an error instead saying that enums shouldnt have an equals method.

**Comment by mkordas** [comment]
Of course overriding `equals(Object)` is not possible, but the following code compiles:
```java
enum InputEnumCovariant {
    EQUALS;

    public boolean equals(InputEnumCovariant inputEnumCovariant) {
        return false;
    }

    int equals(Integer integer) {
        return 0;
    }
}
```
I'm updating the Checkstyle to report these two methods as violations of CovariantEquals.

**Comment by romani** [comment]
merged.
