### ISSUE TITLE
NoWhitespaceAfter takes over WhitespaceAround setting

### ISSUE THREAD

**Issue by maisonobe** [checkstyle/checkstyle#1013]
It seems a fix introduced between 6.2 and 6.3 changed the behaviour of NoWhitespaceAfter which now triggers an error with the following code, despiteWhitespaceAround is configured with at least PLUS in the tokens list :

    public class A {
        public static int[][] create(int i, int j) {
            return new int[i + j][3];
        }
    }

The error is "'i' is followed by whitespace."

I would think that an expression inside the square brackets for the array dimensions should be parsed as an expression, regardless of it being inside the brackets.
```
$ java -jar checkstyle-6.3-all.jar -c config.xml 3.java
Starting audit...
/var/tmp/3.java:3:25: 'i' is followed by whitespace.
Audit done.

$ java -jar checkstyle-6.2-all.jar -c config.xml 3.java
Starting audit...
Audit done.

$ cat 3.java 
public class A {
    public static int[][] create(int i, int j) {
        return new int[i + j][3];
    }
}

$ cat config.xml 
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
    "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
    "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
  <module name="TreeWalker">
    <module name="NoWhitespaceAfter"/>
  </module>
</module>
```

Problem is caused by - https://github.com/checkstyle/checkstyle/commit/e6638c3344a90ec1716feb1830790efe430a123a with attempt to fix #68 and #542

**Comment by romani** [comment]
your project is good target for regression testing :) , as you resolve all checkstyle violations we could use your project in our testing to make sure that regression will not happen after release.

right now you have "There are 17576 checkstyle errors.".

**Comment by maisonobe** [comment]
Well, in fact we use a customized checkstyle.xml which does not follow Sun rules ;-)
We make sure we don't get any checkstyle errors.

**Comment by maisonobe** [comment]
And to be fair, checkstyle is really a *great* help for maintaining our libraries. Thanks a lot!

**Comment by romani** [comment]
please let me know a command you use to check your code that produce no Checkstyle validations.

**Comment by maisonobe** [comment]
mvn site works (it uses maven-checkstyle-plugin 2.15 which in turns uses checkstyle 6.1.1), and looking at the project reports in the generated site.
I also use the eclipse checkstyle plugin 6.5.0 which uses checkstyle 6.5.
I also tried launching checkstyle from the command line with -c checkstyle.xml but needed to add -p prop with a property file containing line "checkstyle.header.file=/the/path/to/orekit/license-header.txt".

In fact, I do have warnings (a few TODO comments) but no error with the first two validation methods. With the third method (direct command line), I get  a handful of messages "Unable to get class information for @throws tag 'OrekitException'", despite the OrekitException class is in the list of 378 files I used in the command line.

What are the kind of errors you see? I often see a few thousand errors only when I fail to use the proper checkstyle.xml file, and in this case it probably defaults to Sun or Google conventions and complains about line lengths, operator wrapping. Is this what you experience?

**Comment by romani** [comment]
I just launched "mvn checkstyle:checkstyle" on master and got that amount of errors.

**Comment by maisonobe** [comment]
I got it!
It is another one of maven tricks. Our checkstyle configuration is set in the reporting section, it was not duplicated in the build section. So when running "mvn checkstyle:checkstyle" from the command line, it used a default configuration and not our regular one.
I have added the proper plugin configuration in the build section of the pom now, so the command can be run as you did and no problems occurs.

So we are back to the initial issue about the array. Note that the problem does not appear anymore in Orekit code since I did change it (precomputing the array size in a final int variable just above the allocation).

**Comment by romani** [comment]
Please push POM changes to remote, i will recheck.

**Comment by maisonobe** [comment]
It should be on github repo now.

**Comment by romani** [comment]
If would be great if you convert all TODO to issues on you issue tracker and remove them from code.
That will help me to run against your code latest checkstyle and expect zero violations.

FYI: please use maven-jxr-plugin to make you Chekstyle report more useful, example: http://roman-ivanov.blogspot.com/2014/10/how-to-use-snapshot-checkstyle-version.html

**Comment by maisonobe** [comment]
I have moved the TODO as requested, and also set up a more recent version of checkstyle (6.6).
maven-jxr-plugin was already set up in the pom.

**Comment by romani** [comment]
still 4 errors from JavadocMethodCheck
http://checkstyle.sourceforge.net/config_javadoc.html#JavadocMethod

please make your config as
```
        <module name="JavadocMethod">
            <property name="allowUndeclaredRTE" value="true"/>
            <property name="allowMissingPropertyJavadoc" value="true"/>
            <property name="validateThrows" value="false"/> <!-- !!!!! -->
        </module>
```

That validation is completely broken and will be deprecated very soon.
please disable that Check or checking

**Comment by maisonobe** [comment]
I have added the validateThrows false. I did not see any errors on my side, is this due to the fact I used 6.6?

**Comment by romani** [comment]
no, that Check exists for years and never worked well.

> There are 4 errors reported 

send me your output, my is below
```
$ mvn checkstyle:checkstyle
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building ORbit Extrapolation KIT 7.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-checkstyle-plugin:2.15:checkstyle (default-cli) @ orekit ---
[INFO] There are 4 errors reported by Checkstyle 6.6 with /home/romani/temp/1/Orekit/checkstyle.xml ruleset.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
```

**Comment by maisonobe** [comment]
I get this:

(lehrin) luc% LANG=C mvn checkstyle:checkstyle
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building ORbit Extrapolation KIT 7.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-checkstyle-plugin:2.15:checkstyle (default-cli) @ orekit ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 18.516s
[INFO] Finished at: Thu Apr 30 21:13:08 CEST 2015
[INFO] Final Memory: 25M/265M
[INFO] ------------------------------------------------------------------------
(lehrin) luc%

the last commit for me is cd73b37315. It is the one I pushed on github a few minutes ago.

**Comment by attatrol** [comment]
I am on it.

**Comment by romani** [comment]
merged.
