### ISSUE TITLE
Update inputs for AbstractJavadocCheckTest

### ISSUE THREAD

**Issue by timurt** [checkstyle/checkstyle#10149]
Child of #10080

**Comment by shashwatj07** [comment]
@timurt This needs discussion

How to handle these cases:
https://github.com/checkstyle/checkstyle/blob/0363d2e6c593b2a984a4514629870836243e2df8/src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheckTest.java#L84
and this one with 2 checks (this is the example you asked here https://github.com/checkstyle/checkstyle/issues/10076#issuecomment-856132949):
https://github.com/checkstyle/checkstyle/blob/0363d2e6c593b2a984a4514629870836243e2df8/src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheckTest.java#L141-L143

**Comment by timurt** [comment]
> ` final DefaultConfiguration checkconfig = createModuleConfig(TempCheck.class); `

for this case, what if we specify `AbstractJavadocCheck.Temp` as check name inside input file? can you justify?

> and this one with 2 checks (this is the example you asked here

it is more difficult, our current comment structure does not support children nodes

**Comment by shashwatj07** [comment]
> for this case, what if we specify ```AbstractJavadocCheck.Temp``` as check name inside input file? can you justify?

```AbstractJavadocCheckTest$Temp``` should work

**Comment by timurt** [comment]
> so we leave it for now?

yes, please create a separate issue, lets discuss there cases with several checks

**Comment by shashwatj07** [comment]
> yes, please create a separate issue, lets discuss there cases with several checks

https://github.com/checkstyle/checkstyle/issues/10171

**Comment by romani** [comment]
Fixed by https://github.com/checkstyle/checkstyle/issues/10171
