### ISSUE TITLE
ModifiedControlVariable: allow ignoring for-each loops

### ISSUE THREAD

**Issue by dhendriks** [checkstyle/checkstyle#1015]
Recently the ModifiedControlVariable check caught the following for me:

```java
for (int a = -10; a < 10; a++) {
    for (int b = -10; a < 10; a++) {
        ....
    }
}
```

Where due to a copy/paste bug, the second loop also changes the 'a' of the outer loop. So, this check is useful. However, I also have the following:

```java
for (String line: lines) {
    line = line.trim();
    ...
}
```

It would be nice if I could keep the ModifiedControlVariable, but exclude for-each loops. I believe this would be a useful extension, making it possible to use this check, without a whole bunch of false postivies for the for-each loops.

**Comment by dhendriks** [comment]
Just to be clear, in for-each loops, changing the value of the control variable doesn't influence the remainder of the iteration, while for 'normal' for loops it does. That is, the iterator object is not affected by changing the 'line' variable in the example above.

**Comment by romani** [comment]
Thanks for sharing your ideas, the main idea of Check is to forbid FOR variable changes, in analogy of forbitting changes to arguments of method.

But looks like we have two issues covered by one Check:
 - modification of iterator that could cause unexpected changes in iterating of collection
-  changes to original values of iterator

Resolution : we need new boolean option skipEnchantedLoop, default value is false.

**Comment by mkordas** [comment]
@romani, do you mean `skipEnhancedLoop`? Also, maybe `skipEnhancedForLoop` would be better?

**Comment by romani** [comment]
Yes, skipEnhancedForLoop is better name. Sorry for typo that was done from phone.

**Comment by romani** [comment]
merged.
