### ISSUE TITLE
Add Configuration.getPropertyNames and Configuration.getProperty and deprecate getAttributeNames getAttribute methods

### ISSUE THREAD

**Issue by shashwatj07** [checkstyle/checkstyle#10164]
there is no Atributes in Checkstyle, we have properties.
https://checkstyle.org/config.html#Properties

Attribute term probably come to us from XML config, as the only way to configure checkstyle.
But we consider other way of doing it configs: yml, .... .

API should be consistent with general documentation, and implementation details should not be leaked in API.

detected at https://github.com/checkstyle/checkstyle/pull/10142#discussion_r657443405

**Comment by timurt** [comment]
Rename `DefaultConfiguration` methods and fields from `attribute` to `property`

**Comment by pbludov** [comment]
Fix is merged.
