### ISSUE TITLE
Add support of Inline Config Parsing for tests with multiple checks

### ISSUE THREAD

**Issue by shashwatj07** [checkstyle/checkstyle#10171]
from https://github.com/checkstyle/checkstyle/issues/10149#issuecomment-867366041

Current Inline Config Parsing does not support tests with multiple checks

Example:
https://github.com/checkstyle/checkstyle/blob/0363d2e6c593b2a984a4514629870836243e2df8/src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheckTest.java#L141-L143

**Comment by romani** [comment]
Let's postpone this issue, we need to get to know why we combined them, it should be very good reason to keep this.

We can skip support for such cases at least till end of summer.

**Comment by romani** [comment]
We can reuse the same approach as I proposed for filters.

And we can keep such strange test on old method, as most likely such methods exists for coverage 100% requirements, not a functional testing of Check
