### ISSUE TITLE
Add support for multiple violations on same line in Input Parser

### ISSUE THREAD

**Issue by shashwatj07** [checkstyle/checkstyle#10190]
part of #10076

detected at https://github.com/checkstyle/checkstyle/pull/10182#discussion_r659023717

**Comment by romani** [comment]
Let's postpone this to the end of project, it might require special strategy on this or even refactoring of tests to avoid this if possible.

Let's collect cases to make better picture when we come to it.

**Comment by shashwatj07** [comment]
> Let's postpone this to the end of project, it might require special strategy on this or even refactoring of tests to avoid this if possible.

Please allow me to work on it right now. If we push it towards the end, we'll again have to refactor all inputs. Right now, I'll take care of it as we incrementally migrate to verify with the parser. This way, we can incrementally test the functionality too.

**Comment by romani** [comment]
Please explain why it will require refactoring ?
It is issue for very limited set of Checks, I expect no updates in other inputs at all. 

You can start sharing proposal of how to resolve this now.

**Comment by shashwatj07** [comment]
> You can start sharing proposal of how to resolve this now.

We'll simply need to use 2 Patterns, one for ```// violation``` and the one for ```// violation xx```. 

```
if("// violation xx" matches)
    add violation x times
else if("// violation" matches)
    add violation once
```

**Comment by shashwatj07** [comment]
https://github.com/checkstyle/checkstyle/pull/10616#discussion_r688828672 proposal

**Comment by romani** [comment]
Fix is merged
