### ISSUE TITLE
Allow block closing '}' to be on same line if single line block

### ISSUE THREAD

**Issue by dhendriks** [checkstyle/checkstyle#1019]
For the RightCurly check, to check that '}' should be on a line by itself, at the start of that line, I use:

```xml
    <module name="RightCurly">
      <property name="option" value="alone"/>
      <property name="tokens" value="CLASS_DEF,METHOD_DEF,CTOR_DEF,LITERAL_FOR,LITERAL_WHILE,LITERAL_DO,STATIC_INIT,INSTANCE_INIT"/>
    </module>
```

This allows for instance the following, as desired:

```java
    public static void main(String[] args) {
        // do something
    }
```

However, it would be nice to also allow the closing '}' to be on the same line as the opening '{', for single line blocks, as follows:

```java
    public String getTypeText() { return "int"; }
```

It appears we have to choose between on a new line or on the same line, and can't allow both these method forms.

I propose adding an option to the 'RightCurly' check, to ignore single line blocks (blocks with opening '{' and closing '}' on the same line.)

**Comment by romani** [comment]
http://checkstyle.sourceforge.net/config_blocks.html#RightCurly
http://checkstyle.sourceforge.net/property_types.html#rcurly

You proposal is reasonable for methods, but not ok for CATCH , FINALLY, ... - multi block statements.
And not on for multi statements single line block, example:
```
 public String getTypeText() { doSmth(); return "int"; }
```

So we could do new option at http://checkstyle.sourceforge.net/property_types.html#rcurly as "alone_or_single" - to enforce "{" to be alone on line and allow single-line-single-statement format  of block

That will force you you to create additional config block for METHOD_DEF, CTOR_DEF as target and that new option.

@dhendriks  , does it make sense to you ?

**Comment by dhendriks** [comment]
@romani I hadn't thought about multiple statements in a block, but I agree in that case you don't want it on a single line. Your proposal makes sense to me. As far as I can see now, it would be a good solution.

**Comment by romani** [comment]
merged.

**Comment by codemanmeet** [comment]
@romani Just wanted to understand, even if my option is     
``<module name="RightCurly">
      <property name="option" value="same"/>
      <property name="tokens" value="CLASS_DEF,METHOD_DEF,CTOR_DEF,LITERAL_FOR,LITERAL_WHILE,LITERAL_DO,STATIC_INIT,INSTANCE_INIT"/>
    </module>``

the following should not give me any error right?
``public String getTypeText() { return "int"; }``

**Comment by romani** [comment]
@codemanmeet , thanks for reporting that for now that is how it worked for long time ("same" mean "same with next " not a "same with } ").
But some improvements should be done: https://github.com/checkstyle/checkstyle/issues/1900

**Comment by MEZk** [comment]
@codemanmeet 
Right curly brace polisy which is set to ``same`` means that the right curly brace must be on **the same line** as the **next part of a multi-block statement** (one that directly contains multiple blocks, generally: if/else-if/else or try/catch/finally. For example:
 ````java 
try {
        ...
} finally { //same line as 'finally'
````

Please check [documentation](http://checkstyle.sourceforge.net/property_types.html#rcurly).

But, I agree that ``same`` seems confusing, because most of the users think that that brace policy means same as left curly or etc.
