### ISSUE TITLE
Standard Package wrong RegExp for CustomImportOrderCheck

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#1020]
I had an import from another utility with the naming "com.rveach.javaconverter" and CustomImportOrderCheck was flagging it in the wrong location as needed to be in "STANDARD_JAVA_PACKAGE". This is definitely not a standard java package.

The root of the problem is the default value for "standardPackageRegExp".
https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/CustomImportOrderCheck.java#L223

It should be something like "^(java\\.|javax\\.).*" to ensure only the first section of the import is "java", not that "java" appears anywhere in the statement.

**Comment by romani** [comment]
UT has to be created to avoid that issue in future.

**Comment by romani** [comment]
merged.
