### ISSUE TITLE
Upgrade Java Grammar from ANTLR2 to ANTLR4

### ISSUE THREAD

**Issue by nmancus1** [checkstyle/checkstyle#10272]
From https://github.com/checkstyle/checkstyle/wiki/Checkstyle-GSoC-2021-Project-Ideas#project-name-upgrade-java-grammar-from-antlr2-to-antlr4:

> Checkstyle needs to have new Java grammar that is based on ANTLR4 version. This task is very difficult but it is critical for Checkstyle as ANTLR2 library is not supported (from 2006) and is far less efficient. Old version has a bunch of syntax analysis limitations that have already been resolved in ANTLR4. Our team is already experiencing difficulties with support of current grammar as it is too complicated due to limited parsing abilities of ANTLR2.

In this issue, we can discuss finer points of this upgrade and remaining issues from https://github.com/checkstyle-antlr4/checkstyle-antlr4:

[Grammar should use all caps in naming of literals
](https://github.com/checkstyle-antlr4/checkstyle-antlr4/issues/22)

[Criteria for main repo merge](https://github.com/checkstyle-antlr4/checkstyle-antlr4/issues/13)

[Add EOF token to AST](https://github.com/checkstyle-antlr4/checkstyle-antlr4/issues/12)

**Comment by nmancus1** [comment]
There are a couple of cases where Checkstyle can currently parse non-compilable files:

[Example 1](https://github.com/INRIA/spoon/blob/master/src/test/resources/executable-reference/Foo.java)

reason - missing semicolon on line 7.

[Example 2](https://github.com/INRIA/spoon/blob/spoon-core-8.0.0/src/test/resources/noclasspath/SubscriptionAdapter.java)

reason - super constructor call not first statement in constructor (line 15)

Is there any good reason to continue supporting this syntax?

**Comment by pbludov** [comment]
No. If the java compiler cannot compile a file, there is no much reason to parse such file.
This is documented feature: https://checkstyle.org/writingchecks.html#Limitations

**Comment by romani** [comment]
Migration is merged
