### ISSUE TITLE
Default language only translation check

### ISSUE THREAD

**Issue by daniilyar** [checkstyle/checkstyle#103]
_Ported from Sourceforge patch [208](https://sourceforge.net/p/checkstyle/patches/208/)_

The issue what we get is related to TranslationCheck, it works fine, but it checks all property file locales for the key presence. In our case we have all keys in the default language (English in our case) property file only, the other languages might miss some keys as it's enough to have it only in English or translation in French is not ready yet. This  [patch](https://sourceforge.net/p/checkstyle/patches/_discuss/thread/014dea40/1321/attachment/) adds new property defaultLocales so TranslationCheck reports the missing keys in property files of the languages codes listed in the defaultLocales property.
For example, there are following properties files:

message.property

**hello=Hello**

message_de.property
hello=Hallo
warning_en.property

**cancel=Cancel**

warning_de.property
cancel=Abbrechen

Assume, that the default locale is English, so setting defaultLocales to , ,en we will get the missing keys "hello" and "cancel" in message.property and warning_en.property accordingly.
##

**Comment by MEZk** [comment]
@romani 
Take a look at the issue. The fix was implemented in #2166.
