### ISSUE TITLE
EmptyLineSeparator always requires empty line between header and package

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#1035]
[EmptyLineSeparator](http://checkstyle.sourceforge.net/config_whitespace.html#EmptyLineSeparator) was created to cover [4.6.1 Vertical Whitespace](http://google-styleguide.googlecode.com/svn/trunk/javaguide.html#s4.6.1-vertical-whitespace).

Right now it always enforces empty line between header and package
```java
///////////////////////////////////////////////////
//HEADER
///////////////////////////////////////////////////
package com.puppycrawl.tools.checkstyle.whitespace; // 'package' should be separated from previous statement.
```

There is nothing about such requirement in Google Style. It only says:
>A single blank line appears between consecutive members (or initializers) of a class: fields, constructors, methods, nested classes, static initializers, instance initializers.

We can either:
 1. Provide option to configure this behavior
 2. Do not check that empty line at all

Moreover, in Checkstyle codebase header is not separated from package, so we are not compliant with ourselves.

What do you think?

**Comment by romani** [comment]
I would rather add empty line to all files.

We tested Google config (http://checkstyle.sourceforge.net/google_style.html), I do not remember that we have that violation over Guava (http://checkstyle.sourceforge.net/reports/google-style/guava/), it mean that Google mean that, as it is part of automatic formatter.

**Comment by mkordas** [comment]
Indeed, they have empty line after header everywhere: https://github.com/google/guava/blob/master/guava/src/com/google/common/base/Enums.java#L16, so I agree, we should be checking that.

Someone might say, that we should provide option to disable something that is not strictly defined in style guide though. But it's up to you :) I'll proceed with PR to add these lines in Checkstyle.

**Comment by romani** [comment]
I have a lot of such conversations with community and Google, but lets wait for user's feedback.
Each option is Api for checkstyle, we need to bit reasonably lazy introducing them.

**Comment by benelog** [comment]
조사해보니, 현재 checkstyle에서는 package 선언문 다음에만 체크할수가 없네요. 우선 해당 규칙을 checkstyle검사에서는 제외합니다.
레거시에서도 거의 지켜지고 있고, IDE formatter에 의해서 신규 모듈에서도 지키는 것을 누락하는 경우가 거의 없어보이기에 우선 그렇게 조치했습니다.

https://oss.navercorp.com/engineering/coding-convention/commit/6980e7ad91aaf45b73f79c76b868145b1520552c

조사해본 결과는 아래와 같습니다.

header와 package사이의 공백체크는  checkstyle 프로젝트의 https://github.com/checkstyle/checkstyle/issues/218 에서 반영되었습니다. 구글 가이드에도 저희와 똑같이 이 규칙이 명시되지 않았는데도 검사를 하기 때문에 https://github.com/checkstyle/checkstyle/issues/1035 에서 개선 의견이 올라왔습니다. 그렇지만 일단 지켜보자는 식으로만 이야기되고 이슈는 닫혔습니다. 구글의 코드에서는 어쩔수 없어서인지 header와 package사이에 공백을 넣고 있기는 했습니다. 개선 의견을 checkstyle쪽에 다시 꺼내보고, 우선 순위가 높은 다른 이슈가 끝나는 시점까지 해결되지 않는다면 Pull request를 보내는것을 고려해보겠습니다. 옵션 넣는 방식으로는 고치는게 어려워보이지는 않네요.
