### ISSUE TITLE
Some Inputs can not have comment on line with violation

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#10378]
cases where we can not place comment on required line:
https://github.com/checkstyle/checkstyle/pull/10374#discussion_r671197262

https://github.com/checkstyle/checkstyle/pull/10491#discussion_r680475590

Proposals:
make comments like `// ^ violation` or `// violation on next line` or ...

**Comment by shashwatj07** [comment]
Example https://github.com/checkstyle/checkstyle/pull/10581#discussion_r684896478

**Comment by timurt** [comment]
another proposal is to make optional violations property in inline configuration comment

**Comment by shashwatj07** [comment]
> another proposal is to make optional violations property in inline configuration comment

this is good. very elegant and clean.

**Comment by romani** [comment]
> another proposal is to make optional violations property in inline configuration comment

@timurt , please make visual example. 

-------

`// violation on next line 'message ....'`
`// violation on previous line 'message ...'`

during parsing of trailing comments, we simply increase line number on +-1 on model object.
verify code should not be affected.

**Comment by shashwatj07** [comment]
@romani 

Why not shorten it to these?
```// violation above 'message'```
```// violation below 'message'```

**Comment by romani** [comment]
Fix is merged, if any enhancement required, we can do this without special issue or reference this issue again
