### ISSUE TITLE
Remove unused verify method

### ISSUE THREAD

**Issue by timurt** [checkstyle/checkstyle#10394]
after #10390

- make sure no class uses  `AbstractModuleTestSupport.verify` method
- remove `AbstractModuleTestSupport.verify`
- remove suppressions and check for  `AbstractModuleTestSupport.verify`

**Comment by romani** [comment]
It should be the last ticket in project, as such method might be required for cases where we can not place comment without affecting behavior

**Comment by rnveach** [comment]
Another option to completely removing it would be to find some way to trigger an error on it's use and allow suppression with reason it must be used in some weird circumstance.

**Comment by romani** [comment]
We can not remove old method as not all Checks can use this bdd concept ( especially if they report violation on first line  of file)

We do removal of allowance to use old style verify method in each PR

**Comment by strkkk** [comment]
@romani @shashwatj07 there is a todo item in code for this issue
https://github.com/checkstyle/checkstyle/blob/cd37aaf9a8e37a826388ce4c30b1ca3ba743eda2/pom.xml#L1530
it fails ci job https://github.com/checkstyle/checkstyle/runs/3392581972, please check

**Comment by romani** [comment]
@shashwatj07 , please use proper issue links over such files in config.
This issue should not be there.

**Comment by shashwatj07** [comment]
> @shashwatj07 , please use proper issue links over such files in config.
> This issue should not be there.

https://github.com/checkstyle/checkstyle/pull/10709
