### ISSUE TITLE
Remove suppressions for original verify method or explain in comment

### ISSUE THREAD

**Issue by timurt** [checkstyle/checkstyle#10390]
Before:
#10391
#10081

Scope of this issue:
- Update test classes one by one (one PR for each test)
- Migrate to new verify method
- Make sure code coverage and pitest coverage didn't change
- Remove suppressions for original `verify` method or expalin each/group of suppression why they stay permanent. All tests on fake/test Checks should be suppressed permanently, as there is no business value in such tests and they exists only for coverage of edge cases that are not achievable by existing public Checks.

Suppression: https://github.com/checkstyle/checkstyle/blob/0544f86f24ca3883393bd8c2f57105d77f2da3de/pom.xml#L1530
we need clear explanation on why each suppresion is required. If we are on lack of time to migrate, but there is no good reason to stay in permanent, separate issue should be create and placed as comment `<!-- until LINK-->`

**Comment by rnveach** [comment]
@romani @timurt Is this issue still valid and what is left to do? I could not find suppression listed in first post.

**Comment by romani** [comment]
Link is working fine, bunch of suppression still there, we need to cleanup/explain them or fix them.

**Comment by romani** [comment]
Yes, we claim now that all is resolved
https://github.com/checkstyle/checkstyle/blob/5e4314550a38ff547d01874f9a16ad9e0c4a5724/pom.xml#L1544
But I would rather recheck why list is so big.
There might be some new separate tickets need to be created to resolve some of them.

**Comment by romani** [comment]
I am closing this issue, we will do final updates at https://github.com/checkstyle/checkstyle/issues/11446
