### ISSUE TITLE
Fix DeclarationOrder check violations in Checkstyle code

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#1049]
Rule: http://checkstyle.sourceforge.net/config_coding.html#DeclarationOrder
Follow-up to #945.

1. Class (static) variables. First the public class variables, then protected, then package level (no access modifier), and then private.
2. Instance variables. First the public class variables, then protected, then package level (no access modifier), and then private.
3. Constructors
4. Methods

**Comment by romani** [comment]
merged

**Comment by romani** [comment]
eventually we will use https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/master/sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/CustomDeclarationOrderCheck.java for declaration order check.

**Comment by mkordas** [comment]
Looks good :) We also need to remember about #924 for CustomDeclarationOrder...
