### ISSUE TITLE
Update inputs for IndentationCheckTest

### ISSUE THREAD

**Issue by shashwatj07** [checkstyle/checkstyle#10497]
Child of #10080

**Comment by romani** [comment]
@shashwatj07 , be careful with this Check Inputs, they already have trailing comments
there might be some other approach is requied for placing a trailing comment.

please place config on top as in all other Checks, but probably it is better to not update file with trailing comments "// violation" there might be huge amount on complications and we could deal with them as we start automation of it.

**Comment by shashwatj07** [comment]
@romani 
Even while placing config on top it is not happy.

```

java.lang.IllegalStateException: File "C:\Users\Shashwat\checkstyle\src\test\resources\com\puppycrawl\tools\checkstyle\checks\indentation\indentation\InputIndentationStrictCondition.java" has no indentation comment or its format malformed. Error on line: 1


```

**Comment by romani** [comment]
moved to https://github.com/checkstyle/checkstyle/issues/10663
