### ISSUE TITLE
upgrade appveyor to 3.8.1 maven and use option to now show download process

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#10513]
our Appveyor is still on 3.2.5 maven
we already moved most to 3.8.1 and use option in maven CLI to not print download progress that make logs much easier to read.

example of exhaustive logs https://ci.appveyor.com/project/Checkstyle/checkstyle/builds/40209636/job/9gdq17n6xvaqy4n7 with huge noise due to downloads

**Comment by romani** [comment]
@AkMo3 , can you help us with this ?
Looks like you become advanced in cloud CIs management.

**Comment by AkMo3** [comment]
Sure, I will look into it by end of this week. Just busy with a couple of things right now.

**Comment by romani** [comment]
Fix is merged
