### ISSUE TITLE
How to define null in inlined config

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#10527]
Think on this
https://github.com/checkstyle/checkstyle/pull/10525#discussion_r681395881
> checkConfig.addProperty("message", null);
> How do we replicate this in config comment?

**Comment by rnveach** [comment]
I am sure its not possible to. From memory, we only have tests like that incase someone programmatically calls our tool. We treat nearly everything as text, so `""` and `"null"` will not give you a true `null` but a string.

**Comment by shashwatj07** [comment]
Suggestion:

```
property = (null)
```
Let's consider this string as null.

**Comment by timurt** [comment]
I am ok with `property = (null)`
