### ISSUE TITLE
Add support for messages in inlined config

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#10545]
detected at https://github.com/checkstyle/checkstyle/pull/10532#discussion_r681905396

**Comment by shashwatj07** [comment]
Bad Idea:
```message = custom_message```
Some checks already have message property, hence this shall have nuances.

Worth considering:
```customMessage = custom_message```
```checkMessage = custom_message```

These don't have conflicts as of now with properties. Conflicts arising in future are also unlikely.

**Comment by romani** [comment]
in inlined config we have simple key value storage.

key is name of property. values is value of property.

> checkConfig.addMessage("matchxpath.match", "Do not use double-brace initialization");

we can do:
`message.matchxpath.match = Do not use double-brace initialization`

Two points:
1) prefix "message."
2) real java value never has "." in name so it will be very easy to distinguish them in parser.
