### ISSUE TITLE
Update maven-assembly-plugin to 2.5.4

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#1055]
Release Notes - Maven Assembly Plugin - Version 2.5.4

* Bug
    * [MASSEMBLY-742] - Unclosed ZipFile warnings when ZIP archives are included
    * [MASSEMBLY-746] - Warnings about platform dependent paths inconsistent.
    * [MASSEMBLY-747] - StackOverflowError when building assembly
    * [MASSEMBLY-748] - problem to extract zip files including file
names with umlauts
    * [MASSEMBLY-750] - descriptor in "dir" format changes symbolic
links in non symlink files
    * [MASSEMBLY-753] - LineEnding CR to LF conversion output is wrong
: All EOL are removed
    * [MASSEMBLY-754] - Non existing folder produces NPE
    * [MASSEMBLY-755] - missing whitespace in log message

* Improvement
    * [MASSEMBLY-764] - Upgrade to plexus-archiver 2.10 and io 2.5

**Comment by romani** [comment]
merged.

@mkordas , I think you can skip issue creation for such updated, just do PR, and change commit message after PR is created.

**Comment by mkordas** [comment]
All right, however this kind of updates are simples when done from web, and I can't update commit message without git client.

**Comment by mkordas** [comment]
Moreover, do we really want to use the same naming convention (`, issue#xxxx`) to refer to PRs? Issue is not PR, although they share the same numbering. 
This link works: https://github.com/checkstyle/checkstyle/pull/1056
But this doesn't:  https://github.com/checkstyle/checkstyle/issue/1056

**Comment by romani** [comment]
> But this doesn't: https://github.com/checkstyle/checkstyle/issue/1056

you missed "s" at the end of "issue", https://github.com/checkstyle/checkstyle/issues/1056 works as redirect.

> Moreover, do we really want to use the same naming convention (, issue#xxxx) to refer to PRs? I

I would rather remove "issue" and keep "#XXXX" to avoid any difference and keep reference to link that explain changes and reason in detail.

**Comment by mkordas** [comment]
Thanks for spotting typo :)

OK, that's great idea to get rid of `issue` in every commit. Can you modify http://checkstyle.sourceforge.net/contributing.html accordingly?

**Comment by romani** [comment]
done.
