### ISSUE TITLE
Util classes should be moved out of api package

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#1057]
com.puppycrawl.tools.checkstyle.api.AnnotationUtility
com.puppycrawl.tools.checkstyle.api.ScopeUtils

should be moved to com.puppycrawl.tools.checkstyle package with the same names and content.
Old files need to be marked as deprecated and removed in 6.8 or 6.9 release.

**Comment by mkordas** [comment]
@romani, I think this issue can be closed.
