### ISSUE TITLE
TreeWalker: Problems while checking always results to severity "error"

### ISSUE THREAD

**Issue by daniilyar** [checkstyle/checkstyle#106]
*Ported from Sourceforge patch [122](https://sourceforge.net/p/checkstyle/patches/122/), the text below was copy-pasted from there:*

Hello!
I would like to stop the build if checkstyle reports an "error" but the build should not stop if a "warning" occurs.
The problem is, that if Checkstyle is not able to do a test for some reason (e.g. "Got an exception - java.lang.RuntimeException: Unable to get class information for COSVisitorException.") the build fails because an "error" is reported.
The attatched patch uses the severity assigned to the module TreeWalker (default: "error") for this messages instead of always "error".
Greetings
[Bernhard Mähr](https://sourceforge.net/u/bmaehr/profile/)

There is suggested patch for TreeWarker: https://sourceforge.net/p/checkstyle/patches/_discuss/thread/b96f7579/95b4/attachment/TreeWalker.patch
and also additional patch which adds docs: 
https://sourceforge.net/p/checkstyle/patches/_discuss/thread/b96f7579/eb6c/attachment/TreeWalker.doku.patch

**Comment by romani** [comment]
in scope of https://github.com/checkstyle/checkstyle/issues/1304 all errors are rethrown to caller of checkstyle library.
