### ISSUE TITLE
Unit tests that involve `StackOverflow` should use limited stack size

### ISSUE THREAD

**Issue by nmancus1** [checkstyle/checkstyle#10605]
From discussion at https://github.com/checkstyle/checkstyle/pull/10600:

> The stack size depends on the platform (Java on 32-bit platforms uses a smaller stack).
Moreover, this may vary depending on the JVM vendor.

> Ideally, we need to be able to explicitly run a test with limited stack size.
I tried to do something like this in #9163 with a helper method:

> https://github.com/pbludov/checkstyle/commit/f3f96b326ec2901cfc3366e95787340e8e27a05c#diff-ae096b8cfa78e1dac18326e43375cbc21cc3b646bc99a85e49e83e971e88d68eR259

_Originally posted by @pbludov in https://github.com/checkstyle/checkstyle/issues/10600#issuecomment-896843237_

Due to differences in CI environment (type of machine, version/ vendor of Java, etc.) sometimes, the input at https://github.com/checkstyle/checkstyle/blob/5485431038c796622df4372f316fdcc4d31363cf/src/test/resources/com/puppycrawl/tools/checkstyle/javaparser/InputJavaParserNoStackOverflowOnDeepStringConcat.java will fail to kill pitest mutation in `JavaAstVisitor#visitBinOp`. Example: https://github.com/checkstyle/checkstyle/pull/10437/checks?check_run_id=3297051073

We have created a temporary fix for this case at https://github.com/checkstyle/checkstyle/pull/10600, but it would be ideal to ensure consistent behavior for all such tests.

**Comment by rnveach** [comment]
How is this issue different from https://github.com/checkstyle/checkstyle/issues/9253 ?

**Comment by nmancus1** [comment]
> How is this issue different from #9253 ?

This would be smaller in scope; we would only use this for specific unit test that require it. #9253 aims to create a specific CI build; this will not help us in this case, unless we also limit pitest CI stack size.
