### ISSUE TITLE
HideUtilityClassConstructor detects main classes as utility classes

### ISSUE THREAD

**Issue by mirkoseifert** [checkstyle/checkstyle#1061]
Classes which contain a public static void main(String[] args) method are detected by the HideUtilityClassConstructor as utility class. I think such classes should be not considered as utility class (unless they contain other public static methods).

If you agree, I can adjust the check.

**Comment by mkordas** [comment]
Would you consider the following class as valid?

    class Main {
        public static void main(String[] args) {
        }
     }

and this as invalid?

    final class Main {
        private Main() {};

        public static void main(String[] args) {
        }
     }

Utility class is just general name for all classes that contain only static methods or fields and the check is to prevent code such as `new Main()`, because it doesn't make sense to instantiate such classes.

**Comment by mirkoseifert** [comment]
Personally, I'd consider the first class valid and the second one also.

The reason I stumbled upon this is that we've got a lot of main class that look like this:

    public class Main {
        public static void main(String[] args) {
             new Main().run(args);
        }
        public void run(String[] args) {
             // Do the actual work
        }
    }

This allows to use the class both from the command line and from Java code itself (without calling a static method in the latter case). I get you point that this can also be achieved by putting the run() method into another class, but usually this feels a bit too much.

I see that one could argue about this for a while (as for many code style topics). What do you think about a configuration option for the HideUtilityClassConstructor check that allows to exclude classes from the check where the only static method is a `main(String[] args)` method?

**Comment by rnveach** [comment]
@mirkoseifert That example isn't picked up by HideUtilityClassConstructor in 6.6 as I checked running your example. A utility class must have all static fields/methods and/or private fields/methods and extend nothing or the java lang Object.
Your example has the non-static public "run". For your example to get flagged, "run" would have to be private or static.

**Comment by mirkoseifert** [comment]
You're right. The run method in the example should actually be private. This is what the our code for main classes usually looks like.

**Comment by romani** [comment]
> Utility class is just general name for all classes that contain only static methods or fields and the check is to prevent code such as new Main(), because it doesn't make sense to instantiate such classes.

Lets change a message (or create a new message) to clearly state what checkstyle dislike in that target code. Messages have to clear to all developers.

@mirkoseifert , even you have one method as private "run" and "main" method as public, it looks convenient only on first site. It cause serious misunderstanding how to use that class in production runtime (by "main" from cli or by java code ). I had such examples in my practice, and fortunately I persuaded to move all that "main()" to test folders and do not mislead other developers on how that Class is intended to be used.

If that pattern "main+run" do good for your project, I do not want to persuade you, I hope you know what you are doing. I do not see a reason in new option, I think you just need to use suppressions on classes you know for sure that "main" method is good to have. If you have "main" in almost all classes I would recommend you to disable that Check at all in your config (it is not a rare case when good practices do harm to code/performance/.... ).

**Comment by mirkoseifert** [comment]
Ok, you've convinced me :)

**Comment by ivan-gammel** [comment]
@mirkoseifert @romani is it possible to add a parameter for this check to ignore classes with the main method or with some specific annotation?
It's a common design pattern in Spring Boot world to have a class with main method only, which, due to framework limitations, cannot be declared final or have private constructor. With this check currently there exist only two options, neither of which is good one: 

1. Disable this check completely and do not validate real utility classes.
2. Ignore this check in every Spring Boot microservice individually.

My preference here would be 1 for the cleaner code in lots of classes, but the cost of it seems being still too high.

**Comment by ivan-gammel** [comment]
#3155 is about the same problem

**Comment by romani** [comment]
@MEZk , @timurt , please recheck if our upcomming xpath suppression could cover such cases. 
Users want to suppress violation on classes that have `@SpringBootApplication` annotation .

**Comment by MEZk** [comment]
@romani 
Asked @timurt to write UT for the mentioned case.

**Comment by enexusde** [comment]
Workaround:
You could implement serializable ([because logic say so](https://github.com/checkstyle/checkstyle/blob/5c9175616d844789bab980a6f1bdfea6f7d567fc/src/main/java/com/puppycrawl/tools/checkstyle/checks/design/HideUtilityClassConstructorCheck.java#L112)) and get rid of the marker.
