### ISSUE TITLE
SingleLineJavadoc and inheritDoc

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#1063]
The SingleLineJavadocCheck flags single line javadocs like @inheritDoc, which I think is wrong.

Code:
````
package test;

public class TestClass extends TestClass2 {
	/** {@inheritDoc} */
	@Override
	public void test1() throws Exception {
	}

	/**
	 * {@inheritDoc}
	 * */
	@Override
	public void test2() throws Exception {
	}
}
````

It flags line 4, the first javadoc, and not line 9, the second javadoc. I was expecting it to flag none.

I don't see why inheritDoc would require multiple lines, as it is a very simple doc to copy the parent's doc.
Google's documentation of this check just refer to the standard at-clauses. No mention of the inheritDoc specifically.
http://google-styleguide.googlecode.com/svn/trunk/javaguide.html#s7.1.3-javadoc-at-clauses
Even checkstyle's code uses this as a single line in most places.

**Comment by mkordas** [comment]
Thanks for reporting @rnveach. Indeed even Checkstyle code uses `/** {@inheritDoc} */` in one line. 
However, Google Style Guide says strictly: 
> The single-line form may be substituted when there are no at-clauses present, and the entirety of the Javadoc block (including comment markers) can fit on a single line.

and there are no exceptions to that rule. So I'd rather submit issue to Google first, but still, the majority inheritDocs I've seen on Github are mutliline: https://github.com/search?l=Java&q=inheritDoc+language%3AJava&type=Code

**Comment by romani** [comment]
We need to extend this Check with option to configure list of javadoc-tokens.

Check should work for all users, but google config should strictly follows Google guideline even it looks strange for others. We could investigate code of google and give them a note that most likely that tag was missed in style and most of Google code already use single line format.

Discussion with Guava project - https://github.com/google/guava/issues/1891

**Comment by romani** [comment]
assigned to @Vladlis .

**Comment by Vladlis** [comment]
>list of javadoc-tokens
@romani, you mean javadoc-tokens, which should ignored by the Check? If so, then which javadoc-tokens should be allowed in this list, any?

**Comment by romani** [comment]
> 1) @romani, you mean javadoc-tokens, which should ignored by the Check?

Yes, example of javadoc-tokens list please see at http://checkstyle.sourceforge.net/config_javadoc.html#AtclauseOrder

Option could be named as - ignoredAtclauses

> 2) if user wants to add an inline tag, which requires parameters, for instance

as user defined an ignored list he is responsible for that tokens, it is his responsibility to make sure that there is no tokens that require parameter. It even good that user can disable violation of tokens with parameters if he do want to do that.

>so only tags with parameter Comparable will be ignored?
Or should be both of these variants acceptable?

See my first reply, you should not consider parameters , just look at javadoc-tokens.

**Comment by romani** [comment]
merged.
