### ISSUE TITLE
SevNTU is no longer available in Eclipse

### ISSUE THREAD

**Issue by nkavian** [checkstyle/checkstyle#10657]
**Describe what you expect in detail.**

I'm using the latest Eclipse 2021-06.
I installed/updated to the latest Checkstyle plugin which upgraded me from 8.35 to 8.44.

The sevntu checks were available when I used 8.35.

After the upgrade, the sevntu checks have disappeared from the configuration screen. If I make any changes to other checks, the XML file is modified and the sevntu checks are removed.

If I search through the available update sites, the sevntu plugin is not found.
If I uninstall and reinstall Checkstyle, it doesn't resolve.

Everything however works fine if I stick with my Maven setup for 8.44 + 1.40.0

**Comment by romani** [comment]
Please move ticket to https://github.com/checkstyle/eclipse-cs/issues
