### ISSUE TITLE
Permanent suppression section at checkstyle_input_suppressions.xml

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#10652]
move Inputs that cannot have or no benefit of header inlined config to permanent suppression section:

https://github.com/checkstyle/checkstyle/blob/82c124e67c63d2764e32ebb4855f51df3685b092/config/checkstyle_input_suppressions.xml#L22

reword section:
` <!-- Suppress input files for JavadocMetadataScraper, as they are not inputs related to check configuration. -->`
to
` <!-- Suppress input files for following test classes, as they are not inputs related to check configuration. -->`

it will be section for permanent suppression.
Please do the same for "StyleValidationCommentInInputs" 

following java classes (and there respective Inputs should be moved to permanent suppression):
asttreestringprinter
detailastimpl
header
regexpheader
nocodeinfile
javadocdetailnodeparser
javadocpropertiesgenerator
newlineatendoffile
InputAllChecksDefaultConfig.java - we cannot use bdd here.
InputPackageNamesLoaderNotXml.java  - there is no intend to validate this file, used for different purpose.
InputXpathFilterElementSuppressByXpath - not used for Checks validation
InputDetailAstImplJustToMakeStackoverflowError - not used for Checks validation
InputChecker - not used for Checks validation
InputCheckerClearDetailAstLazyLoadCache  - not used for Checks validation
(if I missed something, please extend list)

All other should have separate issues and excuse comment should be "until #xxxxxxx", like for "indentation", "filters"

Indentation:
it is already on bdd, but on different implementation, lets keep it as is for now as such approach validate a lot more than our general bdd concept.
Please put all indentation in permanent suppression and please create issue to try to move Indentation to dbb, this issue should outside of gsoc21. All indentation group of suppression please squash into single suppression by package name like "indentation/*" and place a comment above it "until #xxxxxx".

Filters: 
https://github.com/checkstyle/checkstyle/issues/10653

**Comment by shashwatj07** [comment]
> please create issue to try to move Indentation to dbb

https://github.com/checkstyle/checkstyle/issues/10663
