### ISSUE TITLE
Migrate to Inline Config Parser in Sizes Check Tests

### ISSUE THREAD

**Issue by shashwatj07** [checkstyle/checkstyle#10676]
child of #10390

- [x] AnonInnerLengthCheckTest - #10678
- [ ] ExecutableStatementCountCheckTest - https://github.com/checkstyle/checkstyle/pull/10697
- [x] FileLengthCheckTest - #10678
- [x] LambdaBodyLengthCheckTest - #10681
- [x] LineLengthCheckTest - #10680
- [x] MethodCountCheckTest - #10678
- [x] MethodLengthCheckTest - #10678
- [x] OuterTypeNumberCheckTest - #10678
- [x] ParameterNumberCheckTest - #10678
- [x] RecordComponentNumberCheckTest - #10678

**Comment by romani** [comment]
Final is merged
