### ISSUE TITLE
Migrate to Inline Config Parser in Imports Check Tests

### ISSUE THREAD

**Issue by shashwatj07** [checkstyle/checkstyle#10671]
child of #10390

- [x] AvoidStarImportCheckTest - #10682
- [x] AvoidStaticImportCheckTest - #10682
- [x] CustomImportOrderCheckTest - #10682
- [x] IllegalImportCheckTest - #10683
- [ ] ImportControlCheckTest - #10727
- [x] ImportOrderCheckTest - https://github.com/checkstyle/checkstyle/pull/10686
- [x] RedundantImportCheckTest - #10687
- [x] UnusedImportsCheckTest - #10687

**Comment by shashwatj07** [comment]
> ImportControlCheckTest

This is an edge case. We pass the entire XML path to verify method. What to do?

**Comment by romani** [comment]
@shashwatj07 , please point to exact line that make problem to you. I do not understand you.

**Comment by shashwatj07** [comment]
@romani 

https://github.com/checkstyle/checkstyle/blob/cbe13dedb4f9d049e53a4ba87472ff068d41c068/src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlCheckTest.java#L66-L72

We do ```checkConfig.addProperty("file", getPath("InputImportControlOne.xml"));``` in original code.
However, in our parser if we specify inline config like ```file = InputImportControlOne.xml```, it won't work. We must supply entire path to config.

**Comment by romani** [comment]
> We must supply entire path to config.

Yes, this is nuance, usage or this method `getPath` was convenient  in UT method.
But in inlined config we should use full path, result  of getPath method.

**Comment by romani** [comment]
ImportControlCheckTest is left.

ideas for file path support:

> romani
08/22/2021
We can use some special identification as we did with default
file=(path)src/test/resources/checks/mycheck/InputConfigFile.xml
Inlined config has path in Linux format
After parsing we can convert path to windows format if required
And make it absolute path to be comparable to config from it method

> argyn
Yesterday at 2:51 AM
lets support two types
1. file=(path)src/test/resources/checks/mycheck/InputConfigFile.xml
2. file=(path)InputConfigFile.xml
for the second type we can generate full path using inputFilePath provided in TestInputConfiguration.parse method
