### ISSUE TITLE
Migrate to Inline Config Parser in Naming Check Tests

### ISSUE THREAD

**Issue by shashwatj07** [checkstyle/checkstyle#10688]
child of #10390

- [ ] AbbreviationAsWordInNameCheckTest - #10691
- [ ] AbstractClassNameCheckTest - #10691
- [ ] CatchParameterNameCheckTest - #10691
- [ ] ClassTypeParameterNameCheckTest - #10691
- [ ] ConstantNameCheckTest - #10691
- [ ] IllegalIdentifierNameCheckTest - #10691
- [ ] InterfaceTypeParameterNameCheckTest - #10691
- [ ] LambdaParameterNameCheckTest - #10691
- [ ] LocalFinalVariableNameCheckTest - #10691
- [ ] LocalVariableNameCheckTest - #10691
- [ ] MemberNameCheckTest - #10691
- [ ] MethodNameCheckTest - #10691
- [ ] MethodTypeParameterNameCheckTest - #10691
- [ ] PackageNameCheckTest - #10691
- [ ] ParameterNameCheckTest - #10691
- [ ] PatternVariableNameCheckTest - #10691
- [ ] RecordComponentNameCheckTest - #10691
- [ ] RecordTypeParameterNameCheckTest - #10691
- [ ] StaticVariableNameCheckTest - #10691
- [ ] TypeNameCheckTest - #10691

**Comment by romani** [comment]
Fix is merged
