### ISSUE TITLE
Return count reported incorrectly with Java 8 and lambda

### ISSUE THREAD

**Issue by ctl80** [checkstyle/checkstyle#1068]
There is a scenario where a method return count is reported as 2 when it should be 1, where the extra return counted comes from a lambda.  I've put together a small sample project here:

https://github.com/ctl80/checkstyle-returns  (see run_checkstyle.sh script and config.xml to see configuration of checkstyle).

Here's the part that is the most relevant and flagged for having multiple returns:
```java
public Properties getClientInfo() {
    return managedResource.withConnection(conn -> {
            Properties clientInfo = new Properties();
            try {
                clientInfo = conn.getClientInfo();
            } catch (SQLException e) {
                e.printStackTrace();
            }
            return clientInfo;
        });
}
```

**Comment by mkordas** [comment]
What about the following method?
```java
public int getClientInfo() {
    return managedResource.withConnection(conn -> {
            if (something) return 1;
            else if (somethingElse) return 2;
            else return 3;
        });
}
Do you expect the check to fail? Should we treat each lambda as nested method with its own limit?

**Comment by romani** [comment]
Lamdas is like an inner class-method, with its own scope and its own return counter.

**Comment by romani** [comment]
merged.
