### ISSUE TITLE
Github actions for pitest does not safe artifacts in master builds for all executions

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#10684]
https://github.com/checkstyle/checkstyle/actions/runs/1153979451

after all execution there is only one artifact: 
pitest-report-java-ast-visitor 

but we need all artifacts from failed jobs only for PRs.
and all artifacts failure/success in master.

Right now I need to advice contributors on what to do with certain pitest failure that in already in master and in ignore list, but I do not have report (shared with me and contributor)

**Comment by romani** [comment]
@AkMo3 , please help to resolve this issue.

**Comment by AkMo3** [comment]
This have been introduced in https://github.com/checkstyle/checkstyle/commit/003704a000881455349bd42bf9b16b91f2724ab9#diff-b6d38a7582c04d5561547ee4eaf0076a1a8c9b36bf27fcbbda4139449aefc0bc . I do a PR to fix this PR shortly.
