### ISSUE TITLE
Migrate to Inline Config Parser in Whitespace Check Tests

### ISSUE THREAD

**Issue by shashwatj07** [checkstyle/checkstyle#10689]
child of #10390

- [x] EmptyForInitializerPadCheckTest - #10696
- [x] EmptyForIteratorPadCheckTest - #10696
- [ ] EmptyLineSeparatorCheckTest - #10724
- [x] FileTabCharacterCheckTest - #10696
- [x] GenericWhitespaceCheckTest - #10696
- [x] MethodParamPadCheckTest - #10696
- [x] NoLineWrapCheckTest - #10696
- [x] NoWhitespaceAfterCheckTest - #10696
- [x] NoWhitespaceBeforeCaseDefaultColonCheckTest - #10696
- [x] NoWhitespaceBeforeCheckTest - #10696
- [x] OperatorWrapCheckTest - #10696
- [x] ParenPadCheckTest - #10696
- [x] SeparatorWrapCheckTest - #10696
- [x] SingleSpaceSeparatorCheckTest - #10696
- [x] TypecastParenPadCheckTest - #10696
- [x] WhitespaceAfterCheckTest - #10696
- [x] WhitespaceAroundCheckTest - #10696

**Comment by romani** [comment]
Fix is merged
