### ISSUE TITLE
Migrate to Inline Config Parser in Miscellaneous Check Tests

### ISSUE THREAD

**Issue by shashwatj07** [checkstyle/checkstyle#10693]
child of #10390

- [x] ArrayTypeStyleCheckTest - https://github.com/checkstyle/checkstyle/pull/10694
- [x] AvoidEscapedUnicodeCharactersCheckTest - #10695
- [x] DescendantTokenCheckTest - https://github.com/checkstyle/checkstyle/pull/10694
- [x] FinalParametersCheckTest - https://github.com/checkstyle/checkstyle/pull/10694
- [ ] NewlineAtEndOfFileCheckTest - https://github.com/checkstyle/checkstyle/pull/10722
- [x] NoCodeInFileCheckTest - #10698
- [x] OuterTypeFilenameCheckTest - #10698
- [x] TodoCommentCheckTest - #10698
- [ ] TrailingCommentCheckTest - https://github.com/checkstyle/checkstyle/pull/10722
- [x] UncommentedMainCheckTest - #10698
- [x] UpperEllCheckTest - #10698

**Comment by romani** [comment]
Fix is merged
