### ISSUE TITLE
Sign Drone CI config

### ISSUE THREAD

**Issue by sukolenvo** [checkstyle/checkstyle#10690]
Investigate possibilities of protecting Drone CI config files from tempering.
Design a workflow that would allow members to review and approve config changes (maybe github actions?).
Starting point: https://readme.drone.io/signature/

**Comment by romani** [comment]
After extra consideration , see details at https://github.com/checkstyle/checkstyle/pull/10679#discussion_r693419083 we decided to not use signing of config, to let contributors easily extend it, sending extension by PR.

We might come back to this signing in future.
