### ISSUE TITLE
Migrate to Inline Config Parser in Javadoc Check Tests

### ISSUE THREAD

**Issue by shashwatj07** [checkstyle/checkstyle#10692]
child of #10390

- [x] AtclauseOrderCheckTest - #10701
- [x] InvalidJavadocPositionCheckTest - #10701
- [x] JavadocBlockTagLocationCheckTest - #10701
- [x] JavadocContentLocationCheckTest - #10701
- [x] JavadocMethodCheckTest - #10702
- [x] JavadocMissingLeadingAsteriskCheckTest - #10702
- [x] JavadocMissingWhitespaceAfterAsteriskCheckTest - #10702
- [x] JavadocParagraphCheckTest - #10703
- [x] JavadocStyleCheckTest - #10705
- [x] JavadocTagContinuationIndentationCheckTest - #10707
- [x] JavadocTypeCheckTest - #10707
- [x] JavadocVariableCheckTest - #10710
- [x] MissingJavadocMethodCheckTest - #10707
- [x] MissingJavadocPackageCheckTest - #10708
- [x] MissingJavadocTypeCheckTest - #10708
- [x] NonEmptyAtclauseDescriptionCheckTest - https://github.com/checkstyle/checkstyle/pull/10989
- [x] RequireEmptyLineBeforeBlockTagGroupCheckTest - #10710
- [x] SingleLineJavadocCheckTest - #10710
- [x] SummaryJavadocCheckTest - https://github.com/checkstyle/checkstyle/pull/10712
- [x] WriteTagCheckTest - https://github.com/checkstyle/checkstyle/pull/10380

**Comment by shashwatj07** [comment]
> NonEmptyAtclauseDescriptionCheckTest

There is a problem with this. We cannot place violation comments. If we place a comment in from of an empty atclause, it becomes non empty, and no longer a violation. Placing comments on adjacent lines is not always possible.

> WriteTagCheckTest

We cannot place comments in frot of tags with a custom format.

**Comment by romani** [comment]
> NonEmptyAtclauseDescriptionCheckTest

```
/**
         * Some javadoc. // violation below
         * @param a
         * @param b
         * @param c
         */ // violation above
        public InputNonEmptyAtclauseDescription(String a, int b, double c)
// violation 4 lines above
// violation 5 lines above

```

**Comment by romani** [comment]
https://github.com/checkstyle/checkstyle/blob/1891eec4f9cba1fc960b1a775e3345a2abdfae52/src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/writetag/InputWriteTag.java#L15

```
// violation 2 lines below
/**
 * Testing tag writing
 * @author Daniel Grenner 

```

**Comment by romani** [comment]
Looks like all items are addressed/merged.
