### ISSUE TITLE
Migrate to Inline Config Parser in ImportOrderCheckTest

### ISSUE THREAD

**Issue by timurt** [checkstyle/checkstyle#10733]
#10390

**Comment by romani** [comment]
Only one method 
https://github.com/checkstyle/checkstyle/blob/1891eec4f9cba1fc960b1a775e3345a2abdfae52/src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheckTest.java#L680

**Comment by romani** [comment]
covered in https://github.com/checkstyle/checkstyle/issues/10671
