### ISSUE TITLE
Migrate to Inline Config Parser for filters

### ISSUE THREAD

**Issue by timurt** [checkstyle/checkstyle#10737]
#10390

- [x] BeforeExecutionExclusionFileFilterTest
- [x] SuppressWithPlainTextCommentFilterTest
- [x] SuppressWithNearbyCommentFilterTest
- [x] ~SuppressionFilterTest~ no input related tests
- [x] SuppressWarningsFilterTest
- [x] SuppressionCommentFilterTest
- [ ] SuppressionSingleFilterTest

**Comment by shashwatj07** [comment]
SuppressionFilterTest does not use input files.

**Comment by romani** [comment]
We need to convert test methods to use input file with inlined config where we have some Check, for example MemberName , and we have suppression ER

**Comment by romani** [comment]
@Vyom-Yadav, 
Please send update like
https://github.com/checkstyle/checkstyle/pull/11417
Please enforce no usage of old test method.

**Comment by Vyom-Yadav** [comment]
@romani Please reopen this, SuppressionSingleFilterTest is not done, only the input files are migrated to inline config parser, the tests are not, they still use the traditional verification method.

**Comment by nick-mancuso** [comment]
> SuppressWithPlainTextCommentFilterTest is also weirdly done

Please share details here.

**Comment by romani** [comment]
Probably better to create two separate tickets, it will be easier to track them

**Comment by Vyom-Yadav** [comment]
> Please share details here.

I did the changes in #11424, there were some missed tests and a few lines of dead code.

> Probably better to create two separate tickets, it will be easier to track them

Fall under the same parent issue so creating a new ticket won't be required IMO :)

**Comment by romani** [comment]
Finally Resolved by @Vyom-Yadav

**Comment by romani** [comment]
@Vyom-Yadav , please recheck https://github.com/checkstyle/checkstyle/runs/5612335973?check_suite_focus=true where we missed to remove reference to this issue?

**Comment by shashwatj07** [comment]
Thanks a lot @Vyom-Yadav 

My sincere apologies to @romani and everyone in the Checkstyle community for keeping this hanging. I tried my best to do it, and even did half the work in my local branch but failed to complete it due to personal and family health issues and university things.
