### ISSUE TITLE
Migrate to Inline Config Parser in PackageDeclarationCheckTest

### ISSUE THREAD

**Issue by timurt** [checkstyle/checkstyle#10732]
#10390

**Comment by shashwatj07** [comment]
Only one test is remaining in old verify.
https://github.com/checkstyle/checkstyle/blob/0d8c5b6be7594497082214615cd9b6c0a5ac616c/src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/PackageDeclarationCheckTest.java#L154-L162

This cannot use BDD as the file is meant to be empty. We need to keep it empty for coverage, hence it does not support Inlined Config.
https://github.com/checkstyle/checkstyle/blob/0d8c5b6be7594497082214615cd9b6c0a5ac616c/src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/packagedeclaration/InputPackageDeclarationEmptyFile.java#L1

**Comment by romani** [comment]
@shashwatj07 , can use annotation of this tool ? To suppress violations 
https://github.com/policeman-tools/forbidden-apis/wiki/MavenUsage#suppression-of-generated-classes

**Comment by romani** [comment]
> @shashwatj07 , can use annotation of this tool ? To suppress violations
> https://github.com/policeman-tools/forbidden-apis/wiki/MavenUsage#suppression-of-generated-classes
> 
> Here is ready to use annotation from tool https://github.com/policeman-tools/forbidden-apis/blob/main/src/main/java/de/thetaphi/forbiddenapis/SuppressForbidden.java
> Or we can "copy" it to our repository to avoid extra dependencies to jars but in test scope we have freedom to use any library.
