### ISSUE TITLE
JavadocMetadataScraper fails silently if it can't write the XML files

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#10747]
Identified through https://github.com/sevntu-checkstyle/sevntu.checkstyle/issues/857 ,

At https://github.com/checkstyle/checkstyle/blob/13481f2c410e4944ecf5ab93ec49948a523a0c82/src/main/java/com/puppycrawl/tools/checkstyle/meta/XmlMetaWriter.java#L179 , checkstyle will fail silently if there are no descriptions to write for the file it scrapped.

I was expecting the files to be generated, or give me an error why they couldn't be generated. Since there was no message and no files, this required me to debug through the code to find out why it wasn't generating my files or complaining.

I feel we should print an error message while continuing to process other files.

I also feel `MetadataGeneratorUtil` should report any errors back somehow so the client and calling tests can handle the situation appropriately.

**Comment by Vyom-Yadav** [comment]
I am working on it.

**Comment by rnveach** [comment]
The issue is split into 2 PRs. The first will add the error message to the module. The second will have the util print out the errors to the user when it is run.

**Comment by nmancus1** [comment]
@Vyom-Yadav I have a question; after this issue is solved, will build fail if XML files are not written?

**Comment by Vyom-Yadav** [comment]
@nmancus1 
> will build fail if XML files are not written?

The test will fail if the file contains a Javadoc comment which does not contain any description. XML file for the check won't be created in this case.

**Comment by rnveach** [comment]
Final fix was merged
