### ISSUE TITLE
MetadataGeneratorUtil should take the module folders as inputs

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#10749]
Identified at https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/meta/MetadataGeneratorUtil.java#L83 ,

Not all repos have these same 3 folders. Sevntu for example only has `checks`. The way the code is written now, it is required to check all folders and those folders must exist. If those folders do not exist, for whatever reason, they an exception will be generated and the util will stop.

The Util should be changed so that those 3 folders are taken as required inputs and not hardcoded in.

**Comment by bkaur-bkj** [comment]
@rnveach @romani sir, I would like to work on this issue please assign it to me

**Comment by AayushSaini101** [comment]
Can i work on this issue

**Comment by strkkk** [comment]
> Can i work on this issue

yes

**Comment by theanmolsharma** [comment]
I would like to work on this issue. @strkkk @AayushSaini101

**Comment by MUzairS15** [comment]
@AbhinavRajputEXE are you working on this?

**Comment by MUzairS15** [comment]
@rnveach Can I try on this?

**Comment by strkkk** [comment]
@MUzairS15 yes, please go ahead

**Comment by MUzairS15** [comment]
Can you help me understand, what MetadataGeneratorUtil does, I am not able to understand clearly what is the use.
Also, how can I run this Util, I mean to check whether my changes are working as expected?

**Comment by strkkk** [comment]
> Can you help me understand, what MetadataGeneratorUtil does, I am not able to understand clearly what is the use. Also, how can I run this Util, I mean to check whether my changes are working as expected?

It generates metadata files for checkstyle modules. You can check class unit tests to see how to run it and use TDD to implement changes.

**Comment by MUzairS15** [comment]
I have made a PR, please suggest additional changes if needed, if I misunderstood something.

**Comment by strkkk** [comment]
fix is merged
