### ISSUE TITLE
JavadocMetadataScraper doesn't identify "CheckstyleTestMakeupCheck" name correctly

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#10756]
Identified at https://github.com/checkstyle/checkstyle/blob/13481f2c410e4944ecf5ab93ec49948a523a0c82/src/main/java/com/puppycrawl/tools/checkstyle/meta/JavadocMetadataScraper.java#L183-L185 ,

`JavadocMetadataScraper` thinks the name of the class is just "Check" instead of `CheckstyleTestMakeup`.

We have always identified check names by if they end with `Check` or not and just subtract that to get the name of the check.

`JavadocMetadataScraper` should follow this pattern instead of creating its own.

**Comment by romani** [comment]
fix is merged.
