### ISSUE TITLE
XmlMetaReader fails if package given to it has no expected resource files listed

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#10773]
Identified at https://github.com/checkstyle/eclipse-cs/issues/256 when removing eclipse-cs meta files and trying to make a test to understand things more,

The stack trace:
````
net.sf.eclipsecs.core.config.meta.MetadataFactoryTest
java.lang.ExceptionInInitializerError
	at net.sf.eclipsecs.core.config.meta.MetadataFactoryTest.test(MetadataFactoryTest.java:35)
...
Caused by: java.lang.IllegalStateException: com.puppycrawl.tools.checkstyle.filefilters
	at com.puppycrawl.tools.checkstyle.meta.XmlMetaReader.readAllModulesIncludingThirdPartyIfAny(XmlMetaReader.java:85)
	at net.sf.eclipsecs.core.config.meta.MetadataFactory.createMetadataMap(MetadataFactory.java:582)
	at net.sf.eclipsecs.core.config.meta.MetadataFactory.doInitialization(MetadataFactory.java:559)
	at net.sf.eclipsecs.core.config.meta.MetadataFactory.refresh(MetadataFactory.java:539)
	at net.sf.eclipsecs.core.config.meta.MetadataFactory.<clinit>(MetadataFactory.java:144)
	... 66 more
Caused by: org.reflections.ReflectionsException: Scanner ResourcesScanner was not configured
	at org.reflections.Store.get(Store.java:39)
	at org.reflections.Store.get(Store.java:61)
	at org.reflections.Store.get(Store.java:56)
	at org.reflections.Reflections.getResources(Reflections.java:564)
	at org.reflections.Reflections.getResources(Reflections.java:572)
	at com.puppycrawl.tools.checkstyle.meta.XmlMetaReader.readAllModulesIncludingThirdPartyIfAny(XmlMetaReader.java:83)
	... 70 more
````
(Checkstyle was modified in eclipse-cs to provide more error information in the stack trace to track down the issue)

Checkstyle's `XmlMetaReader` will throw this exception when it is given a package (valid or invalid) that contains no supporting resource files, which we are trying to match against `.*checkstylemeta-.*\\.xml`.

eclipse-cs has the packages `filters` and `filefilters` inside `checkstyle_packages.xml`. Though these are valid packages, they contain no checkstyle meta files when searching. When `filters` and `filefilters` are removed from `checkstyle_packages.xml`, the exception goes away, everything passes with no issues.

This is not an issue in eclipse-cs *currently* because eclipse-cs still has its own metadata resource files for these packages which I assume is preventing the library issue. Removing the files causes the exception to show up. This issue looks like it is preventing the completion of https://github.com/checkstyle/eclipse-cs/issues/256 and removing all eclipse-cs meta files.

This issue can occur outside eclipse-cs' files if a 3rd party check provides their own `checkstyle_packages.xml` with checks but provide no resource files in the package. As an example, they can put their checks in 1 folder and their meta files in another.

This issue was also confirmed in the library at https://github.com/ronmamo/reflections/issues/273 . It seems this issue is taking an extended time to get resolved, so it may be up to each user of the library to find accommodations around the issue.

**Comment by romani** [comment]
@rnveach , what is your proposal ? Do no exception for such cases ?

**Comment by rnveach** [comment]
@romani 
I am going to assume that the original intention was that these packages given to checkstyle are optional to have or not required to always contain XML files. It makes sense that checks and XML files can be in different packages. Checkstyle has a special `meta` folder for our metadata while we place our checks inside the `checks` folder, not in the same package as the other. Since we are a library, we shouldn't rely on our users to identify which packages are valid before sending us the list unless we are going to provide them a way to do the validation.

My proposal is we catch all `ReflectionsException`s and check if the message is `Scanner ResourcesScanner was not configured` and silence the exception if they all match. I am assuming other `ReflectionsException`s can be thrown from the library unrelated to the bug like if there was a real issue. We obviously have configured the scanner, so this message can only be related to this one thing, IMO.

Its sad that the library hasn't resolved the issue for over a year. Unless there is another library we can switch to, we will just have to make do with this for now.

**Comment by romani** [comment]
We should be compatible with old behavior, so we should support empty folders.

If we can not prevent exception by extra IF code, ok lets base logic on catch of exception.

**Comment by strkkk** [comment]
fix is merged
