### ISSUE TITLE
Inline @return tag does not pass SummaryJavadocCheck

### ISSUE THREAD

**Issue by octylFractal** [checkstyle/checkstyle#10776]
I have read check documentation: https://checkstyle.org/config_javadoc.html#SummaryJavadoc
I have downloaded the latest checkstyle from: https://checkstyle.org/cmdline.html#Download_and_Run
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

```bash
[octy@Draconnet JavaTesting]$ javac SummaryJavadocNewInlineReturn.java 
[octy@Draconnet JavaTesting]$ cat config.xml 
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
"-//Puppy Crawl//DTD Check Configuration 1.3//EN"
"http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
<module name="Checker">
    <property name="charset" value="UTF-8"/>
    <property name="severity" value="error"/>
    <property name="fileExtensions" value="java, properties, xml"/>
    <module name="TreeWalker">
        <module name="SummaryJavadocCheck"/>
    </module>
</module>
[octy@Draconnet JavaTesting]$ cat SummaryJavadocNewInlineReturn.java
public class SummaryJavadocNewInlineReturn {
    /**
     * {@return a foo that is {@code 0}}
     */
    public int foo() {
        return 0;
    }
}
[octy@Draconnet JavaTesting]$ java -Duser.language=en -Duser.country=US -jar checkstyle-9.0-all.jar -c config.xml SummaryJavadocNewInlineReturn.java 
Starting audit...
[ERROR] /home/octy/Documents/JavaTesting/SummaryJavadocNewInlineReturn.java:2: Summary javadoc is missing. [SummaryJavadoc]
Audit done.
Checkstyle ends with 1 errors.
```

in place of the last 2 commands above.

---

in JDK16+ The inline `{@return}` tag should pass `SummaryJavadocCheck` as it results in the following javadoc content:
which includes the necessary period to pass the summary check.

```
$ javadoc SummaryJavadocNewInlineReturn.java
Loading source file SummaryJavadocNewInlineReturn.java...
Constructing Javadoc information...
Building index for all the packages and classes...
Standard Doclet version 17.0.1+12-39
Building tree for all the packages and classes...
Generating ./SummaryJavadocNewInlineReturn.html...
SummaryJavadocNewInlineReturn.java:1: warning: no comment
public class SummaryJavadocNewInlineReturn {
       ^
Generating ./package-summary.html...
Generating ./package-tree.html...
Generating ./overview-tree.html...
Building index for all classes...
Generating ./allclasses-index.html...
Generating ./allpackages-index.html...
Generating ./index-all.html...
Generating ./index.html...
Generating ./help-doc.html...
1 warning
```
![image](https://user-images.githubusercontent.com/812984/147022460-ce7edf9d-1bbd-42b4-83bc-58902ee1596b.png)

in JDK11 such javadoc is not valid:
```
$ javadoc SummaryJavadocNewInlineReturn.java
Loading source file SummaryJavadocNewInlineReturn.java...
Constructing Javadoc information...
Standard Doclet version 11
Building tree for all the packages and classes...
Generating ./SummaryJavadocNewInlineReturn.html...
SummaryJavadocNewInlineReturn.java:3: error: no tag name after @
     * {@return a foo that is {@code 0}}
       ^
SummaryJavadocNewInlineReturn.java:5: warning: no @return
    public int foo() {

```

**Note:**
according to the [specs](https://docs.oracle.com/en/java/javase/16/docs/specs/javadoc/doc-comment-spec.html#return), the inline return tag is allowed only for methods.

**Comment by romani** [comment]
I placed https://checkstyle.org/config_javadoc.html#SummaryJavadoc in PR description., Please do this next time, yourself, it gives us understanding that you read doc before issue creation

**Comment by rnveach** [comment]
More comments at https://github.com/checkstyle/checkstyle/issues/9745 can be found about inline return tags.
Pre and post-JDK 16 handling with javadoc tool at https://github.com/checkstyle/checkstyle/issues/9745#issuecomment-912999795
More examples of when it is valid at https://github.com/checkstyle/checkstyle/issues/9745#issuecomment-913017096

To me this issue looks valid. It just depends on agreement of handling pre and post JDKs auditing.

**Comment by rnveach** [comment]
This issue does look valid to me.

> `{@return a foo that is {@code 0}}`

The sad fact is that this inline tag automatically adds a period to the text.
See https://github.com/openjdk/jdk/commit/b29f9cd7#diff-42c90a8eded4f2fafe6386521e56956312a33016f23ce8a8316ff10f8bc358feR103
Example: https://github.com/openjdk/jdk/commit/b29f9cd7#diff-873b8bd2b8ecd4acd77f5e500aa0ef469787e2e8976dd8bfc530c19465fcd9d0R128

**Comment by pbludov** [comment]
> The sad fact is that this inline tag automatically adds a period to the text.

Moreover, it does this blindly:
```java
    /** {@return some value.}  */
    public int getValue() {}
```
becomes "Returns some value.."

![image](https://user-images.githubusercontent.com/900805/132125055-a6db3c90-efe2-4bfe-9426-55fd06182e11.png)

 We need a separated check to ensure that `{@return foo}` does not end with a period.

**Comment by romani** [comment]
@octylFractal, this Check https://checkstyle.org/config_javadoc.html#SummaryJavadoc does not care about tags.

Summary is text before any tag.
Violation is valid.
Can you share whole image of javadoc, not a part of it ?

**Comment by rnveach** [comment]
@romani Please read over https://github.com/checkstyle/checkstyle/issues/9745#issuecomment-913016063 first. This tag becomes the summary and is required to be the first thing listed in the summary.

**Comment by romani** [comment]
```
$ javadoc Test.java
Loading source file Test.java...
Constructing Javadoc information...
Building index for all the packages and classes...
Standard Doclet version 17.0.1+12-39
Building tree for all the packages and classes...
Generating ./Test.html...
Test.java:1: warning: no comment
public class Test {
       ^
Generating ./package-summary.html...
Generating ./package-tree.html...
Generating ./overview-tree.html...
Building index for all classes...
Generating ./allclasses-index.html...
Generating ./allpackages-index.html...
Generating ./index-all.html...
Generating ./index.html...
Generating ./help-doc.html...
1 warning

/var/tmp$ cat Test.java 
public class Test {
   /**
     * {@return a foo that is {@code 0}}
     */
    public int foo() {
        return 0;
    }
}
```
![image](https://user-images.githubusercontent.com/812984/147022117-c4cccf0f-e198-45e0-8a57-81bdc6c96bf2.png)

**Comment by romani** [comment]
I am approving this issue.
SummaryJavadocCheck should recognize this `{@return }` tag ONLY if it is first in content and do not demand period for it.
I do believe behavior should be very similar to `{@summary}` tag that we already support.
If users use this tag on old jdk, Check behavior should be same on new jdk. Old Jdk  raising error on such content.

**Comment by strkkk** [comment]
@Vyom-Yadav it may be interesting for you, since you are working with this check right now

**Comment by romani** [comment]
attention there is already a PR - https://github.com/checkstyle/checkstyle/pull/10772 , lets see if author is responding or abandoned his PR.

**Comment by Vyom-Yadav** [comment]
If the linked PR is abandoned, I have no problem continuing the work.

**Comment by octylFractal** [comment]
As requested in https://github.com/checkstyle/checkstyle/pull/10772#discussion_r818319192:
> Sorry if I missed it, but can you point to where we analyzed how the javadoc tool behaves with this or the class one?

I didn't analyze it prior, but just now I tested:
```java
public class SummaryJavadocNewInlineReturn {
    /** 
     * {@return invalid}
     */
    public final int foo = 0;
}
```
```sh
$ javadoc SummaryJavadocNewInlineReturn.java
Loading source file SummaryJavadocNewInlineReturn.java...
Constructing Javadoc information...
Building index for all the packages and classes...
Standard Doclet version 16.0.2+7
Building tree for all the packages and classes...
Generating ./SummaryJavadocNewInlineReturn.html...
SummaryJavadocNewInlineReturn.java:3: error: invalid use of @return
     * {@return invalid}
       ^
[other messages removed]
```
So `javadoc` produces a hard error when this is placed on a non-method class member. Therefore, we don't check it in checkstyle.
