### ISSUE TITLE
Fix up messages - mojibake, lone apostrophes and accidental apostrophes substitutes

### ISSUE THREAD

**Issue by victorwss** [checkstyle/checkstyle#10828]
Some message translations features:

1. Mojibake.
2. Lone apostrophes (they should be doubled due to escaping).
3. Accidental apostrophes substitutes (` and ’ instead of ').

Disclaimer: Since #10811 and #10812 are too fat to be properly and fully peer-reviewed, I am resubmiting them in small baby-steps issues and commits.

**Comment by romani** [comment]
@victorwss, is there something left to fix in this issue ?

**Comment by rnveach** [comment]
@romani Should we close this as its been 5 months?
