### ISSUE TITLE
UT output should be silent

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#10844]
during "mvn test"

```
[INFO] Running com.puppycrawl.tools.checkstyle.meta.XmlMetaReaderTest
[main] INFO org.reflections.Reflections - Reflections took 423 ms to scan 2 urls, producing 220 keys and 233 values 
[main] INFO org.reflections.Reflections - Reflections took 341 ms to scan 2 urls, producing 220 keys and 233 values 
[main] INFO org.reflections.Reflections - Reflections took 348 ms to scan 2 urls, producing 220 keys and 233 values 
[main] INFO org.reflections.Reflections - Reflections took 372 ms to scan 2 urls, producing 220 keys and 233 values 
[main] INFO org.reflections.Reflections - Reflections took 15 ms to scan 11 urls, producing 0 keys and 0 values 
```

expected, no output from tests

**Comment by Vyom-Yadav** [comment]
@romani https://github.com/ronmamo/reflections/issues/266 someone gave the solution at the end, but that requires installing `ch.qos.logback:logback-classic:1.2.3`

**Comment by romani** [comment]
Test scope dependencies are ok to introduce

**Comment by rnveach** [comment]
@Vyom-Yadav Since the util is using a logger, there should be some way to just disable through it's existing logger.

https://github.com/ronmamo/reflections/blob/9a1ac08d59311a91f3dad06f0c831eccdc47f1e3/src/main/java/org/reflections/Reflections.java#L245
It appears to be using sl4j and I found the following code to work.
````
System.setProperty("org.slf4j.simpleLogger.log.org.reflections", "off");
````

**Comment by strkkk** [comment]
May be just use `-q` maven cli option?
```
-q, --quiet
    Quiet output - only show errors 

The -q option only prints a message to the output if there is an error or a problem.
```

**Comment by rnveach** [comment]
No one has said "I am on it" so the issue is open to anyone right now.

**Comment by romani** [comment]
fix is merged
