### ISSUE TITLE
Use EqualsVerifier library to test equals and hashCode methods

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#1088]
[EqualsVerifier](https://github.com/jqno/equalsverifier) is library that can be used in Java unit tests to verify whether the contract for the `equals` and `hashCode` methods in a class is met.

Let's use it in Checkstyle to improve coverage and find all problems in custom `equals` and `hashCode` implementations.

**Comment by romani** [comment]
merged, discussion is at #1096
