### ISSUE TITLE
Setup JDK17 build

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#10905]
A new version of Java has recently been released. We need to set up a CI build before we start working on Java 17-specific issues.
Unfortunately, it doesn't work out of the box.

Current progress:
- [X] Source compiles
- [x] All tests passed

Blockers: #7368

**Comment by pbludov** [comment]
Local build with JDK17 succeeded. We can replace Java16 build with Java17 one.

**Comment by romani** [comment]
fix is merged
