### ISSUE TITLE
New check: AvoidOptionalOrElseForMethodCalls

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#10906]
**How it works Now:**

```java
import java.util.Optional;

public class TestClass {

    public static void main(String... args){
        var value = Optional.ofNullable(foo())
                .orElse(bar()); // violation Consider using "Optional.orElseGet"

        value = Optional.ofNullable(foo())
                .orElseGet(() -> bar()); // OK

        System.out.println(value);
    }

    static String foo() {
        System.out.println("foo called");
        return "foo";
    }

    static String bar() {
        System.out.println("bar called");
        return "bar";
    }

}
```

```bash
/var/tmp $ java TestClass.java
foo called
bar called
foo called
foo
```

----

The problem is that both methods were executed. And the result of the second call is just discarded (silently!). This may be not what the user expected.
Today I spend some time to figure out a DB entity leak. It turns out that method `getOrCreate` was implemented as `Optional.ofNullable(getExisting()).orElse(creteNew())`. And it was creating a new entity on every call.
Anyway, making some work and then just discard the result is a bad practice.

The solution is simple: replace `orElse(bar())` with `orElseGet(() -> bar())`. If the `orElse` part is required, then it should be extracted to a variable, like this:

```
var first = foo();  // it is clear that both methods should be invoked
var second = bar();

var value = Optional.ofNullable(first)
                .orElse(second);
```

The idea of new check is to verify that only constant values or variables are passed to `orElse(...)`.
 All complicated stuff should be done in `orElseGet(() -> ...)`

A good article for this issue: https://www.baeldung.com/java-optional-or-else-vs-or-else-get

**Comment by rnveach** [comment]
@pbludov If this is not going to be implemented in Checkstyle than please close the issue. Something like this seems to need to be more type aware,

If you plan to create an issue or implement in spot bugs, then please post a link to this issue.

**Comment by pbludov** [comment]
Moved to https://github.com/spotbugs/spotbugs/discussions/1783
