### ISSUE TITLE
LineLengthCheck ignores length of import and package statements.

### ISSUE THREAD

**Issue by Vyom-Yadav** [checkstyle/checkstyle#10907]
Continuing From #9999, https://github.com/checkstyle/checkstyle/pull/10046#issuecomment-950376678
https://checkstyle.org/config_sizes.html#LineLength
I have downloaded the latest cli from: https://checkstyle.org/cmdline.html#Download_and_Run
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

**How it works Now:**

`Test.java`
```
package com.puppycrawl.tools.checkstyle.checks.indentation.indentation;

import com.puppycrawl.tools.checkstyle.checks.indentation.indentation.*;

public class Test {
}
```

`config.xml`
```
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
    <module name="LineLength">
        <property name="max" value="20"/>
    </module>
</module>
```

```
$ java -jar /mnt/DownloadsExt/checkstyle-9.0.1-all.jar -c config.xml A.java
Starting audit...
Audit done.
```
**Describe the solution you'd like**
```
Starting audit...
$ java -jar /mnt/DownloadsExt/checkstyle-9.0.1-all.jar -c config.xml A.java
Test.java:1: Line is longer than 20 characters (found 71). [LineLength]
Test.java:3: Line is longer than 20 characters (found 72). [LineLength]
Audit done.
```
**Additional context**
Below mentioned import and package statements are compilable-
```
import com.
        puppycrawl.
        tools.checkstyle.checks.indentation.indentation.*; // same goes for package statements
```
```
package com.          puppycrawl.tools.       checkstyle.checks.indentation.indentation; // same goes for import statements
```
---

### Mutually accepted solution-

- Completely remove the field `IGNORE_PATTERN`
https://github.com/checkstyle/checkstyle/blob/6d083c70ba90fa86db668bd77ee2aa3a7107b134/src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/LineLengthCheck.java#L133-L134

- Modify `ignorePattern`, change its default value to `"^(package|import) .*"`
https://github.com/checkstyle/checkstyle/blob/6d083c70ba90fa86db668bd77ee2aa3a7107b134/src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/LineLengthCheck.java#L139-L140

**Comment by Vyom-Yadav** [comment]
@romani ping

**Comment by romani** [comment]
we should update default value of `ignorePattern` to explicitly have/show `^(package|import) .*`
to let it work same for people who did not override value of this property.
and yes it will be breacking changes for people who override this value now, as violations appear on such import/package lines.

@Vyom-Yadav , @rnveach , @nmancus1 , @pbludov , @strkkk 
are you agree on this breaking changes ?

**Comment by rnveach** [comment]
> we should update default value of ignorePattern to explicitly have/show ^(package|import) .*

I don't really see updating the regexp as breaking compatibility. I am ok on the change.
We should also make a similar change in sevntu.
https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/master/sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/sizes/LineLengthExtendedCheck.java#L124

**Comment by pbludov** [comment]
> are you agree on this breaking changes ?

This change is easy to fix if someone's working config breaks. I see no problems here.

**Comment by romani** [comment]
ok , it will be big change of behavior we can classify it as "bug" , as Check always suppressed such lines. It will not be breaking changes of api.

@nmancus1, @strkkk , what are your thoughts ?

**Comment by nmancus1** [comment]
Yes, I think we can call this a bug. We should add an example to documentation showing new behavior (and change of default value for `ignorePattern`, of course).

**Comment by romani** [comment]
@Vyom-Yadav , issue is approved

**Comment by rnveach** [comment]
Fix was merged
