### ISSUE TITLE
Remove curly braces usage for javadoc tags in translations

### ISSUE THREAD

**Issue by strkkk** [checkstyle/checkstyle#10910]
Issue come from https://github.com/checkstyle/checkstyle/pull/10854#discussion_r736815881_

There are failures in tests when autoescape for single quotes added.

I suggest to remove usages of curly braces in messages. At the moment there are only 2 messages (in english + entries in other langs)
```
 grep -R --include "messages.properties" "'{'" .
./src/main/resources/com/puppycrawl/tools/checkstyle/checks/annotation/messages.properties:annotation.missing.override=Must include @java.lang.Override annotation when '{'@inheritDoc'}' Javadoc tag exists.
./src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages.properties:javadoc.invalidInheritDoc=Invalid use of the '{'@inheritDoc'}' tag.
```

So we can change it to 
```
Must include @java.lang.Override annotation when '@inheritDoc' Javadoc tag exists.
```
and 
```
Invalid use of the '@inheritDoc' tag.
```

Other option is to disable escape and manage escapes by yourselves (user has to add escapes in crowdin), but I think it is not a very convinient way.

**Comment by rnveach** [comment]
Fix was merged
