### ISSUE TITLE
messages.properties doesn't work

### ISSUE THREAD

**Issue by pysoftware** [checkstyle/checkstyle#10919]
Hey, I have package `com.qulice.checkstyle.coding` with class `RedundantReturnCheck`

also I have in resource folder `com.qulice.checkstyle.coding` `messages.properties` with keys
` key.name=Bad return.`

but when I use in `RedundantReturnCheck` `log(ast, "keyName")` in IDE I only see `Checkstyle: key.name` message,
instead of `Bad return` message
 
I build mvn as `mvn package` and then use .jar from `target` folder in IDE

my `checks.xml` that i use in IDE
```
<!DOCTYPE module PUBLIC "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
        "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
<module name="Checker">
    <property name="localeLanguage" value="en"/>
    <module name="TreeWalker">
        <module name="com.qulice.checkstyle.coding.RedundantReturnCheck" />
    </module>
</module>
```

Maven checkstyle dependency
```
<dependency>
      <groupId>com.puppycrawl.tools</groupId>
      <artifactId>checkstyle</artifactId>
      <version>9.1</version>
      <exclusions>
        <exclusion>
          <groupId>org.abego.treelayout</groupId>
          <artifactId>org.abego.treelayout.core</artifactId>
        </exclusion>
        <exclusion>
          <groupId>net.sf.saxon</groupId>
          <artifactId>Saxon-HE</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
```

BTW, checker works fine - the problem is message key

`

**Comment by romani** [comment]
You can find examples of custom Checks at https://github.com/sevntu-checkstyle/sevntu.checkstyle/tree/master/sevntu-checks

I am closing issue, but you can continue ask questions here.
