### ISSUE TITLE
Checkstyle should force logging of AST in checks that require it

### ISSUE THREAD

**Issue by nick-mancuso** [checkstyle/checkstyle#10933]
> @pbludov should we somehow limit the usage of "old" `log` method to help prevent this is in the future?

This is a good idea. Developers should be aware of this. We have a [check](https://github.com/checkstyle/checkstyle/blob/38df63e992c1270eac87d5e98d5d8cb281c4a20b/config/checkstyle_sevntu_checks.xml#L215) to forbid some method by its name and number of parameters.

 Unfortunately, the "old" `log` method is still used by Javadoc checks and filters. See #4830 for the details.
This means we should add an entry for `ForbidCertainMethodCheck` and suppress this violation for `*Flter` and `Javadoc*Check`.

_Originally posted by @pbludov in https://github.com/checkstyle/checkstyle/issues/10930#issuecomment-962656895_

-----------------

Confusion between `AbstractCheck#log` methods, as noticed in https://github.com/checkstyle/checkstyle/pull/10930#issuecomment-962656895, can be difficult for contributors to troubleshoot when `XPathRegression...` tests are failing due to suppressions not functioning as expected. It might be a good idea to add some sort of warning about this to the documentation for `AbstractViolationReporter#log` as well. Perhaps we could extend the current summary (`Log a message that has no column information.`) to something like `Log a message that has no column information. Usage of this log method should be restricted to FileSet checks, Javadoc checks, and filters.`

**Comment by romani** [comment]
Can we use https://github.com/policeman-tools/forbidden-apis/wiki/SignaturesSyntax ?

**Comment by nick-mancuso** [comment]
> Can we use https://github.com/policeman-tools/forbidden-apis/wiki/SignaturesSyntax ?

Looks like a great solution, thanks for recommendation.

**Comment by rnveach** [comment]
Fix was merged
