### ISSUE TITLE
Activating a research fault localization bot on your project?

### ISSUE THREAD

**Issue by dginelli** [checkstyle/checkstyle#10939]
Hi! 

We are software engineering researchers and are currently looking for active open-source projects where we could test a new cool software bot: flacocobot!

When a new pull request is open, if it has test failures/errors, flacocobot analyzes the failure and posts a diagnosis as comments to the pull request, highlighting the most suspicious lines that likely need to be analyzed to fix the bug.

flacocobot works as follows:

- When a new PR is open, if the test suite fails, flacocobot starts its analysis.
- The top k suspicious (potentially buggy) lines of code are then highlighted as comments to the PR.

We would love to have your feedback in order to understand what you like or you do not like, what we can improve, and if you find it useful!

If you are interested in trying it, we will run flacocobot on your project for a period of two weeks and then give you a 1-minute questionnaire to collect your feedback.

What do you think? Can we activate flacocobot for [checkstyle](https://github.com/checkstyle/checkstyle)?

Thanks,

Davide (@dginelli), André (@andre15silva), Matias (@martinezmatias), Benjamin (@danglotb), Martin (@monperrus)

You can find out more in our tools repos:
- https://github.com/SpoonLabs/flacoco
- https://github.com/eclipse/repairnator

**Comment by nmancus1** [comment]
Hello @dginelli , I see that you have included links for tools that your bot uses (flacoco and repairinator), but I do not see a link to the repo for flacocobot itself. Can you provide a link?

**Comment by dginelli** [comment]
Hello @nmancus1,

Thank you for your answer. We are happy to see that you are interested in the project. I give you more details in order to better explain how it works.

The source code of flacocobot is integrated in Repairnator. In this moment, the last updates are not in the main branch, but in a [pull request](https://github.com/eclipse/repairnator/pull/1243). It is still not merged, but I can give you the details about the functioning.

The entypoint is represented by [FlacocoScanner](https://github.com/andre15silva/repairnator/blob/flacoco-github/src/repairnator-realtime/src/main/java/fr/inria/spirals/repairnator/realtime/FlacocoScanner.java).

This scanner has a list of projects to scan in order to find open and failed pull requests of those projects. More precisely, at the first iteration, it searches for the open failed pull requests created in the last 7 days. If it finds any suspicious lines, it adds a review comment with the 5 most suspicious lines.

For the next iterations, flacocobot searches for new open failed pull requests created after the last scan or for updates in the other pull requests previously inspected. If it detects an update in one of these pull requests (it does not consider updates related to the addition of new comments or review comments), it will add a new review comment on the pull request. [GithubAPIPullRequestAdapter](https://github.com/andre15silva/repairnator/blob/flacoco-github/src/repairnator-realtime/src/main/java/fr/inria/spirals/repairnator/realtime/githubapi/pullrequests/GithubAPIPullRequestAdapter.java) is the class that has the logic to decide if a pull request satisfies the requirements to be analyzed or not.

After a pull request has been selected, the source code associated with the pull request [is cloned in a Docker container](https://github.com/andre15silva/repairnator/blob/3f6ead8771b0bd8338e16f3f192bfc1a4abdcf73/src/repairnator-realtime/src/main/java/fr/inria/spirals/repairnator/realtime/DockerPipelineRunner.java#L91) to have a clean environment where to run the test cases associated with the project.

Flacoco Localization tool detects the lines that should be investigated to find the reason of the test failure/error. Flacoco associates a suspiciousness score to every line.

At this point, the last point of the process is in the class [PushFaultLocalizationSuggestions](https://github.com/andre15silva/repairnator/blob/flacoco-github/src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/push/PushFaultLocalizationSuggestions.java). This class checks the diff introduced by the pull request compared to the original source code. If a line detected with Flacoco is also in the diff, then this line is selected to be suggested to the developers. In the end, flacocobot finds the top 5 most suspicious lines and [suggests them in a review comment to the pull request](https://github.com/andre15silva/repairnator/blob/3f6ead8771b0bd8338e16f3f192bfc1a4abdcf73/src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/push/PushFaultLocalizationSuggestions.java#L51).

Let us know if you need other details and if you would like to test flacocobot :-)

**Comment by romani** [comment]
Failure in tests in CI is rare case, as all tests are executed on contributors local laptop.
CI care more about integration testing or other code validation tools.

Do you have example how this tool already running on some project ?

**Comment by dginelli** [comment]
Hello @romani,

You can see an example [here](https://github.com/dginelli/failingProject/pull/13).

I see. For us, it would be enough to run our bot on your project, and then we would have two possibilities:

1) If there will be no failed pull request because, as you wrote, contributors run tests on their machine, we will just ask you to fill a super short questionnaire about software bots in general;

2) If, on the contrary, we will be lucky and we will have a failed pull request with suggestions provided by flacocobot, you can tell us if one of the lines suggested by flacocobot is the one that has to be changed to fix the bug. Moreover, It will be interesting for us to see if flacocobot detects the correct line and if it proposes it as first/second/third etc. line in the ranking of the suggestions.

Obviously, we do not want to appear insistent, so if you are not convinced and you decide not to participate to the test, no problem: we will not activate the bot on your project :-)

**Comment by romani** [comment]
In this project, where we have 100 % coverage by braches and mutation. I do not see how not can suggest something that is not very obvious.

Your bot might be interesting on local when people do come coding, but in this particular  project, all is under tests, driven by tests.

We now in a state of quality where code does not really matter, what is matter is testing inputs. Even our tests are very boring, no code classes.
