### ISSUE TITLE
Remove dependency on Powermock from tests

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#10932]
We have a number of Powermock powered tests:
https://github.com/checkstyle/checkstyle/tree/master/src/test/java/com/puppycrawl/tools/checkstyle/internal/powermock

We need them for coverage testing. Mostly because Mockito framework does not support mocking of a static methods prior to version 3.4.0. For today, the Powermock is not compatible with JDK17 and abandoned. This is a blocker for the future development. We can not set up a JDK17 build (#10905), so we can not test JDK17-specific features.

But we can replace `PowerMock.mockStatic` with `Mockito.mockStatic` if we switch to new [mockito-inline](https://mvnrepository.com/artifact/org.mockito/mockito-inline) framework.

Unfortunately, both frameworks (mockito-inline and powermock) cannot coexist. So we need to drop the Powermocks library first.
Some work will be done in #7368.

The goal of this issue is to replace the Powermock dependency with a recent Mockito and keep as much coverage as possible.

Started here: https://github.com/checkstyle/checkstyle/pull/10899#issuecomment-962649128

**Comment by rnveach** [comment]
As part of this issue, we should also verify if we can combine Mockito with pitest and merge the tests back together into their original tests instead of keeping them split like this.

**Comment by rnveach** [comment]
Fixes were merged

**Comment by rnveach** [comment]
@romani @pbludov Since powermock is gone, what does this mean for the following things we still have?

In code:
https://github.com/checkstyle/checkstyle/blob/d7f0b83b550aa0f2c6c81b481a06bc539b0157ea/src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionsLoaderTest.java#L78

Issue:
https://github.com/checkstyle/checkstyle/blob/d7f0b83b550aa0f2c6c81b481a06bc539b0157ea/src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionsLoaderTest.java#L78

**Comment by pbludov** [comment]
> @romani @pbludov Since powermock is gone, what does this mean for the following things we still have?
> 
> In code:
> 
> https://github.com/checkstyle/checkstyle/blob/d7f0b83b550aa0f2c6c81b481a06bc539b0157ea/src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionsLoaderTest.java#L78
> 
> Issue: #4970

We can fix them now. A normal test should not contain `if`s. Such tests should be rewritten with `assumeTrue` or new JUnit5 annotation `@EnabledIf`

Also, we should partially revert #4399. Parameter `checkConstructorIsPrivate` should be removed.
