### ISSUE TITLE
UnnecessaryParentheses too strict with combined && and ||

### ISSUE THREAD

**Issue by robtimus** [checkstyle/checkstyle#10946]
I have read check documentation: https://checkstyle.sourceforge.io/config_coding.html#UnnecessaryParentheses
I have downloaded the latest checkstyle from: https://checkstyle.org/cmdline.html#Download_and_Run
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

```bash
/var/tmp $ javac UnnecessaryParenthesesExample.java

/var/tmp $ cat config.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
  <module name="TreeWalker">
    <module name="UnnecessaryParentheses"/>
  </module>
</module>

/var/tmp $ cat UnnecessaryParenthesesExample.java
public class UnnecessaryParenthesesExample {

    public static boolean foo(int x, int y) {
        return (x == 0 && y > 0) || (x > 0 && y == 0);
    }

    public static void main(String... args) {
        System.out.printf("x = 0, y = 0: %b%n", foo(0, 0));
        System.out.printf("x = 0, y = 1: %b%n", foo(0, 1));
        System.out.printf("x = 1, y = 0: %b%n", foo(1, 0));
        System.out.printf("x = 1, y = 1: %b%n", foo(1, 1));
    }
}

/var/tmp $ RUN_LOCALE="-Duser.language=en -Duser.country=US"
/var/tmp $ java $RUN_LOCALE -jar checkstyle-9.1-all.jar -c config.xml UnnecessaryParenthesesExample.java
Starting audit...
[ERROR] I:\_tmp\_checkstyle\UnnecessaryParenthesesExample.java:4:16: Unnecessary parentheses around expression. [UnnecessaryParentheses]
[ERROR] I:\_tmp\_checkstyle\UnnecessaryParenthesesExample.java:4:37: Unnecessary parentheses around expression. [UnnecessaryParentheses]
Audit done.
Checkstyle ends with 2 errors.
```

---

While technically these parentheses are indeed unnecessary (`LAND` has a higher precedence than `LOR`), it makes the intent more clear. I've only been able to disable this warning by removing `LAND` from the tokens, but then Checkstyle won't be strict enough.

For now I've been adding helper variables and methods to work around the issue, but it would be nice to at least allow some extra parentheses when combining `LAND` and `LOR`.

**Comment by Vyom-Yadav** [comment]
'too strict' is relative, it may be for you but for others it might not be, the max that could be possibly done is a property like `strictlyRemoveUnnecessaryParen` or something like that, but then also, strictness is a relative term, can you propose to what level to want parenthesis with few examples of different kinds.

**Comment by robtimus** [comment]
I think that the only issue I have is the example I've shown: combining `LAND` and `LOR`. Probably more precisely, combining one or more statements that use `LAND` with `LOR`, since the other way around already requires parentheses, and Checkstyle doesn't find any violations for that.

So basically, `statement1 || statement2`, where either statement contains `&&`, should not produce any warning.

**Comment by robtimus** [comment]
Note that I wouldn't mind a flag to enable this. This flag shouldn't prevent too many violations, otherwise the entire check loses (some of) its value.

**Comment by romani** [comment]
>entire check loses (some of) its value.

Yes, this Check is more fanatic people.
But if we get clear definition of how to ease validation, it would be good, to let other group of people use it.
Main problem what rules to use to soften validation.

**Comment by romani** [comment]
@robtimus , please share examples where you still think extra parentheses are good to remove.

**Comment by robtimus** [comment]
@romani, I think that in most cases it's good to remove unnecessary parentheses. Only if it hinders readability would I allow them myself. And maybe "readability" is something that isn't always clear. The combination of `LAND` and `LOR` is one example I encountered, but other people may want more cases.

I'm starting to think that maybe this issue should be closed without any action. If a case is added for `LAND` and `LOR`, then someone may want a case for arithmetic and boolean, like `(a + b > c) && (a + b < d)`. And if that's done, someone else may want another case. And where will it then end?

In the end, I think it's going to be a case of disabling the check, using additional methods and variables, or giving up some readability and just make use of the operator precedence.

**Comment by romani** [comment]
In case where I wanted to use extra parentheses I use new lines

```
return x == 0 && y > 0
              || x > 0 && y == 0;
```

Not sure it always works, but I do not remember if I even run into case where it did work.
But I agree that sometime extra parentheses is good, but it is hard to formulate that rule to automate it.

**Comment by robtimus** [comment]
I agree, and I like the new line suggestion. That makes it a lot more readable without parentheses.

**Comment by romani** [comment]
I am closing issue, but discussion can be continued in case somebody find a way how to keep visually useful and helpful parentheses
