### ISSUE TITLE
Can we skip via checkstyle via command line or build.gradle 

### ISSUE THREAD

**Issue by Sadashiv** [checkstyle/checkstyle#10961]
Hi Team,
sonarqube: 8.9
plugin: checkstyle: 4.29
We have project with huge code can we skip chekcstyle via command line or build.gradle
If yes how we can skip.

Below these are not helped
checkstyleMain {
    ignoreFailures = true
}

checkstyle {
   ignoreFailures = true
}

checkstyleTask.ignoreFailures = true

Please help on this part.

I have read check documentation: https://checkstyle.org/config_xxxxxx.html#NameOfAffectedCheck
I have downloaded the latest checkstyle from: https://checkstyle.org/cmdline.html#Download_and_Run
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

```bash
/var/tmp $ javac YOUR_FILE.java
#[[MAKE SURE THERE IS SUCCESSFUL COMPILATION]]

/var/tmp $ cat config.xml
#[[PLACE YOUR OUTPUT HERE]]

/var/tmp $ cat YOUR_FILE.java
#[[PLACE YOU OUTPUT HERE]]

/var/tmp $ RUN_LOCALE="-Duser.language=en -Duser.country=US"
/var/tmp $ java $RUN_LOCALE -jar checkstyle-X.XX-all.jar -c config.xml YOUR_FILE.java
#[[PLACE YOUR OUTPUT HERE]]
```

For Windows users, please use `type` instead of `cat` and run

```cmd
set RUN_LOCALE="-Duser.language=en -Duser.country=US"
java %RUN_LOCALE% -jar checkstyle-X.XX-all.jar -c config.xml YOUR_FILE.java
```

in place of the last 2 commands above.

---

**Describe what you expect in detail.**

---

Still not clear ???
see example - https://checkstyle.org/report_issue.html#How_to_report_a_bug.3F

ATTENTION: FAILURE TO FOLLOW THE ABOVE TEMPLATE WILL RESULT IN THE ISSUE BEING CLOSED.

**Comment by strkkk** [comment]
@Sadashiv this is not an issue of checkstyle itself (we do not support build system plugins such as gradle), please search for answer in stackoverflow
