### ISSUE TITLE
Release notes should mention that `CheckUtil#createFullType` has been removed.

### ISSUE THREAD

**Issue by nmancus1** [checkstyle/checkstyle#10982]
Noticed while running check regression reports for #10979 with Sevntu checks, the commit that removes `CheckUtil#createFullType` (https://github.com/checkstyle/checkstyle/pull/10839/commits/7462b00c2f0d470be6d3d8825f83c717cc5696aa), does not mention that this method has been removed. `createFullType` is used in two sevntu checks:

```bash
➜  sevntu-checks git:(master) grep -R createFullType
src/main/java/com/github/sevntu/checkstyle/checks/coding/IllegalCatchExtendedCheck.java:        final FullIdent ident = CheckUtil.createFullType(excType);
src/main/java/com/github/sevntu/checkstyle/checks/coding/AvoidNotShortCircuitOperatorsForBooleanCheck.java:                CheckUtil.createFullType(node.findFirstToken(TokenTypes.TYPE));

```

It is likely that `CheckUtil#createFullType` is also used in third party checks, so I think we should mention that this method has been removed in release notes (perhaps as breaking change?).

Edit: Sevntu PR at https://github.com/sevntu-checkstyle/sevntu.checkstyle/pull/876

**Comment by strkkk** [comment]
Oh, unfortunately I didn't think about it, I saw it is not used in checkstyle code so I removed this method.

So there are 2 options -
1. add appropriate label to issue and fix senvtu
2. revert this part of changes

@romani @rnveach @pbludov what do you think is best?

I prefer option 1, also it can be easily replaced with `FullIdent.createFullIdent` method

**Comment by romani** [comment]
Util is not API.
Usage of our internals is on their own risk

**Comment by nmancus1** [comment]
> Util is not API.
Usage of our internals is on their own risk

I agree, but I do not see harm in informing users of such a change in Checkstyle's case. I would expect anyone writing their own checks to use any utility available to them (as was done in Sevntu repo). If nothing else, adding a release note with a link makes it easier for a user to see how usages were replaced, to use as example for their own check.

**Comment by romani** [comment]
Release notes are taken from issues that are referenced in commits.
Changes are done in https://github.com/checkstyle/checkstyle/commit/7462b00c2f0d470be6d3d8825f83c717cc5696aa

So release notes line will be:
ClassFanOutComplexity fails to count all classes in multicatch and implements clause.

Title from https://github.com/checkstyle/checkstyle/issues/10144

If we want to hint changes in utility class we can change title of issue above.

**Comment by strkkk** [comment]
I changed issue title

**Comment by romani** [comment]
@nmancus1 , please close this issue if you are satisfied
