### ISSUE TITLE
TrailingCommentsCheck ignores first comment character

### ISSUE THREAD

**Issue by hd42** [checkstyle/checkstyle#10997]
We had a rule for our eclipse-plugin projects
`<module name="TrailingComment">
    <property name="legalComment" value="\$NON-NLS" />
</module>`
because Eclipse internationalization requires this trailing comment for Non-Localized Strings.

Since some versions (I believe https://github.com/checkstyle/checkstyle/commit/ebef3bd59fdc2c97587a67bc59d57af6ecbb9072, introduced in 8.41), this did no longer work, I needed to change it to 
`<module name="TrailingComment">
    <property name="legalComment" value="NON-NLS" />
</module>`
because in `isLegalSingleLineComment`, the commentText is extracted with comment.substring(1).trim();
Why would the first character of a comment be ignored?

I have read the check documentation: https://checkstyle.org/config_misc.html#TrailingComment
I have downloaded the latest checkstyle (9.2) from: https://checkstyle.org/cmdline.html#Download_and_Run
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words:

```
(base) schwering /ws/fips/cs/src$ javac cs/C.java
(base) schwering /ws/fips/cs/src$ cat trailingChecks.xml 
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module PUBLIC "-//Puppy Crawl//DTD Check Configuration 1.3//EN" "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
<module name="Checker">
    <property name="severity" value="warning" />
    <module name="TreeWalker">
        <module name="TrailingComment">
            <property name="legalComment" value="\$NON-NLS" />
        </module>
    </module>
</module>
(base) schwering /ws/fips/cs/src$ cat cs/C.java 
package cs;

public class C {

    public static void main(String[] args) {
        System.out.println("foo"); //$NON-NLS-1$
    }

}
(base) schwering /ws/fips/cs/src$ RUN_LOCALE="-Duser.language=en -Duser.country=US"
(base) schwering /ws/fips/cs/src$ java $RUN_LOCALE -jar checkstyle-9.2-all.jar -c trailingChecks.xml cs/C.java 
Starting audit...
[WARN] /exchange/ws/fips/cs/src/cs/C.java:6:36: Don't use trailing comments. [TrailingComment]
Audit done.
```

When I change the config, it works:
```
(base) schwering /ws/fips/cs/src$ cat trailingChecks.xml 
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module PUBLIC "-//Puppy Crawl//DTD Check Configuration 1.3//EN" "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
<module name="Checker">
    <property name="severity" value="warning" />
    <module name="TreeWalker">
        <module name="TrailingComment">
            <property name="legalComment" value="NON-NLS" />
        </module>
    </module>
</module>
(base) schwering /ws/fips/cs/src$ java $RUN_LOCALE -jar checkstyle-9.2-all.jar -c trailingChecks.xml cs/C.java 
Starting audit...
Audit done.
```

It is not caused by the escaped dollar sign, as removing it in both the Java class and the config does again not work:
```
(base) schwering /ws/fips/cs/src$ cat cs/C.java 
package cs;

public class C {

    public static void main(String[] args) {
        System.out.println("foo"); //NON-NLS-1$
    }

}
(base) schwering /ws/fips/cs/src$ cat trailingChecks.xml 
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module PUBLIC "-//Puppy Crawl//DTD Check Configuration 1.3//EN" "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
<module name="Checker">
    <property name="severity" value="warning" />
    <module name="TreeWalker">
        <module name="TrailingComment">
            <property name="legalComment" value="NON-NLS" />
        </module>
    </module>
</module>
(base) schwering /ws/fips/cs/src$ java $RUN_LOCALE -jar checkstyle-9.2-all.jar -c trailingChecks.xml cs/C.java 
Starting audit...
[WARN] /exchange/ws/fips/cs/src/cs/C.java:6:36: Don't use trailing comments. [TrailingComment]
Audit done.
```

**Comment by nmancus1** [comment]
@hd42 please update issue description to follow issue template, this helps us to diagnose your problem.

**Comment by hd42** [comment]
@nmancus1, I have updated the description as requested.

I still believe that https://github.com/checkstyle/checkstyle/commit/ebef3bd59fdc2c97587a67bc59d57af6ecbb9072#diff-10fc864a1b0cedc1fc52a213219ee796b822378fe705dbed22e1ad7796409007R282 is the root of the problem - why would the first character of a single line comment be irrelevant?

**Comment by nmancus1** [comment]
@hd42 thanks for your example, and the link to the suspicious code.

> why would the first character of a single line comment be irrelevant?

I can only surmise that the check assumed that comments would be written like `// XXXX` instead of `//XXXX`, but in that case, the call to `trim()` takes care of leading whitespace anyway.

**Comment by nmancus1** [comment]
I am on it

**Comment by romani** [comment]
Regression from 8.41.1
https://github.com/checkstyle/checkstyle/commit/ebef3bd59fdc2c97587a67bc59d57af6ecbb9072#diff-10fc864a1b0cedc1fc52a213219ee796b822378fe705dbed22e1ad7796409007R282

**Comment by pbludov** [comment]
Fix is merged
