### ISSUE TITLE
Coverage checks have not been met

### ISSUE THREAD

**Issue by Rahulkhinchi03** [checkstyle/checkstyle#10995]
I am getting this error of `Coverage checks have not been met` which says:
`[WARNING] Rule violated for class com.puppycrawl.tools.checkstyle.checks.coding.IllegalTypeCheck: branches covered ratio is 0.97, but expected minimum is 1.00`

This issue occurred while resolving the issue: #10817, You can see here: #10958

**Comment by nmancus1** [comment]
@Rahulkhinchi03 this will be resolved in https://github.com/checkstyle/checkstyle/issues/10817, we will not merge PR unless coverage is 100%.

**Comment by Rahulkhinchi03** [comment]
I got this while running `MVN CLEAN VERIFY`. May I know how to resolve this in my local environment?

**Comment by strkkk** [comment]
@Rahulkhinchi03 please ask such question in gitter or in issue.

That means that some of your new code lines are not covered by tests.
you can import result jacoco coverage report (in target folder) an see what lines are not covered
https://www.jetbrains.com/help/idea/viewing-code-coverage-results.html
