### ISSUE TITLE
remove dead code from FinalClassCheck

### ISSUE THREAD

**Issue by Vladlis** [checkstyle/checkstyle#1100]
Getting modifiers == null appears to be impossible while running on an input file:
https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/design/FinalClassCheck.java#L69
https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/design/FinalClassCheck.java#L71
https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/design/FinalClassCheck.java#L77
Also toString() in the private nested class is never used
https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/design/FinalClassCheck.java#L173-L181

**Comment by romani** [comment]
![screenshot - 05182015 - 05 05 41 pm](https://cloud.githubusercontent.com/assets/812984/7693044/48871c50-fd80-11e4-8a38-12ffc38ea4ce.png)

the same Tree structure is for methods and c-tor.
