### ISSUE TITLE
Version 9.x Reports Whitespace Before Paren After String with Emojis

### ISSUE THREAD

**Issue by alzimmermsft** [checkstyle/checkstyle#11001]
I have read check documentation: https://checkstyle.org/config_whitespace.html#ParenPad
I have downloaded the latest checkstyle from: https://checkstyle.org/cmdline.html#Download_and_Run
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

```bash
/var/tmp $ javac Test.java

/var/tmp $ cat config.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
  "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
  "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
  <module name="TreeWalker">
    <module name="ParenPad"/>
  </module>
</module>

/var/tmp $ cat Test.java
public class Test {
    void emojiFamilyRunner(Consumer<String> testRunner, String text) {
        testRunner.accept("👩‍👩‍👧‍👧 " + text); // count as 12 units
    }

    void emojiFamilyWithSkinToneModifierRunner(Consumer<String> testRunner, String text) {
        testRunner.accept("👩🏻‍👩🏽‍👧🏾‍👦🏿 " + text); // count as 20 units
    }
}

/var/tmp $ RUN_LOCALE="-Duser.language=en -Duser.country=US"
/var/tmp $ java $RUN_LOCALE -jar checkstyle-9.2-all.jar -c config.xml Test.java
Starting audit...
[ERROR] C:\Users\Work\Documents\Playground\CheckstylePlayground\.\src\main\java\Test.java:8:44: ')' is preceded with whitespace. [ParenPad]
[ERROR] C:\Users\Work\Documents\Playground\CheckstylePlayground\.\src\main\java\Test.java:12:48: ')' is preceded with whitespace. [ParenPad]
Audit done.
```

For Windows users, please use `type` instead of `cat` and run

```cmd
set RUN_LOCALE="-Duser.language=en -Duser.country=US"
java %RUN_LOCALE% -jar checkstyle-9.2-all.jar -c config.xml Test.java
```

in place of the last 2 commands above.

---

I would have expected no errors to be reported in this case but it appears the emoji messes up with where the paren is being seen. This doesn't occur when using 8.45.1.

This appears to be similar to https://github.com/checkstyle/checkstyle/issues/10920.

**Comment by romani** [comment]
Series of emoji ticket, so much fun :)

**Comment by romani** [comment]
@nmancus1

**Comment by nmancus1** [comment]
While this could be done in https://github.com/checkstyle/checkstyle/issues/10924, I think it is better to provide a quick fix for this issue since scope of https://github.com/checkstyle/checkstyle/issues/10924 just grew significantly and may not make it into next release.

**Comment by nmancus1** [comment]
I am on it.

**Comment by romani** [comment]
Fix merged
