### ISSUE TITLE
All scripts in Travis should be single line to return exit code to Travis

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#11027]
After migration to Free tier Travis execution, we were have to abandon usage of "set -e" in travis.yml
https://github.com/checkstyle/checkstyle/issues/10778#issuecomment-962530901

We refactored almost all embedded executions except for eval of CMD.
Unfortunately this also needs to be moved to travis.sh file too.

problem is detected at https://github.com/checkstyle/eclipse-cs/pull/330#issuecomment-987591833
fixed by https://github.com/checkstyle/eclipse-cs/commit/07c0c9cc9963fd327b10df788e76b7a017a45720
but as we use IF conditions, we can not use same simple fix.

**Comment by rnveach** [comment]
Fix was merged
