### ISSUE TITLE
remove dead code from MutableExceptionCheck

### ISSUE THREAD

**Issue by Vladlis** [checkstyle/checkstyle#1103]
IDENT of an EXTENDS_CLAUSE can't be null while running the check, as the code is incompilable in this case
https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/design/MutableExceptionCheck.java#L155

**Comment by romani** [comment]
please create an issue and prove by picture from gui.Main that it is really dead code
http://checkstyle.sourceforge.net/cmdline.html#Download_and_Run, all changes in code should have a reason, especially removing checks for NULL.

**Comment by Vladlis** [comment]
![-checkstyle inputmutableexceptioncheck java](https://cloud.githubusercontent.com/assets/9678372/7693969/6ec09df8-fde2-11e4-932a-d7561e2e1820.png)

**Comment by romani** [comment]
Please never make a input on incompilable sources, tree could be weird. Checkstyle always work on compilable sources, behavour on noncompilable sources is unpredictable it could even crash.

**Comment by romani** [comment]
merged.
