### ISSUE TITLE
Enhance logging approach of SummaryJavadocCheck and use AST-based approach to get content of inline tag.

### ISSUE THREAD

**Issue by Vyom-Yadav** [checkstyle/checkstyle#11030]
I have downloaded the latest cli from: https://checkstyle.sourceforge.io/config_javadoc.html#SummaryJavadoc
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

**How it works Now:**

```bash
/var/tmp $ javac Test.java

/var/tmp $ cat config.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
    <module name="TreeWalker">
        <module name="SummaryJavadocCheck"/>
    </module>
</module>

/var/tmp $ cat Test.java
public class Test {

    /**
     * {@summary Missing period}
     */
    void foo() {
    }

    /**
     * {@summary Missing period
     * and having multiple lines}
     */
    void hoo() {
    }
}


/var/tmp $ RUN_LOCALE="-Duser.language=en -Duser.country=US"
/var/tmp $ java $RUN_LOCALE -jar checkstyle-10.0-all.jar -c config.xml Test.java
Starting audit...
[ERROR] /var/tmp/Test.java:3: Summary of Javadoc is missing an ending period. [SummaryJavadoc]
[ERROR] /var/tmp/Test.java:9: Summary of Javadoc is missing an ending period. [SummaryJavadoc]
Audit done.
Checkstyle ends with 2 errors.
```

**Describe the solution you'd like**
The logging approach is not optimized, it directly logs the violation at the start of javadoc comment, the least improvement that can be done is to log violation at the `@summary` tag.

Expected output-
```bash
/var/tmp $ RUN_LOCALE="-Duser.language=en -Duser.country=US"
/var/tmp $ java $RUN_LOCALE -jar checkstyle-9.2-all.jar -c config.xml Test.java
Starting audit...
[ERROR] /var/tmp/Test.java:4: Summary of Javadoc is missing an ending period. [SummaryJavadoc]
[ERROR] /var/tmp/Test.java:10: Summary of Javadoc is missing an ending period. [SummaryJavadoc]
Audit done.
Checkstyle ends with 2 errors.
```

Additionally, the check currently uses regex in the following method-
https://github.com/checkstyle/checkstyle/blob/c9134ce31c4776e4ab6764824bb234bf5495be0e/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SummaryJavadocCheck.java#L435-L446

This should be replaced by the AST approach which was initially discussed in https://github.com/checkstyle/checkstyle/issues/9993

**Comment by Vyom-Yadav** [comment]
@strkkk @nmancus1 Please share your thoughts so we can move forward in #10021

**Comment by strkkk** [comment]
@Vyom-Yadav I think it is a better approach than take text and try to replace something in it, as check does now

> The change in the logging approach has been demonstrated here.

Can there be something above summary tag? In this case difference in violation positions will be clearer. But it seems to me that it is an enhancement for check

**Comment by Vyom-Yadav** [comment]
> Can there be something above the summary tag? In this case difference in violation positions will be clearer.

@strkkk There can be something above the `@summary` tag but it will be redundant to do so as it won't be a part of the summary. 
Eg-
```
    /**
     * This is the first line.
     * {@summary This is the summary of the method.}
     */
    public void method() {

    }
```
Renders as-
![Screenshot from 2021-12-15 10-07-14](https://user-images.githubusercontent.com/73882557/146124196-be9f4dd7-379b-470a-9859-9f2805c1f049.png)

and Javadoc is generated with a warnnig-
```
/home/vyom/IdeaProjects/ConfigCheckstyle/src/TestP/Test.java:7: warning: invalid use of @summary
     * {@summary This is the summary of the method.}
       ^
```
Though you can see it in module details-
![Screenshot from 2021-12-15 10-11-16](https://user-images.githubusercontent.com/73882557/146124473-91978ae6-4baf-4d82-a230-35903da281ae.png)

> But it seems to me that it is an enhancement for check

Yes, this is an enhancement.

**Comment by nmancus1** [comment]
@strkkk After thinking on this a bit, I propose the following:

1. Change this issue to something like "Add support for `JAVADOC_INLINE_TAG` token to `SummaryJavadocCheck`" and show in description that exact line for violation is not shown without it (as demonstrated in https://github.com/checkstyle/checkstyle/pull/10021#issuecomment-989936364).
2. Send PR to update check, using implementation in https://github.com/checkstyle/checkstyle/pull/10021 to get tag content, and let creation of util method become a side effect of PR to solve this issue.
3. Close https://github.com/checkstyle/checkstyle/issues/9993 via PR for this issue.
4. Close https://github.com/checkstyle/checkstyle/pull/10021

This way we guarantee that util method works right the first time, and that changes in the check work as expected. Right now, it seems like https://github.com/checkstyle/checkstyle/issues/9993 and this issue depend on each other; do you think this is problematic?

**Comment by strkkk** [comment]
Great, I like your idea. I updated title and closed PR and issue. @Vyom-Yadav Please update description in this issue and send PR.

**Comment by Vyom-Yadav** [comment]
Updated Issue description

**Comment by Vyom-Yadav** [comment]
As pointed out by @romani in https://github.com/checkstyle/checkstyle/pull/11051#discussion_r786310930 we cannot add `JAVADOC_INLINE_TAG` to default tokens as that results in a `FileStatefulCheck`. Instead manual approach of searching for `JAVADOC_INLINE_TAG` will be followed, cost of finding `JAVADOC_INLINE_TAG` will be reduced by solving #11213

**Comment by romani** [comment]
@Vyom-Yadav, please update issue description to be issue template that we demand. Now I need to recover whole context from scratch and it became hard, sorry that I didn't insist on strict following issue template from the beginning.

**Comment by romani** [comment]
Keep in mind that issue title and description is all that our user have to understand what is changed and how it should work after update.
