### ISSUE TITLE
Rebase Github action is failing due to missed permission

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#11052]
https://github.com/checkstyle/checkstyle/runs/4561181390?check_suite_focus=true#step:6:24

https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#permissions

```
+ git push --force-with-lease fork issue_7688
To https://github.com/Binita-tech/checkstyle.git
 ! [remote rejected]     issue_7688 -> issue_7688 (refusing to allow a GitHub App to create
 or update workflow `.github/workflows/check-pr-description.yml` without `workflows` permission)
error: failed to push some refs to 'https://github.com/Binita-tech/checkstyle.git'
```

**Comment by romani** [comment]
@rcowsill , please suggest a fix.

**Comment by rcowsill** [comment]
It looks like the `GITHUB_TOKEN` doesn't allow this, see:

https://github.community/t/workflows-vs-actions-which-permission-is-correct/178137/2

This is intended to catch workflows updating themselves and running repeatedly. Unfortunately, it also blocks rebase of PRs when either the head or base have workflow changes.

You could use a Personal Access Token instead of `GITHUB_TOKEN`, but I think that's risky. Each GITHUB_TOKEN is only valid for one workflow run, whereas a PAT used for this would never expire.

Other than that, I think the only option is to manually rebase. If the workflow changes are in the PR base, then the automatic rebase should work fine afterwards (until the next workflow change).

**Comment by strkkk** [comment]
@rcowsill may be there is some way to create a specific token with enough permissions (instead of default GITHUB_TOKEN) and use it in this action?

**Comment by romani** [comment]
We can Update security to user more powerful token by default, and demand all our actions (except rebase) to define permissions in file by CI validation.
Defined permission block in workflow file override all default.

**Comment by rcowsill** [comment]
> We can Update security to user more powerful token by default(settings that we used before recent update), and demand all our actions (except rebase) to define permissions in file by CI validation. Defined permission block in workflow file override all default.

@romani Changing the default GITHUB_TOKEN permissions back to read/write won't help, unfortunately. This issue already existed before the permissions changes, for example:

https://github.com/checkstyle/checkstyle/runs/4422863678?check_suite_focus=true

That workflow had unrestricted permissions, but still failed to push the rebase because it contained an update to `.github/workflows/diff_report.yml`

**Comment by romani** [comment]
as experiment I did token RW at https://github.com/checkstyle/checkstyle/settings/actions
![image](https://user-images.githubusercontent.com/812984/146657500-150016bc-474e-4d8e-a7b7-8101bdb1f2a9.png)

and commented out permission in workflow - https://github.com/checkstyle/checkstyle/commit/f5d651654625f053a8eea833428f5a3da6b8744b

**Comment by romani** [comment]
after above changes ...
triggered at https://github.com/checkstyle/checkstyle/pull/10942#issuecomment-997303329
failed the same - https://github.com/checkstyle/checkstyle/runs/4571840746?check_suite_focus=true#step:6:25

**Comment by romani** [comment]
@strkkk , do you still have your testing repo where you tested this originally ? is it still works?

**Comment by strkkk** [comment]
@romani yes, I checked it and it still works
https://github.com/strkkk/checkstyle/pull/31

**Comment by romani** [comment]
Can you copy yml file from checkstyle repo to your repo to confirm that it works ?

**Comment by strkkk** [comment]
it fails with 
```
 ! [remote rejected]     chore/gitignore-change -> chore/gitignore-change (refusing to allow a GitHub App to create or update workflow `.github/workflows/rebase.yml` without `workflows` permission)
```

**Comment by rcowsill** [comment]
Can you try changing rebase.yml back to what it was in commit [358df70](https://github.com/strkkk/checkstyle/blob/358df70946226db7d4c1bce2496b298867288559/.github/workflows/rebase.yml), then auto-rebase https://github.com/strkkk/checkstyle/pull/31

**Comment by strkkk** [comment]
> Can you try changing rebase.yml back to what it was in commit [358df70](https://github.com/strkkk/checkstyle/blob/358df70946226db7d4c1bce2496b298867288559/.github/workflows/rebase.yml), then auto-rebase [strkkk#31](https://github.com/strkkk/checkstyle/pull/31)?

it worked as you can see in PR

**Comment by romani** [comment]
So problem is in yml file do you see critical diff ?

**Comment by rcowsill** [comment]
Sorry, I forgot something important - https://github.com/strkkk/checkstyle/pull/31 never got rebased to include the [84e24c7](https://github.com/strkkk/checkstyle/commit/84e24c7834df376da41f77b8474c3a81f5d75ed3) change. The test passed because there was no workflow yml diff in the [4596920356](https://github.com/strkkk/checkstyle/runs/4596920356?check_suite_focus=true) test run

**Comment by romani** [comment]
I removed this commented out code - https://github.com/checkstyle/checkstyle/commit/f1ebb4adff61b0f1732a82a6ecb4f0e93bffa859
triggered - https://github.com/checkstyle/checkstyle/pull/10930#issuecomment-998989665
failed - https://github.com/checkstyle/checkstyle/runs/4598443258?check_suite_focus=true

**Comment by romani** [comment]
and now it works - https://github.com/checkstyle/checkstyle/runs/4599844328?check_suite_focus=true
https://github.com/checkstyle/checkstyle/pull/11089#issuecomment-999081094

looks like only on new commits (that are rebased over my removal of commented out permissions) it become to work.
I am surprised.

**Comment by romani** [comment]
So we should update all following workflows to have permissions block:
```
✔ ~/java/github/romani/checkstyle [master|✔] 
$ grep -L "permissions" .github/workflows/* | grep -v rebase.yml""
.github/workflows/check-pr-description.yml
.github/workflows/no-exception-workflow.yml
.github/workflows/no_old_refs.yml
.github/workflows/pitest.yml
.github/workflows/run_link_check.yml
```

and place this bash validation to CI to make sure all further actions specify permissions explicitly

**Comment by strkkk** [comment]
@romani if there were changes in workflows, rebase wont work. Only commits without changes in workflows can be rebased. It is a known issue and it was there [before](https://github.com/checkstyle/checkstyle/issues/8842#issuecomment-696708847)

**Comment by romani** [comment]
good to know, thanks a lot for reminding, in this case such problem was before and continue to be, irrespective of default permission.

But does it mean that we can update global setting back to "Read permission" and specify permissions as rebase workflow and just pass a period until all PR manually rebased over such update ?

**Comment by strkkk** [comment]
we can just test it on any brand new fork created after this permissions change

**Comment by romani** [comment]
but in addition I have to revert https://github.com/checkstyle/checkstyle/commit/f1ebb4adff61b0f1732a82a6ecb4f0e93bffa859 and activate all that permissions.

**Comment by romani** [comment]
"Read repository contents permission" is set, 
rebase workflow permissions are back - https://github.com/checkstyle/checkstyle/commit/68bae70b0b4cff40b6511d9c9f403a476399cf9c

**Comment by romani** [comment]
I tested this 
and it is working !!!
https://github.com/checkstyle/checkstyle/pull/11089#issuecomment-999131013
https://github.com/checkstyle/checkstyle/runs/4600636585?check_suite_focus=true
![image](https://user-images.githubusercontent.com/812984/147005120-f8d393a5-6e10-4cfc-a2a6-7104cb1528ad.png)

**Comment by strkkk** [comment]
@romani I have an idea. We can create a wiki page with possible reasons of failure and add it to failure message of the action.

**Comment by romani** [comment]
next time it fails, we need to search in github isue tracker - it will give us solution.
