### ISSUE TITLE
AbstractExpressionHandler.getFirstAstNode might throw NPE

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#11055]
https://sonarcloud.io/project/issues?id=org.checkstyle%3Acheckstyle&issues=AXyeERcVIEIrBWM4sA6A&open=AXyeERcVIEIrBWM4sA6A

https://github.com/checkstyle/checkstyle/blob/e0aa61acf1f06e6ff0a1db0b90114e1becfdffbb/src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/AbstractExpressionHandler.java#L430-L434

disabled in Sonar until this issue, so remove Wontfix in Sonar after fix.

![image](https://user-images.githubusercontent.com/812984/146663340-65e11594-3493-4ef3-9417-60a2f6193b15.png)

**Comment by theexplorist** [comment]
Hi @romani want to work on this but what is the expected fix here?

**Comment by rnveach** [comment]
For these type of issues, we should confirm if an Exception is even possible. Do some regression to search for a case.

For this we need to identify which part of the code the exception is possible from.

If we can confirm that an Exception isn't possible logically and in regression, then we need to look to see how we can rewrite the code to hide the possible issue from the static scanner.

See how I handled a similar case in https://github.com/checkstyle/checkstyle/issues/11054 which is now resolved and closed.

**Comment by theexplorist** [comment]
> For these type of issues, we should confirm if an Exception is even possible. Do some regression to search for a case.
> 
> For this we need to identify which part of the code the exception is possible from.
> 
> If we can confirm that an Exception isn't possible logically and in regression, then we need to look to see how we can rewrite the code to hide the possible issue from the static scanner.
> 
> See how I handled a similar case in #11054 which is now resolved and closed.

@rnveach Can you please shed some more light on regression if possible, I surely want to work on this!

**Comment by rnveach** [comment]
> please shed some more light on regression 

https://github.com/checkstyle/contribution/tree/master/checkstyle-tester#checkstyle-tester
https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/README_MANUAL_EXECUTION.md#executing-diffgroovy
https://github.com/checkstyle/contribution/tree/master/checkstyle-tester#checkstyle-pitest-regression

**Comment by rnveach** [comment]
@romani How do you want to resolve this issue?

If `ast` coming into this method is `null`, then the result will be `null`.
If `ast` coming into this method is not `null`, then result will always be non-null. `while` loop says `curNode` is never `null`, and `curNode` is always assigned to the variable that is returned from this method, and nothing else modifies it.

If an NPE was possible, I assume we would have run into in regression. I can provide regression if you want.

I checked some of the calling methods, and they don't really seem possible to send a `null` downstream, with some having their own `null` checks.

**Comment by romani** [comment]
I think alanyser was misguided by null in while.

https://github.com/checkstyle/checkstyle/blob/e0aa61acf1f06e6ff0a1db0b90114e1becfdffbb/src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/AbstractExpressionHandler.java#L430-L434

if we remove this `curNode != null` then it will alert us. And it might be more correct as we should not go above node that we were given.

**Comment by rnveach** [comment]
Let me know how to proceed with this. I am thinking we can close this as the exact verbage is "might throw" and isnt' "does throw". With our limitations of how we write tests (no junits), I am not seeing how we can add a test to make code changes for and pass pitest/coverage.

I think analyzer does see `curNode != null` and thinks like I said, `ast` can be given as `null`, but really doesn't seem to be a valid case to cause it as it would already show in regression.

**Comment by romani** [comment]
I meant something like `while (curNode != ast` in form `do .... while`

**Comment by rnveach** [comment]
As discussed in PR,

There is no surviving mutations on this, so a lot of our tests says the code has to be like this. The code is identical to our TreeWalker code. The code is looking for a node by line/column, and since we don't keep our nodes ordered in source order, doing a random scan is really the only way. There are times we do go to null in this code. There are times were we going through multiple ASTs before we exit with our "answer". I don't see any "find by..." AST here then we already have.

I think we need to specify this as we won't fix it.

**Comment by romani** [comment]
by top link in issue, in sonarqube open Activity tab
![image](https://user-images.githubusercontent.com/812984/216782369-32249634-d888-48ef-a40c-30c63cc5a5d7.png)

changed to be permanent suppression.
