### ISSUE TITLE
removing dead code and refactoring in VisibilityModifierCheck

### ISSUE THREAD

**Issue by Vladlis** [checkstyle/checkstyle#1107]
Getting modifiers == null appears to be impossible while running on an input file, as it is explained in #1100 
https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/design/VisibilityModifierCheck.java#L569

Also, the whole method
https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/design/VisibilityModifierCheck.java#L547-L559
can be replaced by using just two methods - findFirstToken() and getNextSibling(), as it is shown here
https://github.com/checkstyle/checkstyle/compare/master...Vladlis:issue%231107?expand=1#diff-67e0d412b2b09442c70b1cd03c79b858R444

**Comment by Vladlis** [comment]
One branch here is unreachable, as nextSubTreeNode() never returns a token of type SEMI
https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/design/VisibilityModifierCheck.java#L668
when subTreeRootAst is found
https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/design/VisibilityModifierCheck.java#L691-L692
method returns toVisitAST, which is null, it can be seen from condition
https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/design/VisibilityModifierCheck.java#L690
so, condition nextSubTreeNode.getType() != TokenTypes.SEMI may be removed in order to achieve 100% coverage

**Comment by romani** [comment]
please run https://github.com/checkstyle/contribution/tree/master/checkstyle-tester project on all projects that are referenced at https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/projects-to-test-on.properties and make sure that no exceptions happen.

**Comment by Vladlis** [comment]
I guess, this issue can be closed, as https://github.com/checkstyle/checkstyle/pull/1109 is merged.
