### ISSUE TITLE
rename CheckStyleTask to CheckstyleAntTask

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#1108]
https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/CheckStyleTask.java

Class has to be moved to subpackage  "ant" to clearly show that it is not past of library.

As we host Ant extension, we need to rename this class to clealy state that is not related to library in pure meaning of term.

**Comment by mkordas** [comment]
When migrating Checkstyle Ant Task from Checkstyle 6.7 or older to Checkstyle 6.8, resource name in taskdef needs to be changed from `resource="checkstyletask.properties"` to `resource="checkstyle_ant_task.properties"`.

**Comment by mkordas** [comment]
Checkstyle Ant Task migration while updating to Checkstyle 6.8:
* replace all occurrences of `checkstyletask.properties` with `com/puppycrawl/tools/checkstyle/ant/checkstyle-ant-task.properties`
* replace all occurrences of `antlib:com.puppycrawl.tools.checkstyle` with `antlib:com.puppycrawl.tools.checkstyle.ant`

**Comment by romani** [comment]
merged.

**Comment by romani** [comment]
ATTENTION: compatibility with gradle plugin was broken (as gradle reused CheckStyleTask class) - https://travis-ci.org/sevntu-checkstyle/checkstyle-samples , plugin has to be updated

**Comment by romani** [comment]
https://discuss.gradle.org/t/checkstyle-6-8-release-brake-compatibility-with-gradle-checkstyle-plugin/10375

**Comment by mkordas** [comment]
That's quite serious incompatibility. Shouldn't we revert that commit and release as 6.8.2? We can wait for the fix on Gradle side and then bring the commit back. Moreover we should have integration test with Gradle as a lot of people use it these days.

**Comment by WonderCsabo** [comment]
[Issue on Gradle's JIRA.](https://issues.gradle.org/browse/GRADLE-3314)

**Comment by romani** [comment]
As we remove that fix, there will be incentive for community to upgrade to latest gradle, we would have to keep that fix for long time.

Old version users should stay with 6.7 .

**Comment by jsotuyod** [comment]
The same incompatibility is present with Maven's checkstyle plugin.

https://issues.apache.org/jira/browse/MCHECKSTYLE-300

**Comment by WonderCsabo** [comment]
@jsotuyod i do not think there is an incompatibility with maven-checkstyle-plugin. It does not use the `CheckStyleTask` class, and actually works with CS 6.8, i just tried it in a big project.

**Comment by jsotuyod** [comment]
@WonderCsabo you are absolutely right, thanks!

**Comment by romani** [comment]
> maven-checkstyle-plugin 

there should be no problem, we use maven plugin in our regression testing. So we will notice any braking compatibility on PR level.

**Comment by cperry-gpsw** [comment]
How do I get this fix into my build?

**Comment by romani** [comment]
switch to latest gradle. Example that works (verified by Travis) - https://github.com/sevntu-checkstyle/checkstyle-samples/tree/master/gradle-project
