### ISSUE TITLE
Fail test execution if Input file does nor have message on violation line and Check has not signle message

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#11091]
it become clear at https://github.com/checkstyle/checkstyle/pull/11051#issuecomment-999107833
that we do need to enforce it.

TODO:
if Check has not single message, and Input file contain `//violation` marker in it, we should fail validation and advice user to specify message in addition.

**Comment by Vyom-Yadav** [comment]
On it.

**Comment by Vyom-Yadav** [comment]
@romani What is expected for-

- `// X violations`
- `// X violations above`
- `// X violations below`

As in these, we cannot specify the message.

**Comment by Vyom-Yadav** [comment]
@romani Just had a thought, if we have multiple checks in a config file then it is a must to specify violation message irrespective of the number of error messages in the check as it would improve the readibility of violations, what do you think?

**Comment by romani** [comment]
> As in these, we cannot specify the message.

not yet :) , and yes, your proposal is good.
It might be challange to fit few messages in same line, but we might find a way.
We can relax our validation to not demand messages if any of such trailing comments are present.

**Comment by romani** [comment]
>  if you have multiple checks in an input file

lets skip such cases completely from validation
