### ISSUE TITLE
Remove checkConstructorIsPrivate from TestUtil#isUtilsClassHasPrivateConstructor

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#11107]
Parameter `checkConstructorIsPrivate` was added as a workaround for Powermock limitations. It is not required for now and should be removed.

_Originally posted by @pbludov in https://github.com/checkstyle/checkstyle/issues/10932#issuecomment-1001098029_

**Comment by pbludov** [comment]
@nmancus1 @rnveach @romani @strkkk 
I don't like `...isTrue()` checks. They are unnatural.

We can use Truth [extensions](https://truth.dev/extension) to implement `checkConstructorIsPrivate`. The assertion will be like that:

```
        assertWithMessage("Constructor is not private")
                .about(checkstyle())
                .that(ScopeUtil.class)
                .hasPrivateConstructor();
```

What do you think about such an idea?

**Comment by rnveach** [comment]
I have nothing against `isTrue`/`isFalse`.

**Comment by pbludov** [comment]
> I have nothing against `isTrue`/`isFalse`. Those are the ones I would prefer.

The problem with `isTrue/isFalse` is that the error message is less informative.
For example:

```java
        assertWithMessage("Some details")
                .that("a".endsWith("b"))
                .isTrue();
```
reports
```
value of: endsWith(...)
expected to be true
```
in turn
```java
        assertWithMessage("Some details")
                .that("a")
                .endsWith("b");
```
reports
```
expected to end with: "b"
but was             : "a"
```

the first variant only indicates that there are some failed assertions, without any hints.

**Comment by rnveach** [comment]
@pbludov can you provide the full message failure with `isTrue`? How does "Some details" plays into the output?

**Comment by pbludov** [comment]
> @pbludov can you provide the full message failure with `isTrue`? How does "Some details" plays into the output?

Of course, a good message can fix this. But you don't need to rely on him alone.

**Comment by nmancus1** [comment]
@pbludov can you show current output and proposed output upon failure of assertion for this case? I am having a hard time tying failure of util class to have private constructor into your example at https://github.com/checkstyle/checkstyle/issues/11107#issuecomment-1001102198

**Comment by pbludov** [comment]
Current output
```
Constructor is not private
value of: isUtilsClassHasPrivateConstructor(...)
expected to be true
```

Proposed output
```
Constructor is not private
class ScopeUtil
expected to have constructor with access modifier: private
but was:                                           public
```

```

**Comment by nmancus1** [comment]
Personally, I think that the current output is "good enough". Proposed output is better, though.

I think that the greatest value of this change would be to have an example of extending truth within the project, to make future extensions easier for maintainers (by having a "template" of sorts).
