### ISSUE TITLE
FinalParameters in checkstyle 9.2.1 gives error for records without final on parameters in constructor when having more than one constructor

### ISSUE THREAD

**Issue by kajh** [checkstyle/checkstyle#11126]
I have read check documentation: https://checkstyle.org/config_misc.html#FinalParameters
I have downloaded the latest checkstyle from: https://checkstyle.org/cmdline.html#Download_and_Run
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

```bash
/var/tmp $ javac DemoRecordOneConstructor.java
/var/tmp $ javac DemoRecordTwoConstructors.java

/var/tmp $ cat config.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
    "-//Puppy Crawl//DTD Check Configuration 1.2//EN"
    "http://www.puppycrawl.com/dtds/configuration_1_2.dtd">

<module name="Checker">
    <module name="TreeWalker">
        <module name="FinalParameters"/>
    </module>
</module>

/var/tmp $ cat DemoRecordOneConstructor.java 
public record DemoRecordOneConstructor(String name,int age){
}

/var/tmp $ cat DemoRecordTwoConstructors.java
public record DemoRecordTwoConstructors(String name,int age){

   public DemoRecordTwoConstructors(String name){
        this(name,50);
   }
}


/var/tmp $ RUN_LOCALE="-Duser.language=en -Duser.country=US"
/var/tmp $ java $RUN_LOCALE -jar checkstyle-9.2.1-all.jar -c config.xml DemoRecordOneConstructor.java 
Starting audit...
Audit done.

/var/tmp $ java $RUN_LOCALE -jar checkstyle-9.2.1-all.jar -c config.xml DemoRecordTwoConstructors.java 
Starting audit...
[ERROR] /Users/kajh/tmp/checkstyle/DemoRecordTwoConstructors.java:4:37: Parameter name should be final. [FinalParameters]
Audit done.
Checkstyle ends with 1 errors.
```
---
For records in java constructorparameters should not be required to be final when I use ```<module name="FinalParameters"/>```. This works fine with one constructor as shown with DemoRecordOneConstructor.java, but when I have two constructors I get an error when not having ```final``` on the parameters of the second constructor as shown with DemoRecordTwoConstructors.java.
---

**Comment by pbludov** [comment]
@kajh it is not clear what wrong with this check.

Such code
```java
public record DemoRecord(String name, int age) {

    public DemoRecord(final String name) {
        this(name, 50);
    }
}
```
compiles fine and has no violations.

**Comment by kajh** [comment]
Thanks for looking into this isssue. When running checkstyle 9.2.1 on this file I get one error:
```
/var/tmp $ java $RUN_LOCALE -jar checkstyle-9.2.1-all.jar -c config.xml DemoRecord.java
Starting audit...
[ERROR] /Users/kajh/tmp/checkstyle/DemoRecord.java:4:23: Parameter name should be final. [FinalParameters]
```
and I would expect this to not give this error.

**Comment by romani** [comment]
@kajh , please fix link to Check in issue description

**Comment by kajh** [comment]
@romani Done. Thanks for letting me know! Sorry for not doing this right the first time!

**Comment by pbludov** [comment]
> and I would expect this to not give this error. If I only have one constructor I don't get this error.

Still not clear. Please show the Java code with _one constructor_ and with _no error_.

**Comment by kajh** [comment]
Got it! Sorry! Fixed now! Thanks for your patience!

**Comment by strkkk** [comment]
@kajh issue can be closed?

**Comment by kajh** [comment]
Sorry if I misunderstand here, but from what I understand checkstyle should not give any errors for either of the classes, but it does for DemoRecordTwoConstructors.java. I think that is a bug. Do you agree?

**Comment by strkkk** [comment]
No, I do not agree. This check checks parameter name in constructor, this record has a constructor, so name of the parameter is checked.

Can you clarify why you expect no violations here?

**Comment by kajh** [comment]
My mistake! You are right! I thought since parameters in the declaration of the records does not need a final, the parameters in the constructors don't need it. That is of cource not right when I'm looking closer at it, since in the constructors the parameters can be changed but not in the declaration. Sorry for the noise and thanks again for your patience!
