### ISSUE TITLE
missing `-all.jar` file in the latest 9.2.1 release

### ISSUE THREAD

**Issue by chenrui333** [checkstyle/checkstyle#11121]
👋 it looks like the jar file is missed in the latest release, v9.2.1, can you please verify on your end? Thanks!

**Comment by Vyom-Yadav** [comment]
Yes it is missing, @romani kindly take a look, @chenrui333 In the meantime if you want to use the jar file you can download the zip file, cd into the zip file after extracting and run the command
 `mvn clean package -Passembly`
the jar file will be generated and will be located in `target/`, the command requires maven to be installed on your system.

**Comment by romani** [comment]
fixed.
generated by command above 

https://github.com/checkstyle/checkstyle/releases/tag/checkstyle-9.2.1

**Comment by chenrui333** [comment]
Thanks @Vyom-Yadav, @romani!
