### ISSUE TITLE
Add division operator to list of allowed tokens between numbers in MagicNumber check

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#1113]
Follow-up to http://stackoverflow.com/questions/30337382/checkstyle-doesnt-like-quotient-expression-for-constant

According to [MagicNumberCheck.java#L109][1] the following tokens are allowed between the number literals and enclosing constant definition to not be considered as magic numbers:

- ASSIGN (`=`),
- ARRAY_INIT (array initializer),
- EXPR (any expression),
- UNARY_PLUS (`+`),
- UNARY_MINUS (`-`),
- TYPECAST (cast operator),
- ELIST (list of expressions),
- LITERAL_NEW (`new`),
- METHOD_CALL (method call),
- STAR (`*`)

There is no **DIV** (`/`) token the list and this list is unfortunately unconfigurable:

```java
private static final int DEFAULT_SIZE_IN_BYTES = 256 * 1024; // fine

private static final double SPECIAL_RATIO = 4.0 / 3.0; // MagicNumber violations
```

My proposition is to add **DIV** to the list, as I see no harm in defining named special ratios.

#### Open questions:
1. Should users be able to configure the list of allowed tokens?
1. Should this list of allowed tokens be better documented?
1. Should the following also not cause any violations by default?
```java
private static final double SPECIAL_SUM = 2.0 + 10.0; // MagicNumber violations
private static final double SPECIAL_DIFFERENCE = 4.0 - Math.PI; // MagicNumber violation
```
  [1]: https://github.com/checkstyle/checkstyle/blob/0f58857d73933c7b6b7e62f0c7c16ad7af51556f/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MagicNumberCheck.java#L109

**Comment by romani** [comment]
> Should users be able to configure the list of allowed tokens?

No.

> Should this list of allowed tokens be better documented?

Possibly yes.

> Should the following also not cause any violations by default?

Yes.

**Comment by romani** [comment]
> ALLOWED_PATH_TOKENTYPES 

I misread your questions, sorry, that set of tokens could be managed by user through option, that will be good. As it will allow to be very strict if required. Feel free to open new issue for this, 

Your changes I am merging as you fixed original problem.

**Comment by romani** [comment]
merged.
