### ISSUE TITLE
Github CI does not run upon `Github, rebase` action

### ISSUE THREAD

**Issue by nrmancuso** [checkstyle/checkstyle#11134]
After PRs are rebased with `Github, rebase`, all other CI runs except for Github CI.

Example from https://github.com/checkstyle/checkstyle/pull/10999:
![image](https://user-images.githubusercontent.com/31252532/147765525-14d99eee-ff91-41d1-b6a9-dd6fea25c1c1.png)

Another example, from https://github.com/checkstyle/checkstyle/pull/11112:

![image](https://user-images.githubusercontent.com/31252532/147765703-a9dd3db2-0bba-45fc-b59e-1d330c30eeeb.png)

<details>
 <summary>Click to see tasks that ran in each PR</summary>

```
@cirrus-ci
Cirrus - JDK17 Successful in 20m — Task Summary
Details
@romani
IDEA Inspections Pull Request (Checkstyle) — TeamCity build finished
Details
@travis-ci
Travis CI - Pull Request Successful in 17m — Build Passed
Details
@azure-pipelines
checkstyle.checkstyle Successful in 13m — Build #20211228.10 succeeded
Details
@azure-pipelines
checkstyle.checkstyle (Job MacOS JDK11 verify) Successful in 13m — Job MacOS JDK11 verify succeeded
Details
@azure-pipelines
checkstyle.checkstyle (Job MacOS JDK13 verify) Successful in 11m — Job MacOS JDK13 verify succeeded
Details
@azure-pipelines
checkstyle.checkstyle (Job MacOS JDK14 verify) Successful in 10m — Job MacOS JDK14 verify succeeded
Details
@azure-pipelines
checkstyle.checkstyle (Job MacOS JDK8 verify) Successful in 9m — Job MacOS JDK8 verify succeeded
Details
@azure-pipelines
checkstyle.checkstyle (Job OpenJDK11 verify) Successful in 6m — Job OpenJDK11 verify succeeded
Details
@azure-pipelines
checkstyle.checkstyle (Job markdownlint) Successful in 19s — Job markdownlint succeeded
Details
@azure-pipelines
checkstyle.checkstyle (Job pr-age) Successful in 12s — Job pr-age succeeded
Details
@azure-pipelines
checkstyle.checkstyle (Job spelling) Successful in 23s — Job spelling succeeded
Details
@azure-pipelines
checkstyle.checkstyle (Job test) Successful in 2m — Job test succeeded
Details
@azure-pipelines
checkstyle.checkstyle (Job test-de) Successful in 3m — Job test-de succeeded
Details
@azure-pipelines
checkstyle.checkstyle (Job test-es) Successful in 3m — Job test-es succeeded
Details
@azure-pipelines
checkstyle.checkstyle (Job test-fi) Successful in 2m — Job test-fi succeeded
Details
@azure-pipelines
checkstyle.checkstyle (Job test-fr) Successful in 3m — Job test-fr succeeded
Details
@azure-pipelines
checkstyle.checkstyle (Job test-ja) Successful in 2m — Job test-ja succeeded
Details
@azure-pipelines
checkstyle.checkstyle (Job test-pt) Successful in 3m — Job test-pt succeeded
Details
@azure-pipelines
checkstyle.checkstyle (Job test-tr) Successful in 3m — Job test-tr succeeded
Details
@azure-pipelines
checkstyle.checkstyle (Job test-zh) Successful in 2m — Job test-zh succeeded
Details
@azure-pipelines
checkstyle.checkstyle (Job versions) Successful in 22s — Job versions succeeded
Details

ci/circleci: no-error-xwiki — Your tests passed on CircleCI!
Details

ci/circleci: no-exception-cassandra-storm-tapestry-javadoc — Your tests passed on CircleCI!
Details

ci/circleci: no-exception-hadoop-apache-groovy-scouter-javadoc — Your tests passed on CircleCI!
Details

ci/circleci: no-exception-lucene-and-others-javadoc — Your tests passed on CircleCI!
Details

ci/circleci: no-exception-only-javadoc — Your tests passed on CircleCI!
Details

ci/semaphoreci/pr: Checkstyle CI pipeline on Semaphore — The build passed on Semaphore 2.0.
Details

continuous-integration/appveyor/pr — AppVeyor build succeeded
Details

continuous-integration/drone/pr — Build is passing
Details

security/snyk (checkstyle) — No manifest changes detected in 1 project
Details

wercker/build — Wercker pipeline passed

```
</details>

In each, a total of 32 checks ran.

---------------------------
Expected behavior of CI:

Example:
![image](https://user-images.githubusercontent.com/31252532/147766371-69067fab-79fc-45d2-9b9d-68d1dc2d5ee0.png)

Note there is a total of 62 checks normally.

<details>
 <summary>Click to see tasks that ran in PR with no rebase action</summary>

```
@github-actions
Check PR Description / Analyze (pull_request) Successful in 6s
Details
@github-actions
CodeQL / Analyze (java) (pull_request) Successful in 4m
Details
@github-actions
Pitest / pitest-annotation (pull_request) Successful in 2m
Details
@github-actions
no-exception testing / no-exception-openjdk16 (pull_request) Successful in 62m
Details
@github-actions
Pitest / pitest-ant (pull_request) Successful in 1m
Details
@github-actions
Pitest / pitest-api (pull_request) Successful in 3m
Details
@github-actions
Pitest / pitest-blocks (pull_request) Successful in 1m
Details
@github-actions
Pitest / pitest-coding (pull_request) Successful in 7m
Details
@github-actions
Pitest / pitest-common (pull_request) Successful in 3m
Details
@github-actions
Pitest / pitest-common-2 (pull_request) Successful in 3m
Details
@github-actions
Pitest / pitest-design (pull_request) Successful in 2m
Details
@github-actions
Pitest / pitest-filters (pull_request) Successful in 2m
Details
@github-actions
Pitest / pitest-header (pull_request) Successful in 1m
Details
@github-actions
Pitest / pitest-imports (pull_request) Successful in 2m
Details
@github-actions
Pitest / pitest-indentation (pull_request) Successful in 8m
Details
@github-actions
Pitest / pitest-javadoc (pull_request) Successful in 8m
Details
@github-actions
Pitest / pitest-main (pull_request) Successful in 2m
Details
@github-actions
Pitest / pitest-metrics (pull_request) Successful in 2m
Details
@github-actions
Pitest / pitest-misc (pull_request) Successful in 4m
Details
@github-actions
Pitest / pitest-modifier (pull_request) Successful in 1m
Details
@github-actions
Pitest / pitest-naming (pull_request) Successful in 2m
Details
@github-actions
Pitest / pitest-packagenamesloader (pull_request) Successful in 1m
Details
@github-actions
Pitest / pitest-regexp (pull_request) Successful in 2m
Details
@github-actions
Pitest / pitest-sizes (pull_request) Successful in 1m
Details
@github-actions
Pitest / pitest-tree-walker (pull_request) Successful in 2m
Details
@github-actions
Pitest / pitest-utils (pull_request) Successful in 4m
Details
@github-actions
Pitest / pitest-whitespace (pull_request) Successful in 3m
Details
@github-actions
Pitest / pitest-xpath (pull_request) Successful in 1m
Details
@github-actions
Pitest / pitest-java-ast-visitor (pull_request) Successful in 4m
Details
@cirrus-ci
Cirrus - JDK17 Successful in 22m — Task Summary
Details
@github-code-scanning
Code scanning results / CodeQL Successful in 2s — No new or fixed alerts
Details
@romani
IDEA Inspections Pull Request (Checkstyle) — TeamCity build finished
Details
@travis-ci
Travis CI - Pull Request Successful in 27m — Build Passed
Details
@azure-pipelines
checkstyle.checkstyle Successful in 10m — Build #20211222.17 succeeded
Details
@azure-pipelines
checkstyle.checkstyle (Job MacOS JDK11 verify) Successful in 8m — Job MacOS JDK11 verify succeeded
Details
@azure-pipelines
checkstyle.checkstyle (Job MacOS JDK13 verify) Successful in 7m — Job MacOS JDK13 verify succeeded
Details
@azure-pipelines
checkstyle.checkstyle (Job MacOS JDK14 verify) Successful in 9m — Job MacOS JDK14 verify succeeded
Details
@azure-pipelines
checkstyle.checkstyle (Job MacOS JDK8 verify) Successful in 6m — Job MacOS JDK8 verify succeeded
Details
@azure-pipelines
checkstyle.checkstyle (Job OpenJDK11 verify) Successful in 5m — Job OpenJDK11 verify succeeded
Details
@azure-pipelines
checkstyle.checkstyle (Job markdownlint) Successful in 21s — Job markdownlint succeeded
Details
@azure-pipelines
checkstyle.checkstyle (Job pr-age) Successful in 11s — Job pr-age succeeded
Details
@azure-pipelines
checkstyle.checkstyle (Job spelling) Successful in 26s — Job spelling succeeded
Details
@azure-pipelines
checkstyle.checkstyle (Job test) Successful in 2m — Job test succeeded
Details
@azure-pipelines
checkstyle.checkstyle (Job test-de) Successful in 3m — Job test-de succeeded
Details
@azure-pipelines
checkstyle.checkstyle (Job test-es) Successful in 3m — Job test-es succeeded
Details
@azure-pipelines
checkstyle.checkstyle (Job test-fi) Successful in 3m — Job test-fi succeeded
Details
@azure-pipelines
checkstyle.checkstyle (Job test-fr) Successful in 3m — Job test-fr succeeded
Details
@azure-pipelines
checkstyle.checkstyle (Job test-ja) Successful in 3m — Job test-ja succeeded
Details
@azure-pipelines
checkstyle.checkstyle (Job test-pt) Successful in 3m — Job test-pt succeeded
Details
@azure-pipelines
checkstyle.checkstyle (Job test-tr) Successful in 3m — Job test-tr succeeded
Details
@azure-pipelines
checkstyle.checkstyle (Job test-zh) Successful in 3m — Job test-zh succeeded
Details
@azure-pipelines
checkstyle.checkstyle (Job versions) Successful in 21s — Job versions succeeded
Details

ci/circleci: no-error-xwiki — Your tests passed on CircleCI!
Details

ci/circleci: no-exception-cassandra-storm-tapestry-javadoc — Your tests passed on CircleCI!
Details

ci/circleci: no-exception-hadoop-apache-groovy-scouter-javadoc — Your tests passed on CircleCI!
Details

ci/circleci: no-exception-lucene-and-others-javadoc — Your tests passed on CircleCI!
Details

ci/circleci: no-exception-only-javadoc — Your tests passed on CircleCI!
Details

ci/semaphoreci/pr: Checkstyle CI pipeline on Semaphore — The build passed on Semaphore 2.0.
Details

continuous-integration/appveyor/pr — AppVeyor build succeeded
Details

continuous-integration/drone/pr — Build is passing
Details

security/snyk (checkstyle) — No manifest changes detected in 1 project
Details

wercker/build — Wercker pipeline passed
Details

```
</details>

**Comment by Vyom-Yadav** [comment]
on it.

**Comment by Vyom-Yadav** [comment]
@nmancus1 @romani @strkkk The reason rebase is not triggering new workflows is due to the fact that it uses default `GITHUB_TOKEN` and any PR's made by this default token won't trigger any workflows (GitHub actions based). 
https://github.com/checkstyle/checkstyle/blob/6e47445b3a966b6fb39af87177e308570e1b15bb/.github/workflows/rebase.yml#L40-L41
Related documentation-
https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#triggering-new-workflows-using-a-personal-access-token
The workaround github suggests uses PAT but PAT stays forever so I found a workaround that involves-

>### Authenticating with GitHub App generated tokens
>A GitHub App can be created for the sole purpose of generating tokens for use with GitHub actions.
These tokens can be used in place of `GITHUB_TOKEN` or a [Personal Access Token (PAT)](https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token).
GitHub App generated tokens are more secure than using a PAT because GitHub App access permissions can be set with finer granularity and are scoped to only repositories where the App is installed.
>1. Create a minimal [GitHub App](https://docs.github.com/en/developers/apps/creating-a-github-app), setting the following fields:
    - Set `GitHub App name`.
    - Set `Homepage URL` to anything you like, such as your GitHub profile page.
    - Uncheck `Active` under `Webhook`. You do not need to enter a `Webhook URL`.
    - Under `Repository permissions: Contents` select `Access: Read & write`.
    - Under `Repository permissions: Pull requests` select `Access: Read & write`.
>2. Create a Private key from the App settings page and store it securely.
>3. Install the App on any repository where workflows will run requiring tokens.
>4. Set secrets on your repository containing the GitHub App ID, and the private key you created in step 2. e.g. `APP_ID`, `APP_PRIVATE_KEY`.
>5. The following example workflow shows how to use [tibdex/github-app-token](https://github.com/tibdex/github-app-token) to generate a token for use with this action.
```yaml
    steps:
      - uses: actions/checkout@v2

      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      # Make changes to pull request here

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ steps.generate-token.outputs.token }}
```
[source](https://github.com/peter-evans/create-pull-request/blob/master/docs/concepts-guidelines.md#authenticating-with-github-app-generated-tokens)
I even tested this out in a test repo I made, https://github.com/Vyom-Yadav/actions-test.
Here is when I triggered rebase and the CI build was started again - https://github.com/Vyom-Yadav/actions-test/pull/3

**Comment by nmancus1** [comment]
@Vyom-Yadav thanks for investigating and making detailed example. Is it possible to use Github workflow API to run other workflows (Github CI tasks) from `rebase.yml` if rebase action is successful instead of PAT or specially created github app?

**Comment by Vyom-Yadav** [comment]
@nmancus1 Intrigued by your suggestion to use workflow API to run workflows I gave it a shot in my https://github.com/Vyom-Yadav/actions-test repo. I was expecting it to fail with the `GITHUB_TOKEN`, as automatic triggers do not support that (so manual also shouldn't support). The results-

- Was able to manually trigger a workflow using PAT but not using `GITHUB_TOKEN`, some commands if you want to also give it a try-
```yaml
- name: Manually trigger another workflow
        run: |
          curl \
          -X POST \
          -H "Authorization: token $token" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/Vyom-Yadav/actions-test/actions/workflows/action1.yml/dispatches \
          -d '{"ref":"testingRestApi"}'
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
```
won't work with `GITHUB_TOKEN`, replace it with-
```yaml
env:
   token: ${{ secrets.PAT }}
```
for the workflow to be triggered. 

- The manually triggered workflow won't appear in the checks column of the PR, it would be only visible in the actions tab.
![image](https://user-images.githubusercontent.com/73882557/149300096-42a3261b-b854-400f-8994-b01514426927.png)
It won't appear here ↑

Github currently [doesn't support](https://github.community/t/status-check-for-manual-action-workflow-dispatch/140333) manually triggered workflows to appear in checks tab. You will find a difference between `GITHUB_REF` on manual workflow and automatic workflow, for me in manual it was `refs/heads/testingRestApi`, and in automatic it was `refs/pull/4/merge`. You cannot pass in `refs/pull/4/merge` as the ref parameter in the body of API call, documentation says-
```
ref - Required. The git reference for the workflow. The reference can be a branch or tag name.
```
So now only solution in my opinion is to use PAT or a Github App. If you do not want to use either of them just close and reopen the PR after rebase, the checks will run again, which is not recommended. 
If you are concerned about security of Github App for generating tokens, it is better than PAT, the generated token remains usable for 60 sec or so which is better than PAT which may not even expire.

**Comment by rnveach** [comment]
@nrmancuso @Vyom-Yadav Do we have a way forward to make this work again?

**Comment by romani** [comment]
From CI
https://cloud.drone.io/checkstyle/checkstyle/13134/4/2

```
Cloning into 'checkstyle'...
LATEST_RELEASE_TAG=checkstyle-10.3.4
CS_RELEASE_VERSION=10.3.5
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

[WARN] Issue #12243 "Pitest/Checker: Drop New/Unnecessary Displays And Switch to Git Diff" is not closed! Please review issue https://github.com/checkstyle/checkstyle/issues/12243
[WARN] Issue #11214 "Specify violation messages in input files." is not closed! Please review issue https://github.com/checkstyle/checkstyle/issues/11214

Generation ends with 1 errors.
```

There are no error message that we expect.

**Comment by romani** [comment]
We already use PAT a lot. Let's use to let benefit from this action.

@stoyanK7 , can we reuse your master experience in actions to make our rebase work again?

**Comment by stoyanK7** [comment]
@romani 

Can you first check this out? It came out in Feb 2022. https://github.blog/changelog/2022-02-03-more-ways-to-keep-your-pull-request-branch-up-to-date/

Reading [the documentation](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-suggestions-to-update-pull-request-branches#about-suggestions-to-update-a-pull-request-branch) on it, I understand that
> people with write permissions will always have the ability, on the pull request page, to update a pull request's head branch when it's not up to date with the base branch.

---
If the above proposal is not what you are looking for, the only thing that needs to be done is to switch from `GITHUB_TOKEN` to `PAT`. Maybe also add `persist-credentials: false`(see https://github.com/actions/checkout/issues/485#issue-868200459) 

From what I've seen before, I suppose `PAT` has quite a lot of permissions. For security reasons, you can create a new personal access token `REBASE_TOKEN`(for example) with only these permissions:
https://github.com/checkstyle/checkstyle/blob/fd31119f2acdf8072e4205b6dd2abf5f118d4dd6/.github/workflows/rebase.yml#L15-L17

**Comment by romani** [comment]
@nrmancuso , what is your opinion on this ?

**Comment by nrmancuso** [comment]
> people with write permissions will always have the ability, on the pull request page, to update a pull request's head branch when it's not up to date with the base branch.

It is rare that we use origin branch for PRs, so this isn’t really an option. 

I think we should create some service user, and create PAT from there with exact permissions.

However, we still assume some risk on the checkstyle side of someone was able to get the PAT. I could think of a few ways to do this, but I won’t enumerate them here. The question becomes: is this GitHub action worth having a token with write access compromised?

**Comment by romani** [comment]
Based on https://github.blog/changelog/2022-02-03-more-ways-to-keep-your-pull-request-branch-up-to-date/

I activated at https://github.com/checkstyle/checkstyle/settings

>Always suggest updating pull request branches 
Whenever there are new changes available in the base branch, present an “update branch” option in the pull request.
