### ISSUE TITLE
Bump year to 2022

### ISSUE THREAD

**Issue by Vyom-Yadav** [checkstyle/checkstyle#11194]
Bump year to 2022
https://github.com/checkstyle/checkstyle/blob/master/.ci/bump-license-year.sh
https://github.com/checkstyle/checkstyle/blob/master/.ci/bump-license-year-in-all-projects.sh

**Comment by rnveach** [comment]
Feel free to say you are on it and send a PR.

**Comment by Vyom-Yadav** [comment]
on it

**Comment by Vyom-Yadav** [comment]
Why don't we set up an action for it with `cron` set to the new year, I can set it up if want.

**Comment by strkkk** [comment]
@Vyom-Yadav I like your idea, sound great. PR is welcome.

**Comment by romani** [comment]
I completely forgot to do this

**Comment by romani** [comment]
Done
