### ISSUE TITLE
Move methods common in UnusedLocalVariableCheck and FinalClassCheck to util

### ISSUE THREAD

**Issue by Vyom-Yadav** [checkstyle/checkstyle#11201]
From https://github.com/checkstyle/checkstyle/pull/10930#discussion_r785397301
To be addressed after merging #10930 
UnusedLocalVariableCheck (#10930) and FinalClassCheck (Check +  #10968) has some methods in common-

```
- extractQualifiedName(..)
- classNameMatchingCount(..)
- getQualifiedClassOrInterfaceName(DetailAST classAst) (known as `getQualifiedClassName` in final class)
- getQualifiedClassOrInterfaceName(String packageName, String outerClassQualifiedName, String className) (known as `getQualifiedClassName` in final class)
```
Also FinalClassCheck and UnusedLocalVariableCheck have a static nested class in common - `ClassDesc`. We may merge both of these classes and extract it somewhere, there are some overlapping properties.

When #10968 will be merged, extract these methods to util and try to remove the suppression for `ExcessiveClassLength` in UnusedLocalVariableCheck.

**Comment by romani** [comment]
we need to make sure that after moving to Util classes such methods we will not start covering them by pure unit test. All coverage should be done by Inputs like tests (functional tests).

**Comment by Vyom-Yadav** [comment]
UT's won't be required.

**Comment by Vyom-Yadav** [comment]
@nmancus1 @romani I want to combine `TypeDeclDesc` and `ClassDesc` and extract them somewhere, what would be the right place to extract them? I am thinking to place it in the util folder, will that be alright?

**Comment by romani** [comment]
ok, to keep them in 'util' package for now

**Comment by romani** [comment]
@Vyom-Yadav , please recheck https://github.com/checkstyle/checkstyle/runs/5612335973?check_suite_focus=true where we missed to remove reference to this issue?

**Comment by rnveach** [comment]
````
 ./config/pmd.xml:337 -> https://github.com/checkstyle/checkstyle/issues/11201
./config/suppressions.xml:63 -> https://github.com/checkstyle/checkstyle/issues/11201
````
