### ISSUE TITLE
Update `bump-license-year.sh` to use `g4` file extension.

### ISSUE THREAD

**Issue by nmancus1** [checkstyle/checkstyle#11203]
Currently, file name pattern in `find` only specifies `*.g`, which is ANTLR2 file extension:

https://github.com/checkstyle/checkstyle/blob/51159e3f1219622b9b45e827976912f0dd6c8b25/.ci/bump-license-year.sh#L12

 We need to update this to find ANTLR4 files (*.g4) to bump license year, and manually run workflow to send PR for license year bump to show that it works.

```
➜  grep -R "2001-202" | grep -v "2001-2022\|target"
src/main/resources/com/puppycrawl/tools/checkstyle/grammar/java/JavaLanguageParser.g4:// Copyright (C) 2001-2021 the original author or authors.
src/main/resources/com/puppycrawl/tools/checkstyle/grammar/java/JavaLanguageLexer.g4:// Copyright (C) 2001-2021 the original author or authors.
src/test/resources/com/puppycrawl/tools/checkstyle/checks/header/header/InputHeaderjava3.header://testvdfv Copyright (C) 2001-2020 the original author or authors.


```

**Comment by nmancus1** [comment]
On it

**Comment by rnveach** [comment]
@nmancus1 @romani Our javadoc grammar doesn't have a license on it as the first post demonstrates. Neither does our DTDs.

**Comment by rnveach** [comment]
> InputHeaderjava3.header

We should remove the license from inputs.
