### ISSUE TITLE
Option allowPublicFinalFields does not exist in VisibilityModifier check

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#1126]
Documentation of [VisibilityModifier](http://checkstyle.sourceforge.net/config_design.html#VisibilityModifier) states that there is property `allowPublicFinalFields`.

However, after setting this Checkstyle fails with error `Failed during checkstyle configuration: cannot initialize module TreeWalker - Property 'allowPublicFinalFields' in module VisibilityModifier does not exist, please check the documentation`

**Comment by Vladlis** [comment]
@mkordas, this must be typo in documentation, as there is property allowPublicImmutableFields in this check.

**Comment by romani** [comment]
fixed.
