### ISSUE TITLE
remove extra checkstyle build in no-exception-test.sh

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#11281]
detected at https://github.com/checkstyle/checkstyle/pull/11206#issuecomment-1030028019

checksyle buils is done in shell script:
https://github.com/checkstyle/checkstyle/blob/72f2d4c86626c39bb3b9647f98d7a6b5fb3f6e41/.ci/no-exception-test.sh#L17
+1 more checkstyle build is done in diff.groovy one more time, so 2 extra checkstyle builds :).

we do not need extra build in shell, we should remove it.

**Comment by Vyom-Yadav** [comment]
on it.
