### ISSUE TITLE
Add icon to the GUI window

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#11292]
Currently, the default Java application icon is used in the GUI window. This makes it difficult to use.
We have an icon image for the site `favicon`. It is possible to reuse this icon for GUI.

**Comment by romani** [comment]
share image how it is without icon

**Comment by pbludov** [comment]
The Java mascot:

![image](https://user-images.githubusercontent.com/900805/152688124-892c38cc-12e0-4ee2-9528-18f6f4aec854.png)

**Comment by pbludov** [comment]
Same for Alt+Tab:
![image](https://user-images.githubusercontent.com/900805/152688292-137f41fc-cc0a-4568-a224-449e54796957.png)

**Comment by pbludov** [comment]
Now:
![image](https://user-images.githubusercontent.com/900805/152689102-a01f5085-5040-44af-80e8-3eb77b8c890f.png)

**Comment by rnveach** [comment]
@romani @pbludov Is this issue fixed or is there still more to do?
