### ISSUE TITLE
All Checks have to work in defalt configuration without any Exceptions 

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#1129]
RegexpMultiline cause NPE in default config.
Regexp - cause NPE

Expeceted: some weird regexp is used "###NEVERMATCH###" or similar.

Please recheck all other Checks (https://github.com/checkstyle/checkstyle/blob/master/config/checkstyle_checks.xml) to work in default config without problem.

**Comment by mkordas** [comment]
:+1: - this was very annoying for me when I played with Checkstyle for a first time

**Comment by mkordas** [comment]
Is it also true for checks that require some external config like `ImportControl`?

**Comment by romani** [comment]
yes, even for filters that is true (all elements that we have config xml). they should do nothing in default config, and definitely not crashing.

**Comment by mkordas** [comment]
Are you sure about "doing nothing"?

E.g. _Header_ fails with meaningful exception `cannot initialize module Header - property 'headerFile' is missing or invalid in module Header`
and there are tests for that:
https://github.com/checkstyle/checkstyle/blob/master/src/test/java/com/puppycrawl/tools/checkstyle/checks/header/HeaderCheckTest.java#L175

I wouldn't remove this logic completely. What about replacing this exception with special violation like it's done in _ImportControl_? https://github.com/checkstyle/checkstyle/blob/master/src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlCheckTest.java#L74

**Comment by romani** [comment]
Yes "do noting" is too strict, but we have to choose for user what validation we can do by default.

Throw error us not useful as it will appear on each file, but should exists ones.

For this Check i think will be reasonale to just check existance of header with any text in it.

**Comment by romani** [comment]
@mkordas , are you ok if I assign that issue to @MEZk ?

**Comment by mkordas** [comment]
Sure - there's not much left to be done anyway.

**Comment by romani** [comment]
merged.
