### ISSUE TITLE
Replace usages of deprecated method AccessibleObject.isAccessible

### ISSUE THREAD

**Issue by nmancus1** [checkstyle/checkstyle#11309]
Noticed in https://github.com/checkstyle/checkstyle/pull/10904/files#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8L1521

Now that we have moved to Java 11, we should be able to replace usages of `AccessibleObject#isAccessible` and remove supressions at:

https://github.com/checkstyle/checkstyle/blob/d60a1b6638aa59e6cfb247184ecf7191b0743791/pom.xml#L1520-L1523

**Comment by rnveach** [comment]
Added as part of https://github.com/checkstyle/checkstyle/issues/10391
