### ISSUE TITLE
Remove noise from Coveralls by using one JDK for coverage builds

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#1133]
Oracle JDK 8 build (last one) always show about 0.1% higher code coverage:

![enter image description here][2]

Even if the pull request clearly only adds coverage, Coveralls calculates difference between worst coverage in current jobs (JDK 7) with the best one from the previous one (JDK 8), hence causing [comments in pull requests][3] like: 

![enter image description here][4]

My idea is to run Coveralls just on one JDK, not entire matrix.

  [2]: http://i.stack.imgur.com/bgiGj.png
  [3]: https://github.com/checkstyle/checkstyle/pull/1098
  [4]: http://i.stack.imgur.com/XMomY.png

**Comment by romani** [comment]
merged.
