### ISSUE TITLE
Wrap `assertThrows` with `getExpectedThrowable` method.

### ISSUE THREAD

**Issue by nrmancuso** [checkstyle/checkstyle#11343]
From https://github.com/checkstyle/checkstyle/issues/11315#issuecomment-1049494653:

> ATTENTION: I do not know why, but my brain do not not reading `assertThrows` properly. as it should be named `expectThrows` and assert on it done in separate block of code. should we create util method in our repo? to wrap/re-call `assertThrows`. To just have different name of method that is more logical to my mind.
> 
> code will looks like:
> 
> ```
>     public void testMethodGood() {
> 
>         int[] arr = new int[]{};
>         final IndexOutOfBoundsException exception =
>                 expectThrows(IndexOutOfBoundsException.class,
>                         () -> {
>                             int i = arr[2];
>                         });
> 
>         assertWithMessage("Invalid error message")
>                 .that(exception.getMessage())
>                 .isEqualTo("Index 2 out of bounds for length 0");
> 
>     }
> ```

In the scope of this issue, we should:

1. Create `getExpectedThrowable`method in TestUtils
2. Restrict import of `Assertions#assertThrows` to TestUtils only
3. Fix all violations in project.
4. Update`MatchXPath` module introduced in #11315 

We can consider using new feature mentioned at https://github.com/checkstyle/checkstyle/pull/11995#pullrequestreview-1051882798

**Comment by romani** [comment]
@pbludov , @strkkk , @rnveach , please share approval

**Comment by rnveach** [comment]
I am fine with the new util method.

**Comment by nick-mancuso** [comment]
All approve, label added.

**Comment by Kevin222004** [comment]
can i start work on this issue ?

**Comment by strkkk** [comment]
@Kevin222004 yes

**Comment by Kevin222004** [comment]
Maintainer it is request to you that it may be delay more to make a pull request My university  examination is starting 
sorry for  inconsistency

**Comment by romani** [comment]
This might be an option https://github.com/checkstyle/checkstyle/pull/11995#pullrequestreview-1051882798

**Comment by nrmancuso** [comment]
Closed via https://github.com/checkstyle/checkstyle/pull/14686

Thanks a lot @Kevin222004 !
