### ISSUE TITLE
Add ignoreMethodAnnotatedBy property to ParameterNumberCheck

### ISSUE THREAD

**Issue by tfij** [checkstyle/checkstyle#11340]
Check name: [ParameterNumberCheck](https://checkstyle.org/config_sizes.html#ParameterNumber)

https://checkstyle.org/checks/sizes/parameternumber.html#ParameterNumber

## Problem

https://www.baeldung.com/jackson-annotations#1-jsoncreator
https://fasterxml.github.io/jackson-annotations/javadoc/2.7/com/fasterxml/jackson/annotation/JsonCreator.html
If I implement external API, I have no power over the number of parameters, e.g. when creating a DTO class for REST API and deserializing JSON to an object by constructor annotated by @JsonCreator

```
class MyDto {
  private final String a1;
  private final String a2;
  private final String a3;
  private final String a4;
  private final String a5;
  private final String a6;
  private final String a7;
  private final String a8;
  private final String a9;

  @JsonCreator
  MyDto(String a1, String a2, String a3, String a4, String a5, String a6, String a7, String a8, String a9) {
    this.a1 = a1;
    this.a2 = a2;
    this.a3 = a3;
    this.a4 = a4;
    this.a5 = a5;
    this.a6 = a6;
    this.a7 = a7;
    this.a8 = a8;
    this.a9 = a9;
  }
}
```

## Solution

I'd like to configure check to ignore this constructor. In general, ignore all methods annotated by `@JsonCreator`, e.g.

```
 <module name="ParameterNumber">
   <property name="max" value="5"/>
   <property name="ignoreMethodAnnotatedBy" value="JsonCreator"/>
 </module>
```

The PR with the proposal is here https://github.com/checkstyle/checkstyle/pull/11339

Check already has property `ignoreOverriddenMethods`  so new property will make it more general.

**Comment by bgalek** [comment]
Nice!

**Comment by nmancus1** [comment]
Supression of constructors with this annotation can be achieved via [SuppresionXpathSingleFilter](https://checkstyle.sourceforge.io/config_filters.html#SuppressionXpathSingleFilter):

```
➜  java cat Test.java 
public class Test {
    private final String a1;
    private final String a2;
    private final String a3;
    private final String a4;
    private final String a5;
    private final String a6;
    private final String a7;
    private final String a8;
    private final String a9;

    @JsonCreator
    Test(String a1, String a2, String a3, String a4, String a5, String a6, String a7, String a8, String a9) {
        this.a1 = a1;
        this.a2 = a2;
        this.a3 = a3;
        this.a4 = a4;
        this.a5 = a5;
        this.a6 = a6;
        this.a7 = a7;
        this.a8 = a8;
        this.a9 = a9;
    }
}

@interface JsonCreator {}

➜  java javac Test.java

➜  java cat config.xml 
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
        "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>
    <module name="TreeWalker">
        <module name="ParameterNumber">
            <property name="max" value="5"/>
        </module>
        <module name="SuppressionXpathSingleFilter">
            <property name="checks" value="ParameterNumber"/>
            <property name="query"
                      value="//CTOR_DEF/IDENT[preceding-sibling::MODIFIERS/ANNOTATION/IDENT[@text='JsonCreator']]"/>
        </module>

    </module>
</module>

➜  java java -jar checkstyle-9.3-all.jar -c config.xml Test.java
Starting audit...
Audit done.


```

@tfij we typically try to avoid adding properties to checks when we can handle suppression of special cases with some filter. If you prefer to use a suppression file, you can use the same XPath with https://checkstyle.sourceforge.io/config_filters.html#SuppressionXpathFilter.

**Comment by romani** [comment]
@nmancus1 , @rnveach , @strkkk , @pbludov ,
lets think/vote/re-consider on our decision to avoid extra suppresion/ignore properties. We use to make this decision as we had no time to provide updates to all user requests, so Xpath is definitely workaround for user, but it is not very good for configurations as it imply two modules that are hard to keep together and manage later on.

in the same time, updating Checks to have such properties might also be not that good, as potentially all Checks might need something like this. And it is magic of certain library that not everyone is using. But in the same time instrumenting code with magic annotations is definitely a trend.

**Comment by nmancus1** [comment]
As for me, I prefer to keep checks simple, and only add properties if they cannot be covered by some reasonable/ reliable XPath or other filter. So,

> avoid extra suppresion/ignore properties

would be my vote. 

As experience has shown, checks with lots of properties become harder to maintain; not just from a simple code standpoint, but also the logic of how the properties interact with each other. 

Just as a related note - I think that we need to keep a "repository" of sorts (or entire website page) for all of the XPath related modules that we create, to help users more readily find what they need (with examples).

**Comment by romani** [comment]
usually we resolved such cases, by example in documentation (xdoc) on how to handle frequently use edge cases, so googling usually helps to find solution.

**Comment by tfij** [comment]
I agree with @romani 
> it imply two modules that are hard to keep together and manage later on

How about making it possible to set suppress property for any check configuration? In this case

```
<module name="ParameterNumber">
    <property name="max" value="5"/>
    <suppress-check query="//CTOR_DEF/IDENT[preceding-sibling::MODIFIERS/ANNOTATION/IDENT[@text='JsonCreator']]
                            | //METHOD_DEF/IDENT[preceding-sibling::MODIFIERS/ANNOTATION/IDENT[@text='JsonCreator']]" />
</module>
```

or something like this.

It will solve a problem with two modules maintained separately.

**Comment by romani** [comment]
we did not make it like this few years ago, as implementation of Xpath was not mature enough, we still have items to finish to make it for all Checks. May be we can start sooner, somebody need to do deep thinking on this.

Even we will have this option, it is not user friendly approach and can help users for edge cases. But we still need to think on most common ways to suppress and allow them to be done by Check properties. This border of xpath to Check special property is not defined by us and not clear for us.

**Comment by pbludov** [comment]
I am against complicating the check. Such property will fix this particular issue, but it won't work for another.
Suppressions are more flexible.

**Comment by rnveach** [comment]
I think I might like the idea of adding suppressions to the check itself, locking the 2 together. The only downside to that is there would need to be some type of double checking that this new suppression is only suppressing the violations of this check and not accidentally picking up some other check by user configuration error.

I am probably more extreme in that we have `ignoreOverriddenMethods` which is already looking at annotations. Why don't we just deprecate that and extend it to all annotation and then the user can add `@Override` or any other annotation. (`ignoreOverriddenMethods` is default to `false`, so we would continue that default in the new property). To me this makes more sense as it allows, like this issue wants, a more broader usage.

Otherwise, I don't think I can get behind having the 2 options live together in the same check.

**Comment by romani** [comment]
Deprecation is long for us and painful process for users. Better to keep two options and let them work by same code inside.

Xpath is too brutal to user, it tooks awhile for users to understand how to do this, and how to make xpath expression that is required. @tfij, imagine we did not give you xpath expression, how much time you will spend to make it ?

But in the same time Lombok like libraries become very popular way of codding now. So suppression by annotation might be well used approach.

**Comment by tfij** [comment]
Agree, xpath is very mysterious. Mainly because I don't know what XML structure I'm scanning.
I imagine that if user hadn't found a ready or similar solution in the documentation or on stackoverflow, it would take hours to work out this by themself.

**Comment by nmancus1** [comment]
After reading through the discussion here, and thinking on this some more, I have reconsidered my general position on check properties. If a new check property that is a “feature” is proposed, I stay with my original position. But - if new property is some simple suppression (i.e. checking for a particular annotation) , we should consider it. Most of the time, this will just require some Boolean method used to guard the `log` method.

We do not want to make Checkstyle difficult to configure or inflexible, this will only frustrate users.

**Comment by romani** [comment]
I more care about users experience, implementation pain is limited to few people during PR and eventually forgotten. We use/reconfigure checkstyle more than we spend time to code it.

Xpath suppression was good approach to resolve problem on user side quickly, temporary hack. And it might continue to serve this purpose.

But custom ignore properties are a way more easy to use.

**Comment by romani** [comment]
Ignore by annotation will be most used ignore/suppression approach. As annotation imply some third-party features/magic that happening in runtime or compilation time,
Checkstyle  is not working at that time, so we have to skip validation in some cases.

We did not have time to implement ignore properties in Checks, that is why we invested more in xpath to let users has workaround sooner, but if implementation is provided by community, I think it is good to accept it. Especially if we see that such ignore approach can be widely reused.

**Comment by nick-mancuso** [comment]
Let's make a decision here, in regards to this particular issue. If we want to continue discussion about adding check properties in general, let's create a Github discussion and continue there.

After thinking on @romani 's comments above, I am for approval of this issue.

**Comment by romani** [comment]
One more example of Lombok usage that cause unwanted violation https://github.com/checkstyle/checkstyle/issues/11415

**Comment by tfij** [comment]
Hi, is there anything I can do to help make the decision?
I hope it will be the approval of this proposal :)

**Comment by romani** [comment]
@tfij, can I ask you to help :
We need to review all Checks that has same property and list all of them, and we need to choose a good name from existing or just new.

For now I think we should name it like: ignoreAnnothedBy or something similar. We should avoid usage of "method" or similar words to let it be used for any Check target.

Can we also analyze what Checks are highly likely to have such property in future? And what Check unlikely to change behavior by annotated target.

**Comment by romani** [comment]
one more example how annotation make false positive for static analisys - https://github.com/checkstyle/checkstyle/pull/11481
pmd using property `ignoredAnnotations`

**Comment by romani** [comment]
All Checks, any readable format, to see what we have already

**Comment by tfij** [comment]
@romani 
This is a list of all checks with all not static fields (type and name).
https://gist.github.com/tfij/58f1b0e1e5e6e15c0a3730f46872762e
Hope it will be useful. Reach out if you need any other data.

**Comment by romani** [comment]
@tfij, thanks a lot.
can ask you grep properties that are about ignorance/skip/exclude by annotations.

**Comment by romani** [comment]
Sorry that issue lost from my attention for more than year.

I am ok to approve issue with new property `ignoreAnnotatedBy`.

@nrmancuso , pre-approved at https://github.com/checkstyle/checkstyle/issues/11340#issuecomment-1062967967

@rnveach , please share your opinion and if you agree , please put approved label.

**Comment by rnveach** [comment]
My only question on adding this type of properties is why go through this trouble when xpath suppression can do the same thing.

I also question if the property will use the FQCP for the annotation, or if it will just be the class name.

Otherwise, I am good.

**Comment by romani** [comment]
>  if the property will use the FQCP for the annotation,

yes

>  why go through this trouble when xpath suppression can do the same thing.

xpath is very complicated concept, it is good for one time workaround, but for cases where lombok is popular (people are lazy to type and lombok is  popular to generate code for people, all IDEs support it, so it become a part of our life). and Lombok is not the only library that does this, there are many. Consolidation of whole config in one `<module>`  is easy for user concept.

I am not ready to discuss embebded xpath suppression property in each module for now, but looks like we slowly going to this decision.

**Comment by romani** [comment]
```
 <module name="ParameterNumber">
   <property name="max" value="5"/>
   <property name="ignoreAnnotatedBy" value="JsonCreator"/>
 </module>
```

sounds like ignore parameter that is annotated by, not a method.

Sounds like we have to come back to originnal:
```
 <module name="ParameterNumber">
   <property name="max" value="5"/>
   <property name="ignoreMethodAnnotatedBy" value="JsonCreator"/>
 </module>
```
to be very explicit where annotation is expected. Ideally user should not read documentation to understand how to configure Check.

@rnveach , please approve.

**Comment by romani** [comment]
@rnveach , @nrmancuso , please review and approve.

@tfij, if no response will be there before 1 january 2023, please mention me here, I will approve issue.

**Comment by nrmancuso** [comment]
I would prefer this new property to be called `ignoreAnnotatedBy` for two reasons:

1. ParameterNumber also checks constructors
2. As we extend this concept to other checks, property name can be consistent and users don’t have to be concerned with details

**Comment by romani** [comment]
Ok, let's move forward with `ignoreAnnotatedBy`.

**Comment by romani** [comment]
Everyone is welcome to finish this PR https://github.com/checkstyle/checkstyle/pull/11339, just reuse code and move this PR across finish line.

@sktpy, do you have time to help us with this issue ?

**Comment by sktpy** [comment]
Label needs to be added (new feature ig)
https://github.com/checkstyle/checkstyle/actions/runs/8361654518/job/22890247968#step:4:130

Also, I am not sure how the release works, but I think this was supposed to be released with 10.15.0 https://github.com/checkstyle/checkstyle/pull/14553#discussion_r1506925745 but the bot has added it to 10.14.3 milestone.

**Comment by nrmancuso** [comment]
@sktpy  thanks for noticing this, we have added the label. As far as the milestone goes, I think that is automatically recalculated based on what labels were on the issues at the time of release.

**Comment by romani** [comment]
yes, but maintainers has classify issue after fix/merge and update version by github action

https://github.com/checkstyle/checkstyle/actions/runs/8369880545/job/22916356794#step:4:130

>Generation ends with 1 errors.
Error:  Validation of release number failed. Release number is a patch(10.14.3), but release notes contain 'new' or 'breaking compatability' labels. Please correct release number by running https://github.com/checkstyle/checkstyle/actions/workflows/bump-version-and-update-milestone.yml . The offending issue(s): https://github.com/checkstyle/checkstyle/issues/11340
Error: Process completed with exit code 254.

**Comment by romani** [comment]
done https://github.com/checkstyle/checkstyle/actions/runs/8375045697
