### ISSUE TITLE
Large overhead from using streams in TokenUtil.isOfType

### ISSUE THREAD

**Issue by SanderGielisse** [checkstyle/checkstyle#11370]
By doing some time analysis using VisualVM, I found that the `isOfType` method of the `TokenUtil` class taking quite a lot of time, as shown below.
![issue0](https://user-images.githubusercontent.com/4587552/156930498-c85d7ad3-dbdb-4a47-a862-52abfb3114fc.png)

The current implementation is;
```
    public static boolean isOfType(int type, int... types) {
        return Arrays.stream(types).anyMatch(tokenType -> tokenType == type);
    }
```

While the slight overhead of using streams (which was probably done to improve readability / maintainability) does not seem like a big issue at first sight, I found that, when executed on some larger projects, this `isOfType` method is called somewhere in the order of several **billion** times... Using the current implementation, I've found cases where around 30% of the time is spent inside of the stream logic (see screenshot). I have tested that a simple naive implementation reduces this to almost 0%. 

Note; this is not a full-benchmark from start-to-end as I stopped it after +/- 120 seconds. So the time spent inside of `isOfType` took 30% of the first 120 seconds of running Checkstyle (quite a lot...), which using the naive implementation dropped to near 0. If it is desired, I could look into doing further benchmarks to give more precise and definitive answers regarding the exact effect, but I hope this issue at least shows a naive implementation is more advantageous in general.

Opened a PR at https://github.com/checkstyle/checkstyle/pull/11371

**Comment by nick-mancuso** [comment]
> By doing some time analysis using VisualVM

@SanderGielisse I am curious, what prompted your investigation?

**Comment by rnveach** [comment]
From my local and running checkstyle on itself,
https://github.com/rnveach/checkstyle/commits/more_audits
````
    public static boolean isOfType(int type, int... types) {
        boolean matching = false;
        synchronized (instance) {
        Checker.GLOBAL_DISPATCHER.fireCustomStarted("isOfType");
        matching = Arrays.stream(types).anyMatch(tokenType -> tokenType == type);
        Checker.GLOBAL_DISPATCHER.fireCustomFinished("isOfType");
        }
        return matching;
    }
````

Output:
````
Run Time: 41.293

Format:
Name	Uses	Time	Min	Max	Average


Parses: (2)
Java	967	5.69	0.0	0.355	0.005
JavaDoc	6022	20.341	0.0	0.6	0.003


Customs: (1)
isOfType	2712864	0.546	0.0	0.002	0.0
````

Based on this, total time for `isOfType` is currently only 1.3% of the total execution time for Checkstyle. If your run was 60 minutes, we wouldn't even be talking about 1 minute of time.

**Comment by rnveach** [comment]
@SanderGielisse Also please provide us what version of checkstyle you are using and JDK.
I would also like to do a test run on your project if it is opensource.

**Comment by SanderGielisse** [comment]
You are right in your case, I've also confirmed that this is not an issue when running Checkstyle on Checkstyle using the Checkstyle configs. However, for me the issue exists under different conditions.

I was running Checkstyle on a project using the `google_checks.xml`configuration, though it never had been formatted / programmed for these checks (so LOTS of warning / errors). I am not sure if the issue is with the large number of warnings / errors, or the `google_checks.xml` on itself, but the issue persists if you run Checkstyle on Checkstyle using `google_checks.xml` instead of the Checkstyle configs. Then I get in the order of several billion `isTypeOf`-calls rather quickly which slows down everything significantly.

With regards to the speed-up, I am not sure why your findings with regards to the naive approach's performance are so different from mine. I am not sure how your checker works, but how accurate is your `Checker.GLOBAL_DISPATCHER` approach? I have not used it before, but wouldn't running this millions of times cause such reasonable overhead that you are no longer actually measuring the performance of the `isTypeOf` method? The difference with VisualVM is really big. I will test this a bit more later as I'm quite curious.

In any case, I currently do not see any cases where the naive faster method is bad, nor can I think of any. Even if there are just a couple specific cases in which it causes a significant speedup, I feel like it could already be beneficial if it is at practically no cost. Running more and more benchmarks would probably give us perfect numbers, but I am not sure if going that way is useful, but I'd love to hear your opinion on that.

**Comment by nick-mancuso** [comment]
I think we can further improve on `TokenUtil#isOfType` implementation now that we switched to Java 11: modify `TokenUtil#isOfType` to accept a `Set` of tokens to check (via `Set#contains`), instead of an array of `int`s. We can pass tokens as an argument to method using `Set.of()`. We never care about the order of such tokens, so iteration is not needed. Both `Set#of` and `Set#contains` run in constant time.

**Comment by SanderGielisse** [comment]
Neat idea, yet I am unsure if it's necessarily faster. From what I saw during debugging, these 'sets' would usually be really small, like a couple of elements. Using a HashSet or something similar would be great for enormous sets, but I feel like when they are so small it might just be overhead (hash calculations, etc...); a naive loop might still be the fastest option. Currently, the naive loop is so fast that in my VisualVM I no longer see the calls to `isTypeOf`, but I could of course change the timings a bit. I like the idea though and we could surely look into it a bit more.

**Comment by nick-mancuso** [comment]
Good point, most calls to `TokenUtil#isOfType` are with less than 10 elements, so extra method calls, etc. are probably not worth it.

**Comment by rnveach** [comment]
> I was running Checkstyle on a project using the google_checks.xmlconfiguration, though it never had been formatted / programmed for these checks (so LOTS of warning / errors)

I didn't see an answer to my previous post, again, see it and provide us your project if you can. We really could be talking about make up of source files and errors outputted. I would think CPU speed between us would be relative to a degree.

> I am not sure how your checker works, but how accurate is your Checker.GLOBAL_DISPATCHER approach? 
>  I have not used it before

`more_audits` is my unofficial way of doing speed tests for Checkstyle only. So pretty much no one has. :)

I will say it has not gone through any strict review process, but from the testing I have done and such, I feel it does give an accurate representation of execution time. I tried doing my own double checking when setting it up to ensure I wasn't providing wrong data, and things lined up. I built it as I wanted raw data on a lot of things, and disliked how VisualVM needed to hang the thread at the end to see the data or have it be lost.

I tried running `google_checks` over our project since I don't have your project, and the numbers dropped more with `google_checks`. (0.27% execution time)
````
Run Time: 33.1

Customs: (1)
isOfType	253062	0.091	0.0	0.0	0.0
````

> wouldn't running this millions of times cause such reasonable overhead that you are no longer actually measuring the performance of the isTypeOf method? 

IMO, I think we may be starting to split some hairs here. I can't believe VisualVM can do the exact same without some of it's own slowdowns or quirks as it must track things in a somewhat similar fashion on when something starts and ends.

You are correct that doing this will slow down the run. I need to call a method to tell it when, where, and how to start the time and end the time. The start and end times that are funneled through `DebugListener` are built that time starts at the very end of the method call, and time ends at the very beginning of the next method call with trying to reduce any extra tasks in-between those points. There is very little room between the extra call and the code being tested. I tried to do everything I could with this implementation so it could be usable, if not accurate.

If there was any extra overhead being added, I would expect all numbers to have that same overhead. This should make them all be relative to each other. The slowdown will be added to the total run time, as well as the specific points run time. So saying 1% slowdown should still be similar to with and without this listener added.

The time being used is nano time, so it is as accurate as Java will let it be. I keep adding any number given to the total time, so I am not dropping anything above 0 nanos.

> I'd love to hear your opinion on that.

I am already fine on your implementation, I just wanted to look at your case.

**Comment by rnveach** [comment]
I tried one last on a LONGER run. I ran `google_checks` over everything in Checkstyle, inputs and all.

`-c ${workspace_loc}\checkstyle\src\main\resources\google_checks.xml ${workspace_loc}\checkstyle --executeIgnoredModules`

````
Run Time: 775.37

Files: (6380)

Parses: (2)
Java	5298	82.304	0.0	30.46	0.015
JavaDoc	17028	25.557	0.0	0.668	0.001


Customs: (1)
isOfType	1716671758	393.225	0.0	0.041	0.0
````

I also did a second run to confirm the results.

````
Run Time: 608.623

Parses: (2)
Java	5298	84.853	0.0	32.199	0.016
JavaDoc	17028	23.903	0.0	0.586	0.001


Customs: (1)
isOfType	1716671758	235.244	0.0	0.037	0.0
````

While the results differ between each other, they show 50.7% and 38.6% , which now starts to align with @SanderGielisse .

To be provide results with fix in place below.

**Comment by SanderGielisse** [comment]
@rnveach thank you for the thorough investigation. I can confirm your following setup is indeed almost identical to mine. I was indeed running it on all of Checkstyle.

> `-c ${workspace_loc}\checkstyle\src\main\resources\google_checks.xml ${workspace_loc}\checkstyle --executeIgnoredModules`

With regards to your timings, I ran the following two commands and obtain the following VisualVM plots;
`java -jar j_unfixed.jar -c ./google-checks.xml ./checkstyle --executeIgnoredModules`
![issue_unfixed](https://user-images.githubusercontent.com/4587552/156941183-df8cc6f4-bba9-4f43-ae7a-f13dd56b8c1b.png)

`java -jar j_fixed.jar -c ./google-checks.xml ./checkstyle --executeIgnoredModules`
![fixed](https://user-images.githubusercontent.com/4587552/156941186-95bd5702-8a80-4705-91a9-9d65d5b81b77.png)

Both run until they crash at the same point. Interestingly the time until the code reaches this point is 125 seconds for the stream version and 85 seconds for the naive version. The `isOfType` takes around 35% of total runtime in the stream version, while taking near 0% for the naive version (I will get to why this is just an approximation later).

With regards to your earlier message about any form of timer having to cause some kind of overhead, I believe the way VisualVM works is not to time every method. Instead, it 'probes' the running process many times per second to obtain exactly in which method the CPU execution is at that point in time. Methods that are more CPU intensive spend more time on the CPU and are thus more likely to be worked on whenever the sampler probes. This way, you get an average overview of which methods are most time consuming, without inducing any additional overhead. Using the naive function, the `isOfType` method does not even show up. This does not mean that it was not executed, it just means that from all the times the CPU was probed, it was never busy on the `isOfType` method. This is different from the stream implementation, where it was working on that quite often (thus spending more time on it on average), around 35% of the execution time (so 35% of all the probes resulted into `isOfType`).

You also mentioned that overhead for manual function timing would be a relative thing, but I think I disagree. Let's say the naive function takes 1 nanosecond while the stream version takes 10 nanoseconds. If the overhead for requesting system time, some additional method calls and possibly some other things is as little as 10 nanoseconds, the resulting timings will show 11 nanoseconds vs 21 nanoseconds, a seemingly factor 2 difference, while in fact the speed difference is a factor of 10.

Like I said, thank you for the thorough investigation. I think, and I feel like you agree, that in the general case of running Checkstyle on just the specified source files, the number of calls of `isOfType` is only a couple million and the long-term runtime difference between the implementations will be a couple of seconds at best on really large projects. However, I am unsure what causes the number of method calls to run into the order of billions (as with running Checkstyle on everything of Checkstyle). I think you have way more expertise with the actual specifics of Checkstyle, and thus I think your opinion on the importance of fixing this is key in considering this a valid issue or not. However, I personally do not see any disadvantages, and I believe any (even minor) performance increase that does not go at cost of readability or maintainability is a good thing, hence my PR :)

**Comment by rnveach** [comment]
I am sure we are going off topic of the prime issue, but I pinged @romani to look at this for approval.

====

I think you are misunderstanding relative.

If naturally its 11 nanos, but with mine its 21 nanos, then that is their relative values to each other (11 to 21). 11 without will be 21 with. So if we slowed down and it becomes 22 without, it should remain relative as 42 with. Now if with my process, it becomes 44 nanos, we can use the previous relative to determine without would be 23. We can still determine the percentage of this change (42 to 44), as it is still apples to apples comparison. 11 to 22, is double. 21 to 42 is double. 42 to 44 is the ratio 21 to 22.

All these relatives can be expressed as percentages. This is why I kept providing percentages (portion of view / full run time) and percentage of time changes. If my process increases 1 portions time, it will increases total run time relatively. These percentages is what remains relative.

>  it just means that from all the times the CPU was probed, it was never busy on the isOfType method

That would be the main difference then. Mine tries to account actual time spent everywhere, even if its as small as 1 nano, while VM does slices of time and can miss out on things. Eventually all these nanos, add up.

> the number of calls of isOfType is only a couple million and the long-term runtime difference between the implementations will be a couple of seconds at best on really large projects.

My real confusion is why calling it 2.7 million versus a 1.7 billion, again doesn't remain relative. I would expect to be a formula for one, and be able to calculate the other. My initial said 1%, but now I can show 30%, which is all relative to time and calls. It may just be something with the VM and how the code is generated and maintained in memory.

**Comment by SanderGielisse** [comment]
> I am sure we are going off topic of the prime issue
Haha, we absolutely are, but thank you for pinging.

I believe the problem is with your following statement:
> So if we slowed down and it becomes 22 without, it should remain relative as 42 with
The overhead from running timings is a constant factor, it is independent of the function you are measuring, i.e. this took 10 nano's in your example, so if your function becomes twice as slow, from 11 to 22, your timings will add a constant 10 nano's again and make you end up with 32 nano's measured. In your claim of 22 nano's 'without' becoming 42 nano's 'with', you are assuming the overhead of calling the time method etc also increased by a factor of two. This is not true.

**Comment by strkkk** [comment]
@SanderGielisse Can you please provide JMH metrics for current implementation and proposed solution?
I think this will answer all questions.

**Comment by SanderGielisse** [comment]
> @SanderGielisse Can you please provide JMH metrics for current implementation and proposed solution? I think it will answer all questions.

I have done so but I have no idea for what values of `types` and `type` to test. The numbers I get are not representative of the problem I encountered, but look more like the values that @rnveach found earlier, so around a factor 2 difference. While it's nice, it's more like a 1% overall speedup, rather than the 30% of my specific case (by running Checkstyle on all of Checkstyle using google checks, like before). However I think a free 1% at practically no cost is definitely something to consider.

Regarding the really slow case, I have the suspicion that it might have to do with some specific edge cases. I am not completely familiar with the implementation of `Arrays.stream(types).anyMatch` but I think it might be going over the entire array, copying it first to make it of non-primitive type `Integer` rather than `int`. The naive loop doesn't do so and just stops as soon as a matching value is found. For large `types` and the `type` being one of the first elements, I can see how the performance gap can grow to become something as significant as we saw in this second case.

**Comment by strkkk** [comment]
> I have done so but I have no idea for what values of types and type to test.

You can take all tokens and every time pick some random token to search.

Autoboxing to Integer can be an issue. I doubt that implementation makes a copy.

**Comment by romani** [comment]
I am approving issue, but we will see in PR exact change and exact measurement of improvement to see if it matter to do this.

**Comment by nick-mancuso** [comment]
@SanderGielisse are you able to share the project that you have been using for your analysis?

**Comment by SanderGielisse** [comment]
> @SanderGielisse are you able to share the project that you have been using for your analysis?

For all the experiments above I ran Checkstyle on all of Checkstyle using the Google checks, as such; `java -jar checkstyle_compiled.jar -c ./google-checks.xml ./checkstyle --executeIgnoredModules`

**Comment by romani** [comment]
Fix is merged
