### ISSUE TITLE
Conver test for SuppressionXpathSingleFilterTest to use inlined config in Input files

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#11439]
Detected at https://github.com/checkstyle/checkstyle/pull/11437/files

All filters should migrate to use config inlined in Input files.
Suppression that was left in that commit should be removed.

**Comment by Vyom-Yadav** [comment]
I am on it.

**Comment by Vyom-Yadav** [comment]
@romani I need some advice, suppose we have the following inline config
```
/*
SuppressionXpathSingleFilter
files = InputSuppressionXpathSingleFilter
checks = .*
message = (default)(null)
id = (default)(null)
query = //VARIABLE_DEF[./IDENT[@text='pi'] and ../../IDENT[@text='countTokens']] | //VARIABLE_DEF[./IDENT[@text='someVariable'] and ../../IDENT[@text='sum']]

*/
```
Now the query line is exceeding the mark of 100, there are two options to fix this-

1. Just add suppression for line length
2. Create some custom logic in parser to handle XPath queries, for eg, it should be able to parse this-
```
/*
SuppressionXpathSingleFilter
files = InputSuppressionXpathSingleFilter
checks = .*
message = (default)(null)
id = (default)(null)
query = (XpathQuery)(//VARIABLE_DEF[./IDENT[@text='pi'] and ../../IDENT[@text='countTokens']] | 
//VARIABLE_DEF[./IDENT[@text='someVariable'] and ../../IDENT[@text='sum']])

*/
```
It can handle multiline XPath queries, we surround the Xpath query by parentheses.

Both are doable, the first one being obviously the easier one. We can keep things simple by just suppressing or follow the style guidelines and develop custom logic.

**Comment by romani** [comment]
We already support line wrap, see example at long 'token' values.
