### ISSUE TITLE
refactoring to Main.java accounrding to ThrowCountCheck

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#1144]
https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/Main.java#L208

ThrowCountCheck limit is 2.

```
    private static int runCheckstyle(CliOptions cliOptions)
            throws CheckstyleException, UnsupportedEncodingException, FileNotFoundException {
```

please try to make it 
```
    private static int runCheckstyle(CliOptions cliOptions)
            throws CheckstyleException {
```

to clearly show that from Checkstyle execution user will return only CheckstyleException.

**Comment by mkordas** [comment]
Comment from #1083:
>"UnsupportedEncodingException, FileNotFoundException" is dues to loading of properties :(. Original idea of this method was to show how Checkstyle need to be initialized to work as embedded code, that is why I decided to use CliOptions class. It is method of main logic in whole Main class. After 2 days of thinking about this issue, i am ok to move properties load to "main" and have in CliOptions ready to use Property object. That will even show that "runCheckstyle" method will return one type of checked exception - CheckstyleException. 

I don't think the above is correct. These exceptions come from `com.puppycrawl.tools.checkstyle.Main#createListener`, not `com.puppycrawl.tools.checkstyle.Main#loadProperties`.

**Comment by romani** [comment]
right, but we still need to think how to make design more ideal of that methods.

**Comment by Bhavik3** [comment]
@romani 
Here, Whenever exception happen, we can surround with try-catch block and throw CheckstyleException(message).
like,
```
try {
     listener = new DefaultLogger(out, closeOut);
} catch (UnsupportedEncodingException e) {
     throw new CheckstyleException(e.getMessage(), e);
}
```

**Comment by romani** [comment]
we need to resolve a design problem but not a put HACKs in our code to satisfy/cheat validation tools.

just wrapping by try-catch is not enough.

**Comment by MEZk** [comment]
@romani 
Resolved in scope of https://github.com/checkstyle/checkstyle/pull/2034

**Comment by romani** [comment]
release in 6.11
