### ISSUE TITLE
JavadocMethod parses allowedAnnotations incorrectly

### ISSUE THREAD

**Issue by GustavCarlson** [checkstyle/checkstyle#1145]
According to its [documentation](http://checkstyle.sourceforge.net/config_javadoc.html#JavadocMethod), `allowedAnnotations` [is a `StringSet`](http://checkstyle.sourceforge.net/property_types.html#stringSet) (referred to as "list of strings") whose documentation states that "The string representation is parsed as a set of comma (',') separated strings.", but `JavadocMethodCheck#setAllowedAnnotations` actually splits the given argument on `", "` (comma + space), and also does not account for whitespace (e.g. line breaks, which may occur in XML attributes).

**Comment by romani** [comment]
merged. Thanks a lot !!!
