### ISSUE TITLE
Unit tests for Checkstyle GUI components

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#11475]
## Issue
Checkstyle has minimalist graphical interface, used by developers for troubleshooting and research purpose.
This feature is not important, and has no much support. There is no tests for GUI in Checkstyle (except for the model).
And there is a reason for this. GUI tests require a physical display and exclusive access to input interfaces.
As a result, it is possible to break the GUI after some refactoring. See #9004 for example.

## Idea
However, this can be done with [caciocavallo](https://github.com/CaciocavalloSilano/caciocavallo), a pure virtual AWT driver.
With Cacio, all GUI windows are invisible and untouchable. This means that we can use it in CI and on the developer's PC without distracting the user with unexpected pop-ups.

## Restrictions
- The behavior of AWT components depends on the toolkit. On Mac, Linux and Windows, anything may be different. And, of course, it will be something different for the virtual toolkit. So it is **impossible** to gain 100% coverage for GUI: we need, for example, some lines of Windows-specific code and such code can be tested only on Windows.
- Another restriction is *modal dialogs*: all of them should be *mocked* to prevent hanging of tests.

## Result
The goal of this issue is to set up initial configuration for GUI tests and write tests for some components to validate this approach.
The improvement of GUI coverage should be done in other issues.

**Comment by romani** [comment]
@pbludov , I presume we need to keep this issue to remove all excludes on gui classes.

Better to create new issue with more details on how exactly do updates what is left to fo

**Comment by pbludov** [comment]
Nick is working on #11482 right now. We should merge it. Then it will be possible to calculate the coverage %.

**Comment by pbludov** [comment]
Continuation of this issue will be done in #11514
