### ISSUE TITLE
Update doc for MethodLength

### ISSUE THREAD

**Issue by nick-mancuso** [checkstyle/checkstyle#11474]
https://checkstyle.org/config_sizes.html#MethodLength

Add example for each existing config to show what code is ok and what code cause violation.

A good example is https://checkstyle.org/config_naming.html#AbstractClassName.

Look at referenced commits of https://github.com/checkstyle/checkstyle/issues/5832, to see what and how should be changed in code.

Please play with module/check by means of https://checkstyle.org/cmdline.html to understand how it works.

PLEASE READ https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-examples

**Comment by nick-mancuso** [comment]
We should show in new examples that both block and single line comments are not counted in length of method when `countEmpty` is false.

**Comment by adekzs** [comment]
Can I work on this

**Comment by nick-mancuso** [comment]
Sure, please leave a comment "I am on it", and send PR. Pay special attention to comment at https://github.com/checkstyle/checkstyle/issues/11474#issuecomment-1079951359 pertaining to changes made at https://github.com/checkstyle/checkstyle/pull/11312

**Comment by adekzs** [comment]
I am on it

**Comment by Shaman20** [comment]
Can I work on this issue?

**Comment by romani** [comment]
No, there is already PR for this issue Issue https://github.com/checkstyle/checkstyle/pull/11523

**Comment by strkkk** [comment]
fix is merged
