### ISSUE TITLE
WhitespaceAfter should support LITERAL_YIELD token

### ISSUE THREAD

**Issue by turbanoff** [checkstyle/checkstyle#11508]
https://checkstyle.org/config_whitespace.html#WhitespaceAfter

I have downloaded the latest cli from: https://checkstyle.org/cmdline.html#Download_and_Run
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

**How it works Now:**

```bash
/var/tmp $ javac WithYield.java
/var/tmp $

/var/tmp $ cat config.xml
<!DOCTYPE module PUBLIC
        "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
        "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
<module name="Checker">
    <module name="TreeWalker">
        <module name="WhitespaceAfter">
            <property name="tokens" value="LITERAL_YIELD"/>
        </module>
    </module>
</module>

/var/tmp $ cat WithYield.java
public class WithYield {
    public static void main(String[] args) {
        int a = switch (args[0]) {
            case "got":
                yield 1;
            case "my":
                yield(3);
            default:
                yield 2;
        };
        System.out.println(a);
    }
}


/var/tmp $ RUN_LOCALE="-Duser.language=en -Duser.country=US"
/var/tmp $ java $RUN_LOCALE -jar checkstyle-10.1-all.jar -c config.xml WithYield.java
com.puppycrawl.tools.checkstyle.api.CheckstyleException: cannot initialize module TreeWalker - Token "LITERAL_YIELD" was not found in Acceptable tokens list in check com.puppycrawl.tools.checkstyle.checks.whitespace.WhitespaceAfterCheck
        at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:476)
        at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:201)
        at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:403)
        at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:330)
        at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:189)
        at com.puppycrawl.tools.checkstyle.Main.main(Main.java:126)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Token "LITERAL_YIELD" was not found in Acceptable tokens list in check com.puppycrawl.tools.checkstyle.checks.whitespace.WhitespaceAfterCheck
        at com.puppycrawl.tools.checkstyle.TreeWalker.registerCheck(TreeWalker.java:223)
        at com.puppycrawl.tools.checkstyle.TreeWalker.setupChild(TreeWalker.java:133)
        at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:201)
        at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:471)
        ... 5 more
Checkstyle ends with 1 errors.
```

**Is your feature request related to a problem? Please describe.**
It would be nice if checkstyle could detect missing space after `yield` keyword.

**Describe the solution you'd like**
WhitespaceAfter could support new literal type - `LITERAL_YIELD`

#11489, #11493 and #11494 are similar requests for `try`/`finally`/`synchronized` keywords support

**Comment by Binita-tech** [comment]
I am on it.

**Comment by Binita-tech** [comment]
```
public class InputWhitespaceAfterLiteralYield {
   public static void main(String[] args) {
     int a = switch (args[0]) {
       case "got":
         yield (1); // OK
       case "my":
         yield(3); // violation ''yield' is not followed by whitespace'
     };
   }
}
```
I am using above code in input file but I am getting this error- 
[ERROR]/C:/Users/Dell/OneDrive/Desktop/G_Checkstyle/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespaceafter/InputWhitespaceAfterLiteralYield.java:[12,14] switch expressions are not supported in -source 11
[ERROR]   (use -source 14 or higher to enable switch expressions)
I changed settings also but it didn't work
![image](https://user-images.githubusercontent.com/78761614/166798126-44f7c632-a47a-48b5-9874-11c8c52a8378.png)
Please guide.

**Comment by nick-mancuso** [comment]
You must put this input file in noncompilable test input folder. I find it helpful to work on these files separately in another editor window for syntax checking, etc.

**Comment by Binita-tech** [comment]
I made input file in resources-noncompilable folder like this-
![image](https://user-images.githubusercontent.com/78761614/167156793-f59c4521-7023-4bd9-b83d-ae78ba34a0e4.png)
Now, what should I do about below files as there is no file of InputWhitespaceAfterBad.java and  InputWhitespaceAfterGood.java in resources-noncompilable folder?
![image](https://user-images.githubusercontent.com/78761614/167157038-250db5cf-3f7e-4f30-a0fd-c3104efbd0e7.png)

**Comment by nick-mancuso** [comment]
@Binita-tech please send PR with check update and check test/ input update only, and we will go from there. Let’s not worry about Google style inputs for this token yet.
