### ISSUE TITLE
Split pitest-coding execution into two executions and investigate instability

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#11528]
pitest-coding is running too long in comparison to other and fails too often

we need stabilize it and make it quicker to execute.

I am open to any solutions.

related to https://github.com/checkstyle/checkstyle/issues/11427

**Comment by romani** [comment]
@Vyom-Yadav , can you help us with this ?

**Comment by Vyom-Yadav** [comment]
@romani Sure, I am on it.

**Comment by nick-mancuso** [comment]
Let’s make multiple PRs to close this issue. One for each instability, and then final PR to split execution.

**Comment by romani** [comment]
EqualsAvoidNullCheck is fixed, Requirethis still need to be fixed, but we moved it to temp suppression to allow CI be green.

**Comment by nick-mancuso** [comment]
@Vyom-Yadav ping, let's finish this up by splitting execution of pitest-coding so that we can achieve faster feedback loop in https://github.com/checkstyle/checkstyle/pull/11672

**Comment by nick-mancuso** [comment]
Closed via https://github.com/checkstyle/checkstyle/pull/11707
