### ISSUE TITLE
Fix methods for package-info file check

### ISSUE THREAD

**Issue by strkkk** [checkstyle/checkstyle#11531]
Current implementation of FileContents looks like
https://github.com/checkstyle/checkstyle/blob/5df2e3fdceabef4c8d269bac18e982ad11f4779d/src/main/java/com/puppycrawl/tools/checkstyle/api/FileContents.java#L332-L334

It will return true on inputs like `some-package-info.java`

It should be fixed. Also after https://github.com/checkstyle/checkstyle/pull/11502 replacement method CheckUtil#isPackageInfo should be fixed as well.

**Comment by adinayyu** [comment]
I am adithya from India and as part of gsoc 2022 i want to work on open jdk code convention coverage or reconcile formatters of ides project. I want to work on this issue to contribute to checkstyle. How to work on this issue and this is my first issue

**Comment by romani** [comment]
Please read https://github.com/checkstyle/checkstyle/wiki/To-GSoC-participant attentively, first, second, third issues are mandatory to fix first.

**Comment by adinayyu** [comment]
> Please read https://github.com/checkstyle/checkstyle/wiki/To-GSoC-participant attentively, first, second, third issues are mandatory to fix first.

Thanks for clarification sir

**Comment by strkkk** [comment]
Fix is merged
