### ISSUE TITLE
Add 'git diff' validation after execution of verify phase to Azure

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#11554]
detected at https://github.com/checkstyle/checkstyle/pull/11553

This is how it done in Travis:
https://github.com/checkstyle/checkstyle/blob/b09a9ce9d4f48c179f3d5647b6656e5737462656/.travis.yml#L127

we need to move this shell method to validation.sh as it become not specific to Travis and execute it in Azure as post build step after "mvn verify".

**Comment by romani** [comment]
Please make extra commit to show how in will work. Any changes in property description without update in xml file.

**Comment by Rahulkhinchi03** [comment]
@nick-mancuso @romani The PR is merged. Please close this issue.

**Comment by nick-mancuso** [comment]
Fix is merged.
