### ISSUE TITLE
Resolve IDEA violations from Teamcity 2022.04 (Bundled IntelliJ IDEA 2021.2.3)

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#11566]
Link to the report: https://teamcity.jetbrains.com/viewLog.html?buildId=3844938&tab=Inspection&buildTypeId=Checkstyle_IdeaInspectionsPullRequest#

Mostly **Grammar** and **http links**, but other violations should be fixed.

## General
* [ ] Redundant suppression (Errors) (12)
* [ ] Syntax error (Errors) (2)
## Java/Abstraction issues
* [ ] Private method only used from inner class (Errors) (1)
## Java/Code maturity
* [ ] Commented out code (2)
* [ ] Deprecated member is still used (2)
## Java/Code style issues
* [ ] 'if' statement can be replaced with conditional or boolean expression (Errors) (4)
## Java/Data flow
* [ ] Scope of variable is too broad (Errors) (2)
* [ ] Java/Java language level migration aids/Java 9
* [ ] Null check can be replaced with method call (4)
## Java/JUnit
* [ ] JUnit test method without any assertions (Errors) (8)
## Java/Memory
* [ ] Static collection (73)
## Java/Performance
* [ ] Call to 'set.removeAll(list)' may work slowly (2)
## Java/Probable bugs
* [ ] Result of method call ignored (1)
## Java/Threading issues
* [ ] 'synchronized' method (1)
## Java/Verbose or redundant code constructs
* [ ] Redundant String operation (2)
* [ ] Redundant usage of unmodifiable collection wrappers (2)
## JavaScript and TypeScript/Potentially undesirable code constructs
* [ ] Anonymous function (Errors) (7)
## Proofreading
* [ ] Grammar (379)
## RegExp
* [ ] Duplicate character in character class (2)
## Security
* [ ] Link with unencrypted protocol (64)
## YAML
* [ ] Validation by JSON Schema (10)

**Comment by romani** [comment]
To speed up green state, it might be good to disable some inspections until fix is provided.

**Comment by pbludov** [comment]
I'll try to fix all errors asap, warnings may be postponed.

**Comment by romani** [comment]
I asked TC support to install previous version , they installed 2020.1.1

I activated this version in master build only, build is started
https://teamcity.jetbrains.com/buildConfiguration/Checkstyle_IdeaInspectionsMaster/3847241?hideProblemsFromDependencies=false&hideTestsFromDependencies=false

**Comment by pbludov** [comment]
These violations:
* [AutoCloseable used without 'try'-with-resources (Errors) (23)](https://teamcity.jetbrains.com/viewLog.html?buildId=3847241&tab=Inspection&buildTypeId=Checkstyle_IdeaInspectionsMaster#)
* I/O resource opened but not safely closed (12)

are false positives and were fixed in the new version.

**Comment by romani** [comment]
>These violations:

Does it means that we use to has different idea inspection installed?
So ideally we should have version that was there before, so we can come back to 0 violations at least in master.

**Comment by pbludov** [comment]
> So ideally we should have version that was there before, so we can come back to 0 violations at least in master.

Yes. We can revert 2b2391d95136208a0d6a14f6fd5c610a3414683c and re-apply it later.

**Comment by romani** [comment]
It would help a lot if we had TC config in file

**Comment by romani** [comment]
I moved master build to new inspections version, we should fix by going forward as we are in the middle of updates and it might not easy to keep compatibility.

But I highly recommend to disable whole rules or put suppression quickly to gain green state asap, and deal with ideal solutions step by step.

**Comment by romani** [comment]
@pbludov , FYI
Downgrade to warn does not affect build status
https://github.com/checkstyle/checkstyle/commit/7e9943cfdeb1763131a229538f1ee24205f3559d#diff-ab946ffc43c4ac01e08c33ce3843b3f5bbc1d7e676b478f549a9372947ea0f15R653
We need to disable inspection.

**Comment by romani** [comment]
We still need to fix or disable grammar inspection
https://www.jetbrains.com/help/idea/grammar.html#rules

>Ensure that the [Grazie](https://plugins.jetbrains.com/plugin/12175-grazie) plugin is installed and enabled

I noticed this name in config file but didn't matched it to grammar

**Comment by romani** [comment]
Most items were fixed.
There are few suppression were introduced and will be resolved as separate issues.
