### ISSUE TITLE
Wercker service will be shutdown on October 31st, 2022

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#11564]
>Important Notice: Wercker service will be shutdown on October 31st, 2022 . We recommend you to use [OCI DevOps service](https://docs.oracle.com/en-us/iaas/Content/devops/using/getting_started.htm). Thank you for using Wercker.
Note: [OCI DevOps](https://www.oracle.com/devops/devops-service/) doesn't have a free build resource for free-tier "always free" account types; if you migrate to OCIDevOps, you will need a paid Oracle Cloud account. You can upgrade to a paid Oracle Cloud account by adding a payment method. OCI offers "Pay As You Go" if your usage is small. For larger accounts, please contact one of our Oracle [Sales](https://cloud.oracle.com/account-management/payment-method) team members for assistance.

We need to migrate off Wercker and disable Wercker.
in all repos.

**Comment by Rahulkhinchi03** [comment]
@romani I would like to work on it. Please guide me on how to resolve this issue?

**Comment by romani** [comment]
Remove https://github.com/checkstyle/checkstyle/blob/master/wercker.yml file.

**Comment by rnveach** [comment]
https://github.com/checkstyle/checkstyle/blob/master/.ci/wercker.sh should also be moved to other files. Shell scripts should avoid being CI specific unless it is truly something that can only be done on that CI, which should be rare.

**Comment by romani** [comment]
https://github.com/checkstyle/checkstyle/blob/master/.ci/wercker.sh already empty, just need to be removed

**Comment by Rahulkhinchi03** [comment]
@romani Is it the only way to move execution? Why can't we use SonarQube (https://www.sonarqube.org/)

**Comment by Rahulkhinchi03** [comment]
@romani When moving the execution. What can we use instead of `WERCKER_CACHE_DIR` in Travis Ci?

**Comment by romani** [comment]
@Rahulkhinchi03 , wercker has no verification jobs now, we moved all out in last long instability on wercker.

https://app.wercker.com/checkstyle/checkstyle/runs/build/628a8f8f5014f50008570d7b

Please remove wercker.yml and wercker.sh and badge from readme.
Please recheck other sources files to make sure nothing is pointing to wercker.

I am removing checkstyle app in wercker web UI.

**Comment by Rahulkhinchi03** [comment]
`pitest.sh` uses this comment as `# Attention, there is no "-x" to avoid problems on Wercker`

`validation.sh`  is extensively used `projects-for-wercker.properties.`

`validation.sh` ( sonarqube job uses wercker in comment as ):
```
# executed only in wercker for security reasons

  # SONAR_TOKEN=xxxxxx ./.ci/wercker.sh sonarqube
  # SONAR_TOKEN=xxxxxx PR=xxxxxx WERCKER_GIT_BRANCH=xxxxxx ./.ci/wercker.sh sonarqube
```

Only these 2 .sh files uses wercker in comment and its property file. Should I have to refactor all the comment and use Travis CI instead of wercker.

projects-for-wercker.properties Should I have to replace this file too?

**Comment by romani** [comment]
>pitest.sh uses this commen

Change comment to circleci. Same problem on all CIs.

>validation.sh is extensively used projects-for-wercker.properties

Rename property file or combine content to other file that is used in validation.sh

Sonar already moved to GitHub actions
