### ISSUE TITLE
Java8 try resource indent failed

### ISSUE THREAD

**Issue by longtai-cn** [checkstyle/checkstyle#11562]
I have read check documentation: https://checkstyle.org/config_xxxxxx.html#NameOfAffectedCheck
I have downloaded the latest checkstyle from: https://checkstyle.org/cmdline.html#Download_and_Run
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

> Sorry, I can't use the latest version because of the Java version. The following program is based on ` checkstyle-8.45.1-all Jar ` demo

```bash
/var/tmp $ javac Test.java
SUCCESSFUL COMPILATION]

/var/tmp $ cat config.xml
<?xml version="1.0"?>

<!DOCTYPE module PUBLIC "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
        "http://checkstyle.sourceforge.net/dtds/configuration_1_3.dtd">
<module name="Checker">
    <module name="TreeWalker">
        <module name="Indentation">
            <property name="lineWrappingIndentation" value="8"/>
        </module>
    </module>
</module>

/var/tmp $ cat Test.java
import java.io.InputStreamReader;

public class Test {

    public static void main(String[] args) {
        try (InputStreamReader reader = new InputStreamReader(System.in);
             InputStreamReader reader1 = new InputStreamReader(System.in)) {
            // try block...
        } catch (Exception e) {
            // catch block...
        }
    }
}

/var/tmp $ RUN_LOCALE="-Duser.language=en -Duser.country=US"
/var/tmp $ java $RUN_LOCALE -jar  checkstyle-8.45.1-all.jar -c config.xml Test.java
Starting audit...
[ERROR] /Users/single/checkstyle/Test.java:7:14: 'try resource' has incorrect indentation level 13, expected level should be 16. [Indentation]
Audit done.
Checkstyle ends with 1 errors.
```

---

**Describe what you expect in detail.**

The indentation of the second line in the try is formatted by the default of idea, which violates the rules of 'checkstyle'. How can I be compatible

**Comment by romani** [comment]
>checkstyle-8.45.1-all

We do not support old version .
Please read https://checkstyle.org/cmdline.html#Download_and_Run and run on latest.

**Comment by longtai-cn** [comment]
@romani Thank you very much for your reply, I changed the indentation and the problem is solved.
