### ISSUE TITLE
Resolve SimplifiableIfStatement inspection violations 

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#11588]
Taken from https://github.com/checkstyle/checkstyle/issues/11566

see commit: https://github.com/checkstyle/checkstyle/commit/009cffaae0f1bd79f5c0084f5354f45ed391e346

we need to revert suppression of SimplifiableIfStatement or explain why they should be permanent.

**Comment by nick-mancuso** [comment]
On it
