### ISSUE TITLE
SuppressWarningsHolder reports violations with incorrect messages

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#1158]
Sample report: http://mkordas.github.io/suppress-warnings-holder/checkstyle.html

1. Translations are missing for `suppress.warnings.invalid.target` and `suppress.warnings.missing.value`
2. Should this check report as warning that target is invalid? Should the list of targets be extended?
3. Should this check report empty SuppressWarnings annotation?

**Comment by romani** [comment]
1) human messages should be added for both cases
2) target list need to be extended, in java8 it even more wide, we need to review all inputs for annotations that we  introduced for java8 and change them to SuppressWarnings base on that results new issues could be created
3) no, if user need that, it should be caught by separare Check, i think we have such Check in sevntu - RequiredParameterForAnnotationCheck

**Comment by mkordas** [comment]
Re 1) - is just English enough or should I translate messages to other languages too?

**Comment by romani** [comment]
Only english (root locale)

**Comment by romani** [comment]
@mkordas , I reassigned that issue to @Vladlis to speedup fix.
