### ISSUE TITLE
Report problem to IDEA issue tracker 

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#11594]
~Unfortunate false positive from inspection
https://github.com/checkstyle/checkstyle/commit/e892be80ddd3c82f03d153d51b680f2db1f2cfc9#diff-d30b04994870dfa6d43e4095694af6af2938eeddb1f2c0db3ddd55956bfdc10cR51~

Request option to ignore usage in  tests https://github.com/checkstyle/checkstyle/commit/e892be80ddd3c82f03d153d51b680f2db1f2cfc9#diff-efcf78d0957b14212cbef50a335aac82c9820f9a7956d2a57f74bddbed6edd2eR142

REPORTED: https://youtrack.jetbrains.com/issue/IDEA-293684/

We need to report them to jetbrains team

**Comment by nick-mancuso** [comment]
https://github.com/checkstyle/checkstyle/commit/e892be80ddd3c82f03d153d51b680f2db1f2cfc9#diff-d30b04994870dfa6d43e4095694af6af2938eeddb1f2c0db3ddd55956bfdc10cR51 is not a false posittive, as `List.copyOf` returns an immutable list.

**Comment by romani** [comment]
I do not see this method in javadoc, hmm

**Comment by romani** [comment]
> remove suppression

done - https://github.com/checkstyle/checkstyle/commit/f7f6bed9db2e0107b6a67c369d02e672d49921fe
