### ISSUE TITLE
PMD ExceptionAsFlowControl: Do not use exceptions as flow control to create objects in PackageObjectFactory

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#1159]
To instantiate each module in Checkstyle multiple exceptions are thrown:
* https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/PackageObjectFactory.java#L90
* https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/PackageObjectFactory.java#L142

This should be refactored to not use exceptions.

**Comment by romani** [comment]
original problem was at line 142, from original issue
```
com.puppycrawl.tools.checkstyle.PackageObjectFactory:142 Rule:ExceptionAsFlowControl Priority:3 Avoid using exceptions as flow control..
com.puppycrawl.tools.checkstyle.PackageObjectFactory:147 Rule:ExceptionAsFlowControl Priority:3 Avoid using exceptions as flow control..
```

@mkordas , What is a problem in line 42 ?

**Comment by romani** [comment]
> void addPackage(String packageName)

should be removed as it is used only in UTs.

> public Object createModule(String name)

should be moved to the top of Class, below c-tor

> createModule(String name) and doMakeObject(String name)

are the same form method that try one creation and the another, we need to create method createObjectWithIgnoringProblems(String name, Set<String> secondAttempt) that will do 
it will be used as
createObjectWithIgnoringProblems(name, Set.of(name + "Check"))
createObjectWithIgnoringProblems(name, getAllPossibleNames(packages, name))

> throw new CheckstyleException

All that throws should be removed from code is sequence of IF for NULL should be used. The only place there throws could stay is public method (but even that could be changed, as it is not API). 

> throw new CheckstyleException("Unable to instantiate " + name);

I do not remember an issue , but I already had a request to provide there all names that we used to match class.

> private Object createObject(String className)

should just a swallow exception and do logging, no wrapping is required.

**Comment by romani** [comment]
for this rule we have an suppression - https://github.com/checkstyle/checkstyle/blob/master/config/pmd.xml#L220

@mkordas , do you have ideas how to make code to pass a Rule, if no ideas , lets close this issue and put description comment to configuration.

**Comment by mkordas** [comment]
I will look into it during the weekend. I'm sure we can do something about it.

**Comment by mkordas** [comment]
For now I need to park this issue. Anyone can take over.

**Comment by romani** [comment]
fix is merged.
