### ISSUE TITLE
IndentationCheck works incorrectly for fluent method calls

### ISSUE THREAD

**Issue by krzyk** [checkstyle/checkstyle#116]
Example:

``` java
1:        new String()
2:            .substring(
3:                0, 100
4:            )
5:            .substring(
6:                0, 50
7:            );
```

The above code (with default settings of IndentationCheck) warns that:
`method call rparen at indentation level 12 not at correct indentation, 8 (IndentationCheck)` on line 4.

So according to checkstyle this parentheses should be at the same indentation as `new String()`, but it doesn't have a problem with parentheses on line 7.

**Comment by jhyot** [comment]
Has there been a regression? Exactly the testcase from https://github.com/checkstyle/checkstyle/issues/116#issuecomment-38412959 does not work with checkstyle 7.1.1.

Could it have something to do with #3208?

**Comment by ati90ati** [comment]
Hello,
I'm using checkstyle 8.14 and the issue is still there. Any news / ideas?

        <module name="Indentation">
            <property name="lineWrappingIndentation" value="8"/>
        </module>

        assertThat(result).hasSize(2)
                .extracting(
                        MyDto::getField1,
                        MyDto::getField2,
                        MyDto::getField3)
                .containsOnly(     // <- this is at level 16
                        tuple(ID_1, expectedField2, expectedField3),
                        tuple(ID_2, expectedField2, expectedField3)
                );          // <- 'method call rparen' has incorrect indentation level 16, expected level should be 8. [Indentation]

NOTE: `assertThat` is from `assertj-core` library.

**Comment by romani** [comment]
Create new issue, please recheck existing issues on this check

**Comment by ati90ati** [comment]
Added issue: https://github.com/checkstyle/checkstyle/issues/6210
