### ISSUE TITLE
There are semantic problems in the Chinese error message of keyword `design.forExtension` .

### ISSUE THREAD

**Issue by ssquan** [checkstyle/checkstyle#11649]
Here is the error report:

```bash
[ERROR] XXX.java:[15,1] (design) DesignForExtension: 類 'XXX' 看起來像是為擴展設計的（可以是子類），但方法 'badmethod' 沒有javadoc，解釋瞭如何安全地執行。如果類不是為擴展而設計的，請考慮創建類 'Application' final或使方法 'badmethod' static/final/abstract/empty，或為方法添加允許的
```

---

There are semantic problems in the error message above. And it's in Traditional Chinese, not Simplified Chinese like the rest messages in file `messages_zh.properties`

This error message cloud be better:
` 方法 {} 可被子类重写且不是抽象方法或空方法，应为其添加 javadoc 说明，或将类 {} 设置为不可继承。`

---

**Comment by romani** [comment]
Please send Pull request to fix problems in wording.
Most wording were done by Google translate so human correction is appreciated. Non of mainteners knows Chinese.

If you see more problems just send us Pull request :).

**Comment by strkkk** [comment]
fix is merged
