### ISSUE TITLE
Support .editorconfig format configuration

### ISSUE THREAD

**Issue by astubbs** [checkstyle/checkstyle#11647]
http://editorconfig.org/ is becoming somewhat of a standard?

Support for using .editorconfig configuration file for the formatting would be great.

**Comment by romani** [comment]
CheckStyle is not a formatter, yes we have bunch of formatting related modules, but it not a goal of our project.

If community wants to make .editorconfig that covers Google style formatting portion, I am ok to host it at https://github.com/checkstyle/contribution . Please create issue there and send PR.
