### ISSUE TITLE
New RegexpSinglelineJava property ignoreStrings/ignoreTextBlocks

### ISSUE THREAD

**Issue by solomax** [checkstyle/checkstyle#11653]
Similar idea discussed at https://github.com/checkstyle/checkstyle/issues/1405

https://checkstyle.org/config_regexp.html#RegexpSinglelineJava

```
java --version
openjdk 17.0.3     2022-04-19
OpenJDK Runtime Environment (build 17.0.3+7-Ubuntu-0ubuntu0.22.04.1)
OpenJDK 64-Bit Server VM (build 17.0.3+7-Ubuntu-0ubuntu0.22.04.1, mixed mode, sharing)
```

```bash
/var/tmp $ javac Test.java
#[[COMPILATION IS SUCCESSFUL]]

/var/tmp $ cat checkstyle.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
		"-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
		"https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name="Checker">
	<property name="fileExtensions" value="java,js,css,xml"/>
	<module name="TreeWalker">
		<module name="RegexpSinglelineJava">
			<property name="id" value="tabs-only"/>
			<property name="format" value="^\t* "/>
			<property name="message" value="Indent must use tab characters"/>
			<property name="ignoreComments" value="true"/>
		</module>
	</module>
</module>

# attention: tabs characters are used, copy code from edit mode
/var/tmp $ cat Test.java
public class Test {
	private static String test = """
		{
		  "health": {
		    "inited": true,
		    "installed": true,
		    "dbOk": true
		  }
		}""";

	public static void main(String[] args) {
		System.out.println(test);
	}
}

/var/tmp $ java -Duser.language=en -Duser.country=US -jar ../checkstyle-10.2-all.jar -c checkstyle.xml Test.java
Starting audit...
[ERROR] /home/solomax/work/tmp/checkstyle/11653/Test.java:4: Indent must use tab characters [tabs-only]
[ERROR] /home/solomax/work/tmp/checkstyle/11653/Test.java:5: Indent must use tab characters [tabs-only]
[ERROR] /home/solomax/work/tmp/checkstyle/11653/Test.java:6: Indent must use tab characters [tabs-only]
[ERROR] /home/solomax/work/tmp/checkstyle/11653/Test.java:7: Indent must use tab characters [tabs-only]
[ERROR] /home/solomax/work/tmp/checkstyle/11653/Test.java:8: Indent must use tab characters [tabs-only]
Audit done.
Checkstyle ends with 5 errors.
```

**Is your feature request related to a problem? Please describe.**
Checkstyle should report no issues since all leading spaces inside `text block` are "removed" remaining white-spaces are not code and might follow it's own rules

**Describe the solution you'd like**
I would be happy with

- dedicated check for tab-indentation
- special option for `RegexpSinglelineJava` to ignore strings/text block

```bash
Starting audit...
Audit done.
```

**Comment by romani** [comment]
Please strictly follow issue template. It will guide you on all aspects that matters for us to approve issue

**Comment by solomax** [comment]
@romani I hope the updated description is clear enough and corresponds the rules :)

**Comment by romani** [comment]
Remove from config Checks other than RegexpSinglelineJava
Please add property "id" to RegexpSinglelineJava Checks to let violations be related to exact Check instances

**Comment by solomax** [comment]
@romani unfortunately I can't

> Please add property "id" to RegexpSinglelineJava Checks

`<module id="tabs-only" name="RegexpSinglelineJava">`
results:

```
com.puppycrawl.tools.checkstyle.api.CheckstyleException: unable to parse configuration stream - Attribute "id" must be declared for element type "module".:9:54
	at com.puppycrawl.tools.checkstyle.ConfigurationLoader.loadConfiguration(ConfigurationLoader.java:322)
	at com.puppycrawl.tools.checkstyle.ConfigurationLoader.loadConfiguration(ConfigurationLoader.java:267)
	at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:372)
	at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:330)
	at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:189)
	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:126)
Caused by: org.xml.sax.SAXParseException; systemId: file:/home/solomax/work/tmp/checkstyle/11653/checkstyle.xml; lineNumber: 9; columnNumber: 54; Attribute "id" must be declared for element type "module".
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:204)
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:135)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:396)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:284)
	at java.xml/com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.addDTDDefaultAttrsAndValidate(XMLDTDValidator.java:1237)
	at java.xml/com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.handleStartElement(XMLDTDValidator.java:1846)
	at java.xml/com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.startElement(XMLDTDValidator.java:728)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1407)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2726)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:542)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:889)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:825)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1224)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:637)
	at com.puppycrawl.tools.checkstyle.XmlLoader.parseInputSource(XmlLoader.java:79)
	at com.puppycrawl.tools.checkstyle.ConfigurationLoader.parseInputSource(ConfigurationLoader.java:198)
	at com.puppycrawl.tools.checkstyle.ConfigurationLoader.loadConfiguration(ConfigurationLoader.java:315)
	... 5 more
Checkstyle ends with 1 errors.

```

**Comment by romani** [comment]
Please read https://checkstyle.org/config.html#Id

**Comment by solomax** [comment]
Done!
sorry @romani mis-read your comment :(

**Comment by solomax** [comment]
Hello @strkkk,
Thanks for the answer!
Could you please give an example of "negative lookahead"?

**Comment by strkkk** [comment]
```
^(?!(.*href=|.*http(s)?:|import |(.* )?package |.* files=|.*\.dtd| \* \{@code| \* com\.)).{101,}$
```
this, for example. This is line from checkstyle config. Its purpose is to check that line does not contain some excluded stuff

**Comment by solomax** [comment]
I'm not sure what to exclude :(

The rule should check all file are indented with tabs, not spaces
Multi line text blocks can break this rule
The example in the description is equivalent to
```
	private static String test = "{\n" +
		"  \"health\": {\n" +
		"    \"inited\": true,\n" +
		"    \"installed\": true,\n" +
		"    \"dbOk\": true\n" +
		"  }\n" +
		"}";
```

please NOTE the spaces inside the strings

could you please provide the "exclusion" example for the text from description?
The text shouldn't be JSON, it can be arbitrary multi line text BTW :(

**Comment by strkkk** [comment]
like this?
`^ +` 

I suggest to use any online regex validator to check what fits your usecases

**Comment by nick-mancuso** [comment]
We would require some property for this request that checks if we are in/ on line with `TEXT_BLOCK_CONTENT` token (excluding line with initial triple quote delimiter).

**Comment by solomax** [comment]
@strkkk the idea of this regex is to check source code is indented with tabs, as far as I see your regex will make this check useless (I can get the same effect by removing the check completely ...)

> If tabs exist in the source code, they should be flagged regardless of the context

The idea is to have indentation with tabs :) not spaces
the spaces ARE flagged, but they shouldn't since they are part of the string

**Comment by nick-mancuso** [comment]
@solomax thanks for clearing that up; however, the same principle applies. IMO, this seems like something that should be handled as a pre-commit hook, instead of mixing tabs and spaces in the same file. 

That said, it seems like a reasonable request to have some way to suppress checking for regex in text block content, due to the nature of what they may contain compared to a string literal.

**Comment by solomax** [comment]
@nick-mancuso I would agree BUT :)
this mixture is "by-design" and caused by text-block content

I'd love to see support of "suppress checking for regex in text block content" :)

**Comment by solomax** [comment]
Any chances this might be implemented in nearest future? :)
Shall I ping here or just wait? :)

**Comment by romani** [comment]
Sorry for delay, there is high volume of activities for GSOC, your issue is not forgotten.

**Comment by romani** [comment]
I can not find history of this Check.
It is not clear why we need this check and what is purpose of it, what is difference with RegexpSingleLine. 
It is not ast aware Check unfortunately. All violations are not AST specific.

It might that somebody created such check due to lack of filtering out file by extension in RegexpSingleLine , but this check has it https://checkstyle.org/config_regexp.html#RegexpSingleline_Properties

I have doubt that. It makes sense to extend this Check, it will be very hacky.

I think creation if new Check is more beneficial.

**Comment by solomax** [comment]
Thanks for the answer @romani :)
new check is OK with me :)
Can't wait to test it :)

**Comment by romani** [comment]
Do you have time to make it yourself ?
We can host it in https://github.com/sevntu-checkstyle/sevntu.checkstyle there we are less demanding for design and quality,  so you can create something that works for you.

No matter what it is topic of separate issue

**Comment by nick-mancuso** [comment]
@solomax a good way to suppress such violations would be to use `SuppressWithPlainTextCommentFilter`:


```
➜  java git:(master) ✗ cat config.xml 
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="fileExtensions" value="java,js,css,xml"/>
    <module name="SuppressWithPlainTextCommentFilter">
        <property name="offCommentFormat" value='"""'/>
        <property name="onCommentFormat" value='""";'/>
    </module>
    <module name="TreeWalker">
        <module name="RegexpSinglelineJava">
            <property name="id" value="tabs-only"/>
            <property name="format" value="^\t* "/>
            <property name="message" value="Indent must use tab characters"/>
            <property name="ignoreComments" value="true"/>
        </module>
    </module>
</module>

➜  java git:(master) ✗ cat Test.java 
public class Test {
    private static String test = """
                {
                  "health": {
                    "inited": true,
                    "installed": true,
                    "dbOk": true
                  }
                }""";

    public static void main(String[] args) {
        System.out.println(test);
    }
}

➜  java git:(master) ✗ java -jar checkstyle-10.3.1-all.jar -c config.xml Test.java
Starting audit...
Audit done.


```

**Comment by nick-mancuso** [comment]
@solomax suppression for content of text blocks can be achieved with `SuppressWithPlainTextCommentFilter`:

```
➜  java git:(master) ✗ cat config.xml 
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="fileExtensions" value="java,js,css,xml"/>
    <module name="LineLength">
        <property name="max" value="100"/>
    </module>
    <module name="SuppressWithPlainTextCommentFilter">
        <property name="offCommentFormat" value='=\s+"""'/>
        <property name="onCommentFormat" value='^\s+.*""";'/>
    </module>
    <module name="TreeWalker">
        <module name="RegexpSinglelineJava">
            <property name="id" value="tabs-only"/>
            <property name="format" value="^\t* "/>
            <property name="message" value="Indent must use tab characters"/>
            <property name="ignoreComments" value="true"/>
        </module>
    </module>
</module>

➜  java git:(master) ✗ cat Test.java 
public class Test {
    private static String test = """
                {
                  "health": {
                    "inited": true,
                    "installed": true,
                    "dbOk": true
                  }
                }""";

    public static void main(String[] args) {
        System.out.println(test);
    }
}

➜  java git:(master) ✗ java -jar checkstyle-10.3.1-all.jar -c config.xml Test.java
Starting audit...
[ERROR] /home/nick/IdeaProjects/Tester/src/main/java/Test.java:11: Indent must use tab characters [tabs-only]
[ERROR] /home/nick/IdeaProjects/Tester/src/main/java/Test.java:12: Indent must use tab characters [tabs-only]
[ERROR] /home/nick/IdeaProjects/Tester/src/main/java/Test.java:13: Indent must use tab characters [tabs-only]
Audit done.
Checkstyle ends with 3 errors.


```

**Comment by solomax** [comment]
Many thanks @nick-mancuso!
will try it ASAP :)

**Comment by nick-mancuso** [comment]
@solomax if this works well for your team, let us know and we will make an issue to extend the documentation of SuppressWithPlainTextCommentFilter to include text block usage.

**Comment by solomax** [comment]
Unfortunately I'm getting 
```
Failed during checkstyle configuration: unable to parse configuration stream - Element type "property" must be followed by either attribute specifications, ">" or "/>".:7:98
```
It is definitely due to `SuppressWithPlainTextCommentFilter`  module

Is there any way to turn on some sort of debug?
`-X` provides no valuable info :(

this is maybe because I'm using checkstyle config in the pom

**Comment by solomax** [comment]
@nick-mancuso triple check those :(
escaped `"` with `&quot;`
tried to rewrite regexp with `[\t ]+`
no luck :((

will try to debug :(

**Comment by solomax** [comment]
Finally made it :)))

for the `checkstyle.xml` inside `pom.xml` the rule should look like:

```
<module name="SuppressWithPlainTextCommentFilter">
	<property name="offCommentFormat" value="[=+](\s+)&amp;quot;&amp;quot;&amp;quot;"/>
	<property name="onCommentFormat" value="^\s+.*&amp;quot;&amp;quot;&amp;quot;;"/>
</module>
```

Thanks a million for your hints :)

**Comment by lrozenblyum** [comment]
> [@solomax](https://github.com/solomax) suppression for content of text blocks can be achieved with `SuppressWithPlainTextCommentFilter`:
> 
> ```
> ➜  java git:(master) ✗ cat config.xml 
> <?xml version="1.0"?>
> <!DOCTYPE module PUBLIC
>         "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
>         "https://checkstyle.org/dtds/configuration_1_3.dtd">
> 
> <module name="Checker">
>     <property name="fileExtensions" value="java,js,css,xml"/>
>     <module name="LineLength">
>         <property name="max" value="100"/>
>     </module>
>     <module name="SuppressWithPlainTextCommentFilter">
>         <property name="offCommentFormat" value='=\s+"""'/>
>         <property name="onCommentFormat" value='^\s+.*""";'/>
>     </module>
>     <module name="TreeWalker">
>         <module name="RegexpSinglelineJava">
>             <property name="id" value="tabs-only"/>
>             <property name="format" value="^\t* "/>
>             <property name="message" value="Indent must use tab characters"/>
>             <property name="ignoreComments" value="true"/>
>         </module>
>     </module>
> </module>
> 
> ➜  java git:(master) ✗ cat Test.java 
> public class Test {
>     private static String test = """
>                 {
>                   "health": {
>                     "inited": true,
>                     "installed": true,
>                     "dbOk": true
>                   }
>                 }""";
> 
>     public static void main(String[] args) {
>         System.out.println(test);
>     }
> }
> 
> ➜  java git:(master) ✗ java -jar checkstyle-10.3.1-all.jar -c config.xml Test.java
> Starting audit...
> [ERROR] /home/nick/IdeaProjects/Tester/src/main/java/Test.java:11: Indent must use tab characters [tabs-only]
> [ERROR] /home/nick/IdeaProjects/Tester/src/main/java/Test.java:12: Indent must use tab characters [tabs-only]
> [ERROR] /home/nick/IdeaProjects/Tester/src/main/java/Test.java:13: Indent must use tab characters [tabs-only]
> Audit done.
> Checkstyle ends with 3 errors.
> ```

it works indeed. Yet if the text block ends not with semicolon but for example with concatenation we'll have an issue that the whole next file content is Checkstyle-ignored.

**Comment by romani** [comment]
Validation by Regexp is always error prone.
If you need something robust, please, you need new module implementation that does what you need.
