### ISSUE TITLE
New Check: non-ASCII characters in source files

### ISSUE THREAD

**Issue by msteiger** [checkstyle/checkstyle#1165]
Some tools are not able to deal with non-ASCII files properly or recognize the encoding. For example not specifying the correct encoding in `javac` can cause problems.

I think that it is rarely useful or even necessary to use these characters in source code files. An exception to that rule could be (javadoc) comments in a different language than English.

Thus, I suggest adding a check for ASCII characters where only the lower 7 bits are used and chars 0x80 to 0xFF are invalid.

 Grep can list lines with invalid characters (recursive, java files only, write line number, use Perl regex):
```bash
grep -r --include "*.java" -n -P "[\x80-\xFF]" 
```

I think it would be useful to have this as a proper CheckStyle rule.

**Comment by romani** [comment]
Can our Regexp Check help you to do that ?

We are at moratorium period for new Checks for now, all new Checks should go to sandbox/experimental project sevntu.checkstyle .

**Comment by mkordas** [comment]
RegexpSinglelineJava does that easily, please see #1186. The question is if we want to wrap it to separate check or just extend documentation for Regexp check with 'suggested' patterns?

**Comment by romani** [comment]
I doubt that all of us will benefit with special Check for that, http://checkstyle.sourceforge.net/config_regexp.html#RegexpSingleline check  (not only RegexpSinglelineJava) will do that .
