### ISSUE TITLE
Add an option to specify legal pattern for RegexpSinglelineJava

### ISSUE THREAD

**Issue by krichter722** [checkstyle/checkstyle#1166]
Negating regex pattern in java is painful and the absence of an easy way to do that is definitely a large design error in the `java.util.regex` package. Therefore it'd be nice to be able to specify a legal pattern instead of an illegal pattern to `RegexpSinglelineJava` in order to overcome this java shortcoming easily.

**Comment by romani** [comment]
what behavior you expect if illegalPatern state FALSE and legalPattern state TRUE (both patterns are specified) ?

**Comment by krichter722** [comment]
They should be exclusive.

**Comment by romani** [comment]
please provide examples (not one example) of "legal" usage , I still do not see a real useful use-case for that.

**Comment by romani** [comment]
@krichter722 ,

please provide requested information and examples.
If now information provided in 2 weeks , I will close issue as incomplete.

**Comment by romani** [comment]
I am closing issue for now, if smb come-up with examples we will reopen it.
