### ISSUE TITLE
Investigate incorrect cobertura code coverage 

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#1167]
Assigned: @MEZk 

cobertura show non covered lines of code at ExecutableStatementCountCheck that definitely executed during UTs.
We need to open issue against cobertura about this.
We need to try substitute cobertura maven plugin with jacoco maven plugin

**Comment by mkordas** [comment]
I don't have this problem locally:
![image](https://cloud.githubusercontent.com/assets/5467276/7991972/48f770a2-0afc-11e5-904f-1a77d474c714.png)

Have you tried executing `clean cobertura:cobertura`?

**Comment by romani** [comment]
sorry , that was my mistake, I just tried to move private email conversation be public.

problem is at MethodCountCheck . that is the only exclusion left after task for whole package coverage is fixed - https://github.com/checkstyle/checkstyle/blob/master/pom.xml#L854

**Comment by MEZk** [comment]
@mkordas 
cobertura reports 28% line coverage and 31% branch coverage on MethodCountCheck, whereas eclemma plugin for Eclipse and JaCoCo plugin for IDEA report 100% coverage. I've already tried to invoke setters directly in UT but results remain the same. I'm working on this.

**Comment by mkordas** [comment]
@MEZk I have the solution already. It's bug in Cobertura. Workaround - instead of:
```java
            counters.push(new MethodCounter(
                TokenTypes.INTERFACE_DEF == ast.getType()));
```
it's enough to extract equality check to variable:
```java
            boolean inInterface = TokenTypes.INTERFACE_DEF == ast.getType();
            counters.push(new MethodCounter(inInterface));
```
I'll raise PR soon.

**Comment by MEZk** [comment]
@romani 
Can we exclude if statement? It is the last line that is reported uncovered by cobertura due to conditional coverage 50%.

```java
else if (TokenTypes.METHOD_DEF == ast.getType()) {
    raiseCounter(ast);
}
````

 We have already checked all acceptable tokens ( TokenTypes.CLASS_DEF, ENUM_CONSTANT_DEF, ENUM_DEF,  INTERFACE_DEF) for current check except METHOD_DEF in if statement 

````java
if (TokenTypes.CLASS_DEF == ast.getType()
 || TokenTypes.INTERFACE_DEF == ast.getType()
 || TokenTypes.ENUM_CONSTANT_DEF == ast.getType()
 || TokenTypes.ENUM_DEF == ast.getType()) {
````

**Comment by romani** [comment]
@MEZk 
yes, but testing on all projects with comparison of validation will be required, you already have bad experience of removing code that looks like dead :) .

@mkordas , please explain changes in UTs, am not expecting that, especially in extra "s" symbol.

**Comment by mkordas** [comment]
@romani, I've commited too much by mistake, should be fixed now.
04-06-2015 23:12 użytkownik "Roman Ivanov" <notifications@github.com>
napisał:

**Comment by mkordas** [comment]
@romani, I've commited too much by mistake, should be fixed now.

**Comment by romani** [comment]
I merged changes of mkordas, but I doubt that it will resolve problem with cobertura completely, and we will not be able to do workaround always. Jacoco is way better.

**Comment by MEZk** [comment]
@romani 
https://github.com/checkstyle/checkstyle/pull/1172

**Comment by romani** [comment]
I resolved cobertura problems on may local by appending "clean" to "compile", full command:
```mvn clean compile cobertura:cobertura```
