### ISSUE TITLE
Checkstyle doesn't publish test source code

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#11681]
Identified at https://github.com/rnveach/checkstyle-extras ,

I was expecting maven to bring in checkstyle's tests and it's respective sources so I could develop and debug issues that arise in checkstyle's core test code.

While tests is working, I noticed I could not view the source code of the tests, thus preventing proper debugging.

https://repo1.maven.org/maven2/com/puppycrawl/tools/checkstyle/10.3/
It seems there is no test sources in maven, while the test code itself is there. The only java files the test jar itself holds is the Input files, and none of the TestSupports or such.

I would the test sources to be published to properly debug the code and step through the source.

**Comment by rnveach** [comment]
This may help. https://stackoverflow.com/questions/53948780/maven-how-do-i-create-source-jar-for-test-package

**Comment by strkkk** [comment]
just curious - what is the point of publishing test code? Some users wanted to use it?

**Comment by romani** [comment]
IDEs will be able to download it and show sources if somebody try to debug their test that use our tests.

**Comment by pbludov** [comment]
Fix is merged.
