### ISSUE TITLE
Missed limitation: Checkstyle can't parse UTF8 Java File with UTF8 BOM

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#11698]
Identified at https://github.com/rnveach/checkstyle-extras when doing regression on XML on sevntu,

During review of XML regression and a parse error, it was identified sevntu had an XML file with an UTF8 BOM.
https://raw.githubusercontent.com/sevntu-checkstyle/sevntu.checkstyle/master/sevntu-checks/sevntu-checks.xml
https://en.wikipedia.org/wiki/Byte_order_mark#UTF-8

If it wasn't for the BOM, the file would parse correctly. In thinking over the solution for XML, it was identified that this issue also applies to Checkstyle and it's Java parsing.

Code to Construct and Show the case (UTF8 BOM is non-printable):
````
package com.puppycrawl.tools.checkstyle;

import java.io.BufferedWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;

public class CreateJavaBom {

    public static void main(String... args) throws IOException {
        try (BufferedWriter bw = Files.newBufferedWriter(Paths.get("M:\\JavaBOM.java"))) {
            bw.write("\ufeff"); // UTF8 BOM
            bw.write("public class TestClass {");
            bw.newLine();
            bw.write("    void method() {");
            bw.newLine();
            bw.write("    }");
            bw.newLine();
            bw.write("}");
            bw.newLine();
        }

        Main.main("-T", "M:\\JavaBOM.java");
    }

}
````

Output:
````
com.puppycrawl.tools.checkstyle.api.CheckstyleException: IllegalStateException occurred while parsing file M:\JavaBOM.java.
	at com.puppycrawl.tools.checkstyle.JavaParser.parse(JavaParser.java:105)
	at com.puppycrawl.tools.checkstyle.JavaParser.parseFileText(JavaParser.java:122)
	at com.puppycrawl.tools.checkstyle.JavaParser.parseFile(JavaParser.java:142)
	at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.printFileAst(AstTreeStringPrinter.java:65)
	at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:293)
	at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:189)
	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:126)
	at com.puppycrawl.tools.checkstyle.CreateJavaBom.main(CreateJavaBom.java:26)
Caused by: java.lang.IllegalStateException: 1:0: no viable alternative at input '﻿public'
	at com.puppycrawl.tools.checkstyle.JavaParser$CheckstyleErrorListener.syntaxError(JavaParser.java:255)
	at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
	at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:543)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportNoViableAlternative(DefaultErrorStrategy.java:310)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:136)
	at com.puppycrawl.tools.checkstyle.grammar.java.JavaLanguageParser.compilationUnit(JavaLanguageParser.java:424)
	at com.puppycrawl.tools.checkstyle.JavaParser.parse(JavaParser.java:99)
	... 7 more
Caused by: org.antlr.v4.runtime.NoViableAltException
	at org.antlr.v4.runtime.atn.ParserATNSimulator.noViableAlt(ParserATNSimulator.java:2028)
	at org.antlr.v4.runtime.atn.ParserATNSimulator.execATN(ParserATNSimulator.java:467)
	at org.antlr.v4.runtime.atn.ParserATNSimulator.adaptivePredict(ParserATNSimulator.java:393)
	at com.puppycrawl.tools.checkstyle.grammar.java.JavaLanguageParser.compilationUnit(JavaLanguageParser.java:380)
	... 8 more
Checkstyle ends with 1 errors.
````

Expected Output:
````
COMPILATION_UNIT -> COMPILATION_UNIT [1:0]
`--CLASS_DEF -> CLASS_DEF [1:0]
    |--MODIFIERS -> MODIFIERS [1:0]
    |  `--LITERAL_PUBLIC -> public [1:0]
    |--LITERAL_CLASS -> class [1:7]
    |--IDENT -> TestClass [1:13]
    `--OBJBLOCK -> OBJBLOCK [1:23]
        |--LCURLY -> { [1:23]
        |--METHOD_DEF -> METHOD_DEF [2:4]
        |  |--MODIFIERS -> MODIFIERS [2:4]
        |  |--TYPE -> TYPE [2:4]
        |  |  `--LITERAL_VOID -> void [2:4]
        |  |--IDENT -> method [2:9]
        |  |--LPAREN -> ( [2:15]
        |  |--PARAMETERS -> PARAMETERS [2:16]
        |  |--RPAREN -> ) [2:16]
        |  `--SLIST -> { [2:18]
        |      `--RCURLY -> } [3:4]
        `--RCURLY -> } [4:0]
````

While this shows the issue with `-T` for the command line, it is also seen in running with a configuration file, even with `<property name="charset" value="UTF-8"/>`.

I expect Checkstyle to be able to work with the file like it was any other file as Checkstyle is now suppose to support UTF8.

**Comment by romani** [comment]
Please show that javac can do compilation.

**Comment by rnveach** [comment]
Javac cannot compile a file with the BOM.
````
M:\>javac JavaBOM.java
JavaBOM.java:1: error: illegal character: '\u00bb'
∩╗┐
 ^
JavaBOM.java:1: error: illegal character: '\u00bf'
∩╗┐
  ^
2 errors
````

https://stackoverflow.com/questions/4897876/reading-utf-8-bom-marker/4897993#4897993
> In Java, you have to consume manually the UTF8 BOM if present. This behaviour is documented in the Java bug database, [here](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=4508058) and [here](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=6378911). There will be no fix for now because it will break existing tools like JavaDoc or XML parsers. The [Apache IO Commons](https://commons.apache.org/proper/commons-io/javadocs/api-release/org/apache/commons/io/input/BOMInputStream.html) provides a BOMInputStream to handle this situation.
>
> Take a look at this solution: [Handle UTF8 file with BOM](http://www.rgagnon.com/javadetails/java-handle-utf8-file-with-bom.html)

This explains why the BOM isn't removed even though we have the UTF8 charset set.

If we aren't going to do anything about the BOM for Java or even non-Java files, we should add this as one of our limitations to make it clear.
https://checkstyle.org/writingchecks.html#Limitations

**Comment by romani** [comment]
Java file is not compilable, why we need to add something else in limitations ?

**Comment by rnveach** [comment]
> It is a limitation that we don't support for non-Java files

Other files, like the one found for xml ignore the BOM. If you open the file in an editor or on GitHub you don't even notice the codes in there. It's not just because they are invisible but they are identified as a marker and they can't be removed or changed by normal means. If we are not going to treat the BOM as it is, it seems to me this makes it a no fix issue, or a limitation of the utility, similar we don't support Unicode escaped java code.

**Comment by romani** [comment]
For non java files we give whole content of file to Check, it should have all as is. If bom if it is present.

**Comment by nick-mancuso** [comment]
For Java files, I think our current docs do a good job of explaining what Checkstyle supports. I do not think we need to be any more nuanced in our philosophy or in our explanation in this case. If a file cannot be compiled by javac, there does not need to be further explanation IMO.

>For non java files we give whole content of file to Check, it should have all as is. With bom if it is present.

Agreed.

**Comment by romani** [comment]
I am to extend limitations wording if that clarify nuances. May be in PR it will be more clear.

**Comment by romani** [comment]
fix for doc is merged.
