### ISSUE TITLE
Adding More Labels to the Issue

### ISSUE THREAD

**Issue by Rahulkhinchi03** [checkstyle/checkstyle#11715]
Right now, checkstyle generally uses a `miscellaneous` label for the issues which are general.

Proposal:
We should introduce more `labels` for the issues so that it can make new contributors easy to find issues. By checking for `approved` and `miscellaneous`, it is sometimes overwhelming. 

We can introduce labels like:

- `Shell` ( for shell/bash script issues)
- `Pitest` (For Pitest related issues)
- Instead of GSoC First Issues, We can use `Good First Issues`

and many more.

The main aim of this issue is to focus on `specialization` instead of `generalization` to help contributors find it easy to contribute. 

@romani @rnveach @nick-mancuso @pbludov @strkkk @Vyom-Yadav, Would you please share your opinion?

**Comment by nick-mancuso** [comment]
@Rahulkhinchi03 please investigate impact this will have on release note generation, and propose how we will handle each label when we generate release notes.

**Comment by rnveach** [comment]
> make new contributors easy to find issues. By checking for approved and miscellaneous, it is sometimes overwhelming.

`misc` or other labels connected to release note generation usually do not get added to the issue until it is finished or already being worked. Those type of issues normally don't apply to new contributors.

**Comment by romani** [comment]
Labels does work for new contributors.

Labels required for mentors to group tickets and do release notes generation.

>Instead of GSoC First Issues, We can use Good First Issues

We have "easy" for long time, it never worked.

Gsoc first/second/.... are done for a reason and it works during specific time.
