### ISSUE TITLE
Disable IDEA Inspection for  `AnnotationClass` 

### ISSUE THREAD

**Issue by nick-mancuso** [checkstyle/checkstyle#11710]
The `AnnotationClass` inspection is a "Java Language Level" issue, which pertains to Java versions less than 1.5 (Java 5). Since we only support jdk/jre >= 11, this inspection is not relevant to the project. Sadly, the IDEA inspections website has no information about this inspection, but from the "Inspections" view in Intellij: 

`Reports annotation interfaces. Such interfaces are not supported in Java 1.4 and earlier JVM. `

~~The `'assert' statement` inspection pertains to Java versions less than 1.3 (Java 3). Since we only support jdk/jre >= 11, this inspection is not relevant to the project. Sadly, the IDEA inspections website also has no information about this inspection, but from the "Inspections" view in Intellij:~~

~~`Reports assert statements. By default, assert statements are disabled during execution in the production environment. Consider using logger or exceptions instead.
The assert statements are not supported in Java 1.3 and earlier JVM. `~~

We can safely remove ~~these two~~ this inspection since we do not support language levels below 11.

**Comment by romani** [comment]
Asserts are disabled, but they are ok to be in code without warning from compiler. We can benefit from this inspection is somebody from really old school send us PR with asset in it

**Comment by nick-mancuso** [comment]
These inspections are warning us that someone with a Java version < Java 5 won't be able to compile the given code. We do not need these inspections anymore since we demand Java 11.

**Comment by rnveach** [comment]
I am good to disable these inspections.

**Comment by romani** [comment]
If inspection just report on this method  - it is what we need. All other reasons are not relevant to us.

Can you write asset in main code and send PR. If no violation from TC, we can disable inspection in l file

**Comment by nick-mancuso** [comment]
Link to similar inspection that is already disabled for the same reason: https://github.com/checkstyle/checkstyle/blob/28f4960cdaaa117574f2796675d102ce493e6cae/config/intellij-idea-inspections.xml#L631

**Comment by nick-mancuso** [comment]
I am ok to leave assert inspection, as we do not use this anyway, but `AnnotationClass` inspection is causing us pain.
