### ISSUE TITLE
Update wiki to page to mention latest pitest profiles.

### ISSUE THREAD

**Issue by Vyom-Yadav** [checkstyle/checkstyle#11728]
Update https://github.com/checkstyle/checkstyle/wiki/How-to-run-certain-phases-and-validations#how-to-generate-pitest-report to reflect changes done in #11707

**Comment by romani** [comment]
We need to just mention that `.ci/pitest.sh --list` prints all

**Comment by nick-mancuso** [comment]
Duplicate of https://github.com/checkstyle/checkstyle/issues/11765 (other issue is already approved, otherwise I would close that one)
