### ISSUE TITLE
Automate update of releasenotes.xml by content for new release

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#11729]
We need ready to have script that is located in `.ci` folder
and generates content based on current sources that are on file system

Generator that already can update xml file:
https://github.com/checkstyle/contribution/tree/master/releasenotes-builder 

example of content generation: https://cloud.drone.io/checkstyle/checkstyle/10662/4/3

**Comment by romani** [comment]
Release notes builder in contribution repo already can do this.

Target is https://github.com/checkstyle/checkstyle/blob/8c7e41abefa2a9e004b0dfd7c6eee9dc8a23027d/src/xdocs/releasenotes.xml#L12

**Comment by Rahulkhinchi03** [comment]
@romani We need to use `releasenotes-builder` and not any other tool to automate in the checkstyle repository?

**Comment by romani** [comment]
I do not know other tool that can do it :).
And it worked for us for numerous years.
