### ISSUE TITLE
Automate twitter posts to use single shell command

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#11725]
we need to do https://github.com/checkstyle/checkstyle/wiki/How-to-make-a-release#announcements
automatically.

we have release notes builder - https://github.com/checkstyle/contribution/tree/master/releasenotes-builder
it has ability to do posts in twitter.

TODO:
make script in checkstyle/checkstyle repo in folder ".ci", with name `tweet-releasenotes.sh <git-tag>`.
script should clone repo to `.ci-temp`  checkout to that tag, build release notes, and do tweet. 

Generation of token: https://developer.twitter.com/en/docs/twitter-api/getting-started/getting-access-to-the-twitter-api

**Comment by romani** [comment]
Look at code of releasenotes builder, it should already do this.
We need to wrap it with shell script to be able to run it in CI and from local easily.

**Comment by Rahulkhinchi03** [comment]
@romani 
1. Do you mean that `<git-tag>`, we have to create 3 sh files for the bug, miscellaneous, and feature?
2. I have to use the env variable for twitterConsumerKey, twitterConsumerSecret , twiterAccessToken, twitterAccessTokenSecret?
3. Do we need to add any twitter property?
4. I also have to create a `twitter.txt` file?
