### ISSUE TITLE
satelite projects should use latest  checkstyle as soon at is appears in maven repo

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#11724]
Right now we do bump a version in few projects https://github.com/checkstyle/checkstyle/wiki/How-to-make-a-release#update-for-released-version-reference right after release.

Lets find way to define in pom.xml latest snapshot version of most recent version. And latest released version when we define dependencies. To let us skip such updates at all.

CI of such projects should be able to get latest version from https://repo1.maven.org/maven2/com/puppycrawl/tools/checkstyle/maven-metadata.xml  and run projects with such version.

We can have in all such repos, GitHub action that runs ones a day check https://repo1.maven.org/maven2/com/puppycrawl/tools/checkstyle/maven-metadata.xml , put such values in required files and send PRs with changes (PR is required as we need notice is any problems happens if we introduce breaking changes)

<details>
<summary>Abandoned approach:</summary>
it should be 2 separate scripts for each group that I (later it will be done by CI) should be able to execute from local.

script should clone repository(ies), update sources and push changes back to github,clean up temp clones.

scripts should be at `.ci` folder.
all clones should be done to `.ci-temp` folder.

Updates of xml by shell https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/master/pom-version-bump.sh
That we use in release of sevntu project https://github.com/sevntu-checkstyle/sevntu.checkstyle/wiki/How-to-release-sevntu.checkstyle
</details>

**Comment by Rahulkhinchi03** [comment]
Checking, if I can comment.

**Comment by romani** [comment]
attention:
>update to new snapshot version https://github.com/checkstyle/contribution/edit/master/checkstyle-tester/pom.xml#L15

we need to investigate where it is used ... we might need to change execution script of checkstyle-tester to get this version itself based on what main repo has currently.

**Comment by rnveach** [comment]
> ... we might need to change execution script of checkstyle-tester to get this version itself based on what main repo has currently

It already does this.
https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/diff.groovy#L632

**Comment by Rahulkhinchi03** [comment]
@romani @rnveach While creating a proposal, I mentioned the `RELEASE-IT` tool (https://github.com/release-it/release-it).

We need 2 scripts? One should run in CI and the other in Git/Maven?

**Comment by romani** [comment]
We can probably better skip updates for latest version and defining specific version if we find a way to define it as "latest" released.

@Rahulkhinchi03 , can you investigate how we skip defining exact version and let build system try to use latest only.

I will look a release-it closely to provide feedback.

**Comment by Rahulkhinchi03** [comment]
I believe maven might help us with: `mvn versions:set -DnewVersion=your_new_version` from  [HERE](https://stackoverflow.com/questions/2341906/in-a-maven-project-how-can-i-automatically-update-the-version-all-child-modules) or maybe this link is similar to what we are trying to solve: [Stackoverflow](https://stackoverflow.com/a/10750448/14927620)

**Comment by Rahulkhinchi03** [comment]
We can automate the release update of versioning easily with maven. By following this documentation: http://www.vineetmanohar.com/2009/10/how-to-automate-project-versioning-and-release-with-maven/
These are One time configuration needed for using maven release feature:

1. After versioning our project, maven will deploy our project artifact (jar or war) to a remote repository.
2. It has different options of publishing the artifacts like: `scp`, `wedbav`, `sftp`
3. We need to specify the credentials needed to publish to the remote repo in the settings.xml file that we will be creating as a pre-requisite.

After,
The normal process that @romani do following the documentation of how to make a release.

Last step:
The following command will tag source control, bump up the current pom.xml version and push a tagged artifact (jar or war) to a remote repo.
`mvn release:prepare release:perform -B  `

**Comment by romani** [comment]
>By following this documentation

We already do this, please read release.sh

**Comment by Rahulkhinchi03** [comment]
> I believe maven might help us with: `mvn versions:set -DnewVersion=your_new_version` from [HERE](https://stackoverflow.com/questions/2341906/in-a-maven-project-how-can-i-automatically-update-the-version-all-child-modules) or
> 
> maybe this link is similar to what we are trying to solve: [Stackoverflow](https://stackoverflow.com/a/10750448/14927620) that is releasing the projects using this `<properties>` substitution: keeping the versions of the project as properties in a centralized location like the parent-pom, is valid as long as you don't release the projects

Please read this.

**Comment by romani** [comment]
Yes, we can use it if it does a job.

But better to avoid version definition, and let build system grab latest.

**Comment by Rahulkhinchi03** [comment]
If we use Release It, it has: [HERE](https://github.com/release-it/release-it#update-or-re-run-existing-releases)

> Use `--no-increment` to not increment the last version, but update the last existing tag/version.

**Comment by romani** [comment]
This tool will not work for maven projects.
Maven by itself have all this features for decades. We have no problem with release of jar to maven repository. We have problems to make release notes for user and  make deploy completely in CI to be not dependent on any person.

**Comment by romani** [comment]
In scope of this issue. We need :
1) recheck that placing version "0.0-snapshot" at https://github.com/checkstyle/contribution/edit/master/checkstyle-tester/pom.xml#L15
And recheck that regression report by GitHub still works.

2) recheck how to  let all at `WE need to recheck why “RELEASE” as version does not help us` use latest released version automatically.

**Comment by romani** [comment]
non of this will work reliably, as we need to do same for mave, gradle, ant, .....  
too much work.

last link is not very relevant.

Such projects using latest version just to make sure that use what we release.
I think we should update such projects to use property values in config files for version. Use some latest version by default.
in CI jobs we can take latest version from https://repo1.maven.org/maven2/com/puppycrawl/tools/checkstyle/ , specifically from https://repo1.maven.org/maven2/com/puppycrawl/tools/checkstyle/maven-metadata.xml file and use it as variable value for execution of all jobs as override version to run.

**Comment by Rahulkhinchi03** [comment]
In maven, do we need to use this in pom.xml?
```
          <configuration>
            <tagNameFormat>@{project.version}</tagNameFormat>
          </configuration>
```

**Comment by romani** [comment]
> [checkstyle-tester/pom.xml#L15](https://github.com/checkstyle/contribution/edit/master/checkstyle-tester/pom.xml#L15)

should be fine to make 0.0.0-SNAPSHOT (in worse case set some version here) as are not using this version.

-------

all others

should get version from [maven-metadata.xml](https://repo1.maven.org/maven2/com/puppycrawl/tools/checkstyle/maven-metadata.xml) , update by Github action

**Comment by Rahulkhinchi03** [comment]
SCOPE OF THIS ISSUE ( IN MY UNDERSTANDING):

- I need to create one GITHUB ACTION in all the projects which will update the project version to use the latest release version. 
- The latest release version should be taken from https://repo1.maven.org/maven2/com/puppycrawl/tools/checkstyle/maven-metadata.xml
- The GITHUB ACTION runs every day at a particular time to check the https://repo1.maven.org/maven2/com/puppycrawl/tools/checkstyle/maven-metadata.xml
-

**Comment by romani** [comment]
correct

**Comment by romani** [comment]
No , you need to make GitHub action to update hardcoded version to value that in maven central repo.

**Comment by Rahulkhinchi03** [comment]
@romani  What is the need of this then?

> Gradle might be good to use https://stackoverflow.com/a/68255869, so system will use latest automatically.

**Comment by romani** [comment]
It is not reliable way, it gives no guarantee. You can Google on it, all people discourage to use it. 

We do not it also.

We need hardcoded usage of latest version that 100% workable solution.

**Comment by romani** [comment]
You need one action, that check latest release available and update if it mismatches with what in repository 

Each repository should have its own action.

**Comment by romani** [comment]
Take examples of how we update versions in xml without maven plugin https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/master/pom-version-bump.sh
As you can see this script can update value in xml at any place.

You can always update version by value from metadata file. And simply check no `git diff` to skip push.

Please send PR for each target file separately to let us step by step accomplish task.
First PR can be to create shell file that does update of version in one file, second PR for second file, .... Separate PR to introduce action that runs shell script.

**Comment by Rahulkhinchi03** [comment]
@romani The work of GitHub action is just to run a shell script (every day at one particular time), right? 

IMO: I am not sure if maven-metadata.xml is that unstable. We can run actions once a week or once a month too. Please share your thoughts.

**Comment by romani** [comment]
Just run it each day at any time

**Comment by romani** [comment]
fixed by:
https://github.com/sevntu-checkstyle/checkstyle-samples/issues/35
https://github.com/sevntu-checkstyle/sevntu.checkstyle/issues/893
https://github.com/checkstyle/contribution/issues/634
