### ISSUE TITLE
Include CDG Accelerator Plugin to boost pitest performance

### ISSUE THREAD

**Issue by Vyom-Yadav** [checkstyle/checkstyle#11727]
Pitest takes a significant amount of time to execute in the CI, there are ways in which this time can be improved. Fast feedback form CI will be important in long run and will be super important for this summer's project.

The CDG Accelerator Plugin or the JUnit 5 Accelerator Plugin claims to improves mutation test performance by reducing the overhead in running tests that use a limited set of JUnit Jupiter features. Tests that use only these features will run more quickly, tests that use features outside this set will be executed as normal.

See https://docs.arcmutate.com/docs/accelerator.html#eligible-tests section for the eligible tests.

A license needs to be acquired in order to use the plugin, it is free for open-source projects.
See https://www.arcmutate.com/pricing/ for more details.

**Comment by romani** [comment]
Request to support was sent.

**Comment by nick-mancuso** [comment]
From support:

>A licence for checkstyle should be attached. It will work for any code in the `com.puppycrawl.tools.checkstyle` package and its children. If this is incorrect (or there are additional root packages), please let us know and we will update it.

>The licence will work with all our products, including the extended mutators, junit 5 accelerator and git integration.

From https://docs.arcmutate.com/docs/accelerator.html#installation:

>The licence file must be named cdg-pitest-licence.txt and placed at the root of the project.

License file is here: https://drive.google.com/file/d/14myq90ytUhCC0dvbxqgT3ihlV3J0WueN/view?usp=sharing
