### ISSUE TITLE
Move codenarc to non GitHub CI

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#11747]
From https://github.com/checkstyle/checkstyle/pull/11739#issuecomment-1157245833

I would move this check to Travis or other not high demand CI. It it most likely that such groovy script(s) will never be updated after initial creation, so better to have it run in some less critical CI.

**Comment by romani** [comment]
Can use Travis?

**Comment by nrmancuso** [comment]
Closed via #12349
