### ISSUE TITLE
automate execution by Github action bump-license-year.sh on first day of month

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#11744]
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onschedule

First day of 1st month of year:
`0 0 1 1 *`

This simple task will let us have experience to update sources from Action, that we will need during release notes update in sources.

We will have such action in all satellite projects, so update will happen in same time in parallel, or we will shift all of them by +1 min after main repo

**Comment by Rahulkhinchi03** [comment]
do we need to change some commands in the GitHub action of checkstyle/checkstyle too?
What is the reason for having `bump-license-year-in-all-projects.sh` when we added GitHub actions in all repositories.

**Comment by romani** [comment]
please send PR to remove https://github.com/checkstyle/checkstyle/blob/master/.ci/bump-license-year-in-all-projects.sh and we are ok to close this issue.
