### ISSUE TITLE
remove exclude of ci/pitest-survival-check-xml.groovy from TC

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#11766]
remove exclude of ci/pitest-survival-check-xml.groovy from TC

this should be done AFTER we migrate to file based TC config as prove that it works.

https://teamcity.jetbrains.com/admin/editRunType.html?id=buildType:Checkstyle_IdeaInspectionsMaster&runnerId=RUNNER_415&cameFromUrl=%2Fadmin%2FeditBuildRunners.html%3Fid%3DbuildType%253ACheckstyle_IdeaInspectionsMaster%26init%3D1&cameFromTitle=

![image](https://user-images.githubusercontent.com/812984/175783234-82634794-b056-4a0f-9ecf-690e3223389c.png)

**Comment by Vyom-Yadav** [comment]
@romani @nrmancuso Is this still valid? We dropped the idea of migrating to file based TC config.

**Comment by romani** [comment]
We should remove it from https://github.com/checkstyle/checkstyle/pull/12188/files#diff-d804a8b7018fcdc78e36a4cc2d3e9125fb1018c75a920275071de9ee1ee68858R8

@Vyom-Yadav , as this PR is not merged, can create new PR with copy of Nick changes and in extra commit removal suppression.

**Comment by Vyom-Yadav** [comment]
Yes, once we get green CI in #12188, I will make a PR for the removal of suppressions. Let's get the inspections to run properly, later we can tweak it.

**Comment by romani** [comment]
TC is deprecated as it is constantly failing.
