### ISSUE TITLE
Update "How to run certain phases and validations" section in wiki for pitest

### ISSUE THREAD

**Issue by nrmancuso** [checkstyle/checkstyle#11765]
Now that we have changed pitest execution considerably, we should update the wiki to reflect these changes. This includes:

1. New script name
2. New script output and functionality (`--g` option, etc.)
3. Remove list of profiles, completely, since this is bound to become outdated
4. Mention of separation of pitest execution and report validation

This can only be done by maintainers that have write access to the repo.

**Comment by savy-8** [comment]
sir can you explain what is pitest and how  it works and can i contribute something in it 
i have understanding of java and spring boot only

**Comment by romani** [comment]
@savy-8, if you are new to our project, it is better to start from another issue.

Please follow this way:
>As first issue please choose untouched issue from list - https://github.com/checkstyle/checkstyle/labels/gsoc%20first%20issue , such issues are very very simple, but them are good to start and understand project and contribution workflow. As next issue please choose [gsoc second issue](https://github.com/checkstyle/checkstyle/labels/gsoc%20second%20issue), [gsoc third issue](https://github.com/checkstyle/checkstyle/labels/gsoc%20third%20issue) and further any unassigned issue with "easy" label, after "medium".

From https://github.com/checkstyle/checkstyle/wiki/To-GSoC-participant

**Comment by nick-mancuso** [comment]
Link to gist: https://gist.github.com/Vyom-Yadav/4a75df1de3d7f5a1ee9c6e9c66c69542

**Comment by nrmancuso** [comment]
Due to extensive nature of new pitest docs, I have removed pitest section from "Certain phases..": https://github.com/checkstyle/checkstyle/wiki/How-to-run-certain-phases-and-validations

New page is linked from main wiki page, here is direct link: https://github.com/checkstyle/checkstyle/wiki/How-to-Generate-and-Analyze-Pitest-Reports

@romani please review changes and close this issue if you are satisfied.

**Comment by Vyom-Yadav** [comment]
@nrmancuso @romani See the latest pitest gist, it mentions the required Groovy version too. Please make update the wiki page.

**Comment by romani** [comment]
Put getting list profiles on top
And execution of certain after it https://github.com/checkstyle/checkstyle/wiki/How-to-Generate-and-Analyze-Pitest-Reports#how-to-generate-pit-report

**Comment by romani** [comment]
I updated https://github.com/checkstyle/checkstyle/wiki/How-to-Generate-and-Analyze-Pitest-Reports#experimental-naked-receiver to be more structured and shared link to example PR of how to resolve mutation. By example it is more easy to learn.
