### ISSUE TITLE
Remove unused MethodCallLineWrapHandler

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#1178]
Is file [MethodCallLineWrapHandler.java](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/MethodCallLineWrapHandler.java) needed for anything or used anywhere? 
If not, it can be safely removed.

**Comment by romani** [comment]
remove and launch UTs and google-test project (as it was created for Google's updates), if no problem - remove.

**Comment by mkordas** [comment]
google-test-project works correctly if this class is removed

**Comment by romani** [comment]
merged.
