### ISSUE TITLE
tweet-releasenotes.sh does not check env variables

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#11784]
```
✔ ~/java/github/checkstyle/checkstyle [master|✔] 
$ ./.ci/tweet-releasenotes.sh 
fatal: destination path 'contribution' already exists and is not an empty directory.
^C
```

expected: failure that varaibles are not defined.

**Comment by Rahulkhinchi03** [comment]
I still think we should use:

```
checkForVariable() {
  if [[ "$(declare -p "$1")" =~ ^declare\ -x ]]; then
    echo "Error: Define $1 environment variable"
    exit 1
  fi
}
```
![bsdfgb](https://user-images.githubusercontent.com/71710042/175993425-ee32826e-f519-4f12-9e32-cc5fc205d5e6.png)

**Comment by romani** [comment]
fix is https://stackoverflow.com/questions/65705411/bash-conditional-expression-v-to-check-if-a-variable-is-set

**Comment by romani** [comment]
Fix is merged
