### ISSUE TITLE
Use groovy version provided by `apt` in pitest.yml

### ISSUE THREAD

**Issue by nick-mancuso** [checkstyle/checkstyle#11823]
Instability in CI noted at:

https://github.com/checkstyle/checkstyle/runs/7168691832?check_suite_focus=true
https://github.com/checkstyle/checkstyle/runs/7168691878?check_suite_focus=true

and elsewhere, we should use groovy version that ships with Ubuntu version that CI runner uses to avoid failed download. This will require changes to pitest-survival-check-xml.groovy` to not use newer language features (records).

**Comment by romani** [comment]
Fix is merged
