### ISSUE TITLE
RequireThisCheck not able to handle try-with-resources

### ISSUE THREAD

**Issue by Vyom-Yadav** [checkstyle/checkstyle#11821]
I have read check documentation: https://checkstyle.sourceforge.io/config_coding.html#RequireThis
I have downloaded the latest checkstyle from: https://checkstyle.org/cmdline.html#Download_and_Run
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

```bash
/var/tmp $ javac Test.java
```
```bash
/var/tmp $ cat config.xml
```
```XML
<!DOCTYPE module PUBLIC
        "-//Puppy Crawl//DTD Check Configuration 1.2//EN"
        "http://www.puppycrawl.com/dtds/configuration_1_2.dtd">

<module name="Checker">
  <module name="TreeWalker">
    <module name="RequireThisCheck">
      <property name="validateOnlyOverlapping" value="false" />
    </module>
  </module>
</module>
```
```bash
/var/tmp $ cat Test.java
```
```java
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;

public class Test {

    public BufferedReader instFld2;

     void method() {
        try (BufferedReader instFld2 = new BufferedReader(new InputStreamReader(null, "utf-8"))) {
        }
        catch (IOException e) {
        }
    }
}
```
```bash
/var/tmp $ RUN_LOCALE="-Duser.language=en -Duser.country=US"
/var/tmp $ java $RUN_LOCALE -jar checkstyle-10.3.1-all.jar -c config.xml Test.java
Starting audit...
[ERROR] /var/tmp/Test.java:10:29: Reference to instance variable 'instFld2' needs "this.". [RequireThis]
Audit done.
Checkstyle ends with 1 errors.
```

The violation is given for resource definition, which is not expected.

**Comment by stoyanK7** [comment]
I am on it.

**Comment by Vyom-Yadav** [comment]
@stoyanK7 This may help https://github.com/Vyom-Yadav/checkstyle/commit/4bcd6879795bf6e25cf11becb1352207c5b9b060

**Comment by stoyanK7** [comment]
I already fixed it, but thank you!

**Comment by stoyanK7** [comment]
That is a completely different approach from mine though. I never thought I can use frames for that. Is it expected I use them at all cost?

**Comment by Vyom-Yadav** [comment]
Changes in approach can be discussed in the PR.

**Comment by pbludov** [comment]
Fix is merged.

**Comment by Vyom-Yadav** [comment]
Awesome work!! @stoyanK7

**Comment by romani** [comment]
@pbludov , I am changing it to bug, as there is no new token that user choose to select.
