### ISSUE TITLE
3 tests in EmptyLineSeparatorCheckTest cannot be updated to use verifyWithInlineConfigParser() due to coverage issues

### ISSUE THREAD

**Issue by stoyanK7** [checkstyle/checkstyle#11846]
Related to #11446

## The tests
* `testPrePreviousLineEmptiness()`
https://github.com/checkstyle/checkstyle/blob/5444844c338dfe2b9a3543721af62cc40113ecee/src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheckTest.java#L305-L311
* `testJavadocCommentAfterPackageWithImports()`
https://github.com/checkstyle/checkstyle/blob/5444844c338dfe2b9a3543721af62cc40113ecee/src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheckTest.java#L184-L192
* `testPrePreviousLineIsEmpty()`
https://github.com/checkstyle/checkstyle/blob/5444844c338dfe2b9a3543721af62cc40113ecee/src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheckTest.java#L314-L322
---
## Why changing these tests to use `verifyWithInlineConfigParser()` does not work
Adding the config inside the `Input*.java` file and tweaking the `expect`ed variable will make each test pass. [Here is a commit that makes these changes.](https://github.com/stoyanK7/checkstyle/commit/684e19fa028d70e912e96fe31156fe20cc559178)
### Coverage issues
**However**,  `mvn clean verify` shows that branch coverage is now at `0.99`:
![crash](https://user-images.githubusercontent.com/23459549/177387996-15d2c485-bff9-469c-856d-afe0ec43fb90.png)

Generating test coverage report with `mvn -e clean test -Dtest=EmptyLineSeparatorCheckTest jacoco:restore-instrumented-classes jacoco:report@default-report` shows that coverage issues occur on the following 2 lines:
* https://github.com/checkstyle/checkstyle/blob/5444844c338dfe2b9a3543721af62cc40113ecee/src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheck.java#L646
![647](https://user-images.githubusercontent.com/23459549/177388025-f0163782-3130-47b9-90d7-310f75248264.png)

* https://github.com/checkstyle/checkstyle/blob/5444844c338dfe2b9a3543721af62cc40113ecee/src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheck.java#L812
![812](https://user-images.githubusercontent.com/23459549/177388042-e781e633-b65b-446d-a276-4b29100a8338.png)

---
After having added the configuration in the `Input*.java` files, the AST's being checked would move 11(or so) rows down and would no longer be on lines
* `1`. Will go to line `13`
https://github.com/checkstyle/checkstyle/blob/5e2873f627630f304c3d30edde42192f967bd1c5/src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorJavadocCommentAfterPackage.java#L1
* `2`. Will go to line `13`
https://github.com/checkstyle/checkstyle/blob/5e2873f627630f304c3d30edde42192f967bd1c5/src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorPrePreviousLineEmptiness.java#L2
* `3`. Will go to line `14`
https://github.com/checkstyle/checkstyle/blob/5e2873f627630f304c3d30edde42192f967bd1c5/src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorPrePreviousLineIsEmpty.java#L3

which means `ast.getLineNo() > 1`  and `lineNo >= number(3)` will now always be `true`. The `false` branches are no longer covered. 

## The problem
The problem is that you need those ASTs staying on those first lines(`1`,`2` and `3`) to cover the `false` branches but in order to utilize inline configs, the configs need to be placed in the beginning of the file and therefore push the code down away from those first lines.

**Comment by romani** [comment]
I agree that such tests are conflicting with our bdd model with config on top. We can not use here inlined configs.

I recommend to put comment in sources over such Check `<!-- due to ....link... -->` and close issue.
