### ISSUE TITLE
custom javadoc inline tags cause parse error

### ISSUE THREAD

**Issue by Vladlis** [checkstyle/checkstyle#1184]
Custom javadoc inline tags like {@customTag} cause unrecognized parse error
```
$ java -cp checkstyle-6.7-all.jar com.puppycrawl.tools.checkstyle.Main -c my_check.xml Test.java 
Starting audit...
/home/vlad/cli/Test.java:3: Javadoc comment at column 4 has parse error. Unrecognized error from ANTLR parser: null
Audit done.
Checkstyle ends with 1 errors.

vlad@vlad-N61PC-M2S ~/cli $ cat Test.java
package test.javadoc;
class Foo{
    /** {@customTag} */
    void bar() {}
}

vlad@vlad-N61PC-M2S ~/cli $ cat my_check.xml 
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
<module name = "Checker">
    <module name="TreeWalker">
         <module name="SingleLineJavadocCheck"/>
    </module>
</module>
```
Although, this must be a valid tag, according to this
https://docs.oracle.com/javase/7/docs/technotes/tools/windows/javadoc.html#spellcheckingtagnames
>You can also create more complex block tags, or custom inline tags with the -taglet option.

**Comment by romani** [comment]
you can provide stackstace from UT only if you share that UTs or point to it. As you can not do that so please provide output from CLI - http://checkstyle.sourceforge.net/cmdline.html . Example - https://github.com/checkstyle/checkstyle/issues/1180

**Comment by Vladlis** [comment]
@romani 
fixed

**Comment by romani** [comment]
fix is merged.
