### ISSUE TITLE
Move TeamCity Inspections to project based config

### ISSUE THREAD

**Issue by nrmancuso** [checkstyle/checkstyle#11876]
As experience has shown, configurations in code that live in the project are easier to manage and provide better visibility than configurations that live in web-based UI's. We need to move our current configuration out of our TeamCity server, and into the project. 

Resources:
Initial setup (could be helpful): https://www.jetbrains.com/help/teamcity/creating-and-editing-build-configurations.html#Creating+Build+Configuration+Template

"Storing Project Settings in Version Control﻿"(https://www.jetbrains.com/help/teamcity/storing-project-settings-in-version-control.html#Synchronizing+Settings+with+VCS)

We can set up settings sync here (as detailed in above link): https://teamcity.jetbrains.com/admin/editProject.html?projectId=Checkstyle&tab=versionedSettings

---------------------

Procedure to export configs:
1. Go to project in Team City UI
2. Go to "Versioned Settings"
3. Make selections as follows:
![image](https://user-images.githubusercontent.com/31252532/184139522-12f85bce-384b-4138-bcf2-c95161f71772.png)

>  use settings from VCS
Builds in branches and history builds use settings from corresponding branch and revision in VCS. Developers can also change settings in personal builds.

What this means is that we can make changes in a PR and see them reflected in build (as long as change is made in PR config)

**Comment by romani** [comment]
I do not remember why we did two config per project, one for master one for PR, may be some old TC limitations.

**Comment by nick-mancuso** [comment]
proof of export of configs:

commit from contribution: https://github.com/checkstyle/contribution/commit/7da08e8d90a1e20bc50a9c1a05c09b2457e584fa

commit from sonar-checkstyle:

commit from main repo:

**Comment by nick-mancuso** [comment]
I propose that we close this issue after we do the following:

1. Do we want to investigate consolidation of master and PR configs (possible limitation mentioned at https://github.com/checkstyle/checkstyle/issues/11876#issuecomment-1179730313)?
2. Take care of #11772
3. As proof that config is pulled from VCS branch, do version bump for #11865
4. As further proof of update, do #11766

**Comment by romani** [comment]
>Do we want to investigate consolidation of master and PR configs

It makes sense to ask support, badges might be improved in last 5 years so such problem might be avoided with extra parameter in url 

>Remove branch filter pitest from Team City config #11772

I think this model proved to be very helpful, and we didn't not finish killing all, so there will be one more wave to finish. And we might need such option to run without CI to deal with most stubborn survivals. I recommend to make branch name a bit long to unlikely be used not on purpose. Skip by such branch should stay forever.

>3 and 4

Yes

**Comment by nick-mancuso** [comment]
> I think this model proved to be very helpful, and we didn't not finish killing all

@Vyom-Yadav This model never worked at all, did it?

**Comment by Vyom-Yadav** [comment]
> > I think this model proved to be very helpful, and we didn't not finish killing all
> 
> @Vyom-Yadav This model never worked at all, did it?

No, it didn't work even once.

**Comment by nick-mancuso** [comment]
Clean up from this issue remains.

TODO:

- [ ] Switch TC back to web ui config only
- [ ] remove all `.teamcity` directories from https://github.com/checkstyle/checkstyle, https://github.com/checkstyle/contribution, and https://github.com/checkstyle/sonar-checkstyle

**Comment by romani** [comment]
@nrmancuso , please recheck issue completion. I think it is done.

**Comment by nrmancuso** [comment]
@romani thanks for reminder, all cleanup is completed.
