### ISSUE TITLE
Calculate and compare the pitest execution time after including CDG accelerator plugin.

### ISSUE THREAD

**Issue by Vyom-Yadav** [checkstyle/checkstyle#11871]
From https://github.com/checkstyle/checkstyle/pull/11869#issuecomment-1179587293

The execution time of pitest has reduced after including the CDG accelerator plugin see detailed report at #11869.

 The task of this PR is to calculate the execution time of pitest alone (without setting up the environment in Github actions) and give that report to the maintainers of the plugin.

To calculate the time, create a `pitest-all` profile in local (with all classes present in all the different profiles). Run mutation coverage without the CDG accelerator plugin, and save the log (basically, the time elapsed).

Now run the same profile with the plugin, compare the diff, and report. If the mutation coverage does not take a lot of time (last time we tried the `pitest-all` profile, it took 12 hrs) make a PR, with that profile in a Github action.

**Comment by romani** [comment]
@Vyom-Yadav , can you take most long executed jobs (1-3) and compare results. I hope it would be great feeedback to owners of this library.

**Comment by romani** [comment]
I did testing at https://github.com/checkstyle/checkstyle/pull/12336

**Comment by romani** [comment]
Our tests are complicated and heavy by design, on purpose. Our heavy tests produce more quality value. In such situations we value quality more than speed of tests.
