### ISSUE TITLE
Group pitest profiles logically to reduce time wasted in setting up environment

### ISSUE THREAD

**Issue by Vyom-Yadav** [checkstyle/checkstyle#11872]
https://github.com/checkstyle/checkstyle/runs/7264372538?check_suite_focus=true 1m run.

if we spend 20 seconds on start/finish . and from 40 secnds of mvn execution, about 10 goes to compilation. So we spend 50% on non-pistest ...... it is time to rethink split of pitest execution and make them to run for ~5 minutes to spedn more on pitest rather then start/finish

_Originally posted by @romani in https://github.com/checkstyle/checkstyle/issues/11869#issuecomment-1179562479_

Combine logically similar pitest profiles to reduce the time setting up the environment and reduce the time waiting for the runner to pick up the job.

**Comment by strkkk** [comment]
may be just make a common compilation stage, cache/store compiled project in some common place and execute pitest job on it?

**Comment by romani** [comment]
Execution on all mutations increase significantly execution time, lets wait for final phase on pitest , to let us see full picture of execution time.

**Comment by romani** [comment]
we now only about 15 jobs that take from 2m to 5min execution.
and only 4 job that takes from 2m to 3 minutes.
total amount of jobs is 28.

If we waste only 30sec per job for non-pitest execution, I think it is fine to keep it as it, time will increase as we continue to add more code and tests.
