### ISSUE TITLE
Add possibility to configure targets for ParenPad check

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#1189]
Follow-up to #1058.

Right now it is not possible to control where ParenPad check should be applied, because LPAREN and RPAREN tokens are part of multiple constructs and there is no finer-grained control over them. 

Proposed solution:
* remove from target LPAREN and RPAREN - user needs to configure only exact targets of interests like CTOR_CALL, METHOD_CALL, SUPER_CTOR_CALL, ANNOTATION, LITERAL_IF and so on.
* do manual AST traversing to find LPAREN or RPAREN

**Comment by romani** [comment]
@Vladlis , please help us with this issue.

**Comment by romani** [comment]
merged.
