### ISSUE TITLE
Mutations created by INLINE_CONSTS mutator are hard to understand

### ISSUE THREAD

**Issue by Vyom-Yadav** [checkstyle/checkstyle#11895]
Noticed at #11873 

While adding the `ALL` mutator group, surviving mutations created by the `INLINE_CONSTS` mutator became hard to debug. 
```java
private void validateDefaultJavadocTokens() {
    if (getRequiredJavadocTokens().length != 0) {
        final int[] defaultJavadocTokens = getDefaultJavadocTokens();
        Arrays.sort(defaultJavadocTokens);
        for (final int javadocToken : getRequiredJavadocTokens()) {
            if (Arrays.binarySearch(defaultJavadocTokens, javadocToken) < 0) {
                final String message = String.format(Locale.ROOT,
                                                     "Javadoc Token \"%s\" from required javadoc "
                                                         + "tokens was not found in default "
                                                         + "javadoc tokens list in check %s",
                                                     javadocToken, getClass().getName());
                throw new IllegalStateException(message);
            }
        }
    }
}
```
Surviving Mutation was on line-
```java
final String message = String.format(Locale.ROOT,
```
```
Substituted 2 with 3 → SURVIVED
```
The explanation given by @rnveach at https://github.com/checkstyle/checkstyle/pull/11873#discussion_r920652226:

> Please remember, pitest is a bytecode manipulator. It doesn't read or understand the source code. If you really want to understand what pitest is doing, you need to look at the bytecode.
> 
> > I do not understand what is 2 and what is 3 in such code.
> 
> The source,
> ````
>                     final String message = String.format(Locale.ROOT,
>                             "Javadoc Token \"%s\" from required javadoc "
>                                 + "tokens was not found in default "
>                                 + "javadoc tokens list in check %s",
>                             javadocToken, getClass().getName());
> ````
> 
> converts to:
> 
> > javap -c -l '.\AbstractJavadocCheck.class'
> 
> ````
>       49: getstatic     #32                 // Field java/util/Locale.ROOT:Ljava/util/Locale;
>       52: ldc           #42                 // String Javadoc Token \"%s\" from required javadoc tokens was not found in default javadoc tokens list in check %s
>       54: iconst_2
>       55: anewarray     #34                 // class java/lang/Object
>       58: dup
>       59: iconst_0
>       60: iload         5
>       62: invokestatic  #14                 // Method java/lang/Integer.valueOf:(I)Ljava/lang/Integer;
>       65: aastore
>       66: dup
>       67: iconst_1
>       68: aload_0
>       69: invokevirtual #36                 // Method java/lang/Object.getClass:()Ljava/lang/Class;
>       72: invokevirtual #37                 // Method java/lang/Class.getName:()Ljava/lang/String;
>       75: aastore
>       76: invokestatic  #38                 // Method java/lang/String.format:(Ljava/util/Locale;Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/String;
>       79: astore        6
> ````
> 
> I'll avoid going too far, but basically pitest is manipulating the iconst_2 ( https://github.com/hcoles/pitest/blob/master/pitest/src/main/java/org/pitest/mutationtest/engine/gregor/mutators/InlineConstantMutator.java#L204 ) connected to the following lines:
> ````
>       54: iconst_2
>       55: anewarray     #34                 // class java/lang/Object
> ````
> 
> So what is this code doing and how did it come from the source?
> 
> Basically, `String.format` parameters are `format(Locale l, String format, Object... args)` and this all comes down to how `Object...` is handled in the bytecode when calling this method.
> 
> The source passes each part of the `args` as separate strings, but the method doesn't accept separate strings. It accepts only an array. What Java does for the developers to make coding easier is it sees and makes this simple conversion for you.
> 
> To make this conversion it actually instantiates an Object array for you and puts the arguments you are passing into the array and passes that to the method. In this case we are passing **2** strings to the `args`. So basically your simple `   javadocToken, getClass().getName()` in the source actually becomes `new Object[] {javadocToken, getClass().getName()}` or basically:
> ````
> final Object[] temp = new Object[2];
> temp[0] = javadocToken;
> temp[1] = getClass().getName();
> ````
> 
> You all can start to see where the 2 comes into play here. It is the number of arguments being passed specifically to the `Object...`.
> 
> 3 is just the new value pitest is replacing 2 with to look and find some failure. IE: `new Object[2]` ==> `new Object[3]`.
> 
> If you actually embed the bytecode representation in the source and place it on an isolated line and run pitest, you will see the surviving mutant is only on this line and the rest of the code passes.

**Comment by romani** [comment]
We use this issue only as documentation of reason why we do not use this mutation
