### ISSUE TITLE
Surviving pitest mutations for conditions reducing time complexity at PackageObjectFactory

### ISSUE THREAD

**Issue by Vyom-Yadav** [checkstyle/checkstyle#11902]
Two mutation cases to discuss, these conditions are present to reduce the time complexity.
https://github.com/checkstyle/checkstyle/blob/a583508cfe3478137d58f3776f860dd4fa548a03/config/pitest-suppressions/pitest-common-suppressions.xml#L210-L217

1.
```
<mutation unstable="false">                                                                          
  <sourceFile>PackageObjectFactory.java</sourceFile>                                                 
  <mutatedClass>com.puppycrawl.tools.checkstyle.PackageObjectFactory</mutatedClass>                  
  <mutatedMethod>createModule</mutatedMethod>                                                        
  <mutator>org.pitest.mutationtest.engine.gregor.mutators.RemoveConditionalMutator_EQUAL_IF</mutator>
  <description>removed conditional - replaced equality check with true</description>                 
  <lineContent>if (thirdPartyNameToFullModuleNames == null) {</lineContent>                          
</mutation>                                                                                          
```
Complete relevant code https://github.com/checkstyle/checkstyle/blob/678c547af6de156c604595fe42ffdd0cb05c0023/src/main/java/com/puppycrawl/tools/checkstyle/PackageObjectFactory.java#L189-L193

This null check is present to reduce the time complexity, the method `generateThirdPartyNameToFullModuleName(..)` uses `moduleClassLoader` (final instance field) and `packages` (another final instance field) so even if  `thirdPartyNameToFullModuleNames` is recalculated again and again the result will be the same. The only way it can change is if you access the internal fields, for eg - `packages` using reflections and add an element to the set. But in the current code those fields are not modified. 

2.
```
<mutation unstable="false">                                                                          
  <sourceFile>PackageObjectFactory.java</sourceFile>                                                 
  <mutatedClass>com.puppycrawl.tools.checkstyle.PackageObjectFactory</mutatedClass>                  
  <mutatedMethod>createModule</mutatedMethod>                                                        
  <mutator>org.pitest.mutationtest.engine.gregor.mutators.RemoveConditionalMutator_EQUAL_IF</mutator>
  <description>removed conditional - replaced equality check with true</description>                 
  <lineContent>if (!name.contains(PACKAGE_SEPARATOR)) {</lineContent>                                
</mutation>                                                                                          
```

Complete relevant code https://github.com/checkstyle/checkstyle/blob/678c547af6de156c604595fe42ffdd0cb05c0023/src/main/java/com/puppycrawl/tools/checkstyle/PackageObjectFactory.java#L186-L196

The mutation is replacing the condition with true, if there is some name with `PACKAGE_SEPARATOR` that enters this branch, then it is guaranteed that it will still remain null.
`createFromStandardCheckSet(..)` the standard check set does not contain any module which has `PACKAGE_SEPARATOR` in its short name.
`generateThirdPartyNameToFullModuleName(..)` implementation guarantees it that there are no short names which contain `PACKAGE_SEPARATOR` as it uses `Class#getSimpleName()` to get the short name.
This condition is only present to reduce the time complexity. But this time complexity is enormous, 4 min to 36 minutes for "mvn verify" , see https://github.com/checkstyle/checkstyle/pull/13752#issuecomment-1723463076

**Comment by romani** [comment]
> time complexity

what is time complexity ?

**Comment by Vyom-Yadav** [comment]
> what is time complexity ?

@romani 
Didn't dive into the asymptotic side but if we remove them then it will take a hit if we have multiple modules to load then every time it is not present in standard checks we would recalculate `thirdPartyNameToFullModuleNames`, the same condition can occur in the second case too.

These were the recorded times in populating `thirdPartyNameToFullModuleNames`:
```
258 ms
139 ms
121 ms
132 ms
3 ms
340 ms
```
It depends on how many packages are present there in `private final Set<String> packages;` as we stream `packages` are perform operations on it.

**Comment by Vyom-Yadav** [comment]
@romani @nick-mancuso @baratali @pbludov @rnveach Ping

**Comment by romani** [comment]
@rdiachenko , @Vyom-Yadav , looks like we should not remove this code and it is not a nano performance optimization.
is there any ideas how to wrap suppression in any way that is not a survival file?
in pom.xml we can exclude whole method from pitest.

**Comment by Vyom-Yadav** [comment]
@romani Yes, we can exclude the method using `excludedMethods` in the configuration file, but that defeats the purpose of fine-grained suppressions. The complete method will not be under pitest inspection. Yes, we rarely change those methods, but still, I am much more in favour of keeping them permanently in suppression files.

**Comment by romani** [comment]
> but that defeats the purpose of fine-grained suppressions.

goal of project to minimize as possible usage of fine-grained supprressions. Reason is is that if contributor see a way to suppress, he will always try to suppress, rather then resolve. It is easier to persuade contributor to do effort when where is not suppression at all. In other case contributor think that we unfair on him with overdemand.

**Comment by romani** [comment]
> if (!name.contains(PACKAGE_SEPARATOR))

I thinks we can sacrifice this performance, load of modules happens only ones per whole execution, so it is very nano optimization. Users almost never use full names of modules in configs.

**Comment by romani** [comment]
> if (thirdPartyNameToFullModuleNames == null) {

this one is big performance improvement, as generateThirdPartyNameToFullModuleName is heavy operation
https://github.com/checkstyle/checkstyle/blob/678c547af6de156c604595fe42ffdd0cb05c0023/src/main/java/com/puppycrawl/tools/checkstyle/PackageObjectFactory.java#L304-L307
as it goes to class loading to search in all classes that we have in runtime.

what if we make method:
```
private boolean isHeavyOperationCollectionInitialized(Object obj) {
 return obj != null;
}
```
and we exclude it from pitest as we did with:
https://github.com/checkstyle/checkstyle/blob/f22c784ff4d2ae8a5dc8d4ffbed2b3cc6b641c8c/pom.xml#L3282-L3284
https://github.com/checkstyle/checkstyle/blob/f22c784ff4d2ae8a5dc8d4ffbed2b3cc6b641c8c/pom.xml#L4437-L4441
https://github.com/checkstyle/checkstyle/blob/f22c784ff4d2ae8a5dc8d4ffbed2b3cc6b641c8c/pom.xml#L4606-L4612
for method:
https://github.com/checkstyle/checkstyle/blob/f22c784ff4d2ae8a5dc8d4ffbed2b3cc6b641c8c/pom.xml#L3048-L3055

**Comment by romani** [comment]
@rdiachenko , @Vyom-Yadav , please share your opinion.

**Comment by Vyom-Yadav** [comment]
I am ok with suppressing using `excludedMethods`.

**Comment by rdiachenko** [comment]
How about using Optional for Case 1? Created a draft PR to check it https://github.com/checkstyle/checkstyle/pull/13733

Regarding Case 2, I haven't checked it in details. Can't we cover it by a test? @Vyom-Yadav

**Comment by romani** [comment]
For another case, It sounded like performance improvement, so test will not help to kill pitest

**Comment by romani** [comment]
we merged all changes.
in https://github.com/checkstyle/checkstyle/blob/master/config/pitest-suppressions/pitest-common-suppressions.xml there is no RemoveConditionalMutator_EQUAL_IF
