### ISSUE TITLE
Reuse Plain text release notes from releasenotes-builder in Github release page

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#11901]
page https://github.com/checkstyle/checkstyle/releases/tag/checkstyle-10.3
right now we post only link to release notes.

but we can use Plain text content of releasenotes builder to generate new post in Github format.
Keep "Plan text" unchanged and create new template and "Github post":

We can add `#XXXX` at the begining of text lines so links will be active and easy to use.
`#XXXXXX: title`
we need to keep grouping of issue as it is now in Plan text release notes. 

no links to issues for Notes section!!!
Example plain text released notes generation https://cloud.drone.io/checkstyle/checkstyle/11388/4/2

Structure of new post: 
```
Checkstyle 10.4 - https://checkstyle.org/releasenotes.html#Release_10.4

Breaking compatibility:
  #xxxx - Change ....

New features:
  #xxxx - Support ....

Bug fixes:
  #xxxx - Support qualified annotation names
  #xxxx - Update google_checks.xml to have the SuppressionCommentFilter and SuppressWarningsHolder modules in the config by default (and by extension, SuppressWarningsFilter)


Notes:
  Pitest: Kill all surviving mutations
  update code base to have javadoc tag to explain noinspection tag content
  doc: put example of enableExternalDtdLoad to xdoc
  update doc for SuppressWarningsHolder
  releasenotes script generated empty commit
  Include CDG Accelerator Plugin to boost pitest performance
  Enforce file size on Java inputs
  Expand XPath IT Regression Testing
  There are semantic problems in the Chinese error message of keyword `design.forExtension` .
  prepare-settings.sh fails to create settings.xml
  Use groovy version provided by `apt` in pitest.yml
  Solve fb-contrib errors
  tweet-releasenotes.sh does not check env variables
  download of m2 cache from sourceforge.io is slow 
  infra: turns off create dependency reduced pom for shade plugin
  Update Tests to use new 'verifyXxxxxx' method or 'execute' that use inlined config in Input files
  Specify violation messages in input files.
  pitest: increase mutation coverage for javadoc profile to 100%

==============================================
```

This will make github release page be more readable.

We do update of this page at https://github.com/checkstyle/checkstyle/blob/8c7e41abefa2a9e004b0dfd7c6eee9dc8a23027d/release.sh#L65 

example of release notes page https://github.com/hcoles/pitest/releases/tag/1.9.0

It should be a script that takes Github token from file as it is done in release.sh and do update over existing release page. Eventually it will be executed from release.sh script as just another command.

**Comment by Rahulkhinchi03** [comment]
Things I understood:

1. I need to create a shell script that takes GitHub token.
2. I need to run the shell script in the GitHub workflow.

Confused here: 
> create a new template and "Github post":

3. Is it like I have to create a new template named `GitHub Post` in releasenotes-builder and use the `GitHub Post. `

**Comment by romani** [comment]
>Is it like I have to create a new template named GitHub Post in releasenotes-builder and use the GitHub Post.

Yes. Update releasenotes builder to generate  such content by specific arguments. 
She'll script should do:
- generate content
- update content of release page with content from release notes builder

**Comment by romani** [comment]
fixed in scope of  https://github.com/checkstyle/contribution/issues/623
