### ISSUE TITLE
create Github action that does version bump and update of milestone

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#11900]
https://github.com/checkstyle/contribution/blob/master/releasenotes-builder/diagrams.md

top and most botton actions of Maintainer is just a version bump to required version and update Github milestone.
we need to have github action that can do this for maintainers.
So this will help to avoid manual operation in terminal by maintainers and just trigger Github action with definition of version and it does job.

So in case of release of bug fix (10.3.1) user will do:
1) trigger Githib action to update 10.4-SNAPSHOT to 10.3.1-SNAPSHOT
2) trigger release  
3) trigger Githib action to update 10.3.2-SNAPSHOT to 10.4-SNAPSHOT

we need automation for step 1 and 3.

**Comment by Rahulkhinchi03** [comment]
for this, do we need 2 shell scripts? one for version bump by GitHub API and one for an update of the milestone by maven command? or can instead of creating a shell script, should we just run the command in GitHub actions?

**Comment by romani** [comment]
In my mind it was one sh file that do both: bump, push, update milestone.
But if you see reason to have two, ok, send PR, we will see.

Action should run such script.

**Comment by Rahulkhinchi03** [comment]
> * trigger Githib action to update 10.4-SNAPSHOT to 10.3.1-SNAPSHOT
> * trigger release
> * trigger Githib action to update 10.3.2-SNAPSHOT to 10.4-SNAPSHOT

Why do we need step 3? Also, Should I create another shell script for step3 to make it more clear and not generalized.

**Comment by romani** [comment]
It is same script, the same operations as in first step.

It use to be required, as next version of checkstyle was in many places, so I always kept it on major version increment. But we most likely change this.

For now it is just execution of same action/script as in first , you do not need to create anything extra.
