### ISSUE TITLE
Sarif support is not extended onto the Ant task defined.

### ISSUE THREAD

**Issue by jknair0** [checkstyle/checkstyle#11985]
Current version of Ant Task is not being extended to generate sarif report.
I have created an ant project and tried to create a sarif output format.

**How it works Now:**

adding formatter type to sarif should generate the sarif file in reports like it does for xml. But this formatter type is not supported.
Sample snippet:
```xml
<checkstyle config="checkstyle.xml">
            ...
            <formatter type="xml" tofile="${checkstyle.report.file.xml}"/>
            <formatter type="plain"/>
            <formatter type="sarif" tofile="${checkstyle.report.file.sarif}"/>
            <!-- this ^ will cause error -->
</checkstyle>
```

**Is your feature request related to a problem? Please describe.**
It is related to a feature added in https://github.com/checkstyle/checkstyle/pull/9671

**Describe the solution you'd like**
added the sarif logger like we have added xml logger to generate report in `src/main/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTask.java`

**Comment by jknair0** [comment]
Can i pick this up ?

**Comment by romani** [comment]
we always welcome community to fix issue.

**Comment by jknair0** [comment]
If this patch is merged, will it be released as a patch from the version in which `sarif` was supported ?

**Comment by romani** [comment]
We do release one a month, next release is next weekend. If you pass review quickly, you will be released very quick.

**Comment by rnveach** [comment]
Fixed was merged

**Comment by jknair0** [comment]
Hi. I see milestone 10.4 was added. Will it also be released on 8.x version as patch as well. This is more of a missing part in ant task after the release of SARIF support on version 8.43.

**Comment by romani** [comment]
Sorry, We do not fix old versions, we release only forward.

**Comment by romani** [comment]
@rnveach , I changed it to bug, as we have SARIF for long time, we just missed it in ANT.

**Comment by jknair0** [comment]
Thanks 👍
