### ISSUE TITLE
New Check "Prefer method reference to lambda"

### ISSUE THREAD

**Issue by isopov** [checkstyle/checkstyle#120]
Playing with Java8 it seems to me that methods references are much more readable then lambdas. Of cause they can not be used everywhere as a replacement to lambdas, but in many places where lambda is used - method reference will be much more readable and shorter option. Consider implementing such a check for Java8.

Example:

``` java
list.foreach(s -> System.out.println(s));
list.foreach(System.out::println);
```
##

**Comment by Vampire** [comment]
This should also consider "full fledged" lambdas, not only expression lambdas.
So
`list.foreach(s -> { System.out.println(s); });`
should also be adviced to
`list.foreach(System.out::println);`
Or
`Stream.of(1, 2, 3).map(integer -> { return integer.doubleValue(); });`
should be advised to
`Stream.of(1, 2, 3).map(Integer::doubleValue);`
and so on.

It would be nice if the check would also advise to use expression lambdas where method references are not possible but full-fledged lambdas are used, so for example
`Stream.of("1", "2", "3").map(string -> { return Integer.valueOf(string, 10); });`
should be advised to
`Stream.of("1", "2", "3").map(string -> Integer.valueOf(string, 10));`
which cannot be collapsed to a method reference, or
`Stream.of("1", "2", "3").map(string -> { return string.indexOf('a'); });`
to
`Stream.of("1", "2", "3").map(string -> string.indexOf('a'));`

**Comment by metaphor** [comment]
any updates on this?

**Comment by romani** [comment]
we need sombody to implement this, please feel free to send PullRequest for this.

**Comment by strkkk** [comment]
I will try to implement this.
I do not see any additional properties here.

@romani @rnveach @pbludov 
Most important question - how to name this check?

**Comment by pbludov** [comment]
> Most important question - how to name this check?

Maybe `AvoidOneMethodLambda`?

**Comment by strkkk** [comment]
or `MethodRefInsteadOfLambda`

**Comment by romani** [comment]
just `PreferMethodRefence` .

**Comment by strkkk** [comment]
What about cases when lambda parameters contain annotations, e.g.
```
Function<Object, Integer> func = (@Nonnull Object obj) -> obj.hashCode();
```
From one point of view, it can be ignored, because such syntax is used to apply annotations to lambda params and this can be intentional.
On the other hand, IDEA inspection reports warning for such code.

Possible solution is to add property like `skipIfParametersAnnotated` with default value = `false` (?) or just detect/ignore such cases completely.
@romani @rnveach @pbludov  what do you think?

**Comment by rnveach** [comment]
> `(@Nonnull Object obj) -> obj.hashCode();`

The conversion would be `Object::hashCode` I assume.
Shouldn't we always flag these areas? The `@Nonnull` should take its value from the direct method being called, `hashCode`. It is not like the lambda will override the method's annotation if it is just a direct call. if it was something like `-> obj == null ? null : obj.hashCode` then I could see why the annotation is important, but we are only looking for simple cases to convert.

I don't think annotation should play a role in ignoring lambdas to convert.

**Comment by romani** [comment]
I would rather start with violating all cases, and create property `skipAnnotatedParameters` if users become to complain, as they can use xpath to suppress.

@mbert , you are well known expert in such annotations. Would you expect checkstyle to complain on such code ? What might be a reason to keep such code as labda (not method ref).

**Comment by pbludov** [comment]
Since we are talking about lambdas consisting of a single method call, their annotations should mimics the annotations of the calling method. Otherwise, they will only confuse readers.

**Comment by mbert** [comment]
> I would rather start with violating all cases, and create property `skipAnnotatedParameters` if users become to complain, as they can use xpath to suppress.
> 
> @mbert , you are well known expert in such annotations. Would you expect checkstyle to complain on such code ? What might be a reason to keep such code as labda (not method ref).

Spontaneously I would expect the Jsr305AnnotationsCheck (I guess you're referring to this one, right?) to complain about the code above, because in Java such expressions technically override `@FunctionalInterface` methods. 

According to the Jsr305AnnotationsCheck rulest increasing "nonnullness" constraints in parameters of overridden methods is not allowed (because the implementation could then rely on parameters to be nonnull while the implemented/overridden method's contract does not guarantee this). Conversely code like `(@Nullable Object obj) -> obj.hashCode()` would be legal.

**Comment by Vampire** [comment]
Am I right that my request from comment https://github.com/checkstyle/checkstyle/issues/120#issuecomment-466602250 will not be covered?
Should we invent a different check like `PreferExpressionLambda` for that?

**Comment by romani** [comment]
@Vampire , please start new issue for discussion.

**Comment by romani** [comment]
A bit more nuances about reference usage https://www.baeldung.com/java-methods-references-eval

**Comment by romani** [comment]
implementation is almost done at https://github.com/checkstyle/checkstyle/pull/8232 

It is sad that we lost energy to finish it.
This Check looks interesting idea but has a lot uncertainties and in some cases very controversial. If I accept such implementation there will be numerous bugs on us to improve that we unlikely can make.

If somebody has time and interest I recommend to move this implementation(PR https://github.com/checkstyle/checkstyle/pull/8232) to sevntu https://github.com/sevntu-checkstyle/sevntu.checkstyle where we keep such Checks. It will help us to release it and start use it and collect real life experience to prove that it works and can be moved to main repo or collect set of problems and iterate in design as much as we need, in sevntu we can damage breaking compatibility as much as we need, all Checks considered as experimental.

**Comment by romani** [comment]
if somebody have time to make it happen, please do it https://github.com/sevntu-checkstyle/sevntu.checkstyle/issues/825 , it will be much easier to do this in that project.

**Comment by vlsi** [comment]
I'm inclined the check should be auto-correctable, so OpenRewrite or IDEA are better tools than Checkstyle here.

See https://docs.openrewrite.org/reference/recipes/java/cleanup/replacelambdawithmethodreference
