### ISSUE TITLE
SuppressWarningsCheck fails with exception on its own input file InputSuppressWarningsHolder.java

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#1201]
Attempt to launch Checkstyle over its own sources (all sources , not only production code ) cause strange Exception "java.lang.IllegalStateException: Should never get here, type: 125 text: +"

my logs ( /home/rivanov/java/git-others/checkstyle/checkstyle is clone of master from github):
```
21:25 /var/tmp $ java -jar checkstyle-6.8-SNAPSHOT-all.jar -c /home/rivanov/java/git-others/checkstyle/checkstyle/config/checkstyle_checks.xml -p /home/rivanov/java/git-others/checkstyle/checkstyle/config/checkstyleProperties.properties /home/rivanov/java/git-others/checkstyle/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/InputSuppressWarningsHolder.java
Jun 10, 2015 9:48:48 PM com.puppycrawl.tools.checkstyle.TreeWalker processFiltered
SEVERE: IllegalStateException occurred during the analysis of file /home/rivanov/java/git-others/checkstyle/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/InputSuppressWarningsHolder.java.
java.lang.IllegalStateException: Should never get here, type: 125 text: +
	at com.puppycrawl.tools.checkstyle.checks.annotation.SuppressWarningsCheck.visitToken(SuppressWarningsCheck.java:183)
	at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:393)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:482)
	at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:322)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:195)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:76)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:260)
	at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:234)
	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:86)

Starting audit...
.......
21:50 /var/tmp $ cat /home/rivanov/java/git-others/checkstyle/checkstyle/config/checkstyleProperties.properties
checkstyle.suppressions.file=/home/rivanov/java/git-others/checkstyle/checkstyle/config/suppressions.xml
checkstyle.header.file=/home/rivanov/java/git-others/checkstyle/checkstyle/config/java.header
checkstyle.importcontrol.file=/home/rivanov/java/git-others/checkstyle/checkstyle/config/import-control.xml

```

**Comment by romani** [comment]
@mkordas , can you please take a look, you updated that Check and input several days ago.

**Comment by romani** [comment]
on completion commit https://github.com/checkstyle/contribution/commit/8bfde0caa0bc526b83e6d4950c06f9e58002012f should be reverted

**Comment by mkordas** [comment]
@romani, I've just added new input file that intentionally has some crazy `@SuppressWarnings` annotations.

The issue is that the SuppressWarnings check doesn't know that `@SuppressWarnings("un" + "used")` is equivalent to `@SuppressWarnings("unused")`. Should it calculate it?

Even if you say yes, what about cases like `@SuppressWarnings({('u' + 'n') + ((""+((("used" + ""))))) + "",})`, which is also equivalent to  `@SuppressWarnings("unused")`?)
When should we say _no_, we won't calculate this expression? Maybe `java.lang.IllegalStateException` from `SuppressWarningsCheck.java:183` should be just removed?

**Comment by romani** [comment]
> @SuppressWarnings("un" + "used") is equivalent to @SuppressWarnings("unused"). Should the check calculate it?

lets not support that, please put that as LIMITATION to do if you with.

>Maybe java.lang.IllegalStateException from SuppressWarningsCheck.java:183 should be just removed?

yes, please remove "throw", add a comment to code with example (as it is not obvious at all) and UT that will use that "default" and will not failing.

**Comment by romani** [comment]
merged.
