### ISSUE TITLE
tweet-releasenotes.sh should be able to generate release notes for any release of past 

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#12011]
https://github.com/checkstyle/checkstyle/blob/master/.ci/tweet-releasenotes.sh

1)
it is not clear why we demand 
`checkForVariable "CS_RELEASE_VERSION"`

and in same time do
```
CS_RELEASE_VERSION="$(getCheckstylePomVersion)"
echo CS_RELEASE_VERSION="$CS_RELEASE_VERSION"
```

2)
This script should work in two modes:
`.ci/tweet-releasenotes.sh` - generation of twit for latest release
`.ci/tweet-releasenotes.sh 10.3.2` - generation of twit for release 10.3.2

**Comment by Rahulkhinchi03** [comment]
> it is not clear why we demand

We need it to refer to the current `releaseNumber`. This number is required to run the releasenotes-builder. So we check for it before only. However, releasenotes give the error when it doesn't find the release number but we check it before it runs.

> and in same time we do

Yes, I agree with this. When we do this step then we can terminate doing `checkForVariable "CS_RELEASE_VERSION"`

**Comment by romani** [comment]
Send PR

**Comment by Rahulkhinchi03** [comment]
> This script should work in two modes:
> `.ci/tweet-releasenotes.sh` - generation of twit for latest release
> `.ci/tweet-releasenotes.sh 10.3.2` - generation of twit for release 10.3.2

I can run both and getting the execution succeed only:
`.ci/tweet-releasenotes.sh`
`.ci/tweet-releasenotes.sh 10.3.2`

**Comment by romani** [comment]
You need to update script to work in such modes

**Comment by Rahulkhinchi03** [comment]
> it is not clear why we demand
> checkForVariable "CS_RELEASE_VERSION"

Yes, @romani you were right. We don't need this for all the shell scripts. We need the latest project version only in some scripts. I used `LATEST_RELEASE_INDEX` in the Twitter issue as `-releaseNumber`.
