### ISSUE TITLE
Backward compatibility broken by rename of FileContents.getFilename() to getFileName()

### ISSUE THREAD

**Issue by tsjensen** [checkstyle/checkstyle#1205]
[This recent commit](https://github.com/checkstyle/checkstyle/commit/7dd24c8c35572b5db3e5c905d440e813cfe2538c) causes problems with custom checks compiled against earlier versions of Checkstyle, because the method `getFilename()` in class FileContents has been renamed to `getFileName()`. The effects are simliar to issue #505 because custom checks stop working unless they are recompiled against the new Checkstyle version (and in fact, they must have their code changed).
This is bad because SonarQube does not follow Checkstyle's fast release cycle ([they are still on 6.4.1](http://docs.sonarqube.org/display/PLUG/Checkstyle+Plugin)). So if the custom check gets reworked to run in a current IDE, it no longer works in SonarQube.

**Comment by romani** [comment]
do you want me to return it as Deprecated ? please do PR.

FYI: we will keep that deprecated method for few releases , but it will not stay in code for long time.
Please expect some small braking changes each release. API package will get serious update this year.

**Comment by romani** [comment]
> This is bad because SonarQube does not follow Checkstyle's fast release cycle

please open issue against them to update a version, it is not a big deal for them.

**Comment by tsjensen** [comment]
OK - I opened PR #1206 

Please keep the deprecated methods for some amount of *time* rather than for a number of releases. A period of one year would give everyone (especially SonarQube) enough time to react, I would suggest.

**Comment by romani** [comment]
merged. Thanks a lot!
