### ISSUE TITLE
Github action "Release prepare"

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#12078]
https://github.com/checkstyle/contribution/blob/master/releasenotes-builder/diagrams-manual-trigger.md

we need to make action to do `run Github action "Release Prepare '10.3.1'"` (action takes human provided version as input, just to make sure it can not be executed unintentionally)
if user provider input is not matching pom - fail build
so we simply make script that do "mvn:prepare"
and github action commit and push changes and push created commit by maven.

**Comment by romani** [comment]
beware that release:prepare creates extra files:
```
✔ ~/java/github/checkstyle/checkstyle [master ↑·2|…2] 
06:39 $ git status
On branch master
Your branch is ahead of 'origin/master' by 2 commits.
  (use "git push" to publish your local commits)
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	pom.xml.releaseBackup
	release.properties

nothing added to commit but untracked files present (use "git add" to track)
✔ ~/java/github/checkstyle/checkstyle [master ↑·2|…2] 
06:39 $ git diff
✔ ~/java/github/checkstyle/checkstyle [master ↑·2|…2] 
06:39 $ cat release.properties 
#release configuration
#Sun Jul 31 06:38:51 PDT 2022
project.scm.com.puppycrawl.tools\:checkstyle.developerConnection=scm\:git\:git@github.com\:checkstyle/checkstyle.git
remoteTagging=true
project.scm.com.puppycrawl.tools\:checkstyle.url=https\://github.com/checkstyle/checkstyle
scm.commentPrefix=[maven-release-plugin] 
completedPhase=end-release
project.dev.com.puppycrawl.tools\:checkstyle=10.3.3-SNAPSHOT
scm.url=scm\:git\:git@github.com\:checkstyle/checkstyle.git
project.scm.com.puppycrawl.tools\:checkstyle.connection=scm\:git\:git@github.com\:checkstyle/checkstyle.git
project.scm.com.puppycrawl.tools\:checkstyle.tag=HEAD
exec.additionalArguments=-DskipTests -DskipITs -Dcheckstyle.ant.skip\=true -Dcheckstyle.skip\=true   -Dpmd.skip\=true -Dspotbugs.skip\=true -Djacoco.skip\=true -Dxml.skip\=true -Psonatype-oss-release -P gpg
pushChanges=true
scm.tag=checkstyle-10.3.2
project.rel.com.puppycrawl.tools\:checkstyle=10.3.2
preparationGoals=clean verify
```

them are requred for `release:perform` but I am not sure how critical it. As we execute in different time such goals and in different action/hosts, we need to make sure `release:perform` ahve such files before execution or prove that such files arer not required and "perform" can be executed without them if we checkout to release tag.

**Comment by Rahulkhinchi03** [comment]
We can run `mvn release:clean` after the `mvn release:perform`. It will first let` release:perform` use these files and then we can delete these files after the `perform `

**Comment by Rahulkhinchi03** [comment]
I had an issue before for generating a `gpg key`. I am not sure how to generally create it.
