### ISSUE TITLE
Github action to update sources with release notes

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#12077]
https://github.com/checkstyle/contribution/blob/master/releasenotes-builder/diagrams-manual-trigger.md

we need to make action to do `run Github action "Push releasenotes '10.3.1'"`  (action takes human provided version as input, just to make sure it can not be executed unintentionally)
if user provider input is not matching pom - fail build
so we simply make script that update releasenotes.xml
and github action commit and push changes

**Comment by Rahulkhinchi03** [comment]
SCOPE Confirmation:

1. GitHub Action will take the version from the input.
2. condition to check if pom version and input version match. ( if not then fail GitHub action)
3. If doesn't match, the shell script will update the releasenotes.xml to INPUT VERSION ([Line 13](https://github.com/checkstyle/checkstyle/blob/master/src/xdocs/releasenotes.xml#L13) to User Input Version )
4. Commit and Push

**Comment by Rahulkhinchi03** [comment]
We already have one script that updates releasenotes.xml and pushes releasenotes to the master branch,
Script: https://github.com/checkstyle/checkstyle/blob/master/.ci/releasenotes-gen-xdoc-push.sh

Then why do we need another script for the same?
