### ISSUE TITLE
Github action "Copy site to sourceforge"

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#12081]
https://github.com/checkstyle/contribution/blob/master/releasenotes-builder/diagrams-manual-trigger.md

we need to make action to do `run Github action "Copy site to sourceforge '10.3.1'"` (action takes human provided version as input)
see https://github.com/checkstyle/checkstyle/blob/master/.ci/copy-site-to-sourceforge.sh, reuse it.
see when I executed such script https://github.com/checkstyle/checkstyle/wiki/How-to-make-a-release#perform-release-build

for testing, create your own projects on sourceforge and test script execution.

ATTENTION: lest postpone this task for later....
There might be BIG problem to authorize copy by SSH/SCP, I am still placing password manually(interactive mode), it will be blocker during execution in girhub (non-interactive mode)

```
✔ ~/java/github/checkstyle/checkstyle [master|✔] 
 $ ./.ci/copy-site-to-sourceforge.sh $PREV_RELEASE $NEW_RELEASE
PREVIOUS RELEASE version:10.3
RELEASE version:10.3.1
Please provide password for romanivanov,checkstyle@shell.sourceforge.net
Pseudo-terminal will not be allocated because stdin is not a terminal.

You already have a shell created.

Clone by ssh only to avoid passwords on push
Cloning into 'checkstyle.github.io'...
```

------

strange it works fine now.

**Comment by Rahulkhinchi03** [comment]
I am not sure with Sourceforge but How do you resolve this when` uploading to Sourceforge`? Please provide feedback.

FROM: https://github.com/checkstyle/checkstyle/blob/master/.ci/copy-site-to-sourceforge.sh#L37-L39

```
Uploading to sourceforge ...
scp: /home/project-web/checkstyle/: Is a directory
rahul@rk7:~/Desktop/opensource/checkstyle$ 
```

-> I am using `checkstyle.github.io` as a special repo and uploading this project only.

**Comment by romani** [comment]
> scp: /home/project-web/checkstyle/: Is a directory

is folder in sourceforge host. you need to modify my script to copy to your folder.

We need to find way to copy files to sourceforge without interactive request for password. Please contact sourceforge support to ask them to help how to do `scp <file on laptop> <folder in sourceforge host>` without password and do it from Github Action or any other CI.

**Comment by romani** [comment]
workaround for sourceforge interactive mode:
```
$ sudo apt install sshpass
$ export SSHPASS='your password'
$ export SF_USER=your_user
$ echo "exit" | sshpass -e ssh -t $SF_USER,checkstyle@shell.sourceforge.net create
Pseudo-terminal will not be allocated because stdin is not a terminal.

Requesting a new shell for "your_user" and exiting when it is ready.
queued... creating... starting...
```

So we need action that installs `sshpass`
repo will have two secrets: SF_USER, SF_PASS 
action will init environment variables: SF_USER, SSHPASS

**Comment by Rahulkhinchi03** [comment]
sshpass action:
```
    - name: Run sshpass commands
      uses: matheusvanzan/sshpass-action@v2
      with:
        host: ${{ secrets.SERVER_HOST }}
        user: ${{ secrets.SF_USER }}
        key: ${{ secrets.SF_PASS }}
        run: |
```

**Comment by romani** [comment]
No need, just install this tool and let's use it

**Comment by stoyanK7** [comment]
On it.

**Comment by stoyanK7** [comment]
Everything seems to be fine now. Got my access back. Will try to have MR by today/tomorrow.
