### ISSUE TITLE
Github action "Update Github"

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#12080]
https://github.com/checkstyle/contribution/blob/master/releasenotes-builder/diagrams-manual-trigger.md

we need to make action to do `run Github action "Update Github '10.3.1'"` (action takes human provided version as input, just to make sure it can not be executed unintentionally)
if user provider input is not matching pom - fail build

so we simply make script that update github milestones and upoad "-all.jar"
see all code in release.sh

**Comment by Rahulkhinchi03** [comment]
Confirmation:
1. User Input
2. POM Version != User Input ( if not - fail build )
3.  Shell script will first run` update-github-milestone.sh` and then [75-82](https://github.com/checkstyle/checkstyle/blob/master/release.sh#L75-L82)
