### ISSUE TITLE
update all shell scripts for release automation to check that parameter is definied

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#12083]
example - update-github-milestone.sh

execution without parameter defined, consider version to be be empty string so it is damage.

upadate script to be clear that is requfed READ_ONLY or GITHUB_TOKEN(read write):
-  READ_ONLY_TOKEN
- GITHUB_TOKEN

Example: update-github-milestone.sh should use GITHUB_TOKEN as it updates, it is not readonly - whole script should operate by read-write token

**Comment by Rahulkhinchi03** [comment]
`bump-version.sh` - NO TOKEN
`prepare-settings.sh` - NO TOKEN

`releasenotes-gen.sh` - **READ_ONLY_TOKEN** (uses only 1 token for releasenotes-builder)
`releasenotes-gen-xdocs-push.sh` - **READ_ONLY_TOKEN** (uses only 1 token for releasenotes-builder)

`tweet-releasenotes.sh` - GITHUB_READ_ONLY_TOKEN - (Uses 3 times, same token only )

`update-github-milestone.sh` - [ Changed READ_ONLY_TOKEN -> GITHUB_TOKEN]
