### ISSUE TITLE
Release notes for GitHub shows escape at-symbol 

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#12092]
https://github.com/checkstyle/checkstyle/pull/12007#issuecomment-1221431907

**Comment by Rahulkhinchi03** [comment]
Works fine with ```@```

**Comment by Rahulkhinchi03** [comment]
@romani Here, do I just need to escape it from GitHub Page or do I need to add some condition or changes in the script or something?

**Comment by Rahulkhinchi03** [comment]
```
public static String EscapeAt(String atSymbol) {                         
    return string.replace("@", "`@`");                            
}               
```  

I am facing a problem to understand where should I add this function in the releasenotes-builder code.

**Comment by romani** [comment]
In template you use field name of class, you just need to have one more field that is escaped.

**Comment by Rahulkhinchi03** [comment]
Create an issue in the contribution repository. Please close this issue.

**Comment by romani** [comment]
moved to https://github.com/checkstyle/contribution/issues/652
