### ISSUE TITLE
InnerTypeLast. Report enum

### ISSUE THREAD

**Issue by pozdeiev** [checkstyle/checkstyle#12136]
Hello.
Should `InnerTypeLast` check reports inner enums which are not placed at the bottom of the primary class?

**Comment by nick-mancuso** [comment]
Please follow issue template, or ask questions on our gitter or mailing list.

**Comment by romani** [comment]
>Should InnerTypeLast check reports inner enums which are not placed at the bottom of the primary class?

Yes, it should.
