### ISSUE TITLE
Unable to Install in Eclipse

### ISSUE THREAD

**Issue by garberfc** [checkstyle/checkstyle#12139]
I have read check documentation: https://checkstyle.org/config_xxxxxx.html#NameOfAffectedCheck
I have downloaded the latest checkstyle from: https://checkstyle.org/cmdline.html#Download_and_Run
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

**Describe what you expect in detail.**
I'm attempting to install the CheckStyle plug-in from the Eclipse Marketplace, but it errors out with the message: 
**Unable to read repository at https://checkstyle.org/eclipse-cs-update-site/content.xml.
Stream already closed**

When I attempt to load the page https://checkstyle.org/eclipse-cs-update-site/content.xml into a browser, I get a 404 error. Page not found...

ATTENTION: FAILURE TO FOLLOW THE ABOVE TEMPLATE WILL RESULT IN THE ISSUE BEING CLOSED.

**Comment by nick-mancuso** [comment]
Please report this issue to https://github.com/checkstyle/eclipse-cs, we do not maintain plug-in in main repo.
