### ISSUE TITLE
add helper methods hasModifiers and hasNotModifiers

### ISSUE THREAD

**Issue by ZuevKirill95** [checkstyle/checkstyle#12143]
I suggest adding helper methods hasModifiers and hasNotModifiers
More detailed in this PR - https://github.com/checkstyle/checkstyle/pull/12088

**Comment by rnveach** [comment]
@ZuevKirill95 Please move important details here. This should include why this is needed, recommended method signature, note about scope of change (lots of checks were changed), etc...

**Comment by romani** [comment]
I don't understand a reason of such methods.
We do not host methods that we are not using.
