### ISSUE TITLE
About endOfSentenceFormat i18n

### ISSUE THREAD

**Issue by CorvusYe** [checkstyle/checkstyle#12141]
**How it works Now:**

```java
/**
 * The language of the comment, the end symbol is not .?!, but 。？！
 */
public Demo {
}
```

```log
First sentence should end with a period.
```

**Describe the solution you'd like**
When using the mother tongue in javadoc, we should follow the use style of the mother tongue and use appropriate sentence terminators.

**Additional context**
pr: https://github.com/checkstyle/checkstyle/pull/12140

Thanks !

**Comment by nick-mancuso** [comment]
@CorvusYe please follow issue template

**Comment by nrmancuso** [comment]
Judging from linked PR, this issue references JavadocStyle check. Please read https://checkstyle.sourceforge.io/config_javadoc.html#JavadocStyle, specifically the Properties table, to see how to change the endOfSentenceFormat in your config.

**Comment by CorvusYe** [comment]
Thanks~
