### ISSUE TITLE
failure to publish github release notes ' R: Publish GitHub Page'

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#12169]
https://github.com/checkstyle/checkstyle/runs/8179578319?check_suite_focus=true
```
Run ./.ci/publish-releasenotes-githubpage.sh 10.3.3
TARGET_VERSION=10.3.3
Error: Define  environment variable
Error: Process completed with exit code 1.
```

**Comment by romani** [comment]
Still problem

**Comment by romani** [comment]
problem above is fixed at https://github.com/checkstyle/checkstyle/commit/46acc04a505826b8aae479be92a982454d558681
now we have problem with https://github.com/checkstyle/checkstyle/runs/8227729521?check_suite_focus=true
```
TARGET_RELEASE_INDEX=0
PREVIOUS_RELEASE_INDEX=1
START_REF=checkstyle-10.3.2
END_REF=checkstyle-10.3.3
{"message":"Resource not accessible by integration",
  "documentation_url":"https://docs.github.com/rest/reference/users#get-the-authenticated-user"}
usage:
java -jar releasenotes-buil......
```

**Comment by romani** [comment]
https://github.com/checkstyle/checkstyle/runs/8228730807?check_suite_focus=true#step:3:201
one more problem:
```
{
  "message": "Problems parsing JSON",
  "documentation_url": "https://docs.github.com/rest/reference/repos#update-a-release"
100  2177  100   129  100  2048    658  10448 --:--:-- --:--:-- --:--:-- 11107
}
```

**Comment by stoyanK7** [comment]
@romani Trying to replicate [the above comment's](https://github.com/checkstyle/checkstyle/issues/12169#issuecomment-1239374997) behavior on local but have had no success. Can you help with this?
```
./.ci/update-github-page.sh 10.3.3
```
```
Generation ends with 2 errors.

[ERROR] Issue #12351 does not have breaking compatibility, bug, miscellaneous, new feature, new module label! Please set label at https://github.com/checkstyle/checkstyle/issues/12351
[ERROR] Issue #12370 does not have breaking compatibility, bug, miscellaneous, new feature, new module label! Please set label at https://github.com/checkstyle/checkstyle/issues/12370

```

**Comment by stoyanK7** [comment]
The problem is because of unescaped `"` characters in GitHub page notes. This is where the conversion happens https://github.com/checkstyle/checkstyle/blob/d515c25aab3c7e0288575512c2b290df82986c00/.ci/update-github-page.sh#L76-L85

Will try to find a way to escape them via `\"`.

**Comment by romani** [comment]
`jq` tool can escape it exactly as json need it, I posted comemment in PR

**Comment by romani** [comment]
Fix is merged
