### ISSUE TITLE
execution of 'R: Update github.io' with '10.3.3' faililng

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#12160]
https://github.com/checkstyle/checkstyle/runs/8170868585?check_suite_focus=true

```
Run ./.ci/update-github-io.sh 10.3.3
TARGET_VERSION=10.3.3
error: pathspec 'checkstyle-10.3.3' did not match any file(s) known to git
Error: Process completed with exit code 1.
```

please do `git fetch ---tags` after clone.

**Comment by rnveach** [comment]
Just pointing to the line in issue:
https://github.com/checkstyle/checkstyle/runs/8170868585?check_suite_focus=true#step:2:49
> /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +aa6fc8c2bb52d668812f26ecfd220024db00fe7d:refs/remotes/origin/master

It specifically does not pull in tags as shown by `--no-tags`.

**Comment by Rahulkhinchi03** [comment]
@romani @rnveach How about using?

Fetch all history for all tags and branches:

```
- uses: actions/checkout@v3
  with:
    fetch-depth: 0
```

**Comment by romani** [comment]
https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches
