### ISSUE TITLE
Enable Checker Framework

### ISSUE THREAD

**Issue by nrmancuso** [checkstyle/checkstyle#12164]
In our relentless pursuit to use all static analysis and code quality tools, we would like to add the [Checker Framework](https://checkerframework.org/) to our project. This framework uses annotations and utilities to enhance type checking and reduce potential defects in code.

Here is the built-in Checkers:

 - [ ] [Nullness Checker](https://checkerframework.org/manual/#nullness-checker) for null pointer errors 
- [ ] [Initialization Checker](https://checkerframework.org/manual/#initialization-checker) to ensure all @NonNull fields are set in the constructor 
- [ ] [Map Key Checker](https://checkerframework.org/manual/#map-key-checker) to track which values are keys in a map 
- [ ] [Optional Checker](https://checkerframework.org/manual/#optional-checker) for errors in using the [Optional](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/Optional.html) type 
- [ ] [Interning Checker](https://checkerframework.org/manual/#interning-checker) for errors in equality testing and interning 
- [ ] [Called Methods Checker](https://checkerframework.org/manual/#called-methods-checker) for the builder pattern 
- [ ] [Resource Leak Checker](https://checkerframework.org/manual/#resource-leak-checker) for ensuring that resources are disposed of properly 
- [ ] [Fake Enum Checker](https://checkerframework.org/manual/#fenum-checker) to allow type-safe fake enum patterns and type aliases or typedefs 
- [ ] [Tainting Checker](https://checkerframework.org/manual/#tainting-checker) for trust and security errors 
- [ ] [Lock Checker](https://checkerframework.org/manual/#lock-checker) for concurrency and lock errors 
- [ ] [Index Checker](https://checkerframework.org/manual/#index-checker) for array accesses 
- [ ] [Regex Checker](https://checkerframework.org/manual/#regex-checker) to prevent use of syntactically invalid regular expressions 
- [ ] [Format String Checker](https://checkerframework.org/manual/#formatter-checker) to ensure that format strings have the right number and type of % directives 
- [ ] [Internationalization Format String Checker](https://checkerframework.org/manual/#i18n-formatter-checker) to ensure that i18n format strings have the right number and type of {} directives 
- [ ] [Property File Checker](https://checkerframework.org/manual/#propkey-checker) to ensure that valid keys are used for property files and resource bundles 
- [ ] [Internationalization Checker](https://checkerframework.org/manual/#i18n-checker) to ensure that code is properly internationalized 
- [ ] [Signature String Checker](https://checkerframework.org/manual/#signature-checker) to ensure that the string representation of a type is properly used, for example in Class.forName 
- [ ] [GUI Effect Checker](https://checkerframework.org/manual/#guieffect-checker) to ensure that non-GUI threads do not access the UI, which would crash the application 
- [ ] [Units Checker](https://checkerframework.org/manual/#units-checker) to ensure operations are performed on correct units of measurement 
- [ ] [Signedness Checker](https://checkerframework.org/manual/#signedness-checker) to ensure unsigned and signed values are not mixed 
- [ ] [Purity Checker](https://checkerframework.org/manual/#purity-checker) to identify whether methods have side effects 
- [ ] [Constant Value Checker](https://checkerframework.org/manual/#constant-value-checker) to determine whether an expression’s value can be known at compile time 
- [ ] [Reflection Checker](https://checkerframework.org/manual/#reflection-resolution) to determine whether an expression’s value (of type Method or Class) can be known at compile time 
- [ ] [Initialized Fields Checker](https://checkerframework.org/manual/#initialized-fields-checker) to ensure all fields are set in the constructor 
- [ ] [Aliasing Checker](https://checkerframework.org/manual/#aliasing-checker) to identify whether expressions have aliases 
- [ ] [Must Call Checker](https://checkerframework.org/manual/#must-call-checker) to over-approximate the methods that should be called on an object before it is de-allocated 
- [ ] [Subtyping Checker](https://checkerframework.org/manual/#subtyping-checker) for customized checking without writing any code 
- [ ] [Third-party checkers](https://checkerframework.org/manual/#third-party-checkers) that are distributed separately from the Checker Framework 

Not all of these apply to our project, we can discuss the Checkers here and decide which will be valuable for us. Also, suppression of various Checkers can be a bit different, so we can take this on a case-by-case basis.

1 Checker == 1 PR

As for minimizing/ keeping annotations out of our codebase, we can consider https://checkerframework.org/annotation-file-utilities/#viewing-source, which is a tool to externally store annotations and insert them into source code as needed (such as during execution of Checker).

**Comment by romani** [comment]
Being 100% covered, and fanatically use pitest (nulls everywhere, substitution everywhere ) ..... how much such annotations can benefit us ?
or may be they will bring some value to our plugins/integrations and users will rely on them.

**Comment by Vyom-Yadav** [comment]
For the nullness checker, we usually get NPE's if `nextSibling()`, `prevSibling()`, etc. is null which the Checker framework can't detect as such cases are dependent on the input.

**Comment by romani** [comment]
CheckerFramework suppose to just warn that method might return null, so caller code should be ready to handle both cases.

**Comment by romani** [comment]
>may be they will bring some value to our plugins/integrations and users will rely on them

this might be good reason to cover our `api` package first, to let others use our methods with visually explicit contract.

**Comment by nrmancuso** [comment]
>ATTENTION: this might be good reason to cover our api package first, to let others use our methods with visually explicit contract.

I like this idea, let's decide which will be most important to users of Checkstyle as a library.

I think the following are probably good candidates:
[Nullness Checker](https://checkerframework.org/manual/#nullness-checker) for null pointer errors
[Resource Leak Checker](https://checkerframework.org/manual/#resource-leak-checker) for ensuring that resources are disposed of properly
...

**Comment by nrmancuso** [comment]
Let's do the following for suppression model:

Example:
```
Warning:  /home/runner/work/checkstyle/checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/api/Violation.java:[556,19] [return] incompatible types in return.
  type of expression: @Initialized @Nullable ResourceBundle
  method return type: @Initialized @NonNull ResourceBundle

```
Let's have fields:

`filename`: `checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/api/Violation.java:`
`specifier`: `return`
`message`: `incompatible types in return.`
`details`: `type of expression: @Initialized @Nullable ResourceBundle method return type: @Initialized @NonNull ResourceBundle`

This should be unique enough to provide valuable suppressions. I am ok on first pass of this issue to have suppressions that might suppress more than one violation (if that is even possible)

**Comment by romani** [comment]
Fix is merged
