### ISSUE TITLE
'R: Publish GitHub Page' failing at perform curl command but action status is succcess

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#12181]
https://github.com/checkstyle/checkstyle/actions/runs/3007811873

such execution should be failed.

**Comment by raghav-rama** [comment]
iam on it

**Comment by stoyanK7** [comment]
@romani I am getting `bad credentials` when trying to run this job on my fork. https://github.com/stoyanK7/checkstyle/actions/runs/3441249109/jobs/5740730073#step:3:125. Any ideas?

**Comment by nrmancuso** [comment]
@stoyanK7 please share details of token you are using, such as if it is PAT or built in, and the scopes you have granted if it is PAT

**Comment by stoyanK7** [comment]
Personal Access Token(PAT) -> Token(classic) -> All scopes possible are granted.

**Comment by nrmancuso** [comment]
Check required environment variables, length of obfuscated token looks suspect, as does absence of builder token https://github.com/stoyanK7/checkstyle/actions/runs/3441249109/jobs/5740730073#step:3:5

also, I remember some nuance in GitHub actions with PAT, maybe search for this

**Comment by nrmancuso** [comment]
@stoyanK7  if you figured out PAT issue, please share details here to help the next person that might have the same :)

**Comment by stoyanK7** [comment]
Oh, absolutely. PAT's permissions were alright and GitHub was picking it up correctly. I assumed` BUILDER_GITHUB_TOKEN` is something GitHub takes care of but it turns out you have to set it manually under `your checkstyle fork` -> `Settings` -> `Secrets` -> `Actions` -> `New repository secret` and you add it.

**Comment by rnveach** [comment]
Fix was merged
