### ISSUE TITLE
Remove call to Lexer#removeErrorListeners

### ISSUE THREAD

**Issue by nrmancuso** [checkstyle/checkstyle#12186]
Must be some  changes in Lexer/ ErrorListener:
```
New surviving mutation(s) found:

Source File: "JavaParser.java"
Class: "com.puppycrawl.tools.checksty le.JavaParser"
Method: "parse"
Line Contents: "lexer.removeErrorListeners();"
Mutator: "org.pitest.mutationtest.engine.gregor.mutators.VoidMethodCallMutator"
Description: "removed call to com/puppycrawl/tools/checkstyle/grammar/java/JavaLanguageLexer::removeErrorListeners"
Line Number: 88

```
We need to investigate.

In order to merge dependency update, we have allowed suppression of pitest. This suppression will be removed in work for this issue.

_Originally posted by @nrmancuso in https://github.com/checkstyle/checkstyle/issues/12172#issuecomment-1239185471_

**Comment by arinmodi** [comment]
Can I work on this ?

**Comment by nrmancuso** [comment]
@arinmodi issue is already assigned, please take another

**Comment by nrmancuso** [comment]
@Kevin222004 you can try it out, but please limit the time you spend. When I wrote the code in question, it was necessary to prevent a weird error message. I couldn't find the change on the ANTLR side that caused the behavior on our side to change.

**Comment by nrmancuso** [comment]
We put a lot of time into researching this change in behavior, and could not explain why we don't need to remove the default error listeners in the lexer any longer. We have a bunch of tests on this, which we will leave in place. I am going to remove the offending code to get rid of this mutation.

**Comment by romani** [comment]
There was reason on such code on old versions of antlr https://github.com/checkstyle/checkstyle/pull/13990#issuecomment-1810406927
