### ISSUE TITLE
Investigate why GITHUB token has no access to issues 

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#12182]
Investigate why GITHUB token has no access to issues 
example https://github.com/checkstyle/checkstyle/issues/12169#issuecomment-1239316050

https://docs.github.com/en/rest/overview/permissions-required-for-github-apps#permission-on-issues
https://docs.github.com/en/rest/overview/permissions-required-for-github-apps
https://docs.github.com/en/actions/security-guides/automatic-token-authentication

I think we need in action something like:
```
permissions:
  contents: issues
```
this will help us to remove BUILDER_GITHUB_TOKEN (personal token)

**Comment by stoyanK7** [comment]
Any suggestions on how to reproduce this? My personal token has full access and I am not sure trial and error is the way to go here.

**Comment by romani** [comment]
You can create your own repository, and not create own token but try to use token that is provided to all actions by default.

**Comment by stoyanK7** [comment]
Looking at [failed actions job](https://github.com/checkstyle/checkstyle/actions/runs/3007532049/jobs/4830183641) that is mentioned in your comment, [`GITHUB_TOKEN` has the default permissions](https://github.com/checkstyle/checkstyle/actions/runs/3007532049/jobs/4830183641#step:1:16):
```
GITHUB_TOKEN Permissions
  Contents: read
  Metadata: read
```

I checked out back to commit https://github.com/checkstyle/checkstyle/commit/46acc04a505826b8aae479be92a982454d558681 where the issue happened and [set the same permissions for my `GITHUB_TOKEN`](https://github.com/stoyanK7/checkstyle/actions/runs/3461395211/jobs/5779127890#step:1:16) too. Didn't get the same error for the part of script which runs `releasenotes-builder` but [rather at the end for updating the github tag page](https://github.com/stoyanK7/checkstyle/actions/runs/3461395211/jobs/5779127890#step:3:188).
```
 Updating Github tag page
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
{
  "message": "Resource not accessible by integration",
  "documentation_url": "https://docs.github.com/rest/reference/repos#update-a-release"
}
100  2047  100   146  100  1901    466   6079 --:--:-- --:--:-- --:--:--  6560
```
