### ISSUE TITLE
Minor word missing in checkstyle docs

### ISSUE THREAD

**Issue by NitishKumar06** [checkstyle/checkstyle#12203]
The following link (https://checkstyle.org/contributing.html#Quality_matters) contains the information to build the checkstyle project, add a new feature, etc.

There's a line that says `If you add new end user features (Check, Filter, ....), remember to document them in JavaDoc of java classes and xdoc files that used to generate that site. Please recheck site and all bundles generation by mvn clean site`.

I found certain words that are missing in the line have the chance to be improved for eg. "document the in JavaDOc of java classes and xdoc files that 'are' used to generate that site.' should be there. Notice, the addition of 'are'.

**Comment by romani** [comment]
Please send PR

**Comment by romani** [comment]
If you notice more problems like this, you can just send a PR , and make commit message to have prefix "doc: "

**Comment by NitishKumar06** [comment]
Alright, I'm working on it.
