### ISSUE TITLE
Debug documentation is not clear

### ISSUE THREAD

**Issue by NitishKumar06** [checkstyle/checkstyle#12207]
The following link (https://checkstyle.org/idea.html#Debug)  shows how to debug the application. Although, when you look at it carefully, you'll find that the documentation needs to be improved.

The line _Open the Check's source file by double-click on it in a source tree as is shown:_  creates confusion. The image shows that the file that has been made run is present in the `src/main/java/checks`. Althoug when you try to look for the file, you'll find that there's no run option visible on the directory.

The correct directory should be `src/test/java/checks` where you can debug and run the test cases.

Solution: Modify the Debug documentation

**Comment by NitishKumar06** [comment]
I'm working on it. I'd like to know how do we see the changes on our website? In short, how do we run the website locally so that we can see the changes that we implemented?

**Comment by nrmancuso** [comment]
Please see https://github.com/checkstyle/checkstyle/issues/12203#issuecomment-1248034815, you did not need to create this issue. See https://github.com/checkstyle/checkstyle/wiki/How-to-run-certain-phases-and-validations for how to generate our website.

**Comment by NitishKumar06** [comment]
The rest of the points mentioned are needed to be made fixed upon which I'm working!

**Comment by romani** [comment]
@NitishKumar06 , please send update 
source of page is here - https://github.com/checkstyle/checkstyle/blob/master/src/xdocs/idea.xml

**Comment by NitishKumar06** [comment]
@romani Yes I'm working on it. I'll soon raise a PR as I'm going through other portion of documents as well to keep in mind.

**Comment by romani** [comment]
Fix is merged
