### ISSUE TITLE
Add method to ignore unstable checker framework violations.

### ISSUE THREAD

**Issue by Vyom-Yadav** [checkstyle/checkstyle#12210]
From https://github.com/checkstyle/checkstyle/actions/runs/3074040335/jobs/4966560151

link to Suppression :
https://github.com/checkstyle/checkstyle/blob/6335dd84f14a40150e7eb7a037f9a20e5f189236/.ci/checker-framework-suppressions/checker-framework-nullness-optional-interning-suppressions.xml#L2963-L2973

```
New surviving error(s) found:

File Name: "checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/HandlerFactory.java"
Specifier: "argument"
Message: "incompatible argument for parameter constructor of invokeConstructor."
Line Contents: "handlerCtor, indentCheck, ast, parent);"
Line Number: 164
Details: found   : @Initialized @Nullable Constructor&lt;capture#394 extends @Initialized @Nullable Object&gt;
         required: @Initialized @NonNull Constructor&lt;capture#394 extends @Initialized @Nullable Object&gt;
```

https://github.com/checkstyle/checkstyle/blob/6335dd84f14a40150e7eb7a037f9a20e5f189236/.ci/checker-framework-suppressions/checker-framework-nullness-optional-interning-suppressions.xml#L3404-L3414
```
File Name: "checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/HandlerFactory.java"
Specifier: "type.argument"
Message: "incompatible type argument for type parameter T extends Object of invokeConstructor."
Line Contents: "resultHandler = (AbstractExpressionHandler) CommonUtil.invokeConstructor("
Line Number: 163
Details: found   : capture#394[ extends @UnknownKeyFor Object super @KeyForBottom Void]
         required: [extends @UnknownKeyFor Object super @UnknownKeyFor NullType]
```

These errors are unstable because `capture#` keeps changing with every run. Although these errors are present in the current suppression model as `unstable = "true"` but it does not work because unlike pitest unstable suppression model, here the content of the error changes.

Another one is:
https://github.com/checkstyle/checkstyle/blob/6335dd84f14a40150e7eb7a037f9a20e5f189236/.ci/checker-framework-suppressions/checker-framework-methods-resource-fenum-suppressions.xml#L80-L89
```
New surviving error(s) found:

File Name: "checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTask.java"
Specifier: "required.method.not.called"
Message: "@MustCall method close may not have been invoked on temp-var-20910 or any of its aliases."
Line Contents: "sarifLogger = new SarifLogger(new LogOutputStream(task, Project.MSG_INFO),"
Line Number: 705
Details: The type of object is: org.apache.tools.ant.taskdefs.LogOutputStream.
         Reason for going out of scope: possible exceptional exit due to new SarifLogger(new LogOutputStream(task, Project.MSG_INFO), AutomaticBean.OutputStreamOptions.CLOSE) with exception type java.io.IOException
```

Here `temp-var-\d+` keeps on changing, this field is present in `Message:`

**Comment by rnveach** [comment]
If it is always `capture#\d+`, then we could just do a blind string replace and remove it.

**Comment by Vyom-Yadav** [comment]
> If it is always `capture#\d+`, then we could just do a blind string replace and remove it.

We got a new one `temp-var-\d+`, and we could get new ones in the future, don't think replacing would be a very stable way.

**Comment by Vyom-Yadav** [comment]
Or for unstable errors, we could just remove any numbers (just while comparing) present in `<details>` and `<message>` and then we can compare the errors.

**Comment by romani** [comment]
lets remove details for now, to make fix quicker.
Details might change from version to version, lets try to live without considering of it for failure.

**Comment by romani** [comment]
Fix is merged
