### ISSUE TITLE
Rename all 'Checker-Framework / checker-..' actions 

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#12229]
On mobile long names are not good
We have "Checker-Framework / checker-..."
is what visible.
We need to rename them to be 'Checker / checker-...'

**Comment by NitishKumar06** [comment]
I'm working on this.

@romani Could you provide a link/reference where could I find "Checker-Framerwork/checker-...", It'd be helpful!

**Comment by romani** [comment]
Just search it in yml files, all is in sources of our repository

**Comment by rnveach** [comment]
@romani This issue is complete, right?
