### ISSUE TITLE
Create CI task to fail PR if merge commit exists

### ISSUE THREAD

**Issue by nrmancuso** [checkstyle/checkstyle#12259]
Noticed at https://github.com/checkstyle/checkstyle/pull/12256#issuecomment-1270588550, even though we have a bunch of checks in place for commit message, stale PR branch, etc., we do not fail CI for merge commits in PR branches.

I see github action https://github.com/greenled/no-merge-commits-check, maybe we can re-use the [script](https://github.com/greenled/no-merge-commits-check/blob/main/entrypoint.sh) in this repo and create a CI task to fail build if merge commits exist, and provide a message with link to https://checkstyle.org/beginning_development.html#Starting_Development .

**Comment by romani** [comment]
We need to recheck why our commit validation is not catching this.

**Comment by rnveach** [comment]
https://github.com/checkstyle/checkstyle/blob/70bbcd835e7d51062abd2801d3329b791854891c/src/test/java/com/puppycrawl/tools/checkstyle/internal/CommitValidationTest.java#L260
https://github.com/checkstyle/checkstyle/blob/70bbcd835e7d51062abd2801d3329b791854891c/src/test/java/com/puppycrawl/tools/checkstyle/internal/CommitValidationTest.java#L372

Merge commits will fail CI as travis always works as a merge commit even if there is none in PR.

**Comment by nrmancuso** [comment]
Sounds like shell script is the best way to handle this case then.

**Comment by romani** [comment]
What is we made update in code and allow skip of merged only if some system variable is defined. And set it in Travis. All others will run without allowance of merge commit.

**Comment by rnveach** [comment]
> system variable is defined. And set it in Travis

I remember we had issues with different CIs and looking at git history similar to PR view. Travis was just the one I remember clearly.

**Comment by romani** [comment]
At time we created this Junit validation Travis probably was the only CI we had.

**Comment by nrmancuso** [comment]
I am on it
