### ISSUE TITLE
Resolve Pitest suppression for AbstractParenPadCheck

### ISSUE THREAD

**Issue by Kevin222004** [checkstyle/checkstyle#12251]
Related to https://github.com/checkstyle/checkstyle/issues/7797 

 kill mutation 
https://github.com/checkstyle/checkstyle/blob/de37e02b799305fa9309f162f8961c4297fce865/.ci/pitest-suppressions/pitest-whitespace-suppressions.xml#L17
for AbstractParenPadCheck

**Comment by romani** [comment]
Do you understand what mutation is actually done to code?

**Comment by Kevin222004** [comment]
> Do you understand what mutation is actually done to code?
> 
> https://pitest.org/quickstart/mutators/#EXPERIMENTAL_NAKED_RECEIVER

yes I have described full detail in thread

**Comment by nrmancuso** [comment]
Closed via #12258
