### ISSUE TITLE
Resolve Pitest suppression for OperatorWrapCheck

### ISSUE THREAD

**Issue by Kevin222004** [checkstyle/checkstyle#12266]
Related to https://github.com/checkstyle/checkstyle/issues/7797

kill mutation
https://github.com/checkstyle/checkstyle/blob/ba8efc21659a66600a25ed662b62d1b1cb7611ea/.ci/pitest-suppressions/pitest-whitespace-suppressions.xml#L143
and 
https://github.com/checkstyle/checkstyle/blob/ba8efc21659a66600a25ed662b62d1b1cb7611ea/.ci/pitest-suppressions/pitest-whitespace-suppressions.xml#L152

for OperatorWrapCheck

**Comment by rnveach** [comment]
Fixed was merged
