### ISSUE TITLE
Resolve  Pitest suppression for AbstractParenPadCheck - 2

### ISSUE THREAD

**Issue by Kevin222004** [checkstyle/checkstyle#12260]
Related to https://github.com/checkstyle/checkstyle/issues/7797

kill mutation

https://github.com/checkstyle/checkstyle/blob/70bbcd835e7d51062abd2801d3329b791854891c/.ci/pitest-suppressions/pitest-whitespace-suppressions.xml#L8

for AbstractParenPadCheck

**Comment by rnveach** [comment]
Fix was merged
