### ISSUE TITLE
Resolve Pitest suppression for MethodParamPadCheck 

### ISSUE THREAD

**Issue by Kevin222004** [checkstyle/checkstyle#12264]
Related to https://github.com/checkstyle/checkstyle/issues/7797

kill mutation
https://github.com/checkstyle/checkstyle/blob/ba8efc21659a66600a25ed662b62d1b1cb7611ea/.ci/pitest-suppressions/pitest-whitespace-suppressions.xml#L134

for MethodParamPadCheck

**Comment by rnveach** [comment]
Fix was merged
