### ISSUE TITLE
Resolve Pitest suppression for EmptyForInitializerPadCheck

### ISSUE THREAD

**Issue by Kevin222004** [checkstyle/checkstyle#12265]
Related to https://github.com/checkstyle/checkstyle/issues/7797

kill mutation
https://github.com/checkstyle/checkstyle/blob/ba8efc21659a66600a25ed662b62d1b1cb7611ea/.ci/pitest-suppressions/pitest-whitespace-suppressions.xml#L17
and
https://github.com/checkstyle/checkstyle/blob/ba8efc21659a66600a25ed662b62d1b1cb7611ea/.ci/pitest-suppressions/pitest-whitespace-suppressions.xml#L26

for EmptyForInitializerPadCheck

**Comment by rnveach** [comment]
Fix was merged
