### ISSUE TITLE
Resolve Pitest suppression for EmptyForIteratorPadCheck

### ISSUE THREAD

**Issue by Kevin222004** [checkstyle/checkstyle#12261]
Related to https://github.com/checkstyle/checkstyle/issues/7797

kill mutation
https://github.com/checkstyle/checkstyle/blob/ba8efc21659a66600a25ed662b62d1b1cb7611ea/.ci/pitest-suppressions/pitest-whitespace-suppressions.xml#L53
and 
https://github.com/checkstyle/checkstyle/blob/ba8efc21659a66600a25ed662b62d1b1cb7611ea/.ci/pitest-suppressions/pitest-whitespace-suppressions.xml#L44

 for EmptyForIteratorPadCheck

**Comment by romani** [comment]
Can we fix all similar issues at one issue and multiple PR or one PR?

**Comment by nrmancuso** [comment]
If we are only adding tests, I think it would be fine to resolve a few of these in the scope of one PR/issue.

**Comment by rnveach** [comment]
My wording to him before this issue was:

> Single mutation issues was just for getting started to ensure we can confirm communication and confirm understanding of pitest and how it functions. Since this check only has 2 mutations, please just create 1 more issue of a single mutation and afterwards I think we can do multiple. However, even with multiple it is best to keep separate PRs between adding tests and changing production code. Adding tests is easier to merge then changing production code which will require a closer review and regression reports.
Beware, if PRs start to get complex we will want them split more, so I would be careful on putting too much into a single PR. It is not that much more work to create separate branches and PRs.

`this check` was `AbstractParenPadCheck` at the time.

**Comment by Kevin222004** [comment]
I have updated the pr description

**Comment by rnveach** [comment]
Fix was merged
