### ISSUE TITLE
Resolve Pitest suppression for EmptyLineSeperator

### ISSUE THREAD

**Issue by Kevin222004** [checkstyle/checkstyle#12278]
Related to https://github.com/checkstyle/checkstyle/issues/7797

kill mutation
https://github.com/checkstyle/checkstyle/blob/49a93e4ab83c4a25d25c10e16a19dafe40595027/.ci/pitest-suppressions/pitest-whitespace-suppressions.xml#L30-L37
and 
https://github.com/checkstyle/checkstyle/blob/49a93e4ab83c4a25d25c10e16a19dafe40595027/.ci/pitest-suppressions/pitest-whitespace-suppressions.xml#L57-L64

**Comment by NitishKumar06** [comment]
I'm working on this.

**Comment by rnveach** [comment]
This will be resolved under https://github.com/checkstyle/checkstyle/issues/12601 so I am closing this.
