### ISSUE TITLE
Resolve Pitest suppression for EmptyForInitializerPad-2

### ISSUE THREAD

**Issue by Kevin222004** [checkstyle/checkstyle#12275]
Related to https://github.com/checkstyle/checkstyle/issues/7797

kill mutation

https://github.com/checkstyle/checkstyle/blob/357ba1ed99f82b07d5663d23091ca9c10bb382b8/.ci/pitest-suppressions/pitest-whitespace-suppressions.xml#L4-L9

 for EmptyForInitializerPad

**Comment by Kevin222004** [comment]
As of know it is different mutation, so I have taken just one mutation in this pr

**Comment by romani** [comment]
fix is merged
