### ISSUE TITLE
Resolve Pitest suppression for ParenPad

### ISSUE THREAD

**Issue by Kevin222004** [checkstyle/checkstyle#12282]
Related to https://github.com/checkstyle/checkstyle/issues/7797

kill mutation
https://github.com/checkstyle/checkstyle/blob/fa6856985e3eb32f11ae63e56c19fc2181a50d06/.ci/pitest-suppressions/pitest-whitespace-suppressions.xml#L93-L100

**Comment by Gairick52** [comment]
@Kevin222004 please suggest me some good first issues

**Comment by romani** [comment]
@Gairick52 , please read https://github.com/checkstyle/checkstyle/wiki/To-GSoC-participant, there are first,second,thrird issue to let you gradually be introduced to project.

**Comment by Gairick52** [comment]
@romani thank you very much

**Comment by Kevin222004** [comment]
@rnveach We have currently this line of code which is mutated https://github.com/checkstyle/checkstyle/blob/ad27aa0feb4804cf3a14430b2cb90c3d13dbe532/src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/ParenPadCheck.java#L257

and the source code for this mutated code is just to remove it

**Comment by rnveach** [comment]
> the source code for this mutated code is just to remove it

The mutation is not to remove it.

**Comment by Kevin222004** [comment]
@rnveach yes we don't have to remove the switch case according to wiki I have also done like that before. and know it is clear to me 

when we are making the changes like that I am getting errors in three input file i am sharing one with you 
https://github.com/checkstyle/checkstyle/blob/ad27aa0feb4804cf3a14430b2cb90c3d13dbe532/src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/parenpad/InputParenPadLeftRightAndNoSpace1.java#L122-L126
here the violation is missing in line 125 at 2 places 
according to the current scenario checkstyle don't generate the violation for any case for `QUESTION` I just want to know it is expected a violation in such condition like line no 126 in same file according to its config comment msg

**Comment by rnveach** [comment]
If you make a change to mimic a mutation and our test fails, then either the mutation you applied isn't correct or there is more going on with pitest than the mutation alone (caching, etc...).  Normally tests do not fail with the mutation applied.

Please provide me the step by step we request. Provide me the mutated branch pushed to the server. Let me know if tests fail with the mutation applied.

**Comment by romani** [comment]
Please send PR with mutation to let us see all details.

Please try to remove all other "case" one by one.

**Comment by rnveach** [comment]
Fix was merged, complex understanding of pitest is at https://github.com/checkstyle/checkstyle/pull/12318#issuecomment-1286800059 and simpler understanding at https://github.com/checkstyle/checkstyle/pull/12318#issuecomment-1287030155
