### ISSUE TITLE
Resolve Pitest suppression for EmptyLineSeperator-2

### ISSUE THREAD

**Issue by Kevin222004** [checkstyle/checkstyle#12281]
Related to https://github.com/checkstyle/checkstyle/issues/7797

kill mutation
https://github.com/checkstyle/checkstyle/blob/fa6856985e3eb32f11ae63e56c19fc2181a50d06/.ci/pitest-suppressions/pitest-whitespace-suppressions.xml#L66-L73
and
https://github.com/checkstyle/checkstyle/blob/fa6856985e3eb32f11ae63e56c19fc2181a50d06/.ci/pitest-suppressions/pitest-whitespace-suppressions.xml#L66-L73
and
https://github.com/checkstyle/checkstyle/blob/fa6856985e3eb32f11ae63e56c19fc2181a50d06/.ci/pitest-suppressions/pitest-whitespace-suppressions.xml#L39-L46

**Comment by Kevin222004** [comment]
I am on it, Make pr when it is approved

**Comment by rnveach** [comment]
This will be resolved under #12601 so I am closing this.
