### ISSUE TITLE
Resolve Pitest suppression for SingleSpaceSeparatorCheck

### ISSUE THREAD

**Issue by Kevin222004** [checkstyle/checkstyle#12280]
Related to https://github.com/checkstyle/checkstyle/issues/7797

kill mutation
https://github.com/checkstyle/checkstyle/blob/fa6856985e3eb32f11ae63e56c19fc2181a50d06/.ci/pitest-suppressions/pitest-whitespace-suppressions.xml#L120-L136

**Comment by Kevin222004** [comment]
I am working on it, send pr when its approved

**Comment by rnveach** [comment]
I am closing this and moving it under #12594 .
