### ISSUE TITLE
Resolve Pitest suppression for block profile

### ISSUE THREAD

**Issue by Kevin222004** [checkstyle/checkstyle#12296]
Related to https://github.com/checkstyle/checkstyle/issues/7797

kill mutation

https://github.com/checkstyle/checkstyle/blob/b51b4af16093835732716d8237e45658b4afea04/.ci/pitest-suppressions/pitest-blocks-suppressions.xml#L2-L10
and
https://github.com/checkstyle/checkstyle/blob/b51b4af16093835732716d8237e45658b4afea04/.ci/pitest-suppressions/pitest-blocks-suppressions.xml#L12-L19
and 
https://github.com/checkstyle/checkstyle/blob/b51b4af16093835732716d8237e45658b4afea04/.ci/pitest-suppressions/pitest-blocks-suppressions.xml#L30-L37
and 
https://github.com/checkstyle/checkstyle/blob/b51b4af16093835732716d8237e45658b4afea04/.ci/pitest-suppressions/pitest-blocks-suppressions.xml#L39-L46
and 
https://github.com/checkstyle/checkstyle/blob/b51b4af16093835732716d8237e45658b4afea04/.ci/pitest-suppressions/pitest-blocks-suppressions.xml#L84-L91
and 
https://github.com/checkstyle/checkstyle/blob/b51b4af16093835732716d8237e45658b4afea04/.ci/pitest-suppressions/pitest-blocks-suppressions.xml#L93-L100

**Comment by Kevin222004** [comment]
I have contained a lots of mutation just a single pr because it is as similar as https://github.com/checkstyle/checkstyle/commit/4f9c2a47f9e4941f79559626a00b217ccdb35ad4

only requirement is of test file

**Comment by Kevin222004** [comment]
I am on it

**Comment by rnveach** [comment]
@Kevin222004 Did that PR resolve this issue?

**Comment by Kevin222004** [comment]
> @Kevin222004 Did that PR resolve this issue?
> 
> Edit: From the mutations it looks like it did, let me know if I am wrong.

Report is actually ready
May be , I forget to put it after making pr

**Comment by Kevin222004** [comment]
1) EmptyBlockCheck
 
 https://kevin222004.github.io/blocks/com.puppycrawl.tools.checkstyle.checks.blocks/EmptyBlockCheck.java.html --->mutation at line 201

after killing mutation 
https://kevin222004.github.io/solvedblocks/com.puppycrawl.tools.checkstyle.checks.blocks/EmptyBlockCheck.java.html

2) LeftCurlyCheck

https://kevin222004.github.io/blocks/com.puppycrawl.tools.checkstyle.checks.blocks/LeftCurlyCheck.java.html ---> mutation at line 265

after killing it 

https://kevin222004.github.io/solvedblocks/com.puppycrawl.tools.checkstyle.checks.blocks/LeftCurlyCheck.java.html

3) RightCurlyCheck

https://kevin222004.github.io/blocks/com.puppycrawl.tools.checkstyle.checks.blocks/RightCurlyCheck.java.html ---> mutation at lien 260

after Killing it 

https://kevin222004.github.io/solvedblocks/com.puppycrawl.tools.checkstyle.checks.blocks/RightCurlyCheck.java.html
