### ISSUE TITLE
Fix empty html page for extending Checkstyle

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#1231]
Page https://github.com/checkstyle/checkstyle/blob/master/src/xdocs/extending.xml is empty but it should as minimum give links too all its child pages http://checkstyle.sourceforge.net/extending.html

**Comment by Vladlis** [comment]
http://checkstyle.sourceforge.net/style_configs.html is also empty

**Comment by romani** [comment]
merged.
