### ISSUE TITLE
Resolve Pitest suppression for Javadoc profile

### ISSUE THREAD

**Issue by Kevin222004** [checkstyle/checkstyle#12315]
Related to https://github.com/checkstyle/checkstyle/issues/7797

kill mutation
https://github.com/checkstyle/checkstyle/blob/ad27aa0feb4804cf3a14430b2cb90c3d13dbe532/.ci/pitest-suppressions/pitest-javadoc-suppressions.xml#L93-L109
and
https://github.com/checkstyle/checkstyle/blob/67a577de8adc38b9d3fb039fbcbb38c9088d3a1a/.ci/pitest-suppressions/pitest-javadoc-suppressions.xml#L543-L550
and
https://github.com/checkstyle/checkstyle/blob/67a577de8adc38b9d3fb039fbcbb38c9088d3a1a/.ci/pitest-suppressions/pitest-javadoc-suppressions.xml#L561-L568
and
https://github.com/checkstyle/checkstyle/blob/ad27aa0feb4804cf3a14430b2cb90c3d13dbe532/.ci/pitest-suppressions/pitest-javadoc-suppressions.xml#L768-L775

**Comment by romani** [comment]
Fix is merged
