### ISSUE TITLE
checker-framework.groovy depends too much on name of repo

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#12311]
From https://github.com/checkstyle/checkstyle/issues/12232#issuecomment-1258515152

It seems to be the groovy script requires the top checkstyle folder of source to be named `checkstyle`.
https://github.com/checkstyle/checkstyle/blob/c6005cbec365444c3f4704725355ddfd3e588bab/.ci/checker-framework.groovy#L170
In this case, my folder was named `checkstyle2` as this process takes a while to run and was starting to use 2 cloned repos to speed things up.

I don't think should be a requirement. We should look instead for `src/(it|main|test)/java`.

I think we can simply remove this reference, I don't think we will have files other than in our repo in plugin output.

**Comment by romani** [comment]
@Vyom-Yadav , can you help us to resolve this issue ?

**Comment by nrmancuso** [comment]
I will take a look at this

**Comment by romani** [comment]
Fix is merged
