### ISSUE TITLE
Resolve Pitest suppression for misc profile

### ISSUE THREAD

**Issue by Kevin222004** [checkstyle/checkstyle#12314]
Related to https://github.com/checkstyle/checkstyle/issues/7797

kill mutation
https://github.com/checkstyle/checkstyle/blob/ad27aa0feb4804cf3a14430b2cb90c3d13dbe532/.ci/pitest-suppressions/pitest-misc-suppressions.xml#L39-L46
and
https://github.com/checkstyle/checkstyle/blob/ad27aa0feb4804cf3a14430b2cb90c3d13dbe532/.ci/pitest-suppressions/pitest-misc-suppressions.xml#L48-L55

**Comment by romani** [comment]
Fix is merged
