### ISSUE TITLE
Resolve Pitest suppression for AccessModifierOption

### ISSUE THREAD

**Issue by shubh220922** [checkstyle/checkstyle#12326]
Reference from https://github.com/checkstyle/checkstyle/issues/7797

Kill the mutation

https://github.com/checkstyle/checkstyle/blob/4c7c3cc832a2b6ddefa529a816008880a9db9255/.ci/pitest-suppressions/pitest-naming-suppressions.xml#L12-L19

**Comment by shubh220922** [comment]
I am on it.

**Comment by romani** [comment]
Fix is merged
