### ISSUE TITLE
Resolve Pitest for Annotation Profile

### ISSUE THREAD

**Issue by Kevin222004** [checkstyle/checkstyle#12329]
Related to https://github.com/checkstyle/checkstyle/issues/7797

kill mutation
https://github.com/checkstyle/checkstyle/blob/aad6891485ab1ea6b5ecaedbb5bd5cc03539f2b0/.ci/pitest-suppressions/pitest-annotation-suppressions.xml#L1-L10
and
https://github.com/checkstyle/checkstyle/blob/aad6891485ab1ea6b5ecaedbb5bd5cc03539f2b0/.ci/pitest-suppressions/pitest-annotation-suppressions.xml#L12-L19
and
https://github.com/checkstyle/checkstyle/blob/aad6891485ab1ea6b5ecaedbb5bd5cc03539f2b0/.ci/pitest-suppressions/pitest-annotation-suppressions.xml#L21-L28

**Comment by Kevin222004** [comment]
Now, I guess I will handle this all in one pr by just solving one at a time in my local

**Comment by romani** [comment]
I highly recommend to send PR as soon as killed one mutation (or batch it by day of work). The smaller PR the quicker it is merged.

**Comment by rnveach** [comment]
This will be resolved in https://github.com/checkstyle/checkstyle/issues/12591 which is waiting on pitest plugin changes, so I am closing this.
