### ISSUE TITLE
Remove CheckstyleAntTask's classpath

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#12338]
Identified at https://github.com/checkstyle/checkstyle/pull/12335#discussion_r1002612965 ,

https://github.com/checkstyle/checkstyle/blob/527578f9a89abd7136552763bf942f9cb334c203/src/main/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTask.java#L92

This is left over when we had checks against the classpath. Code was removed at 
https://github.com/checkstyle/checkstyle/commit/145160f5e21b80c27dc93a1904fe33b9afd4f212#diff-56ee8828e56742120dd2db0061ea82707b7b27c5c0f9e9963a8cefe3aa2dbc3aL405
as part of https://github.com/checkstyle/checkstyle/issues/3773

This is a custom property sent to our Checkstyle Ant. It is not related to Java's classpath loader.
https://github.com/checkstyle/checkstyle/blob/527578f9a89abd7136552763bf942f9cb334c203/src/main/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTask.java#L92

Java's classpath loader is at https://github.com/checkstyle/checkstyle/blob/af99c7d552ee8470cd07590211e6cdf1a8881050/config/ant-phase-verify.xml#L10-L12 .

If you examine the code, you will see this property is only used to display as an error if an exception occurs.
https://github.com/checkstyle/checkstyle/blob/527578f9a89abd7136552763bf942f9cb334c203/src/main/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTask.java#L430-L431

CI is still running and passing with it removed.

We should deprecate it unless we want to full remove it in one go.

=====

**Migration Notes**

Gradle users will need to remove any assignments of the classpath as it will no longer exist.
Example: https://github.com/pgjdbc/pgjdbc/commit/327e6250ae7c00eb548923daf32172d60ba8852d

Ant users will need to remove `classpath` from inside the Checkstyle task as it will not be available anymore.
See https://github.com/sevntu-checkstyle/checkstyle-samples/commit/e42427807e87a887def7e92bbc5fa4948c057cd8

**Comment by romani** [comment]
If we did this property do nothing long time ago, we can remove any time now.

**Comment by rnveach** [comment]
I am fine with that. I just didn't think we would want to remove instantly.

**Comment by romani** [comment]
We do not have deprecation warning messages. We usually make it not functional to not break config loading phase on user side, but we change behavior.
Later on do hard removal.

**Comment by nrmancuso** [comment]
```
    Execution failed for task ':benchmarks:checkstyleJmh':02:49
        : checkstyle doesn't support the nested "classpath" element.02:49
            at org.apache.tools.ant.UnknownElement.handleChildren(UnknownElement.java:372)02:49
            at org.apache.tools.ant.UnknownElement.configure(UnknownElement.java:206)02:49
            at org.apache.tools.ant.UnknownElement.maybeConfigure(UnknownElement.java:165)02:49
            at org.gradle.api.internal.project.ant.BasicAntBuilder.nodeCompleted(BasicAntBuilder.java:80)02:49
            at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:484)02:49
            at ...
org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:30)02:49
            at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:54)02:49
            at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:40)02:49
            Caused by: The <checkstyle> type doesn't support the nested "classpath" element.

```
Gradle users will need to update gradle version to 7.5+ in order to use next release of checkstyle (10.6)

**Comment by strkkk** [comment]
fix is merged
