### ISSUE TITLE
Resolve pitest for profile misc-2

### ISSUE THREAD

**Issue by Kevin222004** [checkstyle/checkstyle#12334]
Related to https://github.com/checkstyle/checkstyle/issues/7797

kill mutation
https://github.com/checkstyle/checkstyle/blob/aad6891485ab1ea6b5ecaedbb5bd5cc03539f2b0/.ci/pitest-suppressions/pitest-misc-suppressions.xml#L147-L163

**Comment by nrmancuso** [comment]
@Kevin222004 please reference https://github.com/checkstyle/checkstyle/issues/12341 for any new pitest issues as you create them, this will help others to find your issues/PRs as examples in the future.

**Comment by romani** [comment]
as of now, all misc survivals are resolved by other PRs of this project
