### ISSUE TITLE
Resolve Pitest for profile coding-2

### ISSUE THREAD

**Issue by Kevin222004** [checkstyle/checkstyle#12331]
Related to https://github.com/checkstyle/checkstyle/issues/7797

kill mutation:-
part - 1
https://github.com/checkstyle/checkstyle/blob/aad6891485ab1ea6b5ecaedbb5bd5cc03539f2b0/.ci/pitest-suppressions/pitest-coding-2-suppressions.xml#L3-L28
and 
part - 2
https://github.com/checkstyle/checkstyle/blob/aad6891485ab1ea6b5ecaedbb5bd5cc03539f2b0/.ci/pitest-suppressions/pitest-coding-2-suppressions.xml#L84-L91
and 
part - 3
https://github.com/checkstyle/checkstyle/blob/aad6891485ab1ea6b5ecaedbb5bd5cc03539f2b0/.ci/pitest-suppressions/pitest-coding-2-suppressions.xml#L174-L370

**Comment by romani** [comment]
I recommend to keep each mutation separately to not block easy mutations

**Comment by Kevin222004** [comment]
@romani @rnveach according to https://checkstyle.org/config_coding.html#FinalLocalVariable

```
cat Test.java
class Test {

    Test(int a) {
    }

}
```
```
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
    <module name="TreeWalker">
        <module name="FinalLocalVariableCheck">
        <property name="tokens" value="PARAMETER_DEF" />
        </module>
    </module>
</module>   
```
```
output
kevin@inspiron-15-5510:~/Desktop/check_style$ java -jar checkstyle-10.6.0-all.jar -c config.xml Test.java
Starting audit...
[ERROR] /home/kevin/Desktop/check_style/Test.java:3:14: Variable 'a' should be declared final. [FinalLocalVariable]
Audit done.
Checkstyle ends with 1 errors.
```

I have a doubt here should we really expect violation in constructor here

**Comment by rnveach** [comment]
@Kevin222004 Why do you doubt?
https://checkstyle.org/config_coding.html#FinalLocalVariable_Description
https://checkstyle.org/config_coding.html#FinalLocalVariable_Examples
> The check can be configured to also check that unchanged parameters are declared final. 
> static int foo(int x, int y) { //violations, parameters should be final

**Comment by Kevin222004** [comment]
it might be lack of my knowledge i have not seen this type of code before that's why

**Comment by nrmancuso** [comment]
>it might be lack of my knowledge i have not seen this type of code before that's why

Yes, in general, modifiers on parameters have fallen out of favor, especially with the advent of static analysis/IDEs that will flag reassigned parameters for you. However, this code is still valid.

**Comment by Kevin222004** [comment]
@rnveach in this issue all the mutation except 
https://github.com/checkstyle/checkstyle/blob/811983e0f89edf2419b9165ca60bb04a7c3c1ea6/config/pitest-suppressions/pitest-coding-2-suppressions.xml#L2-L19
has been killed can you please help with this
this is the different one may be, 

according to pit the 
https://github.com/checkstyle/checkstyle/blob/811983e0f89edf2419b9165ca60bb04a7c3c1ea6/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/ExplicitInitializationCheck.java#L269-L284
in this method case value 138 and 139 is mutated but their is no any token type defined in code which value is 138 and 139

**Comment by Kevin222004** [comment]
Yes it is looking like https://github.com/hcoles/pitest/issues/1137.  the two extra cases which are not available in code they are not giving test failure in default  as well in without default case

**Comment by nrmancuso** [comment]
@Kevin222004 what do we have left to do to close this issue?

**Comment by Kevin222004** [comment]
@nrmancuso According to the issur description part-2 and part-3 has been done but in part 1 
this two are left not sure this is pitest bug or what https://github.com/checkstyle/checkstyle/issues/12331#issuecomment-1379531007

**Comment by romani** [comment]
there is not such survivals any more in project, see referenced commits or PR in project on how it was fixed
