### ISSUE TITLE
Resolve pitest for profile metrics

### ISSUE THREAD

**Issue by Kevin222004** [checkstyle/checkstyle#12333]
Related to https://github.com/checkstyle/checkstyle/issues/7797

kill mutation
https://github.com/checkstyle/checkstyle/blob/aad6891485ab1ea6b5ecaedbb5bd5cc03539f2b0/.ci/pitest-suppressions/pitest-metrics-suppressions.xml#L102-L145

**Comment by nrmancuso** [comment]
@Kevin222004 what do we have left to do here?

**Comment by Kevin222004** [comment]
@nrmancuso all the mutations in this issue are killed 

nothing left

**Comment by nrmancuso** [comment]
Closed via #12549
