### ISSUE TITLE
Resolve Pitest for Block Profile-2

### ISSUE THREAD

**Issue by Kevin222004** [checkstyle/checkstyle#12330]
Related to https://github.com/checkstyle/checkstyle/issues/7797

kill mutation
https://github.com/checkstyle/checkstyle/blob/aad6891485ab1ea6b5ecaedbb5bd5cc03539f2b0/.ci/pitest-suppressions/pitest-blocks-suppressions.xml#L12-L19

**Comment by Kevin222004** [comment]
I am on it

**Comment by romani** [comment]
I removed from description 
>and
https://github.com/checkstyle/checkstyle/blob/aad6891485ab1ea6b5ecaedbb5bd5cc03539f2b0/.ci/pitest-suppressions/pitest-blocks-suppressions.xml#L48-L145

it is better to make issue for each suppression individually, as fixing it is not easy.
