### ISSUE TITLE
Feature request: add FATAL SeverityLevel

### ISSUE THREAD

**Issue by pcbouman-eur** [checkstyle/checkstyle#12355]
I have read check documentation: https://checkstyle.org/config_xxxxxx.html#NameOfAffectedCheck
I have downloaded the latest cli from: https://checkstyle.org/cmdline.html#Download_and_Run
I have executed the cli and show small examples below.

To summarize my feature request, I would like to have checkstyle support the same severity levels as PMD, which has a *fatal* severity level that checkstyle lacks. Technically, this seems to involve adding a single additional entry to the [SeverityLevel.java](../blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/SeverityLevel.java) enum and doing so seems to not break any tests or running `mvn package` on the full source tree of checkstyle.

**How it works Now:**

I have deviated from the template because it is not helpful in communicating my feature request clearly, given that checkstyle currently works as intended, as long as my configuration XML defines rules as follows:

```xml
		<module name="MissingJavadocType">
			<property name="severity" value="error" />
		</module>
```

I am using both checkstyle and PMD in a automated grading platform (Codegrade) to generate automated style feedback for student assignments. This platform supports four severity levels for general linters: "info", "warning", "error" and "fatal", which all exist in PMD, but of which only three exist in checkstyle.

What I would like define a rule as follows (note the severity level `fatal`), so I can use the same levels that are available in PMD. Checkstyle obviously fails reading in the configuration because I use a non-existing SeverityLevel:

```xml
		<module name="MissingJavadocType">
			<property name="severity" value="fatal" />
		</module>
```

Which leads to the CLI output:

```
$ java -jar checkstyle-10.4-all.jar -c checkstyle.xml FruitBasket.java
Exception in thread "main" java.lang.IllegalArgumentException: No enum constant com.puppycrawl.tools.checkstyle.api.SeverityLevel.FATAL
        at java.base/java.lang.Enum.valueOf(Enum.java:273)
        at com.puppycrawl.tools.checkstyle.api.SeverityLevel.getInstance(SeverityLevel.java:67)
        at com.puppycrawl.tools.checkstyle.ConfigurationLoader$InternalLoader.endElement(ConfigurationLoader.java:575)
        .... and the stack trace goes on
```

In practice, if I still want to use the fatal severity level supported by my other tooling, I have two options:

* Work with the `ignored` severity level and use wrapper scripts remap the output of checkstyle bumping up the severity levels by one
* Download checkstyle's source code, adjust the `SeverityLevel` enum to include an additional level `FATAL` and recompile checkstyle using `mvn package`, obtaining a custom binary and uploading this as a custom linter to the platform I am using.

Currently, I am using the second option which suprisingly works without any problems. Doing so yields the following CLI output:

```
$ java -jar checkstyle-alt.jar -c checkstyle.xml FruitBasket.java
Starting audit...
[FATAL] /path/to/FruitBasket.java:1:1: Missing a Javadoc comment. [MissingJavadocType]
Audit done.
```
I do think that rather than rolling my own binary package, it would be nice to be able to use "vanilla" checkstyle for this at some point in the future. I also think the adjustment is so small that perhaps this can be considered - in particular as this might not be the only case where it is desireable to combine output from multiple source code analysis tools.

**Is your feature request related to a problem? Please describe.**

The main problem is that I want to combine output from PMD and checkstyle to generate style feedback for students, but that in my custom rule configuration, PMD has an additional severity level not supported by checkstyle. As a consequence I have less flexibility in assigning different scoring levels to the different style transgessions for the rules provided by checkstyle.

**Describe the solution you'd like**

I would like to have the `SeverityLevel` enum extended with one more entry called `FATAL`. Experimentation suggests that from a technical point of view, this is the only adjustment needed to have the same severity levels in checkstyle so they match the ones available in PMD.

**Additional context**

I think that technically this change is very small. However, there can be practical issues related to the conceptual design of checkstyle or related to how other software uses checkstyle. I am not able to envision whether there are arguments from these perspectives against this feature. 

It seems one concern could be that other software depends on the maping of numeric constants to the values of enum. However, I believe this change would not result in a remapping of the existing mapping to numeric constants as they are already defined in an increasing order of severity: ignored=0, info=1, warning=2, error=3. Adding `FATAL` to the end of the enum would introduce it mapped to the constant 4, which is consistent with the fact that it is a higher level of severity than error.

An additional change besides introducing a new entry into the enum, is that the testcases in [SeverityLevelTest.java](../blob/master/src/test/java/com/puppycrawl/tools/checkstyle/api/SeverityLevelTest.java) that test the enum would need to be extended for the sake of completeness, although they do not seem fail when a new level is introduced. However, it seems straightforward to extend the current testcases to deal with a new fatal severity level.

If desired, I would be able to propose the relevant source code edits for this feature.

**Comment by romani** [comment]
I don't understand why fatal is required. Need more details on this.
Is next severity is catastrophic ?

We have severity:
- do not show
- do not make exit code as failure
- do fail 

Why we need more ?

**Comment by pcbouman-eur** [comment]
Good question,s I was indeed not entirely aware of the semantic meanings of the current levels from the documentation. I also fully understand the fear of a sliding scale.

I can agree with the argument that in a typical software engineering workflow adding more levels does not make a lot of sense. I might be stretching the usage scope of checkstyle by using it in a didactical workflow, rather than a software engineering workflow. In my case I believe it is helpful for a learner to have somewhat more finegrained feedback on the severity of style violations beyond merely accept/reject. In the autograding platform I am using this also corresponds to a color mapping when students view their source code with the generated style feedback: info is blue, warning is yellow, error is light red and fatal is dark red. To provide a bit more of an idea of how these level are used by a teacher on the platform I am using can be found [here](https://help.codegrade.com/automatic-grading-guides/java#set-up-a-checkstyle-or-pmd-code-quality-test). The final way in which a student sees the checkstyle output is only demod in [a Youtube video](https://youtu.be/GXonT-ZganA?t=182)

In my configuration I typically use the fatal level for the violations of hand-in rules, such as not defining the author of the class or not providing documentation where this is required. The error level is typically used for things that are really considered a bad practice, and which students should not make a habit or which are common sources of errors - for example I want students to think about exception and tell that writing empty catch blocks is a bad idea. The warning level is typically used for things that are very sloppy, e.g. leaving commented out code in the submission. The info level is typically used for things such as small layout violations, that are not directly related to the code itself.

**Comment by pcbouman-eur** [comment]
The [documentation of PMD](https://pmd.sourceforge.io/pmd-5.3.3/customizing/rule-guidelines.html) contains more information on the meaning of their five severity levels. I do agree that checkstyle's documentation could be improved to reflect the semantics of the severity levels better.

An alternative solution to my problem could be to deal with this in a wrapper script. As a preprocessing step, a valid checkstyle configuration file is derived from a configuration file that contains invalid severity levels. In a postprocessing step, the severity levels in checkstyle's output are adjusted based on the rule names and the original "invalid" severity levels. This would at least eliminate any potential side effects of adding an additional severity level to checkstyle.

**Comment by romani** [comment]
I am closing issue,but discussion can be continued if new ideas come up later on.

**Comment by pcbouman-eur** [comment]
Thanks you for all the explanations! Now that I understand the levels better I agree that adding another one is arbitrary. I am also happy that you now have an improvement your documentation of this aspect in the pipeline!

After this discussion I imagine it could be nice to have some way to attach some form of user defined semantic metadata to the different checks. However, that is a feature request with a much bigger impact than the original request, and it seems to me that at the moment wrapper scripts are the simpler option to pursue.

**Comment by nrmancuso** [comment]
> After this discussion I imagine it could be nice to have some way to attach some form of user defined semantic metadata to the different checks.

@pcbouman-eur you could hack this by using the [id](After this discussion I imagine it could be nice to have some way to attach some form of user defined semantic metadata to the different checks.) property or adding some information to the [mesage]{https://checkstyle.sourceforge.io/config.html#Custom_messages) property, depending on how you want to "consume" your metadata. Consider:

```
[nick@fedora src]$cat Test.java 
public class Test {
    void m(int BAD) {}
}

[nick@fedora src]$ cat config.xml 
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
    <module name="TreeWalker">
        <module name="ParameterName">
            <property name="id" value="ParameterName_FATAL"/>
            <message key="name.invalidPattern"
                     value="FATAL: Parameter name ''{0}'' must match pattern ''{1}''"/>
        </module>
    </module>
</module>

[nick@fedora src]$ java -jar checkstyle-10.4-all.jar -c config.xml Test.java 
Starting audit...
[ERROR] /home/nick/IdeaProjects/tester/src/Test.java:2:16: FATAL: Parameter name 'BAD' must match pattern '^[a-z][a-zA-Z0-9]*$' [ParameterName_FATAL]
Audit done.
Checkstyle ends with 1 errors.

```
