### ISSUE TITLE
Checker: false violation removals on other failures

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#12379]
Identified at https://github.com/checkstyle/checkstyle/actions/runs/3405402498/jobs/5663345165 ,

`xml-maven-plugin` failed and checker reported back all suppressions should be removed even though Checker never actually run.

We should skip anything else besides Checker to ensure groovy script behaves correctly.

**Comment by NitishKumar06** [comment]
@rnveach I'd like to work on this issue but don't know how to get started . Any suggestions?

**Comment by nrmancuso** [comment]
@NitishKumar06 it is likely that we can resolve this issue with no code changes. Take a look at https://github.com/checkstyle/checkstyle/blob/7159bb04953e5fb6cce4897993f1c3ec09172430/.github/workflows/checker-framework.yml#L1.

If we can change conditions of some steps, that is all we should need. My thoughts are as follows: 

Always run git diff, not only on failure. If there is no difference, workflow should succeed. This may require modification of git diff command.

This change will allow `Execute checker framework` to fail the entire workflow and never generate patch.

**Comment by rnveach** [comment]
I recommend we check if we can implement simplier maven solutions where we aren't copying the same turn offs everywhere.
Example: https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/master/.ci/validation.sh#L50
> mvn -e verify -Pno-validations,selftesting

**Comment by rnveach** [comment]
Fix was merged
