### ISSUE TITLE
Improper text in NewLineAtEndOfFileCheck documentation

### ISSUE THREAD

**Issue by NitishKumar06** [checkstyle/checkstyle#12370]
The following link (https://checkstyle.org/config_misc.html#NewlineAtEndOfFile) explains the check for adding a new line at the end of file. There's a line mentioned which says _Example (line 36 should not be in diff):_.

Although when you look at the image below, you find that there is no line number  present / way to find out the line number 36.

The IDE is capable of showing the line 36 but the line numbers are not visible in the website.

Would it be a good idea to modify the documentation little bit in order to add line number/ remove the text?

**Comment by strkkk** [comment]
I think it can be simpler, just 2 lines and refer to them as line 1 and line 2.

**Comment by romani** [comment]
and use output of `diff -u`

**Comment by romani** [comment]
Probably better to send PR and discuss exact wording in PR.

**Comment by NitishKumar06** [comment]
I believe it'd be a good idea if we remove "line 36 should not be in diff" since different files have different line numbers which may leads to confusion.
