### ISSUE TITLE
update list of related Tools

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#1238]
http://checkstyle.sourceforge.net/#Related_Tools

make two tables:
1) Active tools
2) Inactive/old tools

All proejcts that are below 5.0 release (http://checkstyle.sourceforge.net/releasenotes.html#Release_5.0), should be considered as old and inactive for sure.

All project that use 6.X version should be sorted to the top.

**Comment by dawidnejman** [comment]
Hi. I would like to start contributing to checkstyle and I think this would be an easy task for me to begin. Could you assign me to it?

**Comment by romani** [comment]
assigned to @dawidnejman .

**Comment by romani** [comment]
@dawidnejman , just want to remind you that it better to tackle this task in several atomic PRs. It is ok to send PR with update only to one tool. If you have very limited amount of time to spend on project, approach of micro but atomic PRs is best choice - continuous integration (even by small steps).

**Comment by dawidnejman** [comment]
@romani Below you can see my progress and internal documentation at the same time. I will do as you have suggested with first PR covering those inactive tools that I have discovered. 

Plugin name | CheckStyle version used | Comment
----------------- | --------------------------------- | -------------
SCM-Manager Plugin Page | 5.6 | Last update: 2014-05-22
jGRASP | 5.0 | Tool allows user to select his own CheckStyle binaries so theoretically any version should be valid, but it states (p.1) that it is optimised for version 5.0
SonarQube | 6.4.1 | Last update: 2015-04-16
Eclipse-CS | 6.9 |
sevntu-checkstyle | 6.7 | Last update: 2015-09-30
Checklipse | 4.1 | Last update: 2006-05-19
QAPlug | 5.6 | Last update: 2014-03-20
Checkstyle-idea | 6.10.1
JetStyle | 4.4 | Last update: 2008-03-09
Checkstyle Beans | 6.7 | Last update: 2015-06-19
nbCheckStyle | 3.4 | Last update: 2005-09-24
Software Quality Environment (SQE) | 6.10.1 | Last update: 2015-06-19
fawkeZ | ?
bluejcheckstyle | 4.3 | Last update: 2011-10-25
tIDE | ?
Emacs JDE | 3.1 | Last update: 2015-07-06 Last checkstyle update: 2007-12-29
jEdit | 5.5 | Last update: 2014-06-26

**Comment by romani** [comment]
I recommend you to do PRs with these changes, we will discuss in actual patch of xml file content that need to be changed.

**Comment by dawidnejman** [comment]
Sure

**Comment by mkordas** [comment]
@dawidnejman, [checkstyle-idea](https://github.com/jshiell/checkstyle-idea/issues/189) has just added support for Checkstyle 6.11.2

**Comment by dawidnejman** [comment]
@mkordas thanks for pointing this out. Things change very fast.

**Comment by dawidnejman** [comment]
Roman, instead having one table separated by empty row, how about using sub-sections?
I think it would be more readable:
![image](https://cloud.githubusercontent.com/assets/2310862/10416083/5249421a-7006-11e5-8fe8-b4595da396ca.png)

**Comment by mkordas** [comment]
+1 from me

**Comment by romani** [comment]
Very good.

fyi: Checkstyle for Bamboo is inactive

**Comment by dawidnejman** [comment]
Bitbucket page for checkstyle for Bamboo looks alive: https://bitbucket.org/atlassian/bamboo-checkstyle-plugin

**Comment by romani** [comment]
:) , ok , please reconcile both link of this project in our table, second show that it is inactive.

**Comment by romani** [comment]
Intersting project, please add it.
https://marketplace.atlassian.com/plugins/at.apogeum.bitbucket.checkstyle

**Comment by romani** [comment]
One more: http://roman-ivanov.blogspot.com/2015/10/checkstyle-integration-to.html?m=1

**Comment by romani** [comment]
release 6.12 is planned to be done at end of the month (in 7 days).

@dawidnejman , do you have time to finish this issue ? do you need help ?

**Comment by dawidnejman** [comment]
@romani sorry for delay. I took some time to figure out the checkstyle versions for those three missing projects. I will update the page today.

**Comment by romani** [comment]
Please do not hesitate to ask questions in our char room or mail-list. If something is not clear, it is sigh for us to improve.

**Comment by dawidnejman** [comment]
The three projects we were missing are: *fawkeZ*, *tIDE* and *JArchitect*:

**fawkeZ** - the project that *checkstyle* page is originally referring to, was renamed to *[fawkeZ-old](https://github.com/jCoderZ/fawkez-old)* and new version was splitted into few other projects. The part which is responsible for report generation is *[fawkez-code-report](https://github.com/jCoderZ/fawkez-code-report)*. So the links on the page will have to be changed.

**tIDE** - no official information on supported *checkstyle*. Source code has references to version 5.6. I have run the software and tried to used 6.11.2 but it was not compatible.

**JArchitect** - I have ran the application and I was able to import successfully *checkstyle* report created with version 6.11.2. The team responsible for the application confirmed that it should work with latest *checkstyle* version.

**Comment by romani** [comment]
Ok, add them to table

**Comment by romani** [comment]
final change is merged
