### ISSUE TITLE
Missing Link found on Checkstyle docs

### ISSUE THREAD

**Issue by NitishKumar06** [checkstyle/checkstyle#12393]
**Problem:**

The following doc (https://checkstyle.org/cmdline.html#Command_line_usage) explains how to run checkstyle using the command line.

The last 3rd paragraph of this section says "Note that the -`n packageNamesFile` option has been dropped for Checkstyle 5.0, because of significant changes regarding package name file handling. See for details."

The text _See of details_ should actually contain a link but it's plain text.

**Proposed Solution:**

Add the missing link.

**Comment by rnveach** [comment]
https://github.com/checkstyle/checkstyle/blob/master/src/xdocs/cmdline.xml.vm#L150
The link exists but the HTML for it is invalid, so nothing is showing up as a link or such.

**Comment by NitishKumar06** [comment]
@rnveach Isn't there any way we could fix this?

**Comment by nrmancuso** [comment]
@NitishKumar06 issue is approved, please send PR to fix invalid HTML

**Comment by romani** [comment]
Fix is merged
