### ISSUE TITLE
Ordering issue with nested classes in static imports

### ISSUE THREAD

**Issue by ddossot** [checkstyle/checkstyle#1239]
Using CheckStyle `6.7`.

I'm trying to find a configuration of the `ImportOrder` rule that matches Eclipse's default import ordering rules. I'm currently using:

        <module name="ImportOrder">
            <property name="option" value="top" />
            <property name="groups" value="io,/^javax?\./,net,org,com" />
            <property name="ordered" value="true" />
            <property name="separated" value="false" />
            <property name="caseSensitive" value="true" />
            <property name="sortStaticImportsAlphabetically" value="true" />
        </module>

which works great for everything except for static imports of nested classes fields.

Eclipses insists on this order:

    import static io.netty.handler.codec.http.HttpHeaders.addHeader;
    import static io.netty.handler.codec.http.HttpHeaders.Names.DATE;

while `sortStaticImportsAlphabetically` wants:

    import static io.netty.handler.codec.http.HttpHeaders.Names.DATE;
    import static io.netty.handler.codec.http.HttpHeaders.addHeader;

At this point I'm not sure what to do besides opening this issue. I'm not sure it's a CheckStyle bug, after all Eclipse has a pretty convoluted ordering strategy. This said, it seems to make sense to give precedence to methods/fields of parent class before the methods/fields of a nested class...

**Comment by romani** [comment]
please make caseSensitive=false, see example below:
```
20:32 /var/tmp $ cat CheckstyleBug.java 
import static io.netty.handler.codec.http.HttpHeaders.addHeader;
import static io.netty.handler.codec.http.HttpHeaders.Names.DATE;

public class CheckstyleBug {

}
20:32 /var/tmp $ cat config.xml 
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
    "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
    "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
  <module name="TreeWalker">
    <module name="ImportOrder">
        <property name="option" value="top" />
        <property name="groups" value="io,/^javax?\./,net,org,com" />
        <property name="ordered" value="true" />
        <property name="separated" value="false" />
        <property name="caseSensitive" value="true" />
        <property name="sortStaticImportsAlphabetically" value="true" />
    </module>
  </module>
  
</module>

20:33 /var/tmp $ java -jar checkstyle-6.8-SNAPSHOT-all.jar -c config.xml CheckstyleBug.java 
Starting audit...
/var/tmp/CheckstyleBug.java:2: Wrong order for 'io.netty.handler.codec.http.HttpHeaders.Names.DATE' import.
Audit done.
Checkstyle ends with 1 errors.

20:33 /var/tmp $ cat config.xml 
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
    "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
    "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
  <module name="TreeWalker">
    <module name="ImportOrder">
        <property name="option" value="top" />
        <property name="groups" value="io,/^javax?\./,net,org,com" />
        <property name="ordered" value="true" />
        <property name="separated" value="false" />
        <property name="caseSensitive" value="false" />
        <property name="sortStaticImportsAlphabetically" value="true" />
    </module>
  </module>
  
</module>

20:33 /var/tmp $ java -jar checkstyle-6.8-SNAPSHOT-all.jar -c config.xml CheckstyleBug.java 
Starting audit...
Audit done.
20:33 /var/tmp $ 
```

**Comment by romani** [comment]
html doc was extended to make it clear.

**Comment by ddossot** [comment]
Thanks for the question response.

If I switch `caseSensitive` to `false`, I receive tons of errors for non-static imports because ChekStyle wants:

    import com.google.inject.assistedinject.FactoryModuleBuilder;
    import com.google.inject.name.Names;
    import com.google.inject.Provides;
    import com.google.inject.Singleton;

but Eclipse actually does:

    import com.google.inject.Provides;
    import com.google.inject.Singleton;
    import com.google.inject.assistedinject.FactoryModuleBuilder;
    import com.google.inject.name.Names;

I reckon there's no way out of this conundrum :crying_cat_face:

**Comment by ivanov-alex** [comment]
@ddossot We are reviewing ImportOrder to make it work with major IDEs and reviewed your problem again. 
Organize Imports feature works not perfectly in Eclipse. In Mars release they have fixed sorting of non-static imports, but I have checked your case and it still works the same.

I have entered [Eclipse defect](https://bugs.eclipse.org/bugs/show_bug.cgi?id=473629) for your case.
You can vote for this defect (using **vote** link in **Importance** section of defect) and ask other people to do the same to raise priority of the defect.

**Comment by ddossot** [comment]
@ivanov-alex Thank you for following up on this. I've upvoted the defect :+1:

**Comment by romani** [comment]
@ddossot and @ivanov-alex  , does it make sense to close this issue as problem is on Eclipse side ?

**Comment by ddossot** [comment]
Agreed.
