### ISSUE TITLE
Inconsistent allowedAbbreviations when a method is contains an underscore. 

### ISSUE THREAD

**Issue by NickPaul41** [checkstyle/checkstyle#12409]
https://checkstyle.org/config_naming.html#AbbreviationAsWordInName

```bash
/var/tmp $ javac Test.java
````
```bash
/var/tmp $ cat config.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
  <module name="TreeWalker">
        <module name="AbbreviationAsWordInName">
            <property name="allowedAbbreviations" value="ORDER, OBSERVATION, UNDERSCORE, TEST" />
        </module>
    </module>
</module>
````
```bash
/var/tmp $ cat Test.java
public class Test {
  void getTEST() {
  } // WORKING

  void getORDER_OBSERVATION() {} // NOT WORKING

  void getUNDERSCORE() {} // WORKING

  void getTEST_OBSERVATION() {} // WORKING

  void getTEST_UNDERSCORE() {} // WORKING

  void getORDER() {} // WORKING

  void getOBSERVATION() {} // WORKING

  void getORDER_UNDERSCORE() {} // NOT WORKING
}
````
```bash
/var/tmp $ RUN_LOCALE="-Duser.language=en -Duser.country=US"
/var/tmp $ java $RUN_LOCALE -jar checkstyle-10.4-all.jar -c config.xml Test.java
[ERROR] /var/tmp/Test.java:5:8: Abbreviation in name 'getORDER_OBSERVATION' must contain no more than '4' consecutive capital letters. [AbbreviationAsWordInName]
[ERROR] /var/tmp/Test.java:17:8: Abbreviation in name 'getORDER_UNDERSCORE' must contain no more than '4' consecutive capital letters. [AbbreviationAsWordInName]
````
---
There are four words in allowedAbbreviations when defining a method that has an underscore between different combinations, some are allowed and others are not. It is unclear to me why getTEST_OBSERVATION works and getORDER_OBSERVATION throws an an error. 

---

**Comment by rnveach** [comment]
I am just talking about this from the code and the reason.

This seems similar to https://github.com/checkstyle/checkstyle/issues/8863 but this issue has a better report.

`getORDER_OBSERVATION` is not seen as `ORDER` to the code, but is seen as `ORDE`. The `R` is most likely seen as the next letter of the rest. If the name was "ORDERest", it sees "ORDE" and "Rest". If you add `ORDE` to the list of abbreviations, all the violations go away.

**Comment by romani** [comment]
I think there is issue with `_` interpretation in Check. We might lack testing on snake naming convention.

I am approving issue.

Whole logic is at https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/AbbreviationAsWordInNameCheck.java
Test - https://github.com/checkstyle/checkstyle/blob/master/src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/AbbreviationAsWordInNameCheckTest.java

How to debug https://checkstyle.org/beginning_development.html

PR is welcome.

**Comment by arinmodi** [comment]
@romani, 

Config:

```
AbbreviationAsWordInName
allowedAbbreviationLength = 5
allowedAbbreviations = NUMBER, MARAZMATIC, VARIABLE
ignoreFinal = (default)true
ignoreStatic = (default)true
ignoreStaticFinal = (default)true
ignoreOverriddenMethods = (default)true
tokens = CLASS_DEF, VARIABLE_DEF, METHOD_DEF, ENUM_DEF, ENUM_CONSTANT_DEF, PARAMETER_DEF, \
         INTERFACE_DEF, ANNOTATION_DEF


```

Are Following Violations or Not, According To Current Code it's not violation but I think it should be violation ?

```
                int marazmaticVARIABLEName = 2;
                int MARAZMATICVariableName = 1;
```

**Comment by romani** [comment]
I should not be violation, as all capitalized words are in allowed list

**Comment by arinmodi** [comment]
> I should not be violation, as all capitalized words are in allowed list

If you see closely, it's not "VARIABLE" but it is "VARIABLEN" which is not part of allowed list. Still not violation ?

**Comment by romani** [comment]
`N` is part of next word.
In camel case notation it is like this.

**Comment by arinmodi** [comment]
Got it

**Comment by rnveach** [comment]
Fix was merged
