### ISSUE TITLE
checkstyle tests depend on user Locale

### ISSUE THREAD

**Issue by Bananeweizen** [checkstyle/checkstyle#12406]
* check out checkstyle source
* mvn clean install

Many tests fail because the expected (English) messages don't match the German messages produced on my system. (the localized message would be correct, so the code as such is working as expected)

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTaskTest
[ERROR] Tests run: 45, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 0.984 s <<< FAILURE! - in com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTaskTest
[ERROR] testExecuteIgnoredModules  Time elapsed: 0.123 s  <<< FAILURE!
com.google.common.truth.ComparisonFailureWithFacts:
Content of file with violations differs from expected
expected: Starting audit...
but was : Beginne Prüfung...
        at com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTaskTest.testExecuteIgnoredModules(CheckstyleAntTaskTest.java:392)
```
Assuming that it is possible to enforce checkstyle to be executed with a given locale, can that be added in the verification of itself, please?

**Comment by rnveach** [comment]
This is a known issue that is trying to be resolved.

First reported issue is at https://github.com/checkstyle/checkstyle/issues/7911 . Resolution is trying to be done at https://github.com/checkstyle/checkstyle/issues/12104 , but it is probably going to be a bit complex and may require breaking changes.

**Comment by Bananeweizen** [comment]
Thanks for the pointers. Closing as duplicate then.
