### ISSUE TITLE
RedundantModifier for inner classes and enum constructors

### ISSUE THREAD

**Issue by WonderCsabo** [checkstyle/checkstyle#1242]
`RedundantModifier` should also check:

* modifier of enum constructor (implicitly **private**)
* modifier of inner type of interface (implicitly **static**)
```java
public enum MyEnum {
  private MyEnum() { } // private modifier is redundant
}

public interface MyInterface {
  static class MyInnerClass { } // static modifier is redundant
}
```

**Comment by romani** [comment]
Please provide code examples to make this issue clear for future contributor.

**Comment by WonderCsabo** [comment]
@romani you are right, i added code examples.

**Comment by romani** [comment]
assigned to @liscju .

**Comment by romani** [comment]
merged.

**Comment by marcelstoer** [comment]
That's nice but it doesn't play well with [JavadocMethod#scope](http://checkstyle.sourceforge.net/config_javadoc.html#JavadocMethod). If you don't enforce Javadoc for private constructors you now get a warning if you remove the `private` modifier from enum constructors.

**Comment by WonderCsabo** [comment]
JavadocMethod should realize that enum constructors are implicitly private,
that is a separate issue I guess.

**Comment by romani** [comment]
Issue is closed, if smth does  not work as expected - please open new issue

**Comment by marcelstoer** [comment]
I know I should create a new issue - and I will. I left the comment here for people who find this issue because the were looking into why JavadocMethod fails for enum constructors.
