### ISSUE TITLE
Resolve Pitest suppression for SeparatorWrapCheck

### ISSUE THREAD

**Issue by arinmodi** [checkstyle/checkstyle#12430]
Parent #12341

Kill The Mutation :

https://github.com/checkstyle/checkstyle/blob/7e0f1533d39c2811bd7804c5163d4d3b7fc2cd6b/.ci/pitest-suppressions/pitest-whitespace-suppressions.xml#L84-L91

For SeparatorWrapCheck

**Comment by arinmodi** [comment]
I am on it

**Comment by arinmodi** [comment]
Any Maintainers, please guide me if am at wrong path

**Comment by arinmodi** [comment]
hardcoded mutation means, I have to replace the line specified in mutation with suggested line given as description ?

Am I correct ?

**Comment by nrmancuso** [comment]
It looks like this and following `trim` are suspect, this code was previously copy pasted from another check: https://github.com/checkstyle/checkstyle/pull/180/files#

> hardcoded mutation means, I have to replace the line specified in mutation with suggested line given as description ?

@arinmodi Yes, all tests should still pass if you have hardcoded the correct mutation.

**Comment by nrmancuso** [comment]
@arinmodi please always reference parent issue at https://github.com/checkstyle/checkstyle/issues/12341 in issue description
