### ISSUE TITLE
Re-enable sonar 

### ISSUE THREAD

**Issue by nrmancuso** [checkstyle/checkstyle#12431]
We need to reactivate sonar since we temporarily disabled it at  https://github.com/checkstyle/checkstyle/commit/e7b2fd8175e62a2a7f722769168512bad8eb0c01

PR for this was merged prematurely, before sonar was working 100%

**Comment by rnveach** [comment]
@romani @nrmancuso Does this close the issue?

**Comment by nrmancuso** [comment]
Let's leave it open, it looks like we need to tweak it a bit for master build: https://sonarcloud.io/summary/new_code?id=org.checkstyle%3Acheckstyle

I'm not sure if we need to update the quality gate or upload/sonar parameters, I will investigate.

**Comment by nrmancuso** [comment]
Master build is green now: https://circleci.com/gh/checkstyle/checkstyle/204262

Passed build in Sonar: https://sonarcloud.io/dashboard?id=org.checkstyle%3Acheckstyle&branch=master

I am closing this.
