### ISSUE TITLE
Resolve Pitest suppression for RightCurlyCheck

### ISSUE THREAD

**Issue by arinmodi** [checkstyle/checkstyle#12441]
Parent : #12341

Kill Mutations:

https://github.com/checkstyle/checkstyle/blob/55e09e57c77d0f63b65b931c31fddeec243298bd/.ci/pitest-suppressions/pitest-blocks-suppressions.xml#L138-L145

**Comment by nrmancuso** [comment]
@arinmodi please limit issues to a single mutation

**Comment by nrmancuso** [comment]
Fixed via #12442
