### ISSUE TITLE
Make release by another admin - rnveach

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#12453]
@rnveach , please request access to checktyle namespace.
Example https://issues.sonatype.org/browse/OSSRH-11819

Share with me link to new issue to let me confirm access.

**Comment by rnveach** [comment]
https://issues.sonatype.org/browse/OSSRH-86535

**Comment by rnveach** [comment]
Sevntu at https://issues.sonatype.org/browse/OSSRH-86561

**Comment by rnveach** [comment]
@romani As a reminder, I don't have access to sevntu's organization at https://github.com/organizations/sevntu-checkstyle/settings/profile

**Comment by romani** [comment]
I will provide access for sure, to let you be admin of sevntu organization.

**Comment by romani** [comment]
I made you as owner at https://github.com/orgs/sevntu-checkstyle/people?query=rn
![image](https://user-images.githubusercontent.com/812984/204096433-adb4a26e-d939-45b8-bae0-c238b0abb1b6.png)

by suggestion at https://stackoverflow.com/a/64107022

**Comment by rnveach** [comment]
Going by https://github.com/checkstyle/checkstyle/wiki/How-to-make-a-release#pre-reqs ,

Next on the list is I need a GPG key and upload it.
https://github.com/sevntu-checkstyle/dsm-maven-plugin/wiki/How-to-config-GPG-and-sign-artifact-with-it says how to go about doing this so I will start looking it over

**Comment by rnveach** [comment]
https://github.com/checkstyle/checkstyle/wiki/How-to-make-a-release#pre-reqs
> put [Github token](https://github.com/settings/tokens) to ~/.m2/token-checkstyle.txt

Token must be given a name and a expiration date. Repository access must either be all of owners or given selected repositories. (Selected it probably preferred for security).

Since this ties to https://github.com/checkstyle/checkstyle/blob/135eec54c26ff07cfc64e26790475e94bd5d0671/release.sh#L65

The following permission is assumed to be needed for now.
````
Issues Access: Read and write
Issues and related comments, assignees, labels, and milestones. 
Contents Access: Read and write
Repository contents, commits, branches, downloads, releases, and merges. 
````

**Comment by rnveach** [comment]
https://github.com/checkstyle/checkstyle/wiki/How-to-make-a-release#pre-reqs

> Setup ~/.m2/settings.xml to include the servers ([instructions](http://central.sonatype.org/pages/apache-maven.html)). Follow Maven guide on how to encrypt passwords

Password encryption can be found at https://maven.apache.org/guides/mini/guide-encryption.html .

sonatype-nexus-staging is using JIRA's user/pass.

**Comment by romani** [comment]
10.7.1 will be done by me to do final test that all actions works.

10.7.2 should be done by @rnveach

**Comment by romani** [comment]
@rnveach , lets plan to do release 10.8.1 by you by manual and sequential triggering of each action, as we have some functional changes in repo.

**Comment by romani** [comment]
@rnveach , please do release by actions https://github.com/checkstyle/checkstyle/wiki/Semi-automated-release

**Comment by romani** [comment]
https://github.com/checkstyle/checkstyle/actions/runs/4369202631/jobs/7642726929 is latest release notes, it is passed, so no bumps is required.

Yes, we need to review latest release notes generation execution. For typos in title that we want to fix or last chance to correct labels on issues or ...

**Comment by romani** [comment]
Release is 10.8.1 is done not by me, first time in last 10 years.

**Comment by rnveach** [comment]
@romani Documentation update is still needed at https://github.com/checkstyle/checkstyle/issues/12453#issuecomment-1462045872

**Comment by romani** [comment]
I removed:

>- Change version. Run [R: Bump version/Update Milestone](https://github.com/checkstyle/checkstyle/actions/workflows/bump-version-and-update-milestone.yml)

We already moved this demand and validation to release notes generation. So we just need to follow CI.

**Comment by rnveach** [comment]
And the other 6-7 items I mentioned?

**Comment by romani** [comment]
>We should probably add something to ensure milestone has correct end date.

As we complete training of 2 extra maintainers to do release without worries. We need to change scheduling of release. This is separate thread of activities.

My shallow vision is to stay at 1 month as maximum. And do release before any breaking changes merges. And do it by request of author of fix.
