### ISSUE TITLE
Improve exception handling in CheckstyleAntTask class

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#1245]
Catching `Exception` is bad practice. Code around `com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTask.java:367` needs to be changed.

Discussion from #1195:

> interesting case ... after update it will be in case of IOException --> BuildException("Unable to create a Checker: ") , but in case of NPE or NumberFormatException ---> NPE or NumberFormatException :). If we do not guarantee a type of exception from our code why we should bother with BuildException at all ?
Please look at https://github.com/checkstyle/checkstyle/blob/master/config/findbugs-exclude.xml#L13
I do not claim that basic ANT taks are done in right approach, but will follow their pattern.
Here is an example of catching smth specific - https://git-wip-us.apache.org/repos/asf?p=ant.git;a=blob;f=src/main/org/apache/tools/ant/taskdefs/Chmod.java;h=ac0c3d8d143493706be0d1ae875177146db43f67;hb=HEAD#l197

> I did more search and found : 
https://ant.apache.org/manual/tutorial-writing-tasks.html

 >>Oh, what's that in execute()? Throw a BuildException? Yes, that's the usual way to show
 Ant that something important is missed and complete build should fail. The string 
provided there is written as build-failes-message. Here it's necessary because the log()
 method can't handle a null value as parameter and throws a NullPointerException.
 (Of course you can initialize the message with a default string.)

>So it looks like ANT suggest to throw BuildException only if some arguments are missed or smth is not correct with initialization phase. 
So it mean that we are ok with your solution , but it would be better to somehow split initialization phase and processing and throw BuildException by initialization failure, and throw exception as is in all other cases. [That could be done as another issue]

**Comment by romani** [comment]
fixed by 3ef918920c58c550169ccef3cfe1706aede11a6e
