### ISSUE TITLE
Remove new curl parameter from all GitHub actions for release 

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#12456]
Detected during update from 10.5 to 10.5.0
https://github.com/checkstyle/checkstyle/actions/runs/3551338748/jobs/5965427201

Reason to bump https://github.com/checkstyle/checkstyle/actions/runs/3551179138/jobs/5965170464#step:3:129

We should not use until https://github.com/checkstyle/checkstyle/issues/12451

**Comment by romani** [comment]
@stoyanK7 , please help to fix.

**Comment by stoyanK7** [comment]
On it.

**Comment by romani** [comment]
fix merged
