### ISSUE TITLE
Restore curl --fail-with-body at summer 2023

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#12451]
https://curl.se/mail/lib-2021-03/0056.html 
released with `add --fail-with-body` at  Wed, 31 Mar 2021, but not all images in CI have it yet.

one of examples: https://github.com/checkstyle/checkstyle/pull/12446

we need to try to restore this flag in curl at summer of 2023.

**Comment by arinmodi** [comment]
Is this going to be part of GSOC 2023 ?

**Comment by romani** [comment]
no

**Comment by stoyanK7** [comment]
On it.

**Comment by nrmancuso** [comment]
@stoyanK7 it might be a good idea to specify the Ubuntu version in all of our docker images in CI to make sure we are on one with the correct version of curl.

**Comment by stoyanK7** [comment]
@nrmancuso I will check them but I believe all are on `ubuntu-latest`. Thanks for the heads up.

**Comment by nrmancuso** [comment]
Might be a good idea to pin to specific version

**Comment by stoyanK7** [comment]
Oh, got it.
