### ISSUE TITLE
SuppressWarnings check does not support value pair representation

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#1246]
[SuppressWarnings check](http://checkstyle.sourceforge.net/config_annotation.html#SuppressWarnings) recognizes annotation `@SuppressWarnings(value = UNUSED)` as empty one and produces warning `The warning '' cannot be suppressed at this location. `.

Before assuming that `SuppressWarnings` is empty, it must be checked for existence of `ANNOTATION_MEMBER_VALUE_PAIR` token.

**Comment by romani** [comment]
merged.
