### ISSUE TITLE
upate local environment to operate on same scripts as at remote

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#12465]
on my local
```
11:34 $ ./.ci/copy-site-to-sourceforge.sh $PREV_RELEASE $NEW_RELEASE
RELEASE version:10.4
Creating shell for @shell.sourceforge.net
Warning: Identity file /home/rivanov/.ssh/private_sourceforge_key not accessible: No such file or directory.
usage: ssh [-1246AaCfGgKkMNnqsTtVvXxYy] [-b bind_address] [-c cipher_spec]
           [-D [bind_address:]port] [-E log_file] [-e escape_char]
           [-F configfile] [-I pkcs11] [-i identity_file] [-L address]
           [-l login_name] [-m mac_spec] [-O ctl_cmd] [-o option] [-p port]
           [-Q query_option] [-R address] [-S ctl_path] [-W host:port]
           [-w local_tun[:remote_tun]] [user@]hostname [command]

```

workaround was to revert latest commit and continue release.

I need to update my local to comply to CI folder structure

**Comment by Adityasaini10012001** [comment]
assign this to me

**Comment by nrmancuso** [comment]
@Adityasaini10012001 please find an issue with the `approved` label. If this is your first contribution to checkstyle, I suggest to start with a `gsoc first issue`.

**Comment by romani** [comment]
I just did on my local:
`$ ln ~/.ssh/id_rsa ~/.ssh/private_sourceforge_key`

and it works.

**Comment by romani** [comment]
I update wiki page for release - https://github.com/checkstyle/checkstyle/wiki/How-to-make-a-release/_compare/68ccdd43488042e28fc9ca1f7bab9e3ee4b5f167

and updated script to remind defining required variable - https://github.com/checkstyle/checkstyle/commit/25677735a9089a1249219020742a799a50545cf2
