### ISSUE TITLE
'R: Push Release Notes' failing on push

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#12479]
https://github.com/checkstyle/checkstyle/actions/runs/3580170024/jobs/6022052073
```
Run git config user.name 'github-actions[bot]'
[master 4cb1649] doc: release notes for 10.5.1
 1 file changed, 1[7](https://github.com/checkstyle/checkstyle/actions/runs/3580170024/jobs/6022052073#step:5:8) insertions(+)
remote: Permission to checkstyle/checkstyle.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/checkstyle/checkstyle/': The requested URL returned error: 403
Error: Process completed with exit code 12[8](https://github.com/checkstyle/checkstyle/actions/runs/3580170024/jobs/6022052073#step:5:9).
```

We need to define write permission to action.
https://github.com/checkstyle/checkstyle/blob/77040f2cce4767fbb49e60073203a85885c2e99c/.github/workflows/bump-version-and-update-milestone.yml#L13

**Comment by romani** [comment]
@stoyanK7 , please help to fix

**Comment by stoyanK7** [comment]
On it.

**Comment by romani** [comment]
Now it works https://github.com/checkstyle/checkstyle/commit/d4079e265de66bb6061fc3743fec5c44f0545aa5

**Comment by romani** [comment]
Unfortunately no way to revert commit from web UI, I will do this as I come to laptop

**Comment by rnveach** [comment]
> `<section name="Release 10.5.1-SNAPSHOT">`

Shouldn't we make this fail if `SNAPSHOT` is in the release?
