### ISSUE TITLE
Use of mutation testing in checkstyle - Help needed

### ISSUE THREAD

**Issue by belene** [checkstyle/checkstyle#12480]
Hello there!

My name is Ana. I noted that you use the mutation testing tool pit in the project. 
I am a postdoctoral researcher at the University of Seville (Spain), and my colleagues and I are studying how mutation testing tools are used in practice. With this aim in mind, we have analysed over 3,500 public GitHub repositories using mutation testing tools, including yours! This work has recently been published in a journal paper available at https://link.springer.com/content/pdf/10.1007/s10664-022-10177-8.pdf. 

To complete this study, we are asking for your help to understand better how mutation testing is used in practice, please! We would be extremely grateful if you could contribute to this study by answering a brief survey of 21 simple questions (no more than 6 minutes). This is the link to the questionnaire https://forms.gle/FvXNrimWAsJYC1zB9.

Drop me an e-mail if you have any questions or comments (anasan@us.es). Thank you very much in advance!!

**Comment by nrmancuso** [comment]
@belene would you like only one maintainer from our project to answer your survey, or if multiple maintainers are interested, is it ok for more than one to answer?

**Comment by belene** [comment]
Hello Nick,

Thanks for your reply. The more people involved in mutation testing respond
to the survey the better. Your help is very much appreciated.

Regards,
Ana

**Comment by romani** [comment]
Done

**Comment by nrmancuso** [comment]
Done
