### ISSUE TITLE
'R: Push Release Notes' makes xml section version as snapshot 

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#12488]
Detected at https://github.com/checkstyle/checkstyle/issues/12479#issuecomment-1333069436

Execution of action:
https://github.com/checkstyle/checkstyle/actions/runs/3588732543/jobs/6040435644#step:4:1

Results in snapshot version in xml. That is not correct.

Detected:
`<section name="Release 10.5.1-SNAPSHOT">`

Expected:
`<section name="Release 10.5.1">`

**Comment by stoyanK7** [comment]
On it.
