### ISSUE TITLE
inconsistent documentation for TEXT_BLOCK_abc token types

### ISSUE THREAD

**Issue by Bananeweizen** [checkstyle/checkstyle#12491]
The 3 examples in
* https://checkstyle.sourceforge.io/apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#TEXT_BLOCK_CONTENT
* https://checkstyle.sourceforge.io/apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#TEXT_BLOCK_LITERAL_BEGIN
* https://checkstyle.sourceforge.io/apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#TEXT_BLOCK_LITERAL_END

all parse the same input, but produce different outputs.
* with/without braces "(" ")" around the tokens
* with \r\n or with \n only (where the \r\n seems wrong, since the compiler will normalize to \n on all platforms)

I would expect these 3 outputs to be identical, or am I missing some concept around the syntax tree output?

**Comment by nrmancuso** [comment]
@Bananeweizen good catch; this is likely a combination of students using different OS's to create the AST examples and the "old style" of examples (with `(` around content.

**Comment by nrmancuso** [comment]
Let's use example from https://checkstyle.sourceforge.io/apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#TEXT_BLOCK_CONTENT for all.

**Comment by nrmancuso** [comment]
> Should we update our docs too ?

Sure, it would be good to mention when this feature actually became “official “ :)

**Comment by MANISH-K-07** [comment]
> > Should we update our docs too ?
> 
> Sure, it would be good to mention when this feature actually became “official “ :)

Done at PR #14622

**Comment by nrmancuso** [comment]
Closed via #14622
