### ISSUE TITLE
'R: Push Release Notes' generate extra empty line with spaces

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#12498]
https://github.com/checkstyle/checkstyle/actions/runs/3609971168 
generated
https://github.com/checkstyle/checkstyle/commit/2f0f5f90c0d1f93b1179757e7ae5f2d7568bde95

but there is extra empty line with two spaces in it.
is ti possible to avoid this ?

this results in violation of checkstyl:
```
[INFO] --- maven-antrun-plugin:3.1.0:run (ant-phase-verify) @ checkstyle ---
[INFO] Executing tasks
[INFO]      [echo] Checkstyle started (checkstyle_checks.xml): 03/12/2022 11:52:27 AM
[INFO] [checkstyle] Running Checkstyle  on 1496 files
[ERROR] [checkstyle] [ERROR] /home/rivanov/java/github/checkstyle/checkstyle/src/xdocs/releasenotes.xml:13: Trailing whitespace is not allowed [noTrailingWhitespace]
[INFO]      [echo] Checkstyle finished (checkstyle_checks.xml) : 03/12/2022 11:53:26 AM
[INFO]      [echo] Checkstyle started (checkstyle_non_main_files_checks.xml): 03/12/2022 11:52:27 AM

```

**Comment by romani** [comment]
@stoyanK7 , is it possible/easy to fix this ?

**Comment by stoyanK7** [comment]
@romani Yes. From https://freemarker.apache.org/docs/dgui_misc_whitespace.html, we can use trimmer directives

and change the template `xdoc_freemarker_template` from 
https://github.com/checkstyle/contribution/blob/bd4792e62665e153d876862ef4b0bc57f7cd7391/releasenotes-builder/src/test/resources/com/github/checkstyle/xdocBreakingCompatibility.txt#L1
to this `  <#t><#escape x as x?html>`

Shall I open a PR in `contribution`?

**Comment by romani** [comment]
Sure.
I thought problem was in our way we insert content. But let's see details in PR
