### ISSUE TITLE
mixed whitespace in text blocks

### ISSUE THREAD

**Issue by Bananeweizen** [checkstyle/checkstyle#12490]
In multiple projects I have run into the issue of mixed whitespace (i.e. tabs and spaces) in text blocks. This is discouraged: https://docs.oracle.com/en/java/javase/13/text_blocks/index.html#detecting-potential-issues-with-white-space

I haven't immediately found any related check in the whitespace section. Is anything like that planned maybe? I know I can always fall back to regex in my own projects, but it seems that more people should be made aware of that problem by having an explicit checker.

**Comment by nrmancuso** [comment]
Have you tried https://checkstyle.sourceforge.io/config_coding.html#IllegalTokenText?

**Comment by Bananeweizen** [comment]
I think that one is sufficient for my purpose, thanks.
