### ISSUE TITLE
Create GitHub action to put current milestone on issue of closed PR

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#12497]
We put milestone manually after we merge PR.

This should be automatic.
https://www.jessesquires.com/blog/2022/08/04/automatically-assign-milestones-with-github-actions/
https://github.com/orgs/community/discussions/26724#discussioncomment-3253107

Or something special for us. As sometimes pull request needs to marked with milestone as it is referred in commit, but it is rare case we can skip it if this is complicated.

**Comment by rnveach** [comment]
It can't be automatic if the issue already has a milestone set. We sometimes have issues that span multiple releases.

**Comment by romani** [comment]
I think it is fine to have latest milestone. Long lasting usually misc issues, user unlikely interested in watching them.

**Comment by ayush27prasad** [comment]
@romani I am working on this issue, could you please assign it to me?

**Comment by romani** [comment]
@Kevin222004, can you help with this issue?

**Comment by Kevin222004** [comment]
I am on it

**Comment by stoyanK7** [comment]
@Kevin222004 Are you still working on it? I am interested to take it.

**Comment by Kevin222004** [comment]
@stoyanK7 please take it I am busy with exam till 2march 
And then still I have to learn more about this. 

Please work on it

**Comment by stoyanK7** [comment]
Thanks a lot.

On it then.

**Comment by rnveach** [comment]
Not working at https://github.com/checkstyle/checkstyle/pull/12797#issuecomment-1454895114

**Comment by romani** [comment]
@stoyanK7, please take a look

**Comment by stoyanK7** [comment]
@rnveach 

> We should fail on any error.

From what I remember, `--fail-with-body` was not available in all images so I didn't even bother adding it: https://github.com/checkstyle/checkstyle/issues/12451
I will try adding it to see if it is supported now.

---
> https://github.com/checkstyle/checkstyle/actions/runs/4332960192/jobs/7565786160
> {
  "message": "Resource not accessible by integration",
  "documentation_url": "https://docs.github.com/rest/reference/issues#update-an-issue"
}

It seems that the `GITHUB_TOKEN` does not have sufficient permissions to update the issue milestone which is strange. 
We should have the right permissions for this:
 https://github.com/checkstyle/checkstyle/blob/bbd4975a606d9c7670f695a6160f3e6c8575a463/.github/workflows/set-milestone-on-referenced-issue.yml#L16-L18

However, at the `Set up job` step of the failing job, this is shown:
https://github.com/checkstyle/checkstyle/actions/runs/4332960192/jobs/7565786160#step:1:17
```
GITHUB_TOKEN Permissions
  Issues: read
  Metadata: read
  PullRequests: read
```

**Comment by stoyanK7** [comment]
Could it be this? For me, the setting is enabled.

https://docs.github.com/en/organizations/managing-organization-settings/disabling-or-limiting-github-actions-for-your-organization#preventing-github-actions-from-creating-or-approving-pull-requests

**Comment by rnveach** [comment]
@romani Ping. I have no knowledge here.

**Comment by romani** [comment]
this is might be token or permission that author of PR has or specially limited to avoid outside people to get access to resources.
in Fork all is done by owner, trusted person.

as we have special logic in action `${{ github.event.pull_request.merged == true }}` that limits execution a lot, and content is trusty in this case. We should use PAT.

**Comment by rnveach** [comment]
@romani @stoyanK7 
https://github.com/checkstyle/checkstyle/actions/runs/4336909275/jobs/7572544051
> Run ./.ci/set-milestone-on-referenced-issue.sh 12799
PULL_REQUEST_NUMBER=12799
Error: Set not empty value to GITHUB_TOKEN environment variable
Error: Process completed with exit code 1.

This looks to be the latest from what I saw.

**Comment by stoyanK7** [comment]
@rnveach @romani Is there a `PAT` secret in the repository secrets?

**Comment by stoyanK7** [comment]
I think it comes from the
```yml
on:
  pull_request:
    types:
      - closed
```

Something tells me action should be executed on pushes to `master`.

**Comment by stoyanK7** [comment]
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflows-in-forked-repositories-2
> With the exception of GITHUB_TOKEN, secrets are not passed to the runner when a workflow is triggered from a forked repository. The GITHUB_TOKEN has read-only permissions in pull requests from forked repositories. For more information, see "[Automatic token authentication](https://docs.github.com/en/actions/security-guides/automatic-token-authentication)."

**Comment by romani** [comment]
>Something tells me action should be executed on pushes to master.

it will be more secure, and probably logical, as we use commit message as source of truth, it does not matter how commit come to master branch, it will be part of next release. The only extra complexity is what range of commits to use for validation.

**Comment by stoyanK7** [comment]
@romani

> The only extra complexity is what range of commits to use for validation.

Could you explain more?

For sure concurrency has to be deactivated.

> auto cancel will do a job for this action.

What do you mean by auto cancel?

**Comment by romani** [comment]
There are cases when one PR is merging two commits, we need to make sure a action will run on both commits.

>What do you mean by auto cancel?

https://github.com/checkstyle/checkstyle/blob/e70d42157269bce3568251f5db82fc3464281258/.github/workflows/codeql-analysis.yml#L19

**Comment by stoyanK7** [comment]
Oh yeah, makes sense. Back on it.

**Comment by romani** [comment]
I think we need to repeat what our release notes builder is doing in iteration of commits. Execute in same way.


Maybe even add this functionality to builder as extra mode.

**Comment by romani** [comment]
https://github.com/checkstyle/checkstyle/actions/runs/4339680750/jobs/7577497529

```
0s
Run ./.ci/set-milestone-on-referenced-issue.sh [1](https://github.com/checkstyle/checkstyle/actions/runs/4339680750/jobs/7577497529#step:3:1)2775
PULL_REQUEST_NUMBER=12775
Error: Set not empty value to GITHUB_TOKEN environment variable
Error: Process completed with exit code 1
```

**Comment by romani** [comment]
Fixed by https://github.com/checkstyle/checkstyle/pull/12801

**Comment by rnveach** [comment]
@stoyanK7 This still seems to be broken.
https://github.com/checkstyle/checkstyle/actions/runs/4369202639/jobs/7642723623#step:3:46

Please review and confirm.

**Comment by romani** [comment]
Yes, if not issue or pull, we should skip such commit
