### ISSUE TITLE
Create CI task to lint github actions

### ISSUE THREAD

**Issue by nrmancuso** [checkstyle/checkstyle#12501]
Noticed during work on #12435, github actions/workflows have a specific format and syntax that can be validated by [actionlint](https://github.com/rhysd/actionlint). While we will have yamllint in place after #12435, actionlint goes a few steps further for github action/workflows (only), to check things like:
 - deprecated commands
 - permissions
 - workflow names
 - job dependencies
 - contextual typing
 - shellcheck integration for scripts in `run`

Checking deprecated commands saves a lot of time from digging through workflow logs to find them. See a list of all checks available at https://github.com/rhysd/actionlint/blob/main/docs/checks.md.

Since we are increasingly favoring github actions and workflows for CI, extra validation in place will help to ease maintainence in the long term.

**Comment by rnveach** [comment]
Fix was merged
