### ISSUE TITLE
Use SHA-1 instead on non-standard SHA in PropertyCacheFile

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#1251]
Issue is in [PropertyCacheFile.java:201](../blob/master/src/main/java/com/puppycrawl/tools/checkstyle/PropertyCacheFile.java#L200).

According to http://stackoverflow.com/questions/14903539/what-specific-hash-algorithm-does-messagedigest-getinstancesha-return, `SHA` is non-standard one and `SHA-1` should be used.

**Comment by romani** [comment]
merged.
