### ISSUE TITLE
Empty ErrorStream in `checker-framework.groovy` to prevent buffer exhaustion and external processes from blocking

### ISSUE THREAD

**Issue by Vyom-Yadav** [checkstyle/checkstyle#12522]
Currently, `checker-framework.groovy` only empties the standard output stream and ignores the error stream. 
https://github.com/checkstyle/checkstyle/blob/f0633dcf0c0b4430ab6ded44bdd6aa3327b31039/.ci/checker-framework.groovy#L116-L121

This can cause the error stream buffer to fill completely which can block external processes. 

A better approach would be to redirect the error stream to prevent buffer from filling completely.

Source: https://wiki.sei.cmu.edu/confluence/display/java/FIO07-J.+Do+not+let+external+processes+block+on+IO+buffers

**Comment by rnveach** [comment]
Fix was merged
