### ISSUE TITLE
Simplify JavadocStyleCheck: remove functionality for missing package-info Javadoc

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#12520]
Identified at https://github.com/checkstyle/checkstyle/issues/7416 item 1,

https://checkstyle.org/config_javadoc.html#JavadocStyle

We are attempting to trim back JavadocStyleCheck to help with a conversion to AbstractJavadocCheck. The first thing is to remove functionality that is identified as already being available in other checks.

> Ensure package-info.java has a Javadoc.
> is a duplicate of MissingJavadocPackage (Since 8.22).

This will remove this functionality and guide users on how to migrate their check.

========

**Migration Notes**

Users will have to add `MissingJavadocPackage` to their configuration, if it is not there already. No other options are needed.

Old Config Example:
````
<module name="Checker">
    <module name="TreeWalker">
<module name="JavadocStyle"/>
    </module>
</module>
````

Migrated Config Example:
````
<module name="Checker">
    <module name="TreeWalker">
<module name="JavadocStyle"/>
<module name="MissingJavadocPackage"/>
    </module>
</module>
````

https://www.baeldung.com/java-package-info
https://stackoverflow.com/questions/22095487/why-is-package-info-java-useful

**Comment by nrmancuso** [comment]
Closed via #12521
