### ISSUE TITLE
Add support for more complex annotations in SuppressWarnings check

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#1252]
Examples of not supported annotation contents in [SuppressWarnings check](http://checkstyle.sourceforge.net/config_annotation.html#SuppressWarnings) :
```java
@SuppressWarnings("un" + "used")
@SuppressWarnings((String) "unused")
@SuppressWarnings({('u' + (char)'n') + ((""+((("used" + (String)""))))) + ((1 != 1) ? "" : ""),})
```

**Comment by romani** [comment]
@mkordas , Do we need support of this ? I would rather ignore them, even Eclipse have ERROR for such cases "The value for annotation attribute must be a constant expression", I noticed that sometime.
One more point is that we will never be able to support all craziness that human can do in code.

My proposal to add a note to javadoc/xdoc about unsupported cases.

**Comment by mkordas** [comment]
IntelliJ is fine with these annotations ;)

But I agree, there is no point in supporting such craziness. I've never seen such code in any project.
