### ISSUE TITLE
Don't gitignore IDE formatter settings

### ISSUE THREAD

**Issue by Bananeweizen** [checkstyle/checkstyle#12540]
Right now /.settings is gitignored, thereby not having any Eclipse specific settings in this repository. There might be a good intention, like verifying and managing the formatting in the checkstyle run when it verifies its own source code and similar.

However, the net result is rather bad: Every contributor using Eclipse commits changes in a style that is either the Eclipse defaults, or whatever he has changed in his personal workspace settings. It would be way more useful to commit Eclipse formatter settings in that directory, which make Eclipse format source code changed by contributors exactly like the project wants the sources to be formatted (without those contributors needing to know anything about the formatting style). That would simplify the life for non-regular committers.

I know how to configure such settings correctly and would like to commit them (that is jdt.core.prefs, jdt.ui.prefs, core.resources.prefs). They wouldn't have any effect on users of other tools, the CI system etc., but would simplify the life of Eclipse based contributors. Objections?

(And no, while I have already done similar changes for VS Code and IDEA, I'm not expert enough to commit similar settings there)

**Comment by romani** [comment]
It would be awesome if people have minimal amount of conflicts.

**Comment by Bananeweizen** [comment]
> In main repo we can not give preference to Eclipse, but we ok to host some instructions or ... To make it simpler. 

It doesn't work that way. The 3 files mentioned above must be committed in this repo. They will not change anything for anyone else doing other work.

> I might be wrong but we use to have eclipse settings in git, but it was heavily misused, people always tried to commit them and different Eclipse version is hard to reconcile .... , we might have some other approach

That's because most people just commit either the complete `settings` directory or nothing. Both are wrong. And as I said, I know how to do this right. There will not be any conflicts, there will not be any changes in those files from other developers, because they will not have to do any further local changes. It will just work for them.

**Comment by nrmancuso** [comment]
I think to commit these files in `.settings` as you propose would require a high bar to merge, such as:

1. CI job to validate autoformatting (run eclipse formatting from CLI and check diff)
2. No conflict with existing tools
3. Entire project formatted in this style

Which bring us to @romani's point about most contributors using IDEA. I have no actual numbers to back this up, but after maintaining the project for a few years it sure seems this way.  We are bound to run into conflicts between IDE's, and I am not sure that it is worth trying to resolve all such formatting errors between IDEs. Formatting can even change between versions of the same IDE.

All that aside, I think that the eclipse settings would be valuable to keep in the https://github.com/checkstyle/contribution repo, with some link from the eclipse setup page in our docs.

**Comment by rnveach** [comment]
> CI job to validate autoformatting (run eclipse formatting from CLI and check diff)

No NON-Eclipse user will want to do this. I already go through this for Linux only tools we use and am forced to copy a git diff to apply it to my local for CI to pass. I despise this the most from Checkstyle.

**Comment by Bananeweizen** [comment]
It's funny how everyone explains me how this doesn't work, even though they are not using Eclipse at all, and I have exactly these settings in my own local version, without creating any conflicts or reformatting the whole project code every time I change code.

**Comment by rnveach** [comment]
> even though they are not using Eclipse at all

I am the only Eclipse user of the normal Checkstyle admins/reviewers, atleast that is open about using it.

I also have settings enabled for Checkstyle but I know we can't enable a lot of them since non-Eclipse users will never trigger them unless something is added to the CI for this. One example we do have enabled is at https://github.com/checkstyle/checkstyle/blob/master/config/org.eclipse.jdt.core.prefs . We can't turn on autoformat, auto organize imports because of non-Eclipse users.

The other issue without enabling them in CI is if we update our other configs, no one will really remember to update these solo files as no one really validates against them since so many people don't use Eclipse.

The only way I can see any type of enablement of Eclipse specific settings is if we have them validated against in the CI, similar for what we do for IDEA and it's inspections.

**Comment by Bananeweizen** [comment]
> We can't turn on autoformat, auto organize imports because of non-Eclipse users. The 2 would have a battle as Eclipse users would autoformat the entire file, even on lines not changed, and non-Eclipse users will never obey formatting and do their own thing.

And that's exactly where everyone is wrong about how it works. It can be configured to only format touched lines, to not modify import order (or just in a certain way) etc. such that there is absolutely no back-and-forth editing.

And even if you wouldn't trust the auto-format, and auto-organize imports, it would still be useful to just configure the settings that say what kind of whitespace should be used, how names should be created (e.g. your checkstyle rules say that exceptions must not be named "e", and that can be avoided by changing one setting in Eclipse), which kind of comments shall be added to newly created methods etc. I have seen several of these issues as unwanted changes in PRs of others, and thought it would be good to automatically avoid that people run into those problems, at least in the IDE where I know how to avoid it for everyone. But I can live without contributing this.

**Comment by romani** [comment]
can we keep such files in contribution repo (https://github.com/checkstyle/contribution) and instruct users how to copy them before import.
in this case we can be agnostic to IDE (I have worries that after this files, users will ask too keep files for all other IDEs) and in same time let users share configs that are helpful.

most files in contrubution repo were in main repo 10 years ago, and I moved them out to focus on what matters most.
we can keep utilizing this repo for this reason.
