### ISSUE TITLE
Checkstyle are ignoring class usage in javadoc and marks import as unused

### ISSUE THREAD

**Issue by MairwunNx** [checkstyle/checkstyle#12546]
Checkstyle are ignoring the fact that class used in javadoc via @link uses specified import and marks that import as unused

Simple example:

```java
import java.util.concurrent.ConcurrentHashMap; // Checkstyle: Unused import - java.util.concurrent.ConcurrentHashMap. 

/**
* Bla bla bla {@link ConcurrentHashMap} bla bla bla
*/
public class Foo {
}
```

**Comment by rnveach** [comment]
@MairwunNx Please follow https://checkstyle.org/report_issue.html#How_to_report_a_bug.3F on reporting issues otherwise we will not be able to assist.

**Comment by Vyom-Yadav** [comment]
@MairwunNx I think you may be using the wrong configuration:
```xml
<module name="UnusedImports">                   
  <property name="processJavadoc" value="false"/>
</module>                                       
```
You should use the default configuration if you want to process javadoc i.e.:
```xml
<module name="UnusedImports"/>
```

**Comment by MairwunNx** [comment]
@Vyom-Yadav Thank you very much, I totally missed that. Closing the issue as it is now resolved.
