### ISSUE TITLE
Restore pitest.sh to ease operation on local

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#12557]
We lost pitest.sh files that was very convenient to use on local to validate pitest.

Right now it is two steps in Github action and users need to know how to craft command line.

we need to restore our easy ability as it was before `./.ci/pitest.sh ant` and it does all required.

**Comment by romani** [comment]
@nrmancuso , 
https://github.com/checkstyle/checkstyle/blob/069905ab1bdd6a866a6b2c1090c192e82e83100c/.github/workflows/pitest.yml#L61-L67

do we have any reasons to keep this steps separately ?

**Comment by Vyom-Yadav** [comment]
Do we want the complete file back? A short simple script to run both commands with user input will do the job.

**Comment by romani** [comment]
No restoration of what was before. We need new wrapper that execute mvn and groovy sequentially.

**Comment by Vyom-Yadav** [comment]
On it.

**Comment by nrmancuso** [comment]
> @nrmancuso ,
> 
> https://github.com/checkstyle/checkstyle/blob/069905ab1bdd6a866a6b2c1090c192e82e83100c/.github/workflows/pitest.yml#L61-L67
> 
> do we have any reasons to keep this steps separately ? keeping them as one step will do same in CI and ease users life on local to run pitest.

No need to separate them, we can just replace with one step that uses the new script.

**Comment by romani** [comment]
PR is sent

**Comment by nrmancuso** [comment]
Completed via #12561
