### ISSUE TITLE
Add 'when' to default IllegalIdentifierName pattern

### ISSUE THREAD

**Issue by nrmancuso** [checkstyle/checkstyle#12553]
I have read check documentation: https://checkstyle.sourceforge.io/config_naming.html#IllegalIdentifierName
I have compiled snapshot from #12531 
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

How it works now:
```bash                                                                                                          
➜  src cat Test.java 
public class Test {
    String m(Integer integer) {
        return switch(integer) {
          case Integer when when when < 0 -> when + " is negative";
          case null, default -> "";
        };
    }
}

➜  src cat config.xml 
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
  <module name="TreeWalker">
    <module name="IllegalIdentifierName"/>
  </module>
</module>

➜  src javac --enable-preview --release 19 Test.java
Note: Test.java uses preview features of Java SE 19.
Note: Recompile with -Xlint:preview for details.

➜  src java -jar checkstyle-10.5.1-SNAPSHOT-all.jar -c config.xml Test.java
Starting audit...
Audit done.

```

Expected:
```
➜  src java -jar checkstyle-10.5.1-SNAPSHOT--all.jar -c config.xml Test.java
Starting audit...
[ERROR] /home/nick/IdeaProjects/tester/src/Test.java:4:13: Name 'when' must match pattern '(?i)^(?!(record|yield|var|permits|sealed|when|_)$).+$'. [IllegalIdentifierName]
Audit done.
Checkstyle ends with 1 errors.

```

**Comment by romani** [comment]
better to focus on Check deal with single "when" , multiple only as super stability. I hope it will be blocked by javac in final version.

**Comment by Kevin222004** [comment]
I am on it

**Comment by Kevin222004** [comment]
so i want be able to see the ast till https://github.com/checkstyle/checkstyle/pull/12531 not get merged and i get the snapshot of that right

**Comment by nrmancuso** [comment]
@Kevin222004 you do not need to wait; since this check just looks at identifiers of other structures, it does not depend on #12531. You could make a branch off of the branch at #12531 to work on this if you wanted to, though. It goes something like this:

```
git checkout master
git fetch upstream pull/12531/head:pull-12531
git checkout pull-12531
git checkout -b issue-12553

```

**Comment by Kevin222004** [comment]
@nrmancuso I have reused your one java file form https://github.com/checkstyle/checkstyle/pull/12531 as i am not much aware of when and also not good resources form internet

**Comment by romani** [comment]
Users should do update in Check config by themselves if required. We will not make it as default, as there is too much affect.
