### ISSUE TITLE
Migrate from Travis to other CI pipeline

### ISSUE THREAD

**Issue by Vyom-Yadav** [checkstyle/checkstyle#12565]
Travis CI builds have been failing for a long time: 
https://app.travis-ci.com/github/checkstyle/checkstyle/builds/

The stabilization attempt at https://github.com/checkstyle/checkstyle/pull/12547 worked just for a few runs and failures started occurring again.

Migrate to other free CI options, like:

- GitLab CI for GitHub https://about.gitlab.com/solutions/github/ 
- Buildkite (https://buildkite.com/home)

Feel free to add more options.

**Comment by Vyom-Yadav** [comment]
@romani @nrmancuso @rnveach @strkkk @pbludov ping

**Comment by nrmancuso** [comment]
From https://docs.gitlab.com/ee/ci/ci_cd_for_external_repos/index.html: 

>GitLab CI/CD can be used with [GitHub](https://docs.gitlab.com/ee/ci/ci_cd_for_external_repos/github_integration.html), [Bitbucket Cloud](https://docs.gitlab.com/ee/ci/ci_cd_for_external_repos/bitbucket_integration.html), or any other Git server, though there are some [limitations](https://docs.gitlab.com/ee/ci/ci_cd_for_external_repos/index.html#limitations).

>Instead of moving your entire project to GitLab, you can connect your external repository to get the benefits of GitLab CI/CD.

>Connecting an external repository sets up [repository mirroring](https://docs.gitlab.com/ee/user/project/repository/mirror/index.html) and creates a lightweight project with issues, merge requests, wiki, and snippets disabled. These features [can be re-enabled later](https://docs.gitlab.com/ee/user/project/settings/index.html#configure-project-visibility-features-and-permissions).

Ok, so we would host a mirror on Gitlab... this is a good idea anyway, in case something happens to Github. We will need to make sure it is obvious that it is a mirror only, by shutting off issues, PRs, etc. We should also amend the README or repo description in Gitlab.


-----------------------

From  https://buildkite.com/pricing : 

> Buildkite is free for open source projects. Sign up for our Developer plan, if you need additional usage or inclusions, [contact us](https://buildkite.com/contact) and we’ll be happy to help.

Buildkite looks promising, too.

@Vyom-Yadav which options allow custom images to be used? I think this needs to be a new requirement for us going forward, as we spend a lot of time battling with dependencies, etc. If a CI allows us to use custom image, most CI tasks become simple:

1. start image
2. run some script
3. persist some artifacts (sometimes)

**Comment by Vyom-Yadav** [comment]
> which options allow custom images to be used?

You can pull images from any registry, you can set it up the way you want, and both allow this.

Both solutions are good and trusted, but I am more tempted to try Buildkite.

**Comment by romani** [comment]
lets try buildkite.
You can try creation of config on Free plan. and you become ready, I can apply to opensource plan.

**Comment by romani** [comment]
Let's close this, I am creating new issue for bitekite.
