### ISSUE TITLE
Lint GitHub Actions workflows executed twice

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#12568]
![image](https://user-images.githubusercontent.com/812984/210149835-d426e0c7-1a18-4f69-b7be-d05928a00929.png)

expected: one execution.

**Comment by romani** [comment]
@nrmancuso , ^^^

**Comment by nrmancuso** [comment]
From https://github.com/checkstyle/checkstyle/pull/12569#issuecomment-1369080345:
>@nrmancuso , after merge please test it by PR from branch in this repo (not a fork)

Before closing this issue, we need to test by creating a PR on a repo branch.

**Comment by nrmancuso** [comment]
Proof that we now only have one actionlint execution in repo branch:
![image](https://user-images.githubusercontent.com/31252532/210301650-21b2865a-f788-4223-b215-8a5a8c8e3f24.png)

**Comment by nrmancuso** [comment]
@romani please close issue and test PR at https://github.com/checkstyle/checkstyle/pull/12582 if you are good
