### ISSUE TITLE
add step of git config command before cloning the repository.

### ISSUE THREAD

**Issue by Aarav238** [checkstyle/checkstyle#12577]
I have read check documentation: https://checkstyle.org/config_xxxxxx.html#NameOfAffectedCheck
I have downloaded the latest cli from: https://checkstyle.org/cmdline.html#Download_and_Run
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

**How it works Now:**

```bash
/var/tmp $ javac YOUR_FILE.java
#[[MAKE SURE THERE IS SUCCESSFUL COMPILATION]]

/var/tmp $ cat config.xml
#[[PLACE YOUR OUTPUT HERE]]

/var/tmp $ cat YOUR_FILE.java
#[[PLACE YOU OUTPUT HERE]]

/var/tmp $ RUN_LOCALE="-Duser.language=en -Duser.country=US"
/var/tmp $ java $RUN_LOCALE -jar checkstyle-X.XX-all.jar -c config.xml YOUR_FILE.java
#[[PLACE YOUR OUTPUT HERE]]
```

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**
- When we run mvn install after cloning the repo some of the test get fails.
-  If we run this command this command in the terminal 
```
git config core.autocrlf
```
- After this maven install will complete without any issue.

**Additional context**

Still not clear ???
see examples:

- https://checkstyle.org/report_issue.html#How_to_request_new_feature_for_existing_functionality.3F

- https://checkstyle.org/report_issue.html#How_to_request_new_Check.2FModule.3F

**Not a feature?**
If (Check, property, new behavior) that you are requesting is already
implemented and you are unsatisfied with their behaviour, report it here
in bug template format:

- https://checkstyle.org/report_issue.html#How_to_report_a_bug.3F

ATTENTION: FAILURE TO FOLLOW THE ABOVE TEMPLATE WILL RESULT IN THE ISSUE BEING CLOSED.

**Comment by Aarav238** [comment]
I have raised PR related to this issue.

**Comment by nrmancuso** [comment]
@Aarav238 please follow issue template, otherwise issue will be closed. Also - we do not accept PRs for issues that are not approved.

**Comment by Aarav238** [comment]
@nrmancuso  I tried to followed but i have given the description of issue. What i need to add more?

**Comment by nrmancuso** [comment]
Show CLI output of cloning without this command that contains failure/ problem you are trying to resolve, show output with command that shows success, remove parts of template that do not apply.

**Comment by Aarav238** [comment]
I have add screenshots ? @nrmancuso

**Comment by nrmancuso** [comment]
Screenshots are not very helpful in reproduction of issues, please share CLI output of failure/ success

**Comment by Aarav238** [comment]
okay

**Comment by romani** [comment]
@Aarav238 , please share your problem as you reported it in gitter.

**Comment by Aarav238** [comment]
same tests are getting failed again @romani

**Comment by romani** [comment]
@Aarav238, please declare problem from scratch, other mentors are confused on context

**Comment by Aarav238** [comment]
should i tell here or on gitter? @romani

**Comment by nrmancuso** [comment]
@Aarav238 pretend you have no knowledge/context of problem, and read your issue description attentively ; it is very difficult to understand, especially because of parts of the template that are left there. Update the issue description so that anyone can very easily read and understand your problem.

**Comment by nrmancuso** [comment]
@Aarav238 pretend you have no knowledge/context of problem, and read your issue description attentively ; it is very difficult to understand, especially because of parts of the template that are left there. Update the issue description so that anyone can very easily read and understand your problem.

**Comment by Aarav238** [comment]
okay @nrmancuso . I am sorry. Let me try to describe the issue

**Comment by Aarav238** [comment]
@nrmancuso  I am closing this issue and i'll open the new issue with proper template and description.
