### ISSUE TITLE
update all release action to have 'Setup local maven cache' step to optimize download of artifacts

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#12571]
all actions that executes `mvn` takes a lot of time to download jars .... we need to use maven cache as we do in other actions that works on PRs 

example: https://github.com/checkstyle/checkstyle/blob/bef49aea4a923bc003b0ffd1338b8f1606f2badc/.github/workflows/pitest.yml#L54

**Comment by romani** [comment]
@stoyanK7 , please help to fix this issue

**Comment by stoyanK7** [comment]
On it.

**Comment by romani** [comment]
it was and issue at "release: prepare" https://github.com/checkstyle/checkstyle/actions/runs/4054790160/jobs/6977062039
