### ISSUE TITLE
`bump_license_year.yml` not adding year to commit message.

### ISSUE THREAD

**Issue by Vyom-Yadav** [checkstyle/checkstyle#12572]
Noted at https://github.com/checkstyle/checkstyle/commit/54616f662130aa0ca5afe45f72d36cdefb78a781, the commit message didn't include the year, however, the changes made by the commit are correct.

The bad commit message was:
> minor: Bump year to 

It should have been:
> minor: Bump year to 2023

**Comment by rnveach** [comment]
@Vyom-Yadav Doesn't this expand to other repos as well?

https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/master/.github/workflows/bump_license_year.yml
https://github.com/checkstyle/contribution/blob/master/.github/workflows/bump_license_year.yml

@romani Is there any other repos? Is there a list for this somewhere?

**Comment by Vyom-Yadav** [comment]
Strange, why is cron different in all the jobs, is it intentional? I am sending a fix for all repos.

**Comment by rnveach** [comment]
@romani can explain it better.

Another, https://github.com/sevntu-checkstyle/methods-distance/blob/master/.github/workflows/bump-license-year.yml .

**Comment by romani** [comment]
Cron is slightly different to let naun repo be updated first, dependable repositores update after. Distance might be in 1-2 hour as in main repo queue is longer.
