### ISSUE TITLE
Resolve surviving annotation mutations for pitest

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#12591]
Mutations:
https://github.com/checkstyle/checkstyle/blob/master/config/pitest-suppressions/pitest-annotation-suppressions.xml

This issue will resolve the remaining suppression and remove the entire file. POM is not at 100% for this profile, so the profile needs to be updated.

This is blocked by https://github.com/hcoles/pitest/issues/1137 (target pitest release 1.10.5) as all the suppressions are basically false positives and cannot be resolved.

**Comment by rnveach** [comment]
Issue is now unblocked with pitest bump, I will be resolving the issue.

**Comment by nrmancuso** [comment]
Completed via #12719
