### ISSUE TITLE
Validation for next version in GitHub action 

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#12608]
I did typo at version bump
https://github.com/checkstyle/checkstyle/actions/runs/3863258249/jobs/6585335155#step:3:1

I put 1.7.0 instead 10.7.0

We need enforce validation to be allow bump only for +1 in any of digits from previous. Ideally we should use more smart validation, but let's see what can we do with less efforts

**Comment by romani** [comment]
Attempt to fix resulted in error at milestone update 
https://github.com/checkstyle/checkstyle/actions/runs/3863310120/jobs/6585423852

```
Run .ci/update-github-milestone.sh 10.7.0
TARGET_VERSION=10.7.0
Updating milestone at github
jq: error (at <stdin>:1): Cannot index object with number
Error: Process completed with exit code 5.
```

I fixed milestone manually. But we need to think how to make output more descitive on what is problematic

**Comment by romani** [comment]
@stoyanK7 , please help to fix this issue.

**Comment by stoyanK7** [comment]
On it.

**Comment by stoyanK7** [comment]
> I fixed the milestone manually. But we need to think how to make output more descriptive on what is problematic

@romani We can change `jq` to do a `try-catch` block and print the input it got from `curl` if parsing the json fails.
```
curl -s -X GET https://api.github.com/repos/checkstyle/checkstyle/milestones?state=open | jq '. as $raw | try (.[0]|.id) catch $raw'
```
![Screenshot from 2023-02-04 22-37-38](https://user-images.githubusercontent.com/23459549/216790590-381d0830-6c8e-461f-8936-1ca69e7a404c.png)

**Comment by romani** [comment]
Better to fail at https://github.com/checkstyle/checkstyle/blob/master/.ci/bump-version.sh

May be there is something already done in web to restrict typos, I doubt only we run into this
