### ISSUE TITLE
`pitest-survival-check-xml.groovy` should automatically update list of suppressions

### ISSUE THREAD

**Issue by Vyom-Yadav** [checkstyle/checkstyle#12613]
Current Behaviour: The user has to manually patch the list of suppressions if new suppressions needed to be added or old suppressions need to be removed.

Expected Behaviour: The script automatically updates the list of suppressions. Similar to what [checker-framework.groovy](https://github.com/checkstyle/checkstyle/blob/master/.ci/checker-framework.groovy) does.

**Comment by rnveach** [comment]
Fix was merged
