### ISSUE TITLE
Resolve surviving pitest-blocks mutations for pitest

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#12615]
Mutations:
https://github.com/checkstyle/checkstyle/blob/master/config/pitest-suppressions/pitest-blocks-suppressions.xml

This issue will resolve the remaining suppressions and remove the entire file. POM does need to be updated.

~Part of this issue is blocked by https://github.com/hcoles/pitest/issues/1137 (target pitest release 1.10.5) as those suppressions are basically false positives and cannot be resolved.~

**Comment by nrmancuso** [comment]
Completed via #12618
