### ISSUE TITLE
Resolve surviving pitest-coding-require-this-check mutations for pitest

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#12626]
Mutations:
https://github.com/checkstyle/checkstyle/blob/master/config/pitest-suppressions/pitest-coding-require-this-check-suppressions.xml

This issue will resolve the remaining suppressions and remove the entire file. POM does need to be updated.

**Comment by nrmancuso** [comment]
@rnveach which PR will have pom update?

**Comment by rnveach** [comment]
@nrmancuso It depends which PR is the last to merge? I can't specify 100% when there are 2 open PRs. While there is a rounding issue with pitest, most likely, neither one will register 100% without the other.

**Comment by rnveach** [comment]
Fixes were merged
