### ISSUE TITLE
pitest: validate wildcards on target classes

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#12625]
Identified at https://github.com/checkstyle/checkstyle/pull/12622 ,

https://github.com/checkstyle/checkstyle/blob/811983e0f89edf2419b9165ca60bb04a7c3c1ea6/pom.xml#L3355

We need to create a new validation, that ensures all `targetClasses` provided to the pitest profiles have a `*` on the end of them. The `*` is needed to include all sub-classes of the target class. Without it, pitest will miss mutations as we saw in the mentioned PR.

**Comment by romani** [comment]
Yes, may be we can use xmlstarlet to print required tags and grep to accomplish this

**Comment by nrmancuso** [comment]
I am on it
