### ISSUE TITLE
Resolve surviving pitest-design-check mutations for pitest

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#12641]
Mutations:
https://github.com/checkstyle/checkstyle/blob/master/config/pitest-suppressions/pitest-design-suppressions.xml

This issue will resolve the remaining suppressions and remove the entire file. POM does need to be updated.

**Comment by bharatsheoran03** [comment]
I want to work on this issue, but I don't know how to do as I am beginner and new to open source. Proper guidance can help to resolve this issue.

**Comment by rnveach** [comment]
@bharatsheoran03 This issue is already being worked on.

Please look over https://github.com/checkstyle/checkstyle/wiki/To-GSoC-participant to begin.

**Comment by rnveach** [comment]
Fix was merged
