### ISSUE TITLE
All Github CI workflows should have concurrency of 1

### ISSUE THREAD

**Issue by nrmancuso** [checkstyle/checkstyle#12645]
Currently, all of our Github workflows will continue to run after new pushes to a PR. This is usually pointless, and consumes a lot of extra resources (credits + occupied containers). This causes other workflows to be queued for long periods, and also can slow down the release process.

Solution: we need to set all github workflows to have a concurrency of 1, and automatically cancel in progress workflows.

Example of yaml update:
```
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
```

We also need to create some check to make sure that all github workflows have this concurrency setting.

**Comment by rnveach** [comment]
We do this for other CIs, it shouldn't be any different for GH CI.

> credits 

Can you point to where GH CI says we are using credits?

**Comment by nrmancuso** [comment]
>Can you point to where GH CI says we are using credits?

Github calls them minutes: https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions. I would venture a guess and say that we use more than the given number of minutes per month, so maybe this is not a hard limit.

**Comment by rnveach** [comment]
Fix was merged
