### ISSUE TITLE
Cannot use config file bundled in jar

### ISSUE THREAD

**Issue by stinny** [checkstyle/checkstyle#1265]
Starting from 6.8, config file bundled in jar can no longer be used.
```
> java -jar checkstyle-6.8-all.jar -c /sun_checks.xml MyClass.java
unable to find '/sun_checks.xml'.
```

The breaking commit is https://github.com/checkstyle/checkstyle/commit/3004b4d8810fae5956864d1493ea94f183b9442c

**Comment by romani** [comment]
merged.
