### ISSUE TITLE
Picocli's coloring interfering with tests

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#12667]
Identified at https://github.com/checkstyle/checkstyle/pull/12545 ,

It was identified at https://github.com/checkstyle/checkstyle/pull/12545#issuecomment-1378719744 , that when our project's tests on Git Bash on Windows, which in turn run picocli and look at it's output, the picocli part of the run in the tests differed than the expected results and failed the run.

The command being run is: mvn clean verify

After testing, it was identified at https://github.com/checkstyle/checkstyle/pull/12545#issuecomment-1380783716 , that it is actually colors causing the difference in the output. By using Ansi.OFF, running our tests in Git Bash passed and there was no longer differences on color.

This issue is about how we will handle this issue. Our choices are:
1) Turn off colors in picocli completely.
2) Turn off colors in picocli for test. (probably preferred over 4) (Thanks to @remkop)
3) Add a test/document the issue when colors will possibly show up.
4) Strip colors from the test output.

**Comment by remkop** [comment]
Picocli itself solves this problem by ensuring environment-independent behaviour in the tests.
Any tests that verify the usage help message should:

* (if just verifying the usage help text without verifying coloring): ensure colors are switched OFF by explicitly setting system property `picocli.ansi` to `false`; now the test can reliably verify that the output matches the expected usage help text (without ANSI escape codes)
* (if the test intends to verify coloring also - this is rare): ensure colors are switched ON by explicitly setting system property `picocli.ansi` to `true` and verifying that the output has the expected ANSI escape codes

**Comment by romani** [comment]
Fix is merged
