### ISSUE TITLE
Replace doctype with W3C schema

### ISSUE THREAD

**Issue by delanym** [checkstyle/checkstyle#12661]
Hi there. Im trying to sort the checkstyle.xml file during a build using the [sortpom-maven-plugin](https://github.com/Ekryd/sortpom).
The author has made the plugin reject any xml with a doctype declaration (for security reasons), see https://github.com/Ekryd/sortpom/issues/281
``` xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
          "https://checkstyle.org/dtds/configuration_1_3.dtd">
```

I don't particularly care either way, but then why not just replace the doctype with a W3C xml schema instead?

There are tools for converting DTD to XSD, such as https://www.w3.org/2000/04/schema_hack/
Using the updated tools at http://lists.xml.org/archives/xml-dev/200101/msg00481.html
I run `perl dtd2xsd.pl -ns https://checkstyle.org/configuration/1.3 configuration_1_3.dtd`
resulting in an XSD:
``` xsd
<schema
  xmlns='http://www.w3.org/2000/10/XMLSchema'
  targetNamespace='https://checkstyle.org/configuration/1.3'
  xmlns:t='https://checkstyle.org/configuration/1.3'>

 <element name='module'>
  <complexType>
   <choice minOccurs='0' maxOccurs='unbounded'>
    <element ref='t:module'/>
    <element ref='t:property'/>
    <element ref='t:metadata'/>
    <element ref='t:message'/>
   </choice>
   <attribute name='name' type='NMTOKEN' use='required'/>
  </complexType>
 </element>

 <element name='property'>
  <complexType>
   <attribute name='name' type='NMTOKEN' use='required'/>
   <attribute name='value' type='string' use='required'/>
   <attribute name='default' type='string' use='optional'/>
  </complexType>
 </element>

 <element name='metadata'>
  <complexType>
   <attribute name='name' type='NMTOKEN' use='required'/>
   <attribute name='value' type='string' use='required'/>
  </complexType>
 </element>

 <element name='message'>
  <complexType>
   <attribute name='key' type='NMTOKEN' use='required'/>
   <attribute name='value' type='string' use='required'/>
  </complexType>
 </element>
</schema>
```

Then the checkstyle.xml will start
``` xml
<?xml version="1.0" encoding="UTF-8"?>
<module name="Checker" xmlns="https://checkstyle.org/configuration/1.3"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="https://checkstyle.org/configuration/1.3 https://checkstyle.org/checkstyle-v3_0.xsd">
```
Also note the added **encoding** attribute in the xml declaration/xml prolog.

With a modified schemaLocation to a local copy, both the Intellij extension and the maven-checkstyle-plugin fail with
`Failed during checkstyle configuration: unable to parse configuration stream - Document root element "module", must match DOCTYPE root "null".:2:209`

**Comment by nrmancuso** [comment]
@delanym Thanks for the detailed issue description; can you add your checkstyle version please?

**Comment by delanym** [comment]
Im sorry but why do I always get this response - I know very well you dont maintain the Maven plugin. Are you telling me checkstyle still functions if you remove the DOCTYPE element of your checkstyle.xml file?

Im using Checkstyle-IDE 5.75.0 which uses Checkstyle 10.6.0
also maven-checkstyle-plugin v3.2.1

**Comment by delanym** [comment]
The checkstyle_checks.xml has a curious history
![image](https://user-images.githubusercontent.com/5310238/213190976-4abcf09b-e194-4b3d-93a7-7ff7f30fdf44.png)

Why does xdocs/google_style.xml use a W3C schema?
``` xml
<?xml version="1.0" encoding="UTF-8"?>

<document xmlns="http://maven.apache.org/XDOC/2.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/XDOC/2.0
                              https://maven.apache.org/xsd/xdoc-2.0.xsd">
```

**Comment by rnveach** [comment]
> Why does xdocs/google_style.xml use a W3C schema?

xdocs is our website documentation. It is not the checkstyle configuration file. I assume the program that generates the final HTML uses that schema.

**Comment by nrmancuso** [comment]
>Im sorry but why do I always get this response - I know very well you dont maintain the Maven plugin. 

I am not familiar with other responses that you might have received, but if they are also reported in the same way (`maven-checkstyle-plugin fails...`), it is understandable. Our issue and feature request templates demand reproduction via our CLI. This is for several reasons:
1. Many of our contributors are students, and it is very helpful for them to be able to easily reproduce the issue
2. Maintainers have limited time, the easier it is for us to reproduce your issue
3. Make sure that some third party (maven checkstyle plugin in this case) is not affceting the behavior in any way

>Are you telling me checkstyle still functions if you remove the DOCTYPE element of your checkstyle.xml file?

I have no idea, we won't know until we try it out via CLI :)
