### ISSUE TITLE
Resolve pitest for FinalLocalVariableCheck

### ISSUE THREAD

**Issue by Kevin222004** [checkstyle/checkstyle#12671]
Part of https://github.com/checkstyle/checkstyle/issues/12341

This issue contains all the mutations for `FinalLocalVariableCheck` from

https://github.com/checkstyle/checkstyle/blob/6647ab368fb58e4ca8c71c1ffc029d0122bce227/config/pitest-suppressions/pitest-coding-2-suppressions.xml#L39-L91

 profile pitest-coding-2-suppressions.xml

**Comment by Kevin222004** [comment]
@romani please approve this so I start working on this

**Comment by romani** [comment]
I highly recommend to not send PR as soon as at least one survival is killed.
It is completely ok to send few PRs for same issue. The smaller PR the easier review and quicker merge.

**Comment by stoyanK7** [comment]
@Kevin222004 Out of curiosity, have you managed to kill any of those mutations?

**Comment by Kevin222004** [comment]
@stoyanK7 no I have not done anything to kill this mutation

**Comment by romani** [comment]
I removing self assignment

**Comment by coderdeadpool** [comment]
I am on Mutation: 
https://github.com/checkstyle/checkstyle/blob/5768a5e30a00ad8c2ae80da5fb67961219acf7b6/.ci/pitest-suppressions/pitest-coding-2-suppressions.xml#L57-L64

**Comment by coderdeadpool** [comment]
I am on Mutation:
https://github.com/checkstyle/checkstyle/blob/b9cd0cb3553a21795d27a0238625c96ed8f8a33d/config/pitest-suppressions/pitest-coding-2-suppressions.xml#L12-L19

**Comment by coderdeadpool** [comment]
I am on Mutation:
https://github.com/checkstyle/checkstyle/blob/e1e578b472d2730f82b0963173ab462be5e54901/config/pitest-suppressions/pitest-coding-2-suppressions.xml#L12-L19

**Comment by romani** [comment]
issue is resolved by inscope of project "Pitest Resolution" by some referenced above commits.
