### ISSUE TITLE
Re-enable action lint

### ISSUE THREAD

**Issue by nrmancuso** [checkstyle/checkstyle#12678]
Actionlint docker image does not like arguments to the container, see https://github.com/checkstyle/checkstyle/actions/runs/3998588410/jobs/6861429747:

```
could not read "deprecated.*'": open deprecated.*': no such file or directory


```

It is splitting the arguments even if we use `=` or enclose them in quotes. Let's disable actionlint for now to unblock restoration of diff report generation with patch config, and deal with actionlint later.

**Comment by nrmancuso** [comment]
@stoyanK7 as you are github action expert, can you help with this issue?

**Comment by stoyanK7** [comment]
@nrmancuso Is this what you are looking for?

https://github.com/stoyanK7/checkstyle/actions/runs/4553573127/jobs/8030294702#step:4:6
```
.github/workflows/release-new-milestone-and-issues-in-other-repos.yml:27:92: property "concurrency-group" is not defined in object type {version: any} [expression]
.github/workflows/release-publish-releasenotes-twitter.yml:23:92: property "concurrency-group" is not defined in object type {version: any} [expression]
.github/workflows/release-update-github-io.yml:23:92: property "concurrency-group" is not defined in object type {version: any} [expression]
.github/workflows/release-update-github-page.yml:23:92: property "concurrency-group" is not defined in object type {version: any} [expression]
.github/workflows/release-upload-all-jar.yml:26:92: property "concurrency-group" is not defined in object type {version: any} [expression]
```

All these should work:
 - `-ignore=".* was deprecated.*"`
 - `'-ignore ".* was deprecated.*"'`
 - `-ignore ".* was deprecated.*"`
 
From https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepswithargs
> A single argument that includes spaces should be surrounded by double quotes `""`

**Comment by romani** [comment]
fix is merged
