### ISSUE TITLE
Checking existance of config file before processing target file.

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#1267]
https://github.com/checkstyle/checkstyle/commit/3004b4d8810fae5956864d1493ea94f183b9442c that commit was reverted, please review #1265.

Write provide integration tests and UTs for Main to avoid such cases in future.

**Comment by romani** [comment]
@Bhavik3 , please address.

**Comment by Bhavik3** [comment]
@romani 
From Main, How can I check for `-jar` option?

**Comment by romani** [comment]
launch as command line from java, smth like https://docs.oracle.com/javase/7/docs/api/java/lang/Runtime.html#exec%28java.lang.String%29

**Comment by Bhavik3** [comment]
My solution is to:
First check for config location as we did before.
If file not exist in that way, check for config location in .classpath
If still not exist then give error message.

Is it fine?

**Comment by romani** [comment]
yes

**Comment by Bhavik3** [comment]
ok
I implemented it. works fine.
But, how can I write UT for it.

**Comment by romani** [comment]
try to create a file in target folder  ..... need to be investigateds

**Comment by Bhavik3** [comment]
Intermediate solution:
https://github.com/Bhavik3/checkstyle/commit/5369f353d5f7dd9086e4e5f109c731c48b0e5e4e

problem is naming of jar file in target folder....(can differ by version)

Or, have other method to generate jar in pre-defined name.

**Comment by Bhavik3** [comment]
@romani 
Have check this out?

**Comment by romani** [comment]
not yet, but I will for sure. 

You can do smth else meanwhile.

**Comment by romani** [comment]
1) You need to create integration test , not a UTs
Please review https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html#A_Build_Lifecycle_is_Made_Up_of_Phases
ITs are next step after package.

You need to create new package there:
https://github.com/checkstyle/checkstyle/tree/master/src/it/java
as "com/puppycrawl/tools/checkstyle" and create a new test file , that will be launched during ITs phase only.

2) 
> mvn clean package -Passembly -Dlinkcheck.skip=true

maven should do that for for you, please review options of http://maven.apache.org/surefire/maven-failsafe-plugin/integration-test-mojo.html to not hardcode any strict version and build commands in ITs files.

**Comment by Bhavik3** [comment]
@romani 
I am poor working with maven. I can't find how to generate Jar file. 
Never work on Integration test. Need help here..

**Comment by romani** [comment]
> Never worked on Integration test.

ITs are just another UTs but working after package phase is done , so they could test binaries as it would be done by user.

>  I can't find how to generate Jar file.

https://github.com/checkstyle/checkstyle/blob/master/config/assembly-bin.xml#L14 here is how "-all" jar is generated. Please update that config to gnerate the same content jar but without version there.

Here is maven plugin - https://github.com/checkstyle/checkstyle/blob/master/pom.xml#L1034 that responsible for "all" jar generation. That plugin exists in special profile, so it will not be launched in general maven build till "-Passembly" is specified. So we need to investigate a way to do "all" jar generation during general build too.

Or we could think about running  ITs over checkstyle-6.8.2.jar but classpath need to be setup for it.

Please continue investigation of maven, If you run into problem let me know - I will help you.

**Comment by Bhavik3** [comment]
@romani 
I don't know how to generate -all jar. You can assign it to someone. I don't think I can find some maven plugin to generate jar with particular name.

**Comment by romani** [comment]
It is ok, task is not simple.

Alljar is generated by mvn clean package -Passembly

**Comment by romani** [comment]
merged.
