### ISSUE TITLE
Remove Serializable interface from Violation class and EventObject extension from AuditEvent

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#12681]
Since we don't use serialization, we will remove this class being serializable as it is not serializable due to `arg` field.

Serialization was added at https://github.com/checkstyle/checkstyle/commit/d2af4accdde3eac0a2103353f490e97bf62f61d2#diff-52efb9bb7c26b577e3885a9539eac7d5R42 titled Apply parts of patch #1952556 fixing some FindBugs bugs. Thanks to Travis Schneeberger.

http://git.net/ml/java.audit.checkstyle.devel/2008-04/msg00067.html

Findbugs does produce this error if I remove the serialization:

`    [INFO] Class com.puppycrawl.tools.checkstyle.api.AuditEvent defines non-transient non-serializable instance field localizedMessage [com.puppycrawl.tools.checkstyle.api.AuditEvent] In AuditEvent.java SE_BAD_FIELD`

This is because AuditEvent is serialized through inheritance of EventObject.
Such inheritance also should be removed. 

============

Now this is become why is `AuditEvent` serialized and need `EventObject`.

-------

Second problem of serialization:
Detected by IDEA inspection and Sonar Inspection Make "args" transient or serializable.
https://sonarcloud.io/project/issues?id=org.checkstyle%3Acheckstyle&issues=AW9t2w2MYD2QG1pPXIUJ&open=AW9t2w2MYD2QG1pPXIUJ

https://github.com/checkstyle/checkstyle/blob/54616f662130aa0ca5afe45f72d36cdefb78a781/src/main/java/com/puppycrawl/tools/checkstyle/api/Violation.java#L67-L76

Slightly related problem: https://github.com/checkstyle/checkstyle/issues/7488#issue-551562551 but a different approach.

=====

PR Discussion resolution for second problem:

Changing `args` to something more serializable would be a huge break for whole Checkstyle. This would impact property files which use special properties of `MessageFormat` to format the argument into a meaningful display.

**Comment by nitishmalang** [comment]
please assign me i can work on this issue

**Comment by rnveach** [comment]
@nitishmalang This is already taken and has a PR awaiting review.

**Comment by romani** [comment]
Should we title issue something as `Remove serializable interface from Violation class` ?

**Comment by nrmancuso** [comment]
Closed via #12675
