### ISSUE TITLE
Use Environment Files instead of `set-output` in GitHub Actions.

### ISSUE THREAD

**Issue by Vyom-Yadav** [checkstyle/checkstyle#12696]
From https://github.com/checkstyle/checkstyle/actions/runs/4055751603/jobs/6979309020

`
Warning: The set-output command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
`

See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ for the new way to `set-output`.

**Comment by nrmancuso** [comment]
Will be done in scope of https://github.com/checkstyle/checkstyle/issues/12678

**Comment by Vyom-Yadav** [comment]
Cool, let's keep this open so we don't forget about this, are you working on it?

**Comment by romani** [comment]
Let's not be blocked by referenced issue, GitHub already show violation, it is better to fix it sooner. Referenced issue will enforce best practices, it is second step.

**Comment by nrmancuso** [comment]
Closed via https://github.com/checkstyle/checkstyle/pull/12970
