### ISSUE TITLE
Make coverage 100% for Indentation check

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#1270]
[Indentation check](../blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheck.java) requires 100% code coverage, as it is pure algorithm.

**Comment by romani** [comment]
coverage is 100% - https://codecov.io/github/checkstyle/checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation?ref=5d967ca3168da2a2d1674683d8a23e921b9f6067

Thanks a lot for your help !
