### ISSUE TITLE
Remove admins from white list on commit validation 

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#12717]
https://github.com/checkstyle/checkstyle/actions/runs/4076473411/jobs/7024253795#step:4:121

Commit:
Issue 12705: remove .m2 for codenarc execution to make it more stable

Symbol # is missing.
Missed validation due to https://github.com/checkstyle/checkstyle/blob/a144e7fb576f6a875bf5a630190754ca025b7381/src/test/java/com/puppycrawl/tools/checkstyle/internal/CommitValidationTest.java#L72
It was fine for long time, but now, as all automated, all should follow rules. Admins always have all permissions to skip CI and brutal action if required, so better for now for all to follow. Admins should be removed fr this list.

Exception:
```
Exception in thread "main" java.lang.NumberFormatException: For input string: "Issue 12705"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at com.github.checkstyle.github.CommitMessage.getIssueNumber(CommitMessage.java:81)
```

Additionally, we should fallback release notes categories to "misc" if something is wrong with parsing a format, we need to update release notes generator.

**Comment by romani** [comment]
@stoyanK7 , please help to fix this.

**Comment by stoyanK7** [comment]
On it.

**Comment by stoyanK7** [comment]
> Additionally, we should fallback release notes categories to "misc" if something is wrong with parsing a format, we need to update release notes generator.

On that as well.

**Comment by stoyanK7** [comment]
@romani This one can be closed.

**Comment by romani** [comment]
Hmm , and now we have a problem that release notes builder is not failing if labels are not defined.

**Comment by rnveach** [comment]
Issue seems to be https://github.com/checkstyle/contribution/blob/2617fbafa32323ef3c3a4b25172388451177c8c1/releasenotes-builder/src/main/java/com/github/checkstyle/github/NotesBuilder.java#L138 returns false when it shouldn't.

**Comment by stoyanK7** [comment]
If that is the case, why did `CommitValidationTest` not fail?
https://github.com/checkstyle/checkstyle/blob/a144e7fb576f6a875bf5a630190754ca025b7381/src/test/java/com/puppycrawl/tools/checkstyle/internal/CommitValidationTest.java#L74

**Comment by stoyanK7** [comment]
Alright, I see it removes the line endings..
https://github.com/checkstyle/checkstyle/blob/a144e7fb576f6a875bf5a630190754ca025b7381/src/test/java/com/puppycrawl/tools/checkstyle/internal/CommitValidationTest.java#L190

**Comment by stoyanK7** [comment]
Shall I just do the same in `isIssueOrPull()` then?

**Comment by romani** [comment]
Now missed label is detected https://github.com/checkstyle/checkstyle/actions/runs/4152982784/jobs/7184317745#step:4:126
