### ISSUE TITLE
Make scripts and configurations filenames consistent

### ISSUE THREAD

**Issue by stoyanK7** [checkstyle/checkstyle#12716]
The `.github/workflows` folder is inconsistent with the filenames inside it. We have some mix of `kebab-case` and `snake_case`.

```
stoyan @ zenbook: ~/open-source/checkstyle/.github/workflows                                                                                                                master [↑]
$ ls                                                                                                                                                                               10:38:44 pm
actionlint.bak                         codeql-analysis.yml           new-milestone-and-issue-in-other-repo.yml  publish_releasenotes_outside.yml  site.yml
bump_license_year.yml                  copy_site_to_sourceforge.yml  no-exception-workflow.yml                  rebase.yml                        update_github_io.yml
bump-version-and-update-milestone.yml  diff_report.yml               no_old_refs.yml                            releasenotes-gen.yml              update_sources.yml
checker-framework.yml                  error-prone.yml               pitest.yml                                 run_link_check.yml                upload-all-jar.yml
check-pr-description.yml               maven_prepare.yml             publish_releasenotes_for_twitter.yml       shellcheck.yml

```

I noticed GitHub uses `kebab-case` in their GitHub Actions documentation, but some people suggest depending on the surrounding software so that would be `PascalCase` in checkstyle's case? For me, it doesn't matter as long as it's consistent.

---
Further edit:
Since we are covering 
> We should use kebab-case for naming of scripts or configs.

we include the scripts in the `.ci` folder as well.

# Folders to cover
- [x] `.ci`
- [x] `.github/workflows`
- [x] `config`

**Comment by romani** [comment]
We should use kebab-case for naming of scripts or configs.  But until we have Check that does enforcement on each build , it is hard.

We need look if we can do this by some of our Checks. And renaming is good, at least new contributor will more likely to follow, if all around is same

**Comment by stoyanK7** [comment]
On it. We have a couple of `RegexpOnFilenameCheck` set up in `checkstyle_checks.xml`. I will see what can be done.

**Comment by romani** [comment]
Look at other config files with check with name non-main

**Comment by rnveach** [comment]
@stoyanK7 
> We should use kebab-case for naming of scripts or configs.

If we are including scripts in this issue, please update issue so it contains what is being fixed.

**Comment by stoyanK7** [comment]
>We will keep existing issue open, we already reference folders: config, .ci

In this case, we should generalize issue title a bit. `Make scripts and configurations filenames consistent`, does that sound better?

**Comment by romani** [comment]
Yes, please do

**Comment by rnveach** [comment]
@stoyanK7 I assume there will be more PRs?

**Comment by stoyanK7** [comment]
@rnveach Yes, absolutely. I will open one today/tomorrow.

**Comment by rnveach** [comment]
@stoyanK7 Can you create a list of what is left to do so we know when the issue can be closed?

**Comment by stoyanK7** [comment]
@rnveach Done. Please check issue description.

**Comment by romani** [comment]
@stoyanK7 , I think we are done for this issue.
Is there anything else left ?

**Comment by stoyanK7** [comment]
No, everything is done it seems.
