### ISSUE TITLE
Make action to trigger all release steps

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#12720]
so we have all steps/phases of release automated but still required to be manually executed sequentially.
https://github.com/checkstyle/contribution/blob/master/releasenotes-builder/diagrams-manual-trigger.md

Ideally all of them should be auto triggered by themself.
One of the approach is: each action create git tag, other action triggered by tag creation.
https://github.com/checkstyle/contribution/blob/master/releasenotes-builder/diagrams.md

May be there is already some other way to execution actions one after another.

**Comment by romani** [comment]
@stoyanK7 , this is very last issue to close a project. this is kind of binding of all actions to make release to be done by one manual action from maintainer.

**Comment by stoyanK7** [comment]
@romani I already did some "research" on it yesterday. I had the idea to create one master workflow file to take care of all jobs.

GitHub allows reusing workflows: https://docs.github.com/en/actions/using-workflows/reusing-workflows#example-reusable-workflow

One limitation is that
> You can call a maximum of 20 reusable workflows from a single workflow file.

but from what I see, we fit in that number.

What do you think?

**Comment by rnveach** [comment]
Just my thought if we have scripts fully automated (either from one or chain), we create an issue to do release and script executes from issue and posts statuses in issue until release is done, and it can report failures and such. Eventually we could have triggers do resumes from after failure point.

**Comment by stoyanK7** [comment]
Just pasting what is possible: https://docs.github.com/en/actions/using-workflows/about-workflows#triggering-a-workflow

> Workflow triggers are events that cause a workflow to run. These events can be:
> - Events that occur in your workflow's repository
> - Events that occur outside of GitHub and trigger a repository_dispatch event on GitHub
> - Scheduled times
> - Manual

> For example, you can configure your workflow to run when a push is made to the default branch of your repository, when a release is created, or when an issue is opened.

**Comment by romani** [comment]
I am in favor of simple and reliable actions, we do not need fancy reporting now. We just need it to work.

**Comment by stoyanK7** [comment]
Already on it. Goes a bit slow since I need to do a lot of tweaks to point to my repo. I will open draft PR in the following days.

**Comment by stoyanK7** [comment]
Since the release will be performed by one single workflow file triggered by a maintainer, can we rename the issue? Something in the lines of `Make action to trigger all release steps`?

**Comment by romani** [comment]
renamed

**Comment by stoyanK7** [comment]
@romani @rnveach Could you please put a label on this issue so I can run publishing of releasenotes successfully.

https://github.com/stoyanK7/checkstyle/actions/runs/4173553537/jobs/7226080680#step:4:136

```

Error:  Issue #12720 does not have breaking compatibility, bug, miscellaneous, new feature, new module label! Please set label at https://github.com/checkstyle/checkstyle/issues/12720
Error: Process completed with exit code 254.
```

**Comment by rnveach** [comment]
@stoyanK7 Done.

**Comment by romani** [comment]
timing of 10.8.0 release
```
R: Copy Site to SourceForge                                       - 6m 15s 
R: Publish Tweet R: Publish Tweet                                 - 57s
R: Update github.io R: Update github.io                           - 2m 42s
R: Close/Create Milestone, ..... Upload '-all' jar, Create issues - 1m 43s
R: Publish GitHub Page R: Publish GitHub Page                     - 47s
R: Maven Release Perform R: Maven Release Perform                 - 2m 44s
R: Maven Release Prepare R: Maven Release Prepare                 - 1m 41s
R: Push Release Notes R: Push Release Notes                       - 1m 26s

```

**Comment by rnveach** [comment]
Fix was merged
