### ISSUE TITLE
End of free builds for CloudBees CodeShip

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#12758]
You are receiving this communication as a user of CloudBees CodeShip.  As of March 1, 2023, the free plan for CloudBees CodeShip will no  longer be available. At that time, CloudBees will remove all free  organizations within paid accounts and remove all users who only have  free organizations.  To learn how to migrate projects from your free account to your paid account, or to answer other common questions, visit the FAQs.  If you have any questions not addressed in the FAQs, please contact us at supportATcodeship.com.   CloudBees

CloudBees

You are receiving this communication as a user of CloudBees CodeShip. As of March 1, 2023, the free plan for CloudBees CodeShip will no longer be available. At that time, CloudBees will remove all free organizations within paid accounts and remove all users who only have free organizations.

To learn how to migrate projects from your free account to your paid account, or to answer other common questions, visit the [FAQs](https://assets.cloudbees.com/MzMzLVFQVi03MjUAAAGJrPK7Psg4hSSkNDo9t_KS_btFkMLgvHGSQKy9SqMMKFCSUMwwy_pcaFrYRNT__lUcjdo9Zds=).

If you have any questions not addressed in the [FAQs](https://assets.cloudbees.com/MzMzLVFQVi03MjUAAAGJrPK7Psg4hSSkNDo9t_KS_btFkMLgvHGSQKy9SqMMKFCSUMwwy_pcaFrYRNT__lUcjdo9Zds=), please contact us at [support@codeship.com](https://e.mail.ru/compose/?mailto=mailto%3asupport@codeship.com).

CloudBees

**Comment by romani** [comment]
I removed all projects at https://app.codeship.com/checkstyle

**Comment by rnveach** [comment]
Fix was merged
