### ISSUE TITLE
CommitValidationTest fails on revert commits

### ISSUE THREAD

**Issue by stoyanK7** [checkstyle/checkstyle#12766]
Commit: 26cadbb6772aa6ca85d6e95a9bff5d5366ca0430
Message: `Revert "doc: release notes for 10.8.0"`
Pipeline fail: https://dev.azure.com/romanivanovjr/romanivanovjr/_build/results?buildId=13264&view=logs&j=c902ebb4-c9f8-5f09-4e17-ff78fbbc842e&t=9ca98c81-ff64-58f0-9d03-a23ac1c4a111&l=795
```
[ERROR] Failures: 
[ERROR]   CommitValidationTest.testCommitMessageHasProperStructure:183 Commit 26cadbb6772aa6ca85d6e95a9bff5d5366ca0430 message: "Revert "doc: release notes for 10.8.0"\n\nThis reverts commit ff8bcc73c3c22161656794c969bb28a8cb09595f.\n" is invalid
Proper commit message should adhere to the following rules:
    1) Must match one of the following patterns:
        ^Issue #\d+: .*$
        ^Pull #\d+: .*$
        ^(minor|config|infra|doc|spelling|dependency|supplemental): .*$
    2) It contains only one line of text
    3) Must not end with a period, space, or tab
    4) Commit message should be less than or equal to 200 characters

The rule broken was: 1
[INFO] 
[ERROR] Tests run: 3931, Failures: 1, Errors: 0, Skipped: 2

```

**Comment by romani** [comment]
Reverts should be excluded from validation. I thought we already had support for this.

**Comment by stoyanK7** [comment]
On it,

**Comment by stoyanK7** [comment]
So the check regex would be `^Revert .*`

Take for example the commit message
```
Revert "doc: release notes for 10.8.0"
This reverts commit ff8bcc73c3c22161656794c969bb28a8cb09595f.
```
and the code that checks it
https://github.com/checkstyle/checkstyle/blob/bbfa7fb4f08ef138c450a4146696b62d19cf580b/src/test/java/com/puppycrawl/tools/checkstyle/internal/CommitValidationTest.java#L204-L231
![Screenshot from 2023-02-26 19-14-12](https://user-images.githubusercontent.com/23459549/221429094-53e8bb0c-8204-4a45-8089-1c44e07be893.png)

Problem is that it violates second(`else if (!trimRight.equals(message))`) and third(`else if (INVALID_POSTFIX_PATTERN.matcher(message).matches())`) checks. 

Shall we just this at the end of the file to work around all of this?
```java
        if (message.matches(REVERT_COMMIT_MESSAGE_REGEX_PATTERN)) {
            result = 0;
        }
```

**Comment by romani** [comment]
Yes, if it is revert commit, no more validation should be applied.
