### ISSUE TITLE
CommitValidationTest should ignore the release process

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#12765]
Identified in gitter and at https://dev.azure.com/romanivanovjr/romanivanovjr/_build/results?buildId=13251&view=logs&j=c902ebb4-c9f8-5f09-4e17-ff78fbbc842e&t=9ca98c81-ff64-58f0-9d03-a23ac1c4a111&l=795 ,

`[ERROR]   CommitValidationTest.testCommitMessageHasProperStructure:183 Commit 97ae29bd44209dc6a7f2082516e4175726a9b77e message: "[maven-release-plugin] prepare for next development iteration\n" `

Admins were an ignored user but now they aren't since a recent update and have to follow the proper commit process.

However, the valid use of the release process should not fail the CommitValidationTest. It is the proper commit messaging we use for releases.

The test needs to be updated to not fail on valid release process commits.

**Comment by romani** [comment]
@stoyanK7 , please help us to fix this issue

**Comment by stoyanK7** [comment]
@romani On it.

**Comment by romani** [comment]
fix is merged
