### ISSUE TITLE
Use dynamic names for release workflow runs

### ISSUE THREAD

**Issue by stoyanK7** [checkstyle/checkstyle#12785]
From https://github.com/checkstyle/checkstyle/pull/12782#discussion_r1121759835 
> unrelated:
> I like a fact that action execution prints input in its title https://github.com/stoyanK7/checkstyle/actions/workflows/set-milestone-on-referenced-issue.yml
> how you did this and how can we make it for our release executions ?
> 
> All are same: https://github.com/checkstyle/checkstyle/actions/workflows/bump-version-and-update-milestone.yml

---
https://github.blog/changelog/2022-09-26-github-actions-dynamic-names-for-workflow-runs/
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#run-name

**Comment by stoyanK7** [comment]
On it.

**Comment by romani** [comment]
Fix is merged
