### ISSUE TITLE
Change default value of property "format" to "^Abstract.*$" in AbstractClassNameCheck

### ISSUE THREAD

**Issue by Bhavik3** [checkstyle/checkstyle#1279]
I can not see any specific reason why class name with pattern "^.*Factory$" has to be defined Abstract. Nobody force Factory named classes to be Abstract according to spring sources.

If anyone can find reason for why Factory named classes should be abstract by default, most welcome to post evidence for the same.

**Comment by romani** [comment]
discussion of #1260.

merged.
