### ISSUE TITLE
Give better names to release actions and files

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#12807]
Identified at https://github.com/checkstyle/checkstyle/issues/12453 ,

https://github.com/checkstyle/checkstyle/blob/master/.github/workflows/update-sources.yml
Action file name is called `update sources`, but internal name is `Push Release Notes`, which calls the shell file `update-releasenotesxml`.

Naming doesn't seem consistent between action file name, internal name, and script name. It will make debugging this confusing since there is no consistency.

I recommend we give all 3 similar names. It is fine if file names are shorter and internal name is longer, or vice versa, but there should be some consistency to easily link the 3 together.
For example, I think `update-releasenotes` and `Update Release Notes` works fine.

We may also want to consider all release scripts/actions starting with `r-` or `release-` similar to the action's internal name.

I am using the first one as an example for now, but all of the release process should be reviewed too.

current action / shell file:
```
update-sources.yml
  update-releasenotesxml.sh

maven-prepare.yml
  maven-prepare.sh

maven-release-perform.yml
  maven-release-perform.sh

new-milestone-and-issue-in-other-repo.yml
  close-create-milestone.sh
  creation-of-issue-in-other-repos.sh

publish-releasenotes-outside.yml
  update-github-page.sh

update-github-io.yml
  push-website-to-github-io.sh

upload-all-jar.yml
  upload-all-jar.sh

copy-site-to-sourceforge.yml
  copy-site-to-sourceforge.sh

publish-releasenotes-for-twitter.yml
  tweet-releasenotes.sh
```

**Comment by romani** [comment]
I invented "R" prefix to let easy to find in GitHub list, as we already have a lot actions and release specific actions also.


I ok to do same/similar to filenames.

I am ok to rename files to be logical.
@rnveach , can you suggest your vision on names.

**Comment by rnveach** [comment]
I shared vision in my post for the one example.

**Comment by stoyanK7** [comment]
Adding some small inconsistencies I observed while working on the release process:
 - `publish-releasenotes-outside` makes no sense. Better name it `publish-releasenotes-github`. And it calls `update-github-page.sh` so that can be changed to stay consistent with caller workflow.
 - `publish-releasenotes-for-twitter.yml` can just be `publish-releasenotes-twitter`. 
 - `maven-release-perform` can be shortened to `maven-perform` so it stays consistent with `maven-prepare`.

**Comment by romani** [comment]
> maven-release-perform can be shortened to maven-perform so it stays consistent with maven-prepare

better rename `maven-prepare` to `maven-release-prepare`. as "prepare" is goal of maven release plugin not a maven.

@stoyanK7 , please send update on your proposal, it is better to cleanup now, while all is fresh in our mind and we plan to do release after each bug fix update.

**Comment by romani** [comment]
@stoyanK7 , @rnveach , proposal:
```
action / shell file

release-update-xdoc-with-notes.yml
  release-update-xdoc-with-notes.sh

release-maven-prepare.yml
  release-maven-prepare.sh

release-maven-perform.yml
  release-maven-perform.sh

release-new-milestone-and-issue-in-other-repo.yml
  release-close-create-milestone.sh
  release-creation-of-issue-in-other-repos.sh

release-update-github-page.yml
  release-update-github-page.sh

release-update-github-io.yml
  release-update-github-io.sh

release-upload-all-jar.yml
  release-upload-all-jar.sh

release-copy-github-io-to-sourceforge.yml
  release-copy-github-io-sourceforge.sh

release-publish-releasenotes-twitter.yml
  release-publish-releasenotes-twitter.sh
```

please suggest better names or vote on this proposal.

**Comment by rnveach** [comment]
Internal name needs updating too.

> Action file name is called update sources, but internal name is Push Release Notes, which calls the shell file update-releasenotesxml.

**Comment by romani** [comment]
if we agree on file name, internal name will follow that patter.

**Comment by stoyanK7** [comment]
@romani 
I mostly agree with the proposal apart from:
 - `release-creation-of-issue-in-other-repos.sh`. Why not `release-create-issues-in-other-repos.sh`? It is shorter and keeps consistency by starting filename with a verb.
 - `release-publish-releasenotes-twitter` and `release-update-xdoc-with-notes`. One uses `notes`, the other `releasenotes`. Better stick with one. I'd prefer `releasenotes`, but `notes` works too.

**Comment by romani** [comment]
@stoyanK7 , I agree with your proposal.

@rnveach , are you agree with rename ?

**Comment by stoyanK7** [comment]
On it.

**Comment by rnveach** [comment]
Fix was merged
