### ISSUE TITLE
Some issues with the use of Checkstyle

### ISSUE THREAD

**Issue by springcoco** [checkstyle/checkstyle#12813]

**Comment by nrmancuso** [comment]
@springcoco please open a discussion instead of an issue, and provide concrete examples of what you would like to do. Issues are used for feature requests and bugs, and what you’ve described above didn’t sound like either one.

**Comment by springcoco** [comment]
@nrmancuso Very sorry for my impatience, which caused trouble for you. May I ask how to start a discussion?
