### ISSUE TITLE
Error in checkstyle xml-file Unable to create a checker...

### ISSUE THREAD

**Issue by hjmf1954** [checkstyle/checkstyle#1281]
When running this setting I got the error message:
Unable to create a Checker: cannot initialize module TreeWalker - Property 'ignoreInlineTags' in module TreeWalker does not exist, please check the documentation

Please change the 194 and 195 into:
<img width="525" alt="screen shot 2015-07-04 at 15 52 43" src="https://cloud.githubusercontent.com/assets/3748128/8508140/dada0e9c-2264-11e5-8acf-5299f43b5b47.png">

**Comment by Bhavik3** [comment]
According to error you have written, looks like you have defined property `ignoreInlineTags` under `TreeWalker` module. You need to define it under `SingleLineJavadoc`. 
If it is not so, share config.

**Comment by romani** [comment]
https://github.com/checkstyle/checkstyle/issues/1275 , the same problem

**Comment by romani** [comment]
please follow #1275 for a status, I am closing this issue.
