### ISSUE TITLE
Add conditional to run on:push workflows only in checkstyle repository

### ISSUE THREAD

**Issue by stoyanK7** [checkstyle/checkstyle#12824]
Every time I update my fork master branch via the `Update branch` button or just push to it, the following GitHub CI workflows are kicked off:
![image](https://user-images.githubusercontent.com/23459549/224541606-86f6e961-e03b-41ab-93c3-872350d84447.png)

All these workflows are triggered because of push event to master
https://github.com/checkstyle/checkstyle/blob/a68418155f292639a17e1e4d914cbc2ccffa5092/.github/workflows/pitest.yml#L3-L6

I think we can spare GitHub those CI action minutes..

We can add a condition to run those only in `checkstyle repository`: https://github.com/prisma/prisma/issues/3539#issuecomment-690260573
`github.repository_owner == 'checkstyle'`

**Comment by romani** [comment]
@stoyanK7 , please send update
