### ISSUE TITLE
Generate site workflow should provide more specific links

### ISSUE THREAD

**Issue by stoyanK7** [checkstyle/checkstyle#12853]
From https://github.com/checkstyle/checkstyle/pull/12151#issuecomment-1471936585
> in my dreams this extra link is auto generated :), it is proved fact by usage experience that it is convenient. Looks like we are ready to make issue on it, to let somebody to fix it.

---
We comment `Github, generate website` and receive a comment like this one from `github-actions[bot]`:
```
https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/7727c78_2023030917/index.html
```

We are often interested in the page that contains the changes made in the PR and it would be convenient if workflow could recognize those changes and give a more specific link along with the current one. For example in #12151, we introduce new filter `SuppressWithNearbyTextFilter`
![Screenshot from 2023-03-16 18-35-45](https://user-images.githubusercontent.com/23459549/225705283-258680e2-3b2b-49c3-a989-732e9fbd5805.png)

**Comment by stoyanK7** [comment]
On it.

**Comment by nrmancuso** [comment]
@stoyanK7 let's favor scripts instead of bash directly in CI configs as logic becomes more complicated; this eases maintenance and testing locally

**Comment by romani** [comment]
Yes,no logic in CI configs. All should be in shell scripts and executable on local

**Comment by nrmancuso** [comment]
@stoyanK7 before we close this issue, let's test action out in main repo

**Comment by stoyanK7** [comment]
@nrmancuso Just ran a test at https://github.com/checkstyle/checkstyle/pull/12151#issuecomment-1490373873

**Comment by stoyanK7** [comment]
Not sure if I should have rebased first though.

**Comment by nrmancuso** [comment]
GitHub action behavior on PR branches from forks is hard to understand, we should probably rebase first

**Comment by stoyanK7** [comment]
I think I found a problem with concurrencies when checking why my site generation didn't kick off.
https://github.com/checkstyle/checkstyle/actions/runs/4565421640 
```
parse_pr_info
Canceling since a higher priority waiting request for 'Site-refs/heads/master' exists
```
The workflow uses this group

`group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}`

But this workflow context does not have `github.event.pull_request.number`, rather `github.event.issue.number` so it falls back to `github.ref`. Theoretically, we can not run 2 site generations in this repo? 

Here is a print of the `github` context of this workflow from my fork.
https://github.com/stoyanK7/checkstyle/actions/runs/4544370282/jobs/8010295603#step:4:90
```
    "event": {
       "issue": {
         "number": 61,
```

**Comment by stoyanK7** [comment]
@nrmancuso Could you label this issue? 

https://github.com/checkstyle/checkstyle/actions/runs/4565352325/jobs/8056362329#step:4:129
```
Error:  Issue #12853 does not have breaking compatibility, bug, miscellaneous, new feature, new module label! Please set label at https://github.com/checkstyle/checkstyle/issues/12853

```

**Comment by Sloent** [comment]
@stoyanK7 I'm very sorry for the inconvenience. I accidentally merged my code with yours, and now I have performed the revert operation.

**Comment by romani** [comment]
@stoyanK7 ,

> But this workflow context does not have github.event.pull_request.number, rather github.event.issue.number

please send PR to update, for github issues and pulls are in same numeric sequence. it is same thing. I doubt we ever tested this concurrency, we most likely blindly set up just to have something.
