### ISSUE TITLE
Updating with the optimise code

### ISSUE THREAD

**Issue by Rohitrky2021** [checkstyle/checkstyle#12867]
I have read check documentation: https://checkstyle.org/config_xxxxxx.html#NameOfAffectedCheck
I have downloaded the latest cli from: https://checkstyle.org/cmdline.html#Download_and_Run
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

**How it works Now:**
Changes can be seen here:- [https://github.com/checkstyle/checkstyle/pull/12861/files](https://github.com/checkstyle/checkstyle/pull/12861/files)
want to improve the code as some places its using string changing it to stringbuilder and some other changes so it

Validation and early exit: If all input extensions are already in the correct format, the method simply sets the fileExtensions field to the input array, which is more efficient than creating a new array.

Better error handling: If any input extension is not in the correct format, the method builds a formatted string with all the input extensions and logs a warning message with the invalid extensions and the formatted string. Then, it creates a new array with the formatted extensions and sets the fileExtensions field to the new array.

StringBuilder usage: A StringBuilder is used to build the formatted string of extensions, which is more efficient than concatenating strings with the + operator.

Improved variable naming: The variable name extension is used consistently
```bash
/var/tmp $ javac YOUR_FILE.java
#[[MAKE SURE THERE IS SUCCESSFUL COMPILATION]]

/var/tmp $ cat config.xml
#[[PLACE YOUR OUTPUT HERE]]

/var/tmp $ cat YOUR_FILE.java
#[[(https://github.com/checkstyle/checkstyle/pull/12861/files)]]

/var/tmp $ RUN_LOCALE="-Duser.language=en -Duser.country=US"
/var/tmp $ java $RUN_LOCALE -jar checkstyle-X.XX-all.jar -c config.xml YOUR_FILE.java
#[[[PLACE YOUR OUTPUT HERE](https://github.com/checkstyle/checkstyle/pull/12861/files)]]
```as we can se here

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**
A clear and detailed description of what you want to happen.
You could provide the expected/suggested cli output for your solution.

```bash
expected/suggested cli output
```

**Additional context**

Still not clear ???
see examples:

- https://checkstyle.org/report_issue.html#How_to_request_new_feature_for_existing_functionality.3F

- https://checkstyle.org/report_issue.html#How_to_request_new_Check.2FModule.3F

**Not a feature?**
If (Check, property, new behavior) that you are requesting is already
implemented and you are unsatisfied with their behaviour, report it here
in bug template format:

- https://checkstyle.org/report_issue.html#How_to_report_a_bug.3F

ATTENTION: FAILURE TO FOLLOW THE ABOVE TEMPLATE WILL RESULT IN THE ISSUE BEING CLOSED.

**Comment by nrmancuso** [comment]
@Rohitrky2021 I suggest you familiarize yourself with the project before attempting to make functional changes, [This](https://github.com/checkstyle/checkstyle/wiki/To-GSoC-participant) document is a good place to start, even if you are not a GSOC student.

**Comment by nrmancuso** [comment]
I am closing this, seems like we have lost contact with the author and we were never clear about issue in the first place.
