### ISSUE TITLE
Resolve pitest suppression for AbstractViolationReporter

### ISSUE THREAD

**Issue by shubh220922** [checkstyle/checkstyle#12876]
Related to https://github.com/checkstyle/checkstyle/issues/12341

Kill the surviving mutation.

https://github.com/checkstyle/checkstyle/blob/d59b83b0ed74436e3868ced9a477557b780574d7/config/pitest-suppressions/pitest-api-suppressions.xml#L3-L10

**Comment by shubh220922** [comment]
@romani please approve.

**Comment by shubh220922** [comment]
I'm on it.

**Comment by nrmancuso** [comment]
Closed via https://github.com/checkstyle/checkstyle/pull/12884
