### ISSUE TITLE
Resolve pitest suppression for BeforeExecutionFileFilterSet

### ISSUE THREAD

**Issue by shubh220922** [checkstyle/checkstyle#12878]
Related to #12341 

Kill the surviving mutation:

https://github.com/checkstyle/checkstyle/blob/d59b83b0ed74436e3868ced9a477557b780574d7/config/pitest-suppressions/pitest-api-suppressions.xml#L21-L28

**Comment by shubh220922** [comment]
Please approve.

**Comment by nrmancuso** [comment]
Closed via #12883
