### ISSUE TITLE
Kill surviving mutation in FilterSet.java

### ISSUE THREAD

**Issue by shubh220922** [checkstyle/checkstyle#12887]
Kill the surviving mutation:

https://github.com/checkstyle/checkstyle/blob/54df97c85d5fae09e38cda3c83781ac83b857930/config/pitest-suppressions/pitest-api-suppressions.xml#L102-L109

**Comment by shubh220922** [comment]
@romani @nrmancuso 
Please approve.

**Comment by nrmancuso** [comment]
Approved, but let's complete (or close) hanging PRs (such as https://github.com/checkstyle/checkstyle/pull/12469) before sending more.

**Comment by shubh220922** [comment]
@nrmancuso Alright. Will push changes for that today.

**Comment by romani** [comment]
Fix is merged
