### ISSUE TITLE
Typo in Documentation of VariableDeclarationUsageDistance

### ISSUE THREAD

**Issue by jxr98** [checkstyle/checkstyle#12898]
In [documentation](https://checkstyle.org/config_coding.html#VariableDeclarationUsageDistance), 
```
final int PI;
PI = 3.14;
```
There's a typo. PI should be of type double or float.

**Comment by jxr98** [comment]
If it is approved, I think I can work on it •ᴗ•.

**Comment by romani** [comment]
@jxr98, please send pr

**Comment by romani** [comment]
Fix merged
