### ISSUE TITLE
Kill surviving mutation in PackageDeclarationCheck.java

### ISSUE THREAD

**Issue by shubh220922** [checkstyle/checkstyle#12890]
Kill mutation :

https://github.com/checkstyle/checkstyle/blob/54df97c85d5fae09e38cda3c83781ac83b857930/config/pitest-suppressions/pitest-coding-1-suppressions.xml#L75-L82

**Comment by shubh220922** [comment]
please approve.

**Comment by shubh220922** [comment]
I'm on it.

**Comment by romani** [comment]
issue is resolved by inscope of project "Pitest Resolution" by some special PR.
