### ISSUE TITLE
Violation messages and Example of Usage links do not work.

### ISSUE THREAD

**Issue by Vyom-Yadav** [checkstyle/checkstyle#12905]
The hyperlink for violation messages does not work anymore.
![Screenshot from 2023-03-25 08-49-53](https://user-images.githubusercontent.com/73882557/227689386-2f6a6109-c012-4fe1-bfeb-401a43fe1ffd.png)

This link directs to:
![Screenshot from 2023-03-25 08-53-10](https://user-images.githubusercontent.com/73882557/227689425-0f71dfcb-64e2-489d-b63b-b4ee137269cd.png)

GitHub suggests the correct path i.e. https://github.com/search?q=path%3Asrc%2Fmain%2Fresources%2Fcom%2Fpuppycrawl%2Ftools%2Fcheckstyle%2Fchecks%2Fcoding+path%3A**%2Fmessages*.properties+repo%3Acheckstyle%2Fcheckstyle+%22array.trailing.comma%22&type=code

The same is true for [Example_of_Usage](https://checkstyle.org/config_coding.html#VariableDeclarationUsageDistance_Example_of_Usage) section.

Update the hyperlinks of all the checks and make sure they're correct. This can be done for all checks using `awk`, etc., or in IDE features like find and replace.

The GitHub docs still show it as working but it is not actually working, opened https://github.com/github/docs/issues/24666 for the same.

**Comment by romani** [comment]
this works: `path:src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding filename:messages*.properties repo:checkstyle/checkstyle 'variable.declaration.usage.distance'`

I used single quotes `'` instead `"`.

this link works: `https://github.com/search?q=path%3Asrc%2Fmain%2Fresources%2Fcom%2Fpuppycrawl%2Ftools%2Fcheckstyle%2Fchecks%2Fcoding+filename%3Amessages*.properties+repo%3Acheckstyle%2Fcheckstyle+%27variable.declaration.usage.distance%27`

we need to update whole xdoc codebase to use single quotes.

**Comment by romani** [comment]
https://github.com/checkstyle/checkstyle/blob/2065b9c178c8efd2fba2c6450ad04e67118e3df6/src/xdocs/config_coding.xml#L8084

`%22` should be changed to `%27`

**Comment by Vyom-Yadav** [comment]
> this link works: https://github.com/search?q=path%3Asrc%2Fmain%2Fresources%2Fcom%2Fpuppycrawl%2Ftools%2Fcheckstyle%2Fchecks%2Fcoding+filename%3Amessages*.properties+repo%3Acheckstyle%2Fcheckstyle+%27variable.declaration.usage.distance%27

This still doesn't work for me.

**Comment by Vyom-Yadav** [comment]
> I used single quotes ' instead ".

Single quotes don't work for me, double quotes do, how is it the reverse?

**Comment by romani** [comment]
try to open it few times, it looks like not stable, but it works periodically.

**Comment by Vyom-Yadav** [comment]
The only thing working for me consistently is:
`path:src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding path:**/messages*.properties repo:checkstyle/checkstyle "variable.declaration.usage.distance"`

**Comment by romani** [comment]
I remember such problems even before, it was unstable , but nothing we can do, it is GitHub, you can open issue on them instead.

**Comment by romani** [comment]
Fixed by https://github.com/checkstyle/checkstyle/issues/13059#issuecomment-1560466879
