### ISSUE TITLE
Update documentation on Development Cycle

### ISSUE THREAD

**Issue by stoyanK7** [checkstyle/checkstyle#12913]
Checkstyle moved to Semantic Versioning in `10.5.0` on 27 Nov 2022: https://github.com/checkstyle/checkstyle/discussions/12436#discussioncomment-4242955

The following article needs to be revised.
https://checkstyle.sourceforge.io/#Development_Cycle
![Screenshot from 2023-03-26 18-50-25](https://user-images.githubusercontent.com/23459549/227791217-355537da-8d73-4544-9d49-193aa9e655a7.png)

**Comment by romani** [comment]
>Checkstyle moved to Semantic Versioning

We are not following semantic versioning. This why this section exists and explains our version model
