### ISSUE TITLE
Grammar error in documentation of AbstractClassNameCheck.xml 

### ISSUE THREAD

**Issue by Bharath-Ganesh** [checkstyle/checkstyle#12932]
In [documentation](https://checkstyle.org/config_naming.html#AbstractClassName),

Rationale: Abstract classes are convenience base class implementations of interfaces, not types as such. As such they should be named to indicate this. Also, _if names of _classes starts__ with 'Abstract' it's very convenient that they will have abstract modifier.

Grammatical error : 
1. As "classes" are plural, it should have been start.
2. I would also propose to include "The name of classes" instead of "if names of classes"

**Comment by nrmancuso** [comment]
@Bharath-Ganesh for simple documentation update, you do not need to create an issue, you can just send a PR with commit message like `doc: improve grammar in AbstractClassNameCheck`

**Comment by Bharath-Ganesh** [comment]
@nrmancuso Thanks for your suggestion, I'll make a note of it.
Since I raised an issue, can I tag the Issue number in the commit or go with the commit you suggested(without having the issue number)?

**Comment by nrmancuso** [comment]
You can reference issue number now that we approved :)

**Comment by 244651227892** [comment]
PR
