### ISSUE TITLE
Resolve pitest suppression for FallThroughCheck

### ISSUE THREAD

**Issue by coderdeadpool** [checkstyle/checkstyle#12943]
Related to https://github.com/checkstyle/checkstyle/issues/12341

Kill the surviving mutation:
https://github.com/checkstyle/checkstyle/blob/a1afeab15e59469c334079e03b37c8e931f92b2e/config/pitest-suppressions/pitest-coding-2-suppressions.xml#L3-L10

**Comment by coderdeadpool** [comment]
@nrmancuso @romani Please approve.

**Comment by romani** [comment]
Fix is merged
