### ISSUE TITLE
Resolve pitest suppression for FallThroughCheck

### ISSUE THREAD

**Issue by ShivamPandey00** [checkstyle/checkstyle#12948]
Related to #12341 
Kill the surviving mutation:
https://github.com/checkstyle/checkstyle/blob/a1afeab15e59469c334079e03b37c8e931f92b2e/config/pitest-suppressions/pitest-coding-2-suppressions.xml#L12-L19

**Comment by coderdeadpool** [comment]
Please approve

**Comment by coderdeadpool** [comment]
I am on it

**Comment by nrmancuso** [comment]
@romani we have a problem: we introduced breaking changes in a pitest issue, how should we communicate this to users?

**Comment by romani** [comment]
We just need to change title of issue

**Comment by romani** [comment]
Resolved  at https://github.com/checkstyle/checkstyle/issues/12948
