### ISSUE TITLE
Kill surviving mutations in SuppressWithNearbyTextFilter

### ISSUE THREAD

**Issue by stoyanK7** [checkstyle/checkstyle#12952]
After #12151 gets merged, it will introduce 2 new surviving mutations.
```
  <mutation unstable="false">
    <sourceFile>SuppressWithNearbyTextFilter.java</sourceFile>
    <mutatedClass>com.puppycrawl.tools.checkstyle.filters.SuppressWithNearbyTextFilter</mutatedClass>
    <mutatedMethod>accept</mutatedMethod>
    <mutator>org.pitest.mutationtest.engine.gregor.mutators.NonVoidMethodCallMutator</mutator>
    <description>removed call to java/lang/String::equals</description>
    <lineContent>if (!cachedFileAbsolutePath.equals(eventFileTextAbsolutePath)) {</lineContent>
  </mutation>

  <mutation unstable="false">
    <sourceFile>SuppressWithNearbyTextFilter.java</sourceFile>
    <mutatedClass>com.puppycrawl.tools.checkstyle.filters.SuppressWithNearbyTextFilter</mutatedClass>
    <mutatedMethod>accept</mutatedMethod>
    <mutator>org.pitest.mutationtest.engine.gregor.mutators.RemoveConditionalMutator_EQUAL_IF</mutator>
    <description>removed conditional - replaced equality check with true</description>
    <lineContent>if (!cachedFileAbsolutePath.equals(eventFileTextAbsolutePath)) {</lineContent>
  </mutation>
```

---
First is the real line and the hardcoded mutation below it:
```
if (!cachedFileAbsolutePath.equals(eventFileTextAbsolutePath)) {
```
```
if (true) {
```
The mutation shows that there is no test to assert that the caching happens only once per file. 

We need to write a test to assert that any method inside the `if` statement is called only once - could be `collectSuppressions()` or `getFileText()`.

---
Because `getFileText()`'s implementation is the exact same in both this filter and `SuppressWithPlainTextCommentFilter`, it can be extracted to `FilterUtil` and we can assert that this method is invoked only once - https://github.com/checkstyle/checkstyle/commit/383b0791daa4db9c4a5c6c57c2afc6d260fa4c18

**Comment by romani** [comment]
Yes, we need split huge update in few subtasks

**Comment by romani** [comment]
Closed in favor of https://github.com/checkstyle/checkstyle/issues/14019
