### ISSUE TITLE
Create script for appending text to $GITHUB_OUTPUT

### ISSUE THREAD

**Issue by stoyanK7** [checkstyle/checkstyle#12954]
From https://github.com/checkstyle/checkstyle/pull/12946#discussion_r1155903342

> I think we need to make it obvious to others that may not be experienced with bash what is going on here. As GitHub had their special `set-output` command that we replaced, we should create a script to use for appending multiple lines to workflow output. Please create an issue on this, I propose we do something like ` ./append-to-github-output.sh` message.
> 
> This will also help in future maintainence/debugging efforts, since we can check for existence of `message`, etc.

**Comment by nrmancuso** [comment]
@stoyanK7 issue is approved

**Comment by stoyanK7** [comment]
I am on it.

**Comment by nrmancuso** [comment]
Closed via #12959
