### ISSUE TITLE
Javadoc of RightCurlyCheck is broken

### ISSUE THREAD

**Issue by Bananeweizen** [checkstyle/checkstyle#12968]
`{@code '}'}` is not a valid inline code tag, both in the Javadoc and metadata of RightCurlyCheck. That tag stops at the first curly brace, and then has `'}` as additional unformatted text. 

Can be fixed by using `<code>'}'</code>` instead (as is already done 13 lines deeper in the same Javadoc).

![grafik](https://user-images.githubusercontent.com/406876/230789831-a952990a-48d0-44cf-9004-08a397fa8994.png)
first highlight is the broken one, second is the correct one

**Comment by rnveach** [comment]
https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java#L34
https://github.com/checkstyle/checkstyle/blob/master/src/xdocs/config_blocks.xml#L1252

We should also verify there are no other instances in our repo.

**Comment by renjith7189** [comment]
I am on it.

**Comment by romani** [comment]
Fix is merged

**Comment by rnveach** [comment]
https://github.com/checkstyle/checkstyle/issues/12968#issuecomment-1501195772
> We should also verify there are no other instances in our repo.

Where was this done?

**Comment by nrmancuso** [comment]
@rnveach looks like we are good:
```bash
➜  checkstyle git:(master) ag -Q "{@code '}'}"
src/test/resources/com/puppycrawl/tools/checkstyle/meta/javadocmetadatascraper/ExpectedJavadocMetadataScraperRightCurlyCheck.txt
8: Checks the placement of right curly braces ({@code '}'}) for code blocks. This check supports

src/test/resources/com/puppycrawl/tools/checkstyle/meta/javadocmetadatascraper/InputJavadocMetadataScraperRightCurlyCheck.java
24: * Checks the placement of right curly braces ({@code '}'}) for code blocks. This check supports

```
