### ISSUE TITLE
Add more unit test cases for VariableDeclarationUsageDistanceCheck

### ISSUE THREAD

**Issue by jxr98** [checkstyle/checkstyle#12976]
There are some example code from the [regression report](https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/252e206_2023054402/reports/diff/index.html), which are not covered by the existing test cases.

**Comment by jxr98** [comment]
I can take this issue if it is approved.

**Comment by nrmancuso** [comment]
Why aren't we adding these tests in scope of https://github.com/checkstyle/checkstyle/pull/12822 / https://github.com/checkstyle/checkstyle/issues/11968 ?

**Comment by jxr98** [comment]
I have added tests of try with resources in #12822, but there are some test cases not related to try with resources. I am not sure if it is suitable to include those tests in #12822.

**Comment by nrmancuso** [comment]
@jxr98 if we found new tests in check regression report due to changes at https://github.com/checkstyle/checkstyle/pull/12822, new tests belong in that PR.

>For example...

Please share a link to exact violation on this in the regression report.

**Comment by jxr98** [comment]
Got it. 
Here's one. https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/252e206_2023054402/reports/diff/openjdk17/index.html#A16

**Comment by jxr98** [comment]
Just for confirmation, are we adding new tests to #12822?

**Comment by romani** [comment]
If you created new issue , create new/separate PR
