### ISSUE TITLE
Infra: enable dependabot for github actions

### ISSUE THREAD

**Issue by Bananeweizen** [checkstyle/checkstyle#12984]
Dependabot only upgrades the Maven dependencies of checkstyle. However, it can also be configured to upgrade the github actions: https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot

I'm not sure if dependabot can be configured to use hashes instead of versions for github actions. All the non hashed Github actions currently lead to a penalty for the checkstyle project on its scorecard: https://deps.dev/maven/com.puppycrawl.tools%3Acheckstyle/10.9.2 (go to bottom right, "pinned dependencies").

**Comment by AayushSaini101** [comment]
I am on it

**Comment by rnveach** [comment]
Fix was merged
