### ISSUE TITLE
Resolve pitest suppression for FinalLocalVariableCheck

### ISSUE THREAD

**Issue by coderdeadpool** [checkstyle/checkstyle#13000]
Related to #12341 

Kill the surviving mutation:
https://github.com/checkstyle/checkstyle/blob/5768a5e30a00ad8c2ae80da5fb67961219acf7b6/.ci/pitest-suppressions/pitest-coding-2-suppressions.xml#L57-L64

**Comment by coderdeadpool** [comment]
Please approve

**Comment by romani** [comment]
Ok let's use that issue, but there could be multiple PRs to fix each survival separately.
