### ISSUE TITLE
Update doc for UnusedImports

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#13007]
https://checkstyle.org/config_imports.html#UnusedImports

Add example for each existing config AND for each property to show what code is ok and what code cause violation.

A good example is https://checkstyle.org/config_naming.html#AbstractClassName.

Look at referenced commits of https://github.com/checkstyle/checkstyle/issues/5832, to see what and how should be changed in code.

Please play with module/check by means of https://checkstyle.org/cmdline.html to understand how it works.

PLEASE READ https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-examples

There should be two examples: for default and for property with not default value. Both examples should have same java snippet and only trailing comments changing to mark where violation is happening.

**Comment by TanayMorakhia** [comment]
I am on it.

**Comment by romani** [comment]
Fix is merged
