### ISSUE TITLE
Update Maven PMD Plugin to 3.5

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#1300]
Maven PMD Plugin version 3.5 contains update for PMD to latest 5.3.2.

The biggest functional change is better detection of boolean return that may be simplified [#1320](https://sourceforge.net/p/pmd/bugs/1320/).

**Comment by mkordas** [comment]
@romani - we can close this one, right?

**Comment by romani** [comment]
yes, clolsed
