### ISSUE TITLE
Resolve Pitest Suppressions for pitest-coding-2 profile

### ISSUE THREAD

**Issue by coderdeadpool** [checkstyle/checkstyle#13025]
Part of #12341 
This issue contains all the mutations from profile ` pitest-coding-2-suppressions.xml`
https://github.com/checkstyle/checkstyle/blob/72f182241a3b8a6d905328dfcfc9739dfffac9bd/config/pitest-suppressions/pitest-coding-2-suppressions.xml#L1-L371

**Comment by coderdeadpool** [comment]
please approve.

**Comment by romani** [comment]
Please do not create new issues, just reference existing issue.
