### ISSUE TITLE
Node.js 12 actions are deprecated.

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#13045]
example: https://github.com/checkstyle/checkstyle/actions/runs/4867700331

> parse_pr_info Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: khan/pull-request-comment-trigger@master. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

> send_message Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: checkstyle/contribution/comment-action@master. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

we need to migrate in other case we will problems.
>To raise awareness of the upcoming change, we are adding a warning into workflows which contain Actions running on Node 12. This will come into effect starting on September 27th.

**Comment by AayushSaini101** [comment]
I am on it

**Comment by romani** [comment]
Fix is merged

**Comment by romani** [comment]
Testing at https://github.com/checkstyle/checkstyle/pull/13825#issuecomment-1748109980

**Comment by romani** [comment]
it is still an issue: https://github.com/checkstyle/checkstyle/actions/runs/6416571161

**Comment by romani** [comment]
@AayushSaini101 , do you see a reason why one warning of old node still survived ?

**Comment by AayushSaini101** [comment]
@romani looking into it

**Comment by AayushSaini101** [comment]
> @AayushSaini101 , do you see a reason why one warning of old node still survived ?

I guess this PR is pending https://github.com/checkstyle/contribution/pull/804/files and  it is depends on the The following actions uses node12 which is deprecated and will be forced to run on node16: checkstyle/contribution/comment-action@master

**Comment by romani** [comment]
Merged and testing started at https://github.com/checkstyle/checkstyle/pull/13825#issuecomment-1749706963

**Comment by romani** [comment]
It works without warnings https://github.com/checkstyle/checkstyle/actions/runs/6424851753
