### ISSUE TITLE
Print release notes and link to issues with problems 

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#13047]
this is not showing me point of failure: https://github.com/checkstyle/checkstyle/actions/runs/4894357953/jobs/8738488388#step:4:125

So to make sure that this is correct, the only way is for me to check the last release date and commits and issues. I would expect a job called "Generate release notes" to persist an artifact.

Link to offending issue in output would be good

**Comment by romani** [comment]
@stoyanK7 , can you help us to improve release notes validation?

**Comment by stoyanK7** [comment]
@romani Sure. 

Just to get things straight
> I would expect a job called "Generate release notes" to persist an artifact.

You mean an artifact(zip file) with the release notes page?

> Link to offending issue in output would be good

On it.

**Comment by nrmancuso** [comment]
> You mean an artifact(zip file) with the release notes page?

@romani how are we on s3 space? Can we just host it with some short ttl?

**Comment by stoyanK7** [comment]
Is the following good enough of a message?

> Validation of release number failed. Release number is a patch(10.10.1), but release notes contain 'new' or 'breaking compatability' labels. Please correct release number by running https://github.com/checkstyle/checkstyle/actions/workflows/bump-version-and-update-milestone.yml. The offending issue(s): `https://github.com/checkstyle/checkstyle/issues/13047` `https://github.com/checkstyle/checkstyle/issues/13048`

**Comment by romani** [comment]
If easy, I would print release notes outputs to make it visual that we have breaking changes or new features and version is strange.

**Comment by nrmancuso** [comment]
Let’s see how hard it is to do https://github.com/checkstyle/checkstyle/issues/13047#issuecomment-1536647624, if it is too hacky then just show all release notes like @romani suggested.

**Comment by romani** [comment]
>Error:  Validation of release number failed. Release number is a patch(10.10.1), but release notes contain 'new' or 'breaking compatability' labels. Please correct release number by running https://github.com/checkstyle/checkstyle/actions/workflows/bump-version-and-update-milestone.yml. The offending issue(s): https://github.com/checkstyle/checkstyle/issues/11109
Error: Process completed with exit code 254.

https://github.com/checkstyle/checkstyle/actions/runs/4894357953/jobs/8754935524#step:4:125
