### ISSUE TITLE
Maven plugin warnings with maven 3.9.x+

### ISSUE THREAD

**Issue by lprimak** [checkstyle/checkstyle#13057]
looks like the plugin needs update:

[INFO] --- checkstyle:3.2.2:checkstyle (default) @ flowlogix-jee ---
[WARNING] Parameter 'localRepository' is deprecated core expression; Avoid use of ArtifactRepository type. If you need access to local repository, switch to '${repositorySystemSession}' expression and get LRM from it instead.
[INFO] Rendering content with org.apache.maven.skins:maven-default-skin:jar:1.3 skin.
[INFO] Starting audit...
Audit done.

**Comment by rnveach** [comment]
@lprimak Are you sure this issue shouldn't be directed at maven-checkstyle-plugin instead of us?

**Comment by lprimak** [comment]
@rnveach You are right! I already reported it and forgot about it :)
Here is the plugin JIRA ticket: https://issues.apache.org/jira/browse/MCHECKSTYLE-429
