### ISSUE TITLE
Broken Link: Github search links are broken in documentation

### ISSUE THREAD

**Issue by ashutoshdubey133** [checkstyle/checkstyle#13059]
Github search links in documentation such as:
1. https://checkstyle.org/config_coding.html#FallThrough_Example_of_Usage
2. https://checkstyle.org/config_coding.html#FallThrough_Violation_Messages

![image](https://github.com/checkstyle/checkstyle/assets/812984/cd04c406-b290-4758-8a6c-d4c832466522)

These are broken because they use "filename" which is not a supported qualifier in the new github search.
For a list of supported qualifers - https://docs.github.com/en/search-github/github-code-search/understanding-github-code-search-syntax

We would have to replace "filename" with "path" qualifer and use regex.

**Comment by romani** [comment]
@ashutoshdubey133 , if know how to fix, please send pull request.

**Comment by rnveach** [comment]
Image and link shows suggestion. Suggestion worked for me and looks similar to old behavior.

**Comment by Vyom-Yadav** [comment]
This is similar to https://github.com/checkstyle/checkstyle/issues/12905.
I opened an issue on GH repo regarding this https://github.com/github/docs/issues/24666

**Comment by Andromeda227799** [comment]
I am on It

**Comment by Andromeda227799** [comment]
@romani can we close #12905 also, since it looks like a similar issue?
