### ISSUE TITLE
.ci/pitest.sh --list doesn't show all pitest profiles on Mac

### ISSUE THREAD

**Issue by rdiachenko** [checkstyle/checkstyle#13063]
Related issue #11730

Steps to reproduce:
```
/var/tmp/checkstyle[master|✔] [20:43:02]% uname -v
Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000
/var/tmp/checkstyle[master|✔] [20:43:16]% ./.ci/pitest.sh --list
Supported profiles:
```

Detected: empty list of profiles
```
Supported profiles:
```

Expected:
```
Supported profiles:
pitest-annotation
pitest-ant
pitest-api
pitest-blocks
pitest-coding-1
pitest-coding-2
pitest-coding-require-this-check
pitest-common
pitest-common-2
pitest-design
pitest-filters
pitest-gui
pitest-header
pitest-imports
pitest-indentation
pitest-java-ast-visitor
pitest-javadoc
pitest-main
pitest-metrics
pitest-misc
pitest-modifier
pitest-naming
pitest-packagenamesloader
pitest-regexp
pitest-sizes
pitest-tree-walker
pitest-utils
pitest-whitespace
pitest-xpath
```

**Comment by heyannely** [comment]
@ rdiachenko Hello if there is not someone on the working on this issue, can i please take this issue. I am not an experienced developer but I would like to contribute. also I have a potential solution already.

**Comment by romani** [comment]
@heyannely , if you are new to project, please start contribution from https://github.com/checkstyle/checkstyle/issues?q=is%3Aopen+is%3Aissue+label%3A%22gsoc+second+issue%22 to smooth be introduced to project and be productive quickly.

**Comment by romani** [comment]
Please read https://github.com/checkstyle/checkstyle/wiki/What-label-to-put-on-issue-%3F for labels.

**Comment by heyannely** [comment]
@romani Thank you, we will follow all guidelines. We have validated a potential solution on both windows and mac. We would like to submit a pull request following guidelines.

**Comment by romani** [comment]
Ok please send separate PR to improve further.

**Comment by romani** [comment]
Fix is merged
