### ISSUE TITLE
Invalid Bump URL

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#13070]
https://github.com/checkstyle/checkstyle/actions/runs/4998008640/jobs/8952982505
````
Error:  Validation of release number failed. Release number is a patch(10.11.1), but release notes contain 'new' or 'breaking compatability' labels. Please correct release number by running https://github.com/checkstyle/checkstyle/actions/workflows/bump-version-and-update-milestone.yml. The offending issue(s): https://github.com/checkstyle/checkstyle/issues/12507
````

https://github.com/checkstyle/checkstyle/actions/workflows/bump-version-and-update-milestone.yml.
````
Not found 

This workflow does not exist.
````

I am expecting a valid and working URL.

**Comment by rnveach** [comment]
The issue appears to be slightly a github actions display error.

GH actions display thinks the end period, which ends the sentence, is part of the URL and so added it to the link. I am just clicking on the link in the display and not copying/pasting it.

**Comment by romani** [comment]
Fixed at https://github.com/checkstyle/contribution/commit/aa6702eada6b6a20e3ce48f3391c1cdeecfe6e67

Reruning generator.

**Comment by romani** [comment]
Extra fix: https://github.com/checkstyle/contribution/commit/0a72c4e56fe0840db142408a0674ed5132dc5f9b

Sorry for my code changes from phone.

Passed: https://github.com/checkstyle/checkstyle/actions/runs/5015842959/jobs/8991944288
