### ISSUE TITLE
Split modules' xdoc into separate pages

### ISSUE THREAD

**Issue by stoyanK7** [checkstyle/checkstyle#13097]
All modules are grouped by a category on a single page - https://checkstyle.sourceforge.io/config_filters.html

This issue aims to split them so that every module has its own page.

Categories to split:

- [x] [Filters](https://checkstyle.sourceforge.io/config_filters.html)
- [x] [File Filters](https://checkstyle.sourceforge.io/config_filefilters.html)
- [x] [Annotations](https://checkstyle.sourceforge.io/config_annotation.html)
- [x] [Block Checks](https://checkstyle.sourceforge.io/config_blocks.html)
- [x] [Class Design](https://checkstyle.sourceforge.io/config_design.html)
- [x] [Coding](https://checkstyle.sourceforge.io/config_coding.html)
- [x] [Headers](https://checkstyle.sourceforge.io/config_header.html)
- [x] [Imports](https://checkstyle.sourceforge.io/config_imports.html)
- [x] [Javadoc Comments](https://checkstyle.sourceforge.io/config_javadoc.html)
- [x] [Metrics](https://checkstyle.sourceforge.io/config_metrics.html)
- [x] [Miscellaneous](https://checkstyle.sourceforge.io/config_misc.html)
- [x] [Modifiers](https://checkstyle.sourceforge.io/config_modifier.html)
- [x] [Naming Conventions](https://checkstyle.sourceforge.io/config_naming.html)
- [x] [Regexp](https://checkstyle.sourceforge.io/config_regexp.html)
- [x] [Size Violations](https://checkstyle.sourceforge.io/config_sizes.html)
- [x] [Whitespace](https://checkstyle.sourceforge.io/config_whitespace.html)

**Comment by stoyanK7** [comment]
Can we disregard the `config_` prefix for new xdoc files?

What should the folder structure look like? 
- `xdoc/<check>` - `xdoc/abstractclassname.xml`
- `xdoc/<category>/<check>` - `xdoc/naming/abstractclassname.xml`
- `xdoc/checks/<category>/<check>` - `xdoc/checks/naming/abstractclassname.xml` - I would go with this personally

What do you think?

**Comment by nrmancuso** [comment]
> Can we disregard the config_ prefix for new xdoc files?

I am good with this.

I also prefer option 3 for file structure.

**Comment by romani** [comment]
> xdoc/checks/naming/abstractclassname.xml

yes, lets do this.

**Comment by nrmancuso** [comment]
Closed via #13266
