### ISSUE TITLE
Resolves Pitest for VariableDeclarationUsageDistanceCheck

### ISSUE THREAD

**Issue by Kevin222004** [checkstyle/checkstyle#13095]
Part of https://github.com/checkstyle/checkstyle/issues/13089

This issue will cover all the suppressed mutation for VariableDeclarationUsageDistanceCheck.

https://github.com/checkstyle/checkstyle/blob/6f451fbb49afc21b0e04b46c0576c7a984419a88/config/pitest-suppressions/pitest-coding-1-suppressions.xml#L111-L190

**Comment by Kevin222004** [comment]
I am on it.

**Comment by romani** [comment]
Resolved at scope of https://github.com/checkstyle/checkstyle/issues/13109

Point `6)`
