### ISSUE TITLE
Resolves Pitest for DeclarationOrderCheck

### ISSUE THREAD

**Issue by Kevin222004** [checkstyle/checkstyle#13102]
Part of #13089

This issue will cover all the suppressed mutation for DeclarationOrderCheck
https://github.com/checkstyle/checkstyle/blob/d60bae5293a4221f4e5b28da1300441a90be5d44/config/pitest-suppressions/pitest-coding-1-suppressions.xml#L12-L28

**Comment by romani** [comment]
Please keep in mind that you can send few PRs to fix them, do not block some fixes is some other are ready for merge.

**Comment by romani** [comment]
Resolved at scope of https://github.com/checkstyle/checkstyle/issues/13109

Point `5)`
