### ISSUE TITLE
Resolves Pitest for AbstractSuperCheck

### ISSUE THREAD

**Issue by Kevin222004** [checkstyle/checkstyle#13108]
Part of https://github.com/checkstyle/checkstyle/issues/13089

This issue will cover all the suppressed mutation for AbstractSuperCheck.java

https://github.com/checkstyle/checkstyle/blob/d60bae5293a4221f4e5b28da1300441a90be5d44/config/pitest-suppressions/pitest-coding-1-suppressions.xml#L3-L10

**Comment by romani** [comment]
@Kevin222004 , lets not create too much tickets.
please copy https://github.com/checkstyle/checkstyle/issues/13089 to new ticket created by you and simply reference only it in all PRs

you can always update ticket to put link to PR for specific mutation, to see that is in flight , what is done and what is still not done.

**Comment by nrmancuso** [comment]
Closed via #13111
