### ISSUE TITLE
Create separate ant-phase-verify execution for xdocs-examples

### ISSUE THREAD

**Issue by stoyanK7** [checkstyle/checkstyle#13116]
From https://github.com/checkstyle/checkstyle/pull/13112#discussion_r1211651794
> 
> what is benefit to include such files in this validation ?
> https://github.com/checkstyle/checkstyle/blob/master/config/checkstyle-non-main-files-checks.xml
> 
> I see no reason to reuse all this validation and fight with suppression later on.
> 
> Lets have one more config and separate execution.

**Comment by romani** [comment]
Start with two, we will continue extension as we notice what should done also

**Comment by nrmancuso** [comment]
A few I can think of:
 - file length
 - tabs in file
 - no trailing whitespace

**Comment by stoyanK7** [comment]
On it.

**Comment by rnveach** [comment]
Fix was merged
