### ISSUE TITLE
Two spaces indentation for xdoc tests

### ISSUE THREAD

**Issue by stoyanK7** [checkstyle/checkstyle#13113]
It was proposed to use 2 spaces of indentation instead of 4 for xdoc tests to keep them short. I'm personally okay with that.

If everybody agrees, a checkstyle rule has to be created for those test inputs.

**Comment by nrmancuso** [comment]
@stoyanK7 @romani how is this different than https://github.com/checkstyle/checkstyle/issues/13116?

**Comment by romani** [comment]
This issue for particular Check 
That issue just to setup checkstyle ant execution on special config.

**Comment by stoyanK7** [comment]
@nrmancuso It actually isn't any different. I opened it before getting the suggestion to make a completely separate config. My bad. I should have just edited this one.

**Comment by nrmancuso** [comment]
@stoyanK7 no worries, better to track all ideas and not lose anything :)
