### ISSUE TITLE
guidelines for using part of Example file in xdoc content 

### ISSUE THREAD

**Issue by stoyanK7** [checkstyle/checkstyle#13130]
From https://github.com/checkstyle/checkstyle/pull/13112#discussion_r1212496420
> How do we know when to include package in examples and when not to?

**Comment by romani** [comment]
I still recommend for now to make hardcoded list of allowances, and rethink this at the end of summer when we have whole picture.

**Comment by nrmancuso** [comment]
> I still recommend for now to make hardcoded list of allowances, and rethink this at the end of summer when we have whole picture.

Yes, for now we can have a hardcoded 'includes' list.

**Comment by stoyanK7** [comment]
Can we not make the examples input parser look for comments like `// example from` and `// example to` and decide what to put in xdoc based on those?

**Comment by nrmancuso** [comment]
> Can't we make the examples input parser look for comments like `// example from` and `// example to` and decide what to put in xdoc based on those?

Yes. But if we want to make sure that examples are the “same” without having to be identical (comments, line wrap, etc), using the AST and some properties declared in examples makes it much easier and more reliable.

**Comment by romani** [comment]
> Can't we make the examples input parser look for comments like

good idea. It might also resolve a issue that we need to put whole class or method signature in Example, but such lines requires only for compiler and for human it will just a noise.

**Comment by stoyanK7** [comment]
Closing this as we now use delimiters to include part of example - `// xdoc section -- start` and `// xdoc section -- end`
Issue: https://github.com/checkstyle/checkstyle/issues/13134
Merged PR: https://github.com/checkstyle/checkstyle/pull/13357
