### ISSUE TITLE
Bad Side effects of Pitest

### ISSUE THREAD

**Issue by Kevin222004** [checkstyle/checkstyle#13142]
This issue is been created to make a list of some bad side effects of Pitest on the codebase.

# 0 All caching of operations

Surviving pitest mutations for conditions reducing time complexity at PackageObjectFactory - https://github.com/checkstyle/checkstyle/issues/11902

# 1 creation of mutable collection consider as can be avoided 
 https://github.com/checkstyle/checkstyle/pull/13127 
and https://github.com/checkstyle/checkstyle/pull/13126  
```
        public Set<DetailAST> getMethodCalls() {
            return Collections.unmodifiableSet(methodCalls);
        }
```
this code has been mutated as 
```
        public Set<DetailAST> getMethodCalls() {
            return methodCalls;
        }
```
Modifying the code with Pitest from `return Collections.unmodifiableSet(methodCalls)` to `return new HashSet<>(methodCalls)` eliminates the guarantee of returning an unmodifiable set, potentially leading to unintended modifications and inconsistent behavior.

but in same time if method is API, it is good to add pure unit test to kill mutation - [Example](https://github.com/checkstyle/checkstyle/pull/13156#pullrequestreview-1461216335).
-------------------------------
 
# 2 does not allow performance optimization in logic 

https://github.com/checkstyle/checkstyle/pull/13557 RequireEmptyLineBeforeBlockTagGroup
https://github.com/checkstyle/checkstyle/pull/13120 VariableDeclarationUsageDistanceCheck
https://github.com/checkstyle/checkstyle/pull/13149  UnusedLocalVariableCheck
https://github.com/checkstyle/checkstyle/pull/13196   MagicNumberCheck
https://github.com/checkstyle/checkstyle/pull/13416 BlockCommentPosition
https://github.com/checkstyle/checkstyle/pull/13430  CheckUtil
```
        while (result
                && !isUsedVariableDeclarationFound
                && currentSiblingAst != null) {
```
mutated as 
```
        while (!isUsedVariableDeclarationFound
                && currentSiblingAst != null) {
```
by the removal of the result, the output will not affect.
but the whole loop can run for more time than it was running with the result. This type of change is not good as it might lead to a problem.

------

It forcing to write less explicit code even it is redundant. So user readability is tiny decreasing sometimes.
Example: https://github.com/checkstyle/checkstyle/pull/13381#issuecomment-1627715592

-----------

# 3. Extra code that does help to make code more robust to future changes that might miss extended testing.

https://github.com/checkstyle/checkstyle/pull/13334  (ImportOrderCheck)
The code is extra the removal will not make any issue but it might be problematic in future and affect the user 
for example in this pr https://github.com/checkstyle/checkstyle/pull/13334
we can simply follow the mutation and remove the code from the reset stage but this might lead to a bigger problem.

-----------

# 4. Copy of array(collections) to protect data from changes

https://github.com/checkstyle/checkstyle/pull/13340

----------

# 5. Pitest config allows only whole Test class execution, but it would be good to have option to run single test method from class

see details at https://github.com/checkstyle/checkstyle/pull/13810#discussion_r1342147419

# 6 code might be less elegant if chained call of cast to type is present

Read details at https://github.com/checkstyle/checkstyle/pull/13913
cast and creation of modifiable https://github.com/checkstyle/checkstyle/pull/13944#discussion_r1370143348

**Comment by rnveach** [comment]
> return Collections.unmodifiableSet(methodCalls);
> this code has been mutated as
> return new HashSet<>(methodCalls);

I would have to see the report, but I would expect pitest is actually mutating it to `return methodCalls`.

**Comment by nrmancuso** [comment]
> > return Collections.unmodifiableSet(methodCalls);
> > this code has been mutated as
> > return new HashSet<>(methodCalls);
> 
> I would have to see the report, but I would expect pitest is actually mutating it to `return methodCalls;` .

This is correct.

**Comment by Kevin222004** [comment]
> > return Collections.unmodifiableSet(methodCalls);
> > this code has been mutated as
> > return new HashSet<>(methodCalls);
> 
> I would have to see the report, but I would expect pitest is actually mutating it to `return methodCalls;` .

reply yes it is actually mutating to return methodCalls. i am updating it

**Comment by Vyom-Yadav** [comment]
> Modifying the code with Pitest from return Collections.unmodifiableSet(methodCalls) to return new HashSet<>(methodCalls) eliminates the guarantee of returning an unmodifiable set, potentially leading to unintended modifications and inconsistent behavior.

Pure UTs are the only things that can kill these mutations. We have some existing pure UTs for other type of cases too: https://github.com/checkstyle/checkstyle/blob/db858f85ea50d79c0638e1e2a9c6e6d0c098ce86/src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheckTest.java#L300-L408

**Comment by romani** [comment]
We need to open issues on pitest project for all above items.

**Comment by Kevin222004** [comment]
I have opened the issue in the Pitest project mentioned in the Description.

Point no-1 :-  https://github.com/hcoles/pitest/issues/1300

point no-2 :-  https://github.com/hcoles/pitest/issues/1299

point no-4 :-  https://github.com/hcoles/pitest/issues/1301

point no-5 :-  https://github.com/hcoles/pitest/issues/1298

point no-6 :-  https://github.com/hcoles/pitest/issues/1304

**Comment by nrmancuso** [comment]
Bottom line here is that pitest just needs a more robust suppression model (which we have built with groovy).

**Comment by romani** [comment]
I am closing this issue.

@Kevin222004 , did a huge work, I doubt anybody did so deep resolving of survivals on such experimental mutators. I hope pitest will be able to improve and not raise extra raise mutations.

Our project is very strong evidence that pitest is way better metric on coverage of code by test. Jacoco is super basic metric, and pitest is next level of coverage metric.
