### ISSUE TITLE
Trigger linkcheck by Github comment

### ISSUE THREAD

**Issue by stoyanK7** [checkstyle/checkstyle#13162]
From https://github.com/checkstyle/checkstyle/pull/13103#issuecomment-1576878233
> I think we need to think one more time to make GitHub action triggered by comment to run link check plugin validation. It will help a lot us during summer.

**Comment by stoyanK7** [comment]
We can upload the report as an artifact. Also, I think the script itself will have to be changed. I intentionally put a broken link and it does not show in the terminal output but is visible in the report.
https://github.com/checkstyle/checkstyle/blob/655196ed840b1cb443607a9e6f330a562bfcb2c4/.ci/run-link-check-plugin.sh#L17

**Comment by romani** [comment]
Github, generate linkcheck report

Post link on failure, is ok.

**Comment by stoyanK7** [comment]
Moving to `in progress`, I have it working at https://github.com/stoyanK7/checkstyle/commit/37cf99c01c98727efbae445fae2f297fb2b2b33a but first we need to take care of https://github.com/checkstyle/checkstyle/issues/13166.

**Comment by nrmancuso** [comment]
Execution of this script in CircleCI takes 4 minutes: https://app.circleci.com/pipelines/github/checkstyle/checkstyle/18752/workflows/57f04258-3226-4c84-8f59-0f5cf9c70d50/jobs/301384

Why aren't we just running it on all PRs in regular CI execution?

**Comment by romani** [comment]
Strange on my local it took about 15 minutes, this plugin use to run during release process that I did on my local each month.
If only 4 minutes now in cloud let's keep it in CI on each PR, but it might be annoying.
Any migration of url from http to https will be failure in all PRs - not good.

Let's do this by request, it is more reliable from my experience

**Comment by stoyanK7** [comment]
Takes around 4 minutes for me as well.

> Let's do this by request, it is more reliable from my experience

https://github.com/checkstyle/checkstyle/pull/13174 adds it to every PR so I assume this is what we are going with.

**Comment by nrmancuso** [comment]
> Let's do this by request, it is more reliable from my experience

This is a bunch of extra work (to make GitHub action triggered by comment). Your experience has also shown that execution takes 15 minutes, which was not accurate. I am not afraid to modify/remove this job if it causes us problems in the future. Let’s merge PR at https://github.com/checkstyle/checkstyle/pull/13174 and move on.

**Comment by nrmancuso** [comment]
> Let's do this by request, it is more reliable from my experience

This is a bunch of extra work (to make GitHub action triggered by comment). Your experience has also shown that execution takes 15 minutes, which was not accurate. I am not afraid to modify/remove this job if it causes us problems in the future. Let’s merge PR at https://github.com/checkstyle/checkstyle/pull/13174 and move on.

Also experience has shown me that we should not count on human to remember to run link check by comment.

**Comment by romani** [comment]
I am ok to merge activation in CircleCI

**Comment by stoyanK7** [comment]
Closing this issue because of https://github.com/checkstyle/checkstyle/pull/13174

**Comment by romani** [comment]
I reopened it, as execution in PR CI, will be too prone to outside of our repo changes, so we likely to disable it after summer.

We can put this issue to bottom of priority for xdoc generation project, and decide on it at end of summer.

**Comment by avadhutmali** [comment]
Is this still in scope for contribution? I would like to work on it.

**Comment by Krish-876** [comment]
Hi, I looked into this issue. There is already a comment triggered workflow for site preview in `site.yml`, but it runs with `-Pno-validations`, which skips linkcheck and there is already a master only linkcheck workflow, but it does not cover PR comment-triggered use. I’m planning a separate comment triggered workflow for linkcheck so the current site preview flow stays unchanged. Please let me know if this direction looks fine.

**Comment by romani** [comment]
first version is merged.

testing at https://github.com/checkstyle/checkstyle/pull/19796#issuecomment-4424780821

runs: https://github.com/checkstyle/checkstyle/actions/runs/25695048699/job/75441012171

**Comment by romani** [comment]
works good.
https://github.com/checkstyle/checkstyle/pull/19796#issuecomment-4424906123
