### ISSUE TITLE
Decide on how to handle edge cases for `@MessageKey`

### ISSUE THREAD

**Issue by stoyanK7** [checkstyle/checkstyle#13160]
From https://github.com/checkstyle/checkstyle/pull/13129#issuecomment-1575564110

> There is an edge case here. Take `RegexpMultiline` for example. It does not have any message keys declared and gets its error messages from `MultilineDetector`. How should we deal with that?
> 
> Another annotation? Leave a clue in the xdocs template to go look for them in that module?

https://github.com/checkstyle/checkstyle/pull/13129#issuecomment-1575566153
> uhh, this is are of code that we did not look at for 20 years.
> ideally we should refactor it to copy all MSG to Checks (even there will be few copies)
> and let MultilineDetector just return to Check boolean flag to report violation or not.
> log must be only in Checks, all other classes are just helpers.
> This should be separate issue and we need to make decision to do this in this project or not.
> I think refactoring will be easier then thinking how to workaround this case.

**Comment by romani** [comment]
There are more Checks that do have abstract classes with logic of validation, and they inherited messages from parents.

Please look at metadata module, it already does this, and it looks like it does it in runtime after all classes are loaded.

**Comment by rnveach** [comment]
This is what is being referenced:

https://github.com/checkstyle/checkstyle/blob/655196ed840b1cb443607a9e6f330a562bfcb2c4/src/test/java/com/puppycrawl/tools/checkstyle/internal/utils/CheckUtil.java#L224-L244

**Comment by stoyanK7** [comment]
Closing this as we went with the code that was referenced above, not annotations above message keys.

PR with implementation: https://github.com/checkstyle/checkstyle/pull/13423
