### ISSUE TITLE
Extend `generate-extra-site-links.sh` to not include deleted pages in comments

### ISSUE THREAD

**Issue by stoyanK7** [checkstyle/checkstyle#13175]
Detected at https://github.com/checkstyle/checkstyle/pull/13103#issuecomment-1577583272

> Just clicking on a few in the last comment turned up this one that doesn't work: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/810d38a_2023210012/config_annotation.html#

In that case, the file `config_annotation.xml` is deleted and no link should be written by the action.

**Comment by romani** [comment]
We will do this At the end of summer.

**Comment by stoyanK7** [comment]
Another related: https://github.com/checkstyle/checkstyle/pull/13357#discussion_r1264395057
