### ISSUE TITLE
Implement module java parser

### ISSUE THREAD

**Issue by stoyanK7** [checkstyle/checkstyle#13177]
The purpose of this issue is to gather requirements on how this parser should work and then implement it after an agreement is achieved.

The job of this parser is to read the module java - for instance `AbstractClassName.java` and extract the following data:
- Description - from class Javadoc
- Since - from class Javadoc
- Package - from the package above imports
- Properties - from class fields and their javadocs
- Violation messages - from `@Message key` annotation https://github.com/checkstyle/checkstyle/issues/13114 and https://github.com/checkstyle/checkstyle/issues/13160#issuecomment-1575691954
- Parent module - There is a proposal to add a `@ParentModule("Checker")` annotation. An issue needs to be opened there.

> Note: the above are just an initial proposal

**Comment by nrmancuso** [comment]
Can we determine parent module from superclass of check? Where is the proposal for new annotation?

**Comment by romani** [comment]
We can make a decision of Check parent by analysis of parent classes and methods of module. Treewalker children has AST based methods. If not Treewalker, it is Checker.

**Comment by romani** [comment]
@stoyanK7 , do we still need this issue, looks like we split it into few smaller and did them separartely.
please close if I am right.

**Comment by nrmancuso** [comment]
@stoyanK7 ping ^

**Comment by stoyanK7** [comment]
Absolutely, the issue was split into multiple
- Properties macro - https://github.com/checkstyle/checkstyle/pull/13407
- Parent module - https://github.com/checkstyle/checkstyle/pull/13435
- Violation messages - https://github.com/checkstyle/checkstyle/pull/13423
