### ISSUE TITLE
Fix broken anchors in subdirectories/subpages

### ISSUE THREAD

**Issue by stoyanK7** [checkstyle/checkstyle#13190]
Moved from https://github.com/checkstyle/checkstyle/pull/13103#issuecomment-1584750932
> Let's move this to separate issue. We can have regression here for for month or two.

---
#### problem
> There is also a bug where I cannot create links to sub-headers like Description and Properties when clicking on said sub-header.

#### explanation
> The reason is that the headers are same for all pages and path to script is relative.
https://github.com/checkstyle/checkstyle/blob/958051594a64ea5a228359919ed7426e69a242d7/src/site/site.xml#L45-L56

> 
> ```
> GET
> https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/810d38a_2023210012/checks/annotation/js/anchors.js
> [HTTP/1.1 403 Forbidden 105ms]
> ```
> 
> There are two solutions here. Either we go with absolute paths (harder in my opinion) or we remove the `<head>` from the snippet above and write a `<head>` tag for **every singe page**. It is a lot of duplication but I wouldn't mind it that case. Or maybe e there is a third option I can not think of but you know?

--------

"To top" button does not work, and direct to non existent page, also and should be fixed.

**Comment by rnveach** [comment]
> we go with absolute paths 

Just reminding absolute paths won't work for older version documentation and github site generation.

> or we ... write a <head> tag for every singe page

What tool do we use to generate the site from the xdoc? I would like to see what it supports, and if we should file an issue with them.

**Comment by romani** [comment]
>What tool do we use to generate the site from the xdoc?

Maven site plugin. Doxia library is used to manage html generation.

**Comment by rnveach** [comment]
> remove the <head> from the snippet above and write a <head> tag for every singe page

We already have duplicate `head` tags in pages for the title.
See https://github.com/checkstyle/checkstyle/blob/master/src/xdocs/idea.xml#L7-L9 .

We would just need to move the tags with changing relative paths.

**Comment by rnveach** [comment]
As a side note, `maven-site-plugin` 3.12.1. doesn't use the latest version of `doxia-module-xdoc`. It uses `1.11.1` and according to https://mvnrepository.com/artifact/org.apache.maven.doxia/doxia-module-xdoc the plugin had a `1.12.0` release this year. The M releases of `maven-site-plugin` upgrade to xdoc further.

Don't think this will play a role in this issue.

**Comment by rnveach** [comment]
@stoyanK7 After looking into this a bit more, I did not find a solution, but I do believe this is a doxia issue.

https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/8cea5c0_2023162451/checks/annotation/annotationlocation.html#AnnotationLocation
If you look at the HTML source generated, you can see other links are being relativized correctly that we are not directly controlling.

> `    <link rel="stylesheet" href="../../css/maven-base.css" />`
> `    <link rel="stylesheet" href="../../css/maven-theme.css" />`
> `    <link rel="stylesheet" href="../../css/site.css" />`
> `    <link rel="stylesheet" href="../../css/print.css" media="print" />`
> `<a href="../.././" id="bannerLeft" title="Checkstyle"><img src="../../images/header-checkstyle-logo.png"  alt="Checkstyle"/></a>`
> `<a href="../../index.html" title="Checkstyle">Checkstyle</a>`

We don't lose our CS logo, and links to other pages work correctly.

So obviously, Doxia knows what is going on but we can't get it to apply to our scripts. I could not find anything doing searches.

It could be that our page is doing a "hack" and we are using scripts improperly for their tool.
https://github.com/checkstyle/checkstyle/blob/master/src/site/site.xml#L47
Removing the `CDDATA` now prints an error that `head` should be completely empty.

We should report this as an issue to them. While we are also reporting this, please also report https://github.com/checkstyle/checkstyle/issues/11572#issuecomment-1399388079 as you touched on it as well and my Stackoverflow question has not gotten any responses.

Until a proper fix is found, I am ok with the "header" hack as a temporary workaround.

**Comment by rnveach** [comment]
> "To top" button does not work, and direct to non existent page, also and should be fixed.

This is broken because it is actually coded as a link when it should not be.

https://github.com/checkstyle/checkstyle/blob/master/src/site/site.xml#L58
https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/8cea5c0_2023162451/checks/annotation/annotationlocation.html#AnnotationLocation
> `<a href="../../" title="toTop">toTop</a>`

Without the proper Javascript (or with JS disabled), the link comes out.

The html should really be something like `<a href="#" title="toTop">toTop</a>` so it won't direct anywhere but to the same page.

The only thing I can think of is to remove this, and see if we can add the special HTML to the `footer` section inside `site.xml`.

**Comment by rnveach** [comment]
@stoyanK7 New Update.

Change things like `src="js/checkstyle.js"` to `src="$relativePath/js/checkstyle.js"` in `site.xml`.

**Comment by stoyanK7** [comment]
As https://github.com/checkstyle/checkstyle/pull/13103 gets merged, this issue can be closed. The fix works.

**Comment by rnveach** [comment]
If it can be needed separately, then I recommend that. Does your fixes include https://github.com/checkstyle/checkstyle/issues/13190#issuecomment-1586242871 ?

**Comment by stoyanK7** [comment]
The `$relativePath` fix was found at https://github.com/apache/maven-doxia-sitetools/blob/1f9fcf561c3a4e7ccd39dfd49bb905a296bfac1b/doxia-site-renderer/src/main/resources/org/apache/maven/doxia/siterenderer/resources/default-site.vm#L44
Even though the file ends in `.vm`, the feature works on normal `.xml` xdoc files.

---
`.vm` extension is connected with the `Velocity`project.

**Comment by rnveach** [comment]
> the feature works on normal .xml xdoc files.

The feature actually doesn't work on XML files under the xdoc folder, but does work on the VM files in said directory. I assume `site.xml` must be treated as a velocity page even though the extension is different.

Also,
> The html should really be something like `<a href="#" title="toTop">toTop</a>` so it won't direct anywhere but to the same page.

Was not done from https://github.com/checkstyle/checkstyle/issues/13190#issuecomment-1586242871

**Comment by stoyanK7** [comment]
Documentation for `$relativePath`
https://maven.apache.org/doxia/doxia-sitetools/doxia-site-renderer/#velocity-processing
