### ISSUE TITLE
Automate extraction of examples

### ISSUE THREAD

**Issue by stoyanK7** [checkstyle/checkstyle#13204]
From https://github.com/checkstyle/checkstyle/pull/13135#issuecomment-1586040828

> looks like we all aligned on final view.
Please proceed with conversion of xdoc java snippets to Examples. I am not sure what is best approach: manual or semi-automated.
Please share your vision on this, in separate issue.
Better to not continue discussion in this PR.

Doing this completely manually would be awful.

I already have a Python script that does all the boilerplate stuff for me but manual work is still required. First, to make the examples compilable, I have to create the imports sometimes. IntelliJ takes care of this so not a big issue. Second, the violation messages have to always be taken care of manually because I have to decide what part needs to be included from them while at the same time keeping the message short. And finally, creating the tests themselves. I have to run the example to see what exactly is a violation and input it in the expected violations. This one is probably the most time-consuming of all. I haven't noticed other things **for now**.

It would be good to add some check to ensure that those examples have been moved correctly. But at the same time it needs to be very flexible because examples might change(if we want to make them shorter, etc..) One thing that can be asserted for sure is the XML config is moved correctly. The Java code I am not sure how to assert without the check breaking on every other extraction.

Another note, the script I wrote creates a `.template.xml` file and puts placeholders in place of the extracted examples. It would be a good idea to start making the templates from now.

**Comment by nrmancuso** [comment]
@stoyanK7 I am not clear on why we created this issue. If this is only for discussion about your python script to migrate xml examples to java code, please convert to GitHub discussion.
