### ISSUE TITLE
Add links to examples paragraphs

### ISSUE THREAD

**Issue by stoyanK7** [checkstyle/checkstyle#13205]
From https://github.com/checkstyle/checkstyle/pull/13112#discussion_r1225682976
> As the discussion in discord, should these PRs add the ID to connect the xdoc and input together?

This is a good idea but I cannot add `id` prop directly to a `source` tag
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.12.1:site (default-site) on project checkstyle: Error parsing '/home/stoyan/open-source/checkstyle/src/xdocs/config_blocks.xml': Error validating the model: Error:
[ERROR]   Public ID: null
[ERROR]   System ID: null
[ERROR]   Line number: 85
[ERROR]   Column number: 26
[ERROR]   Message: cvc-complex-type.3.2.2: Attribute 'id' is not allowed to appear in element 'source'.
```

An option here is to create an invisible div above the example.
```diff
+        <div id="Example1.config" style="display:none;"></div>
        <source>
&lt;module name=&quot;AvoidNestedBlocks&quot;/&gt;
        </source>
```

In addition to this, I see there is a task at https://github.com/orgs/checkstyle/projects/5 to investigate the ability to set links for any place we think. 

Why don't we combine those two?

**Comment by stoyanK7** [comment]
I am going to create a couple of proposals and post screenshots below soon.

**Comment by stoyanK7** [comment]
![Screenshot from 2023-06-13 17-15-07](https://github.com/checkstyle/checkstyle/assets/23459549/7bc2cb5d-f9b0-4dc5-bce7-2a924f3e6542)
Link points to `file:///home/stoyan/open-source/checkstyle/target/site/config_naming.html#Example1.config`
Similar to how section and subsection titles' anchors work - you have to hover to see it

**Comment by stoyanK7** [comment]
![Screenshot from 2023-06-13 17-44-48](https://github.com/checkstyle/checkstyle/assets/23459549/8b7a5075-5162-4c90-91b3-4e5b5725ddaf)
Examples have just enough padding to fit in the example anchor on the top left.
Link points to `file:///home/stoyan/open-source/checkstyle/target/site/config_naming.html#Example1.config`

**Comment by nrmancuso** [comment]
I feel that it would be better to have some explicit link. Not exactly like `See …`, but something similar.

**Comment by stoyanK7** [comment]
As in the link written out on top of the example? Please elaborate more.

**Comment by nrmancuso** [comment]
Ok, after seeing working examples, I realize I misunderstood the whole point of this issue (I am not very familiar with web dev terms). I like https://github.com/checkstyle/checkstyle/issues/13205#issuecomment-1589523232

**Comment by stoyanK7** [comment]
I suppose this is what we are going with - it is also consistent with how other anchors work until now. I will make sure to add those in new examples from tomorrow. And I have to open a PR about the ones that have already been merged.

**Comment by stoyanK7** [comment]
We can add a check to ensure all examples have an anchor. I imagine a big file of suppressions being made and gradually removing them.

**Comment by rnveach** [comment]
fix was merged
