### ISSUE TITLE
Accept more types of comments in `InlineConfigParser`

### ISSUE THREAD

**Issue by stoyanK7** [checkstyle/checkstyle#13222]
From https://github.com/checkstyle/checkstyle/pull/13219#discussion_r1228944093

> While the html config "comment" is debatable (I am not a big fan), this is not valid xml. As we demand compilation for java files, we should have valid xml. Are we able to simply put this comment inside of a valid multiline xml comment? If fix is that easy, we should also update html file.

---
All inline test configurations have to start with `/*` which is an issue with files whose comments are different. For example `xml`,`html` with `<!--` and `-->`. The purpose of this issue is to allow more types of comments be accepted in test configurations.

**Comment by stoyanK7** [comment]
The improvement is only a minor change in the method at https://github.com/checkstyle/checkstyle/blob/79d3c5536760d2645b0676c5a7f31da3bb0eed72/src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java#L164-L167. I have it working. I am going to push at #13219 for proof and then open a PR for that soon.

**Comment by nrmancuso** [comment]
> Let's deal with such exceptional examples at the end . I am fine for now to have them as hard coded in template without validation of execution.
> 
> We will deal with them at the end of project

Update was simple, no need to delay. It will be more effort on all parties to push this task back.

**Comment by romani** [comment]
If simple, I am ok. I just try to share with you all that it should not take bunch of our time, while no main functionality of project is done.

There are also bash files, property files in examples. It might grow quickly to very complicated feature.

**Comment by romani** [comment]
Better to do it in different way
https://github.com/checkstyle/checkstyle/issues/13267
