### ISSUE TITLE
Extend checkstyle-examples-checks

### ISSUE THREAD

**Issue by nrmancuso** [checkstyle/checkstyle#13244]
As we progress in xdocs generation project, we are discovering more check modules that need to be added. We can use this issue to track them. Please comment here and I will update list as needed until we send a PR.

 - enforce newline at end of file
 - forbidden regexp in violation messages
 - check for compilation comments in non-compilable resource folder
 - discourage usage of regexp escaping in violation messages ( we should use java examples code without such symbols)
 - Add CommentsIndentation check
 - check for presence of xdoc delimiter comments (`// xdoc section -- start`)

**Comment by stoyanK7** [comment]
From https://github.com/checkstyle/checkstyle/pull/13214#discussion_r1235726628
> Add CommentsIndentation.

> Better to add it later on, please create issue to do this in separate PR.
In other case we will never finish first step - just some validation activation.

**Comment by stoyanK7** [comment]
From https://github.com/checkstyle/checkstyle/pull/13214#discussion_r1235726628
> Add CommentsIndentation.

> Better to add it later on, please create issue to do this in separate PR.
In other case we will never finish first step - just some validation activation.

**Comment by rnveach** [comment]
Fix was merged
