### ISSUE TITLE
Remove suppressed broken link after 10.12.1 is released

### ISSUE THREAD

**Issue by stoyanK7** [checkstyle/checkstyle#13247]
In https://github.com/checkstyle/checkstyle/pull/13176 we add a suppression for a link.
The line `<td><i><a class="externalLink" href="https://checkstyle.org/checks/annotation/suppresswarningsholder.html#SuppressWarningsHolder">https://checkstyle.org/checks/annotation/suppresswarningsholder.html#SuppressWarningsHolder</a>: 404 Not Found</i></td></tr></table></td></tr>` has to be removed from `config/linkcheck-suppressions`.

**Comment by romani** [comment]
We should do this after june release
