### ISSUE TITLE
Move Filters and File Filters to be a sibling of Checks in site menu

### ISSUE THREAD

**Issue by stoyanK7** [checkstyle/checkstyle#13283]
Right now `Filters` and `FileFilters` are under `Configuration`
![Screenshot from 2023-06-21 13-56-56](https://github.com/checkstyle/checkstyle/assets/23459549/7c4c3ef4-b968-4b8b-9873-02ba9f00c182)

We can move them to be a sibling of `Checks` like this. They are already a big package of modules.
![Screenshot from 2023-06-21 13-56-18](https://github.com/checkstyle/checkstyle/assets/23459549/1f8b4604-71d8-4c72-8fce-8cbb88c78368)

**Comment by nrmancuso** [comment]
@rnveach please take a look, and approve if you are good with this change. As mentioned in discord, @romani and I are good with this.

**Comment by romani** [comment]
I am good with proposal, looks good even above "Checks"
