### ISSUE TITLE
Add supported Java Language Level to website

### ISSUE THREAD

**Issue by nrmancuso** [checkstyle/checkstyle#13293]
Discussed at https://github.com/checkstyle/checkstyle/issues/13279, it would be a good idea to point out what language level the project currently supports:

> @nrmancuso , do you think it is reasonable to put somewhere on our website info what version of jdk syntax we support currently ?
we have only run time - https://checkstyle.org/#JRE_and_JDK

_Originally posted by @romani in https://github.com/checkstyle/checkstyle/issues/13279#issuecomment-1602646621_

**Comment by romani** [comment]
@nrmancuso , what jdk syntax we support now ? 19th ? do we have full support or partial ?

**Comment by nrmancuso** [comment]
All preview and regular language features for JDK19 are supported currently.

**Comment by rnveach** [comment]
This issue should also document what we won't support, when we identify those things, like [JEP 445: Unnamed Classes and Instance Main Methods ](https://openjdk.org/jeps/445).
