### ISSUE TITLE
Add support to our Inputs for lines with multiple violations

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#13307]
This was a problem for long time but become very acute at https://github.com/checkstyle/checkstyle/pull/13276#discussion_r1237941452

We need to update our Abstract Test classes to allow lines like: 
```
    Runnable noop = () ->{}; // 4 violations, see messages below 
                          // ''->' is not followed by whitespace'
                          // ''{' is not followed by whitespace'
                          // ''{' is not preceded with whitespace'
                          // ''}' is not preceded with whitespace'
```

so all messages are just on new lines below ` 4 violations, see messages below `
So Reviewer will clearly see what is a violation.

example: 
https://github.com/checkstyle/checkstyle/blob/3d8ed42ab60c0399550b3e7d54ca9dd767583101/src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationlocation/InputAnnotationLocationIncorrect.java#L38
but there are more in code.

pattern that used at [PR](https://github.com/checkstyle/checkstyle/pull/13951), may be extra `:` is required to signal that second line is continuation:
```
    /**
     *  <p> <li> <TR> <Td> <tH> <.....
     *      <tFoot> // ok
     * @param field5 </p> value to which {@link #field5} is to be set to
     */
    // 4 violations 4 lines above:
    //                            'Unclosed HTML tag found: p'
    //                            'tag P_TAG_START'
    //                            'tag LI_TAG_START'
    //                            'tag BODY_TAG_START'
    private void setField5(int field5) {this.field5 = field5;}
```

As we process lines one by one, of we detect multiple-line pattern we look ahead for defined set of lines. Processing of such lines with violation only will not match any pattern so they will be skipped by general iteration over lines. Location of single quoted message can be at any indentation, to let user user any formatting to show message as he wants.

**Comment by romani** [comment]
@jxr98 , can you help us with this issue ?

**Comment by jxr98** [comment]
Thanks. I would love to help with this issue.

**Comment by romani** [comment]
@jxr98 , design is not set in stone, so your suggestion to change it to get more robust implementation is appreciated.
All we need is some form of explicit and visial definition of expected violation messages.

**Comment by jxr98** [comment]
Gotcha. Thanks for clarifying.

**Comment by jxr98** [comment]
The multiple violations in one line now are specified in comments as below
```
for (int i = 1; i > 1; i++) {} // 2 violations
                               // 'no space after '{', no space before '}''
```
As Romani pointed out, we can change to the example below
```
for (int i = 1; i > 1; i++) {} // 2 violations, list on separate lines below
                               // 'no space after '{''
                               // 'no space before '}''
```
The differences between multiple violations on one line and single violation on one line:
1. There're no numbers before the word violation in single violation. (multiple violations use the plural form)
2. Multiple violations are followed by newlines.
We can use these two differences to distinguish multiple violations and single violation. Each line followed by the plural form(violations) will be regared as a violation, and the `verifyWithInlineConfigParser` function will need to check if the specified number match the number of newlines as well.
Plz leave a message if you have any idea and correct me if I'm wrong. Thanks.

**Comment by nrmancuso** [comment]
What if we do:
```java

    /*
      4 violations below:
      ''->' is not followed by whitespace'
      ''{' is not followed by whitespace'
      ''{' is not preceded with whitespace'
      ''}' is not preceded with whitespace'
    */
    Runnable noop = () ->{};

```
and

```java

    Runnable noop = () ->{};
    /*
      4 violations above:
      ''->' is not followed by whitespace'
      ''{' is not followed by whitespace'
      ''{' is not preceded with whitespace'
      ''}' is not preceded with whitespace'
    */
```
?

I find this easier to read (less noise than single line comments and no comments on the lines with the code), and probably easier to parse since we have two ways to check for end of violation list (number of violations/lines in first comment line + block comment end delimiter).

**Comment by romani** [comment]
I like both variants, if we need to choose I would use what is easier to implement now to have this feature sooner.

**Comment by romani** [comment]
Reopened fo

NOT done validation of messages for:
```
public class InputAbstractJavadocNonTightHtmlTags2 {
    /** <p> <p> paraception </p> </p> */
    // 3 violations above
    //                    'Unclosed HTML tag found: p'
    //                    'tag P_TAG_START'
    //                    'tag P_TAG_START'
```
I think it is better to do this after this PR, to make sure prove of concept is megred and second PR will be easy to accept as it will just extension.

**Comment by nrmancuso** [comment]
Completed via #14156
