### ISSUE TITLE
JavadocParagraph allows new line before the next paragraph

### ISSUE THREAD

**Issue by pbaranchikov** [checkstyle/checkstyle#1332]
http://checkstyle.sourceforge.net/config_javadoc.html#JavadocParagraph
created base on requirements of http://google.github.io/styleguide/javaguide.html#s7.1.2-javadoc-paragraphs

According to documentation:
> Each paragraph but the first has `<p>` immediately before the first word, with no space after.

I could have `<p>` tag, followed by new line. Text is continued from the next line, so the tag is not "immediately before the first word"

```java
/**
 * First paragraph.
 * 
 * <p>
 * Second paragraph.
 */
```
Also, even spaces are not violated:
```java
/**
 * First paragraph.
 * 
 * <p> Second paragraph.
 */
```

**Comment by romani** [comment]
good point, I do not see any reference in code that it do validation for that, completely missed functionality.

**Comment by romani** [comment]
merged.
