### ISSUE TITLE
Targeted Pitest Mutation in July 2023

### ISSUE THREAD

**Issue by Kevin222004** [checkstyle/checkstyle#13328]
extended from https://github.com/checkstyle/checkstyle/issues/13109 

------

# Pitest-Import Profile

**5) UnusedImportsCheck**
- [x] MemberVariableMutator (1)
       https://github.com/checkstyle/checkstyle/pull/13332

-----------------

# Pitest-api Profile 

**7) FullIdent**
- [x] NonVoidMethodCallMutator (1)
      https://github.com/checkstyle/checkstyle/pull/13179 

--------------------

# Pitest-PackageNamesLoader Profile

- [x] ArgumentPropagationMutator (3)
- [x] NonVoidMethodCallMutator (2)
- [x] EmptyObjectReturnValsMutator (1)
    all the mutations covered by 
    https://github.com/checkstyle/checkstyle/pull/13286

---------

Pitest-coding-1 

**14) EqualsAvoidNullCheck**
- [x] ArgumentPropagationMutator (2)
       https://github.com/checkstyle/checkstyle/pull/13127

**16) VariableDeclarationUsageDistanceCheck**
- [x] RemoveConditionalMutator_EQUAL_IF (1)
       https://github.com/checkstyle/checkstyle/pull/13120

------------

# Pitest-coding-2

**29) UnusedLocalVariableCheck$TypeDeclDesc**
- [x] NonVoidMethodCallMutator (1)
       https://github.com/checkstyle/checkstyle/pull/13331
       
**22) StringLiteralEqualityCheck**
- [x] NakedReceiverMutator (1)
       https://github.com/checkstyle/checkstyle/pull/13277

**26) OneStatementPerLineCheck**
- [x] MemberVariableMutator (2)
      https://github.com/checkstyle/checkstyle/pull/13281
      https://github.com/checkstyle/checkstyle/pull/13163 

**34) IllegalInstantiationCheck**
- [x] MemberVariableMutator (1)
      https://github.com/checkstyle/checkstyle/pull/13284

**27) HiddenFieldCheck$FieldFrame**
- [x] RemoveConditionalMutator_EQUAL_IF (1)

**Comment by Vyom-Yadav** [comment]
@Kevin222004 Are you updating the issue body?

**Comment by romani** [comment]
Issue is closed. There is separate issue for all items that were left to be done.
