### ISSUE TITLE
Implement module properties macro

### ISSUE THREAD

**Issue by stoyanK7** [checkstyle/checkstyle#13399]
After https://github.com/checkstyle/checkstyle/pull/13357 is merged, we will have xdoc templates that use macros for examples. We can create a macro for the properties table that can look like:
```xml
    <macro name="properties">
      <param name="modulePath"
             value="src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/AbstractClassNameCheck.java"/>
    </macro>
```

When the generation of xdocs is run, the macro should produce the following result by crawling the java module
https://github.com/checkstyle/checkstyle/blob/41572dac51680bac020cac3dfc3d866320b38e73/src/xdocs/checks/naming/abstractclassname.xml#L24-L63

**Comment by nrmancuso** [comment]
Closed via #13407
