### ISSUE TITLE
xml-maven-plugin reports violation in site.xml

### ISSUE THREAD

**Issue by Vladlis** [checkstyle/checkstyle#1341]
xml-maven-plugin reports violation in site.xml
https://github.com/Vladlis/checkstyle/commit/79de7c95a420e00fb358f0f40d0397e916297f0e#diff-600376dffeb79835ede4a0b285078036R1009
> [ERROR] Failed to execute goal org.codehaus.mojo:xml-maven-plugin:1.0:validate (default-cli) on project checkstyle: While parsing /home/vlad/eclipseProjects/checkstyle/src/site/site.xml, at file:/home/vlad/eclipseProjects/checkstyle/src/site/site.xml, line 24,  column 31: cvc-complex-type.3.2.2: Attribute 'width' is not allowed to appear in element 'logo'. -> [Help 1]

**Comment by Vladlis** [comment]
I'll do this

**Comment by romani** [comment]
merged.
