### ISSUE TITLE
Create example id's with macro

### ISSUE THREAD

**Issue by stoyanK7** [checkstyle/checkstyle#13439]
Continuing discussion from  https://github.com/checkstyle/checkstyle/pull/13357#discussion_r1272558845

> Is there a reason the macro doesn't create the ids itself so that we don't need to add them manually? Making sure we looked into it, but I guess it would put the link too far below the text it is connected to.

---

> As far as I'm aware, the macro would not be able to do this - edit a paragraph outside of its scope.
> 
> If we really want to automate it - I imagine some method that runs before the Xdoc generation and edits the templates. That method iterates through the macros, constructs an id based on parameters of the macro(Example2-code for example), and adds it to the paragraph preceding the macro.

---

> I was thinking more of adding the link to the end of the paragraph right where we start the scope. I am good regardless, it is just something to think about.

---

> Even if the paragraph is a whole screen-height long, the anchor will appear at the end of it, right above the example snippet. That's how the javascript that appends the anchors works.
> 
> Or am I misunderstanding you?

**Comment by romani** [comment]
this was done somewhere in summer 2023.
![image](https://github.com/checkstyle/checkstyle/assets/812984/c68ea749-65fa-4d8d-8d3f-e059712a0376)
