### ISSUE TITLE
JavadocPackage reports missing package-info.java when package is split accross several folders

### ISSUE THREAD

**Issue by serianox** [checkstyle/checkstyle#13440]
I have read check documentation: https://checkstyle.org/checks/javadoc/javadocpackage.html#JavadocPackage
I have downloaded the latest checkstyle from: https://checkstyle.org/cmdline.html#Download_and_Run
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

```bash
$ java -version
java version "17.0.8" 2023-07-18 LTS
Java(TM) SE Runtime Environment (build 17.0.8+9-LTS-211)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.8+9-LTS-211, mixed mode, sharing)

$ find . -name *.java | xargs javac

$ cat config.xml
```

```xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
  <module name="JavadocPackage"/>
</module>
```

```bash
$ cat A/mypackage/A.java
```

```java
package mypackage;

class A {

}
```

```bash
$ cat A/mypackage/package-info.java 
```

```java
package mypackage;
```

```bash
$ cat B/mypackage/B.java
```

```java
package mypackage;

class B {

}
```

```bash
$ RUN_LOCALE="-Duser.language=en -Duser.country=US"
$ find . -name *.java | xargs java $RUN_LOCALE -jar checkstyle-10.12.1-all.jar -c config.xml
Starting audit...
[ERROR] <XXX>\.\B\mypackage\B.java:1: Missing package-info.java file. [JavadocPackage]
Audit done.
Checkstyle ends with 1 errors.
```

---

When a package is split into two or more folders, the _JavadocPackage_ module reports missing _package-info.java_ for java files not in the same folder as the _package-info.java_.

Since the package is properly documented, _and_ Checkstyle has read the package-info.java, I would expect no error to be reported there.

It seems that [JavadocPackageCheck](https://github.com/checkstyle/checkstyle/blob/bb64c20cbcf6e543b297b6e809f379bd8746b5e7/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocPackageCheck.java#L116) is simply checking for each directory if a _package-info.java_ exists in the directory, instead of (more complicated) mapping all _package-info.java_ to Java packages, and then checking each package.

---

**Comment by serianox** [comment]
Thanks @romani for answering so fast. 🙂 

I assume you are referencing the following limitation? So yeah, by design Checkstyle can't or won't keep track of packages of all java files that have been seen.

>  You cannot see the contents of other files. You have access to the content of one file only during all Checks execution. All files are processed one by one. 

I've indeed started using suppress to remove false positives. 👍🏻

**Comment by romani** [comment]
@serianox, please share suppression config to let others reuse your achievement.

**Comment by serianox** [comment]
@romani I'm currently on holiday, so I can't copy/paste my work conf. 😅 

My solution basically involves [SuppressWithNearbyCommentFilter](https://checkstyle.org/filters/suppresswithnearbycommentfilter.html#SuppressWithNearbyCommentFilter). I simply write this comment at the end of the file which triggers the occurrence of the false positive. Note that the file _may_ change between versions of Checkstyle, or the JVM used.

```xml
<module name="SuppressWithNearbyCommentFilter">
  <property name="commentFormat" value="(?i)checkstyle.suppressJavadocPackage"/>
  <property name="checkFormat" value="javadocPackage"/>
  <property name="influenceFormat" value="-99999"/>
</module>
```

```java
// checkstyle.suppressJavadocPackage
```

**Comment by serianox** [comment]
@yannleglise It's a case insensitive match, to avoid searching why the filter doesn't work if someone put a capital at the wrong place in the suppression comment.
