### ISSUE TITLE
Local build failure downloading jme3-natives due to  expired certificate?

### ISSUE THREAD

**Issue by andygibson** [checkstyle/checkstyle#13476]
For the last couple of days, I'm getting local build failures : 

```
Download natives from https://objects.jmonkeyengine.org/native-snapshots/3d49531fb98c8e41bf39d6a2167d5c3b95557148/jme3-natives.zip 
to /home/xxx/xxx/xxx/jmonkeyengine/build/3d49531fb98c8e41bf39d6a2167d5c3b95557148-natives.zip

FAILURE: Build failed with an exception.

* Where:
Build file '/home/xxx/xxx/xxx/jmonkeyengine/build.gradle' line: 219

* What went wrong:
Execution failed for task ':getNativesZipFile'.
> javax.net.ssl.SSLHandshakeException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed

```
I tried the link in a browser and I get a security error, saying the cert expired 2 days ago. From my browser:
```
This server could not prove that it is objects.jmonkeyengine.org; its security certificate expired 2 days ago. This may be caused by a misconfiguration or an attacker intercepting your connection. 
```

Is this an issue for anyone else?

**Comment by rnveach** [comment]
I get the same error for `https://objects.jmonkeyengine.org` but this is not our domain and there is nothing we can do about it. Checkstyle library does not use any `jmonkey`.

**Comment by romani** [comment]
Looks like spam or big mistake in repo to report issue.

**Comment by andygibson** [comment]
Oh geez, sorry guys - Too many github windows, I reported the problem on the wrong project.  I'm working on integrating checkstyle into JmonkeyEngine so I had some of your github windows open. I'll go repost on their project.

Sorry about that! 

Cheers,

Andy
