### ISSUE TITLE
allowMissingPropertyJavadoc can't working

### ISSUE THREAD

**Issue by iven98** [checkstyle/checkstyle#13487]
checkstyle.xml
```xml
        <module name="MissingJavadocMethod">
            <property name="allowedAnnotations" value="Override,Deprecated"/>
            <property name="allowMissingPropertyJavadoc" value="true"/>
        </module>
```
![image](https://github.com/checkstyle/checkstyle/assets/44129442/1229e3d9-90ac-4d15-b43f-7ed1589b0f89)
version:10.12.1

**Comment by romani** [comment]
@iven98 , please strictly follow issue template

**Comment by iven98** [comment]
sorry,I need to be pointed out that no matter how I set it, the constructor method will always be prompted that there is a lack of comments.

**Comment by iven98** [comment]
version:10.12.1
