### ISSUE TITLE
Create templates from xdocs

### ISSUE THREAD

**Issue by stoyanK7** [checkstyle/checkstyle#13498]
From https://github.com/checkstyle/checkstyle/pull/13423#discussion_r1280676726

> If that is kind of automate-able, please migrate all, I will merge quickly.
It will be easily review as they should be no diff (except escaping and indentation maybe)

The purpose of this issue is to convert all xdocs to templates. This means copying the xdoc as `.xml.template`. After running `mvn clean verify`, I expect some characters inside `source`/`code` tags ,etc.. to be escaped but no indentation to be broken.

This will be done in chunks per category - annotations, block, coding, naming, etc...

- [x] [Annotations](https://checkstyle.sourceforge.io/checks/annotation/index.html)
- [x]    [Block Checks](https://checkstyle.sourceforge.io/checks/blocks/index.html)
- [x]    [Class Design](https://checkstyle.sourceforge.io/checks/design/index.html)
- [x]    [Coding-1](https://checkstyle.sourceforge.io/checks/coding/index.html)
- [x]    [Coding-2](https://checkstyle.sourceforge.io/checks/coding/index.html)
- [x]    [Headers](https://checkstyle.sourceforge.io/checks/header/index.html)
- [x]    [Imports](https://checkstyle.sourceforge.io/checks/imports/index.html)
- [x]    [Javadoc Comments](https://checkstyle.sourceforge.io/checks/javadoc/index.html)
- [x]    [Metrics](https://checkstyle.sourceforge.io/checks/metrics/index.html)
- [x]    [Miscellaneous](https://checkstyle.sourceforge.io/checks/misc/index.html)
- [x]    [Modifiers](https://checkstyle.sourceforge.io/checks/modifier/index.html)
- [x]    [Naming Conventions](https://checkstyle.sourceforge.io/checks/naming/index.html)
- [x]    [Regexp](https://checkstyle.sourceforge.io/checks/regexp/index.html)
 - [x]   [Size Violations](https://checkstyle.sourceforge.io/checks/sizes/index.html)
- [x]    [Whitespace](https://checkstyle.sourceforge.io/checks/whitespace/index.html)
- [x] [Filters](https://checkstyle.sourceforge.io/filters/index.html)
- [x] [File Filters](https://checkstyle.sourceforge.io/filefilters/index.html)

**Comment by nrmancuso** [comment]
Closed via #13499

**Comment by nrmancuso** [comment]
@stoyanK7 two questions:

1. What is left to do here?
2. Do we have a ticket to migrate examples in templates to generated content?

**Comment by stoyanK7** [comment]
@nrmancuso This one can be closed. I checked and ticked off the remaining categories. I am focusing on #13100
