### ISSUE TITLE
Indentation on annotation parameters is wrong

### ISSUE THREAD

**Issue by krzyk** [checkstyle/checkstyle#1349]
When using `<property name="tabWidth" value="4"/><module name="Indentation"/>`, during build checkstyle 6.8.1 complains about:
```
    @Cascade(
        org.hibernate.annotations.CascadeType.DELETE_ORPHAN
    )
```
with:
```
ClickConfig.java:77: ')' have incorrect indentation level 4, expected level should be 8.
```

But it should accept such formatting as the right parenthes closes a block that started on indentation level 4, so it should also be on 4, not on 8.

**Comment by romani** [comment]
issue is partly addressed in referenced fixed , final fix will be at #2795.
