### ISSUE TITLE
Remove from EmptyLineSeparator documentation attention note about no xpath suppression support 

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#13506]
Detected at https://github.com/checkstyle/checkstyle/issues/8179#issuecomment-1663613128

warning 

>ATTENTION: violations from multiple empty lines cannot be suppressed via XPath: [#8179](https://github.com/checkstyle/checkstyle/issues/8179)

Should be removed from the documentation
https://checkstyle.org/checks/whitespace/emptylineseparator.html#EmptyLineSeparator

-----

We need to recheck why CI job for validation of presence in code closed tickets did not catch it.

**Comment by relentless-pursuit** [comment]
If i got it right, it involves removing the warning from the document. Also, as it is not assigned any project, can i initiate a PR on it?

**Comment by romani** [comment]
@relentless-pursuit, please help.
Yes, just remove sentence from xdoc file and javadoc. That is all.
