### ISSUE TITLE
Re-enable ArchUnit Testing

### ISSUE THREAD

**Issue by Kevin222004** [checkstyle/checkstyle#13544]
Temporarily we are skipping the ArchUnit Testing to avoid conflicts in Pitest-Resolution in summer 2023 at https://github.com/checkstyle/checkstyle/pull/13542. 

The issue is opened to re-enable them all at the end of summer.

**Comment by romani** [comment]
Not approved until end of pitest project

**Comment by romani** [comment]
Moved to https://github.com/checkstyle/checkstyle/issues/14053
