### ISSUE TITLE
Update Violation Message in Input files for FallThroughCheck

### ISSUE THREAD

**Issue by Kevin222004** [checkstyle/checkstyle#13552]
**Check** :- https://checkstyle.org/checks/coding/fallthrough.html#FallThrough

We violation messages:
https://github.com/checkstyle/checkstyle/blob/8134680099d82c13c8231ca1b96048a01773a356/src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages.properties#L19-L20

We need update all the Input files to not mention the keyword "fall through" in the violation message

We might use `Fall\ through from the previous branch of the switch statement` (escaping of space) to not let Check to consider it as a violation as it is not matching.

From :-  https://github.com/checkstyle/checkstyle/pull/12966

**Comment by kalpadiptyaroy** [comment]
Hi. I am on it.

**Comment by Kevin222004** [comment]
@kalpadiptyaroy sorry for delay.

Yes you only have to change the message as
`Fall\ through from the previous branch of the switch statement` in all input.
