### ISSUE TITLE
Move CheckUtil#isGetterMethod and CheckUtil#isSetterMethod to MissingJavadocMethodCheck

### ISSUE THREAD

**Issue by nrmancuso** [checkstyle/checkstyle#13596]
Noticed at https://github.com/checkstyle/checkstyle/pull/13555, the only place we use these utility methods is in MissingJavadocMethodCheck, we should just move them there along with associated tests.

**Comment by relentless-pursuit** [comment]
I am on it.

**Comment by rnveach** [comment]
`CheckUtil#getSurroundingAccessModifier` is only used in `JavadocMethodCheck`.

**Comment by romani** [comment]
Better to create separate issue, tests updates make it complicated.

**Comment by rnveach** [comment]
It was just an example, my thoughts are we shouldn't be doing this because of how things from one instance to the next. Current block is an example.

**Comment by nrmancuso** [comment]
Completed via #13607
