### ISSUE TITLE
Use violation messages macro in all templates

### ISSUE THREAD

**Issue by stoyanK7** [checkstyle/checkstyle#13627]
In https://github.com/checkstyle/checkstyle/pull/13423 we implemented the violation messages macro and applied it only to a single file `src/xdocs/checks/whitespace/whitespaceafter.xml.template`.

All module xdocs now have templates and it is time to use this macro everywhere.

I will do this PR in chunks (per category) - annotation, blocks, naming, etc..

- [x] [Annotations](https://checkstyle.org/checks/annotation/index.html)
- [x]     [Block Checks](https://checkstyle.org/checks/blocks/index.html)
 - [x]    [Class Design](https://checkstyle.org/checks/design/index.html)
- [x]     [Coding](https://checkstyle.org/checks/coding/index.html)
- [x]     [Headers](https://checkstyle.org/checks/header/index.html)
- [x]     [Imports](https://checkstyle.org/checks/imports/index.html)
 - [x]    [Javadoc Comments](https://checkstyle.org/checks/javadoc/index.html)
- [x]     [Metrics](https://checkstyle.org/checks/metrics/index.html)
- [x]     [Miscellaneous](https://checkstyle.org/checks/misc/index.html)
- [x]     [Modifiers](https://checkstyle.org/checks/modifier/index.html)
- [x]     [Naming Conventions](https://checkstyle.org/checks/naming/index.html)
- [x]     [Regexp](https://checkstyle.org/checks/regexp/index.html)
- [x]     [Size Violations](https://checkstyle.org/checks/sizes/index.html)
- [x]     [Whitespace](https://checkstyle.org/checks/whitespace/index.html)

**Comment by stoyanK7** [comment]
Macro was applied to all templates.

**Comment by rnveach** [comment]
I am re-opening this issue as it was said it is complete, but it is not.

All remaining changes needed are located at https://github.com/checkstyle/checkstyle/blob/d316b893da935d33736e90321b909f9b72d835d8/config/checkstyle-non-main-files-suppressions.xml#L184-L228
