### ISSUE TITLE
Document ability to use whitespace in array configuration properties

### ISSUE THREAD

**Issue by Bananeweizen** [checkstyle/checkstyle#13650]
All the array based properties in https://checkstyle.org/property_types.html#String.5B.5D are documented to use comma as separator. However, in reality it's rather "whitespace plus comma", which might be related to https://github.com/checkstyle/checkstyle/blob/0dba32b6c8c29977d74af675078501fa8052c10f/src/main/java/com/puppycrawl/tools/checkstyle/AbstractAutomaticBean.java#L375

Being able to use whitespace makes the configuration way more readable, e.g. when listing 30 fully qualified names. Because of the missing documentation I've only discovered this by chance after several years of checkstyle usage now. :)

It would be nice if the documentation of the related array based properties could be updated to reflect the whitespace usage. Especially the examples would benefit from using "a, b, c" instead of "a,b,c".

**Comment by romani** [comment]
From doc:
>The string representation is parsed as a set of comma (',') separated strings.

We can make it `The string representation is parsed as a set of comma (',') separated strings. Extra spaces are allowed.`

And update example config to have a space after comma.

**Comment by Redeem-Grimm-Satoshi** [comment]
Hi @Bananeweizen @romani. I am Redeem Grimm, A Java developer and I'm excited about this project, also new to the community. 

Can I work on this issue?

**Comment by Redeem-Grimm-Satoshi** [comment]
@romani sent a PR

**Comment by nrmancuso** [comment]
closed via #13805

**Comment by nrmancuso** [comment]
@Redeem-Grimm-Satoshi thanks a lot for the update!
