### ISSUE TITLE
Order properties alphabetically in xdocs and javadocs

### ISSUE THREAD

**Issue by stoyanK7** [checkstyle/checkstyle#13668]
Followup from issue https://github.com/checkstyle/checkstyle/issues/13666 / PR https://github.com/checkstyle/checkstyle/pull/13667

The purpose of this issue is to rearrange the properties of modules and remove them from the `MODULES_WITH_UNORDERED_PROPERTIES` suppression list in `XdocsPagesTest`.

If author of PR notice that property description starts with lower character, please update to upper case.
We need to minimize update that will happen by macros usage.

**Comment by romani** [comment]
Let's pause for a bit and get alignment here.

@rnveach , @nrmancuso , do you want to keep ordering where tokens are at the bottom of table ?

I like them to be at the bottom.

**Comment by nrmancuso** [comment]
> I like them to be at the bottom.

I agree. I prefer them to be last since they are often the largest row (most content).

**Comment by romani** [comment]
I remember @rnveach  told somewhere that he also prefers as it is now, tokens are last.

@stoyanK7 , looks like majority are in favor of having custom ordering.

Let's change title of this issue to actually fix property macros implementation.

**Comment by rnveach** [comment]
> I remember @rnveach told somewhere that he also prefers as it is now, tokens are last.

This is how it was when I joined and started the xdoc tests. I continued this behavior since it was how we had it at the time. I am for continuing the order of tokens that the test enforced.

**Comment by rnveach** [comment]
@romani @stoyanK7 What is the difference between this issue and https://github.com/checkstyle/checkstyle/issues/13666 ?

**Comment by romani** [comment]
It was attempted to separate activities of massive updates and actual validation enforcement. Being done in parallel is way quicker than waiting for all to be done at ones.

But after trying to do this, I found that usage of macros is easier approach.

**Comment by romani** [comment]
all are ordered with reference to https://github.com/checkstyle/checkstyle/issues/13666 issue
