### ISSUE TITLE
Assert that properties are ordered alphabetically in xdoc

### ISSUE THREAD

**Issue by stoyanK7** [checkstyle/checkstyle#13666]
As suggested in https://github.com/checkstyle/checkstyle/pull/13407#discussion_r1309128616

We need to rearrange properties in alphabetical order(xdoc and javadoc since they are connected) and add a test for that. This will ease reviews when applying the properties macro to checks.

https://checkstyle.org/checks/annotation/annotationusestyle.html for example, has properties that do not follow alphabetical order:

- elementStyle
- closingParens
- trailingArrayComma

Edit: This issue is only for adding the test with suppressions. I will deal with ordering the properties at https://github.com/checkstyle/checkstyle/issues/13668

Update: almost all are ordered with reference to this issue. #13668 is closed.

**Comment by stoyanK7** [comment]
Do we still want to keep `tokens`/`javadocTokens` at the end or do we want true alphabetical order?

**Comment by romani** [comment]
Let's do alphabetical for now, after migration to macroses it will be easy to change to any alphabetical-special.

**Comment by stoyanK7** [comment]
Already went with alphabetical and `javadocTokens`, `tokens` at the end. Please check #13677

**Comment by romani** [comment]
>This will ease reviews when applying the properties macro to checks.

I found it as not easy, a way easier is to migrate to macros, so ordering is enforcing by macros.
