### ISSUE TITLE
Simplify requirement for what we consider a setter method in ClassAndPropertiesSettersJavadocScraper

### ISSUE THREAD

**Issue by stoyanK7** [checkstyle/checkstyle#13680]
Noticed at https://github.com/checkstyle/checkstyle/pull/13678#issuecomment-1702760681
```
[INFO] Running com.puppycrawl.tools.checkstyle.internal.XdocsPagesTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.181 s <<< FAILURE! -- in com.puppycrawl.tools.checkstyle.internal.XdocsPagesTest
[ERROR] com.puppycrawl.tools.checkstyle.internal.XdocsPagesTest -- Time elapsed: 1.181 s <<< ERROR!
java.lang.NullPointerException
```

The problem was noticed with MatchXpathCheck's `setQuery()`. The current implementation of `isSetterMethod()` returns `false` for that setter. In particular at:
```java
                // Maximum nodes allowed in a body of setter
                final int setterBodySize = 3;
                if (slist != null && slist.getChildCount() == setterBodySize) {
                    final DetailAST expr = slist.getFirstChild();
                    setterMethod = expr.getFirstChild().getType() == TokenTypes.ASSIGN;
                }
```

The `slist` has 4 children:
![Screenshot from 2023-09-01 15-52-07](https://github.com/checkstyle/checkstyle/assets/23459549/3cfd7bd0-1634-4f0b-a38b-aea6abd2cee4)

**Comment by nrmancuso** [comment]
@stoyanK7 let's make setter method validation as dumb as possible, we will catch bad property generation more readily than we will diagnose weird failures.
