### ISSUE TITLE
Use module properties macro in all templates

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#13693]
macros is implemented at https://github.com/checkstyle/checkstyle/issues/13422
we need to use it in all templates

this is example of update we need to make for template files - https://github.com/checkstyle/checkstyle/pull/13681/files#diff-01387dd92ef7af5a9a1f274744b44e12fbeda8302eb79072785f7d6c9d559727L40

`mvn clean test -Dtest=XdocsPagesTest,XdocsJavaDocsTest`

**Comment by romani** [comment]
We can not migrate modules that has tokens as property as xdoc validation demands them to be the last in table. 

But for now macros use simple alphabetical ordering

**Comment by rnveach** [comment]
https://github.com/checkstyle/checkstyle/issues/13666 should be done first for each page before adding the macro to the page. The re-ordering should be a manual process of moving the property to a new position so we are sure the new macro isn't causing issues, as we found one.

**Comment by nrmancuso** [comment]
Current state of migration:
```bash
➜  checkstyle git:(master)  for f in $(find . -name "*.xml.template"); do grep -l "<table>" $f | xargs basename 2>&1 | grep xml.template; done
customimportorder.xml.template
nonemptyatclausedescription.xml.template
writetag.xml.template
missingjavadocmethod.xml.template
summaryjavadoc.xml.template
javadocparagraph.xml.template
javadocstyle.xml.template
javadoctagcontinuationindentation.xml.template
javadoctype.xml.template
javadocvariable.xml.template
missingjavadoctype.xml.template
requireemptylinebeforeblocktaggroup.xml.template
singlelinejavadoc.xml.template
npathcomplexity.xml.template
javancss.xml.template
commentsindentation.xml.template
finalparameters.xml.template
orderedproperties.xml.template
todocomment.xml.template
trailingcomment.xml.template
uncommentedmain.xml.template
uniqueproperties.xml.template
arraytypestyle.xml.template
newlineatendoffile.xml.template
translation.xml.template
avoidescapedunicodecharacters.xml.template
indentation.xml.template
classmemberimpliedmodifier.xml.template
redundantmodifier.xml.template
interfacememberimpliedmodifier.xml.template
catchparametername.xml.template
illegalidentifiername.xml.template
packagename.xml.template
patternvariablename.xml.template
recordcomponentname.xml.template
recordtypeparametername.xml.template
abbreviationaswordinname.xml.template
constantname.xml.template
membername.xml.template
methodname.xml.template
parametername.xml.template
abstractclassname.xml.template
localvariablename.xml.template
classtypeparametername.xml.template
interfacetypeparametername.xml.template
localfinalvariablename.xml.template
methodtypeparametername.xml.template
lambdaparametername.xml.template
regexp.xml.template
regexpmultiline.xml.template
regexponfilename.xml.template
regexpsingleline.xml.template
regexpsinglelinejava.xml.template
```

**Comment by relentless-pursuit** [comment]
Is there any change of the issues arising out of the migration be a part of GSOC 2024?

**Comment by nrmancuso** [comment]
> Is there any change of the issues arising out of the above migration be a part of GSOC 2024?

Anything is possible! We will start planning GSOC soon, I would expect to have some project to complete documentation automation. Thanks for your interest @relentless-pursuit  :)

**Comment by relentless-pursuit** [comment]
> > Is there any change of the issues arising out of the above migration be a part of GSOC 2024?
> 
> Anything is possible! We will start planning GSOC soon, I would expect to have some project to complete documentation automation. Thanks for your interest @relentless-pursuit :)

Looking forward to it. Thank you.

**Comment by romani** [comment]
This part is very tricky even for maintainers, too much old problems pop up as reminder about themselves, solutions are not trivial as requiring consideration of a lot historical context, to distinguish typo and design problem that can not be fixed to avoid breaking compatibility changes.
