### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Bananeweizen** [checkstyle/checkstyle#13735]
https://checkstyle.org/checks/javadoc/invalidjavadocposition.html#InvalidJavadocPosition

> This comment looks like javadoc but it at an invalid location.

* but it _is_ at an...
* Javadoc should be uppercase here (only the javadoc tool is lowercase, the documentation itself is uppercase)

**Comment by Clint-Mathews** [comment]
Hey @Bananeweizen can I pick this up?

**Comment by Bananeweizen** [comment]
@Clint-Mathews sure. please be aware I'm not a project member, just the author of the issue.

**Comment by romani** [comment]
@Clint-Mathews, please help us, referenced text in our GitHub repo, just search and change it.

**Comment by Clint-Mathews** [comment]
@romani Raised an [MR](https://github.com/checkstyle/checkstyle/pull/13738) with fix!

**Comment by romani** [comment]
Fix is merged.

**Comment by romani** [comment]
@Clint-Mathews , thanks a lot for help, please help us to fix more.
