### ISSUE TITLE
Add Examples Macro Support to All Checks

### ISSUE THREAD

**Issue by nrmancuso** [checkstyle/checkstyle#13732]
We missed some checks in the Examples Macro migration:

https://github.com/checkstyle/checkstyle/blob/8e8962a365fdafec1b3e5fade58784a7fe0e32c7/config/checkstyle-non-main-files-suppressions.xml#L170-L204

We need to add these macros to the associated templates and remove the supressions in the above permalink. We are not ready to migrate filters yet.

You can see an example of how to do this at https://github.com/checkstyle/checkstyle/commit/beeba16536bbcbc054a5f25e50618ef866282742#diff-433fa4ac5c3dc207aa39c0f5fe8756054c91feb6af98036a3a872d94d8ee6b47.

**Comment by nrmancuso** [comment]
@relentless-pursuit can you help with this one?

**Comment by relentless-pursuit** [comment]
> @relentless-pursuit can you help with this one?

Sure, I will try to raise a PR on the same.

**Comment by relentless-pursuit** [comment]
@nrmancuso i couldn't find any example files of `importcontrol.xml.template`. can you suggest me how to implement macros for `importcontrol.xml.template`?
