### ISSUE TITLE
MissingDeprecated shows unclear message on not closed html tag

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#13745]
I have read check documentation: https://checkstyle.org/checks/annotation/missingdeprecated.html#MissingDeprecated
I have downloaded the latest checkstyle from: https://checkstyle.org/cmdline.html#Download_and_Run
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

```bash
rivanov@p5510:/var/tmp$ cat Test.java 
public class Test {
/**
 * @deprecated
 * <p>
 */
@Deprecated
public static final int CONST = 12; // violation, tight HTML rules not obeyed
}

$ cat config.xml 
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN" 
     "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name="Checker">
  <module name="TreeWalker">
    <module name="MissingDeprecated">
      <property name="violateExecutionOnNonTightHtml" value="true"/>
    </module>
  </module>
</module>

$ java -jar checkstyle-10.11.0-all.jar -c config.xml Test.java
Starting audit...
[ERROR] /var/tmp/Test.java:4: javadoc.unclosedHtml [MissingDeprecated]
Audit done.
Checkstyle ends with 1 errors.
```

expected message https://github.com/checkstyle/checkstyle/blob/a95d8ef412c8709242beff68b5441279b1bc9081/src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages.properties#L27

**Comment by nrmancuso** [comment]
@romani it might make more sense to migrate this check to javadoc checks package than to leak javadoc messages to annotation package. This check always checks javadoc of declaration, there is no way to turn this off, so I would consider it to be a javadoc check. Also - this check extends AbstractJavadocCheck.

**Comment by nrmancuso** [comment]
Looks like this is the only javadoc check that is not in the javadoc checks package:
```
➜  checkstyle git:(master) ag -lQ "extends AbstractJavadocCheck" | grep "/checks/"
src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/MissingDeprecatedCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocBlockTagLocationCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AtclauseOrderCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMissingWhitespaceAfterAsteriskCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocParagraphCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/NonEmptyAtclauseDescriptionCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/RequireEmptyLineBeforeBlockTagGroupCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SingleLineJavadocCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMissingLeadingAsteriskCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SummaryJavadocCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheckTest.java
```

**Comment by nrmancuso** [comment]
It seems like it was a design mistake to print parser errors as violations to all checks. Maybe we should remove such abilities from all javadoc checks and make a check specifically for unclosed html tags. `MissingDeprecated` should not care about unclosed html tags.

**Comment by romani** [comment]
Converted recently to javadoc AST https://github.com/checkstyle/checkstyle/issues/4983

**Comment by relentless-pursuit** [comment]
While looking into `annotation/message.properties`, i came across 
`javadoc.missed.html.close=Javadoc comment at column {0} has parse error. Missed HTML close tag ''{1}''. Sometimes it means that close tag missed for one of previous tags.`

Can the above be used as it already exists rather than trying to use `javadoc.UnclosedHtml`?

**Comment by romani** [comment]
We should not use different messages name/key as we have single parser and it use special message key/name.

Fact that we a package based for looks up by key is unfortunate gap in design.

**Comment by nrmancuso** [comment]
Link to property: https://github.com/checkstyle/checkstyle/blob/71a1a358be681eea74099a51ef02ebde2ee0d55b/src/main/resources/com/puppycrawl/tools/checkstyle/checks/annotation/messages.properties#L13

The only usage of this property (via IDEA static analysis) is in JavadocDetailNodeParser: https://github.com/checkstyle/checkstyle/blob/c9190ed2fbb919beafeb992bbce98912c6fa8717/src/main/java/com/puppycrawl/tools/checkstyle/JavadocDetailNodeParser.java#L63

The message key we are looking for is declared in AbstractJavadocCheck, where it is "overridden", and only used in tests: https://github.com/checkstyle/checkstyle/blob/c9190ed2fbb919beafeb992bbce98912c6fa8717/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheck.java#L60


The unclosed tag message key is coming from here: https://github.com/checkstyle/checkstyle/blob/c9190ed2fbb919beafeb992bbce98912c6fa8717/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheck.java#L322

We should probably just use `MSG_JAVADOC_MISSED_HTML_CLOSE`, seems like a miss on our part. 

@romani @rnveach thoughts?

**Comment by romani** [comment]
We discuss to just reuse of message. It will stay as violation.

**Comment by nrmancuso** [comment]
Third option: do not allow abstract check classes to log violations at all, and move this to a separate, single check.

**Comment by romani** [comment]
This was and idea that we discussed a lot and looks like agreed. Only final Check explicitly define what messages it can emit. All abstract classes get messages in Ctor.

-----

For now I recommend to choose from above two.

**Comment by romani** [comment]
I ok to do `reuse MSG_JAVADOC_MISSED_HTML_CLOSE`. @nrmancuso , looks like too.

@rnveach , do you agree?

**Comment by rnveach** [comment]
> do you agree?

https://github.com/checkstyle/checkstyle/issues/13745#issuecomment-1729592472
> I don't really agree with swapping a normal violation with a parse error unless there is some reason. Why is there this difference between the 2?

**Comment by romani** [comment]
I thought I answered by post bellow.

ok, I went deeper:
We hard parse error and soft violation for incorrect html.
Parse error is covered by:
https://github.com/checkstyle/checkstyle/blob/ccc12eb6d7f6c8e0876077e7883cf8f59a541a37/src/test/java/com/puppycrawl/tools/checkstyle/DetailNodeTreeStringPrinterTest.java#L193-L203
for case:
https://github.com/checkstyle/checkstyle/blob/ccc12eb6d7f6c8e0876077e7883cf8f59a541a37/src/test/resources/com/puppycrawl/tools/checkstyle/detailnodetreestringprinter/InputDetailNodeTreeStringPrinterWrongHtmlTagOrder.javadoc#L1

Violation: for cases like `* <p>`

So conceptually they are two different problem and can end up with two different messages and different amount of parameters.
It is better to keep them separate.

I am calling back my vote.
I am for `add MSG_UNCLOSED_HTML_TAG to annotation package properties`

@nrmancuso , please share your vote and thoughts.

**Comment by nrmancuso** [comment]
> I am calling back my vote.
I am for add MSG_UNCLOSED_HTML_TAG to annotation package properties

Let’s also create an issue to remove declaration of other message from AbstractJavadocCheck

**Comment by romani** [comment]
> Let’s also create an issue to remove declaration of other message from AbstractJavadocCheck

we hide all parser mesages by field of abstract check:

https://github.com/checkstyle/checkstyle/blob/c525c6732e2c1f15bd3f85f943770c649f1ab775/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheck.java#L59-L72

**Comment by relentless-pursuit** [comment]
Hi @romani, can we add a hacktober fest label to this issue?

**Comment by romani** [comment]
@relentless-pursuit , done.
there is another label `hacktoverfest-accepted`, I am not sure why it exists, let us know what label we should use

**Comment by relentless-pursuit** [comment]
> @relentless-pursuit , done. there is another label `hacktoverfest-accepted`, I am not sure why it exists, let us know what label we should use

I am not sure either. Let's see. If this PR get's merged, and if see my count increasing, maybe this works. But, thanks for the update.

**Comment by romani** [comment]
Fix is merged by @https://github.com/checkstyle/checkstyle/pull/13808#event-10520685545
