### ISSUE TITLE
infra: actionlint bad yaml

### ISSUE THREAD

**Issue by Bananeweizen** [checkstyle/checkstyle#13765]
https://github.com/checkstyle/checkstyle/blob/ccc12eb6d7f6c8e0876077e7883cf8f59a541a37/.github/workflows/actionlint.yml#L9 should be an array, not just a string

![grafik](https://github.com/checkstyle/checkstyle/assets/406876/dacac97b-1d47-4631-b84b-bbd1c498c0a8)

**Comment by nrmancuso** [comment]
Link to actions syntax: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpull_requestpull_request_targetbranchesbranches-ignore

@Bananeweizen what tool are you using for schema validation?

**Comment by rnveach** [comment]
This is eclipse. I see the same thing on mine, 2022-06.

**Comment by Bananeweizen** [comment]
@rnveach You should really upgrade more often. You are missing so many new features and bug fixes. I regularly develop on milestone and snapshot releases, and even those are typically quite stable.

**Comment by rnveach** [comment]
I am connected to the version I use at work. I did recently get the 2023-06, but I haven't switched over my personal yet.

**Comment by romani** [comment]
Let's try to fix it if it is not conflicts with some other validation.

**Comment by AayushSaini101** [comment]
@romani Can I take this issue? I read the documentation, We can mention master and * as mentioned in the official doc

**Comment by Bananeweizen** [comment]
BTW: eclipse-cs meanwhile has a copy of this action, with a fix applied already: https://github.com/checkstyle/eclipse-cs/blob/master/.github/workflows/actionlint.yml#L10 However, since it has not yet run in the eclipse-cs repo, I can't say anything about whether it works correctly there. :)

**Comment by romani** [comment]
@AayushSaini101 , you can take any approved issue, just recheck that nobody made comment "I am on it" before, and do comment "I am on it", and send fix.

**Comment by AayushSaini101** [comment]
> @AayushSaini101 , you can take any approved issue, just recheck that nobody made comment "I am on it" before, and do comment "I am on it", and send fix.

Thanks @romani I am on it

**Comment by romani** [comment]
Fix is merged
