### ISSUE TITLE
Enforce Linux Style End-of-Line (LF instead of CRLF) in all XML files for windows environment.

### ISSUE THREAD

**Issue by kalpadiptyaroy** [checkstyle/checkstyle#13770]
Detected in issue #11816 within PR #13696.

When we perform `mvn clean verify` then `XdocsPagesTest` gets executed. Within the test the following pre-condition causes regeneration of `.xml` files.

**Refer to this line.**

https://github.com/checkstyle/checkstyle/blob/c525c6732e2c1f15bd3f85f943770c649f1ab775/src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java#L296-L299

**What is happening now?**
The problem is when the above line gets executed this regeneration happens and in an windows environment the End-Of-Line used is `CRLF` by default. This causes a difference to git version control and the build process fails - due to constraints of `validation.cmd`.

**What is expected?**
We have to find out a way to make sure when `.xml` files are regenerated they have `LF` End-Of-Line instead of `CRLF` so that no further git diff arises and post execution of test cases the validation.cmd doesn't end up with an error.

**[Update]** - Issue has been raised at Apache Doxia for ability to configure new-line character. https://issues.apache.org/jira/browse/DOXIA-707

**Comment by Bananeweizen** [comment]
you probably want to configure https://www.git-scm.com/docs/gitattributes#_eol for the path matching the file(s) with those line endings

**Comment by kalpadiptyaroy** [comment]
@Bananeweizen. Yes! Even I was going through this article below.
https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings

I am planning to add `text eol=lf` to `.gitattributes` and then see what's the reaction of CI.

**Comment by rnveach** [comment]
Git Attributes is already set.

https://github.com/checkstyle/checkstyle/blob/master/.gitattributes#L2

**Comment by romani** [comment]
Git attributes are for checkout of sources, we have problem that after checkout we execute java test and it generates files that we track git with windows end lining, but git expect them to be as on checkout - Linux style.

**Comment by rnveach** [comment]
> Git attributes are for checkout of sources, we have problem that after checkout 

I thought git attributes applies to all git commands, not just checkout. I would expect it to apply to git status.

https://git-scm.com/book/en/v2/Customizing-Git-Git-Attributes
> Using attributes, you can do things like specify separate merge strategies for individual files or directories in your project, tell Git how to diff non-text files, or have Git filter content before you check it into or out of Git

**Comment by romani** [comment]
Ok, git will expect \n but after some execution files becomes \r\n. There will be diff.
We try to play with it, but do not see a way to make it

**Comment by michael-o** [comment]
While I don't understand why all files need to be `LF`, you can address this issue here:
https://github.com/checkstyle/checkstyle/blob/c2f5568c26e22b3d40f16346f89cf677371e0ac8/src/main/java/com/puppycrawl/tools/checkstyle/site/XdocsTemplateSink.java#L49-L52. Provide a writer which prints `\n` only.

**Comment by rnveach** [comment]
@michael-o This issue is already being worked on and first details issue with version control failing on windows.
PR in works is at https://github.com/checkstyle/checkstyle/pull/13774 .

**Comment by nrmancuso** [comment]
Closed via #13774 

@kalpadiptyaroy can we close doxia issue?

**Comment by kalpadiptyaroy** [comment]
> Closed via #13774 
> 
> @kalpadiptyaroy can we close doxia issue?

Sure. We have found a permanent solution to configure a custom new line without the need to modify doxia.
So let's close the doxia issue.

**Comment by rnveach** [comment]
The PR did not modify any permanent files. `XdocsTemplateSink` is a temporary file and can be removed when we are done looking over xdoc changes.

**Comment by nrmancuso** [comment]
@romani are we good to close this? Or should we wait for rebase and green CI in other PR?

**Comment by kalpadiptyaroy** [comment]
Wait till rebase - I will ping on success

**Comment by kalpadiptyaroy** [comment]
Closing this issue as #13696 is merged.
