### ISSUE TITLE
Fix typo in Indentation check for word 'initialisation'

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#13783]
from https://github.com/checkstyle/checkstyle/pull/13778#discussion_r1336536013

fix typo in Indentation check for word `initialisation`
should be `initialization`

consider https://sapling.ai/usage/initialize-vs-initialise

**Comment by romani** [comment]
lines to fix: https://github.com/search?q=repo%3Acheckstyle%2Fcheckstyle%20initialisation&type=code

**Comment by aarishshahmohsin** [comment]
Can I work on this issue?

**Comment by Redeem-Grimm-Satoshi** [comment]
@romani should `initialisation` be replaced with `initialize` to be clear?

**Comment by romani** [comment]
initialisation
should be initialization

**Comment by suniti0804** [comment]
I am on it

**Comment by nrmancuso** [comment]
@shubham562004 looks like we already fixed this issue and forgot to close it. @romani please confirm that https://github.com/checkstyle/checkstyle/pull/13912 closes this.

**Comment by shubham562004** [comment]
@nrmancuso thanks for letting me know.
i am completly beginner to open source.
I am looking forward to contribute more in this project .
But i want know that which tech stack or technologies should i know to understand and solve issues.

**Comment by nrmancuso** [comment]
Carefully read through https://checkstyle.org/beginning_development.html, take some time to look around, then pick up some issues with "GSOC first issue" label. Thanks for your interest!

**Comment by shubham562004** [comment]
Ok ,Thanks for information.

**Comment by romani** [comment]
Issue is fixed by https://github.com/checkstyle/checkstyle/pull/13912
