### ISSUE TITLE
Fix Violation messages in Xdocs of AnnotationLocation

### ISSUE THREAD

**Issue by relentless-pursuit** [checkstyle/checkstyle#13790]
I have read check documentation: https://checkstyle.sourceforge.io/checks/annotation/annotationlocation.html

While trying to resolve the issue for AnnotationLocationExamplesTest, I was going through the documentation and the codebase. And, i found that in Example2.txt, despite the module configuration ensuring some restrictions, there is no violation registered in the examples. 

Use the following configuration to allow multiple annotations on the same line:

```
<module name="AnnotationLocation">
  <property name="allowSamelineMultipleAnnotations" value="true"/>
  <property name="allowSamelineSingleParameterlessAnnotation"
    value="false"/>
  <property name="allowSamelineParameterizedAnnotation" value="false"/>
</module>
```

Example to allow any location multiple annotations:

```
@NotNull private boolean field1; //ok
@Override public int hashCode() { return 1; } //ok
@NotNull //ok
private boolean field2;
@Override //ok
public boolean equals(Object obj) { return true; }
@Mock DataLoader loader; //ok
@SuppressWarnings("deprecation") DataLoader loader; //ok
@SuppressWarnings("deprecation") public int foo() { return 1; } //ok
@NotNull @Mock DataLoader loader; //ok
```

How is `@NotNull private boolean field1; //ok` not a violation as the config says   
```
<property name="allowSamelineSingleParameterlessAnnotation"
    value="false"/>
```

Similarly, i feel there are other violations in this code as per the config.

**Comment by relentless-pursuit** [comment]
Upon minute reading of the documentation, i had missed out some exceptions like @Override, local variables and the issue doesn't hold true.

**Comment by nrmancuso** [comment]
@relentless-pursuit thanks for following up!

**Comment by romani** [comment]
It makes sense to put in comment as explanation, if you were confused, 50% of world will be confused also
