### ISSUE TITLE
windows folder case insensitive issue

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#1382]
Inside the folder "src/it/resources/com/google/checkstyle/test/chapter5naming" there are 2 folders with the same, case insensitive name which is causing issues with windows. "rule521packageNames" and "rule521packagenames" are the same letters/numbers but one has a captial N and the other has a lowercase n. Windows doesn't allow these 2 folders to exist in the same parent.

**Comment by romani** [comment]
on completion, we need to use http://www.appveyor.com/ , configuration example - http://www.yegor256.com/2015/01/10/windows-appveyor-maven.html

**Comment by romani** [comment]
first steps of windows build CI - https://ci.appveyor.com/project/romani/checkstyle
as it become stable I will move it to - checkstyle/checkstyle .

any further steps for build success are welcome.
we could continue after #1389 is fixed.

**Comment by romani** [comment]
https://github.com/checkstyle/checkstyle/tree/master/src/it/resources/com/google/checkstyle/test/chapter5naming

There is :
rule521_packagenames
rule521$packagenames
rule521packagenames
rule521packageNamesCamelCase

most likely you look at old sources.

**Comment by romani** [comment]
That URL https://ci.appveyor.com/project/romani/checkstyle will official till I figureout how to detach it from my personal account.

Windows build is passing.
