### ISSUE TITLE
Ability to extend/override an existing configuration (for reusing Sun's style, Google's style)

### ISSUE THREAD

**Issue by rkrisztian** [checkstyle/checkstyle#13828]
I'd like to be able to import Google's style configuration into my custom configuration, but I can't find a way to do this. A related thread I found is https://github.com/checkstyle/checkstyle/issues/4484, I have the same goal: making updates to Google's style easier in the future. If this is not possible, then I'm wondering why no support has been added so far, the idea came up years ago, and without it my work is more cumbersome.

(By the way, have you ever considered switching to some other language for the configuration file? Ideally no sane person codes in XML anymore, unless limited by legacy reasons.)

**Comment by rnveach** [comment]
This issue has been brought up many times. Another instance of it is at https://github.com/checkstyle/checkstyle/issues/2873 . I am sure there may be others.

There is an option like https://checkstyle.org/config_system_properties.html#Enable_External_DTD_load but this requires you to be able to modify the original config, and you can't do that with our styles. I also think it may also be considered a security issue using it.

Main blockers are coming up with the requirements on how this should be done, admin agreement on how to proceed, and someone actually implementing it.

**Comment by rkrisztian** [comment]
Sorry for bringing it up one too many times, feel free to resolve this as duplicate.

I checked [Enable_External_DTD_load](https://checkstyle.org/config_system_properties.html#Enable_External_DTD_load), thanks for the idea, but my use case is different, where I would have my own styles and import the google style rules to in a way that I don't need to modify the original release (the XML file Google distributes). I would just treat Google's XML like a build dependency where we can easily set the version if we want to update the file to a new release.

**Comment by rnveach** [comment]
No worries.

> the XML file Google distributes

Just to clarify, if you are referring to the Google config that comes with Checkstyle ( https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/google_checks.xml ) , this is not created by Google.

**Comment by rnveach** [comment]
Closing as duplicate. I recommend following other issue or commenting you are looking for it to be done too.
