### ISSUE TITLE
Convert Parent Modules to Macro

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#13829]
I couldn't find an issue for this, so I am creating it.

Suppressions at https://github.com/checkstyle/checkstyle/blob/d316b893da935d33736e90321b909f9b72d835d8/config/checkstyle-non-main-files-suppressions.xml#L178-L182 need to be removed and we need to convert plain text in parent section to use our macro.

**Comment by AayushSaini101** [comment]
I am on it. @rnveach Can you explain a little bit "we need to convert plain text in parent section to use our macro" this process ?

**Comment by rnveach** [comment]
It is similar to 766360f8b25c20c700667560f6c607d226e88f01

**Comment by romani** [comment]
https://github.com/checkstyle/checkstyle/pull/13831

**Comment by romani** [comment]
@AayushSaini101 , please be aware that I fixed it at https://github.com/checkstyle/checkstyle/pull/13831
