### ISSUE TITLE
New check: Check annotation elements for presence and/or presence of an element's value

### ISSUE THREAD

**Issue by Mmuzaf** [checkstyle/checkstyle#13864]
I want to enforce a check of all annotations in the source code for the presence of certain elements they have. A good example there is the `@Deprecated` annotation, which has the "since" element and we want to make this element to be present with its non-default value for all annotations in the source code. 

I have checked the documentation to find out how to solve this problem, but haven't found a good solution to:
- custom annotations - this probably solves the problem, but doesn't look like a generic solution for all similar cases;
- AnnotationUseStyle - doesn't have configurations of a requested target;
- RegexpSinglelineJava - this can cause a lot of false positives in comments, and requires maintaining this type of exclusion;
- ParameterNumberCheck - it seems to have only the maximum limit of the parameters;

Do we want to add something similar to MissingDeprecate,  or is there another good solution for the case described above? I've also gone through the issues here as well and haven't found anything similar.

**Comment by nrmancuso** [comment]
I think that MatchXPath check is your best bet, if you want to provide some example code we can help you to create a suitable configuration.  You can also include some of the other annotations that you use and we can work those in as well.

**Comment by Mmuzaf** [comment]
@nrmancuso thank you for your response! I'll take a look at the `MatchXPath`.

#### A couple of examples.

```java
// OK

/**
 * @deprecated it is replaced by {@link #hasImprovedMinMax()} since 'nc' and to be completetly removed since 'oa'
 */
@Deprecated(since = "5.0")
public abstract boolean hasAccurateMinMax();
```

```java
// OK

@Deprecated(since = "4.0") public String getAllEndpointStates();
@Deprecated(since = "5.0") public String getAllEndpointStatesWithResolveIp();
```

```java
// NOT OK

/**
 * Dropped tasks for small message TCP Connections
 */
@Deprecated()
public Map<String, Long> getSmallMessageDroppedTasks();
```

**Comment by nrmancuso** [comment]
@Mmuzaf here you go:

```bash
➜  src cat config.xml 
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
     "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name="Checker">
  <module name="TreeWalker">
    <module name="MatchXpath">
      <property name="query" value="//ANNOTATION[./IDENT[@text='Deprecated']
              and not(./ANNOTATION_MEMBER_VALUE_PAIR/IDENT[@text='since'])]"/>
      <message key="matchxpath.match"
              value="'Deprecated annotation must provide 'since' value."/>
    </module>
  </module>
</module>

➜  src cat Test.java 
public class Test {

    @Deprecated // violation
    public void m1() {}

    @Deprecated() // violation
    public void m2() {}

    @Deprecated(since = "1.9")
    public void m3() {}

    @Deprecated // violation
    public class C {}

    @Deprecated() // violation
    public class D {}

    @Deprecated(since = "1.9")
    public class E {}
}

➜  src javac Test.java 

➜  src java -jar checkstyle-10.12.3-all.jar -c config.xml Test.java
Starting audit...
[ERROR] /home/nick/IdeaProjects/tester/src/Test.java:3:5: Deprecated annotation must provide since value. [MatchXpath]
[ERROR] /home/nick/IdeaProjects/tester/src/Test.java:6:5: Deprecated annotation must provide since value. [MatchXpath]
[ERROR] /home/nick/IdeaProjects/tester/src/Test.java:12:5: Deprecated annotation must provide since value. [MatchXpath]
[ERROR] /home/nick/IdeaProjects/tester/src/Test.java:15:5: Deprecated annotation must provide since value. [MatchXpath]
Audit done.
Checkstyle ends with 4 errors.

```

Should be pretty straightforward to adapt to other annotations by just swapping out the `text` fields.

**Comment by Mmuzaf** [comment]
I've tested it and it works as expected. I'm really grateful for the help, and I hope that this conversation will be indexed by search engines to share it with everyone else :-)

**Comment by romani** [comment]
@Mmuzaf , please share your config it might help user to reuse ready to use best practice.
