### ISSUE TITLE
Standardize Representation of Empty Default Values in Documentation

### ISSUE THREAD

**Issue by relentless-pursuit** [checkstyle/checkstyle#13876]
While working on https://github.com/checkstyle/checkstyle/issues/13859 , it was found inconsistency in representing emploty devaule values. The representation is currently inconsistent, with instances of both `.` and `empty` string being used. To ensure clarity and consistency across the codebase, there should be standardized representation of empty default values in all documentation, and it should be `{@code ""}`.

Here is the diff showcasing the discrepancy in the documentation:

```
diff (-expected +actual):
    @@ -13,7 +13,7 @@
     Property {@code message} - Define the message which is used to notify about violations; if empty then the default message is used. Type is {@code java.lang.String}. Default value is {@code ""}.
     </li>
     <li>
    -Property {@code tokens} - tokens to check Type is {@code java.lang.String[]}. Validation type is {@code tokenSet}. Default value is: .
    +Property {@code tokens} - tokens to check Type is {@code java.lang.String[]}. Validation type is {@code tokenSet}. Default value is: {@code ""}.
     </li>
     </ul>
     <p>
```

**Comment by rnveach** [comment]
> instances of both . and empty 

Where is example of both?

**Comment by rnveach** [comment]
https://checkstyle.org/checks/coding/illegaltokentext.html#Properties

I disagree there is an inconsistency here, atleast on xdoc. Default value is displayed in the form of the type. If you look above at the boolean, there is no quotes around `false`. The rest are some form of string.
Other tokens (things like enum types) that don't have an empty set are not encased in quotes. See https://checkstyle.org/checks/blocks/rightcurly.html#Properties . So you would creating the inconsistency if you only add it for empty tokens.

**Comment by relentless-pursuit** [comment]
> https://checkstyle.org/checks/coding/illegaltokentext.html#Properties
> 
> I disagree there is an inconsistency here, atleast on xdoc. Default value is displayed in the form of the type. If you look above at the boolean, there is no quotes around `false`. The rest are some form of string. Other tokens (things like enum types) that don't have an empty set are not encased in quotes. See https://checkstyle.org/checks/blocks/rightcurly.html#Properties . So you would creating the inconsistency if you only add it for empty tokens.

Okay. Thank you for the references. I am yet to develope a complete understanding on the same. However, the suggestion was came while trying to fix https://github.com/checkstyle/checkstyle/issues/13859. Maybe, the PR i have pushed https://github.com/checkstyle/checkstyle/pull/13875 could have your feedback on what i am doing wrong. Because, i had to change the javadoc comment from `{@code ""}` to `""` to make it work.

**Comment by romani** [comment]
issue is created by request in https://github.com/checkstyle/checkstyle/pull/13875/files
but we found workaround, so I am closing this issue.
