### ISSUE TITLE
Problem with UT coverage for "default" branch on switch(enum)

### ISSUE THREAD

**Issue by ivanov-alex** [checkstyle/checkstyle#1387]
This issue was entered to write down the problem, research performed to find solution and decision so that it can be changed to better in the future.

ImportOrderCheck contains following peace of code in visitToken:
```java
        switch (getAbstractOption()) {
            case TOP:
                // code for top
                ...
            case UNDER:
                // code for under
            default:
                // code for default
```         
getAbstractOption() return enum and case arguments are all options of enum.
As a result, "default" option is never executed affecting UT coverage.

Following options to resolve were reviewed:
1) Change last option to default. Rejected because it will make code less clear. Person who analyses this code in the future will need to review several files (AbstractOptionCheck and ImportOrderOption) to understand which option is processed this way and why (which not very obvious)
2) Change enum dynamically on runtime using reflection. Rejected as a result of investigation, see description on the bottom.
3) Refactor to avoid using enum in switch, use strings (option names) or integers (option ordinal numbers). Rejected because it is significant code change to satisfy coverage plugin (not a good idea).
4) combine default with last option. Rejected because it is not obvious solution and one will try to optimize it later by removing "case UNDER".
```java
            case UNDER:
            default:
                // actions for UNDER option, no actions for default.
```
5) Refactor to if statements. Code will have more brackets and repeating of switch argument, so it will be less elegant comparing to switch. 
6) Suppress warnings for this branch. Rejected because coverage tools cannot suppress lines of codes, only methods for now. See links on the bottom of the message.
Option 5 was chosen as lesser evil. Option 6 will be a good candidate after coverage tools improvement.

##### Reflection Investigation:
Several options were found in the Internet:
1) Reflection approach1 (http://www.javaspecialists.eu/archive/Issue161.html). This article is dated 2008-05-23 and labeled "Java version: Sun JDK 6". 
Outcome: I failed to compile code from it: some classes used are not available in packages in imports section. Looks like it is outdated Java-specific code
2) Reflection approach2. More up-to-date code: http://stackoverflow.com/questions/25355936/aspectj-is-is-possible-to-extend-an-enums-value (originating [Jérôme Kehrli's blog](from http://niceideas.ch/roller2/badtrash/entry/java_create_enum_instances_dynamically))
You can find code on: https://gist.github.com/ivanov-alex/f76bdc6483d14662e188
Outcome: It changes enum succesfully, but it doesn't help. When I run test testCoverDefaultInVisitToken() individually in Eclipse or debug it, it works.
When I run test suite for the check or all tests using "mvn clean verify", it fails with "java.lang.ArrayIndexOutOfBoundsException: 5" on a switch statement.
3) Mock enum using something like Mockito (based on http://stackoverflow.com/questions/5323505/mocking-java-enum-to-add-a-value-to-test-fail-case)
You can find code on: https://gist.github.com/ivanov-alex/e0cc14d3dc6fc1520283

Finally it appeared that problem cannot be solved with reflection due to physical implementation of switches: http://www.benf.org/other/cfr/switch-on-enum.html

##### Coverage links
Problem can not be suppressed due to limitations of cobertura and jacoco.
Cobertura ignore options are applicable to methods only(not by line):
https://github.com/cobertura/cobertura/wiki/Ant-Task-Reference#ignore-method-annotation
https://github.com/cobertura/cobertura/wiki/Coverage-Annotations
jacoco filters are not implemented (ignore options):
https://github.com/jacoco/jacoco/issues/15
https://github.com/jacoco/jacoco/issues/14
https://github.com/jacoco/jacoco/wiki/FilteringOptions

**Comment by romani** [comment]
merged.
