### ISSUE TITLE
NoFinalizer: allow an empty final finalizer to allow for security vulnerability mitigation

### ISSUE THREAD

**Issue by xenoterracide** [checkstyle/checkstyle#13896]
https://checkstyle.org/checks/coding/nofinalizer.html#NoFinalizer

**How it works Now:**

```xml
<?xml version="1.0" ?>
<!DOCTYPE module PUBLIC "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
  "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
  <module name="TreeWalker">
    <module name="NoFinalizer" />
  </module>
</module>
```

```java
public class AccountOperations {

	public AccountOperations() {
		if (!isAuthorized()) {
			throw new SecurityException("You can't access the account");
		}
	}

	public boolean isAuthorized() {
		return false;
	}

	public void transferMoney(double amount) {
		System.out.println("Transferring " + amount + " to beneficiary");
	}

	final protected void finalize() {
		
	}
}
```
```
❯ java -jar checkstyle-10.12.4-all.jar -c config.xml AccountOperations.java
Starting audit...
[ERROR] /tmp/AccountOperations.java:17:9: Avoid using finalizer method. [NoFinalizer]
Audit done.
Checkstyle ends with 1 errors.
```

**Is your feature request related to a problem? Please describe.**

Spotbugs started reporting a security vulnerability

> CT_CONSTRUCTOR_THROW: Be wary of letting constructors throw exceptions.
Classes that throw exceptions in their constructors are vulnerable to Finalizer attacks

> A finalizer attack can be prevented, by declaring the class final, using an empty finalizer declared as final, or by a clever use of a private constructor.

> See [SEI CERT Rule OBJ-11](https://wiki.sei.cmu.edu/confluence/display/java/OBJ11-J.+Be+wary+of+letting+constructors+throw+exceptions) for more information.

That link was down at the time of this writing, however, I found another example (also where I copy pasta-ed my example java) [here](https://self-learning-java-tutorial.blogspot.com/2020/03/finalizer-attack-in-java.html)

**Describe the solution you'd like**

I think that adding the following would be sufficient

```xml
<module name="NoFinalizer">
  <property name="allowEmptyFinal" value="true">
</module>
```

**Comment by rnveach** [comment]
Seems this could also be a check for ensure constructors that throw exceptions must have a final finalizer.

**Comment by romani** [comment]
Can we use xpath filter to suppress this edge case ?
https://checkstyle.org/filters/suppressionxpathsinglefilter.html

**Comment by xenoterracide** [comment]
Can that be easily used to check if a method is empty? Because in all cases of doing this you would only want to do it if the method is final and empty. Anything else should still fail.

**Comment by romani** [comment]
https://checkstyle.sourceforge.io/apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#CLASS_DEF

This is pattern of empty method
```
`--OBJBLOCK -> OBJBLOCK
     |--LCURLY -> {
     `--RCURLY -> }
```

**Comment by xenoterracide** [comment]
To be honest although that's probably a reasonable work around I still think that a feature or something should be implemented.

**Comment by romani** [comment]
I just try to help with workaround while issue is in approval and waiting of some contributor to pickup issue, ...

**Comment by romani** [comment]
@xenoterracide , I read https://wiki.sei.cmu.edu/confluence/display/java/OBJ11-J.+Be+wary+of+letting+constructors+throw+exceptions , ok there is some possibility of users to run something on not fully initialized class to steal some data.
BUT ..... execution runtime of such malicious code already imply that they have access to all, they can even use crazy reflection to get access to all data in JVM, so this protection is not strong protection.

the only way I see it to be dangerous if malicious app send such java class over the net to secure app and it stoles  data from remote JVM and return to malicious app. But whole such approach is very bad from security perspective.

Please help me understand this. If we see that this is crazy edge case that some people need, not all, we would rather use xpath suppression. If audience is big, we can consider Check property for this.

**Comment by xenoterracide** [comment]
Yeah, I was thinking about how realistic this is after I created this issue. If you have the access to do this, in what world do not have the access to do a bunch of other stuff...

 I think I'm probably just going to redesign my code to use more static factories and throw the exceptions in there... But then I'm working on a Greenfield project. Maybe the real question is how many people are going to complain about this after spotbugs updates and starts whining at them.

**Comment by rnveach** [comment]
There does seem to be a way to disable reflection.
https://stackoverflow.com/questions/40218973/java-security-manager-completely-disable-reflection

So for example, this vulnerability could still be an issue if you had a secure, production environment, where you are not in control of the environment's security settings to to re-enable reflection, but could still have enough access to release code to it. Most time vulnerabilities like this are enough for hackers to gain elevated privileges, so its more about closing possible holes for safety than the holes are actually able to be abused.

Realistically, you wouldn't be able to full disable reflection as many general use utilities use it for like injection and configurable modules (like Checkstyle). I don't know Java's security very well, but it is probably a given it can be customized to the specific utilities.

**Comment by romani** [comment]
I vote to just share xpath suppression for this if user want to make finalizers.

This Check is by design prone to manual tuning by suppressions by user. Usage of finalize is sometimes required by design, all this Checks is trying to do is to highlight cases like this to let seniors in team to confirm that it is allowed usage.

**Comment by romani** [comment]
```
public class Test {

  final protected void finalize() {

  }
}

$ java -jar checkstyle-10.12.4-all.jar -t Test.java

COMPILATION_UNIT -> COMPILATION_UNIT [1:0]
`--CLASS_DEF -> CLASS_DEF [1:0]
    |--MODIFIERS -> MODIFIERS [1:0]
    |   `--LITERAL_PUBLIC -> public [1:0]
    |--LITERAL_CLASS -> class [1:7]
    |--IDENT -> Test [1:13]
    `--OBJBLOCK -> OBJBLOCK [1:18]
        |--LCURLY -> { [1:18]
        |--METHOD_DEF -> METHOD_DEF [3:2]
        |   |--MODIFIERS -> MODIFIERS [3:2]
        |   |   |--FINAL -> final [3:2]
        |   |   `--LITERAL_PROTECTED -> protected [3:8]
        |   |--TYPE -> TYPE [3:18]
        |   |   `--LITERAL_VOID -> void [3:18]
        |   |--IDENT -> finalize [3:23]
        |   |--LPAREN -> ( [3:31]
        |   |--PARAMETERS -> PARAMETERS [3:32]
        |   |--RPAREN -> ) [3:32]
        |   `--SLIST -> { [3:34]
        |       `--RCURLY -> } [5:2]
        `--RCURLY -> } [6:0]

```

**Comment by romani** [comment]
suppression config SuppressionXpathSingleFilter is below with prove that it works:
```
$ cat Test.java 
public class Test {

  final protected void finalize() {

  }
}

$ cat config.xml 
<?xml version="1.0" ?>
<!DOCTYPE module PUBLIC "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
  "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
  <module name="TreeWalker">
    <module name="NoFinalizer" />
    <module name="SuppressionXpathSingleFilter">
        <property name="query" value="//METHOD_DEF[./IDENT[@text='finalize'] and ./MODIFIERS/FINAL and count(./SLIST)=1]"/>
    </module>

  </module>
</module>

$ java -jar checkstyle-10.12.4-all.jar -c config.xml Test.java
Starting audit...
Audit done.

```
