### ISSUE TITLE
Migrate illegaltype.xml.template to use properties template

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#13893]
same as https://github.com/checkstyle/checkstyle/issues/13853

we need to use properties macros in illegaltype.xml.template file.

**Comment by AayushSaini101** [comment]
I am on it

**Comment by romani** [comment]
@AayushSaini101, please send PR again depending update is fixed, I hope this update becomes easy now.

**Comment by aayushRedHat** [comment]
> @AayushSaini101, please send PR again depending update is fixed, I hope this update becomes easy now.

Sure Created new PR @romani

**Comment by romani** [comment]
fix is merged
