### ISSUE TITLE
IllegalToken description: incorrect description

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#1393]
http://checkstyle.sourceforge.net/config_coding.html#IllegalToken

The description says "By default labels are prohibited." but later it describes the default values as "LITERAL_SWITCH, POST_INC, POST_DEC". Label is not listed as part of the default values.

This was actually a recent change in commit dd47d21, so just the default values in the documentation have to change.

**Comment by romani** [comment]
merged.
