### ISSUE TITLE
Update Javadoc checks to avoid // violation in Javadoc comments

### ISSUE THREAD

**Issue by suniti0804** [checkstyle/checkstyle#13969]
As identified in https://github.com/checkstyle/checkstyle/issues/11214#issuecomment-1784139525 Javadoc checks have javadoc comments having  `// violation` in them. We used to have this before we added support of `// violation X lines below`.

Now we should refactor such tests to remove `// violation` comment from javadoc comments.

Example of a check having this issue - [JavaDocStyleCheckTest](https://github.com/checkstyle/checkstyle/blob/a18d30f4b23c9184b22ea684624299abd18ff2eb/src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocStyleCheckTest.java)

All cases to fix:
```
$ grep -rl "// violation" | grep -E "*Test\.java"
src/test/java/com/puppycrawl/tools/checkstyle/internal/AllChecksTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTokenCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocStyleCheckTest.java
```

- [x] IllegalTokenCheckTest
- [x] JavadocStyleCheckTest

**Comment by meesha2000** [comment]
Hi All,
 I am excited to get started with my first open source contribution to your project, CheckStyle. I have been following the project for a while and believe that contributing would be a great learning experience. I am reaching out to seek guidance on how to get started effectively and make a meaningful contribution to the project.

As a first-time contributor to open source, I want to ensure that I follow best practices and contribute in a way that aligns with the project's goals and standards. Could anyone please provide some guidance on how to get started. 

Also I would like to take on this issue if it is still open.

Thank you

**Comment by romani** [comment]
@meesha2000 , please read https://github.com/checkstyle/checkstyle/wiki/To-GSoC-participant

**Comment by meesha2000** [comment]
@romani, I have gone through the above link. I cloned project in my system and just going through it. I am finding some bugs in my pc, not sure if it is same for others as well.

**Comment by romani** [comment]
Please move this conversation to chat room at matrix https://github.com/checkstyle/checkstyle#
Or to https://github.com/checkstyle/checkstyle/discussions

**Comment by meesha2000** [comment]
sure @romani

**Comment by relentless-pursuit** [comment]
After spending considerable amount of time on this issue, i feel it shouldn't have been a part of the issue and little more prudence should be taken into account. Because, for this specifc input class, it says tokens = COMMENT_CONTENT. It means, it considers the comments as violations too, and not just comments. To give more perspective, 
```
/*
IllegalToken
tokens = COMMENT_CONTENT


*/
// violation 6 lines above 'Using 'tokens == COMMENT_CONTENT' is not allowed.'
```
Here, it the actual violations would be be 2 while, there is just one violation, and another comment trying to point the violation. The exsiting mechanism was right. This issue might hold true for `JavadocStyleCheckTest`. And, i don't see any reason for `AllChecksTest` to be in the list. Please correct me if i am wrong. The issuer has just used the grep command and added all files which had `//violation` in the test.

**Comment by suniti0804** [comment]
@relentless-pursuit regarding `AllChecksTest` I agree with you, this class is not having` // violation` in it.

**Comment by relentless-pursuit** [comment]
> @relentless-pursuit regarding `AllChecksTest` I agree with you, this class is not having `// violation` in it.
I don't think `IllegalTokenCheckTest` should also be in the list. Please let me know if you feel why it should be.

**Comment by suniti0804** [comment]
I am working on `JavadocStyleCheckTest`

**Comment by romani** [comment]
Issue is fixed.
