### ISSUE TITLE
Update CI to have Maven Version 3.8.8, update min required maven version in pom to 3.5.4 

### ISSUE THREAD

**Issue by suniti0804** [checkstyle/checkstyle#13970]
As identified in https://github.com/checkstyle/checkstyle/pull/13887#issuecomment-1763414859 we need to update the current maven version. In the pom.xml file, version mentioned is 3.3.9 and running maven with this  version 3.3.9 (as mentioned in pom.xml) results in the following error message -

`[ERROR] Failed to execute goal org.codehaus.mojo:xml-maven-plugin:1.1.0:check-format (default) on project checkstyle: The plugin org.codehaus.mojo:xml-maven-plugin:1.1.0 requires Maven version 3.5.4 -> [Help 1]`

**Comment by relentless-pursuit** [comment]
I think the version should be a stable/major release. And, from the documentation, i can see 3.9.5 seems to be a stable release. So, the version should be a stable or major release version. Reference: https://maven.apache.org/docs/history.html

**Comment by romani** [comment]
I am ok to use 3.8.8

**Comment by relentless-pursuit** [comment]
I am new to devops, as to my understanding it requires some changes in docker file. I don't want to block the issue. If i fail to create a PR in next 2 days, anybody is free to take up this issue. Until then, I am on it.

**Comment by relentless-pursuit** [comment]
I found a similar issue https://github.com/checkstyle/contribution/issues/763. While trying to upgrade maven for CI flow, i was trying to make changes to dockerfile in the contribution repo. And, i also was facing issue with outdated groovy version. And, hence upgraded both in the dockerfile. Meanwhile, when the image build was successful, and inside container trying to run mvn -version, i constantly got `Unrecognized option: --add-exports`. On googling, it suggests java verson mismatch being used and being run inside container. Hence, i am relying on the CI flow to know if changes worked fine. 

Secondly, is there a difference between https://github.com/checkstyle/checkstyle/issues/13970 and https://github.com/checkstyle/contribution/issues/763. I am asking this to understand what extra needs to be done for https://github.com/checkstyle/checkstyle/issues/13970 from the perspective fo CI.

**Comment by nrmancuso** [comment]
Issue in contribution repo: update dockerfile, build new image

issue in checkstyle repo: update CI to use new image

**Comment by relentless-pursuit** [comment]
> Issue in contribution repo: update dockerfile, build new image
> 
> issue in checkstyle repo: update CI to use new image

Thank you. I have updated the PR. And, this time it did reflect the maven version inside container. 
 
```
% docker run -it --name new_maven newmaven /bin/sh

# mvn -version
Apache Maven 3.8.8 (4c87b05d9aedce574290d1acc98575ed5eb6cd39)
Maven home: /usr/share/maven
Java version: 11.0.21, vendor: Eclipse Adoptium, runtime: /opt/java/openjdk
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.15.49-linuxkit-pr", arch: "aarch64", family: "unix"
# exit
```
