### ISSUE TITLE
Add reference to the Checkstyle extension for bld to the Active Tools documentation

### ISSUE THREAD

**Issue by ethauvin** [checkstyle/checkstyle#13995]
Added reference to the [Checkstyle extension for bld](https://github.com/rife2/bld-checkstyle) in the ` Active Tools` table (#13994)

**Comment by ethauvin** [comment]
@nrmancuso What more do you need to know? It's pretty self-explanatory. -- Thanks.

**Comment by nrmancuso** [comment]
I am closing this issue, PR is merged.
