### ISSUE TITLE
Transitive dependency rejection after Guava upgrade to 32.1.3-jre

### ISSUE THREAD

**Issue by dtrunk90** [checkstyle/checkstyle#14123]
With checkstyle 10.12.6 guava was upgraded from 32.0.1-jre to 32.1.3-jre
Since there'S also a transitive dependency to `com.google.collections:google-collections:1.0` through `org.apache.maven.doxia:doxia-core:1.12.0` gradle task `:checkstyleMain` fails with:
```
> Could not resolve all files for configuration ':checkstyle'.
   > Could not resolve com.google.guava:guava:32.1.3-jre.
     Required by:
         project : > com.puppycrawl.tools:checkstyle:10.12.6
      > Module 'com.google.guava:guava' has been rejected:
           Cannot select module with conflict on capability 'com.google.collections:google-collections:32.1.3-jre' also provided by [com.google.collections:google-collections:1.0(runtime)]
   > Could not resolve com.google.collections:google-collections:1.0.
     Required by:
         project : > com.puppycrawl.tools:checkstyle:10.12.6 > org.apache.maven.doxia:doxia-core:1.12.0 > org.codehaus.plexus:plexus-container-default:2.1.0
      > Module 'com.google.collections:google-collections' has been rejected:
           Cannot select module with conflict on capability 'com.google.collections:google-collections:1.0' also provided by [com.google.guava:guava:32.1.3-jre(jreRuntimeElements)]
```

There's a workaround reported here: https://github.com/gradle/gradle/issues/27035#issuecomment-1814589243
But I guess it's better to exclude `com.google.collections:google-collections:1.0` because it's part of guava anyway.

See also https://github.com/slugify/slugify/actions/runs/7125400022/job/19431918771?pr=175 if you need a reproduction.

**Comment by romani** [comment]
@dtrunk90, if you know a fix please send a PR.

**Comment by nrmancuso** [comment]
@dtrunk90 would you like us to make a release so that you can get this resolved sooner on your end?

**Comment by nrmancuso** [comment]
Completed via #14140

**Comment by dtrunk90** [comment]
> @dtrunk90 update is merged, would you like us to make a release so that you can get this resolved sooner on your end?

Speaking only for me: I don't need to get this resolved sooner. Thank you.

**Comment by romani** [comment]
We will release it by regular schedule, end of month.

**Comment by marcphilipp** [comment]
This still [happens](https://github.com/junit-team/junit5/actions/runs/7779811413/job/21211547312?pr=3677) with 10.13.0:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':documentation:checkstyleMain'.
> Could not resolve all files for configuration ':documentation:checkstyle'.
   > Could not resolve com.google.guava:guava:33.0.0-jre.
     Required by:
         project :documentation > com.puppycrawl.tools:checkstyle:10.13.0
      > Module 'com.google.guava:guava' has been rejected:
           Cannot select module with conflict on capability 'com.google.collections:google-collections:33.0.0-jre' also provided by [com.google.collections:google-collections:1.0(runtime)]
   > Could not resolve com.google.collections:google-collections:1.0.
     Required by:
         project :documentation > com.puppycrawl.tools:checkstyle:10.13.0 > org.apache.maven.doxia:doxia-core:1.12.0 > org.codehaus.plexus:plexus-container-default:2.1.0
      > Module 'com.google.collections:google-collections' has been rejected:
           Cannot select module with conflict on capability 'com.google.collections:google-collections:1.0' also provided by [com.google.guava:guava:33.0.0-jre(jreRuntimeElements)]
```

**Comment by baron1405** [comment]
I am seeing this with 10.13.0 as well. Please reopen.

**Comment by McPringle** [comment]
I can confirm that this problem still exists with v10.13.0. The last usable version is 10.12.5. Everything newer is broken.

**Comment by XN137** [comment]
there was some follow-up discussion in https://github.com/checkstyle/checkstyle/issues/14211

the workaround did not work in gradle because gradle does not respect `<exclusions>` in published poms for some reason.

it also discusses the currently manually-applied workaround:
```
configurations.checkstyle {
  resolutionStrategy.capabilitiesResolution.withCapability("com.google.collections:google-collections") {
    select("com.google.guava:guava:0")
  }
}
```

**Comment by romani** [comment]
released https://github.com/checkstyle/checkstyle/releases/tag/checkstyle-10.14.2

**Comment by baron1405** [comment]
@romani I can confirm that 10.14.2 works across all my projects including Checkstyle extensions. A big thank you for driving the final fix and subsequent release!

**Comment by dtrunk90** [comment]
Yes, it's fixed now. Thank you! :-)

**Comment by sdavids** [comment]
Verified with:

```shell
------------------------------------------------------------
Gradle 8.6
------------------------------------------------------------

Build time:   2024-02-02 16:47:16 UTC
Revision:     d55c486870a0dc6f6278f53d21381396d0741c6e

Kotlin:       1.9.20
Groovy:       3.0.17
Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023
JVM:          17.0.10 (Eclipse Adoptium 17.0.10+7)
OS:           Mac OS X 14.4 aarch64
```

```
checkstyle = "com.puppycrawl.tools:checkstyle:10.14.2"
```
