### ISSUE TITLE
AnnotationUtil.containsAnnotation no longer matches a simple name to a fully-qualified name

### ISSUE THREAD

**Issue by wilkinsona** [checkstyle/checkstyle#14135]
I apologise for not following the bug report template, but it didn't apply to this problem which affects custom extensions to Checkstyle. Please let me know if you'd like this sort of issue to be reported differently in the future.

Since 10.3.2, `AnnotationUtil.containsAnnotation` no longer matches when given a simple name and the AST contains a fully-qualified name. I think this change in behavior was introduced in https://github.com/checkstyle/checkstyle/commit/2282a7eca66073d838ace295d1d6874818323fab.

Consider this source code:

```
public class JUnit5BadAnnotation {

	@org.junit.Test
	void doSomethingWorks() {
		// test here
	}

}
```

that results in this AST:

```
COMPILATION_UNIT -> COMPILATION_UNIT [22:0]
`--CLASS_DEF -> CLASS_DEF [22:0]
    |--MODIFIERS -> MODIFIERS [22:0]
    |   `--LITERAL_PUBLIC -> public [22:0]
    |--LITERAL_CLASS -> class [22:7]
    |--IDENT -> JUnit5BadAnnotation [22:13]
    `--OBJBLOCK -> OBJBLOCK [22:33]
        |--LCURLY -> { [22:33]
        |--METHOD_DEF -> METHOD_DEF [24:1]
        |   |--MODIFIERS -> MODIFIERS [24:1]
        |   |   `--ANNOTATION -> ANNOTATION [24:1]
        |   |       |--AT -> @ [24:1]
        |   |       `--DOT -> . [24:11]
        |   |           |--DOT -> . [24:5]
        |   |           |   |--IDENT -> org [24:2]
        |   |           |   `--IDENT -> junit [24:6]
        |   |           `--IDENT -> Test [24:12]
        |   |--TYPE -> TYPE [25:1]
        |   |   `--LITERAL_VOID -> void [25:1]
        |   |--IDENT -> doSomethingWorks [25:6]
        |   |--LPAREN -> ( [25:22]
        |   |--PARAMETERS -> PARAMETERS [25:23]
        |   |--RPAREN -> ) [25:23]
        |   `--SLIST -> { [25:25]
        |       `--RCURLY -> } [27:1]
        `--RCURLY -> } [29:0]
```

With 10.3.1, `containsAnnotation` will return `true` when looking for `Test`. With 10.3.2 and later, `containsAnnotation` will only return `true` when looking for `org.junit.Test`.

**Comment by romani** [comment]
Yes, just another example that our utility methods serve to what standard Checks needs and util folder is not an API for user, implementation can change at any time. It unlikely to be not reasonable, but signature of method can change at point of time.

I think here you also need copy old version of method to your codebase.

We updating Checks to use fully qualified names for types to do more correct matching.

**Comment by wilkinsona** [comment]
Thanks, Romani. Understood. Perhaps worth an update to the javadoc? It still states that:

> "Override" will match both java.lang.Override and Override

**Comment by romani** [comment]
@wilkinsona , please send PR with update.

**Comment by wilkinsona** [comment]
I would like to do that and will do so if I can.  It may take a while, unfortunately, as I have a new employer and I'm yet to navigate their approvals process for making contributions to third-party OSS projects.

**Comment by romani** [comment]
create obscure github account and contribute anonymously, as main point to make something done, not "done by my name".
