### ISSUE TITLE
Enable checks from Error Prone Support

### ISSUE THREAD

**Issue by rickie** [checkstyle/checkstyle#14137]
In PR https://github.com/checkstyle/checkstyle/pull/14136 I added Error Prone Support to Checkstyle. As @romani suggested in https://github.com/checkstyle/checkstyle/issues/14129, I'd like to create this issue to discuss which checks from [Error Prone Support](https://github.com/picnicSupermarket/error-prone-support/) are useful for the Checkstyle project to enable. 

The full list of checks can be found here: https://error-prone.picnic.tech/.

1. [AmbiguousJsonCreator](https://error-prone.picnic.tech/bugpatterns/AmbiguousJsonCreator/)
1. [AssertJIsNull](https://error-prone.picnic.tech/bugpatterns/AssertJIsNull/)
1. [AutowiredConstructor](https://error-prone.picnic.tech/bugpatterns/AutowiredConstructor/)
1. [CanonicalAnnotationSyntax](https://error-prone.picnic.tech/bugpatterns/CanonicalAnnotationSyntax/)
1. [CollectorMutability](https://error-prone.picnic.tech/bugpatterns/CollectorMutability/)
1. [DirectReturn](https://error-prone.picnic.tech/bugpatterns/DirectReturn/)
1. [EmptyMethod](https://error-prone.picnic.tech/bugpatterns/EmptyMethod/)
1. [ExplicitEnumOrdering](https://error-prone.picnic.tech/bugpatterns/ExplicitEnumOrdering/)
1. [FormatStringConcatenation](https://error-prone.picnic.tech/bugpatterns/FormatStringConcatenation/)
1. [IdentityConversion](https://error-prone.picnic.tech/bugpatterns/IdentityConversion/)
1. [ImmutablesSortedSetComparator](https://error-prone.picnic.tech/bugpatterns/ImmutablesSortedSetComparator/)
1. [IsInstanceLambdaUsage](https://error-prone.picnic.tech/bugpatterns/IsInstanceLambdaUsage/)
1. [JUnitClassModifiers](https://error-prone.picnic.tech/bugpatterns/JUnitClassModifiers/)
1. [JUnitMethodDeclaration](https://error-prone.picnic.tech/bugpatterns/JUnitMethodDeclaration/)
1. [JUnitValueSource](https://error-prone.picnic.tech/bugpatterns/JUnitValueSource/)
1. [LexicographicalAnnotationAttributeListing](https://error-prone.picnic.tech/bugpatterns/LexicographicalAnnotationAttributeListing/)
1. [MockitoMockClassReference](https://error-prone.picnic.tech/bugpatterns/MockitoMockClassReference/)
1. [MockitoStubbing](https://error-prone.picnic.tech/bugpatterns/MockitoStubbing/)
1. [NestedOptionals](https://error-prone.picnic.tech/bugpatterns/NestedOptionals/)
1. [PrimitiveComparison](https://error-prone.picnic.tech/bugpatterns/PrimitiveComparison/)
1. [RedundantStringConversion](https://error-prone.picnic.tech/bugpatterns/RedundantStringConversion/)
1. [Slf4jLogStatement](https://error-prone.picnic.tech/bugpatterns/Slf4jLogStatement/)
1. [StaticImport](https://error-prone.picnic.tech/bugpatterns/StaticImport/)
1. [StringJoin](https://error-prone.picnic.tech/bugpatterns/StringJoin/)
1. [TimeZoneUsage](https://error-prone.picnic.tech/bugpatterns/TimeZoneUsage/)

I omitted some of the checks from the list as they are definitely not applicable to this project (for example they are Spring or Reactor focused). 

Let me know if this is the right approach, or if we should change something.

I'm curious to hear your thoughts on the checks!

**Comment by rickie** [comment]
Here are a few of my comments on some of the checks:

---
2. **AssertJIsNull**: Only one AssertJ reference in Checkstyle, so not relevant.
--- 

5. **CollectorMutability**: In this PR @romani mentioned that we should enable this rule 😄 https://github.com/checkstyle/checkstyle/pull/12777#pullrequestreview-1325151741. 
---

14. **JUnitMethodDeclaration**: @romani made a comment about that [here](https://github.com/checkstyle/checkstyle/issues/14129#issuecomment-1851012913), saying:

> We had this violation in Sonarqube [error-prone.picnic.tech/bugpatterns/JUnitMethodDeclaration](https://error-prone.picnic.tech/bugpatterns/JUnitMethodDeclaration/)
In team we agreed to have methods to be public even somebody think it is better to be package-private.

So this one is probably not interesting.

---

23. **StaticImport**: In [this comment](https://github.com/checkstyle/checkstyle/issues/14129#issuecomment-1851012913) @romani mentions the following: 

> [error-prone.picnic.tech/bugpatterns/StaticImport](https://error-prone.picnic.tech/bugpatterns/StaticImport/)
We like more explicit code, as majority of time we do code review from phones, so context matters for us.

Just to clarify, in this check we statically import [these members](https://github.com/PicnicSupermarket/error-prone-support/blob/master/error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/StaticImport.java#L58-L153). It is a list of carefully reviewed members that are statically imported as doing so doesn't result in a loss of context. So mostly to remove "duplicate words".  

---


>

**Comment by romani** [comment]
@Vyom-Yadav, FYI

**Comment by romani** [comment]
Please activate:
[AmbiguousJsonCreator](https://error-prone.picnic.tech/bugpatterns/AmbiguousJsonCreator/)
[AssertJIsNull](https://error-prone.picnic.tech/bugpatterns/AssertJIsNull/)
[AutowiredConstructor](https://error-prone.picnic.tech/bugpatterns/AutowiredConstructor/)
[CanonicalAnnotationSyntax](https://error-prone.picnic.tech/bugpatterns/CanonicalAnnotationSyntax/)
[CollectorMutability](https://error-prone.picnic.tech/bugpatterns/CollectorMutability/)

---------

[DirectReturn](https://error-prone.picnic.tech/bugpatterns/DirectReturn/) we can try in separate PR, to see a scope of violations, I remember in some cases it was benefitials to use not direct return.


-------

please activate:
[EmptyMethod](https://error-prone.picnic.tech/bugpatterns/EmptyMethod/)
[ExplicitEnumOrdering](https://error-prone.picnic.tech/bugpatterns/ExplicitEnumOrdering/)

------

[FormatStringConcatenation](https://error-prone.picnic.tech/bugpatterns/FormatStringConcatenation/) we can try in separate PR, to see a scope of violations, I remember in some cases it was benefitials to use concatenation as compact syntax.

-------
please activate:
[IdentityConversion](https://error-prone.picnic.tech/bugpatterns/IdentityConversion/)

-------

[ImmutablesSortedSetComparator](https://error-prone.picnic.tech/bugpatterns/ImmutablesSortedSetComparator/) we can try in separate PR. I have concern on extra dependency, we are library, we care about less transitive dependencies.

-------

please activate:
[IsInstanceLambdaUsage](https://error-prone.picnic.tech/bugpatterns/IsInstanceLambdaUsage/)

------

lets suppress:
[JUnitClassModifiers](https://error-prone.picnic.tech/bugpatterns/JUnitClassModifiers/)
[JUnitMethodDeclaration](https://error-prone.picnic.tech/bugpatterns/JUnitMethodDeclaration/)
[JUnitValueSource](https://error-prone.picnic.tech/bugpatterns/JUnitValueSource/)

-------

please activate:
[LexicographicalAnnotationAttributeListing](https://error-prone.picnic.tech/bugpatterns/LexicographicalAnnotationAttributeListing/)
[MockitoMockClassReference](https://error-prone.picnic.tech/bugpatterns/MockitoMockClassReference/)
[MockitoStubbing](https://error-prone.picnic.tech/bugpatterns/MockitoStubbing/)
[NestedOptionals](https://error-prone.picnic.tech/bugpatterns/NestedOptionals/)
[PrimitiveComparison](https://error-prone.picnic.tech/bugpatterns/PrimitiveComparison/)
[RedundantStringConversion](https://error-prone.picnic.tech/bugpatterns/RedundantStringConversion/)
[Slf4jLogStatement](https://error-prone.picnic.tech/bugpatterns/Slf4jLogStatement/)


-------

lets suppress:
[StaticImport](https://error-prone.picnic.tech/bugpatterns/StaticImport/)


-------

lets try:
[StringJoin](https://error-prone.picnic.tech/bugpatterns/StringJoin/)
[TimeZoneUsage](https://error-prone.picnic.tech/bugpatterns/TimeZoneUsage/)

**Comment by romani** [comment]
@rickie, please send each activation in separate PR, AND is there is bunch of udpates required, it is completely OK to split fixes( before activation) in separate PRs.
Some updates might be very controversial, so it is reasonable to have smaller PR to agree on style before forcing whole code to follow it.

**Comment by nrmancuso** [comment]
I agree with prioritization and selection of bug patterns at https://github.com/checkstyle/checkstyle/issues/14137#issuecomment-1859207808, @rickie please feel free to start sending PRs :)

**Comment by Vyom-Yadav** [comment]
I agree with the discussion above. @romani This can be a good third/fourth issue. Please convert the issue description to a checklist, I too can send a few PRs to have some examples.

**Comment by romani** [comment]
This is not good for junior contributors as it might be controversial and tricky.
But you are not a junior, we are welcome with PR

**Comment by rickie** [comment]
@romani I think we can close this issue now, right?
