### ISSUE TITLE
Breaking API change in AnnotationUtil

### ISSUE THREAD

**Issue by wilkinsona** [checkstyle/checkstyle#14134]
I apologise for not following the bug report template, but it didn't apply to this problem which affects custom extensions to Checkstyle. Please let me know if you'd like this sort of issue to be reported differently in the future.

I am one of the maintainers of some [custom Checkstyle extensions](https://github.com/spring-io/spring-javaformat/tree/main/spring-javaformat/spring-javaformat-checkstyle) and in those extensions we use the [AnnotationUtil API](https://github.com/checkstyle/checkstyle/blob/0010bb8209bf0003bb198b6b989ca5564e9d0184/src/main/java/com/puppycrawl/tools/checkstyle/utils/AnnotationUtil.java). While trying to upgrade to Checkstyle 10.12, I have discovered that a [breaking API change was made to `AnnotationUtil` in 10.3](https://github.com/checkstyle/checkstyle/commit/43ae5d651d5b3078d9c04a0539134e811f461f5c#diff-4dc75461f05b4dd4172b9f0e6105d90f8c127791a35dcee91d259d0323d330d2) where `containsAnnotation(DetailAST ast, List<String> annotations)` was changed to `containsAnnotation(DetailAST ast, Set<String> annotations)`.

For backwards compatibility, would it be possible to overload the method and reinstate the `List<String>`? Or perhaps `AnnotationUtil` isn't considered to be public API and we should stop using it?

**Comment by nrmancuso** [comment]
> Or perhaps AnnotationUtil isn't considered to be public API and we should stop using it?

This is the best policy; while we are careful about changes to checks and classes in the [api](https://github.com/checkstyle/checkstyle/tree/0010bb8209bf0003bb198b6b989ca5564e9d0184/src/main/java/com/puppycrawl/tools/checkstyle/api) package (and quite a few others), we consider anything in [utils](https://github.com/checkstyle/checkstyle/tree/0010bb8209bf0003bb198b6b989ca5564e9d0184/src/main/java/com/puppycrawl/tools/checkstyle/utils) to be “internal”.

**Comment by romani** [comment]
Sorry for inconvenience, but in checkstyle almost everything is like contract with users. To avoid having too much responsibility, we agreed in team that we very very accurate for  classes in api package only, and modules names and properties. All other is internal implementations and serve our internal needs first or all, usage of it by others is not supported. But as all is open users can easily see what method to use instead.

>For backwards compatibility, would it be possible to overload the method and reinstate the List of String?

We can try, but you should be aware that our quality threshold is so demanding (automatically) that we can not have code without usage and test coverage. If we make utility method we must use it in real Checks.

To avoid extra activities, I think that the most easy approach to be compatible is to copy old implementation of this utility method to your codebase and avoid undesirable refactoring.

>Or perhaps AnnotationUtil isn't considered to be public API and we should stop using it?

I still recommend to use it, but be ready for breaking changes. I doubt it will change significantly in future due. If we damage your side, do not hesitate to checkout our old code and copy function to your codebase.

Please be aware of our versioning https://checkstyle.org/#Development_Cycle


I am closing issue , but discussion can continue to answer all questions and assist with migration.

Other option I see to reuse spring in no-error CI testing, this will make sure we check execution and validation on each commit. If any breaking changes happens we usually send patches before we even release our code. The only requirement for this: project must use checkstyle with extensive list of modules and any violations should fail a build. Let me know if you interested in this.
Example of such partnership: https://github.com/checkstyle/checkstyle/blob/0010bb8209bf0003bb198b6b989ca5564e9d0184/.circleci/config.yml#L139
