### ISSUE TITLE
Failed to execute goal com.groupon.maven.plugin.json:json-schema-validator:1.2.0:validate (default) on project checkstyle

### ISSUE THREAD

**Issue by relentless-pursuit** [checkstyle/checkstyle#14155]
I read the documentation involving the build process. Upon cloning a fresh repository, and running `mvn install`, i got the following error:
`[ERROR] Failed to execute goal com.groupon.maven.plugin.json:json-schema-validator:1.2.0:validate (default) on project checkstyle: Exception while locating input file; file=https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Documents/CommitteeSpecifications/2.1.0/sarif-schema-2.1.0.json: Could not find resource 'https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Documents/CommitteeSpecifications/2.1.0/sarif-schema-2.1.0.json'. -> [Help 1]`

I am using the below environment:
% `mvn -version`
```
Apache Maven 3.9.5 (57804ffe001d7215b5e7bcb531cf83df38f93546)
Maven home: /opt/homebrew/Cellar/maven/3.9.5/libexec
Java version: 11.0.11, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk-11.0.11.jdk/Contents/Home
Default locale: en_IN, platform encoding: UTF-8
OS name: "mac os x", version: "10.16", arch: "x86_64", family: "mac"
piyushkumarsadangi@piyushs-MacBook-Air checkstyle % 
```

**Comment by nrmancuso** [comment]
Link to documentation: https://checkstyle.org/contributing.html#Build

@relentless-pursuit can you try out all commands from this section, and if they fail please extend issue description.

**Comment by relentless-pursuit** [comment]
> Link to documentation: https://checkstyle.org/contributing.html#Build
> 
> @relentless-pursuit can you try out all commands from this section? If they fail please extend issue description.

Sure.

**Comment by romani** [comment]
file is available onlline:
![image](https://github.com/checkstyle/checkstyle/assets/812984/8e314709-7715-4177-bab2-b8921b4c901f)

can you try to get this file from terminal by curl ?
Sometime people need to use proxy settings to bypass network limitations.

**Comment by relentless-pursuit** [comment]
@romani, i tried with that. But, failed. 
```
% curl -I https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Documents/CommitteeSpecifications/2.1.0/sarif-schema-2.1.0.json

curl: (28) Failed to connect to raw.githubusercontent.com port 443 after 75239 ms: Couldn't connect to server
```

**Comment by nrmancuso** [comment]
@relentless-pursuit please do:

`curl -v -I https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Documents/CommitteeSpecifications/2.1.0/sarif-schema-2.1.0.json` and share results here. This will turn on "verbose" output to give us additional information.

**Comment by relentless-pursuit** [comment]
I have figured out the issue. Accessing `https://raw.githubusercontent.com/` is blocked my many ISPs in India. Had to change the DNS to `8.8.4.4`. Now, seems to be working fine. 

```
% curl -I  https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Documents/CommitteeSpecifications/2.1.0/sarif-schema-2.1.0.json

HTTP/2 200 
cache-control: max-age=300
content-security-policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
content-type: text/plain; charset=utf-8
etag: "f718e27d3f9d9a3dedcf2c588ecaefff4ef63ea332dbc85e0fbea97381da3de6"
strict-transport-security: max-age=31536000
x-content-type-options: nosniff
x-frame-options: deny
x-xss-protection: 1; mode=block
x-github-request-id: 858A:3568A2:D7A454:F2DF25:6594EF57
accept-ranges: bytes
date: Wed, 03 Jan 2024 05:26:29 GMT
via: 1.1 varnish
x-served-by: cache-bom4722-BOM
x-cache: HIT
x-cache-hits: 1
x-timer: S1704259590.644476,VS0,VE1
vary: Authorization,Accept-Encoding,Origin
access-control-allow-origin: *
cross-origin-resource-policy: cross-origin
x-fastly-request-id: 8850f7c4cc5a6d6e798374ec097bfd6a32a88bcd
expires: Wed, 03 Jan 2024 05:31:29 GMT
source-age: 174
content-length: 112320
```

**Comment by romani** [comment]
Please share what and how you changed settings, it will be useful for future contributors.

**Comment by relentless-pursuit** [comment]
I am getting a BUILD SUCCESS on doing mvn verify. But, i still get the same error mvn clean verify. Not sure of the reasons. 


I assume access to https://raw.githubusercontent.com/ is blocked my ISPs in India. Hence, i was constantly getting this error:
`[ERROR] Failed to execute goal com.groupon.maven.plugin.json:json-schema-validator:1.2.0:validate (default) on project checkstyle: Exception while locating input file; file=https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Documents/CommitteeSpecifications/2.1.0/sarif-schema-2.1.0.json: Could not find resource 'https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Documents/CommitteeSpecifications/2.1.0/sarif-schema-2.1.0.json'. -> [Help 1]`

You can cross-check this by doing something like this:
`curl -I https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Documents/CommitteeSpecifications/2.1.0/sarif-schema-2.1.0.json`

For me it constantly, gave, `curl: (28) Failed to connect to raw.githubusercontent.com port 443 after 75239 ms: Couldn't connect to server`. Moreover, directly trying to access the link was not leading anywhere. 

After scratching the internet, i found that if we change the DNS, it can work. I use macOS Ventura. And, if you use any other OS, the steps might vary. Go to system preference -> wifi -> click on the details as shown below and go to the DNS, and click on + and try with `8.8.4.4`


<img width="488" alt="image" src="https://github.com/checkstyle/checkstyle/assets/95259545/4faff480-4c62-408c-a55d-f16269f518e6">

<img width="667" alt="image" src="https://github.com/checkstyle/checkstyle/assets/95259545/600576e6-b5a5-460f-bbe9-150b32750340">


Preferably, restart and use the below command to flush your DNS cache. 
`sudo dscacheutil -flushcache; sudo killall -HUP mDNSResponder`

And, try accessing the url using curl:
curl -I https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Documents/CommitteeSpecifications/2.1.0/sarif-schema-2.1.0.json

Results of mvn verify:
```
[INFO] --- json:1.2.0:validate (default) @ checkstyle ---
[INFO] Loaded JSON from /Users/piyushkumarsadangi/Development/checkstyle/checkstyle/target/plexus-resources855880363tmp
[INFO] Loaded JSON from /Users/piyushkumarsadangi/Development/checkstyle/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/sariflogger/ExpectedSarifLoggerSingleException.sarif
[INFO] Successfully validated JSON from /Users/piyushkumarsadangi/Development/checkstyle/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/sariflogger/ExpectedSarifLoggerSingleException.sarif against /Users/piyushkumarsadangi/Development/checkstyle/checkstyle/target/plexus-resources855880363tmp
[INFO] Loaded JSON from /Users/piyushkumarsadangi/Development/checkstyle/checkstyle/target/plexus-resources855880363tmp
[INFO] Loaded JSON from /Users/piyushkumarsadangi/Development/checkstyle/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/sariflogger/ExpectedSarifLoggerDoubleException.sarif
[INFO] Successfully validated JSON from /Users/piyushkumarsadangi/Development/checkstyle/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/sariflogger/ExpectedSarifLoggerDoubleException.sarif against /Users/piyushkumarsadangi/Development/checkstyle/checkstyle/target/plexus-resources855880363tmp
[INFO] Loaded JSON from /Users/piyushkumarsadangi/Development/checkstyle/checkstyle/target/plexus-resources855880363tmp
[INFO] Loaded JSON from /Users/piyushkumarsadangi/Development/checkstyle/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/sariflogger/ExpectedSarifLoggerLineOnly.sarif
[INFO] Successfully validated JSON from /Users/piyushkumarsadangi/Development/checkstyle/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/sariflogger/ExpectedSarifLoggerLineOnly.sarif against /Users/piyushkumarsadangi/Development/checkstyle/checkstyle/target/plexus-resources855880363tmp
[INFO] Loaded JSON from /Users/piyushkumarsadangi/Development/checkstyle/checkstyle/target/plexus-resources855880363tmp
[INFO] Loaded JSON from /Users/piyushkumarsadangi/Development/checkstyle/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/sariflogger/ExpectedSarifLoggerSingleWarning.sarif
[INFO] Successfully validated JSON from /Users/piyushkumarsadangi/Development/checkstyle/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/sariflogger/ExpectedSarifLoggerSingleWarning.sarif against /Users/piyushkumarsadangi/Development/checkstyle/checkstyle/target/plexus-resources855880363tmp
[INFO] Loaded JSON from /Users/piyushkumarsadangi/Development/checkstyle/checkstyle/target/plexus-resources855880363tmp
[INFO] Loaded JSON from /Users/piyushkumarsadangi/Development/checkstyle/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/sariflogger/ExpectedSarifLoggerSingleError.sarif
[INFO] Successfully validated JSON from /Users/piyushkumarsadangi/Development/checkstyle/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/sariflogger/ExpectedSarifLoggerSingleError.sarif against /Users/piyushkumarsadangi/Development/checkstyle/checkstyle/target/plexus-resources855880363tmp
[INFO] Loaded JSON from /Users/piyushkumarsadangi/Development/checkstyle/checkstyle/target/plexus-resources855880363tmp
[INFO] Loaded JSON from /Users/piyushkumarsadangi/Development/checkstyle/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/sariflogger/ExpectedSarifLoggerEmpty.sarif
[INFO] Successfully validated JSON from /Users/piyushkumarsadangi/Development/checkstyle/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/sariflogger/ExpectedSarifLoggerEmpty.sarif against /Users/piyushkumarsadangi/Development/checkstyle/checkstyle/target/plexus-resources855880363tmp
[INFO] Loaded JSON from /Users/piyushkumarsadangi/Development/checkstyle/checkstyle/target/plexus-resources855880363tmp
[INFO] Loaded JSON from /Users/piyushkumarsadangi/Development/checkstyle/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/sariflogger/ExpectedSarifLoggerDoubleError.sarif
[INFO] Successfully validated JSON from /Users/piyushkumarsadangi/Development/checkstyle/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/sariflogger/ExpectedSarifLoggerDoubleError.sarif against /Users/piyushkumarsadangi/Development/checkstyle/checkstyle/target/plexus-resources855880363tmp
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
```

**Comment by relentless-pursuit** [comment]
On a side note, I am still getting the error with mvn clean verify. 
```
[INFO] --- json:1.2.0:validate (default) @ checkstyle ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  05:06 min
[INFO] Finished at: 2024-01-03T11:58:28+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.groupon.maven.plugin.json:json-schema-validator:1.2.0:validate (default) on project checkstyle: Exception while locating input file; file=https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Documents/CommitteeSpecifications/2.1.0/sarif-schema-2.1.0.json: Could not find resource 'https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Documents/CommitteeSpecifications/2.1.0/sarif-schema-2.1.0.json'. -> [Help 1]
[ERROR] 
```


However, what's different now is that I can click on the urls and it redirects me to the resource, unlike in the past where it would be a resource not found kind of situation.

**Comment by relentless-pursuit** [comment]
I am closing the issue with the deatiled analysis and findings above.
