### ISSUE TITLE
RightCurlyCheck with RightCurlyOption.SAME rises violation when '}' ends line with single-line block.

### ISSUE THREAD

**Issue by MEZk** [checkstyle/checkstyle#1416]
RightCurlyCheck with the following configuration:
````xml
 <module name="RightCurly"/>
````
rises violation (```'}' should have line break before.```) on the following code example: 
````java
 } finally { future.cancel(true); }
````
Lets analyse.

To begin with, first ```}``` token. Right curly policy is RightCurlyOption.SAME (by default). It is ok that after ```}``` is finally statement. All right, no violation here.

Next, right curly policy is RightCurlyOption.SAME (by default), but look at the second ```}```. There is no continuation of that  multi-block statement (http://google.github.io/styleguide/javaguide.html#s4.1.3-braces-empty-blocks)  after second ```}``` on the same line that is why the check rises violation here, but It is not a good idea to rise violation when ```}``` ends line with single-line block.

**Comment by romani** [comment]
released as 6.10
