### ISSUE TITLE
java8: Demand types for lambda

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#142]
Sources: http://docs.oracle.com/javase/tutorial/java/javaOO/methodreferences.html

```
Arrays.sort(rosterAsArray,
    (Person a, Person b) -> {
        return a.getBirthday().compareTo(b.getBirthday());
    }
);
```

could be written as: 

```
Arrays.sort(rosterAsArray,
    (a, b) -> {
        return a.getBirthday().compareTo(b.getBirthday());
    }
);
```

Rationale: I do believe it will be style question to be verbose ("(Person a, Person b)") or short ("(a, b)") in lambda arguments declaration.
##

**Comment by romani** [comment]
@nrmancuso , please share Xpath for this Chek to be done.
but we will still need Check

**Comment by nrmancuso** [comment]
>@nrmancuso , please share Xpath for this Chek to be done.

https://stackoverflow.com/a/66792636/13160102

>@nrmancuso , please share Xpath for this Chek to be done.
but we will still need Check

I disagree, this Xpath expression is very simple and extensible; if anything, we need to create a searchable repository (conceptually, not necessarily a github repo) of MatchXPath modules with metadata tags and examples like this to help users easily discover such xpath modules.

**Comment by romani** [comment]
I do you have ideas on organize repository or page(s) that will have have such xpath instances? 
Or we will rely on Google ability to find anything anywhere?

**Comment by nrmancuso** [comment]
WE can discuss in https://github.com/checkstyle/checkstyle/issues/9074

**Comment by nrmancuso** [comment]
We have MatchXPath module to do this, we don’t need a new check for such a simple task like this. I am closing this issue.
