### ISSUE TITLE
JavadocType ignores param tags in InnerClass

### ISSUE THREAD

**Issue by pbaranchikov** [checkstyle/checkstyle#1421]
Inner classes are not checked with JavadocType check for missing or extra ``@param`` tags

The following code is Ok, but ``@param`` tags are wrong set in the javadoc
```java
    /**
     * Example inner class.
     * @param <A> documented parameter
     * @param <C> extra parameter
     */

    public static class InnerClass<A,B>
    {
    }
```

**Comment by romani** [comment]
changes of pbaranchikov are merged
