### ISSUE TITLE
Update Maven Shade Plugin to 2.4.1

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#1424]
Release Notes - Maven Shade Plugin - Version 2.4.1

https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12317921&version=12332978

Bugs:

 * [MSHADE-148] - Shade Plugin gets stuck in infinite loop building dependency reduced POM
 * [MSHADE-194] - Reporting uses maven-invoker-plugin version 1.9 instead of 1.10

**Comment by romani** [comment]
merged
