### ISSUE TITLE
Update tests that use inner test Checks to use Input files with violation comments

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#14249]
Detected at https://github.com/checkstyle/checkstyle/pull/14237

But it is not first time I see usage of such inner in test Check that doesn't do violations but do some static collection update.

We need to:
Redo this PR to reuse Input file with inlined config and update Check to do violations, violation  should be reused from one of existing Checks that printing some Check value(comment content) we need to reuse our model of matching several violations that are reported on same line.

Todo: 
- share example of how we did it already.
- find other cases like this to update more tests

**Comment by Harsh4902** [comment]
@romani is anyone working on this issue? If no, then can I work?

**Comment by romani** [comment]
Just make comment "I am on it" and send PR

**Comment by mahfouz72** [comment]
@romani @nrmancuso any update on this? should I send a PR for one similar case to prove my understanding if it is good we can add it as an example in the description. or just wait for approval

**Comment by romani** [comment]
Please send PR , I didn't not found good example, your PR will be awesome example

**Comment by mahfouz72** [comment]
@romani unfortunately I didn't found examples too. however I will make more search and whenever I found I will send pr

**Comment by romani** [comment]
do not search, just do fix, and it will be example for next updates.

**Comment by mahfouz72** [comment]
@romani please check this https://github.com/checkstyle/checkstyle/pull/14518 if it can serve as example as next updates

**Comment by romani** [comment]
Fix is merged
