### ISSUE TITLE
Update google_checks.xml to check order of overloaded constructors

### ISSUE THREAD

**Issue by Zopsss** [checkstyle/checkstyle#14273]
I have read check documentation: https://checkstyle.sourceforge.io/checks/coding/overloadmethodsdeclarationorder.html
I have downloaded the latest cli from: https://checkstyle.org/cmdline.html#Download_and_Run
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

Currently, Checkstyle does not checks the order of overloaded constructors, meaning that all overloaded constructors should be in one order, there can't be any methods in between. This is required based on the latest version of  [Google Java Style Guide](https://google.github.io/styleguide/javaguide.html). The rule is defined at the `3.4.2.1 Overloads: never spilts` section of the [3.4.2 Ordering of class content](https://google.github.io/styleguide/javaguide.html#s3.4.2-ordering-class-contents).

> 3.4.2.1 Overloads: never split
Methods of a class that share the same name appear in a single contiguous group with no other members in between. The same applies to **multiple constructors (which always have the same name)**. This rule applies even when modifiers such as static or private differ between the methods.

we cover this paragraph by single check - https://checkstyle.org/google_style.html#a3.4.2.1

---
### Example

I used [google_checks.xml](https://github.com/checkstyle/checkstyle/blob/b1153c9979b6d63db08c0ab2c3911dae451dbb17/src/main/resources/google_checks.xml) for config file to test the following code: 

**Test.java**
```java
$ cat Test.java 
/**
 * Javadoc comment.
 */
public class Test {
  public Test() { }

  public Test(int a) { }

  public void testing() { }

  public Test(int a, int b) { }

}
```

**Output**
```
$ java -jar checkstyle-10.13.0-all.jar -c src/google_checks.xml src/Test.java
Starting audit...
Audit done.
```
As you can see, the code does not produce any violation while it should be producing a violation telling that all the overloaded constructors should be in order, there can't be any methods in between them.

**Comment by romani** [comment]
@Zopsss ,

please show result of 
`java -jar checkstyle-10.12.7-all.jar -c /google_checks.xml src/Test.java`
to make sure there is no violations from other Check. Google style coverage is done numerous Checks, not a single.

>This rule applies even when modifiers such as static or private differ between the methods.

please check coverage of this by test. if not covered, please open new issue

**Comment by Zopsss** [comment]
> @Zopsss ,
> 
> please show result of `java -jar checkstyle-10.12.7-all.jar -c /google_checks.xml src/Test.java` to make sure there is no violations from other Check. Google style coverage is done numerous Checks, not a single.


Here is the result of using `google_checks.xml` :

```java
$ cat src/Test.java
/**
 * Javadoc comment.
 */

public class Test {
  public Test(int a) { }

  public Test(String a) { }

  public void testing() { }

  public Test(int a, int b) { }
}
```

#### Output
```
$ java -jar checkstyle-10.12.7-all.jar -c /google_checks.xml src/Test.java
Starting audit...
Audit done.
```

Had to add javadoc comment at the starting cuz it was giving some kind of javadoc missing error.

>> This rule applies even when modifiers such as static or private differ between the methods.
>
> please check coverage of this by test. if not covered, please open new issue

The check is passing even when the overloaded methods are `private` or `static`.

File:

```java
$ cat src/Test.java
/**
 * Javadoc comment.
 */

public class Test {
  public void testing() {}

  private void testing(int a) {}

  public void testing(int a, int b) {}

  public static void testing(String a) {}

  public void testing(String a, String b) {}
}
```

**Comment by romani** [comment]
Thanks a lot for testing modifiers, please send PR to contribute Junit test coverage to make sure it will always be like this:).

**Comment by Zopsss** [comment]
Hey @romani I was thinking about starting working on this issue. The check's mostly logic is contained only in one method:

https://github.com/checkstyle/checkstyle/blob/e6518fb9bfd27206e6c42e863f2859373546e8da/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/OverloadMethodsDeclarationOrderCheck.java#L101

this same logic but with few modifications can be use to add support for constructors, so we can add support for constructors by extending the current check and if we do so then I guess we will also need to change the name of the check to something like `OverloasNeverSpilts`. 

There is also other way, we can make a new module which will be specifically for checking overloaded constructors, as far as I can think, the new check mostly will be similar to the current check. 

We can discuss on which approach should we take, then I will raise a PR for it. I would be happy to hear your thoughts on how we should approach this problem :-)

**Comment by Zopsss** [comment]
@romani ping

**Comment by nrmancuso** [comment]
I am removing approved label, since it seems like we are not clear on the goal of this issue. It seems like we have two separate issues here:
1. We do not support this feature in `OverloadMethodsDeclarationOrder` check
2. We do not support this in google_checks.xml

If we want to add new functionality to `OverloadMethodsDeclarationOrder` check, this needs to be done in the scope of an entirely new issue. It has nothing to do with the google style guide. After this work is completed, we can revisit this issue to update google_checks.xml, related documentation, and tests to prove that we support it.

**Comment by Zopsss** [comment]
@nrmancuso so should I open a new issue for the discussion about adding constructor support for `OverloadMethodsDeclarationOrder`, I will link my PR to that issue and when that PR gets merged we can start working on this issue, updating the `google_chcks.xml` right?

**Comment by nrmancuso** [comment]
> @nrmancuso so should I open a new issue for the discussion about adding constructor support for `OverloadMethodsDeclarationOrder`, I will link my PR to that issue and when that PR gets merged we can start working on this issue, updating the `google_chcks.xml` right?

Yes, this is good. Make sure to follow the issue template for a new feature to demonstrate how the check works now, and how you would like it to work.

**Comment by Zopsss** [comment]
hey @nrmancuso I have created a new [issue](https://github.com/checkstyle/checkstyle/issues/14415) as you suggested, can you check that out?

**Comment by nrmancuso** [comment]
Let’s edit this issue description to just have the premise that the Google style guide says that constructors should be ordered as such, but google_checks.xml shows no violations for this code. We don’t need to mention any specific check. Also please make sure to mention that you are using the latest checkstyle, and exactly which version. This is important since we package google_checks.xml with checkstyle.

Also, have we searched for existing issues that might mention this?

Thanks for taking the time to refine these issues!

**Comment by Zopsss** [comment]
> Let’s edit this issue description to just have the premise that the Google style guide says that constructors should be ordered as such, but google_checks.xml shows no violations for this code. We don’t need to mention any specific check. Additionally, please make sure to mention that you are using the latest checkstyle, and exactly which version. This is important since we package google_checks.xml with checkstyle.
> 
> Also, have we searched for existing issues that might mention this?
> 
> Thanks for taking the time to refine these issues!

Got it! I will update the description when I will get on my laptop and I've checked existing issues, they does not mention anything about the order of overloaded constructors

**Comment by Zopsss** [comment]
> Let’s edit this issue description to just have the premise that the Google style guide says that constructors should be ordered as such, but google_checks.xml shows no violations for this code. We don’t need to mention any specific check. Additionally, please make sure to mention that you are using the latest checkstyle, and exactly which version. This is important since we package google_checks.xml with checkstyle.
> 
> Also, have we searched for existing issues that might mention this?
> 
> Thanks for taking the time to refine these issues!

Got it! I will update the description when I will get on my laptop and I've checked existing issues, they does not mention anything about the order of overloaded constructors

**Comment by Zopsss** [comment]
fix is merged by: https://github.com/checkstyle/checkstyle/pull/14921
