### ISSUE TITLE
RequireEmptyLineBeforeBlockTagGroup bug

### ISSUE THREAD

**Issue by liudas-stonys** [checkstyle/checkstyle#14304]
Checkstyle fails for no reason. I've tried adding `<br>` with no luck... Please, help!

![image](https://github.com/checkstyle/checkstyle/assets/38351121/ff188a37-cdd7-4d97-9c4a-76587a7f6b05)

**Comment by nrmancuso** [comment]
Please follow the issue template.

**Comment by rnveach** [comment]
@liudas-stonys You might want to check if your issue is the same as https://github.com/checkstyle/checkstyle/issues/9685
