### ISSUE TITLE
Irrelevant Check inputs

### ISSUE THREAD

**Issue by sktpy** [checkstyle/checkstyle#14312]
While scoping out the Check inputs I observed that several of them were identical and irrelevant to the Check. ([Sample](https://github.com/checkstyle/checkstyle/blob/master/src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/parameternumber/InputParameterNumberSimple.java))

Running `grep -r "Contains simple mistakes" src/ | tee >(wc -l)` gives out **31** matches against that javadoc comment found in these inputs. [(Output sheet)](https://docs.google.com/spreadsheets/u/3/d/11HV4wQ8fWdRTPGUejQz3aegbC6A0xE9u9_mEpAU38xc/edit?usp=gmail)
**Note:** Sheet may not contain all the occurrence of this issue, as this relies on files containing that comment. There may exist those who haven't carried on this comment, or are based/copy of a different broader input suite.

The Check input in question contains input for variety of Checks like name format, accessor, method size etc. 

### Example:
[ParameterNumber](https://github.com/checkstyle/checkstyle/tree/master/src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/parameternumber) ([Documentation](https://checkstyle.org/checks/sizes/parameternumber.html#ParameterNumber)) ([Check test](https://github.com/checkstyle/checkstyle/blob/master/src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/ParameterNumberCheckTest.java))

**Check inputs with the issue:**
[InputParameterNumberSimple](https://github.com/checkstyle/checkstyle/blob/master/src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/parameternumber/InputParameterNumberSimple.java),[InputParameterNumberSimple2](https://github.com/checkstyle/checkstyle/blob/master/src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/parameternumber/InputParameterNumberSimple2.java),[InputParameterNumberSimple3](https://github.com/checkstyle/checkstyle/blob/master/src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/parameternumber/InputParameterNumberSimple3.java),[InputParameterNumberSimple4](https://github.com/checkstyle/checkstyle/blob/master/src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/parameternumber/InputParameterNumberSimple4.java)

**Rationale for why the files above contain irrelevant inputs:**
The check is for enforcing number of parameters of a method or constructor, but these inputs are related to various other checks like name format, method patterns, constants etc. bloating the inputs unnecessarily.

**Examples of unrelated input:**
```java
/** Invalid format **/
public static final int badConstant = 2;
```
```java
/** should be private **/
protected static int sTest3;
```

That being said, these check inputs may contain relevant inputs that are being used in the tests. 
In this example `void toManyArgs`, `test1` (although it was really meant for name format).

### Proposed fix:
Extract, refactor relevant inputs (if any), do the required changes in corresponding tests and discard the rest.

**Example of fix**: https://github.com/sktpy/checkstyle/commit/253ec97b81f978ab3c7dbe7f289c28ad196343ec
- Also fixes parts of [#11163](https://github.com/checkstyle/checkstyle/issues/11163) because every broader input suite based on "simple mistakes" is greater than 120 lines.

**Comment by rnveach** [comment]
I don't see this as being an easy issue, or sure how much sense it makes to do. Our mantra has always been to add new inputs and not remove or change old ones as they were added to cover some needed case.

> Check inputs I observed that several of them were identical and irrelevant 

This is expected. We use to have 1 input file used by many tests but with different configurations and violations reported. As we moved to BDD, we changed from "1 input for multiple tests" to "1 input per test" and the easiest way to do this was to duplicate the same file. The config is now in each input file at the top as a javadoc.

`InputParameterNumberSimple,InputParameterNumberSimple2,InputParameterNumberSimple3,InputParameterNumberSimple4` seems to prove my point. You can see the config at the top slightly changes between tests, but most of the java code itself is similar.

We also use regression and pitest in our project and sometimes finding a case to cover pitest usually is easier by copying part of an input from another check. Full inputs shouldn't be copied, but this can explain why some inputs are so similar.

If you start to modify our input files, pitest and other checks are the most likely culprits to impede progress. In that case, you'll either have to accept the input or do some type of deep dive to trim the input for what is critically needed.

**Comment by sktpy** [comment]
Thanks for the explanation. Had the feeling that I was missing something here, as this much volume couldn't have passed through code reviews without raising a flag.

**Comment by rnveach** [comment]
@sktpy Unless @romani says not too, I am not against you working on this issue. Just warning you why its like this and some difficulties you may face.

**Comment by romani** [comment]
I do not recommend to do this issue. Minimization  of test is tricky process, even CI see no difference it might be actual loss of coverage that will be visible in future.

Let's keep tests to be non optimal, the more the better, as  variants of writing code is uncountable.

We can remove tests that are completely duplicates, but if anything different between them let's keep it.

I am closing this issue but, if any obvious duplicates detected, we can fix them by referencing this issue.

**Comment by romani** [comment]
Referenced update is not actually good, as it implies knowledge on how Check is implemented and what it mostly should target, but from testing perspective we should prove that it is not match any possible comments with different values, so such extensive test file is valid no matter how you implement logic in Check .
