### ISSUE TITLE
upadat example in javadoc for EMBEDDED_EXPRESSION* tokens

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#14317]
from https://github.com/checkstyle/checkstyle/pull/13991#discussion_r1457520275

Update examples for:
EMBEDDED_EXPRESSION_BEGIN
EMBEDDED_EXPRESSION
EMBEDDED_EXPRESSION_END

from 
`String s = STR."Hello, \{getName(firstName, lastName)}!";`
to
`String s = STR."Hello, \{getName("Mr. ", firstName, lastName)}!";`

Reason: to show how `"` are rendered in tree  in `STR."`

**Comment by ViswanathBalla22** [comment]
Hello @romani,

I hope you're doing well! I'm a beginner eager to contribute to Datumaro, and I came across issue #14317 about updating examples for EMBEDDED_EXPRESSION* tokens in Javadoc.

This seems like a great opportunity for me to learn and make my first contribution. I'd love to take on this task and would appreciate any guidance or advice you can provide. If you're open to it, I'm ready to dive in and work on this.

Looking forward to your support and getting started on my first contribution.

**Comment by ViswanathBalla22** [comment]
Hi @romani,

I hope this message finds you well. I'm currently working on issue #14317 regarding the update to examples for EMBEDDED_EXPRESSION_BEGIN, EMBEDDED_EXPRESSION, and EMBEDDED_EXPRESSION_END tokens in the Javadoc.

I noticed that the examples provided in the issue seem to be the same:

Original:

from-
String s = STR."Hello, \{getName("Mr. ", firstName, lastName)}!";
to(same as original):
String s = STR."Hello, \{getName("Mr. ", firstName, lastName)}!";
Could you please provide additional details or clarify the expected changes? I want to make sure I address the issue correctly.

**Comment by romani** [comment]
Issue description is updated, that for pointing to problem.

Tre can be build by https://checkstyle.org/cmdline.html#Command_line_usage
"-t" parameters. 
As fix for new tokens is not released , please build all jar file by https://github.com/checkstyle/checkstyle/wiki/How-to-run-certain-phases-and-validations#how-to-generate-all-binaries-and--alljar--too

**Comment by ViswanathBalla22** [comment]
can you assign this issue to me

**Comment by nrmancuso** [comment]
@ViswanathBalla22 please send a pull request with your proposed changes, and we can go from there

**Comment by ViswanathBalla22** [comment]
hi @nrmancuso , @romani  I send pr check it . This is my first contribution in open source and really excited to do more, if any thing I did wrong give me guidance that will helpful

**Comment by ViswanathBalla22** [comment]
hi @nrmancuso  , @romani after pr send I seen that the fail in workflows what does it mean can you guide me how solve those.

**Comment by nrmancuso** [comment]
Closed via #14512
