### ISSUE TITLE
GenericWhitespace Check ignores exception to the ">" rule for succeeding whitespaces

### ISSUE THREAD

**Issue by sktpy** [checkstyle/checkstyle#14344]
Detected at [#14341](https://github.com/checkstyle/checkstyle/pull/14341).
Affects PR #14364 

([Documentation](https://checkstyle.org/checks/whitespace/genericwhitespace.html))

**Test.java**
```java
import java.util.ArrayList;
import java.util.List;

public class Test {
  List a = new ArrayList<> (); // violation expected
}
```

**config.xml**
```xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
  <module name="TreeWalker">
    <module name="GenericWhitespace"/>
  </module>
</module>
```

**Actual:**
```
java -jar checkstyle-10.12.7-all.jar -c config.xml Test.java
Starting audit...
Audit done.
```

**Expected:** violation on line 5.
`Test.java:5:26: '>' is followed by whitespace. [GenericWhitespace]`

### Explanation:
- As per the documentation, right angle bracket (`>`) should not be followed by whitespace for diamond operators and when preceding method name or constructor.
- In `List a = new ArrayList<> ();` the right angle bracket (`>`) precedes the constructor, and is also part of the diamond operator (`<>`), hence shouldn't be followed by the whitespace.
- The exact example is provided provided in the [documentation](https://checkstyle.org/checks/whitespace/genericwhitespace.html#Example2-code), showcasing that it is incorrect style and should throw a violation, but this is ignored by the Check. (Also evident in the [referenced PR](https://github.com/checkstyle/checkstyle/pull/14341#issuecomment-1907645027))

**Comment by MANISH-K-07** [comment]
@sktpy , I understand that the Checkstyle style mentions the said violation and the same has not been implemented. But does the Sun Java style guide and the Google Java Style Guide also include the whitespace as a violation?? If yes, please attach a snapshot of the rule for reference. If not, perhaps that is why the violation has been ignored so far!!

Thanks.
And also do correct me in case I am wrong.

**Comment by sktpy** [comment]
While Google's Java Style does have an explicit example stating that this exact thing is not allowed, the do say this about [Horizontal whitespace](https://google.github.io/styleguide/javaguide.html#s4.6.2-horizontal-whitespace):
> "Beyond where required by the language or other style rules, and apart from literals, comments and Javadoc, a single ASCII space also appears in the following places **_only_**."

And, in the list of examples that are provided where the space can appear, this case is not one of them.

And, as per the Checkstyle documentation this rule adheres to the "typical convention":
> "Checks that the whitespace around the Generic tokens (angle brackets) "<" and ">" are correct to the **_typical convention_**. The convention is not configurable."

**Comment by sktpy** [comment]
I am on it
