### ISSUE TITLE
Expanding maxmem to resolve OOM Exception (Checker checks)

### ISSUE THREAD

**Issue by MANISH-K-07** [checkstyle/checkstyle#14346]
Identified in various random PRs
for example [Issue #11163: Enforced file size commentsindentation #14338
](https://github.com/checkstyle/checkstyle/pull/14338)
![image](https://github.com/checkstyle/checkstyle/assets/148562451/1601ccda-c6e5-4bbf-8bbb-363a505bb4e8)

As per my observations, the build is a clean success and the problem with Checker checks does not show on my local system.
I'm not sure if this is relevant but my system has JDK x64 bit and I have preset the heap size of JVM to 8192m.
I agree that the failing CI on the server is a huge pain and needs to be resolved asap.

![image](https://github.com/checkstyle/checkstyle/assets/148562451/1201215d-d7f4-40f7-8df0-ebae4ec9a78d)

Ever since the OOM exception started to pop up, I have tried to find a workaround by searching for all possible alternatives to resolve this issue and in the process read the [Oracle Java Documentation](https://docs.oracle.com/javase/8/docs/technotes/guides/troubleshoot/memleaks002.html). After a bit of understanding, the only thing that came to my mind was to expand the memory size of the JVM's heap. The [OOM exception/issue](https://github.com/checkstyle/checkstyle/actions/runs/7630359181/job/20785856626?pr=14338#step:6:101) at hand is the result of the Gc using up >98% of the mem.
As per my understanding of the [pom.xml](https://github.com/checkstyle/checkstyle/blob/master/pom.xml) , the preset initialmem and maxmem for the Checker checks are 1024m & **_4048m_** respectively, which obviously is the root cause of the problem at present. You can check the below snap, which is one of the examples..

![image](https://github.com/checkstyle/checkstyle/assets/148562451/3525835a-4d61-4611-8574-6994c2f62208)

**_Proposed fix :_**
I think expanding the maxmem to higher size (like 8192m as in my local system or whatever limit that you recommend) is most likely to resolve this issue. This can be implemented only for the Checker check(index), as it is the constantly failing check or since like in the current PR where few other Checker checks are also throwing the same said exception unexpectedly, the mem can be expanded for the framework completely (all 8 checks).
I can try to implement the said fix by changing the preset maxmem for Checker Framework so that this is of no longer concern to the project.

**Comment by rnveach** [comment]
This is only a solution if the CI allows expansion to 8 gigs. There is going to be a limit at some point. We won't know though until we try.

**Comment by MANISH-K-07** [comment]
> This is only a solution if the CI allows expansion to 8 gigs. There is going to be a limit at some point. We won't know though until we try.

Hey @rnveach 
I couldn't agree more, and that is precisely why I haven't proceeded with larger expansion. However, if even 8g isn't allowed, I will try reducing the heap size again.

As the problem at hand is due to the Gc using up 98% of 4 gigs, even an expansion of 1g should workout just fine. Again, I agree that this isn't a permanent solution, but it might hold on well enough for a very long time if it works, considering that I have doubled the maxmem.

I have created a PR referencing this. It would be great if you could have a look at it and suggest!!

**Comment by nrmancuso** [comment]
We need to use visualvm and determine why we are consuming so much heap memory. Additionally, we should also share our findings with Checker maintainers.

**Comment by romani** [comment]
Let's fix our CI first, and then all other investigation items
