### ISSUE TITLE
Fix the violations in Release notes

### ISSUE THREAD

**Issue by mahfouz72** [checkstyle/checkstyle#14374]
detected at #14372
the Relase 10.13.0 has a violations in line 50 and 55 `line length is longer than 100 symbols`

![Screenshot 2024-01-28 174300](https://github.com/checkstyle/checkstyle/assets/125591358/cdf79dac-7636-41e6-81ed-8623e90fd8a2)

**Comment by rnveach** [comment]
It should be fixed in master now with https://github.com/checkstyle/checkstyle/commit/50683f10e9d33649dd8d1c42fe0549c003cedccd . Let us know, otherwise please close the issue.

**Comment by Vyom-Yadav** [comment]
@rnveach Shouldn't we be fixing this in the generator itself?

**Comment by rnveach** [comment]
@Vyom-Yadav It is an issue at https://github.com/checkstyle/contribution/issues/813 . Anyone is free to go and fix it if they want.
