### ISSUE TITLE
FallThroughCheck handle finally incorrectly

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#1438]
Code:
`````
package test;

public class TestClass3 {
	enum Test {
		A, B, C
	}

	public static void test() {
		Test test = Test.B;
		int variable = 0;

		switch (test) {
		case A:
			try {
			}
			catch (Exception e) {
			}
			finally {
				break;
			}
		case B:
			try {
				break;
			}
			catch (Exception e) {
				break;
			}
			finally {
			}
		case C:
			break;
		}
	}
}
`````
Config:
`````
<module name="Checker">
	<property name="charset" value="ASCII" />
	<property name="severity" value="error" />
	<property name="fileExtensions" value="java" />
	
	<module name="TreeWalker">
		<module name="FallThrough">
            <property name="reliefPattern" value="no break here" />
        </module>
	</module>
</module>
`````
Output:
`````
Starting audit...
\TestClass3.java:30:17: Fall through from previous branch of the switch statement.
Audit done.
Checkstyle ends with 1 errors.
`````

Sorry for being late with more issues with this check.
Both A and B cases in the switch are fully terminated, but codestyle says case B isn't fully terminated. It's flaw is that it believes the "finally" section should be the only area to examine, and overrides anything that the try/catch do. if the "finally" section is terminated (thought this is bad practice), then it does override the try/catch. If it doesn't, it should fall back on the termination checks of try/catch.

Source involved:
https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/FallThroughCheck.java#L264

**Comment by romani** [comment]
That cases should be supported only in case if that will not damage performace dramatically. To cheat Checkstyle is not complicated task for any Check, that is not our target to catch any possible case, it is ok to skip validation if code is complicated.

**Comment by romani** [comment]
merged.
