### ISSUE TITLE
HideUtilityClassConstructor - Add option to skip validation based on list of annotations

### ISSUE THREAD

**Issue by JoseLion** [checkstyle/checkstyle#14424]
I have read check documentation: https://checkstyle.org/checks/design/hideutilityclassconstructor.html
I have downloaded the latest cli from: https://checkstyle.org/cmdline.html#Download_and_Run
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

**How it works Now:**
As discussed in #5434, the `HideUtilityClassConstructorCheck` can benefit from an option that allows a list of annotations to skip/ignore the validation. This is especially useful when using frameworks with context containers and dependency injection, like Spring and OSGi implementations.

An example of how it's working now is a simple Spring Boot application class. Because the class only contains the static `main(..)` method, the rule expects the class to be `final` and a private/protected constructor to hide the default one. It's not possible to make the class final or the constructor public on the Spring Boot application class because Spring needs to create an instance of it to start the application.

**Is your feature request related to a problem? Please describe.**
Classes with specific annotations should not be final or hide the default constructor because they need to be instantiated later by some framework like Spring or OSGi implementations. Allowing to easily suppress the `HideUtilityClassConstructor` check when these annotations are present in the class can solve this problem.

**Describe the solution you'd like**
Add an option to the `HideUtilityClassConstructor` check that allows the define a list of annotations that skips/ignore validation.

new property should be named `ignoreAnnotatedBy` , as we did at https://github.com/checkstyle/checkstyle/pull/14553

```
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC "-//Puppy Crawl//DTD Check Configuration 1.3//EN" 
     "http://checkstyle.sourceforge.net/dtds/configuration_1_3.dtd">
<module name="Checker">
    <module name="TreeWalker">
        <module name="HideUtilityClassConstructor" >
            <property name="ignoreAnnotatedBy" value="SpringBootApplication,MySomeOther">
         </module>
    </module>
</module>
```

```
package biz.gabrys.agabrys.sonarqube.falsepositives.d20180106;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * @see https://github.com/checkstyle/checkstyle/issues/5434
 */
@SpringBootApplication
public class HideUtilityClassConstructorCheck {

    public static void main(String[] args) {
        SpringApplication.run(HideUtilityClassConstructorCheck.class, args);
    }
}
```

Expected: no violation.

**Additional context**
So far, one workaround is to add an XPath suppression. However, the query is a bit hard to implement and understand, and adding extra annotations makes the query bigger and not so easy to maintain. Here's an example of the XPath suppression that works for the `@SpringBootApplication` annotation:

```xml
<module name="SuppressionXpathSingleFilter">
  <property name="files" value="\.java$" />
  <property name="checks" value="HideUtilityClassConstructor" />
  <property name="query" 
    value="//CLASS_DEF[./MODIFIERS[./ANNOTATION[./IDENT[@text='SpringBootApplication']]]]" />
</module>
```

**Comment by romani** [comment]
new property should be named `ignoreAnnotatedBy` , as we did at https://github.com/checkstyle/checkstyle/pull/14553

```
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC "-//Puppy Crawl//DTD Check Configuration 1.3//EN" "http://checkstyle.sourceforge.net/dtds/configuration_1_3.dtd">
<module name="Checker">
    <module name="TreeWalker">
        <module name="HideUtilityClassConstructor" >
            <property name="ignoreAnnotatedBy" value="SpringBootApplication,MySomeOther">
         </module>
    </module>
</module>
```

```
package biz.gabrys.agabrys.sonarqube.falsepositives.d20180106;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * @see https://github.com/checkstyle/checkstyle/issues/5434
 */
@SpringBootApplication
public class HideUtilityClassConstructorCheck {

    public static void main(String[] args) {
        SpringApplication.run(HideUtilityClassConstructorCheck.class, args);
    }
}
```

Expected: no violation.

**Comment by romani** [comment]
@nrmancuso , please review and approve if you agree with design.

**Comment by nrmancuso** [comment]
We can also start with simple implementation here (exact match), as we did in https://github.com/checkstyle/checkstyle/pull/14553, and extend check to handle imports as needed later.

**Comment by Lmh-java** [comment]
Hi, I would like to work on this
