### ISSUE TITLE
Rename Java Input files and test methods to specify Test functionality

### ISSUE THREAD

**Issue by MANISH-K-07** [checkstyle/checkstyle#14436]
Response to discussion at  https://github.com/checkstyle/checkstyle/pull/14369#discussion_r1469873309

Findings from PR #14369 : 

[Input file](https://github.com/checkstyle/checkstyle/blob/master/src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocvariable/InputJavadocVariableOnInnerClassFields.java) -
```
public class InputJavadocVariableNoJavadocOne          //naming like '1' or 'One' need to be omitted
public class InputJavadocVariableOnInnerClassFields    //preferred based on test functionality
```
[Test Method](https://github.com/checkstyle/checkstyle/blob/master/src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocVariableCheckTest.java) - 

```
@Test
public void testScopesOne() {                              //naming like '1' or 'One' need to be omitted
public void testJavadocVariableOnInnerClassFields() {      //preferred based on test functionality
```

Nonsense test method/input file naming conventions like this need to be avoided. We must come up with some descriptive name to differentiate these tests, considering the content and their functionality. Naming conventions like "`........One`" in both test method names and test inputs are being followed at present which tell us nothing about the purpose of a given test. Imagine that it is required to come back to this test class in near future. Why does this test exist? What did the author want to validate? 

**_A precise naming convention needs to be enforced to give a better idea of what we are testing, without even needing to open up the input file and inspect the configuration and code. Precise naming as mentioned above is an outcome of clear understanding of the check and what it tests, it's functionality or purpose._** 

Fixing all the Java Input files in checkstyle is possible only through active contributions. So, first of all, a huge Thanks to every new contributor. If you are looking forward to working on this issue, **_be sure to analyze the test and look at the example PR :_** 

`Examples of ideal updates` : 

- https://github.com/checkstyle/checkstyle/commit/6d4fe4f19264b5e4f47fe3cbdc3015f61c7a8c58
- https://github.com/checkstyle/checkstyle/commit/b08ea45624d10cd6a3eac7da8c902de3dbb98f8c
- https://github.com/checkstyle/checkstyle/commit/8673001d9b0edacfa0d54bec85b26db46d1cce4d

`Each PR must contain one complete module with all existing filenames and test method names analysed and renamed.`
In update, naming should be such that,  just by looking at the names, anyone can figure out what the test validates from input file without even having to open it.

Test method name and input file name should be similar and describe what we are testing. Example from link above:

- Test method name is `testJavadocVariableOnInnerClassFields`
- Input file name is `InputJavadocVariableCheckOnInnerClassFields`.java

**Update in compliance with https://github.com/checkstyle/checkstyle/issues/6207#issuecomment-522812303 :**  Input files should be named in the pattern  **"Input{CheckName}`Check`Xxxx.java"** . Here, the word "check" is stressed upon for all renamed input files of [src/test](https://github.com/checkstyle/checkstyle/tree/master/src/test) path.

Thanks a lot !!

**Comment by nrmancuso** [comment]
@MANISH-K-07 how will we find such test methods and input files? How can we prevent this from happening in the future? If we can't automate some solution for this, I can tell you that we will not be able to always remember this.

**Comment by MANISH-K-07** [comment]
> how will we find such test methods and input files?

I could manually list-out the modules which consist of badly named Input files as part of Issue description.

> How can we prevent this from happening in the future? If we can't automate some solution for this, I can tell you that we will not be able to always remember to use good naming practices.

One thing that we already did is update the #11163 description asking the future PRs to follow suggested naming convention. 
Coming to the automation part.... I am not fondly familiar with something of that high level as I am still learning on the go !!

Would it be possible to automate this ?.. If yes, what would we actually be checking for ?
I mean how could we fix the check to follow a specific naming pattern when the input files and tests are so diverse ?

Sorry if I am going overboard with the questions  :)
There is one thing I could do to handle this at present. I could manually review all PRs concerning this issue before maintainers need to get involved so that good naming practice is ensured and your time doesn't get wasted ?

**Comment by nrmancuso** [comment]
Please keep communication in PRs and issues short and concise. Your comment at https://github.com/checkstyle/checkstyle/issues/14436#issuecomment-1931281522 can basically be summed as "I don't know".

> I could manually review all PRs

As stated at https://github.com/checkstyle/checkstyle/issues/14436#issuecomment-1931260984, this will not be an option. if something can't be completely automated, it's just not going to happen consistently.

**Comment by MANISH-K-07** [comment]
Sorry about that....

If you could guide me on how to proceed, I will work on implementing automation.
Just a basic idea on how to get started should help a lot

**Comment by nrmancuso** [comment]
Research similar issues in our issue tracker to get some ideas of what we could do here.

**Comment by romani** [comment]
I approved issue to fix what we detected manually.

**Comment by MANISH-K-07** [comment]
> I approved issue to fix what we detected/detecting manually. It can be long ongoing issue with many PRs

That was the idea, yes
:)

**Comment by MANISH-K-07** [comment]
I am on AnnotationOnSameLineCheckTest

**Comment by abhishekmaity** [comment]
I'm working on `InnerAssignmentCheckTest`

**Comment by abhishekmaity** [comment]
@romani @nrmancuso @MANISH-K-07  in connection with `InnerAssignmentCheckTest` what is the use of [InputInnerAssignmentDemoBug1195047Comment3.java](https://github.com/checkstyle/checkstyle/blob/master/src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/innerassignment/InputInnerAssignmentDemoBug1195047Comment3.java). I did not find its usefulness. Please enlighten me, if I missed anything or got it wrong.

**Comment by MANISH-K-07** [comment]
> @romani @nrmancuso @MANISH-K-07 in connection with `InnerAssignmentCheckTest` what is the use of [InputInnerAssignmentDemoBug1195047Comment3.java](https://github.com/checkstyle/checkstyle/blob/master/src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/innerassignment/InputInnerAssignmentDemoBug1195047Comment3.java). I did not find its usefulness. Please enlighten me, if I missed anything or got it wrong.

Said file [InputInnerAssignmentDemoBug1195047Comment3.java](https://github.com/checkstyle/checkstyle/blob/master/src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/innerassignment/InputInnerAssignmentDemoBug1195047Comment3.java) was created as part of PR #14307.
@sktpy , is there any specific reason for the odd naming of the file ??

The check actually checks for Except for the loop idioms, all assignments should occur in their own top-level statement.
This input file is testing for the same in loops and conditionals. 
I would suggest a name like : `InputInnerAssignmentCheckLoopsAndConditionals`.java

@abhishekmaity , 
the purpose of this issue is to browse through such oddly named files and rename them according to test functionality.
Please look at the description to find examples of updates.

**Comment by sktpy** [comment]
> is there any specific reason for the odd naming of the file ??

https://github.com/checkstyle/checkstyle/blob/7b4188aa270234d5701be2981d322bc19ed91b21/src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/InnerAssignmentCheckTest.java#L61

@MANISH-K-07 @abhishekmaity  The original input which was split into the other file to enforce file size was enclosed in the method `demoBug1195047Comment3()`, the new file which was created as the result of this split contained only this method. hence the corresponding test and the Input were named after it.
If you want to change the file name, first investigate why the method in the input was named `demoBug1195047Comment3()`.

**Comment by MANISH-K-07** [comment]
> If you want to change the file name, first investigate why the method in the input was named demoBug1195047Comment3().

Well, I couldn't find any possible explanation or reason to retain the name.
@abhishekmaity , 
proceed with the naming changes in your PR. Let's see if the maintainers suggest otherwise and can modify then if required....

**Comment by abhishekmaity** [comment]
I have renamed
 `InputInnerAssignmentDemoBug1195047Comment3.java` -> **InputInnerAssignmentCheckLoopsAndConditionals.java** 
and 
`demoBug1195047Comment3()` -> **checkLoopsAndConditionals()**

@romani @nrmancuso please review the PR #14543

**Comment by CubeTures** [comment]
Regarding the magicnumber checks: why are they split up into multiple files? The names are specific with files such as InputMagicNumberIgnoreFieldDeclaration and InputMagicNumberIgnoreHashCodeMethod, but then they are all split into 1, 2, and 3 (InputMagicNumberDefault1, InputMagicNumberDefault2, InputMagicNumberDefault3). Is there any specific reason for this?

**Comment by CubeTures** [comment]
I am on InputMissingCtor

**Comment by MANISH-K-07** [comment]
> Regarding the magicnumber checks: why are they split up into multiple files? The names are specific with files such as InputMagicNumberIgnoreFieldDeclaration and InputMagicNumberIgnoreHashCodeMethod, but then they are all split into 1, 2, and 3 (InputMagicNumberDefault1, InputMagicNumberDefault2, InputMagicNumberDefault3). Is there any specific reason for this?

@CubeTures ,
The input files have been split into smaller files as part of issue #11163 to restrict the files to a maximum size of 120 lines.
If you are planning on working on that module as part of this issue, try to analyse each file and keep the naming as accurate as possible. Feel free to reach out in case you need assistance.

**Comment by CubeTures** [comment]
> @CubeTures , The input files have been split into smaller files as part of issue #11163 to restrict the files to a maximum size of 120 lines. If you are planning on working on that module as part of this issue, try to analyse each file and keep the naming as accurate as possible. Feel free to reach out in case you need assistance.

I think I'll leave that test for someone else to take. I can't think of any good names for the files  themselves. You'd probably want to move some of the code around if you want to give the files a better name.

I also just wanted to note while we're changing the regular test names, were aren't changing the names of tests in SuppressionXPathFilter. We'll probably want to change all of those to fit the new names we're giving them here at some point, too.

**Comment by MANISH-K-07** [comment]
> I can't think of any good names for the files themselves. You'd probably want to move some of the code around if you want to give the files a better name.

@CubeTures , It is okay to update the input files to match violations testing similar functionality to organize them better.
However, it must be taken care that we don't lose any code or config.

> were aren't changing the names of tests in SuppressionXPathFilter. We'll probably want to change all of those to fit the new names we're giving them here at some point, too.

Could you point out to some examples of such tests ??

**Comment by CubeTures** [comment]
> Could you point out to some examples of such tests ??

Yeah.
In src/it/java/org/checkstyle/suppessionxpathfilter/XpathRegressionMissingCtorTest, we can see the test files run the tests. They haven't changed their names for the tests there. (XpathMissingCtor still lists tests as one, two, etc.)
Additionally, in src/it/resources/org/checkstyle/suppressionxpathfilter/missingctor, we can see how the test files haven't been changed either and still have their old, uninformative names.

I only noticed this since I was trying to learn how to create XPath Regression tests for Issue #6207.

**Comment by abhishekmaity** [comment]
I'm on MagicNumberCheckTest

**Comment by abhishekmaity** [comment]
I'm on NestedForDepthCheckTest

**Comment by romani** [comment]
I want to re-question necessity of this issue.
detected at https://github.com/checkstyle/checkstyle/pull/14633/files#diff-624d1aa1b8e49bbaed857fe116c7d91c06325ed8c348393eab80a03a5e6b1f87R17

```
- public class InputMagicNumberDefault3 {
+ public class InputMagicNumberCheckHashCodeValue {
```
InputMagicNumberCheckHashCodeValue is not valid name as there bunch of other test input code. We do not group code in Inputs by meaning, it is just a placeholders that are limited to 120 lines. that is why we got such indexes 1,2,3 . as has to  split files, and there is no good name, for just another input code for default config. When we need to add few lines, contributr can create new file or reuse existing.
Is there good naming for numerous names for default?

**Comment by rnveach** [comment]
I also want to remind that longer file names is not always good. Windows constraints is putting some of its users on edge of not being able to clone the repo.
https://github.com/checkstyle/contribution/issues/840

**Comment by romani** [comment]
I see how people are struggling to do updates for this issue.

I also struggling to suggest better name.

I don't see future of such updates. All existing are ok to stay as is. New inputs we will try to request better names.

If we will find good pattern we will reopen this issue
