### ISSUE TITLE
Add ImportOrder check to default configuration on Checkstyle

### ISSUE THREAD

**Issue by ivanov-alex** [checkstyle/checkstyle#1448]
ImportOrder check is not used in default configuration on Checkstyle.
It should be added.

We should also try to minimize amount of conflicts with default configurations of formatters in most common IDEs (Eclipse, IDEA, NetBeans) or advise how formatter settings should be configured to minimize (optimally avoid) conflicts with ImportOrder.

**Comment by MEZk** [comment]
That would be right. For those who uses IntelliJ IDEA required settings (after we'll decide how to configure ImportOrder) will be:
1) Deselect ```optimize imports```
![optimize imports](https://cloud.githubusercontent.com/assets/7242568/8820272/9b53a4e4-305c-11e5-9389-efc746e64166.png)
2) Select ```Use single class import``` and ```Use fully qualified class names```. Section ```Import Layout``` will help to organize the order of imports for ImportOrderCheck.
![screenshot](https://cloud.githubusercontent.com/assets/7242568/8820271/9b537dca-305c-11e5-8338-d395784ebf20.png)

**Comment by romani** [comment]
That is also required to forbid Idea to use star imports.

**Comment by ivanov-alex** [comment]
"Organize Imports" in Eclipse.
To change settings of "Organize Imports" feature, please go to Window -> Preferences.
In Preferences window select Java->Code Style->Organize Imports.
Default configuration should look as following:
![EclipseDefaults](https://cloud.githubusercontent.com/assets/3833078/8834368/7ec65316-30bc-11e5-85e9-f817d0c5adc3.jpg)
We are going to configure ImportOrder to work with default configuration of Eclipse because it works not perfect and sometimes sorts imports in a not obvious way. So we would like to minimize changes to this configuration because we suppose that changed configuration may have even greater flows.

ImportOrder configuration:
```xml
<module name="ImportOrder">
    <property name="groups" value="/^javax?\./,org"/>
    <property name="ordered" value="true"/>
    <property name="separated" value="true"/>
    <property name="option" value="top"/>
    <property name="sortStaticImportsAlphabetically" value="true"/>
</module>
```

Known issues:
1) it looks like Eclipse pays no attention to presence of "com" in configuration. We expect that all non-mentioned imports will go after "com", but quite often Eclipse inserts them before. That's why we don't have "com" on a list of groups.
2) Eclipse inserts imports from "nl.jqno.equalsverifier" package before "org" section. It require manual adjustment.

**Comment by ivanov-alex** [comment]
Intellij IDEA settings:
Go to: File->Settings
then in the tree go to: Editor->Code Style->Java
open Import tab and make following settings:
![IDEA settings](https://cloud.githubusercontent.com/assets/3833078/8843671/32ce48b2-3114-11e5-9fe4-5a587e59db99.jpg)
In "Import Layout" on the bottom configure as following:
![IDEA Import Order](https://cloud.githubusercontent.com/assets/3833078/8843722/18867230-3115-11e5-8189-9ab28b9eb867.jpg)

Link: http://stackoverflow.com/questions/14716283/is-it-possible-for-intellij-to-organize-imports-the-same-way-as-in-eclipse

**Comment by ivanov-alex** [comment]
NetBeans settings:
On menu select Tools->Options
On Options page go to Editor->Formatting->Java->Imports (see image with markers) and set properties as marked in magenta rectangles.
![NetBeans properties](https://cloud.githubusercontent.com/assets/3833078/8867735/3ee899dc-31d6-11e5-97aa-f57ee4f44ba4.jpg)

**Comment by romani** [comment]
merged.
