### ISSUE TITLE
update TokenTypes.java to new format of AST print

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#14516]
We need to update https://checkstyle.sourceforge.io/apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html to reflect the current printed  abstract syntax tree representation.

Example of old style (note the `+` and lack of `->`):
```
 +--LITERAL_NEW (new)
     |
     +--LITERAL_FLOAT (float)
     +--ARRAY_DECLARATOR ([)
     +--ARRAY_INIT ({)
         |
         +--EXPR
             |
             +--NUM_FLOAT (3.0f)
         +--COMMA (,)
         +--EXPR
             |
             +--NUM_FLOAT (4.0f)
         +--RCURLY (})

```

Example of new style:
```
 LITERAL_NEW -> new
  |--IDENT -> ArrayList
  |--TYPE_ARGUMENTS -> TYPE_ARGUMENTS
  |   |--GENERIC_START -> <
  |   `--GENERIC_END -> >
  |--LPAREN -> (
  |--ELIST -> ELIST
  |   `--EXPR -> EXPR
  |       `--NUM_INT -> 50
  `--RPAREN -> )

```

Example of where we need to update: https://checkstyle.sourceforge.io/apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#PARAMETERS , there might be more, ABSTRACT, STRICTFP, LITERAL_NEW, SINGLE_LINE_COMMENT.

How to generate our AST via command line:
```
➜  src cat Test.java
public class Test {
    String s = "";
}
➜  src java -jar checkstyle-10.13.0-all.jar -t Test.java | sed 's/->/-\&gt;/g; s/\[[0-9]\+:[0-9]\+\]//g'
COMPILATION_UNIT -&gt; COMPILATION_UNIT 
`--CLASS_DEF -&gt; CLASS_DEF 
    |--MODIFIERS -&gt; MODIFIERS 
    |   `--LITERAL_PUBLIC -&gt; public 
    |--LITERAL_CLASS -&gt; class 
    |--IDENT -&gt; Test 
    `--OBJBLOCK -&gt; OBJBLOCK 
        |--LCURLY -&gt; { 
        |--VARIABLE_DEF -&gt; VARIABLE_DEF 
        |   |--MODIFIERS -&gt; MODIFIERS 
        |   |--TYPE -&gt; TYPE 
        |   |   `--IDENT -&gt; String 
        |   |--IDENT -&gt; s 
        |   |--ASSIGN -&gt; = 
        |   |   `--EXPR -&gt; EXPR 
        |   |       `--STRING_LITERAL -&gt; "" 
        |   `--SEMI -&gt; ; 
        `--RCURLY -&gt; } 
```

Note that this `sed` command escapes the `>` character and removes the line:column numbers for our documentation. Also, please be aware that we may need to update the existing code sample to be a bit more substantial.

For more details about Checkstyle's command line usage, see: https://checkstyle.org/cmdline.html#Command_line_usage

**Comment by romani** [comment]
@SteLeo1602, please help to resolve this issue.

**Comment by Coding-Aliens** [comment]
Can I work on it?

**Comment by romani** [comment]
@Coding-Aliens, you can , but I recommend you to take more complicated issues. Be aware of two PRs already in flight.
