### ISSUE TITLE
Update Codenarc to highest compatible release - v2.2.0

### ISSUE THREAD

**Issue by MANISH-K-07** [checkstyle/checkstyle#14556]
We are using an old version of codenarc. Latest release is 3.1.0, we are using `v1.4` right now.

From checkstyle/[codenarc.groovy](https://github.com/checkstyle/checkstyle/blob/master/.ci/codenarc.groovy) : 

```
@Grapes(
        @Grab(group='org.codenarc', module='CodeNarc', version='1.4')
)
```

https://github.com/CodeNarc/CodeNarc/releases

Findings from PR https://github.com/checkstyle/contribution/pull/836 that successfully closed Issue https://github.com/checkstyle/contribution/issues/757 : 
We cannot use the latest due to older groovy version used in CI and the groovy syntax used in our scripts. We have settled on `v2.2.0`

The version bump needs to be done in the main repo too.

**Comment by MANISH-K-07** [comment]
@nrmancuso , @romani 

Please review....

**Comment by romani** [comment]
We are not stuck on old version on codenarc, after this update, we can update to latest.

**Comment by nrmancuso** [comment]
> We are not stuck on old version on codenarc, after this update, we can update to latest.

@romani can you restate this? I am not sure that I understand if you want to do this in the scope of this issue or a new one.

**Comment by romani** [comment]
We can merge create new issue, to make it more clear why more code changes are required

**Comment by MANISH-K-07** [comment]
> We can merge create new issue, to make it more clear why more code changes are required

@romani ,
By "code changes", I believe you mean _migration of groovy_ ?
The findings from using different releases are mentioned in the discussion between me and @nrmancuso https://github.com/checkstyle/contribution/pull/836#issuecomment-1959421763

Should I create a new Issue to update to latest version with clear description of all errors and possible changes we may require ??

**Comment by MANISH-K-07** [comment]
> We can merge create new issue, to make it more clear why more code changes are required

@romani ,
By "code changes", I believe you mean _migration of groovy_ ?
The findings from using different releases are mentioned in the discussion between me and @nrmancuso https://github.com/checkstyle/contribution/pull/836#issuecomment-1959421763

Should I create a new Issue to update to latest version with clear description of all errors and possible changes we may require ??

**Comment by MANISH-K-07** [comment]
> We can merge create new issue, to make it more clear why more code changes are required

@romani ,
By "code changes", I believe you mean _migration of groovy_ ?
The findings from using different releases are mentioned in the discussion between me and @nrmancuso https://github.com/checkstyle/contribution/pull/836#issuecomment-1959421763

Should I create a new Issue to update to latest version with clear description of all errors and possible changes we may require ??

**Comment by MANISH-K-07** [comment]
> > We can merge create new issue, to make it more clear why more code changes are required
> 
> @romani , By "code changes", I believe you mean _migration of groovy_ ? The findings from using different releases are mentioned in the discussion between me and @nrmancuso [checkstyle/contribution#836 (comment)](https://github.com/checkstyle/contribution/pull/836#issuecomment-1959421763)
> 
> Should I create a new Issue to update to latest version with clear description of all errors and possible changes we may require ??

@romani , Can this issue be closed as completed via PR #14558 ?

**Comment by MANISH-K-07** [comment]
> We can merge create new issue, to make it more clear why more code changes are required

@romani , I think we are leaving this hanging..
Please confirm https://github.com/checkstyle/checkstyle/issues/14556#issuecomment-1971514863

**Comment by romani** [comment]
Let's create new issue with more clear goal

**Comment by MANISH-K-07** [comment]
> Let's create new issue with more clear goal

Sure !!
One issue with detailed requirements coming right up....

**Comment by MANISH-K-07** [comment]
> > Let's create new issue with more clear goal
> 
> Sure !! One issue with detailed requirements coming right up....

@romani , Issue created at #14680
