### ISSUE TITLE
Add 'just' support

### ISSUE THREAD

**Issue by nrmancuso** [checkstyle/checkstyle#14597]
It is difficult (and of dubious value) to remember all of our commonly used commands, aside from `mvn clean verify`: https://github.com/checkstyle/checkstyle/wiki/How-to-run-certain-phases-and-validations.

For example; why should we have to visit the wiki to find the command we are looking for, copy it, paste it into the terminal, and run it? These are commands after all, and should live in the project to be reused, easily updated, and in use so that they stay valid. Why should we have to point contributors to the wiki and make them do the same repetitive steps?

This is where [just](https://github.com/casey/just) comes in. `just` is a simple command line runner, similar to `make`, that we can use to easily run these commands as needed.  Now, if I want to run a command:

```
$ just --list
Available recipes:

    # runs all validations
    clean-verify
    
    # runs checkstyle ant phase
    ant-phase

    # generate all binaries
    package
  
    ...
```

It is easy to see all commands, and what they do. Now, if I want to run the checkstyle ant phase, I do:

```
 $ just ant-phase
```

That's it. We can also use `just` in scripts to avoid a lot of boilerplate for things like `mvn -e --no-transfer-progress clean install -Pno-validations`: `just install`.

If we approve and implement this issue, we can do some clean up and remove the corresponding wiki page. We also need to update our dev docs to point this tool out.

**Comment by nrmancuso** [comment]
> It is over kill, we already have all in shells simple executions

Please link to our shell script that has our ant phase, Jacoco (with generated classes), install, assemble, etc, that I can easily run to prevent me from constantly visiting the wiki.

**Comment by romani** [comment]
>Please link to the shell script that has our ant phase,

If you need this, just add it. It is same amount of effort to add it to just and to our validation.sh.

**Comment by nrmancuso** [comment]
@romani so, to be clear, you are good to extend validation.sh to include frequently used commands?

**Comment by romani** [comment]
Yes, even we do not use such tasks in Ci, I am good.

**Comment by nrmancuso** [comment]
>just make sense when there are numerous projects or different structures and build tools and numerous OS, ... And some person/team whants generalize operations across all of that variety

Hard disagree here, I feel like maybe you are not really familiar with this tool.


`just` makes sense any time we need to have some commands to run frequently, since you can simply type `just`, and it will display all the commands we use instead of visiting the wiki and copy-pasting, or looking through the validation.sh script to figure out which script to run. You literally have to remember nothing, except `just`. You don't have to remember that the commands are in a script file buried in the `.ci` directory (which doesn't really make sense), or how to find them in the wiki.

**Comment by romani** [comment]
`validation.sh --list`

**Comment by nrmancuso** [comment]
We will not use this tool, I am closing this issue.
