### ISSUE TITLE
License with explicit permission only for non-commercial use

### ISSUE THREAD

**Issue by rahulmohang** [checkstyle/checkstyle#14641]
Hi, 
 
Please excuse the failure to adhere to the template strictly. 

The license mentioned at https://github.com/checkstyle/checkstyle/blob/master/src/site/resources/styleguides/sun-code-conventions-19990420/Copyright.doc.html explicitly allows only non-commercial use. 

We intent to use this in our open source projects. However, we think that the end users of our software may find this license missing permission to use the files for commercial purposes.

**Comment by rahulmohang** [comment]
@rnveach, usually, "for your own internal use in a commercial setting" may be interpreted as 'use inside your company premises, but does not explicitly cover use in a product that is intended for distribution to customers'.  So, the question. 
However, as you pointed out, 'in a commercial setting' may be the differentiator when compared to other usual 'internal' use licenses. 
Was the intention of the statement to cover use cases that involves external distribution along with an end user's product?

**Comment by rahulmohang** [comment]
@rnveach, I am checking this in the context of usage of checkstyle in one of the projects in the Eclipse Foundation, Usually, projects under Eclipse Foundation will be used for commercial and non-commercial purposes including usage in a commercial product of a proprietary company.

**Comment by rnveach** [comment]
I assigned @romani as he is probably better able to handle licensing. I have thoughts on this issue, but I wasn't around when this file was created and don't know what the intention was versus what the language may cover (and may not cover).

**Comment by rahulmohang** [comment]
Ok

**Comment by romani** [comment]
This file was just copy from original location of sun guide, we cached it to make it more controlled. There is no value in it and we not own such style guide.

https://github.com/checkstyle/checkstyle/blob/master/src/site/resources/styleguides/sun-code-conventions-19990420/Copyright.doc.html

Is not part of any jar we distribute, I do not understand how you plan to use it in your projects. If you need our site files , please skip whole folder https://github.com/checkstyle/checkstyle/blob/master/src/site/resources/styleguides/

**Comment by rahulmohang** [comment]
Ok. I understand. Everyone who wants to contribute code to our project implicitly uses this, as it is integrated in our Gradle build. checkstyle, and by extension the checkstyle Gradle Plugin are not used at application runtime, but at compile time. It is neither distributed with the compiled JAR nor with the sources JAR. Nevertheless, I was trying to understand the license better. 

Thank you for the responses.

**Comment by romani** [comment]
Please close issue if you are satisfied with response

**Comment by rahulmohang** [comment]
Ok
