### ISSUE TITLE
Refactor AbstractModuleTestSupport and InlineConfigParser to support XML configs in Input files without extra detalization on modules

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#14653]
detected at https://github.com/checkstyle/checkstyle/pull/14462/files#r1521442922

When we use full XML config in header comment, we parse it, split by modules, and later on assemble back to `DefaultConfiguration`

parsing of full XML:
https://github.com/checkstyle/checkstyle/blob/2c00d23b49ebc1e5fd6ba0eaafc1df1cad5d145e/src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java#L238
```
if (isXmlConfig) {
            final String stringXmlConfig = LATEST_DTD + String.join("", inlineConfig);
            final InputSource inputSource = new InputSource(new StringReader(stringXmlConfig));
            final Configuration xmlConfig = ConfigurationLoader.loadConfiguration(
                inputSource, new PropertiesExpander(System.getProperties()),
                    ConfigurationLoader.IgnoredModulesOptions.EXECUTE
            );
```
resulted config is fully ready to be used in validation execution.

problem comes from `createConfigurationWithoutFilters` and other methods that are used not in general tests but in Filter tests:
https://github.com/checkstyle/checkstyle/blob/master/src/test/java/com/puppycrawl/tools/checkstyle/AbstractModuleTestSupport.java
```
    protected final void verifyFilterWithInlineConfigParser(String filePath,
                                                            String[] expectedUnfiltered,
                                                            String... expectedFiltered)
            throws Exception {
        final TestInputConfiguration testInputConfiguration =
                InlineConfigParser.parseWithFilteredViolations(filePath);
        final DefaultConfiguration configWithoutFilters =
                testInputConfiguration.createConfigurationWithoutFilters();
        final List<TestInputViolation> violationsWithoutFilters =
                new ArrayList<>(testInputConfiguration.getViolations());
        violationsWithoutFilters.addAll(testInputConfiguration.getFilteredViolations());
        Collections.sort(violationsWithoutFilters);
        verifyViolations(configWithoutFilters, filePath, violationsWithoutFilters);
        verify(configWithoutFilters, filePath, expectedUnfiltered);
        final DefaultConfiguration configWithFilters =
                testInputConfiguration.createConfiguration();
```

Detailed slicing and dicing by modules was required for property config in this case we need to recreate config and do bunch of assumptions on Checker and Treewalker. But in XML config all detals are provided, just use it as is.

Expected:
this code should not do any extra operations on config, and after parsing from xml should be used as is.
https://github.com/checkstyle/checkstyle/blob/2c00d23b49ebc1e5fd6ba0eaafc1df1cad5d145e/src/test/java/com/puppycrawl/tools/checkstyle/AbstractModuleTestSupport.java#L232-L238
instead of `createConfiguration()` we should have simple `getConfiguration()`

**Comment by Lmh-java** [comment]
I am working on it

**Comment by romani** [comment]
fix is merged
