### ISSUE TITLE
incompatibility with google-java-format: File Header not separated by blank line from package statement

### ISSUE THREAD

**Issue by sdavids** [checkstyle/checkstyle#14655]
```bash
/var/tmp $ curl -L -O -s https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.14.1/checkstyle-10.14.1-all.jar
/var/tmp $ curl -L -O -s https://github.com/google/google-java-format/releases/download/v1.21.0/google-java-format-1.21.0-all-deps.jar
/var/tmp $ printf '/* File header */\npackage p; class PackageHeader{}\n' > PackageHeader.java
/var/tmp $ cat PackageHeader.java                                                                                                                    
/* File header */
package p; class PackageHeader{}
/var/tmp $ java -jar google-java-format-1.21.0-all-deps.jar --replace PackageHeader.java
/var/tmp $ javac PackageHeader.java
/var/tmp $ cat PackageHeader.java
/* File header */
package p;

class PackageHeader {}
/var/tmp $ RUN_LOCALE="-Duser.language=en -Duser.country=US"
/var/tmp $ java $RUN_LOCALE -jar checkstyle-10.14.1-all.jar -c /google_checks.xml PackageHeader.java
Starting audit...
[WARN] /private/tmp/PackageHeader.java:2:1: 'package' should be separated from previous line. [EmptyLineSeparator]
Audit done.
```

---

Code formatted by `google-java-format` (the de-facto standard Google Java Style formatter) should be compatible with the `google_checks.xml` configuration out-of-the-box.

**Comment by romani** [comment]
Life is changing defacto :),  few years ago people told same about checkstyle config.

But lets look at style guide
https://google.github.io/styleguide/javaguide.html#s3-source-file-structure

>Source file structure
A source file consists of, in order:
License or copyright information, if present
Package statement
Import statements
Exactly one top-level class
Exactly one blank line separates each section that is present.

Pay attention to last sentence. How you can explain it ? May be we should open issue on google-java-format ?

**Comment by romani** [comment]
Life is changing defacto :),  few years ago people told same about checkstyle config.

But lets look at style guide
https://google.github.io/styleguide/javaguide.html#s3-source-file-structure

>Source file structure
A source file consists of, in order:
License or copyright information, if present
Package statement
Import statements
Exactly one top-level class
Exactly one blank line separates each section that is present.

Pay attention to last sentence. How you can explain it ? May be we should open issue on google-java-format ?

**Comment by sdavids** [comment]
https://github.com/google/google-java-format/issues/1084

**Comment by romani** [comment]
I think we are done here, we can reopen issue if new nuances comes up
