### ISSUE TITLE
Add `module-info.java`

### ISSUE THREAD

**Issue by sgammon** [checkstyle/checkstyle#14666]
**Is your feature request related to a problem? Please describe.**
I would like to use Checkstyle with `jlink`, but I can't because there is no `module-info.java`.

**Describe the solution you'd like**
I would like Checkstyle to ship with a `module-info.java`

**Additional context**
JDK8 compatibility can be retained by using [MRJARs](https://openjdk.org/jeps/238)

**Comment by rnveach** [comment]
There is no JDK 8 compatibility in this project.

**Comment by romani** [comment]
Is it same as https://github.com/checkstyle/checkstyle/issues/14120

**Comment by romani** [comment]
What is jlink ?

**Comment by MANISH-K-07** [comment]
> What is jlink ?

jlink tool is kind of partially similar to docker but exclusively for java. Like images to containers in docker, jlink generates a java image which usually contains modules that are required to run the application.

**Comment by romani** [comment]
https://docs.oracle.com/en/java/javase/11/tools/jlink.html
https://snyk.io/blog/jlink-create-docker-images-spring-boot-java/

**Comment by sgammon** [comment]
@rnveach Thanks that's a good point and should make things easier.

**Comment by romani** [comment]
Closed as duplicate of https://github.com/checkstyle/checkstyle/issues/14120

**Comment by sgammon** [comment]
@romani Why was this closed? An `Automatic-Module-Name` isn't the same as a `module-info.java`... it might be a duplicate of #14139?

**Comment by romani** [comment]
https://github.com/checkstyle/checkstyle/pull/14139 is Pull request for issue https://github.com/checkstyle/checkstyle/issues/14120

We closing your issue as duplicate, to keep all reasons in one place.

**Comment by sgammon** [comment]
Ah, understood @romani. Thank you for explaining 👍

**Comment by sgammon** [comment]
@romani If that PR gets stale please tag me, I would be happy to help.

**Comment by romani** [comment]
@sgammon , help is required.

**Comment by sgammon** [comment]
@romani I've started looking into this. Once I have a modular build working correctly, I will post it to the [JPMS Attic](https://javamodules.dev) repository where it can be tested easily with other libraries.

I've already done the work to ship modular Guava and other dependencies that Checkstyle needs. In fact, I'm using Checkstyle's build as an integration test against modular-enabled Guava and Protobuf. It's already passing.

So, doing the work to modularize Checkstyle, and then promoting it from a test in that repo to a library available in the JPMS Attic is not so hard.

I'll check back in when I have news which shouldn't be too long.

**Comment by cowwoc** [comment]
@sgammon Ping pong. Any update on this issue?

**Comment by sgammon** [comment]
@cowwoc fancy seeing you here 😄 after an office move, everything has fallen to the backburner. i can try and peek at this before the end of the week, ty for ping
