### ISSUE TITLE
Static MethodCount

### ISSUE THREAD

**Issue by xenoterracide** [checkstyle/checkstyle#14695]
My head hurts trying to describe this... I want a way to define how many static methods can exist on a utility class vs an instance class or other token as listed on https://checkstyle.org/checks/sizes/methodcount.html

Unfortunately `MethodCount` didn't choose differentiate between static and non static, or between utility classes and instance classes. This is hard to describe because I think What I want is a Token called `UTIL_CLASS_DEF` which probably doesn't work since it's not a real language construct (dear java).

Motivation for this is the number of static methods for a utility class is high, but for a regular class if you have more than a couple of public static (probably factory) methods, then your class is probably misdesigned.

Adding these properties and that token could work

| name	| description |	type |	default value |	since |
|-------|-------------|------|----------------|-------|
| maxStaticPackage |	Specify the maximum number of package methods allowed. |	[int](https://checkstyle.org/property_types.html#int)	| 100	| 5.3 |
| maxStaticPrivate |	Specify the maximum number of private methods allowed. |	[int](https://checkstyle.org/property_types.html#int) |	100 |	5.3 |
| maxStaticProtected	| Specify the maximum number of protected methods allowed. |	[int](https://checkstyle.org/property_types.html#int) |	100 |	5.3 |
| maxStaticPublic |	Specify the maximum number of public methods allowed. |	[int](https://checkstyle.org/property_types.html#int) |	100 |	5.3 |
| maxStaticTotal |	Specify the maximum number of public methods allowed. |	[int](https://checkstyle.org/property_types.html#int) |	100 |	5.3 |
| maxInstancePackage |	Specify the maximum number of package methods allowed. |	[int](https://checkstyle.org/property_types.html#int)	| 100	| 5.3 |
| maxInstancePrivate |	Specify the maximum number of private methods allowed. |	[int](https://checkstyle.org/property_types.html#int) |	100 |	5.3 |
| maxInstanceProtected	| Specify the maximum number of protected methods allowed. |	[int](https://checkstyle.org/property_types.html#int) |	100 |	5.3 |
| maxInstancePublic |	Specify the maximum number of public methods allowed. |	[int](https://checkstyle.org/property_types.html#int) |	100 |	5.3 |
| maxInstanceTotal |	Specify the maximum number of public methods allowed. |	[int](https://checkstyle.org/property_types.html#int) |	100 |	5.3 |
| type | utility or not selector |  list | utility,instance | |

A new check to replace the existing check could also work and at least simplify naming. Maybe 2 checks would work as a utility class should have 0 public and protected instance methods, possibly 0 entirely. The problem is that no matter what way I think to solve this it's a cartesian product of what's already there, you could add more checks, explode the properties.

**Comment by nrmancuso** [comment]
>I think What I want is a Token called UTIL_CLASS_DEF which probably doesn't work since it's not a real language construct (dear java).

We will not add this token, we try to follow the JLS as closely as possible (without too many breaking changes for past weirdness).

This sounds like a good candidate for [MatchXPathCheck](https://checkstyle.org/checks/coding/matchxpath.html#MatchXpath). @xenoterracide have you considered using this check? A good start might be to create an expression like "if a given class name does not contain "Util" and this class has more than 5 static methods, place a violation on the class".

**Comment by romani** [comment]
We will not add non java tokens.

>A new check to replace the existing check could also work and at least simplify naming.

We will not do this, sorry.
We more and more going bin direction to limit scope and target of Checks. To minimize amounts of properties, as combination of their values are hard to support.

You can archive easily what you need by writing your own Check and hosting it in your own repository.
https://checkstyle.org/writingchecks.html
Example of non standard Checks that live on a side of main project: https://github.com/sevntu-checkstyle/sevntu.checkstyle

There are more examples in web for team custom Checks.
