### ISSUE TITLE
Enforce new naming convention "InputXpath{Checkname}Xxxx.java" in IT area

### ISSUE THREAD

**Issue by MANISH-K-07** [checkstyle/checkstyle#14715]
Follow-up of #6981 

Until now, XpathRegressionTest validated the pattern `SuppressionXpathRegressionXxxx.java` for input filenames
All our existing files are named that way, so we bypass them until this issue is fixed.

The pattern has been updated to `InputXpath{Checkname}Xxxx.java` as part of PR #14713 
All existing modules have been suppressed from validation. 

As part of this issue, one module needs to be picked and all input files need to be renamed. Note that the xpath queries need to be verified in respective `XpathRegression{Checkname}Test` after filename change. Also, the set `RENAME_INPUT_XPATH` needs to be updated by removing the updated module to re-enable pattern validation.

The list of suppressions can be found at :
https://github.com/checkstyle/checkstyle/blob/cd1afd907ff8f80b2953617e736040642dc47a1d/src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java#L121-L261

Example of update : https://github.com/checkstyle/checkstyle/commit/e70b8b5814b67cfc2c3ac47cde84822895c399d6

**Comment by Kexin2000** [comment]
Because #14719  fixes the failing build in master, list in the first post does not have a MethodTypeParameterName. I am on that :)

**Comment by MANISH-K-07** [comment]
I am on VisibilityModifier

**Comment by romani** [comment]
@MANISH-K-07, I highly recommend to do fixes by packages or by packs of 20 files. to fnish this update quicker and not making a an epic from it.

**Comment by romani** [comment]
@MANISH-K-07 , please update issue description to reference list of suppression and do udpates based on it.
checkboxes will be a problem to maintain, as fix is easy

**Comment by Lmh-java** [comment]
I am on RecordTypeParameterName

**Comment by Lmh-java** [comment]
I am on AbbreviationAsWordInName

**Comment by romani** [comment]
@Lmh-java, we appreciate your help with easy issues, you are always welcome, but I recommend you next month to focus on more complicated issues to increase your chances to be selected to gsoc.

**Comment by MANISH-K-07** [comment]
@romani , like you said, let's not make an epic of this issue. I'll close this with multiple PRs at a time in 2 batches like @rnveach suggested at https://github.com/checkstyle/checkstyle/pull/14725#issuecomment-2024283600

**Comment by romani** [comment]
ok, lets let only @MANISH-K-07  to work on this issue.
