### ISSUE TITLE
Enhance Command Line documentation by organizing options in Tabular format

### ISSUE THREAD

**Issue by MANISH-K-07** [checkstyle/checkstyle#14759]
Extension of PR #14710 and response to https://github.com/checkstyle/checkstyle/pull/14710#discussion_r1550049366

Current cmdline docs : https://checkstyle.org/cmdline.html#Command_line_usage
Our command line options are bulleted under one section at present.

A better way of documenting for end users would be organizing all the available cmdline options in a Tabular format.
The table would consist of 2 columns (Titles can be "`Command Line Option`" and "`Description`" or decided further) 
and 18 rows for each of the 18 options that we host.

This format of documentation is the standard and can be found followed by Apache maven CLI options too
https://maven.apache.org/ref/3.6.1/maven-embedder/cli.html#

**Comment by MANISH-K-07** [comment]
> I think this would be fine, but I this would need to be an issue first to gain approvals from the others. @nrmancuso is already trying to rewrite other parts of our documentation, so I want to sure we align with his current thoughts.

I think @rnveach is on board with the proposal....
@nrmancuso , @romani , thoughts please ?

**Comment by nrmancuso** [comment]
I like tables, @romani please approve if you are good

**Comment by romani** [comment]
Yes, let's try table view.
Please make first column (or just  embed in name of parameter) to be anchor, let us make direct links to specific argument.

Example:
https://checkstyle.org/google_style.html#a2

**Comment by MANISH-K-07** [comment]
>  let us make direct links to specific argument.

@romani , I'm not sure what links are being referred to here? Are you asking that each option redirects to another page containing description? Because we don't host any existing html to these options as far as I know..

> Example:
> https://checkstyle.org/google_style.html#a2

The links here point to the check html page and google style guide page.
I'm not sure why we need embedded links in cmdline because it is just an option and respective description (2 plain columns)

Could you please elaborate on what your vision is? Or if I'm missing something?

**Comment by romani** [comment]
Google style has links to itself, to specific row.
When you click on anchor image, you got a link and you can share it with others, it will be a link to exact place, not a page in general

**Comment by romani** [comment]
consider https://checkstyle.org/property_types.html#Pattern.5B.5D as example, move mouse over title, anchor appears and by click you can get a link exactly to this item in huge whole page

**Comment by MANISH-K-07** [comment]
Yes @romani , your https://github.com/checkstyle/checkstyle/issues/14759#issuecomment-2039663201 was clear enough for me 😄

**Comment by romani** [comment]
Send PR, I will point what to do in PR

**Comment by MANISH-K-07** [comment]
@romani , @rnveach , I'm waiting on #14710 to get merged before we do this update....

**Comment by romani** [comment]
https://github.com/checkstyle/checkstyle/pull/14799 PR is abandoned, everyone in web welcome to reuse code from it and finish this issue
