### ISSUE TITLE
magic number detection: option to ignore magic numbers in field declarations

### ISSUE THREAD

**Issue by jh3141** [checkstyle/checkstyle#148]
It would be useful to have an option to ignore a magic number if it is an initializer in a field  declaration.  For example, I currently have the following code in one of my classes:

     private double bonus = 0.5;

I don't think any clarity is gained by declaring an additional constant to be used only for initializing this field, and I'm reasonably confident the same is true in most cases where a field is initialized directly to a constant like this.

**Comment by romani** [comment]
fixed, will be in 6.6
