### ISSUE TITLE
Please REMOVE most badges from the README

### ISSUE THREAD

**Issue by nbro** [checkstyle/checkstyle#14837]
It's so confusing. Please, put them at the end or in a dedicated section, but not at the beginning, or just remove most of them. Most people are only interested in badges that link to the documentation (I couldn't not find it - don't blame me because the README is too cluttered, even though it's short - well, that's an achievement!), the supported Java versions, and maybe the license. Well, at least, that's my case. We don't care about all the 10 different tools you use to develop. This is only useful for developers and I suppose most of them don't need to know this anyway.

**Comment by nrmancuso** [comment]
Hi @nbro, as I mentioned at https://github.com/checkstyle/checkstyle/issues/14838, I mostly agree that the badges are a bit noisy, however this is a common GitHub practice and is easily ignored. We won't be removing them, but thank you for the feedback.

**Comment by nbro** [comment]
Right, but you can move them to the end. What I'm saying is that too many badges at the beginning of the README makes it very confusing to newcomers, like mew. Alternatively, if you still want to keep them at the beginning, you could put them or most of them in `<details> here go the badges </details>`

**Comment by romani** [comment]
We will keep it for now on top, but this issue will collect feedback from users, if amount of user who supports your idea be significant , we can reconsider our decision.
