### ISSUE TITLE
Test to ensure website checks/filters are in alphabetical order

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#14840]
Identified at https://github.com/checkstyle/checkstyle/pull/14643#discussion_r1583427852 ,

We need to create a test to ensure [the list of checks, filters and their group names ](https://github.com/checkstyle/checkstyle/blob/c932f533f9dcbf64c09a5ca5f5905402a255b766/src/site/site.xml#L79-L340) for our website are in alphabetical order.

UPDATE: some sorting is split to https://github.com/checkstyle/checkstyle/issues/16013

**Comment by mohitsatr** [comment]
will it be a CI test or normal test?

**Comment by romani** [comment]
Just normal test of Junit. It will be executed in CI with all other tests.
