### ISSUE TITLE
build failure due to maven.plugin.json

### ISSUE THREAD

**Issue by mahfouz72** [checkstyle/checkstyle#14853]
mvn verify is falling in master because json schema used in the json-schema-validator plugin is not found
https://github.com/checkstyle/checkstyle/blob/bb56e9de12e0f42c0188eb2a6cad839404d408c1/pom.xml#L1900
`Could not find resource https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Documents/CommitteeSpecifications/2.1.0/sarif-schema-2.1.0.json .`

the URL may be outdated or the schema file might have been moved to a different location

link: https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Documents/CommitteeSpecifications/2.1.0/sarif-schema-2.1.0.json 
Error 404

**Comment by mahfouz72** [comment]
closed after https://github.com/checkstyle/checkstyle/pull/14854

**Comment by mahfouz72** [comment]
closed via https://github.com/checkstyle/checkstyle/pull/14854

**Comment by rnveach** [comment]
@mahfouz72 You can't close an issue when the PR that fixes it hasn't been merged yet. Also if you create an issue, the PR should reference the issue. If you don't do these things, it makes creating issue basically pointless.

**Comment by mahfouz72** [comment]
@rnveach I was confused if this can be minor or should referenced with an issue. but I decided to make it a minor and close this. because as I know we shouldn't reference issues that don't have approved label
