### ISSUE TITLE
Make coverage 100% for all classes at package com.puppycrawl.tools.checkstyle.ant

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#1487]
CheckstyleAntTask.java should be covered by 100% UTs.

remove exclude: https://github.com/checkstyle/checkstyle/blob/master/pom.xml#L1164

**Comment by romani** [comment]
assigned to @m-mikula

**Comment by romani** [comment]
@m-mikula , do you plan to finish that issue?

**Comment by m-mikula** [comment]
Jup, but I am currently preparing a wedding I'll finish it on sunday
Am 27.08.2015 14:01 schrieb "Roman Ivanov" <notifications@github.com>:

**Comment by romani** [comment]
Some work is done at #2194 , not sure that such changes could be reused, I have have to mention it there.

**Comment by romani** [comment]
workaround is provided, issue is closed.
