### ISSUE TITLE
Drop ci jobs for unsupported java versions

### ISSUE THREAD

**Issue by strkkk** [checkstyle/checkstyle#14877]
Unsupported java versions include versions 15, 16, 18, 19 and 20. [Wiki](https://en.wikipedia.org/wiki/Java_version_history#Release_table)
That can free some CI capacity and speed up builds. 
Build for unsupported versions seems redundant.

**Comment by strkkk** [comment]
@nrmancuso wdyt?

**Comment by nrmancuso** [comment]
we should search and see what input files use these versions, and update them to be compiled with a newer version so that we don’t stop compiling some inputs

**Comment by strkkk** [comment]
Ok, we can exclude java19 and java20 for now and update existing java15 and java16 files to be compiled with java17
There is no java18 files, so it can be dropped right away.

**Comment by romani** [comment]
@strkkk , Why you think we need jdk14 ?
we already agered to migrate to jdk17 in near future, so all below 17 will be base javac.

**Comment by strkkk** [comment]
hmm, for some reason I thought that it was LTS.
No reason, it should be removed too, I will create PR later.
