### ISSUE TITLE
Refactor SummaryJavadoc to avoid null usage 

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#14881]
Refactor as discussed at https://github.com/checkstyle/checkstyle/pull/14690#discussion_r1602405976

**Comment by nrmancuso** [comment]
https://github.com/checkstyle/checkstyle/pull/14690#discussion_r1601538803

**Comment by romani** [comment]
Yes, try to remove Optional if null is required downstream.
But may be we can keep optional and remove usage of null down in the logic.

Send PR and we will see together.

**Comment by mohitsatr** [comment]
@romani, just out of curiosity, why are we removing null usages? Is it because avoiding null is generally considered best practice, or is there a specific reason in this particular context?

**Comment by romani** [comment]
It is fashion of current time to use Optional instead null. And it is more explicit for reader of code that something is not guaranteed to exist.
Checker framework also helps help to explicitly mark what is nullable.

Most ideal case, no null and no Optional :),

**Comment by romani** [comment]
@mohitsatr , thanks a lot.
