### ISSUE TITLE
Rename section 4.1.1 of google style guide implementation and add new test cases for lambdas

### ISSUE THREAD

**Issue by Zopsss** [checkstyle/checkstyle#14908]
I have read check documentation: https://checkstyle.org/checks/blocks/needbraces.html#NeedBraces
I have downloaded the latest cli from: https://checkstyle.org/cmdline.html#Download_and_Run
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

**How it works Now:**

![Screenshot 2024-05-29 103227](https://github.com/checkstyle/checkstyle/assets/86093112/06c5c3f0-3d2e-4225-9359-c09516087a7c)

As you can see in the above diff screenshot, section `4.1.1` of google style guide implementation got renamed from `4.1.1 Braces are used where optional` to `4.1.1 Use of optional braces` in the latest version, so we need to update the section name according to that in google_style.xml:

https://github.com/checkstyle/checkstyle/blob/a7042e5119e6df9b8f782751af6cae2ee54a215a/src/xdocs/google_style.xml#L618-L619

---

A new paragraph paragraph was also added in 4.1.1 section:

![Screenshot 2024-05-29 104132](https://github.com/checkstyle/checkstyle/assets/86093112/922876b3-973c-4782-9bbf-de34817851f2)

We already have support to ignore lambdas for this rule, which I have showed with an example below:

#### UseOfOptionalBraces.java

```java
import java.util.ArrayList;

/**
 * Testing google_checks.xml
 */
public class UseOfOptionalBraces {

  /**
   * testing.
   *
   * @param args testing
   */
  public static void main(String[] args) {
    int a = 1;
    int b = 2;

    if (a == b) System.out.println("testing if"); // warn
    else System.out.println("testing else"); // warn

    for (int x = 0; x < 10; x++) System.out.println("testing for"); // warn

    int x = 0;
    while (x < 10) x++; // warn

    int y = 0;
    do y++; // warn
    while (y < 10);

    ArrayList<Integer> numbers = new ArrayList<Integer>();
    numbers.add(5);
    numbers.add(9);
    numbers.add(8);
    numbers.add(1);
    numbers.forEach((n) -> System.out.println(n)); // ok, braces are not required for lambdas
  }
}
```

#### Config: 

[google_checks.xml](https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/google_checks.xml)

#### Output: 

```bash
$ java -jar checkstyle-10.17.0-all.jar -c google_checks.xml .\UseOfOptionalBraces.java
Starting audit...
[WARN] C:\checkstyle testing\TestingGoogleStyle\.\UseOfOptionalBraces.java:17:5: 'if' construct must use '{}'s. [NeedBraces]
[WARN] C:\checkstyle testing\TestingGoogleStyle\.\UseOfOptionalBraces.java:18:5: 'else' construct must use '{}'s. [NeedBraces]
[WARN] C:\checkstyle testing\TestingGoogleStyle\.\UseOfOptionalBraces.java:20:5: 'for' construct must use '{}'s. [NeedBraces]
[WARN] C:\checkstyle testing\TestingGoogleStyle\.\UseOfOptionalBraces.java:23:5: 'while' construct must use '{}'s. [NeedBraces]
[WARN] C:\checkstyle testing\TestingGoogleStyle\.\UseOfOptionalBraces.java:26:5: 'do' construct must use '{}'s. [NeedBraces]
Audit done.
```

As you can see, there is no warning for lambdas, which means we're following the updated rule.

**Describe the solution you'd like**
We need to update the section name to the new name, add test cases for `lambdas` in [NeedBracesTest.java](https://github.com/checkstyle/checkstyle/blob/master/src/it/java/com/google/checkstyle/test/chapter4formatting/rule411bracesareused/NeedBracesTest.java) to ensure everything is working is fine.

The diff screenshots are taken from: https://github.com/checkstyle/checkstyle/pull/14901/files#diff-3f79fa1ed75e6db042f0bb87505b89c47280f86dc510d90ed8d039c77869ce33

**Comment by rnveach** [comment]
Context: https://github.com/checkstyle/checkstyle/pull/14901/files#diff-3f79fa1ed75e6db042f0bb87505b89c47280f86dc510d90ed8d039c77869ce33L252-R254

New file lines:
https://github.com/checkstyle/checkstyle/blob/4bcfed8ef4a4446fbda32e24fd067abd933030ce/src/site/resources/styleguides/google-java-style-20180523/javaguide.html#L254

**Comment by rnveach** [comment]
@Zopsss 
> We need to update the section name to the new name

If this comes up again, provide us your recommendation on a new name.

I am thinking `4.1.1-braces-usage` or something similar. Let me know if you have any better ideas.

**Comment by Zopsss** [comment]
> I am thinking `4.1.1-braces-usage` or something similar. Let me know if you have any better ideas.

IMO, we should use the same names as google style guide, we're following this rule for every sections. This way the google style guide and our implementation both will have sections with same names. I guess we should keep following this.

In this case, the section's new name is `Use of optional braces` as shown in the diff Screenshot so we should use it.

**Comment by rnveach** [comment]
> we're following this rule for every sections

This doesn't appear to be true. Some sections don't use some words and it seems we use others instead. I didn't look at everything.

https://checkstyle.org/google_style.html#a2.3.2
Test folder left off sequences.

https://checkstyle.org/google_style.html#a4.1.2
Test folder left off everything after `:`.

https://checkstyle.org/google_style.html#a4.8.2.1
Test folder says line instead of declaration.

> the section's new name is Use of optional braces 

I am fine with this.

**Comment by Zopsss** [comment]
> > we're following this rule for every sections
> 
> This doesn't appear to be true. Some sections don't use some words and it seems we use other words instead. I didn't look at everything.
> 
> https://checkstyle.org/google_style.html#a2.3.2 Test folder left off sequences.
> 
> https://checkstyle.org/google_style.html#a4.1.2 Test folder left off everything after `:`.
> 
> https://checkstyle.org/google_style.html#a4.8.2.1 Test folder says line instead of declaration.
> 
> If we were to enforce everything follows a specific patterning, then we would need to create a test for this.


Oh so you meant the test folders. I didn't knew they used different naming conventions, I guess it is just to keep the folder names small. 

thanks, I'll keep this in mind.

**Comment by Zopsss** [comment]
fix is merged
