### ISSUE TITLE
Add new section 4.8.5.4 Field Annotations in google style guide implementation

### ISSUE THREAD

**Issue by Zopsss** [checkstyle/checkstyle#14914]
I have read check documentation: https://checkstyle.org/checks/annotation/annotationlocation.html
I have downloaded the latest cli from: https://checkstyle.org/cmdline.html#Download_and_Run
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

**How it works Now:**
![Screenshot 2024-05-31 113453](https://github.com/checkstyle/checkstyle/assets/86093112/0bb45f45-0eb0-49c4-9e46-2d775f0ed54e)
( Diff Link: https://github.com/checkstyle/checkstyle/pull/14901/files#diff-3f79fa1ed75e6db042f0bb87505b89c47280f86dc510d90ed8d039c77869ce33R793-R800 )

This new section was added in the latest version of google style guide, diving the section 4.8.5 in sub-sections. This rule is for `Fields`. It states that annotations for `Fields` must come immediately after its documentation and there can be multiple annotations on single line. This rule has already being followed in the current implementation, here's an example:

#### FieldAnnotations.java
```java
import java.util.HashMap;
import java.util.Map;

/**
 * testing.
 */
public class FieldAnnotations {

  /**
   * testing.
   */
  @Deprecated @Nullable int abc = 78;

  /**
   * testing.
   */
  @Deprecated
  @Nullable
  int[] myNum = new int[10];

  /**
   * testing.
   */
  @Deprecated @Nullable
  Map<Integer, String> hashMap = new HashMap<>();

  @Deprecated
  @Nullable
  /** // warning, ensuring the annotations comes immediately after the documentation.
   * testing
   */
  String name;

  @Deprecated @Nullable
  /** // warning, ensuring the annotations comes immediately after the documentation.
   * testing
   */
  long phoneNumber;

  interface MyInterface {
    @Deprecated @Nullable
    /** // warning, ensuring the annotations comes immediately after the documentation.
     * testing.
     */
    int xyz = 90;
  }

  record MyRecord(int x) {
    @Deprecated @Nullable
    /** // warning, ensuring the annotations comes immediately after the documentation.
     * testing.
     */
    static String name = "testing";
  }

  enum MyEnum {
    ONE, TWO;

    @Deprecated @Nullable
    /** // warning, ensuring the annotations comes immediately after the documentation.
     * TESTING.
     */
    int test = 90;
  }
}
```

#### Output
```
$ java -jar .\checkstyle-10.17.0-all.jar -c .\google_checks.xml .\FieldAnnotations.java
Starting audit...
[WARN] C:\checkstyle testing\TestingGoogleStyle\.\FieldAnnotations.java:29:3: Javadoc comment is placed in the wrong location. [InvalidJavadocPosition]
[WARN] C:\checkstyle testing\TestingGoogleStyle\.\FieldAnnotations.java:35:3: Javadoc comment is placed in the wrong location. [InvalidJavadocPosition]
[WARN] C:\checkstyle testing\TestingGoogleStyle\.\FieldAnnotations.java:42:5: Javadoc comment is placed in the wrong location. [InvalidJavadocPosition]
[WARN] C:\checkstyle testing\TestingGoogleStyle\.\FieldAnnotations.java:50:5: Javadoc comment is placed in the wrong location. [InvalidJavadocPosition]
[WARN] C:\checkstyle testing\TestingGoogleStyle\.\FieldAnnotations.java:60:5: Javadoc comment is placed in the wrong location. [InvalidJavadocPosition]
Audit done.
```

As you can see there is no warnings for multiple annotations on the same line but there are warnings when the annotations does not comes immediately after the documentation. 

**Describe the solution you'd like**
Add this new section to the [google_style.xml](https://github.com/checkstyle/checkstyle/blob/4bcfed8ef4a4446fbda32e24fd067abd933030ce/src/xdocs/google_style.xml) to update the coverage page, write test cases for it. The test folder name will be: `rule4854fieldannotations`

**Comment by rdiachenko** [comment]
Fix is merged
