### ISSUE TITLE
Establish Presence and Seek Guidance from OpenJDK Mailing List

### ISSUE THREAD

**Issue by mahfouz72** [checkstyle/checkstyle#14922]
We need to develop an approach to engage with the OpenJDK mailing list to seek expert advice on utilizing new language features. Our goal is to leverage the knowledge of those who have created or used these features. They can guide us on best practices and the most effective ways to use these features. This will help us identify which checks may need updates and ideas for new checks.

our conversation: https://mail.openjdk.org/pipermail/discuss/2024-May/006399.html

**Comment by nrmancuso** [comment]
@mahfouz72 please add the link from our existing conversation on the mailing list

**Comment by mahfouz72** [comment]
I am closing this issue. reason:
https://mail.openjdk.org/pipermail/amber-dev/2024-June/008822.html

**Comment by nrmancuso** [comment]
> So I recommend a slightly less lofty-goal, which is discussing whether 
specific patterns should or should not be encouraged by tooling, and let 
these percolate into style guides as appropriate (but let that happen 
somewhere else.)

Sounds like the openjdk folks would prefer to not have conversations about style on their mailing list.
