### ISSUE TITLE
Language Feature Integration Document: JEPS

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#14923]
Identified at https://github.com/checkstyle/checkstyle/pull/14904#discussion_r1622809436 ,

Probably JEPS should be first so the user understands what the new feature is before diving into examining existing checks.

Then looking at Review Associated JEP's Recommendations, it seems like we are splitting apart the same information.

Going with above, I think we should have a common review the JEPs and understand the change better, then updating and creating new checks can talk about their individual specifics that the global started their thinking process.

**Comment by nrmancuso** [comment]
We can come back to this after some tracker issues have been completed and we have some more experience.

**Comment by mahfouz72** [comment]
> We should also extend our check update docs to always consider this check when new keywords are added to the language.

leaving this for just a remainder

**Comment by mahfouz72** [comment]
let's make a general improvements here not just JEP sections
