### ISSUE TITLE
Migrate google style guide tests to follow chapter wise testing

### ISSUE THREAD

**Issue by Zopsss** [checkstyle/checkstyle#14937]
Currently the google style guide tests are implemented as `Per Module Testing` approach. We need to migrate these tests to use `Chapter Wise Testing` approach.

#### What is Per Module Testing?
The testing approach in which every modules used in a rule will have its special test file. All of these different test files will test different areas of the rule to ensure that we follow the rule correctly. 

#### What is Per Module Testing?
The testing approach in which there will be only one test file which will combine all the different modules used for the corresponding rule and ensure we follow the rule correctly. We combine different modules into single test and test the rule as whole.

The support to test `Chapter wise testing`'s documentation was added in this PR: https://github.com/checkstyle/checkstyle/pull/14925

#### Final Goal:
Migrate all google tests to chapter wise testing by combining different modules into single test file and update the coverage page accordingly. 

Following sections needs to be migrated:

- [x] 2.1 File name
- [x] 2.3.1 Whitespace characters
- [x] 2.3.2 Special escape sequences
- [x] 2.3.3 Non-ASCII characters
- [x] 3 Source file structure
- [x] 3.2 Package statement
- [x] 3.3.1 No wildcard imports
- [x] 3.3.2 No line-wrapping
- [x] 3.3.3 Ordering and spacing
- [x] 3.4.1 Exactly one top-level class declaration
- [x] 3.4.2.1 Overloads: never split
- [x] 4.1.1 Use of optional braces
- [x] 4.1.2 Nonempty blocks: K & R style
- [x] 4.1.3 Empty blocks: may be concise
- [x] 4.2 Block indentation: +2 spaces
- [x] 4.3 One statement per line
- [x] 4.4 Column limit: 100
- [x] 4.5.1 Where to break
- [x] 4.5.2 Indent continuation lines at least +4 spaces
- [x] 4.6.1 Vertical Whitespace
- [x] 4.6.2 Horizontal whitespace
- [x] 4.8.2.1 One variable per declaration
- [x] 4.8.2.2 Declared when needed
- [x] 4.8.3.2 No C-style array declarations
- [x] 4.8.4.1 Indentation
- [x] 4.8.4.2 Fall-through: commented
- [x] 4.8.4.3 Presence of the default label
- [x] 4.8.6.1 Block comment style
- [x] 4.8.7 Modifiers
- [x] 4.8.8 Numeric Literals
- [x] 5.2.1 Package names
- [x] 5.2.2 Class names
- [x] 5.2.3 Method names
- [x] 5.2.5 Non-constant field names
- [x] 5.2.6 Parameter names
- [x] 5.2.7 Local variable names
- [x] 5.2.8 Type variable names
- [x] 5.3 Camel case: defined
- [x] 6.2 Caught exceptions: not ignored
- [x] 6.4 Finalizers: not used
- [x] 7.1.1 General form
- [x] 7.1.2 Paragraphs
- [x] 7.1.3 Block tags
- [x] 7.2 The summary fragment
- [x] 7.3 Where Javadoc is used
- [x] 7.3.1 Exception: self-explanatory methods
- [x] 7.3.2 Exception: overrides
- [x] 7.3.4 Non-required Javadoc

**Comment by rnveach** [comment]
Reopening due to failure at https://github.com/mahfouz72/checkstyle/blob/treewalker-property/src/it/java/com/google/checkstyle/test/base/AbstractGoogleModuleTestSupport.java#L152

@Zopsss

**Comment by Zopsss** [comment]
ummmm.... should we remove that "until" comment? or change it to the new issue: https://github.com/checkstyle/checkstyle/issues/15218 ?

**Comment by rnveach** [comment]
Until comment should stay as I mentioned I am expecting this code to be removed when there are no usages left. If comment is assigned to the wrong issue, then it needs to be updated.

**Comment by Zopsss** [comment]
Updated the comment: https://github.com/checkstyle/checkstyle/pull/15219 @rnveach

**Comment by romani** [comment]
Link is fixed
