### ISSUE TITLE
Google Style page isn't consistent in spacing with multiple checks

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#14930]
Example of good spacing:
https://checkstyle.org/google_style.html#a3.2

Some other checks don't follow this pattern and seem a bit mushed together.
https://checkstyle.org/google_style.html#a4.1.2
https://checkstyle.org/google_style.html#a5.2.7
https://checkstyle.org/google_style.html#a5.2.8
https://checkstyle.org/google_style.html#a7.1.1
https://checkstyle.org/google_style.html#a7.1.2
https://checkstyle.org/google_style.html#a7.3
https://checkstyle.org/google_style.html#a7.3.1
https://checkstyle.org/google_style.html#a7.3.2

We should make all spacing consistent and be evenly spaced apart.

**Comment by romani** [comment]
Fix is merged
