### ISSUE TITLE
Google style 7.1.1 has reference to already closed issue 

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#14947]
https://checkstyle.org/google_style.html#a7.1.1

>SingleLineJavadoc Recent update for guide that clarify requirements will be addressed at #4052

Issue is closed , so we should remove it, or reword comment with new limitations

**Comment by Zopsss** [comment]
> or reword comment with new limitations

what are the new limitations?

**Comment by romani** [comment]
I don't know, I am guessing, lets just review this point from scratch.

**Comment by Zopsss** [comment]
> I don't know, I am guessing, lets just review this point from scratch.

Umm I don't think there are any new limitations. 

Here is the style guide rule you provided in that issue's description:

> The basic form is always acceptable. The single-line form may be substituted when the entirety
of the Javadoc block (including comment markers) can fit on a single line. Note that this only
applies when there are no block tags such as @return.

Here is the diff of updated tests from the [PR](https://github.com/checkstyle/checkstyle/pull/9270/):

https://github.com/checkstyle/checkstyle/pull/9270/files#diff-e069439a66edaeec4bf41821776b80dadf53fbf9533f31fe0008c6258c221cc7

The rule is being fully followed. We can remove the message and add ok_green.png

**Comment by rdiachenko** [comment]
@Zopsss , I agree the current check covers Google's requirements. Let's remove the message, mark it with green ok and extend the [current test data](https://github.com/checkstyle/checkstyle/blob/master/src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule711generalform/InputSingleLineJavadocCheck.java) with `@return` in a single javadoc comment.

**Comment by romani** [comment]
Fix is merged
