### ISSUE TITLE
Remove href from LineLength module property in google style config and update test cases

### ISSUE THREAD

**Issue by Zopsss** [checkstyle/checkstyle#14955]
Follow up of: https://github.com/checkstyle/checkstyle/pull/14943#discussion_r1631183000

remove `|href` and https://github.com/checkstyle/checkstyle/pull/14943#discussion_r1631179645 from google_checks.xml:

https://github.com/checkstyle/checkstyle/blob/e65027bba8de99b41f9caf71976c92d1519f7c1c/src/main/resources/google_checks.xml#L45-L49

**Comment by romani** [comment]
Fix is merged
