### ISSUE TITLE
Add Check Support for Java 21 Unnamed Variables & Patterns Syntax: UnusedLocalVariable

### ISSUE THREAD

**Issue by mahfouz72** [checkstyle/checkstyle#14950]
child of #14942 , #14960

we need to update `UnusedLocalVariableCheck` to support unnamed variables in local variables declaration and in enhanced/basic for.

I have read check documentation: https://checkstyle.org/checks/coding/unusedlocalvariable.html
I have downloaded the latest checkstyle from: https://checkstyle.org/cmdline.html#Download_and_Run
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

```
PS D:\CS\test> javac src/Test.java
PS D:\CS\test> cat src/Test.java
import java.util.PriorityQueue;
import java.util.Queue;

class Test {
    void test() {
        Queue<Integer> q = new PriorityQueue<>();
        q.add(1);
        while (!q.isEmpty()) {
            var _ = q.poll();   // violation
        }
    }
}
PS D:\CS\test> cat config.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>
 <module name="TreeWalker">
    <module name="UnusedLocalVariable">

    </module>
 </module>
</module>
PS D:\CS\test> java  -jar checkstyle-10.14.2-all.jar -c config.xml  src/Test.java
Starting audit...
[ERROR] D:\CS\test\src\Test.java:9:13: Unused local variable '_'. [UnusedLocalVariable]
Audit done.
Checkstyle ends with 1 errors.
```
---

**Describe what you expect in detail.**

underscore is used to declare variables that are not intended to be used. So, I consider this example as a false positive.  the check should not violate unnamed variables

---

**Comment by rnveach** [comment]
I am good with this.

> the check should not violate the non-use of the unnamed variables.

=> `the check should not violate unnamed variables`

**Comment by nrmancuso** [comment]
It has become apparent that we should add a new property to not break this check for users on older java versions: https://github.com/checkstyle/checkstyle/issues/14960#issuecomment-2156025055

`allowUnnamedVariables` will essentially suppress violations from this check for unnamed variables. While newer versions of java make sure that `_` is not used, older versions of Java make no guarantees about this.

**Comment by mahfouz72** [comment]
ok, to make sure we are on the same page.
new property `allowUnnamedVariables`, if it is true then we will suppress violations on unnamed variables if it is false then the check will violate unnamed variables (underscore) if they are not used (this case is possible only for code written in Java 9 or older)
and the default value for this property is false.

**Comment by rnveach** [comment]
Current check message is `Unused local variable ''{0}''.`.

Maybe consider changing message to `Unused named local variable ''{0}''.`. It might be a little redundant, so I am unsure.

**Comment by nrmancuso** [comment]
> Current check message is `Unused local variable ''{0}''.`.
> 
> Maybe consider changing message to `Unused named local variable ''{0}''.` if the property is on. It might be a little redundant, so I am unsure.

I like this, @mahfouz72 if you agree let’s do this ^

**Comment by mahfouz72** [comment]
I agree with the new message. this internally guides the users to update it to unnamed if they intend not to use it.





> `allowUnnamedVariables` will essentially suppress violations from this check for unnamed variables.

`allowUnnamedVariables` => control whether to suppress violations for unnamed variables. 

the property name is a little confusing for me should it be `ignoreUnnamedVariables`?
