### ISSUE TITLE
Investigate UnusedLocalVariables Check Updates for Unnamed Variables and Patterns

### ISSUE THREAD

**Issue by nrmancuso** [checkstyle/checkstyle#14960]
from JEP:

The following kinds of declarations can introduce either a named variable (denoted by an identifier) or an unnamed variable (denoted by an underscore):

- A local variable declaration statement in a block (JLS §14.4.2),
- The resource specification of a try-with-resources statement (JLS §14.20.3),
- The header of a basic for loop (JLS §14.14.1),
- The header of an enhanced for loop (JLS §14.14.2),
- An exception parameter of a catch block (JLS §14.20), and
- A formal parameter of a lambda expression (JLS §15.27.1).

before opening an issue, we need to discuss and decide on the possible check updates or new checks due to the presence of unnamed pattern and variables in these constructs 

I tried to cover all possible cases in this example.

```java
import java.util.List;
import java.util.PriorityQueue;
import java.util.Queue;
import java.util.Scanner;
record Point(int x, int y) {};

class Test {

    void testLocalVariables(){
        int _ = 4;  // violation,  but a false positive
        int x = 4; // violation (expected)
    }

    void testForLoops() {
        Queue<Integer> q = new PriorityQueue<>();
        q.add(1);
        for (Integer a : q) {   // violation  (expected)
            q.poll();
        }
        for (int i = 0, k = Integer.valueOf(1); i < 3; i++) { } // violation (expected)

        for (Integer _ : q) {   // violation, but a false positive
            q.poll();
        }
        for (int i = 0, _ = Integer.valueOf(1); i < 3; i++) { } // violation, but a false positive
    }

    public void testLambdaParameter() {
        List<String> list = List.of("a", "b", "c");
        List<String> _ = list.stream().map(character -> "x").toList(); // ok, but a false negative 'character' is unused
        List<String> _ = list.stream().map(_ -> "x").toList(); // ok (expected)
    }

    public void testTryWithResourceAndCatchParameters() {
        try (AutoCloseable a = new Scanner(System.in)) {  // ok, but a false negative 'a' is unused

        } catch (Exception e) {  // ok, but a false negative 'e' is unused
            System.out.println("error");
        }

        try (AutoCloseable _ = new Scanner(System.in)) { // ok (expected)

        } catch (Exception _) {  // ok  (expected)
            System.out.println("error");
        }
    }

    public void testPatternVariables(Object obj) {
        if (obj instanceof Point(int x, int y)) { // ok, but a false negative 'x' and 'y' is unused

        }
        if (obj instanceof Point(int _, int _)) { // ok (expected) unnamed pattern variables

        }
        if (obj instanceof Point(_,_)){ // ok (expected) unnamed pattern

        }

    }
}
```

```
PS D:\CS\test> java  -jar checkstyle-10.14.2-all.jar -c config.xml  src/Test.java
Starting audit...
[ERROR] D:\CS\test\src\Test.java:10:9: Unused local variable '_'. [UnusedLocalVariable]
[ERROR] D:\CS\test\src\Test.java:11:9: Unused local variable 'x'. [UnusedLocalVariable]
[ERROR] D:\CS\test\src\Test.java:17:14: Unused local variable 'a'. [UnusedLocalVariable]
[ERROR] D:\CS\test\src\Test.java:20:14: Unused local variable 'k'. [UnusedLocalVariable]
[ERROR] D:\CS\test\src\Test.java:22:14: Unused local variable '_'. [UnusedLocalVariable]
[ERROR] D:\CS\test\src\Test.java:25:14: Unused local variable '_'. [UnusedLocalVariable]
[ERROR] D:\CS\test\src\Test.java:30:9: Unused local variable '_'. [UnusedLocalVariable]
Audit done.
Checkstyle ends with 7 errors.
PS D:\CS\test> 

```

**Comment by nrmancuso** [comment]
This comment is a WIP

For local variable declaration:
```
    void testLocalVariables(){
        int _ = 4;  // violation,  but a false positive
        int x = 4; // violation (expected)
    }
```

I propose that we add a property to this check `validateUnnamedVariables`. This helps us to bring this check up to 2024, while allowing users with older codebases to turn this feature off.

**Comment by nrmancuso** [comment]
@mahfouz72 thank you very much for this in-depth analysis, it really helped me to figure all this out.

@rnveach please comment here if you are good with my proposed todo list.

**Comment by nrmancuso** [comment]
As for updating the check message, I am on the fence now. The message doesn't tell you *what* to do now, why should we change this? It calls out that a variable is not used, the user can determine if they need to delete it or convert it to an unnamed variable.

**Comment by mahfouz72** [comment]
> I propose that we add a property to this check allowUnnamedVariables. This helps us to bring this check up to 2024, while allowing users with older codebases to turn this feature off.

this feature is useful only for codebases before Java 9 right?, because underscore is not a valid identifier after Java 9

**Comment by mahfouz72** [comment]
@nrmancuso the first item in the todo should be covered by https://github.com/checkstyle/checkstyle/issues/14950. 
I don't see pattern variables do you have any thoughts on this? JLS says they are local variables so should we update the check to support pattern variables?

**Comment by nrmancuso** [comment]
> > I propose that we add a property to this check allowUnnamedVariables. This helps us to bring this check up to 2024, while allowing users with older codebases to turn this feature off.
> 
> this feature is useful only for codebases before Java 9 right?, because underscore is not a valid identifier after Java 9

This feature would be for people on newer java versions, to allow them to avoid violations on unnamed variables.

**Comment by rnveach** [comment]
> Create ticket to add support for resource specification to UnusedLocalVariable

I am good.

>  Create ticket to create new check UnusedCatchParameterShouldBeUnnamed
Create ticket to create new check UnusedLambdaParameterShouldBeUnnamed

I am good with new checks, but why not drop `ShouldBeUnnamed` from these 2? You already plan to support older code bases / java versions with `allowUnnamedVariables` in `UnusedLocalVariableCheck`, so I am confused why you wouldn't support these versions with these new checks.

Coding wise, this doesn't seem to add that much overhead to the check. We still need to identify if the "variable" is unused before recommending a violation. Property would just differentiating picking up `_` variables and recommendation of using unnamed.

> Place details about new property allowUnnamedVariables

I am good. I will place my one recommendation in #14950 .

**Comment by nrmancuso** [comment]
> You already plan to support older code bases / java versions with allowUnnamedVariables in UnusedLocalVariableCheck, so I am confused why you wouldn't support these versions with these new checks.

Because it is not possible to use unnamed variables in older Java versions, and in both cases (catch and lambda) you have no choice but to “declare” this variable.

**Comment by rnveach** [comment]
I am good with the 2 checks now. I didn't think it through fully.

**Comment by nrmancuso** [comment]
@mahfouz72 please translate todo list and any other necessary context to https://github.com/checkstyle/checkstyle/issues/14950 and we can close this.

**Comment by mahfouz72** [comment]
@nrmancuso done
