### ISSUE TITLE
Update XdocPagesTest to validate Google coverage table sections

### ISSUE THREAD

**Issue by Zopsss** [checkstyle/checkstyle#14968]
Detected at: https://github.com/checkstyle/checkstyle/pull/14925#issuecomment-2154850087
Discuss how we should validate presence of module usage in the test file for chapter wise testing approach. 

one of some recent website; https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/5374c9e_2024232637/google_style.html#Google_Coverage_table

we migrated to whole config usage for tests.

We have now:
Google's Java Style Rule  - exact name of section 
Checkstyle Check - list of checks that we place manually 
Applied to config - links to Github search for all Checks that referenced in "Checkstyle Check" column. References to Junit Test classes.

References to junit Test class is useless as it does not show what is correct code for this chapter and what is incorrect. As we migrated to BDD model with  inlined comments in Inputs, it will be a way more useful for users to see our Inputs (folder with Inputs). And it is relatively easy to generate link to them.

**Expected:**
"Checkstyle Check" renamed to "Checkstyle Checks"

"Applied to config" into two columns: "Check Configs" and "Sample files"
"Sample files" - a single link to folder where all Inputs are placed, I think we can generate path to Inputs by name of section.
"Check Configs" - links to Github search for all Checks that referenced in "Checkstyle Check" column. If there is a suppression module, it should be referenced in "Checkstyle Checks"  with it's `id`.

So validation will be for "Check Configs" and "Sample files" column.

**Comment by romani** [comment]
@Zopsss , what is your proposal ?

**Comment by Zopsss** [comment]
@romani we've migrated to whole config now so we dont need this validation anymore. This issue was created at the beginning of the project, at that time we didn't decided to migrated to whole config.

**Comment by romani** [comment]
I will double check and confirm

**Comment by romani** [comment]
Issue will be closed by @rnveach
