### ISSUE TITLE
Add Check Support for Java 21 Unnamed Variables & Patterns Syntax: PatternVariableName

### ISSUE THREAD

**Issue by mahfouz72** [checkstyle/checkstyle#14970]
child of #14942 
I have read check documentation: https://checkstyle.org/checks/naming/patternvariablename.html
I have downloaded the latest checkstyle from: https://checkstyle.org/cmdline.html#Download_and_Run
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

```
record Point(int x, int y) { }
record square(Point upperLeft, Point lowerRight) { }

public class PatternVariables {
    void method(Object obj) {
        if (obj instanceof square(Point(int _, int y), _)) {  // violation
            System.out.println(y);
        }
    }
}
PS D:\CS\test> cat config.xml                                                                                
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>
 <module name="TreeWalker">
    <module name="PatternVariableName">
    </module>
 </module>
</module>
PS D:\CS\test> java  -jar checkstyle-10.14.2-all.jar -c config.xml  src/PatternVariables.java                
Starting audit...
[ERROR] D:\CS\test\src\PatternVariables.java:6:45: Name '_' must match pattern '^[a-z][a-zA-Z0-9]*$'. [PatternVariableName]
Audit done.
Checkstyle ends with 1 errors.

```
---

**Describe what you expect in detail.**

`PatternVariableName` should allow unnamed pattern variables by default

---

**Comment by rnveach** [comment]
While I agree with the issue, how will it allow the variables. Are we changing the default regexp or hardcoding?

What is the oldest Java version which `PatternVariableName` is actually supported on?

**Comment by mahfouz72** [comment]
I think hardcoding here is ok. pattern variables released in Java 16. the usage of  `_`  as a valid variable name has dropped since Java 9

**Comment by rnveach** [comment]
If there is no breaks between 9 and 16 with such a change, then I am good to do hardcoding here and ignore regexp.

**Comment by nrmancuso** [comment]
I would prefer regexp update, this is basically the entire configuration for this check and would even allow someone who did not want to allow the use of unnamed variables to forbid them.

**Comment by nrmancuso** [comment]
@rnveach I am good to approve for regexp update, please add approved label if you are good

**Comment by mahfouz72** [comment]
to restore the old behavior of this check, you can set the pattern back to `^[a-z][a-zA-Z0-9]*$`
