### ISSUE TITLE
Wrong comment in documentation example

### ISSUE THREAD

**Issue by Bananeweizen** [checkstyle/checkstyle#14996]
https://checkstyle.sourceforge.io/checks/regexp/regexpsingleline.html#RegexpSingleline
On of the examples is about checking files with "sql" extension but the comment talks about Java.

![grafik](https://github.com/checkstyle/checkstyle/assets/406876/18f540de-b8cb-4d21-8de7-5e00fb295e0d)

**Comment by romani** [comment]
Fix is merged.
