### ISSUE TITLE
Add Check Support for Java 21 Record Pattern Syntax: OperatorWrap 

### ISSUE THREAD

**Issue by mahfouz72** [checkstyle/checkstyle#15007]
child of https://github.com/checkstyle/checkstyle/issues/14890
I have read check documentation: https://checkstyle.org/checks/whitespace/operatorwrap.html#OperatorWrap
I have downloaded the latest checkstyle from: https://checkstyle.org/cmdline.html#Download_and_Run
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

```
PS D:\CS\test> cat src/Test2.java                                                
record ColoredPoint(int p, int x, String c) { }
record Rectangle(ColoredPoint upperLeft, ColoredPoint lowerRight) { }
public class Test2 {
    void test(Object obj) {
        if (!(obj instanceof                        // violation
                Rectangle(ColoredPoint record,ColoredPoint yield))) { 
        }
    }

}
PS D:\CS\test> cat config.xml                                                    
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
        "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>
    <module name="TreeWalker">
        <module name="OperatorWrap">

        </module>

    </module>
</module>
PS D:\CS\test> java  -jar checkstyle-10.17.0-all.jar -c config.xml src/Test2.java
Starting audit...
[ERROR] D:\CS\test\src\Test2.java:5:19: 'instanceof' should be on a new line. [OperatorWrap]
Audit done.
Checkstyle ends with 1 errors.
PS D:\CS\test> 

```
Describe what you expect in detail.

This can be closed without any updates

**Comment by rnveach** [comment]
I think we should atleast add an input file as other issues are doing.

@mahfouz72 Can you provide the JLS that says `instanceof` is an operator?

I think we should add to documentation a link to said JLS.

**Comment by mahfouz72** [comment]
> I think we should atleast add an input file as other issues are doing.

I just noticed that there is no input file for `instanceof` so yes we should add an input file here.

> @mahfouz72 Can you provide the JLS that says `instanceof` is an operator?

https://docs.oracle.com/javase/specs/jls/se7/html/jls-15.html#jls-15.20.2

I am good to approve for doc improvements and input file for instance of

> Edit: Do we have an issue to cover `ParenPad` for this syntax?

Yes

**Comment by rnveach** [comment]
> Edit: Do we have an issue to cover ParenPad for this syntax?
> Yes

The issue looks to be https://github.com/checkstyle/checkstyle/issues/14948 and it seems the example here is already covered.

**Comment by nrmancuso** [comment]
Approved for

> doc improvements and input file for instance of
