### ISSUE TITLE
Add Check Support for Java 21 Record Pattern Syntax: GenericWhitespace

### ISSUE THREAD

**Issue by mahfouz72** [checkstyle/checkstyle#15008]
child of https://github.com/checkstyle/checkstyle/issues/14890
I have read check documentation: https://checkstyle.org/checks/whitespace/genericwhitespace.html#GenericWhitespace
I have downloaded the latest checkstyle from: https://checkstyle.org/cmdline.html#Download_and_Run
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

```
PS D:\CS\test> cat src/Test2.java                                                
record ColoredPoint(int p, int x, String c) { }
record Rectangle(ColoredPoint upperLeft, ColoredPoint lowerRight) { }
record Pair<T>(T x, T y) {
    }
public class Test2 {
    void test(Object obj) {
        if (obj instanceof Pair < ? > (var s, var y)) {  // 4 violations
        }
    }

}
PS D:\CS\test> cat config.xml                                                    
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
        "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>
    <module name="TreeWalker">
        <module name="GenericWhitespaceCheck">

        </module>

    </module>
</module>
PS D:\CS\test> java  -jar checkstyle-10.17.0-all.jar -c config.xml src/Test2.java
Starting audit...
[ERROR] D:\CS\test\src\Test2.java:7:33: '<' is followed by whitespace. [GenericWhitespace]
[ERROR] D:\CS\test\src\Test2.java:7:33: '<' is preceded with whitespace. [GenericWhitespace]
[ERROR] D:\CS\test\src\Test2.java:7:37: '>' is followed by whitespace. [GenericWhitespace]
[ERROR] D:\CS\test\src\Test2.java:7:37: '>' is preceded with whitespace. [GenericWhitespace]
Audit done.
Checkstyle ends with 4 errors.
PS D:\CS\test> 
```
---
Describe what you expect in detail.

this can be closed and no need for an input file because we already have one in favor of  https://github.com/checkstyle/checkstyle/issues/14502

**Comment by rnveach** [comment]
> this can be closed and no need for an input file because we already have one in favor of https://github.com/checkstyle/checkstyle/issues/14502

Please provide link to line in input file that has this syntax, then I am good to close with nothing more added.

> if (obj instanceof Pair < ? > (var s, var y)) { 

What about `<>`s instead of `var` for the ¿field? (they more closely resemble fields IMO) types?

**Comment by mahfouz72** [comment]
https://github.com/checkstyle/checkstyle/blob/05dd30dbbc7d4e79f28ec86c22531bd8b3e7fc5b/src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/genericwhitespace/InputGenericWhitespaceBeforeRecordHeader.java#L73

**Comment by rnveach** [comment]
I saw an `instanceof` in the same input file. I am good to close if @nrmancuso has nothing else.

**Comment by nrmancuso** [comment]
We are good to close this.
