### ISSUE TITLE
Add Check Support for Java 21 Unnamed Variables & Patterns Syntax: IllegalIdentifierName

### ISSUE THREAD

**Issue by mahfouz72** [checkstyle/checkstyle#15016]
child of https://github.com/checkstyle/checkstyle/issues/14942
I have read check documentation: https://checkstyle.org/checks/naming/illegalidentifiername.html
I have downloaded the latest checkstyle from: https://checkstyle.org/cmdline.html#Download_and_Run
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

```
PS D:\CS\test> cat src/Test.java                                                
import java.util.PriorityQueue;
import java.util.Queue;

public class Test {
    void test() {
        Queue<Integer> q = new PriorityQueue<>();
        q.add(1);
        var _ = q.poll();
    }
}
PS D:\CS\test> cat config.xml                                                   
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
        "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
<module name="Checker">
    <property name="charset" value="UTF-8"/>
    <module name="TreeWalker">
         <module name="IllegalIdentifierName"/>
    </module>
</module>
PS D:\CS\test> java  -jar checkstyle-10.17.0-all.jar -c config.xml src/Test.java
Starting audit...
[ERROR] D:\CS\test\src\Test.java:8:13: Name '_' must match pattern '(?i)^(?!(record|yield|var|permits|sealed|_)$).+$'. [IllegalIdentifierName]
Audit done.
Checkstyle ends with 1 errors.
PS D:\CS\test> 
```

Describe what you expect in detail.

 `IllegalIdentifierName` should allow unnamed pattern variables by default

**Comment by rnveach** [comment]
https://checkstyle.org/checks/naming/illegalidentifiername.html#Properties
`_` already exists in `format`.

Can we clarify how this issue will be resolved?

**Comment by mahfouz72** [comment]
This `(?!)` is a negative lookahead assertion. It ensures that the string does not match the enclosed pattern. one of them is `_`. It was an Illegal identifier before. this is not the case anymore so the fix is simply `(?i)^(?!(record|yield|var|permits|sealed)$).+$"` instead of `(?i)^(?!(record|yield|var|permits|sealed|_)$).+$"`   (removed the underscore)

**Comment by nrmancuso** [comment]
For any users that wish to restore the "old" behavior of this check, you can set the pattern back to `(?i)^(?!(record|yield|var|permits|sealed|_)$).+$`
