### ISSUE TITLE
Add Check Support for Java 21 Unnamed Variables & Patterns Syntax: StaticVariableName

### ISSUE THREAD

**Issue by mahfouz72** [checkstyle/checkstyle#15019]
child of https://github.com/checkstyle/checkstyle/issues/14942
I have read check documentation: https://checkstyle.sourceforge.io/checks/naming/staticvariablename.html
I have downloaded the latest checkstyle from: https://checkstyle.org/cmdline.html#Download_and_Run
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

Unnamed variables can't be static fields.

```
PS D:\CS\test> cat src/Test.java                                                
import java.util.PriorityQueue;
import java.util.Queue;

public class Test {
  final static int _ = 0;
}
PS D:\CS\test> javac  src/Test.java
src\Test.java:5: error: underscore not allowed here
  final static int _ = 0;
                   ^
1 error
PS D:\CS\test> 

```
Describe what you expect in detail.

no update is needed this can be closed

**Comment by nrmancuso** [comment]
Agreed, thanks for the analysis.
