### ISSUE TITLE
Investigating updated rule for section 7.1.2 Javadoc Paragraphs in Google Style Guide

### ISSUE THREAD

**Issue by Zopsss** [checkstyle/checkstyle#15011]
I have read check documentation: https://checkstyle.org/checks/javadoc/javadocparagraph.html
I have downloaded the latest checkstyle from: https://checkstyle.org/cmdline.html#Download_and_Run
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

Continuation of conversation at: https://github.com/checkstyle/checkstyle/pull/14901/files#r1639860137

Diff Screenshot ( The highlighted part was newly added):
![Screenshot 2024-06-17 222038](https://github.com/checkstyle/checkstyle/assets/86093112/9777a378-d550-4d65-8993-1b90a9848467)

Diff Link: https://github.com/checkstyle/checkstyle/pull/14901/files#diff-3f79fa1ed75e6db042f0bb87505b89c47280f86dc510d90ed8d039c77869ce33L1110-R1163

As mentioned in the above screenshot, the block level tags ( ul, li, ol, h1-h6, etc ) should not be preceded with `<p>`. Currently we do not have support to check this.

I tried different combination of preceding `<p>` with block level tag to see if there is any visual difference between them but I couldn't found any. I have attached the screenshots of my experiments with code below:

code:
```java
/**
 * Testing Javadoc....
 *
 * <p><h1>Testing Javadoc with only opening p</h1>
 */
public class TestJavadoc {}
```

html:
![opening p only](https://github.com/checkstyle/checkstyle/assets/86093112/284c5b28-c4a0-4f4a-b395-df409a7ad54b)

---

code:
```java
/**
 * Testing Javadoc....
 *
 * <p></p><h1>Testing Javadoc with starting p</h1>
 */
public class TestJavadoc {}
```

html:
![starting p](https://github.com/checkstyle/checkstyle/assets/86093112/b74ef6f2-f0da-41c4-bdd6-4601678c1758)

---

code:
```java
/**
 * Testing Javadoc....
 *
 * <p><h1>Testing Javadoc with surrounding p</h1></p>
 */
public class TestJavadoc {}
```

html:
![surrounding p](https://github.com/checkstyle/checkstyle/assets/86093112/c49f29c5-796a-4fd0-96b8-8d7ab831434f)

---

code:
```java
/**
 * Testing Javadoc....
 *
 * <h1>Testing Javadoc without p</h1>
 */
public class TestJavadoc {}
```

html:
![without p](https://github.com/checkstyle/checkstyle/assets/86093112/aa6ee0fb-c7e9-4298-b11e-b1d6458c0c7b)

---

As you can see in the provided screenshots, there is no visual difference of `<h1>` even if there is preceding `<p>` present or not.

**Comment by romani** [comment]
Ok, good so we need to make some Check that will violate extra P tag.

**Comment by romani** [comment]
conversation is moved to https://github.com/checkstyle/checkstyle/issues/15458
