### ISSUE TITLE
UnusedLocalVariable Should Support Resource Specifications

### ISSUE THREAD

**Issue by mahfouz72** [checkstyle/checkstyle#15024]
child of #14942
I have read check documentation: https://checkstyle.org/checks/coding/unusedlocalvariable.html#UnusedLocalVariable
I have downloaded the latest checkstyle from: https://checkstyle.org/cmdline.html#Download_and_Run
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

```
PS D:\CS\test> cat src/Test.java
import java.io.BufferedReader;
public class Test {
    void test() throws Exception {
        try (var resource = new BufferedReader(null)) {

        }
    }
}
PS D:\CS\test> cat config.xml   
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
        "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
<module name="Checker">
    <property name="charset" value="UTF-8"/>
    <module name="TreeWalker">
        <module name="UnusedLocalVariable"/>
    </module>
</module>
PS D:\CS\test> java  -jar checkstyle-10.17.0-all.jar -c config.xml src/Test.java
Starting audit...
Audit done.
PS D:\CS\test> 

```

--- 
**Describe what you want in detail.**

I suggest to add new property called  `validateResourceSpecifications`  to control whether to validate resources. becuase we have no choice but to declare the resource but when it is unused it should be declared as unnamed variable. The fix for this example will be as follow
```
       try (var _ = new BufferedReader(null)) {

        }
```
users under java 21 (including us, we will have a lot of similar violtion due to the non use of resources) can't use unnamed variables. That's why I suggest new property to be able to control this behaviour.

**Comment by rnveach** [comment]
> becuase we have no choice but to declare the resource 

Why would someone realistically declare a resource, put it in a try/catch (meaning we are opening said resource), but never use it? Do we have a general use case?

To me this seems like you could just remove the try/catch and the variable, but still call whatever is needed to open the resource, similar to the workaround for regular unusued local variables.

Will code analyzers be smart to know an unassigned resource is not in a try/catch? Even if they are smart to catch this, this still goes back to my first question.

**Comment by mahfouz72** [comment]
> Why would someone realistically declare a resource, put it in a try/catch (meaning we are opening said resource), but never use it? Do we have a general use case?

Yes, there are scenarios where a resource might be declared and opened without any operations performed on it. Here are a couple of general use cases from our codebase:

**1. mocking testing:**  During testing, a resource might be declared and opened to verify that specific behavior  works correctly, even if the actual operations on the resource are mocked

Example : 

https://github.com/checkstyle/checkstyle/blob/c34d756b7e798c1b09112523ee9b9102cb3d6440/src/test/java/com/puppycrawl/tools/checkstyle/TreeWalkerTest.java#L130-L137

This example demonstrates a scenario where the construction of `TreeWalkerAuditEvent` instances is mocked to ensure no audit events are produced during the test execution. The resource is opened and passed around to verify the behavior without performing actual operations on it.

**2. Existence Checks:** when the primary goal is to verify the existence of a resource by attempting to open it. But the real content of the resource is not needed.

Example:
https://github.com/checkstyle/checkstyle/blob/8531fec143058ddd92fab14839f2e9389ac6cf5c/src/main/java/com/puppycrawl/tools/checkstyle/utils/FilterUtil.java#L43-L51

this method checks if a file exists by attempting to open an input stream to the file. If the stream is successfully opened, it means the file exists. If an exception is thrown while trying to open the stream, it means the file does not exist




> To me this seems like you could just remove the try/catch and the variable, but still call whatever is needed to open the resource, similar to the workaround for regular unusued local variables.

But with this solution how to deal with exceptions? try/catch is important for exception handling. Do I misunderstand you?

we should detect these use cases when the resource is not used. They should be unnamed

**Comment by rnveach** [comment]
> Will code analyzers be smart to know an unassigned resource is not in a try/catch? 

I checked this out and Eclipse does have the option to print errors if the resource isn't assigned to a variable.
`Potential resource leak: '<unassigned Closeable value>' may not be closed`

> To me this seems like you could just remove the try/catch and the variable, but still call whatever is needed to open the resource, similar to the workaround for regular unusued local variables.
> But with this solution how to deal with exceptions? 

Example of what I was thinking at the time:
````
     boolean suppressionSourceExists; 
     try {
         CommonUtil.getUriByFilename(fileName).toURL().openStream();
         suppressionSourceExists = true; 
     } 
     catch (CheckstyleException | IOException ignored) { 
         suppressionSourceExists = false; 
     } 
````

However, like I mentioned before this does lead to a resource leak as I didn't include the close. You can assign the resource to a variable and close it, but doesn't really seem desirable as you would need to duplicate the if and try/catch the close in-case it throws an exception. The try-with-resource seems like the better option.

> we should detect these use cases when the resource is not used. They should be unnamed

In a way, it seems like it isn't a good idea to validate unused resources from the above.

Does it make more sense that we just create a new check to require unused resources to be unnamed? We already decided this route for catch and lambda parameters (https://github.com/checkstyle/checkstyle/issues/14960#issuecomment-2156025055).

@nrmancuso Please decide. While users may want to enable this to their desire, it seems like we are creating a violation which can only be resolved by suppression, removing the entire try/catch, or forcing them to add a usage of the resource (which may not be possible). Technically if we require a check to force unnamed, it will lead to the same but they can resolve the violation by making it unknown.

**Comment by nrmancuso** [comment]
First of all, thanks @rnveach and @mahfouz72  for your well thought out and detailed comments. After reflecting on these, I agree with:

> Does it make more sense that we just create a new check to require unused resources to be unnamed?

We should not force users to use suppressions everywhere for what is reasonable try with resources usage. This seems to be a fail on the language side, if anything. 

@mahfouz72 let’s create a ticket for the new check, then we can close this.

**Comment by mahfouz72** [comment]
> it seems like we are creating a violation which can only be resolved by suppression, removing the entire try/catch, or forcing them to add a usage of the resource (which may not be possible).

It can be resolved by turning off the property. Did you notice in my first post that I suggest this to be a property?

**Comment by nrmancuso** [comment]
> Did you notice in my first post that I suggest this to be a property?

Yes. In my mind, why add support to this check and make it more complex for one property, when it can easily be a separate check? We have shot ourselves in the foot on numerous other checks by making them more complicated than they need to be to support all kinds of tangentially related (at best) concepts. 

Let’s look over the check implementation and see if we can cleanly separate checking try with resources.

**Comment by nrmancuso** [comment]
Assigning back to me for a bit

**Comment by rnveach** [comment]
A note when we go for the new check, we should update the documentation of `UnusedLocalVariable` to say why it doesn't support try-with-resources and point them to the new check.

**Comment by mahfouz72** [comment]
> I think that we already have enough going on there. I would prefer to create a new check just for unused resources

I tend to disagree here I think it won't require mush extra work in the check. we just need to stop on `RESOURCE` and add it to the variable stack all other work should be handled by the current check code. I don't think there are any nuances. I vote for approving check updates we should try that first if things turn out to be complex and miss then at this point we should think of a new check. 

---
> does Intellij have a similar inspection?

Yes

```
  void m() throws Exception {
      int x = 0;
      try (var a = lock();) {    // variable a is never used, rename to '_'

      }
  }
```

**Comment by nrmancuso** [comment]
Let’s let this one marinate for a bit and think some more

**Comment by nrmancuso** [comment]
@mahfouz72 let's revisit this issue now that https://github.com/checkstyle/checkstyle/issues/14950 is merged

**Comment by mahfouz72** [comment]
@nrmancuso Ok. Let's make this check configurable by tokens and add `RESOURCE` to the acceptable tokens. UnusedVariable should look at resources at java 21+ so if users are below 21 then they shouldn't add `RESOURCE`.

**Comment by nrmancuso** [comment]
I cannot approve this issue without a draft PR as proof that this update will not cause any breaking changes; I also cannot guarantee that we will be on board with adding tokens property to this check.

If we are to add a tokens property to this check, we would need a separate issue/PR to do so. @mahfouz72 if you want to push ahead with extending UnusedLocalVariable, we will need to do the following:
1. Open an issue to add the `tokens` property to UnusedLocalVariable. We cannot base our reason for adding this property on this issue, as I don't want to introduce a circular dependency
2. Get ^ approved, send PR, and get that merged
3. Come back here, update the issue description using the new tokens property
4. Get approval on this issue and begin work

**Comment by romani** [comment]
UnusedLocalVariable implied removal of variable not a change to `_`.

It might be better to create new Check for goal that you try to archive.

**Comment by mahfouz72** [comment]
There is a disagreement on extending the current check, majority voting for a new check to achieve this. So I am closing this and  moved it to a new check in https://github.com/checkstyle/checkstyle/issues/15484
