### ISSUE TITLE
Add support to check input file against whole google configuration for Google IT tests

### ISSUE THREAD

**Issue by Zopsss** [checkstyle/checkstyle#15026]
Continuation of https://github.com/checkstyle/checkstyle/issues/14929

In the previous issue, we added support to check the input file against the provided list of modules. The verifyWithGooglexxx method for this issue takes file path of the input file and list of modules to load from the google config and check against it the input file. There is no need to provide `expected` violation array. No need to use `// warn` message, instead we require to use `// violation 'violation message'`, following the traditional `verifyWithInlineConfigParser()` way.

In the scope of this issue, we require to create a new `verifyWithWholeGoogleConfig()` ( name can be improved ) method which will only take file path of the input file as input. It will load the whole google config and check it against the input file. We don't need to provide any kind of module list, just the file path of input file.

This way we will need to compulsory follow all the rules of google style guide and show violations only for the required modules.

**Comment by rnveach** [comment]
I am approving this since we decided to go with this approach. We will be using the first few PRs to see how this goes since there was concerns in prior releases on doing this approach.
