### ISSUE TITLE
Add Check Support for Java 21 Unnamed Variables & Patterns Syntax: New Check UnusedLambdaParameterShouldBeUnnamed

### ISSUE THREAD

**Issue by mahfouz72** [checkstyle/checkstyle#15059]
child of #14942 
violate the non-use of the lambda parameters. They should be unnamed.

**Note:** The lambda parameters in the check are the parameters of [lambda expressions](https://docs.oracle.com/javase/specs/jls/se22/html/jls-15.html#jls-15.27) only. The unused pattern variables in the case label of the switch rule are not a target for this check.

---

**Config**

```XML
$ cat config.xml 
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name="Checker">
    <module name="TreeWalker">
        <module name="UnusedLambdaParameterShouldBeUnnamed"/>
    </module>
</module>
```

---

**Example**

```Java
public class Test {
    void test(Object obj) {
        List<String> list = List.of("a", "b", "c");
        List<String> Xss = list.stream().map(character -> "x").toList(); // violation
        List<String> Xs = list.stream().map(_-> "x").toList();
    }
}
```

---

**Expected Output**

```PowerShell
$ java -jar checkstyle-10.19.0-all.jar -c config.xml Test.java 
Starting audit...
[ERROR] D:\Test.java:4:45:Unused  lambda parameter should be unnamed [UnusedLambdaParameterShouldBeUnnamed]
Audit done.
Checkstyle ends with 1 errors.
```

**Comment by rnveach** [comment]
I am good with this but I need confirmation on what a lambda is to this check. Switch rules are lambdas in the tree. Will this check support this too or will ignore it?

I know we have https://github.com/checkstyle/checkstyle/issues/15085 but it hasn't been confirmed we will update `UnusedLocalVariable` yet. I think documentation should be made clear and first post should have an example of the switch rule lambda so we rule out confusion.

> `Unused  lambda`

Unnecessary double space.

> `List<String> Xss = list.stream().map(character -> "x").toList(); // violation`

This is expected violation.

**Comment by mahfouz72** [comment]
> I am good with this but I need confirmation on what a lambda is to this check. Switch rules are lambdas in the tree. Will this check support this too or will ignore it?

the lambda in the check is [lambda expressions](https://docs.oracle.com/javase/specs/jls/se22/html/jls-15.html#jls-15.27) only. switch rule is not a target for this check. I think it is not even considered a lambda expression. It just uses (`->`) same as lambda expressions. So, we will ignore switch rule for this check

> Also can we have multiple unnamed lambda parameters in one lambda expression?

Yes.
```
 Comparator<String> comparator = (_, _) -> {
            System.out.println("Comparing ");
            return 2;
        };
```

**Comment by nrmancuso** [comment]
The `->` being called a LAMBDA in switch rules was our bad, it is not a lambda. I am approving this issue.

**Comment by rnveach** [comment]
> The -> being called a LAMBDA in switch rules was our bad, it is not a lambda. I am approving this issue.

Do we plan to correct this in another issue?

If we won't ever correct this, I think the documentation for this check and first post should make clear we see these as different "lambda"s.

**Comment by rnveach** [comment]
@nrmancuso https://github.com/checkstyle/checkstyle/issues/15059#issuecomment-2192169795

**Comment by nrmancuso** [comment]
> > The -> being called a LAMBDA in switch rules was our bad, it is not a lambda. I am approving this issue.
> 
> Do we plan to correct this in another issue?
> 
> If we won't ever correct this, I think the documentation for this check and first post should make clear we see these as different "lambda"s.

We can make a new issue and discuss this there, I would love to do this but it would require major breaking changes and a lot of work. I really don’t think we need to mention it in this checks documentation since “lambda” is not the same as the token. If we were talking about the actual token in the documentation this would be different.
