### ISSUE TITLE
Add Check Support for Java 21 Unnamed Variables & Patterns Syntax:  DeclarationOrder

### ISSUE THREAD

**Issue by mahfouz72** [checkstyle/checkstyle#15065]
child https://github.com/checkstyle/checkstyle/issues/14942
I have read check documentation: https://checkstyle.org/checks/coding/declarationorder.html

---

> According to [Code Conventions for the Java Programming Language](https://checkstyle.org/styleguides/sun-code-conventions-19990420/CodeConventions.doc2.html#a1852) , the parts of a class or interface declaration should appear in the following order:
> 
> Class (static) variables. First the public class variables, then protected, then package level (no access modifier), and then private.
> Instance variables. First the public class variables, then protected, then package level (no access modifier), and then private.
> Constructors
> Methods

unnamed variables can't be class fields. and  unnamed pattern variable and unnamed patterns is part of a relational expression (if or case). we can close this

**Comment by rnveach** [comment]
I am good with closing this.
