### ISSUE TITLE
Add Check Support for Java 21 Unnamed Variables & Patterns Syntax: MagicNumber

### ISSUE THREAD

**Issue by mahfouz72** [checkstyle/checkstyle#15069]
child of #14942 :

doc :https://checkstyle.org/checks/coding/magicnumber.html

---

```
PS D:\CS\test> cat src/Test.java  
import java.util.LinkedHashMap;
import java.util.List;

record ColoredPoint(String p, String x, int c) { }
record Rectangle(ColoredPoint upperLeft, ColoredPoint lowerRight) { }

public class Test {
    void test(Object obj) {
       int _ = 4;

    }
}

PS D:\CS\test> cat config.xml                                                   
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
        "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
<module name="Checker">
    <property name="charset" value="UTF-8"/>
    <module name="TreeWalker">
        <module name="MagicNumber">
        </module>
    </module>
</module>
PS D:\CS\test> javac src/Test.java
PS D:\CS\test> java  -jar checkstyle-10.17.0-all.jar -c config.xml src/Test.java
Starting audit...
[ERROR] D:\CS\test\src\Test.java:9:16: '4' is a magic number. [MagicNumber]
Audit done.
Checkstyle ends with 1 errors.
PS D:\CS\test> 

```

---

The check always detects magic numbers whether it is assigned to an unnamed variable or not.

**Comment by rnveach** [comment]
Please add an example of a pattern as well.

I am good to add an input.

**Comment by mahfouz72** [comment]
I don't get it. we can't declare a pattern with a magic number. The pattern is being matched only can you share example?

**Comment by rnveach** [comment]
Sorry, patterns can't have numbers directly assigned to them. They are just type and variable name. I believe I was trying to say this issue didn't mention patterns at all, and patterns can have `when`s. This might be another issue, but did we try this check with `when` on patterns?

**Comment by nrmancuso** [comment]
This check is fine on patterns with a `when` guard:
```
➜  src javac Test.java
➜  src cat Test.java  
public class Test {
    public static void main(String[] args) {

       Object o = new Object();

        if (o instanceof Integer i && i < 3) { // violation
            System.out.println("null");
        } else {
            System.out.println("not null");
        }

        switch (o) {
            case Integer i when i < 3: // violation
                System.out.println("null");
                break;
            default:
                System.out.println("not null");
        }
    }
}
➜  src cat config.xml 
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
        "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
<module name="Checker">
    <property name="charset" value="UTF-8"/>
    <module name="TreeWalker">
        <module name="MagicNumber">
        </module>
    </module>
</module>
➜  src java -jar checkstyle-10.17.0-all.jar -c config.xml Test.java
Starting audit...
[ERROR] /home/nick/IdeaProjects/tester/src/Test.java:6:43: '3' is a magic number. [MagicNumber]
[ERROR] /home/nick/IdeaProjects/tester/src/Test.java:13:37: '3' is a magic number. [MagicNumber]
Audit done.
Checkstyle ends with 2 errors.
```

We can skip opening an issue for this if we don't already have one.

This check will not apply to unnamed patterns at all, since `_` can never be referenced (therefore we cannot use it in a `when` guard where we would have some conditional).

**Comment by mahfouz72** [comment]
> do we have an issue for this one?

the things related to `when` only should be covered in the pattern matching for switch syntax tracker. this syntax is not related to unnamed patterns. But the list of the checks there doesn't have `MagicNumberCheck`. So, No we don't have an issue with this syntax for this check. do you think we should open one for an input file only (the behavior is correct)?

---
> This check will not apply to unnamed patterns at all, since _ can never be referenced (therefore we cannot use it in a when guard where we would have some conditional).

then I think we can close this

**Comment by rnveach** [comment]
> the things related to when only should be covered in the pattern matching for switch syntax tracker

https://github.com/checkstyle/checkstyle/issues/14961

> do you think we should open one for an input file only (the behavior is correct)?

I am good with this.

> then I think we can close this

@nrmancuso

**Comment by mahfouz72** [comment]
https://github.com/checkstyle/checkstyle/issues/15107

**Comment by nrmancuso** [comment]
Approved for test inputs
