### ISSUE TITLE
Add Check Support for Java 21 Unnamed Variables & Patterns Syntax: AnnotationLocation

### ISSUE THREAD

**Issue by mahfouz72** [checkstyle/checkstyle#15060]
child of #14942 :
Check documentation:https://checkstyle.org/checks/annotation/annotationlocation.html#AnnotationLocation

```
PS D:\CS\test> cat src/Test.java                                                
record ColoredPoint(int p, int x, int c) { }
record Rectangle(ColoredPoint upperLeft, ColoredPoint lowerRight) { }

public class Test {
    void test(Object obj) {
        if (obj instanceof ColoredPoint( @Deprecated int _,_,_)){
        }
        @Deprecated
        int _ = 0;
    }
}

PS D:\CS\test> cat config.xml                                                   
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
        "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
<module name="Checker">
    <property name="charset" value="UTF-8"/>
    <module name="TreeWalker">
        <module name="AnnotationLocation">
        </module>
    </module>
</module>
PS D:\CS\test> java  -jar checkstyle-10.17.0-all.jar -c config.xml src/Test.java
Starting audit...
Audit done.
PS D:\CS\test> 
```

---
No update is needed for this check.

**Comment by rnveach** [comment]
@mahfouz72 Is it possible to show an example of a violation with unnamed so we know for sure there is no falses? If so, please update first post.

Can the annotation itself have an unnamed?

Otherwise, I am good with an input if there is no concern for this check.

**Comment by mahfouz72** [comment]
I noticed that the variables inside the methods are not being checked. this check only checks for class fields if this is the correct 
behavior (nothing in the doc says that so I am not sure but all examples are on class fields) then we are good we can't have unnamed fields 
```
PS D:\CS\test> cat src/Test.java                                                
record ColoredPoint(int p, int x, String c) { } 
record Rectangle(ColoredPoint upperLeft, ColoredPoint lowerRight) { }
public class Test {
    @SuppressWarnings("deprecation") int x = 0;         // violation
    void test(Object obj) {
        if (obj instanceof ColoredPoint(@SuppressWarnings("deprecation") int _, _ , _)) {
        }
        @SuppressWarnings("deprecation") int x = 0;  // ok ?
    }

}
PS D:\CS\test> java  -jar checkstyle-10.17.0-all.jar -c config.xml src/Test.java
Starting audit...
[ERROR] D:\CS\test\src\Test.java:4:5: Annotation 'SuppressWarnings' should be alone on line. [AnnotationLocation]
Audit done.
Checkstyle ends with 1 errors.
PS D:\CS\test> 

```

---

> Can the annotation itself have an unnamed?

nope.

**Comment by rnveach** [comment]
> Attention: Elements that cannot have JavaDoc comments like local variables are not in the scope of this check even though a token type like VARIABLE_DEF would match them. 

I missed this in documentation. So we can't have unnamed in these spots.

**Comment by nrmancuso** [comment]
This check does not validate local variables at all, we can make a simple input file and move on.
