### ISSUE TITLE
Add Check Support for Java 21 Unnamed Variables & Patterns Syntax: HiddenField

### ISSUE THREAD

**Issue by mahfouz72** [checkstyle/checkstyle#15066]
child of #14942

Check documentation : https://checkstyle.org/checks/coding/hiddenfield.html

---

unnamed variables can't be fields so the hidden field check won't get  affected by unnamed variables.

```
public class Test {
    String c;
    void test(Object obj) {
        if (obj instanceof ColoredPoint(String c, String _, int _)) {  // violation, c hides field 
                                                //  '_' can't hide a field
            c.equals("s");
        }
    }
}
```

**Comment by rnveach** [comment]
I think we should just add an input and move on.

**Comment by nrmancuso** [comment]
I think we can skip an input for this one, we need to move on.
