### ISSUE TITLE
Add Check Support for Java 21 Unnamed Variables & Patterns Syntax: ExplicitInitialization

### ISSUE THREAD

**Issue by mahfouz72** [checkstyle/checkstyle#15064]
child https://github.com/checkstyle/checkstyle/issues/14942
I have read check documentation: https://checkstyle.org/checks/coding/explicitinitialization.html
I have downloaded the latest checkstyle from: https://checkstyle.org/cmdline.html#Download_and_Run
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

---
```
public class Test {
    int x = 0; // violation,  (default value for its type). 
    int _ = 0; // compile error, unnamed field is not allowed
}

```

---
Unnamed variables and unnamed patterns is not applicable to explicit initialization

**Comment by rnveach** [comment]
I am good with dropping this issue.

**Comment by nrmancuso** [comment]
This check is only for fields, I am closing this issue.
