### ISSUE TITLE
Add Check Support for Java 21 Unnamed Variables & Patterns Syntax: VariableDeclarationUsageDistanceCheck

### ISSUE THREAD

**Issue by mahfouz72** [checkstyle/checkstyle#15071]
child of #14942:  
check doc : https://checkstyle.org/checks/coding/variabledeclarationusagedistance.html

---

Declaring an unnamed variable does not place a name in scope, so the variable cannot be written or read after it is initialized, So the usage distance isn't applicable for unnamed variables. They can not be used.

**Comment by rnveach** [comment]
> does not place a name in scope, so the variable cannot be written or read after it is initialized

Except for older Java versions, correct?

I am good with just closing this issue.

**Comment by nrmancuso** [comment]
> > does not place a name in scope, so the variable cannot be written or read after it is initialized
> 
> Except for older Java versions, correct?
> 
> I am good with just closing this issue.

Agreed.
