### ISSUE TITLE
Document System Variables usage for Windows OS

### ISSUE THREAD

**Issue by Zopsss** [checkstyle/checkstyle#15089]
I have downloaded the latest checkstyle from: https://checkstyle.org/cmdline.html#Download_and_Run
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

Referring to: https://github.com/checkstyle/checkstyle/pull/15028#discussion_r1647559846

In this PR, I had modified the `severity` property of [google_checks.xml](https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/google_checks.xml) from:
```
<property name="severity" value="warning"/>
```

to

```
<property name="severity" value="${org.checkstyle.google.severity}" default="warning"/>
```

So we should be able to dynamically change severity level of google_checks.xml using system variable in CLI by something like:

```
java -Dorg.checkstyle.google.severity=error -jar checkstyle-xx.xx.x-all.jar -c google_checks.xml Test.java
```

But this gives error. Here is an example of it:

#### Test.java
```java
public class Test {}
```

#### Output
```
$ java -Dorg.checkstyle.google.severity=error -jar .\checkstyle-10.17.0-all.jar -c .\google_checks.xml .\Test.java
Error: Could not find or load main class .checkstyle.google.severity=error
Caused by: java.lang.ClassNotFoundException: /checkstyle/google/severity=error
```

Now if I modify the `severity` property in google_checks.xml to something like:

```
<property name="severity" value="${testing}" default="warning"/>
```

This works fine. Here's an example of it:

```
$ java -Dtesting=error -jar .\checkstyle-10.17.0-all.jar -c .\google_checks.xml .\Test.java                       
Starting audit...
[ERROR] C:\checkstyle testing\TestingGoogleStyle\.\Test.java:1:1: Missing a Javadoc comment. [MissingJavadocType]
Audit done.
Checkstyle ends with 1 errors.
```

The CLI is working perfectly for this modification, we're able to change severity level from `warning` to `error`. 

We should expect the same behavior for `severity` property mentioned at the beginning:

```
<property name="severity" value="${org.checkstyle.google.severity}" default="warning"/>
```

**Comment by rnveach** [comment]
> Error: Could not find or load main class .checkstyle.google.severity=error

This is a Java error, not a Checkstyle error. This is not a main class.

Are you on Windows? Did you try quoting the property name and value? Ex: `java "-Dorg.checkstyle.google.severity=error" ....`

**Comment by rnveach** [comment]
Proof issue above looks to be a Windows issue, and that the new property works via system property:
````
PS \target> java -jar .\checkstyle-10.18.0-SNAPSHOT-all.jar -c google_checks.xml .\Test.java
Starting audit...
[WARN] M:\checkstyleWorkspaceEclipse\checkstyle\target\.\Test.java:1:1: Missing a Javadoc comment. [MissingJavadocType]
Audit done.

PS \target> java -Dorg.checkstyle.google.severity=error -jar .\checkstyle-10.18.0-SNAPSHOT-all.jar -c google_checks.xml .\Test.java
Error: Could not find or load main class .checkstyle.google.severity=error
Caused by: java.lang.ClassNotFoundException: /checkstyle/google/severity=error

PS \target> java -D"org.checkstyle.google.severity=error" -jar .\checkstyle-10.18.0-SNAPSHOT-all.jar -c google_checks.xml .\Test.java
Starting audit...
[ERROR] M:\checkstyleWorkspaceEclipse\checkstyle\target\.\Test.java:1:1: Missing a Javadoc comment. [MissingJavadocType]
Audit done.
Checkstyle ends with 1 errors.
````

I am closing this issue.

**Comment by romani** [comment]
Let's extend documentation, this is crazy nuance, no much people know about it.

**Comment by rnveach** [comment]
This is OS level controlled and OS specific. I am pretty sure linux doesn't need the quotes.

I thought we agreed in other issues we would not get into things outside our perview. This is not something specific to Checkstyle. Users should find other documentation on how to use Java's system property from command line.

**Comment by romani** [comment]
For me this nuance is very non intuitive.
@nrmancuso , what is your opinion on this?

**Comment by Zopsss** [comment]
> Are you on Windows? Did you try quoting the property name and value? Ex: java -D"org.checkstyle.google.severity=error"

Yes Im on windows and after quoting the property it started working. Thanks for the help I did not knew about quoting the property

**Comment by nrmancuso** [comment]
> For me this nuance is very non intuitive. @nrmancuso , what is your opinion on this?

My opinion is that we should extend our docs to mention this, but not as part of GSOC.

**Comment by romani** [comment]
@nrmancuso , PR is already opened, please look.

**Comment by rnveach** [comment]
@nrmancuso If you agree with this issue, please mark it approved.

**Comment by nrmancuso** [comment]
Issue is approved, I am personally not a big fan of telling users how to use their command line, but if we can help save someone some time, I am good.
