### ISSUE TITLE
Refactor MainTest to avoid usage of System.setProperty that affect other tests

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#15083]
detected at https://github.com/checkstyle/checkstyle/pull/15072#issuecomment-2181549655

should be a remedy https://junit-pioneer.org/docs/system-properties/

We need find all usages of "System.setProperty" and use junit annoations to guard rail system variables.
Multithreading considerations for now out of scope.

**Comment by rnveach** [comment]
@romani This is a duplicate of https://github.com/checkstyle/checkstyle/issues/15073 .
We should forbid this everywhere in the tests. It is a global issue and we need a way to forbid it.

**Comment by romani** [comment]
but other tools already have this property extension mechanism - https://maven.apache.org/plugins/maven-checkstyle-plugin/examples/custom-property-expansion.html

so we should use system property where we declare it as system property https://checkstyle.org/config_system_properties.html
 and should use `-p propertiesFile - Sets the property files to load.` where it is just property.
