### ISSUE TITLE
Investigate UTs failure to MainTest on Windows

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#1510]
https://ci.appveyor.com/project/Checkstyle/checkstyle/build/285/job/es7cf2tftn4okjby#L664

https://travis-ci.org/checkstyle/checkstyle/jobs/73144166#L739

**Comment by mkordas** [comment]
@romani - what do you want to investigate here? Reason is quite obvious from failure message and the easiest solution would be to use `TemporaryFolder` rule instead of creating file manually in `testLoadProperties_IOException`.

Failure message:
```
MainTest.testLoadProperties_IOException:393 expected:<...operties from file '[]\invalid'.> but was:<...operties from file '[C:]\invalid'.>```

**Comment by romani** [comment]
that is task for myself , test is created to do coverage , launch on linux and windows works differently and go paths so coverage is not 100% event is it 100% on linux. I will launch it on Windows today

**Comment by romani** [comment]
merged.

Reason:
That works fine on Linux/Unix, but ....
It's not possible to make a file unreadable in Windows NTFS for owner.
http://stackoverflow.com/a/4354686
https://github.com/google/google-oauth-java-client/issues/55#issuecomment-69403681
