### ISSUE TITLE
Add Check Support for Java 21 Unnamed Variables & Patterns Syntax: Javadoc Checks

### ISSUE THREAD

**Issue by mahfouz72** [checkstyle/checkstyle#15110]
child of https://github.com/checkstyle/checkstyle/issues/14942

#### AtclauseOrderCheck

doc :  https://checkstyle.org/checks/javadoc/atclauseorder.html

> Checks the order of javadoc tags

the targeted variable definition here is the variable definition that is a class field only. and since the unnamed variables can't be class field then this check is completely unrelated.

---

#### JavadocStyleCheck
doc :  https://checkstyle.org/checks/javadoc/javadocstyle.html

> Validates Javadoc comments to help ensure they are well formed.

the targeted variable definition here is the variable definition that is a class field only. and since the unnamed variables can't be class field then this check is completely unrelated.

---

#### JavadocVariable

doc : https://checkstyle.org/checks/javadoc/javadocvariable.html
> Checks that a variable has a Javadoc comment.

the targeted variable definition here is the variable definition that is a class field only. and since the unnamed variables can't be class field then this check is completely unrelated.

---

Example: 

```
PS D:\CS\test> javac src/Test.java                                              
PS D:\CS\test> cat config.xml                                                   
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
        "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
<module name="Checker">
    <property name="charset" value="UTF-8"/>
    <module name="TreeWalker">
               <module name="JavadocStyle">
        </module>
    </module>
</module>
PS D:\CS\test> cat src/Test.java                                                
public class Test {

    /**
     * Some description here             // violation
     */
    int i = 0;

    public void test() {
        /**
         * Some description here
         */
        int _ = 0;  // this is not being checked because it is not a class field

    }
}
PS D:\CS\test> java  -jar checkstyle-10.17.0-all.jar -c config.xml src/Test.java
Starting audit...
[ERROR] D:\CS\test\src\Test.java:3: First sentence should end with a period. [JavadocStyle]
Audit done.
Checkstyle ends with 1 errors.
PS D:\CS\test> 

```

---
#### InvalidJavadocPosition
doc : https://checkstyle.org/checks/javadoc/invalidjavadocposition.html#InvalidJavadocPosition

The check violates the invalid Javadoc position on the unnamed variables (local variable) so it works as intended.
```

$ cat TestClass.java
public class Test {

    /**
     * Some description here             // violation
     */
    int i = 0;

    public void test() {
        /**
         * Some description here
         */
        int _ = 0;  // this is not being checked because it is not a class field

    }
}

$ cat TestConfig.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
          "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name="Checker">
  <module name="TreeWalker">
    <module name="InvalidJavadocPosition"/>
  </module>
</module>

$ java -jar checkstyle-10.17.0-all.jar -c TestConfig.xml TestClass.java
Starting audit...
[ERROR] TestClass.java:9:9: Javadoc comment is placed in the wrong location. [InvalidJavadocPosition]
Audit done.
Checkstyle ends with 1 errors.
```

**Comment by rnveach** [comment]
This may be an example of what happens if we don't scan utils.
https://checkstyle.org/checks/javadoc/invalidjavadocposition.html#InvalidJavadocPosition
I would expect your local variable to put a violation with this check. It wasn't picked up by the scan since this check uses a lot of utils as it was developed as a way to prove our utils were picking up all cases correctly.

````
$ cat TestClass.java
public class Test {

    /**
     * Some description here             // violation
     */
    int i = 0;

    public void test() {
        /**
         * Some description here
         */
        int _ = 0;  // this is not being checked because it is not a class field

    }
}

$ cat TestConfig.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
          "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name="Checker">
  <module name="TreeWalker">
    <module name="InvalidJavadocPosition"/>
  </module>
</module>

$ java -jar checkstyle-10.17.0-all.jar -c TestConfig.xml TestClass.java
Starting audit...
[ERROR] TestClass.java:9:9: Javadoc comment is placed in the wrong location. [InvalidJavadocPosition]
Audit done.
Checkstyle ends with 1 errors.
````

@mahfouz72 Have we done any verification that our automated scan isn't missing any checks we should be looking at?
Also update your first post with this check.

**Comment by rnveach** [comment]
I am good with this issue. No updates and just close the issue.
