### ISSUE TITLE
Add Check Support for Java 21 Unnamed Variables & Patterns Syntax: RequireThis

### ISSUE THREAD

**Issue by mahfouz72** [checkstyle/checkstyle#15111]
child of #14942 
doc : https://checkstyle.org/checks/coding/requirethis.html#RequireThis

from the doc : 

> Checks that references to instance variables and methods of the present object are explicitly of the form "this.varName" or "this.methodName(args)" and that those references don't rely on the default behavior when "this." is absent.

Unnamed variables are not instance variables also we can't have unnamed methods, so this check does not need any update.

**Comment by rnveach** [comment]
I am good on closing issue.
