### ISSUE TITLE
RightCurlyCheck should print user a column number in log message.

### ISSUE THREAD

**Issue by MEZk** [checkstyle/checkstyle#1511]
When we use right curly policy ALONE  it is not clear to what curly brace is violated in following code example and etc: 
````java
} finally { toString(); } //line 580
````
![screenshot](https://cloud.githubusercontent.com/assets/7242568/8966273/2459a1e4-3639-11e5-9dd0-f166e1e16f54.png)

We need to print user a column number to exactly point him to a problem.

**Comment by romani** [comment]
additionally please do:

1)
> public void setShouldStartLine(boolean flag) {

add to javadoc

2) 
>
        final DetailAST rcurly = details.rcurly;
...
        final DetailAST lcurly = details.lcurly;
        validate(details, rcurly, lcurly);

just put as argument "details" only.

3)
> private void validate(Details details, DetailAST rcurly, DetailAST lcurly) {

we need to make that method static, to clearly indicate that it is pure algorith without side-effects.
It could return key violations message string , and all logging will be in visitToken() method. shouldStartLine - should be passed as argument to that method.

**Comment by romani** [comment]
4) 
https://github.com/checkstyle/checkstyle/blob/master/src/xdocs/property_types.xml#L288

next statement should be updated to "part of a multi-block statement (one that directly contains multiple blocks: if/else-if/else or try/catch/finally)."

source: http://google.github.io/styleguide/javaguide.html#s4.1.3-braces-empty-blocks

**Comment by MEZk** [comment]
@romani 
We should also provide internationalization for all new messages in properties according to context, but it should be done by those who are know the language.

From my point of view, we should print column number immediatly after ```}``` in messages this will be a good format for new messages:

```'}' (column ##) should be alone on a line.```

What do you think?

**Comment by romani** [comment]
'}'  at column ## should be alone on a line.

**Comment by romani** [comment]
merged finctional changes and refactoring.

thanks a lot!
