### ISSUE TITLE
Bdd violations messages does not allow skip of leading '.*'

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#15138]
problem is detected at:
https://github.com/checkstyle/checkstyle/pull/15126#discussion_r1654047096

if violation message is long we have to use short/small section of it sometime in the middle to keep most meaning  
this is required now: `// violation above '.* 'newCustomerID' .* no more than '1' .* capital letters.'`
is we try to remove '.*' test is failing

desirable: `// violation above 'newCustomerID.* no more than '1' .* capital letters.'`

**Comment by rnveach** [comment]
If you assume everything starts with `.*`, you will never be able to properly validate the whole violation message is added.

**Comment by romani** [comment]
We never validate whole message in BDD comment, it is not practical. We use it as hint on what violation it is.

Whole message is validated in Test classes by `expected` array that has columns and whole message.

**Comment by rnveach** [comment]
> Right now it forcing us to use cryptic ".*"

Which shows we actually are enforcing entire message.

If we are never going to validate entire message, why don't we automatically inject leading and **trailing** `.*`?

**Comment by rnveach** [comment]
> Because this sting is regexp provided by contributor in file, there might good reason to have .*.

Assuming you mean **trailing** `.*` otherwise, you are providing an example why we **shouldn't** do this issue.

> For us in validation message, we don't need whole content match and strict regexp.
> We just need some short distinct phrases from message to understand different violation message from same Check.

This still doesn't explain why we don't just always add leading and trailing `.*` or switch to a find.

It looks like the referenced commit switches to a find, so if that is the way we are going, then this will support leading and trailing `.*`.

**Comment by romani** [comment]
Yes, find() kind of imply leading and trailing `.*`.
So better to use existing function for it.

**Comment by rnveach** [comment]
We should update old inputs to drop these.

**Comment by romani** [comment]
New issue is created https://github.com/checkstyle/checkstyle/issues/15144

**Comment by rnveach** [comment]
@romani Since you guys duplicated the code, doesn't this also need to be applied in IT area?

**Comment by rnveach** [comment]
Also this only covers "above". What about below and the others?

**Comment by romani** [comment]
https://github.com/search?q=repo%3Acheckstyle%2Fcheckstyle%20VIOLATION_MESSAGE_PATTERN&type=code

We did not duplicate code.
