### ISSUE TITLE
Update all Inputs that has inlined violations to avoid leading and trailing wildcard 

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#15144]
After fixing https://github.com/checkstyle/checkstyle/issues/15138#issuecomment-2192619787

We can update trailing comments like (just example):
`// violation above '.*`
To be
`// violation above '`

All violation comments of all types should be updated.

Trailing wildcard also should be removed

**Comment by rnveach** [comment]
We should also do trailing.
