### ISSUE TITLE
RedundantModifer Should Violate Final Modifer on Unnamed Variables if jdkVersion GTE 22

### ISSUE THREAD

**Issue by mahfouz72** [checkstyle/checkstyle#15159]
child of #14942 

Check documentation: https://checkstyle.org/checks/modifier/redundantmodifier.html#RedundantModifier

---

```
PS D:\CS\test> cat config.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
          "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name="Checker">
  <module name="TreeWalker">
    <module name="RedundantModifier"/>
    <property name="jdkVersion" value="21"/>
  </module>
</module>
PS D:\CS\test> cat src/Test.java
public class Test {
    void m(Object o) throws Exception {
        try (final var a = lock()) {  // violation , resource is effective final
        }

        if (o instanceof R(final int _)) { // expected violation, unnamed pattern variable is effective final

        }

        final int _ = sideEffect(); // expected violation, unnamed variable is effective final
    }
    AutoCloseable lock() { return null; }
    record R(int x) { }
    int sideEffect() { return 0; }
}
PS D:\CS\test> java  -jar checkstyle-10.17.0-all.jar -c config.xml  src/Test.java                                           
Starting audit...
[ERROR] D:\CS\test\src\Test.java:3:14: Redundant 'final' modifier. [RedundantModifier]
Audit done.
Checkstyle ends with 1 errors.
PS D:\CS\test> 
```

---

[JLS](https://docs.oracle.com/javase/specs/jls/se22/html/jls-6.html#jls-6.3) :

> If a declaration does not include an identifier, but instead includes the keyword _ (underscore), then the entity cannot be referred to by name. The following kinds of entity may be declared using an underscore:

Like resources, unnamed variables are effectively final which means that whether the unnamed variable has final modifier or not. the variable can't be reassigned. I expect a violation on the redundant modifer check on unnamed variables.

---
**Describe what you want in detail.**

We should update `RedundantModifer`  to violate the `final` modifier on unnamed variables if `jdkVersion` is >= 22. If a user is on old Java versions (below Java 9). the final modifier will not be redundant because `_` is a normal identifier in this case. 

Example:

```
PS D:\CS\test> cat config.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
          "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name="Checker">
  <module name="TreeWalker">
    <module name="RedundantModifier"/>
    <property name="jdkVersion" value="8"/>
  </module>
</module>
PS D:\CS\test> cat src/Test.java
public class Test {
    void m(Object o) throws Exception {
        final int _ = sideEffect(); // ok, jdkVersion is 8. underscore can be used as normal identifier so final is not redundant
    }
    AutoCloseable lock() { return null; }
    record R(int x) { }
    int sideEffect() { return 0; }
}
PS D:\CS\test> java  -jar checkstyle-10.17.0-all.jar -c config.xml  src/Test.java                                           
Starting audit...
Audit done.
Checkstyle ends with 0 errors.

```

**Note**: This update also includes `final` modifier on unnamed lambda parameters and unnamed catch parameters.

**Comment by rnveach** [comment]
I am good with the basic issue. Documentation needs to be updated as we say what `The check validates` in it.

It looks like all tokens are configurable on this check. For example, you could turn off resources by removing `RESOURCE`. I am not seeing how we can do this with `_`, since it is seen as the same token as other things. I am not sure if someone wants to be able to turn this off. Even if we make this assumption they don't, old Java versions (before 9) this would not be redundant as `_` was an allowed identifier for local variables. `instanceof` example was not possible in old versions.

I am thinking we may need a property to allow turning this on/off to not break the old versions. One other issue we had gone with `ignoreUnnamedVariables`. I forgot if there was others, but I couldn't find it. I am fine with going with this.

**Comment by mahfouz72** [comment]
Yes, I expect to see Resource here. so documentation should be updated

> The check validates:
> 
> 1. Interface and annotation definitions.
> 2. Final modifier on methods of final and anonymous classes.
> 3. Type declarations nested under interfaces that are declared as public or static.
> 4. Class constructors.
> 5. Nested enum definitions that are declared as static.
> 6. record definitions that are declared as final and nested record definitions that are declared as static.

I agree, I am good with a new property to not break check with the old versions.

**Comment by nrmancuso** [comment]
I am approving for new property and documentation update as a supplemental change (separate PR is good).

**Comment by rnveach** [comment]
@nrmancuso @mahfouz72 Just to confirm we are dropping `ignoreUnnamedVariables` as mentioned earlier and instead going with the Java version to basically do the same thing?

@mahfouz72 Please update first post on the property and it's handling.

**Comment by nrmancuso** [comment]
>@nrmancuso @mahfouz72 Just to confirm we are dropping ignoreUnnamedVariables as mentioned earlier and instead going with the Java version to basically do the same thing?

Yes, I think we discussed this in discord (or maybe I made this up), but I think this provides a consistent approach with the other update in this check.

**Comment by mahfouz72** [comment]
> @nrmancuso @mahfouz72 Just to confirm we are dropping ignoreUnnamedVariables as mentioned earlier and instead going with the Java version to basically do the same thing?

Yes. I mentioned this here https://github.com/checkstyle/checkstyle/pull/15376#issuecomment-2252749023

The first post and title are updated.
