### ISSUE TITLE
Documentation: Setting English as the language for messages

### ISSUE THREAD

**Issue by kasper** [checkstyle/checkstyle#152]
It would be worth to note in the documentation that if you wish to have English as the language for the validation messages, you need to set both the `localeCountry` and `localeLanguage` as empty strings (ROOT-locale) rather than English. English will not work, as there are no `messages_en.properties` language files.

```xml
<property name='localeCountry' value='' />
<property name='localeLanguage' value='' />
```

**Comment by andreas-wolf** [comment]
+1, please fix this. Took me hours to figure out that 'en' is an invalid entry.
I think that this is not a bug in the documentation but in the code.

**Comment by mkordas** [comment]
@romani - should we add `en` as possible value or just improve documentation?

**Comment by andreas-wolf** [comment]
Since this setting accepts ISO codes and 'en' is one you should really fix the code for the sake of consistency.

**Comment by romani** [comment]
related issue - #1044

**Comment by romani** [comment]
merged
