### ISSUE TITLE
Format google IT tests' input files to follow all the rules of google java style guide

### ISSUE THREAD

**Issue by Zopsss** [checkstyle/checkstyle#15218]
All google tests are being migrated to whole config testing in this issue: https://github.com/checkstyle/checkstyle/issues/15214

We detected that Google java style simply reference to google-java-format as source of truth for specific chapter about line length (not whole) https://github.com/checkstyle/checkstyle/pull/14901/files#r1639771738 , same is location of `{` at https://github.com/checkstyle/checkstyle/pull/14901/files#r1621156853 . So we need to use this tool for Inputs and see cases where we are conflicting to make decision who is right. For other chapters we will still look at style guide first as source of truth.

As part of this issue, all the google tests' input files needs to be formatted to follow [google java style guide](https://google.github.io/styleguide/javaguide.html) rules. The input files should be formatted by [google-java-format](https://github.com/google/google-java-format) tool locally. This tool helps us to format the java file to follow google java style guide rules. Though this tool formats only some specific parts of the input file, it can fix incorrect spacing, indentation, brackets/curly braces placements, etc but it cannot fix incorrect variable names, missing javadoc comments, etc.

The input files will require to follow all the rules of the style guide, expect it will contain violations only corresponding to their section. In some cases, the input file will require some extra violations outside its corresponding section, which will be required to test the section properly, example: https://github.com/checkstyle/checkstyle/pull/15220#discussion_r1671190653

---

Initially, we thought of adding google-java-format tool as a dependency to our project ( [PR](https://github.com/checkstyle/checkstyle/commit/04ccd77368ac3761e1d54d9c89c738450cbb3415#diff-3323f2bf6b63b5111ea2e99bde3afbdbb048701d56afaee6170bbc10a4fe6e46) in which we tried to did this ) but after doing discussion on this topic, maintainers have come upon the idea of not adding this tool as a dependency for now. In future, we might add support for this tool, but for now we're not doing this, this tool should be used locally to format the input file but should not be added to CS as a dependency.

---

Input files of following sections needs to be formatted to follow all rules of google java style guide:

- [x] 2.1 File name
- [x] 2.3.1 Whitespace characters
- [x] 2.3.2 Special escape sequences
- [x] 2.3.3 Non-ASCII characters
- [x] 3 Source file structure
- [x] 3.2 Package statement
- [x] 3.3.2 No line-wrapping
- [x] 3.3.3 Ordering and spacing
- [x] 3.4.1 Exactly one top-level class declaration
- [x] 3.4.2.1 Overloads: never split
- [x] 4.1.1 Use of optional braces
- [x] 4.1.2 Nonempty blocks: K & R style
- [x] 4.1.3 Empty blocks: may be concise
- [x] 4.2 Block indentation: +2 spaces
- [x] 4.3 One statement per line
- [x] 4.4 Column limit: 100
- [x] 4.5.1 Where to break
- [x] 4.5.2 Indent continuation lines at least +4 spaces
- [x] 4.6.1 Vertical Whitespace
- [x] 4.6.2 Horizontal whitespace
- [x] 4.8.2.1 One variable per declaration
- [x] 4.8.2.2 Declared when needed
- [x] 4.8.3.2 No C-style array declarations
- [x] 4.8.4.1 Indentation
- [x] 4.8.4.2 Fall-through: commented
- [x] 4.8.4.3 Presence of the default label
- [x] 4.8.5.3 Methods And Constructors Annotations
- [x] 4.8.5.4 Field Annotations
- [x] 4.8.6.1 Block comment style
- [x] 4.8.7 Modifiers
- [x] 4.8.8 Numeric Literals
- [x] 5.2.1 Package names
- [x] 5.2.2 Class names
- [x] 5.2.3 Method names
- [x] 5.2.5 Non-constant field names
- [x] 5.2.6 Parameter names
- [x] 5.2.7 Local variable names
- [x] 5.2.8 Type variable names
- [x] 5.3 Camel case: defined
- [x] 6.2 Caught exceptions: not ignored
- [x] 6.4 Finalizers: not used
- [x] 7.1.1 General form
- [x] 7.1.2 Paragraphs
- [x] 7.1.3 Block tags
- [x] 7.2 The summary fragment
- [x] 7.3 Where Javadoc is used
- [x] 7.3.1 Exception: self-explanatory methods
- [x] 7.3.2 Exception: overrides
- [x] 7.3.4 Non-required Javadoc

**Comment by nrmancuso** [comment]
After reading this issue description multiple times, I still cannot understand why we are doing this, how this is in scope for GSOC, and why we did not get maintainer consensus on the issue before approval.

**Comment by romani** [comment]
In future, we will move formatting of inputs to special CI job to do this (kind  of requirements before jdk17) , outside of mvn install execution, but it is more complicated process, let's not go this direction now.
It is better to do this when all is set on what we format and how it works and how we handle edge cases.

**Comment by romani** [comment]
> In future, we will move formatting of inputs to special CI job

Ok, I forgot to mention that in 2 days also mean "future" , here it is, CI job:
https://github.com/checkstyle/checkstyle/pull/15237

**Comment by Zopsss** [comment]
GitHub, generate site

**Comment by Zopsss** [comment]
all sections have been formatted, closing the issue
