### ISSUE TITLE
Google style coverage table should have all paragraphs 

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#15217]
Detected at https://github.com/checkstyle/checkstyle/pull/15213#discussion_r1670332597

To avoid confusion, we should have all paragraphs, it is ok is most of them with be empty with arrows down image.
It will be explicit definition that it was considered and nothing be covered there.

If there is some text in paragraph, It should be present in coverage table. We can skip, if there is no text at all.

**Comment by romani** [comment]
@Zopsss, is there anything left ?

**Comment by Zopsss** [comment]
@romani 2 sections were missing, added them in this PR: https://github.com/checkstyle/checkstyle/pull/15467

**Comment by Zopsss** [comment]
fix is merged. All missing sections has been added, can you close the issue pls? @romani
