### ISSUE TITLE
Create new GitHub  workflow similar to diff-report.yml but to use test-configs repository configs 

### ISSUE THREAD

**Issue by relentless-pursuit** [checkstyle/checkstyle#15231]
Rather than 'Github, generate report' we move to specific check.  And, the testc-config's README.md would be adapted likewise
Example:
`Github, generate report for SummaryJavadoc/Example1`

Existing format used to run regression reports from the comment section:
From https://github.com/checkstyle/test-configs/blob/1e98f67239a38c969893ef095b5026a4ad42a6d2/SummaryJavadoc/Example1/README.md

**Comment by romani** [comment]
merging this to https://github.com/checkstyle/checkstyle/issues/15234
