### ISSUE TITLE
Detect public constructors in non-public classes in RedundantModifier check

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#1537]
Public modifier for constructors in non-public classes is always obsolete.
```java
public class PublicClass {
    public PublicClass() {} // OK
}

class PackagePrivateClass {
    public PackagePrivateClass() {} // violation expected
}
```

**Comment by romani** [comment]
should be added to javadoc and  xdoc as example

**Comment by liscju** [comment]
This is an example in which is not obsolete:

```java
package a;
public class ClassWithProtectedInnerClass {
    protected class ProtectedClass {
        public ProtectedClass () {}
    }
}
```
```java
package b;
import a.ClassWithProtectedInnerClass;
public class ClassExtending extends ClassWithProtectedInnerClass {
    ProtectedClass pc = new ProtectedClass();
}
```

Making ProtectedClass constructor not public result in not possibility of creating object outside the package in class which extends public class ClassWithProtectedInnerClass.

**Comment by romani** [comment]
1) please update javadoc and xdoc with that code example, it is not obvious.

2) please update commit message to have "issue #xxxxx" (space between)

3) please split checkstyle code update and Check update to different commits of the same PR (each commit should ref to the same issue).

**Comment by romani** [comment]
merged

**Comment by nanodeath** [comment]
Ack, this is incorrect! If you have a **nested class** (with no modifier) inside of a **public interface**, that class is implicitly public. Thus, it's valid for the constructor of that class to be public.

**Comment by liscju** [comment]
@nanodeath you are totally right, thanks for letting us know. I created new PR to fix this situation - if you are interested you can take a look here:
https://github.com/checkstyle/checkstyle/pull/2134
