### ISSUE TITLE
regression-report.yml workflow shall run only active PRs. 

### ISSUE THREAD

**Issue by relentless-pursuit** [checkstyle/checkstyle#15412]
The workflow should  be triggered only for active PRs.

Some context at https://github.com/checkstyle/test-configs/issues/131

checkstyle/checkstyle@d575828
Restore just check_PR_status

**Comment by relentless-pursuit** [comment]
<img width="707" alt="image" src="https://github.com/user-attachments/assets/ffd8b381-d1df-4659-99a2-7d8e027e65e4">

This changes were tested in the PR and below is the runner. 
https://github.com/checkstyle-gsoc/checkstyle/actions/runs/10188013296/job/28183274474
https://github.com/checkstyle-gsoc/checkstyle/pull/7

**Comment by romani** [comment]
@relentless-pursuit 

https://github.com/checkstyle/checkstyle/actions/runs/10222480261/job/28287147106

Can we do PR status check before checkout and reacting? 
We should as minimum as possible if user do comments on closed PRs

**Comment by relentless-pursuit** [comment]
> @relentless-pursuit
> 
> Triggered at [#15413 (comment)](https://github.com/checkstyle/checkstyle/pull/15413#issuecomment-2266187181)
> 
> https://github.com/checkstyle/checkstyle/actions/runs/10222480261/job/28287147106
> 
> Can we do PR status check before checkout and reacting? We should as minimum as possible if user do comments on closed PRs

https://github.com/checkstyle/checkstyle/pull/15428

**Comment by romani** [comment]
It works, tested at https://github.com/checkstyle/checkstyle/pull/15428#issuecomment-2267149527

**Comment by romani** [comment]
@relentless-pursuit , We have different problem now 
https://github.com/checkstyle/checkstyle/pull/15237#issuecomment-2267167101 please address asap
