### ISSUE TITLE
Google style: Javadoc is optional for "simple, obvious" members

### ISSUE THREAD

**Issue by Zopsss** [checkstyle/checkstyle#15414]
I have read check documentation: https://checkstyle.org/checks/javadoc/missingjavadocmethod.html
I have downloaded the latest checkstyle from: https://checkstyle.org/cmdline.html#Download_and_Run
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

Follow up of: https://github.com/checkstyle/checkstyle/pull/14901#discussion_r1639825403

Section [7.3.1 Exception: self-explanatory members](https://google.github.io/styleguide/javaguide.html#s7.3.1-javadoc-exception-self-explanatory) of google java style guide mentions that simple members of a class like "get" methods does not necessarily need to have javadoc comments:

> Javadoc is optional for "simple, obvious" members like getFoo(), in cases where there really and truly is nothing else worthwhile to say but "Returns the foo".

We use [MissingJavadocMethod](https://checkstyle.org/checks/javadoc/missingjavadocmethod.html) & [JavadocMethod](https://checkstyle.sourceforge.io/checks/javadoc/javadocmethod.html) module for this section, and to achieve the above mentioned functionality, we use [minLineCount](https://checkstyle.org/checks/javadoc/missingjavadocmethod.html#Properties) property of MissingJavadocMethod module:

https://github.com/checkstyle/checkstyle/blob/e071377c4d6e049491aef610b04bc106e8a8b6a3/src/main/resources/google_checks.xml#L339-L345

By using this property, if a public method of public class has length of 2 lines or shorter than that, we don't need to have javadoc comments for such methods. So if such methods does not have javadoc comment, we don't give violation for that. Example:

**JavadocTesting.java**

```java
/** testing. */
public class JavadocTesting {
  public int getXyzLonger() {
    final int xyz = 10;
    System.out.println("testing longer method");
    return xyz;
  }

  public int getXyzShorter() {
    final int xyz = 10;
    return xyz;
  }
}
```

**Output:**
```
java -jar .\checkstyle-10.17.0-all.jar -c .\google_checks.xml JavadocTesting.java
Starting audit...
[WARN] .\JavadocTesting.java:3:3: Missing a Javadoc comment. [MissingJavadocMethod]
Audit done.
```

Such "get" methods most of the time have simple and easy to understand implementation, they just return what's mentioned in their name so they don't necessarily need to have javadoc comments. But as mentioned in the "important" section of this rule:

> Important: it is not appropriate to cite this exception to justify omitting relevant information that a typical reader might need to know. For example, for a method named getCanonicalName, don't omit its documentation (with the rationale that it would say only /** Returns the canonical name. */) if a typical reader may have no idea what the term "canonical name" means!

Sometimes these methods can be complicated or user might not know the meaning of method's name so he can get confused about what value the method returns. In such cases the method should have javadoc comment explaining the method's behavior.

---

**Describe what you expect in detail.**

It is impossible for us to detect if the method is complicated or it is difficult for user to understand it's working and also the `minLineCount` property we use does not always helps us out. Sometimes a method bigger than 2 lines is easy to understand so it does not require javadoc. 

As scope of this issue, add usage of [allowMissingPropertyJavadoc](https://checkstyle.sourceforge.io/checks/javadoc/missingjavadocmethod.html#Properties) property to allow missing javadoc for setters/getters methods. Such methods are mostly easy to understand only by looking at their name so javadoc isn't required for them but if user wants, he can keep javadoc for them.

**Comment by Zopsss** [comment]
@romani @rdiachenko I was thinking of creating a new property to help us to ignore methods starting with certain characters, this will be used to ignore `get` methods. Javadoc will be not be necessary for `get` methods, lemme know your opinion on this.

**Comment by romani** [comment]
@Zopsss , yes, good catch, this property was created at 8.21 version, and Google style config was created on 6.0 version. 
We just need to activate this property.

**Comment by romani** [comment]
Please update issue to describe from scratch what should be done and why, as you would notice this property from the beginning.

**Comment by rdiachenko** [comment]
> @rdiachenko can you also review the issue?

Yep, looks good to me, we need to start using `allowMissingPropertyJavadoc` in the google config. Additionally, recheck inputs and extend them if needed with cases to cover the property.

**Comment by Zopsss** [comment]
Fix is merged: https://github.com/checkstyle/checkstyle/pull/15580
