### ISSUE TITLE
Add new section 4.8.5.1 Type-use annotations to google style guide coverage page

### ISSUE THREAD

**Issue by Zopsss** [checkstyle/checkstyle#15416]
Follow up of: https://github.com/checkstyle/checkstyle/pull/14901#discussion_r1620639191 https://github.com/checkstyle/checkstyle/pull/14901#discussion_r1623306535

There was a new section introduced in the latest version of google style guide: [4.8.5.1 Type-use annotations](https://google.github.io/styleguide/javaguide.html#s4.8.5.1-type-use-annotation-style)

whole rule:
>Type-use annotations appear immediately before the annotated type. An annotation is a type-use annotation if it is meta-annotated with `@Target(ElementType.TYPE_USE)`. Example:
`final @Nullable String name;`
`public @Nullable Person getPersonByName(String name);`

The rule talks about the placement of type-use annotation, following is the definition of type-use annotation mentioned in the google java style guide documentation:

> An annotation is a type-use annotation if it is meta-annotated with `@Target(ElementType.TYPE_USE)`

Hence, we need to check if the annotation being used was created using `@Target(ElementType.TYPE_USE)`, if yes then it is a type-use annotation and we need to follow this rule.

This is impossible to check for us because of CS' [limitations](https://checkstyle.org/writingchecks.html#Limitations):

> You cannot see the contents of other files. You have access to the content of one file only during all Checks execution. All files are processed one by one.

We're able to follow other annotation rules but we cannot follow this particular rule because of our limitations.

---

**Describe what you expect in detail.**

Add this new section to google style [coverage page](https://checkstyle.org/google_style.html) with a message explaining why we can't follow this rule.

**Comment by romani** [comment]
Section must exists, wording of why we can not we will polish in PR.

**Comment by romani** [comment]
@Zopsss , next time, please use issue https://github.com/checkstyle/checkstyle/issues/15329 to do all updates for coverage table.

No need to open separate issue on each small update.

**Comment by romani** [comment]
coverage table is updated 
decision on what should final solution will be discussed at https://github.com/checkstyle/checkstyle/issues/15416

**Comment by Zopsss** [comment]
@romani issue should be closed, we've added the section with an explanation message https://github.com/checkstyle/checkstyle/pull/15419

**Comment by romani** [comment]
confirmed, we updated coverage table for 4.8.5.1 in that PR
