### ISSUE TITLE
release notes mention wrong parameter

### ISSUE THREAD

**Issue by Bananeweizen** [checkstyle/checkstyle#15420]
https://checkstyle.org/releasenotes.html#Release_10.15.0 mentions "ignoreMethodAnnotatedBy", which is actually not the name of the new option introduced in that version. This is probably because the release notes are auto-generated from github PRs, and the title reflects the old option name.

**Comment by romani** [comment]
>New:
Add ignoreMethodAnnotatedBy property to ParameterNumberCheck. Author: sktpy [#11340](https://github.com/checkstyle/checkstyle/issues/11340)

**Comment by romani** [comment]
It should be `ignoreAnnotatedBy`

I am updating issue description, it is from where generation takes  value

**Comment by nrmancuso** [comment]
@romani the commit doesn't reference this issue, is this a problem for release notes?
