### ISSUE TITLE
Google style: method names should not allow to have '_' unless they are annotated by Test

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#15429]
detected at https://github.com/checkstyle/checkstyle/pull/15411#discussion_r1700123555

this https://github.com/checkstyle/checkstyle/commit/0eadd97b8af5b79e7c49f82958fbb3d863bfdf61 is where _ is explicitly disappear and becomes covered by `\w`.

but it make all methods to be allow to have `_`

in style guide:
> 5.2.3 Method names
Method names are written in [lowerCamelCase](https://google.github.io/styleguide/javaguide.html#s5.3-camel-case).
Method names are typically verbs or verb phrases. For example, sendMessage or stop.
Underscores may appear in JUnit test method names to separate logical components of the name, with each component written in [lowerCamelCase](https://google.github.io/styleguide/javaguide.html#s5.3-camel-case), for example transferMoney_deductsFromSource. There is no One Correct Way to name test methods.

attention to `Underscores may appear in JUnit test method names to separate logical components of the name,`

Required: use https://checkstyle.org/filters/suppressionxpathsinglefilter.html
~https://checkstyle.org/filters/suppressionsinglefilter.html#SuppressionSingleFilter~ to suppress

**Comment by Zopsss** [comment]
@romani how can we detect Test methods? There's no way to check annotations in your suggested suppression?

**Comment by romani** [comment]
https://checkstyle.org/filters/suppressionsinglefilter.html#SuppressionSingleFilter is able to do what we need:
- match by xpath
- if check name is what we need 
- if message is what we need.


```
<module name="SuppressionSingleFilter">
.... Your xpath... 
<property name="checks" value="MethodNameCheck"/>
    <property name="message" value=".*_.*"/>
  </module>
```

**Comment by romani** [comment]
@Zopsss, I updated comment to be more correct

**Comment by Zopsss** [comment]
> <property name="query" value="....."/>


Can you suggest the query to be used? I tried different xpath queries but didn't found any useful ones

**Comment by romani** [comment]
this is example for method name - https://stackoverflow.com/a/75069873
you need to update it to make it for annotation of method.

here is example with annotation - https://stackoverflow.com/a/68138470

**Comment by Zopsss** [comment]
From: https://stackoverflow.com/questions/74978200/unable-to-suppress-checkstyle-test-on-method-with-suppressionxpathsinglefilter/75069873#75069873

> If you check the [XPathFilterElement](https://github.com/checkstyle/checkstyle/blob/098d9c0d764f1d1d92cdcf192e71f56e40e0b68c/src/main/java/com/puppycrawl/tools/checkstyle/filters/XpathFilterElement.java#L192) you can see the XPath expression must match the AST leaf node so the easiest way to fix the XPath query property is to add a wildcard at the end:
>
> ` <property name="query" value="//METHOD_DEF[./IDENT[@text='testOne']]//*"/>`

This is true, I was trying to follow query given in our doc I mentioned at https://github.com/checkstyle/checkstyle/issues/15429#issuecomment-2271904363:

```
//METHOD_DEF[
            .//ANNOTATION/IDENT[@text='Generated']]
```

But this wasn't working. I had to used `//*` at the end to make it work. Should we update the doc and add `//*` there also?

**Comment by romani** [comment]
>Should we update the doc and add //* there also?

Please send separate PR.
