### ISSUE TITLE
UnusedLocalVariable Should be Configurable by Tokens

### ISSUE THREAD

**Issue by mahfouz72** [checkstyle/checkstyle#15439]
We should allow the check to be configurable by tokens, This aims to provide users with more flexibility in configuring the `UnusedLocalVariable` check by allowing them to specify additional tokens, such as `RESOURCE`, or remove it from the tokens array if they don't want to validate resources.

Note: We should add support for resource in https://github.com/checkstyle/checkstyle/issues/15024

**Comment by romani** [comment]
UnusedLocalVariable implied removal not a change to `_`.

It is better to create new Check for goal that you try to archive

**Comment by mahfouz72** [comment]
There is a disagreement on extending the current check, majority voting for a new check to achieve this. So I am closing this and  moved it to a new check in https://github.com/checkstyle/checkstyle/issues/15484
