### ISSUE TITLE
Remove from google style coverage table links to already merged issues 

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#15442]
https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/b4c7950_2024151443/google_style.html latest website

should be removed:

> Between a type annotation and "[]" or "..." cannot be checked yet and actually "NoWhitespaceBefore" configuration checks the opposite for ellipsis. This will be addressed in the issue #6707. 

and all others

**Comment by Zopsss** [comment]
> and all others

which other msg do I need to remove?

**Comment by romani** [comment]
Please click yourself through all of them , there are no much.

**Comment by Zopsss** [comment]
GitHub, generate site

**Comment by romani** [comment]
Issue is fixed

**Comment by Zopsss** [comment]
GitHub, generate site

**Comment by romani** [comment]
@Zopsss , ^^^ this phrase only works in PRs
