### ISSUE TITLE
Updating regression-report.yml to allow running regression for input java file

### ISSUE THREAD

**Issue by relentless-pursuit** [checkstyle/checkstyle#15518]
https://docs.google.com/document/d/1_tuJsvtgA5ejtDajOO7ndCjrYzxZMllCPsjMkAum7Oc/edit

## Current Behavior
The existing workflow supports generating reports using predefined config bundles:
```
Github, generate report for AbstractClassName/Example1
```

## Desired Behavior
We need to extend the workflow to support the following new methods:

1. Generate report from configs in PR description:
   ```
   Github, generate report for configs in PR description
   ```

2. Generate report from a specific config file:
   ```
   Github, generate report by config from src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/methodparampad/InputMethodParamPadWhitespaceAround.java
   ```

### 1. PR Description Config Generation
- Parse the PR description to extract config information.
- Use the extracted config to generate the report.

### 2. Specific Config File Generation
- Implement file search functionality using Linux `find` command:
  ```bash
  find . -path "*InputMethodParamPadWhitespaceAround.java"
  ```
- If the config file ends with "*.java", run the extractor to generate an XML config for diff.groovy.

### General Updates
- Update the `parse_comment` job to handle new command formats.
- Create new jobs for handling PR description configs and specific file configs.
- Modify the `make_report` job to work with the new config generation methods.
- Ensure proper artifact handling for generated configs.

### Error Handling
- Implement appropriate error handling for file not found scenarios.
- Provide clear error messages in the GitHub comment if config generation fails.

## Additional Notes
- The workflow should use configs as defined in the original workflow for complicated cases when different configs are needed for master and patch.
- No need to publish generated content; it will be part of the report.
- Update the concurrency group to prevent conflicts between different report generation requests.
- User won't be forced to provide the full path of the input java file

### Specifying Input Files
- Users should provide the full path/relative path or just the name of the Input file.
- The workflow will not perform automatic input file detection or searching.
- Users are not restricted to only files from the diff; any valid input file can be specified.

Example:
```
Github, generate report by config from src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/methodparampad/InputMethodParamPadWhitespaceAround.java
```

### Changed Files Feature
One of the most desirable features is to generate configs based on changed files in a commit. For example, given a diff like this:

```
.../whitespace/MethodParamPadCheck.java       |  3 ++
.../checks/whitespace/MethodParamPadCheck.xml |  2 +-
src/main/resources/google_checks.xml          |  2 +-
.../whitespace/MethodParamPadCheckTest.java   | 17 +++++++-
.../InputMethodParamPadRecords.java           |  2 +-
.../InputMethodParamPadCheckConstructors.java | 40 +++++++++++++++++++
.../InputMethodParamPadWhitespaceAround.java  |  3 +-
.../checks/whitespace/methodparampad.xml      |  4 ++
```

The workflow will focus on these Input files:
```
.../InputMethodParamPadRecords.java
.../InputMethodParamPadCheckConstructors.java
.../InputMethodParamPadWhitespaceAround.java
```

Configs will be extracted from these files for execution. A default list of projects will be used.
```

**Comment by romani** [comment]
We will allow any Input to be used, not only what is in diff.

**Comment by relentless-pursuit** [comment]
> We will allow any Input to be used, not only what is in diff.

Romani, i forgot to remove the dif. I assume we just focus on input java fils, right? As dicussed earlier, diff isn't necessary.

**Comment by romani** [comment]
>As dicussed earlier, diff isn't necessary.

Not required, remove it.

**Comment by romani** [comment]
>Github, generate report by config from InputRedundantModifierFinalUnnamedVariables.java

Tested at https://github.com/checkstyle/checkstyle/pull/15558#issuecomment-2313968069

**Comment by romani** [comment]
>Github, generate report for configs in PR description

Tested at https://github.com/checkstyle/checkstyle/pull/14882#issuecomment-2314149355

**Comment by romani** [comment]
>Github, generate report for configs in PR description

https://github.com/checkstyle/checkstyle/pull/15102#issuecomment-2314210493

------

I triggered one more.

**Comment by romani** [comment]
>Github, generate report for RegexpHeader/all-examples-in-one

https://github.com/checkstyle/checkstyle/pull/15102#issuecomment-2315237250
