### ISSUE TITLE
bash code that find all Input file that are referenced in this Google format script have InputFormatted file

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#15544]
> can you write bash block that find all Input file that are referenced in this script and make sure we have InputFormatted file for it ?
or it is too advanced bash skills ? Try to ask chatgpt to do this.

_Originally posted by @romani in https://github.com/checkstyle/checkstyle/issues/15542#issuecomment-2304727964_

**Comment by romani** [comment]
This is reminder to do this after we do all updates

**Comment by Zopsss** [comment]
@romani can you assign this issue to me as well? I will try and see if I can solve it by myself or not

**Comment by romani** [comment]
It will be done by https://github.com/checkstyle/checkstyle/pull/15558

PR is linked to different issue.
