### ISSUE TITLE
New isOfType Method that Accepts List as its Parameter

### ISSUE THREAD

**Issue by mahfouz72** [checkstyle/checkstyle#15541]
The `isOfType` method currently accepts an array of `int` as its second parameter. We should overload this method to accept a `List<Integer>`.

https://github.com/checkstyle/checkstyle/blob/8f856ecb1f2182d0b20fd22a83be115c1577e49f/src/main/java/com/puppycrawl/tools/checkstyle/utils/TokenUtil.java#L285-L293

Reason: 
detected at https://github.com/checkstyle/checkstyle/pull/15505#discussion_r1725332873.
If we have `int[]` as a class field the `ImmutabilityTest` will fail as final arrays are technically mutable so another choice is to use Lists to satisfy the `ImmutabilityTest`.

**Comment by mahfouz72** [comment]
@romani please approve if you are good with issue

**Comment by romani** [comment]
We are never limi
