### ISSUE TITLE
Fix issues reported by IntelliJ IDEA inspections in Checkstyle code

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#1555]
IntelliJ provides a lot of useful inspections: https://www.jetbrains.com/idea/features/code_analysis.html

All reasonable errors and warnings should be fixed.

**Comment by MEZk** [comment]
@mkordas 
Can I help you to fix IDEA's code inspection issues? I use IDEA too)

**Comment by mkordas** [comment]
@MEZk - sure, any help is welcome. Could you maybe focus on Java/Abstraction issues?

Each of these rules can be fixed in separate PR:
* Cast to a concrete class
* Chain of 'instanceof' checks
* Feature envy
* 'instanceof' a concrete class
* Local variable of concrete class
* Magic number
* Method parameter of concrete class
* Method return of concrete class
* Overly strong type cast
* Private method only used from inner class
* 'public' method not exposed in interface
* 'public' method with 'boolean' parameter
* Static method only used from one other class
* Type may be weakened
* Type of instance field is concrete class

**Comment by MEZk** [comment]
@mkordas 
Ok, Abstraction issues are mine.

**Comment by romani** [comment]
all violations are resolved.

**Comment by fatmahrazzaq** [comment]
When i create a fragment  class fragment extends showing this error 

This inspection points out unresolved references inside javadoc.
please help me
