### ISSUE TITLE
google_checks failing on 'MethodName' with @ParameterizedTest

### ISSUE THREAD

**Issue by kad-switzc** [checkstyle/checkstyle#15556]
I have read check documentation: https://checkstyle.org/checks/naming/methodname.html#MethodName (version 1.18.0)
I have downloaded the latest checkstyle from: https://checkstyle.org/cmdline.html#Download_and_Run
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

- Compilation is succesful
- Config used: Default google_checks.xml (https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/google_checks.xml)
- Failing method in java file:
```java
  @ParameterizedTest
  @ValueSource(strings = {LEVENSCYCLUS_BREWERY_NIET_OPVRAAGBAAR, MULTI_RELATIE_NODES_NIET_OPVRAAGBAAR,
      LEVENSCYCLUS_AGGREGATIE_NIET_OPVRAAGBAAR})
  void beginValidation_throwsException_forNietOpvraagbareVelden(String query) {
    mockDotwebstackSchema();

    var instrumentationContext = getInstrumentationContext(query);

    List<ValidationError> validationErrors = List.of();

    assertThatThrownBy(() -> instrumentationContext.onCompleted(validationErrors, null))
        .isInstanceOf(AbortExecutionException.class)
        .hasMessageContaining("is niet opvraagbaar!");
  }
```

- Output of checks
```bash
/var/tmp $ RUN_LOCALE="-Duser.language=en -Duser.country=US" 
/var/tmp $ java $RUN_LOCALE -jar checkstyle-X.XX-all.jar -c config.xml YOUR_FILE.java

Starting audit...
[WARN] /src/test/java/nl/kadaster/dhub/bulk/instrumentation/BulkInstrumentationTest.java:217:8: Method name 'beginValidation_throwsException_forNietOpvraagbareVelden' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9]*$'. [MethodName]
Audit done.
```

---

In #15429 there was an issue discussed regarding the MethodName check for test methods. This was fixed by #15515 and released with version 1.18.0. Sinces this release my checks are failing because of the violation of the MethodName check because my test is not annotated with `@Test` but with `@ParameterizedTest`. According to the code this is expected behaviour, but I would think just like `@Test`, `@ParameterizedTest` and `@RepeatedTest` (valid junit annotation [Junit Annotations](https://junit.org/junit5/docs/current/user-guide/#writing-tests-annotations)) should also be allowed to use the pattern `[a-z][a-z0-9][_a-zA-Z0-9]*'.*"`

**Comment by romani** [comment]
We used equal https://github.com/checkstyle/checkstyle/blob/28c50973f23158bad3e8cc2cef1b36320af84952/src/main/resources/google_checks.xml#L361

Please change it to contains - 
https://www.saxonica.com/html/documentation10/functions/fn/contains.html

Let's we if this is all that we need.

**Comment by Zopsss** [comment]
@kad-switzc thank you for opening the issue and helping us to improve our style guide coverage. I have sent a PR regarding this issue: https://github.com/checkstyle/checkstyle/pull/15559

Feel free to review it :)

**Comment by romani** [comment]
@kad-switzc, do you need release to validate on your side ? Or you can adjust config on your side?

We appreciate your feedback on false positives.

**Comment by kad-switzc** [comment]
Thank you for fixing this. We can wait till there is a new release, just ignoring this release for now in applications where we have this problem.

**Comment by romani** [comment]
fix is released https://checkstyle.org/releasenotes.html#Release_10.18.1

@kad-switzc , please share feedback.

**Comment by kad-switzc** [comment]
@romani Yes, it's working again, thank you!
