### ISSUE TITLE
Failure in make_report of regression-report.yml does not make comment in PR

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#15579]
problem from https://github.com/checkstyle/checkstyle/pull/15575

action is failing but no failure comment.

Expected: there should be failure comment.

**Comment by romani** [comment]
I do believe that nuance is a faсt that I created PR not from forked repo, but from branch of the same repository

**Comment by romani** [comment]
One more example of the same problem 
https://github.com/checkstyle/checkstyle/pull/15578#issuecomment-2318212133

For Pull with branch from forked repository.

**Comment by relentless-pursuit** [comment]
wasn't this resolved?

**Comment by romani** [comment]
resolved
