### ISSUE TITLE
update TodoComment to show how to use ignore case in format property

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#15605]
Update https://checkstyle.org/checks/misc/todocomment.html

change:
`<property name="format" value="(TODO)|(FIXME)"/>`
to
`<property name="format" value="(?i)(TODO)|(FIXME)"/>`

Note: The (?i) at the beginning of the regular expression tells the regexp engine to ignore the case. 
this shown that it works at https://checkstyle.sourceforge.io/checks/regexp/regexp.html#Example8-config

goal of this update is to test auto config generation at https://github.com/checkstyle/test-configs/issues/143

**Comment by relentless-pursuit** [comment]
I ran the checkstyle ./setup.sh locally and ran the test cases. I don't observe any diff. Neither did the cron job in my own repo.

**Comment by romani** [comment]
>To configure the check for comments that contain TODO and FIXME: 

https://checkstyle.org/checks/misc/todocomment.html#Example2-config

Let's change to `To configure the check for comments that contain TODO and FIXME case insensitive:`

**Comment by romani** [comment]
Reopening as reminder to do https://github.com/checkstyle/checkstyle/issues/15605#issuecomment-2325383183

**Comment by nrmancuso** [comment]
Closed via #15618
