### ISSUE TITLE
Remove cache cleanup in regression-report.yml

### ISSUE THREAD

**Issue by relentless-pursuit** [checkstyle/checkstyle#15614]
We need to create a step which cleans up the cache keys in regression-report.yml. 

https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/caching-dependencies-to-speed-up-workflows#managing-caches

>Once a repository has reached its maximum cache storage, the cache eviction policy will create space by deleting the oldest caches in the repository.

If cleanup becomes unstable or problematic, we can skip doing it, and GitHub will clean up old stuff itself.

All caches: https://github.com/checkstyle/checkstyle/actions/caches

**Comment by romani** [comment]
Does not work https://github.com/checkstyle/checkstyle/pull/15558#issuecomment-2327553408

**Comment by romani** [comment]
https://github.com/checkstyle/checkstyle/actions/runs/10692871657/job/29644044299#step:6:125

We do duplicate removal request, please fix.
```
Removing cache with key: config-files-ee0ec9081cd326083f7bc698b9a3cdbe24cc8c6e-2327684770
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
{
100   423  100   423    0     0   1524      0 --:--:-- --:--:-- --:--:--  1527
  "total_count": 1,
  "actions_caches": [
    {
      "id": 14504,
      "ref": "refs/heads/master",
      "key": "config-files-ee0ec9081cd326083f7bc698b9a3cdbe24cc8c6e-2327684770",
      "version": "b83bfdb416c2392cf42ae8d3171e06f7ae39c6622f8dc7a00deb2dd7af332214",
      "last_accessed_at": "2024-09-04T01:04:28.653333300Z",
      "created_at": "2024-09-04T01:04:28.653333300Z",
      "size_in_bytes": 4704
    }
  ]
}
Removing cache with key: generated-configs-ee0ec9081cd326083f7bc698b9a3cdbe24cc8c6e-2327684770
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   181  100   181    0     0    659      0 --:--:-- --:--:-- --:--:--   658
100   181  100   181    0     0    658      0 --:--:-- --:--:-- --:--:--   658
curl: (22) The requested URL returned error: 404
{
  "message": "Not Found",
  "documentation_url": "https://docs.github.com/rest/actions/cache#delete-github-actions-caches-for-a-repository-using-a-cache-key",
  "status": "404"
}
```

**Comment by romani** [comment]
https://github.com/actions/cache#cache-limits

>A repository can have up to 10GB of caches. Once the 10GB limit is reached, older caches will be evicted based on when the cache was last accessed. Caches that are not accessed within the last week will also be evicted.

if we end up to have 1 cache from execution, that we plan to do, we will not need cleanup, as Github will auto cleanup all.
