### ISSUE TITLE
regression-report.yml should use label for report comment that took config from Input

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#15619]
One more engagement:
Put name of Input file of label to result successful message 
```
InputFinalParameters6.java:
(Link to report)
```

~Detected at https://github.com/checkstyle/checkstyle/pull/15578#issuecomment-2329379792
GitHub copy path web UI feature copy path like `src/test/resources/com/puppycrawl/tools/checkstyle/checks/finalparameters/InputFinalParameters6.java`
We do search command~ https://github.com/checkstyle/checkstyle/blob/7a1a47fc9796a91a91d2b91401975a70b8ef6377/.github/workflows/regression-report.yml#L229
~We should remove `/src` from workflow and add allow to search at any place in repository~

**Comment by romani** [comment]
One more engagement:
Put name of Input file of label to result successful message 
```
InputFinalParameters6.java:
(Link to report)
```

**Comment by romani** [comment]
I am recalling removal of `src` from find command

it works better with search in folder `/src` and usage of `*` for path section that user provides.
``` 
$ find src -path *src/test/resources/com/puppycrawl/tools/checkstyle/checks/finalparameters/InputFinalParameters5.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/finalparameters/InputFinalParameters5.java
✔ ~/java/github/romani/checkstyle [master|⚑ 2] 

$ find src -path */src/test/resources/com/puppycrawl/tools/checkstyle/checks/finalparameters/InputFinalParameters5.java
✔ ~/java/github/romani/checkstyle [master|⚑ 2] 

$ find src -path */test/resources/com/puppycrawl/tools/checkstyle/checks/finalparameters/InputFinalParameters5.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/finalparameters/InputFinalParameters5.java
✔ ~/java/github/romani/checkstyle [master|⚑ 2] 

$ find . -path *src/test/resources/com/puppycrawl/tools/checkstyle/checks/finalparameters/InputFinalParameters5.java
✔ ~/java/github/romani/checkstyle [master|⚑ 2] 

$ find . -path */src/test/resources/com/puppycrawl/tools/checkstyle/checks/finalparameters/InputFinalParameters5.java
./src/test/resources/com/puppycrawl/tools/checkstyle/checks/finalparameters/InputFinalParameters5.java
✔ ~/java/github/romani/checkstyle [master|⚑ 2] 

$ find . -path *//test/resources/com/puppycrawl/tools/checkstyle/checks/finalparameters/InputFinalParameters5.java
✔ ~/java/github/romani/checkstyle [master|⚑ 2] 

$ find . -path */test/resources/com/puppycrawl/tools/checkstyle/checks/finalparameters/InputFinalParameters5.java
✔ 
```

**Comment by relentless-pursuit** [comment]
`github.head_ref `is only available for pull request events. The workflow is triggered by an issue comment event, not a pull request event directly.

When the workflow is triggered by an issue comment, `github.head_ref` is not set, which is why the checkout action fails to find the correct branch.

Even in our workflow,  we are making an API call to get the PR information in set branch, including the branch name. This worked because it explicitly fetched the PR data, regardless of the event type.

**Comment by romani** [comment]
your comment is moved to new issue https://github.com/checkstyle/checkstyle/issues/15628
