### ISSUE TITLE
google_checks: Section 4.1.3 should not be covered by EmptyBlock and EmptyCatchBlock

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#15642]
split from https://github.com/checkstyle/checkstyle/issues/15338#issuecomment-2308853492

> [4.1.3 Empty blocks: may be concise](https://google.github.io/styleguide/javaguide.html#s4.1.3-braces-empty-blocks)
> 
> An empty block or block-like construct may be in K & R style (as described in [Section 4.1.2](https://google.github.io/styleguide/javaguide.html#s4.1.2-blocks-k-r-style)). Alternatively, it may be closed immediately after it is opened, with no characters or line break in between ({}), unless it is part of a multi-block statement (one that directly contains multiple blocks: if/else or try/catch/finally).

After thinking more on this I'm not sure we use correct checks to cover this section.

Google formatter formats the above block to be in K & R style which is fine.

On the Checkstyle side we use `EmptyBlock` and `EmptyCatchBlock` to cover 4.1.3 section. I think this doesn't make sense, as those checks complain for empty blocks presense, while the section says that it is ok to have empty blocks.

**What we need to do is the following:**
do not give violations for empty blocks, don't use `EmptyBlock` and `EmptyCatchBlock`  as they produce violations that  demand code in blocks, but Section 4.1.3 does not demands code, it demands locations of braces as `{}` or in K&R style (on different lines) 

Update Google section to have red sign and link to https://github.com/checkstyle/checkstyle/issues/15338 as some solution will be provided by this issue.
We can keep Inputs for now, just to show sample code and how google_checks behaves on it.

**Comment by Zopsss** [comment]
I have updated the documentation and removed `EmptyBlock` usage from google_checks.xml at https://github.com/checkstyle/checkstyle/pull/15655/. Will send a PR for correcting the implementation of the section once 15655 is merged.

**Comment by Zopsss** [comment]
we can remove `EmptyBlock` but `EmptyCatchBlock` cannot be removed as it is used by section [6.2](https://checkstyle.org/google_style.html#a6.2). I have sent a PR regarding updating coverage page and removing `EmptyBlock` usage. This issue should be closed after that PR is merged, we will correct the implementation of section as part of https://github.com/checkstyle/checkstyle/issues/15338 and its children issues

**Comment by romani** [comment]
we need to remove them from section 4.1.3

if EmptyCatchBlock is used in other section, it definetely should stay in config.
if EmptyBlock is the only usage in 4.1.3  - it should be removed from config.

**Comment by romani** [comment]
Fix is merged
