### ISSUE TITLE
JavadocParagraph: Add examples for all messages

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#15689]
https://checkstyle.org/checks/javadoc/javadocparagraph.html#JavadocParagraph

we show examples only for 2 violation messages.
but Check has https://checkstyle.org/checks/javadoc/javadocparagraph.html#Violation_Messages
4 special for this Check violation messages.

We need to extend ExampleX classes to show all violation messages.

**Comment by AmitKumarDeoghoria** [comment]
Hello @romani ,

I have started working on this issue, and from my understanding, the tasks required include:

> Writing example classes for the remaining violations, such as redundant paragraph violations.
> Writing unit test cases in JavadocParagraphCheckExamplesTest to verify these changes.
> Making necessary changes in the configuration file.
> Updating the JavadocParagraph XML file with the configuration and description of the examples.

So far, I have completed the example classes for the remaining violations and am now progressing with the other tasks. Could you please let me know if there’s anything additional that needs to be addressed? Additionally, any resources that could provide further guidance would be greatly appreciated.

Thank you in advance for your assistance.

**Comment by romani** [comment]
Please create PR to let us see what you have and we can spot easier what is missing

**Comment by romani** [comment]
fixed at https://github.com/checkstyle/checkstyle/pull/15835
