### ISSUE TITLE
google_checks.xml: JavadocParagraph should have allowNewlineParagraph as false 

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#15716]
detected at https://github.com/checkstyle/checkstyle/pull/15711/files#diff-9adc1bbf4c7e7ab4a9e6f22cca53bbf43b53c1c6e5f4da393b6a7aa27b2d1f4fL3

Fix for Issue #15690 reveled that config is correct, and `allowNewlineParagraph` should be `false` 
This property was created to allow checkstyle style on javadoc, but google requires `p` tag to be immediately before content/text.

Expected behavior:
```
$ cat Test.java 
/**
 * Some Summary.
 *
 * <p>
 * Some test.
 */
public class Test {
}

$ java -jar checkstyle-10.18.1-all.jar -c /google_checks.xml  Test.java 
Starting audit...
[WARN] /var/tmp/Test.java:4: <p> tag should be placed immediately before the first word
    , with no space after. [JavadocParagraph]
Audit done.
```

**Comment by Zopsss** [comment]
@romani PR raised: https://github.com/checkstyle/checkstyle/pull/15726
