### ISSUE TITLE
move all dtd schemas to sourceforge site

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#1571]
http://www.puppycrawl.com/dtds/configuration_1_3.dtd and others dtds from configs need to be hosted at sourceforge site
all configs need to be updated

As a separate commit:
Additionally investigate ability to reuse dtd from local to avoid numerous build failures due to internet connection problems:

> The plugin doesn't work in offline mode. It always tries to resolve external resources and fails, if the network is not available ?
>     You've got to download the resources in question once and store them as part of the project. A catalog file will replace the external resource with your local copy. See this example for details.

http://www.mojohaus.org/xml-maven-plugin/examples/catalog.html 

Location of DTD - https://github.com/checkstyle/checkstyle/tree/master/src/main/resources/com/puppycrawl/tools/checkstyle

DTDs to move to "http://checkstyle.sourceforge.net/dtds/........":
Current:

```
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
```

Should be:

```
<!DOCTYPE module PUBLIC
          "-//Checkstyle//DTD Configuration 1.3//EN"
          "http://checkstyle.sourceforge.net/dtds/configuration_1_3.dtd">
```

Current:

```
<!DOCTYPE suppressions PUBLIC
    "-//Puppy Crawl//DTD Suppressions 1.1//EN"
    "http://www.puppycrawl.com/dtds/suppressions_1_1.dtd">
```

Should be:

```
<!DOCTYPE suppressions PUBLIC
    "-//Checkstyle//DTD Suppressions 1.1//EN"
    "http://checkstyle.sourceforge.net/dtds/suppressions_1_1.dtd">
```

Current:

```
<!DOCTYPE import-control PUBLIC
    "-//Puppy Crawl//DTD Import Control 1.1//EN"
    "http://www.puppycrawl.com/dtds/import_control_1_1.dtd">
```

Should be:

```
<!DOCTYPE import-control PUBLIC
    "-//Checkstyle//DTD Import Control 1.1//EN"
    "http://checkstyle.sourceforge.net/dtds/import_control_1_1.dtd">
```

Current:

```
<!DOCTYPE checkstyle-packages PUBLIC
    "-//Puppy Crawl//DTD Package Names 1.0//EN"
    "http://www.puppycrawl.com/dtds/packages_1_0.dtd">
```

Should be:

```
<!DOCTYPE checkstyle-packages PUBLIC
    "-//Checkstyle//DTD Package Names 1.0//EN"
    "http://checkstyle.sourceforge.net/dtds/packages_1_0.dtd">
```

Attention: all version of config should be uploaded to sourceforge site. There should be no reference to "puppycrawl" at any of your sources/configs/xdoc/.... .
##

**Comment by rnveach** [comment]
@romani
The import schema was done here: https://github.com/checkstyle/checkstyle/issues/2999#issuecomment-247004396 
Is there any chance to get the others moved to free up the linked issues?
Is the physical move something only you can do?

**Comment by romani** [comment]
all schemes are stored in git, all we need is to change them as described , bump their versions (for all except for schema that is changed at #2999) and update our site build process to host them at new place.
Any contributor can do this.

**Comment by MEZk** [comment]
@romani 
I'm on it

**Comment by rnveach** [comment]
Fix is merged.

**Comment by tsjensen** [comment]
Will the current DTDs continue to be available on puppycrawl?
(New versions don't need to be, I'm just talking about existing versions.)

**Comment by romani** [comment]
> Will the current DTDs continue to be available on puppycrawl?

yes, we will not touch them, but eventually (in far future) they could be removed or lost.
