### ISSUE TITLE
IntelliJ Plugin issue parsing CustomImportOrderImporter.ImportGroup

### ISSUE THREAD

**Issue by RicardoMonteiroSimoes** [checkstyle/checkstyle#15780]
I have read check documentation: https://checkstyle.org/checks/xxxxxx/nameofaffectedcheck.html ✅
I have downloaded the latest checkstyle from: https://checkstyle.org/cmdline.html#Download_and_Run ✅
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

---

I am currently working on setting up the imports for intelliJ, and when doing `Editor > Code Style > Java > Import from checkstyle`, the following error appears:

```
Checkstyle configuration import failed with error message: org. infernus. idea. checkstyle. exception. CheckstyleServiceException: Error executing command 'OpPeruseConfiguration': No enum constant org. infernus. idea. checkstyle. importer. modules. CustomImportOrderImporter. ImportGroup. STATIC, STANDARD_JAVA_PACKAGE, SPECIAL_IMPORTS, THIRD_PARTY_PACKAGE
```

Apparently it's missing the enum for `CustomImportOrderImporter. ImportGroup`. The installed plugin version is **0.43.1**, the used checkstyle version is **10.18.1**, and the `checkstyle.xml` file contains the following definition for `CustomImportOrder`

```xml
    <module name="CustomImportOrder">
      <property name="customImportOrderRules"
                value="STATIC, STANDARD_JAVA_PACKAGE, SPECIAL_IMPORTS, THIRD_PARTY_PACKAGE"/>
      <property name="specialImportsRegExp" value="^org\."/>
      <property name="thirdPartyPackageRegExp" value="^com\."/>
      <property name="sortImportsInGroupAlphabetically" value="true"/>
      <property name="separateLineBetweenGroups" value="true"/>
    </module>
```

From what I gather is that intelliJ can't correctly parse the content to adapt the automatic import organization, whilst the check still runs correctly. I somewhat assume that this is an intelliJ issue, but can't be sure.

**Comment by romani** [comment]
I think this issue should be reported to intelijidea plugin 

Might be related https://github.com/jshiell/checkstyle-idea/pull/210
