### ISSUE TITLE
Introducing contributing.md file.

### ISSUE THREAD

**Issue by aboro-code** [checkstyle/checkstyle#16068]
As a new contributor to the Checkstyle project, I found it challenging to navigate through various resources in order to set up the development environment and contribute effectively. The lack of a centralized CONTRIBUTING.md file makes the onboarding process for new contributors more time-consuming and frustrating.

Currently, new contributors need to check multiple locations, such as the README and various wiki pages, to gather all the necessary information on how to set up their local environment, run tests, and follow project-specific guidelines. This scattered approach can create confusion and slows down the process of getting started.

A well-organized CONTRIBUTING.md file would address this issue by consolidating all essential information into one location, making it easier for newcomers to find step-by-step instructions and guidelines for contributing. This could include:

Prerequisite tools and software (e.g., Java versions, IDE setup, etc.)
Steps for setting up the development environment
Instructions for running tests and building the project
Guidelines for submitting pull requests (e.g., code style, commit message format)
Any additional information that would streamline the process for first-time contributors
Having this resource would improve the contribution process, reduce confusion, and encourage more developers to participate in the project. I recommend adding a CONTRIBUTING.md file to the repository to provide a clearer, more efficient guide for new contributors.

**Comment by aboro-code** [comment]
@romani

**Comment by romani** [comment]
We have it here: 
https://github.com/checkstyle/checkstyle/blob/master/.github/CONTRIBUTING.md

What is a benefit of new content or may be location is not good ?

**Comment by romani** [comment]
https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors

>If a repository contains more than one CONTRIBUTING file, then the file shown in links is chosen from locations in the following order:
the .github directory, 
then the repository's root directory, 
and finally the docs directory.

so I think we placed it in good location
