### ISSUE TITLE
UnusedImports: make 'processJavadoc' property value 'true' by default

### ISSUE THREAD

**Issue by rdiachenko** [checkstyle/checkstyle#1627]
@rdiachenko:
>>
@romani there is an option in UnusedImports processJavadoc with false default value. I changed it to true so violations disappeared.

@mkordas:
>>
@rdiachenko @romani - shouldn't we make it default option then? Is there any serious impact on performance with this option enabled?

@rdiachenko:
>>
@mkordas there is a reason why we made the default value as false (http://checkstyle.sourceforge.net/config_imports.html#UnusedImports):
>>
Optionally: it is referenced in Javadoc comments. This check is off by default, as it is considered bad practice to introduce a compile time dependency for documentation purposes only. As an example, the import java.util.Date would be considered referenced with the Javadoc comment {@link Date}. The alternative to avoid introducing a compile time dependency would be to write the Javadoc comment as {@link java.util.Date}.

@romani:
>>
When I first run into a problem that reference in javadoc (special format of multi-line comment) require "import" I was surprised.
>>
I agree that javadoc should live its own live and do not affect class implementation. Extra import is extra dependecies - should be avoided.
>>
But for our code - we need to make processJavadoc as TRUE, as we need to use options that Checks have (just another ITs for a Check+option).
>>
@rdiachenko , please create issue to make options as TRUE - https://github.com/checkstyle/checkstyle/blob/master/config/checkstyle_checks.xml#L192

**Comment by mkordas** [comment]
@romani
I think it is already done: https://github.com/checkstyle/checkstyle/blob/master/config/checkstyle_checks.xml#L200
Can you confirm?

**Comment by romani** [comment]
It is not done yet.

https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/UnusedImportsCheck.java#L77

https://docs.oracle.com/javase/tutorial/java/nutsandbolts/datatypes.html , default value for boolean is FALSE.

**Comment by romani** [comment]
merged.
