### ISSUE TITLE
Documentation: JavadocMethod Examples typo

### ISSUE THREAD

**Issue by Schattensilber** [checkstyle/checkstyle#1668]
In the documentation http://checkstyle.sourceforge.net/config_javadoc.html, in the section for JavadocMethod: Examples, the last example reads:

" To configure the check for ignoring methods named foo(),foo1(),foo2(), etc.:
< module name="JavadocMethodRegex">
 < property name="ignoreMethodNamesRegex" value="^foo.*$"/>
< /module>"

The module name should be "JavadocMethod" instead of "JavadocMethodRegex".

I'm new with checkstyle, that had me confused for a bit.

greetz
Schattensilber

**Comment by MEZk** [comment]
@romani 
You can close the issue.

**Comment by romani** [comment]
Released as 6.10
