### ISSUE TITLE
JavadocVariableCheck configuration option to skip enum values

### ISSUE THREAD

**Issue by jpraet** [checkstyle/checkstyle#1669]
When you activate the JavadocVariableCheck it also requires you to add a javadoc comment to each enum value. It would be nice if there was a configuration option to disable this check for enums.

**Comment by MEZk** [comment]
@jpraet 
You can specify tokens which are checked by the JavadocVariableCheck. 

For example:
````xml
<module name="JavadocVariable">
    <property name="tokens" value="VARIABLE_DEF"/>
</module>
````

Default tokens: VARIABLE_DEF, ENUM_CONSTANT_DEF.
Acceptable tokens: VARIABLE_DEF, ENUM_CONSTANT_DEF.

@romani 
We should update documentation.

**Comment by romani** [comment]
Can you suggest smth common for all Checks ?

**Comment by romani** [comment]
further discussion will be at https://github.com/checkstyle/checkstyle/issues/2169
