### ISSUE TITLE
Enable Checkstyle checks for 'gui' package

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#1676]
Follow-up to #1661.

All Checkstyle check should be enforced also on GUI package.

Exclusion `**/gui/*` needs to be removed from https://github.com/checkstyle/checkstyle/blob/master/config/ant-phase-verify.xml#L31

**Comment by rdiachenko** [comment]
So, there are two places where we can skip Checkstyle verification for certain packages/classes:
- ant-phase-verify.xml
- suppressions.xml

Why do we have such inconsistency? It is not obvious to have suppressions in two places.

**Comment by romani** [comment]
it is history, suppression was not implemented at the beginning. I voting for removal of "exclude" from ant config.

**Comment by romani** [comment]
fixed by https://github.com/checkstyle/checkstyle/commit/3cef81032c4d94b80c7d0780a934f94a988b7290
