### ISSUE TITLE
Checkstyle GUI throws UnsupportedOperationException

### ISSUE THREAD

**Issue by liscju** [checkstyle/checkstyle#1718]
Cause is change : https://github.com/checkstyle/checkstyle/commit/13900919907b38384a0405d349cfc659b2b3d985#diff-f3e21c87ead74b564a9c54eb616d3d6dR217

getLines2position after this change returns unmodifiable copy of lines2positions but its usages use it as modifiable original list:
https://github.com/checkstyle/checkstyle/blob/13900919907b38384a0405d349cfc659b2b3d985/src/main/java/com/puppycrawl/tools/checkstyle/gui/ParseTreeInfoPanel.java#L115

https://github.com/checkstyle/checkstyle/blob/13900919907b38384a0405d349cfc659b2b3d985/src/main/java/com/puppycrawl/tools/checkstyle/gui/ParseTreeInfoPanel.java#L117 

Fix can be as easy as https://github.com/liscju/checkstyle/commit/ad9c3340f458c38aa833e88e83d506bfeb0cc76b or operation clear,add can be extracted in method

**Comment by romani** [comment]
that change was done during update for Idea static analysis validation.

@mkordas , please reconcile Idea and GUI

**Comment by romani** [comment]
merged , @liscju , please confirm.

**Comment by liscju** [comment]
@romani checked , now works fine
