### ISSUE TITLE
Java 8 supported checks?

### ISSUE THREAD

**Issue by mmoayyed** [checkstyle/checkstyle#1804]
I am looking around for Checkstyle checks that strictly enforce Java-8 syntax. Are there any that be configured to force the use of streams or lambdas?

**Comment by romani** [comment]
please provide example of what you want.

**Comment by mmoayyed** [comment]
For example, I want all loops be used using the collect() API and I want checkstyle to warn me to strictly use the new syntax.  There are many other similar examples available.

**Comment by romani** [comment]
unfortunately, there is no such Checks, it might be possible to implement but all discussion about this should be done in our main-list - https://groups.google.com/forum/#!forum/checkstyle-devel .

**Comment by tsjensen** [comment]
Just in case someone stubles on this thread, there is a post on this topic in @oburn's blog:
[http://www.puppycrawl.com/blog/2015/09/03/checkstyle-force-lambdas.html](http://www.puppycrawl.com/blog/2015/09/03/checkstyle-force-lambdas.html).
