### ISSUE TITLE
Incorrect handling of Javadoc for generic type <P>

### ISSUE THREAD

**Issue by Eijsinkdavid** [checkstyle/checkstyle#1878]
I have a generic type P in my class, like this:

    /**
     * @param <P> The type of p
     */
    public class Thing<P> {
    }

Checkstyle gives me a warning that I have to document my generic type (I think it's parsing &lt;P> as an HTML paragraph)

**Comment by romani** [comment]
prove: https://docs.oracle.com/javase/8/docs/technotes/tools/windows/javadoc.html#CHDHJECF

**Comment by baratali** [comment]
``<P>`` is parsed as parameter, not as a paragraph.
```
|--NEWLINE[1x0] : [\n]
|--LEADING_ASTERISK[2x0] : [ *]
|--WS[2x2] : [ ]
|--JAVADOC_TAG[2x3] : [@param <P> The type of p\n ]
    |--PARAM_LITERAL[2x3] : [@param]
    |--WS[2x9] : [ ]
    |--PARAMETER_NAME[2x10] : [<P>]
    |--WS[2x13] : [ ]
    |--DESCRIPTION[2x14] : [The type of p\n ]
        |--TEXT[2x14] : [The type of p]
        |--NEWLINE[2x27] : [\n]
        |--TEXT[3x0] : [ ]
|--EOF[3x1] : [<EOF>]
```

**Comment by romani** [comment]
@Eijsinkdavid , please provide Check config to let us clearly understand where is problem. 
please  reproduce problem by CLI - http://checkstyle.sourceforge.net/cmdline.html#Download_and_Run

**Comment by Eijsinkdavid** [comment]
Ok I found out the problem and I feel a bit silly now. The Eclipse auto formatter parsed the <P> as a parameter and added some whitespace (newlines and tabs) in the Javadoc comments. I didn't think this whitespace would matter to checkstyle, but it does (which is reasonable). Apparently, my beef is with the Eclipse Javadoc auto-format functionality, not with Checkstyle.

**Comment by romani** [comment]
> Checkstyle gives me a warning that I have to document my generic type

please confirm one more time that warning that you mentioned is not from Cehckstyle , if so , please close issue.
