### ISSUE TITLE
New option in CyclomaticComplexityCheck: Treat SWITCH as single desicion point.

### ISSUE THREAD

**Issue by baratali** [checkstyle/checkstyle#2029]
The Check should have an option to treat whole SWITCH as one desicion point and skip its CASE blocks.
PMD already has rule with similar behaviour: [ModifiedCyclomaticComplexity](https://pmd.github.io/pmd-5.3.3/pmd-java/rules/java/codesize.html#ModifiedCyclomaticComplexity)

**Comment by romani** [comment]
discussion at #2069
