### ISSUE TITLE
Option 'ignoreMethods' is useless in DeclarationOrderCheck

### ISSUE THREAD

**Issue by baratali** [checkstyle/checkstyle#2031]
The Check has hardcoded order of class members:
1. Static fields
2. Instance fields
3. Constructors
4 .Methods

The Check warns on class member (i.e. constructor) if something with **bigger index** has been met earlier (i.e. method).

Purpose of ignore* option is to ignore related violation, however it still impacts on other class members.

[Example how ignores work](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/DeclarationOrderCheck.java#L64)

Method has the biggest index, therefore it's impossible to have "something with bigger index above". As we can't get any violations for method definition, it is useless to have **ignoreMethods** option.

**Comment by romani** [comment]
merged
