### ISSUE TITLE
broken compatibility with maven-checkstyle-plugin:2.15 at checkstyle:6.10

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#2065]
caught by https://travis-ci.org/checkstyle/checkstyle/jobs/78162902
reason : https://github.com/checkstyle/checkstyle/compare/aa7b68597a6f...2d8f5576bb30 update of PropertiesExpander

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.15:check (default-cli) on project orekit: Execution default-cli of goal org.apache.maven.plugins:maven-checkstyle-plugin:2.15:check failed: An API incompatibility was encountered while executing org.apache.maven.plugins:maven-checkstyle-plugin:2.15:check: java.lang.NoSuchMethodError: com.puppycrawl.tools.checkstyle.PropertiesExpander.<init>(Ljava/util/Properties;)V
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.apache.maven.plugins:maven-checkstyle-plugin:2.15
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/home/travis/.m2/repository/org/apache/maven/plugins/maven-checkstyle-plugin/2.15/maven-checkstyle-plugin-2.15.jar
[ERROR] urls[1] = file:/home/travis/.m2/repository/com/puppycrawl/tools/checkstyle/6.10-SNAPSHOT/checkstyle-6.10-SNAPSHOT.jar
................
[ERROR] urls[55] = file:/home/travis/.m2/repository/commons-collections/commons-collections/3.2.1/commons-collections-3.2.1.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[project>org.orekit:orekit:7.1-SNAPSHOT, parent: ClassRealm[maven.api, parent: null]]]
[ERROR] 
[ERROR] -----------------------------------------------------
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException
```
##

**Comment by romani** [comment]
@mkordas , fyi.

**Comment by romani** [comment]
issue id resolved in release 6.10.1, but I will keep issue open to implement smth to prevent such failures in future

**Comment by mkordas** [comment]
@romani, do you know why PR with my change was green? I thought we perform
integration test with Orekit, checkstyle-maven-plugin and freshly built jar.

**Comment by romani** [comment]
your PR build is failed too https://travis-ci.org/checkstyle/checkstyle/builds/78132826

It was my bad to merged it , as I thought that this just another internet connection problem, error was very unclear and strange.

right now Orekit is our braking compatibility build for Maven plugin.

Summary: trust Travis :) , and make it green before merge.

**Comment by mkordas** [comment]
Stacktrace:
```
Caused by: java.lang.NoSuchMethodError: com.puppycrawl.tools.checkstyle.PropertiesExpander.<init>(Ljava/util/Properties;)V
                at org.apache.maven.plugin.checkstyle.exec.DefaultCheckstyleExecutor.getConfiguration(DefaultCheckstyleExecutor.java:381)
                at org.apache.maven.plugin.checkstyle.exec.DefaultCheckstyleExecutor.executeCheckstyle(DefaultCheckstyleExecutor.java:218)
                at org.apache.maven.plugin.checkstyle.CheckstyleViolationCheckMojo.execute(CheckstyleViolationCheckMojo.java:530)
                at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
                ... 26 more
```
Lines that caused failure ([DefaultCheckstyleExecutor.java:379](http://svn.apache.org/viewvc/maven/plugins/tags/maven-checkstyle-plugin-2.16/src/main/java/org/apache/maven/plugin/checkstyle/exec/DefaultCheckstyleExecutor.java?view=markup))
```java
	            Properties overridingProperties = getOverridingProperties( request );
	            Configuration config = ConfigurationLoader
	                .loadConfiguration( configFile, new PropertiesExpander( overridingProperties ) );
```
It's just invocation of method that takes `Map<Object, Object>` with `Properties` argument. In Checkstyle code `PropertiesExpander` are constructed with `Properties` argument and it worked fine.

The issue is probably connected with type erasure system. Plugin wouldn't require any changes, just recompilation with latest Checkstyle to recalculate types again.

Looks like issue is not easily reproducible in unit test, so couple of lessons learned:
- always look at the end of line starting with `[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.15:check` - there might be valuable info a few hundreds characters to the right
- never release when build is not green

**Comment by romani** [comment]
IT for maven plugin compatibility should be created (and lets do that for gradle plugin too), to at least be aware of compatibility problems that we might cause.

**Comment by mkordas** [comment]
> IT for maven plugin compatibility should be created 

@romani, I believe we already have such tests - what else you'd like?

> and lets do that for gradle plugin too

Agreed

**Comment by romani** [comment]
Issue could be closed as it is resolved. and we use in CIs a lot of projects with real maven , gradle plugins, so future compatibility problems will be caught by our CIs.
