### ISSUE TITLE
IllegalAccessError in Apache Commons library

### ISSUE THREAD

**Issue by jonjesbuzz** [checkstyle/checkstyle#2066]
I can't use CheckStyle at all (ver 6.9 nor 6.10); upon attempting to run it, I get an `IllegalAccessError`.

```
Exception in thread "main" java.lang.IllegalAccessError: tried to access method org.apache.commons.cli.Options.getOptionGroups()Ljava/util/Collection; from class org.apache.commons.cli.DefaultParser
    at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:109)
    at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:76)
    at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:60)
    at com.puppycrawl.tools.checkstyle.Main.parseCli(Main.java:140)
    at com.puppycrawl.tools.checkstyle.Main.main(Main.java:74)
```

**Comment by romani** [comment]
please provide command line or more details on how your run chekcstyle

**Comment by jonjesbuzz** [comment]
@romani I used `java -jar checkstyle-6.10.jar -c CS1332-checkstyle.xml MyClass.java`.  It fails to run even without my custom rules file though.

**Comment by romani** [comment]
please provide config and input file to be exact

**Comment by romani** [comment]
my output on my files but with the same names as yours:
```
/var/tmp $ java -jar checkstyle-6.10-all.jar -c CS1332-checkstyle.xml MyClass.java
Starting audit...
/var/tmp/MyClass.java:3:45: '}' at column 45 should be on the same line.
/var/tmp/MyClass.java:11:5: '}' at column 5 should be on the same line.
/var/tmp/MyClass.java:19:5: '}' at column 5 should be on the same line.
/var/tmp/MyClass.java:20:1: '}' at column 1 should be on the same line.
Audit done.
Checkstyle ends with 4 errors.
```

**Comment by jonjesbuzz** [comment]
This is happening on two machines that I've seen - one running OS X Yosemite and another running OS X Mavericks (10.9.5).  It works fine on my personal machine running Yosemite (10.10.5).

Here's my check XML.
https://cloudup.com/cyz2tYjV4ei

**Comment by mkordas** [comment]
@jonjesbuzz - I see that you are using `checkstyle-6.10.jar` instead of `checkstyle-6.10-all.jar` meaning that you somehow provide `org.apache.commons.cli` in classpath. But you provide it in version different than required by Checkstyle thus the error you observe.

**Comment by jonjesbuzz** [comment]
@mkordas Good catch, but I had changed the filename (sorry for the confusion).

**Comment by mkordas** [comment]
Just to confirm - do you receive the same error with and without `-all`? If yes, it means that you have some default classpath set that overrides classpath from JAR. Without `-all` you should have `NoClassDefFoundError`.

**Comment by jonjesbuzz** [comment]
I never tried it without the `-all` JAR.  `CLASSPATH` isn't set as an environment variable either.

**Comment by mkordas** [comment]
OK, so can you try without `-all` and confirm that you get something like `java.lang.NoClassDefFoundError: org/apache/commons/cli/CommandLineParser`?

**Comment by romani** [comment]
"-all" jar do have all dependencies inside of it. You can not  use checkstyle-6.10.jar without all dependecies. Most likely all dependecies jars are in your system classpath that is why it works on some of your PC.

Here is some examples http://checkstyle.sourceforge.net/cmdline.html#Usage_by_Classpath_update
