### ISSUE TITLE
Fix additional issues reported by IntelliJ IDEA inspections in Checkstyle code

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#2080]
Follow-up to #1555 .

Below is the list of all inspections, that still remain disabled in `config/intellij-idea-inspections.xml`. Some of them are not applicable to Checkstyle code, but others are very reasonable and just require additional work to fix.

```
AbstractClassExtendsConcreteClass
AbstractClassNamingConvention
AbstractClassWithOnlyOneDirectInheritor
AbstractClassWithoutAbstractMethods
AlphaUnsortedPropertiesFile
Annotation
AnonymousInnerClass
AntResolveInspection
ArrayLengthInLoopCondition
AssertMessageNotString
AssertsWithoutMessages
AssignmentToForLoopParameter
AssignmentToNull
AssignmentToStaticFieldFromInstanceMethod
AutoBoxing
AutoCloseableResource
AutoUnboxing
BooleanMethodIsAlwaysInverted
BooleanParameter
BooleanVariableAlwaysNegated
BreakStatement
CallToSimpleGetterInClass
CastToConcreteClass
ChainedMethodCall
CheckForOutOfMemoryOnLargeArrayAllocation
CheckStyle
CheckedExceptionClass
ClassComplexity
ClassCoupling
ClassHasNoToStringMethod
ClassIndependentOfModule
ClassInheritanceDepth
ClassLoaderInstantiation
ClassNamePrefixedWithPackageName
ClassOnlyUsedInOnePackage
ClassUnconnectedToPackage
ClassWithoutConstructor
ClassWithoutLogger
ClassWithoutNoArgConstructor
CloneableClassInSecureContext
CloneableImplementsClone
CollectionAddAllCanBeReplacedWithConstructor
CollectionsMustHaveInitialCapacity
ConditionalExpression
ConstantConditions
ConstantDeclaredInAbstractClass
ConstantOnRHSOfComparison
ContinueStatement
CssConvertColorToRgbInspection
CssUnusedSymbol
CyclicClassDependency
CyclicPackageDependency
CyclomaticComplexity
DanglingJavadoc
DeprecatedClassUsageInspection
Deprecation
DeserializableClassInSecureContext
DesignForExtension
DisjointPackage
DuplicatePropertyInspection
DuplicateStringLiteralInspection
Duplicates
EmptyMethod
EnumClass
EqualsReplaceableByObjectsCall
EqualsUsesNonFinalVariable
ErrorRethrown
Eslint
ExtendsConcreteCollection
ExtendsThrowable
FeatureEnvy
FieldAccessedSynchronizedAndUnsynchronized
FieldCount
FieldHasSetterButNoGetter
FieldNotUsedInToString
FieldRepeatedlyAccessed
FinalClass
FinalMethod
ForLoopWithMissingComponent
ForeachStatement
FunctionWithMultipleLoopsJS
GjsLint
GuavaFluentIterable
HardCodedStringLiteral
HardcodedFileSeparators
HardcodedLineSeparators
HashCodeUsesNonFinalVariable
HtmlTagCanBeJavadocTag
HtmlUnknownTarget
IfCanBeSwitch
IfMayBeConditional
IgnoreDuplicateEntry
IgnoreRelativeEntry
IgnoreUnusedEntry
ImplicitCallToSuper
ImplicitNumericConversion
InconsistentResourceBundle
InnerHTMLJS
InstanceVariableInitialization
InstanceVariableOfConcreteClass
InstanceofChain
InstanceofInterfaces
InterfaceWithOnlyOneDirectInheritor
JSDeclarationsAtScopeStart
JSHint
JSLint
JUnitTestNG
Jscs
LambdaParameterNamingConvention
LawOfDemeter
LengthOneStringsInConcatenation
LocalCanBeFinal
LocalVariableOfConcreteClass
LongLine
MagicCharacter
MagicConstant
MagicNumber
MavenModelInspection
MethodCallInLoopCondition
MethodCount
MethodNamesDifferOnlyByCase
MethodOnlyUsedFromInnerClass
MethodReturnOfConcreteClass
MethodWithMultipleLoops
MissingPackageInfo
ModuleWithTooManyClasses
MultipleReturnPointsPerMethod
NestedMethodCall
NestedSwitchStatement
NestedTryStatement
NonCommentSourceStatements
NonSerializableFieldInSerializableClass
NonStaticInnerClassInSecureContext
NonSynchronizedMethodOverridesSynchronizedMethod
NoopMethodInAbstractClass
NullableProblems
ObjectAllocationInLoop
ObjectEquality
OverloadedVarargsMethod
PackageVisibleField
PackageWithTooFewClasses
PackageWithTooManyClasses
ParameterHidingMemberVariable
ParameterOfConcreteClass
ParametersPerConstructor
PrivateMemberAccessBetweenOuterAndInnerClass
ProblematicWhitespace
ProtectedField
ProtectedInnerClass
PublicConstructor
PublicMethodNotExposedInInterface
PublicMethodWithoutLogging
RedundantMethodOverride
ResultOfObjectAllocationIgnored
ReturnNull
ReturnThis
SameParameterValue
SerializableClassInSecureContext
SerializableHasSerializationMethods
SimplifiableIfStatement
SingleClassImport
SpellCheckingInspection
StaticMethodOnlyUsedInOneClass
StaticNonFinalField
StaticVariableInitialization
StaticVariableOfConcreteClass
StaticVariableUninitializedUse
StringBufferMustHaveInitialCapacity
StringCompareTo
StringConcatenation
StringConcatenationMissingWhitespace
StringEquals
StringEqualsIgnoreCase
StringTokenizer
SuperTearDownInFinally
SuspiciousLiteralUnderscore
SuspiciousLocalesLanguages
SwitchStatement
SwitchStatementWithTooManyBranches
SynchronizationOnStaticField
SyntaxError
SystemExit
SystemOutErr
SystemProperties
TailRecursion
TestMethodWithoutAssertion
ThisEscapedInConstructor
ThreeNegationsPerMethod
ThrowCaughtLocally
TodoComment
TooBroadCatch
TooBroadThrows
TrailingSpacesInProperty
TransientFieldNotInitialized
TryFinallyCanBeTryWithResources
TsLint
TypeMayBeWeakened
UncheckedExceptionClass
UnclearBinaryExpression
UnnecessaryDefault
UnnecessaryFinalOnLocalVariableOrParameter
UnnecessaryUnicodeEscape
UnqualifiedFieldAccess
UnqualifiedInnerClassAccess
UnqualifiedMethodAccess
UnqualifiedStaticUsage
UnusedProperty
UnusedReturnValue
UseOfAnotherObjectsPrivateField
UseOfPropertiesAsHashtable
UtilityClass
UtilityClassCanBeEnum
VarargParameter
VariableNotUsedInsideIf
WeakerAccess
WrongPropertyKeyValueDelimiter
XmlHighlighting
XmlPathReference
XmlUnboundNsPrefix
unused
```
##

**Comment by romani** [comment]
As we suppress validation we need to put a comment for it in a config, as we could change our mind if we know original reason of suppression. For examples take a look at our configs for pmd , findbugs and checkstyle.

**Comment by romani** [comment]
@mkordas , for some reason I have 27 "Velocity violations" at my local IntelijIdea inspection result.
Example:
```
  Name      index.xml.vm    Location      file [checkstyle] - .../src/xdocs/index.xml.vm    Problem synopsis      Cannot resolve variable 'projectVersion' (at line 8)
```

Do you have the same ?
All of them are real false-positive as web page generation works fine.

**Comment by romani** [comment]
We need to put comments to rules that disabled during August cleanup first.

**Comment by mkordas** [comment]
@romani, how do we want to handle that? Should I create GitHub issue for every reasonable inspection that is not yet fixed? Majority of them require either api changes or just substantial amount of work

**Comment by romani** [comment]
No need for separate issues, thare too much of rules.

Can you skim this list and put a comment for rules that disabled on a reason during August, i hope you still remember some of them.

**Comment by mkordas** [comment]
OK, let's start discussing a few first items

**AbstractClassExtendsConcreteClass**
We have two such classes in API package:
* class `AbstractLoader` is declared 'abstract', and extends a concrete class `DefaultHandler`
* class `AbstractViolationReporter` is declared 'abstract', and extends a concrete class `AutomaticBean`
@romani, do you have any ideas what should we do with those?

**AbstractClassWithOnlyOneDirectInheritor**
Description:
>This inspection is intended for J2ME and other highly resource constrained environments. Applying the results of this inspection without consideration might have negative effects on code clarity and design.
Reports abstract classes which have precisely one direct inheritor. While such classes may offer admirable clarity of design, in memory-constrained or bandwidth-limited environments, they needlessly increase the total footprint of the application. Consider merging the abstract class with its inheritor.

**AbstractClassWithoutAbstractMethods** 
Both `com.puppycrawl.tools.checkstyle.BaseCheckTestSupport` and `com.puppycrawl.tools.checkstyle.gui.AbstractCellEditor` do not have any abstract methods, but they are declared abstract. @romani, any thoughts? I don't see any value in this inspection.

**Annotation**
It's just to detect annotations if project needs to keep compatibility with Java 1.4 and lower - not applicable to us.

**Comment by romani** [comment]
> class AbstractLoader is declared 'abstract', and extends a concrete class DefaultHandler

that is strange design, but I would make API changes only at 7.0, we need to postpone fix of that.

> class AbstractViolationReporter is declared 'abstract', and extends a concrete class AutomaticBean

AbstractViolationReporter is abstract as it has abstract methods. I do not see any problems with such classes. Abstract does not imply that all his parents are abstracts. My be not ideal design, but for now I do not see problem with it.

> AbstractClassWithOnlyOneDirectInheritor

not sure that is problem, we could look case by case, but in general we are library so other child classes could be outside.

> AbstractCellEditor, BaseCheckTestSupport

should be renamed, abstract modified should match a name. That classes are not API, so coudl refactor them easily

> Annotation

we do not need that, we will never support old java version

**Comment by mkordas** [comment]
@romani 
>should be renamed, abstract modified should match a name. That classes are not API, so coudl refactor them easily

Inspection **AbstractClassWithoutAbstractMethods** is not about class name, it's about not having abstract methods. What do you think?

**Comment by romani** [comment]
>Inspection AbstractClassWithoutAbstractMethods is not about class name, it's about not having abstract methods. What do you think?

Abstract modifier should be removed, name should be changed if required.

**Comment by mkordas** [comment]
Let's proceed with explanations:

**CastToConcreteClass**
Description:
> Reports casting a value to a concrete class, rather than an interface. Such declarations may represent a failure of abstraction, and may make testing more difficult. Declarations whose classes come from system or third-party libraries will not be reported by this inspection

65 such issues, we would need to create some additional interfaces, I don't see enough benefits of it.

**CheckedExceptionClass**

Description:
> Reports checked exception classes (i.e. subclasses of Exception which are not also subclasses of RuntimeException). Certain coding standards require that all user-defined exception classes be unchecked.

@romani, should we convert `CheckstyleException` to the unchecked one?

**AssertsWithoutMessages**

Description:
>Reports calls to JUnit assertXXX() or fail() methods that do not have an error message string argument. An error message on assertion failure may help clarify the test case's intent.

Not needed, tests and assertions should be readable without additional documentation.

**Comment by romani** [comment]
Please put such reason comments to config file, in my experience if right now you not see a reason in a Rule/Check , there is non zero chance that you will change your mind after some time (I had a lot of examples from my own experience). But we need to know exact reason why we suppressed the case.

> we would need to create some additional interfaces, I don't see enough benefits of it.

agree

> should we convert CheckstyleException to the unchecked one?

this is good question, it is definitely decision of Checkstyle7 update. Please create issue on this, we need to put there enough links with prove that this is good approach. As first answer "yes, we should make it unchecked" as all other big projects do/did this, but we have recheck one more time and put a lot of evidences to issue.

> tests and assertions should be readable without additional documentation.

In my experience, ```fail()``` is bad and should be ```fail("explanation")``` , with "assertXXX" I am not so strict as assertEquals is self descriptive. Lets have a discussion there or lets share exact code cases.

**Comment by romani** [comment]
I closing in favor of #4681 .
