### ISSUE TITLE
Remove delay on displaying "Starting audit", flush result after each file processing

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#2085]
1) When running checkstyle from the command line, I noticed the text "Starting audit..." actually doesn't show up until the auditing is technically done. This isn't really noticably when checkstyle finishes pretty fast, but when it takes more than a few seconds because its analyzing lots of files with many checks, you start to take notice. Sometimes I even question if the program started or not because the computer might be lagging.

2) It would be a nice feature if for the command line run, it would atleast display the "Starting audit" right away.
It also wouldn't be bad to go the extra mile and do the same for errors after each file is analyzed.

Code wise it seems like a simple change: https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/DefaultLogger.java#L141
The writer just needs to be flushed after the println.

**Comment by romani** [comment]
merged. Thanks a lot !
