### ISSUE TITLE
Wasted disk access

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#2103]
While looking into checkstyle and some of its hot spots on my slower machine, I noticed 2 things with how CS is gathering and using files that are creating slowdowns.

https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/Main.java#L198

If you provide CS with a directory, it will be gathering all the files in every sub-directory here and doing nothing more with them except making sure there is atleast one. We then duplicate the full scan here, https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/Main.java#L224, actually saving the files for processing. CS should only need to do this scan once.

**Comment by romani** [comment]
I am ok with any optimizations in Main.java

**Comment by romani** [comment]
fix is merged.
