### ISSUE TITLE
[gradle checkstyle] java.lang.ClassNotFoundException: com.puppycrawl.tools.checkstyle.CheckStyleTask

### ISSUE THREAD

**Issue by Piasy** [checkstyle/checkstyle#2107]
I'm using checkstyle with Android Studio 1.3.2, gradle 2.4, when I apply the checkstyle plugin, and set toolVersion to 6.10.1, the exception is thrown.

**Comment by romani** [comment]
we need all details of how you run Checkstyle.
Do you use checkstyle through plugin ? if yes please try to contact to plugin team first.
I need to have your checkstyle configuration, file where failure is happen.
Please reproduce issue with our CLI - http://checkstyle.sourceforge.net/cmdline.html#Download_and_Run

**Comment by romani** [comment]
you most likely are facing broken compatibility issue: #1108 , 

FYI: https://issues.gradle.org/browse/GRADLE-3314 is Fixed , Fix Version/s: 2.7-rc-1

**Comment by romani** [comment]
you need to use gradle version 2.7-rc-1 , https://travis-ci.org/sevntu-checkstyle/checkstyle-samples/jobs/78754490#L172 , https://github.com/sevntu-checkstyle/checkstyle-samples/commit/129677111c117af30a1459d260d31ba15dea4295

**Comment by Piasy** [comment]
I'm not use any external plugin, only the built-in gradle checkstyle plugin, the code in my github repo could reproduce the problem with `./gradlew checkstyle` in project root, the code url is: https://github.com/Piasy/vb-android-app-quality/tree/6d60fdac8552eaa7615a813664cd7fccc4f99c76  
When I run the checkstyle-6.10.1-all.jar with command `java -jar checkstyle-6.10.1-all.jar -c ~/src/vb-android-app-quality/config/quality/checkstyle/checkstyle.xml ~/src/vb-android-app-quality/app/src/main/java/vb/android/app/quality/Flavors.java`, it fails with:
```bash
unable to parse configuration stream
Checkstyle ends with 1 errors.
```

**Comment by Piasy** [comment]
Thanks for your reply, I'll try gradle 2.7-rc-1 later.
