### ISSUE TITLE
GenericWhiteSpaces Giving wrong validation error

### ISSUE THREAD

**Issue by Vulpios** [checkstyle/checkstyle#2111]
GenericWhiteSpaces validation is giving the: '&gt;' is followed by an illegal character. To a valid syntax.

extends SomeClass&lt;E&gt;implements GenericDao&lt;E&gt;

SomeClass&lt;E&gt;implements

Does not have spaces in between then and this is a valid syntax to the compiler (although it is ugly, but I found out that it is a bug on eclipse mars formatter, can't get rid of it)

**Comment by romani** [comment]
> Does not have spaces in between then and this is a valid syntax to the compiler 

if you use such formatting (without spaces) you do not need that Check to be activated - just remove it from your configuration.

Checkstyle is about a style/formatting (that is different form team to team) and not about to help compiler with some problematic code.

If you do not need style that is enforced by a Check - remove Check from configuration.

> found out that it is a bug on eclipse mars formatter, can't get rid of it

just report an issue to Eclipse and disable a Check till Eclipse resolve its formatter.

**Comment by Vulpios** [comment]
Ok then! I've done that. Opened a bug on eclipe. Thank you for faster answer.
