### ISSUE TITLE
FileTabCharacterCheckTest.testBadFile fails if locale is non-English

### ISSUE THREAD

**Issue by michael-o** [checkstyle/checkstyle#2137]
Build from current master, I receive:

    Results :
    
    Failed tests:
    FileTabCharacterCheckTest.testBadFile:93->BaseCheckTestSupport.verify:121 error message 0 expected:<...\checkstyle\Claira ([The system cannot find the file specified])> but was:<...\checkstyle\Claira ([Das System kann die angegebene Datei nicht finden])>
    
    Tests run: 1545, Failures: 1, Errors: 0, Skipped: 1

Looking at the tests, I see that the code expects an English locale which is not always the case. Make the test locale independent.

**Comment by mkordas** [comment]
@michael-o Thanks for the report, I'm on it. The test is OS-dependent, so if you have localized version of OS it indeed may fail.

**Comment by romani** [comment]
merged.
