### ISSUE TITLE
Use Error Prone tool to detect issues with code during compile time

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#2160]
Project GitHub: https://github.com/google/error-prone
Documentation: http://errorprone.info

Integration with Checkstyle should be straightforward. We just need to invoke compiler second time for input files without Error Prone.
##

**Comment by mkordas** [comment]
Error Prone has been integrated with the build.

**Comment by romani** [comment]
we have problem with compilation in Eclipse (I tested it on 4.5):
```
Plugin execution not covered by lifecycle configuration: org.apache.maven.plugins:maven-compiler-plugin:3.3:testCompile (execution: compile-with-error-prone, phase: test-compile)
```

I did not found a way to do it by lifecycle-mapping plugin configuration, while problem exists I comment out Error Prone usage in pom.xml, we value ability to work in Eclipse easily more than any plugin.

**Comment by pbludov** [comment]
It looks like there is a working solution in https://github.com/google/error-prone/issues/376#issuecomment-336015822
