### ISSUE TITLE
Unify naming of all files with test inputs

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#2161]
1) All files with code that is bad on purpose should be named in the same way. Let's start their names with 'Input' word.

2) All Input files should be located in the same package as UTest file and Check.

**Comment by MEZk** [comment]
@mkordas 
Good point. As for me, It is also would be a good idea to place input files for UT in folders to follow project structure. Same package-structure: class -> UT -> Input file. On the other hand,  some tests reuse input files. Does it make sense?

**Comment by romani** [comment]
> Same package-structure: class -> UT -> Input file

yes, we try to do that, but there are a lot of files that required to be reviewed.

>  On the other hand, some tests reuse input files.

yes, but that is old approach, reusage of Inputs cause dependency between tests. UTs should always be independent. It will cost us bigger amount of files in repo but will not force to update MethodCountTest and HiddenFieldCheckTest in the same update.

**Comment by rdiachenko** [comment]
'forbiddenapis' verification tool was activated in scope of #1217. Input sources for tests were added to exclude list (see PR #2347). **This exclude list should be reviewed and updated after tests inputs will be renamed in scope of the current issue.**

**Comment by rnveach** [comment]
@romani @mkordas
I believe the 2 items are done, once PR #2418 is merged. All other changes are in master already.
Please feel free to look over everything if you desire, and make any comments/suggestions you see.

**Comment by romani** [comment]
two files without "Input" prefix : 
checkstyle/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle [master|✔] $ ls 
LocalAnnotations.java
MyAnnotation.java

**Comment by rnveach** [comment]
@romani I fixed the remaining files.
InetSocketAddress should be the only one left because the test requires the same name as "java.net.InetSocketAddress".
I reviewed the 'forbiddenapis' and only 2 items can be removed. We can't remove more because it is based on the class names, not the file names, of the input files.

**Comment by romani** [comment]
http://docs.oracle.com/javase/7/docs/api/allclasses-noframe.html

@rnveach , Does it make sense to reuse some of standard classes with name started by Input ? For example - "InputStream" . 

FYI: There is long awaited Check idea https://github.com/sevntu-checkstyle/sevntu.checkstyle/issues/256 that will help us to enforce that rule for future.

**Comment by romani** [comment]
> I reviewed the 'forbiddenapis' and only 2 items can be removed.

Please remove at least these 2 item.

**Comment by romani** [comment]
Two issues (#2541, #2540) are created to let us close this issue.

**Comment by rnveach** [comment]
> Does it make sense to reuse some of standard classes with name started by Input ?

Yes, but this would be changing the purpose of the test the file is connected to.
"VisibilityModifierCheckTest.testImmutableSpecifiedSameTypeName" tests using the default configuration of VisibilityModifierCheck. 
https://github.com/checkstyle/checkstyle/blob/e2cca1a0ad8e34442a7f18e3b214b13d300f165b/src/main/java/com/puppycrawl/tools/checkstyle/checks/design/VisibilityModifierCheck.java#L265
Thats why it specifically uses "InetSocketAddress". There is already a test specifying a custom class list, "testUserSpecifiedImmutableClassesList", and none of the defaults has an "Input".

**Comment by romani** [comment]
please make a comment at our InetSocketAddress that we need the same name as it defined in Check , to avoid such questions in future.

**Comment by romani** [comment]
I will add a comment.

**Comment by romani** [comment]
closed.
