### ISSUE TITLE
TranslationCheck does not catch that some translation files are missed

### ISSUE THREAD

**Issue by MEZk** [checkstyle/checkstyle#2166]
**Problem:**
TranslationCheck checks keys only for existing properties files. If file does not exist (like messages_ja.properties in [checkstyle/src/main/resources](https://github.com/checkstyle/checkstyle/tree/master/src/main/resources/com/puppycrawl/tools/checkstyle)), TranslationCheck will not rise violation. 

**Proposal:**
Create special property for TranslationCheck. Using the property user can specify which localizations (patterns: ja, pt, es, etc.) must be present for TranslationCheck. And if property file is missed, the check will rise violation, for example: "Property file messages_ja.properties is missed."

**Comment by romani** [comment]
fixed.
