### ISSUE TITLE
HiddenFieldCheck does not rise violation, when lambda parameter, which type is omitted, hides a field

### ISSUE THREAD

**Issue by MEZk** [checkstyle/checkstyle#2175]
If parameter types of lambda expression are omitted, HiddenFieldCheck will not rise any violations. The problem is due to the fact that ANTLR parses parameters (which types are omitted) as identifiers and HiddenFieldCheck does not take into account those cases. 

Example:
````java
/**
  * Lambda parameter 'languageCode'
  * hides a field 'languageCode'.
  */
static List<String> languageCodes = Arrays.asList("de", "ja", "fr", "pt");
static String languageCode = new String();
{
    names.forEach(languageCode -> System.out.println(languageCode)); // violation should be risen here
}
````

**Comment by romani** [comment]
merged

discussion and testing results are at https://github.com/checkstyle/checkstyle/pull/2176.
