### ISSUE TITLE
Resovle unstability of SuppressionsLoaderTest.testLoadFromURL

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#2191]
That test fail too much and demand manual relaunch from admins.

https://travis-ci.org/checkstyle/checkstyle/jobs/80531821#L724

```
    @Test
    public void testLoadFromURL() throws Exception {
        boolean online = isInternetReachable();
        Assume.assumeTrue(online);
```

assumption return false - build is failed.
We need to skip a test if we are not online.
Please also update Test to try to download it from github location if sourceforge is not available.

**Comment by michael-o** [comment]
I am suffering from this to in a corporate environment because outbound traffic is routed through a proxy:

    Tests run: 14, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 71.883 sec <<< FAILURE! - in com.puppycrawl.tools.checkstyle.filters.SuppressionsLoaderTest
    testLoadFromURL(com.puppycrawl.tools.checkstyle.filters.SuppressionsLoaderTest)  Time elapsed: 71.699 sec  <<< ERROR!
    org.junit.AssumptionViolatedException: got: <false>, expected: is <true>
            at org.junit.Assume.assumeThat(Assume.java:95)
            at org.junit.Assume.assumeTrue(Assume.java:41)
            at com.puppycrawl.tools.checkstyle.filters.SuppressionsLoaderTest.testLoadFromURL(SuppressionsLoaderTest.java:69)

**Comment by rdiachenko** [comment]
I'm on it

**Comment by michael-o** [comment]
Great, if you have something to test, I'll fetch and test it at work.

**Comment by rdiachenko** [comment]
NOTE: PowerMock has a bug (https://github.com/jayway/powermock/issues/428) with assumeTrue(false) that is why our test is not ignored when ```online = false```.

**Comment by michael-o** [comment]
OK, the issue is pending for two months.

**Comment by romani** [comment]
@rdiachenko , just remove Assume and use a standard statements to skip a test, and put a comment on it, to avoid changing it back in future till powermock issue is resolved

**Comment by romani** [comment]
@rdiachenko, thanks a lot  for fix.

@michael-o , please let us know if you need some fixes to ease(make it more frequest) release process of maven plugin.

**Comment by michael-o** [comment]
Just pulled from canonical master while the issue seems to be fixed, I see now:

    [INFO] --- xml-maven-plugin:1.0:validate (default) @ checkstyle ---
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD FAILURE
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time: 10:33 min
    [INFO] Finished at: 2015-09-24T12:08:41+02:00
    [INFO] Final Memory: 65M/327M
    [INFO] ------------------------------------------------------------------------
    [ERROR] Failed to execute goal org.codehaus.mojo:xml-maven-plugin:1.0:validate (default) on project checkstyle: While parsing /home/osipovmi/Projekte/checkstyle/src/site/resources/files/suppressions_none.xml: null: NullPointerException -> [Help 1]
    [ERROR]
    [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
    [ERROR] Re-run Maven using the -X switch to enable full debug logging.
    [ERROR]

This is probably a bug in the XML Maven Plugin. Thoughts?

**Comment by rdiachenko** [comment]
@michael-o, could you please provide more full log?

**Comment by romani** [comment]
> org.codehaus.mojo:xml-maven-plugin:1.0:validate

That happens some time when internet is not stable. Please try one more time. This happens a lot on Travis too.
xml-maven-plugin have no "skip" option and I did not found any way to report issue for this project. If you know this project it would be great to share a link to issue tracker.

**Comment by mkordas** [comment]
@romani, isn't it just https://github.com/mojohaus/xml-maven-plugin/issues?

**Comment by romani** [comment]
@mkordas , thanks a lot. I will file an issue to it

**Comment by romani** [comment]
issue is created - https://github.com/mojohaus/xml-maven-plugin/issues/2
