### ISSUE TITLE
StrictDuplicateCode trips up on file headers

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#22]
Created: 2012-12-18
Creator: Yegor Bugayenko 
Ref: #sf693
Created: 2009-04-20
Creator: Toby Byron 
ref: #sf555

I cannot use the StrictDuplicateCode check because it reports excessive essentially false duplicates.

Specifically, each of my source code files starts with the same file header (a comment that contains a copyright notice and boilerplate relating to the GPL3 license that my code is released under).

Yes, literally speaking, StrictDuplicateCode is correctly finding duplicates here however standard file headers are clearly not what people want to have reported to them.

So, what StrictDuplicateCode needs is to automatically suppress any duplicate comments at the start of files from its reports.

Would be nice to have a property "header" for StrictDuplicateCodeCheck:

<module name="StrictDuplicateCode">
  <property name="header" value="..."/>
</module>

**Comment by ewoks** [comment]
any further explanation for removal reason? is there or will there be replacement? thanks

**Comment by romani** [comment]
reason of removal - https://github.com/checkstyle/checkstyle/issues/523#issuecomment-68490640
No replacement is planned for now, may be eventually after all completion of hundred ideas of dirty code detection in Java. I would recommend to use CPD to copy paste detection is you are crazy about that. But what I really recommend it to review your application to minimize dependencies between code, look at report against Chekstyle - http://checkstyle.sourceforge.net/dsm/index.html
