### ISSUE TITLE
SuppressWarnings should support CamelCase

### ISSUE THREAD

**Issue by krzyk** [checkstyle/checkstyle#2202]
Following annotation `@SuppressWarnings("checkstyle:redundantmodifier")` is less readable than `@SuppressWarnings("checkstyle:RedundantModifier")`.
Maybe there is a reason why all lower case annotations were introduced, but it makes excluding checkstyle warnings very unreadable in comparison to PMD (`@SuppressWarnings("PMD.AvoidCatchingGenericException")`) ones.

Moreover `SuppressWithNearbyCommentFilter` supports camel case, so I think `SuppressWarningsFilter` should also.

**Comment by romani** [comment]
merged.
