### ISSUE TITLE
create MacOS matrix item for Travis CI

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#2210]
workaround from: https://github.com/travis-ci/travis-ci/issues/2839#issuecomment-73199188

We need only "mvn clean verify" just to be sure that users can do contribution from MacOS.

**Comment by romani** [comment]
caching for MacOS does not work - https://github.com/travis-ci/travis-ci/issues/4011

we need cache to avoid very long build (that could be cancelled and fail the whole build status) as it downloads huge Maven repo again and again - https://travis-ci.org/checkstyle/checkstyle/jobs/81111572

The main reason of MacOS build as users reported a difference of result of MacOS and Linux for verify(coverage) stage, but this stage demand too much artifacts to download.

**Comment by mkordas** [comment]
Can we run just `mvn test` until caching will be possible?

**Comment by romani** [comment]
on Friday even "mvn test" failed, now looks ok.

**Comment by romani** [comment]
cache for Macos is introduced, issue fixed https://github.com/checkstyle/checkstyle/commit/17f31f53b6ab8bddd07a865fb79d35d392b63f17
