### ISSUE TITLE
Rename test classes to match production class name + "Test"

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#2215]
All test classes dedicated for checks should be named the same as check class with additional suffix "Test".
It's not always the case. For example `SummaryJavadocCheck` has its test `SummaryJavadocTest` while it should be `SummaryJavadocCheckTest`.
When following this pattern IDE navigation becomes easier, as tests are detected automatically.

**Comment by romani** [comment]
does it sound like a new Check ? ( we could fix it now , but it is so easy to miss that in future PRs)

Is such Check too specific to Checkstyle code and in real life will not be practical ? (some time people create two test files for one class, or use non-exiting name of class to show that this tests are functional(not a pure Utests) )

Side proposal:
production class name  ===> main class name.
As we have maven folders "main" and "test".

**Comment by mkordas** [comment]
Yes, we could have check for that. It would require that every class has corresponding test. Enums and interfaces should be probably excluded from that.
> some time people create two test files for one class

That's not a problem, we can require at least one class matching pattern MainClassName*Test, meaning that there can be additional description where star is placed.

Benefits:
* simple convention
* unit tests are easy to find
* detection if class is moved to different package, but test is not

It would be very restrictive and controversial though... In practice not every class requires separate unit test. If it's for example simple bean, it may be tested indirectly by its usage.

Anyway, I see a lot of value in such check.

**Comment by romani** [comment]
we might need to go not from main class but from test. If test exists it should be named as one of  main classes of the same package. In this case we will not demand from user anything but convention of names (Checkstyle is not a position to demand tests and be smart of calculating what is required to have a test).

If you agree, please update original description and remove all our discussion from this issue.

**Comment by mkordas** [comment]
Going from the test will not work, as there's nothing bad in having additional tests named as modules, components or functionality areas covered. Then we have also integration, system and end-to-end which obviously won't have any corresponding classes. Typical pattern is to use also AbstractTests to group some testing functionality.

**Comment by romani** [comment]
going from both sides will require long list of what to suppress. But main point is to raise violation on moment test file is created, and we do not demand from user tests (that might be another Check).

**Comment by mkordas** [comment]
Going from main class names is enough. You just take the name and check that in the same package under 'test' root there is something beginning with this name and ending with Test. It is restrictive, but at leas simple convention, that each class should have it's own unit test(s), even if the class has 100% code coverage indirectly.

**Comment by romani** [comment]
> that each class should have it's own unit test(s)

non of my commercial projects had that, only in Checkstyle we are so modular and fanatic to do this.
Idea of pure UTs are non-efficient and impractical. 

Looks like we speak about different things , please give me a name of Check to let me be sure we speak about the same.

**Comment by mkordas** [comment]
My commercial project has that with only a few exceptions. Usually it is needed anyway to achieve 100% code coverage.
Name of the check would be something like Test ForEachClass.

**Comment by MEZk** [comment]
@romani 
I think it has been already done.

**Comment by romani** [comment]
Ok , lets close it, as we did not come to conclusion  in discussion on new Check requirements.
