### ISSUE TITLE
NoWhitespaceAfter, NoWhitespaceBefore and WhitespaceAround don't support GENERIC_START nor GENERIC_END tokens

### ISSUE THREAD

**Issue by hustodemon** [checkstyle/checkstyle#2219]
Hi,
recently I've upgraded from CS 5.8 to 6.10.1 and I'm experiencing the problem mentioned in $subj - we have been using this rules-token combination for eternity and now we must upgrade to CS ver. 6 (because of Java 8).

I wonder if this is a regression (seems that was a lot of refactoring regarding acceptable tokens, like in #342) or an intended behavior (the documentation says that this combination is not valid, but I don't see any note about it in changelog). What do you think?

(PS, I tried using GenericWhitespace rule, but it produces a lot of new violations for our codebase. And unfortunately it is too strict and can't be configured.)

**Comment by romani** [comment]
Thanks for reporting this, it is a regression.

**Comment by romani** [comment]
FYI: GenericWhitespace(http://checkstyle.sourceforge.net/config_whitespace.html#GenericWhitespace)  was updated to follow Generic rules from http://google.github.io/styleguide/javaguide.html#s4.6.2-horizontal-whitespace.

but yes, such a generic Checks should give you ability to make your own style.

**Comment by hustodemon** [comment]
Thanks for the fast reaction!
