### ISSUE TITLE
Replace line-based suppressions with inline ones for Checkstyle's suppressions.xml

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#2226]
All line-based suppressions from https://github.com/checkstyle/checkstyle/blob/checkstyle-6.10.1/config/suppressions.xml should be replaced with code-inline suppressions.

Code-inline suppressions are temporary solution until AST-based suppressions will be implemented.

Rationale - any change in the files with line-based suppressions may cause build failure even if an author was not modifying code related to suppression. Very few people will know that in such case also modification of `suppressions.xml` is required.

**Comment by MEZk** [comment]
@romani 
Can we provide a fix for the issue, because specifying line numbers in suppression.xml always forces us to update the file each time we perform the modification of the code and it really irritates me?

**Comment by romani** [comment]
@MEZk ,

> should be replaced with code-inline suppressions

I completely disagree on this, as code-inline suppression pollute code with extra comments or annotations.
We need to implement https://github.com/checkstyle/checkstyle/wiki/Checkstyle-GSoC-2016-Project-Ideas#project-name-flexible-suppression-model

But we have only 9 cases of suppression by line. So I am ok to move only them to code and create issue to remove them as soon as flexible suppression is implemented.

**Comment by MEZk** [comment]
@romani 
>But we have only 9 cases of suppression by line. 

Why 9? We have 25 cases of suppression by line.

**Comment by romani** [comment]
Ok , lets give it a try. 
Ok to change even it is 25+9 .

**Comment by romani** [comment]
fix is merged.
