### ISSUE TITLE
 InnerAssignment docs need to mention while idiom

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#2230]
Created: 2006-03-11
Creator: Jason Bennett
SF issue: 418

InnerAssignment code specifically checks for the "while
idiom" (while ( ( str = in.readLine() ) != null )) and
allows it, but the documentation does not mention this.
Documentation should be updated to specifically mention
that code like this is allowed.

**Comment by mkordas** [comment]
I'm on it.

**Comment by romani** [comment]
merged
