### ISSUE TITLE
RequireThis check message is not clear enough

### ISSUE THREAD

**Issue by Vladlis** [checkstyle/checkstyle#2239]
Input:
```java
class Test {
    private int foo;

    class Nested {
        void bar() {
            foo++;
        }       
    }
}
```
Result:
```bash
vlad@vlad-N61PC-M2S ~/cli $ java -jar checkstyle-6.10.1-all.jar -c my_check.xml Test.java
Starting audit...
/home/vlad/cli/Test.java:6:13: Reference to instance variable 'foo' needs "this.".
Audit done.
Checkstyle ends with 1 errors.
```

Shouldn't we extend the message? For instance:
> Reference to instance variable 'foo' needs "Test.this."

**Comment by mkordas** [comment]
@Vladlis, what is the output that you'd expect here?

**Comment by Vladlis** [comment]
@mkordas, there should be no violations. Adding ```this``` causes compilation error.

**Comment by mkordas** [comment]
But this check is about requiring `this` in all cases. Shouldn't there be `Test.this.foo++` in code? But I agree that violation message is not helpful in this case.

**Comment by Vladlis** [comment]
@mkordas, yes, you're right.

**Comment by mkordas** [comment]
Unfortunately I don't see test cases covering that. Also xdoc could be updated to make behaviour clear. @Vladlis, would you be able to repair it properly?

**Comment by Vladlis** [comment]
@mkordas, yes, I guess I can handle this.

**Comment by mkordas** [comment]
@Vladlis, are you going to work on this one?

**Comment by romani** [comment]
fix is merged.
