### ISSUE TITLE
cobertura:check goal fails the build while executing on Travic CI

### ISSUE THREAD

**Issue by MEZk** [checkstyle/checkstyle#2243]
**Problem**
cobertura:check goal fails the build while executing on Travis CI. 

**Reason**
TranslationCheck is reported as not fully covered with UT. 
See https://travis-ci.org/checkstyle/checkstyle/jobs/82176441 . 

**Details of investigation**
On local PC cobertura:check does not fail the build. 
AppVeyor also does not fail the build. See https://github.com/checkstyle/checkstyle/pull/2177#issuecomment-142131480
Details of investigation on local PC: https://github.com/checkstyle/checkstyle/pull/2177#issuecomment-142357197

**Attempts to resolve the problem**
The following attemts to resolve the problem do not work:
[Attempt 1](https://github.com/checkstyle/checkstyle/commit/e040b82ce9693d3dd117fca443ab184b97a2b661)
[Attempt 2](https://github.com/MEZk/checkstyle/commit/24acc9ffd52e61033485c6f3a7c3b957b7f2f0be)

**Comment by romani** [comment]
fixed by #2257
