### ISSUE TITLE
problem of custom javadoc tags during mvn release:prepare

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#2245]
noinspection tag blocked be a release.
`mvn release:prepare -DdryRun=true -Darguments='-DskipTests -DskipITs -Dcobertura.skip=true  -Dpmd.skip=true -Dfindbugs.skip=true -Dcheckstyle.ant.skip=true -Dgpg.passphrase=xxxxxxxxxxxx'
`
commit to fix - d98c79e9be2ff038a4cfc2def20d04e7237d3991

we need to figure out, how to explain maven release plugin that such tag is known.  

@mkordas , please take a look.

**Comment by mkordas** [comment]
@romani, I cannot reproduce. Command `mvn release:prepare -DdryRun=true -Darguments='-DskipTests -DskipITs -Dcobertura.skip=true -Dpmd.skip=true -Dfindbugs.skip=true -Dcheckstyle.ant.skip=true -Dgpg.passphrase=xxxxxxxxxxxx'` works for me fine on Java 8.

Moreover, d98c79e removes just one `noinspection` while we have two of them in the code: https://github.com/checkstyle/checkstyle/search?utf8=%E2%9C%93&q=noinspection

**Comment by romani** [comment]
I noticed a warning in logs about extra tag during site build, but it was not failed a build so I ignored it, release was in more priority.

Ok, I will try to reproduce a problem.

**Comment by romani** [comment]
@mkordas , your command reproduce problem easily on my laptop
https://gist.github.com/romani/72b5c9263fdd2d4dc2a3

**Comment by romani** [comment]
I need to do release 6.11.1and this issue is still a problem. 

@mkordas , Does it make sense to remove tag and suppress this IntelijIdea rule till issue is resolved ?

Additionally we need to put this command (mvn release:prepare -DdryRun ....... ) to Travis , it is not a first time a have problem right during release.

**Comment by mkordas** [comment]
Done in #2253

**Comment by wangmaokang** [comment]
Unknown tag 'date'. (6:4)

**Comment by wangmaokang** [comment]
how to fix 'Unknown tag 'date'. (6:4)'

**Comment by romani** [comment]
@wangmaokang, i do not understand your post. Please extend your question
