### ISSUE TITLE
Fix all issues for Java found by Codacy static analysis tool

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#2271]
Recently Codacy added support for Java analysis. All issues from https://www.codacy.com/app/checkstyle/checkstyle/issues should be analyzed and fixed or suppressed in their GUI.

Github integration could give us ability to use it during PR verification - https://support.codacy.com/hc/en-us/articles/207280219-GitHub

**Comment by MEZk** [comment]
@mkordas @romani Could you share Codace rule set. please? Just for my interest.

**Comment by mkordas** [comment]
@MEZk, here is their config: https://github.com/codacy/codacy-pmdjava/blob/master/src/main/resources/docs/patterns.json

**Comment by romani** [comment]
issue is not done yet, if smb wants to continue - please raise a hand.

**Comment by romani** [comment]
codacy now have now violations on our code. I enabled it.
![screenshot-codacy-github-enabled](https://cloud.githubusercontent.com/assets/812984/14853212/75ec2d88-0c3f-11e6-9e0d-da437aee4478.png)


@MEZk , are we ok to close this Issue ? if all issues are enabled we could close the issue.

**Comment by MEZk** [comment]
@romani 
Yes, I reported false positive in UnusedPrivateMethod rule https://github.com/codacy/codacy-pmdjava/issues/14
