### ISSUE TITLE
rename CheckUtils.isVoidMethod to isNonVoidMethod

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#2273]
base on https://github.com/checkstyle/checkstyle/commit/a21164df1fbaff36ba020968b3a6128ab8476756#commitcomment-13570539

name is wrong, "Non" was missed.

**Comment by romani** [comment]
fixed in e2b4e687d7b8f9d6d5e1346d874b90e4567aff81

**Comment by rnveach** [comment]
@romani 
Doesn't the JavaDoc of the method have to be changed as well?
https://github.com/checkstyle/checkstyle/blob/e2b4e687d7b8f9d6d5e1346d874b90e4567aff81/src/main/java/com/puppycrawl/tools/checkstyle/utils/CheckUtils.java#L401

**Comment by romani** [comment]
@rnveach , fixed, thank a lot for pointing this.
