### ISSUE TITLE
SuppressWarningHolder may support the special warning id "all"

### ISSUE THREAD

**Issue by gallandarakhneorg** [checkstyle/checkstyle#2275]
In several cases (generated code, etc.), it is useful to put a `@SuppressWarnings("all")` at the top of the code.
Unfortunately, this special warning id is recognized by Eclipse, but not by checkstyle.

I suggest to add this special warning id in the implementation of SuppressWarningHolderCheck.

**Comment by romani** [comment]
merged.

**Comment by gallandarakhneorg** [comment]
thank you.
