### ISSUE TITLE
xdoc: Sort Checks alphabetically in content sections

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#2292]
Example: http://checkstyle.sourceforge.net/config_misc.html

It is hard to find Indentation Check, but content should be sorted alphabetically.

One more reference https://sourceforge.net/p/checkstyle/feature-requests/511/

**Comment by romani** [comment]
assigned to @ufltysi .

**Comment by romani** [comment]
I lost a contact with @ufltysi , issue become unassigned again.

**Comment by rnveach** [comment]
@romani I will work on this since I am already familar with the xdocs test.

**Comment by romani** [comment]
thanks a lot !!!

**Comment by romani** [comment]
merged.
