### ISSUE TITLE
Javadoc isn't parsed correctly in files with only CR newlines

### ISSUE THREAD

**Issue by robertwhitebit** [checkstyle/checkstyle#2329]
Printing the javadoc tree by using the [JavadocTreePrinter](https://github.com/checkstyle/contribution/blob/d3b74a1ae272ba15bd6a913c7686f1fcb2ec7622/javadoc-tree-serializer/JavadocTreePrinter.java) from the contribution repository for the checkstyle test file [InputNewlineCrAtEndOfFile.java](https://github.com/checkstyle/checkstyle/blob/aaf606ee0268f140c3694baba4c13b03f7839522/src/test/resources/com/puppycrawl/tools/checkstyle/InputNewlineCrAtEndOfFile.java) will print following tree:

```
|--TEXT[7x0] : [\r * Test case for detection of an existing CR newline at EOF, using the \r * NewlineAtEndOfFileCheck.\r * @author Martin Steiger\r *]
|--EOF[7x129] : [<EOF>]
```

If a file is using just CR line endings, newlines or tokens in the javadoc won't be detected.
Replacing all CR by LF in the file will print the correct javacdoc tree:

```
|--NEWLINE[7x0] : [\n]
|--LEADING_ASTERISK[8x0] : [ *]
|--TEXT[8x2] : [ Test case for detection of an existing CR newline at EOF, using the ]
|--NEWLINE[8x71] : [\n]
|--LEADING_ASTERISK[9x0] : [ *]
|--TEXT[9x2] : [ NewlineAtEndOfFileCheck.]
|--NEWLINE[9x27] : [\n]
|--LEADING_ASTERISK[10x0] : [ *]
|--WS[10x2] : [ ]
|--JAVADOC_TAG[10x3] : [@author Martin Steiger\n *]
    |--AUTHOR_LITERAL[10x3] : [@author]
    |--WS[10x10] : [ ]
    |--DESCRIPTION[10x11] : [Martin Steiger\n *]
        |--TEXT[10x11] : [Martin Steiger]
        |--NEWLINE[10x25] : [\n]
        |--LEADING_ASTERISK[11x0] : [ *]
|--EOF[11x2] : [<EOF>]
```

Replacing all CR by Windows line endings CR+LF also does work correctly:

```
|--NEWLINE[7x0] : [\r\n]
|--LEADING_ASTERISK[8x0] : [ *]
...
```
##

**Comment by romani** [comment]
parsing should be the same no matter what line-ending is in file, the same as for java files.

@baratali , please comment on this issue

**Comment by baratali** [comment]
@romani , according to the Javadoc Antlr grammar a newline symbol is '\n' or '\r\n'
https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/com/puppycrawl/tools/checkstyle/grammars/javadoc/JavadocLexer.g4#L62

**Comment by romani** [comment]
fix is merged

**Comment by rnveach** [comment]
Fix was merged but line and column numbers are still incorrect because we rely on ANTLR and ANTLR doesn't and won't support `\r` line returns correctly by themselves.

Example:
https://github.com/checkstyle/checkstyle/blob/439d094e6ac95d31abc49eea71d2e934b9dde6a2/src/test/resources/com/puppycrawl/tools/checkstyle/grammars/javadoc/expectedJavadocWithCrAsNewlineAst.txt
All lines are line 0.

**Comment by rnveach** [comment]
> All lines are line 0.

With fix at https://github.com/checkstyle/checkstyle/issues/6865#issue-462408882 , `\r` is now seen as a new line, so all lines won't be 0 after it. This seems to go with @romani 's comment as we should "treat them all the same". So far I am seeing `\r`, `\n`, and `\r\n` will be handled the same. Each one will be a new line.

**Comment by rnveach** [comment]
This issue could be corrected when we rebuild the tokens on our end.

**Comment by nmancus1** [comment]
This issue should be reopened:

```bash

➜  src cat -v Test.java 
public  class Test {^M    /**^M     * This is a javadoc comment.^M     * More info, on another line.^M     */^M    void doStuff() {^M^M    }^M}^M%

➜  src java -jar checkstyle-8.44-all.jar -J Test.java
CLASS_DEF -> CLASS_DEF [1:0]
|--MODIFIERS -> MODIFIERS [1:0]
|   `--LITERAL_PUBLIC -> public [1:0]
|--LITERAL_CLASS -> class [1:8]
|--IDENT -> Test [1:14]
`--OBJBLOCK -> OBJBLOCK [1:19]
    |--LCURLY -> { [1:19]
    |--METHOD_DEF -> METHOD_DEF [6:4]
    |   |--MODIFIERS -> MODIFIERS [6:4]
    |   |--TYPE -> TYPE [6:4]
    |   |   |--BLOCK_COMMENT_BEGIN -> /* [2:4]
    |   |   |   |--COMMENT_CONTENT -> *\r     * This is a javadoc comment.\r     * More info, on another line.\r      [2:6]
    |   |   |   |   `--JAVADOC -> JAVADOC [2:7]
    |   |   |   |       |--NEWLINE -> \r [2:7]
    |   |   |   |       |--LEADING_ASTERISK ->      * [2:8]
    |   |   |   |       |--TEXT ->  This is a javadoc comment. [2:14]
    |   |   |   |       |--NEWLINE -> \r [2:41]
    |   |   |   |       |--LEADING_ASTERISK ->      * [2:42]
    |   |   |   |       |--TEXT ->  More info, on another line. [2:48]
    |   |   |   |       |--NEWLINE -> \r [2:76]
    |   |   |   |       |--TEXT ->       [2:77]
    |   |   |   |       `--EOF -> <EOF> [2:82]
    |   |   |   `--BLOCK_COMMENT_END -> */ [5:5]
    |   |   `--LITERAL_VOID -> void [6:4]
    |   |--IDENT -> doStuff [6:9]
    |   |--LPAREN -> ( [6:16]
    |   |--PARAMETERS -> PARAMETERS [6:17]
    |   |--RPAREN -> ) [6:17]
    |   `--SLIST -> { [6:19]
    |       `--RCURLY -> } [8:4]
    `--RCURLY -> } [9:0]

```
