### ISSUE TITLE
Typo in Javadoc tag name

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#2376]
Checkstyle supports Javadoc tag named `basefront`: https://github.com/checkstyle/checkstyle/search?utf8=%E2%9C%93&q=basefront&type=Code

That's a typo - correct name of the tag is `basefont`: http://www.w3schools.com/tags/tag_basefont.asp

Grammar file should be changed to fix the issue.

**Comment by romani** [comment]
@baratali , please assist.

**Comment by romani** [comment]
fix is merged.
