### ISSUE TITLE
New option 'onlyObjectReferences' for ExplicitInitialization

### ISSUE THREAD

**Issue by robertwhitebit** [checkstyle/checkstyle#2399]
http://checkstyle.sourceforge.net/config_coding.html#ExplicitInitialization

Imo it's useful to assign default values to primitive member variables and I normally don't care if people do so. e.g.

``` java
private int a = 0;
private int b = 1;
private int c = 2;
// ...
private boolean a = true;
private boolean b = false;
private boolean c = true;
private boolean d = false;
private boolean e = false;
```

However, I don't see any advantages assigning null to members. e.g.

``` java
private A a = new A();
private A b = null;
private C c = null;
private D d = new D();
```

Maybe it's worth a new option?

Off-Issue: A stackoverflow topic about "Why are Explicit Initiallizations of the default value bad?" http://stackoverflow.com/questions/19939118/why-are-explicit-initiallizations-of-the-default-value-bad
##

**Comment by romani** [comment]
Please provide name of option and its description.

Please provide detaoled set of test cases where you expect violations and do not expect if option is activated.

**Comment by robertwhitebit** [comment]
```java
private int a = 0;
private int b = 1;
private int c = 2;

private boolean a = true;
private boolean b = false;
private boolean c = true;
private boolean d = false;
private boolean e = false;

private A a = new A();
private A b = null; // violation
private C c = null; // violation
private D d = new D();
```

I would only expect a violation where null is unnecessarily assigned to member variables. So, if the option is enabled, all ExplicitInitialization violations will be ignored except null.

onlyObjectReferences: Checks if any class or object member is explicitly initialized to null.

...but maybe I'm just the only one who would use this check :smile_cat:

**Comment by subkrish** [comment]
I am on it.

**Comment by romani** [comment]
fix is merged
