### ISSUE TITLE
constructor String(byte bytes[], String charsetName) should not throw IllegalInstantiation

### ISSUE THREAD

**Issue by swisstofu** [checkstyle/checkstyle#2404]
Hello everybody, 

I'm using the  following code to read a file into a string (`java.nio.file.Files`) : 

````java
return new String(Files.readAllBytes(file.toPath()), StandardCharsets.UTF_8);
````

This should be accepted, as there is to my knowledge no other way to instantiate a String from a byte array, but checkstyle gives the following error `(coding) IllegalInstantiation: Instantiation of java.lang.String should be avoided.`

what is your opinion ? shouldn't an exception be added for that constructor ?

thanks

**Comment by romani** [comment]
Check is general - http://checkstyle.sourceforge.net/config_coding.html#IllegalInstantiation
not only String type related. Your custom configuration force Checkstyle control String type implementation.

Checkstyle can not distinguish c-tors, as we unaware of Types completely.

Counting on params amount does not make sense too - http://docs.oracle.com/javase/7/docs/api/java/lang/String.html , String class have a lot of different c-tors .

Solutions:
- update config to remove String type from there as it cause false-positives.
- use suppressions or certain case (if you benefit from current configuration) - http://checkstyle.sourceforge.net/config_filters.html

**Comment by swisstofu** [comment]
Thanks for the feedback!
