### ISSUE TITLE
JavadocStyleCheck: need to support VAR html tag 

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#2410]
http://www.w3.org/TR/html4/struct/text.html#edef-VAR

please add tag to supported list https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocStyleCheck.java#L75
##

**Comment by romani** [comment]
assigned to @Miky38395 .

**Comment by wltan** [comment]
What exactly needs to be done for this issue? I see that `var` is already part of the `ALLOWED_TAGS`:
https://github.com/checkstyle/checkstyle/blob/3e63560eb0fe8c8965abb87ab01a261909096d27/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocStyleCheck.java#L209-L218
Is this just to update the javadoc and xdoc files? Should be a simple fix if it's similar to the other `gsoc first issue`s.

**Comment by romani** [comment]
> Is this just to update the javadoc and xdoc files? 

yes, please update javadoc. It will be enough to close this issue.

> Should be a simple fix if it's similar to the other gsoc first issues.

"first gsoc issue " is about different, there should be special separate issue for documentation extension with example.

**Comment by romani** [comment]
fix is merged.
