### ISSUE TITLE
IllegalTypeCheck ignores "tokens" configuration parameter

### ISSUE THREAD

**Issue by lennartj** [checkstyle/checkstyle#2415]
The IllegalTypeCheck ignores its "token" configuration parameter which implies that it always checks all scopes (parameter, variable, method return type) for illegal type compliance.

This bug implies that one cannot configure the IllegalType check to validate the public API of classes while having another set of rules for the class's internal state. 

This - in turn - creates problems for entity classes using Date or Timestamp types where one would like a modern type representation externally (joda-time or JDK8 time API typically) but requires the internal representation for the JPA ORM types (i.e. internally one must rely on the old Calendar or Date types).

**Comment by lennartj** [comment]
Patched the error.
Provided unit test to verify the solution.
Created PR.

**Comment by romani** [comment]
so, you want to validate method return types for Illegal Classes only and allow such classes for variables and parameters , am I right ?

**Comment by romani** [comment]
By PR #2496 , I make requiredTokens to be IMPORT only to let user configure Check as it want to.
IMPORT is required to make sure that no false-positives are happen during type matching.

**Comment by romani** [comment]
merged.
