### ISSUE TITLE
Consider moving Custom Checks of Tim Tyler

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#2419]
SourceForge feature requests have a lot of reference to project 
http://timtyler.org/checkstyle/ where bunch of custom Checks are implemented.

One we get out of moratorium period for new Checks, we need to review them and try to merge to main project.
##

**Comment by daniilyar** [comment]
@romani the referenced page does not longer exist and I can't find any Tym's check in the web or across SourceForge pathes. Could you please put here some links where we can take Tym's checks from?
