### ISSUE TITLE
XML Examples must have a valid structure

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#2425]
All XML examples under the xdocs must have a valid XML structure so users can copy them as is for testing and won't get atleast parse errors.

My thoughts on requirements:
A starting XML tag ("<?xml..>") is not required. 
Each example must be a single standalone. We do this sometimes and not others. It will make testing and reading easier if we go full standalone I think.
"..." can be used to denote extra tags/attributes, but if removed, the structure must still remain valid.

Invalid Example: https://github.com/checkstyle/checkstyle/blob/fff24e89001ce2ad9c30d1f573639cd640183669/src/xdocs/config_coding.xml#L2777

**Comment by romani** [comment]
To make xml valid and ready for launch we need schema definition and Checker and Treewalker module. See cat of config at https://github.com/checkstyle/checkstyle/issues/2411 as example

**Comment by romani** [comment]
merged, thanks  a lot for fix !
