### ISSUE TITLE
JavaDoc checks missing customizable JavaDoc tokens

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#2427]
https://github.com/checkstyle/checkstyle/blob/fff24e89001ce2ad9c30d1f573639cd640183669/src/xdocs/config_javadoc.xml#L978

CS' documentation makes reference to customizing what JavaDoc tags the checks process.
The issue is the checks actually do not support this feature currently.

When trying the example above, I get the following exception:

> CheckstyleException: Property 'target' in module NonEmptyAtclauseDescription does not exist

AbstractJavadocCheck should have the following methods: getJavadocTokens , getRequiredJavadocTokens, getAcceptableJavadocTokens

This Check need to be updated to have properly named option for tokens: https://github.com/checkstyle/checkstyle/blob/eeec3dc1d23916462560403a27a4ae94260d61f3/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AtclauseOrderCheck.java#L90
##

**Comment by romani** [comment]
@baratali , please take a look, we need your assistance there.

**Comment by baratali** [comment]
Once this issue is resolved, "Writing Javadoc Checks" wiki-page should be updated with explanations how to use new methods and customize Javadoc Checks: http://checkstyle.sourceforge.net/writingjavadocchecks.html#Customize_token_types_in_Javadoc_Checks

**Comment by rnveach** [comment]
@romani 
@baratali If it is ok and you have no plans to work on this soon, I could start the process now by adding the methods and adjusting the checks if needed.

**Comment by romani** [comment]
@rnveach , contributor @baratali  does not have any assignments on project. Looks like he does not have time to contribute more.
He did great effort to sum-up all problems at howto page with all issues that that need to be resolved before we could start updating our.
You are welcome to take any issue that is not assigned to fix it.

**Comment by romani** [comment]
fix is merged.
