### ISSUE TITLE
remove dependency to commons-lang3 library

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#2428]
That task is good for somebody who want to start contribution to Checkstyle

https://github.com/checkstyle/checkstyle/blob/master/pom.xml#L214

we need to remove that dependency, as right now we depend only util fields of that library, we could copy them to our [CommonUtils.java](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/utils/CommonUtils.java) class.
Dependency should be removed.

**Comment by romani** [comment]
assigned to @chrismacias .

**Comment by chrismacias** [comment]
it seems that after taking out the dependency from pom.xml it asks for ArrayUtils, and StingUtils. Those classes also have dependencies and we end up needing: 
import org.apache.commons.lang3.BooleanUtils;
import org.apache.commons.lang3.CharUtils;
import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;
import org.apache.commons.lang3.math.NumberUtils;
import org.apache.commons.lang3.mutable.MutableInt;
import org.apache.commons.lang3.CharSequenceUtils;
import org.apache.commons.lang3.ObjectUtils;
import org.apache.commons.lang3.StringUtils;
import org.apache.commons.lang3.ArrayUtils;

Should i add the rest of the dependencies?

**Comment by romani** [comment]
we just need to copy required methods from ArrayUtils and StingUtils to our CommonUtils.java.
and put a comment on them that they are copy paste from .... .

**Comment by romani** [comment]
@chrismacias , do you need help ?

**Comment by chrismacias** [comment]
thanks, im divinding into smaller pull request. i should start on same branch right?

**Comment by romani** [comment]
please make such PRs independent from each other , each of them should be base on our master.

**Comment by romani** [comment]
all changes of chrismacias does not matter and are uncomplete, issue is unassigned again.

**Comment by romani** [comment]
1) IsBlank method need to be created

2) we should not use deprecated guava methodshttp://docs.guava-libraries.googlecode.com/git/javadoc/com/google/common/base/Objects.html#firstNonNull(T,%20T)

@kaj , do you have time to finish this issue ?

**Comment by kaj** [comment]
I'll make an attempt now.

**Comment by romani** [comment]
final fix is merged.
