### ISSUE TITLE
LineLength: skip imports lines from validation

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#2433]
Raised by https://github.com/checkstyle/checkstyle/pull/2429
Long packages names and static import of long constants.

"imports" are not possible to line-wrap so LineLength should skip them from validation. Special option is not required for this, Javadoc/Xdoc should be updated.

On completion, suppression for tests should be removed.

**Comment by mkordas** [comment]
I'm on it.

**Comment by romani** [comment]
Previous implementation tried to force user to use ignorePattern for import. But default was not defined to have such suppress. It might be obvious fix would be to make ignorePattern="^import .*;$" as default value. 
But on practice it is not obvious to user why he need to be bothered with stuff that already enforced by compiler. So imports suppression is hardcoded in Check again and ignorePattern should be used only for user custom needs.

**Comment by romani** [comment]
merged.

**Comment by rnveach** [comment]
@romani I thought this would include the "package" definition by your wording? If an import is long, without the static, chances are the package line will be just as long too.

**Comment by romani** [comment]
I want to see such code :) before fix, where package is more then 100 symbols, I need to know name of this project :).

**Comment by mkordas** [comment]
I did a search over my commercial project and found packages over 120 characters long, so it happens in real word :) Here it is how it looks:
```java
package com.nameofcompany.nameofdivision.nameofproject.systemtests.parallel.areaoftest.featuretested.flowtested;
```

**Comment by romani** [comment]
ok, please create an issue on this :), no option is required , Check should skip "package".

**Comment by pablo-ml** [comment]
On the first comment, I found this:

""""imports" are not possible to line-wrap so LineLength should skip them from validation. Special option is not required for this, Javadoc/Xdoc should be updated."""

AFAIK, the JLS supports splitting the import:

```
SingleTypeImportDeclaration:
   import TypeName ;

TypeName:
  TypeIdentifier
  PackageOrTypeName . TypeIdentifier

````
So, an import production is of the form:

`import identifier . identifier . identifier .... ;`

ie: a sequence of tokens. AFAIK, whitespaces are accepted between tokens, so technically, you can write an import like this:

````
import my.package.name.
   MyClass;
````

I think that the LineLengthCheck check must be either modified back to the original behaviour, or at least add an option to check for line lengths on import and package statements.
