### ISSUE TITLE
UT to validate tokens option in Check Xdoc

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#2443]
problem was found and fixed https://github.com/checkstyle/checkstyle/commit/edd8b1222205f82f8bfa4e87b9eda9472f4811ef

We need UT to make sure we will never make another problem like this, validate getDefaultTokens and getAcceptableTokens.
We skip reference in xdoc if acceptable==default==required.

**Comment by rnveach** [comment]
I am working on this.

**Comment by rnveach** [comment]
This was added and fixed via PR #2450 .
When tokens are displayed, the list is made up of: default/acceptable tokens minus all required tokens
