### ISSUE TITLE
Unable to access samePackageMatchingDepth in CustomImportOrder

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#2453]
http://checkstyle.sourceforge.net/config_imports.html#CustomImportOrder

We document the property "samePackageMatchingDepth" but we don't have a "setter" method that the users can use.

We should create a setter, and remove the hard coded ignore in XDocsPagesTest.

**Comment by rnveach** [comment]
@romani
I will work on this.

Are we sure we want the user to be allowed to change it directly?
Now that I am looking at this closer, currently "samePackageMatchingDepth" is only set and used when the "customImportOrderRules" contains "SAME_PACKAGE". Hence the variable's name.
https://github.com/checkstyle/checkstyle/blob/eeec3dc1d23916462560403a27a4ae94260d61f3/src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/CustomImportOrderCheck.java#L748
https://github.com/checkstyle/checkstyle/blob/eeec3dc1d23916462560403a27a4ae94260d61f3/src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/CustomImportOrderCheck.java#L481
https://github.com/checkstyle/checkstyle/blob/eeec3dc1d23916462560403a27a4ae94260d61f3/src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/CustomImportOrderCheck.java#L623
All these cases have above it, "SAME_PACKAGE_RULE_GROUP" explicitly.

If we did allow the user to set this value, they would only be overriding their own value they set.
Right now we require them enter this value inside "customImportOrderRules" inside ()s.
Example:
https://github.com/checkstyle/checkstyle/blob/eeec3dc1d23916462560403a27a4ae94260d61f3/src/xdocs/config_imports.xml#L1015
`````
<property name="customImportOrderRules" value="SAME_PACKAGE(3)"/>
````

If we still want to allow them to set the property, maybe we should disable the setting of the same value inside the "customImportOrderRules"?

**Comment by romani** [comment]
this is invalid issue, such field is internal state it is setup by order property.

**Comment by rnveach** [comment]
Ok, I will set up a PR to remove it from the xdoc.

**Comment by romani** [comment]
merged.
