### ISSUE TITLE
Test more project on drone.io

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#2460]
https://cloud.drone.io/

Drone.io implemented matrix items, so we can reuse it as additional testing platform:
http://readme.drone.io/build/matrix.html

It is required to review all java projects from http://www.yegor256.com/txt/2015/award-2015.txt that use checkstyle by maven plugin or gradle plugin.
Choose candidates that enforce checkstyle in its build process and use them as we use Orekit project to catch regression - https://github.com/checkstyle/checkstyle/blob/master/.travis.yml#L63 .

Alternatively we could find usage of us by https://github.com/search?l=maven-pom&q=%22maven-checkstyle-plugin%22&type=Code&utf8=%E2%9C%93

Validation on project should NOT be very long, it is better to choose projects with interesting code style and biggest amount of Checks.

Drones launch should not be bigger then launch of Travis.
##

**Comment by Rahulkhinchi03** [comment]
I am new to drone.io and I tried to check out its website but it says that it is no longer accepting any new registrations. They recommend installing the Drone on own hardware, or you can try out the new `Harness CI Cloud` but it is paid.

**Comment by Rahulkhinchi03** [comment]
@romani @nick-mancuso @strkkk 

I am new to drone.io and I tried to check out its website but it says that it is no longer accepting any new registrations. They recommend installing the Drone on your own hardware, or you can try out the new Harness CI Cloud but it is paid.

Should I install a drone on my own GitHub and follow this information?
https://docs.drone.io/server/provider/github/

**Comment by romani** [comment]
I am closing this issue
We already use it extensively https://cloud.drone.io/checkstyle/checkstyle/10182
