### ISSUE TITLE
NullPointerException in EqualsAvoidNull Check

### ISSUE THREAD

**Issue by clausfod** [checkstyle/checkstyle#2474]
I get a NullPointerException when running EqualsAvoidCheck on this file:
```java
import java.util.EnumSet;
import java.util.HashMap;
import java.util.Map;

public enum NKKLaanType {
    KONTANT_LAAN(1),
    KONTANT_LAAN_EURO(101),
    OBLIGATIONS_LAAN(2),
    OBLIGATIONS_LAAN_EURO(201),
    OBL_MIX_LAAN(21),
    OBL_GRUNDFORBEDRINGSLAAN(22),
    OBL_STAAENDE(23),
    OBL_RENTEMAX(25),
    OBL_RENTEMAX_EURO(251),
    OBL_PAUSELAAN(26),
    OBL_PAUSELAAN_EURO(261),
    RESFL_RESERVEFONDSLAAN(3),
    RESFL_SAELGERPANTEBREVE(31),
    TILPASNINGSLAAN(4),
    TILPASNINGSLAAN_EURO(401),
    RENTE_TILPASNINGSLAAN(41),
    INDEXLAAN(5);

    private static Map<Integer, NKKLaanType> lookup = new HashMap<Integer, NKKLaanType>();

    private int code;

    static {
        for (NKKLaanType s : EnumSet.allOf(NKKLaanType.class)) {
            lookup.put(s.code, s);
        }
    }

    private NKKLaanType(int intType) {
        this.code = intType;
    }

    public static NKKLaanType get(String code) {
        return lookup.get(Integer.valueOf(code));
    }

    public static NKKLaanType get(int code) {
        return lookup.get(code);
    }

    public boolean isObligationsLaan() {
        if (NKKLaanType.OBL_GRUNDFORBEDRINGSLAAN.equals(this) || NKKLaanType.OBL_MIX_LAAN.equals(this)
            || NKKLaanType.OBL_PAUSELAAN.equals(this) || NKKLaanType.OBL_PAUSELAAN_EURO.equals(this) || NKKLaanType.OBL_RENTEMAX.equals(this)
            || NKKLaanType.OBL_RENTEMAX_EURO.equals(this) || NKKLaanType.OBL_STAAENDE.equals(this) || NKKLaanType.OBLIGATIONS_LAAN.equals(this)
            || NKKLaanType.OBLIGATIONS_LAAN_EURO.equals(this) || NKKLaanType.RESFL_SAELGERPANTEBREVE.equals(this)
            || NKKLaanType.RESFL_RESERVEFONDSLAAN.equals(this)) {
            return true;
        }
        return false;
    }

    public boolean isKontantLaan() {
        if (NKKLaanType.KONTANT_LAAN.equals(this) || NKKLaanType.KONTANT_LAAN_EURO.equals(this)) {
            return true;
        }
        return false;
    }

    public boolean isTilpasningsLaan() {
        if (NKKLaanType.RENTE_TILPASNINGSLAAN.equals(this) || NKKLaanType.TILPASNINGSLAAN.equals(this)
            || NKKLaanType.TILPASNINGSLAAN_EURO.equals(this)) {
            return true;
        }
        return false;
    }

}
```

with this checkstyle.xml

```xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Puppy Crawl//DTD Check Configuration 1.2//EN"
        "http://jee-qa/jee-qa/trunk/checkstyle/configuration_1_2.dtd">

<module name="Checker">
    <module name="TreeWalker">
        <module name="EqualsAvoidNull" />
    </module>
</module>
```

java -jar checkstyle-6.11.2-all.jar -c checkstyle_no_suppression.xml NKKLaanType.java

Exception in thread "main" java.lang.NullPointerException
        at com.puppycrawl.tools.checkstyle.checks.coding.EqualsAvoidNullCheck.ge
tFieldType(EqualsAvoidNullCheck.java:453)
        at com.puppycrawl.tools.checkstyle.checks.coding.EqualsAvoidNullCheck.is
CalledOnStringField(EqualsAvoidNullCheck.java:393)
        at com.puppycrawl.tools.checkstyle.checks.coding.EqualsAvoidNullCheck.ch
eckMethodCall(EqualsAvoidNullCheck.java:280)
        at com.puppycrawl.tools.checkstyle.checks.coding.EqualsAvoidNullCheck.tr
averseFieldFrameTree(EqualsAvoidNullCheck.java:262)
        at com.puppycrawl.tools.checkstyle.checks.coding.EqualsAvoidNullCheck.tr
averseFieldFrameTree(EqualsAvoidNullCheck.java:258)
        at com.puppycrawl.tools.checkstyle.checks.coding.EqualsAvoidNullCheck.tr
averseFieldFrameTree(EqualsAvoidNullCheck.java:258)
        at com.puppycrawl.tools.checkstyle.checks.coding.EqualsAvoidNullCheck.fi
nishTree(EqualsAvoidNullCheck.java:173)
        at com.puppycrawl.tools.checkstyle.TreeWalker.notifyEnd(TreeWalker.java:
374)
        at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:332)
        at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker
.java:203)
        at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(Abst
ractFileSetCheck.java:79)
        at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:265)
        at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:277)
        at com.puppycrawl.tools.checkstyle.Main.main(Main.java:118)

**Comment by romani** [comment]
@Vladlis , can you take look ?

**Comment by Vladlis** [comment]
@romani, I'll address PR today

**Comment by romani** [comment]
merged.
