### ISSUE TITLE
add example to DescendantToken for catching ASSIGN under EXPR token

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#2507]
http://checkstyle.sourceforge.net/config_misc.html#DescendantToken

please add example of forbidding ASSIGN at expressions. Requested at https://sourceforge.net/p/checkstyle/feature-requests/539/

```
/var/tmp $ java -jar checkstyle-6.12-SNAPSHOT-all.jar -c 3.xml   3.java
Starting audit...
/var/tmp/3.java:5:9: error: Count of 1 for 'EXPR' descendant 'ASSIGN' exceeds maximum count 0.
Audit done.
Checkstyle ends with 1 errors.

/var/tmp $ cat 3.java 
package test;

class Test {
    Inpu boo() {
    	if (a = 1) {}
    }
}

/var/tmp $ cat 3.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
    "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
    "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
  <module name="TreeWalker">
	<module name="DescendantToken">
	    <property name="tokens" value="EXPR"/>
	    <property name="limitedTokens" value="ASSIGN"/>
	    <property name="maximumNumber" value="0"/>
	</module>
  </module>
</module>
```

**Comment by MEZk** [comment]
1) Consider that we have the following code example:

```java
class Test {
    void foo() {
    boolean a = false;
    if (a = true) { } // line 4
}
```

and we want to configure DescendantToken to check we never assign something in a control statement condition. We would use the following configuration:

```xml
<module name="DescendantToken">
    <property name="tokens" value="LITERAL_IF"/>
    <property name="limitedTokens" value="ASSIGN"/>
    <property name="maximumNumber" value="0"/>
</module>
```
The fourth line will be triggered as a violation by the Check. It is OK, but the Check will also rise false positive violation on the following code example:

```java
class Test {
    void foo() {
        boolean optimistic = true;
        if(optimistic) 
        {
            message = "half full"; // violation here
        }
        else
        {
            message = "half empty"; // violation here
        }
    }
}
```

Configuring the check to check you never assign something in a control statement condition using configuration which is specified above is wrong approach.

2) Consider that we have the following code example:

````java
class Test {
  void foo() {
    Person p1 = new Person ();
    Person p2 = new Person ();
    boolean c;
    c = p1 == p2; // line 6
}
````

and we want to configure DescendantToken to check we never compare two references outside a control statement condition. We would use the following configuration:

````xml
<module name="DescendantToken">
    <property name="tokens" value="EXPR"/>
    <property name="limitedTokens" value="ASSIGN"/>
    <property name="maximumNumber" value="0"/>
</module>
````

The sixth line will be triggered as a violation by the Check, yet it is not a good idea to configure the check in a such way. EXPR token is too generic and may lead to unexpected behaviour of the Check. 

So, it is not possible to cover the issue by the Check.

@romani 
Can be closed.

**Comment by MEZk** [comment]
New check to implement (#2681)
