### ISSUE TITLE
add extra lines to checkstyle_checks.xml

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#2518]
taken from issues in #2500 

We should add fluff lines (empty lines) to each module in checkstyle_checks.xml so we have room to expand our checks with new options and comments without having to redo the XDOC each time. This will also have the added benefit of making the modules stand out more when the user clicks the link as the modules will be separated and not scrunched together.

**Comment by romani** [comment]
we will not be able completely avoid lines updates, but we will minimize it a bit. We need 2 extra lines in config for singleline Checks-tags (one line for ```</module>``` second line for one new option).

**Comment by rnveach** [comment]
I was thinking along the line of atleast 5-10 empty lines.
Some of our comments are alone 3-5 lines, and we should have space for more than one new option.

We could also require modules to start on lines divisible by 5 or 10, so we always remember to add new extra space once we fill up or go over the current space.

**Comment by romani** [comment]
if we do 5 empty lines for each - config will be unreadable.

it is a rare case when check have many option. Most of them have no options. if we put 3 empty lines one check could use all of them and even more, but we could move Check below on extra line down without updating any other Checks below.

**Comment by romani** [comment]
workaround is released as 6.12.1
