### ISSUE TITLE
organize checkstyle_checks.xml

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#2526]
Since we removed our reliance on actual line numbers in links, we can now organize checkstyle_checks.xml however we want.

We should have all Checker checks on top, TreeWalker should always be last.
Each check should be grouped by package with a comment on the package above it.
Each group of package should then ordered by check name alphabetically like we do on the "config_XXXXX.html".

**Comment by mkordas** [comment]
@rnveach, can I also reopen #2244?

**Comment by rnveach** [comment]
@mkordas" xdocs/google_style.xml" still has line links. I will be finishing this soon as part of #2519.
These changes won't go in until we release anyways, so I don't think order matters, but confirm with @romani.

**Comment by romani** [comment]
We cat make release as soon as we merged your changes.

**Comment by romani** [comment]
merged
