### ISSUE TITLE
Code review of CommentsIndentationCheck.java

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#2530]
https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/CommentsIndentationCheck.java

@MEZk ,

1) 
> private static DetailAST getDistributedPreviousStatementOfSingleLineComment(
            DetailAST comment) {

make it single return

2)
> handleSingleLineCommentInEmptyCaseBlock()
handleFallThroughtSingleLineComment()
handleSIngleLineCommentAtTheEndOfTheCodeBlock()
handleSingleLineCommentInEmptyCodeBlock()

does it make sense to move "log" to upper level call stack to consolidate "log" in one method ? that would require splitting handleSingleLineCommentInEmptyCodeBlock into two methods

**Comment by MEZk** [comment]
@romani 
Refactoring of while loop inside other while loop should be discussed. 
https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/CommentsIndentationCheck.java#L499

**Comment by romani** [comment]
yes, case is not simple. But abrupt logic is bad and hard to read.

instead return, please do clean for stack and break. That will finish both loops.

**Comment by romani** [comment]
issue is not closed, I will think more about 2nd case.

**Comment by romani** [comment]
2nd case is not possible to refactor to more encapsulated view as , handleXXXXX methods have "log(" and "logMultilineIndentation(" and at handleSIngleLineCommentAtTheEndOfTheCodeBlock method  logging have different arguments, so can not be refactored to isXXXXXXXX view.
