### ISSUE TITLE
Update Javadoc in GenericWhitespaceCheck.

### ISSUE THREAD

**Issue by maxvetrenko** [checkstyle/checkstyle#254]
Update Javadoc in Check :http://checkstyle.sourceforge.net/config_whitespace.html#GenericWhitespace
Documentation is not obvious, it can't give answers what cases are valid. For example:

<pre><code>protected List&#60;Class&#60;? extends AbstractTester&#62;&#62; getTesters() {
  return ImmutableList.&#60;Class&#60;? extends AbstractTester&#62;&#62; of();
}</code></pre>

It's difficult to understand is this case valid. Documentation says, that Generic tokens &lt; and &gt; should be correct to the <i>typical</i> convention and that's all.

**Comment by romani** [comment]
already resolved at 6.0.
