### ISSUE TITLE
Unify naming of all files with IT inputs

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#2540]
Base on #2161.

please put "Input" to the prefix or as "Suffix" for file name at https://github.com/checkstyle/checkstyle/tree/master/src/it/resources/com/google/checkstyle/test.

**Comment by rnveach** [comment]
I will work on this since I love unifying :)
Will follow test's patterns

**Comment by romani** [comment]
I appreciate your help!

**Comment by romani** [comment]
@rnveach ,

Structure of test files could be a bit weird for you and not strict and all these ITs were created by student as a side task to get under control Google style implementation. During that time I only enforced top level structure. Feel free to propose any improvement.

please rename "rule333orderingandsoacing" to ".......spacing"
"toolongpackagetotestcoveragegooglesjavastylerool" --> ".....rule"

**Comment by rnveach** [comment]
I will look over it a little closer after I finish renaming the files.

> Please rename files to be different by name, each Check-Rule should have independent file Input.

ok.

**Comment by rnveach** [comment]
@romani 
I think this issue is done, unless you see something else.
