### ISSUE TITLE
Remove usage of System.out.println in IT resources

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#2541]
triggered by https://github.com/checkstyle/checkstyle/issues/2161#issuecomment-147886384

All usages of "System.out.println" should be removed and substituted with any other dummy code.
List of excludes https://github.com/checkstyle/checkstyle/blob/master/pom.xml#L897 should be minimized

**Comment by romani** [comment]
work to be done , is to remove lines:
```
          <!-- Tests related -->
          <exclude>**/Input*</exclude>
```
Input files could use any other methods.

**Comment by MEZk** [comment]
Postponed till https://github.com/policeman-tools/forbidden-apis/issues/108

**Comment by MEZk** [comment]
All forbidden-apis violations were fixed. InputAnnotationLocation4 was excluded from validation.
