### ISSUE TITLE
new Check: RegexpOnFilename

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#2546]
Copied from https://github.com/sevntu-checkstyle/sevntu.checkstyle/issues/256

This check applies a given regular expression to the names of files. Depending on the configuration, a warning is logged if a required match is not found, or if an illegal match is found.
This is useful for situations such as:
Checking that resources in certain directories follow a naming convention
Resource file names contain only legal characters
Files of certain types are created in the right places, e.g. Java files under src/*/java
Prevent certain files or types of files altogether, by "banning" their names
By default, this check flags leading and trailing spaces in file names.

targetFolderPattern - regular expression that will be applied to canonical folder location of the file. It does not contains filename, only folder/directory.
fileNamePattern - regular expression that will be applied to filename (with extension).
match - boolean option. TRUE - report matching of files by Paterns (message regexp.filepath.match will be used) , FALSE - report all mismatching of files by Paterns (message regexp.filepath.mismatch will be used)
````
<module name="RegexpOnFilename">
  <property name="targetFolderPattern" value="[\\/]src[\\/](?:test|main)[\\/]java[\\/]"/>
  <property name="fileNamePattern" value="*.java"/>
  <property name="match" value="false"/>
  <message key="regexp.filepath.mismatch" value="The Java file ''{0}'' must reside in a Java source folder."/>
</module>

<module name="RegexpOnFilename">
  <property name="targetFolderPattern" value="[\\/]src[\\/]main[\\/]resources[\\/]html[\\/]views[\\/]"/>
  <property name="fileNamePattern" value="^view_.*"/>
  <property name="match" value="true"/>
  <message key="regexp.filepath.match" value="Name of ''{0}'' must start with ''view_''."/>
</module>

<module name="RegexpOnFilename">
  <property name="fileNamePattern" value="*.gif"/>
  <message key="regexp.filepath.match" value="''{0}'' must be in PNG format, not GIF."/>
</module>
````

**Comment by romani** [comment]
Discussion for implementation details was in #2547 

Checks is merged.
