### ISSUE TITLE
Remove parameters validation from LocalVariableName

### ISSUE THREAD

**Issue by MEZk** [checkstyle/checkstyle#2549]
@romani 
1) LocalVariableName should not validate catch parameters because we already have ParameterName check to check both method and catch parameters. PARAMETER_DEF token should be removed from default and acceptable token sets of LocalVariableName. According to check's name, LocalVariableName should validate only variables, not parameters.
2) We need to update xdoc and javadoc.

Example of not appropriate behaviour:

Test.java:
````java
public class InputOverrideAnnotation {
    public void foo() {
        try {}
        catch (Exception ex) {}
    }
}
````

my_check.xml:
````xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">


<module name = "Checker">
    <property name="charset" value="UTF-8"/>

    <property name="severity" value="warning"/>
    
    <module name="TreeWalker">
         <module name="LocalVariableName">
	    <property name="format" value="^ABC$"/>
	</module>
    </module>
</module>
````

Result of checkstyle execution:

````
andreiselkin@andreiselkin ~/Downloads/temp $ java -jar checkstyle-6.12.1-all.jar -c my_check.xml Test.java

Starting audit...

/home/andreiselkin/Downloads/temp/Test.java:4:26: warning: Name 'ex' must match pattern '^ABC$'.

Audit done.
````

**Comment by mkordas** [comment]
There's nothing about catch parameters in [PackageName](http://checkstyle.sourceforge.net/config_naming.html#PackageName) docs, so probably it should be updated too.

**Comment by romani** [comment]
@mkordas,  I do not understand your comment, please extend it or fix a typo.

**Comment by mkordas** [comment]
@romani
It relates to first sentence from issue description.

**Comment by romani** [comment]
there is "ParameterName" not a "PackageName", I still do not understand. I might be blind , please point me to a problem.

**Comment by MEZk** [comment]
@romani 
I got it. He meant ParameterName. There's nothing about catch parameters names in ParameterName.

I added only example for the option 'skipCatchParameter'
https://github.com/checkstyle/checkstyle/commit/176301250bfd2063f405fed4a960064e0a3e0230#diff-e10391ace65380d053fcf5809489a995R927

So, we should also update description section for ParameterName
http://checkstyle.sourceforge.net/config_naming.html#ParameterName
 but as a separate 'doc' comment.

**Comment by mkordas** [comment]
@romani @MEZk you are right, I meant ParameterName. That's how things end up when you type comments from phone :)

**Comment by MEZk** [comment]
@romani @mkordas 
Is there any reason to validate catch parameters in LocalFinalVariableCheck? We even do not have proper UTs or ITs to check how the check works while validating catch blocks.

**Comment by mkordas** [comment]
@MEZk 
In [Oracle docs](http://docs.oracle.com/javase/7/docs/technotes/guides/language/catch-multiple.html) they use name "catch parameters", so local variable check should not validate them. It should be done either by ParameterName check or better by new CatchParameterName check. @romani, what do you think? I believe it may happen that people want different pattern just for these variables like allowing `e` or `ex`, while demanding for all other method parameters to be at least 3 characters long.

**Comment by romani** [comment]
in my experience with these Checks, I did allowance to all parameters to be 2chars https://github.com/checkstyle/checkstyle/blob/master/config/checkstyle_checks.xml#L334 because of catch-parameters and name "id" that is used a lot in sources around the world. 

But some projects could be more demanding for names and verbose and have regexp like "^(id)|([a-z][a-zA-Z0-9]+)$" ...... may be we also have to do this :)

As I already did a a comment in PR, I would rather avoid new option in ParameterName till user request. If user request this, I think it if reasonable to make it and update documentation to show how user can configure two Checks and control Catch parameter name like "^(ex)|(ignore)|(expected)$".

:) and right now I see that I already persuaded myself that such option is required and described good usage of it :).

@MEZk , if after my comment you also see a reason for this , lets do new option this by separate issue and lets implement it right now.

**Comment by MEZk** [comment]
@romani 
>I would rather avoid new option in ParameterName till user request

I agree.
Lets update documentation for ParameterName to point user how to write regexp to allow two ore more symbols parameter names and disallow one character names.

**Comment by romani** [comment]
To make final decision - please share your opinion at #2616 .

**Comment by romani** [comment]
merged.

**Comment by dpalic** [comment]
I am using the now removed PARAMETER_DEF in some checks after my developer upgraded to the latest version checkstyle is failing totally.
What is the suggestion now to enforce a specific exception catchblock variable/parameter naming?

**Comment by MEZk** [comment]
@dpalic 

Please, use new CatchParameterNameCheck and ParameterNameCheck for your project.
See documentation 
http://checkstyle.sourceforge.net/config_naming.html#CatchParameterName
http://checkstyle.sourceforge.net/config_naming.html#ParameterName

**Comment by dpalic** [comment]
MEZk, big thx for the quick answer and help!
