### ISSUE TITLE
UT to validate google/sun style xdocs

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#2557]
Renaming package names from #2556 made links in the style documentation invalid since they weren't updated.
Some links for "config" are invalid from #2519 because they have "Check" in their name and we don't write "Check" in our configuration files.
Some check names displayed end with "Check", others don't. Same with test classes, some have "Check" others don't.
Some tests have 2 checks combined into one, while others have them separated.

**Comment by romani** [comment]
@rnveach , are done with this issue ?

**Comment by rnveach** [comment]
@romani yes, I believe so.
