### ISSUE TITLE
[Google|Android] Test Method Naming Conventions

### ISSUE THREAD

**Issue by robertwhitebit** [checkstyle/checkstyle#2580]
Currently you can only specify a single format for all method names in your project.

However, Android suggests to use  _ (underscore) in test method names [1]. So it would be awesome to specify different formats for the production and test code.

Maybe a more flexible approach should be implemented? So you can limit checks to folders/files. This would effect all checks of course.

[1] http://source.android.com/source/code-style.html#follow-test-method-naming-conventions

**Comment by romani** [comment]
no way to limit validaton to certain folder.

You can make two configurations for the same Check and do suppressions by Check ID in folders that you do not want.

Not related , but just FYI: in our code we also had such "_" in test, but after some time we just removed "_" and nobody of contributors notice anything,no damage to name happen.

**Comment by robertwhitebit** [comment]
> You can make two configurations for the same Check and do suppressions by Check ID in folders that you do not want.

Oh, thanks a lot! :bow: I somehow missed that completely. :disappointed: -> closed

> Not related , but just FYI: in our code we also had such "\_" in test, but after some time we just removed "\_" and nobody of contributors notice anything,no damage to name happen.

I think I will drop the plan to use underscore for tests for now and will  pick it up again if its getting a problem. Thanks for sharing your experience.
