### ISSUE TITLE
Ignoring selected checks in test code?

### ISSUE THREAD

**Issue by ThrawnCA** [checkstyle/checkstyle#2584]
When using Checkstyle via the Maven plugin, is there an efficient way to apply certain checks to all main code, but ignore them for tests?

For example, 'magic' numbers are common in unit tests (eg making assertions about the size of a returned list and the element at each index). Catching generic exceptions is typically appropriate in tests, too.

**Comment by rnveach** [comment]
@ThrawnCA 
You can always suppress CS violations for specific folders or files for any reason your project wishes, like unit code.

Here is an example of CS' suppression of Magic Numbers on test code.
https://github.com/checkstyle/checkstyle/blob/ffaf99ed9905b6df24bdeb770bfee43066db7b75/config/suppressions.xml#L49

Here is how to configure suppressions.
http://checkstyle.sourceforge.net/config_filters.html#SuppressionFilter

**Comment by romani** [comment]
I think question is fully answered, I am closing the issue
