### ISSUE TITLE
Tests for validating commit message should not allow period at the end of commit message

### ISSUE THREAD

**Issue by MEZk** [checkstyle/checkstyle#2590]
@romani, @liscju
Tests for validating commit message which were implemented in scope of https://github.com/checkstyle/checkstyle/pull/1518 skip period at the end of commit message.

Example: https://github.com/checkstyle/checkstyle/commit/17eaaa5a0aec1943cf0f2c59a95e81fa72b740c1

It leads to a problem for future release notes xdoc generator: some commits messages can have period at the end and other cannot. It is not a big problem, yet we should follow the rules which were suggested in https://github.com/checkstyle/checkstyle/pull/1518.

@liscju 
FYI: we have the following regexp to validate commit message: "^(minor|config|infra|doc|spelling): .*$";

Dot (.) matches any character (except newline).
Proof: https://regex101.com/

**Comment by rnveach** [comment]
@MEZk yes, I saw this validation when I started with my first commit.
I will start putting periods at the end of my commits.

**Comment by MEZk** [comment]
@rnveach 
Sorry, I thought you were the author of the test. My mistake. 
Please, do not put period at the end of the commit message. It is not allowed as discussed in #1518.

**Comment by mkordas** [comment]
@rnveach
Dots at the end of commit messages should be prohibited. Please see [How to Write a Git Commit Message - point 4](http://chris.beams.io/posts/git-commit/#end):
> Do not end the subject line with a period

There are more rules to follow in this article like
>Capitalize the subject line
Use the imperative mood in the subject line

First can be easily automated by requiring capital letter after `Issue #XXX: `. Second one can be implemented as a check that first word doesn't end with "ed" or "ing". If someone really wanted we could also prohibit [these](https://en.wikipedia.org/wiki/List_of_English_irregular_verbs) as first word of commit message.

**Comment by rnveach** [comment]
@MEZk ok sorry for my added confusion, I thought the issue was implying we need the periods

**Comment by romani** [comment]
I am ok to remove this from regexp.

**Comment by MEZk** [comment]
@romani 
New regexp should be **^(minor|config|infra|doc|spelling): .[^\.]*$** for minor, config, infra, doc, or spelling.
[^\.] match a single character not present in the list below.

**^Issue #\\d*: .[^\\.]*$** is for issue massages.
**^Pull #\\d*: .[^\\.]*$** is for pull request messages.

I've checked them with https://regex101.com/

**Comment by romani** [comment]
Please send PR
