### ISSUE TITLE
WhitespaceAround should have an allowEmptyLambda parameter

### ISSUE THREAD

**Issue by DidierLoiseau** [checkstyle/checkstyle#2603]
Consider the following code:

    Runnable noop = () -> {};

With the `LCURLY` and `RCURLY` parameters of [`WhitespaceAround`](http://checkstyle.sourceforge.net/config_whitespace.html#WhitespaceAround), it does not seem possible to configure it to accept this construct if there is no space between the curly brackets.

It thus seems that an `allowEmptyLambda` parameter would be useful, as there is already for constructors, methods etc.

**Comment by romani** [comment]
default value should be FALSE, to be consistent with "allowEmptyMethods" and "allowEmptyTypes"

**Comment by DidierLoiseau** [comment]
I feel like the convention is not to put a space but that seems difficult to attest. Nevertheless, consistency with the other parameters might be more important.
