### ISSUE TITLE
Refactor gui package

### ISSUE THREAD

**Issue by sabaka** [checkstyle/checkstyle#2609]
I don't like current code. Let's try to do it more close to MVC.
I'm going to add some proposals soon.

**Comment by sabaka** [comment]
Ok, lets dig deeper.
1) I don't like the way how we start our gui. As I know good practice is main window object inherits JFrame, but we create some Runnable object and create frame inside. More over, we have strange dependencies with our frame. (Main creates frame, frame creates panel and panel asks main for frame)
2) We have logic mixed with gui. I prefer simple and stupid GUI class and model with logic.
3) We have AbstractTableTreeModel and only one child. I doubt we are going to have more then one AST tree in gui. I propose drop it. Same for TreeTableModel interface.
4) CodeSelector. It seems to me, that it doesn't work. Anyway, I can't remember anything like this in GUI behaviour. (It supposed to select code, when you select AST node). It's useful, I agree, but it doesn't work. :)

There are enough to start, as for me.

**Comment by romani** [comment]
Need to addressed:
CodeSelector is working by pressing Enter key on nodes . without pre-selection it do work but disappear rightaway (not clear for now why) it could be seen by simultaneous pressing of ENTER several times, selection are blinking.

**Comment by romani** [comment]
1) please rename CheckstyleFrameModel.java, no need to have "Checkstyle" in name.

2) did you finish this issue ? What else is left to do ?

**Comment by Vladlis** [comment]
2) I guess so, at least the points mentioned before. We can ask @sabaka , if there is smth left.

**Comment by romani** [comment]
All classes that have imports if swing or awt should as simple as possible. No conditions no data preparations, no decision points. This is not achievable to do completely but we should move decision points as much as possible to simplify testing of such gui classes and keep all decisions in POJO classes that are easy to tests by UTs.
please read: http://martinfowler.com/eaaDev/PresentationModel.html

Items that still need to be changed:

0)
> Additionally we need to update UI to let use know that we have CodeSelector : by context menu, by doble-click, by ......

need to be fixed, to be more obvious for new developers. 
most likely we need to change http://checkstyle.sourceforge.net/writingchecks.html#The_Checkstyle_SDK_Gui to show that selection could be done from tree, no need to make selection yourself.

1)
> CodeSelector

Need to have CodeSelectorPmodel class with all non GUI logic , it will be tiny but it is required to simplify GUI.

2)
> ListToTreeSelectionModelWrapper
> private ListSelectionListener createListSelectionListener()

remove this method. removing ListSelectionHandler class is also ok, its implementation could be anonymous class .

3)
> ListToTreeSelectionModelWrapper
> private void updateSelectedPathsFromSelectedRows()

this method is strange. Can we move smth in Pmodel

4)
> ParseTreeTableModel

all decision points should be delegated to non swing dependent class - ParseTreeTablePmodel

5)
> MainFrame

all decision points should be delegated to non swing dependent class - MainFrameModel
For any data generation/formatting, it should ask MainFrameModel to do a job.

6)
> Main

please make title as "Checkstyle GUI", the same update is required at MainFrame. Image at http://checkstyle.sourceforge.net/writingchecks.html#The_Checkstyle_SDK_Gui need to be updated.

**Comment by romani** [comment]
7)
> if (sourceFile != null) {

All decision point should be in Model and be ready to be covered by UTs.

**Comment by Vladlis** [comment]
@romani 
Points 0) - 2) and 4) - 7) are done.
About 3) - not sure that we should split the class, as it will become more complex and ugly.

**Comment by romani** [comment]
ok, I am agree.

I am marking issue as fixed.
Thanks a lot for refactoring!
