### ISSUE TITLE
refactor internal tests

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#2625]
I wish to refactor the tests that test CS' internal configurations and xdoc files.

I plan to move XDocsPagesTest and AllChecksTest in their own folder, 'internal'. They test more the resources and internal files of CS, instead of testing direct functionality.

Both files use similar utility methods (Ex: `getCheckStyleChecksReferencedInConfig`), and have so many that they are starting to flood the test files. I plan to separate the utilities out into their standalone classes.

I plan to move xdoc tests from AllChecksTest to XDocsPagesTest (Ex: `testAllCheckstyleModulesHaveXdocDocumentation`) since they belong more with validating the xdocs.

Some methods are named 'test*' but don't have the test annotation. They should be called 'validate *' or something proper.

**Comment by mkordas** [comment]
+1

**Comment by romani** [comment]
discussion of the update is at https://github.com/checkstyle/checkstyle/pull/2662
