### ISSUE TITLE
Performance issue in UnusedImportsCheck

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#2631]
Significant amount of time is taken by pattern compilation while analysing Javadoc:
![image](https://cloud.githubusercontent.com/assets/5467276/11285089/0be76cc6-8f0e-11e5-9901-e8853d320bc7.png)
Check could be made faster by compiling patterns used in `JavadocUtils` only once.

**Comment by romani** [comment]
@mkordas , what tool did you use ?

**Comment by mkordas** [comment]
@romani Simplest tool available with every JDK - VisualVM
