### ISSUE TITLE
False negative on brace spacing when using double braces for static collection instantiation

### ISSUE THREAD

**Issue by mcandre** [checkstyle/checkstyle#2684]
Could there be an update to checkstyle's knowledge of Java syntax?

Double curly braces (`{{ ... }}`) are valid Java syntax for statically instantiating collections, but checkstyle falsely reports styling errors about each brace pair being together.
##

**Comment by romani** [comment]
http://checkstyle.sourceforge.net/report_issue.html

**Comment by mcandre** [comment]
Bruh.

**Comment by romani** [comment]
we need to know what config you have, all Checks are highly configurable. What version of checkstyle  do you use ?
Clearly described problem usually get solution quickly.

**Comment by romani** [comment]
@mcandre , if no details provided in 2 weeks, issue will be closed.

**Comment by MEZk** [comment]
@romani 
check this out

**Comment by romani** [comment]
issue is incomplete, closed.
