### ISSUE TITLE
FallThroughCheck generates false positive on loop label in switch statement

### ISSUE THREAD

**Issue by archiecobbs** [checkstyle/checkstyle#2687]
`FallThroughCheck` generates a false positive on code like this:

    switch (x) {
    case 1:
        this.foo();
        break;
    default:
    loop:              // FallThroughCheck triggers here
        for (int i = 0; i < x; i++) {
            if (array[i] == null)
                break loop;
        }
        this.bar(array);
        break;
    }

The problem is that it thinks `loop:` is a switch case instead of a loop label.

Instead, it should only detect a switch case for content matching either `case ...:` or `default:`.

**Comment by romani** [comment]
please do report as requested http://checkstyle.sourceforge.net/report_issue.html to speed process

**Comment by archiecobbs** [comment]
Nevermind, can't reproduce it in latest version. Sorry for the noise.
