### ISSUE TITLE
SDK GUI not expanding nodes

### ISSUE THREAD

**Issue by richardSch** [checkstyle/checkstyle#2689]
The SDK GUI does not allow expanding class OBJBLOCK nodes; the last version I can see working is 6.9. For example, the following code does not expand the class node:

public class XX {
    void x() {
    }
}

**Comment by romani** [comment]
woks fine for me, please read http://checkstyle.sourceforge.net/report_issue.html#How_to_report_a_bug
please make a screenshot, provide OS , ... give more details

**Comment by romani** [comment]
@richardSch , if no details provided, issue will be closed in 2 weeks.
