### ISSUE TITLE
CheckStyles throws in warning that parameters must be final while using Java 8 

### ISSUE THREAD

**Issue by Nikki1993** [checkstyle/checkstyle#2698]
But in Java 8 they are implicitly final so the warning is not really necessary or am I missing something?

For instance public void start(Stage stage) would throw a warning but
public void start(final Stage stage) wouldn't. In Java 8 however, they are implicitly final. 

I am still new to java, so sorry if I missed the point of the check.

**Comment by romani** [comment]
first of all issue need to be reported as  http://checkstyle.sourceforge.net/report_issue.html

most likely you think about http://checkstyle.sourceforge.net/config_misc.html#FinalParameters , so this Check existed far before java8 and it check to `explicit` "final". 
Some people like to place `final` explicitly to be sure that this variable is not changed, while reading the code.

If you do not like this style - just do not use this Check and remove it from configuration.
