### ISSUE TITLE
No explanation of what is metadata tag on checkstyle config

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#2726]
Example: 
`<metadata name="com.atlas-sw.eclipse" value="I like Sydney"/>`
https://github.com/checkstyle/checkstyle/blob/master/config/checkstyle_checks.xml#L15

1) metadata should be described at http://checkstyle.sourceforge.net/config.html 
2) metadata in our config should get smth meaningful.

Some original idea was to let other tools to store in config file their own content without requesting to change a checkstyle format. One example is to store a "name of config" (field of eclipse-cs) for eclipse-cs plugin - https://sourceforge.net/p/eclipse-cs/feature-requests/160/.
##

**Comment by rnveach** [comment]
Addition of metadata in config and reason can be found in this commit
https://github.com/checkstyle/checkstyle/blob/f09c190dff9530b6b47ec14b3ac6d2162ba77b26/src/checkstyle/com/puppycrawl/tools/checkstyle/configuration_1_1.dtd#L21-L29

**Comment by romani** [comment]
Yes, there is many years issue in Eclipse-cs (I opened it) to reuse such feature to store all Eclipse-cs metadata for config and sharing config in git easier.

@Bananeweizen, as we update xdoc, can you do some move in Eclipse-cs ?

**Comment by romani** [comment]
fix is merged.
