### ISSUE TITLE
Setup Codeship CI to run checkstyle-tester project on JDK sources

### ISSUE THREAD

**Issue by Vladlis** [checkstyle/checkstyle#2727]
https://codeship.com/documentation/docker-integration/java/

We need to setup 3-4-N sub-builds(matrix elements) in CI to test JDK sources by checkstyle-tester in groups to let each launch finish in 15min (or level of Codeship).
We need to make sure that Codeship has the same integration with Github to notify us on any failures (ERROR level).

That will let us avoid problems like - #1109 (comment) ,

We already did that in Travis, the only missed point is testing over JDK. Sources of JDK are huge so we need to find a way to split them in chunks and do the testing part by part.

Note: due to java grammar problem we can not use jdk8-9 , we can parse only jdk7. For details please see all issues with "ANTLR" label.

**Comment by romani** [comment]
Codeship could do ParallelCI builds only for Docker-based configuration, that is not free for opensource.

Web UI configuration does not allow us to do anything other than 'mvn -B test' - https://codeship.com/projects/124310/configure_tests

Jan 6th 2016:
>Hi Roman,
We do not offer a "Free-Plan" option for our Docker-based infrastructure post trial at this time.
We will explore the ability to help open-source projects in the future with our Docker-based platform.
Tanner Maguire
Account Executive, Codeship, Inc.

**Comment by romani** [comment]
one stage of Travis was moved to Codeship.

**Comment by romani** [comment]
codeship is used to do validattion by linkcheck maven plugin:
configure command:
`jdk_switcher use oraclejdk8`

Test command:
```
# "grep ... | cat" is required command is running in "set -e" mode and grep could return exit code 1 if nothing is matching
uname -a && mvn --version && mvn clean site -Dcheckstyle.ant.skip=true -DskipTests -DskipITs -Dpmd.skip=true -Dfindbugs.skip=true -Dcobertura.skip=true -Dcheckstyle.skip=true && echo "------------ grep of linkcheck.html--BEGIN" && grep externalLink target/site/linkcheck.html | cat && echo "------------ grep of linkcheck.html--END" && RESULT=$(grep externalLink target/site/linkcheck.html | grep -v 'Read timed out' | wc -l) && echo 'Exit code:'$RESULT && if [[ $RESULT != 0 ]]; then false; fi
```
