### ISSUE TITLE
Probable typo in com.puppycrawl.tools.checkstyle.checks.blocks.RightCurlyCheck

### ISSUE THREAD

**Issue by daytonwilliams-okta** [checkstyle/checkstyle#2762]
The following code produces what seems to be an incorrect error message:

    public boolean doesParamCountMatch(String funcName, int paramCount) {
        if (!PARAM_COUNT.containsKey(funcName)) {
            return false;
        }

        if (funcName.equals("now")) { return (paramCount <= 2); }
        else { return PARAM_COUNT.get(funcName).equals(paramCount); }
    }

The message produced claims that 'Error: '}' should be on the same line.' about the 3rd-to-last line.  This is highly dubious, since a) it IS on the same line, and b) clearly it ought to be complaining that the } should be on a separate line.

**Comment by daytonwilliams-okta** [comment]
Unfortunately, I don't know what version of checkstyle our build tools are using (I don't have direct access to them).

**Comment by romani** [comment]
Please follow http://checkstyle.sourceforge.net/report_issue.html#How_to_report_a_bug

**Comment by MEZk** [comment]
@daytonwilliams-okta 
Please check documentation. See http://checkstyle.sourceforge.net/property_types.html#rcurly

>The brace should be on the same line as the next part of a multi-block statement (one that directly contains multiple blocks: if/else-if/else or try/catch/finally). 

@romani 
We discussed the brace policy for the check last summer. The behaviour of the SAME brace policy is confusing if you don't read documentation.

**Comment by romani** [comment]
@daytonwilliams-okta and @MEZk  is it a reason to update Check message ? to bee long but clear.

**Comment by MEZk** [comment]
@romani 
Yes, message should be updated. Longer but clear is better then confusing.

**Comment by romani** [comment]
what is your proposal ? how new message should looks like ?

**Comment by MEZk** [comment]
@romani 
My proposal is to use the message from xdoc (we took it from Google's style guide):

>The brace should be on the same line as the next part of a multi-block statement (one that directly contains multiple blocks: if/else-if/else or try/catch/finally).

**Comment by romani** [comment]
I am ok with proposal. We should not forget to update all other languages.

**Comment by romani** [comment]
fix is merged.
