### ISSUE TITLE
Indentation: throwsIndent should configure indentation of `throws` on next line

### ISSUE THREAD

**Issue by maikelsteneker** [checkstyle/checkstyle#2763]
This is a PR based on issue #1272. This feature was previously implemented for issue #63. Other information can be found at http://sourceforge.net/p/checkstyle/feature-requests/294/ (already applied by https://github.com/checkstyle/checkstyle/pull/80).

The intention of this feature is to separately configure the indentation of the throws keyword for a method definition when it appears on the next line.

Such a definition looks like this: `void myMethod() throws Exception {`
When `throws Exception` appears on the next line, it is currently required to be at the same indentation as the declaration on the line above. Some styles would choose to indent this next line one level further. The intent is that if `throwsIndent` is set, this is the expected indentation for this second line.

I originally implemented this feature and published my work on GitHub. This was before CheckStyle moved to GitHub, so this was a copy of the project instead of a fork. @ksclarke worked on integrating this work on CheckStyle 5.7 and providing test cases for it. I currently do not have the time to reimplement this feature, but I hope this information will help.

**Comment by rnveach** [comment]
The property `throwsIndent` is not used anywhere in indentation check at this time.

It was added in https://github.com/checkstyle/checkstyle/commit/1ff166e1b64ddf40bd9f9cbd9834b8905f77fd94 with the method `MethodDefHandler.checkThrows`.
It was then removed in https://github.com/checkstyle/checkstyle/commit/e3a48d1527341456a798c3f0c1986de6898a8c60 for currently unknown reason.

I will work on restoring this.

**Comment by rnveach** [comment]
As agreed, here is description of auto formatters for throws indentation.

Showcase of issue:
````
$ cat TestClass.java
public abstract class Test { //indent:0
 public void m1() throws Exception { //indent:1 line:2
 } //indent:1
 public void m2() throws //indent:1 line:4
Exception { //indent:0 line:5
 } //indent:1
 public void m3() throws Exception, //indent:1 line:7
NullPointerException { //indent:0 line:8
 } //indent:1
 public void m4() //indent:1 line:10
throws Exception { //indent:0 line:11
 } //indent:1
 public abstract void m5() //indent:1 line:13
throws Exception; //indent:0 line:14
 public void m6() //indent:1 line:15
throws //indent:0 line:16
Exception { //indent:0 line:17
 } //indent:1
 public void m7() //indent:1 line:19
throws //indent:0 line:20
Exception, //indent:0 line:21
NullPointerException { //indent:0 line:22
 } //indent:1
 public void //indent:1 line:24
    m8() //indent:4 line:25
throws //indent:0 line:26
Exception, //indent:0 line:27
NullPointerException { //indent:0 line:28
 } //indent:1
}

$ cat TestConfig.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>

    <module name="TreeWalker">
        <module name="Indentation">
            <property name="basicOffset" value="1"/>
            <property name="lineWrappingIndentation" value="3"/>
            <property name="throwsIndent" value="5"/>
        </module>
    </module>
</module>

$ java -jar checkstyle-6.15-all.jar -c TestConfig.xml TestClass.java
Starting audit...
Audit done.
````

**Default Auto Formatters**:
**IntelliJ**: All line wrapped throw lines are indented +8, regardless if the throws starts on the same line as method or on the next.
Similar to Eclipse but spaces instead of indents.

**Eclipse**: All line wrapped throw lines are indented +8, regardless if the throws starts on the same line as method or on the next.
````
	public void // indent:1 line:24
	m8() // indent:4 line:25
			throws // indent:0 line:26
			Exception, // indent:0 line:27
			NullPointerException { // indent:0 line:28
	} // indent:1
````

**NetBeans**: All line wrapped throw lines are indented +8, regardless if the throws starts on the same line as method or on the next.
One difference between the others is `m8`, the `throws` line is on the same indent as the method name, which is +8.
````
    public void //indent:1 line:24
            m8() //indent:4 line:25
            throws //indent:0 line:26
            Exception, //indent:0 line:27
            NullPointerException { //indent:0 line:28
    } //indent:1
````

**Comment by romani** [comment]
http://checkstyle.sourceforge.net/config_misc.html#Indentation

that is really weird why we do have option `throwsIndent` and it does not work at all - should be fixed.

I would prefer to follow behavior of IDEs to indent "throws" by special indentation, and have all following wrapping of Exception names to be indented by `throwsIndent`

`throwsIndent=4` :
```
public void m1() throws Exception { //indent:0 -
} //indent:0

public void m1() // indent:0
    throws Exception { //indent:4 -
} //indent:0

public void m1() // indent:0
    throws //indent:4 -
    Exception { //indent:4 -
} //indent:0

public void m1() // indent:0
    throws //indent:4 -
    Exception,  //indent:4 -
    Exception2 { //indent:4 -
} //indent:0


public void m1() // indent:0
        throws Exception { //indent:8 - violation!!!
} //indent:0

public void m1() // indent:0
    throws //indent:4 -
        Exception { //indent:8 - violation!!!
} //indent:0

public void m1() throws // indent:0
        Exception { //indent:8 - violation!!!
} //indent:0

public void m1() // indent:0
    throws //indent:4 -
    Exception,  //indent:4 -
        Exception2 { //indent:8 - violation!!!
} //indent:0



```

**Comment by romani** [comment]
fix is merged
