### ISSUE TITLE
Nesting Checks in each other in config does not produce any error

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#2773]
All Checks should be placed under TreeWalker in config. If by mistake you place one Check config inside another Check no error is happen and Check just ignored

**Comment by rnveach** [comment]
This also happens for AbstractFileSetCheck, like when you place one RegexpSinglelineCheck inside another RegexpSinglelineCheck.

**Comment by romani** [comment]
Issue require more consideration and thought to minimize braking compatibility. Discussion will be at #2846

**Comment by romani** [comment]
fix is merged.
