### ISSUE TITLE
site: make a link to google_checks.xml versioned

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#2777]
page: http://checkstyle.sourceforge.net/google_style.html

link https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/google_checks.xml is directed to latest version but not latest released version that cause problem as new Check could be introduced not not released yet

link should be https://github.com/checkstyle/checkstyle/blob/checkstyle-6.13/src/main/resources/google_checks.xml, master ==> checkstyle-X.XX
##

**Comment by MEZk** [comment]
@romani 
Please, close this issue in favor of https://github.com/checkstyle/checkstyle/issues/3760

**Comment by rnveach** [comment]
Closing

**Comment by romani** [comment]
it would be better to close new issue, as it has no details of what to change.

**Comment by rnveach** [comment]
I moved missing pieces to first description of new issue
