### ISSUE TITLE
StringIndexOutOfBoundsException in getCheckShortName method of AuditEventDefaultFormatter

### ISSUE THREAD

**Issue by MEZk** [checkstyle/checkstyle#2780]
```getCheckShortName``` method of ```AuditEventDefaultFormatter``` throws StringIndexOutOfBoundsException if the name of the check does not end with ```Check```.

In Checkstyle main project we have name convention for checks names: XXXXCheck (each check module should end with ```Check```), yet it is not a rule for Checkstyle extensions. Each developer may name check modules the way he wants. In current implementation of ```getCheckShortName``` it will result in StringIndexOutOfBoundsException. We should be friendly to other tools and extensions and allow different name conventions for checks modules.

Example: https://travis-ci.org/sevntu-checkstyle/checkstyle-samples/jobs/99134853

**Comment by romani** [comment]
fix is merged.
