### ISSUE TITLE
Config of Google Style does not include InterfaceTypeParameterName check

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#2792]
Check `InterfaceTypeParameterName` should be enabled in Google Style config and properly tested/documented as `MethodTypeParameterName` and `ClassTypeParameterName` currently are.

**Comment by romani** [comment]
Please quote line in style guide that we miss, to atach that line to check at http://checkstyle.sourceforge.net/google_style.html

**Comment by mkordas** [comment]
@romani It is http://checkstyle.sourceforge.net/reports/google-java-style.html#s5.2.8-type-variable-names applied for interfaces.

**Comment by romani** [comment]
you are right!

**Comment by romani** [comment]
merged.
