### ISSUE TITLE
Support LITERAL_SYNCHRONIZED token for NoWhitespaceAfter Rule

### ISSUE THREAD

**Issue by elingg** [checkstyle/checkstyle#2803]
I would like to create a rule to make sure there is no space before the left param for synchronized, i.e. I would like to have the style `synchronized(this)` instead of `synchronized (this)` as this is common syntax. Adding the LITERAL_SYNCHRONIZED token to NoWhitespaceAfter(http://checkstyle.sourceforge.net/config_whitespace.html#NoWhitespaceAfter) would address this issue. 

Problem is in set of Allowed tokens - https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceAfterCheck.java#L102

See the discussion on the mailing list here, https://groups.google.com/forum/#!topic/checkstyle/cgNOY2uJDAY.
##

**Comment by romani** [comment]
here https://github.com/checkstyle/checkstyle/commit/aa1032931c3bcb327e77c5d21f63f48a27e947a5 Check was allowed to have any token validation (2002 year).

list of strict token set is restored at https://github.com/checkstyle/checkstyle/commit/103a2068a8c9e56d0202a37cfa198bca6cdc4bab (2006 year)

so we did not change it recently ... that is good.
Still not clear why this Check have limitation of AllowedTokens at all. We need to investigate how much harm there would be to allow user define any token.

**Comment by mkordas** [comment]
@romani I would suggest just providing test case for each token. I imagine that there might me some tokens where this issue does not make sense, like e.g `SLIST`... So we should extend that list but in reasonable way.

**Comment by romani** [comment]
@mkordas , the reason of AllowedTokens collection is to restrict user from usage token that will break Check logic and cause him to throw Exceptions or produce false-positives.
This set does not have intend to limit user to be crazy and configure Check to demand from code weird style - it is problems of user , Checkstyle just follow instructions from configuration.

In short: misconfiguration is problem of user, exceptions and incorrect validation is Checkstyle problems.

But I do not want to allow all tokens in this Check for now.

**Comment by romani** [comment]
@elingg , if you have time and desire to help, please update Check code and UTs for this case, and xdoc files to have on our website example of how to do this (users like examples).

you are welcome with PR.

**Comment by romani** [comment]
Fix is merged
