### ISSUE TITLE
Setup 'Circle CI' to run checkstyle-tester project on JDK sources

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#2815]
Base on #2727.

https://circleci.com/docs/configuration
https://circleci.com/docs/parallel-manual-setup

We need to setup 3-4-N sub-builds(matrix elements) in CI to test JDK sources by checkstyle-tester in groups to let each launch finish in 15min (or level of CI).
We need to make sure that CI has the same integration with Github to notify us on any failures (ERROR level).

That will let us avoid problems like - #1109 (comment) ,

We already did that in Travis, the only missed point is testing over JDK. Sources of JDK are huge so we need to find a way to split them in chunks and do the testing part by part.

Note: due to java grammar problem we can not use jdk8-9 , we can parse only jdk7. For details please see all issues with "ANTLR" label.

**Comment by romani** [comment]
@Vladlis ,

https://circleci.com/gh/checkstyle/checkstyle/4 , there is performance problem caused by downloading numerous of artifacts, is there any way to keep in cache all such artifacts. 
Officially (https://circleci.com/docs/how-cache-works) I do not see a way, but is there a hack way to do this ?
try to investigate this problem in web and try to search other circleci.yml files on github for workaround.

**Comment by romani** [comment]
fix is merged.

**Comment by Vladlis** [comment]
As maven dependency plugin does not work correctly we have to install Checkstyle and run checkstyle-tester on an empty folder in the 'dependencies' section to let CircleCI cache dependencies.
Proof: 
1) after 'mvn dependency:go-offline' command in 'dependencies' a lot of files are still downloaded in the 'test' section
https://circleci.com/gh/checkstyle/checkstyle/57
2) the same after 'mvn dependency:resolve'
https://circleci.com/gh/checkstyle/checkstyle/5

**Comment by romani** [comment]
fix is merged.
