### ISSUE TITLE
FinalClass is over aggressive when extending happen inside class

### ISSUE THREAD

**Issue by jhjensen** [checkstyle/checkstyle#2822]
```
/var/tmp $ cat Foo.java 
public class Foo {
   private Foo(String name) {
   }

   static Foo factory(int type) {
      switch (type) {
         case 1:
            return new Foo1();
         default:
            throw new RuntimeException("bad type");
      }
   }

   private static final class Foo1 extends Foo {
      Foo1() {
          super("1");
      }
   }

}

/var/tmp $ cat Test.xml 
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
<module name = "Checker">
    <module name="TreeWalker">
	    <module name="FinalClass" />
    </module>
</module>

/var/tmp $ java -jar checkstyle-6.14.1-all.jar -c Test.xml Foo.java 
Starting audit...
[ERROR] /var/tmp/Foo.java:1: Class Foo should be declared as final. [FinalClass]
Audit done.
Checkstyle ends with 1 errors.
```

If we add `final` modifier, source file is not compilable
```
/var/tmp $ javac Foo.java 
Foo.java:15: error: cannot inherit from final Foo
   private static final class Foo1 extends Foo {
                                           ^
1 error
```

**Comment by romani** [comment]
to report the issue , all details are required: config, checkstyle version, ...
see http://checkstyle.sourceforge.net/report_issue.html#How_to_report_a_bug

**Comment by romani** [comment]
@jhjensen , your issue is still valid.

I am just curious what is real reason of code that you have.
from example I see that private type is returned outside of class. 

We have a special Check for this - https://github.com/sevntu-checkstyle/sevntu.checkstyle/issues/67

**Comment by jhjensen** [comment]
Mostly a matter of style.  I like making things final and private as much
as possible, and in this case there wasn't any reason to expose even the
existence of multiple implementations generated.

In particular the purpose of the original class was to abstract the
difference between a local file, a remote file, and a directory, so that
other code didn't need to know the difference.

**Comment by jhjensen** [comment]
also the factory function return type is (public)Foo, so I am not sure what
the problem is here.

**Comment by romani** [comment]
fix is merged.
