### ISSUE TITLE
Add option to exclude annotations in ClassFanOutComplexity check

### ISSUE THREAD

**Issue by fracz** [checkstyle/checkstyle#2823]
There are some classes that has many annotations on their field/methods but from the developer point of view they do not increase the complexity of a class. Spring-web controller is a great example of this.

```java
@Controller
@RequestMapping("/user")
public class UserController {
    @Autowired
    private Some someService;

    @RequestMapping("/{user}")
    @ResponseBody
    @PostAuthorize
    public UserDto get(@PathVariable User user) {
        // ...
    }

    @RequestMapping
    @ResponseBody
    @PreAuthorize(...)
    public SomeReturn getSomething(@RequestParam String param) {
        // ...
    }
}

**Comment by fracz** [comment]
I have checked again and it seems that annotations are ignored in ClassFanOutComplexity check. Sorry :-)

**Comment by sabberworm** [comment]
AFAICT, annotations are not ignored. The docs even explicitly state:

>  Checks the number of other types a given class/record/interface/enum/**annotation** relies on. Also, the square of this has been shown to indicate the amount of maintenance required in functional programs (on a file basis) at least. 

(emphasis mine)
