### ISSUE TITLE
Add checkstyle messages to xdocs

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#2836]
> The obvious question is how do you know which message keys a Check uses, so that you can override them? Well, that is the tricky part. To find out which keys a Check uses you currently need to look into the Check's source code, in conjunction with the Check's messages.properties file.

The check's messages and their parameters should be added to the xdocs so it is easier for the user to find these names to override and serves to inform them what error messages to expect from the check they are implementing.

**Comment by romani** [comment]
We also need to find way to enforce this by UTs, to ensure that code and xdoc is always in sync.

**Comment by rnveach** [comment]
@romani I would like to work on this.
I'll start by first making a UT to require all checks to report atleast one error message. So far, I only see checks like `RegexpMultilineCheck` needing an override since the user sets the message.

To make this easy, I am thinking that all error messages should be named `MSG_*` fields so I can use reflection on the check to gather all the messages. This would require:
1) Add `MSG_` to existing field names, like `JavadocTypeCheck.JAVADOC_MISSING`, to match the required format.
2) Move error messages to the check from their supporting classes, like `IndentationCheck` where the messages are stored in `AbstractExpressionHandler` and `LineWrappingHandler`.
3) Convert in-line strings to fields, like in `ArrayTypeStyleCheck`.

Once that is done, then it only requires the UT for verification against the XDOCs and manually adding in the messages.

**Comment by romani** [comment]
Sounds good

**Comment by rnveach** [comment]
@romani @mkordas 
What are your opinions on how the 'Error Messages' section should be displayed?
My current thoughts are to make it in a table format like the below with `AbbreviationAsWordInNameCheck`'s message as an example:
````
+----------------------+------+---------------------------------------------------+
| abbreviation.as.word |      | Abbreviation in name ''{0}'' must contain no more |
|                      |      | than ''{1}'' capital letters.                     |
+----------------------+------+---------------------------------------------------+
|                      |      | Parameter 0    | Text of name being reported.     |
+----------------------+------+---------------------------------------------------+
|                      |      | Parameter 1    | Check's value for                |
|                      |      |                | 'allowedAbbreviationLength'.     |
+----------------------+------+---------------------------------------------------+
````

**Comment by romani** [comment]
I would rather avoid such details in Xdoc, name of string "abbreviation.as.word" and link to it is enough . Message could be changed/extended. We should not forget that we support 7 languages .

**Comment by romani** [comment]
fix is merged.
