### ISSUE TITLE
6.15 complains about missing @return tag in a overridden method

### ISSUE THREAD

**Issue by tmortagne** [checkstyle/checkstyle#2869]
I upgrade from 6.14.1 to 6.15 and the following code

     /**
     * @since 7.1M2
     */
    @Override
    public String toString()
    {
        return prepareToString().append("context", this.executionContext.getProperties()).toString();
    }

gives me the following error:

    Expected an @return tag. [JavadocMethod]

This looks like a bug to me since the each tag is supposed to be automatically copied when not set in an overridden method.

**Comment by rnveach** [comment]
This is from issue #2806.
It was changed because the documentation ([config_javadoc.html#JavadocMethod](http://checkstyle.sourceforge.net/config_javadoc.html#JavadocMethod)) for `allowedAnnotations` says `could allow missed documentation`. I took it to mean that it would skip the method if no documentation was provided, but if any documentation was provided, it should be valid by the normal rules.

**Comment by tmortagne** [comment]
Well the way I understand #2806 is that checkstyle should make sure what is entered make sense (like in the example some @param that does not exist) but each element of the javadoc is treated separately AFAIK so it's not before you put a @since that you don't have the rest.

**Comment by romani** [comment]
> This looks like a bug to me since the each tag is supposed to be automatically copied when not set in an overridden method.

Lets find this in specification - http://docs.oracle.com/javase/8/docs/technotes/tools/windows/javadoc.html . I do not see this.

@tmortagne , Please point to some documentation to prove your idea.

**Comment by tmortagne** [comment]
I'm not sure about where to find the official documentation on this but what I can do is to give you an example of actual javadoc behavior.

The following method source: https://github.com/xwiki/xwiki-commons/blob/xwiki-commons-7.4/xwiki-commons-core/xwiki-commons-observation/xwiki-commons-observation-api/src/main/java/org/xwiki/observation/event/AbstractFilterableEvent.java#L97

Which gives the following javadoc: http://nexus.xwiki.org/nexus/service/local/repositories/releases/archive/org/xwiki/commons/xwiki-commons-observation-api/7.4/xwiki-commons-observation-api-7.4-javadoc.jar/!/org/xwiki/observation/event/AbstractFilterableEvent.html#matches%28java.lang.Object%29

You can see that that none of the parameter or return tags are in the source but yet they do end up in the javadoc, copied from the overridden interface. I don't think Maven Javadoc plugin have a custom implementation of javadoc. Eclipse also behave like this when putting the method over the method.

**Comment by rnveach** [comment]
@romani This looks like it.

http://docs.oracle.com/javase/8/docs/technotes/tools/windows/javadoc.html#CHDFAGJH
> The javadoc command allows method comment inheritance in classes and interfaces to fill in missing text or to explicitly inherit method comments
> When a main description, or @return, @param, or @throws tag is missing from a method comment, the javadoc command copies the corresponding main description or tag comment from the method it overrides or implements (if any). 
> When an @param tag for a particular parameter is missing, the comment for that parameter is copied from the method further up the inheritance hierarchy. When an @throws tag for a particular exception is missing, the @throws tag is copied only when that exception is declared.

**Comment by romani** [comment]
ok, we need to fix this. 

1) We need to keep in mind that Checkstyle have no ability to look at other file, no way to use clas hierachy. 
2) We should trust `@Override` annotation. If such annotation exists - allow all missed javadoc-tags.
3) We need to add xwiki project to our CI (travis)  for validation on each commit , by substitution of https://github.com/xwiki/xwiki-commons/blob/master/pom.xml#L96 to our SNAPSHOT version . This is not a first time xwiki project report issue on us, we need to avoid making troubles for them.

**Comment by romani** [comment]
@tmortagne , 
can you share with us link to your checkstyle config  ? 
do you failure a build by any checkstyle violation or .... ?

**Comment by tmortagne** [comment]
> 3) We need to add xwiki project to our CI (travis) for validation on each commit , by substitution of https://github.com/xwiki/xwiki-commons/blob/master/pom.xml#L96 to our SNAPSHOT version . This is not a first time xwiki project report issue on us, we need to avoid making troubles for them.

That would be super nice :)

>  can you share with us link to your checkstyle config ?

* actual XWiki checkstyle configuration: https://github.com/xwiki/xwiki-commons/blob/master/xwiki-commons-tools/xwiki-commons-tool-verification-resources/src/main/resources/checkstyle.xml
* Maven checkstyle plugin configuration: https://github.com/xwiki/xwiki-commons/blob/master/xwiki-commons-pom/pom.xml#L117
* forced checkstyle version to use (for the checkstyle check and to build the custom rules): https://github.com/xwiki/xwiki-commons/blob/master/pom.xml#L96
* also a few custom rules in https://github.com/xwiki/xwiki-commons/tree/master/xwiki-commons-tools/xwiki-commons-tool-verification-resources project

> do you failure a build by any checkstyle violation or .... ? share with us a way/commands to run checkstyle on your project.

Yes we fail the Maven build by default but standard XWiki Maven build is quite long and a quicker validation would be to just execute `mvn checkstyle:check` in the root of the following repositories:
* https://github.com/xwiki/xwiki-commons/
* https://github.com/xwiki/xwiki-rendering/
* https://github.com/xwiki/xwiki-platform/

(there is other repositories but those 3 should be enough to catch any regression from XWiki point of view at least)

Note: Since we put the version of checkstyle in a Maven property, I think you should be able to run the XWiki Maven build with the version of checkstyle you want by adding `-Dcheckstyle.version=<version>` as in  `mvn checkstyle:check -Dcheckstyle.version=6.15`.

**Comment by romani** [comment]
> Note: Since we put the version of checkstyle in a Maven property

Thanks a lot, I optimized our CI commands.

**Comment by romani** [comment]
Assigned to @Vladlis .

**Comment by Vladlis** [comment]
Should we revert https://github.com/checkstyle/checkstyle/commit/78c1fa440c2fd908c689da5f5e9d397b1fe833a5 ? These tags are redundant.

**Comment by romani** [comment]
I am ok to remove.

**Comment by Vladlis** [comment]
@tmortagne 
look like it's not enough to
> just execute `mvn checkstyle:check` in the root of the following repositories

I get this, when try to validate https://github.com/xwiki/xwiki-platform/
https://travis-ci.org/checkstyle/checkstyle/jobs/109143217

And during the validation of https://github.com/xwiki/xwiki-commons/ for some reason tools are checked with another config, so there's a lot of violations.
https://travis-ci.org/checkstyle/checkstyle/jobs/109077071

Haven't tried https://github.com/xwiki/xwiki-rendering/ yet.
Can you advice something?

https://github.com/Vladlis/checkstyle/commit/b8179d09818d26462e447762f2b1a4da7defcb3f Travis config changes.

**Comment by romani** [comment]
discussion about build problem is in PR #2908 .

**Comment by tmortagne** [comment]
Hmm looks like checkstyle:check force the check even when it's indicated in the pom to skip it. So indeed it's not going to help much since we skip it in several module.

From what I can see in the log the issue you have with platform is that it does not find xwiki-commons pom (that it's using as parent). If you build platform alone you can add the following in your setting.xml so that it download them from XWiki snapshot repository: http://dev.xwiki.org/xwiki/bin/view/Community/Building#HInstallingMaven

**Comment by tmortagne** [comment]
mvn checkstyle:check should be ok on xwiki-commons and xwiki-rendering now. I things there will still be issues on platform with ignored skipped property.

**Comment by tmortagne** [comment]
Actually looks like `mvn checkstyle:check` is fine on all 3 repositories now as far as I can see (just need to make sure rendering and platform will find commons somewhere). Don't hesitate to report us if we break it for you later.

**Comment by romani** [comment]
@Vladlis , lets split fix of the issue into two PRs: 
1) functional fix + manual testing over xwiki
2) Travis update to use xwiki.

**Comment by romani** [comment]
functional fix is merged, but we will keep issue open till we adjust our CI to validate SNAPSHOT version against xwiki sources.

**Comment by romani** [comment]
xwiki update for travis  is moved to #2938

**Comment by romani** [comment]
@tmortagne , we need your assistance at #2947
