### ISSUE TITLE
Global Checkstyle preferences do not get applied 

### ISSUE THREAD

**Issue by Matthew7878** [checkstyle/checkstyle#2877]
Individual projects have overrides on the global checkstyle preference option that prevent them from all being updated together. Even after trying to delete the .checkstyle for a project it still does not receive the update from the global "default" choosing.

**Comment by romani** [comment]
> .checkstyle

please open issue against eclipse-cs project (http://eclipse-cs.sourceforge.net/). checkstyle is just a library, IDE plugins are supported by another teams.
