### ISSUE TITLE
Changed semantics of PropertyExpander

### ISSUE THREAD

**Issue by phejl** [checkstyle/checkstyle#2886]
Since this change https://github.com/checkstyle/checkstyle/commit/7d513f0 the property expander does not resolved default properties stored in passed properties.

**Comment by romani** [comment]
@mkordas , can you please make a first look at this issue. This commit is yours.

**Comment by mkordas** [comment]
@romani sure, I'll take a look soon

**Comment by mkordas** [comment]
@phejl can you post some code how you use property expander and in what context default properties are useful?

**Comment by phejl** [comment]
I think the patch with (failing) test is better...

[issue_2886_test_patch.txt](https://github.com/checkstyle/checkstyle/files/123084/issue_2886_test_patch.txt)

**Comment by mkordas** [comment]
@romani I think @phejl is right - the test from his patch should pass. We need to fix that, please add proper labels.

**Comment by romani** [comment]
@phejl , you are welcome with PullRequest.

**Comment by romani** [comment]
fix is merged.
