### ISSUE TITLE
MissingDeprecated should have an option to ignore elements without JavaDoc

### ISSUE THREAD

**Issue by liutikas** [checkstyle/checkstyle#2889]
http://checkstyle.sourceforge.net/config_annotation.html#MissingDeprecated

MissingDeprecated currently will trigger for cases when an element is marked @Deprecated but it does not have any JavaDoc. Since Javadoc could be optional (based on the rule set) I think it would make sense to add an option to MissingDeprecated to allow it to ignore cases when JavaDoc is missing, but still warn when JavaDoc is present but either @deprecated is missing from JavaDoc or @Deprecated is missing from the element.

Checkstyle version:
6.15

Check/Module:
MissingDeprecated

Code snippet:
```
@Deprecated
public static final int MY_CONST = 123456;
```

Expected:
User of Checkstyle should be able to skip elements with @Deprecated tag if they do not have Javadoc.

This new property for MissingDeprecated could be called `skipNoJavadoc`, default value is `false` to be compatible with previous implementation.

```
<module name="MissingDeprecated">
  <property name="skipNoJavadoc" value="true"/>
 </module>
```

**Comment by romani** [comment]
please report an issue as descried at http://checkstyle.sourceforge.net/report_issue.html#How_to_report_a_bug

**Comment by liutikas** [comment]
Checkstyle version:
6.15

Check/Module:
MissingDeprecated

Code snippet:
`@Deprecated`
`public static final int MY_CONST = 123456;`

Expected:
User of Checkstyle should be able to skip elements with @Deprecated tag if they do not have Javadoc.

This new property for MissingDeprecated could be called `skipNoJavadoc`

`<module name="MissingDeprecated">`
`  <property name="skipNoJavadoc" value="true"/>`
`</module>`

**Comment by romani** [comment]
whole logic of validation is one file https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/MissingDeprecatedCheck.java if smb have a time please be welcome to fix this problem.
For development details please read http://checkstyle.sourceforge.net/contributing.html

**Comment by romani** [comment]
fix is merged.
