### ISSUE TITLE
Provide capability to suppress warnings per method

### ISSUE THREAD

**Issue by awhitford** [checkstyle/checkstyle#289]
I would like to see a mechanism to suppress checkstyle warnings on a per method basis.  This will be particularly useful for generated code.

The same annotation mechanism that PMD uses would be nice:
  http://pmd.sourceforge.net/pmd-5.1.3/suppressing.html

**Comment by alexkravin** [comment]
I do not understand where and what to add, as there're examples in config such as: https://github.com/checkstyle/checkstyle/blob/master/src/xdocs/config.xml#L728
http://checkstyle.sourceforge.net/config.html#SuppressionFilter

**Comment by romani** [comment]
that web page http://checkstyle.sourceforge.net/config.html contains all descriptions about what kind of suppression we have and how to use them, but there are no examples (code + config) there so user have problem to use them. Each Filter should have few examples to clearly show how code will looks like after suppression is used.

**Comment by awhitford** [comment]
Does @SuppressWarnings("all") work?

**Comment by romani** [comment]
no  it does not , all options of names are at http://checkstyle.sourceforge.net/config_annotation.html#SuppressWarningsHolder
