### ISSUE TITLE
Javadoc for try-with-resources tokens is not good enough

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#2899]
There are two different token types in `TokenTypes` for try-with-resources.
![screenshot from 2016-02-11 20-46-20](https://cloud.githubusercontent.com/assets/5467276/12988369/b194f920-d100-11e5-9057-9227b30905b4.png)
The difference between these tokens should be explained there.
##

**Comment by Sukrityshrivastava** [comment]
Can you please provide some more details about what I need to do?

**Comment by rnveach** [comment]
@Sukrityshrivastava We need a clear description of the 2 tokens so users can tell what they are and their differences. Description should be clear and a bit more detailed, we should show a Java code example and a AST Tree example.

**Comment by Sukrityshrivastava** [comment]
Actually I am new and need help so can you please specify in which file I need to do modifications.

**Comment by rnveach** [comment]
@Sukrityshrivastava Changes need to be done in `TokenTypes` file as described in first post.

**Comment by subkrish** [comment]
@rnveach Since @Sukrityshrivastava did not continue to work on this, I would like to take this issue over. I am on it.

**Comment by rnveach** [comment]
Fix is merged
