### ISSUE TITLE
Checkstyle cannot be built using JDK9 as tools.jar has been dropped 

### ISSUE THREAD

**Issue by peteryhwong** [checkstyle/checkstyle#2905]
Checkstyle cannot be built using JDK9 as tools.jar has been dropped. See https://issues.apache.org/jira/browse/MNG-5732

**Comment by romani** [comment]
You are welcome with PR

**Comment by peteryhwong** [comment]
Just made a PR. By the way the following two unit tests have been failing 

```
CheckerTest.testDestroyCacheFileWithInvalidPath:346 Exception did not happen
MainTest.testLoadPropertiesIoException:452 Exception was expected
```
Is this known?

**Comment by romani** [comment]
No, it is not expected, all uts are green in our ci. 

We are still jdk7 focused, we plan to switch to jdk8 in next month. Jdk9 is far future for us. 

Can you share a reason why you need checkstyle on jdk9 ?

**Comment by romani** [comment]
fix is merged.

**Comment by peteryhwong** [comment]
@romani I am working within the OpenJDK community to prepare for JDK 9 release. As part of that effort I am currently trying to make Maven work with JDK 9 and as a consequence the maven plugins I use regularly. The checkstyle Maven plugin is one such plugin :smile:

**Comment by romani** [comment]
Thanks a lot, if you finish mvn build please let us know , we plan to use openjdk sources for our regression testing.

If you know what checkstyle config openjdk project use please let us know. I am interested in helping openjdk with code style automation.
