### ISSUE TITLE
Support for LAMDA token in WhitespaceAround check

### ISSUE THREAD

**Issue by jjlharrison** [checkstyle/checkstyle#2924]
I would like to be able to configure the `WhitespaceAround` check to enforce whitespace around lambda tokens (e.g. `(o) -> o.toString()` instead of `(o)->o.toString()`).

Currently, the check's token property supports a subset of `TokenType`s that does not include `LAMDA`.

**Checkstyle Version**
6.15

**Check/Module**
WhitespaceAround

**Code Snippet**
```java
public static void main(String[] args)
{
    Function<Object, String> function = (o)->o.toString(); // Should fail as there's no space before/after "->".
}
```
**Configuration**
```xml
<module name="WhitespaceAround">
    <property name="tokens" value="LAMDA"/>
</module>
```

**Comment by romani** [comment]
please report issue like http://checkstyle.sourceforge.net/report_issue.html#How_to_report_a_bug

**Comment by jjlharrison** [comment]
@romani I've updated the comment. I hope it includes everything that is required.

**Comment by romani** [comment]
Much better, thank a lot for reporting an issue
