### ISSUE TITLE
UnusedImports should not force us to use full class name in JavaDoc

### ISSUE THREAD

**Issue by ychulovskyy** [checkstyle/checkstyle#2927]
UnusedImports is useful check, however it has one minor issue that stops us from using it.
It forces us to write `{@link java.util.Date}` in JavaDoc instead of
```
import java.util.Date;
...
{@link Date}
```
because "it is considered bad practice to introduce a compile time dependency for documentation purposes only" http://checkstyle.sourceforge.net/config_imports.html#UnusedImports

But we would like to use short class name instead of full, especially if the class is mentioned many times in the JavaDoc.

Is it possible to introduce "allowImportForJavaDoc" flag to fix it?

**Comment by rnveach** [comment]
@ychulovskyy 
please report issue like http://checkstyle.sourceforge.net/report_issue.html#How_to_report_a_bug

To me, what you are describing sounds like the `processJavadoc` property, which is already enabled by default.

**Comment by mkordas** [comment]
@ychulovskyy as @rnveach says this is already implemented and enabled by default. Please update your Checkstyle.
