### ISSUE TITLE
Enforce metioning issue in PR description to create links

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#2929]
Right now GitHub does not create link between issue and PR, when issue is referenced just from PR title, and it is not easy to quickly see from issue all pull requests where issue was implemented.

The solution for it, adopted in many projects, is to provide link to issue somewhere in PR description, for example:

#### `#1 Short PR title`

```
More detailed explanatory text.

Further paragraphs come after blank lines.

Resolves: #1
See also: #2, #3
```
Such approach, would guarantee great traceability in both directions between PR and issue. We can start enforcing it straight away by editing descriptions or asking authors to do that, but ideally it would be great to automate that.

My proposition is to create additional test that would basically do three tasks:
* get issue number (let's say `#1`) from the latest commit (or just pass if there is no issue number)
* read PR description through GitHub API or any other way - the simpler the better
* make assertion that description contains at least one occurrence of `#1`

**Comment by romani** [comment]
We need to valudate this by CI during PR validation.

We already use github api during release notes generation, already in Travis .

Looks like Travis do not have PR number, https://docs.travis-ci.com/user/environment-variables/ . 

Can we get PR number in other CIs that we use ?

**Comment by rnveach** [comment]
> Looks like Travis do not have PR number

Is this what your looking for?
> TRAVIS_PULL_REQUEST: The pull request number if the current job is a pull request, “false” if it’s not a pull request.

**Comment by rnveach** [comment]
> get issue number (let's say #1) from the latest commit (or just pass if there is no issue number)

@mkordas If we are using travis and want to get fancy, maybe it's possible to use this variable to get all issue numbers in-case 1 PR has multiple issues in commits or 1 PR has non-issue commits with issue commits?

> TRAVIS_COMMIT_RANGE: The range of commits that were included in the push or pull request.

**Comment by mkordas** [comment]
@rnveach sure, this could be the second step after prototype will be proved to work fine for us

**Comment by romani** [comment]
moved to https://github.com/checkstyle/contribution/issues/69
