### ISSUE TITLE
DOXIA-525 - Rendering links in xdocs breaks them - is fixed

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#2965]
https://issues.apache.org/jira/browse/DOXIA-525

is fixed, lets try to use workaround that mentioned in this issue.
See suppression in our pom.xml for "DOXIA-525"
##

**Comment by mismatch** [comment]
@romani, I cannot find DOXIA-525 in pom.xml (and any other file in this repository). Is this issue still relevant?

**Comment by romani** [comment]
I am afk for few days, please do grep on whole repo, if no reference if jira issue found, please close this issue, might be resolved by smth else.

You can check out to code state of 2 years ago (day after issue is created) to look at code where it was placed, and how it was resolved.

**Comment by mismatch** [comment]
The line mentioning DOXIA-525 has gone since commit 58f3c6996f38d0d74828689fbab3311244f8afc5 on 1 May 2016. So I suppose this issue should be closed. Someone with right to close issues, please, have a look and take action.

**Comment by rnveach** [comment]
Problem was added at https://github.com/checkstyle/checkstyle/commit/456d918a770b7a8899cd69986ee022fba287fffb#diff-600376dffeb79835ede4a0b285078036R666 and then removed at https://github.com/checkstyle/checkstyle/commit/58f3c6996f38d0d74828689fbab3311244f8afc5#diff-600376dffeb79835ede4a0b285078036L1170 .

Closing.

**Comment by mismatch** [comment]
Thank you!
