### ISSUE TITLE
Add the ability to validate language codes by TranslationCheck

### ISSUE THREAD

**Issue by MEZk** [checkstyle/checkstyle#2969]
TranslationCheck cannot validate user-specified language codes in current implementation.
See https://github.com/checkstyle/checkstyle/blob/master/src/xdocs/config_misc.xml#L1623

Nevertheless, we can implement such validation and inform user if the language code is incorrect.
See suggestions at http://stackoverflow.com/questions/3684747/how-to-validate-a-locale-in-java

**Comment by romani** [comment]
Fix is merged
