### ISSUE TITLE
Resolved relative path for SuppressionFilter file relative to config file location

### ISSUE THREAD

**Issue by baron1405** [checkstyle/checkstyle#2976]
Would it be possible to add to the SuppressionFilter file resolution strategy such that relative paths to the suppression file are resolved relative to the location of the configuration file? Currently, different IDE plugins for Checkstyle handle this in different ways, making it very clumsy to share a single configuration file across the command line, Eclipse (eclipse-cs) and IntelliJ (Checkstyle-IDEA). The Eclipse plugin defines a property 'config_loc', the IntelliJ plugin requires users to define a property for this purpose, and in Gradle you need to wrap its Checkstyle plugin if you want a property defined with the location.

**Comment by romani** [comment]
Please provide more investigation results on how it is in plugins, and what you would like to have (imagine that anything is possible)

**Comment by baron1405** [comment]
Thanks for the quick reply!

We deploy a Checkstyle configuration file along with a suppression file. They live in the same directory. For consumption by the Eclipse Checkstyle plugin (eclipse-cs), we have the following in our configuration file:
```
<module name="SuppressionFilter">
   <property name="file" value="${config_loc}/suppressions.xml"/>
</module>
```
The Eclipse plugin pre-defines the `config_loc` property to be the absolute path of the directory containing the configuration file. This makes it easy to reference the location of the suppression file in a way that is independent of the location of the source tree on the filesystem.

Unfortunately, this only works in Eclipse because the IntelliJ Checkstyle plugin (Checkstyle-IDEA) does not pre-define the same (or any) property. What would be optimal would be for Checkstyle itself to handle this use case. While Checkstyle could pre-define a property in a manner similar to the Eclipse plugin, it would be even easier to be able to specify a relative path for the suppression file:
```
<module name="SuppressionFilter">
    <property name="file" value="suppressions.xml"/>
</module>
```
In this case, the relative path would be resolved against the location of the configuration file on the file system or at the same base URL if the configuration file is obtained via HTTP, or at the same classpath location if that is how the configuration file was obtained.

Adding this feature would make it very easy to share Checkstyle configurations files across build tools (e.g. Gradle), and IDE's (e.g. Eclipse and IntelliJ).

**Comment by baron1405** [comment]
Update: The Checkstyle-IDEA plugin just [added the config_loc property](https://github.com/jshiell/checkstyle-idea/issues/217).

**Comment by romani** [comment]
that is good that IDEs have such variables.

Checkstyle is a library, not a final implementation. We already have variable resolving mechanism. That is why it works in IDE. Somebody need to define this variable from outside of Checkstyle.
We do not set any variable by library to avoid any possible conflicts with user defined systems variables.

Example of how it works in CLI:
```
.../checkstyle [master|✚ 1] $ git diff
diff --git a/config/checkstyle_checks.xml b/config/checkstyle_checks.xml
index 9c28209..d675364 100644
--- a/config/checkstyle_checks.xml
+++ b/config/checkstyle_checks.xml
@@ -34,7 +34,7 @@
     <property name="onCommentFormat" value="CSON\: .*"/>
   </module>
   <module name="SuppressionFilter">
-    <property name="file" value="${checkstyle.suppressions.file}"/>
+    <property name="file" value="${checkstyle.config.path}/suppressions.xml"/>
   </module>
   <module name="SuppressWarningsFilter"/>
   <module name="SuppressWithNearbyCommentFilter">
@@ -50,12 +50,12 @@
 
   <!-- Headers -->
   <module name="Header">
-    <property name="headerFile" value="${checkstyle.header.file}"/>
+    <property name="headerFile" value="${checkstyle.config.path}/java.header"/>
     <property name="fileExtensions" value="java"/>
     <property name="id" value="header"/>
   </module>
   <module name="RegexpHeader">
-    <property name="headerFile" value="${checkstyle.regexp.header.file}"/>
+    <property name="headerFile" value="${checkstyle.config.path}/java_regexp.header"/>
     <property name="fileExtensions" value="java"/>
   </module>
 
@@ -257,7 +257,7 @@
     </module>
     <module name="IllegalImport"/>
     <module name="ImportControl">
-      <property name="file" value="${checkstyle.importcontrol.file}"/>
+      <property name="file" value="${checkstyle.config.path}/import-control.xml"/>
     </module>
     <module name="ImportOrder">
       <property name="groups" value="/^javax?\./,org"/>

/checkstyle [master|✚ 1] $ mvn clean verify -DskipTests -DskipITs -Dcheckstyle.config.path=./config
.....
[INFO] Executing tasks
main:
execute:
     [echo] Checkstyle started: 02/03/2016 05:43:16 AM
[checkstyle] Running Checkstyle 6.17-SNAPSHOT on 878 files
     [echo] Checkstyle finished: 02/03/2016 05:44:17 AM
[INFO] Executed tasks
.....
```

**Comment by romani** [comment]
test of Ant:
```
../checkstyle [master|✚ 2] $ git diff
diff --git a/config/ant-phase-verify.xml b/config/ant-phase-verify.xml
index b14bd47..aba615b 100644
--- a/config/ant-phase-verify.xml
+++ b/config/ant-phase-verify.xml
@@ -16,6 +16,7 @@
 
     <property name="checkstyle.pattern.todo" value="NOTHingWillMatCH_-"/>
     <property name="check.config" location="config/checkstyle_checks.xml"/>
+    <dirname property="checkstyle.config.path" file="${check.config}"/>
 
     <tstamp>
       <format property="STARTED" pattern="dd/MM/yyyy hh:mm:ss aa" />
@@ -33,11 +34,6 @@
       <formatter type="xml" toFile="${mvn.project.build.directory}/cs_errors.xml"/>
       <classpath path="${mvn.runtime_classpath}"/>
       <property key="checkstyle.cache.file" file="${mvn.project.build.directory}/cachefile"/>
-      <property key="checkstyle.header.file" file="config/java.header"/>
-      <property key="checkstyle.regexp.header.file" file="config/java_regexp.header"/>
-      <property key="checkstyle.importcontrol.file" file="config/import-control.xml"/>
-      <property key="checkstyle.suppressions.file"
-                file="config/suppressions.xml"/>
     </checkstyle>
 
     <tstamp>
diff --git a/config/checkstyle_checks.xml b/config/checkstyle_checks.xml
index 9c28209..d675364 100644
--- a/config/checkstyle_checks.xml
+++ b/config/checkstyle_checks.xml
@@ -34,7 +34,7 @@
     <property name="onCommentFormat" value="CSON\: .*"/>
   </module>
   <module name="SuppressionFilter">
-    <property name="file" value="${checkstyle.suppressions.file}"/>
+    <property name="file" value="${checkstyle.config.path}/suppressions.xml"/>
   </module>
   <module name="SuppressWarningsFilter"/>
   <module name="SuppressWithNearbyCommentFilter">
@@ -50,12 +50,12 @@
 
   <!-- Headers -->
   <module name="Header">
-    <property name="headerFile" value="${checkstyle.header.file}"/>
+    <property name="headerFile" value="${checkstyle.config.path}/java.header"/>
     <property name="fileExtensions" value="java"/>
     <property name="id" value="header"/>
   </module>
   <module name="RegexpHeader">
-    <property name="headerFile" value="${checkstyle.regexp.header.file}"/>
+    <property name="headerFile" value="${checkstyle.config.path}/java_regexp.header"/>
     <property name="fileExtensions" value="java"/>
   </module>
 
@@ -257,7 +257,7 @@
     </module>
     <module name="IllegalImport"/>
     <module name="ImportControl">
-      <property name="file" value="${checkstyle.importcontrol.file}"/>
+      <property name="file" value="${checkstyle.config.path}/import-control.xml"/>
     </module>
     <module name="ImportOrder">
       <property name="groups" value="/^javax?\./,org"/>

../checkstyle [master|✚ 2] $ mvn clean verify -DskipTests -DskipITs
.....
[INFO] Executing tasks
main:
execute:
     [echo] Checkstyle started: 02/03/2016 05:57:16 AM
[checkstyle] Running Checkstyle 6.17-SNAPSHOT on 878 files
     [echo] Checkstyle finished: 02/03/2016 05:59:17 AM
[INFO] Executed tasks
.....
```

**Comment by romani** [comment]
In Gradle (and any other build systems) you should have the same ability to define systems variable as I did in ANT (see example above).
Looks like IDE problem is resolved already.

@baron1405 ,
Please provide more prove that checkstyle need to have "file resolution strategy".

**Comment by baron1405** [comment]
Given that the plugins are now uniformly defining the resolution property and Gradle's plugin provides the capability to also define the same resolution property, I agree that Checkstyle itself can remain agnostic to any properties and just support the property infrastructure itself. I am going to close this issue as Won't Fix. Thanks for discussing it!

**Comment by Nikita-Guchakov** [comment]
@baron1405 While it's true that it can be done by configuring variables outside, we forced to configure path variables at two places, idea plugins works somehow with relative paths, gradle does not. If we add prop for the gradle - every developer then have to configure a variable at plugin settings. It's annoying. I don't think there is need to specify strategy explicitly, just support relative to config paths like "<property name="file" value="excluded.xml"/>"

**Comment by romani** [comment]
There are numerous ways how user can define path to file, implementation of any smart strategy will not be simple to not disrupt existing implementation.

Can you use `config_loc` variable ( that is defined by plugin by default) in gradle? To avoid extra  settings in idea plugin.
