### ISSUE TITLE
Allow JUnit ClassRule to be public

### ISSUE THREAD

**Issue by avano** [checkstyle/checkstyle#2987]
The JUnit ClassRule should be treated the same way as JUnit Rule, as must should be declared public.

Currently only @Rule is ignored from the check and latest version complains about:
Variable 'myClassRule' must be private and have accessor methods. [VisibilityModifier]

Class:

    /tmp/checkstyle :: cat Example.java
    public class Class {
    @org.junit.Rule
    public Rule rule = new Rule();
	
    @org.junit.ClassRule
    public static Rule classRule = new ClassRule();
    }

XML:

    /tmp/checkstyle :: cat checkstyle.xml
    <?xml version="1.0"?>
    <!DOCTYPE module PUBLIC
	"-//Puppy Crawl//DTD Check Configuration 1.3//EN"
	"http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

    <module name="Checker">
	<module name="TreeWalker">
		<module name="VisibilityModifier"/>
	</module>
</module>

Outcome:

    /tmp/checkstyle :: java -jar checkstyle-6.16-all.jar -c checkstyle.xml Example.java
    Starting audit...
    [ERROR] /tmp/checkstyle/Example.java:6:28: Variable 'classRule' must be private and have accessor methods. [VisibilityModifier]
    Audit done.
    Checkstyle ends with 1 errors.

JUnit rule is in the 'whitelist' in VisibilityModifierCheck class:
    
    /** Default ignore annotations canonical names. */
    private static final List<String> DEFAULT_IGNORE_ANNOTATIONS = ImmutableList.of(
        "org.junit.Rule",
        "com.google.common.annotations.VisibleForTesting"
    );

but the ClassRule is not, even if it's the same principle.

**Comment by romani** [comment]
Please report issue with all details, see preferable format at http://checkstyle.sourceforge.net/report_issue.html#How_to_report_a_bug

**Comment by avano** [comment]
Hello @romani ,

it's probably an enhancement, not a bug, but here is the info:

Class:

    /tmp/checkstyle :: cat Example.java
    public class Class {
    @org.junit.Rule
    public Rule rule = new Rule();
	
    @org.junit.ClassRule
    public static Rule classRule = new ClassRule();
    }

XML:

    /tmp/checkstyle :: cat checkstyle.xml
    <?xml version="1.0"?>
    <!DOCTYPE module PUBLIC
	"-//Puppy Crawl//DTD Check Configuration 1.3//EN"
	"http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

    <module name="Checker">
	<module name="TreeWalker">
		<module name="VisibilityModifier"/>
	</module>
</module>

Outcome:

    /tmp/checkstyle :: java -jar checkstyle-6.16-all.jar -c checkstyle.xml Example.java
    Starting audit...
    [ERROR] /tmp/checkstyle/Example.java:6:28: Variable 'classRule' must be private and have accessor methods. [VisibilityModifier]
    Audit done.
    Checkstyle ends with 1 errors.

JUnit rule is in the 'whitelist' in VisibilityModifierCheck class:
    
    /** Default ignore annotations canonical names. */
    private static final List<String> DEFAULT_IGNORE_ANNOTATIONS = ImmutableList.of(
        "org.junit.Rule",
        "com.google.common.annotations.VisibleForTesting"
    );

but the ClassRule is not, even if it's the same principle.

What do you think?

**Comment by romani** [comment]
fix is merged, 
thank a lot for full update (code + documentation).
