### ISSUE TITLE
SummaryJavadoc custom period not always working

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#2991]
```
$ cat TestClass.java
public class TestClass
{
    /** test abc */
    void foo3() {}

    /** test . abc */
    void foo4() throws Exception {}
}

$ cat TestConfig.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>

    <module name="TreeWalker">
<module name="SummaryJavadocCheck">
    <property name="period" value="abc"/>
</module>
    </module>
</module>

$ java -jar checkstyle-6.16-all.jar -c TestConfig.xml TestClass.java
Starting audit...
[ERROR] TestClass.java:6: First sentence of Javadoc is incomplete (period is missing) or not present. [SummaryJavadoc]
Audit done.
Checkstyle ends with 1 errors.
```

Use of period as `abc` is just an example of an extreme case. Similar results can be seen with `,` or `!`.
I am expecting no errors because all example JavaDocs end with `abc`.

The issue seems to arise because we switch around using the field `period` and the field `PERIOD`.
https://github.com/checkstyle/checkstyle/blob/b6ab2337e21ed8e4648859eee08026ab5b87953d/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SummaryJavadocCheck.java#L153
This doesn't seem fully related to the other summary javadoc issue.
##

**Comment by romani** [comment]
SummaryJavadocCheck is special Check that follow "javadoc" tool behaviour.

Why you need such functionality ?

Please read: https://github.com/checkstyle/checkstyle/issues/2989#issuecomment-190755819

**Comment by rnveach** [comment]
Like I said this was just an example. You would see this issue with any other replacement set in the period property. Exclamation, comma, unicode period (which the other issue is mainly about), etc.

I am not saying any new functionality is to be added, just that existing one has a flaw when a javadoc contains a true period (`.`) and the user's override of a period through the property.
The check should use the period the user supplies. Otherwise, what is the purpose of the user supplied period if it fails to be identified in this scenario?

**Comment by sagar-shah94** [comment]
I am on it.

**Comment by rnveach** [comment]
I am closing this issue as the problem seems fixed and I get no violations now.

````
$ cat TestClass.java
public class TestClass
{
    /** test abc */
    void foo3() {}

    /** test . abc */
    void foo4() throws Exception {}
}

$ cat TestConfig.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>

    <module name="TreeWalker">
<module name="SummaryJavadocCheck">
    <property name="period" value="abc"/>
</module>
    </module>
</module>

$ java -jar checkstyle-8.4-all.jar -c TestConfig.xml TestClass.java
Starting audit...
Audit done.
````
