### ISSUE TITLE
New CLI option: suppressions no longer needed

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#2995]
While looking over the suppressions file for another issue, I noticed some suppressions from `CommentsTest` that are no longer needed because we refactored them to use the AST printer. https://github.com/checkstyle/checkstyle/blob/25621a3c3391ddf4bc0bb56535d23e73cd293657/config/suppressions.xml#L103-L106
Even though I believe in not using any suppressions, with CS it is apparent suppressions can become a huge list either because of broken/incomplete checks or logic that the coder feels is not warranted in a specific scenario while ok in others.

When fixing suppressions, most of the time the coder knows the suppression exists and that they are fixing it. However, when working on a completely different issue or in a team environment, it is possible a coder can fix a suppression without even knowing about it. Since suppressions hide errors, it is impossible to distinguish an error that is hidden from no error at all.

We have checks for unused imports, so we should have something to find unused suppressions.
We should add a new option to the CLI to help clean up the suppressions file.
When the option is enabled, it should report all suppressions from the file that were never used in the run. The error message should either report the line number the suppression starts at, or some unique way to identify the suppression out of the list.

Some of CS suppressions are multiple files, so it is possible this option won't work with them since one file out of X could report an error. We could discuss splitting one suppression per file.
##

**Comment by romani** [comment]
There was idea to make this as a Check to be part of any build process, rather than cli only.

**Comment by rnveach** [comment]
Closing as duplicate of #3242
