### ISSUE TITLE
fix TokenTypes compatibility problems between 6.15 and 6.16

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#2997]
Commit https://github.com/checkstyle/checkstyle/commit/23e6eba325dd5e56cbe6ccbb58de7d4768fef0f8

damaged compatibility between 6.16 and all previous releases.
checkstyle-6.15-all.jar:/com/puppycrawl/tools/checkstyle/grammars/GeneratedJavaTokenTypes.txt
checkstyle-6.16-all.jar:/com/puppycrawl/tools/checkstyle/grammars/GeneratedJavaTokenTypes.txt

![screenshot-damage-compatibility-6 15-6 16](https://cloud.githubusercontent.com/assets/812984/13478781/934d41fc-e087-11e5-8a45-ea03548fa8db.png)

**Comment by romani** [comment]
We need to find way to prevent this to happen in Future by CI.

**Comment by sabaka** [comment]
And we should add additional comments to grammar with warning, I think. We have something like "put new tokens only in the end", but nothing about deletion.

**Comment by romani** [comment]
Nobody read comments.... UTs should teach future contributor and control us.
