### ISSUE TITLE
Some redundant messages.

### ISSUE THREAD

**Issue by ybbpgfjtey** [checkstyle/checkstyle#3000]
1. As DoubleCheckedLocking check removed in [Release 5.6](http://checkstyle.sourceforge.net/releasenotes_old.html#Release_5.6), message doublechecked.locking.avoid should be removed too;
It belonged to [coding](http://checkstyle.sourceforge.net/config_coding.html) before.

2. Redundant messages in com.putty.tools.checkstyle.metrics : [illegalCatch](https://github.com/search?q=path%3Asrc%2Fmain%2Fresources%2Fcom%2Fpuppycrawl%2Ftools%2Fcheckstyle%2Fchecks%2Fmetrics+filename%3Amessages*.properties+repo%3Acheckstyle%2Fcheckstyle+%22illegalCatch%22), [illegalThrows](https://github.com/search?q=path%3Asrc%2Fmain%2Fresources%2Fcom%2Fpuppycrawl%2Ftools%2Fcheckstyle%2Fchecks%2Fmetrics+filename%3Amessages*.properties+repo%3Acheckstyle%2Fcheckstyle+%22illegalThrows%22), [illegalToken](https://github.com/search?q=path%3Asrc%2Fmain%2Fresources%2Fcom%2Fpuppycrawl%2Ftools%2Fcheckstyle%2Fchecks%2Fmetrics+filename%3Amessages*.properties+repo%3Acheckstyle%2Fcheckstyle+%22illegalToken%22), [illegalType](https://github.com/search?q=path%3Asrc%2Fmain%2Fresources%2Fcom%2Fpuppycrawl%2Ftools%2Fcheckstyle%2Fchecks%2Fmetrics+filename%3Amessages*.properties+repo%3Acheckstyle%2Fcheckstyle+%22illegalType%22), [junit.methodName](https://github.com/search?q=path%3Asrc%2Fmain%2Fresources%2Fcom%2Fpuppycrawl%2Ftools%2Fcheckstyle%2Fchecks%2Fmetrics+filename%3Amessages*.properties+repo%3Acheckstyle%2Fcheckstyle+%22junit.methodName%22), [junit.methodParameters](https://github.com/search?q=path%3Asrc%2Fmain%2Fresources%2Fcom%2Fpuppycrawl%2Ftools%2Fcheckstyle%2Fchecks%2Fmetrics+filename%3Amessages*.properties+repo%3Acheckstyle%2Fcheckstyle+%22junit.methodParameters%22), [junit.methodPublicAndStatic](https://github.com/search?q=path%3Asrc%2Fmain%2Fresources%2Fcom%2Fpuppycrawl%2Ftools%2Fcheckstyle%2Fchecks%2Fmetrics+filename%3Amessages*.properties+repo%3Acheckstyle%2Fcheckstyle+%22junit.methodPublicAndStatic%22), [junit.methodPublicOrProtected](https://github.com/search?q=path%3Asrc%2Fmain%2Fresources%2Fcom%2Fpuppycrawl%2Ftools%2Fcheckstyle%2Fchecks%2Fmetrics+filename%3Amessages*.properties+repo%3Acheckstyle%2Fcheckstyle+%22junit.methodPublicOrProtected%22) and [junit.methodReturnType](https://github.com/search?q=path%3Asrc%2Fmain%2Fresources%2Fcom%2Fpuppycrawl%2Ftools%2Fcheckstyle%2Fchecks%2Fmetrics+filename%3Amessages*.properties+repo%3Acheckstyle%2Fcheckstyle+%22junit.methodReturnType%22).
I didn't see any usage of messages above in [merics](http://checkstyle.sourceforge.net/config_metrics.html)

**Comment by romani** [comment]
second part is not exact, please update description to make it point to exact name of message that is not used.

**Comment by romani** [comment]
fix is merged.

**Comment by trishannhaskett** [comment]
Stop

**Comment by trishannhaskett** [comment]
Stop
