### ISSUE TITLE
ClassNotFoundException when using inherited exception (regression to issue #1192 fix)

### ISSUE THREAD

**Issue by allenhadden** [checkstyle/checkstyle#3008]
Issue #1192 was fixed in Checkstyle 6.8 with this code change:

  https://github.com/checkstyle/checkstyle/commit/18570b7a08376b5b823bd67bfd93b79e0c4fbb1b

Which was later overwritten by this change, which was a fix for issue #1555 (Fix issues reported by IntelliJ IDEA inspections in Checkstyle code):

  https://github.com/checkstyle/checkstyle/commit/80ab48f859c1f16835dbd41afe42414b41969e2f

I'm not exactly sure what the the right answer is here.  It seems that #1555 was complaining "try statements which catch java.lang.Error or any subclass and which do not rethrow the error."  That's good advice generally, but in this case there is a specific case where doing so will result in an issue (#1192).

It seems to me that another option for fixing #1192 would have been to address the underlying NoClassDefFoundError.  Unfortunately I don't know enough about how class loading works in Checkstyle to propose anything.

**Comment by romani** [comment]
fix is merged.

**Comment by allenhadden** [comment]
Wow, thanks for the extremely fast response!
