### ISSUE TITLE
Add New Check: GenericDiamond

### ISSUE THREAD

**Issue by ychulovskyy** [checkstyle/checkstyle#3012]
It would be good to check that developers use Generic diamond operator instead of mentioning types.
E.g.:
```Pair<Integer, String> p1 = new Pair<>(1, "apple");```
instead of
```Pair<Integer, String> p1 = new Pair<Integer, String>(1, "apple");```

**Comment by rnveach** [comment]
Same as issue #2943.

**Comment by ychulovskyy** [comment]
@rnveach closing as Duplicated.
