### ISSUE TITLE
Bad german translation of summary.first.sentence

### ISSUE THREAD

**Issue by MrQNo** [checkstyle/checkstyle#3013]
Using checkstyle (german language), i got a warning "Satz Javadoc ist unvollständig (Zeitraum fehlt) oder nicht vorhanden." I did not understand that info untill i found the english message "period symbol at the end of first javadoc sentence". Period is mistranslated as "time intervall", while there is said "period symbol", and the german word is "Punkt" instead of "Zeitraum".

**Comment by romani** [comment]
please provide PR. Non of maintainers know German, we used google translator to fill missed translations.

**Comment by MrQNo** [comment]
PR means? The sentence should be „Javadoc-Satz ist unvollständig (Punkt fehlt) oder nicht vorhanden.“

**Comment by romani** [comment]
Pull Request. you do not even need to clone and build sources. Just open https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_de.properties#L34 press Edit, save, Pull Request will be sent automatically.

**Comment by romani** [comment]
some problems are fixed, if any new found please open new issue
