### ISSUE TITLE
NPE in CheckUtil#getCheckMessage

### ISSUE THREAD

**Issue by MEZk** [checkstyle/checkstyle#3015]
This is all about test area of our code and how `AllChecksTest.testAllCheckstyleMessages` method works.

'getCheckMessages' method from 'CheckUtil' (from test area of code) class uses 'getResourceAsStream' from Class (java's native library) which loads resource ('messages.properties') as a stream as it is described at http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/8u40-b25/java/lang/Class.java#2215

It means that if we use messages from resource bundle which is not in the same package as the target class, 'getResourceAsStream' does not load the bundle's content (it loads only the content of resource bundle associated with the current class loader). It leads to NPE in 'CheckUtil#getCheckMessage' here:

```java
public static String getCheckMessage(Class<?> module, String messageKey, Object... arguments) {
  ...
  final MessageFormat formatter = new MessageFormat(pr.getProperty(messageKey), Locale.ROOT);
  ...
}
```

Example: there are two property keys ('general.fileNotFound' and 'general.exception') which are used in Tranlation#logIoException. The message resources for the keys are inside ```src/main/resources/com/puppycrawl/tools/checkstyle/messages.properties``` resource bundle. In the current implementation of TranslationCheck we use the keys as string literals, because we cannot extract them to the constants due to NPE in CheckUtil#getCheckMessage and failing of 'testAllCheckstyleMessages' as a result.

**Comment by Vladlis** [comment]
I believe that `general.fileNotFound` and `general.exception` in TranlationCheck shouldn't be constants named `MSG_*`, as they are used for logging exceptions, but not checkstyle violations.

**Comment by rnveach** [comment]
@Vladlis 
> shouldn't be constants named MSG_*, as they are used for logging exceptions

We use `MSG_` for exceptions in atleast one check.
Example:
https://github.com/checkstyle/checkstyle/blob/4ca654c7cbbaad183083a58a99317b24afabac88/src/main/java/com/puppycrawl/tools/checkstyle/JavadocDetailNodeParser.java#L118-L128

If the field is not named `MSG_*`, it can't be required to be placed on the XDOC for the users to know about.
Do the users need to know about and expect this message from the check?

**Comment by romani** [comment]
> Do the users need to know about and expect this message from the check?

No. Exception messages should not be smth that user can change (or we need to hide that possibility in html documentation). We do localization of exception messages only to be more human friendly but user should not reply on them. If such message appear it is a bug in chekcstyle or misconfiguration of checkstyle. IT IS NOT A VIOLATION that could be ignored.

> We use MSG_ for exceptions in atleast one other check.

@rnveach , thanks for pointing to the problem. @Vladlis , please remove "MSG_" prefix from this field in scope of this bug/PR.

**Comment by romani** [comment]
we will not fix this issue. Reason: https://github.com/checkstyle/checkstyle/pull/3051#issuecomment-200329671
