### ISSUE TITLE
Support calculating and reporting metric-like values, not just checking against threshold

### ISSUE THREAD

**Issue by hallvard** [checkstyle/checkstyle#3016]
I am working on a Learning Analytics plugin for Eclipse, that collects and visualises data about coding activities, like line count, test success and failure, use of debugging tools etc. Some of the data is shown in a plot, so you can see how things change over time, and the idea is identify trends and signs of good (or bad) coding habits, breakdowns etc. Checkstyle provides interesting feedback about characteristics of code that affect quality, that would be useful to collect in the same manner. However, checkstyle only gives feedback when a characteristic is within/outside certain limits, and does not report the value(s) themselves, other than in the text message when a rule is violated.

I propose to introduce means for calculating and reporting values within a Check, instead of just logging issues, so that listeners or other tools can provide other kinds of feedback, like plot complexity over time and compare with a benchmark (pre-made solution). It needn't be very complex and can be limited to simple values. E.g. a Check could implement a generic interface MeasureCheck<T> with a method T getMeasure() that could be called to collect these measures for all classes and methods in project. Alternatively, AbstractCheck could add a logMeasure method that a Check can use to report interesting values during an audit, related to classes and methods. It should be possible for listeners or other objects to retrieve these values afterwards.

**Comment by romani** [comment]
> However, checkstyle only gives feedback when a characteristic is within/outside certain limits, and does not report the value(s) themselves

http://checkstyle.sourceforge.net/config_metrics.html

please click on links at "Error Messages" section for each Check, we do return actual value and limit to let user see a difference.

> I propose to introduce means for calculating and reporting values within a Check

Sorry, we will not do this. Check are designed only for logging of certain violation events. Checks are NOT general, they are VERY specific to CERTAIN problem.

> E.g. a Check could implement a generic interface MeasureCheck with a method T getMeasure() that could be called to collect these measures for all classes and methods in project.

Sorry, we will never do this.

>  AbstractCheck could add a logMeasure method that a Check can use to report interesting values during an audit, related to classes and methods.

We will not do this. You need to create custom Checks and do logging in a format that you need for your tool. Yes, you need make custom Audit class to process them.

>  It should be possible for listeners or other objects to retrieve these values afterwards.

Yes, you need to create custom Audit classes to convert String events to your tool format. We will not change anything in checkstyle in a format of log event. It will be string, content of this String is up to you.

------------------

I am closing this issue, if you need to discuss how to make custom Checks please be welcome at https://groups.google.com/forum/#!forum/checkstyle-devel
