### ISSUE TITLE
FallThrough: add report on last case in switch

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#3029]
````
$ cat TestClass.java
public class TestClass {
    void method() {
        int a = 0;

        switch (a) {
        case 0:
            int b = 0;
        case 1:
            int c = 0;
        }
    }
}

$ cat TestConfig.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>

    <module name="TreeWalker">
<module name="FallThrough">
<property name="reliefPattern" value="\$FALL-THROUGH\$" />
</module>
    </module>
</module>

$ java -jar checkstyle-6.16-all.jar -c TestConfig.xml TestClass.java
Starting audit...
[ERROR] TestClass.java:8:9: Fall through from previous branch of the switch statement. [FallThrough]
Audit done.
Checkstyle ends with 1 errors.
````

I was expecting a similar error message for line 10.

Even though the last case isn't falling into another case statement, I consider the reason for "FallThrough" is to make sure **every case** ends with some type of exit (return, throw, break, etc) so when you add a new case anywhere (top, bottom, above another case), you aren't adding the possibility of a fall through bug.
That example shows that the last case doesn't follow that strictly. If a coder just added a new case onto the end of the switch in the example, it would then create a fall through and get reported then. So reporting it earlier helps alleviate some future concerns.

**Comment by romani** [comment]
I am sure it is done on purpose as "break" at the last CASE stylish option , but useless extra line of code. Name of the Check is focused on particular problem detection. 
If you need to enforce that style - new Check need to be created.
Creation of extra option like "reportMissedBreakAtLastCase" will looks strange as it is not FallThrough problem. 

> So reporting it earlier helps alleviate some future concerns.

I am not sure that is right. This Check is not a stylish validation is it potential problem detector.

**Comment by rnveach** [comment]
Yes, it is more stylish when a change is not expected, but chances are it will be a problem if left untreated in the future. It will be a problem if you don't add in the break with new cases on the end of the switch.
I don't feel it is useless, just like `final` on variables serves a purpose, style and non-style.

@romani I am closing this because it actually is already fixed as an additional property of this check. I'm sorry I missed it before opening the issue.
````
$ cat TestClass.java
public class TestClass {
    void method() {
        int a = 0;

        switch (a) {
        case 0:
            int b = 0;
break;
        case 1:
            int c = 0;
        }
    }
}

$ cat TestConfig.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>

    <module name="TreeWalker">
<module name="FallThrough">
<property name="reliefPattern" value="\$FALL-THROUGH\$" />
<property name="checkLastCaseGroup" value="true" />
</module>
    </module>
</module>

$ java -jar checkstyle-6.16-all.jar -c TestConfig.xml TestClass.java
Starting audit...
[ERROR] TestClass.java:9:9: Fall through from the last branch of the switch statement. [FallThrough]
Audit done.
Checkstyle ends with 1 errors.
````
