### ISSUE TITLE
UnnecessaryParenthesesCheck: allow parentheses around non-identifier return values

### ISSUE THREAD

**Issue by crm416** [checkstyle/checkstyle#3047]
The `UnnecessaryParenthesesCheck` will flag lines like:

```
return (x + 1); // parens around return value
...
return (x == 1); // parens around return value
...
```

And so forth.

However, the parentheses in this case can improve readability, as they make it immediately clear that the return type is, say, a `boolean`, rather than the type of `x`.

Ideally, the check would provide an option to allow parentheses around expressions that are being `return`ed (but would still flag parentheses around identifiers, e.g., `return (x)`).

P.S. Happy to submit a PR for this if others agree that it would be useful.
##

**Comment by romani** [comment]
Please provide more details and strict examples of cases where violation is excepted by you and where it is not. 
The best examples are examples of real code.

FYI: you can use checkstyle-tester(https://github.com/checkstyle/contribution/tree/master/checkstyle-tester) tool to generate HTML report of violations on current Check and point to cases where it is too strict. All instructions in its README file.

**Comment by romani** [comment]
no details from author, issue is closed as incomplete.
