### ISSUE TITLE
false positive spacing warning when using double curly brace notation

### ISSUE THREAD

**Issue by mcandre** [checkstyle/checkstyle#3056]
Checkstyle presents spurious warnings about spacing when I use double brace initialization syntax.

http://c2.com/cgi/wiki?DoubleBraceInitialization
##

**Comment by MEZk** [comment]
@mcandre 
Please, provide additional information in accordance with http://checkstyle.sourceforge.net/report_issue.html in order to help us to fix issue quickly.

**Comment by romani** [comment]
@mcandre , please report issue in proper way, you already reported similar issue - https://github.com/checkstyle/checkstyle/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+double+curly+brace

**Comment by romani** [comment]
no details from author, issue is closed as incomplete.
