### ISSUE TITLE
java9: module-info.java files support

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#3059]
http://openjdk.java.net/projects/jigsaw/doc/lang-vm.html#jigsaw-1

http://hg.openjdk.java.net/jdk9/dev/jdk/rev/b2a69d66dc65

> 8142968: Module System implementation Summary: Initial integration of JEP 200, JEP 260, JEP 261, and JEP 282 

File:
http://hg.openjdk.java.net/jdk9/dev/jdk/file/b2a69d66dc65/src/jdk.naming.rmi/share/classes/module-info.java

```
/var/tmp/jdk9 $ java -jar checkstyle-6.17-SNAPSHOT-all.jar -c my_check.xml src
Starting audit...
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing src/jdk.naming.rmi/share/classes/module-info.java
    at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:319)
    at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:275)
    at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:318)
    at com.puppycrawl.tools.checkstyle.Main.main(Main.java:148)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: NoViableAltException occurred during the analysis of file src/jdk.naming.rmi/share/classes/module-info.java.
    at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:195)
    at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:80)
    at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:339)
    at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:309)
    ... 3 more
Caused by: /var/tmp/jdk9/src/jdk.naming.rmi/share/classes/module-info.java:26:1: unexpected token: module
    at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.compilationUnit(GeneratedJavaRecognizer.java:181)
    at com.puppycrawl.tools.checkstyle.TreeWalker.parse(TreeWalker.java:441)
    at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:177)
    ... 6 more
Checkstyle ends with 1 errors.

/var/tmp/jdk9 $ cat /var/tmp/jdk9/src/jdk.naming.rmi/share/classes/module-info.java
/*
 * Copyright (c) 2014, 2015, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */

module jdk.naming.rmi {
    requires java.naming;
    requires java.rmi;
    provides javax.naming.spi.InitialContextFactory
        with com.sun.jndi.rmi.registry.RegistryContextFactory;

    // temporary export until NamingManager.getURLContext uses services
    exports com.sun.jndi.url.rmi to java.naming;
    exports com.sun.jndi.rmi.registry to java.rmi;
}
```
##

**Comment by romani** [comment]
what we could do for now is to update grammar and completely ignore content/block of this `module` keyword.

**Comment by romani** [comment]
workaround is not possible. pre-validation Filter is the only way to resolve this problem for now.

**Comment by rnveach** [comment]
@romani file filters was added to skip `module-info.java`.
Unless we are going to try to parse this files with a new grammar, I think this issue can be closed.

**Comment by marschall** [comment]
Not sure if a new grammar would be easy, the issue is that parsing module-info.java needs a look ahead because `module`, `exports` and `requires` are not keywords. The following file is syntactically valid

```java
module module {
    requires requires;
    exports exports;
}
```

**Comment by heruan** [comment]
I migrated to Java 9 and I'm affected by this issue: Checkstyle fails on `module-info.java` files. I do not find documentation about "exclusions", where do I have to look?

**Comment by rnveach** [comment]
@heruan Check out http://checkstyle.sourceforge.net/config_filefilters.html#BeforeExecutionExclusionFileFilter . It specifically  talks about module-info and JDK9.

**Comment by docrjp** [comment]
@rnveach could we get the exclusion filter to be usable from TreeWalker and JavadocPackage, since these are the affected modules? Right now I have to exclude module-info.java from everything at the Checker level. But the FileTabCharacter module, which has Checker as a parent, works perfectly with module-info.java files.

**Comment by rnveach** [comment]
@docrjp You would have to open a new issue on this as `BeforeExecutionExclusionFileFilter` excludes all modules from running the specific files.

**Comment by delanym** [comment]
What exactly is the `NoViableAltException`? There's no indication you're using ANTLR under the hood, but there's a grammar for Java 20 now if you are https://github.com/antlr/grammars-v4/blob/master/java/java20/Java20Lexer.g4

**Comment by rnveach** [comment]
> There's no indication you're using ANTLR under the hood

https://github.com/checkstyle/checkstyle?tab=readme-ov-file#licensing
https://github.com/checkstyle/checkstyle/blob/master/RIGHTS.antlr
https://github.com/checkstyle/checkstyle/blob/master/pom.xml#L294

**Comment by delanym** [comment]
I meant in the stacktrace. So can you fix it now?

**Comment by delanym** [comment]
Can you reopen the ticket at least?
