### ISSUE TITLE
Capture XMLLogger Object from AuditListener

### ISSUE THREAD

**Issue by atomicpages** [checkstyle/checkstyle#3061]
Hi there,

Is it possible to "capture" the `XMLLogger` object from the `AuditListener`? The reason why I'm asking is because I want to somehow funnel that XML object back into my code. I did a good amount of poking around in the Checkstyle source code + documentation and didn't find an easy way to do this without some contrived, hacky solution. Reaching out to the community for some help!

**Comment by romani** [comment]
there is no way to do this.

> `public interface AuditListener    extends EventListener {`
`public class XMLLogger extends AutomaticBean  implements AuditListener {`

XMLLogger is only one possible destination/serialize-er of all events.
AuditListener is interface it can not be object.

next time please use https://groups.google.com/forum/#!forum/checkstyle-devel for discussions.
Issue tracker is only for issues, not a a discussions.
