### ISSUE TITLE
Uncatch exception using maven-checkstyle-plugin 2.17 if divide is the last character in comments including javadocs

### ISSUE THREAD

**Issue by pcolot01** [checkstyle/checkstyle#3062]
The following comment is silently crashing the maven checkstyle  reporting :

> ```
> /**
>  * Incrément le nombre de OG ou OGI dans le contexte et retourne la valeur /
>  *
>  * @param type
>  * @param String type de guillemet (OG ou OGI) /
>  * @return String contenant le numéro courant (ex: 12.1 pour 1er OGI du
>  * 12èem OG)
>  *
>  */
> ```
##

**Comment by romani** [comment]
please update description to be like - http://checkstyle.sourceforge.net/report_issue.html#How_to_report_a_bug

**Comment by romani** [comment]
no details from author, issue is closed as incomplete.
