### ISSUE TITLE
use new checks and new properties from sevntu.checkstyle project 

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#3064]
http://sevntu-checkstyle.github.io/sevntu.checkstyle/#1.20.0

https://github.com/checkstyle/checkstyle/blob/master/config/checkstyle_sevntu_checks.xml
##

**Comment by rnveach** [comment]
@romani We are already using all checks via travis: https://github.com/checkstyle/checkstyle/blob/0844fffc648ef712462ab68c36384ffaf3510483/.travis.yml#L237
Are there any new properties we are missing?

**Comment by romani** [comment]
Old comment need to be removed https://github.com/checkstyle/checkstyle/blob/master/config/checkstyle_sevntu_checks.xml#L98 .

AvoidModifiersForTypes already use 3 options that were new in that release, it is enough.

**Comment by romani** [comment]
Fix is merged
