### ISSUE TITLE
Enforce EndOfLine symbols at the end of  all files in checkstyle repository

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#3072]
reason: http://checkstyle.sourceforge.net/config_misc.html#NewlineAtEndOfFile

I still see it Input files, mostlikely all other non-main files also have them.

I it is ok to create new checkstyle config to cover all files.
##

**Comment by kukreja-vikramaditya** [comment]
I am on it

**Comment by rnveach** [comment]
Fix is merged
