### ISSUE TITLE
Add COMPILATION_UNIT token in Ast Tree, remove EOF token

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#3095]
base on https://groups.google.com/forum/#!topic/checkstyle/4njXEcUsf34

Javadoc claim that root token exists but it does not exists after parsing:
http://checkstyle.sourceforge.net/apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#EOF

ToDo:
investigate a reason why root node was removed from Ast Tree.
remove 
https://github.com/checkstyle/checkstyle/blob/5bf4e04862b6aa897dc295284def928123f1bb6b/config/import-control.xml#L166-L169

**Rationale of update and hints on how to update affected Checks**:
https://github.com/checkstyle/checkstyle/pull/10574#issuecomment-898806357

**Migration note, affecting all xpath queries**:
https://github.com/checkstyle/checkstyle/issues/3095#issuecomment-897257902

**Comment by rnveach** [comment]
GUI creates it's own root
https://github.com/checkstyle/checkstyle/blob/a73ff0890c27cbe8affc1a55f2710a231687bd85/src/main/java/com/puppycrawl/tools/checkstyle/gui/ParseTreeTablePresentation.java#L257-L261

**Comment by nmancus1** [comment]
Proposed result:

```bash

➜  src cat Test.java
package com.puppycrawl.tools.checkstyle.grammar.antlr4;

import java.io.BufferedReader;
import java.io.FileNotFoundException;

public class Test {}

@interface NonNull{}

➜  src javac Test.java

➜  src java -jar ~/IdeaProjects/checkstyle/target/checkstyle-8.45-SNAPSHOT-all.jar -t Test.java
PACKAGE_DEF -> package [1:0]
|--ANNOTATIONS -> ANNOTATIONS [1:47]
|--DOT -> . [1:47]
|   |--DOT -> . [1:39]
|   |   |--DOT -> . [1:28]
|   |   |   |--DOT -> . [1:22]
|   |   |   |   |--DOT -> . [1:11]
|   |   |   |   |   |--IDENT -> com [1:8]
|   |   |   |   |   `--IDENT -> puppycrawl [1:12]
|   |   |   |   `--IDENT -> tools [1:23]
|   |   |   `--IDENT -> checkstyle [1:29]
|   |   `--IDENT -> grammar [1:40]
|   `--IDENT -> antlr4 [1:48]
`--SEMI -> ; [1:54]
IMPORT -> import [3:0]
|--DOT -> . [3:14]
|   |--DOT -> . [3:11]
|   |   |--IDENT -> java [3:7]
|   |   `--IDENT -> io [3:12]
|   `--IDENT -> BufferedReader [3:15]
`--SEMI -> ; [3:29]
IMPORT -> import [4:0]
|--DOT -> . [4:14]
|   |--DOT -> . [4:11]
|   |   |--IDENT -> java [4:7]
|   |   `--IDENT -> io [4:12]
|   `--IDENT -> FileNotFoundException [4:15]
`--SEMI -> ; [4:36]
CLASS_DEF -> CLASS_DEF [6:0]
|--MODIFIERS -> MODIFIERS [6:0]
|   `--LITERAL_PUBLIC -> public [6:0]
|--LITERAL_CLASS -> class [6:7]
|--IDENT -> Test [6:13]
`--OBJBLOCK -> OBJBLOCK [6:18]
    |--LCURLY -> { [6:18]
    `--RCURLY -> } [6:19]
ANNOTATION_DEF -> ANNOTATION_DEF [8:0]
|--MODIFIERS -> MODIFIERS [8:0]
|--AT -> @ [8:0]
|--LITERAL_INTERFACE -> interface [8:1]
|--IDENT -> NonNull [8:11]
`--OBJBLOCK -> OBJBLOCK [8:18]
    |--LCURLY -> { [8:18]
    `--RCURLY -> } [8:19]
EOF -> <EOF> [9:0]

```

**Comment by rnveach** [comment]
@nmancus1 You can check how the GUI does this from the code snippet I provided, but I was under the impression we are talking about a root node, meaning all nodes will have this as a parent. To me, I don't see a benefit to having a final node in the tree.

**Comment by nmancus1** [comment]
This matches the GUI:

```bash
➜  src cat Test.java


public class Test {

}

➜  src java -jar ~/IdeaProjects/checkstyle/target/checkstyle-8.45-SNAPSHOT-all.jar -t Test.java
EOF -> ROOT [3:0]
`--CLASS_DEF -> CLASS_DEF [3:0]
    |--MODIFIERS -> MODIFIERS [3:0]
    |   `--LITERAL_PUBLIC -> public [3:0]
    |--LITERAL_CLASS -> class [3:7]
    |--IDENT -> Test [3:13]
    `--OBJBLOCK -> OBJBLOCK [3:18]
        |--LCURLY -> { [3:18]
        `--RCURLY -> } [5:0]

```

![image](https://user-images.githubusercontent.com/31252532/127324220-f7cd071b-1ab9-41a5-988d-ffabe1d824d4.png)


However, this doesn't really make any sense; EOF condition for this particular file is at 6:0. I do not understand why we specify that the `EOF` token is the root of the AST; neither the new or old grammar reflects this:

Old grammar:
```antlr

compilationUnit
    :    // A compilation unit starts with an optional package definition
        // semantic check because package definitions can be annotated
        // which causes possible non-determinism in Antlr
        (    (annotations "package")=> packageDefinition
        |    /* nothing */
        )

        // Next we have a series of zero or more import statements
        ( options{generateAmbigWarnings=false;}:importDefinition )*

        // Wrapping things up with any number of class or interface
        //    definitions
        ( typeDefinition )*

        EOF!
    ;

```

New grammar:

```antlr
compilationUnit
    : packageDeclaration? importDeclaration* typeDeclaration* EOF
    ;

```

Furthermore, `EOF` is really not a token, it is a condition.  I think that if anything, I propose that we do the following:

1. Create a new token, `ROOT` (value could be 1, replacing `EOF` in `TokenTypes`).
2. Update GUI to reflect this.
3. Update AST to add new root node.

Example:

```bash
ROOT -> ROOT [3:0]
`--CLASS_DEF -> CLASS_DEF [3:0]
    |--MODIFIERS -> MODIFIERS [3:0]
    |   `--LITERAL_PUBLIC -> public [3:0]
    |--LITERAL_CLASS -> class [3:7]
    |--IDENT -> Test [3:13]
    `--OBJBLOCK -> OBJBLOCK [3:18]
        |--LCURLY -> { [3:18]
        `--RCURLY -> } [5:0]

```

![image](https://user-images.githubusercontent.com/31252532/127327132-8feca6b5-4297-4cd3-be16-1be49dd318f3.png)

We could also make the root node be called `Compilation Unit` to match JLS and our Java grammar, but I think that name is longer than it should be and doesn't really add anything here.

Though this will be technically be a "breaking change', since we never included the `EOF` token anyway, I don't foresee replacing the `EOF` token with `ROOT` as being a problem.

If we agree, let's change the issue description to match this proposal, i.e. something like "No ROOT token in AST".

**Comment by nmancus1** [comment]
@strkkk @pbludov @esilkensen please share your thoughts.

**Comment by romani** [comment]
Nobody use our UI except of occasional developer who likes UI better than cli. 

Modification in UI is not breaking compatibility.

Let's have a ROOT node and deprecate EOF.
As we never supported EOF, we can just rename EOF to ROOT.

**Comment by strkkk** [comment]
COMPILATION_UNIT sounds better to me than ROOT

**Comment by nmancus1** [comment]
Let's vote then, 👍 for `ROOT`, and 🚀 for `COMPILATION_UNIT`. Example with `COMPILATION_UNIT`:

```bash


[8:48:19] ➜  src cat Test.java
import java.util.List;

public class Test {
}

record MyRecord() {

}

interface MyInterface{}
;

➜  src java -jar ~/IdeaProjects/checkstyle/target/checkstyle-8.45-SNAPSHOT-all.jar -t Test.java
COMPILATION_UNIT -> COMPILATION_UNIT [1:0]
|--IMPORT -> import [1:0]
|   |--DOT -> . [1:16]
|   |   |--DOT -> . [1:11]
|   |   |   |--IDENT -> java [1:7]
|   |   |   `--IDENT -> util [1:12]
|   |   `--IDENT -> List [1:17]
|   `--SEMI -> ; [1:21]
|--CLASS_DEF -> CLASS_DEF [3:0]
|   |--MODIFIERS -> MODIFIERS [3:0]
|   |   `--LITERAL_PUBLIC -> public [3:0]
|   |--LITERAL_CLASS -> class [3:7]
|   |--IDENT -> Test [3:13]
|   `--OBJBLOCK -> OBJBLOCK [3:18]
|       |--LCURLY -> { [3:18]
|       `--RCURLY -> } [4:0]
|--RECORD_DEF -> RECORD_DEF [6:0]
|   |--MODIFIERS -> MODIFIERS [6:0]
|   |--LITERAL_RECORD -> record [6:0]
|   |--IDENT -> MyRecord [6:7]
|   |--LPAREN -> ( [6:15]
|   |--RECORD_COMPONENTS -> RECORD_COMPONENTS [6:16]
|   |--RPAREN -> ) [6:16]
|   `--OBJBLOCK -> OBJBLOCK [6:18]
|       |--LCURLY -> { [6:18]
|       `--RCURLY -> } [8:0]
|--INTERFACE_DEF -> INTERFACE_DEF [10:0]
|   |--MODIFIERS -> MODIFIERS [10:0]
|   |--LITERAL_INTERFACE -> interface [10:0]
|   |--IDENT -> MyInterface [10:10]
|   `--OBJBLOCK -> OBJBLOCK [10:21]
|       |--LCURLY -> { [10:21]
|       `--RCURLY -> } [10:22]
`--SEMI -> ; [11:0]
 

```

After thinking on this some more, I think that we should use `COMPILATION_UNIT`: though it is a longer token name, it makes sense to keep naming consistent across grammar/ parser/ JLS/ tokens. `COMPILATION_UNIT` is no longer than some other more frequently used token names, such as `FORMAL_PARAMETERS`  and `RECORD_COMPONENTS`.

**Comment by romani** [comment]
ok, looks like majority on COMPILATION_UNIT , I do not mind , let make it like this.

**Comment by nmancus1** [comment]
**This is a breaking change for XPath users that check top level nodes.**

As a migration note: for any XPath queries that use a top level node as the first node in the query will need to either preface the query with `/COMPILATION_UNIT`, or use the `//` (/descendant-or-self::node()/) operator to find the desired node at any level in the AST.

**The `//` operator should be used with care; this will match a descendant at ANY level of the AST.**

Example:

`/CLASS_DEF` -> `/COMPILATION_UNIT/CLASS_DEF` or  `//CLASS_DEF`

`/PACKAGE_DEF` -> `/COMPILATION_UNIT/PACKAGE_DEF` or `//PACKAGE_DEF`

**Comment by rnveach** [comment]
Fix was merged.
