### ISSUE TITLE
IndentationCheckTest: 'exp' in input files are out of sync with test

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#3105]
Indentation's test currently isn't validating that the expected column warnings (`exp:XXX`) in the input file match what are in the test file and flagged by the check. All we do is make sure they exist and that is it, so this is causing the 2 to be out of sync.

We should enforce a 3 way compare between the test's, the check's, and the input's violations or remove the expected column positions from the input and stick to a 2 way compare between the test and the check.

We still write the expected columns even if there is no violation, making it impossible to validate that they are correct. So unless we make changes to the check to validate them, we should atleast remove them for the non-warnings.

Example:

https://github.com/checkstyle/checkstyle/blob/ccdc3c09c500ccd31d56e4d6ed9c2d86edf2e9f1/src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java#L902

> final String fileName = getPath("InputInvalidClassDefIndent.java");
> ...
> "145: " + getCheckMessage(MSG_ERROR, "}", 6, 8),

https://github.com/checkstyle/checkstyle/blob/ccdc3c09c500ccd31d56e4d6ed9c2d86edf2e9f1/src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/InputInvalidClassDefIndent.java#L145

> }); //indent:6 exp:8,12 warn

Test file warns expect the column to be "8", but input file has written that it expects the columns to be "8, 12". It should just be "8" like the test file.

**Comment by romani** [comment]
> We should enforce a 3 way compare between the test's, the check's, and the input's violations 

for such Check - IndentationCheck. We should be as strict/exact as possible. Lets do 3 way comparison.

**Comment by rnveach** [comment]
@romani Do we want to do something about the multiple expectations with no warning that we can't currently validate at all?

Example: https://github.com/checkstyle/checkstyle/blob/ccdc3c09c500ccd31d56e4d6ed9c2d86edf2e9f1/src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/InputInvalidClassDefIndent.java#L149
> { //indent:8 exp:8,12

We can't validate the 12 is allowed too unless we plug into the Check's logic when it calculates and checks the allowed positions.
We only get the ones for warnings because it is part of the error message.

**Comment by rnveach** [comment]
While working on the first part, it seems to have uncover a hidden bug in one of our tests:

https://github.com/checkstyle/checkstyle/blob/ccdc3c09c500ccd31d56e4d6ed9c2d86edf2e9f1/src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/InputInvalidAnonymousClassIndent.java#L28
> }}}); //indent:16 exp:17 warn

CS Violation is: `InputInvalidAnonymousClassIndent.java:28: 'method def rcurly' have incorrect indentation level 17, expected level should be one of the following: 12, 16.`

CS reports indentation to be 17, when it is in fact 16. I can't temporarly fix the input file as then the input file checker flags it as being inconsistent since it sees the indentation as 16.

**Comment by romani** [comment]
@rnveach ,

> We only get the ones for warnings because it is part of the error message.

we need to care about warning cases only. All other is just for information. Such comments were created as they help to understand current indentation. "exp" part most likely created automatically. We could remove it now if it make problem for us.

> CS reports indentation to be 17, when it is in fact 16. I can't temporarly fix the input file to say indent is 17 as then the input file checker flags it as being inconsistent since it sees the indentation as 16.

please open issue on this and remove this case from input(by separate commit). On issue completion such case need to be restored(commit reverted).

> This also shows we are not validating the 'indent' against the CS violation,

I am open for proposals.

**Comment by rnveach** [comment]
@romani 

> understand current indentation

You mean indentation logic at the time when the input was written. As with the fixes in my PR, old comments may not have been updated as we made changes to IndentationCheck's logic. There could very well be cases, but I have no proof, were written `exp` doesn't match current logic. 

> I am open for proposals.

This was fixed in the PR.

**Comment by romani** [comment]
> You mean indentation logic at the time when the input was written.

yes. Update was huge when we introduced such model.

> There could very well be cases, but I have no proof, were written exp doesn't match current logic. 

that will good :) , pure bug .

**Comment by rnveach** [comment]
fixes were merged and we will not be validating non-violation comments.
