### ISSUE TITLE
Indentation: multiple try with resource not checked

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#3131]
```
$ cat TestClass.java
public class TestClass //indent:0 exp:0
{ //indent:0 exp:0
    private static void test(String fn) { //indent:4 exp:4
        try (FileInputStream fis = new FileInputStream(fn); //indent:8 exp:8
JarInputStream jis = new JarInputStream(fis, false)) //indent:0 // line 5
        { //indent:8 exp:8
        }
    } //indent:4 exp:4
} //indent:0 exp:0


$ cat TestConfig.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>

    <module name="TreeWalker">
<property name="tabWidth" value="4"/>

    <module name="Indentation">
      <property name="arrayInitIndent" value="4"/>
      <property name="basicOffset" value="4"/>
      <property name="braceAdjustment" value="0"/>
      <property name="lineWrappingIndentation" value="4"/>
    </module>
    </module>
</module>

$ java -jar checkstyle-6.17-all.jar -c TestConfig.xml TestClass.java
Starting audit...
Audit done.
```

I was expecting some type of violation on line 5, like requiring it to be at column 8 or 12, as it doesn't fit at column 0.
##

**Comment by kukreja-vikramaditya** [comment]
I am on it.

**Comment by kukreja-vikramaditya** [comment]
@rnveach 
I'll take it as 12 for now. But what should happen if line wrapping in such a case

```java
public class TestClass //indent:0 exp:0
{ //indent:0 exp:0
    private static void test(String fn) { //indent:4 exp:4
        try (FileInputStream fis = new FileInputStream(fn); //indent:8 exp:8
            JarInputStream jis = new JarInputStream(fis, //indent:12 acceptable 8/12
 false)) //indent:0 // line 6
        { //indent:8 exp:8
        }
    } //indent:4 exp:4
} //indent:0 exp:0

```

In general what can be done about the indentation of line 6? Are there any style guides that give info about such cases? try resources in general

**Comment by rnveach** [comment]
@kukreja-vikramaditya 

> In general what can be done about the indentation of line 6? Are there any style guides that give info about such cases?

Our only guide are IDEs. Many IDEs offer auto-formatting of code. Users will rely on that more than our check for uniformity, especially since they can auto-format the code on save without any action from user.
Please try formatting the example in the 3 major IDEs (Eclipse, NetBeans, IntelliJ) with their default formatters and see how they handle the wrapping and post the results here.
To me, it looks like it should be requested to be indented by `lineWrappingIndentation`.

**Comment by kukreja-vikramaditya** [comment]
(no line wrapping. each diff line)
This is the result of an input file I was working on.
Currently the changes I have made to `TryHandler` can only detect error in the starting line of a resource as in my soln I am detecting differences in `RESOURCE_SPECIFICATION`, `RESOURCES` and `RESOURCE` tokens. If works fine but only compares `RESOURCE` with `RESOURCES` for now. Is something like `checkExpressionSubtree` required too for checking the children of `LITERAL_TRY` in cases of try with resources.

**1. IDEA**
```java
    void method(InputStream is) {
        try (
                BufferedInputStream bis = new BufferedInputStream(is);
                BufferedInputStream bis1 = new BufferedInputStream(is,
                        0);
                BufferedInputStream bis2 = new
                        BufferedInputStream
                        (
                                is
                                ,
                                10)
                ;
                BufferedInputStream
                        bis3
                        =
                        new BufferedInputStream(
                                is,
                                Integer
                                        .parseInt
                                                (
                                                        "123"
                                                )
                        );

        ) {
        } catch (IOException
                e
                ) {
            e.printStackTrace();
        }
    }
```

**2. Netbeans**
```java
    void method(InputStream is) {
        try (
                BufferedInputStream bis = new BufferedInputStream(is);
                BufferedInputStream bis1 = new BufferedInputStream(is,
                        0);
                BufferedInputStream bis2 = new BufferedInputStream(
                        is,
                         10);
                 BufferedInputStream bis3
                = new BufferedInputStream(
                        is,
                        Integer
                                .parseInt(
                                        "123"
                                )
                );) {
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
```

**3. Eclipse**
```java
	void method(InputStream is) {
		try (BufferedInputStream bis = new BufferedInputStream(is);
				BufferedInputStream bis1 = new BufferedInputStream(is, 0);
				BufferedInputStream bis2 = new BufferedInputStream(is, 10);
				BufferedInputStream bis3 = new BufferedInputStream(is,
						Integer.parseInt("123"));

		) {
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
```

**Comment by kukreja-vikramaditya** [comment]
Also check input file at `src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/InputValidTryResourcesIndent.java` 

This file uses indent of 4 for multiline resources (no line wrapping). Is this done because there was no check for something similar? Will this be needed to be updated too?

**Comment by rnveach** [comment]
> It adds \t automatically everywhere

Eclipse by default uses tabs for indentation, instead of spaces.

> This is the result of an input file I was working on.

I got different results on my IDEA. It wouldn't break any lines, but it did line up all `BufferedInputStream` resources like your results.

The basic concensus is, it looks like all IDEs treat the resources as wrapped lines as they are all indented by 8 spaces.
offset of a resource should be `try` position + `lineWrappingIndentation`. offset of wrapped resource should be resource position + `lineWrappingIndentation`.
@romani You agree?

**Comment by kukreja-vikramaditya** [comment]
>UPDATE: The indentaion changes if one of the line in written directrly after the ( in try resources

When the first resource is placed directly after the try, the indentation of other lines changes as well as shown here

```java
     void method(InputStream is) {
        try (BufferedInputStream bis = new BufferedInputStream(is); //indent:16
             BufferedInputStream bis1 = new BufferedInputStream(is,
                     0);
             BufferedInputStream bis2 = new
                     BufferedInputStream
                     (
                             is
                             ,
                             10)
             ;
             BufferedInputStream
                     bis3
                     =
                     new BufferedInputStream(
                             is,
                             Integer
                                     .parseInt
                                             (
                                                     "123"
                                             )
                     );

        ) {
        } catch (IOException
                e
                ) {
            e.printStackTrace();
        }
    }
```

**Comment by kukreja-vikramaditya** [comment]
>offset of a resource should be try position + lineWrappingIndentation. offset of wrapped resource should be resource position + lineWrappingIndentation.


Take example case where the resource itself has wrong indent,
Ex,  line 4
```java
        try ( //indent:8 exp:8
                BufferedWriter writer = Files.newBufferedWriter(outputFilePath, charset); //indent:16 exp:16
               ZipFile zf = new ZipFile( //indent:15 exp:16 warn
                   zipFileName) //indent:19 exp:19? or 20?  warn?
        ) { //indent:8 exp:8
            zf.getName(); //indent:12 exp:12
        } //indent:8 exp:8
```
Similarly if try has wrong indent

Ex
```java
       try ( //indent:7 exp:8 warn
                BufferedWriter writer = Files.newBufferedWriter(outputFilePath, charset); //indent:16 exp:16
               ZipFile zf = new ZipFile( //indent:15 exp:16 warn
                   zipFileName) //indent:19 exp:19? or 20?  warn?
        ) { //indent:8 exp:8
            zf.getName(); //indent:12 exp:12
        } //indent:8 exp:8
```

**Comment by rnveach** [comment]
> Ofcourse I created that line breaking in the first place, but IDEA doesn't convert them into a single line.

That is what I am seeing, IDEA doesn't break/merge lines by default. I assumed yours was which was why I was commenting on how I wasn't seeing your broken up like that, but I understand now that you did it to show its indentation level for various breaks.

>              BufferedInputStream bis1 = new BufferedInputStream(is, //indent:13

I am seeing this behavior as well, it is keeping the 2nd+ resources lined up with first resource in the `try`. Unless @romani specifies otherwise, I am fine for ignoring this for now to keep implementation simple.

> Use first resource's starting column for other resources in that try block ?

No, see my other comment.
> offset of a resource should be try position + lineWrappingIndentation

Subsequent resources should use that same offset that was generated from first.

> Take example case where the resource itself has wrong indent,
>                    zipFileName) //indent:19 exp:19? or 20?  warn?
> Similarly if try has wrong indent, Should indent of next line be 16?

I asked this same question in the PR at https://github.com/checkstyle/checkstyle/pull/4171#issuecomment-293034808 to @romani . I am fine with implementation where requested resource indent is based on requested indentation of `try`, not it's actual position. Same with wrapping the resource, based on requested indentation not actual.
We do base indentation in other areas on actual positions, but I am not sure why. You can see this with wrapping throws list in method definition.

**Comment by romani** [comment]
@kukreja-vikramaditya , thanks a lot for your fix to this not simple problem to the most complicated Check in whole checkstyle.

**Comment by kukreja-vikramaditya** [comment]
@romani @rnveach 
Thanks for helping out!
