### ISSUE TITLE
Proper support for generics in visibility modifier check

### ISSUE THREAD

**Issue by KTannenberg** [checkstyle/checkstyle#3142]
Related to https://github.com/checkstyle/checkstyle/issues/61

Affects: VisibilityModifierCheck

Rationale: Current implementation is not strict enough and would allow to expose some mutable date by wrapping it into immutable class.

Requested:
* Type of generics should be also checked against known immutable classes
 * For example, `Optional<String> keyword` or `ImmutableMap<String, BigDecimal> perfValues` or `ImmutableMap<String, ImmutableSet<Long>> perfSeries` should be considered OK, while `ImmutableMap<String, ArrayList<Long>> perfSeries` should not be considered as immutable field.
* Currently if you add immutable class which happens to have generic type (like `java.util.Optional<>`) check allows you to create public fields with mutable type (although mutability is slightly restricted by container, i.e. `ImmutableSet` or `Optional`)
* It will be nice to have TextArea with automatical word-wrapping instead of TextField in check's configuration window

**Comment by romani** [comment]
@KTannenberg , please report issue like described at http://checkstyle.sourceforge.net/report_issue.html#How_to_report_a_bug

**Comment by romani** [comment]
fix is merged.
