### ISSUE TITLE
UnusedImports: value javadoc tag does not reference imports

### ISSUE THREAD

**Issue by lutovich** [checkstyle/checkstyle#3157]
Javadoc `{@value}` tag can reference static constants and makes constant value appear in the generated javadoc. Constant can be referenced either by fully qualified name `{@value java.util.Calendar#MONTH}` or by relative name `{@value Calendar#MONTH}` when corresponding import is present `import java.util.Calendar;`.

```
$ javac InputUnusedImportWithValueTag.java
$ cat InputUnusedImportWithValueTag.java
import java.util.Calendar; // import is used in javadoc {@value}

public class InputUnusedImportWithValueTag {

    /**
     * Method determines current month as for {@value Calendar#MONTH}.
     *
     * @return index of the current month.
     */
    public int currentMonth() {
        return 1;
    }
}
$ cat config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module PUBLIC
        "-//Puppy Crawl//DTD Check Configuration 1.2//EN"
        "http://www.puppycrawl.com/dtds/configuration_1_2.dtd">

<module name="Checker">
  <module name="TreeWalker">
    <module name="UnusedImports">
      <property name="processJavadoc" value="true"/>
    </module>
  </module>
</module>
$ java -jar checkstyle-6.18-all.jar -c config.xml InputUnusedImportWithValueTag.java
Starting audit...
[ERROR] InputUnusedImportWithValueTag.java:1:8: Unused import - java.util.Calendar. [UnusedImports]
Audit done.
Checkstyle ends with 1 errors.
```
I'd be happy to contribute and fix this issue. Tentative fix: https://github.com/lutovich/checkstyle/commit/25c5b4e5060d8de22d0d12a121960e69d4bdf746.
Please let me know if my help is needed or PR should be created from this branch.

Thanks!

**Comment by romani** [comment]
please update description of issue to be like it is requested at http://checkstyle.sourceforge.net/report_issue.html#How_to_report_a_bug

> I'd be happy to contribute and fix this issue.

contributors are always welcome.
glance through http://checkstyle.sourceforge.net/contributing.html , do PR and follow CI failures (if any).
Ask questions, I will guide you through development process.

**Comment by lutovich** [comment]
@romani updated description and created a PR.

**Comment by romani** [comment]
fix is merged.
