### ISSUE TITLE
Reduce the number of tasks performed by Travis CI

### ISSUE THREAD

**Issue by MEZk** [checkstyle/checkstyle#3159]
Travis CI has too many tasks  (33) to perform now. This increases the server load and is time consuming as we have to wait until all tasks are finished. 

![default](https://cloud.githubusercontent.com/assets/7242568/15055542/da44b02a-1315-11e6-8be9-537c669856e2.PNG)

From my point of view, it will be reasonable to reduce the amount of tasks which are performed by Travis CI. For example, we can move a part of them to [Wercker CI](http://devcenter.wercker.com/index.html). 

**Wercker's characteristics:**

- Supported languages: java, javascript, PHP, Python, Ruby, Goland

- GitHub integration

- support of shell scripts

- .yml support

- webhooks

**Comment by rnveach** [comment]
Not in disagreement on the amount of time it takes for the PR to be validated, but how will moving it from one CI to another reduce this time?

**Comment by romani** [comment]
I do not like wercker works ....

https://app.wercker.com/#checkstyle/checkstyle/build/576de03eefc0c401000122d7?step=576de04c8c574e0001449dd4

Failed tests: 
CheckerTest.testMultipleConfigs:633->BaseCheckTestSupport.verify:126->BaseCheckTestSupport.verify:134->BaseCheckTestSupport.verify:162 error message 0 expected:<...626812/file.java:1: [Missing a header - not enough lines in file].> but was:<...626812/file.java:1: [Header fehlt - Datei hat nicht genug Zeilen].>
 

it has problem with locale testing, it is so unstable in PRs. For now I did not noticed problem in master.

**Comment by romani** [comment]
issue is closed, final note will be addressed at #3314
