### ISSUE TITLE
AnnotationLocation: unclear behavior when annotation is among modifiers

### ISSUE THREAD

**Issue by lutovich** [checkstyle/checkstyle#3164]
Hello,

Here is a minimal test case but the same issue is observed when annotation is among class and method modifiers:

```
$ javac Test.java
$ cat Test.java
public class Test {
    public final @Deprecated Object o = new Object();
}
$ cat config.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
        "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
<module name="Checker">
    <module name="TreeWalker">
        <module name="AnnotationLocation">
            <property name="allowSamelineMultipleAnnotations" value="false"/>
            <property name="allowSamelineSingleParameterlessAnnotation" value="false"/>
        </module>
    </module>
</module>

$ java -jar checkstyle-6.18-all.jar -c config.xml Test.java
Starting audit...
Audit done.
```

I'd expect check to fail for the given code saying `'Deprecated' should be alone on line`.

**Comment by lutovich** [comment]
I've made an opportunistic fix here: https://github.com/lutovich/checkstyle/commit/7beaa7b70184b22710a5cc9809f5ae43e43baec2. Can submit a PR if this issue confirms.

**Comment by romani** [comment]
@lutovich , thanks for issue and ready to use fix.

There is a nuance that worry me and it would be great if you help me prove that.
Review users code from issue #903 . We need to make sure that after merge of you fix we will not introduce strange demand for type annotations.

**Comment by lutovich** [comment]
@romani I've noticed same thing today. `ModifierOrder` rule makes checkstyle fail as expected for the given test. I'll write tests with both `ModifierOrder` and `AnnotationLocation` present and update this issue.

**Comment by lutovich** [comment]
@romani added a test here: https://github.com/lutovich/checkstyle/commit/c84c8c8871f6ebe7b74408dca2024c493a332a5f it works fine before and after my fix.
To create the test i've basically copied all possible type annotations from here: https://dzone.com/articles/java-8-type-annotations
Please, let me know what you think about this test.

**Comment by romani** [comment]
@lutovich,

in your example you have:
`public final @Deprecated Object o = new Object();`

in #903 there is sample : 
`public @Nullable Long getStartTimeOrNull() { ... }`

If we apply your logic case from #903 should be:
```
@Nullable
public Long getStartTimeOrNull() { ... }
```

that is exactly that #903 is want to avoid.
So we have a conflict of Checks due to limitation of checkstyle to distinguish target of annotation (no way to find it).

I would stay with false-negative cases for AnnotationLocation rather than false-positives ModifierOrderCheck.

Let me know if I miss smth.

**Comment by lutovich** [comment]
@romani your are right. this example fails with the proposed fix. combination of `AnnotationLocation` and `ModifierOrderCheck` seem to cover all cases and works fine for me. please feel free to close this issue and thanks for your collaboration.

**Comment by romani** [comment]
Yes, that is why i have "approved" tag not all ideas a good.

But as soon such nuance was misleading for you and hard in decision for me - lets update javadoc and xdoc  to prevent such issues in future.

You are always welcome to make checkstyle better.

**Comment by romani** [comment]
documentation fix is merged.
