### ISSUE TITLE
Pullrequests validation for commit mesage miss some cases

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#3168]
UTs are green - https://travis-ci.org/checkstyle/checkstyle/jobs/129464987
after merge:
failure - https://travis-ci.org/checkstyle/checkstyle/jobs/129475961#L794

validation for "." is unstable.

**Comment by mkordas** [comment]
@romani 
* the link to AUTH-96 doesn't work for me, what is that?
* why do you think that build is unstable? We don't allow dot at the end of commit message

**Comment by rnveach** [comment]
@mkordas 
> why do you think that build is unstable? 

The checks for the PR on that commit are all green, yet it finally failed when it merged with master. The PR should not have passed.
See PR #3167

**Comment by mkordas** [comment]
@rnveach That's indeed interesting, I see there success
```
Running com.puppycrawl.tools.checkstyle.internal.CommitValidationTest

Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.351 sec - in com.puppycrawl.tools.checkstyle.internal.CommitValidationTest
```
while it should have failed obviously...

**Comment by rnveach** [comment]
Some ideas:
* `lastCommits` is an empty array
* `commitMessage` has a hidden character before the end that didn't transfer into master (IE: `.<space>`)

**Comment by romani** [comment]
fix is merged.
