### ISSUE TITLE
CheckstyleAntTask: substitude setConfig(File) with setConfig(String)

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#3185]
base on discussion at #3119 .

having two methods `setConfg(File file)` and `setConfigUrl` (and `setConfigURL`) is unclear for users.

in Checkstyle 8 we need to remove `setConfigUrl` and `setConfigURL` and `setConfig(File file)`
and make new `setConfig(String location)` that works exactly as setConfigUrl.
##

**Comment by rnveach** [comment]
@romani This looks like a Checkstyle 8 candidate.

**Comment by romani** [comment]
fixed in scope of #4449
