### ISSUE TITLE
XDoc Config: create unit test to verify property types and default values

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#3187]
For types:
https://github.com/checkstyle/checkstyle/blob/20506e1ceb2de74c9a85367135be714f8208643f/src/xdocs/config_coding.xml#L1283
We interchange `Type Set` and `list of types`.
https://github.com/checkstyle/checkstyle/blob/20506e1ceb2de74c9a85367135be714f8208643f/src/xdocs/config_coding.xml#L2005
We interchange `boolean`/`Boolean` and `integer`/`Integer` types.
https://github.com/checkstyle/checkstyle/blob/20506e1ceb2de74c9a85367135be714f8208643f/src/xdocs/config_naming.xml#L57
We have improper types, `3` instead of `Integer`.

For default values:
https://github.com/checkstyle/checkstyle/blob/20506e1ceb2de74c9a85367135be714f8208643f/src/xdocs/config_coding.xml#L1789
https://github.com/checkstyle/checkstyle/blob/20506e1ceb2de74c9a85367135be714f8208643f/src/xdocs/config_imports.xml#L54
We interchange blanks with `{}`, `all files`, or `empty list` for sets depending on the context.
https://github.com/checkstyle/checkstyle/blob/20506e1ceb2de74c9a85367135be714f8208643f/src/xdocs/config_javadoc.xml#L524
https://github.com/checkstyle/checkstyle/blob/20506e1ceb2de74c9a85367135be714f8208643f/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocPackageCheck.java#L60
Some default values are wrong.

There will be 2 hurdles with creating a junit for default values:
1) Bean fields must have the same name as the setter, which is what `BeanUtil` sees.
https://github.com/checkstyle/checkstyle/blob/20506e1ceb2de74c9a85367135be714f8208643f/src/main/java/com/puppycrawl/tools/checkstyle/checks/TranslationCheck.java#L190-L191

**Comment by romani** [comment]
@rnveach ,

please move " We use String in the setter for everything, from regular expressions, file locations, to 
custom enumerations." to separate issue, it will not be a just clean up .

**Comment by rnveach** [comment]
I moved it.

**Comment by romani** [comment]
> For types:

is done.

> For default values:

is NOT done yet.

**Comment by romani** [comment]
@rnveach , is smth left as not-fixed here ?

**Comment by rnveach** [comment]
@romani Until we align all types in Issue #3212, we can't fully validate strings.
Right now setters are String type, but are then converted to Patterns and custom enumerations. All we see is String right now, so we can't tell the difference to accurately say if it is a String or something else.

These are the current overrides that need to be removed for full validation:
https://github.com/checkstyle/checkstyle/blob/c58874e1ede888709e54871b297287e56e68432b/src/test/java/com/puppycrawl/tools/checkstyle/internal/XDocsPagesTest.java#L541
https://github.com/checkstyle/checkstyle/blob/c58874e1ede888709e54871b297287e56e68432b/src/test/java/com/puppycrawl/tools/checkstyle/internal/XDocsPagesTest.java#L586

**Comment by romani** [comment]
issue is too big, please split into separate issue (it will be non "miscellaneous" update ) and close this issue.

**Comment by rnveach** [comment]
Closed because issue is split
