### ISSUE TITLE
Developers on Macs are hitting a problem due to tools.jar when using Checkstyle (not even when developing on/contributing to Checkstyle)

### ISSUE THREAD

**Issue by vorburger** [checkstyle/checkstyle#3191]
See https://lists.opendaylight.org/pipermail/odlparent-dev/2016-May/000321.html .. in a project using Checkstyle, we're seeing developers on Macs hitting a problem due to tools.jar:

```
[ERROR] Failed to execute goal
org.apache.maven.plugins:maven-checkstyle-plugin:2.16:check (check-license) on project root: Execution check-license of goal
org.apache.maven.plugins:maven-checkstyle-plugin:2.16:check failed: Plugin org.apache.maven.plugins:maven-checkstyle-plugin:2.16 or one of its dependencies could not be resolved: Could not find artifact com.sun:tools:jar:1.7.0 at specified path /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/../lib/tools.jar -> [Help 1]
```

To me this seems a fairly major problem, do you agree? Note that appears simply when using Checkstyle as a normal dependency (of maven-checkstyle-plugin, but that's not the main point), and NOT just when developing on/contributing to Checkstyle's own code base (which would be minor, if none of you use Macs; I don't either!).

I'll just have a look at the checkstyle pom.xml and see if something could be done about this.

@romani would you potentially consider releasing a 6.16.x maintenance release with a fix, if I contribute one for master? The FLOSS project I'm involved in cannot easily upgrade to 6.19-SNAPSHOT just yet (we're held back because of eCS); and perhaps this fix would be useful for other users as well?

**Comment by vorburger** [comment]
So https://github.com/checkstyle/checkstyle/pull/3193 would be my suggestion how to fix this problem.

Solution inspired by http://stackoverflow.com/questions/3080437/jdk-tools-jar-as-maven-dependency, found via https://bugs.eclipse.org/bugs/show_bug.cgi?id=397293.

**Comment by romani** [comment]
> To me this seems a fairly major problem, do you agree?

please provide strict steps to reproduce a problem.
We have MacOs build on travis (https://travis-ci.org/checkstyle/checkstyle/jobs/131195461)  and it worked fine, one of our contributor was on MacOS , he did not told about any problems with "tools".
I need strict steps to move them to Travis and make sure and in future we will not make problem again.

**Comment by vorburger** [comment]
> please provide strict steps to reproduce a problem.

I actually cannot reproduce this myself personally, but have proposed this change based on analysis of a problem described in thread "[Odlparent-dev] Issue building integration in my Mac" of https://lists.opendaylight.org/pipermail/odlparent-dev/2016-May/thread.html#321. 

My understanding is that it appears that on at least SOME MacOS, even if java.vendor is Oracle Corporation, then tools.jar is in ${java.home}/../Classes/classes.jar instead of in the standard location ${java.home}/../lib/tools.jar. Perhaps you can mention the contributor who is on MacOS here so he can comment? Or cross check this against the MacOs build on travis, somehow? Perhaps it depends on the exact MacOS and/or java version - I recalled having read somewhere when researching this yesterday that this changed at some point. Clearly others have had similar problems with locating tools.jar though, see links above.

I won't be able to offer more help, but have emailed the original person who's using a Mac and had this issue to engage here.

**Comment by vorburger** [comment]
Closing this issue, as it turns out the only problem here was "between the chair and the screen" (the person having this problem on MacOS simply had a wrong JAVA_HOME set; see https://lists.opendaylight.org/pipermail/odlparent-dev/2016-May/000328.html)

Very sorry for the confusion raised by this!
