### ISSUE TITLE
CONTRIBUTING.md file documenting expected commit message format

### ISSUE THREAD

**Issue by vorburger** [checkstyle/checkstyle#3194]
Hi, if you would like more people to contribute to Checkstyle, perhaps you would like to have a CONTRIBUTING.md file at the root of this repository? That then shows up on top when people raise PRs on GitHub. See this https://help.github.com/articles/setting-guidelines-for-repository-contributors/ documentation.

This would be somewhat better than PR builds failing with the CommitValidationTest (cool idea though! and easy to run that locally - I would document that in your CONTRIBUTING.md ...).

**Comment by romani** [comment]
@vorburger , thanks a lot for notifying about this feature. I remember that I reported such feature-request to github but missed its announcements.

We need this for:
- commit format, 
- PR description format, 
- how to report the issue/feature request, ..... .

I will read more about this github feature.

**Comment by romani** [comment]
fixed by df9e190c52a706dba9bd5bb86a39285e160d2063 and d11a606888aa7799d3a28ad0ccaa85faa7eba220

further suggestions to improve please do by PRs :).

**Comment by vorburger** [comment]
Will do (PR) ;-)
