### ISSUE TITLE
Broken encoding in Checkstyle's output with user-defined violation message

### ISSUE THREAD

**Issue by MEZk** [checkstyle/checkstyle#3197]
As it is described in [documentation](http://checkstyle.sourceforge.net/config.html#Custom_messages) It is possible to specify user-defined violation messages. Nevertheless, if user defines his own message, for example, in Russian, Checkstyle will print message with broken encoding into output.

Test.java
```java
public class Test {
	public static void main(String[] args) {
		System.out.println("Hello, World!");
	}
}
```

checkstyle_test_config.xml
```xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
  <module name="TreeWalker">
      <module name="UncommentedMain">
        <message key="uncommented.main"
          value="Следует комментировать метод main в коде."/>
  </module>
  </module>
</module>
```

run command:
```
java -jar checkstyle-6.18-all.jar -c checkstyle_test_config.xml Test.java
```

Console output:
```
C:\Users\Andrei\Desktop\Test>java -jar checkstyle-6.18-all.jar -c checkstyle_test_config.xml Test.java
Starting audit...
[ERROR] C:\Users\Andrei\Desktop\Test\Test.java:2: ╨б╨╗╨╡╨┤╤Г╨╡╤В ╨║╨╛╨╝╨╝╨╡╨╜╤В╨╕╤А╨╛╨▓╨░╤В╤М ╨╝╨╡╤В╨╛╨┤ main ╨▓ ╨║╨╛╨┤╨╡. [UncommentedMain]
Audit done.
Checkstyle ends with 1 errors.
```

OS: Windows 8.1
Java: 
```
java version "1.8.0_77"
Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
Java HotSpot(TM) 64-Bit Server VM (build 25.77-b03, mixed mode)
```

I'm able to reproduce the problem on WIndows. There is no problem on Ubuntu 14.04 LTS.

**Comment by rnveach** [comment]
I get similar results when running in the command prompt on Windows 7 with Java 1.7.0_40.
When running in Eclipse, the output is correct.
`chcp 65001` didn't help in the command prompt.

Another possibility is this: http://stackoverflow.com/questions/20386335/printing-out-unicode-from-java-code-issue-in-windows-console/20387039#20387039
but I haven't tried it yet.

**Comment by rnveach** [comment]
@MEZk 
I got it to work for me.
It turns out besides enabling `chcp 65001` (UTF-8 code page), you also have to set the console's font to `Lucida Console` (Do Alt-Space to get the menu, click properties, and select the font tab).


I tried adding displays to `ConfigurationLoader`, where we are getting the value from the config, and nothing I did would print the Unicode correctly without those 2 settings. Even when I did a pure `System.out` of just the string literal.

**Comment by romani** [comment]
I think such issue should be closed, @MEZk , please do.

**Comment by MEZk** [comment]
@rnveach 

Setting font to Lucida Console as IntelliJ IDEA's terminal font does not help. I still got broken encoding:

```
[ERROR] C:\Work\IDEA_Projects\v.1.18-distribution\Business\src\com\rssl\ikfl\crediting\Offer.java:47: РђР‘Р‘Р Р•Р’Р?РђРўРЈР Рђ. [AbbreviationAsWordInName]
```

My source code has windows-1251 encoding and I set

```xml
<property name="charset" value="windows-1251"/>
```

in my configuration for Checkstyle.

**Comment by rnveach** [comment]
@MEZk 
Sorry, I thought this was for the command prompt as you didn't mention IntelliJ before.
Have you tried this? http://stackoverflow.com/questions/1082343/unicode-characters-appear-as-question-marks-in-intellij-idea-console
