### ISSUE TITLE
Modules and XDocs: changed setter methods to recieve similar types with field type for easier xdoc validation

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#3212]
From Issue #3187 

Affected modules/checks: SuppressWarningsHolder , AtclauseOrderCheck, SingleLineJavadocCheck

To create a JUnit for module's default types we need to know the type we are dealing with to display it correctly. Unfortunately, We use `String` in the setter for everything, from regular expressions, file locations, to custom enumerations.
It might be better if we could align the setter type to the bean's type, using https://github.com/checkstyle/checkstyle/blob/20506e1ceb2de74c9a85367135be714f8208643f/src/main/java/com/puppycrawl/tools/checkstyle/api/AutomaticBean.java#L65.

So we will change bean methods from:

````
void setProperty(String s) {
    field = s.split(",");
}
```

into:

````
void setProperty(String... s) {
    field = s;
}
````

This may break compatibility in areas where original methods weren't code correctly for all weird issues, like https://github.com/checkstyle/checkstyle/pull/3250#issue-158782661 where the setter method wasn't trimming spaces from comma delimited input.

**Comment by romani** [comment]
fix is merged.

**Comment by rnveach** [comment]
@romani What was merged was just for String arrays.
If we want to go all the way for aligning setters so we can fully validate all types for #3187, we need to also do Patterns, enumerations, etc.

**Comment by romani** [comment]
please split this to separate issue, I need to think about this.
It looks reasonable on first sight, but we need to think about this a long lasting approach.
