### ISSUE TITLE
Replace terms in WritingJavadocChecks wiki-page by terms from HTML specification

### ISSUE THREAD

**Issue by baratali** [checkstyle/checkstyle#3218]
https://www.w3.org/TR/html4/
beginning/closing tag -> start/end tag
singleton tag -> empty tag
##

**Comment by sagar-shah94** [comment]
@romani only replacement of following words need to be done?
beginning/closing tag -> start/end tag
singleton tag -> empty tag

**Comment by romani** [comment]
@sagar-shah94 , yes.

**Comment by romani** [comment]
documentation is already fixed.
at http://checkstyle.sourceforge.net/writingjavadocchecks.html there are no reference to bad terms.

But AST structure still have this terms, to fix this antlr file that contains grammar should be fixed and examples as in xdoc file.
but this should be new issue - #4448 .
