### ISSUE TITLE
ClassDataAbstractionCoupling : Add a excludeClassesRegexps property  

### ISSUE THREAD

**Issue by TehBakker** [checkstyle/checkstyle#3234]
I've quite a few check because my classes are creating different Exception.
Would be nice to be able to excluse .*Exception in a pattern like attribut
##

**Comment by timurt** [comment]
I am on it

**Comment by romani** [comment]
fix is merged

**Comment by romani** [comment]
@timurt , for some reason PR was not validated by shippable CI.
Now we have protest failure in our master https://app.shippable.com/github/checkstyle/checkstyle/runs/2147/summary
Please provide fix asap.
Command to test https://github.com/checkstyle/checkstyle/blob/master/shippable.yml#L36
