### ISSUE TITLE
AbstractJavadocCheck should process only doc comments placed before class, interface, constructor, method, or field declarations

### ISSUE THREAD

**Issue by baratali** [checkstyle/checkstyle#325]
From [Javadoc guide](http://docs.oracle.com/javase/7/docs/technotes/tools/windows/javadoc.html#documentationcomments): 
Placement of comments - **Documentation comments are recognized only when placed immediately before class, interface, constructor, method, or field declarations** -- see the class example, method example, and field example. Documentation comments placed in the body of a method are ignored. Only one documentation comment per declaration statement is recognized by the Javadoc tool.

**Comment by romani** [comment]
fix is merged.
