### ISSUE TITLE
Modules and XDocs: changed setter methods to recieve similar types with field type for easier xdoc validation 

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#3255]
Taken from Issue #3212

To create a JUnit for module's default types we need to know the type we are dealing with to display it correctly. Unfortunately, We use String in the setter for everything, from regular expressions, file locations, to custom enumerations.
It might be better if we could align the setter type to the bean's type, using https://github.com/checkstyle/checkstyle/blob/20506e1ceb2de74c9a85367135be714f8208643f/src/main/java/com/puppycrawl/tools/checkstyle/api/AutomaticBean.java#L65.

This issue is specifically to change all `setProperty(String)` methods to `setProject(Type)`, where type are patterns or custom enumerations.
I counted around 10 different types that would need to be added.

```
        cub.register(new PatternConverter(), Pattern.class);
        cub.register(new FileConverter(), File.class);
        cub.register(new UriConverter(), URI.class);
        cub.register(new ServerityLevelConverter(), SeverityLevel.class);
        cub.register(new ScopeConverter(), Scope.class);
```
##

**Comment by romani** [comment]
Yes it is reasonable.

Check are our implementations, they should be able to be created as java beans and used with fully typed parameters. String was used only to simplify customization from XML (strings only format). We already have bunch of converters, we control code that read that XML so we can use custom converters. Users will still use string values in config file to do configuration.

No breaking compatibility is expected.

**Comment by romani** [comment]
I did a merge of first big update for RegExp.
But we need to do additional update, in PR , there was a change:
```
+    public void setFormat(Pattern pattern) {
+        format = pattern.pattern();
+        regexp = pattern;
```

we do not really need to store `format`. We need to get rid of this field. We stored it previously as we need to keep unchanged what user gave us. As we changed String to Pattern, there should stay only one field - that store pattern.

**Comment by rnveach** [comment]
> We stored it previously as we need to keep unchanged what user gave us.

@romani To confirm, some checks use format to display violation. We will keep fields for those instances or replace them with `pattern.pattern()` (which is just a simple getter)? 
Examples:
https://github.com/checkstyle/checkstyle/blob/8888fa5919dc31c6abe07ddc2f5fe0e29f66ef37/src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/AbstractClassNameCheck.java#L126
https://github.com/checkstyle/checkstyle/blob/8888fa5919dc31c6abe07ddc2f5fe0e29f66ef37/src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpCheck.java#L274

**Comment by romani** [comment]
> We will keep fields for those instances or replace them with pattern.pattern() (which is just a simple getter)? 

replace with `pattern.pattern()`, the less fields we have the better.

> Also to confirm, this will involve renaming regexp to format as we need to find the bean to get its value since we have no getters.

I do not follow you, can you send me a link to code. If that is not user property - it is ok to rename to keep name correct.

**Comment by rnveach** [comment]
first post was updated for bean types that need to be moved to referenced issues until API issue can be fixed.

**Comment by romani** [comment]
setters were fixed for mentioned in description Enums. 
Other Enums will be covered in #3543 .
