### ISSUE TITLE
CommitValidationTest.testCommitMessageHasSingleLine to support github default format

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#3266]
Example: https://travis-ci.org/checkstyle/checkstyle/jobs/136760315#L794

Reason: I did merge from web UI. Such format is used by default in github.

I think we need to extend validation to allow such format. I more and more use web ui merge to speed up process.

**Comment by rnveach** [comment]
It looks like commit message is stored as "commit\n\n", if u can confirm.
We should rewrite the test to also be more specific about reason for failure so its easier to track down issues.

I will work on this.

**Comment by romani** [comment]
I can confirm that i did just a merge from web ui. Sing of web ui usage is extra reference of PR number at the end of message - `Issue #3142: Add proper support for generics in VisibilityModifierCheck (#3247)`

**Comment by romani** [comment]
fix is merged.
