### ISSUE TITLE
Investigate pitest tool

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#3271]
Assigned to @Efremenkov .

Pitest: http://pitest.org/quickstart/maven/

Report: http://checkstyle.sourceforge.net/reports/pitest/
Report built for Commit: 5a0a3041650662daace014106bbc82522827e442
Report generation: 4h (in 4thread, full usage of all cores and memory)

Code change:

```
05:44 $ git diff
diff --git a/pom.xml b/pom.xml
index 903337a..d20f4df 100644
--- a/pom.xml
+++ b/pom.xml
@@ -989,6 +989,20 @@
         </execution>
       </executions>
     </plugin>
+    <plugin>
+    <groupId>org.pitest</groupId>
+    <artifactId>pitest-maven</artifactId>
+    <version>1.1.10</version>
+    <configuration>
+        <targetClasses>
+            <param>com.puppycrawl.tools.checkstyle*</param>
+        </targetClasses>
+        <targetTests>
+            <param>com.puppycrawl.tools.checkstyle*</param>
+        </targetTests>
+        <threads>4</threads>
+    </configuration>
+</plugin>
     </plugins>
   </build>
```

command to generate report: `mvn test org.pitest:pitest-maven:mutationCoverage`

report will be at: `firefox target/pit-reports/2016XXXXXXXXX/index.html`

TODO: 
- investigate missed point of UTs, fix them.
- investigate usage in CI to enforce quality of testing in PR
##

**Comment by rnveach** [comment]
Interesting tool.

Description:
> PIT runs your unit tests against automatically modified versions of your application code. When the application code changes, it should produce different results and cause the unit tests to fail. If a unit test does not fail in this situation, it may indicate an issue with the test suite.
> it is actually able to detect whether each statement is meaningfully tested

Description and Examples on how code is modified: http://pitest.org/quickstart/mutators/

Active mutators in CS report: 
*    INCREMENTS_MUTATOR
*    VOID_METHOD_CALL_MUTATOR
*    RETURN_VALS_MUTATOR
*    MATH_MUTATOR
*    NEGATE_CONDITIONALS_MUTATOR
*    INVERT_NEGS_MUTATOR
*    CONDITIONALS_BOUNDARY_MUTATOR

**Comment by rnveach** [comment]
pitest isn't working on Windows with CS (says test suite isn't green but it is) but it works fine on Ubuntu. I opened an issue with them.

> full usage of ... memory

4 gigs of ram + 1 gig swap is not enough, as I kept getting heap errors than the VM died when all the swap was used.
It finished successfully with 6 gigs of ram and swap filled up almost halfway.

Build Time: `[INFO] Total time: 02:43 h` (4 threads)
I did notice alot of timeouts during the process, probably around 400 total.
Other than that, the report looks the same.

**Comment by rnveach** [comment]
With the move to JDK 8, pitest wouldn't work for me anymore. See https://github.com/hcoles/pitest/issues/302 .
Temporary solution to get pitest to work is to switch to ECJ (Eclipse's Java Compiler) as the ASM bug is actually a bug in JDKs that they haven't fixed.

My branch: https://github.com/rnveach/checkstyle/commits/pitest
see `minor: test` and `minor: remove resources for ecj`

**Comment by romani** [comment]
All work is done in scope of #3316
