### ISSUE TITLE
Enable IntellijIdea inspection: 'throw' inside 'finally' block

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#3301]
From IntelijIdea:  `Error handling: 'throw' inside 'finally' block (Errors) (5)`
good explanations: http://programmers.stackexchange.com/questions/188858/throwing-an-exception-inside-finally

Issue is blocked by: https://github.com/cobertura/cobertura/issues/289 

 Details:

```
 src/main/java/com/puppycrawl/tools/checkstyle/api
 LocalizedMessage.java (1)
 src/main/java/com/puppycrawl/tools/checkstyle/checks
 NewlineAtEndOfFileCheck.java (1)
 UniquePropertiesCheck.java (1)
 src/main/java/com/puppycrawl/tools/checkstyle
 PropertyCacheFile.java (2)
```

Example for one file - LocalizedMessage : 

```
 src/main/java/com/puppycrawl/tools/checkstyle/api
 LocalizedMessage.java (1)
424: newBundle() IOException might be thrown inside 'finally' block
```

current code:

```
final Reader streamReader = new InputStreamReader(stream, "UTF-8");
try {
    // Only this line is changed to make it to read properties files as UTF-8.
    resourceBundle = new PropertyResourceBundle(streamReader);
}
finally {
    stream.close();
}
```

Expected code:

```
    try (Reader streamReader = new InputStreamReader(stream, "UTF-8")) {
        // Only this line is changed to make it to read properties files as UTF-8.
        resourceBundle = new PropertyResourceBundle(streamReader);
    }
```

results to:

```
[INFO] --- cobertura-maven-plugin:2.7:check (default) @ checkstyle ---
[INFO] Cobertura 2.1.1 - GNU GPL License (NO WARRANTY) - See COPYRIGHT file
[INFO] Cobertura: Loaded information on 382 classes.
[ERROR] com.puppycrawl.tools.checkstyle.api.LocalizedMessage$Utf8Control failed coverage check. Branch coverage rate of 83.3% is below 100.0%
```
##

**Comment by MEZk** [comment]
@romani 

>[ERROR] com.puppycrawl.tools.checkstyle.api.LocalizedMessage$Utf8Control failed coverage check. Branch coverage rate of 83.3% is below 100.0%

Such code will be transpormed into:

```java
Reader streamReader;
try {
   streamReader = new InputStreamReader(stream, "UTF-8");
}
finally {
  if(streamReader != null) {
     try {
       streamReader.close();
     } catch (Exception ex) {
        throw ex;
     }
  }
}
```

That is why Cobertura is not happy. I remember @Vladlis having similar problems while implementing some UTs.

FYI:
http://stackoverflow.com/questions/21727663/cobertura-java7-try-with-resource
http://stackoverflow.com/questions/17354150/8-branches-for-try-with-resources-jacoco-coverage-possible

**Comment by romani** [comment]
By such code it will suppress original exception from try block. Instead of `throw ex` we need to create new exception and put original exception as suppressed in exception ctor. Such code will be correct but it is too ugly to make it.

I decided to think about it a bit later.

**Comment by MEZk** [comment]
@romani 
No, what I meant was that Cobertura is correct as try-with-rosources will be automatically replaced with the code I had mentioned, so new UTs should be created.

**Comment by romani** [comment]
No matter what it will result to, it is not simple issue, so need to be done separately.

**Comment by romani** [comment]
@Nimfadora , I doubt that we can resolve this now, we are stuck with cobertura usage at it keeps our code at 100% level.
We cannot use try-with-resources till we switch to jacoco, some day in future, as try-with-resources it challenge even for jacoco (it is not done yet).

So lets suppress Idea inspection by `till we switch to jacoco that support try-with-resources`. Commit should have reference to this issue.

**Comment by romani** [comment]
suppress comment is provided

**Comment by ZaheerAhmadDev** [comment]
@romani, As we are now using `jacco` checked locally by enabling the inspection.
`  <inspection_tool class="ThrowFromFinallyBlock" enabled="false" level="ERROR"
                   enabled_by_default="true"/>` 
Now the branch coverage is `100 percent`  as we are now using `jacco`.
Should i send pr for it ????

**Comment by romani** [comment]
@ZaheerAhmadDev, you can try. But test it on local first

**Comment by romani** [comment]
10 years later, fix is merged :)
