### ISSUE TITLE
ClassDataAbstractionCoupling and ClassFanOutComplexity: property to exclude packages

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#3309]
Created: 2004-07-29
Creator: Paul
Private: No

Hi there,

http://checkstyle.sourceforge.net/config_metrics.html#ClassDataAbstractionCoupling

It would be nice to be able to exclude packages from
the Data Abstraction Coupling check. For example the
entire Java SDK packages could be excluded by
specifying java. and javax. to be excluded.

Cheers,
Paul.
Discussion

```
Gunter Blache
2004-08-09
I would like to support the request. Especially when writing
Swing GUI code, you easily surpass the default data
abstraction coupling and class fan out values, although
these values definately make a lot of sense for regular classes.
E.g. a regualar main window uses GUI components JFrame,
JPanel, JButton, JTextField, JMenuBar, JMenu, JMenuItem,
JFileChooser, event handling classes like ActionListener,
WindowListener, MouseListener, models like Document,
ButtonGroup, and the standard classes String, File etc. and
there is just no way around it ( except from breaking this
into multiple classes, but this usually does not make sense )
```
##

**Comment by romani** [comment]
Assigened to @IgorMaksymov

**Comment by soon** [comment]
I am on it

**Comment by soon** [comment]
@romani I'd like to discuss this issue. You said, that it is not very easy issue, but I don't see any problems with it.

All we need to do is to add another parameter like `excludedClasses` and use it in the [`isSignificant`](https://github.com/checkstyle/checkstyle/blob/55aa8cedc60d4faa776d7a36f8ae2d0bed0ada45/src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/AbstractClassCouplingCheck.java#L295) method. The simple check using `startsWith` should work pretty well. Trie (or similar) could also be used for large amount of excluded packages or input classes.

Is my approach right, or I missed something?

**Comment by romani** [comment]
@soon ,
package names should be provided by user in form "java.util" (not "java.util." or "java.util.*").
Package name is identifier without any trailing symbols.

**Comment by romani** [comment]
@soon ,
title of issue is changed, so it is ok to change both classes.

**Comment by romani** [comment]
Fix is merged
