### ISSUE TITLE
display code metrics

### ISSUE THREAD

**Issue by nkv123** [checkstyle/checkstyle#3318]
/var/tmp $ javac YOUR_FILE.java
[[PLACE YOU OUTPUT HERE]]

/var/tmp $ cat YOUR_FILE.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.metropolitan.data_changer.base;

import org.apache.commons.lang3.StringUtils;
import rs.metropolitan.data_changer.AbstactDataSeperator;

/**
 *
 * @author ladmin
 */
public class ToDouble extends NewClass {

    public ToDouble() {
    }

    public ToDouble(String input) {
        super(input);
    }

    @Override
    public String getInput() {
        return super.getInput(); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void setInput(String input) {
        super.setInput(input); //To change body of generated methods, choose Tools | Templates.
    }

    public boolean checking(String data) {
        String dot = ".";
        String beforeDot = StringUtils.substringBefore(data, dot);
        String afterDot = StringUtils.substringBefore(data, dot);
        return StringUtils.isNumeric(beforeDot) && StringUtils.isNumeric(afterDot)
                && StringUtils.countMatches(data, dot) == 1;
    }

    @Override
    public Double changeString(String data) {
        try {
            if (checking(data)) {
                return new Double(data);
            }
            return null;
        } catch (NumberFormatException ex) {
            System.err.print(ex.getLocalizedMessage());
            return null;
        } catch (Exception ex) {
            System.err.print(ex.getLocalizedMessage());
            return null;
        }
    }

    @Override
    public Double changeString() {
        return changeString(super.getInput());
    }

}

/var/tmp $ cat config.xml

<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">

<module name="TreeWalker">
<property name="tabWidth" value="4"/>

<module name="BooleanExpressionComplexity">
<property name="max" value="7"/>
</module>
<module name="ClassDataAbstractionCoupling">

<property name="excludedClasses" value="boolean, byte, char, double, float, int, long, short, void, Boolean, Byte, Character, Double, Float, Integer, Long, Short, Void, Object, Class, String, StringBuffer, StringBuilder, ArrayIndexOutOfBoundsException, Exception, RuntimeException, IllegalArgumentException, IllegalStateException, IndexOutOfBoundsException, NullPointerException, Throwable, SecurityException, UnsupportedOperationException, List, ArrayList, Deque, Queue, LinkedList, Set, HashSet, SortedSet, TreeSet, Map, HashMap, SortedMap, TreeMap, DetailsAST, CheckstyleException, UnsupportedEncodingException, BuildException, ConversionException, FileNotFoundException, TestException"/>
</module>
<module name="ClassFanOutComplexity">
<property name="max" value="25"/>

<property name="excludedClasses" value="boolean, byte, char, double, float, int, long, short, void, Boolean, Byte, Character, Double, Float, Integer, Long, Short, Void, Object, Class, String, StringBuffer, StringBuilder, ArrayIndexOutOfBoundsException, Exception, RuntimeException, IllegalArgumentException, IllegalStateException, IndexOutOfBoundsException, NullPointerException, Throwable, SecurityException, UnsupportedOperationException, List, ArrayList, Deque, Queue, LinkedList, Set, HashSet, SortedSet, TreeSet, Map, HashMap, SortedMap, TreeMap, DetailsAST, CheckstyleException, UnsupportedEncodingException, BuildException, ConversionException, FileNotFoundException, TestException, Log, Sets, Multimap, TokenStreamRecognitionException, RecognitionException, TokenStreamException, IOException"/>
</module>
<module name="CyclomaticComplexity"/>
<module name="JavaNCSS"/>
<module name="NPathComplexity"/>

</module>

</module>
      
/var/tmp $ java -jar checkstyle-X.XX-all.jar -c config.xml YOUR_FILE.java
java -jar checkstyle-7.0-all.jar -c metrics_checks.xml  ToDouble.java
Starting audit...
Audit done.

---------------

copied metrics form checkstyle.xml, just want metrics report in terminal.

--------------

Still not clear ??? - see example - http://checkstyle.sourceforge.net/report_issue.html#How_to_report_a_bug

**Comment by rnveach** [comment]
copy of #3319
