### ISSUE TITLE
how to display code metric?

### ISSUE THREAD

**Issue by nkv123** [checkstyle/checkstyle#3319]
/var/tmp $ javac YOUR_FILE.java
[[PLACE YOU OUTPUT HERE]]

/var/tmp $ cat YOUR_FILE.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.metropolitan.data_changer.base;

import org.apache.commons.lang3.StringUtils;
import rs.metropolitan.data_changer.AbstactDataSeperator;

/**
 *
 * @author ladmin
 */
public class ToDouble extends NewClass {

    public ToDouble() {
    }

    public ToDouble(String input) {
        super(input);
    }

    @Override
    public String getInput() {
        return super.getInput(); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void setInput(String input) {
        super.setInput(input); //To change body of generated methods, choose Tools | Templates.
    }

    public boolean checking(String data) {
        String dot = ".";
        String beforeDot = StringUtils.substringBefore(data, dot);
        String afterDot = StringUtils.substringBefore(data, dot);
        return StringUtils.isNumeric(beforeDot) && StringUtils.isNumeric(afterDot)
                && StringUtils.countMatches(data, dot) == 1;
    }

    @Override
    public Double changeString(String data) {
        try {
            if (checking(data)) {
                return new Double(data);
            }
            return null;
        } catch (NumberFormatException ex) {
            System.err.print(ex.getLocalizedMessage());
            return null;
        } catch (Exception ex) {
            System.err.print(ex.getLocalizedMessage());
            return null;
        }
    }

    @Override
    public Double changeString() {
        return changeString(super.getInput());
    }

}

/var/tmp $ cat config.xml
[metrics_checks.xml.txt](https://github.com/checkstyle/checkstyle/files/335121/metrics_checks.xml.txt)

      
/var/tmp $ java -jar checkstyle-X.XX-all.jar -c config.xml YOUR_FILE.java
java -jar checkstyle-7.0-all.jar -c metrics_checks.xml  ToDouble.java
Starting audit...
Audit done.

---------------

report in terminal 

--------------

Still not clear ??? - see example - http://checkstyle.sourceforge.net/report_issue.html#How_to_report_a_bug

**Comment by rnveach** [comment]
@nkv123 
You never really describe what you want to see in the output, but I take it you want the checks `BooleanExpressionComplexity, ClassDataAbstractionCoupling, ClassFanOutComplexity, CyclomaticComplexity, JavaNCSS, and NPathComplexity` to actually print reports on all your code (IE: specifying class `X,Y,Z` has methods `A,B,C` with a complexity score of `T`). Is that correct?

Our checks only print violations when you go over a certain complexity you place in the configuration file.
None of our checks actually print full reports.
To learn more on each check, I suggest you check out their documentation: http://checkstyle.sourceforge.net/checks.html

**Comment by romani** [comment]
To print all metrics, make all limit properties to minimal values to force Check to violate everithing
