### ISSUE TITLE
new Check: CommentsIndentationCheck 

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#333]
http://google-styleguide.googlecode.com/svn/trunk/javaguide.html#s4.8.6.1-block-comment-style

from whole paragraph looks like only : 
```
Block comments are indented at the same level as the surrounding code. 
They may be in /* ... */ style or // ... style. For multi-line /* ... */ comments, 
subsequent lines must start with * aligned with the * on the previous line.
```
 is a rule and just Indentation validation for single line and multi-line comments.
It might be reasonable to update existing Indentation Check, but I would prefer to keep it separate, lets discuss.

**Comment by MEZk** [comment]
@romani 
The Check throws NPE when running against checkstyle source codes with checkstyle-tester and while use mvn clean verify, but works fine on guava library. I'm trying to resolve these problems.

See [log](https://github.com/MEZk/MEZk.github.io/blob/master/CommentsIndentationLog.txt)

**Comment by MEZk** [comment]
@romani 
I added additional null-check for [nextStatement](https://github.com/alexkravin/checkstyle/blob/CommentsIndentationCheck%23333/src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/CommentsIndentationCheck.java#L142) and [prevBlock.getLastChild()](https://github.com/alexkravin/checkstyle/blob/CommentsIndentationCheck%23333/src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/CommentsIndentationCheck.java#L164) and resolved NPE. I'll send PR when I will  be sure that there are no Exceptions and Errors in the Check.

**Comment by romani** [comment]
ok, all cases should appear in UTs. 
As we detected that problem on Checkstyles code, please add checkstyle code to Travis before PR with fix for that issue.

please generate reports for projects and lets see result, please do PR and we will start code review process.

> It is also necessary to provide international violation messages.

not required, we do not do that for now, you can skip it if you want, but I can not forbid you to do that.

> we should also correct format of } and {.

do all that is required to let that Check merge and test.

**Comment by MEZk** [comment]
@romani 
>As we detected that problem on Checkstyles code, please add checkstyle code to Travis before PR with fix for that issue.

The problem appeared when I added new test input file at IT's resource folder with code which was mentioned above. Travis CI use checkstyle-tester to check  checkstyle's SNAPSHOTS. ITs input files are not excluded, that is why they are checked? Or did I misunderstand something?

**Comment by romani** [comment]
> Or did I misunderstand something?

yes, it was my bad, https://github.com/checkstyle/checkstyle/blob/master/.travis.yml#L78
we already do that. please ignore my request.
