### ISSUE TITLE
Support more tokens in WhitespaceAfter check

### ISSUE THREAD

**Issue by vanniktech** [checkstyle/checkstyle#3333]
Assigned to @MaksimP­

Right now it only supports `COMMA, SEMI, TYPECAST`. I'd love to have support for `LITERAL_IF` that for instance `if(` will be marked as a checkstyle error because it should be `if (`.

Also some other would come in handy:
- LITERAL_IF
- LITERAL_WHILE
- LITERAL_FOR
- LITERAL_DO
- DO_WHILE
- LITERAL_NEW
- LITERAL_ELSE

----------------

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/35632289-support-more-tokens-in-whitespaceafter-check?utm_campaign=plugin&utm_content=tracker%2F500528&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F500528&utm_medium=issues&utm_source=github).

**Comment by eric-milles** [comment]
Currently this is supported using WhitespaceAround.  Do you have a reason to have "if" not preceded by a space?

```xml
        <module name="WhitespaceAround">
            <message key="ws.notPreceded" value="Keyword ''{0}'' should be preceded by a space" />
            <message key="ws.notFollowed" value="Keyword ''{0}'' should be followed by a space" />
            <property name="tokens" value="LITERAL_ASSERT,LITERAL_CATCH,LITERAL_ELSE,LITERAL_FINALLY,LITERAL_FOR,LITERAL_IF,LITERAL_RETURN,LITERAL_SWITCH,LITERAL_SYNCHRONIZED,LITERAL_TRY,LITERAL_WHILE,DO_WHILE" />
        </module>
```

**Comment by vanniktech** [comment]
Uh nice you're right. Thanks a lot! Do you also happen to know if there's a check that flags the following:

```java
    }

}
```

as it should be

```java
    }
}
```

**Comment by eric-milles** [comment]
I don't think there is a specific check.  The way that I have devised is to use multi-line regex checks.  In our case, we have CRLF as the endline sequence, which is leveraged by the latter two of the checks below.

Note: If you use "if (...) {" style followed by a blank line for extra spacing, the first check will not be desirable.  We use braces on their own line most of the time.

```xml
    <module name="RegexpMultiline">
        <property name="message" value="Blank line at start of block should be removed" />
        <property name="format" value="(?&lt;=(?&lt;!^beans )\{\s{0,99}$)^$" />
        <property name="fileExtensions" value="groovy,java" />
    </module>
    <module name="RegexpMultiline">
        <property name="message" value="Blank line at end of block should be removed" />
        <property name="format" value="(?&lt;!\{\s{0,99}$)^$(?=^\s{0,99}\})" />
        <property name="fileExtensions" value="groovy,java" />
    </module>
    <module name="RegexpMultiline">
        <property name="message" value="Blank line before start of block should be removed" />
        <property name="format" value="(?&lt;=[!-:&lt;-~] {0,48}?\r\n {0,48}?)\r\n *(\{|else)" />
        <property name="fileExtensions" value="groovy,java" />
    </module>
    <module name="RegexpMultiline">
        <property name="message" value="Extra blank line(s) should be removed" />
        <property name="format" value="^(?:(?:\r\n){2,}|\r\n$)" />
        <property name="fileExtensions" value="groovy,html,htm,java,jj,jjt,vm,xml,xsl" />
    </module>
```

**Comment by vanniktech** [comment]
@eric-milles thanks man. Very much appreciated. @romani since the functionality I asked for is supported by a different check I'll leave the decision up to you whether this should be implemented or not.

**Comment by rnveach** [comment]
@romani Can you confirm that this is still an approved issue?
I see nothing wrong with adding the tokens, but then why doesn't `WhitespaceAfter` have more things from `WhitespaceAround`.

I don't think `LITERAL_NEW` should be added as it is impossible to write code without a space after `new`. The Java compiler thinks it is a method name and not an  instantiation clause. Ex: `newString()`.

**Comment by romani** [comment]
> Can you confirm that this is still an approved issue?

I am ok to close it, if original author do not need it any more.

> I see nothing wrong with adding the tokens, 

I am still ok to have this issue, as Checks should be independent and user should be able customize them to match his needs.

> why doesn't WhitespaceAfter have more things from WhitespaceAround for space required after token

have no idea, all Checks are independent, and extended/developed by user requests ....

> I don't think LITERAL_NEW should be added as it is impossible to write code without a space after

yes, this literal should not be present. We do not need nonsense. If users find example where it could be used - we will extend it later.

**Comment by romani** [comment]
token `DO_WHILE` was added.

**Comment by romani** [comment]
New tokens could be default as it generally acceptable style.
It is not conflicting with google style http://checkstyle.sourceforge.net/reports/google-java-style.html#s4.6.2-horizontal-whitespace , even this check is not in use at google_checks.xml .

**Comment by vanniktech** [comment]
I'm in favor of making them the default.

**Comment by romani** [comment]
fix is merged.

**Comment by eric-milles** [comment]
Will this generate multiple violations if both WhitespaceAround and WhitespaceAfter are used?

**Comment by romani** [comment]
Check is responsible for his violations. if you have few Checks that do kind of the same you will have multiple violations.

**Comment by eric-milles** [comment]
So, as I indicated, WhatespaceAround already supports all those tokens.  Now you're making them default in WhitespaceAfter when they should probably be optional since they are default in WhitespaceAround.  http://checkstyle.sourceforge.net/config_whitespace.html#WhitespaceAround

Isn't the more common case that you do not allow symbol characters directly adjacent to keywords like if? And so the WhitespaceAround has the more sensible defaults.

**Comment by romani** [comment]
we very very rare consider dependencies between Checks. All of them works like it is only one Check in the configuration.
It is user responsibility to adjust config to receive less duplicates or behavior he likes. 
By the way two violation on the same code is even better, kind of "second opinion".
