### ISSUE TITLE
Support jdk 1.7.x at run-time

### ISSUE THREAD

**Issue by vrozov** [checkstyle/checkstyle#3341]
Apache Apex can't upgrade to checkstyle 7.0 due to jdk 1.8 required at run-time. Please consider adding support for jdk 1.7 back.

**Comment by rnveach** [comment]
My work, which I use CS for and got me into working with CS, uses RAD and WebSphere, which currently only support Java 1.6. We can request 1.7 installed for RAD with some additional work, but it isn't the default and our servers are still only 1.6.
I don't know my work's plans to upgrade to newer Java versions, but I know it took us many years just to get JRE 7. We have restricted computers, so it isn't like I or others can just install 1.8 on it and the issue be over with.

Right now, I downgrade each CS release to Java 1.6 compliance by rebasing my own personal changes in a private repository on top of CS'.
I looked at some [utilities online ](https://en.wikipedia.org/wiki/Java_backporting_tools) that can downgrade byte code but have not specifically tried them. They have their limitations too, as there are also specific `java` packages and classes in CS that are 1.7+ only, which I only just recently ran into when I tried running my 1.6 CS on a machine that didn't have 1.7 installed.

I'm hoping there is some way to support both sides of the coin, future version and backwards compatibility, without a lot of work or manual intervention.

**Comment by romani** [comment]
I do understand community that dropping jdk7 is undesirable. 
My decision about jdk updates are explained - https://groups.google.com/forum/#!topic/checkstyle-devel/nd8rWCtJ7Tg .

it is possible to revert all changes for jdk8 (I tried to keep them compact) and build checkstyle java without tests to make what you need, but this should be done by community. I could help in mail-list with some extra explanations and revert nuances.

We did hundreds of bug fixes in jdk7 version, we used jdk7 more than I planned originally.
Checkstyle team is very tiny, I need to keep project on modern jdk to attract new contributors, new blood to the project. Nobody want to spend hours on ancient stuff, it is not a job, fun should be an incentive to contribute. 

Sorry. I am closing the issue.

**Comment by vrozov** [comment]
Please reconsider or help to bring this topic to the community discussion. It is equally important to attract developers to use checkstyle in their projects. As I mentioned Apache Apex will not be able to upgrade to the latest version of checkstyle where few bugs reported by me were fixed.

**Comment by romani** [comment]
> Please reconsider or help to bring this topic to the community discussion.

I did a lot of social posts and actions to attract attention to help with project, does not really help.

> As I mentioned Apache Apex will not be able to upgrade to the latest version of checkstyle where few bugs reported by me were fixed.

That is rare and unfortunate case. You just came to us too late with your problems. You might find more problems in checkstyle and all of them will be fixed in recent version of checkstyle, without back porting.

**Comment by vrozov** [comment]
I disagree that it is a rare and unfortunate case. Majority and Apache Apex developers are on JDK 1.7 and forcing them to upgrade to JDK 1.8 is not justifiable as we still need to support JDK 1.7 at run-time. IMO, community support comes from a project usage and restricting the usage will not help with attracting new developers or projects in a long run.

**Comment by romani** [comment]
> Majority and Apache Apex developers are on JDK 1.7 and forcing them to upgrade to JDK 1.8 is not justifiable as we still need to support JDK 1.7 at run-time

I am not forcing you to use jdk8 in runtime, checkstyle runtime and Apex runtime is completely different. It is not required to update https://github.com/apache/apex-core/blob/master/pom.xml#L141 to use checkstyle, all you need is too have jdk8 installed (JAVA_HOME is pointing to it) on your PC or CI to run build or verify phase on jdk8 but with target 1.7 (as it is right now). If Apex sources are not compilable on jdk8(with 1.7 as targe), it is smth Apex project have to address, as jdk8 usage is unavoidable eventually.
There are profiles is maven that could activate some plugins is right jdk is detected , ..... there bunch of workarounds.

> IMO, community support comes from a project usage and restricting the usage will not help with attracting new developers or projects in a long run.

kind of yes, but in my experience of managing Checkstyle project it is minor help, the most contributions does not come this way. Maintainers of other open-source projects are too focused on their projects in their minimal spare time (I even in the same position).

-------------------

Resolution: if want jdk7 backports please help me find a person who is ready make it happen.
You do not even need my approval, just do fork, and .... . I would be happy to make note on all our websites that there are jdk7 version and point to that repo.

**Comment by vrozov** [comment]
It will be quite inconvenient for developers not to be able to execute checkstyle plugin before committing their changes and rely on CI to run the full build and verify that new changes follow proper code style. So, basically, it will require every Apex contributor to upgrade to JDK 1.8. As we need to support 1.7 at run-time, such upgrade is not justifiable now as contributors won't be able to use 1.8 Java language constructs in their code.

> Resolution: if you want jdk7 backports please help me find a person who is ready make it happen. You do not even need my approval, just do fork, and .... . I would be happy to make note on all our websites that there are jdk7 version and point to that repo.

I doubt that anyone wants to do the work on a fork. In case, the necessary changes to downgrade to JDK 1.7 will be merged back to the master branch, I will check with Apex community.

**Comment by romani** [comment]
> As we need to support 1.7 at run-time, such upgrade is not justifiable now as contributors won't be able to use 1.8 Java language constructs in their code.

java is designed to work in such way, there could be some problems as hashing algorithm was changed, and some incorrect code will start fail - but it is pure bugs. At my work place we support some java6 projects, but we are using jdk8 for long time (NOT a syntax features of java8, just a jvm).

> I doubt that anyone wants to do the work on a fork.

I do not want to host that backport, as I am not going to support it. 

> In case, the necessary changes to downgrade to JDK 1.7 will be merged back to the master branch

We have too much more serious problems, we will focus on them. Backport will never be merged to master. I do not want to even host them in branch to not be responsible to support them. Jdk7 got his end of life a year ago - http://www.oracle.com/technetwork/java/eol-135779.html , more and more projects are switching to jdk8 . 

> I will check with Apex community.

If smb want to support old stuff - welcome. I could help with some advices.

**Comment by vrozov** [comment]
> java is designed to work in such way, there could be some problems as hashing algorithm was changed, and some incorrect code will start fail - but it is pure bugs of your project. At my work place we support some java6 projects, but we are using jdk8 for long time (NOT a syntax features of java8, just a jvm).

I never said that we can't use JDK 1.8 to compile to 1.7 compatible byte code as long as the source code is at 1.7 level and possibly some developers already have JDK 1.8 installed and use it to compile the Apache Apex project. My point is that forcing all Apache Apex contributors and committers to upgrade their environment to JDK 1.8 simply because it is required for checkstyle plugin is not justifiable at this point.

> Jdk7 got his end of life a year ago - http://www.oracle.com/technetwork/java/eol-135779.html , more and more projects are switching to jdk8 .

Apache Apex is an execution engine and while applications are free to use the latest JDKs, tools (like eclipse, Idea, maven), platforms (Hadoop) and engines (Apex) need to support what community is using and, there is still a large number of java 1.7 and even 1.6 out on the field.

OK, looks like we will have to stay on old version of checkstyle for now. It is sad that the work that was done by checkstyle contributors will not be used by the project that requested those bug fixes and enhancements.

**Comment by romani** [comment]
> OK, looks like we will have to stay on old version of checkstyle for now

yes, please use suppressions over problems that fixed in checkstyle versions that you can not upgrade to. We are even more planning to do serious brake for api in September. So ease of upgrade to new version will demand plugins update, so there will be more problems.

@rnveach told me that he has backport to jdk6, on his side, contact him get access to that version. But I will not approve issue creation on that version (jdk6) in this issue tracker, binaries will not be hosted in the same maven repo.

**Comment by rnveach** [comment]
@vrozov 
I created a repository that holds a Java 6 backport of checkstyle 7 @ https://github.com/rnveach/checkstyle-backport-jre6.
Please try it out using the following in your pom:
````
	<pluginRepositories>
		<pluginRepository>
			<id>checkstyle-backport-jre6-maven</id>
			<name>checkstyle-backport-jre6-maven</name>
			<url>http://rnveach.github.io/checkstyle-backport-jre6/maven2</url>
		</pluginRepository>
	</pluginRepositories>

	<dependencies>
          <dependency>
            <groupId>com.puppycrawl.tools</groupId>
            <artifactId>checkstyle-backport-jre6</artifactId>
            <version>7.0</version>
          </dependency>
	</dependencies>
````

**Comment by vrozov** [comment]
@rnveach, @romani We are not interested in using not official checkstyle release that will not be supported.

**Comment by rnveach** [comment]
@vrozov I will support it by merging in changes from checkstyle for future versions, but any issues that aren't directly related to the backporting will have to be issued against the main checkstyle repo.

**Comment by vrozov** [comment]
@rnveach Thanks for the backport, but it is safer for us to stay on the old version and use exclude rules that are already in place. Switching to unofficial release will require discussion on Apex dev mailing list and approval from the community. As I am against using a version that is not officially supported and that potentially may cause trouble for Apex contributors, I am not even in a position to initiate such discussion (where my vote is -1).
