### ISSUE TITLE
IndentationCheckTest makes assumption about the order of HashMap

### ISSUE THREAD

**Issue by azy2** [checkstyle/checkstyle#3369]
The tests `IndentationCheckTest.testGetRequiredTokens` and `IndentationCheckTest.testGetAcceptableTokens` both use `handlerFactory.getHandledTypes` which internally uses a `HashMap`. HashMap does not guarantee any order of iteration. In these tests however,  the code is assuming that the order of iteration will be the same twice in a row, which can result in test failures.

**Comment by romani** [comment]
@azy2 , good catch.
How did you reproduced this problem ? 
I need this to setup a test on CI avoid such problem in future.

**Comment by azy2** [comment]
I caught these assumptions with a tool called [NonDex](https://github.com/TestingResearchIllinois/NonDex) which I helped develop with a research group at the University Of Illinois. The tool is available as a maven plugin from Maven Central and it is pretty easy to add to your pom and Travis. If you want I can create a pull request integrating it.

**Comment by romani** [comment]
@azy2 , please create PR to integrate it, we like static analysis tools, we have bunch of them already enforced over our code.

**Comment by azy2** [comment]
@romani I added the pull request to integrate NonDex

**Comment by romani** [comment]
I am closing this issue, all further updates should be done at #3378
