### ISSUE TITLE
Support suppressions for MethodLength for specific methods

### ISSUE THREAD

**Issue by Xsasan** [checkstyle/checkstyle#3376]
According to my SO-issue http://stackoverflow.com/questions/38562036/how-to-ignore-checkstyle-on-methods-according-to-a-specific-pattern, it would be nice to have an opportunity to define exceptions / suppressions for specific methods for the **MethodLength** rule. 

That would be great for situations where a method naturally is very big, like data mapping methods, or, in my case, I have a (legacy) method called `getMetaInformation()` where I collect fields and relations for UI presentation. This method occurs in some hundreds of files, and I don't want to refactor each of it. In those cases, the `MethodLength` rule should ignore the method length of methods according to a given pattern or list.

I.e. there should be a new option for the `MethodLength` module configuration like:

`<module name="MethodLength">`
`   <property name="max" value="30"/>`
`   <property name="countEmpty" value="true"/>`
`   <property name="ignorePattern" value="^(getMetaInformation)"/>`
`</module>`

Instead of an ignorePattern, it could be also i.e. a comma-separated list of methodNames:
`<module name="MethodLength">`
`   <property name="ignorePattern" value="getMetaInformation,anotherLongMethodToIgnore"/>`
`</module>`

**Comment by romani** [comment]
Please provide examples of real code where that is required and very inconvenient to use filters/suppressions . The more examples the better.

**Comment by Xsasan** [comment]
@romani Thank you for your answer. I don't see the advantage of real code - should I wrote a large method with more than 30 LOC? I tried to better explain the usage of such suppressions, and I gave an configuration example how I would expect it. Is this enough? Do you need more information?
In fact, there should be a similar configuration as for the `LineLength` module, but for whole methods instead single lines:

`<module name="LineLength">`
`   <property name="ignorePattern" value="^ *\* *[^ ]+$"/>`
`</module>`

**Comment by robstoll** [comment]
Pull request is ready, please approve ;)

**Comment by romani** [comment]
@Xsasan , @robstoll .

Why you want to extend Check with an option instead of using ready to use suppression abilities of Checkstyle (by comment, by annotation, on whole file in config, ..... ).
I do not want to extend Checks with extra options only because it mean I have to support them forever (unfortunate design nuance of checkstyle).

If you have legacy code - use suppressions/filters (http://checkstyle.sourceforge.net/config_filters.html). It is completely ok, and even unavoidable.

**Comment by robstoll** [comment]
Due to legacy code. I would like to use checkstyle and limit the method length in general, but since in lot of classes there is one or two methods (always the same name) which are longer, my team colleagues do not want to use checkstyle, a more strict method length rule respectively, because we would need to annotate the code with @SuppressWarnings or use suppression comments and my team colleagues do not want to see suppression annotations or comments in code due to some external tool (in this case checkstyle)

Thus, ideally I could define two methodLength Rules one which is for new methods and includes the new ignore pattern property, in order to ignore the legacy methods, and another rule which uses the new ignore pattern property to filter out all but the legacy methods. This way I could define that new methods should not be longer than 40 lines and legacy methods should not be longer than 200 lines. With the new ignore pattern property, I can assure that the legacy methods do not continue to grow and enforce a stricter rule for new methods at the same time. Sounds nice no?

**Comment by romani** [comment]
@robstoll ,

your explanation is not very persuasive.

> my team colleagues do not want to use checkstyle

sad, you are already in bad and non-cooperative situation.

> my team colleagues do not want to see suppression annotations or comments in code due to some external tool

yes, I also do not like this.

> I can assure that the legacy methods do not continue to grow and enforce a stricter rule for new methods at the same time. Sounds nice no?

on shallow review yes, but in long perspective  - no. Method is not a name only. Method is full signature, you proposal is too ignore it. It is already looks as bad design. If you keep in mind that all properties are API in checkstyle, and if you add property checkstyle have to support it.
I do not like your solution. I do understand you that you want to get what you need in easy way, but .... .

You need more smart and non in place suppression mode for checkstyle. To let you keep suppression out or sources and keep it pretty sticky to certain method to not be fragile by refactoring. Here is description of idea - https://github.com/checkstyle/checkstyle/wiki/Checkstyle-GSoC-2016-Project-Ideas#project-name-flexible-suppression-model that need to be implemented and it will might help you. Another idea is to make a suppression by AuditEvent content. To let user make suppression for certain Check and certain message of it.

**Comment by Xsasan** [comment]
@romani As far as I see, with Checkstyle it is simply not possible to ignore the MethodLength rule on some specific methods, even with suppression. Therefor this feature cannot be applied to any project that has legacy code which would break the rule. 
If there IS a way, it would be great if you could provide the solution in http://stackoverflow.com/questions/38562036/how-to-ignore-checkstyle-on-methods-according-to-a-specific-pattern. According to @mkordas comment: 
> I could implement it and you'll be able to use it whenever next version is released.

**Comment by robstoll** [comment]
@romani 
> sad, you are already in bad and non-cooperative situation.

Sure and I am certain you are with me when I say I would like to change the situation. As mentioned in  https://github.com/checkstyle/checkstyle/wiki/Checkstyle-GSoC-2016-Project-Ideas#project-name-flexible-suppression-model the problem with checkstyle is, that the suppression-filters do not work well if one has legacy code mixed with new code. The implementation provides a fast pragmatic way to improve this. Sure it does not cover all corner cases but it is surely also not over-engineered as a more flexible solution might be. 

>>I can assure that the legacy methods do not continue to grow and enforce a stricter rule for new methods at the same time. Sounds nice no?

> on shallow review yes, but in long perspective - no. Method is not a name only

Sure but I do not think this is really a problem unless you have legacy methods which are named the same way as new methods, vice versa respectivly. Following a possible configuration with the new ignore pattern:
```
<module name="MethodLength">
   <property name="max" value="40"/>
   <property name="ignorePattern" value="getXmlDescriptor|getMetadata"/>
</module>
<module name="MethodLength">
   <property name="max" value="130"/>
</module>
```
With this simple configuration I am able to define that all methods except the ones called `getXmlDescriptor` and `getMetadata` should not be longer than 40 lines whereas the later two methods should not be longer than 130 lines. If I am going to rename `getXmlDescriptor` or `getMetadata` then the stricter rule will apply (hence a developer will quickly realise that she either needs to update the checkstyle-config or refactor the method). 

> If you keep in mind that all properties are API in checkstyle, and if you add property checkstyle have to support it.

Sure, I could also add a custom rule instead. I just figured it might be helpful for others (at least @Xsasan seems to be interested)

**Comment by romani** [comment]
@robstoll , if you need it so much, lets make a new Check at [sevntu.checkstyle](https://github.com/sevntu-checkstyle/sevntu.checkstyle) project (our sandbox and test area of experimental Checks).
There you will have this Check available for you, and it might move to main project if more and more users will vote for it.

**Comment by robstoll** [comment]
@romani thanks, that would make things quite a bit easier. Please let me know when the next release is available :)

**Comment by romani** [comment]
> Please let me know when the next release is available :)

do you need release of sevntu.checkstyle ?
uhh, looks like I missed a release of it, I will do it in next day or two.
Please create an issue in that repo and you can start working.

=====================

To ALL,

if smb have other real stories of requirements for this feature , please share it in that issue.
For now issue is closed. I could change my mind if more votes appear.
