### ISSUE TITLE
Rule to enforce blank lines as wrap of class declaration

### ISSUE THREAD

**Issue by mcandre** [checkstyle/checkstyle#3379]
Oracle, IBM, Google, and Mozilla Java code often inserts a blank line between the opening curly brace of a class declaration and the class contents, as well as a blank line between the contents and the closing class curly brace. For example:

https://github.com/oracle/atg-build-tools/blob/master/atg-maven-plugin/src/main/java/com/oracle/atg/ateam/RunAssemblerMojo.java

Classes with no contents require no blank lines:

```
public class SomeClass {}
```

Could Checkstyle please feature a rule that enforces n (0, 1, 2, ...) blank lines in this context?

There appears to be a rule for enforcing a blank line at the beginning of class declarations, but I can't find one to enforce a blank line at the end as well.
##

**Comment by ieabbas** [comment]
Hello! I am new to Checkstyle, but I'm interested in contributing to this repository, beginning namely with this issue. Apologies for the lack of knowledge, but how should I go about creating this rule?

**Comment by romani** [comment]
issue is not approved yet for development. I do not have time now ... , will do that in a month.

Please take any another issue that have label "approved" and you are always welcome to start contributing, we will guide you through development process.
For now please read:
http://checkstyle.sourceforge.net/contributing.html
http://checkstyle.sourceforge.net/beginning_development.html

if you need more help, please join to chekcstyle-devel mail-list for discussion.

**Comment by eric-milles** [comment]
I can understand the blank line at the start of the class def to give some space before the first field or method.  But why at the end?  A closing brace followed by another with proper indentation seems fine.

```java
    }
}
```

I can tell the class is closed as the last brace in the file, also no indent clues me in.

**Comment by plastiv** [comment]
Interesting enough, we have exact the opposite code style convention of removing an empty line between closing braces, but I can't find a way to enforce it with the checkstyle.

**Comment by mcandre** [comment]
> Interesting enough, we have exact the opposite code style convention of removing an empty line between closing braces, but I can't find a way to enforce it with the checkstyle.

Awesome! I'd love to see support for enforcing both styles in Checkstyle configuration.

**Comment by eric-milles** [comment]
To enforce no blank lines at the beginning and end of any block, we use multi-line regular expression checks:
```xml
    <module name="RegexpMultiline">
        <property name="message" value="Blank line at start of block should be removed" />
        <property name="format" value="(?&lt;=\{\s{0,99}$)^$" />
        <property name="fileExtensions" value="groovy,java" />
    </module>
    <module name="RegexpMultiline">
        <property name="message" value="Blank line at end of block should be removed" />
        <property name="format" value="(?&lt;!\{\s{0,99}$)^$(?=^\s{0,99}\})" />
        <property name="fileExtensions" value="groovy,java" />
    </module>
```
"^$" signifies the blank line.

**Comment by romani** [comment]
@mcandre , 

we have one more request for the same feature https://groups.google.com/forum/#!topic/checkstyle/rzNJDM_uvyg , and looks like I lost tracking of this issue.

> Could Checkstyle please feature a rule that enforces n (0, 1, 2, ...) blank lines in this context?

please explain why you need multiple lines (2 empty lines or more) ?

**Comment by romani** [comment]
This issue is hard to read and understand what is requested.

I created new issue #3923 with clear request for new functionality.

request for "rule that enforces n (0, 1, 2, ...) blank lines in this context" is skipped as author did not explain a reason of it.

Implementation of new option as described in new issue will not brake compatibility with existing functionality.

If somebody care about NoEmptyLineSeparator - please create new issue and define usecases. @plastiv  , please do. There was similar request at https://github.com/checkstyle/checkstyle/issues/3089#issuecomment-278135207 . @robertpainsi .

**Comment by ati90ati** [comment]
Quick solution with multiline regex (the code should be well formatted):

    <module name="RegexpMultiline">
        <property name="format" value="^([^\n ]+ )*(class|interface|enum) [^{]*\{\n[^\n}]"/>
        <property name="message" value="Leave empty row after class/interface/enum definition!"/>
        <property name="severity" value="error"/>
        <property name="fileExtensions" value="groovy,java"/>
    </module>

    <module name="RegexpMultiline">
        <property name="format" value="[^\n{]\n\}\n"/>
        <property name="message" value="Leave empty row before end of class/interface/enum!"/>
        <property name="severity" value="error"/>
        <property name="fileExtensions" value="groovy,java"/>
    </module>

**Comment by GuyLewin** [comment]
@ati90ati for Windows support, I added `\r`:
```xml
<module name="RegexpMultiline">
    <property name="format" value="^([^[\r]?\n ]+ )*(class|interface|enum) [^{]*\{[\r]?\n[^\r\n}]"/>
    <property name="message" value="Leave empty row after class/interface/enum definition!"/>
    <property name="severity" value="error"/>
    <property name="fileExtensions" value="groovy,java"/>
</module>

<module name="RegexpMultiline">
    <property name="format" value="[^\r\n{][\r]?\n\}[\r]?\n"/>
    <property name="message" value="Leave empty row before end of class/interface/enum!"/>
    <property name="severity" value="error"/>
    <property name="fileExtensions" value="groovy,java"/>
</module>
```

**Comment by ati90ati** [comment]
@GuyLewin I've checked your suggestion.

For me, the first stopped working. It's not supposed to have this in regex: `[^[\r]?\n ]`
Bracket in bracket not supposed to be used.

My current approach is this (I adapted your Windows support, this is my best guess however I have not tested it on Windows):

```xml
<module name="RegexpMultiline">
    <property name="id" value="RegexpMultilineEmptyRowAfterClassDef"/>
    <property name="format" value="^([^\r\n ]+ )*(class|interface|@interface|enum) [^{]*\{[\r]?\n[^\r\n}]"/>
    <property name="message" value="Leave empty row after class/interface/@interface/enum definition!"/>
    <property name="severity" value="error"/>
    <property name="fileExtensions" value="groovy,java"/>
</module>

<module name="RegexpMultiline">
    <property name="id" value="RegexpMultilineEmptyRowBeforeClassEnd"/>
    <property name="format" value="[^\r\n{][\r]?\n\}[\r]?\n"/>
    <property name="message" value="Leave empty row before end of class/interface/@interface/enum!"/>
    <property name="severity" value="error"/>
    <property name="fileExtensions" value="groovy,java"/>
</module>
```

**Comment by pavelicii** [comment]
@ati90ati, thank you for the solution!

If I also want to check inner/nested classes for `RegexpMultilineEmptyRowAfterClassDef`, is it OK to change `format` to:

`^([\t ]*[^\r\n ]+ )*(class|interface|@interface|enum) [^{]*\{[\r]?\n[^\r\n}]`?

(added `[\t ]*` in the beginning to allow spaces/tabs before nested class definition)

**Comment by romani** [comment]
it would be awesome if somebody find a time to formalize https://github.com/checkstyle/checkstyle/issues/5313 and even implement it.

**Comment by ati90ati** [comment]
@pavelicii I updated my comment with the latest regex I have. I think your suggestion is accurate if you want to check inner classes too.

**Comment by Orachigami** [comment]
Extended version of @pavelicii pattern:
`^([ \t]{0,}@\w+[ \t]*(\(.*\))?)?[ \t]{0,}([a-z]+ )*(class|@?interface|enum)[^{]+\{[ \t]{0,}(?=\r?\n[ \t]{0,}(?!\})[^\s]|[^\r\n]*[^\s])`

I added annotation checks and empty class declaration ignoring

Demo can be checked here:
https://regex101.com/r/ELsq2R/3
