### ISSUE TITLE
Update Google style coverage to state of 12 July 2016

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#3381]
Style guide is changed - https://github.com/google/styleguide/commits/gh-pages/javaguide.html

Our version: http://checkstyle.sourceforge.net/reports/google-java-style.html (March 21, 2014)
New version: https://google.github.io/styleguide/javaguide.html (July 12, 2016)

Text variants for web comparison (https://www.diffchecker.com/si5nrlfh):
[google-style-12-July-2016.txt](https://github.com/checkstyle/checkstyle/files/392215/google-style-12-July-2016.txt)
[google-style-21-March-2014.txt](https://github.com/checkstyle/checkstyle/files/392216/google-style-21-March-2014.txt)

Issue is created base on : #3363 , #941
##

**Comment by agcuda** [comment]
It seems to me that the only changes that affect checkstyle are:
+ 3.3.3: Import order (already addressed by #941)
+ 4.5: method reference (::) behaves like dot separator etc
+ 4.8.7: added "default" modifier
+ 5.2.6: parameter names can be one-character long in non-public methods

The last three items are pretty trivial to implement, and I could create a pull request for each of them. Would you like me to create also three new issues or pull requests should simply reference this issue?

**Comment by romani** [comment]
Please reference one issue, please do not forget to update xdoc file that show coverage of rules

**Comment by agcuda** [comment]
Ok. I have created three different pull requests since they all impact the code. If/when they are approved I will also update the coverage doc, it that's ok for you.

**Comment by romani** [comment]
fix is merged.
