### ISSUE TITLE
Skip dry run build item for maven release commit

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#3383]
Example: https://travis-ci.org/checkstyle/checkstyle/builds/148617922

Todo: skip this build item then commit message is for version bump.
##

**Comment by MarcinWieczorek** [comment]
What should it allow?
`[maven-release-plugin]` or ` [maven-release-plugin] prepare release checkstyle-XX` or what?

**Comment by romani** [comment]
we should write some shell commands that get git commit message (https://github.com/checkstyle/checkstyle/commit/456808656e90cfc7e4ff496f96dce9f1cbca5dfc), if it equal to "[maven-release-plugin] prepare release checkstyle-" we need to return `0` and finish travis build item with success.

**Comment by MarcinWieczorek** [comment]
I think we need a regex for that in here:
https://github.com/checkstyle/checkstyle/blob/master/src/test/java/com/puppycrawl/tools/checkstyle/internal/CommitValidationTest.java

**Comment by romani** [comment]
no need , just check for "\[maven-release-plugin\] prepare release checkstyle-.*" .

**Comment by MarcinWieczorek** [comment]
But why with a bash script and not CommitValidationTest?

**Comment by romani** [comment]
Becaused problem is in CI (travis) only, nobody will run that phase on local - nonsesnse.
Whole build for this commit is useless. But we have problem only in one item so lets skip only it

**Comment by romani** [comment]
travis, wercker, circle-ci, shippable, .... ALL should skip build for this commit.
Travis already check it as:
`    SKIP_DEPLOY=$(if [ $(git log -1 | grep -E "\[maven-release-plugin\] prepare release" | cat | wc -l) -lt 1 ]; then echo false; else echo true; fi;)
`
but only for one build item, but we need all items(whole build)

**Comment by ahmadshabib** [comment]
Hey, i am planning to pick that item any more information should i know ?

**Comment by romani** [comment]
Thanks a lot for help.

There is already some kind of skip in CI configs https://github.com/checkstyle/checkstyle/blob/master/.travis.yml#L258
Please rename SKIP_CI to SKIP_CI_BY_FILES in first commit, and in second commit introduce new variable SKIP_CI_BY_COMMIT

**Comment by romani** [comment]
Fix is merged.
@ahmadshabib , thanks a lot for fix.
