### ISSUE TITLE
EmptyLineSeparator causing violation in `package-info.java`

### ISSUE THREAD

**Issue by mkobit** [checkstyle/checkstyle#3426]
`main/java/com/my/package/package-info.java`

``` java
/**
 * My package for doing things.
 */
package com.my.package;
```

Config:

``` xml
        <module name="EmptyLineSeparator">
            <property name="allowNoEmptyLineBetweenFields" value="true"/>
        </module>
```

Output (using Gradle and Checkstyle 7.1)

```
[ant:checkstyle] [WARN] main/java/com/my/package/package-info.java:5: 'package' should be separated from previous statement. [EmptyLineSeparator]
```

---

I expect that adding Javadoc to my `package-info.java` file to not trigger this violation.

Adding a separate line between the Javadoc comment and the package declaration causes the violation to not be triggered, but I want to keep them together, especially if I annotate my package definition (like `@ParametersAreNonnullByDefault`)
## 

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/37552627-emptylineseparator-causing-violation-in-package-info-java?utm_campaign=plugin&utm_content=tracker%2F500528&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F500528&utm_medium=issues&utm_source=github).

**Comment by romani** [comment]
http://checkstyle.sourceforge.net/config_whitespace.html#EmptyLineSeparator

looks like we step into a problem of distinguishing of header  and javadoc of package that usually placed in special files - package-info.java.
In our project we do have such files but files have header too - https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/package-info.java

logic is very simple and need to be adjusted to expect annotations: https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheck.java#L407

and distinguish javadoc vs simple multiline header - http://hg.openjdk.java.net/jdk9/jdk9/jdk/file/2bf254421854//test/tools/pack200/typeannos/TypeUseTarget.java . Javadoc comment has special identification - http://checkstyle.sourceforge.net/writingjavadocchecks.html#What_is_Javadoc_comment

**Comment by romani** [comment]
Fix is merged
