### ISSUE TITLE
JavadocParagraph check ignores other block elements

### ISSUE THREAD

**Issue by elharo** [checkstyle/checkstyle#3427]
```
/var/tmp $ javac YOUR_FILE.java
$ javac Foo.java
$

/var/tmp $ cat YOUR_FILE.java
$ cat Foo.java
/**
 * Some Javadoc.
 *
 * <p>
 * Some Javadoc.
 *
 * <pre>
 * Some preformatted Javadoc.
 * </pre>
 *
 */
 
 public class Foo {
 }

/var/tmp $ cat config.xml
$ cat config.xml
cat: config.xml: No such file or directory

/var/tmp $ java -jar checkstyle-X.XX-all.jar -c config.xml YOUR_FILE.java
$  java -jar checkstyle-7.1-all.jar -c config.xml Foo.java
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/puppycrawl/tools/checkstyle/Main : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
```

---------------

```
/**
 * Some Javadoc.
 *
 * <p>
 * Some Javadoc.
 *
 * <p>  Some Javadoc.
 *
 * <pre>
 * Some preformatted Javadoc.
 * </pre>
 *
 */
```

should be OK (as should `<table>, <div>`, etc.) Not everything needs to be wrapped in a paragraph like

```
/**
 * Some Javadoc.
 *
 * <p>
 * Some Javadoc.
 *
 * <p>  Some Javadoc.
 *
 * <p>
 * <pre>
 * Some preformatted Javadoc.
 * </pre>
 *
 */
```

--------------

**Comment by rnveach** [comment]
@elharo 
You may want to fix up your report as it is hard to read, and parts are missing.
Also please block/quote your files as it is being processed by GitHub and is very hard to read and understand.

> cat: config.xml: No such file or directory

Config file is needed.

> Exception in thread "main" java.lang.UnsupportedClassVersionError: com/puppycrawl/tools/checkstyle/Main : Unsupported major.minor version 52.0

CS requires Java 8 which is what this error probably is. We need to see the output of CS, to see your issue.

**Comment by romani** [comment]
I did some updates to description to make it a bit more readable

**Comment by rnveach** [comment]
Based on the referenced issue, this is their pom: https://github.com/GoogleCloudPlatform/appengine-plugins-core/blob/master/pom.xml#L140
Their config looks to be `google_checks.xml`.

When I run CS with this, I do get a violation, but it appears to be just related to not closing the `<p>` tag as there are no violations when it is fixed.
@elharo Can you confirm all this?

````
$ cat TestClass.java
/**
 * Some Javadoc.
 *
 * <p>
 * Some Javadoc.
 *
 * <pre>
 * Some preformatted Javadoc.
 * </pre>
 *
 */
 public class Foo {
 }

$ cat TestConfig.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>

    <module name="TreeWalker">
<module name="JavadocParagraph"/>
    </module>
</module>

$ java -jar checkstyle-7.1.1-all.jar -c TestConfig.xml TestClass.java
Starting audit...
[ERROR] TestClass.java:4: <p> tag should be placed immediately before the first word, with no space after. [JavadocParagraph]
Audit done.
Checkstyle ends with 1 errors.
````

There is no violation with:
````
/**
 * Some Javadoc.
 *
 * <p>
 * Some Javadoc.
 * </p>
 *
 * <pre>
 * Some preformatted Javadoc.
 * </pre>
 *
 */
````

**Comment by romani** [comment]
No reply from author.
Original problem was reported on attempt to run checkstyle on old jvm. We do not support such issues.
If you need to run checkatyle on old version , please look at http://checkstyle.sourceforge.net/ for backporting version to java6.

**Comment by elharo** [comment]
I believe the JVM version is a complete red herring here, and present only because you're insisting on a laundry list of irrelevant details for filing a bug. Otherwise I wouldn't have even attempted to run it. The issue is as described in the original report.
