### ISSUE TITLE
Fix grammar in issue templates

### ISSUE THREAD

**Issue by elharo** [checkstyle/checkstyle#3428]
This is a mets issue in the github templates, not in checkstyle itself:

YOU --> YOUR
detail --> details
trying to trying
etc.

**Comment by romani** [comment]
thanks for noticing, not sure where exactly but I will take a look ....
such templates are from https://github.com/checkstyle/checkstyle/tree/master/.github files , you can change them in web and send PR from web (no clone is required)

**Comment by elharo** [comment]
I actually did fork and fix, but got stuck at the point where the PR wanted an approved issue.

**Comment by romani** [comment]
trying is fixed too.
