### ISSUE TITLE
Cut down on Checkstyle's dependencies on Guava

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#3433]
Since now we use Java 1.8, it worth cutting down on Checkstyle's dependencies on Guava library:

1) Guava's Optional replaced with Java's native.
2) Guava's Predicate and Iterables should be replaced with Java's Predicate and streams. We cannot do this until we resolve or find workaround for Cobertura report generation problem on Java 1.8. (#3269 (comment), mojohaus/cobertura-maven-plugin#21)
3) ...

as we go in minimizing of thirdparty dependencies we need to restrict its usage now.

Please create separate PR and move all general allowances of guava usage https://github.com/checkstyle/checkstyle/blob/master/config/import-control.xml#L10 to certain package/class.

As soon as we/you do refactoring to remove some class usage - it should be removed from config too to never let others easily introduce it back.

**Comment by romani** [comment]
@MEZk , please do a summary of that is left here (we had numerous discussion in different PRs), with links on other issues that block further refactoring.

**Comment by MEZk** [comment]
@romani 

**Part 1:**
Got rid of the following dependencies and prohibited their usage in code:
1) com.google.collect.Iterables
2) com.google.common.base.String
3) com.google.common.base.Function
4) com.google.common.base.Supplier
5) com.google.common.base.Charsets
6) com.google.common.base.MoreObjects
7) com.google.common.base.Equivalence
8) com.google.common.base.Preconditions
9) com.google.common.base.Optional
10) com.google.common.base.Predicate
11) com.google.common.io.Files (partially)
12) com.google.common.io.CharSource
13) com.google.common.primitives.Ints
14) com.google.common.annotations.Beta

**Part 2:**
Got rid of the following dependencies and prohibited their usage in code:
1) com.google.common.collect.Queues
2) com.google.common.collect.Sets
3) com.google.common.collect.Lists
4) com.google.common.collect.Maps (parttially)
5) com.google.common.collect.Iterators

**Part 3:**
Got rid of the following dependencies and prohibited their usage in code:
1) com.google.common.annotations.GwtCompatible
2) com.google.common.annotations.GwtInCompatible
3) com.google.common.collect.TreeTraverser
4) com.google.common.io.Files

**Part 4:**
Got rid of the following dependencies and prohibited their usage in code:
1) com.google.common.collect.ImmutableList
2) com.google.common.collect.ImmutableSortedSet
3) com.google.common.collect.ImmutableSet
4) com.google.common.collect.ImmutableMap

## Remaining dependencies:

**com.google.common.collect.HashMultimap, com.google.common.collect.HashMultiset, com.google.common.collect.SetMultimap, com.google.common.collect.Multimap, com.google.common.collect.Multiset, com.google.common.collect.MapDifference**
> MEZk: do not have easy to use analogs in Java.
> romani: yes, for now no analogs.

**com.google.common.collect.***

**ImmutableCollection**
Checkstyle's API which uses ImmutableCollection (should be resolved in future - #3455):
1) com.puppycrawl.tools.checkstyle.DefaultContext
2) com.puppycrawl.tools.checkstyle.api.AutomaticBean
3) com.puppycrawl.tools.checkstyle.api.Context

**ImmutableList**
Checkstyle's API which uses ImmutableList (should be resolved in future - #3455):
1) com.puppycrawl.tools.checkstyle.DefaultContext

**ImmutableMap**
Checkstyle's API which uses ImmutableMap (should be resolved in future - #3455)
1) com.puppycrawl.tools.checkstyle.DefaultConfiguration
2) com.puppycrawl.tools.checkstyle.api.AbstractViolationReporter
3) com.puppycrawl.tools.checkstyle.api.Configuration
4)com.puppycrawl.tools.checkstyle.api.FileContents

Uses **ImmutableMap** by accessing Checkstyle's API (should be resolved in future - #3455)
1) com.puppycrawl.tools.checkstyle.checks.AvoidEscapedUnicodeCharactersCheck
2) com.puppycrawl.tools.checkstyle.checks.TrailingCommentCheck
3) com.puppycrawl.tools.checkstyle.filters.SuppressionCommentFilter
4) com.puppycrawl.tools.checkstyle.filters.SuppressWithNearbyCommentFilter
5) com.puppycrawl.tools.checkstyle.ConfigurationLoaderTest
6) com.google.checkstyle.test.chapter5naming.rule528typevariablenames.ClassTypeParameterNameTest
7) com.google.checkstyle.test.chapter5naming.rule528typevariablenames.InterfaceTypeParameterNameTest
8) com.google.checkstyle.test.chapter5naming.rule528typevariablenames.MethodTypeParameterNameTest
9) com.google.checkstyle.test.chapter5naming.rule526parameternames.ParameterNameTest
10) com.google.checkstyle.test.chapter5naming.rule525nonconstantfieldnames.MemberNameTest
11) com.google.checkstyle.test.chapter5naming.rule523methodnames.MethodNameTest
12) com.google.checkstyle.test.chapter5naming.rule522typenames.TypeNameTest
13) com.google.checkstyle.test.chapter5naming.rule521packagenames.PackageNameTest
14) com.google.checkstyle.test.chapter5naming.rule51identifiernames.CatchParameterNameTest
15) com.google.checkstyle.test.chapter4formatting.rule462horizontalwhitespace.GenericWhitespaceTest
16) com.google.checkstyle.test.chapter4formatting.rule462horizontalwhitespace.WhitespaceAroundTest

Uses **ImmutableMap.Builder**:
1) com.puppycrawl.tools.checkstyle.utils.TokenUtils uses ImmutableMap builder. If we replace it with unmodifiable map it will not allow to change the content of the map.
2) com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocTagInfo
3) com.puppycrawl.tools.checkstyle.utils.TokenUtils

**ImmutableSet**
Uses ImmutableSet for testing. Can be checked separately after https://github.com/checkstyle/checkstyle/issues/3462 .
1) com.puppycrawl.tools.checkstyle.checks.design.InputImmutable
2) com.puppycrawl.tools.checkstyle.checks.design.InputVisibilityModifierGenerics

Uses Guava's classes which return **ImmutableSet**
1) com.puppycrawl.tools.checkstyle.internal.CheckUtil

Used in test scope (input file). Can be checked separately after https://github.com/checkstyle/checkstyle/issues/3462 .
**com.google.common.annotations.VisibleForTesting** 
**com.google.common.base.Ascii** 

**com.google.common.base.CaseFormat** and **com.google.common.base.CharMatcher**
> romani: If that become again the only reason to use Guava - it is usage is small, and we can copy-paste only required code to our utils, I am ok.

**com.google.common.reflect.ClassPath.**
>it could stay as "test" scope dependency.

**com.google.common.io.Flushables** and **com.google.common.io.Closables**. 
> MEZk: If we get rid of the dependency it will require additional UTs and decrease readibility of the code as we will need to use additional try-catch block. 
> romani: yes, but that syntax cobertura does not support, so we avoid try-with-resources on purpose.
If that class be last , we could do copy-paste of required methods to our utils package.

**Comment by romani** [comment]
Remaining dependencies will be addressed at #3484
