### ISSUE TITLE
activate IntellijIdea inspection InterfaceMayBeAnnotatedFunctional

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#3435]
original discussion was at https://github.com/checkstyle/checkstyle/pull/3434#issuecomment-245462497

we need to review interfaces and confirm that they will stay functional.

https://docs.oracle.com/javase/8/docs/api/java/lang/FunctionalInterface.html

> However, the compiler will treat any interface meeting the definition of a functional interface as a functional interface regardless of whether or not a FunctionalInterface annotation is present on the interface declaration.

so there is no rush to activate this inspection.  Interfaces in API part should be specially investigated, as we will not be able to revert changes in them easily.

Good task for Checkstyle 8.X releases.
##

**Comment by Kietzmann** [comment]
I'm on it.
Should I add FunctionalInterface annotation in test interfaces?

**Comment by romani** [comment]
@Kietzmann , sorry, but this is GSoC issue
will be addressed on next week.

**Comment by romani** [comment]
@Nimfadora , please provide list of violations for me to confirm.

**Comment by Nimfadora** [comment]
@romani [here](https://teamcity.jetbrains.com/viewLog.html?buildId=1116964&buildTypeId=Checkstyle_IdeaInspectionsPullRequest&tab=Inspection) selected inspection is @FunctionalInterface

**Comment by romani** [comment]
I am fine to put annotation to all interfaces.
It does give only one limitation is that after such annotation, we can not add another method in interface.
See discussion at https://stackoverflow.com/questions/36881826/what-is-use-of-functional-interface-in-java-8/36882003
But I think such interfaces are already stable.

@rnveach , please review and confirm that you are ok with update to put annotation on all that interfaces.

**Comment by rnveach** [comment]
@romani I am fine with the annotation if it will not be a problem to remove it if we decide any interface needs a new method.

**Comment by romani** [comment]
Such interfaces already could be used in lambda so any extension to them could potentially do problem with compilation, annotation only one give user certainty that it  functional by design.
Let's try.

**Comment by romani** [comment]
fix is merged
