### ISSUE TITLE
PackageDeclaration does not check whether the package name matches the directory name for the source file

### ISSUE THREAD

**Issue by pepri** [checkstyle/checkstyle#3437]
The PackageDeclaration check should allow you to check whether the package name matches the directory name for the source file as stated in the [documentation](http://checkstyle.sourceforge.net/config_coding.html#PackageDeclaration).

Maven compiles classes with non-matching package name just fine and I would like to prevent having such classes. After searching for this feature, I found out it was removed (#209). I think this change should be reverted, since [the Java language specification doesn't force files to be in a certain directory](http://stackoverflow.com/a/8395934).
##

**Comment by romani** [comment]
we could restore removed option , but now it should be heavily documented.

**Comment by kukreja-vikramaditya** [comment]
I'm on it

**Comment by kukreja-vikramaditya** [comment]
@romani 
As per checkstyle's documentation, it is mentioned that [PackageDeclaration](http://checkstyle.sourceforge.net/config_coding.html#PackageDeclaration) can optionally check for  package name and directory name mismatch. So I would need to create a new MSG_KEY like (`mismatch.package.dir`)? or edit the [old one](https://github.com/search?q=path%3Asrc%2Fmain%2Fresources%2Fcom%2Fpuppycrawl%2Ftools%2Fcheckstyle%2Fchecks%2Fcoding+filename%3Amessages*.properties+repo%3Acheckstyle%2Fcheckstyle+%22missing.package.declaration%22)?

**Comment by rnveach** [comment]
@kukreja-vikramaditya 
Violation messages should be clear on guiding user to direct issue. Saying "Problem can be A or B" will be misguided and will require user to hunt down which one it is himself.
I don't see how original message can be updated and avoid that problem.
I think it is best to create a new message.

In addition to the logic change, we should have some example of new option in our xdoc. We should enable this option by default in our own configuration.

**Comment by rnveach** [comment]
Fix is merged
