### ISSUE TITLE
Update description of Checkstyle SDK GUI in xdocs

### ISSUE THREAD

**Issue by baratali** [checkstyle/checkstyle#3444]
## Should be done only after https://github.com/checkstyle/checkstyle/issues/3445 and https://github.com/checkstyle/checkstyle/issues/3432 bugs are fixed.

GUI changed once this issue was implemented: https://github.com/checkstyle/checkstyle/issues/408
Need to describe new features and attach new screenshots.
Following pages mention SDK GUI:
http://checkstyle.sourceforge.net/writingchecks.html#The_Checkstyle_SDK_Gui
http://checkstyle.sourceforge.net/writingjavadocchecks.html#Checkstyle_SDK_GUI
##

**Comment by romani** [comment]
issue is done, except for #3432.
#3442 could be done separately.
