### ISSUE TITLE
IllegalImport: new property illegalClasses to let blacklist certain classes import

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#3449]
Base on discussion at #3358.

How about implementing a second parameter `illegalClasses` (default: `null`):

``` xml
<module name="IllegalImport">
    <property name="illegalPkgs" value="sun, java.awt"/>
    <property name="illegalClasses" value="java.util.Date, java.util.Calendar"/>
</module>
```

Furthermore we could add a third parameter `regexp` (default: `false`) that determines whether the comma separated package or class names should be interpreted as regular expressions:

``` xml
<module name="IllegalImport">
    <property name="illegalPkgs" value="sun, java\.awt"/>
    <property name="illegalClasses" value="java\.util\.(Calendar|Date)"/>
    <property name="regexp" value="true"/>
</module>
```

Both would support the mentioned case without interfering with the current behavior.
1. Users might want to use more than one `ImportControl` check with varying severity. This would be much less straight forward using the `ImportControlCheck`, simply because it would require multiple `import_control.xml` files.
2. Users might just want to globally forbid certain classes (such as old [FindBugs annotations](http://findbugs.sourceforge.net/api/edu/umd/cs/findbugs/annotations/package-summary.html), where some annotations in the same package are still valid). In cases like this, defining an `import_control.xml` file seems like overkill to me, when the same could be achieved with just these two additional parameters.
##

**Comment by romani** [comment]
While issues are not resolved, you can take a look at http://sevntu-checkstyle.github.io/sevntu.checkstyle/apidocs/com/github/sevntu/checkstyle/checks/coding/ForbidCertainImportsCheck.html it might do what is needed.

**Comment by romani** [comment]
one more request base on  vanniktech's Tweet: https://twitter.com/vanniktech/status/788030816005873664?s=09

**Comment by timurt** [comment]
I am on it.

**Comment by timurt** [comment]
"whether the comma separated package or class names should be interpreted as regular expressions"
What do you think about 2 separate regexp flags, one for packages one for classes?

**Comment by romani** [comment]
one should be enough, as you will just compare string in import with user defined string by regexp.
User is completely responsible for proper definition of RegExp.
It is user responsibility to make regexp like `^com.mycompany$, com.company.MyBadClass` to make proper/strict match.
You will add that case in xdoc file as description of property and example to show user what is expected.

**Comment by timurt** [comment]
I finished with java coding, now I am doing config_imports.xml. Should I edit <subsection name="Examples">, if yes how can I preview my editings.

**Comment by Vladlis** [comment]
@timurt 
Yes, add new examples. You can generate site to validate changes, take a look at our wiki:
https://github.com/checkstyle/checkstyle/wiki/Build-all-jars-and-generate-maven-site

**Comment by timurt** [comment]
I have one problem, my last PR has failed check, because TeamCity claims that I should replace 
`        for (String illegalClass : illegalClasses) {`
`            illegalClassesRegexps.add(CommonUtils.createPattern(illegalClass));`
`        }`
with collect call, 
I rewrote this part to
`illegalClassesRegexps = illegalClasses.parallelStream()`
`                .map(item -> CommonUtils.createPattern(item))`
`                .collect(Collectors.toList());`
And now compiler says "Cannot assign a value to final variable", what I am doing wrong?

**Comment by romani** [comment]
fix is merged

**Comment by coolifewindy** [comment]
not bad
