### ISSUE TITLE
ImportControl: allow to load files from resources

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#3450]
base on #3358

> ImportControl does not appear to be able to find configurations that are resources, only files. So this does not seem to be usable at all if checkstyle.xml is in your project as a resource rather than a file.
## 

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/37980823-importcontrol-allow-to-load-files-from-resources?utm_campaign=plugin&utm_content=tracker%2F500528&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F500528&utm_medium=issues&utm_source=github).

**Comment by jochenvdv** [comment]
I will implement this.

**Comment by jochenvdv** [comment]
It looks like ImportControlLoader is already capable of loading URIs with classpath protocols, but ImportControlCheck prevents this as it treats the path as a file path.

Should we allow users to load an import control configuration from a resources with a classpath URI:
`classpath://org/my/package/resource.ext`? Or should it be done differently?

I do not like the way [SuppressionFilter](http://checkstyle.sourceforge.net/config_filters.html#SuppressionFilter) tries to load the path as a file and falls back to trying to load it as a resource. I think it is more straightforward to just treat it as a URI.

**Comment by romani** [comment]
yes, by URI (web, filesystem, classpath) - https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/ConfigurationLoader.java#L177

**Comment by jochenvdv** [comment]
`SuppresionFilter` has a single property `file` which is interpreted as a filename or URL and resource as a fallback method,
but `ImportControlCheck` has already separate properties for file and URL.

Shall I make a separate property `resource` which accepts a path like `my/package/resource.ext`?

```xml
<module name="ImportControl">
    <property name="resource" value="my/package/import-control.xml"/>
</module>
```

Or shall I use the `file` property and fall back to trying to load as a resource if the file could not be found?

```xml
<module name="ImportControl">
    <!-- File my/package/import-control.xml not found, so interpreted as resource in classpath -->
    <property name="file" value="my/package/import-control.xml"/>
</module>
```

BTW, the file you link loads Checkstyle's main configuration, but the checks seem to use their own implementation which also extends `AbstractLoader`.

**Comment by romani** [comment]
> but ImportControlCheck has already separate properties for file and URL. 

it is legacy. It exists only because we can not easily remove property without breaking backward compatibility. That is why we wait for major release to do this. Please create separate issue on this , i will put "checkstyle8" label on it.
Please use "file", it ok to use CommonUtils. If there is some own implementation of loading - create separate issue.

**Comment by jochenvdv** [comment]
OK. I will change implementation of the `file` property to use `CommonUtils`. This will make it able to load files, URLs and resources. I will document it as well.

I will create a separate issue for removing the url property.
Should I already document it as deprecated in my PR or do this in a separate PR?

**Comment by romani** [comment]
> Should I already document it as deprecated in my PR or do this in a separate PR?

to mark as deprecated please do by separate issue to explain the reason and prove that certain property is odd. Our releasenotes have links to issues, there all details should be.

**Comment by romani** [comment]
fix is merged.
