### ISSUE TITLE
api: remove from API all guava code 

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#3455]
Checkstyle 8 task.

file config/import-control.xml

```
<allow class="com.google.common.io.Closeables" local-only="true"/>
<allow class="com.google.common.collect.ImmutableCollection" local-only="true"/>
<allow class="com.google.common.collect.ImmutableMap" local-only="true"/>
```

API should be clear from any non standard classes.

Since this change is being done in API code, this will break backward compatibility with any existing code that uses it if it is not re-compiled. When upgrading, to mitigate this issue, all custom JARs must be recompiled against new checkstyle code.

Example of failure:
https://app.wercker.com/checkstyle/checkstyle/runs/build/5a27437a9fe1e0000127e823?step=5a2743a0540e1a00018beb4f
> java.lang.Error: Error was thrown while processing /pipeline/source/src/test/java/com/puppycrawl/tools/checkstyle/AbstractPathTestSupport.java
Caused by: java.lang.NoSuchMethodError: com.puppycrawl.tools.checkstyle.api.FileContents.getBlockComments()Lcom/google/common/collect/ImmutableMap;

The method still does exist, but the signature was changed. So technically there is nothing wrong with code, it just needs to be recompiled to correct the signature.

**Comment by rnveach** [comment]
@romani I think this can have the checkstyle 8 label.

**Comment by romani** [comment]
fix is merged
