### ISSUE TITLE
Import:  Missing imported classes.

### ISSUE THREAD

**Issue by ATsurkanu** [checkstyle/checkstyle#3459]
package com.puppycrawl.tools.checkstyle;

import com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocLexer;// missing
import com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser;//missing

public class JavadocDetailNodeParser 

---------------
Expexted: in com.puppycrawl.tools.checkstyle.grammars should exists javadoc.JavadocLexer and javadoc.JavadocParser (see import on the top), they are don't exists.
--------------

**Comment by romani** [comment]
These classes are generated during build process.  Please `mvn compile` . If you stil have problems please review build logs of our CIs (see badges in readme.md file)
