### ISSUE TITLE
building v5.7 unable to find https://raw.github.com/checkstyle/checkstyle/master/src/testinputs/com/puppycrawl/tools/checkstyle/suppressions_none.xml

### ISSUE THREAD

**Issue by spyhunter99** [checkstyle/checkstyle#3467]
Tests in error: 
  testLoadFromURL(com.puppycrawl.tools.checkstyle.filters.SuppressionsLoaderTest): unable to find https://raw.github.com/checkstyle/checkstyle/master/src/testinputs/com/puppycrawl/tools/checkstyle/suppressions_none.xml
---------------

Attempting to build v5.7 (sorry I know it's old) and it's looking for an online resource. Not a big deal since i can skip the tests. Just reporting the condition as an FYI

--------------

**Comment by romani** [comment]
We do not support old versions. Sorry.
