### ISSUE TITLE
Add METHOD_REF to the list of valid tokens for OperatorCheck

### ISSUE THREAD

**Issue by agcuda** [checkstyle/checkstyle#3472]
Java 8 introduces the new "Method reference" (::) operator. It is treated e.g. by the Google Style Guide as a "non-assignment operator" and it [says](https://google.github.io/styleguide/javaguide.html#s4.5.1-line-wrapping-where-to-break) that in case of line wrap, the line break should occur before that symbol.

OperatorWrap should accept METHOD_REF in the list of valid tokens, e.g.:
```
         <module name="OperatorWrap">
             <property name="option" value="NL"/>
             <property name="tokens" value="METHOD_REF, BAND, BOR, BSR ..."/>
         </module>
```

**Comment by agcuda** [comment]
One thing I forgot to ask: should METHOD_REF be added to the default list of tokens when "tokens" is not specified?

**Comment by romani** [comment]
fix is merged. 
thanks a lot for your contribution !
