### ISSUE TITLE
Cut down on Checkstyle's dependencies on Guava, phase II

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#3484]
split from #3433
## Remaining dependencies:

**com.google.common.collect.HashMultimap, com.google.common.collect.HashMultiset, com.google.common.collect.SetMultimap, com.google.common.collect.Multimap, com.google.common.collect.Multiset, com.google.common.collect.MapDifference**

> MEZk: do not have easy to use analogs in Java.
> romani: yes, for now no analogs.

**com.google.common.collect.***

**ImmutableCollection**
Checkstyle's API which uses ImmutableCollection (should be resolved in future - #3455):
1) com.puppycrawl.tools.checkstyle.DefaultContext
2) com.puppycrawl.tools.checkstyle.api.AutomaticBean
3) com.puppycrawl.tools.checkstyle.api.Context

**ImmutableList**
Checkstyle's API which uses ImmutableList (should be resolved in future - #3455):
1) com.puppycrawl.tools.checkstyle.DefaultContext

**ImmutableMap**
Checkstyle's API which uses ImmutableMap (should be resolved in future - #3455)
1) com.puppycrawl.tools.checkstyle.DefaultConfiguration
2) com.puppycrawl.tools.checkstyle.api.AbstractViolationReporter
3) com.puppycrawl.tools.checkstyle.api.Configuration
4)com.puppycrawl.tools.checkstyle.api.FileContents

Uses **ImmutableMap** by accessing Checkstyle's API (should be resolved in future - #3455)
1) com.puppycrawl.tools.checkstyle.checks.AvoidEscapedUnicodeCharactersCheck
2) com.puppycrawl.tools.checkstyle.checks.TrailingCommentCheck
3) com.puppycrawl.tools.checkstyle.filters.SuppressionCommentFilter
4) com.puppycrawl.tools.checkstyle.filters.SuppressWithNearbyCommentFilter
5) com.puppycrawl.tools.checkstyle.ConfigurationLoaderTest
6) com.google.checkstyle.test.chapter5naming.rule528typevariablenames.ClassTypeParameterNameTest
7) com.google.checkstyle.test.chapter5naming.rule528typevariablenames.InterfaceTypeParameterNameTest
8) com.google.checkstyle.test.chapter5naming.rule528typevariablenames.MethodTypeParameterNameTest
9) com.google.checkstyle.test.chapter5naming.rule526parameternames.ParameterNameTest
10) com.google.checkstyle.test.chapter5naming.rule525nonconstantfieldnames.MemberNameTest
11) com.google.checkstyle.test.chapter5naming.rule523methodnames.MethodNameTest
12) com.google.checkstyle.test.chapter5naming.rule522typenames.TypeNameTest
13) com.google.checkstyle.test.chapter5naming.rule521packagenames.PackageNameTest
14) com.google.checkstyle.test.chapter5naming.rule51identifiernames.CatchParameterNameTest
15) com.google.checkstyle.test.chapter4formatting.rule462horizontalwhitespace.GenericWhitespaceTest
16) com.google.checkstyle.test.chapter4formatting.rule462horizontalwhitespace.WhitespaceAroundTest

Uses **ImmutableMap.Builder**:
1) com.puppycrawl.tools.checkstyle.utils.TokenUtils uses ImmutableMap builder. If we replace it with unmodifiable map it will not allow to change the content of the map.
2) com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocTagInfo
3) com.puppycrawl.tools.checkstyle.utils.TokenUtils

**ImmutableSet**
Uses ImmutableSet for testing. Can be checked separately after https://github.com/checkstyle/checkstyle/issues/3462 .
1) com.puppycrawl.tools.checkstyle.checks.design.InputImmutable
2) com.puppycrawl.tools.checkstyle.checks.design.InputVisibilityModifierGenerics

Uses Guava's classes which return **ImmutableSet**
1) com.puppycrawl.tools.checkstyle.internal.CheckUtil

Used in test scope (input file). Can be checked separately after https://github.com/checkstyle/checkstyle/issues/3462 .
**com.google.common.annotations.VisibleForTesting** 
**com.google.common.base.Ascii** 

**com.google.common.base.CaseFormat** and **com.google.common.base.CharMatcher**

> romani: If that become again the only reason to use Guava - it is usage is small, and we can copy-paste only required code to our utils, I am ok.

**com.google.common.reflect.ClassPath.**

> it could stay as "test" scope dependency.

**com.google.common.io.Flushables** and **com.google.common.io.Closables**. 

> MEZk: If we get rid of the dependency it will require additional UTs and decrease readibility of the code as we will need to use additional try-catch block. 
> romani: yes, but that syntax cobertura does not support, so we avoid try-with-resources on purpose.
> If that class be last , we could do copy-paste of required methods to our utils package.
##

**Comment by rnveach** [comment]
Removing all of guava produces 22 violations:
````
[ERROR] \src\main\java\com\puppycrawl\tools\checkstyle\checks\javadoc\SummaryJavadocCheck.java:28:1: Disallowed import - com.google.common.base.CharMatcher. [ImportControlMain]
[ERROR] \src\main\java\com\puppycrawl\tools\checkstyle\checks\TranslationCheck.java:43:1: Disallowed import - com.google.common.collect.HashMultimap. [ImportControlMain]
[ERROR] \src\main\java\com\puppycrawl\tools\checkstyle\checks\TranslationCheck.java:44:1: Disallowed import - com.google.common.collect.SetMultimap. [ImportControlMain]
[ERROR] \src\main\java\com\puppycrawl\tools\checkstyle\checks\UniquePropertiesCheck.java:30:1: Disallowed import - com.google.common.collect.HashMultiset. [ImportControlMain]
[ERROR] \src\main\java\com\puppycrawl\tools\checkstyle\checks\UniquePropertiesCheck.java:31:1: Disallowed import - com.google.common.collect.ImmutableMultiset. [ImportControlMain]
[ERROR] \src\main\java\com\puppycrawl\tools\checkstyle\checks\UniquePropertiesCheck.java:32:1: Disallowed import - com.google.common.collect.Multiset. [ImportControlMain]
[ERROR] \src\main\java\com\puppycrawl\tools\checkstyle\checks\UniquePropertiesCheck.java:33:1: Disallowed import - com.google.common.collect.Multiset.Entry. [ImportControlMain]
[ERROR] \src\main\java\com\puppycrawl\tools\checkstyle\DefaultConfiguration.java:28:1: Disallowed import - com.google.common.collect.ImmutableMap. [ImportControlMain]
[ERROR] \src\main\java\com\puppycrawl\tools\checkstyle\DefaultContext.java:25:1: Disallowed import - com.google.common.collect.ImmutableCollection. [ImportControlMain]
[ERROR] \src\main\java\com\puppycrawl\tools\checkstyle\DefaultContext.java:26:1: Disallowed import - com.google.common.collect.ImmutableList. [ImportControlMain]
[ERROR] \src\main\java\com\puppycrawl\tools\checkstyle\gui\CodeSelector.java:27:1: Disallowed import - com.google.common.collect.ImmutableList. [ImportControlMain]
[ERROR] \src\main\java\com\puppycrawl\tools\checkstyle\gui\CodeSelectorPresentation.java:24:1: Disallowed import - com.google.common.collect.ImmutableList. [ImportControlMain]
[ERROR] \src\main\java\com\puppycrawl\tools\checkstyle\gui\MainFrameModel.java:29:1: Disallowed import - com.google.common.collect.ImmutableList. [ImportControlMain]
[ERROR] \src\main\java\com\puppycrawl\tools\checkstyle\gui\TreeTable.java:41:1: Disallowed import - com.google.common.collect.ImmutableList. [ImportControlMain]
[ERROR] \src\main\java\com\puppycrawl\tools\checkstyle\JavadocDetailNodeParser.java:45:1: Disallowed import - com.google.common.base.CaseFormat. [ImportControlMain]
[ERROR] \src\main\java\com\puppycrawl\tools\checkstyle\PropertyCacheFile.java:41:1: Disallowed import - com.google.common.io.BaseEncoding. [ImportControlMain]
[ERROR] \src\main\java\com\puppycrawl\tools\checkstyle\PropertyCacheFile.java:42:1: Disallowed import - com.google.common.io.ByteStreams. [ImportControlMain]
[ERROR] \src\main\java\com\puppycrawl\tools\checkstyle\PropertyCacheFile.java:43:1: Disallowed import - com.google.common.io.Closeables. [ImportControlMain]
[ERROR] \src\main\java\com\puppycrawl\tools\checkstyle\PropertyCacheFile.java:44:1: Disallowed import - com.google.common.io.Flushables. [ImportControlMain]
[ERROR] \src\main\java\com\puppycrawl\tools\checkstyle\TreeWalker.java:31:1: Disallowed import - com.google.common.collect.HashMultimap. [ImportControlMain]
[ERROR] \src\main\java\com\puppycrawl\tools\checkstyle\TreeWalker.java:32:1: Disallowed import - com.google.common.collect.Multimap. [ImportControlMain]
[ERROR] \src\main\java\com\puppycrawl\tools\checkstyle\utils\ModuleReflectionUtils.java:29:1: Disallowed import - com.google.common.reflect.ClassPath. [ImportControlMain]
````

I know for sure Guava must stay for `ModuleReflectionUtils`.

**Comment by rnveach** [comment]
> Used in test scope (input file). 

We want to remove guava even from test code? You made the import control file for test allow anything, and we don't even look at inputs right now.

> > com.google.common.reflect.ClassPath.

> it could stay as "test" scope dependency.

This needs to stay for production use since we use class path scanning.

**Comment by romani** [comment]
@rnveach , @MEZk , we should be accurate with removal of guava.
Original idea was to remove stuff that is available in jdk8. But Guava is bigger and have some good collections (multi collection , immutable collections, .... some utils classes). Idea to completely get rid of it is some how force us to be come to complete asceticism (no extra suff), and we could end-up in bunch of inconvenient code and some time non-intuitive(then it come to return collection that suppose to be immutable but it isnot clear from type).

**Comment by rnveach** [comment]
@romani Are the other guava imports staying or will we remove them too?
They are com.google.common.base.CaseFormat, com.google.common.base.CharMatcher, com.google.common.io.Flushables, and com.google.common.io.Closables.

**Comment by romani** [comment]
Closeable almost removed by usage of try-with-resouces , will be more obvious ones @pbludov finish his PR #5753.

Other I need to review from laptop, if dependency is so minimal we can drop them, and probably copy required method to our util classes

**Comment by romani** [comment]
Reasonable part of issue is fixed and merged
