### ISSUE TITLE
DetailAST should invalidate childCount cache

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#3486]
Similar to https://github.com/checkstyle/checkstyle/issues/3466#issue-179024433 and the existing issue described at https://github.com/checkstyle/checkstyle/issues/3466#issuecomment-250868051, we must erase the cache stored inside DetailAST between the non-comment trees and comment trees as the extra nodes being added make the cache values wrong.

The fix in the previous issue invalidated `branchTokenTypes` cache but it did not invalidate `childCount` which was also in issue's description.
Since we also cache `childCount` and don't reset it on add/set children/siblings methods, it will keep count from non-comment trees into comment trees, as long as we don't call `setFirstChild` which is the only method to invalidate it currently. To avoid calling `setFirstChild`, issue can be seen with code samples like `public /* comment */ static void method () {}` where a comment/javadoc is between 2 other similar nodes.

In previous issue's fix, `getChildCount` was called on `METHOD_DEF` in UT while the comments are located as a child of `MODIFIERS` in input. So the UT in that fix isn't directed at the correct location to showcase the `getChildCount` issue.

Showcase of issue at: https://github.com/checkstyle/checkstyle/pull/3485#issuecomment-250883463

**Comment by MEZk** [comment]
@romani 

>public /* comment */ static void method () {}

That is correct test case and we did not check it when we were discussing the issue #3466

**Comment by romani** [comment]
Fix is merged
