### ISSUE TITLE
Turn on Config Cache File Locally for Developers

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#3487]
http://checkstyle.sourceforge.net/config.html#Checker property cacheFile.
It speeds up checkstyle's run by not rechecking files that have no issues and have not changed.

I want to turn that on locally, but currently the only way to do that is to modify the config for each branch I make.
I feel this will help developers who have to constantly re-run the checkstyle before sending a PR to the server. Some computers that are slower take a few minutes to run this command, so any performance boost is appreciated.

I assume we can make like a maven property which we can override locally that will set it when we run the checkstyle, that way it doesn't change CI behavior and turn it on there.

When I run locally in Eclipse, I can run it either through maven:

> mvn verify -Dmaven.test.skip=true -Dpmd.skip=true -Dfindbugs.skip=true -Dcobertura.skip=true -Dforbiddenapis.skip=true

or directly running `Main`:

> Main class: com.puppycrawl.tools.checkstyle.Main
> 
> Program Arguments: -c M:\checkstyleWorkspaceEclipse\checkstyle\config\checkstyle_checks.xml M:\checkstyleWorkspaceEclipse\checkstyle\src\it\java M:\checkstyleWorkspaceEclipse\checkstyle\src\main\java M:\checkstyleWorkspaceEclipse\checkstyle\src\test\java M:\checkstyleWorkspaceEclipse\checkstyle\src\xdocs
> 
> VM arguments: -Dcheckstyle.header.file="M:\checkstyleWorkspaceEclipse\checkstyle\config\java.header" -Dcheckstyle.suppressions.file="M:\checkstyleWorkspaceEclipse\checkstyle\config\suppressions.xml" -Dcheckstyle.regexp.header.file="M:\checkstyleWorkspaceEclipse\checkstyle\config\java_regexp.header" -Dcheckstyle.importcontrol.file="M:\checkstyleWorkspaceEclipse\checkstyle\config\import-control.xml"
##

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/38024932-turn-on-config-cache-file-locally-for-developers?utm_campaign=plugin&utm_content=tracker%2F500528&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F500528&utm_medium=issues&utm_source=github).

**Comment by rnveach** [comment]
It appears we do set the location for the cache file in the ant-phase-verify, but we don't use it anywhere in the configuration: https://github.com/checkstyle/checkstyle/blob/4b7adec5ae396e24d3d0bf0d790919a45bac5421/config/ant-phase-verify.xml#L35
> <property key="checkstyle.cache.file" file="${mvn.project.build.directory}/cachefile"/>

Seems all we have to do is add it to the configuration file and developers can hook into it, through maven or ant or any other process.

Question: Is it safe to put the cache file into the build directory? Seems like it could accidentally get picked in the maven `clean` commands we are required to run in various situations, like cobertura.

**Comment by romani** [comment]
yes we should activate cache in our config - https://github.com/checkstyle/checkstyle/blob/4b7adec5ae396e24d3d0bf0d790919a45bac5421/config/checkstyle_checks.xml#L19, http://checkstyle.sourceforge.net/config.html#Checker
No changes on Travis is required, as it should do all validation without any cache to avoid any leak of violations due to cache problems.

Please rename file from "cachefile" to "checkstyle.cache" to make it clear that that is not maven file.

> Question: Is it safe to put the cache file into the build directory?

yes, when you run "mvn clean ...." you force maven to clean all caches and .... from all plugins and phases. If smb want to reuse he need to not use "clean" phase in his commands.

**Comment by rnveach** [comment]
@romani This issue can't be completed even if all cache issues are resolved, because we don't support multi-file validation (`TranslationCheck`) and that check is enabled in our configuration currently. Turning cache on with the check will create issues.

To continue with this issue we must either disable it in the default config and have a special CI only config for it.
Our only other option is to abandon this issue completely until multi-file validation can be sorted out.

**Comment by romani** [comment]
We should not disable this Check in our config as we have a rule to use all Checks. Yes, we have problems , fortunately it will not be a problem for users, it will not be a problem for CIs, it might be a problem for contributors (but very rare use case, unlikely to happen). Contributors will come to us and we will explain this.

@rnveach , We should enable caching by default to let you do development verification stage quicker.

**Comment by romani** [comment]
Fix is mergee
