### ISSUE TITLE
Checker Cache invalidated falsely on load in second run due to external resources

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#3489]
I tried populating the cache file with a modified CS run with all files because of #3488, to verify another issue. During debugging, I noticed all files were being reported as not in the cache even though I could verify them in my cache file.
The cache file was being invalidated in the beginning due to: https://github.com/checkstyle/checkstyle/blob/4b7adec5ae396e24d3d0bf0d790919a45bac5421/src/main/java/com/puppycrawl/tools/checkstyle/PropertyCacheFile.java#L115-L120
We always put in the config hash during a load. My run was saying the config hash key didn't exist on load.

After searching it turns out this is happening because external resources have changed and we clear out the entire cache and don't put the config hash back in to make it a valid cache file: https://github.com/checkstyle/checkstyle/blob/4b7adec5ae396e24d3d0bf0d790919a45bac5421/src/main/java/com/puppycrawl/tools/checkstyle/PropertyCacheFile.java#L233

When we clear the cache file, we have to put the config hash back in, otherwise it won't be a valid cache file.

**Comment by MEZk** [comment]
@rnveach 
We fill the cache here https://github.com/checkstyle/checkstyle/blob/4b7adec5ae396e24d3d0bf0d790919a45bac5421/src/main/java/com/puppycrawl/tools/checkstyle/PropertyCacheFile.java#L235 .

**Comment by romani** [comment]
Fix is merged
