### ISSUE TITLE
refactoring to ImportControlCheck 

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#3498]
1)2)
that points were removed as not reasonable to implement.

3)

```
inPkg = full.getText();
```

rename inPkg --> package

4)

```
currentLeaf
```

rename to currentPkgControl

5)

```
            final FullIdent imp;
            if (ast.getType() == TokenTypes.IMPORT) {
                imp = FullIdent.createFullIdentBelow(ast);
            }
            else {
                // know it is a static import
                imp = FullIdent.createFullIdent(ast
                        .getFirstChild().getNextSibling());
}
```

make it as function that return String, nobody need FullIdent class out of this scope.

6)

```
final DetailAST nameAST = ast.getLastChild().getPreviousSibling();
final FullIdent full = FullIdent.createFullIdent(nameAST);
```

make a function from this with clear name of what is it doing.

7)

```
currentLeaf.checkAccess(imp.getText(),inPkg);
```

order of argument should be different(by pattern WHERE-->WHAT), should be `currentPkgControl.checkAccess(package, currentImport);`
## 

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/38132941-refactoring-to-importcontrolcheck?utm_campaign=plugin&utm_content=tracker%2F500528&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F500528&utm_medium=issues&utm_source=github).

**Comment by rnveach** [comment]
@romani
> such validation should be done in setter

If setter is never called, when property is not defined, validation error will never be printed.
Validation of missing, required property should probably be done in `init`.

**Comment by romani** [comment]
>  it should probably be done in init.

may be. But All Checks do some default behavior if nothing is set - nothing is done.

**Comment by romani** [comment]
point 1) and 2) were removed as not reasonable.
