### ISSUE TITLE
Add context to the error message for RightCurlyOption.SAME

### ISSUE THREAD

**Issue by jacalata** [checkstyle/checkstyle#3501]
Test.java
1: if {
2:   // code 
3: }
4: else {
5:    // code
6: }

checkstyle rule: RightCurlyOption SAME
http://checkstyle.sourceforge.net/apidocs/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyOption.html

/var/tmp $ java -jar checkstyle-X.XX-all.jar -c config.xml YOUR_FILE.java
Test.java:3: '}' should be on the same line.

---------------

Error message would be more helpful if it said " '}' should be on the same line as the next block"

--------------

**Comment by romani** [comment]
Valid point.

We can add to message text from javadoc "as the the next part of a multi-block statement".
Translations shpuld be updated too .

@MEZk , do you remember why we did not do this? when we extended that option meaning

**Comment by MEZk** [comment]
@romani 

@jacalata uses an old version of Checkstyle. We updated the message.

>[ERROR] TestClass.java:4:8: '}' at column 8 should be on the same line as the next part of a multi-block statement (one that directly contains multiple blocks: if/else-if/else, do/while or try/catch/finally). [RightCurly]

https://github.com/checkstyle/checkstyle/blob/25a37e5049b7816b34c552899841a978efc37a63/src/main/resources/com/puppycrawl/tools/checkstyle/checks/blocks/messages.properties#L10

http://rveach.no-ip.org/checkstyle/checkstyle.php?action=view&config=7fe66916c88d0aa2f63c5f3c5b750e1a&code=31430c90e75f2235f598df58a63de89e&checkstyle=checkstyle-7.1.2-all.jar&printTree=
