### ISSUE TITLE
CatchParameterName add support for 2 character length parameter name

### ISSUE THREAD

**Issue by borcherspm** [checkstyle/checkstyle#3518]
$ javac SomeClass.java
[no output]

$ cat SomeClass.java
```java
public class SomeClass {
	public void saveEnrollmentAclOverride() {
		try {
			//
		}
		catch (ValidationException ve) {
			//
		}
	}
	
	class ValidationException extends RuntimeException {
	
	}
}
```

$ cat checkstyle.xml
```xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC "-//Puppy Crawl//DTD Check Configuration 1.3//EN" "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
	<module name="TreeWalker">
		<module name="CatchParameterName"/>
	</module>
</module>
```

$ java -jar checkstyle-7.1.2-all.jar -c checkstyle.xml SomeClass.java
```
Starting audit...
[ERROR] C:\Users\borcherspm\Desktop\checkstyle\SomeClass.java:8:44: Name 've' must match pattern '^(e|t|ex|[a-z][a-z][a-zA-Z]+)$'. [CatchParameterName]
Audit done.
Checkstyle ends with 1 errors.
```

---------------

I expected it to pass because I want to be able to specify a 2 character length catch parameter as long as is ends with an 'e'.

**Comment by romani** [comment]
Please report issue as it was requested in template. Details http://checkstyle.sourceforge.net/report_issue.html#How_to_report_a_bug

**Comment by romani** [comment]
you need to use special property "format" , https://github.com/checkstyle/checkstyle/blob/master/config/checkstyle_checks.xml#L369
example: https://github.com/checkstyle/checkstyle/blob/master/config/checkstyle_checks.xml#L369

you do with regexp, what ever you need to satisfy your requirements.
