### ISSUE TITLE
Ant: Cannot override default Checker

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#3530]
Similar to #3515, Ant hardcodes Checker and doesn't allow user to set custom RootModule.
https://github.com/checkstyle/checkstyle/blob/fbf3f95c2273be23b966cba6e6ef89390a6fb020/src/main/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTask.java#L422-L430

**Comment by romani** [comment]
fix is merged
