### ISSUE TITLE
Checkstyle tests should not require internet

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#3536]
Since moving the import DTD to sourceforge, we have been getting intermittent 403 errors on PRs, master builds, and locally (for me personally).
Example:
https://travis-ci.org/checkstyle/checkstyle/jobs/174479836#L497
````
checkstyle.checks.imports.ImportControlCheckTest.testTwoRegExp(ImportControlCheckTest.java:177)
Caused by: java.lang.reflect.InvocationTargetException
	at com.puppycrawl.tools.checkstyle.checks.imports.ImportControlCheckTest.testTwoRegExp(ImportControlCheckTest.java:177)
Caused by: org.apache.commons.beanutils.ConversionException: Unable to load /home/travis/build/checkstyle/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/import-control_two-re.xml
	at com.puppycrawl.tools.checkstyle.checks.imports.ImportControlCheckTest.testTwoRegExp(ImportControlCheckTest.java:177)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: unable to read file:/home/travis/build/checkstyle/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/import-control_two-re.xml
	at com.puppycrawl.tools.checkstyle.checks.imports.ImportControlCheckTest.testTwoRegExp(ImportControlCheckTest.java:177)
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: http://checkstyle.sourceforge.net/dtds/import_control_1_2.dtd
	at com.puppycrawl.tools.checkstyle.checks.imports.ImportControlCheckTest.testTwoRegExp(ImportControlCheckTest.java:177)
````
and
`[ERROR] around Ant part ...<ant antfile="config/ant-phase-verify.xml"/>... @ 7:47 in /home/travis/build/checkstyle/checkstyle/target/antrun/build-main.xml: cannot initialize module TreeWalker - Cannot set property 'file' to '/home/travis/build/checkstyle/checkstyle/config/import-control.xml' in module ImportControl: InvocationTargetException: Unable to load /home/travis/build/checkstyle/checkstyle/config/import-control.xml: unable to read file:/home/travis/build/checkstyle/checkstyle/config/import-control.xml: Server returned HTTP response code: 403 for URL: http://checkstyle.sourceforge.net/dtds/import_control_1_2.dtd`

We should either create our own proxy on tests and override connections to the internet (to simulate being online) and have an offline mode for DTD validation (or skip it entirely).
The second will require changes to the CLI and the Ant task.

**Comment by romani** [comment]
Strange, we had such problem on moment on  when this dtd is introduced, after some time it is cached somehow and did not see such provlems for a while on ci and local.
Please look at pr where dtd was intriduced, it has shell script that test connection.

**Comment by rnveach** [comment]
Local failure for me is when I am at work behind a firewall. It is windows only so I can't run shells.

@romani 
Were we suppose to update the `ImportControlLoader` for the new DTD? 1.2 isn't listed.
https://github.com/checkstyle/checkstyle/blob/5530d4c27d508c513b68af67aadede84b4cfa102/src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlLoader.java#L58
https://github.com/checkstyle/checkstyle/blob/5530d4c27d508c513b68af67aadede84b4cfa102/src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlLoader.java#L78

When testing proxy, I am only seeing connections for invalid URLs and for `import_control_1_2.dtd`.

**Comment by romani** [comment]
> Were we suppose to update the ImportControlLoader for the new DTD? 1.2 isn't listed.

yes, missed update.
PR is merged.

> When testing proxy, I am only seeing connections for invalid URLs and for import_control_1_2.dtd.

I do not understand this, please state the re-phrase.

**Comment by rnveach** [comment]
> > When testing proxy, I am only seeing connections for invalid URLs and for import_control_1_2.dtd.
> I do not understand this, please state the re-phrase.

Issue was to make tests completely offline. I inserted a proxy into the tests to prevent connections to the internet and had it print what requests the tests were making.

One was `import_control_1_2.dtd` which lead me to the fix I made.
Others were for files that don't exist and are part of the test:
````
http://checkstyle.sourceforge.net/non_existing_suppression.xml
http://checkstyle.sourceforge.net/files/suppressions_none.xml
http://mock.sourceforge.net/suppressions_none.xml
UnableToLoadThisURL:443
````

**Comment by romani** [comment]
for 1st an 2nd  - I remember.
not sure why there 3rd and 4th, but it might be some test for bad url.

do you still have a problem ?

**Comment by rnveach** [comment]
With fix I don't have as big as problem as before.
Some tests that require internet still fail for me like `SuppressionFilterTest.testRemoteFileExternalResourceContentDoesNotChange`.

**Comment by romani** [comment]
as you see this problem , can you try smth like - http://www.codeaffine.com/2013/11/18/a-junit-rule-to-conditionally-ignore-tests/ ?
to skip this test

**Comment by rnveach** [comment]
> http://stackoverflow.com/a/1689309/1015848 

[We already use assume on this test](https://github.com/checkstyle/checkstyle/blob/25a37e5049b7816b34c552899841a978efc37a63/src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionFilterTest.java#L232), but junit and maven still puts it as an error.

````
Tests run: 11, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 65.615 sec <<< FAILURE! - in com.puppycrawl.tools.checkstyle.filters.SuppressionFilterTest
testRemoteFileExternalResourceContentDoesNotChange(com.puppycrawl.tools.checkstyle.filters.SuppressionFilterTest)  Time elapsed: 42.168 sec  <<< ERROR!
org.junit.AssumptionViolatedException: got: <false>, expected: is <true>
	at com.puppycrawl.tools.checkstyle.filters.SuppressionFilterTest.testRemoteFileExternalResourceContentDoesNotChange(SuppressionFilterTest.java:232)
````

**Comment by romani** [comment]
http://junit.sourceforge.net/javadoc/org/junit/Assume.html

>The default JUnit runner treats tests with failing assumptions as ignored. Custom runners may behave differently.

Looks like smth(powermock) change default Runner.

Can you try Rule instead ?

Proxy is overcomplication for such simple issue.

**Comment by rnveach** [comment]
@romani It doesn't work. It too uses an assumption.
````
org.junit.AssumptionViolatedException: Ignored by MyTest
	at org.junit.Assume.assumeTrue(Assume.java:59)
	at com.puppycrawl.tools.checkstyle.internal.ConditionalIgnoreRule$IgnoreStatement.evaluate(ConditionalIgnoreRule.java:110)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.evaluateStatement(PowerMockJUnit47RunnerDelegateImpl.java:107)
````

**Comment by romani** [comment]
ok , looks like simple IF condition is the most robust solution, please do, please add comment above to explain why this is not Assume and Rule :), it is not so obvious.

**Comment by romani** [comment]
@rnveach , please confirm that you do not have any issues with this anymore (only you can verify this issue). Please close if it is actually fixed.

**Comment by rnveach** [comment]
@romani 
> only you can verify this issue

This is not true, anyone can test it.
Since test requires internet, all you have to do is go off offline and issue will present itself, either unplug ethernet or disable wifi.

**Comment by pbludov** [comment]
The site checkstyle.sourceforge.net is still on maintenance. And suppression tests are still failing.
Maybe we should move the test content to github.io?
Or make a mirror and use github.io as back up for sourceforge.net in the test?

**Comment by romani** [comment]
Originally tests were hitting github.com (not a github.io) , so they were even more unstable as file got error to download even there were no maintenance.

>Or make a mirror and use github.io as back up for sourceforge.net in the test?

Probably yes, it might be, beneficial to have copy of web site at GitHub.io , or maybe be eventually migrate to github.io completely.

**Comment by rnveach** [comment]
We could try using Mock Server
http://www.mock-server.com/mock_server/getting_started.html
