### ISSUE TITLE
Move AutomaticBean out of API package

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#3542]
Taken from https://github.com/checkstyle/checkstyle/pull/3541#issuecomment-259830261 and Issue #3255.

`AutomaticBean` needs to understand check's beans to be able to determine how to convert them and send them as simple setters. It is needed to complete #3255.

`[ERROR] src/main/java/com/puppycrawl/tools/checkstyle/api/AutomaticBean.java:[47] (extension) ForbidCertainImports: Import 'com.puppycrawl.tools.checkstyle.checks.whitespace.PadOption' should not match '.+\.checks\..+' pattern, it is forbidden.`

While it remains in API package, it is not possible to complete the desired issue as checks can't be referenced in API.

It should also be considered to allow checks to specify these bean conversions themselves so custom checks can make use of them.

**Comment by rnveach** [comment]
@romani Should this class just go into `com.puppycrawl.tools.checkstyle`?
For custom modules to provide their bean own implementations, should this class be public and singleton?

**Comment by romani** [comment]
> Should this class just go into com.puppycrawl.tools.checkstyle?

yes.

> should this class be public and singleton?

singletons are always a problem, let avoid singletons as much as possible.

**Comment by rnveach** [comment]
> singletons are always a problem, let avoid singletons as much as possible.

Without a singleton, we will have to pass the class instance as a parameter to `AbstractFileSetCheck` and `AbstractCheck`, both of which are `api`. This will create an import in those classes and create a reliance between these API classes on a non-api class, as we want to move `AutomaticBean` out of API. There is nothing in import control that would allow this currently.
Is this ok?

If not, and you still are against singleton, then lets keep `AutomaticBean` in API and pass it around via parameters and have checks manually add their own types?

**Comment by romani** [comment]
> If not, and you still are against singleton, then lets keep AutomaticBean in API and just pass it around via parameters and have checks manually add their own types?

moving this class around (to Checks) is not good either. I do not have good idea right now, but it better to no over-complicate Checks (may eb they could have inteface method that allow converter to be provided to Checker).
It is also good to make a such design to avoid usage of very specifics ("checks" package) in top ".....puppycrawl.checkstyle".

> Or are we not going to allow users to customize their own beans?

we should, but it should be convenient for both sides.

**Comment by romani** [comment]
@rnveach ,

I still do not like idea to put all converters to Checks. As Check as class is not aware from where all its parameters are de-serialized.
Check should receive type that he need and all other is not its business.

I did not think about this problem a lot ... but ... what if introduce new module type Converter and allow place them xml/run-time/.... configuration. So Checker on moment of Check initialization will use Converter modules. So thirparty Checks will need to place one more module(Converter) to config to allow Checkstyle to load config and convert user values properly to user's custom Checks. Checks will stay as logic collector, unaware of from where it was executed/configured.

**Comment by rnveach** [comment]
> As Check as class is not aware from where all its parameters are de-serialized.
> Checks will stay as logic collector, unaware of from where it was executed/configured.

This is slightly wrong. De-serialization is in `AutomaticBean` which all checks/modules extend from. They know where they are de-serialized just not the exact method.
All are given `public` methods `configure`, `contextualize`, and `getConfiguration`. There isn't much protecting checks from learning about their configuration and I see these type converters as just a small extension.
The check will still be unaware of most other things, all it is telling everyone how to do is convert from String's to it's own basic types. it isn't learning about the rest of the structure of the XML file.

> Check should receive type that he need and all other is not its business.

This is one reason why it should be in the check and `AutomaticBean`. If it is any where else, other Check's could collide with types if each wants to parse the same type in different ways. if we have a 3rd party module for the check, there is no way to define that module can only be used with a specific check unless you specify the check class which just shows that the Check and converter have a bond and should stick together in the same place.

As the PR is right now, each check will be able to define it's own converter regardless of other checks using the same type. Check A and B could make different conversions for URL and it wouldn't affect each other or our own checks that do the conversion already.

> allow place them xml/run-time/.... configuration
> will need to place one more module(Converter) to config 

If it is separated from Check, then it is not a good design imo.
You now have to remember to include a specific converter for that check and like I mentioned above, conflicts will happen it multiple checks want to unravel the same type differently. These checks will never work without these converters because the default support of `String` will be lost. Everyone will get `Cannot set property` errors.
This will also conflict with all the modules we plan to change in https://github.com/checkstyle/checkstyle/issues/3543 as each converter with each module will need a new module to convert with, and break all existing configurations that use those modules.
If we are going to break these modules and configurations, we might as well go on with making `misc` package and such.

**Comment by rnveach** [comment]
@romani I am closing this since you don't want to put converters to checks.
We will have to use the check's field instead.
