### ISSUE TITLE
Use Huntbugs tool in our build process

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#3556]
https://github.com/amaembo/huntbugs

we need to start to use it.

**Comment by Nimfadora** [comment]
@romani I have a several concerns about this tool:
1) Do you really want add it to checkstyle? Looks like currently it is dead (No updates for 9 month). And the majority of checks are taken from findbugs, as said in their manual:
> Currently 222 FindBugs warnings reimplemented and several new warnings added.

2) I took a closer look into ways to use in our project, and it happened to be not so easy.
This tool analyses not the sources, but already compiled bytecode. And it gives a huge number of violations on antlr classes - around 95% of all violations.
Thats why we will need somehow to ignore antlr classes. But it's [maven plugin](https://github.com/amaembo/huntbugs/blob/master/huntbugs-maven-plugin/src/main/java/one/util/huntbugs/maven/plugin/HuntBugsMojo.java) does not provide such functionality. It takes only one input directory and thats all.

**Comment by romani** [comment]
@Nimfadora ,

> Looks like currently it is dead (No updates for 9 month)

Findbugs is dead completely - http://findbugs.sourceforge.net/
The current version of FindBugs is 3.0.1, released on 13:05:33 EST, 06 March, 2015

> I took a closer look into ways to use in our project, and it happened to be not so easy.
This tool analyses not the sources, but already compiled bytecode

the same as findbugs

> It takes only one input directory and thats all.

sad, please contact project maintainers in gitter chat for details.
If no reply - create and issue on them to do some excludes for classes or implement suppression model to let at least suppress violations on certain classes.

If there is no suppression model , it is good reason to skip it. But issue has to be created on their issue tracker and link to it should be shared in this issue.

**Comment by Nimfadora** [comment]
@romani , acording to [reply in gitter](https://gitter.im/amaembo/huntbugs), it looks like this tool will not be supported any longer. Should I create issue in github?

**Comment by rnveach** [comment]
Gitter conversation and google translation:
> Nimfadora
> Привет, а хантбаг еще будет поддерживаться? Хотим использовать его в https://github.com/checkstyle/checkstyle , но нам не хватает возможности саппресить определенные ворнинги и более гибко настраивать какие классы он будет чекать...
> Hello, and hantbag will still be supported? We want to use it in https://github.com/checkstyle/checkstyle, but we do not have enough opportunity to apply certain wins and more flexible to configure which classes it will check ...

> Tagir Valeev
Привет! Маловероятно :worried:
Можете форкать и забирать себе =)
Hello! Unlikely: worried:
You can forge and take yourself =)

**Comment by romani** [comment]
From gitter at 20170628:

Nimfadora 07:17
Привет, а хантбаг еще будет поддерживаться? Хотим использовать его в https://github.com/checkstyle/checkstyle , но нам не хватает возможности саппресить определенные ворнинги и более гибко настраивать какие классы он будет чекать...

Tagir Valeev 07:24
Привет! Маловероятно :worried:
Можете форкать и забирать себе =)

Maxim Degtyarev 08:06
ЖетБрейнс взяло тебя в рабство и времени теперь хватает только на то, чтобы поработать и поспать? )

Tagir Valeev 08:17
Ну пилить две похожие штуки одновременно явно странно
Лучше делать одну, но хорошо :grinning:

So, if you translate, you can see that tool is unlikely to be supported.
We should not use it too.
