### ISSUE TITLE
Cache conflict between Maven/Ant and Eclipse/CLI run

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#3566]
While finishing up #3487, I noticed that running Checkstyle through Maven and CLI kept causing the cache to be erased. When looking into it, the main differences was the hash for the configuration.

Since I am using the exact same configuration, properties, settings, etc on the same workspace, I am expecting the 2 to work together, generate the same hash, and not keep erasing the cache when running the 2.

By default, when CLI runs a check with the check's severity as `ignore`, the check is still processed but [violations are not printed by the `DefaultLogger`](https://github.com/checkstyle/checkstyle/blob/5e0ab75777985f056715f6d9dc5e4667b1a0dfa2/src/main/java/com/puppycrawl/tools/checkstyle/DefaultLogger.java#L121) (which is also [the same as `XMLLogger`](https://github.com/checkstyle/checkstyle/blob/5e0ab75777985f056715f6d9dc5e4667b1a0dfa2/src/main/java/com/puppycrawl/tools/checkstyle/XMLLogger.java#L120)). This is why they still appear as part of the configuration hash.
`maven-checkstyle-plugin` currently uses it's own version of the CLI so it still processes ignored checks like our CLI.
Ant run skips ignored checks because of `omitIgnoredModules` which is the heart of the problem. https://github.com/checkstyle/checkstyle/blob/fbf3f95c2273be23b966cba6e6ef89390a6fb020/src/main/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTask.java#L111

Users don't expect checks with a configured severity of `ignore` on the check itself to be run, so this is how our CLI and Ant should be by default.

In terms of what this issue should do:

1) We should add the option `omitIgnoredModules` to the CLI. It should default to on (TRUE) (like Ant), but can be turned off.
2) All our uses in our ANT configs of `omitIgnoredModules` should be turned off (FALSE). We want to run every check to be a sort-of no-exception validation.
3) We should make a request to `maven-checkstyle-plugin` to add the property `omitIgnoredModules` so users can specify it, and so we can make sure it stays off (FALSE) by default.
4) Do similar requests to Eclipse-CS and IntelijIdea plugins.

**Comment by rnveach** [comment]
Differences:
* Maven removes all checks with `severity` ignore. This explains `SeverityMatchFilter`, `MissingCtor`, `FinalParameters`.
* Number differences is 18h vs 19h, and 91h vs 93h. This adds up to 3 and since Eclipse has more, this is equal to the number of missing checks.

It looks like this is an issue with maven/ant dropping off checks that are ignored.

**Comment by rnveach** [comment]
@romani 
The easiest thing would be to turn off `omitIgnoredModules` for us and this won't be an issue anymore.

But this is not clear to the users since we hide the working of our cache.
Why is the default for `omitIgnoredModules` set to true, forcing people to opt in, when we don't do the same for the CLI?
CLI doesn't even have this kind of option. Is this something we would want to add?

Imo, both gateways should have the same defaults, have similar options (or explainable why one doesn't have it), and act the same. That's what I expected naturally.

**One thing to note:** Since we set them to ignore and have `omitIgnoredModules` turned on for ANT, we are not testing these modules during our CI process. They are completely removed from running, which is the intention of having them in our configuration to begin with. This could cause use to miss Exceptions on runs in our code.

**Comment by rnveach** [comment]
After talking with @romani , we came up with the following,

I tried to clarify my posts, when I specify maven, I mean maven's run of the verify phase and ant task and not by using `maven-checkstyle-plugin`. `maven-checkstyle-plugin` currently uses it's own version of the CLI so it still processes ignored checks like our CLI.

By default, when CLI runs a check with the check's severity as `ignore`, the check is still processed but [violations are not printed by the `DefaultLogger`](https://github.com/checkstyle/checkstyle/blob/5e0ab75777985f056715f6d9dc5e4667b1a0dfa2/src/main/java/com/puppycrawl/tools/checkstyle/DefaultLogger.java#L121) (which is also [the same as `XMLLogger`](https://github.com/checkstyle/checkstyle/blob/5e0ab75777985f056715f6d9dc5e4667b1a0dfa2/src/main/java/com/puppycrawl/tools/checkstyle/XMLLogger.java#L120)). This is why they still appear as part of the configuration hash.

Users don't expect checks with a configured severity of `ignore` on the check itself to be run, so this is how our CLI and Ant should be by default.

In terms of what this issue should do:

1) We should add the option `omitIgnoredModules` to the CLI. It should default to on (like Ant), but can be turned off.
2) All our uses of `omitIgnoredModules` should be turned off. We want to run every check to be a sort-of no-exception validation.
3) We should make a request to `maven-checkstyle-plugin` to add the property `omitIgnoredModules` so users can specify it, and so we can make sure it stays off.

**Comment by romani** [comment]
@rnveach , please squash all that investigation/discussion to single clear description to let anybody catch it and know what to do.

**Comment by rnveach** [comment]
@romani I squashed all posts into 2 posts.
1st contains issue and what is to be done.
2nd contains analysis to re-produce issue.

**Comment by rnveach** [comment]
Issue for `maven-checkstyle-plugin` can be found at: https://issues.apache.org/jira/browse/MCHECKSTYLE-338
Issue for `Eclipse-CS` can be found at: https://sourceforge.net/p/eclipse-cs/feature-requests/169/

**Comment by romani** [comment]
fix is merged.
