### ISSUE TITLE
use ForbidAnnotationElementValueCheck from sevntu.checkstyle

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#3567]
create PR to Checkstyle project to use new Checks at https://github.com/checkstyle/checkstyle/blob/master/config/checkstyle_sevntu_checks.xml

new Check: ForbidAnnotationElementValueCheck, 1.22.0

**Comment by jochenvdv** [comment]
Shouln't this issued be close? It seems resolved.

**Comment by rnveach** [comment]
@jochenvdv There is one item to look over that romani wasn't happy with on how I transformed it.

**Comment by romani** [comment]
@rnveach , Is it done ?

**Comment by rnveach** [comment]
Yes, all fixes are done.
