### ISSUE TITLE
Move DetailAST log away from AbstractViolationReporter

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#3574]
https://github.com/checkstyle/checkstyle/blob/25a37e5049b7816b34c552899841a978efc37a63/src/main/java/com/puppycrawl/tools/checkstyle/api/AbstractViolationReporter.java#L131-L141

This method is purely for Java and antlr checks to use, but it is located in a base abstract class used by filters and other things possibly never doing anything antlr related.
It should be moved to a more logical place like `AbstractCheck`.

**Comment by sagar-shah94** [comment]
I am on it

**Comment by rnveach** [comment]
@sagar-shah94 You cannot work on this issue. It is labeled with Checkstyle 8 and we are still on version 7.
It is a backward-breaking change and most wait for the new version.

**Comment by romani** [comment]
fix is merged
