### ISSUE TITLE
Modules and XDocs: change setter methods to recieve similar types with field type for easier xdoc validation (more 2)

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#3575]
Taken from #3255. These can be done at any time.

These types still need to be added to the `AutomaticBean` class.

````
        cub.register(new FileConverter(), File.class);
        cub.register(new UriConverter(), URI.class);
        cub.register(new ServerityLevelConverter(), SeverityLevel.class);
        cub.register(new ScopeConverter(), Scope.class);
````

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/39498616-modules-and-xdocs-change-setter-methods-to-recieve-similar-types-with-field-type-for-easier-xdoc-validation-more-2?utm_campaign=plugin&utm_content=tracker%2F500528&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F500528&utm_medium=issues&utm_source=github).

**Comment by romani** [comment]
fix for Scope is merged.

**Comment by rnveach** [comment]
File was dropped because only case is being removed.

**Comment by romani** [comment]
URI fix is merged.

**Comment by romani** [comment]
final fix is merged.
