### ISSUE TITLE
ImportControl: Remove deprecated 'url' property

### ISSUE THREAD

**Issue by jochenvdv** [checkstyle/checkstyle#3578]
See #3450.

The `url` property for `ImportControlCheck` should be removed.
The `file` property will be used to load files, URLs and resources instead. This will make it consistent with other external resource loaders.

**Comment by Kietzmann** [comment]
Looks like this has been done already.

**Comment by romani** [comment]
method is still there - https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlCheck.java#L210

**Comment by romani** [comment]
fix is merged
