### ISSUE TITLE
ImportControl: Deprecate 'url' property in favor of the 'file' property

### ISSUE THREAD

**Issue by jochenvdv** [checkstyle/checkstyle#3584]
See issue #3450 and PR #3583.

The `file` property of `ImportControlCheck` should now be used to load configuration from regular files, URLs and resources in the classpath.

In scope of this issue, we need to put deprecation annotation on setter and somehow mark it in xdoc documentation.

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/39535809-importcontrol-deprecate-url-property-in-favor-of-the-file-property?utm_campaign=plugin&utm_content=tracker%2F500528&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F500528&utm_medium=issues&utm_source=github).

**Comment by romani** [comment]
fix is merged
