### ISSUE TITLE
multiple configurations for different types of classes

### ISSUE THREAD

**Issue by KarolRoman** [checkstyle/checkstyle#3588]
Hi,

I use checkstyle in my project and I have following problem:
In my project I have several types of files (classes) like DTO, Entity classes, unit tests, business logic, data structure etc.
Each type of classes has different structure and code style rules. I accept magic numbers in unit tests, but not in business logic. I accept large number of properties in DTO but only a few for other classes.

In ideal world I would like to have the ability to annotate classes with for example “@DTO” or “@UnitTest” and there would be a mechanism that validates such class with appropriate checkstyle configuration. 
My questions are:
Is it possible to achieve this with current checkstyle? If yes, how can I do that?
If not: is it possible to write single plugin for checkstyle that does what I expect?

Regards,
Karol

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/39588698-multiple-configurations-for-different-types-of-classes?utm_campaign=plugin&utm_content=tracker%2F500528&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F500528&utm_medium=issues&utm_source=github).

**Comment by rnveach** [comment]
> Is it possible to achieve this with current checkstyle? If yes, how can I do that?

Ignoring violations by custom annotaiton is not achievable with current checkstyle. We also don't support multiple configuration files in 1 run but you can do multiple runs with different configurations.
Your best bet right now would be to use [suppressions](http://checkstyle.sourceforge.net/config_filters.html) to ignore violations you think shouldn't apply to your tiers/classes/methods.

> is it possible to write single plugin for checkstyle that does what I expect?

Without diving into your specific requirements, it is hard to say, but it sounds possible except for multiple configurations like I stated before.
Suppression by annotation is supported with [SuppressWarningsFilter](http://checkstyle.sourceforge.net/config_filters.html#SuppressWarningsFilter). It uses `SuppressWarnings` annotation, so you would need a customized version to support your annotations, their specific placements, and their custom rules.

**Comment by romani** [comment]
> If not: is it possible to write single plugin for checkstyle that does what I expect?

plugin .... two what project.
Checkstyle itself is just a library - jar with cli interface. But is has numerous plugins to IDEs and build systems to run it.
So answer is not simple , and to help us guide you in right direction we need more details. But it is possible, it will not be the same quick as original Checkstyle, as you will require double parsing of java file. Implementation will not be simple, so I would recommend to play with our suppressions first.
For conversations like this please use https://groups.google.com/forum/#!forum/checkstyle-devel .

In this issue tracker we track only real problems with project.

> Each type of classes has different structure and code style rules. I accept magic numbers in unit tests, but not in business logic. I accept large number of properties in DTO but only a few for other classes.

You can do archive this by suppressions (not ideal solution but it works). We also have different rules for main code and test code - so we can distinguish them by folder(or package name).
Example how we do this - https://github.com/checkstyle/checkstyle/blob/master/config/suppressions.xml#L30. Please review whole file it will give you number of examples.
