### ISSUE TITLE
repo files should not have execute permissions

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#3600]
```
$ ll
total 1488
drwxrwxr-x 2 rivanov rivanov   4096 Nov 23 13:43 ./
drwxrwxr-x 7 rivanov rivanov   4096 Jun 24 10:58 ../
-rw-rw-r-- 1 rivanov rivanov  13370 May 20  2016 anttask.xml.vm
...
-rw-rw-r-- 1 rivanov rivanov  56984 Nov 14 13:05 config_imports.xml
-rw-rw-r-- 1 rivanov rivanov  76904 Nov 14 13:05 config_javadoc.xml
-rw-rw-r-- 1 rivanov rivanov  34304 Jun 10 06:33 config_metrics.xml
-rwxrwxr-x 1 rivanov rivanov  71591 Nov 14 13:05 config_misc.xml*
...
```
attention to last line "rwx", "x" flag on files is not required , except for "*.sh" files.
please find other files in repo, there should be more files like this.

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/39628110-repo-files-should-not-have-execute-permissions?utm_campaign=plugin&utm_content=tracker%2F500528&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F500528&utm_medium=issues&utm_source=github).

**Comment by MaksimP** [comment]
little bash script
(find ./src ./config  -type f -perm 775 -print;)

./src/main/java/com/puppycrawl/tools/checkstyle/api/DetailAST.java
./src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheck.java
./src/main/java/com/puppycrawl/tools/checkstyle/TreeWalker.java
./src/main/resources/com/puppycrawl/tools/checkstyle/grammars/javadoc/JavadocLexer.g4
./src/main/resources/com/puppycrawl/tools/checkstyle/grammars/javadoc/JavadocParser.g4
./src/xdocs/config_misc.xml

**Comment by MaksimP** [comment]
now after "git fetch" or "git  clone" from ....checkstyle/checkstyle.git

./src/main/java/com/puppycrawl/tools/checkstyle/api/DetailAST.java
./src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
./src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheck.java
./src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAfterCheck.java
./src/main/java/com/puppycrawl/tools/checkstyle/TreeWalker.java
./src/main/resources/com/puppycrawl/tools/checkstyle/grammars/javadoc/JavadocLexer.g4
./src/main/resources/com/puppycrawl/tools/checkstyle/grammars/javadoc/JavadocParser.g4
./src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAfterCheckTest.java
./src/test/java/com/puppycrawl/tools/checkstyle/grammars/GeneratedJavaTokenTypesTest.java
./src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/InputDoWhile.java
./src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/InputWhitespaceAfter.java
./src/xdocs/config_misc.xml
./src/xdocs/config_whitespace.xml

**Comment by romani** [comment]
fix is merged.

` $ find ./src ./config -type f -perm 775 -print;`
return no result.

**Comment by rnveach** [comment]
@romani We aren't adding this to travis to verify we don't break this in the future?
Notification of this in github review is not very noticeable. Even you couldn't find it when i first pointed it out.

**Comment by romani** [comment]
If that problem happen one more time, we will make validation in travis
