### ISSUE TITLE
MethodParamPad: add examples

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#3601]
http://checkstyle.sourceforge.net/config_whitespace.html#MethodParamPad

it is required to add examples for users.
source of documentation is at https://github.com/checkstyle/checkstyle/blob/master/src/xdocs/config_whitespace.xml#L642

Issue is abandoned , so following commits are not correct.

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/39629043-make-examples-for-methodparampad-xdoc?utm_campaign=plugin&utm_content=tracker%2F500528&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F500528&utm_medium=issues&utm_source=github).

**Comment by MEZk** [comment]
Assigned to @SergeyDzyuba

**Comment by SergeyDzyuba** [comment]
I am on it

**Comment by romani** [comment]
PRs is closed as we lost connection with contributor, any contributor could continue this work to make it done.
Last referenced commit could be considered as starting point for right fix.

**Comment by ImmortalRabbit** [comment]
I am on it.

**Comment by romani** [comment]
fix is merged.
