### ISSUE TITLE
Set Load external DTD feature to be enabled

### ISSUE THREAD

**Issue by liutikas** [checkstyle/checkstyle#3605]
I realize this is a somewhat odd request, but here it goes. In our project (Android OS) we [use ENTITY in our config](https://android.googlesource.com/platform/development/+/master/tools/checkstyle/android-style.xml) to allow composing our config files from many different files as some subprojects of Android OS have different style requirements. This normally works great with Checkstyle, however our default `java` installation has `load-external-dtd` feature disabled (due to security reasons). This is a request to add
`
final SAXParserFactory factory = SAXParserFactory.newInstance();
factory.setFeature("http://apache.org/xml/features/nonvalidating/load-external-dtd", true);`

to `com.puppycrawl.tools.checkstyle.api.AbstractLoader`.

This would not affect anyone, except to allow us to keep using Checkstyle without any downstream modifications. 

both features load-external-dtd and external-general-entities are normally default set to true. Our company has set their java defaults to false as it can lead to cross scripting attacks if not handled correctly. load-external-dtd feature allows to load external DTD into a an XML document and external-general-entities feature allows to these these external DTDs in elements. Using these two we are able to compose configuration files from multiple XML files. Since both of these features are enabled by default in default java set ups it should be a no-op for most checkstyle users.

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/39700319-set-load-external-dtd-feature-to-be-enabled?utm_campaign=plugin&utm_content=tracker%2F500528&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F500528&utm_medium=issues&utm_source=github).

**Comment by romani** [comment]
https://docs.oracle.com/javase/tutorial/jaxp/properties/scope.html

**Comment by romani** [comment]
@liutikas , please provide PR with update.

**Comment by romani** [comment]
fix is merged.

**Comment by romani** [comment]
@liutikas , can you share an example on how different projects override path to ENTITY ?

**Comment by liutikas** [comment]
https://android.googlesource.com/platform/prebuilts/checkstyle/+/master/android-style.xml is the use we have in Android project.

**Comment by romani** [comment]
@liutikas , yes, I got this from issue description.

>to allow composing our config files from many different files as some subprojects of Android OS have different style requirements.

Please share a link to project that override default.

**Comment by liutikas** [comment]
Sure, disable it.

**Comment by romani** [comment]
@liutikas , changed at scope of #6474 , released as 8.18.
