### ISSUE TITLE
100% UT coverage for ParseTreeTablePModel.java

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#3606]
this task is good for newbies.

http://checkstyle.sourceforge.net/cobertura/com.puppycrawl.tools.checkstyle.gui.ParseTreeTablePModel.html

we need to update UTs to have 100% coverage.

https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/gui/ParseTreeTablePModel.java
https://github.com/checkstyle/checkstyle/blob/master/src/test/java/com/puppycrawl/tools/checkstyle/gui/ParseTreeTablePModelTest.java

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/39798788-100-ut-coverage-for-parsetreetablepmodel-java?utm_campaign=plugin&utm_content=tracker%2F500528&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F500528&utm_medium=issues&utm_source=github).

**Comment by ssdeep** [comment]
Was working on it.
ParseTreeTablePModel.isCellEditable() will always be false because getColumnClass() never returns ParseTreeTablePModel, it only returns ParseTreeTableModel.

**Comment by romani** [comment]
fixes are merged.
