### ISSUE TITLE
Checker: option to allow printing exception as violation and continue execution

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#3611]
Taken from [here](https://github.com/sevntu-checkstyle/sevntu.checkstyle/pull/514#issuecomment-264748898).

An option in Checker is needed to prevent exceptions from checks/checkstyle from stopping execution of regression reports.
Since regression uses maven-checkstyle plugin, this type of option would have to be in the configuration file as a property of Checker.
I propose the property `haltOnException` which is either `true`/`false` (defaults to `true`):
````
<module name="Checker">
    <property name="haltOnException" value="false"/>
</module>
````

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/39791030-checker-option-to-allow-printing-exception-as-violation-and-continue-execution?utm_campaign=plugin&utm_content=tracker%2F500528&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F500528&utm_medium=issues&utm_source=github).

**Comment by romani** [comment]
fix is merged.
