### ISSUE TITLE
extend examples for NoLineWrap

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#3625]
http://checkstyle.sourceforge.net/config_whitespace.html#NoLineWrap

extend examples, source file -  https://github.com/checkstyle/checkstyle/blob/master/src/xdocs/config_whitespace.xml#L792

**Comment by kukreja-vikramaditya** [comment]
Is there a requirement of more examples? Above mentioned PR got merged which adds static import examples (both bad and good).

**Comment by romani** [comment]
I do not see a need for more examples now.
Issue is closed.
