### ISSUE TITLE
Add new Sevntu checks and create UT for missing checks

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#3628]
Based on discussion in https://github.com/sevntu-checkstyle/sevntu.checkstyle/pull/557

Checkstyle is missing the following checks from sevntu in [it's own sevntu config](https://github.com/checkstyle/checkstyle/blob/master/config/checkstyle_sevntu_checks.xml):
````
com.github.sevntu.checkstyle.checks.coding.ReturnCountExtendedCheck
com.github.sevntu.checkstyle.checks.design.ConstructorWithoutParamsCheck
com.github.sevntu.checkstyle.checks.coding.AvoidModifiersForTypesCheck
com.github.sevntu.checkstyle.checks.design.HideUtilityClassConstructorCheck
````

These should be added to our sevntu config.

We also need a new UT that verifies we have all checks in our sevntu configuration file.

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/39913191-add-new-sevntu-checks-and-create-ut-for-missing-checks?utm_campaign=plugin&utm_content=tracker%2F500528&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F500528&utm_medium=issues&utm_source=github).

**Comment by romani** [comment]
we could grab all Check list from http://sevntu-checkstyle.github.io/sevntu.checkstyle/apidocs/allclasses-frame.html
it could be done by shell commands even.

**Comment by romani** [comment]
validation is merged to master and become just another Travis point - https://github.com/checkstyle/checkstyle/commit/9d9053066e0efa023a7043fa01c7c8fc3d049f04#diff-354f30a63fb0907d4ad57269548329e3R329

as soon all Checks are activated, it is required to remove `| cat` in `diff` command.

**Comment by romani** [comment]
xmlstarlet could be used after update to travis config for `apt`:
```
sudo: false
cache:
  apt: true
  directories:
    - ~/.m2/

addons:
  apt:
    packages:
      - xsltproc
      - xmlstarlet

```

**Comment by romani** [comment]
all Checks are activated.
Travis validation is activated.
