### ISSUE TITLE
travis: use standalone shell files 

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#3632]
Create folder: `.\ci\travis`
place in it shell files that it is required to be launched by Travis.

Travis config need to be changed to work like: 
https://github.com/checkstyle/sonar-checkstyle/blob/master/.travis.yml
https://github.com/checkstyle/sonar-checkstyle/blob/master/travis.sh

We can use travis.sh as single collector for commands that are simple.
Complicated commands should be created in separate shells.

Cons:
- one CI, multiple files, and even separate folder for this.
- mixture of files for CI and actual projects content in the same repo

Benefits:
- User can run the same commands easily on their local
- scripts become more userfirendly
- it would be possible to use `"` in scripts, in string concatenation that does not work

Side notes: 
github already kind of "forced" us to create ".guthub" folder , so we already have a mix.

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/39919169-travis-use-standalone-shell-files?utm_campaign=plugin&utm_content=tracker%2F500528&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F500528&utm_medium=issues&utm_source=github).

**Comment by rnveach** [comment]
Just a note: Scripts will be shell and require windows users to install mingw or something similar to run them.

I think this is a good idea.

**Comment by romani** [comment]
all scripts were moved to travis.sh
