### ISSUE TITLE
make code coverage for MainFrameModel 100%

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#3648]
good task for newbies to project.

class: https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/gui/MainFrameModel.java

excluded from coverage: https://github.com/checkstyle/checkstyle/blob/master/pom.xml#L1444

It is required to cover it by test to 100%, as completed, remove it from excludes.

**Comment by MEZk** [comment]
Actual line from excludes
https://github.com/checkstyle/checkstyle/blob/master/pom.xml#L1454

**Comment by xpdavid** [comment]
I am on this. :)

**Comment by rnveach** [comment]
Fix is merged
`
