### ISSUE TITLE
Expand missing testing for PropertyCacheFile tests

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#3650]
Taken from #3594.

The reason why our tests passed but our coverage failed is because we are calling methods and not verifying any type of result. There were only some minor comments that eluded to what was being tested.
Example: 
The test before the fix: https://github.com/checkstyle/checkstyle/blob/56cc11416ebdf52dd299d11424fb04fda42fa63f/src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java#L617-L638
The test after the fix: https://github.com/checkstyle/checkstyle/blob/94a7d07b64fbd646f0c6be61e34f80ae90a3187f/src/test/java/com/puppycrawl/tools/checkstyle/PropertyCacheFileTest.java#L133-L161

There are more tests like this for the cache in `CheckerTest` that could cause the same type of failure. These tests should be fixed to actually test their results to make sure they are working correctly.
Some examples:
https://github.com/checkstyle/checkstyle/blob/56cc11416ebdf52dd299d11424fb04fda42fa63f/src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java#L661-L664
https://github.com/checkstyle/checkstyle/blob/56cc11416ebdf52dd299d11424fb04fda42fa63f/src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java#L682-L684
https://github.com/checkstyle/checkstyle/blob/56cc11416ebdf52dd299d11424fb04fda42fa63f/src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java#L712-L718

**Comment by romani** [comment]
Pitest shoyld also catch all tests that does not care about result

**Comment by MEZk** [comment]
I'm on it.

**Comment by MEZk** [comment]
@rnveach 
Not only the tests for PropertyCacheFile, but also [the tests for Checker itself](https://github.com/checkstyle/checkstyle/blob/56cc11416ebdf52dd299d11424fb04fda42fa63f/src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java#L351) assert nothing. I think that they also need to be fixed.

**Comment by rnveach** [comment]
I am fine with making any tests better.

**Comment by MEZk** [comment]
> Not only the tests for PropertyCacheFile, but also the tests for Checker itself assert nothing. I think that they also need to be fixed.

Will be addressed in the scope of #4128.

**Comment by romani** [comment]
fix is merged.

if smt is left, it will be addressed during #3746 .

**Comment by rnveach** [comment]
I am closing this since fix was merged and anything else found will be done as part of GSoC issues
