### ISSUE TITLE
Remove checkstyle_packages.xml from checkstyle

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#3660]
We know where our classes are located, we should continue to support that in other jars

**Comment by MEZk** [comment]
@romani 
Will we need to resolve https://github.com/checkstyle/checkstyle/issues/3607 if we remove checkstyle_packages.xml ?

**Comment by rnveach** [comment]
@MEZk Our `checkstyle_packages.xml` is for only loading our checks. We know where our checks are by the hardcoded list we do in `PackageObjectFactory`.
#3607 is to probably to load external, 3rd party checks which is why we need reflection.
So I don't think this issue relies on another other.

**Comment by MEZk** [comment]
@rnveach 
Now I see.
1. We try to create a module based on NAME_TO_FULL_MODULE_NAME map which contains all fully qualified names of Checkstyle modules. ([createObjectFromMap](https://github.com/checkstyle/checkstyle/blob/fcfacfc6ecc20303998e0522ab655775913a7be1/src/main/java/com/puppycrawl/tools/checkstyle/PackageObjectFactory.java#L124-L124))
2. If the previous attempt fails we try to create a module based on the information about packages taken from checkstyle_packages.xml.

The second attempt is for 3rd party libs as we know all Checkstyle modules when we try to perform the first attempt of the module creation.

**Comment by rnveach** [comment]
@MEZk yes.

**Comment by romani** [comment]
Fix is merged
