### ISSUE TITLE
create xdoc for FileContentsHolder

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#3664]
there is no information about FileContentsHolder and what is it for.

Some notes are at:
http://checkstyle.sourceforge.net/config_filters.html#SuppressionCommentFilter
http://checkstyle.sourceforge.net/config_filters.html#SuppressWithNearbyCommentFilter

but this module should have its own documentation, and should be referenced at http://checkstyle.sourceforge.net/checks.html as it is similar to SuppressWarningsHolder

**Comment by rnveach** [comment]
@romani XDoc for `FileContentsHolder` is located in `config_misc`.
http://checkstyle.sourceforge.net/config_misc.html#FileContentsHolder

**Comment by romani** [comment]
ok , we just need to add them to `checks.html` probably it make sense to make new group there just to avoid confusions

**Comment by romani** [comment]
Them = FileContentsHolder , SuppressWarningsHolder

**Comment by rnveach** [comment]
`SuppressWarningsHolder` does appear on the page already. The test doesn't verify if something is there that shouldn't be.

**Comment by romani** [comment]
it will be confusing why in table of Checks we place Holders .... They are not Checks ... should we place them in separate table ? on the same page or different ? .... hmmm

**Comment by romani** [comment]
Fix is merged
