### ISSUE TITLE
remove deprecated menthod from FileContents

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#3666]
https://github.com/checkstyle/checkstyle/blob/master/config/findbugs-exclude.xml#L69

remove deprecated method in checkstyle 8.

**Comment by Kietzmann** [comment]
@romani 
I can't see that method (`setFile[nN]ame`?) in `FileContents.java`. Does this issue was resolved?

**Comment by romani** [comment]
@Kietzmann , please do not touch issue with label "chekstyle8" we are in 7.X release.

**Comment by subkrish** [comment]
I'm on it.

**Comment by romani** [comment]
fix is merged.
