### ISSUE TITLE
Module term and usage is confusing in test area

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#3667]
We have a utility method [getCheckstyleModules](https://github.com/checkstyle/checkstyle/blob/62926b6106cbc22cb73f08c32b964c9e6e8d8b45/src/test/java/com/puppycrawl/tools/checkstyle/internal/CheckUtil.java#L152), which I thought would return every module we have in checkstyle. Isn't everything we do a module?

[isCheckstyleModule](https://github.com/checkstyle/checkstyle/blob/62926b6106cbc22cb73f08c32b964c9e6e8d8b45/src/test/java/com/puppycrawl/tools/checkstyle/internal/CheckUtil.java#L193) does not define `AbstractFileSetCheck`. Isn't that a module? We define filters, filefilters, and checks. Why isn't `AbstractFileSetCheck` a module? We also don't define root module `Checker`.

[isCheckstyleNonAbstractCheck](https://github.com/checkstyle/checkstyle/blob/62926b6106cbc22cb73f08c32b964c9e6e8d8b45/src/test/java/com/puppycrawl/tools/checkstyle/internal/CheckUtil.java#L181) limits only checks that end with `Check`, but we have checks that don't end with that. Example is `FileContentsHolder` and `SuppressWarningsHolder`.

In [testAllCheckstyleModulesInCheckstyleConfig](https://github.com/checkstyle/checkstyle/blob/62926b6106cbc22cb73f08c32b964c9e6e8d8b45/src/test/java/com/puppycrawl/tools/checkstyle/internal/AllChecksTest.java#L179-L181) we are trying to compare checks to modules. The test is named module so we should be checking all modules, right? Not all checks.

In [testAllCheckstyleModulesHaveMessage](https://github.com/checkstyle/checkstyle/blob/62926b6106cbc22cb73f08c32b964c9e6e8d8b45/src/test/java/com/puppycrawl/tools/checkstyle/internal/AllChecksTest.java#L189) we are checking only checks but we named the test module.

http://checkstyle.sourceforge.net/config.html#Modules
> Root module Checker has child FileSetChecks JavadocPackage and TreeWalker.
> Module TreeWalker has submodules AvoidStarImport, ConstantName, and EmptyBlock.

Everything we do is a module by these definitions. So `getCheckstyleModules` should return everything, and all tests that rely on it should be changed to better suite what they are testing.

**Comment by rnveach** [comment]
http://checkstyle.sourceforge.net/config.html#Checker
> AuditListener children: modules that report filtered events.

We also do not pull in `AuditListener`s as modules.
We should also extend that documentation to include all children. It is missing File Filters.

**Comment by romani** [comment]
>  Isn't everything we do a module?

If in config it is module so it is a module.

> AbstractFileSetCheck. Isn't that a module?

It is not, only exact implementations that could be instaciated could be a module.

> The test is named module so we should be checking all modules, right? Not all checks

Yes. Or rename the method.


> So getCheckstyleModules should return everything, and all tests that rely on it should be changed to better suite what they are testing.

If that is easy, yes. But we could rename it too.

**Comment by rnveach** [comment]
> > AbstractFileSetCheck. Isn't that a module?
> It is not, only exact implementations that could be instantiated 

Sorry for the confusion, I meant any type that extends `AbstractFileSetCheck`. For example, `TreeWalker` is not currently picked up as a module.

**Comment by romani** [comment]
Yes. Agree.
All classes that could be referenced in config are modules.

**Comment by romani** [comment]
@rnveach , PR is merged.
please close it if addressed all points that you raised int his issue.
