### ISSUE TITLE
remove deprecated property maxLineLength from LeftCurlyCheck

### ISSUE THREAD

**Issue by dbyron0** [checkstyle/checkstyle#3671]
I notice that https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/google_checks.xml#L55 specifies a maxLineLength property for LeftCurly, but http://checkstyle.sourceforge.net/config_blocks.html#LeftCurly says it's deprecated.  If it's OK to remove, I can submit a pull request.

Thanks.

-DB

**Comment by rnveach** [comment]
It is deprecated, and won't do anything if given.
https://github.com/checkstyle/checkstyle/blob/25a37e5049b7816b34c552899841a978efc37a63/src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/LeftCurlyCheck.java#L131-L133

We are removing a lot of deprecated stuff in version 8, so most likely this item will be added to the list.

**Comment by Kietzmann** [comment]
I am on it

**Comment by rnveach** [comment]
@romani Please see discussion at https://github.com/checkstyle/checkstyle/issues/3855#issuecomment-282307879 for why we don't keep this property.

**Comment by romani** [comment]
please share your ideas on - https://github.com/checkstyle/checkstyle/issues/3855#issuecomment-313551376

**Comment by romani** [comment]
PR referenced above was not complete and closed. New contributors are welcome to pick up this issue

**Comment by romani** [comment]
fix is merged.
