### ISSUE TITLE
ParameterName: deprecate 'scope' and 'excludeScope' properties, introduce new property 'accessModifiers'

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#3675]
```
$ cat config.xml 
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
                        "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
<module name="Checker">
  <property name="charset" value="UTF-8"/>
  <property name="severity" value="warning"/>
  <module name="TreeWalker">
    <module name="ParameterName">
      <property name="severity" value="warning"/>
      <property name="format" value="^([a-z][a-z][a-zA-Z])$"/>
      <property name="ignoreOverridden" value="false"/>
      <property name="scope" value="private"/>
    </module>
  </module>
</module>

$ cat MyClass.java 
public final class MyClass {
    /**
     * This is a method.
     * @author Name with dot.
     */
    public void foo(String publicPar){}

    /**
     * This is a method.
     * @author Name wihtout dot
     */
    private void foo2(String privatePar){}    
}

$ java -jar checkstyle-7.3-all.jar -c config.xml MyClass.java 
Starting audit...
[WARN] /var/tmp/MyClass.java:6:28: Name 'publicPar' must match pattern '^([a-z][a-z][a-zA-Z])$'. [ParameterName]
[WARN] /var/tmp/MyClass.java:12:30: Name 'privatePar' must match pattern '^([a-z][a-z][a-zA-Z])$'. [ParameterName]
Audit done.
```

scope is private, so expected violations are only on private methods.
the same for excludeScope.

Side note: when config is changed to work only with "public" - it works fine. Looks like scope is counted by more visible and less visible. But should be simply by matching.

**Comment by MEZk** [comment]
@romani 
Method [matchScope(https://github.com/MEZk/checkstyle/blob/3ddf152905d21e640033010bdafcfed6ee3b5bde/src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/ParameterNameCheck.java#L181-L181) uses [isIn](https://github.com/MEZk/checkstyle/blob/617ebf2bf27d284dcc7b866f85439fcf6dab3402/src/main/java/com/puppycrawl/tools/checkstyle/api/Scope.java#L64-L64) method which assumes that PUBLIC is a subscope of PRIVATE. That means that all methods with private and higher scopes will be checked. For now 'scope' parameter of the check sets the lower boundary of the scope to check.

> But should be simply by matching.

Get the idea, however it will completely change check's behavior for scopes.

**Comment by romani** [comment]
Yes, we have to change behavior completely to be clear on how it works.
That was recently requested to cover google rule, so we just need satisfy google rule

**Comment by MEZk** [comment]
@romani 
Just few examples of how it will work:

1) scope = private, format = ^h$
```java
public void v1(int haaa) {} // OK
protected void v4(int haaa) {} // OK
void v2(int haaa) {} // OK
private void v3(int abc) {} // violation
```

1) scope = private, format = ^h$
```java
public void v1(int haaa) {} // OK
protected void v4(int haaa) {} // OK
void v2(int haaa) {} // OK
private void v3(int abc) {} // violation
public void l() {
        FuncIfc l1 = (int lexp)->{}; // violation (scope is private)
        FuncIfc l2 = (limp)->{};  // violation (scope is private)
    }
```

2) scope = anoninner, format = ^h$
```java
public void v1(int haaa) {} // OK
protected void v4(int haaa) {} // OK
void v2(int haaa) {} // OK
private void v3(int abc) {} // OK
```

**Comment by MEZk** [comment]
@romani 
And also take a look at our description for 'scope' parameter type
http://checkstyle.sourceforge.net/property_types.html#scope

>The scope is treated inclusively (as javadoc does): 'package' means all 'package', 'protected' and 'public' methods/fields/classes.

**Comment by romani** [comment]
> Are they correct?

yes , that was smth we suppose to create initially.

> And also take a look at our description for 'scope' parameter type

#3511 .

> Maybe scope and exludeScope should become String parameters and declare the name of the scope. 

I think it is good idea.

**Comment by romani** [comment]
fix is merged.

**Comment by erikhuizinga** [comment]
This 'fix' causes an error in the event log of IntelliJ IDEA:
>The Checkstyle rules file could not be parsed.
> cannot initialize module TreeWalker - Property 'accessModifiers' in module ParameterName does not exist, please check the documentation
> The file has been blacklisted for 60s.

I use [google_checks.xml](blob/master/src/main/resources/google_checks.xml) and the [Checkstyle-IDEA IntelliJ plugin](https://github.com/jshiell/checkstyle-idea) on IntelliJ IDEA 2016.3.3.

**Comment by MEZk** [comment]
@erikhuizinga 
You gave the incorrect link
https://github.com/checkstyle/checkstyle/issues/blob/master/src/main/resources/google_checks.xml

I assume that you used  google_checks.xml from our master branch . That version of  google_checks.xml  has not been released yet. As you can see this issue has 'breaking compatibility' label which means that after release all changes in this issue become incompatible with previous Checkstyle version.

Please, use  google_checks.xml from our previous release.

**Comment by MEZk** [comment]
@romani 
The [link](https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/google_checks.xml) to  Checkstyle configuration for 'Google Java Style' refers to master version of google_checks.xml. It means that all changes that we make in google_checks.xml are available for users who want to download the config from Checkstyle site.  google_checks.xml usually contains unreleased changes. 

The [link](https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/google_checks.xml) to  Checkstyle configuration for 'Google Java Style' must point to release version of  google_checks.xml .

**Comment by erikhuizinga** [comment]
@MEZk thanks, my bad! Also, the link was indeed broken, my bad again, but I fixed it.

Is there by chance a permalink to the latest release raw xml? I can only find a URL to the file in the specific release: https://raw.githubusercontent.com/checkstyle/checkstyle/checkstyle-7.4/src/main/resources/google_checks.xml

**Comment by MEZk** [comment]
@erikhuizinga 
Sorry, but now we don't have the link, only specific release. We try to fix this ASAP.

**Comment by romani** [comment]
> s there by chance a permalink to the latest release raw xml?

No. to avoid problems with version differences  please use xml config from checkstyle jar, that is embedded.
to reference it do "/google_config.xml" (it will load it from classpath).
Example: http://checkstyle.sourceforge.net/cmdline.html#Download_and_Run

> The link to Checkstyle configuration for 'Google Java Style' must point to release version of google_checks.xml .

we need to think how to change search URL to reference strict tag, if that is possible by github API, so we could create issue to make it more secure.

**Comment by MEZk** [comment]
@romani 
Issue #3760 addresses the problem.

**Comment by erikhuizinga** [comment]
Take a look at: http://stackoverflow.com/questions/24987542/is-there-a-link-to-github-for-downloading-a-file-in-the-latest-release-of-a-repo
