### ISSUE TITLE
Holders should not do logging and have any logic for other modules

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#3691]
1) SuppressWarningsHolder is a Check that do logging , even it is not a real Check and suppose to be used for SuppressWarningsFilter.

All Holders should just be containers of data and general for all, whole logic should be in filters, checks, .... .

2) Holders should not extend AbstractCheck class. Documentation page where all Checks are listed should be fixed to state that Holder are not Checks.

**Comment by romani** [comment]
we will think about it in details during checkstyle8

what I see now is that Filter https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressWarningsFilter.java is using 
`public static boolean isSuppressed(AuditEvent event)` that method is doing examination bas eon internal cache of Entry classes, no AST there. AST is used during collection/creation of Entry cache.

**Comment by rnveach** [comment]
@romani Should this be closed in favor of https://github.com/checkstyle/checkstyle/issues/4831 ?

**Comment by romani** [comment]
yes, will be done in #4831
