### ISSUE TITLE
Google style: allow single character variables

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#3702]
Based on google/styleguide#214

Local variables and catch arguments, method parameters should be allowed to be one characters

**Comment by MEZk** [comment]
[Chapter 5.2.6 Parameter Names](https://google.github.io/styleguide/javaguide.html#s5.2.6-parameter-names) will be covered by https://github.com/checkstyle/checkstyle/pull/3722

**Comment by MEZk** [comment]
@romani 
I do not find any information about identifiers like ```aParam```. Should we allow them. Google Style guide does not prohibit their usage.

> Local variable names are written in lowerCamelCase.
Even when final and immutable, local variables are not considered to be constants, and should not be styled as constants.

> Parameter names are written in lowerCamelCase.
One-character parameter names in public methods should be avoided.

[lowerCamelCase section](https://google.github.io/styleguide/javaguide.html#s5.3-camel-case) does not say anything about such parameters names.

**Comment by rnveach** [comment]
@MEZk 
> I do not find any information about identifiers like `aParam`.

What about this?
https://google.github.io/styleguide/javaguide.html#s5.1-identifier-names
> In Google Style special prefixes or suffixes, like those seen in the examples `name_`, `mName`, `s_name` and `kName`, are not used.

**Comment by MEZk** [comment]
@rnveach 
Sorry, I did not notice that on the top and thought that ```identifiers``` did not refer to parameters) My fault.

**Comment by rnveach** [comment]
> thought that identifiers did not refer to parameters

We name parameter name as `IDENT` in CS tree, so I assume `identifiers` means all variable names.

> We need to update check's regexpes to disallow consequences of upper case characters.

It sounds reasonable. `AbbreviationAsWordInName` should be set to 0 too like we are planning to do in our own config at https://github.com/checkstyle/checkstyle/issues/3721#issuecomment-272285236.

**Comment by MEZk** [comment]
https://google.github.io/styleguide/javaguide.html#s5.1-identifier-names is a bit controversial:

They says:
> Identifiers use only ASCII letters and digits, and, in a small number of cases noted below, underscores. Thus each valid identifier name is matched by the regular expression \w+ .

```
\w+ matches any word character (equal to [a-zA-Z0-9_])
+ quantifier — Matches between one and unlimited times, as many times as possible, giving back as needed.
```

So one can think that identifiers with underscore are allowed: parameter_number1, parameter_number. But then Google Style states that 

> In Google Style special prefixes or suffixes, like those seen in the examples name_, mName, s_name and kName, are not used.

and 

>Parameter names are written in lowerCamelCase.

and 

> Local variable names are written in lowerCamelCase.

They should have prohibited underscore usage in the first sentence.

**Comment by romani** [comment]
@MEZk , do you still need comments from me ?

**Comment by MEZk** [comment]
@romani 
No.I'm OK to start resolving the issues.

**Comment by MEZk** [comment]
@romani @rnveach 
I came p with the following regexp pattern:
```^[a-z]{2,}([a-z0-9][A-Z]?[a-z0-9]*)*$```

Examples:
camelCase - MATCHES
Param1 - DOES NOT MATCH
singleLineCComment - DOES NOT MATCH
paramABBB - DOES NOT MATCH
param1 - MATCHES
1asd - DOES NOT MATCH

paramA1 - MATCHES (?)
paramA1Asdas - MATCHES (?)
asdqA1A1 - MATCHES (?)

(?) - Google Style guide allows digits in identifiers but says nothing about their placement in Camel Case.

**Comment by rnveach** [comment]
Fix is merged

**Comment by rnveach** [comment]
It should be noted that Google Style never responded to our requests to update their document.

Issue: https://github.com/google/styleguide/issues/226
PR: https://github.com/google/styleguide/pull/227
