### ISSUE TITLE
Checker's haltOnException doesn't obey severity property

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#3704]
````
$ cat TestClass.java
BAD

$ cat TestConfig.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>
    <property name="severity" value="warning"/>
    <property name="haltOnException" value="false"/>

    <module name="TreeWalker">
        <module name="FinalLocalVariable" />
    </module>
</module>

$ java -jar checkstyle-7.4-all.jar -c TestConfig.xml TestClass.java
Starting audit...
[ERROR] TestClass.java:0: Got an exception - com.puppycrawl.tools.checkstyle.api.CheckstyleException: NoViableAltException occurred during the analysis of file TestClass.java. [Checker]
Audit done.
Checkstyle ends with 1 errors.
````

Checker severity is set to `warning`, but checkstyle still ends with error when `haltOnException` is set to false and an exception happens.
Severity of violation must be `warning` for regression to not halt.

**Comment by romani** [comment]
`severity` is for violations only - for "expected"/"possible" feed-back from Checks/Modules.

Exceptions are not expected and reported to code that call checkstyle(Checker). Checkstyle should not log exceptions (I remember we fixed that some time ago), just throw it up to caller.

You use CLI, here Main class is caller of Checker, so Main class set log level to ERROR by default (with no customization, as it was never requested to be).

**Comment by rnveach** [comment]
@romani CLI is just example here as it is requested reporting for all issues, but this example does clearly show it reporting the violation as an error.

This issue is really tied to regression where we turn off `haltOnException`. Caller there is JXR and I believe maven-checkstyle-plugin.
[The purpose of `haltOnException` was to give us a way to print exceptions as a violation in regression because they halted the reporting process](https://github.com/checkstyle/checkstyle/issues/3611#issue-193642113). Unfortunately, [the set severity for these exceptions is `error` because we don't specify a specific severity level](https://github.com/checkstyle/checkstyle/blob/ec2834e43a38c63774dc34a4ebafb783fcb68ca2/src/main/java/com/puppycrawl/tools/checkstyle/Checker.java#L330-L333). `error` in regression has the same effect and still halts the regression process. [This is why the default configuration has `severity` set as warning](https://github.com/checkstyle/contribution/blob/6d26cc82719e456c24a1bbb6c95a2a2c09ff4c10/checkstyle-tester/my_check.xml#L11).

> so Main class set log level to ERROR by default (with no customization, as it was never requested to be).

I set `severity` to `warning` in configuration, so I am trying to tell it to not write these exceptions as errors.
Also Main does not set severity in this case, [It is set by `LocalizedMessage`](https://github.com/checkstyle/checkstyle/blob/25a37e5049b7816b34c552899841a978efc37a63/src/main/java/com/puppycrawl/tools/checkstyle/api/LocalizedMessage.java#L61).

> severity is for violations only

If we don't want to mix violations and exceptions, how about a configurable severity for exceptions then?

**Comment by romani** [comment]
Hmm, i am ok  to make it as cli option but not in Checker.

**Comment by rnveach** [comment]
> i am ok to make it as cli option but not in Checker.

How would that get set during regression?

**Comment by romani** [comment]
checkstyle should not process unexpected situations and delegate this to CLI or plugins or ....

we have an option 'haltOnException' , that reports exceptional event as ERROR and continue. Exceptional event != violation. Severity are for violations only.
So severity is not applicable to exceptional events.

**Comment by rnveach** [comment]
> and delegate this to CLI or plugins or ....

There is no way to delegate this out of the Root Module (Checker) at the moment. With `haltOnException` turned off, any exception is turned into a "violation" with a fixed severity of ERROR. Checker handles and prints all violations, and only passes back the number of errors it created. Violations are locked away inside Checker. We can hide violations with suppressions, we can change severity of normal violations through the configuration, but there is no standard way to change severity of this "exception violation".

https://github.com/checkstyle/contribution/pull/148 has a fix for this narrow, specific issue with `maven-checkstyle-plugin` and our regression scripts. Setting `failsOnError` to `false` prevents `maven-checkstyle-plugin` from stopping on any error violations, including those created by turning off `haltOnException`, and allows regression to continue.
