### ISSUE TITLE
PR validation for "approved" label does not work 

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#3707]
PR validation for "approved" label does not work.
In PR there is no requied variables that are defined in TRAVIS

```
{ "message": "Bad credentials", "documentation_url": "https://developer.github.com/v3" }
jq: error: Cannot index object with number
Messages from github:...
Issue number:
PR validation succeed.
```

todo: for PRs we need to send request without auth token (I hope we will not quickly run into limit of free requests).
for master commit validation, auth token should be used it will help to catch accidental merge of unapproved issue.

**Comment by rnveach** [comment]
Since we can't use private tokens in travis in PRs, why don't we encrypt the token directly in the YML file?
https://docs.travis-ci.com/user/encryption-keys/

**Comment by romani** [comment]
Let try

**Comment by Rahulkhinchi03** [comment]
@rnveach @romani 
Do we still need to encrypt the auth token in the `travis.yml` for master commit validation?

**Comment by romani** [comment]
Yes, encryption always required

**Comment by Rahulkhinchi03** [comment]
I just need to add this lines in travis.yml files? 
+ Where can I fin d the auth token which should be used? Do I have to generate a temporary GitHub Auth Token?
```
{"config"=>
  {"host"=>"travis-ci.org",
   "pusher"=>{"key"=>"AUTOTOKEN"},
   "github"=>
    {"api_url"=>"https://api.github.com",
     "scopes"=>
      ["read:org",
       "user:email",
       "repo_deployment",
       "repo:status",
       "write:repo_hook"]}}}
```
