### ISSUE TITLE
NoWhitespaceBefore: Add support for varargs

### ISSUE THREAD

**Issue by cypai** [checkstyle/checkstyle#3718]
I was surprised to see that NoWhitespaceBefore does not support varargs:
```
$ javac Test.java 
$ cat Test.java
public class Test {
    public static void main(String ... args) {} // Would like to have a violation here
}
```

There's no easy regex for this, so it would be nice to have this addition.

**Comment by romani** [comment]
I even surprised it is compilable, I have never seen such a code.

**Comment by romani** [comment]
This token should be in set of defaults

**Comment by rnveach** [comment]
Fix is merged
