### ISSUE TITLE
Verify tokens in checkstyle config

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#3720]
We have a test to verify all modules are used in our config file.
We don't have a test to verify we are using all tokens. Some of our check specify a limited amount of tokens to be used on in our configuration. It is not clear if this is on purpose, we don't want to use the token, or if we forgot to add the token in a PR when it was introduced.
Some checks are also split into 2 or more instances, so it makes it harder to verify that all tokens are being used.

We need a test to verify this.
New test should verify all acceptable tokens for all checks are being used. If we don't want a token to be used at all, it should be listed in an override section.
If one check is split into multiple instances, the tokens from those instances should be combined into one and verified that way. We don't care how the tokens are being used in those split instances, just that we are using them all.

**Comment by romani** [comment]
fix is merged.

**Comment by rnveach** [comment]
@romani Do we want to extend this validation to sevntu or google configurations?

**Comment by romani** [comment]
@rnveach , lets try to do this, but each config in separate issues.
