### ISSUE TITLE
Intorduce Snap CI as a new CI Server for Checkstyle

### ISSUE THREAD

**Issue by MEZk** [checkstyle/checkstyle#3728]
Snap CI web site
https://www.snap-ci.com

It is free for Open Source projects.

**Features**
https://www.snap-ci.com/features/

**Note**, Snap CI may not have yml-based configuration.

**Rationale**
We can move a part of pitest tests from Shippable CI to Snap CI in order to reduce the time of the build.

**Comment by MEZk** [comment]
Just to keep in mind. From Snap CI doc:
> Every stage in Snap runs on machines we call workers. Each worker has the following resources by default:
2 CPUs
2 GB of memory
10 GB of disk space

**Comment by romani** [comment]
> Snap CI announced that its last day will be August 1

https://dzone.com/articles/snap-ci-shutting-down-what-others-have-to-say
