### ISSUE TITLE
reevaluate tokens in IllegalTokenText

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#3729]
Taken from PR #3723 ,
When reviewing the tokens of IllegalTokenText, it was noticed that some tokens have no text that users can change, they are constants. It doesn't make sense to leave these tokens for the purpose of this check. If user wants to disallow a token, they should IllegalToken instead.

We need to identify these constant value tokens and remove them from the check.
We should try to make a UT for this for when any new tokens are added.

**Comment by rnveach** [comment]
There doesn't seem to be a way to identify token's with constant text from dynamic test unless we parse the grammar or generated java file.

Grammar: `#(#[ANNOTATION,"ANNOTATION"], `
Generate Java: `astFactory.create(ANNOTATIONS,"ANNOTATIONS")`

**Comment by romani** [comment]
@Vladlis , can we reuse checkstyle/target/generated-sources/antlr/com/puppycrawl/tools/checkstyle/grammars/GeneratedJavaTokenTypes.txt file for this validation ?
or reuse logic that generate this file and avoid dependencies to this file and do all in memory.

related files:
https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/doclets/TokenTypesDoclet.java
checkstyle/target/classes/com/puppycrawl/tools/checkstyle/api/tokentypes.properties

**Comment by Vladlis** [comment]
@romani , I don't see how these files can be useful
@rnveach , parsing might be too hard, try to find out what is the text of `CTOR_CALL` by parsing for example

I suppose we should try another @romani's idea: make a java file with all the tokens inside and see there whether names match texts taking into account a hardcoded list of exclusions (like text `;` for `SEMI`).

**Comment by rnveach** [comment]
> make a java file with all the tokens inside 

This would work, but would require this file to have all tokens incase we update the grammar. Even with all tokens, I'm not sure if we would need different ways of creating the tree in-case we use the same token differently elsewhere.
All the files `checkstyle\src\test\resources\com\puppycrawl\tools\checkstyle\grammars\InputRegressionJava*` were made for this purpose. You could just reuse them by either re-running the Java tree or reading their printed parse tree.

> taking into account a hardcoded list of exclusions 

Doesn't that defeat the purpose of trying to make a list dynamically instead of hardcoding said list?

**Comment by romani** [comment]
I did review of issue one more time.

I do not see good dynamic model of verification.
To resolve this issue I recommend to:
- make special UT in this check to control amount of Tokens to fail each time we will add new token.
- in UT we should make hardcoded list of tokens that will not have text from source/input file.
- to minimize hardcoded list, we can skip all tokens that have "LITERAL" in name (GeneratedJavaTokenTypes.java could help)

**Comment by rnveach** [comment]
Fix is merged
