### ISSUE TITLE
expand documentation on METHOD_REF token

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#3731]
Taken from PR #3723 ,

Documentation for METHOD_REF at http://checkstyle.sourceforge.net/apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#METHOD_REF needs to be expanded, preferably with an example of it used in java code like some of the other tokens.

**Comment by romani** [comment]
Assigned to Vadzim Matsiushona­k

**Comment by Luolc** [comment]
I am on it :)

**Comment by romani** [comment]
fix is merged.
