### ISSUE TITLE
Override default modules

### ISSUE THREAD

**Issue by andreevym** [checkstyle/checkstyle#3738]
can you add opportunity to override models in default xml?

**Comment by romani** [comment]
@andreevym , please be as detailed as possible. 
What is "model" ? What do you mean by "override". Whats is "default xml" ?

just describe what you have now in details and what you would like to be able to do (in details).

**Comment by andreevym** [comment]
I have maven plugin with 
There are 2 predefined rulesets: sun_checks.xml, google_checks.xml
I want to change predefined value:
1) does not require package-info.java
2) max line length 150
3) TODO becomes warning instead of error

My maven pom is
<plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-checkstyle-plugin</artifactId>
        <version>2.17</version>
        <executions>
          <execution>
            <id>validate</id>
            <phase>validate</phase>
            <configuration>
              <encoding>UTF-8</encoding>
              <consoleOutput>true</consoleOutput>
              <failsOnError>true</failsOnError>
            </configuration>
            <goals>
              <goal>check</goal>
            </goals>
          </execution>
        </executions>
      </plugin>

**Comment by jochenvdv** [comment]
Checkstyle does not yet support overriding or inheriting configurations (this is a duplicate of issue #2873).

You have to create your own configuration file for now that you can base on the default Google or Sun style. Copy `sun_checks.xml` or `google_checks.xml` and adapt to your needs. Configure `pom.xml` to use your custom configuration using the `configLocation` tag.

**Comment by romani** [comment]
OK you use maven plugin.
Let's imagine that all is possible. Please write us configuration you would like to have to make it happen for all three cases that you mentioned.

I need to know user preferences.

**Comment by andreevym** [comment]
I hope people wants customize common and override xml

We’ve found 967 code results
https://github.com/search?l=Maven+POM&q=sun_checks.xml&type=Code&utf8=%E2%9C%93

1) I comment 

We’ve found 15,840 code results
https://github.com/search?q=%3C%21--%3Cmodule+name%3D%22JavadocPackage%22%2F%3E--%3E&type=Code&utf8=%E2%9C%93

2) add 
    <module name="LineLength">
      <property name="max" value="150"/>
    </module>
3) I comment

**Comment by romani** [comment]
@andreevym , customization is known demand.

main question how to users want it to looks like, overrides by Xpath or ....

**Comment by andreevym** [comment]
POM looks like they want to write xml, maybe add specific <override> and add in this block xml, or path to xml file.

I just think like work with xml like with JAXB objects for me it's one field, and I want to change this field.

**Comment by rnveach** [comment]
@romani Since this thread has become inactive, me and @jochenvdv came up with a more concrete examples of how we think inheritance in configurations should look like in #2873 .

**Comment by andreevym** [comment]
Sorry guys, but I open this conversation to recognize requirements to solve this problem. I didn't understand why you discuss in another "issue".
