### ISSUE TITLE
Verify tokens in google config

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#3740]
Spinoff of Issue #3720

We are now verifying if tokens should or shouldn't be in our checkstyle configuration and we found some missing ones that we added in the mentioned issue.

We should extend this to check tokens in google's configuration.

> New test should verify all acceptable tokens for all checks are being used. If we don't want a token to be used at all, it should be listed in an override section.

**Comment by romani** [comment]
Mostly fixed. 
There are few others issues created
