### ISSUE TITLE
reevaluate tokens in google config for OperatorWrapCheck

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#3749]
Taken from PR #3743,
When reviewing the tokens of OperatorWrapCheck, it is unclear if we should add the following tokens to google configuration.

> "DIV_ASSIGN", "BOR_ASSIGN", "SL_ASSIGN", "ASSIGN", "BSR_ASSIGN", "BAND_ASSIGN", "PLUS_ASSIGN", "MINUS_ASSIGN", "SR_ASSIGN", "STAR_ASSIGN", "BXOR_ASSIGN", "MOD_ASSIGN"

We should review them and ask google for clarification.

**Comment by rnveach** [comment]
All the tokens in question are assignment operators.

http://checkstyle.sourceforge.net/reports/google-java-style-20160712.html#s4.5.1-line-wrapping-where-to-break
> When a line is broken at an assignment operator the break typically comes after the symbol, but either way is acceptable.

Either is acceptable, but they prefer after the symbol.
@romani How do we want to handle this? Just ignore the tokens since either method is acceptable?

**Comment by romani** [comment]
if acceptable it means allowed.
checkstyle can not satisfy "preferred" term at all. In checkstyle it is either allowed or forbidden.

**Comment by rnveach** [comment]
@romani Then for this issue, we will not add the tokens or change the configuration and and just update the reason in the test, correct?

**Comment by romani** [comment]
yes.
we might add this cases in ITs to enforce this a bit firmly.
