### ISSUE TITLE
Config: forbid assert token by Illegal token Check

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#3751]
https://github.com/checkstyle/checkstyle/blob/master/config/checkstyle_checks.xml#L223

Assert token should be added.
Why we have two lines for tokens ?  It is override. Should be forbidden by XML schema.

**Comment by rnveach** [comment]
@romani 
> Why we have two lines for tokens ? It is override. Should be forbidden by XML schema.

[DefaultConfiguration merges multiple properties together like it was one line.](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/DefaultConfiguration.java#L106-L114) Some were already like this in the config, so I thought it was acceptable for history viewing to clearly show removes/adds.
[There is an old commit where tokens were purposely made like this.](https://github.com/checkstyle/checkstyle/commit/95f7a7cde50ceac50d41c2bff65b6983c888bea3) Most of those changes and documentation are still around.
Ex: http://checkstyle.sourceforge.net/property_types.html#stringSet
> this property can be supplied multiple times which is equivalent to a set of comma separated strings.

**Comment by romani** [comment]
fix for config is merged.
