### ISSUE TITLE
reevaluate tokens in google config for NeedBracesCheck

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#3753]
Taken from PR #3743,
When reviewing the tokens of NeedBracesCheck, we would like more time to review the following tokens before adding them.

> LAMBDA

**Comment by rnveach** [comment]
`NeedBracesCheck` will require braces always when the statements are used.

http://checkstyle.sourceforge.net/reports/google-java-style-20160712.html#s4.1-braces
> Braces are used with if, else, for, do and while statements

It doesn't mention lambda, so it is not requesting them all the time.
http://checkstyle.sourceforge.net/reports/google-java-style-20160712.html#s4.1.2-blocks-k-r-style is only mentioning if the braces are added.

Going even further, the newest style guide has an example of a lambda with no braces.
https://google.github.io/styleguide/javaguide.html#s4.5.1-line-wrapping-where-to-break

@romani It seems to me there is nothing that requests lambda have braces all the time. So the configuration shouldn't change.
We just need to update the reason in the test.

**Comment by romani** [comment]
yes, comment need to be updated

from new guide:

> A line is never broken adjacent to the arrow in a lambda, except that a break may come immediately after the arrow if the body of the lambda consists of a single unbraced expression.

It is requirements. can Check cover it ?

**Comment by rnveach** [comment]
@romani 
`NeedBraces` doesn't deal with line breaks and the requirement is `unbraced`.
`unbraced` also throws out `LeftCurlyCheck`.
Even if `SeparatorWrap` or `OperatorWrap` could handle the lambda token, which it can't, it can't handle the extra requirement by default (`if the body of the lambda consists of a single unbraced expression`). The checks just look at the token itself for the most part.

**Comment by romani** [comment]
Fix is merged
