### ISSUE TITLE
try to avoid non jdk runtime exceptions in code

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#3763]
We should avoid usage of non-jdk exceptions that could be thrown from our code.
`org.apache.commons.beanutils.ConversionException` should be changed to IllegalArgumentException.
Whole code should be reviewed to fins similar cases.
Try to forbid this by ImportControl check.

```
import org.apache.commons.beanutils.ConversionException;
.....
public class RightCurlyCheck extends AbstractCheck {
.....
    public void setOption(String optionStr) {
        try {
            option = RightCurlyOption.valueOf(optionStr.trim().toUpperCase(Locale.ENGLISH));
        }
        catch (IllegalArgumentException iae) {
            throw new ConversionException("unable to parse " + optionStr, iae);
        }
}
```

**Comment by rnveach** [comment]
fix is merged

**Comment by mkordas** [comment]
@romani what was wrong with using non-JDK exceptions? Are there any articles or blog posts saying it is a bad practice?

**Comment by romani** [comment]
@mkordas , just minimization of dependencies to thirdparty libraries for no reason in our project.
It is not idea for new Check :). Just desire to keep usage of classes under control and do not use smth fancy from thirdparty library is there is analog/similar class in jdk.
