### ISSUE TITLE
refactoring: RightCurlyCheck code expression

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#3764]
https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java#L174

```
    @Override
    public void visitToken(DetailAST ast) {
        final Details details = getDetails(ast);
        final DetailAST rcurly = details.rcurly;

        if (rcurly != null && rcurly.getType() == TokenTypes.RCURLY) {
        .....
```

Why rcurly variable could store non `TokenTypes.RCURLY` .
I might miss smth, but expected code is 
```
       .....
        if (rcurly != null) {
       .....
```

**Comment by rnveach** [comment]
`ELSE` doesn't verify that it has curlies.
https://github.com/checkstyle/checkstyle/blob/b4a337a599e853cdc44b19a76da28fcfab2956cd/src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java#L338-L348
https://github.com/checkstyle/checkstyle/blob/b4a337a599e853cdc44b19a76da28fcfab2956cd/src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java#L350-L355

**Comment by romani** [comment]
get details method should put in field only curly AST token

**Comment by romani** [comment]
Fix is merged
