### ISSUE TITLE
Add the Hibernate Search project to the Checkstyle CI

### ISSUE THREAD

**Issue by yrodiere** [checkstyle/checkstyle#3790]
As per our discussion in https://github.com/yrodiere/hibernate-search/commit/a62a9e2e31edbb31f83ee3b893afb43b19659c42#commitcomment-20699212, I'm creating this ticket to add the [Hibernate Search](https://github.com/hibernate/hibernate-search) project to your CI.

The branch master has been [recently updated](https://github.com/hibernate/hibernate-search/commit/e0b13416813744a9c0554b23248cb5518b9446a1) and builds successfully on Checkstyle 7.4, because we are affected by issue #3789 in 7.5. The Checkstyle version used in the build can be controlled using the maven property `puppycrawl.checkstyle.version`.

The repo includes a `.travis.yml` file. To set up a different CI, please see https://github.com/hibernate/hibernate-search#building-from-source.

**Comment by romani** [comment]
fix is merged.

**Comment by romani** [comment]
additional updates (cleanup for cloned sources) were required to resolve wercker limitations:
```
Storing artifacts
Storing artifacts failed: Size exceeds maximum size of 1000MB
```
