### ISSUE TITLE
Wercker CI should use Checkstyle's own Docker image

### ISSUE THREAD

**Issue by MEZk** [checkstyle/checkstyle#3799]
As Wercker CI has become more popular (https://github.com/checkstyle/checkstyle/issues/3798, https://github.com/checkstyle/checkstyle/issues/3670, https://github.com/checkstyle/checkstyle/issues/3790), it would be good to have our own Docker Profile and Image.

What should be done in scope of this issue:

- Docker Profile need to be created

- Docker Profile need to be uploaded to Checkstyle's Github repo to make it available from DockerHub

- Docker Image should be built based on Arch Linux/Ubuntu/CentOS or Mint

- Docker Image need to be uploaded to DockerHub

- Wercker should use Checkstyle's own Docker Image.

**Comment by romani** [comment]
What is a reason of special docker ?

**Comment by MEZk** [comment]
Now Checkstyle Wercker config depends on Maven Docker Image which itself depends on Ubuntu Docker Image. It means that if they decided to change something in the image which can affect Checkstyle execution process, it will result in continuous build failure.

**Comment by romani** [comment]
It is is strict docker image. It will stay as it now for very long time. I do see any risk and any possible build failures.
