### ISSUE TITLE
Typo in website documentation for JavadocMethod.

### ISSUE THREAD

**Issue by NickButcher1** [checkstyle/checkstyle#3800]
There is a typo in this sentence

	whether to ignore errors when a method declares that it throws exceptions but does have matching throws tags in the javadoc.

on this page

http://checkstyle.sourceforge.net/config_javadoc.html#JavadocMethod

Replace "does have" with "does not have".

Thanks.

**Comment by romani** [comment]
thanks a lot.

next time you find typo in docs, you can fix it yourself online (all documentation is in repo), without any code checkout
https://github.com/checkstyle/checkstyle/edit/master/src/xdocs/config_javadoc.xml#L256 , do changes, create PR, done.

**Comment by romani** [comment]
fix is merged.
