### ISSUE TITLE
messages_ja.properties contains funny (wrongly machine-translated) messages

### ISSUE THREAD

**Issue by satob** [checkstyle/checkstyle#3831]
messages_ja.properties in directories listed below contains some funny (wrongly machine-translated) messages.

- src/main/resources/com/puppycrawl/tools/checkstyle/checks/annotation/messages_ja.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/blocks/messages_ja.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_ja.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/design/messages_ja.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/imports/messages_ja.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/indentation/messages_ja.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_ja.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/messages_ja.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/metrics/messages_ja.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/naming/messages_ja.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/regexp/messages_ja.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/sizes/messages_ja.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/messages_ja.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/messages_ja.properties

For example:
> final.parameter = パラメータ{0}最終的にする必要があります。

(reserved word "final" was wrongly translated to Japanese "最終的")

> trailing.comments = コメントを末尾に使用DON''T。

(maybe string "Don''t" wasn't handled propery in machine translation)

> properties.duplicate.property = 重複プロパティ ''{0}'' {1} の発生（S））。

(the message don't have beginning parenthesis, and plural "s" remains in the message (Japanese word don't have plural form))

**Comment by rnveach** [comment]
We have no native translators so we must rely on google translate.
If you can, feel free to give corrections and be welcome with a PR.

**Comment by romani** [comment]
Fix is merged
