### ISSUE TITLE
RequireThisCheck is not fully covered with UTs

### ISSUE THREAD

**Issue by MEZk** [checkstyle/checkstyle#3848]
Due to https://github.com/checkstyle/checkstyle/issues/3843 it appears that RequireThisCheck is not fully covered:

![screenshot at 2017-02-22 00-36-32](https://cloud.githubusercontent.com/assets/7242568/23186120/fcdf4228-f896-11e6-8821-79d13698ac48.png)

100% branches and lines coverage need to be reached.

**Comment by MEZk** [comment]
I'm on it.

**Comment by romani** [comment]
fix is merged.
