### ISSUE TITLE
WhitespaceAfterCheck

### ISSUE THREAD

**Issue by rwalkerands** [checkstyle/checkstyle#3850]
/var/tmp $ javac an/extremelylongpackagenamethat/hasmultiplecomponents/Test.java
/var/tmp $ cat an/extremelylongpackagenamethat/hasmultiplecomponents/Test.java
```
package an.extremelylongpackagenamethat.hasmultiplecomponents;

public class Test {

    public static void main(String args[]) {
        Test test =
            new an.extremelylongpackagenamethat.hasmultiplecomponents.Test();
        Test test2 = (an.extremelylongpackagenamethat.hasmultiplecomponents.
                 Test) test;
    }

}
```
/var/tmp $ cat config.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module PUBLIC "-//Puppy Crawl//DTD Check Configuration 1.3//EN" "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
  <property name="severity" value="warning"/>
  <module name="TreeWalker">
    <module name="WhitespaceAfter"/>
  </module>
</module>
```
/var/tmp $ java -jar checkstyle-7.5.1-all.jar -c config.xml an/extremelylongpackagenamethat/hasmultiplecomponents/Test.java
```
Starting audit...
[WARN] /private/var/tmp/an/extremelylongpackagenamethat/hasmultiplecomponents/Test.java:9:23: 'typecast' is not followed by whitespace. [WhitespaceAfter]
Audit done.
```

---------------

Describe what you expect in detail.

I expect no warning. There _is_ whitespace after the cast. The check seems to get confused by the fact that there is a line break in the cast. I have to have a line break in order to keep the line under 80 characters.

--------------

**Comment by rnveach** [comment]
@romani This looks valid. [When we first receive the token, we capture the line we are dealing with](https://github.com/checkstyle/checkstyle/blob/b4a337a599e853cdc44b19a76da28fcfab2956cd/src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAfterCheck.java#L104) and [this is the line we use to validate against for whitespaces](https://github.com/checkstyle/checkstyle/blob/b4a337a599e853cdc44b19a76da28fcfab2956cd/src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAfterCheck.java#L107).
Unfortunately `TYPECAST` is a special case [where we use a different token to validate against and we don't update the line](https://github.com/checkstyle/checkstyle/blob/b4a337a599e853cdc44b19a76da28fcfab2956cd/src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAfterCheck.java#L106). The token we are now examining is on a different line, and this causes the false violation.

Had the user had 1 extra space in the place we are looking on the previous line, no violation would have shown.
````
$ cat TestClass.java
package test;

public class TestClass {
    public void test() {
        Test test =
                new an.extremelylongpackagenamethat.hasmultiplecomponents.Test();
        Test test2 =  (an.extremelylongpackagenamethat.hasmultiplecomponents.
                 Test) test;
    }
}


$ cat TestConfig.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>

    <module name="TreeWalker">
    </module>
</module>

$ java -jar checkstyle-7.5.1-all.jar -c TestConfig.xml TestClass.java
Starting audit...
Audit done.
````

**Comment by romani** [comment]
@rnveach , workaround is funny.

issue is approved.

@rwalkerands , please be welcome to provide the fix, as this case is  so rear.

**Comment by rwalkerands** [comment]
Adding a space at the end of a line is not possible for me, otherwise -- with my actual configuration (based on Sun checks) -- I get a warning about trailing whitespace. (And I have Eclipse configured to remove it on save, anyway.)

**Comment by rwalkerands** [comment]
Oh sorry, misread it completely. I now see where the space is. Indeed, it raised an eyebrow.

**Comment by romani** [comment]
Fix is merged
