### ISSUE TITLE
Travis CI is always green even command return not zero exit code

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#3858]
master and PRs are affected:
https://travis-ci.org/checkstyle/checkstyle/jobs/204781086#L301
https://travis-ci.org/checkstyle/checkstyle/jobs/204944791#L864

**Comment by rnveach** [comment]
Checking the return code after the script executes may be a solution.
https://travis-ci.org/rnveach/checkstyle/builds/205072852#L189-L194
