### ISSUE TITLE
Eclipse Checkstyle - The following solutions are not available checkstyle plug-in 7.3.0

### ISSUE THREAD

**Issue by 1Mark** [checkstyle/checkstyle#3859]
I can't install checkstyle I keep getting

The following solutions are not available checkstyle plug-in 7.3.0

The same with other plugins too.

Help -> Eclipse Marketplace -> SearchBox (checkstyle) -> then I recieve

The following solutions are not available: Checkstyle Plug-in 7.3.0 (id=net.sf.eclipsecs.feature.group, site=http://eclipse-cs.sourceforge.net/update/)

**Comment by rnveach** [comment]
Looks the same as Issue #3834.

@1Mark You will probably have to contact the people who maintain the Eclipse-CS Plugin at https://sourceforge.net/p/eclipse-cs/bugs/ .
We only deal with the utility JAR, not the eclipse plugin.

**Comment by rnveach** [comment]
This is the reported bug already: https://sourceforge.net/p/eclipse-cs/bugs/419/
