### ISSUE TITLE
appveyor:  provide ability to skip CI executions base on commit files

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#3870]
continuation of #3818 .

we need to extend build script to skip CI execution if non-related files are changed only.
wercker , travis, distelli, shippable are already  updated.

**Comment by padmavasanth** [comment]
Hi @romani - Can I work on this fix?

**Comment by romani** [comment]
be welcome !

**Comment by umkamax** [comment]
I working with the issue.

**Comment by romani** [comment]
fix is merged.

@umkamax , thanks a lot for elegant solution.
