### ISSUE TITLE
Pattern doesn't match the lowerCamelcase

### ISSUE THREAD

**Issue by tfereyre** [checkstyle/checkstyle#3871]
![testpattern](https://cloud.githubusercontent.com/assets/26063123/23363318/64214550-fcfa-11e6-9a4a-4ebb8864260c.jpg)

The local variable "aKey" doesn't match the following google style pattern : `"^[a-z]([a-z0-9][a-zA-Z0-9]*)?$"`. See my test case

**Comment by romani** [comment]
issue need to be formatted as demanded at http://checkstyle.sourceforge.net/report_issue.html#How_to_report_a_bug

if no requested details provided , issue will be closed as invalid in 2 weeks.

**Comment by tfereyre** [comment]
It's just a pattern problem in google_checks.xml. Sorry but I will not have time to install an run checkstyle. I mean I solved the problem using the default checkstyle pattern instead of the google one.
