### ISSUE TITLE
WritingChecks: add documentation on java grammar

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#3883]
'Writing Javadoc Checks' has a full example on using the CLI to print the javadoc tree. http://checkstyle.sourceforge.net/writingjavadocchecks.html#Tool_to_print_Javadoc_tree_structure

Java has a somewhat similar section with http://checkstyle.sourceforge.net/writingchecks.html#The_Checkstyle_SDK_Gui , but it doesn't contain a full example and doesn't mention the CLI.
I wanted to use something like the javadoc one to point new people to see to get familar with our Java tree, but a full example doesn't seem to exist unless I missed it.

I think we should add a new section 'Tool to print Java treestructure' to 'Writing Checks'. Show users how to use the CLI and give a full example of our Java tree just like Javadoc does.

**Comment by sagar-shah94** [comment]
I am on it.

**Comment by rnveach** [comment]
Fix is merged
