### ISSUE TITLE
Erroneous 'Equals Avoid Null' reported when argument to equals(Object) is not a string literal

### ISSUE THREAD

**Issue by demonfiddler** [checkstyle/checkstyle#3886]
There's no point reporting 'Equals Avoid Null' if transposing the equals() receiver and argument would result in the same error being reported. This error should **only** be reported for expressions of the form `variable.equals("string literal")`.

For example:

`return a.equals(b + c);`

gets flagged with an error, despite the fact that transposing the expression to:

`return (b + c).equals(a);`

would also get flagged with the same error.

**Comment by rnveach** [comment]
I am unable to reproduce your results.

issue need to be formatted as demanded at https://github.com/checkstyle/checkstyle/blob/master/.github/ISSUE_TEMPLATE.md (example: http://checkstyle.sourceforge.net/report_issue.html#How_to_report_a_bug )

**Comment by jabbar86** [comment]
Use “some String literal”.equals(myString) instead of myString.equals(“some String literal”). it saves null check..
String myString = getSomeString();
if ("some String literal".equals(myString)) {
  // do something 
}

**Comment by demonfiddler** [comment]
@jabbar86 please re-read my original description - you obviously haven't understood it.

**Comment by rnveach** [comment]
@jabbar86 Please give us a demonstration of the issue you are having like I asked in my other comment.

**Comment by rnveach** [comment]
I will close this issue in 2 weeks if no new information is given.

**Comment by rnveach** [comment]
Issue closed due to no response. Issue can be reopened with response.
