### ISSUE TITLE
Split and Organize Checkstyle inputs by Test for WhitespaceAfterCheck

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#3897]
subtask of #3891 .

do a copy of all test input files to separate folder for WhitespaceAfterCheck .
Not any other Check should use new inputs.

**Comment by romani** [comment]
pre-assigned to Pedro Portela .

**Comment by Pedro12909** [comment]
Working on it!

**Comment by Pedro12909** [comment]
I'm struggling to figure out what I'm supposed to do to fix this issue. Could you provide me some clearance? Thanks in advance!

**Comment by romani** [comment]
find UT file - WhitespaceAfterCheckTest
look for lines like "verify(configurationTestCast, getPath("InputWhitespace.java"), expected);"
you need to copy all input files to separate folder and name them as InputWhitespaceAfterXXXX. All that files should be in separate folder to let other check do not use them at all.

**Comment by romani** [comment]
fix is merged.
