### ISSUE TITLE
Split and Organize Checkstyle inputs by Test for WhitespaceAround

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#3898]
subtask of #3891 .

do a copy of all test input files to separate folder for WhitespaceAround.
Not any other Check should use new inputs.

**Comment by romani** [comment]
pre-assigned to Nikhil Shinde (https://groups.google.com/forum/#!topic/checkstyle-devel/zFiXoW7k9Co)

**Comment by nikshinde1996** [comment]
I am on it !

**Comment by nikshinde1996** [comment]
I have followed all the steps provided by your description.. Then how come build failed. Please guide me to fix this issue.

**Comment by rnveach** [comment]
@nikshinde1996 See my comments at https://github.com/checkstyle/checkstyle/pull/3982#issuecomment-285866174

**Comment by shivanshsoni** [comment]
@nikshinde1996 Are you still working on this issue?

**Comment by romani** [comment]
fix is merged
