### ISSUE TITLE
Split and Organize Checkstyle inputs by Test for TypecastParenPad

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#3900]
subtask of #3891 .

do a copy of all test input files to separate folder for TypecastParenPad.
Not any other Check should use new inputs.

**Comment by romani** [comment]
Pre-assigned to Rishabh Mehrotra .
https://groups.google.com/forum/m/#!topic/checkstyle-devel/5rsmhCi-jUI

**Comment by ps-sp** [comment]
Kindly review the modifications I made and let me know if it'd be alright to make a pull request for it.

**Comment by rnveach** [comment]
Fix is merged.

**Comment by RishMeh19** [comment]
I am on it
