### ISSUE TITLE
Formatting issue in documentation

### ISSUE THREAD

**Issue by sagar-shah94** [checkstyle/checkstyle#3902]
At following link
http://checkstyle.sourceforge.net/writingjavadocchecks.html#HTML_Code_In_Javadoc_Comments
when ever you try to zoom in browser following line comes out of box and due to which scrollbar comes in bottom part of browser

line where issue is:
**[ERROR:0] Javadoc comment at column 1 has parse error. Missed HTML close tag 'audio'. Sometimes it means that close tag missed for one of previous tags.**
![image](https://cloud.githubusercontent.com/assets/6566854/23555557/65a5aa44-004f-11e7-9395-93ad31ea3610.png)
I have attached a screenshot of issue.

**Comment by sagar-shah94** [comment]
i am on it

**Comment by rnveach** [comment]
If you zoom in enough, all source areas will see this issue. So it is not restricted to this one area.

**Comment by romani** [comment]
problem with line wrap in code block is general for whole site. Some CSS magic is required.

**Comment by rnveach** [comment]
Fix is merged
