### ISSUE TITLE
I am on it

### ISSUE THREAD

**Issue by RishMeh19** [checkstyle/checkstyle#3903]
/var/tmp $ javac YOUR_FILE.java

[[PLACE YOUR OUTPUT HERE]]

/var/tmp $ cat YOUR_FILE.java

[[PLACE YOU OUTPUT HERE]]

/var/tmp $ cat config.xml

[[PLACE YOUR OUTPUT HERE]]

/var/tmp $ java -jar checkstyle-X.XX-all.jar -c config.xml YOUR_FILE.java

[[PLACE YOUR OUTPUT HERE]]

---------------

Describe what you expect in detail.

--------------

Still not clear ??? - see example - http://checkstyle.sourceforge.net/report_issue.html#How_to_report_a_bug

**Comment by RishMeh19** [comment]
I am on it

**Comment by MEZk** [comment]
@romani @rnveach 
Please close the issue as the author did not read [the manual](http://checkstyle.sourceforge.net/report_issue.html#How_to_report_a_bug) at all. Issue is unclear and looks like a mockery.
