### ISSUE TITLE
Split and Organize Checkstyle inputs by Test for SeparatorWrap

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#3904]
subtask of #3891 .

do a copy of all test input files to separate folder for SeparatorWrap .
Not any other Check should use new inputs.

**Comment by romani** [comment]
pre-assigned to Vrushank Upadhyay 
https://groups.google.com/forum/#!topic/checkstyle-devel/C-ZlDU-Qg78

**Comment by sagar-shah94** [comment]
@romani Vrushank Upadhyay has not commented "i am on it"
Can i comment if i want to work on this issue?

**Comment by sagar-shah94** [comment]
I am on it

**Comment by rnveach** [comment]
Fixed is merged
