### ISSUE TITLE
SummaryJavadoc: no violation on absent summary and on javadoc where '.' is used not as end of sentense

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#3907]
taken from #3014

```
$ cat config.xml 
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
<module name="Checker">
    <module name="TreeWalker">
        <module name="SummaryJavadoc">
        </module>
    </module>
</module>

$ cat Test.java 
public class Test {

    /**
     * JAXB 1.0 only default validation event handler
     */
    public static final byte NUL = 0;

    /**
     * @throws Exception if an error occurs.
     */
    public void foo1() throws Exception {

    }

    /**
      * @return 1.
      */
    public int foo2(){
        return 1;
    }

    /**
      * <a href="mailto:vlad@htmlbook.ru"></a>
      */
    public void foo3() {

    }
    /**
     *  A {@code Foo.  Foo}
     */
    public void foo(){

    }

}

$ java -jar checkstyle-7.6-all.jar -c config.xml Test.java 
Starting audit...
Audit done.
```

Expected: violations for each javadocs

**Comment by sagar-shah94** [comment]
I am on it

**Comment by sagar-shah94** [comment]
Sir How following java docs violates condition?
  /**
      * @return 1.
      */

 /**
     * @throws Exception if an error occurs.
     */

**Comment by sagar-shah94** [comment]
Do i have to consider this case?is it valid or invalid?
For java summary docs we have to consider only first line ..Am i right?
/**
* This is test
* Valid or invalid.
*/

**Comment by romani** [comment]
>think no violation message should be shown for these java docs

There are first sentence at all, so it is a violation. Javadoc Tagged lines are not a first sentence. They does not belong to description.

**Comment by romani** [comment]
>Do i have to consider this case?is it valid or invalid?

Valid. Just first sentence is wrapped to few lines.

**Comment by sagar-shah94** [comment]
ok sir thanx

**Comment by sagar-shah94** [comment]
@romani @rnveach  should i create separate class to check period at the end of sentence or i should add method in summaryjavadoccheck.java we can throw only one exception at a time so it is better to create separate class for this.
What do you say?

**Comment by rnveach** [comment]
We are expecting a fix to `SummaryJavadocCheck`. Issue will have special label for that called `new module`.

> we can throw only one exception 

Why are we throwing exceptions? Exceptions should be last resort when something out of our hands has gone wrong (file not found, etc.).

**Comment by sagar-shah94** [comment]
@rnveach @romani 
i think at this line it violates a condition.this javadoc should not be placed in InputCorrectSummaryJavaDoc.java file .

https://github.com/checkstyle/checkstyle/blob/master/src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/InputCorrectSummaryJavaDoc.java#L19

**Comment by rnveach** [comment]
> this javadoc should not be placed in InputCorrectSummaryJavaDoc.java file .

it is the same as example's `foo1`, so yes, it shouldn't be in `correct` file.

**Comment by sagar-shah94** [comment]
Should i create issue to move that code to another file?

**Comment by rnveach** [comment]
@sagar-shah94 no, it can be done in this issue as we are correcting these cases to be violations.

**Comment by sagar-shah94** [comment]
@rnveach @romani 
in following case period should be after A or after A {@code Foo.  Foo}?
    /**
     *  A {@code Foo.  Foo}
     */
    public void foo(){

    }
in following case do we have to put period after closing anchor tag or summary java doc is missing?
<a href="mailto:vlad@htmlbook.ru"></a>

**Comment by romani** [comment]
> in following case period should be after A or after A {@code Foo. Foo}?

we do not know fore sure, only user know, 
but in case no period is defined at all we we have to demand at the most end - after `{@code Foo. Foo}`.

> in following case do we have to put period after closing anchor tag or summary java doc is missing?

at the most end , after closing anchor tag.

**Comment by rnveach** [comment]
Fix was merged, new issues will be created on code style
