### ISSUE TITLE
CommitValidationTest: add character limit to line

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#3910]
Taken from https://github.com/checkstyle/checkstyle/pull/3905#issuecomment-284103522:

We restrict commit messages to be 1 line to be concise, but we don't limit how long that line can be allowing users to create 400+ character messages.

`CommitValidationTest` needs to be modified to restrict the line length to 200 characters.

Rules message needs to be updated to show this new rule with it's own number when validation fails so users know how to correct the issue.

**Comment by sagar-shah94** [comment]
i am on it.

**Comment by ps-sp** [comment]
On it

**Comment by sagar-shah94** [comment]
Already sent pull request

**Comment by ps-sp** [comment]
kudos.

**Comment by sagar-shah94** [comment]
Thanks @ps-sp

**Comment by ps-sp** [comment]
I was almost done too man :P ! It hurts :P

**Comment by sagar-shah94** [comment]
@ps-sp Sorry i did not know .when i commented i am on it .i did not see any comment that is why i commented.
Sorry :(

**Comment by ps-sp** [comment]
NO ! You don't have to be sorry bro. You got it done before me so it's rightfully yours. Also, if it makes you feel better, I'd have made a PR even in spite of seeing your comment, if I had completed it before you that is ! 😋

**Comment by romani** [comment]
who first did "i am on it.", that user will be assignee and I expect fix from it, any racing will be rejected.

**Comment by romani** [comment]
fix is merged

**Comment by rnveach** [comment]
I am re-opennig the issue. Rule number was added but no updates were done to the violation message to inform the user of this new rule.
See https://github.com/checkstyle/checkstyle/blob/master/src/test/java/com/puppycrawl/tools/checkstyle/internal/CommitValidationTest.java#L289

@sagar-shah94 since you did first update, can you finish this?

**Comment by sagar-shah94** [comment]
@rnveach doing it now

**Comment by sagar-shah94** [comment]
@rnveach Sir added violation message please review and approve

**Comment by romani** [comment]
fix is merged.
