### ISSUE TITLE
 Split and Organize Checkstyle inputs by Test for NoWhitespaceBefore

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#3930]
subtask of #3891 .

do a copy of all test input files to separate folder for NoWhitespaceBefore .
Not any other Check should use new inputs.

**Comment by romani** [comment]
pre-assigned https://mail.google.com/mail/u/0/#inbox/15a929548a82d33a

**Comment by bansalayush** [comment]
I am on it

**Comment by vrush03** [comment]
I am on it.

**Comment by romani** [comment]
@bansalayush , you issue is #3931 . This issue belong to another contibutor

**Comment by subkrish** [comment]
@romani Since @vrush03 did not continue to work on this, I will be taking this issue over. I am on it.

**Comment by romani** [comment]
fix is merged
