### ISSUE TITLE
Split and Organize Checkstyle inputs by Test for NoWhitespaceAfter

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#3931]
subtask of #3891 .

do a copy of all test input files to separate folder for NoWhitespaceAfter .
Not any other Check should use new inputs.

**Comment by romani** [comment]
pre-assigned https://groups.google.com/forum/#!topic/checkstyle-devel/fqVPQz-t1Zk

**Comment by bansalayush** [comment]
I am on it

**Comment by bansalayush** [comment]
I am on it

**Comment by bansalayush** [comment]
Kindly review the modifications I made and let me know if it'd be alright to make a pull request for it.

**Comment by sabaka** [comment]
@bansalayush , where we can find changes you made?
I've tried to find any commits in your fork, but there is only copy of the main repo.

**Comment by bansalayush** [comment]
@sabaka my bad . Now you can see the changes in my fork https://github.com/bansalayush/checkstyle

**Comment by rnveach** [comment]
@bansalayush You must start a PR before we start reviewing your changes. We only review once CI in PR passes. This also keeps the issue clean of any implementation problems and only focuses and the issue.

**Comment by bansalayush** [comment]
Umm... What is PR and CI???

**Comment by rnveach** [comment]
@bansalayush I assume you are familar with github and git?
https://help.github.com/articles/github-glossary/ 
https://en.wikipedia.org/wiki/Continuous_integration
PR = pull request, CI = continuous integration

**Comment by bansalayush** [comment]
Yeah, I have been using git for quiet some time but never collaborated with anyone ,anyways I will go through it ....

**Comment by sabaka** [comment]
@bansalayush try to make all changes in your fork in separate branches (one per issue) and keep master branch up to date with main checkstyle repo (I use two remotes: origin for my fork and upstream for main repo). With this approach, when your fix is ready, you can do pull from upstream to your master, do rebase of your topic branch and send PR from branch.

Now I would suggest you to do following:
1) switch to branch from master
2) push branch to your fork
3) reset your commit in master
4) pull master branch from main repo
5) rebase you branch
6) send PR from branch

**Comment by bansalayush** [comment]
I followed your instructions.
But during CI test i couldn't pass any of the test. What could i have done wrong . Appreciate your help and patience.

**Comment by romani** [comment]
please make sure that you can pass tests before your changes on your local, if it pass it mean that your changes caused problems - investigate what change cause first problem.

**Comment by Kietzmann** [comment]
Hi,
May I deal with this issue?

**Comment by romani** [comment]
@Kietzmann , yes you can

**Comment by romani** [comment]
fix is merged
