### ISSUE TITLE
Split and Organize Checkstyle inputs by Test for NoLineWrap

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#3933]
subtask of #3891 .

do a copy of all test input files to separate folder for NoLineWrap .
Not any other Check should use new inputs.

**Comment by romani** [comment]
pre-assigned https://groups.google.com/forum/#!topic/checkstyle-devel/bIw5aEnEtT8

**Comment by divsidhu-26** [comment]
I am on it.........

**Comment by divsidhu-26** [comment]
Please review the changes i made and let me know if they are okay to make a pull request.

**Comment by rnveach** [comment]
@divsidhu-26 make a PR and we review there as it keeps issue clean of implementation fixes.
I can tell you right now we are only expecting changes in `NoLineWrapCheckTest` and it's inputs. Not any other class.

**Comment by Kietzmann** [comment]
May I deal with it?

**Comment by Vladlis** [comment]
@Kietzmann ,
After the May 1st : https://github.com/checkstyle/checkstyle/pull/3947#issuecomment-292544442

**Comment by romani** [comment]
fix is merged
