### ISSUE TITLE
doc: add examples for xdoc for ArrayTrailingComma

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#3943]
http://checkstyle.sourceforge.net/config_coding.html#ArrayTrailingComma

make examples of correct and code with violation in examples to make it clear for user how Check is working.

Good example: http://checkstyle.sourceforge.net/config_coding.html#MagicNumber

**Comment by romani** [comment]
pre assigned to  @Pedro12909  (time out 1 day).

**Comment by Pedro12909** [comment]
Working on it

**Comment by rnveach** [comment]
Fix is merged
