### ISSUE TITLE
Split and Organize Checkstyle inputs by Test for MethodParamPad

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#3954]
subtask of #3891 .

do a copy of all test input files to separate folder for MethodParamPad 
Not any other Check should use new inputs.

**Comment by romani** [comment]
Pre-assigned to abulfazahmadov

**Comment by GitToasterhub** [comment]
I am on it

**Comment by GitToasterhub** [comment]
I created as it's stated in task, new folder in resource/check/whitespace/inputmethodparampad
and placed there 2 input files of  MethodParamPadCheckTest, InputParamPad.java and InputWhitespaceAround.java respectively
Also I changed a bit in getPath() method ,to a new input files position,and I ran this test,I got 4 successful 3 failed with reason (  '(' is preceded with whitespace.  )
I was trying to find out why 3 test are failed and get stuck a bit.Am I doing something wrong?Or I had missed something ?If you could help me somehow I would be thankful!

**Comment by rnveach** [comment]
@GitToasterhub We can't tell what you have done until we see the PR. Most likely you changed the file when you moved/copied it.

> new folder in resource/check/whitespace/inputmethodparampad

folder name should be `methodparampad`, input files should be `InputMethodParamPad...`.

**Comment by GitToasterhub** [comment]
@rnveach Oh sure,I made folder not inputmethodparampad but methodinputparampad.I am trying to make pull request using step-by-step guide from here http://checkstyle.sourceforge.net/beginning_development.html

and unfortunately when I do git push origin my-new-check
I get the following:
remote: Permission to checkstyle/checkstyle.git denied to GitToasterhub.
fatal: unable to access 'https://GitToasterhub@github.com/checkstyle/checkstyle.git/': The requested URL returned error: 403

**Comment by rnveach** [comment]
@GitToasterhub 
> fatal: unable to access 'https://GitToasterhub@github.com/checkstyle/checkstyle.git/':

When you cloned, the URL should be `github.com/GitToasterhub/checkstyle.git`. You will have to modify your remote or re-clone to fix the URL.

**Comment by Vladlis** [comment]
@GitToasterhub 
you try to push directly to Checkstyle, but you actually need to:
1. Make your own fork of Checkstyle.
2. Clone your fork.
3. Create branch in the cloned project.
4. Make all neccesary changes.
5. Make commit and push.
6. Make pull request from your fork to Checkstyle.

**Comment by GitToasterhub** [comment]
@Vladlis Thanks ,your advices are very helpful! I finally made a pull request

**Comment by GitToasterhub** [comment]
As I mentioned,7 tests are ran in MethodParamPadCheckTest,and 4 of them are successful 3 are failed.I simply copied classes InputMethodParamPad and InputWhiteSpaceAround to methodparampad folder,having not changed these 2 classes.I trying to explore what can be a problem but yet I am stuck,and I hope for your help.

**Comment by GitToasterhub** [comment]
@rnveach Thanks for help! You were right,intellij idea were modifying somehow the class,when I copied it.I copied it simply via notepad and then ran tests in IDEA and everything worked.PR is also ready,It's my first PR ,and I might have done something wrong,I renamed it to Issue #3954 .

**Comment by rnveach** [comment]
Fix is merged
