### ISSUE TITLE
StackOverflowError on lengthy if/else cascade

### ISSUE THREAD

**Issue by oglueck** [checkstyle/checkstyle#3956]
Minimal test case:
http://odi.ch/download/issue83.tar.gz

Originally reported against the Sonar-Checkstyle plugin:
https://github.com/checkstyle/sonar-checkstyle/issues/83

**Comment by rnveach** [comment]
@oglueck Where you able to reproduce the problem with the checkstyle command line directly?
http://checkstyle.sourceforge.net/cmdline.html#Download_and_Run

**Comment by oglueck** [comment]
Ah! No, I can't reproduce it, even when I use Sonar's config file and the same Java options. So it must be the Sonar integration.
