### ISSUE TITLE
Split and Organize Checkstyle inputs by Test for FileTabCharacter

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#3959]
subtask of #3891 .

do a copy of all test input files to separate folder for FileTabCharacter
Not any other Check should use new inputs.

**Comment by romani** [comment]
Pre-assigned to Osho Agyeya

**Comment by osho-agyeya** [comment]
I am on it.

**Comment by Kietzmann** [comment]
Hi,
May I deal with this issue?

**Comment by romani** [comment]
@Kietzmann , yes you can. 1 month is too much, look like it is adandoned

**Comment by Kietzmann** [comment]
Please review #4182

**Comment by romani** [comment]
Fix is merged
