### ISSUE TITLE
DetailASTTest: 'checkTree' failing on deep AST tree

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#3961]
Taken from https://github.com/checkstyle/checkstyle/pull/3894#issuecomment-285104957 and seen at https://travis-ci.org/checkstyle/checkstyle/jobs/208912195#L254 ,

> java.lang.StackOverflowError
	at com.puppycrawl.tools.checkstyle.api.DetailASTTest.checkTree(DetailASTTest.java:158)

We should find a way to re-write this test, if possible, so it doesn't use the stack for each child.
When we run this on a deeply nested tree, we get a stackoverflow.
We should be able to walk through the tree like we do in other areas, see https://github.com/checkstyle/checkstyle/blob/b4a337a599e853cdc44b19a76da28fcfab2956cd/src/main/java/com/puppycrawl/tools/checkstyle/TreeWalker.java#L495-L508

Any file skips in this test should be removed as proof the fix works.

**Comment by Luolc** [comment]
I have reviewed some codes in DetailASTTest when handling https://github.com/checkstyle/checkstyle/issues/3700. I think I am able to rewrite the test 😄 
I will work on it once approved.

**Comment by romani** [comment]
Approved

**Comment by rnveach** [comment]
@Luolc Since your PR fixed the file with the original test, it is probably best to start off with another file that will fail and then provide fix to show it isn't an issue anymore.

**Comment by Luolc** [comment]
@rnveach That makes sense. So the steps tend to be:
1. Create an input file and let the CI failed.
2. Rewrite the test to prove the fix will work on a deeply nested tree.
3. Delete the input file.
I will do that step by step 😄

**Comment by rnveach** [comment]
> So the steps tend to be

Yes to all except step 3. The file needs to stay to prove we don't revert back and break the test again.

**Comment by Luolc** [comment]
@rnveach Got it. Just not sure where to put the input file. I am doing with step one now and the input file is put at https://github.com/checkstyle/checkstyle/tree/master/src/test/resources/com/puppycrawl/tools/checkstyle/checks (where the `InputAllEscapedUnicodeCharacters` in #3700 is). Should I put the file at https://github.com/checkstyle/checkstyle/tree/master/src/test/resources/com/puppycrawl/tools/checkstyle/api? (same package as DetailASTTest)

**Comment by rnveach** [comment]
@Luolc Since its an input file to the test, it should be in the same package as the test.

**Comment by Luolc** [comment]
@rnveach Done. Shall we move the discussion to the PR page #3966 ? 😄

**Comment by romani** [comment]
fix is merged.
