### ISSUE TITLE
remove from Input files "Compilable with Java8"

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#3965]
All files under https://github.com/checkstyle/checkstyle/tree/master/src/test/resources/com/puppycrawl/tools/checkstyle
should not have such comment "Compilable with Java8", whole checkstyle is on java8 already.
To avoid massive UTs updates for line numbers , new line should be added after imports.

**Comment by Luolc** [comment]
Is that OK to just replace the comment with an empty line? That can be simply implemented by a plain replace operation. Or we may need the help of regular expression to do the replacement.

**Comment by rnveach** [comment]
> Is that OK to just replace the comment with an empty line?

Yes, empty line is fine.

We will leave how it be done by the person who does the PR. I am not sure on the variations of the comment.

**Comment by Luolc** [comment]
@rnveach Got it.
I am on it :)

**Comment by romani** [comment]
Empty line in NOT ok

**Comment by rnveach** [comment]
> new line should be added after imports
> Empty line is NOT ok

My bad, I missed the idea of just putting the empty line after the imports.

**Comment by rnveach** [comment]
Fix is merged
