### ISSUE TITLE
Split and Organize Checkstyle inputs by Test for EmptyForInitializerPadCheck

### ISSUE THREAD

**Issue by sabaka** [checkstyle/checkstyle#3970]
subtask of #3891 .

do a copy of all test input files to separate folder for EmptyForInitializerPad.
Not any other Check should use new inputs.

**Comment by sabaka** [comment]
Preassigned to Jabbar Memon: https://groups.google.com/forum/#!topic/checkstyle-devel/urnRIydZGGA

**Comment by sabaka** [comment]
No confirmation.
Reassigned to Samuel Gu: https://groups.google.com/forum/#!topic/checkstyle-devel/f0bIANn3D4w

**Comment by samuel-gu** [comment]
I'm on it

**Comment by romani** [comment]
fix is merged
