### ISSUE TITLE
Split and Organize Checkstyle inputs by Test for EmptyForIteratorPad

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#3976]
subtask of #3891 .

do a copy of all test input files to separate folder for EmptyForIteratorPad .
Not any other Check should use new inputs.

**Comment by romani** [comment]
pre-assigned to Shivansh Soni - https://groups.google.com/forum/#!topic/checkstyle-devel/ee95NUc09p0

**Comment by shivanshsoni** [comment]
I am on it

**Comment by rnveach** [comment]
Fix is merged.
