### ISSUE TITLE
Split and Organize Checkstyle inputs by Test for EmptyLineSeparator

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#3985]
subtask of #3891 .

do a copy of all test input files to separate folder for EmptyLineSeparator .
Not any other Check should use new inputs.

**Comment by romani** [comment]
pre-assigned to Deepti Verma - https://groups.google.com/forum/#!topic/checkstyle-devel/r6WP256EgxY

**Comment by anudeepti2004** [comment]
I am on it.

**Comment by romani** [comment]
fix is merged
