### ISSUE TITLE
Split and Organize Checkstyle inputs by Test for AnonInnerLength

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#3986]
subtask of #3891 .

do a copy of all test input files to separate folder for AnonInnerLength .
Not any other Check should use new inputs.

**Comment by romani** [comment]
pre-assigned to https://groups.google.com/forum/#!topic/checkstyle-devel/mlF9yJ9l3AY

**Comment by samuel-gu** [comment]
@romani Can I work on this since the assignee hasn't accepted it yet?

**Comment by samuel-gu** [comment]
I'm on it

**Comment by romani** [comment]
yes, please do this

**Comment by romani** [comment]
fix is merged
