### ISSUE TITLE
Google style report: put it under git control

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#3987]
Taken from https://github.com/checkstyle/checkstyle/issues/3755#issuecomment-285870120 and https://github.com/checkstyle/checkstyle/issues/3755#issuecomment-285911703 :

Everytime we update our compliance with google's style, romani has to manually update our snapshot of the google style report, see http://checkstyle.sourceforge.net/reports/google-java-style-20160712.html .
Every update requires to have a new URL with a date attached to the end.

We should drop this person-specific, manual process and find a way so anyone can do it with a PR.

I am recommending we put the HTML file under Git control, somewhere probably in our `site` directory so it is naturally deployed with each release. It should remain as a pure HTML file. It shouldn't require a rename every release, so the URL never needs to be changed. Since it is under Git, we can just look in the history to look at old versions if we need to and easily see what has changed.

Additionally we need to resolve potential problems of missed updates , see example https://github.com/checkstyle/checkstyle/pull/4053#pullrequestreview-27761092 . We should have only one version of guide html file - reports/google-java-style.html .

Ideal solution will be to keep absolute copy of html file from google repo (with all their css and other stuff)

**Comment by romani** [comment]
generation of site on local could be done by `mvn site -Pno-validations`

**Comment by yajna-pandith** [comment]
I am on it

**Comment by romani** [comment]
this issue is already done in scope of #6619

https://github.com/checkstyle/checkstyle/blob/master/src/site/resources/styleguides/google-java-style-20180523/javaguide.html
