### ISSUE TITLE
find a reason why Travis localized UTs are passed but failed on local

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#3990]
to reproduce revert fix of https://github.com/checkstyle/checkstyle/commit/7caba87cc7113bf4484ca6046483a7a9bad58ec8

if build if failing on local it should fail on Travis.

some hints for investigation:
- recheck order of Tests on local and Travis
- make system.out printing to find out what is different (may be localization is not passed to UT correctly from command line or .................).
- as it will be debuging on remote - Travis. PR should have last commit in it contains changes only at ".travis.yml" that will skip majority other CIs to do builds.

**Comment by rnveach** [comment]
Was it 1 test failing or multiple?

https://github.com/checkstyle/checkstyle/commit/7caba87cc7113bf4484ca6046483a7a9bad58ec8#diff-23a91bdf13c0cfdb630e766fab19e2e5R59
It might be that we set a global variable like here and never undid it for future tests.
I think we have another issue to remove all ROOT locales.

**Comment by romani** [comment]
lets close this issue, commit is not revertable easily, so problem might not exist anymore or .....
one day it will come back in more easy to investigate way.
