### ISSUE TITLE
Split and Organize Checkstyle inputs by Test for ExecutableStatementCount

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#3991]
subtask of #3891 .

do a copy of all test input files to separate folder for ExecutableStatementCount .
Not any other Check should use new inputs.

**Comment by romani** [comment]
pre-assigned to Gabriel Bercaru - https://groups.google.com/forum/#!topic/checkstyle-devel/te3JelPOdGA

**Comment by GabrielBercaru** [comment]
I am on it

**Comment by GabrielBercaru** [comment]
https://github.com/GabrielBercaru/checkstyle/commit/15e6070d686011b43533eb159e482ebfc8990892

**Comment by rnveach** [comment]
@GabrielBercaru If that is the only input file in the test, then yes, that is the only one that should be in the folder.

**Comment by romani** [comment]
fix is merged
