### ISSUE TITLE
Split and Organize Checkstyle inputs by Test for MethodLength

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#4024]
subtask of #3891 .

do a copy of all test input files to separate folder for  MethodLength .
Not any other Check should use new inputs.

**Comment by romani** [comment]
Pre assigned to "Madhu Kiran" from Google groups

**Comment by madhukiran98** [comment]
i am on it

**Comment by subkrish** [comment]
@romani @rnveach Since @madhukiran98  did not continue to work on this, I would like to take this issue over. I am on it.

**Comment by rnveach** [comment]
Closing as this was done in another issue
