### ISSUE TITLE
Add new setting in Beginning Development for IDEA docs

### ISSUE THREAD

**Issue by kukreja-vikramaditya** [checkstyle/checkstyle#4030]
It is a common case when copy pasting is required in an IDE but it automatically indents all lines according to it's rules. I would suggest that a solution to this be mentioned in Beginning Development using IDEA [docs](http://checkstyle.sourceforge.net/idea.html) . Other IDE docs should also be edited for a similar setting.

To prevent this in IDEA use 
`Settings` > `Editor` > `Smart Keys` > `Reformat on paste` set value to `None`

**Comment by Pedro12909** [comment]
Working on it

**Comment by kukreja-vikramaditya** [comment]
@Pedro12909 
I have already sent PR. It wasn't a very imp issue so I didn't add "I am on it". Sorry for the confusion.

**Comment by rnveach** [comment]
Fix is merged
