### ISSUE TITLE
rename STMT in BlockOption class to STATEMENT

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#4035]
code https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/BlockOption.java#L49

Message name was changed too from "block.noStmt" to "block.noStatement"

full word should be used.

**Comment by kukreja-vikramaditya** [comment]
I am on it.
Just to confirm one thing - 
I need to change the field of BlockOption, any other java file using this particular field, messages.properties, config_blocks.xml, and any comments in these respective files right ? Or should I also increase the scope and look for more files in the `blocks` and `test` packages?  
Ofcourse including the diff reports for these changes

**Comment by rnveach** [comment]
@kukreja-vikramaditya This has checkstyle 8 label. It can't be done yet as we are still in version 7.

**Comment by subkrish** [comment]
Do I also have to change MSG_KEY_BLOCK_NO_STMT to MSG_KEY_BLOCK_NO_STATEMENT in EmptyBlockCheck and the subsequent changes as well?

https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/EmptyBlockCheck.java#L72

**Comment by romani** [comment]
> EmptyBlockCheck and the subsequent changes as well?

yes, please.

**Comment by romani** [comment]
fix is merged
