### ISSUE TITLE
Split and Organize Checkstyle inputs by Test for OuterTypeNumber

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#4043]
subtask of #3891 .

do a copy of all test input files to separate folder for OuterTypeNumber .
Not any other Check should use new inputs.

**Comment by romani** [comment]
pre-assigned to https://groups.google.com/forum/#!topic/checkstyle-devel/tvy6T7W9-SQ

**Comment by tashish** [comment]
I am on it

**Comment by romani** [comment]
fix is merged.
