### ISSUE TITLE
SingleLineJavadoc update for new requirements what tags are allowed in singleline javadoc

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#4052]
parent issue - #3888 

guide update - https://github.com/google/styleguide/commit/594d91bfbb8dfcbcac0f148af8175f2b7ec9857b#diff-b6c9191ee5ccb7a5ef170e98e51d94d8L1084

> The basic form is always acceptable. The single-line form may be substituted when the entirety
of the Javadoc block (including comment markers) can fit on a single line. Note that this only
applies when there are no block tags such as `@return`.

http://checkstyle.sourceforge.net/config_javadoc.html#SingleLineJavadoc

we already have property - `ignoredTags` and it is null by default so no block tags are allowed.
`ignoreInlineTags` - is true by default.

We need to change our google config to ignore inline tags (switch to default by removing `ignoreInlineTags`).
current code:
https://github.com/checkstyle/checkstyle/blob/14005e371803bd52dff429904b354dc3e72638c0/src/main/resources/google_checks.xml#L343-L345

definition of "block tags" (exact list of them) - http://docs.oracle.com/javase/8/docs/technotes/tools/windows/javadoc.html#CHDBEFIF ([for java7](http://docs.oracle.com/javase/7/docs/technotes/tools/windows/javadoc.html#javadoctags))
Lets save this link in xdoc to explain user meaning of such terms.

lets do updates for our IT inputs, case from #3762 should be added too.

----------

**Current behavior:**
```
/var/tmp$ cat Test.java 
public class Test {
  /** Create a new {@code Test} instance. */
  public Test() {}
}

/var/tmp$ java -jar checkstyle-8.36.2-all.jar -c /google_checks.xml Test.java
Starting audit...
[WARN] /var/tmp/Test.java:2: Single-line Javadoc comment should be multi-line. [SingleLineJavadoc]
Audit done.
```

**Expected:** no violations.

**Comment by romani** [comment]
pre-assigned to @divsidhu-26 .

**Comment by divsidhu-26** [comment]
I am on it......

**Comment by romani** [comment]
>Have you got any plans to update google_checks.xml in master?

Issue is approved, we just wait for smb to fix it. Please send PR , we will guide you on all required changes.

>So that means current solution/workaround is to remove <property name="ignoreInlineTags" value="false"/> from <module name="SingleLineJavadoc">. Right?

Yes. It will work to make a workaround on your side.
To fix it in master, in addition to config change, there should be done trivial changes in tests files, as some violations should disappear

**Comment by himanshurijal** [comment]
I am on it.

**Comment by romani** [comment]
fix is merged
