### ISSUE TITLE
NewlineAtEndOfFile default should be OS agnostic

### ISSUE THREAD

**Issue by jayvdb** [checkstyle/checkstyle#4073]
Currently the default for `NewlineAtEndOfFile` is `system`, which means that checkstyle *will* fail on a clean repository VCS checkout on either Windows or Unix if the EOLs where not converted to native EOLs by the VCS client, if that is even an option available in the client.

If someone very definitely wanted a certain EOL type, then surely they need a (new?) check which confirms all EOLs throughout all files are using that EOL type, not merely the EOLs at EOF as done by `NewlineAtEndOfFile`.

I think `NewlineAtEndOfFile` default of `lf_cr_crlf` (added https://github.com/checkstyle/checkstyle/pull/1045) more closely matches what the configuration name implies.

That will mean the ruleset https://raw.githubusercontent.com/noveogroup/android-check/master/android-check-plugin/src/main/resources/checkstyle/checkstyle-hard.xml will work as is on Windows, without depending on the git config of the users or requiring creation of `.gitattributes`, etc

**Comment by jayvdb** [comment]
A scenario that will also fail is a cygwin git clone with a native Windows java.

Also note that the current default on Unix will happily accept files with crlf due to https://github.com/checkstyle/checkstyle/issues/4074 , so the current behaviour on Unix is "crlf or lf".

**Comment by romani** [comment]
@jayvdb and @Vampire ,
Such default is used from the beginning of This Check (16 years ago)
https://github.com/checkstyle/checkstyle/commit/59aa156470fbdf19a54382fb2caaca2a95f4dbd5

change of default might break behavior in other group of users.

Why you can simply adjust your configs to use mode that you need ?

**Comment by jayvdb** [comment]
In my case, I am not asking for myself, but because I want source analysers and test suites that are not dependent on how the files were checked out, unless the user quite explicitly wants that.  Usually EOL settings on Windows are a user preference.

Other rulesets inherit the default of this rule, so they get the strange sets of behaviour of this rule without realising it.  It isnt easy to find the problem - it took me a while to realise why the windows machines were having problems.  Other rulesets could change the default by using the more permissive value, but then I need to raise this type of issue with each published ruleset which other users are using.

Changing NewlineAtEndOfFile to be more permissive of all types of EOL isnt likely to break anyone; more likely is the inverse -- someone expecting it to enforce system EOL would have that expectation removed by the default change.

But as explained above, that possible person really shouldnt be relying on this rule to enforce system EOL, as this rule is only about the end-of-file-EOL.  A checker for the type of EOL used should apply to all of the EOLs in the file, not just the final EOL.

**Comment by Vampire** [comment]
@romani of course we can adjust the config.
But I feel like @jayvdb, that `system` is not a sensible default that makes most users happy and work as expected.
Leaving the deprecated single CR out of the discussion as no recent OS uses it as default, changing to LF as default will not add violations to any project, but only make it work like expected on Windows with Linux line-endings as explained above. Using LF_CR_CRLF would then even serve the users with CR line endings no matter on which OS.
So even if this was the default from the start of this check I think a new default that is a bit more permissive is more in the spirit of this check, as it only validates that there is a line break character in the end of the file and does not check line ending types generally.
A system default that is neither LF, CR or CRLF can imho be ignored at least for the default case, as no sane person should use anything different. And if so, they can explicitly set it to `system`. But I broadly state that this will hit less than 0.1% of the Checkstyle userbase.

**Comment by romani** [comment]
thanks to @Vampire  and @jayvdb for comments.

Ok, I am fine with change, even it become minor breaking compatibility.

@rnveach , please review this issue and if you are agree, lets mark it approved and proceed with PRs review/merge.

**Comment by romani** [comment]
fix is merged.
