### ISSUE TITLE
Update Checkstyle GUI in order to display Javadoc tokens

### ISSUE THREAD

**Issue by baratali** [checkstyle/checkstyle#408]
Need to parse block comments as Javadoc comments and show Javadoc DetailNode tree instead of block comment.
![screenshot](http://checkstyle.sourceforge.net/images/gui_screenshot.png)

**Comment by rnveach** [comment]
@baratali Are you still working on this?

**Comment by baratali** [comment]
@rnveach I'm working on https://github.com/checkstyle/checkstyle/issues/652 now

**Comment by romani** [comment]
as soon we put Javadoc nodes to parse tree , GUI will show them automatically.

**Comment by baratali** [comment]
Before providing a pull-request I'd like to disscuss GUI layout.
I added a new dropdown next to "Reload" button:
![](https://s3.postimg.org/q61cxulpv/Checkstyle_GUI.png)
@romani , is it OK?

**Comment by romani** [comment]
Looks good

**Comment by romani** [comment]
fix is merged.
