### ISSUE TITLE
Split and Organize Checkstyle inputs by Test for SingleSpaceSeparator

### ISSUE THREAD

**Issue by sabaka** [checkstyle/checkstyle#4080]
subtask of #3891 .

do a copy of all test input files to separate folder for SingleSpaceSeparator .
Not any other Check should use new inputs.

**Comment by sabaka** [comment]
preassigned to Jun Lin: https://groups.google.com/forum/#!topic/checkstyle-devel/2CNx7zxhJug

**Comment by wate123** [comment]
I'm on it

**Comment by wate123** [comment]
can you give me some hint? please

**Comment by wate123** [comment]
After I run the `mvn clean verify`. It give me an error
`Tests run: 2001, Failures: 4, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:14 min
[INFO] Finished at: 2017-03-23T11:13:12-05:00
[INFO] Final Memory: 44M/599M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project checkstyle: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/jun/git/checkstyle/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
`
Please help me out.

**Comment by rnveach** [comment]
> Failures: 4

@wate123 You must look above for list of tests that fail. There are 4 of them.

**Comment by wate123** [comment]
`Results :

Failed tests: 
  SingleSpaceSeparatorCheckTest.testNoSpaceErrors:45->BaseCheckTestSupport.verify:191->BaseCheckTestSupport.verify:227->BaseCheckTestSupport.verify:261 unexpected output: /home/jun/Downloads/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/singlespaceseparator/InputSingleSpaceAfterNoErrors.java:0: Got an exception - /home/jun/Downloads/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/singlespaceseparator/InputSingleSpaceAfterNoErrors.java (No such file or directory) expected:<0> but was:<1>
  SingleSpaceSeparatorCheckTest.testSpaceErrors:88->BaseCheckTestSupport.verify:191->BaseCheckTestSupport.verify:227->BaseCheckTestSupport.verify:258 error message 0 expected:<...aceAfterErrors.java:[11:3: Use a single space to separate non-whitespace characters.]> but was:<...aceAfterErrors.java:[0: Got an exception - /home/jun/Downloads/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/singlespaceseparator/InputSingleSpaceAfterErrors.java (No such file or directory)]>
  SingleSpaceSeparatorCheckTest.testSpaceErrorsAroundComments:104->BaseCheckTestSupport.verify:191->BaseCheckTestSupport.verify:227->BaseCheckTestSupport.verify:258 error message 0 expected:<...eAfterComments.java:[13:13: Use a single space to separate non-whitespace characters.]> but was:<...eAfterComments.java:[0: Got an exception - /home/jun/Downloads/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/singlespaceseparator/InputSingleSpaceAfterComments.java (No such file or directory)]>
  SingleSpaceSeparatorCheckTest.testSpaceErrorsIfCommentsIgnored:114->BaseCheckTestSupport.verify:191->BaseCheckTestSupport.verify:227->BaseCheckTestSupport.verify:258 error message 0 expected:<...eAfterComments.java:[13:13: Use a single space to separate non-whitespace characters.]> but was:<...eAfterComments.java:[0: Got an exception - /home/jun/Downloads/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/singlespaceseparator/InputSingleSpaceAfterComments.java (No such file or directory)]>
Tests in error: 
  CommitValidationTest.setUp:101->getCommitsToCheck:183 » IllegalArgument One of...

Tests run: 2001, Failures: 4, Errors: 1, Skipped: 0`



I don't understand why there is no such file or directory?

**Comment by rnveach** [comment]
> /home/jun/Downloads/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/singlespaceseparator/InputSingleSpaceAfterComments.java

Carefully look at directory structure and confirm file is in that location. Tests don't lie.

**Comment by wate123** [comment]
Thanks for your help! I have a last error right now 
`Failed tests: 
  SingleSpaceSeparatorCheckTest.testSpaceErrors:88->BaseCheckTestSupport.verify:191->BaseCheckTestSupport.verify:227->BaseCheckTestSupport.verify:258 error message 28 expected:<...AfterErrors.java:6:4[2]: Use a single space...> but was:<...AfterErrors.java:6:4[7]: Use a single space...>

Tests run: 2001, Failures: 1, Errors: 0, Skipped: 0
` 
can you explain the error to me? Thanks

**Comment by rnveach** [comment]
> expected:<...AfterErrors.java:6:4[2]: Use a single space...> but was:<...AfterErrors.java:6:4[7]: Use a single space...>'

You should become more familar with Junit and how it works.
This is saying the violation column changed. Inputs should nearly be an exact copy of the original, so violations shouldn't change. Input must have been changed somehow.

**Comment by wate123** [comment]
Hi. I solve all the errors and ready to push my changes into GitHub, after I do `git push origin my-new-check`. I got an error about non-fast-forward, then, I follow the hint, do  `git push origin my-new-check`. this still reject my push.

**Comment by wate123** [comment]
not sure why, but Every time I modify the InputSingleSpaceErrors file will give the error

`SingleSpaceSeparatorCheckTest.testSpaceErrors:88->BaseCheckTestSupport.verify:191->BaseCheckTestSupport.verify:227->BaseCheckTestSupport.verify:258` error message 28 expected:<...aratorErrors.java:6:[42]: Use a single space...> but was:<...aratorErrors.java:6:[51]: Use a single `space...>` 
I stuck on this  for few hours.....

**Comment by rnveach** [comment]
@wate123 Please verify your changes in git history for the file.
I can't see what is wrong until you push changes to PR.

**Comment by romani** [comment]
fix is merged
