### ISSUE TITLE
Wrong German translation of declaration.order.access in messages_de.properties

### ISSUE THREAD

**Issue by sirdis** [checkstyle/checkstyle#4081]
In the file src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_de.properties, the value of property "declaration.order.access" changed to "Es wird auf eine Variable zugegriffen, bevor diese deklariert wurde." This seems to have happened in commit 165fb0b3135a01875b9adf6838e108aa837bcc04, before that it was correctly "Fehlerhafte Deklarationsreihenfolge für diesen Scope."

If there is a situation where the new value describes the warning correctly, the property should be split into two. Otherwise I suggest to revert to the old value.

**Comment by romani** [comment]
@sirdis , please send us PR please.

**Comment by sirdis** [comment]
Ok, created the PR. Fixed a few typos in other places of the properties file, too. Furthermore, the keys "fall.through" and "fall.through.last" have values that are syntactically incomplete German sentences. Since I don't understand the intention of the original author, I left them unchanged.

**Comment by romani** [comment]
> have values that are syntactically incomplete German sentences. 

if they are incomplete - just provide your translation for such sentences. We do not have maintainers who know German, so we rely on community only.

**Comment by romani** [comment]
fix is merged, thanks a lot
