### ISSUE TITLE
Split and Organize Checkstyle inputs by Test for ParameterNumber

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#4090]
subtask of #3891 .

do a copy of all test input files to separate folder for ParameterNumber .
Not any other Check should use new inputs.

**Comment by romani** [comment]
pre-asigned to @Icy-flames (request from gitter)

**Comment by GabrielBercaru** [comment]
@romani Is this issue still active, since nobody commented yet "I am on it" here?

**Comment by GabrielBercaru** [comment]
I am on it.

**Comment by romani** [comment]
fix is merged
