### ISSUE TITLE
Split and Organize Checkstyle inputs by Test for AbbreviationAsWordInName

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#4095]
subtask of #3891 .

do a copy of all test input files to separate folder for AbbreviationAsWordInName .
Not any other Check should use new inputs.

**Comment by romani** [comment]
pre-assigned to @unrealwork

**Comment by unrealwork** [comment]
I am on it.

**Comment by rnveach** [comment]
Fix is merged
