### ISSUE TITLE
Create web-page with instructions: how to create Javadoc Check

### ISSUE THREAD

**Issue by baratali** [checkstyle/checkstyle#410]
Like this http://checkstyle.sourceforge.net/writingchecks.html

**Comment by romani** [comment]
@baratali , please send draft notes about (they are the most critical):
1) Javadoc is expecting XHTML , .....
2) why why make a tree up to CHAR token ? 
3) Comment identificator for javadoc

> checkstyle-6.18-all.jar , checkstyle-6.18-SNAPSHOT-all.jar

change to "checkstyle-X.XX-all.jar" we are about to become 7th and 8th version in next month or two.

**Comment by romani** [comment]
>  Check create new class and extend AbstractJavadocCheck.

all reference to class and methods should by done as links.

> Overview

this paragraph should start from "What is javadoc (XHTML)" and how javadoc is detected in multiline comment.
it is the most critical point of our implementation. XHTML is so non-typicality in web, usage of it is more exception rather than a rule.

**Comment by romani** [comment]
@baratali 

I did a lot of minor changes for documentation, please review.

1) 
We need to explain a reason why we continue parsing even javadoc content is not XHTML
We also need to use "predictable" instead of "incorrect". As "incorrect" mean bug.

2)
We need to explain why we have in AST (CHAR, WS), as we do not have this in Java AST tree.

3)
Please add code examples to "Access Java AST from Javadoc Check"

4)
> HTML code in Javadoc Comments

It is hard to  find a difference.
Does it make sense to place them as table ? Example:
---------------------------------------
|Non-predictable| Predictable |
---------------------------------------
| javadoc            |       javadoc |
---------------------------------------
| AST tree          |       Ast tree |
---------------------------------------

**Comment by baratali** [comment]
1) 
> We need to explain a reason why we continue parsing even javadoc content is not XHTML

done

2)
> We need to explain why we have in AST (CHAR, WS), as we do not have this in Java AST tree.

done

3)
> Please add code examples to "Access Java AST from Javadoc Check"

done

4)
> Does it make sense to place them as table ? Example:

done. Transformed to the table.

**Comment by romani** [comment]
8)
> However result tree will be unpredictable.

So predictable or not predictable ?

9)
>  In Javadoc comment every whitespace matters, so parse tree contains whitespace nodes (WS javadoc token type). So do CHAR javadoc token that presents single character. The only redundancy Javadoc tree has because of this is that TEXT node consists of CHAR and WS nodes which is useless, but it is implementation nuance.

We need to rephrase this paragraph. I do not understand it.

10)

> (In future we will try to resolve this)

please open the issue and make a link.

**Comment by romani** [comment]
@baratali , please mark items you fixed as DONE.

**Comment by baratali** [comment]
8)
> > However result tree will be unpredictable.

> So predictable or not predictable ?

rephrased to this:

>Javadoc grammar requires XHTML, but it can also parse some parts of HTML code (like some unclosed tags). If HTML tags are not closed Javadoc grammar cannot determine content of these tags, so structure of the parse tree will not be nested like it is while using XHTML. It is done just to not fail on every Javadoc comment, because there are tons of using unclosed tags, etc.

9)
> > In Javadoc comment every whitespace matters, so parse tree contains whitespace nodes (WS javadoc token type). So do CHAR javadoc token that presents single character. The only redundancy Javadoc tree has because of this is that TEXT node consists of CHAR and WS nodes which is useless, but it is implementation nuance.

> We need to rephrase this paragraph. I do not understand it.

rephrased and moved to "Difference between Java Grammar and Javadoc comments Grammar" section:
> Main Java grammar skips any whitespaces and newlines, so in Java Abstract Syntax Tree there are no whitespace/newline nodes. In Javadoc comment every whitespace matters, and Javadoc Checks need all those whitespaces and newline nodes to verify format and content of the Javadoc comment. Because of that Javadoc grammar includes all whitespaces, newlines to the parse tree (WS, NEWLINE). As you may notice there is also CHAR javadoc token that presents single character. It is quite useless and is used for building only TEXT node which consists of CHAR and WS nodes, but it is implementation nuance. (In future we will try to resolve this. See Github Issue #3170).

10)
> > (In future we will try to resolve this)

> please open the issue and make a link.

done

**Comment by romani** [comment]
> This means that every HTML tag should have matching closed HTML tag or it is self-closed one (singlton tag). The only exceptions are 

exceptions == singleton tags ?
We need to put somewhere in doc a reason why we do care about HTML  tag names at all. Why not a general/any name (most likely it is to control HTML singletons and ..... but this could be done by special Check ... I remember that we had discussion about this awhile ago and got a reason) ? 
most likely it is google groups topic ...

**Comment by romani** [comment]
11) missed links for getDefaultJavadocTokens(), visitJavadocToken in section "How to create Javadoc Check"

12)
> Tags do not require   closing tag
don't need closing tag

that is from section "HTML code in javadoc comments".
It is not clear, look like the same. Lets extend documentation with links to definition of singleton tag and .... and lets make an examples.

13)
> html code in javadoc comments
if Checkstyle meat unknown tag it does not fail ....

What if HTML5 tag is present but not closed ?

**Comment by baratali** [comment]
> 11) missed links for getDefaultJavadocTokens(), visitJavadocToken in section "How to create  Javadoc Check"

Done

> 12)
> Tags do not require closing tag
> don't need closing tag
> that is from section "HTML code in javadoc comments".
> It is not clear, look like the same. Lets extend documentation with links to definition of singleton tag and .... and lets make an examples.

Done

> 13)
> html code in javadoc comments
> if Checkstyle meat unknown tag it does not fail ....
> What if HTML5 tag is present but not closed ?

in progress...

**Comment by romani** [comment]
I did some minor changes.

14) 
For "Limitation" chapter.
Smth is not good.... We expect non XHTML structure(we are not failing) so all Javadoc check have to expect non-nested AST.  It will create a lot of problems to write reliable Javadoc Check, as amount of false positives will be huge.
We need somehow to allow Check to decide to skip execution on Javadoc that is not XHTML , to let author of Check decide to support non-nested AST or not. 
Can we somehow grab from parser a flag that javadoc is not xhtml ? (separate issue)
We should raise violation by Check if it can not be executed on non-XHTML javadoc ? (separate issue)
We need Check that will validate XHTML structure, please create an issue.

15)
> tags that are "don't require closing tag"

can you provide link to this term ?

16)
> and a list of tags whose end tag is forbidden (also known as empty html tags

What does "forbidden" mean  ? it is completely ok to have it self-closed.

**Comment by baratali** [comment]
15)
>> tags that are "don't require closing tag"
>
>can you provide link to this term ?

As I know there is no special term for this kind of tags.
It's described differently:
``element’s end tag may be omitted`` - https://www.w3.org/TR/html-markup/p.html#p
``End tag is Optional`` - https://www.w3.org/TR/html4/index/elements.html

**Comment by romani** [comment]
current state is more that descriptive. Issue is closed.
