### ISSUE TITLE
Enforce more checks over checkstyle resources

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#4100]
Expanding on Issue #3072 and from discussions in it's PR https://github.com/checkstyle/checkstyle/pull/4075#discussion_r108035623 .

New configuration will maintain small number of checks on checkstyle's resources. Right now it is being configured with `NewlineAtEndOfFileCheck`.

I would like to propose we add the following checks to the resource:
`OuterTypeFilenameCheck` - main class in input should be named after file
`PackageDeclarationCheck` - package name should be same as folder location

Other ideas for checks against resources as they can cause some confusion with new contributors as we disallow them in main configuration:
remove trailing spaces.
remove tabs.

**Comment by rnveach** [comment]
There are 2 problems with adding these checks.
1) They may cause an excessive amount of violations in tests that require them to be different for some reason.
2) They require `TreeWalker` and we can't run this on non-compilable code.

For Point 1, I am thinking these input files should be given a special name so an easy suppression can be generated for all them. It depends on how many cases there are.

Point 2 is the most troublesome right now.
`BeforeExecutionExclusionFileFilter` can't be used because then it will exclude those files from `NewlineAtEndOfFile` check. Suppressions won't prevent us from exceptions on grammar failure.
We may need to create something new to be able to do this.

**Comment by Vladlis** [comment]
What about enabling:
- `FileTabCharacter`
- `RegexpSingleline` for trailing whitspaces
- maybe even `RegexpOnFilename` on inputs?

**Comment by romani** [comment]
I am fine with more rules for code, the more the better.

We could do any kind of renaming to make suppression easy and manageable.

**Comment by romani** [comment]
> They require TreeWalker and we can't run this on non-compilable code.

most of non-compilable inputs are future jdk or eclipse. 
ALL inputs should be processed by our parser.
In most very rare case - such file should be filtered by Checker on pre-execution filtering.

All input files should have a comment inside to explain what actually is a problem.

**Comment by rnveach** [comment]
If you exclude files by pre-execution filter, then you exclude the file from all checks not just TreeWalker checks. This is why I didn't go anywhere further with this issue. We either need pre-execution TreeWalker filter, a path on the TreeWalker module, or a special module that only executes children on a specific path.

**Comment by romani** [comment]
@rnveach , please show me few Input file that in not compile-able by jdk and not parse-able by checkstyle and we do need to run TreeWalker Checks on them and can not skip them.

**Comment by rnveach** [comment]
I didn't say we need to run TreeWalker on them, I said if we exclude them, we exclude them from FileSets like NewlineCheck.

**Comment by romani** [comment]
> NewlineAtEndOfFileCheck

already enforce by config/checkstyle_non_main_files_checks.xml

> OuterTypeFilenameCheck and PackageDeclarationCheck 

enforced by config/checkstyle_resources_checks.xml

>    maybe even RegexpOnFilename on inputs?

enforced by config/checkstyle_resources_checks.xml

>    FileTabCharacter and RegexpSingleline for trailing whitespace

moved to #5941

**Comment by romani** [comment]
Fixes are merged
