### ISSUE TITLE
Split and Organize Checkstyle inputs by Test for AbstractClassName

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#4106]
subtask of #3891 .

do a copy of all test input files to separate folder for AbstractClassName .
Not any other Check should use new inputs.

**Comment by romani** [comment]
pre-assigned to https://groups.google.com/forum/#!topic/checkstyle-devel/WbRmIympNC4

**Comment by Nimfadora** [comment]
I'm Valeria Vasylieva, I'm on it.

**Comment by romani** [comment]
fix is merged
