### ISSUE TITLE
DefaultComesLastCheck: examine code looking at line/column numbers

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#4107]
Looking at the code for `DefaultComesLastCheck`.
https://github.com/checkstyle/checkstyle/blob/753537bc2309a51e6b4647bb1c792f2fef9e30df/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/DefaultComesLastCheck.java#L80-L82
````
            if (defaultGroupAST.getLineNo() != lastGroupAST.getLineNo()
                || defaultGroupAST.getColumnNo()
                    != lastGroupAST.getColumnNo()) {
````

It is not clear why this check is looking at line/column numbers of the input file.
Check is only examining if `default` is last group in switch. It shouldn't have to rely on the exact positioning in the file.

We need to examine this and see if it should be replaced with something simplier, like: `defaultGroupAST != lastGroupAST`

**Comment by sagar-shah94** [comment]
@rnveach I have made more readable code,please verify my pull request.
https://github.com/checkstyle/checkstyle/pull/4084

**Comment by rnveach** [comment]
@sagar-shah94 This is a new issue. We are not expecting you to fix this for another issue.
This isn't even `approved`.

**Comment by romani** [comment]
I am ok with refactoring, if no regression is proved.

**Comment by LubainaTariq** [comment]
I am on it

**Comment by rnveach** [comment]
@LubainaTariq I would probably look for another issue.
The PR this issue is created from removed these lines as part of it's fix.
It is still working on being merged.

**Comment by LubainaTariq** [comment]
Then kindly assign me another easy issue just like the one I committed on
before in java.
Thanks

**Comment by rnveach** [comment]
Closing this as it was fixed in the mentioned PR
