### ISSUE TITLE
AbstractCheck: remove tabWidth

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#4111]
Taken from issue in sonar at https://github.com/checkstyle/sonar-checkstyle/issues/94

We should remove [`tabWidth` from `AbstractCheck`](https://github.com/checkstyle/checkstyle/blob/bd9b4b293fc9b1ba19622ac028a0604bed8fdb5f/src/main/java/com/puppycrawl/tools/checkstyle/api/AbstractCheck.java#L49) as it is making all checks have this property. All checks having it makes it difficult to see which ones actually use it.

It may be ok to keep it in `AbstractFileSet`.

Before any implementation, we must consider why `tabWidth` is in this abstract class. Right now [`TreeWalker` is the parent of this property and passes it to all check children](https://github.com/checkstyle/checkstyle/blob/bd9b4b293fc9b1ba19622ac028a0604bed8fdb5f/src/main/java/com/puppycrawl/tools/checkstyle/TreeWalker.java#L143).
Also removing it will cause some issues with [how we calculate violation column positions for one of the `log` methods](https://github.com/checkstyle/checkstyle/blob/bd9b4b293fc9b1ba19622ac028a0604bed8fdb5f/src/main/java/com/puppycrawl/tools/checkstyle/api/AbstractCheck.java#L252-L253).

**Comment by unrealwork** [comment]
I am on it.

**Comment by rnveach** [comment]
@unrealwork This issue has the label `checkstyle8` on it. We are still only version 7, so you can't start this.

**Comment by rnveach** [comment]
@romani Because of https://github.com/checkstyle/checkstyle/issues/6485 where we are adding tabWidth to more places, this issue makes it harder and unworkable to remove tabWidth from AbstractCheck. It is needed to calculate the correct position of the violation from any check as any could have a tab in the file.

This issue will have to be closed and sonar will have to be modified to say tabWidth is on every check.

**Comment by rnveach** [comment]
I am closing this as discussion should be moved to sonar side and I made a comment on the 8.19 issue there that started this change.
