### ISSUE TITLE
Verifying tokens in checkstyle config handles default tokens wrong

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#4119]
Found in https://github.com/checkstyle/checkstyle/pull/4117#discussion_r108739172 , and confirmed by looking in our configuration file https://github.com/checkstyle/checkstyle/blob/e9f6521e0101fb685456ca5548065acbecd5eae1/config/checkstyle_checks.xml#L175-L188.

We do not validate [all tokens in `RightCurly`](https://github.com/checkstyle/checkstyle/blob/e9f6521e0101fb685456ca5548065acbecd5eae1/src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java#L148). We are missing `LITERAL_IF` and `LITERAL_ELSE` and others.

Problem is with `AllChecksTest.validateAllCheckTokensAreReferencedInConfigFile` and how we handle default tokens in https://github.com/checkstyle/checkstyle/blob/e9f6521e0101fb685456ca5548065acbecd5eae1/src/test/java/com/puppycrawl/tools/checkstyle/internal/AllChecksTest.java#L371.

Once fixed, we will have to re-confirm all new tokens found, if they should be added to our config or not.
This will also affect google config.

**Comment by romani** [comment]
each change in google config should be proved by quote from style guide.

**Comment by rnveach** [comment]
Fix was merged
