### ISSUE TITLE
Expand missing testing for Checker tests

### ISSUE THREAD

**Issue by MEZk** [checkstyle/checkstyle#4128]
Apart from #3650 there are 5 UTs which call methods and do not verify any type of result.

1. [testNoModuleFactory](https://github.com/checkstyle/checkstyle/blob/master/src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java#L352)
2. [testFinishLocalSetupFullyInitialized](https://github.com/checkstyle/checkstyle/blob/master/src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java#L360)
3. [testSetupChildListener](https://github.com/checkstyle/checkstyle/blob/master/src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java#L388)
4. [testWithCacheWithNoViolation](https://github.com/checkstyle/checkstyle/blob/master/src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java#L490)
5. [testClearLazyLoadCacheInDetailAST](https://github.com/checkstyle/checkstyle/blob/master/src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java#L699)

The above mentioned tests are not related to PopertyCacheFile.

**Comment by romani** [comment]
@MEZk , all such problems will be fixed ones we start fixing Pitest coverage. please do not waste time to search for such methods it will be done during GSoC 2017.

**Comment by romani** [comment]
this issue will be addressed during #3746 .

**Comment by MEZk** [comment]
@romani 
Should I close the issue?

**Comment by romani** [comment]
Let's keep it to make sure that whoever takes purest to resolve should confirm that all found cases by you are covered.

**Comment by rnveach** [comment]
I am adding this to GSoC

**Comment by Nimfadora** [comment]
After enabling pmd on tests found
SignatureDeclareThrowsException, 1510 
AvoidDuplicateLiterals, 930
CommentRequired, 431
JUnitTestContainsTooManyAsserts, 200
TooManyStaticImports, 44
TooManyMethods, 22
CheckstyleCustomShortVariable, 19
ExcessiveMethodLength, 15
NcssMethodCount, 14
AccessorMethodGeneration, 12
UncommentedEmptyMethodBody, 8
ExcessiveImports, 7
AbstractNaming, 5
DefaultPackage, 4
AvoidUsingHardCodedIP, 4
CommentDefaultAccessModifier, 4
ConfusingTernary, 4
AppendCharacterWithChar, 3
UncommentedEmptyConstructor, 3
ExcessivePublicCount, 3
ExcessiveClassLength, 3
ShortClassName, 2
AccessorClassGeneration, 2
InsufficientStringBufferDeclaration, 2
AddEmptyString, 1
AvoidCatchingGenericException, 1
ShortMethodName, 1
CouplingBetweenObjects, 1
LoggerIsNotStaticFinal, 1
JUnit4TestShouldUseBeforeAnnotation, 1
JUnit4TestShouldUseTestAnnotation, 1
UselessOverridingMethod, 1
NPathComplexity, 1
NcssTypeCount, 1

I will divide them and make sequential pull requests

**Comment by rnveach** [comment]
@Nimfadora This issue isn't for PMD. I think you have the wrong issue.

**Comment by Nimfadora** [comment]
@rnveach you are right, mistaken

**Comment by romani** [comment]
all cases were resolved in scope of #4400
