### ISSUE TITLE
Split and Organize Checkstyle inputs by Test for CatchParameterName

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#4136]
subtask of #3891 .

do a copy of all test input files to separate folder for CatchParameterName .
Not any other Check should use new inputs.

**Comment by romani** [comment]
pre-assigned at https://groups.google.com/forum/#!topic/checkstyle-devel/w1p06rhozH4

**Comment by arnav97** [comment]
I am on it

**Comment by Kietzmann** [comment]
@rnveach 
Seems that this issue should be closed due to complete as previous one I mentioned

**Comment by rnveach** [comment]
Agree, closed
