### ISSUE TITLE
Split and Organize Checkstyle inputs by Test for ClassTypeParameterName

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#4137]
subtask of #3891 .

do a copy of all test input files to separate folder for ClassTypeParameterName .
Not any other Check should use new inputs.

**Comment by romani** [comment]
pre-assigned to @Samin12

**Comment by Kietzmann** [comment]
Hi,
could I deal with it?

**Comment by romani** [comment]
No, time out is 1 month.

**Comment by romani** [comment]
fix is merged
