### ISSUE TITLE
Split and Organize Checkstyle inputs by Test for ConstantName

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#4141]
subtask of #3891 .

do a copy of all test input files to separate folder for ConstantName .
Not any other Check should use new inputs.

**Comment by romani** [comment]
pre-assigned at https://groups.google.com/forum/#!topic/checkstyle-devel/EvWs6iYt2g8

**Comment by harisriaz17** [comment]
I am on it.

**Comment by harisriaz17** [comment]
Hey romani, I need a little help. Can you point me to the correct source file/source files where I can get started with implementing this feature? There are so many files, I just need you to tell me specifically which files I need to look in.
Thanks.

**Comment by romani** [comment]
fix is merged
