### ISSUE TITLE
Split and Organize Checkstyle inputs by Test for InterfaceTypeParameterName

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#4142]
subtask of #3891 .

do a copy of all test input files to separate folder for InterfaceTypeParameterName .
Not any other Check should use new inputs.

**Comment by romani** [comment]
pre-assigned https://groups.google.com/forum/#!topic/checkstyle-devel/EWgEtsS_N_w

**Comment by LevanSe** [comment]
I am on it.

**Comment by LevanSe** [comment]
can you give me more details about task because I don't understand exactly what I must to do.

**Comment by romani** [comment]
please look at other similar task/fixed (already merged in master) for details.

**Comment by rnveach** [comment]
fix was merged
