### ISSUE TITLE
Split and Organize Checkstyle inputs by Test for LocalFinalVariableName

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#4144]
subtask of #3891 .

do a copy of all test input files to separate folder for LocalFinalVariableName .
Not any other Check should use new inputs.

**Comment by romani** [comment]
pre-assigned to @kuri-leo .
@kuri-leo, if you agree on assignment ,please make comment "I am on it"

**Comment by kuri-leo** [comment]
I am on it

**Comment by kuri-leo** [comment]
@romani I'm sorry to disturb you but I have a bug, I've change all the name, and when I did the unit test , found messeages.properties was only copied to `com.puppycrawl.tools.checkstyle.checks.naming` but it should be in `com.puppycrawl.tools.checkstyle.checks.naming.LocalFinalVariableName`. So I'm not sure where I can change the code to fix it, could you please give me a hint?

The exception output is `java.util.MissingResourceException: Can't find bundle for base name com.puppycrawl.tools.checkstyle.checks.naming.LocalFinalVariableName.messages, locale zh_CN`

**Comment by romani** [comment]
@Luolc , please take a look at this zh_CN localization problem .

**Comment by Luolc** [comment]
@romani Sure. :)

**Comment by kuri-leo** [comment]
@Luolc
Thank for your suggestions. This is my first time contributed to a open source project, I will pay more attention to the PR rules next time!

**Comment by kuri-leo** [comment]
Hi @romani and @Vladlis ,I also want to help izishared to rename all checks to practice myself and make up my incorrect closing of PR.
So, can I rename all checks in `com.puppycrawl.tools.checkstyle.checks.naming` as a begin? :)

**Comment by romani** [comment]
fix is merged
