### ISSUE TITLE
Split and Organize Checkstyle inputs by Test for LocalVariableName

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#4150]
subtask of #3891 .

do a copy of all test input files to separate folder for LocalVariableName .
Not any other Check should use new inputs.

**Comment by romani** [comment]
pre-assigned to @Shubhk15 .
@Shubhk15 , please make comment "I am on it" to confirm assignment.

**Comment by Kietzmann** [comment]
I am on it

**Comment by Kietzmann** [comment]
Please, make code review.
Thanks.

**Comment by romani** [comment]
Fix is merged
