### ISSUE TITLE
Split and Organize Checkstyle inputs by Test for MemberName

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#4151]
subtask of #3891 .

do a copy of all test input files to separate folder for MemberName .
Not any other Check should use new inputs.

**Comment by romani** [comment]
pre-assigned to Gaurav Sharma.

**Comment by gvsharma13** [comment]
I'm on it

**Comment by romani** [comment]
@gvsharma13 , please review in git history other commits, and do this task in similar way.
please read:
http://checkstyle.sourceforge.net/contributing.html
http://checkstyle.sourceforge.net/beginning_development.html

**Comment by gvsharma13** [comment]
Sir ,  is there time limit for this bug? Because it's my exam time. Can u extend ?

**Comment by romani** [comment]
you have 1 month to fix it, in your case till 15th May.

**Comment by rnveach** [comment]
Fix is merged
