### ISSUE TITLE
WhitespaceAround: Add support for varargs

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#4157]
$ javac Test.java 
$ cat Test.java
```
public class Test {
    public static void main(String... args) {} // Would like to have a violation here
}
```
Actually, we need opposite of https://github.com/checkstyle/checkstyle/issues/3718

**Comment by samuel-gu** [comment]
I'm on it

**Comment by sergileon** [comment]
I think what 
`public class Test {
    public static void main(String... args) { } // No violation
}`
`public class Test {
    public static void main(String ... args) { } // violation 
}`
All right?

**Comment by romani** [comment]
No, completely opposite.
WhitespaceAround demand spaces around token.
User wants to add this token to allowed tokens of this Check to enforce spaces around '...' .

This token should not be default.

**Comment by romani** [comment]
fix is merged
