### ISSUE TITLE
Split and Organize Checkstyle inputs by Test for checks in coding package

### ISSUE THREAD

**Issue by Vladlis** [checkstyle/checkstyle#4165]
subtask of #3891 

move / do a copy of all test input files to a separate folder for all checks in `coding` package.
Not any other Check should use new inputs.

**Comment by Vladlis** [comment]
@izishared 
Please help us with this issue

**Comment by romani** [comment]
each Check/Test should be done in separate PR, multiple PRs are expected.
Do not do all at ones!

**Comment by Vladlis** [comment]
@romani ,
why not combine few commits in PR? but with a separate commit for each Check?

**Comment by romani** [comment]
new contributors have problems to make correct udpate for one Check , for some of them it takes few weeks. I wish @izishared could impress me , but I doubt. Verification of big PR is also time consuming task.

**Comment by romani** [comment]
Fix is merged

**Comment by Kietzmann** [comment]
@izishared @romani 
Can I help with classes that are left?

**Comment by romani** [comment]
if smth is left in this package please be welcome to let us close this issue

**Comment by Kietzmann** [comment]
@romani 
Seems that the latest PR related to this issue from izishared that you approved will done with classes left.

**Comment by rnveach** [comment]
@Kietzmann That PR only covered one test. Atleast IllegalThrowsCheck is not done. I don't know if there are others.
https://github.com/checkstyle/checkstyle/blob/master/src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalThrowsCheckTest.java#L38

**Comment by Vladlis** [comment]
One file in non-compilable resources is missed: https://github.com/checkstyle/checkstyle/tree/master/src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding

**Comment by Kietzmann** [comment]
@Vladlis 
I'll try to do it ASAP

**Comment by Kietzmann** [comment]
@Vladlis 
#4359

**Comment by romani** [comment]
@Vladlis , was it last change for this issue ?

**Comment by Vladlis** [comment]
@romani
No. I've found 2 files with inappropriate names:
https://github.com/checkstyle/checkstyle/blob/master/src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/packagedeclaration/InputNoPackage.java
https://github.com/checkstyle/checkstyle/blob/master/src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/magicnumber/InputIntMethodAnnotation.java
 @Kietzmann , these files were moved by your commits, please take care of them

**Comment by Kietzmann** [comment]
@Vladlis 
Fixed in #4360

**Comment by rnveach** [comment]
@Vladlis we good now?

**Comment by Vladlis** [comment]
@rnveach, yes, all inputs seem to be moved in appropriate packages and properly renamed.

@Kietzmann, thanks!
