### ISSUE TITLE
Checkstyle ignores javadoc that placed over Annotation type elements 

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#4169]
http://checkstyle.sourceforge.net/config_javadoc.html#AtclauseOrder
http://checkstyle.sourceforge.net/config_javadoc.html#SummaryJavadoc

```
/var/tmp $ javac TestClass.java

/var/tmp $ cat YOUR_FILE.java
package test;

/**
 * Text
 * @version 1.0
 * @author Tester Testerson
 *
 */
public @interface TestClass
{
  /**
   * Text
   * @version 1.0
   * @author Tester Testerson
   */
  @TestClass("foo")
  String value() default "";
}

/var/tmp $ cat TestConfig.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
  "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
  "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
  <property name="charset" value="UTF-8"/>
  <module name="TreeWalker">
    <module name="SummaryJavadocCheck">
        <property name="forbiddenSummaryFragments" value="^Text*"/>
    </module>
    <module name="AtclauseOrder">
      <property name="tagOrder" value="@author, @version"/>
    </module>
  </module>
</module>

/var/tmp $ java -jar checkstyle-7.6.1-all.jar -c TestConfig.xml TestClass.java
Starting audit...
[ERROR] /var/tmp/TestClass.java:3: Forbidden summary fragment. [SummaryJavadoc]
[ERROR] /var/tmp/TestClass.java:6: At-clauses have to appear in the order '[@author, @version]'. [AtclauseOrder]
Audit done.
Checkstyle ends with 2 errors.
````
---------------

There must be 4 errors from, but Checkstyle does not process second javadoc .
I don't think AbstractJavadocCheck#isCorrectJavadocPosition supports this token.

**Comment by rnveach** [comment]
@pbludov 
http://checkstyle.sourceforge.net/config_javadoc.html#AtclauseOrder
Specify the targets as those areas are not validated by default.

````
$ cat TestClass.java
package test;

/**
 * @version 1.0
 * @author Tester Testerson
 * 
 */
public @interface TestClass
{
  /**
   * @version 1.0
   * @author Tester Testerson
   */
  @TestClass("foo")
  String value() default "";
}

$ cat TestConfig.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
  "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
  "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
  <property name="charset" value="UTF-8"/>
  <module name="TreeWalker">
    <module name="AtclauseOrder">
      <property name="target" value="ANNOTATION_DEF"/>
      <property name="tagOrder" value="@author, @version"/>
    </module>
  </module>
</module>

$ java -jar checkstyle-7.6.1-all.jar -c TestConfig.xml TestClass.java
Starting audit...
[ERROR] TestClass.java:5: At-clauses have to appear in the order '[@author, @version]'. [AtclauseOrder]
Audit done.
Checkstyle ends with 1 errors.
````

@romani 
However, setting `ANNOTATION_FIELD_DEF` for the target still doesn't get a violation at line 12.
I don't think `AbstractJavadocCheck#isCorrectJavadocPosition` supports this token.

**Comment by romani** [comment]
AtclauseOrder should not care on what javadoc it is running. 
By its design it should runs on all javadocs and do validation. Why such simple case does not works , I not sure ....

**Comment by sagar-shah94** [comment]
I am on it.

**Comment by romani** [comment]
@sagar-shah94 ,I do not understand your comment, please rephrase.
Check should be executed on each javadoc block, is it happening ?

**Comment by sagar-shah94** [comment]
It is not happening for following comment.
  /**
   * @version 1.0
   * @author Tester Testerson
   */
  @TestClass("foo")
Please verify once because above java doc was not executed when i tried to debug above example.

**Comment by romani** [comment]
after discussion with @sagar-shah94 , and @rnveach , I updated original description and title to clearly define problem.

**Comment by pbludov** [comment]
There are two different issues:
1. AtClauseOrder and the like should check all possible doc comments. There is no point in making any exceptions by default.
2. AbstractJavadocCheck#isCorrectJavadocPosition does not process the annotation fields. This blocks the first issue.
If someone fixes the first issue, then I can do the second issue on my own. The last one looks quite easy.

**Comment by romani** [comment]
pre-asigned to  @kuri-leo .

@kuri-leo , if you agree please make a comment "I am on it"

**Comment by kuri-leo** [comment]
I am on it, thanks!

**Comment by kuri-leo** [comment]
Hi @pbludov ,
I've read the source code in past few days and now want to talk to you to make sure I have correct understading of your issue:
The output you expect is “**two errors: one for outer javadoc and one for inner javadoc**”, but right now **there was only one**.
If I misunderstood it, please tell me. then I can begin to debug.
Thanks!

**Comment by pbludov** [comment]
Hi @kuri-leo !

As  @rnveach noted, AbstractJavadocCheck#isCorrectJavadocPosition is too strict:

> Documentation comments are recognized only when placed immediately before class, interface, constructor, method, or field declarations

But the parser produces different tags for fields and annotation fields. That is the problem. The tag ANNOTATION_FIELD_DEF is missed in BlockCommentPosition.isOnField.
Or, may be there must be BlockCommentPosition.isOnAnnotationField method and isCorrectJavadocPosition should use it.

Some other cases may be also missing. That is what should be fixed.

If I were you, I'd made a list of all tags that can have a comment. I would write a test where all these cases are. Then I corrected the code so all the tests were passing.

I'm not too familiar with this library, so I can't do it myself. I need your help.

**Comment by pbludov** [comment]
Hold on. There is an issue similar to https://github.com/checkstyle/checkstyle/issues/5226.

BlockCommentPosition.isOnPlainClassMember() fails to recognize javadoc comments on methods without modifiers but with full qualified types, like this:

```
interface Test {
  java.lang.String method();
}
```
I'll update the PR soon.

**Comment by pbludov** [comment]
That's what I'm talking about:
```
    |--ANNOTATION_FIELD_DEF -> ANNOTATION_FIELD_DEF [243:10]
    |   |--MODIFIERS -> MODIFIERS [243:10]
    |   |--TYPE -> TYPE [243:10]
    |   |   `--DOT -> . [243:10]
    |   |       |--DOT -> . [243:5]
    |   |       |   |--BLOCK_COMMENT_BEGIN -> /* [242:1]
    |   |       |   |   |--COMMENT_CONTENT -> *Javadoc [242:3]
    |   |       |   |   |   `--JAVADOC -> JAVADOC [242:4]
    |   |       |   |   |       |--TEXT -> Javadoc [242:4]
    |   |       |   |   |       `--EOF -> <EOF> [242:11]
    |   |       |   |   `--BLOCK_COMMENT_END -> */ [242:10]
    |   |       |   |--IDENT -> java [243:1]
    |   |       |   `--IDENT -> lang [243:6]
    |   |       `--IDENT -> String [243:11]
```

between the `BLOCK_COMMENT_BEGIN` tag and the `TYPE` tag may be any count (including zero) of the 'DOT' tag.

**Comment by romani** [comment]
fix is merged.
@pbludov , thank you very much for your work!
