### ISSUE TITLE
Add suppression of .DS_Store for NewlineAtEndOfFile

### ISSUE THREAD

**Issue by Luolc** [checkstyle/checkstyle#4176]
We have added https://github.com/checkstyle/checkstyle/blob/master/config/checkstyle_non_main_files_checks.xml.

And it didn't suppress `.DS_Store` now. It does not affect the online CI but mac developers would always failed with `mvn verify` now if they enable `.DS_Store` on their PC.

Although we could tell them to banned the generation of `.DS_Store` manually. But I think it is better to add a simple `<suppress checks="NewlineAtEndOfFile" files=".DS_Store"/>` at the suppression file.

**Comment by rnveach** [comment]
I think we should add it to the list of excludes in the POM at https://github.com/checkstyle/checkstyle/blob/master/pom.xml#L509 . We should add all `.gitignore` files to the pom exclude so we don't have any other problems.

**Comment by romani** [comment]
fix is merged.
