### ISSUE TITLE
Add LAMBDA in RightCurly to checkstyle_checks

### ISSUE THREAD

**Issue by Vladlis** [checkstyle/checkstyle#4177]
taken from [discussion](https://github.com/checkstyle/checkstyle/pull/3969#issuecomment-292750251).

After #3546 is fixed LAMBDA has to be added to checkstyle_ckecks.xml to make that we created functionality that are usable. Unfortunately this case is controversial and we do not have prober mode now in Check

To my current view of issue, we need to treat lambda the same as anonymous classes,  for classes we are using now `alone`, and we do not process anonymous classes right now by our config. Anonymous class is just OBJBLOCK under LITERAL_NEW, and we do not process(not supported token) LITERAL_NEW in http://checkstyle.sourceforge.net/config_blocks.html#RightCurly .

```
$ javac MyClass.java

$ cat MyClass.java 
public class MyClass {
    public void foo() {
        new Thread( new Runnable() {
          // some overrides
        }).start();
    }

}

$ java -jar checkstyle-7.6-all.jar -t MyClass.java 
CLASS_DEF -> CLASS_DEF [1:0]
|--MODIFIERS -> MODIFIERS [1:0]
|   `--LITERAL_PUBLIC -> public [1:0]
|--LITERAL_CLASS -> class [1:7]
|--IDENT -> MyClass [1:13]
`--OBJBLOCK -> OBJBLOCK [1:21]
    |--LCURLY -> { [1:21]
    |--METHOD_DEF -> METHOD_DEF [2:4]
    |   |--MODIFIERS -> MODIFIERS [2:4]
    |   |   `--LITERAL_PUBLIC -> public [2:4]
    |   |--TYPE -> TYPE [2:11]
    |   |   `--LITERAL_VOID -> void [2:11]
    |   |--IDENT -> foo [2:16]
    |   |--LPAREN -> ( [2:19]
    |   |--PARAMETERS -> PARAMETERS [2:20]
    |   |--RPAREN -> ) [2:20]
    |   `--SLIST -> { [2:22]
    |       |--EXPR -> EXPR [5:16]
    |       |   `--METHOD_CALL -> ( [5:16]
    |       |       |--DOT -> . [5:10]
    |       |       |   |--LITERAL_NEW -> new [3:8]
    |       |       |   |   |--IDENT -> Thread [3:12]
    |       |       |   |   |--LPAREN -> ( [3:18]
    |       |       |   |   |--ELIST -> ELIST [3:20]
    |       |       |   |   |   `--EXPR -> EXPR [3:20]
    |       |       |   |   |       `--LITERAL_NEW -> new [3:20]
    |       |       |   |   |           |--IDENT -> Runnable [3:24]
    |       |       |   |   |           |--LPAREN -> ( [3:32]
    |       |       |   |   |           |--ELIST -> ELIST [3:33]
    |       |       |   |   |           |--RPAREN -> ) [3:33]
    |       |       |   |   |           `--OBJBLOCK -> OBJBLOCK [3:35]
    |       |       |   |   |               |--LCURLY -> { [3:35]
    |       |       |   |   |               `--RCURLY -> } [5:8]
    |       |       |   |   `--RPAREN -> ) [5:9]
    |       |       |   `--IDENT -> start [5:11]
    |       |       |--ELIST -> ELIST [5:17]
    |       |       `--RPAREN -> ) [5:17]
    |       |--SEMI -> ; [5:18]
    |       `--RCURLY -> } [6:4]
    `--RCURLY -> } [8:0]
```

Here are reports against Checkstyle:
https://vladlis.github.io/rcurly/lambda/same/checkstyle/site/
https://vladlis.github.io/rcurly/lambda/alone/checkstyle/site/
https://vladlis.github.io/rcurly/lambda/alone_or_singleline/checkstyle/site/

We need to decide what brace policy to use, or may be create a new policy.
This is issue is not ready to code, investigation should be done first to define how we are going to fix it..

**Comment by romani** [comment]
After discussion in  #4058 (PR #4173)

We made a decision to make a new Check to support formatting of RightCurly in blocks of expression (blocks which can be embedded/nested into statements as arguments or ..... ).
See details at #5945.
