### ISSUE TITLE
Add LAMBDA in RightCurly to google_checks

### ISSUE THREAD

**Issue by Vladlis** [checkstyle/checkstyle#4178]
After #3546 is fixed LAMBDA has to be added to google_checks.xml

The problem is specified here: https://github.com/checkstyle/checkstyle/pull/3969#issuecomment-292750251

> google do not mention formatting of anonymous classes and nested lambdas. We need to open issue against guide , and probably against https://github.com/google/google-java-format for details.

**Comment by romani** [comment]
before we put approved label on issue , we need to get to know expected behavior from Google.
Issue on "google style guide" or google-java-format need to be created.

**Comment by Vladlis** [comment]
@romani 
An existing issue on google style guideis updated: https://github.com/google/styleguide/issues/112

And here is like google-java-format plugin for IntelliJ IDEA works:
this **(1)**
```java
        Stream.of("Hello").filter(s -> {
                return s != null;
        }).collect(Collectors.toList());
```
and this **(2)**
```java
        Stream.of("Hello").filter(s -> {return s != null;})
                .collect(Collectors.toList());
```
and this **(3)**
```java
        Stream.of("Hello").filter(s -> {return s != null;}).collect(Collectors.toList());
```
is formatted like this **(1), (2), (3) -> (4)**
```java
    Stream.of("Hello")
        .filter(
            s -> {
              return s != null;
            })
        .collect(Collectors.toList());
```

also all of
**(5)**
```java
        bar(() -> {return;}, () -> {return;});
````
**(6)**
```java
        bar(() -> {
            return;
        }, () -> {return;});
````
**(7)**
```java
        bar(() -> {
            return;
        }, () -> {
            return;
        });
````
**(8)**
```java
        bar(() -> {
            return;}, () -> {return;});
````
**(9)**
```java
        bar(() -> {
            return;
        }, () -> {
            return;});
```
become this **(5), (6), (7), (8), (9) -> (10)**
```java
bar(
        () -> {
          return;
        },
        () -> {
          return;
        });
```

**Comment by romani** [comment]
Yes, they treat lambda as anonymous class.
We need new mode to be introduced for Check to focus on  anonymous classes and lambdas.
