### ISSUE TITLE
Include ENUM_DEF as an accepted token for RightCurlyCheck

### ISSUE THREAD

**Issue by ps-sp** [checkstyle/checkstyle#4180]
Why is such behaviour 'ok' if the brace policy is set to alone ?

https://github.com/checkstyle/checkstyle/blob/master/src/it/resources/com/google/checkstyle/test/chapter4formatting/rule412nonemptyblocks/InputRightCurlyOtherAlone.java#L125

Is it because ENUM_DEF isn't an accepted token for the check ?

**Comment by rnveach** [comment]
@ps-sp Look over http://checkstyle.sourceforge.net/report_issue.html#How_to_report_a_bug . We only accept issues that are clear and in this format.

> Is it because ENUM_DEF isn't an accepted token for the check ?

This is most likely the reason as best I can tell from the given report.
This will be fixed in Issue #3547 .
