### ISSUE TITLE
Split and Organize Checkstyle inputs by Test for ParameterName

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#4191]
subtask of #3891 .

do a copy of all test input files to separate folder for ParameterName .
Not any other Check should use new inputs.

**Comment by romani** [comment]
pre-assigned to @Shubhk15 .

@Shubhk15 , please make comment "I am on it" to confirm assignment

**Comment by Shubhk15** [comment]
I am on it

**Comment by Shubhk15** [comment]
@romani Please verify the PR
Thanks.

**Comment by romani** [comment]
fix is merged
