### ISSUE TITLE
ImportOrder option "bottom" allows the same static import placement as "under" 

### ISSUE THREAD

**Issue by vrozov** [checkstyle/checkstyle#4196]

**Comment by rnveach** [comment]
@vrozov Please look over http://checkstyle.sourceforge.net/report_issue.html#How_to_report_a_bug and edit your first post to show us the issue you are talking about.

**Comment by vrozov** [comment]
@rnveach It is up to you if you want to close the issue instead of fixing it.

**Comment by romani** [comment]
@vrozov  , please put in description required details. It helps a lot. Easy to reproduce issue are resolved first.

**Comment by vrozov** [comment]
@romani It is easy to reproduce the bug with the provided description.

**Comment by romani** [comment]
@vrozov , sorry, rules are equal for all.

**Comment by vrozov** [comment]
@romani Sure, it is your product, the next time I will not even bother to report the problem.

**Comment by romani** [comment]
We appreciate your feedback.
I could reopen your issue, but nobody will touch it as it unclear, so it is the same as no issue at all ( we already has bunch issue like this in backlog). I just share with you my experience for maintaining of this project for many years. As you report issue as requested you will notice that smb will catch it.

**Comment by vrozov** [comment]
It is OK, you may keep the issue closed.  If you don't care about the bug in the project you maintain for years, I don't care either. IMO, the description of the bug is clear and provides an easy way to reproduce it (or at least try to reproduce). It took longer to discuss and close the issue than to try to reproduce it.
