### ISSUE TITLE
SuppressionCommentFilter not working properly in multi-thread environment

### ISSUE THREAD

**Issue by nstaeger** [checkstyle/checkstyle#4198]
Hi there,

we are using the `SuppressionCommentFilter` to disable Checkstyle for specific areas of our code. We are also using the Maven Checkstyle Plugin (version 2.27) to execute a Checkstyle scan when building the project. However, since we upgraded Checkstyle from 6.16 to 7.6.1 the Maven build-process fails sporadically when building with multiple threads (using `-T4C`) because of Checkstyle. It reports warnings for parts of the code, where Checkstyle was disabled (using `CHECKSTYLE:OFF`/`:ON`). So the Filter seems to not work correctly in a multi-threaded environment.

Any ideas highly appreciated.

Best

**Comment by rnveach** [comment]
Please see the following:
https://groups.google.com/forum/#!topic/checkstyle-devel/ay2CxvaKeQo
https://github.com/checkstyle/checkstyle/wiki/Checkstyle-GSoC-2017-Project-Ideas#project-name-multi-thread-mode-for-java-files-processing

Checkstyle is not a multi-threaded tool. We don't support it right now, and probably other things will break if you try to run it as such.

**Comment by nstaeger** [comment]
Hey @rnveach,

thanks for your reply! It worked well with version 6.16 but perhaps we just were lucky.
