### ISSUE TITLE
Split and Organize Checkstyle inputs by Test in the blocks package

### ISSUE THREAD

**Issue by subkrish** [checkstyle/checkstyle#4220]
subtask of #3891 

Move / Make a copy of all test input files to a separate folder for all checks in `blocks` package.
Not any other Check should use new inputs.

**Comment by rnveach** [comment]
pre-assigned to @subkrish 

1 test and it's inputs per PR for now

**Comment by romani** [comment]
fix is merged

**Comment by subkrish** [comment]
The two remaining checks in this package have not been pushed yet, i.e. `NeedBracesCheckTest.java` and `RightCurlyCheckTest.java`.

**Comment by romani** [comment]
commit 2036e7a4abceddad23311f4fa4bc61460072756a is reverted from master as it caused build failure.
@subkrish , please rebase and send changes again.

**Comment by Kietzmann** [comment]
@romani 
Seems that this issue should be closed due to complete

**Comment by rnveach** [comment]
Agree, I see no inputs left in base folder.
Closing as done.
