### ISSUE TITLE
[Feature Request] - Baseline support

### ISSUE THREAD

**Issue by vanniktech** [checkstyle/checkstyle#4222]
I'd like to add Checkstyle to and old legacy project however the warnings and errors are in the thousands. 

It would be handy if I could let Checkstyle run once, generate a baseline file and then only get new errors / warnings reported from Checkstyle.

**Comment by romani** [comment]
Checkstyle does not store state of previous validations.
You will be able to archive it by flexible AST based suppressions.

https://github.com/checkstyle/checkstyle/wiki/Checkstyle-GSoC-2017-Project-Ideas#project-name-flexible-suppression-model

We plan to make generator of suppressions for legacy projects.

Keep an eye on #102
