### ISSUE TITLE
Broken test in master branch

### ISSUE THREAD

**Issue by Kietzmann** [checkstyle/checkstyle#4267]
While running mvn test in master branch I'm receiving the next error:

Failed tests: 
  EmptyBlockCheckTest.testAllowEmptyDefaultWithText:206->BaseCheckTestSupport.verify:191->BaseCheckTestSupport.verify:227->BaseCheckTestSupport.verify:258 error message 0 expected:<...utEmptyDefault.java:[11:13: Empty default block.]> but was:<...utEmptyDefault.java:[0: Got an exception - /home/dmytro/IdeaProjects/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/emptyblock/InputEmptyDefault.java (No such file or directory)]>
  EmptyBlockCheckTest.testForbidDefaultWithoutStatement:225->BaseCheckTestSupport.verify:191->BaseCheckTestSupport.verify:227->BaseCheckTestSupport.verify:258 error message 0 expected:<...utEmptyDefault.java:[11:13: Must have at least one statement.]> but was:<...utEmptyDefault.java:[0: Got an exception - /home/dmytro/IdeaProjects/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/emptyblock/InputEmptyDefault.java (No such file or directory)]>

Tests run: 2037, Failures: 2, Errors: 0, Skipped: 0 

It is caused by last @subkrish commit #4223  for issue #4220 
$ cat EmptyBlockCheckTest.java

../

    @Test
    public void testAllowEmptyDefaultWithText() throws Exception {
        final DefaultConfiguration checkConfig = createCheckConfig(EmptyBlockCheck.class);
        checkConfig.addAttribute("option", BlockOption.TEXT.toString());
        checkConfig.addAttribute("tokens", "LITERAL_DEFAULT");
        final String[] expected = {
            "5:30: " + getCheckMessage(MSG_KEY_BLOCK_EMPTY, "default"),
            "11:13: " + getCheckMessage(MSG_KEY_BLOCK_EMPTY, "default"),
            "36:22: " + getCheckMessage(MSG_KEY_BLOCK_EMPTY, "default"),
            "44:47: " + getCheckMessage(MSG_KEY_BLOCK_EMPTY, "default"),
            "50:22: " + getCheckMessage(MSG_KEY_BLOCK_EMPTY, "default"),
            "78:13: " + getCheckMessage(MSG_KEY_BLOCK_EMPTY, "default"),
        };
        verify(checkConfig, getPath("InputEmptyDefault.java"), expected);
    }

    @Test
    public void testForbidDefaultWithoutStatement() throws Exception {
        final DefaultConfiguration checkConfig = createCheckConfig(EmptyBlockCheck.class);
        checkConfig.addAttribute("option", BlockOption.STMT.toString());
        checkConfig.addAttribute("tokens", "LITERAL_DEFAULT");
        final String[] expected = {
            "5:30: " + getCheckMessage(MSG_KEY_BLOCK_NO_STMT, "default"),
            "11:13: " + getCheckMessage(MSG_KEY_BLOCK_NO_STMT, "default"),
            "15:13: " + getCheckMessage(MSG_KEY_BLOCK_NO_STMT, "default"),
            "26:30: " + getCheckMessage(MSG_KEY_BLOCK_NO_STMT, "default"),
            "36:22: " + getCheckMessage(MSG_KEY_BLOCK_NO_STMT, "default"),
            "44:47: " + getCheckMessage(MSG_KEY_BLOCK_NO_STMT, "default"),
            "50:22: " + getCheckMessage(MSG_KEY_BLOCK_NO_STMT, "default"),
            "65:22: " + getCheckMessage(MSG_KEY_BLOCK_NO_STMT, "default"),
            "78:13: " + getCheckMessage(MSG_KEY_BLOCK_NO_STMT, "default"),
        };
        verify(checkConfig, getPath("InputEmptyDefault.java"), expected);
    }

InputEmptyDefault.java wasn't moved to the new package, so it causes an error.
Right now I'm fixing this bug and preparing pull request to fix it.

**Comment by rnveach** [comment]
@Kietzmann Please provide a PR for fix

**Comment by Kietzmann** [comment]
@rnveach 
No, it was caused by @subkrish patch definitely.

**Comment by rnveach** [comment]
@Kietzmann Yes, his test modifications is the one that is causing the error, but the input file was created from mentioned commit. They were merged 24 hours apart and subkrish's original commit was made 3 days ago, 2 days before the mentioned commit was merged.
It looks like bad timing that they were working in similar areas and there were no conflicts to warn us during merge.

**Comment by romani** [comment]
problematic commit was reverted , issue is reopened #4220 .
