### ISSUE TITLE
Split and Organize Checkstyle inputs by Test for checks in annotation package

### ISSUE THREAD

**Issue by Kietzmann** [checkstyle/checkstyle#4313]
subtask of #3891

move / do a copy of all test input files to a separate folder for all checks in `annotation` package.
Not any other Check should use new inputs.

**Comment by rnveach** [comment]
https://github.com/checkstyle/checkstyle/tree/master/src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation

`InputAnnotationLocation2.java` is still left.

**Comment by rnveach** [comment]
Fixes have been merged
