### ISSUE TITLE
Split and Organize Checkstyle inputs by Test for checks in design package

### ISSUE THREAD

**Issue by Kietzmann** [checkstyle/checkstyle#4314]
subtask of #3891

move / do a copy of all test input files to a separate folder for all checks in `design` package.
Not any other Check should use new inputs.

**Comment by rnveach** [comment]
@Kietzmann 3 input files remain in package.
https://github.com/checkstyle/checkstyle/tree/master/src/test/resources/com/puppycrawl/tools/checkstyle/checks/design
Can they be removed or moved to their specific sub-folder?

**Comment by rnveach** [comment]
fixes have been merged
