### ISSUE TITLE
Change in behaviour between 5.9 and 6.0 for Javadoc referencing checked exception that is not thrown

### ISSUE THREAD

**Issue by stubillwhite** [checkstyle/checkstyle#432]
We recently upgraded from a very old version of Checkstyle to the most recent version, and noticed a change in behaviour for the situation where Javadoc indicates that a checked exception may be thrown but there is no corresponding throws clause on the method.

The behaviour seems to have changed between versions 5.9 and 6.0 of Checkstyle. I've created a test case here: https://gist.github.com/stubillwhite/a96545347e471e2284e7

For completeness, we're using IBM Java 7 but I don't believe that's relevant.

Output for run-checkstyle-5.9.bat:
Starting audit...
C:\TRASH\checkstyle-behaviour-change\ExceptionJavadoc.java:8:8: warning: Unused @throws tag for 'java.io.IOException'.
Audit done.

Output for run-checkstyle-6.0.bat:
Starting audit...
Audit done.

(On a side note, thank you for all your hard work on Checkstyle -- we find it invaluable.)
##

**Comment by mkordas** [comment]
The thing here is simple. In Checkstyle 6.0 `validateThrows` option was added to JavadocMethod and it's default value is `false`. This means that by default `@throws` is not validated at all. @romani, any idea why it is so? You were merging #329.

**Comment by rnveach** [comment]
@romani 
Like mkordas said, the original issue of validating throws is false as default. http://checkstyle.sourceforge.net/config_javadoc.html#JavadocMethod
Setting it as true brings back the behavior the user wants.
I think this issue can be closed as a result.

````
$ cat TestClass.java
/**
 * This is my class.
 */
public final class ExceptionJavadoc
{
    /**
     * This is a method.
     * @throws java.io.IOException sometimes.
     */
    public void badMethod()
    {
        // Bad method Javadocs a CHECKED exception that isn't declared in the throws clause.
    }
}

$ cat TestConfig.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>

    <module name="TreeWalker">
        <module name="JavadocMethod">
            <property name="scope"                  value="protected"/>
            <property name="allowMissingThrowsTags" value="true"/>
            <property name="logLoadErrors"          value="true"/>
            <property name="suppressLoadErrors"     value="true"/>
            <property name="allowUndeclaredRTE"     value="true"        />
<property name="validateThrows" value="true"/>
        </module>
    </module>
</module>

$ java -jar checkstyle-7.2-all.jar -c TestConfig.xml TestClass.java
Starting audit...
[ERROR] TestClass.java:8:8: Unused @throws tag for 'java.io.IOException'. [JavadocMethod]
Audit done.
Checkstyle ends with 1 errors.
````

**Comment by mkordas** [comment]
@rnveach I think that it should be enabled by default

**Comment by romani** [comment]
We can not reliably validate exceptions, is user define any runtime exception it will be false-positive. Checkstyle is not type aware tool. Other limitations  - http://checkstyle.sourceforge.net/writingchecks.html#Limitations
It is up to a user to use this option or not, it is his responsibility .
Default value should be such that produce no false-positives or minimal amount of it.
```
/var/tmp$ cat MyClass.java 
public final class MyClass
{
    /**
     * This is a method.
     * @throws java.lang.IllegalArgumentException sometimes.
     */
    public void badMethod()
    {
        // Bad method Javadocs a CHECKED exception that isn't declared in the throws clause.
    }
}
/var/tmp$ javac MyClass.java 
/var/tmp$ javadoc MyClass.java
Loading source file MyClass.java...
Constructing Javadoc information...
Standard Doclet version 1.8.0_102
Building tree for all the packages and classes...
Generating ./MyClass.html...
Generating ./package-frame.html...
Generating ./package-summary.html...
Generating ./package-tree.html...
Generating ./constant-values.html...
Building index for all the packages and classes...
Generating ./overview-tree.html...
Generating ./index-all.html...
Generating ./deprecated-list.html...
Building index for all classes...
Generating ./allclasses-frame.html...
Generating ./allclasses-noframe.html...
Generating ./index.html...
Generating ./help-doc.html...

/var/tmp$ cat MyClass.html | grep "java.lang.IllegalArgumentException" -C 10
<a name="badMethod--">
<!--   -->
</a>
<ul class="blockListLast">
<li class="blockList">
<h4>badMethod</h4>
<pre>public&nbsp;void&nbsp;badMethod()</pre>
<div class="block">This is a method.</div>
<dl>
<dt><span class="throwsLabel">Throws:</span></dt>
<dd><code>java.lang.IllegalArgumentException</code> - sometimes.</dd>
</dl>
</li>
</ul>
</li>
</ul>
</li>
</ul>
</div>
</div>
<!-- ========= END OF CLASS DATA ========= -->

```

Summary: Checkstyle can not reliably validate `@throws`.
