### ISSUE TITLE
publish all dtd schemas to sourceforge site automatically

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#4341]
base on results #1571

we need find a way to copy dtd files to `target/site` folder during `mvn site -Pno-validations` command.
Right now dtd files were copied by me manually ones before #1571 is merged, so we already have kind of outdated dtd files of our static website.

**Comment by MEZk** [comment]
@romani 
Judging by the Maven Site Plugin documentation it is not possible to download additional content to SourceForge by the plugin. One of the possible solutions can be [Exec Maven Plugin](http://www.mojohaus.org/exec-maven-plugin/index.html). The plugin can execute a shell command or script which will upload dtd schemes to SourceForge. The script invocation can be assigned to site phase.

**Comment by romani** [comment]
@MEZk , you missed a point. 
whole site is prepared in `target/site`. All we have to do is to put our files to `target/site/dtds` folder on local, all other will be done by maven site during deploy phase.

**Comment by MEZk** [comment]
As I see it, dtds schemes should stay in resources folder. As far as I know, mvn-site plugin cannot move external files to site folder. How can we move dtds from resource folder to site? We cannot just copy-paste them and support two copies which must be identical.

**Comment by romani** [comment]
I do not know solution, any proposals are welcome.

**Comment by MEZk** [comment]
@romani 
Another solution without exec plugin
https://maven.apache.org/plugins/maven-resources-plugin/examples/copy-resources.html

I'll send a PR.

**Comment by romani** [comment]
fix is merged

**Comment by romani** [comment]
linked folder outside of htdocs was moved inside, so dtds are physically inside htdocs folder.
