### ISSUE TITLE
Javadoc parser: Package names should permit digits in their name

### ISSUE THREAD

**Issue by blerner** [checkstyle/checkstyle#4349]
Per the JLS, https://docs.oracle.com/javase/specs/jls/se8/html/jls-7.html#jls-7.4.1, package names are permitted to be any sequence of identifiers.  But JavadocParser.g4 (https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/com/puppycrawl/tools/checkstyle/grammars/javadoc/JavadocParser.g4#L907) specifies that package references use `PACKAGE` names as their leading tokens, which in turn are defined (https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/com/puppycrawl/tools/checkstyle/grammars/javadoc/JavadocLexer.g4#L122) without permitting digits.

**Comment by rnveach** [comment]
Fix is merged
