### ISSUE TITLE
codeship: provide ability to skip CI executions base on commit files

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#4352]
continuation of #3818 .

we need to extend build script to skip CI execution if non-related files are changed only.
wercker , travis, distelli, shippable are already updated.

codeship just run https://github.com/checkstyle/checkstyle/blob/master/.ci/run-link-check-plugin.sh file.
So he need to be updated with same logic as we did at #3818 .

**Comment by Gaurav-Punjabi** [comment]
@romani So we need to update the code of `run-link-check-plugin.sh` to skip CI Execution base on commit files. Correct?

**Comment by romani** [comment]
fix is merged.

**Comment by romani** [comment]
I reverted fix as CI looks like not supporting multiline commands.

**Comment by Gaurav-Punjabi** [comment]
Okay, so to fix the failure should we use multiple "command" for each step or wait for the support to for multiline commands ?

**Comment by Gaurav-Punjabi** [comment]
My bad. I just saw that you have already fixed it 👍 
Thanks
