### ISSUE TITLE
refactoring: remove 'final' modifier from all arguments of method/c-tor at ImportControlCheck and around

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#4353]
problem was found at https://github.com/checkstyle/checkstyle/pull/4282#discussion_r116366595

New code added a lot of unnecessary `final` in parameters of methods and constructors.
We have a guard Check that catch reusage of argument, so this finals in these areas just make code verbose.
We should remove all `final` in parameters for these areas.

Fix should be done after PR #4282 is merged.

**Comment by sharang108** [comment]
I want to contribute, but I don't know where to begin after pulling the source code.

**Comment by MEZk** [comment]
@sharang108 
See http://checkstyle.sourceforge.net/contributing.html

**Comment by sharang108** [comment]
How can I contribute without using IDEs?

**Comment by jochenvdv** [comment]
These steps can be applied to any text editor or IDE:

1. Fork the repository
2. Create and switch to a new branch for your fixes
3. Implement your changes using an editor of choice
3. Run tests and code analysis using `mvn clean verify`
4. Commit and push your fixes to your fork
5. View your forked repo on GitHub and create a PR against the original Checkstyle master branch, make sure to adhere to the PR rules mentioned above

**Comment by sharang108** [comment]
I am ready with the platform what to do next?

**Comment by rnveach** [comment]
@sharang108 See jochenvdv's post. It lists all the steps you need to do.
When you are done, there will be a PR with your changes here that we will review.

**Comment by sharang108** [comment]
@rnveach  What fixes?? I don't know what to fix, that's why I need something to start with.

**Comment by rnveach** [comment]
@sharang108 Read issue title and first post. I made it more clear what we want done and why.
Find all `final` parameters in methods/constructors/catch in 'main' code and remove them.

**Comment by sharang108** [comment]
@romani @rnveach @MEZk Is [this](https://github.com/sharang108/checkstyle/commit/bf3607120ba72169da231d25d49220fdcc4de17b) what you are asking for?

**Comment by rnveach** [comment]
@sharang108 Yes, in test and in main check.

**Comment by romani** [comment]
@sharang108 , did you finish the issue ?

**Comment by sharang108** [comment]
@romani Yes, but just confirm with @rnveach

**Comment by romani** [comment]
fix is merged.

**Comment by romani** [comment]
@rnveach , it might be good to have such a Check in checkstyle to forbid final on arguments, what do you think ?

**Comment by rnveach** [comment]
@romani See https://github.com/sevntu-checkstyle/sevntu.checkstyle/issues/581
