### ISSUE TITLE
Do investigation where to put parallelization in checkstyle

### ISSUE THREAD

**Issue by sabaka** [checkstyle/checkstyle#4354]
Measure how much time do we spend on checkstyle phases which potentially can be parallelized.

According to plan we have 3 potential places:
1) Parsing to AST (the most time consuming process)
2) Launching several “Checkstyles” base on pool of AST  
3) Launching each visitToken in separate “thread” if Check is completely stateless and this is where light treads will be in demand (probably does not make sense in comparison with Antlr processing)

Also give forecast of performance improvements we can get there in MT mode.

**Comment by soon** [comment]
Initial measurements based on guava project:

- Stats: [GDocs](https://docs.google.com/spreadsheets/d/141Z96uYmGayp8O8zAj5XFuVZs2FFJnjxjCP1KuwsYj0/edit?usp=sharing)
- Branch: [github](https://github.com/soon/checkstyle/commit/07208a5fa25d7517a4576de603216a6cd15b2ea9). Dev version only, does not pass `verify`. Build as `mvn -Passembly package` and then run as usual via `java -cp checkstyle-7.8-SNAPSHOT-jar-with-dependencies.jar com.puppycrawl.tools.checkstyle.Main  -c /google_checks.xml ${FILES_TO_CHECK} > /dev/null`. Creates `stats.csv` in the current directory.

**Comment by rnveach** [comment]
@soon One problem with your measurements is 'walk comments'.
You aplit apart 'ast' and 'normal walk', but 'walk comments' is a combination of 'walk with comments' and 'javadoc ast'. This is most likely why 'walk' is normally green and yellow, and 'walk comments' is all over the place in colors.
If you accounted for javadoc ast, I expect both walks to be the same.

Some other things I questions:
Is google checks the best configuration to use? It doesn't contain all modules, so it is slightly skewed to modules that can only be used for google.
I assume your stats is only one run, and doesn't account for Java's JIT compiler which is constantly rewriting code based on hot spots? Should we account for this somehow? Most places I have read on this say to do a few dozen warm up runs before you start recording numbers.
Your numbers are based on 'treewalker' which means we are ignoring `AbstractFileSetCheck`s. I know issue mentions mostly 'AST', but we are just going to single thread all filesets then?

**Comment by Vladlis** [comment]
@soon, when you provide some measurements please also share with us a brief analysis. 

Just a thought: doesn't usage of existing checks provide additional inaccuracy to the measurements? What if we use mocks, which will perform some simple (or not simple) actions on AST?

**Comment by sabaka** [comment]
I did copy to my drive and added average values and pie chart.
[GSheets](https://docs.google.com/spreadsheets/d/1zWtoKA-cq-4i_o_gFqEAum4MAHcWBIOA3XB5roUPXYE/edit?usp=sharing)
Now we can see that in average we spend 42% of time on AST creation, 36% on javadoc and 21% on walk. Javadoc performance is another project and I'm not sure it's correct to mix them right now.

@soon , Could you please add file size column? I'm interested how parse time depends on file size.

@Vladlis, which results do you want to retrieve with replacing checks with mocks? Not clear.

**Comment by Vladlis** [comment]
@sabaka, I think mocks would provide fairer results for the time spent on walk. This time might become less dependent on file contents.

**Comment by soon** [comment]
@sabaka Added file size column ([GSheets](https://docs.google.com/spreadsheets/d/1_Loc-FrPku1E22xTbtm8BAttJArG95rVr2GJFihSnaE/edit?usp=sharing))

Also collected stats for the openjdk8 ([GSheets](https://docs.google.com/spreadsheets/d/15jH8AEberXBozDFZ9UsRl9YslrnO8rtjSqr1oKJimwY/edit?usp=sharing)) using the following command:

`java -cp /home/soon/Src/Java/checkstyle/target/checkstyle-7.8-SNAPSHOT-jar-with-dependencies.jar com.puppycrawl.tools.checkstyle.Main  -c /sun_checks.xml -e test/tools/pack200/typeannos * > /dev/null`

According to the stats collected for the openjdk project AST parsing takes 68% of the tame, walk - 24%, append comments - 2%, walk comments - 6%

@rnveach, @Vladlis, thank you for your corrections, I'll take them into account and will post results here

> I assume your stats is only one run, and doesn't account for Java's JIT compiler which is constantly 
> rewriting code based on hot spots? Should we account for this somehow? Most places I have read 
> on this say to do a few dozen warm up runs before you start recording numbers.

Not sure if JIT warmup is suitable here. It is required if we're collecting stats for the long-running applications (like web servers), but checkstyle is a tool and all JIT optimizations will be eliminated as soon as the checkstyle finishes all checks. But I'll, of course, collect stats with JIT warmup and compare them with the current stats.

> Just a thought: doesn't usage of existing checks provide additional inaccuracy to the 
> measurements? What if we use mocks, which will perform some simple (or not simple) actions on 
> AST?

In my opinion, we should collect stats for real projects with real checks, because collecting stats for mock checks allows us to optimize, well, mock checks :) But I'll also collect stats for this case, as soon as I resolve issues with javadoc ast and JIT.

**Comment by rnveach** [comment]
> Javadoc performance is another project and I'm not sure it's correct to mix them right now.

@sabaka We are not changing any AST, java or javadoc. We are just looking at hotspot areas as a whole and finding places and ways to multi-thread them. Since we aren't diving further into the compiled grammar code, there is no mixing.

**Comment by sabaka** [comment]
@Vladlis , If I understood correct, it would help to measure time spent on parsing only, but we want to know is it worth to launch checks in parallel and how much performance it can gain. If we use mocks - we will get only parsing time measurements.
@rnveach , you are right.

**Comment by Vladlis** [comment]
@sabaka ok, I see
@soon please don't bother running tests with mocks

**Comment by soon** [comment]
Added stats for file-based checks (see last Total) tab:

1. openjdk7: [GSheets](https://docs.google.com/spreadsheets/d/1EgfJRGJ6XHTKFAFeEVBiAKR0T6n615InEOqxFIiPB2Q/edit?usp=sharing)
2. openjdk8: [GDrive](https://drive.google.com/open?id=0B2tqvnoN8fAWRzZRUlNlQTNPa00) (unfortunately, I'm unable to convert this report to GSheets)
3. guava: [GSheets](https://docs.google.com/spreadsheets/d/1uwZiiv6AODm3bRJvwZogPBNGyf2UsntfAOHApRcpiqM/edit?usp=sharing)
4. apache-ant: [GSheets](https://docs.google.com/spreadsheets/d/1C4m0iUhmFY3jbdQutPcFBTWka79hxuf3uLIW5OIClVs/edit?usp=sharing)

Brief results: `TreeWalker` consumes about 95% and `RegexpSinglelineCheck` consumes about 4% of the total check time.

**Comment by soon** [comment]
Initial report for guava project with google checks: [GSheets](https://docs.google.com/spreadsheets/d/1M72yj1WGS5M6xEi6ncoBd-W0DZfaoGWHZ6APE0YJfPM/edit?usp=sharing). The javadoc parse consumes about 10% of the total TreeWalker time.

Unfortunately, I'm unable to retrieve javadoc parse stats using sun_checks on jdk projects. Going to prepare reports for checkstyle_checks.xml instead.

**Comment by soon** [comment]
There is another possible bottleneck. According to the measurements (on the checkstyle sources), the `AbstractChecker::fireErrors` takes about 12sec, while the total execution time is 43 sec, i.e. it takes 25% of the total execution (https://github.com/soon/checkstyle/commit/9fb44245745fe9f82f3409c5cea1d051d74d5457):

```
rm -f cachefile && time java -Dcheckstyle.cache.file=cachefile -Dcheckstyle.suppressions.file=/home/soon/Src/Java/checkstyle/config/suppressions.xml -Dcheckstyle.header.file=/home/soon/Src/Java/checkstyle/config/java.header -Dcheckstyle.regexp.header.file=/home/soon/Src/Java/checkstyle/config/java_regexp.header -Dcheckstyle.importcontrol.file=/home/soon/Src/Java/checkstyle/config/import-control.xml  -cp /home/soon/Src/Java/checkstyle/target/checkstyle-8.0-SNAPSHOT-jar-with-dependencies.jar com.puppycrawl.tools.checkstyle.Main  -c /home/soon/Src/Java/checkstyle/config/checkstyle_checks.xml -e src/etc/testcases/taskdefs/fixcrlf/expected -e src/etc/testcases/taskdefs/fixcrlf/input -e src/tests/antunit/taskdefs/javac-dir/bad-src -e  src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle -e ./pom.xml -e src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace -e src/it/resources/com/google/checkstyle/test/chapter4formatting/rule487modifiers -e src/it/resources -e src/test/resources -e src/test/resources-noncompilable * | sort > mt.res.txt 

Fire errors calls: 1045
Fire errors time: 11.77
Actual filters accept time: 11.75
Actual fire errors to listers: 0.00
java -Dcheckstyle.cache.file=cachefile     -cp   -c  -e  -e  -e  -e  -e  -e    84.15s user 0.47s system 192% cpu 43.933 total
sort > mt.res.txt  0.00s user 0.00s system 0% cpu 43.932 total
```

Here `Fire errors calls` is the number of calls to `AbstractChecker::fireErrors` method, `Fire errors time` is the total time of all `AbstractChecker::fireErrors` calls, `Actual filters accept time` is the total time of `FilterSet::accept` calls, and `Actual fire errors to listers` is the time of `AuditListener::addError` calls.

However, for the guava project the time consumption is much less:

```
Fire errors calls: 3136
Fire errors time: 1.76
Actual filters accept time: 0.01
Actual fire errors to listers: 1.72
java -Dcheckstyle.cache.file=cachefile     -cp   -c /google_checks.xml -e  -e  132.68s user 0.68s system 148% cpu 1:29.58 total
sort > mt.res.txt  1.91s user 0.04s system 2% cpu 1:30.30 total
```

I'll do another measurements to see if it is really matter. Probably, there is an issue with a filter which is not using for the guava project

**Comment by rnveach** [comment]
> the guava project the time consumption is much less

You are using different configurations, so it is not a 1 to 1 compare. Are you getting many violations outputted in checkstyle?

One possible place of slowdown in fire errors is outputting to the console which is what `listener.addError` is.
I'm not sure you can multi-thread the console output otherwise it will be garbled.

**Comment by soon** [comment]
> You are using different configurations, so it is not a 1 to 1 compare

Yes, for guava project I'm using  `google_checks.xml`. Checkstyle config takes more than 10min to check the guava project and I decided to run it a bit later.

> One possible place of slowdown in fire errors is outputting to the console

I used to think so, but according to measurements, `listener.addError` takes less than one second to print errors (https://github.com/soon/checkstyle/commit/9fb44245745fe9f82f3409c5cea1d051d74d5457#diff-3f1acef1d510e7cf234339bed2c8782fR459): 

    Actual fire errors to listers: 0.00

However, `FilterSet.accept` takes `11.75sec` (https://github.com/soon/checkstyle/commit/9fb44245745fe9f82f3409c5cea1d051d74d5457#diff-38d3b7e05ff298b37b59f2996f15129cR98)

I'll provide more detailed report a bit later

**Comment by rnveach** [comment]
> according to measurements, listener.addError takes less than one second to print errors 
> Actual fire errors to listers: 0.00

Your google runtime specified `Actual fire errors to listers: 1.72` at https://github.com/checkstyle/checkstyle/issues/4354#issuecomment-310978142 which is why I thought it would be error printing.

If you find a slow-down area, you should drill down as much as possible to find where it is specifically happening. Making assumptions doesn't help.
