### ISSUE TITLE
Check one line empty before tags in javadoc

### ISSUE THREAD

**Issue by PashaTurok** [checkstyle/checkstyle#4356]
Oracle (in JDK they use it) suggests to insert one empty line in javadoc before tags (param, return etc) see http://www.oracle.com/technetwork/articles/java/index-137868.html. For example like this,

```
/**
 * Method for doing it.
 *
 * @param foo somefoo.
 */
public void doIt(Foo foo){}
```
So I suggest to add to checkstyle such rule.

**Comment by Vladlis** [comment]
@romani @rnveach
Should this be a separate check? Something like JavadocEmptyLineSeparator?

**Comment by rnveach** [comment]
@Vladlis The document he linked to is the one romani specified in the GSoC document.
https://github.com/checkstyle/checkstyle/wiki/Checkstyle-GSoC-2017-Project-Ideas#project-name-coverage-of-documentation-comments-style-guide-and-performance-optimization-of-javadoc-parser
So it seems to me this will happen in terms of GSoC.

**Comment by gaurabdg** [comment]
I am on it.

**Comment by baratali** [comment]
Same issue: https://github.com/checkstyle/checkstyle/issues/6192

**Comment by strkkk** [comment]
It seems that this has been fixed in https://github.com/checkstyle/checkstyle/issues/6192, I am closing this
