### ISSUE TITLE
DesignForExtension and javadoc comment

### ISSUE THREAD

**Issue by PashaTurok** [checkstyle/checkstyle#4357]
According to documentation here http://checkstyle.sourceforge.net/config_design.html#DesignForExtension 

> ATTENTION: If the method which can be overridden in a subclass has a javadoc comment (a good practise is to explain its self-use of overridable methods) the check will not rise a violation.

However, is not clear what javadoc comment such method must contain. When I start my javadoc with "This implementation ..." this check any way gives error.

**Comment by rnveach** [comment]
> When I start my javadoc with ... this check any way gives error.

@PashaTurok 
Please report problem like http://checkstyle.sourceforge.net/report_issue.html#How_to_report_a_bug so we can help you with your issue.

**Comment by PashaTurok** [comment]
@rnveach Sorry my fault. I used old version of checkstyle.

**Comment by MEZk** [comment]
@romani 
As long as I remember we wanted to extend the check and give the user an ability to specify the start part of the comment message.

**Comment by PashaTurok** [comment]
I use checkstyle only few days (very little experience) and I have to use two version at the same time. Because version 5.6 in in Netbeans 8.1 plugin and version 7.7 is used in maven plugin. 

But it seems to me that with version 7.7 there is no logic. Because if there is a javadoc (with any contents) then, as I understand, check doesn't give error. I think that for disabling **this** error there must be some **specific** comment.

**Comment by romani** [comment]
issue is not reported properly and result is mess . Issue is closed.
