### ISSUE TITLE
DesignForExtension: Special comment

### ISSUE THREAD

**Issue by PashaTurok** [checkstyle/checkstyle#4358]
http://checkstyle.sourceforge.net/config_design.html#DesignForExtension

This is Test.java:

```
public class Test{

    /**
     * The do it method.
     */
    public void doIt(){
	System.out.println("Do it");
    }

    public void dontDoIt(){
	System.out.println("Don't do it");     
    }
}
```
This is checkstyle.xml;
```
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
<module name="Checker">
    <property name="fileExtensions" value="java, properties, xml"/>
    <module name="TreeWalker">
        <!-- See http://checkstyle.sf.net/config_design.html -->
        <module name="DesignForExtension"/>
    </module>
</module>
```
This is command line:
`java -jar checkstyle-7.7-all.jar -c checkstyle.xml Test.java`

This is output:

> Starting audit...
> [ERROR] /home/Temp/Test.java:11:5: Class 'Test' looks like designed for extension (can be subclassed), but the method 'dontDoIt' does not have javadoc that explains how to do that safely. If class is not designed for extension consider making the class 'Test' final or making the method 'dontDoIt' static/final/abstract/empty, or adding allowed annotation for the method. [DesignForExtension]
> Audit done.
> Checkstyle ends with 1 errors.

As you see the only thing that is necessary to do to suppress this check is to add **any** comment. I think that is not logical, because if javadoc checks are used then we will have any comment in any case. So there is no meaning in such check. I suggest that for suppressing this error some **special** comment must be in javadoc. For example `Method can be safely overridden` or some pattern must be set in properties of the module.

**Comment by romani** [comment]
Yes, during testing of this Check new implementation we run into this. We used simple approach (any javadoc) only to simplify upgrade from old implementation to new.
But user do need to control excuse comment content by special new property , I propose `requiredJavadocPhrase`.
To avoid usage of javadoc parser (that will result in perfomance problems) we could convert javadoc to single line string(with all html tags .....) and do regexp match. User is responsible for RegExp content.

**Comment by gaurabdg** [comment]
I am on it.

**Comment by romani** [comment]
fix is merged
