### ISSUE TITLE
Split and Organize Checkstyle inputs by Test for checks in header package

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#4365]
subtask of #3891

move / do a copy of all test input files to a separate folder for all checks in header package.
Not any other Check should use new inputs.

**Comment by romani** [comment]
@sharang108, please help us with this issue. 
You can find bunch of example on how to do this (in parent issue there are refercences to commits from others for similar task)

**Comment by sharang108** [comment]
@romani I am on it!

**Comment by rnveach** [comment]
https://github.com/checkstyle/checkstyle/tree/master/src/test/resources/com/puppycrawl/tools/checkstyle/checks/header

There should be no files left in this folder if all tests were done.

**Comment by romani** [comment]
@sharang108 , can you help us to finish this issue ? 
two input files left.

**Comment by sharang108** [comment]
@romani  which files?

**Comment by romani** [comment]
@sharang108 , please open https://github.com/checkstyle/checkstyle/tree/master/src/test/resources/com/puppycrawl/tools/checkstyle/checks/header , in this folder should be no files at all.

**Comment by romani** [comment]
https://github.com/checkstyle/checkstyle/tree/master/src/test/resources/com/puppycrawl/tools/checkstyle/checks/header folder is empty , task is done. Thanks to all participants.

**Comment by rnveach** [comment]
@romani I am re-opening this issue.
One part was done, moving files. What wasn't done was renaming files to be named after their tests.

https://github.com/checkstyle/checkstyle/tree/master/src/test/resources/com/puppycrawl/tools/checkstyle/checks/header/header
`InputRegexpHeader.java` should be named `InputHeaderRegexp.java` or any other variant.
@Kietzmann Please fix it.

I also question the usage of `getConfigPath`. https://github.com/checkstyle/checkstyle/blob/master/src/test/java/com/puppycrawl/tools/checkstyle/checks/header/HeaderCheckTest.java#L64
We are storing extra inputs at https://github.com/checkstyle/checkstyle/tree/master/src/test/resources/com/puppycrawl/tools/checkstyle/configs which is outside the directory of the other inputs.
Shouldn't these files be moved with the other inputs and named accordingly?
@romani Please confirm this point.

**Comment by romani** [comment]
ok, lets finish this

**Comment by romani** [comment]
final fix is provided
