### ISSUE TITLE
recheck that mutationThreshold values are up-to-date 

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#4366]
Please run all of them on your local and recheck that mutationThreshold is biggest possible value to keep build passing
https://github.com/checkstyle/checkstyle/blob/master/pom.xml#L1522
If some values are outdated - please send PR to raise values right now.
In you work each fix should be done together with raising value of mutationThreshold

Execution commands for pitest are at https://github.com/checkstyle/checkstyle/blob/master/shippable.yml

Example:
`mvn -Ppitest-checks-whitespace,no-validations clean verify org.pitest:pitest-maven:mutationCoverage`

**Comment by Nimfadora** [comment]
@romani I've checked that all threshold values are up to date, should I attach some report data to confirm it?

**Comment by romani** [comment]
No need, you will make them 100% during summer.
