### ISSUE TITLE
pitest: create profile for non-checks code 

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#4367]
right now we do have maven profiles only for Checks (check packages),
we do need create one more(or few) profiles to run tests of non-checks code.

Whole our code should be covered by pitest. Pitest should check all packages of code.
No changes for test are required now, we just need profile(s) and strict mutationThreshold value in profiles to fail build if threshold is lowered.

Execution time of profile should not be more then 15-20 min (limitation of CI for execution time of build).

**Comment by rnveach** [comment]
@romani How is this different than Issue #3746 ?
It sounds like both are asking for non-check pitests and not 100% enforcement.

**Comment by romani** [comment]
This issue does not demand 100% mutation coverage - just create profile and enforce what we have now

**Comment by Nimfadora** [comment]
@romani, I found that com.puppycrawl.tools.checkstyle.DefaultContext has no test, should it be included to non-checks profile or ignored?

**Comment by rnveach** [comment]
@Nimfadora IMO, it should be included incase there ever comes a time where we expand it's functionality.

**Comment by romani** [comment]
Ok to add if that is required by smth.

**Comment by Nimfadora** [comment]
@romani, what should I do with grammar package tests, big part of them use checks, for ex. Java7DiamondTest uses MemberNameCheck. Should I add these tests to profiles which include used Check classes? And second question, there are some classes in test dir, like XdocUtil, CheckUtil, should I include them in <targetClasses/> instead of <targetTests/>?

**Comment by Nimfadora** [comment]
@romani, another issue, JavadocParseTreeTest generates 78 mutation units and fails by timeout.

**Comment by Nimfadora** [comment]
@romani, and not all checks are covered by mutation tests, annotation package and those in base package: com.puppycrawl.tools.checkstyle.checks.* . What were the reasons to not include them?

**Comment by rnveach** [comment]
@Nimfadora It was probably just an oversight they were missed as we wish to enforce pitest over whole project.

**Comment by Nimfadora** [comment]
@romani, add profiles for all files except grammars and internal packages, BaseCheckTestSupport, BaseFileSetCheckTestSupport. Last two classes and those in internal package are util classes mostly. Case with grammar package I discribed in comments before.

**Comment by Nimfadora** [comment]
@rnveach, maybe you could answer my questions about grammar and internal packages, and classes mentioned before?

**Comment by rnveach** [comment]
@Nimfadora You didnt ask any questions as there is no `?` in your post so it is unclear what is not a statement.
We should be creating no pitest for the test tier and the grammar package. Everything else should be connected to pitest. Pitest is only for production code in `main` folder.

**Comment by Nimfadora** [comment]
@rnveach, https://github.com/checkstyle/checkstyle/issues/4367#issuecomment-304446210 , here I asked some questions, but you answered them in this comment, thank you.

**Comment by romani** [comment]
all profiles are created
