### ISSUE TITLE
set checkFirstSentence=false, but it doesn't work

### ISSUE THREAD

**Issue by CharkeyQK** [checkstyle/checkstyle#4374]
Using IntelliJ IDEA with CheckStyle-IDEA-5.5.1

Code has comment like this:

```java
/**
 * something to do
 *
 * @param request request
 * @param response response
 * @return void
 * @author charkey
 */
```

CheckStyle:

```xml
<module name="JavadocStyle">
    <property name="checkFirstSentence" value="false"/>
    <property name="checkEmptyJavadoc" value="true"/>
    <property name="checkHtml" value="false"/>
</module>
```

After check this file, msg shows "Javadoc the first sentence should end with a period. "

And I try to remove "JavadocStyle" module config, still got that message output.

Thank you all.

**Comment by rnveach** [comment]
@CharkeyQK Please update post with required reporting from http://checkstyle.sourceforge.net/report_issue.html#How_to_report_a_bug showing you still get violation when module is removed.
`JavadocStyle` is the only one that reports this error. If you don't get it with the CLI, than it sounds like an issue with CheckStyle-IDEA.

**Comment by zolv** [comment]
I know it is an old issue already closed. But recently I came into the same problem and after investigation I found out that the `checkFirstSentence` setting for `JavadocStyle` module is overwritten by [`period` property of `SummaryJavadocCheck` module](https://checkstyle.sourceforge.io/config_javadoc.html#SummaryJavadoc). So to make it work either remove `SummaryJavadocCheck` module entry (then `JavadocStyle` works just fine) or set the `period` value empty:

```
<module name="SummaryJavadocCheck">
    <property name="period" value=""/>
</module>
```

**Comment by romani** [comment]
@zolv , please open new issue, but do not repeat mistake of this issue author and please follow issue template.
