### ISSUE TITLE
Refactor Javadoc AST Tests

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#4381]
Identified at https://github.com/checkstyle/checkstyle/pull/4378 and similar to https://github.com/checkstyle/checkstyle/issues/2396 ,

We should drop creating custom trees in our tests for Javadocs and compare the output printing the tree, see proposal details at #2396 . We do similar comparisons for our Java grammar in `AstRegressionTest` with `verifyAst`.

We should do this conversion for `ParseTreeBuilder`.

**Comment by Vladlis** [comment]
https://github.com/checkstyle/checkstyle/issues/3796 should be done first to avoid double refactoring

**Comment by rnveach** [comment]
It should be noted that when refactoring, some trees in `ParseTreeBuilder` are not in use at all.
Example: 
https://github.com/checkstyle/checkstyle/search?utf8=%E2%9C%93&q=treeAsteriskInJavadocInlineTag&type=

https://github.com/checkstyle/checkstyle/blob/ef112d1868e476219fbff6f4ed8a8e9dc54af3c3/src/test/java/com/puppycrawl/tools/checkstyle/grammars/javadoc/ParseTreeBuilder.java#L4231

It was traced back to b4c351b03d4a9d7dffc9a3502d17a41fb3e440b4 but has no input file connected to it.

**Comment by ps-sp** [comment]
@romani @rnveach @Vladlis 
These tests are for the ANTLR parser we use. If we do things the way we do with `AstRegressionTest` we would be actually verifying the `DetailNodeTreeStringPrinter` and `JavadocDetailNodeParser`. We won't be able to verify the ANTLR parser directly.

We sort of parse javadoc twice. Once with ANTLR and then we process the whole resulting tree and [convert](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/JavadocDetailNodeParser.java#L118-#L120) it to _(or generate)_ a `DetailNode` tree. Right now the javadoc tests to be refactored are verifying the ANTLR parser and rightfully belong to the `JavadocParseTreeTest` class. But if we start verifying the final tree that gets generated then those tests should perhaps belong to `DetailNodeTreeStringPrinterTest`.

I wish that we were able to parse just once and use ANTLR generated tree as it is. I am not sure though if that can be achieved with an efficient design or not. Will have to look into it.

**Comment by rnveach** [comment]
>  we would be actually verifying the DetailNodeTreeStringPrinter and JavadocDetailNodeParser. We won't be able to verify the ANTLR parser directly.

What would we need to verify from the ANTLR parser directly that we can't achieve through the printers?

No one uses the parser directly. All our modules and such rely on the results that come from `JavadocDetailNodeParser`. This is the same with Java's `TreeWalker` and grammar.
The point of these tests is for regression on our grammar, hence the name of `AstRegressionTest`. Even when we do regression tests on javadoc using the new shell script, we use the `-J` option which is the final tree, not the actual ANTLR grammar.

**Comment by ps-sp** [comment]
>This is the same with Java's TreeWalker and grammar

But we don't post process the tree we parse for java. We don't have a parser of our own for java. We just [call](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/TreeWalker.java#L448-#L450) `parser.getAst()` and don't post process the result with our own parser. TreeWalker is just for walking the tree. We walk the same tree we obtain from ANTLR. For javadoc we are not walking the ANTLR generated tree but the `DetailNode` tree we generate from the ANTLR generated Tree.

>What would we need to verify from the ANTLR parser directly that we can't achieve, or is lost, through the printers?

I can't think of anything straightaway. But they are two different _units_ and the post processing involved is heavy. ANTLR tree is not the one that is printed. Again, we generate a `DetailNode` tree from an ANTLR tree and then print it. `DetailNode` is a class that we created and isn't something from ANTLR. So if we change the tests we would be only indirectly testing one unit by directly testing the other. Perhaps it can be logically proven that both indirect and direct testing of ANTLR parser is equivalent, but we don't know that as of yet.

**Comment by rnveach** [comment]
> we don't post process the tree we parse for java
> We walk the same tree we obtain from ANTLR

We do post-processing for comments.
One reason we don't have to do this is because the Java grammar is filled with custom Java code inside the grammar and inside `DetailAST`, which is a slightly bad design. It means the grammar can only be used with the Java language. If we ever switch to ANTLR4 for Java, we will probably have to change to heavier post-processing of the nodes created like Javadoc.

> I can't think of anything straightaway.
> Perhaps it can be logically proven that both ... is equivalent, but we don't know that as of yet

pitest would show us if we are losing important lines covered by tests. Passing pitest with no extra tests would show that the 2 forms of testing are exactly equivalent.
In fact, extra tests that directly and clearly test something special in the `JavadocDetailNodeParser`/grammar would be better. It would make it clearer some specifics we doing during the extra post-processing, like it does at https://github.com/checkstyle/checkstyle/pull/4455#discussion_r122071714 .

**Comment by ps-sp** [comment]
@rnveach fair enough. One more thing, so the tests should remain in `JavadocParseTreeTest` or should be transferred to `DetailNodeTreeStringPrinterTest` ? What do you think ?

**Comment by rnveach** [comment]
> so the tests should remain in JavadocParseTreeTest or should be transferred to DetailNodeTreeStringPrinterTest ?

I don't want to move them to `DetailNodeTreeStringPrinterTest` because these tests are more regression than testing that class. I am fine with them remaining in `JavadocParseTreeTest` for now unless we want to move them to some new class.

**Comment by ps-sp** [comment]
@rnveach There are about 9 files in grammars/javadoc which have no UTs related to them. The will lead to added UTs. May be we can add them in a separate "minor: Added javadoc UTs" commit rather than adding them in this issue by splitting into 2 commits ?

**Comment by rnveach** [comment]
@ps-sp Are they the files I made note of at https://github.com/checkstyle/checkstyle/issues/4381#issuecomment-305951523 ?
I don't think should be minor. IMO, they should all be part of this issue.
1 or 2 commits doesn't bother me.

**Comment by ps-sp** [comment]
@rnveach yes they are. Ok, 2 commits then.

**Comment by ps-sp** [comment]
@rnveach we don't want the input javadoc files to be `.javadoc` instead of `.txt`. There are `.javadoc` input files for a few UTs. But all the `AstRegressionTest` input files are `.txt`

**Comment by rnveach** [comment]
> we don't want the input javadoc files to be .javadoc instead of .txt

I didn't really notice them before. We can put the javadocs into `.javadoc` and put the resulting trees into `.txt`.

**Comment by ps-sp** [comment]
@rnveach ok. Also there seem to be some mismatches in the Input files that were previously not in any UTs. For example look at [this](https://github.com/checkstyle/checkstyle/blob/master/src/test/resources/com/puppycrawl/tools/checkstyle/grammars/javadoc/javadocTags/InputAsteriskInLiteral.txt) , [this](https://github.com/checkstyle/checkstyle/blob/master/src/test/resources/com/puppycrawl/tools/checkstyle/grammars/javadoc/javadocTags/InputAsteriskInJavadocInlineTag.txt) and [this](https://github.com/checkstyle/checkstyle/blob/master/src/test/resources/com/puppycrawl/tools/checkstyle/grammars/javadoc/javadocTags/InputNewlineAndAsteriskInParameters.txt). You can have a look at the trees printed for them [here](https://github.com/ps-sp/checkstyle/commit/0792f8740d2ca6e6b40aa1a2c4f6c396604096b9)

**Comment by romani** [comment]
fix is merged.
