### ISSUE TITLE
Remove strong, wildcard suppressions in configuration

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#4384]
Identified at https://github.com/checkstyle/checkstyle/pull/4378#pullrequestreview-40668750 , 

We have very strong suppressions for the following files at https://github.com/checkstyle/checkstyle/blob/980f9f57b6431b47ff2117b94597c5399807cb2b/config/suppressions.xml#L56-L57 : `JavadocTokenTypes` and `ParseTreeBuilder`.

Suppressing everything means we do no simple validation like import ordering or curly positioning. We should change this to suppress specific checks and the ones that are easy should be fixed and removed.

**Comment by MEZk** [comment]
Should it be a part of [GSoC project](https://github.com/checkstyle/checkstyle/projects/1)?

**Comment by rnveach** [comment]
I don't see this as a very strong connection, but this should be a simple task.

**Comment by romani** [comment]
it is good part of "Practice what you preach".

**Comment by romani** [comment]
analysis of suppression was done at #4985.
After merge of this PR, It is required to fix only JavadocParagraph violations.

**Comment by romani** [comment]
@Nimfadora , PR is merged, please provide a fix for JavadocParagraph.

**Comment by romani** [comment]
JavadocParagraph is fixed.
