### ISSUE TITLE
Add a configurable timeout parameter to checkstyle

### ISSUE THREAD

**Issue by blerner** [checkstyle/checkstyle#4391]
As a stopgap solution for #4390, and a potentially generally useful addition, would it be possible to add some kind of timeout controls to checkstyle, so that users could specify how long they were willing to wait for results? I don't much care whether it's done via command line flag(s) or configuration file properties; whichever is preferable to the checkstyle maintainers & developers is fine.

I see four potential granularities of control: total time for all the tests on all the code, total time for all the tests on a single file, total time for a particular test on all files, and total time for an individual test on an individual file.

This definitely interacts with the other issues I've seen planning on multithreaded support, and indeed might not even be easily doable without that infrastructure.

**Comment by romani** [comment]
user need to use exclude properties to avoid such files.
issue with performance need tobe resolved.

**Comment by blerner** [comment]
Sorry -- the BeforeExecutionExclusionFileFilter doesn't suffice for me.  I'm trying to run the style checker on student-written Java files: I do not know in advance whether any of them will trigger pathological performance in checkstyle or not, so I can't use a filter to exclude them.

Issues with performance need to be resolved, sure.  But that's an open-ended exploration of all the style checks you have, to ensure none of them have corner cases that take an unreasonably long time.  "Normal" Java files probably won't trigger bad behavior, or you'd have noticed it already in your own code.  But student code is, pretty much by definition, not normal.

**Comment by rnveach** [comment]
> that's an open-ended exploration of all the style checks you have

We are very sure that checks are not the issue of execution time. It is parsing of code in ANTLR.
Issue #3727 shows this very clearly as `-j` CLI option doesn't run any checks.
