### ISSUE TITLE
pitest: increase mutation coverage for pitest-checkstyle-api profile to 100%

### ISSUE THREAD

**Issue by Nimfadora** [checkstyle/checkstyle#4394]
We created pitest profiles for non-checks code in #4367 . Currently, we should increase coverage for `pitest-checkstyle-api` profile up to 100%.
This issue is a subtask of #3708 

Also in scope of this task, we should remove exclusion of `com.puppycrawl.tools.checkstyle.api.Check` class from the profile, as it has no methods or fields and does not influence mutation coverage.

Current threshold of `pitest-checkstyle-api` profile: 45

**Comment by romani** [comment]
@Nimfadora ,

from  #5015 .

there is regression:
`
Survived items:target/pit-reports/201708281641/com.puppycrawl.tools.checkstyle.api/SeverityLevelCounter.java.html:<td class='survived'> target/pit-reports/201708281641/com.puppycrawl.tools.checkstyle.api/SeverityLevelCounter.java.html:<td class='covered'><pre><span class='survived'> count.set(0);</span></pre></td></tr>
`

please help us to fix this.

**Comment by romani** [comment]
final fix is mergged
