### ISSUE TITLE
pitest: increase mutation coverage for pitest-checkstyle-utils profile to 100%

### ISSUE THREAD

**Issue by Nimfadora** [checkstyle/checkstyle#4395]
We created pitest profiles for non-checks code in #4367. Currently, we should increase coverage for `pitest-checkstyle-utils` profile up to 100%.
This issue is a subtask of #3708 

Current threshold of `pitest-checkstyle-utils` profile: 40

**Comment by Nimfadora** [comment]
@romani I'm stuck with this package at this stage, please provide assistance on fixing [mutations remained](https://nimfadora.github.io/issue4395.html)

**Comment by romani** [comment]
https://nimfadora.github.io/pr/com.puppycrawl.tools.checkstyle.utils/CheckUtils.java.html

1)
> type.getChildCount(TokenTypes.LITERAL_VOID) > 0

type could have only one `void` so change it to findFirstChild or smth similar from our utils.

2)
> && newNode.getColumnNo() < currentNode.getColumnNo()

please make UT that require this line on custom AST structure. non-functional test.

================

https://nimfadora.github.io/pr/com.puppycrawl.tools.checkstyle.utils/TokenUtils.java.html

3)
remove this line.

===============================================

https://nimfadora.github.io/pr/com.puppycrawl.tools.checkstyle.utils/JavadocUtils.java.html
4)
```
            if (!Modifier.isPublic(field.getModifiers())
                    || field.getType() != Integer.TYPE) {
                continue;
            }
```
this code is required to skip `private static final int RULE_TYPES_OFFSET = 10000;` please make assert that 10000 is not present in result map.

5)
> all cases from `lookForInlineTags` , `getPreviousSibling`, `getTokenName`

please make non functional UTs to cover them.

**Comment by romani** [comment]
last fix is merged

**Comment by romani** [comment]
issue is reopened to fix last missed coverage line

**Comment by romani** [comment]
final fix is merged
