### ISSUE TITLE
pitest: increase mutation coverage for pitest-checkstyle-filters profile to 100%

### ISSUE THREAD

**Issue by Nimfadora** [checkstyle/checkstyle#4396]
We created pitest profiles for non-checks code in #4367. Currently, we should increase coverage for `pitest-checkstyle-filters` profile up to 100%.
This issue is a subtask of #3708

Current threshold of `pitest-checkstyle-filters` profile: 95

**Comment by romani** [comment]
It might be reasonable to split api from filters. Filters are like Checks, their logic is not used by others.
It will help us quickly cover filters as 100% as there is one GSoC project is focused on filter implementation.

from coverage report:

> SuppressionsLoader.java// suppress.setModuleId(modId);

just run loader on config that have module with "id", example - https://github.com/checkstyle/checkstyle/blob/master/config/checkstyle_checks.xml#L57

> SuppressionCommentFilter.java// ..... all cases 

please play through `accept(AuditEvent event)` method to cover them.

> SuppressWithNearbyCommentFilter.java// ..... all cases 

please play through `accept(AuditEvent event)` method to cover them.

**Comment by romani** [comment]
the whole code is covered in this profile.
