### ISSUE TITLE
pitest: increase mutation coverage for pitest-checkstyle-gui profile to 100%

### ISSUE THREAD

**Issue by Nimfadora** [checkstyle/checkstyle#4397]
We created pitest profiles for non-checks code in #4367. Currently, we should increase coverage for `pitest-checkstyle-gui` profile up to 100%.
This issue is a subtask of #3708

Current threshold of `pitest-checkstyle-gui` profile: 30

**Attention**: please postpone gui package coverage to the very end, it does not contain code that all uses use, it is code to ease development of Checkstyle project only, so priority is low.

**Comment by romani** [comment]
coverage of gui code  to fanatic 100% does not make sense and extremely hard.
GUI is not part of code that whole java community use, so quality of it should be a bit less than all other code.
GUI is unlikely very popular since we did AST print in CLI.
