### ISSUE TITLE
pitest: increase mutation coverage for pitest-checkstyle-main profile to 100%

### ISSUE THREAD

**Issue by Nimfadora** [checkstyle/checkstyle#4399]
We created pitest profiles for non-checks code in #4367. Currently, we should increase coverage for `pitest-checkstyle-main` profile up to 100%.
This issue is a subtask of #3708

Current threshold of `pitest-checkstyle-main` profile: 93

**Comment by Nimfadora** [comment]
@romani what should we do with the mutation cases mentioned [here](https://github.com/checkstyle/checkstyle/pull/4660#issue-241449759)

> All other cases are connected to different ways of closing IO streams. I can test them with PowerMock, but as it uses reflection it is in a conflict with [this](https://github.com/checkstyle/checkstyle/blob/master/src/test/java/com/puppycrawl/tools/checkstyle/MainTest.java#L150) Main test. They cannot coexist, one of them fails when I try to fix another.

**Comment by romani** [comment]
> I can test them with PowerMock, but as it uses reflection it is in a conflict with this Main test. They cannot coexist, one of them fails when I try to fix another.

such test exists only for satisfy coverage , I am to change it at any possible way to avoid conflicts. 
I value pitest test more in that case.

**Comment by Nimfadora** [comment]
> such test exists only for satisfy coverage , I am to change it at any possible way to avoid conflicts.
> I value pitest test more in that case.

@romani there are two solutions here: 
1) disable calls to CommonUtils and Closables in pitest main profile
2) remove check of private constructor (decrease cobertura) and use PowerMock to check that Closeables and CommonUtils close streams. (private constructor check and PowerMock could not coexist, as PowerMockRunner somehow makes all private public)

I found work-around with [negation issue](https://github.com/hcoles/pitest/issues/377) : we can simply make two ifs inside one another - that kills all mutations. 

After we decide what to do, I will quickly increase main coverage to real 100.

**Comment by romani** [comment]
> disable calls to CommonUtils and Closables in pitest main profile

only as last resort.

> remove check of private constructor ....  as PowerMockRunner somehow makes all private public

looks like whole problem is due to implementation of `assertUtilsClassHasPrivateConstructor` https://github.com/checkstyle/checkstyle/blob/master/src/test/java/com/puppycrawl/tools/checkstyle/internal/TestUtils.java#L50
please make new argument in this method to skip `if (!Modifier.isPrivate(constructor.getModifiers())) {`
. This argument will be used when Test using PowerMock Runner.
Please try.

> we can simply make two ifs inside one another - that kills all mutations.

ok lets try, there will be violations from Tc and pmd and ..... all of them could be suppressed till pitest resolve the issue.

**Comment by romani** [comment]
Final fix is merged
