### ISSUE TITLE
pitest: increase mutation coverage for pitest-check-header profile to 100%

### ISSUE THREAD

**Issue by Nimfadora** [checkstyle/checkstyle#4401]
We should increase coverage for `pitest-check-heade`r profile up to 100%.
This issue is a subtask of #3708

Current threshold of `pitest-checkstyle-header` profile: 78

**Comment by Nimfadora** [comment]
@romani, in `com.puppycrawl.tools.checkstyle.checks.header.RegexpHeaderCheck#postProcessHeaderLines` there is a line like this: `headerRegexps.clear();`
It seems unnecessary, as I struggled quite a lot of time trying to brake it, and all my attempts failed. It can not be tested either. 
The case is that this line prevents mutation coverage of 100% for this class, as when it is deleted no tests fail. I suggest to delete this line.

**Comment by romani** [comment]
fix is merged
