### ISSUE TITLE
Simple name conflict of Checks from thirdparty checks will cause exception in run time

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#4414]
the same problem as in #4387 

I did ugly fix to make it work as before, without testing, that need to be fixed in this issue.

We will still have the same exception then few Checks from few thirparty jars are in conflict.
We need to give user clear message how to resolve the issue.

**Comment by rnveach** [comment]
@Luolc can you help us finally finish this based on our discussions in previous PR?
We need to finish this and one other issue to do another release and go to CS8 as some GSoC items will require it.

**Comment by romani** [comment]
fix is merged.
@Luolc , thanks a lot for your hard work to resolve issue.
