### ISSUE TITLE
Create XPath tree as clone of DetailAST tree

### ISSUE THREAD

**Issue by MEZk** [checkstyle/checkstyle#4415]
The problem was found in https://github.com/checkstyle/checkstyle/issues/3095 .

Due to the fact that AST tree does not have the root node, we have 2 pseudo-root nodes:
1) PACKAGE_DEF
2) CLASS_DEF

For example,

```java
package my.pack;

public class TestClass {
}
```

```
PACKAGE_DEF -> package [1:0]
|--ANNOTATIONS -> ANNOTATIONS [1:10]
|--DOT -> . [1:10]
|  |--IDENT -> my [1:8]
|  `--IDENT -> pack [1:11]
`--SEMI -> ; [1:15]
CLASS_DEF -> CLASS_DEF [3:0]
|--MODIFIERS -> MODIFIERS [3:0]
|  `--LITERAL_PUBLIC -> public [3:0]
|--LITERAL_CLASS -> class [3:7]
|--IDENT -> TestClass [3:13]
`--OBJBLOCK -> OBJBLOCK [3:23]
    |--LCURLY -> { [3:23]
    `--RCURLY -> } [4:0]
```

As it can be seen from the example, the tree does not have the root. PACKAGE_DEF and CLASS_DEF are siblings. It also can be proven by the following test:

TestAst:
```java
package com.puppycrawl.tools.checkstyle;

public class TestAst {

}

```

```java
@Test
public void testRootAst() throws Exception{
    final FileText text = new FileText(new File("src/test/resources/com/puppycrawl/tools/checkstyle/TestAst.java"),
        System.getProperty("file.encoding", "UTF-8"));
    final FileContents contents = new FileContents(text);

    DetailAST rootAST = TreeWalker.parse(contents);
    
    assertEquals(null, rootAST.getParent());
    assertEquals(null, rootAST.getNextSibling().getParent());
}

```

The test shows that two nodes do not have a parent.

JLS says that
> CompilationUnit is the goal symbol (§2.1) for the syntactic grammar (§2.3) of Java programs.

and

> Starting from a sentence consisting of a single distinguished nonterminal, called the goal symbol, a given context-free grammar specifies a language, namely, the set of possible sequences of terminal symbols that can result from repeatedly replacing any nonterminal in the sequence with a right-hand side of a production for which the nonterminal is the left-hand side.

and finally 

> A syntactic grammar for the Java programming language is given in Chapters 4, 6-10, 14, and 15. This grammar has tokens defined by the lexical grammar as its terminal symbols. It defines a set of productions, starting from the goal symbol CompilationUnit (§7.3), that describe how sequences of tokens can form syntactically correct programs.

Thus, from my point of view, ```compilation unit``` should be the root of the tree. By the way, PMD declares ```compilation unit``` as a root. See https://github.com/pmd/pmd/blob/511c7778c5bc2e8718e7cd3c7fec85937a493315/pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTCompilationUnit.java#L15-L15
 

This issue blocks https://github.com/checkstyle/checkstyle/issues/4369
Saxon framework for Xpath has [NodeInfo](http://www.saxonica.com/html/documentation/javadoc/net/sf/saxon/om/NodeInfo.html) interface which is going to be used in XPath to AST mapper. The interface has the method which is called [getRoot](http://www.saxonica.com/html/documentation/javadoc/net/sf/saxon/om/NodeInfo.html#getRoot()) which should return the root node of the DOM tree. In order to implement the mapper properly we need to have one-to-one correspondence of the DOM tree which will be specified by XPath with AST tree. As AST tree does not have the root node, it will be a problem to refer to the root of the AST tree from Xpath.

**Comment by rnveach** [comment]
I don't see any harm in adding the root node.
Since we are changing the tree structure, this seems like it would have to be for Checkstyle 8.

**Comment by romani** [comment]
@MEZk , please investigate this tokentype - http://checkstyle.sourceforge.net/apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#EOF , name is far from being human friendly. 

can we reuse it ? how it will affect view of queries ?

or should we make new token ? that is light AST update , should not cause breaking compatibilities, but we should avoid AST changes as much as possible.

**Comment by MEZk** [comment]
> name is far from being human friendly.

Yes, should not be used as a root.

> can we reuse it ?

I'm against its usage.

> how it will affect view of queries ?

Before (the whole expression, the root is CLASS_DEF token, class is not in the package)
```
//CLASS_DEF//METHOD_DEF
```

After
```
//EOF//CLASS_DEF//METHOD_DEF
```

However, usage of the root is not required. If we assume that EOF is a root token, then this will be a valid XPath expression:
```
./CLASS_DEF//METHOD_DEF
```

> or should we make new token ?

Why can't we use CompilationUnit. It is already a syntax unit.

**Comment by romani** [comment]
> However, usage of the root is not required. If we assume that EOF is a root token, then this will be a valid XPath expression

in first implementation we could append "//EOF" to user query, to cheat Library that root is present. .... but that is not very good.

> Why can't we use CompilationUnit? It is already a syntax unit.

There only TokenTypes. What is `CompilationUnit` ? what is `syntax unit` ?
If you mean that is syntax structure of java by jdk ...... yes we could , but we will need change grammar in backward compatible way and retest ..... . And we need to deprecate EOF as we substitute it.

Btw, if there were not possible to use this token, so nobody used it, so we can rename it, and make it appear in tree. Can you investigate this approach ?

**Comment by MEZk** [comment]
> in first implementation we could append "//EOF" to user query, to cheat Library that root is present. .... but that is not very good.

user can ommit EOF, however we cannot process the tree without root node with Saxon library.

> Btw, if there were not possible to use this token, so nobody used it, so we can rename it, and make it appear in tree.

This will be the perfect solution. We need to decide whether we should follow JLS and name the rename EOF to COMPILATION_UNIT or use ROOT_NODE as the new name for EOF.

> Can you investigate this approach?

Yes, we can search its usage over GitHub and in Checkstyle source base.

**Comment by timurt** [comment]
> Can you investigate this approach?

`TokenTypes,EOF` is used only inside `ParseTreeTablePresentation.createArtificialTreeRoot` method,
`GeneratedJavaTokenTypes,EOF` is used inside UT and resource java files.

**Comment by romani** [comment]
all usages inside testing could be ignored, we can change anything in our tests easily.

main question is: if user will unlikely use root token in xpath query - no need to make new token "COMPILATION_UNIT", lets reuse EOF.

@MEZk , @timurt , It think users will be lazy to define completely full xpath from root.

**Comment by timurt** [comment]
@MEZk @romani 
As a part of my implementation of 4369, I have added root node.
Inside my root node I have created field `tokenType` and initialized it with `TokenTypes.EOF`
I made `CLASS_DEF` and `PACKAGE_DEF` nodes as two children of my root.

To propose solution, I want to ask, which of the following queries is more right about describing full path
`/CLASS_DEF/OBJBLOCK/`
or
`/EOF/CLASS_DEF/OBJBLOCK/`

**Comment by Vladlis** [comment]
@timurt 
What about `ENUM_DEF` and `INTERFACE_DEF`? Shouldn't they also be children of the root node?

**Comment by timurt** [comment]
@Vladlis 
Yes, you are right. I was testing only usual java class, that's why I said PACKAGE and CLASS_DEF,
for interface it will be PACKAGE and INTERFACE_DEF, for enum PACKAGE and ENUM_DEF

I take the root DetailAst 
`DetailAST result = TreeWalker.parse(contents);`

And then iterating all its siblings and making them children of the Saxon root node

```
if (detailAst != null) {
    DetailAST iterator = detailAst;
    while (iterator != null) {
        final ElementNode child = new ElementNode(this, this, iterator);
        addChild(child);
        iterator = iterator.getNextSibling();
    }
}
```

**Comment by MEZk** [comment]
@romani 

> Inside my root node I have created field tokenType and initialized it with TokenTypes.EOF
I made CLASS_DEF and PACKAGE_DEF nodes as two children of my root. In my implementation I do not use EOF or ROOT keywords in my queries, only /

I'm OK with this temporal solution. It will help as to avoid changes in AST tree structure for now so we will be backward compatible for sure. We just create our own implementation of XPath tree. 

Example:

![tree exaple](https://user-images.githubusercontent.com/7242568/27985675-0303c8c8-63f8-11e7-928a-e84212d53af7.jpg)

**Comment by MEZk** [comment]
@timurt 
To sum up, we do not make changes in AST. Xpath-AST is a kind of clone of DetailAST. It is a wrapper. We can modify it as we need. That is why it is OK to add the root only for Xpath-AST.

**Comment by rnveach** [comment]
@romani Just to summarize issue, are we making `EOF` the root node for the Java tree?

**Comment by romani** [comment]
I do not see a reason to fix anything as part of this issue. 
Who\What will benefit from new root node to be appeared ?
Xpath works fine. 

@MEZk , do we still need this issue ?

**Comment by rnveach** [comment]
@romani Xpath only works because we made some override for no root.
Root node could be beneficial when we print tree. Right now it just shows them listed with no root.
Javadoc has root node.

Even if there isn't much benefit, I think we should still make a root node.

**Comment by romani** [comment]
> Even if there isn't much benefit, I think we should still make a root node.

lets close this issue, as Xpath is ok without root node. If Root node required for just processing it is different issue and we need to find a reason to have it. existence of it could deprecate [beginTree](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/AbstractCheck.java#L145) event ?

No matter what reason we find and approve issue Xpath filter is not reason (it make a copy of AST, so it can do even more that fake root node). 

> Root node could be beneficial when we print tree.

show the prove, nobody care about it, it is just extra level that make no sense to user. Most application that show tree structure in UI, omit root node and show user meaningful content. It could technically exists but it is not required. there should be some other reason.

**Comment by rnveach** [comment]
@romani Ok to close this?
