### ISSUE TITLE
Add token type to LocalizedMessage

### ISSUE THREAD

**Issue by MEZk** [checkstyle/checkstyle#4419]
XPath to AST mapper which will be implemented in the scope of #4369 will help us to find AST node which corresponds the XPath expression starting from the root. When the AST node is found, we need to compare the node with the AST node which causes the violation. If they are equal, the audit event need to be denied. 

For example, if we have the following XPath expression to suppress a violation logged by MethodLengthCheck

```java
//CLASS_DEF//METHOD_DEF[@Text='foo']
```

then the mapper will return the method definition AST node. MethodLengthCheck emits the violation for method ```foo```. We need to log method definition AST node, because we should compare the node with the AST node given by mapper. If both nodes are equal, then audit event (violation) should be denied.  

Thus, in order to suppress the violation by XPath expression we need to have the AST node which causes the violation. However, now the whole information about a violation (lineNo, columnNo, etc) is collected in LocalizedMessage. I propose to rename LocalizedMessage to Violation ann [log](https://github.com/MEZk/checkstyle/blob/154f120d7b71c30ec64f3ef801fb080a24a21c4a/src/main/java/com/puppycrawl/tools/checkstyle/api/AbstractViolationReporter.java#L143-L143) AST everywhere. AST contains all required information (columnNo, lineNo, token type, ets).

**Comment by MEZk** [comment]
@romani @rnveach 
Please, take a look at the issue.

**Comment by rnveach** [comment]
Will xpath suppression support javadoc, as well as Java? If so, you would need both DetailAST and DetailNode.

I agree that the node will be required to attach to LocalizedMessage for violations. FileSets won't need to supply any nodes, so the fields will have to be optional.

@MEZk Instead of passing the AST, can we convert it to something XPath-y and store that in the message so we are not adding new fields for every type of AST we have to store in it?

**Comment by MEZk** [comment]
>  If so, you would need both DetailAST and DetailNode.

In the first implementation I want to work only with AST nodes in order to prove that:
1) We can work with XPath 
2) Users will really use our new suppression model.

> I agree that the node will be required to attach to LocalizedMessage for violations.

From my point of view, LocalizedMessage will become inappropriate name for the class. 

>  Instead of passing the AST, can we convert it to something XPath-y and store that in the message so we are not adding new fields for every type of AST we have to store in it?

No, we cannot. The basic idea is:
1) Store AST-node which causes violation. Lets call it AST1.
2) Starting from root AST node create ElementNode (Element node is a part of Saxon XPath model) in order to apply Saxon-based tree traversal algorithms (searching in tree, iterating, etc).
3) Parse XPath-expression. Find corresponding ElementNode (which actually stores the reference to AST nodes). In this step we find each AST-node in the AST by XPath-node. Lets call the found node AST2.
4) We should check whether AST1 is equal to AST2. Once again, AST1 is a node which we found in the basic AST starting from root by XPath-expression. AST2 is a node which causes the violation. If AST1 is equal to AST2, we deny the AuditEvent.

Based on the sequence of actions mentioned above, we need to have the DetailAST object to work with.

**Comment by rnveach** [comment]
@MEZk It looks like putting `DetailAST` directly into `LocalizedMessage` which is in `api` package might conflict with https://github.com/checkstyle/checkstyle/issues/3417 .

Attachable `DetailAST` might have to be declared as `Object`?

**Comment by timurt** [comment]
@rnveach @MEZk 
Can't we just compare primitive variables like `columnNo`, `lineNo` and etc. If nodes are the same, they will have same values, no?

**Comment by MEZk** [comment]
@timurt 
columnNo, lineNo are not enough. For example,

```java
public class TestClass {
    void method() {
    }
}
```

```
CLASS_DEF -> CLASS_DEF [1:0]
|--MODIFIERS -> MODIFIERS [1:0]
|  `--LITERAL_PUBLIC -> public [1:0]
|--LITERAL_CLASS -> class [1:7]
|--IDENT -> TestClass [1:13]
`--OBJBLOCK -> OBJBLOCK [1:23]
    |--LCURLY -> { [1:23]
    |--METHOD_DEF -> METHOD_DEF [2:4]
    |  |--MODIFIERS -> MODIFIERS [2:4]
    |  |--TYPE -> TYPE [2:4]
    |  |  `--LITERAL_VOID -> void [2:4]
    |  |--IDENT -> method [2:9]
    |  |--LPAREN -> ( [2:15]
    |  |--PARAMETERS -> PARAMETERS [2:16]
    |  |--RPAREN -> ) [2:16]
    |  `--SLIST -> { [2:18]
    |      `--RCURLY -> } [3:4]
    `--RCURLY -> } [4:0]
```

As it can be seen there are 4 tokents which have the same column and raw number:
```
    |--METHOD_DEF -> METHOD_DEF [2:4]
    |  |--MODIFIERS -> MODIFIERS [2:4]
    |  |--TYPE -> TYPE [2:4]
    |  |  `--LITERAL_VOID -> void [2:4]
```

However, they have the different token types.

 We may identify the node by columnNo, lineNo, tokenType.

**Comment by rnveach** [comment]
> Can't we just compare primitive variables like columnNo, lineNo and etc. 
> We may identify the node by columnNo, lineNo, tokenType.

Please read https://github.com/checkstyle/checkstyle/issues/3417#issuecomment-311135040 .

**Comment by MEZk** [comment]
@rnveach @timurt 
We have a SKype conversation with @romani and decided that we don't need the whole DetailAST object to be part of LocalizedMessage. LocalizedMessage already has lineNo and columnNo. We need to put token  type to the class. AST node could be identified by lineNo, columnNo and token type.

**Comment by MEZk** [comment]
@timurt
In summary, we should add token type to LocalizedMessage. LocalizedMessage object should contain token type, line, and column number. This information should be enough for AST filters to find the AST node in the tree (by line, column number, and token type). So, in the scope of this issue LocalizedMessage should be updated to have token type and a new constructor which receives token type and other arguments required to form the object. It is not expected to update checks, or other logic. All changes have to be done only in LocalizedMessage.

**Comment by romani** [comment]
fix is merged
