### ISSUE TITLE
Split and Organize Checkstyle inputs by Test for checks in modifier package

### ISSUE THREAD

**Issue by subkrish** [checkstyle/checkstyle#4431]
subtask of #3891

Move / Make a copy of all test input files to a separate folder for all checks in modifier package.
Not any other Check should use new inputs.

**Comment by subkrish** [comment]
I'm on it. 1 test and its inputs per PR.

**Comment by rnveach** [comment]
@subkrish It looks like we have 1 input leftover. https://github.com/checkstyle/checkstyle/tree/a8874c6cf3d593bf8c975d6b116e2d1f9cbf3aef/src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier
If it is not used by anything, please delete it.

**Comment by rnveach** [comment]
Fixes have been merged
