### ISSUE TITLE
Split and Organize Checkstyle inputs by Test for checks in imports package

### ISSUE THREAD

**Issue by subkrish** [checkstyle/checkstyle#4437]
subtask of #3891

Move / Make a copy of all test input files to a separate folder for all checks in imports package.
Not any other Check should use new inputs.

**Comment by subkrish** [comment]
I'm on it. 1 test and its inputs per PR.

**Comment by subkrish** [comment]
@romani @rnveach I was thinking about changing the input file for `UnusedImportsCheckTest`, so that once all the checks are arranged the extra files can be deleted.

I was planning to move `InputImportBug` to 'unusedimports' and change the test file a little accordingly.

**Comment by romani** [comment]
> I was planning to move InputImportBug to 'unusedimports' and change the test file a little accordingly.

lets not change content in scope of this issue. Lets finish just moving and then do some changes to content.

> once all the checks are arranged the extra files can be deleted.

if we have extra input files that nobody use - please remove them in separate PR.

**Comment by subkrish** [comment]
> lets not change content in scope of this issue. Lets finish just moving and then do some changes > to content.

Should I just make PR stating a minor change in input files after this issue is closed?

**Comment by romani** [comment]
@subkrish , yes, separate PR.

**Comment by romani** [comment]
there 4 files left:
```
$ ls --group-directories-first | grep "\."
import-control_one-re.xml
import-control_one.xml
InputAvoidStaticImportNestedClass.java
InputImportBug.java
```

**Comment by subkrish** [comment]
@romani  Yes there are 4 files left. I will check if any files are using them or delete them in the final PR for this issue. If any files are using some inputs because of which I would need to alter the input file I will handle them in another minor PR outside this issue.

**Comment by subkrish** [comment]
@romani @rnveach The 4 files are used in different places. 

> import-control_one.xml and import-control_one-re.xml

Used by CheckerTest at https://github.com/checkstyle/checkstyle/blob/master/src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java#L683 and at https://github.com/checkstyle/checkstyle/blob/master/src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java#L711.

> InputAvoidStaticImportNestedClass.java

Used by InputAvoidStaticImportDefault.java and AvoidStaticImportCheckTest.java.

> InputImportBug.java

Used by InputImportOrder_WildcardUnspecified.java, InputUnusedImports.java, RedundantImportCheckTest.java and UnusedImportsCheckTest.java

They are accessed from that directory. Should I just create a 'minor' PR outside this issue and make the necessary changes in the test files or the input files or should it be done in this issue itself?

**Comment by romani** [comment]
In scope of this issue please

**Comment by rnveach** [comment]
@subkrish @romani Please confirm all work is done.

**Comment by subkrish** [comment]
@rnveach @romani Loos like all the files have been arranged and no files are left outside the subdirectory folders.

**Comment by romani** [comment]
issue is done.
```
$ ls 
avoidstarimport    customimportorder  importcontrol        importorder      unusedimports
avoidstaticimport  illegalimport      importcontrolloader  redundantimport
```

@subkrish , thanks a lot for your contribution.
