### ISSUE TITLE
google_checks.xml - please remove <property name="severity" value="warning"/>

### ISSUE THREAD

**Issue by jjYBdx4IL** [checkstyle/checkstyle#4452]
That setting is incoherent with sun_checks.xml and cost me a ton of time to find out what's the problem when trying to use it with maven-checkstyle-plugin.

TY!

**Comment by MEZk** [comment]
@jjYBdx4IL 
Please, report the problem as described at http://checkstyle.sourceforge.net/report_issue.html

**Comment by jjYBdx4IL** [comment]
maven-checkstyle-plugin ignores warnings reported by checkstyle. that severity level does not work with it.

**Comment by romani** [comment]
default severity is error - http://checkstyle.sourceforge.net/config.html#Checker
We do not that demanding by default in this files. Google config also has warning by default to let user continue development if small issues appear in code and address them when they have time. If some group of user need to fail a build - they need to override this value.

**Comment by jjYBdx4IL** [comment]
I found that maven-checkstyle-plugin has a parameter to set the threshold level for failure, though it's still inconsistent: either it is in violation of style rules or not. How those violations get treated shouldn't be part of checkstyle tbh.

**Comment by romani** [comment]
>  though it's still inconsistent: either it is in violation of style rules or not. How those violations get treated shouldn't be part of checkstyle tbh.

No.
user can define himself what he care about (set of Rules/Checks), user can define severity up to his quality rules. We will never make config that is good for all and for all purposes. All use Google config as start point and disable or make more strict some parts of it.

**Comment by aaronkavlie-wf** [comment]
This also cost me a lot of time; removing this makes sense to me for a couple of reasons:

- `sun_checks.xml` does not have severity set to `"error"`; I don't see why `google_checks.xml` should differ
- This severity setting hides the number of Checkstyle errors in output of a run of `mvn checkstyle` goals, which is one of the most useful pieces of output

**Comment by romani** [comment]
If somebody this the same please keep complaining with reasons

**Comment by anandwana001** [comment]
How to modify the severityLevel in command line?
Complete question here - https://stackoverflow.com/questions/64815801/checkstyle-command-line-change-property

**Comment by romani** [comment]
There is no way to do this as severity could be defined in each module of same config.
You need to use java system variable in config and provide value in command line.
Example at https://checkstyle.org/config.html#Properties
