### ISSUE TITLE
Add FinalParameters option to ignore primitive types

### ISSUE THREAD

**Issue by todd-richmond** [checkstyle/checkstyle#446]
It is common in Java to modify method parameters that are primitive types and not class references. For example, an int -1 value for a param called "length" is often used to denote "entire object length". The method then modifies "length" to object.size() and continues. boolean negations are also somewhat common

This is a request to have an option to the FinalParameters validation to ignore primitive types so that class references are still a warning and code like this passes

class Final {
    Final(final String s, int i) {
        if (i == -1)
            i = s.length();
        ...
    }
}

**Comment by mstup** [comment]
Could be java.lang.String added as option as well, but not only primitive types ?

**Comment by romani** [comment]
@mstup , please create new issue.
