### ISSUE TITLE
Rename LocalizedMessage to Violation

### ISSUE THREAD

**Issue by MEZk** [checkstyle/checkstyle#4465]
Based on https://github.com/checkstyle/checkstyle/issues/4419, AST node which caused a violation should be a part of LocalizedMessage. LocalizedMessage will become the class which stores all information about a violation. LocalizedMessage is an inappropriate name for the class. From my point of view, we need to rename the class to CheckstyleViolation.

**Comment by MEZk** [comment]
@romani @rnveach 
What do you thing about this change?

**Comment by rnveach** [comment]
> Class 'LocalizedMessages' should also be renamed 

See https://github.com/checkstyle/checkstyle/issues/3545 .

**Comment by MEZk** [comment]
@rnveach 
Ok, agree. with #3545.

**Comment by romani** [comment]
What about more simple name "Violation" ? 
as all in our project about checkstyle.

**Comment by romani** [comment]
If you agree please fix title and put approved label on issue

**Comment by MEZk** [comment]
@romani 
I agree.

**Comment by AkMo3** [comment]
I am on it

**Comment by romani** [comment]
fix is merged.
