### ISSUE TITLE
Property illegalClasses in module IllegalImport not implemented?!

### ISSUE THREAD

**Issue by funfried** [checkstyle/checkstyle#4467]
When I'm trying to configure illegalClasses in the IllegalImport module, maven tells me that the property illegalClasses does not exist for that module, as soon as I switch to illegalPkgs it works.

Is this not implemented (, yet)?

```
<module name="IllegalImport">
  <property name="illegalPkgs" value="java.util.logging, org.apache.logging.log4j, org.apache.log4j"/>
</module>
```

```
<module name="IllegalImport">
  <property name="illegalClasses" value="javax.ws.rs.GET, javax.ws.rs.PUT, javax.ws.rs.POST, javax.ws.rs.DELETE, javax.ws.rs.QueryParam, javax.ws.rs.PathParam, javax.ws.rs.Produces, javax.ws.rs.Consumes, javax.ws.rs.core.MediaType, javax.ws.rs.core.Response"/>
</module>
```

> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check (checkstyle) on project [PROJECT_NAME]: Failed during checkstyle configuration: cannot initialize module TreeWalker - Property 'illegalClasses' in module IllegalImport does not exist, please check the documentation -> [Help 1]

**Comment by rnveach** [comment]
@funfried Confirm the version of checkstyle you are using. [This was added in version 7.8](http://checkstyle.sourceforge.net/releasenotes.html#Release_7.8). 

If you still have issues, see http://checkstyle.sourceforge.net/report_issue.html#How_to_report_a_bug .

**Comment by rnveach** [comment]
> please check the documentation

@romani This is a common issue and documentation doesn't specify version the property/module was added.
Should we expand xdoc for this and place that it could be a version issue in the error message?

**Comment by romani** [comment]
It would be good to have `since` version point in xdoc.
I think we already discussed this a lot of times, but updating whole documentation is huge work to fill it for all properties of all Checks.
`since` is required for Module and for all properties of module.

**Comment by rnveach** [comment]
@romani It could be partially automated if we have all release jars. For each module and property, create a simple configuration and run it against all versions of the JAR. First one to not fail with unknown module/property, is the version it was added. If none fail, than we must not have old enough JARs. I don't expect we renamed modules/properties very often. Old modules/properties that we have removed shouldn't matter anymore, so no need to document them.

I will look into this.

**Comment by romani** [comment]
We should create new issue for since introduction.
This issue is closed as nothing we can do, user need to use custom checkstyle version in his pom https://maven.apache.org/plugins/maven-checkstyle-plugin/examples/upgrading-checkstyle.html

**Comment by funfried** [comment]
@rnveach My bad, I suggested that the newest maven checkstyle plugin also uses the newest checkstyle version, but regarding to the checkstyle maven plugin site it's version 6.11.2.
@romani Thanks for the link, I will update to a newer version
