### ISSUE TITLE
Add since version to Checkstyle documentation

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#4475]
Taken from https://github.com/checkstyle/checkstyle/issues/4467#issuecomment-309448377 ,

Users are always trying to add new modules/properties before they are even released or with older versions of Checkstyle.
We should add a new column in our xdocs, `since` and display what version of checkstyle the property was added.

> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check (checkstyle) on project [PROJECT_NAME]: Failed during checkstyle configuration: cannot initialize module TreeWalker - Property 'illegalClasses' in module IllegalImport does not exist, please check the documentation -> [Help 1]

This message and any similar message should also be expanded to tell the user to check/compare their version they are using.

**Comment by MEZk** [comment]
@rnveach 
1) The new column in xdoc should be verified by the UT. I think that we should also require to put the version to Javadoc. For example, as [Spring does](https://docs.spring.io/spring/docs/current/javadoc-api/). For this purpose we can use ```@since``` tag.
2) Existing xdoc and javadoc should be updated as well, I guess.

**Comment by rnveach** [comment]
Here is the little utility I made to find the versions of CS that support a specific module/property.
https://github.com/rnveach/checkstyle/commits/version_regression

Here is the results of the run with debug on: http://rveach.no-ip.org/checkstyle/version output with debug.zip
Here is the results without debug: http://rveach.no-ip.org/checkstyle/version output.zip
They show all modules, their properties, and what versions they were found in (sorted).

It scanned versions between 5.7 and 7.8.2 (47 versions in total).
I had to drop version 6.7 from the scan, because it had a bug with exceptions. It never displayed them, so it was impossible to tell the cause of any failures.
Oddly the versions between 6.12 and 6.14.1 kept getting random, unexplained timeout issues. This happened 174 times, out of 73k+ runs. 
`severity` properties aren't reliable for testing if the module exists because an exception happens first in `ConfigurationLoader` before we can even get to trying to instantiate the module and populate the property. Assigning a true value for severity could alleviate this issue in the program. It seems to be the only property that has this behavior this.

Let me know if you think we should expand more before 5.7 and I will try to create all JARs for them to run on.

> The new column in xdoc should be verified by the UT. 

I plan this.

> I think that we should also require to put the version to Javadoc. 

I think we should create a new check for this if one doesn't exist. It will probably be made for GSoC.

**Comment by MEZk** [comment]
@rnveach 
> I think we should create a new check for this if one doesn't exist. It will probably be made for GSoC.

Probably we could use [WriteTag](http://checkstyle.sourceforge.net/config_javadoc.html#WriteTag), but it does not support class fields and getters, setters.

**Comment by romani** [comment]
Please avoid usage of WriteTag, it is badly designed and will be reimplemented or even completely removed, we should have an issue on it already

**Comment by romani** [comment]
> Let me know if you think we should expand more before 5.7

I would be ideal, but I do not think it is reasonable.
the most recent updates are at http://checkstyle.sourceforge.net/releasenotes.html [5.8-.....)
in `since` we can define "5.8 or early"

FYI. I keep in web hosting all previous web sites, for all recent versions [5.8-.....) , I had a  dream to make some update in web site and allow users to look at previous version websites for documentation.
If smb want to help with this and know how to make it conveniently for users and for us to support, let me know and probably we can make issue on this.

**Comment by rnveach** [comment]
> > Let me know if you think we should expand more before 5.7

> It would be ideal

Currently the process needs `all` jars. Running with non-all JAR would be a little complicated right now to manually include all dependencies.

5.4 to 5.6 can't be built from source. 
`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.0-beta-3:site (gen-site) on project checkstyle: Execution gen-site of goal org.apache.maven.plugins:maven-site-plugin:3.0-beta-3:site failed: A required class was missing while executing org.apache.maven.plugins:maven-site-plugin:3.0-beta-3:site: org/sonatype/aether/graph/DependencyFilter`

5.3 was built from source with minor changes. I will examine for differences.

5.0 to 5.2 don't exist as a tag.
4.3 to 4.4 doesn't package correctly from source as is. Empty jar is created.
4.2 has no POM.

**Comment by romani** [comment]
No need to go below 5.0 , as it was major update, I doubt that smb use us below 5.0 .

**Comment by rnveach** [comment]
I updated the extract files with regression all the way back to 3.1.
3.0 doesn't have severity to ignore violations produced by check.
2.X doesn't support configuration files, doesn't have separate checks, and must be configured through system properties.

I will begin making the PR.

**Comment by romani** [comment]
fix is merged
