### ISSUE TITLE
maven-checkstyle-plugin doesn't work when bind maven lifecycle

### ISSUE THREAD

**Issue by Untweet** [checkstyle/checkstyle#4480]
I don't know why this happened。When I  execute “checkstyle:check“ ,it's ok。But when binding to the   maven lifecycle,it's doesn't work。Nothing to console.
`<plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-checkstyle-plugin</artifactId>
                    <version>2.17</version>
                    <configuration>
                        <includeTestSourceDirectory>true</includeTestSourceDirectory>
                        <configLocation>${basedir}/my_cs.xml</configLocation>
                    </configuration>
                    <executions>
                        <execution>
                            <id>checkstyle-check</id>
                            <goals>
                                <goal>check</goal>
                            </goals>
                            <phase>validate</phase>
                            <configuration>
                                <violationSeverity>error</violationSeverity>
                                <consoleOutput>true</consoleOutput>
                                <failOnViolation>true</failOnViolation>
                                <failsOnError>true</failsOnError>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>`

**Comment by romani** [comment]
You need to report this issue to checkstyle maven plugin project https://issues.apache.org/jira/projects/MCHECKSTYLE , there might be already such issue , sounds like I saw this before.

In this repo we accept issues that could be reproduced by our CLI http://checkstyle.sourceforge.net/cmdline.html .

Issue report should follow strict format http://checkstyle.sourceforge.net/report_issue.html#How_to_report_a_bug
