### ISSUE TITLE
How to extend/override an existing configuration (sun, google)

### ISSUE THREAD

**Issue by binkley** [checkstyle/checkstyle#4484]
I'd like to slightly modify the existing `sun_checks.xml` without copying it into my project.  This way I'd pick up improvements in newer version of checkstyle for Sun style (or Google as well), and only keep my modifications.

In particular, I'd like to set `NewLineAtEndOfFile` property `lineSeparator` to `lf` rather than use the system ending.  The code base uses UNIX endings regardless of developer platform.

Perhaps this is a limitation of the maven plugin, and not in checkstyle?  Trying to provide configuration of both `configLocation` and `checkstyleRules` (inline config in `pom.xml`) is not supported.

Any suggestions would be appreciated!

**Comment by rnveach** [comment]
> I'd like to slightly modify the existing sun_checks.xml without copying it into my project. 

This is not possible right now. You must physically copy the file right now and make changes as you wish.

There was a discussion of providing a way to allow this at https://github.com/checkstyle/checkstyle/issues/2873 , but it hasn't gone anywhere.

**Comment by romani** [comment]
@binkley , 

> I'd like to slightly modify the existing sun_checks.xml

just FYI, this config is not complete coverage of sun code convention. It is some state that might be very similar. Detailed coverage http://checkstyle.sourceforge.net/sun_style.html is not done yet.
We have good coverage only for google style guide - http://checkstyle.sourceforge.net/google_style.html
