### ISSUE TITLE
Split and Organize Checkstyle inputs by Test for checks in 'indentation' package

### ISSUE THREAD

**Issue by subkrish** [checkstyle/checkstyle#4538]
subtask of #3891

Move / Make a copy of all test input files to a separate folder for all checks in 'indentation' package.
Not any other Check should use new inputs.

**Comment by subkrish** [comment]
I'm on it. 1 test and its inputs per PR.

**Comment by rnveach** [comment]
Still some files left at https://github.com/checkstyle/checkstyle/tree/master/src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation

**Comment by subkrish** [comment]
@romani @rnveach I think with this last PR the issue can be closed once the PR is reviewed and merged.

**Comment by rnveach** [comment]
Fixes were merged
