### ISSUE TITLE
Can't resolve systemId of configuration file

### ISSUE THREAD

**Issue by mebigfatguy** [checkstyle/checkstyle#4569]
running the ant version of checkstyle, it produces the following output

resolving systemId: http://www.puppycrawl.com/dtds/configuration_1_3.dtd
could not resolve systemId

and then throws exceptions, like

Caused by: org.xml.sax.SAXParseException; systemId: file:/home/dave/dev/acme/acme_platform-2.0/checkstyle/acme_checkstyle.xml; lineNumber: 6; columnNumber: 24; Unexpected element "{}module" {antlib:org.apache.tools.ant}module

and seemingly just stalls there ad. infinitum.

Any ideas what i'm doing wrong?

config like
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module PUBLIC
    "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
    "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
	<module name="FileTabCharacter"/>
	<module name="UniqueProperties"/>
</module>
```

**Comment by rnveach** [comment]
> "http://www.puppycrawl.com/dtds/configuration_1_3.dtd"

Try `"http://checkstyle.sourceforge.net/dtds/configuration_1_3.dtd"`.
https://github.com/checkstyle/checkstyle/blob/master/config/checkstyle_checks.xml#L4

**Comment by mebigfatguy** [comment]
same issue

resolving systemId: http://checkstyle.sourceforge.net/dtds/configuration_1_3.dtd
could not resolve systemId

**Comment by romani** [comment]
@mebigfatguy , can you make simple project on github to let us reproduce the  problem  ?

**Comment by mebigfatguy** [comment]
Ok, i made a simple project, and what i've learned is that there is nothing wrong with my checkstyle configuration file, nor the ant task to run it with. The problem therefore must have something to do with the set of files i'm running it on, as it works perfectly fine with a bogus one file src set. The set i'm running on is 20K plus files, where the systemId problem arises. Not sure why that should matter, but i will cut down my src code set and see if anything shakes out.

**Comment by rnveach** [comment]
@mebigfatguy Can you atleast update your first post with the full stacktrace?

**Comment by romani** [comment]
@mebigfatguy, please use our CLI http://checkstyle.sourceforge.net/cmdline.html#Download_and_Run to run over your sources to see is it ANT related issue or pure checkstyle issue.

**Comment by romani** [comment]
if no reproduce steps provided till end of July 2017, we will close this issue.
