### ISSUE TITLE
remove JUnitTestCase from Checkstyle

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#457]
details https://github.com/checkstyle/checkstyle/pull/431,
as Check does not care of class it is validating - it is useless and should be removed.

**Comment by uhafner** [comment]
Shouldn't a breaking change made visible by updating the major version (and not the minor version)? See: http://semver.org/

**Comment by romani** [comment]
unfortunately almost any change in checkstyle is braking for some extend.

I decided to keep major version as signal for major changes/braking in API (usually all plugins are mostly affected by that). Unfortunately almost all changes in Checks are braking for users configurations or expected behaviour - there will be a lot of such brakes, we have huge technical debt :( that have to be resolved now.

I recommend to follow our new feeds, and review release notes - http://checkstyle.sourceforge.net/releasenotes.html there try to describe all brakes in compatibility.

Sorry for caused inconvenience.
