### ISSUE TITLE
Split and Organize Checkstyle inputs by Test for checks in 'metrics' package 

### ISSUE THREAD

**Issue by subkrish** [checkstyle/checkstyle#4575]
subtask of #3891

Move / Make a copy of all test input files to a separate folder for all checks in 'metrics' package.
Not any other Check should use new inputs.

**Comment by subkrish** [comment]
I'm on it. 1 test and its inputs per PR.

**Comment by romani** [comment]
folder is empty https://github.com/checkstyle/checkstyle/tree/master/src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics

issue is done.
