### ISSUE TITLE
Reorganize token methods of all Checks

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#4581]
Broken off from https://github.com/checkstyle/checkstyle/issues/605 ,

> Acceptable >= Default >= Required

As explained from gitter:
> getAcceptableTokens should call getRequiredTokens
getRequiredTokens should call for return new int[] {TokenTypes.BLOCK_COMMENT_BEGIN };
all other call getRequiredTokens

This change should be done to both Checkstyle and Sevntu on all checks.

**Comment by subkrish** [comment]
@rnveach 

> getAcceptableTokens should call getRequiredTokens
getRequiredTokens should call for return new int[] {TokenTypes.BLOCK_COMMENT_BEGIN };
all other call getRequiredTokens

Could you please elaborate a little on this?

**Comment by romani** [comment]
@subkrish ,

look at commit https://github.com/checkstyle/checkstyle/commit/dfa3cee94273bf210acc39c3910a5b936f9be42f
for changes like:
```
+    @Override
+    public final int[] getAcceptableTokens() {
+        return getDefaultTokens();
+    }
+
+    @Override
+    public final int[] getRequiredTokens() {
+        return getDefaultTokens();
+    }
```

code should be like:
```
    @Override
    public final int[] getDefaultTokens() {
        return getRequiredTokens();
    }

    @Override
    public final int[] getAcceptableTokens() {
        return getRequiredTokens();
    }

    @Override
    public final int[] getRequiredTokens() {
        return new int[] {.......................};
    }
```

**Comment by subkrish** [comment]
@romani @rnveach I am on it.

**Comment by subkrish** [comment]
@rnveach @romani 
```
    @Override
    public int[] getDefaultTokens() {
        return new int[] {
            TokenTypes.DOT,
            TokenTypes.COMMA,
        };
    }

    @Override
    public int[] getAcceptableTokens() {
        return new int[] {
            TokenTypes.DOT,
            TokenTypes.COMMA,
            TokenTypes.SEMI,
            TokenTypes.ELLIPSIS,
            TokenTypes.AT,
            TokenTypes.LPAREN,
            TokenTypes.RPAREN,
            TokenTypes.ARRAY_DECLARATOR,
            TokenTypes.RBRACK,
            TokenTypes.METHOD_REF,
        };
    }

    @Override
    public int[] getRequiredTokens() {
        return CommonUtils.EMPTY_INT_ARRAY;
    }
```
How do you suggest altering this kind of set up?

**Comment by romani** [comment]
@subkrish , please skip such Checks. If Required tokens are empty, no valuable refactoring could happen. We should not change logic of Check.

**Comment by romani** [comment]
@subkrish , do you still have smth to contribute in this issue ?

**Comment by subkrish** [comment]
@romani As far as I am concerned the work on this issue is done but there are still some files that have to be changed. But upon changing it is causing it to lose mutation coverage. So any file that causes this has not been changed. I do not know how to go about such issues.

**Comment by rnveach** [comment]
> upon changing it is causing it to lose mutation coverage
> I do not know how to go about such issues.

@subkrish It depends on the missing mutation, but since this is all revolving around the token methods, all you probably need to do is add a test to verify their values.
Example: https://github.com/checkstyle/checkstyle/blob/master/src/test/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationOnSameLineCheckTest.java#L47-L69

If you build the mutation report when you have problems, we can guide you.

**Comment by romani** [comment]
Please provide list of Checks that still need to updated.
Please share a pitest report for them , and we will guide you

**Comment by subkrish** [comment]
@romani @rnveach 

Sorry I'm coming back to this after a long time. But I finally got back to working on this issue. I generated the report for the `naming` checks.

Report: [https://subkrish.github.io/](url)

So based on this, how do I move forward?

**Comment by rnveach** [comment]
https://subkrish.github.io/com.puppycrawl.tools.checkstyle.checks.naming/InterfaceTypeParameterNameCheck.java.html#org.pitest.mutationtest.report.html.SourceFile@70a9cdf8_65
https://subkrish.github.io/com.puppycrawl.tools.checkstyle.checks.naming/LocalVariableNameCheck.java.html#org.pitest.mutationtest.report.html.SourceFile@178c5f0e_105
https://subkrish.github.io/com.puppycrawl.tools.checkstyle.checks.naming/MethodTypeParameterNameCheck.java.html#org.pitest.mutationtest.report.html.SourceFile@432e1b90_65

@subkrish Like report suggests, you must write a test that verifies the contents of `getAcceptableTokens`.

**Comment by rnveach** [comment]
@subkrish Please confirm all methods are done in all checks.

**Comment by subkrish** [comment]
@rnveach @romani 

Yes, I checked to make sure all methods have been changed in all checks keeping in mind the ones @romani asked me not to change (https://github.com/checkstyle/checkstyle/issues/4581#issuecomment-336298979) in these type of checks https://github.com/checkstyle/checkstyle/issues/4581#issuecomment-335508029.

This issue can be closed.

**Comment by rnveach** [comment]
Thanks.
