### ISSUE TITLE
Restore wercker CIs that have custom Checks

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#4582]
Broken off from #605 in commit 9135ea36c3d58dcf3cab24e680cff5d99e0f3a35 ,

3 wercker CIs had to be disabled to pass the build. We need to send PRs to them to be able to restore them to usage in our CI.

1) NoErrorTest - XWiki 
2) NoErrorTest - Hibernate Search
3) NoErrorTest - checkstyle's sevntu

**Comment by rnveach** [comment]
Testing changes in xwiki gave me this error:
> [WARNING] Rule 0: org.apache.maven.plugins.enforcer.RequireUpperBoundDeps failed with message:
Failed while enforcing RequireUpperBoundDeps. The error(s) are [
Require upper bound dependencies error for com.google.guava:guava:20.0 paths to dependency are:
+-org.xwiki.commons:xwiki-commons-tool-verification-resources:9.6-SNAPSHOT
  +-com.puppycrawl.tools:checkstyle:8.0-SNAPSHOT
    +-com.google.guava:guava:20.0 (managed) <-- com.google.guava:guava:22.0
and
+-org.xwiki.commons:xwiki-commons-tool-verification-resources:9.6-SNAPSHOT
  +-com.puppycrawl.tools:checkstyle:8.0-SNAPSHOT
    +-com.google.guava:guava:20.0

**Comment by rnveach** [comment]
PR to xwiki is created. https://github.com/xwiki/xwiki-commons/pull/17
We require more changes to their POM to restore regression.

**Comment by rnveach** [comment]
From xwiki:
> The issue with Guava can be followed at https://jira.xwiki.org/browse/XCOMMONS-1155.

**Comment by rnveach** [comment]
I stated new PR for xwiki's POM: https://github.com/xwiki/xwiki-commons/pull/18

**Comment by romani** [comment]
fix is merged
