### ISSUE TITLE
Split and Organize Checkstyle inputs by Test for checks in 'regexp' package 

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#4585]
subtask of #3891

Move / Make a copy of all test input files to a separate folder for all checks in 'regexp' package.
Not any other Check should use new inputs.

There are a lot of other issues/commit that named as "Split and Organize Checkstyle inputs ..."  , you can find example of what to do there.

all files should be in subfolders on completion - https://github.com/checkstyle/checkstyle/tree/master/src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp

**Comment by romani** [comment]
pre-assigned to Tarun from https://groups.google.com/forum/#!topic/checkstyle-devel/z7amqo3n9O4

**Comment by TarunISCO** [comment]
I am on it.

**Comment by romani** [comment]
@Kietzmann , thanks a lot for updates , there 3 files left in folder.

**Comment by romani** [comment]
final fix is merged.
@Kietzmann , thanks a lot !
