### ISSUE TITLE
Split and Organize Checkstyle inputs by Test for checks in 'javadoc' package 

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#4586]
subtask of #3891

Move / Make a copy of all test input files to a separate folder for all checks in 'javadoc' package.
Not any other Check should use new inputs.

There are a lot of other issues/commit that named as "Split and Organize Checkstyle inputs ..." , you can find example of what to do there.

All files should be in subfolders on completion - https://github.com/checkstyle/checkstyle/tree/master/src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc

**Comment by djydewang** [comment]
Please assign me this issue.

**Comment by romani** [comment]
ok you got it.

**Comment by djydewang** [comment]
I have finished all task except when I test JavadocMethodcheckTest.java with InputJavadocMethodTags.java. It's Failure:
`org.junit.ComparisonFailure: error message 10 expected:<...docMethodTags.java:3[20:9: 缺少 Javadoc] 。> but was:<...docMethodTags.java:3[3: 需要一个 Javadoc注释 @return] 。>
`

**Comment by djydewang** [comment]
@romani I have finished all task except when I test [JavadocMethodCheckTest.java](https://github.com/checkstyle/checkstyle/blob/master/src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheckTest.java) with [InputJavadocMethodTags.java(InputTags.java)](https://github.com/checkstyle/checkstyle/blob/master/src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/InputTags.java) This is Failure:
org.junit.ComparisonFailure: error message 10 expected:<...docMethodTags.java:3[20:9: 缺少 Javadoc] 。> but was:<...docMethodTags.java:3[3: 需要一个 Javadoc注释 @return] 。>
I find actual is really different from expect when I debug it.

**Comment by djydewang** [comment]
@romani I have finished all task except when I test [JavadocMethodCheckTest.java](https://github.com/checkstyle/checkstyle/blob/master/src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheckTest.java) with [InputJavadocMethodTags.java(InputTags.java)](https://github.com/checkstyle/checkstyle/blob/master/src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/InputTags.java) This is Failure:
org.junit.ComparisonFailure: error message 10 expected:<...docMethodTags.java:3[20:9: 缺少 Javadoc] 。> but was:<...docMethodTags.java:3[3: 需要一个 Javadoc注释 @return] 。>
I find `actual` is really different from `expect` when I debug it.

**Comment by djydewang** [comment]
@romani I have finished all task except when I test [JavadocMethodCheckTest.java](https://github.com/djydewang/checkstyle/blob/master/src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheckTest.java) with [InputJavadocMethodTags.java(InputTags.java)](https://github.com/djydewang/checkstyle/blob/master/src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmethod/InputJavadocMethodTags.java) This is Failure:
`org.junit.ComparisonFailure: error message 10 expected:<...docMethodTags.java:3[20:9: 缺少 Javadoc] 。> but was:<...docMethodTags.java:3[3: 需要一个 Javadoc注释 @return] 。>`
I find `actual` is really different from `expect` when I debug it.

**Comment by romani** [comment]
Without review of your code changes it is hard to help, but no changes in it's are expected. please do PR to let me see all your changes and exact place it fails

**Comment by romani** [comment]
Fix is merged.

@djydewang , thanks a lot for your help. You are ready for more complicated issue now, let me know if need help to choose next issue
