### ISSUE TITLE
Split and Organize Checkstyle inputs by Test for checks in 'checks' package 

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#4587]
subtask of #3891

Move / Make a copy of all test input files to a separate folder for all checks in 'checks' package.
Not any other Check should use new inputs.

Attention: that is bit different issue. We need to create folder "..../checks/misc". In "misc" folder put files as we do in all other issues of this series: "misc/transaltion/Input..... .java", "misc/upperl/ ......" ,... 

There are a lot of other issues/commit that named as "Split and Organize Checkstyle inputs ..." , you can find example of what to do there.

all files should in subfolders - https://github.com/checkstyle/checkstyle/tree/master/src/test/resources/com/puppycrawl/tools/checkstyle/checks

**Comment by Kietzmann** [comment]
I'm on it
If I've correctly understood, we need to clean up checks package from input files which are related to tests that are located directly in 'checks' package?

**Comment by romani** [comment]
yes

**Comment by romani** [comment]
@Kietzmann , reminder, please do PR for each Check update.

**Comment by Kietzmann** [comment]
@romani 
Oops
may for first two updates it'll be in one PR?

**Comment by romani** [comment]
ok, but please try to keep PR of easy to revive size, if some case might be unclear please do comment in description.

**Comment by Kietzmann** [comment]
ok

**Comment by romani** [comment]
all input files were moved to subfolders.

@Kietzmann , thanks a lot for your update !
