### ISSUE TITLE
Split and Organize Checkstyle inputs for MainTests to 'main' folder

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#4588]
subtask of #3891

Move / Make a copy of all test input files to a separate folder "main" for MainTest.
Not any other XxxxxTest files should use that inputs.

There are a lot of other issues/commit that named as "Split and Organize Checkstyle inputs ..." , you can find example of what to do there.

https://github.com/checkstyle/checkstyle/tree/master/src/test/resources/com/puppycrawl/tools/checkstyle should be empty on completion.

**Comment by Kietzmann** [comment]
@romani 
Could please give a more exact description of what should be done? Thanks

**Comment by rnveach** [comment]
@Kietzmann Exact description can be found at https://github.com/checkstyle/checkstyle/issues/3891#issue-211193862 .

**Comment by Kietzmann** [comment]
@romani 
Do I need to move all resource files to /main package or only used by MainTest
*A lot of files in /checkstyle dir is not used by MainTest.java

**Comment by rnveach** [comment]
Only those by `MainTest`.
If there are still files leftover once done and they are not used by any other test, they should be removed.

**Comment by romani** [comment]
there still some files left in resource folder.
@Kietzmann , are they related to MainTest ?

**Comment by Kietzmann** [comment]
@romani 
No, they're not. They're used by other tests

**Comment by romani** [comment]
@Kietzmann , please provide list of test that use such files, we need to know what should be fixed.
This folder should be empty from files ideally.

**Comment by Kietzmann** [comment]
cache.tmp -> PropertyCacheFileTest
externalResource.tmp -> PropertyCacheFileTest
import-control_complete.xml -> FileTextTest, AllCheckTest
inputDefaultConfig -> AllCheckTest
inputImportControlOne.xml -> CheckerTest, ImportControlCheckTest
inputImportControlOneRegExp.xml -> CheckerTest, ImportControlCheckTest
InputMain -> ChekcerTest, TreeWalkerTest
InputTreeWalkerHiddenComments -> TreeWalkerTest
java.header -> PropertyCacheFileTest, XdocsPagesTest
suppress_all.xml -> CheckerTest

**Comment by romani** [comment]
AllChecksTest and XdocsPagesTest is in "internal" package in test  ... should be copied/moved to "internal" subfolder.
@rnveach  , please confirm.

> inputImportControlOne.xml -> CheckerTest, ImportControlCheckTest
inputImportControlOneRegExp.xml -> CheckerTest, ImportControlCheckTest

input files should be copied to "checks/input", looks like it was missed during #4437 .
@Kietzmann , please help us to finish cleanup in this folder.
in https://github.com/checkstyle/checkstyle/tree/master/src/test/resources/com/puppycrawl/tools/checkstyle should be left only inputs that belong to Tests files from https://github.com/checkstyle/checkstyle/tree/master/src/test/java/com/puppycrawl/tools/checkstyle

**Comment by rnveach** [comment]
> java.header -> XdocsPagesTest

This is not true. We use checkstyle's main `java.header` in config path, not a test's input.
See: https://github.com/checkstyle/checkstyle/blob/6457b171524f7c84c69a40af9c777814d9d4cba0/src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java#L225
Notice there is no `getPath` so it is relative to repository root.

> @rnveach , please confirm.

I am fine with moving to internal folder for `AllChecksTest`.

**Comment by Kietzmann** [comment]
@rnveach 
Hi,
I'm receiving RegexpMultiline Error while checkstyle trying to check
`return super.getPath("internal" + File.separator + filename);`
Could you please tell me if I should suppress this check or modify my code?
Thanks

**Comment by romani** [comment]
What is a message of violation ?

**Comment by Kietzmann** [comment]
Unnecessary consecutive lines [RegexpMultiline]

**Comment by rnveach** [comment]
@Kietzmann You should modify your code. It is complaining that you have 2 or more consecutive empty lines.

**Comment by Kietzmann** [comment]
Thanks

**Comment by Kietzmann** [comment]
What should I do with rest files?

**Comment by romani** [comment]
verified.
Lets keep that files there.
Issue is closed.
