### ISSUE TITLE
Implement check state resetting for MT mode

### ISSUE THREAD

**Issue by soon** [checkstyle/checkstyle#4624]
Based on https://github.com/checkstyle/checkstyle/issues/4473#issuecomment-313149913

Some file-stateful checks clears state through the `clear` method of the field, e.g. [UnusedImportsCheck](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/UnusedImportsCheck.java#L100):

    @Override
    public void beginTree(DetailAST rootAST) {
        collect = false;
        imports.clear();
        referenced.clear();
    }

This works well for ST mode, but this approach cannot be used to clear check state in MT mode, because check clones will still hold the same reference. The code above should be rewritten as follows:

    @Override
    public void beginTree(DetailAST rootAST) {
        collect = false;
        imports = new HashSet<>();
        referenced = new HashSet<>();
    }

Also, in this issue a `OneCheckInstancePerThread` interface should be introduced to mark all file-stateful checks (see here https://github.com/checkstyle/checkstyle/issues/4473#issuecomment-309869446 for the interface explanations)

@rnveach @sabaka

**Comment by rnveach** [comment]
@soon You are doing clones on the checks.
Issue is the result of doing a `shallow` clone. There is no way to make the clone implement a `deep` cloning method?

**Comment by soon** [comment]
@rnveach Implementing deep cloning now. Will finish it by the end of the week, and then will close this issue.

**Comment by rnveach** [comment]
Please share how you are doing deep clone before closing.

**Comment by soon** [comment]
@rnveach I'm using 3rd party library `uk.com.robust-it.cloning` (as far as I remember, you used the same library). It works pretty well, I just ignore fields which should not be cloned and everything seems fine (no performance degradation found, checked on openjdk7, 1m35s MT, 1m58s ST)

I finished checks rewriting, but seems like some of them still should be improved to clear the state (like this https://github.com/soon/checkstyle/commit/fddb4ea9c462ff1f11f3a545c84e1fcba1f4ee43#diff-ae242d78c6530da97299ecf215d1ed38R97). I'll create 

See the current implementation here (https://github.com/soon/checkstyle/commit/fddb4ea9c462ff1f11f3a545c84e1fcba1f4ee43#diff-404a4bfa3acb4cbc7635f4b2f27435b1R11)

**Comment by rnveach** [comment]
@romani Please confirm you are ok with a new 3rd party library for clonning.

**Comment by romani** [comment]
@soon , It might be already discussed somewhere, if so please give me links.
Why we prefer cloning to simple new Check instance and configuration of it ?

**Comment by soon** [comment]
@romani Are you asking about creating the new check using the `ModuleFactory` and `contextualize` / `configure` configuration methods? Good idea, haven't found discussion for this approach. Going to implement it and write here for results

**Comment by soon** [comment]
@romani, yes, seems like we could just create new check  from the configuration. The 3rd party cloning library is redundant now,

**Comment by soon** [comment]
Closing in favor of https://github.com/checkstyle/checkstyle/issues/4869
