### ISSUE TITLE
Checkstyle should have a way to accept long list of files to check

### ISSUE THREAD

**Issue by denizarsan** [checkstyle/checkstyle#4629]
Checkstyle currently treats the arguments as a list of files/directories to check. However, this can run into the command length limit (which depends on the shell/OS), as I experienced while running some big experiments with Checkstyle.

We could introduce an option to the CLI to treat the argument(s) as file(s) containing lists of files to check with Checkstyle. For example:

$ cat test
```
C1.java
C2.java
```
$ cat C{1,2}.java
```java
class C1 {
    int[] i = new int[]{ 1};
}
class C2 {
    int[] i = new int[]{ 2};
}
```
$ javac C{1,2}.java

$ cat config.xml
```
<!DOCTYPE module PUBLIC "-//Puppy Crawl//DTD Check Configuration 1.3//EN" "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
<module name="Checker">
  <module name="TreeWalker">
    <module name="NoWhitespaceAfter"/>
  </module>
</module>
```
$ java -jar checkstyle-8.1-SNAPSHOT-all.jar -c config.xml test **-F**
```
Starting audit...
[ERROR] /Users/darsan/Desktop/checkstyle/C1.java:2:25: '{' is followed by whitespace. [NoWhitespaceAfter]
[ERROR] /Users/darsan/Desktop/checkstyle/C2.java:2:25: '{' is followed by whitespace. [NoWhitespaceAfter]
Audit done.
Checkstyle ends with 2 errors.
```
Here **-F** is the option that tells Checkstyle to treat the arguments as individual files containing lists of files.

**Comment by romani** [comment]
why usage of folder(s) in CLI does not work for you ? 
just move all your files to folder and run CLI validation on folder.

please give more details on why you need this feature .

**Comment by rnveach** [comment]
Issue closed due to no response. Issue can be reopened with response.

Issue might be able to work around with picocli. See https://picocli.info/#AtFiles .
