### ISSUE TITLE
Avoid usage of getLines method from FileText

### ISSUE THREAD

**Issue by MEZk** [checkstyle/checkstyle#4641]
Taken from https://github.com/checkstyle/checkstyle/pull/4525

After merge of https://github.com/checkstyle/checkstyle/pull/4525 all calls to FileText#getLines will create the copy of the inner array of strings. We should avoid usage of the method (ideally we need to remove it) and replace all method calls with FileText#get(i) and FileText#size().

**Comment by timurt** [comment]
@MEZk 
Inside `RegexpSinglelineCheck#processFiltered` should I create `List<String>` and copy values from `FileText` using `FileText#get` and `FileText#size` methods 
or
Inside `SinglelineDetector` class create new method with signature 
`public void processLines(FileText fileText) {`

**Comment by MEZk** [comment]
@timurt 
I think that the second approach will be better.

**Comment by romani** [comment]
Second approach please, to keep performance as it was before.

Please recheck that getLines is used, if not used in our code, so should be removed

**Comment by romani** [comment]
fix is merged
