### ISSUE TITLE
IllegalThrowsCheck could use a way to ignore packages

### ISSUE THREAD

**Issue by mebigfatguy** [checkstyle/checkstyle#4650]
Have a package of aspects, which by nature need to throw Throwable. would be nice to be able to exclude them all at once, rather than by method name.

**Comment by romani** [comment]
Non of Check be that extended to be able to satisfy suppression requirements of users.
You have to use checkstyle suppressions http://checkstyle.sourceforge.net/config_filters.html

You can disable Check on the whole folder of sources.
Example: https://github.com/checkstyle/checkstyle/blob/master/config/suppressions.xml#L95
