### ISSUE TITLE
pitest: increase mutation coverage for pitest-checks-misc profile to 100%

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#4675]
We should increase coverage for pitest-checks-misc profile up to 100%.
This issue is a subtask of #3708

Current threshold of pitest-checks-misc profile: XX

**Comment by romani** [comment]
@Nimfadora , FYI, missed set of classes.

**Comment by romani** [comment]
fix is merged

**Comment by romani** [comment]
problematic test is reverted to unlock release process. See issue #5141

Now uncovered mutations are:
![image](https://user-images.githubusercontent.com/812984/31309120-033cd37c-ab36-11e7-903d-45fa90569333.png)

![image](https://user-images.githubusercontent.com/812984/31309129-1fce39ea-ab36-11e7-9c18-6d23081f4535.png)

**Comment by rnveach** [comment]
Latest report: http://rveach.no-ip.org/checkstyle/regression/pitest-reports/13/

Report shows `TrailingCommentCheck` is not at 100% code coverage, and `TranslationCheck` is missing mutation coverage.

**Comment by rnveach** [comment]
@romani Missing mutation coverage for `TranslationCheck` that was reverted might be brought back if Issue #5141 is fixed. It has a PR that has been sitting.

**Comment by romani** [comment]
the only missed coverage we have is 
![image](https://user-images.githubusercontent.com/812984/34343244-31edb42c-e97d-11e7-8b55-c63da7a85eb7.png)
`removed call to com/puppycrawl/tools/checkstyle/api/MessageDispatcher::fireFileFinished → SURVIVED`

@Nimfadora , please help us to finish this issue.

**Comment by Nimfadora** [comment]
@romani, ok, I will do it today.

**Comment by Nimfadora** [comment]
@romani xml output varies only in order of lines when I comment out line with missed coverage. And comment in testLogOutput says:

```
            // order is not always maintained here for an unknown reason.
            // File names can appear in different orders depending on the OS and VM.
            // This ensures we pick up the correct file based on its name and the
            // number of children it has.
```
 
So, I don't really understand how to test it, if it influences only order, which we can't check by known reasons.

**Comment by romani** [comment]
@Nimfadora , if line of code does not affect anything, and generated xml report is still correct (all violations reported on proper files, no false-postives). 
Such line should be removed from code completely - please do.

**Comment by rnveach** [comment]
@romani 
Please look over https://github.com/checkstyle/checkstyle/issues/5057 in terms of this fire call.
Just removing this line will have weird affects on any listener as we are sending violations without triggering a file has been started or a previous file is done.
Other issue might be the reason this one is so hard to kill.

Removing the call to `fileFinished` in this case can cause violations not to be printed.
See https://github.com/checkstyle/checkstyle/blob/3b531fe996078098c7fa30b8ab0645a6157dc6d1/src/main/java/com/puppycrawl/tools/checkstyle/XMLLogger.java#L141

**Comment by romani** [comment]
Final fix is merged
