### ISSUE TITLE
remove deprecated AbstractDeclarationCollector, AbstractFormatCheck, AbstractOptionCheck 

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#4677]
remove deprecated: 
- AbstractDeclarationCollector, 
- AbstractFormatCheck, 
- AbstractOptionCheck 

removal is required also from all our configs (pom, suppressions, .....)

**Comment by Kietzmann** [comment]
I'm on it

**Comment by Kietzmann** [comment]
@romani 
Should I remove AbstractTypeAwareCheck also(it is deprecated too)?

**Comment by rnveach** [comment]
@Kietzmann No, 1 non-deprecated check is depended on it for now.

**Comment by romani** [comment]
AbstractTypeAwareCheck will be removed at #4676 .

**Comment by Kietzmann** [comment]
Please close the issue

**Comment by rnveach** [comment]
Fix was merged
