### ISSUE TITLE
create Travis ready to use shell script to check that pistes profiles cover all classes

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#4684]
we have a lot of profiles that test certain set of classes.
There is no guaranty that all classes are covered, we even missed misc Checks at all for long time.

TODO:
make a shell script that grab "param" and and take list of all Check files on filesystem and make sure nothing is missed from pitest coverage.

**Comment by rnveach** [comment]
@romani Since I consider you to be our bash expert, is `xmlstarlet` the best and only and way to pull the list of `targetClasses` from the POM for each pitest entry?
If so, is there an easy way to start creating an xpath for this purpose?

**Comment by romani** [comment]
I am not sure that it is the best way, but it is better than `grep`. If no other tool appeared in web for querting XML , we should continue to use it.

is there an easy way to start creating an xpath for this purpose?

I do not know, I usually just look at examples and in similar way. We have bunch of examples already , please review sevntu repo too.

**Comment by rnveach** [comment]
For Bash, I only found one other tool, xmllint, but it doesn't print different nodes on separate lines, so that may cause issues since we need someway to specify an array.

I am using this xpath currently to find all pitest target classes: `cat pom.xml | sed '3 s/xmlns=".*"//g' | xmlstarlet sel -t -v "//profile[./id[contains(text(),'pitest')]]//targetClasses/param" -n | tr -d '[ ]'`

**Comment by romani** [comment]
Xmlstarlet have option to define xsd, I did this to parse pom.xml , examples be in our repository for sure, let me know if you need link to example

**Comment by rnveach** [comment]
@romani I have a bash script that prints a command to use and the command works, but the weird thing is the command doesn't work when executed inside the bash script through the variable but works when I paste it into terminal manually. I assume I am missing something simple, maybe how `'` are handled?

Current Script:
````
#!/bin/bash

cd checkstyle

list=($(cat pom.xml | sed '3 s/xmlns=".*"//g' | xmlstarlet sel -t -v '//profile[./id[contains(text(),'pitest')]]//targetClasses/param' -n))

CMD="find src/main/java -type f ! -name 'package-info.java'"

for item in ${list[@]}
do
	CMD="$CMD -and ! -wholename '*/${item//\./\/}*'"
done

echo $CMD
echo
echo

echo $($CMD)
````

Here is the results though when I run the command. It shows we have 14 files not being maintained by the pitest.
````
src/main/java/com/puppycrawl/tools/checkstyle/checks/LineSeparatorOption.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/SuppressWarningsHolder.java
src/main/java/com/puppycrawl/tools/checkstyle/XpathFileGeneratorAuditListener.java
src/main/java/com/puppycrawl/tools/checkstyle/StatelessCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/PropertyResolver.java
src/main/java/com/puppycrawl/tools/checkstyle/XpathFileGeneratorAstFilter.java
src/main/java/com/puppycrawl/tools/checkstyle/JavadocPropertiesGenerator.java
src/main/java/com/puppycrawl/tools/checkstyle/FileStatefulCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/ModuleFactory.java
src/main/java/com/puppycrawl/tools/checkstyle/XmlLoader.java
src/main/java/com/puppycrawl/tools/checkstyle/GlobalStatefulCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/JavaParser.java
src/main/java/com/puppycrawl/tools/checkstyle/AuditEventFormatter.java
src/main/java/com/puppycrawl/tools/checkstyle/grammar/CommentListener.java
````

**Comment by romani** [comment]
Heh, one more pack of technical debt.

Please add such classes to some common/general pitest profile, and suppress all missed items in pitest.sh if size of them is not that huge.
If you are not sure, just add them to profile and let CI fail and print all problems for review

**Comment by rnveach** [comment]
Script needs to be relooked at because of https://github.com/checkstyle/checkstyle/pull/6254#issuecomment-445503405 .

**Comment by romani** [comment]
Fix is merged

**Comment by rnveach** [comment]
@romani 
> If you are not sure, just add them to profile and let CI fail and print all problems for review

As mentioned at https://github.com/checkstyle/checkstyle/pull/6251#issuecomment-445463114 , if there is percentage failure, pitest.sh won't finish and print missing mutations. I believe this is because low percentage is seen as a maven build failure and stops the execution.
If you can change this behavior, please do.

**Comment by romani** [comment]
We can lower an percentage number, we relied on it before we found that it is NOT trusty.
That is why we have that shell post processing where we define exact list of on covered lines, line by line
