### ISSUE TITLE
Split and Organize Checkstyle inputs by Test for checks in 'ant' package

### ISSUE THREAD

**Issue by subkrish** [checkstyle/checkstyle#4686]
subtask of #3891

Move / Make a copy of all test input files to a separate folder for all checks in 'ant' package.
Not any other Check should use new inputs.

**Comment by subkrish** [comment]
I'm on it.

There is only one file in this package -> `CheckstyleAntTaskTest`. Its inputs will be moved to `checkstyleanttask` directory

**Comment by romani** [comment]
@subkrish , @rnveach 
1 test - https://github.com/checkstyle/checkstyle/tree/master/src/test/java/com/puppycrawl/tools/checkstyle/ant
https://github.com/checkstyle/checkstyle/tree/master/src/test/resources/com/puppycrawl/tools/checkstyle/ant

do we really need to have subfolders here ? whole ant folder is belong to one Test .

**Comment by subkrish** [comment]
@romani 

I feel the reason here is that all the inputs need to belong to one folder. For example, `config_custom_root_module.xml` lies outside the folder `ant` instead of being in it although it is being used by `CheckstyleAntTaskTest`.

One thing we could do is move the inputs into the `ant` folder as you have suggested. This would help us to use the `getPackageLocation()` under https://github.com/checkstyle/checkstyle/issues/4592#issuecomment-313853992 .

Since the inputs are scattered in different folders when I add the path in the method I am forced to leave it `com/puppycrawl/tools/checkstyle` instead of `com/puppycrawl/tools/checkstyle/ant`.

**Comment by rnveach** [comment]
> whole ant folder is belong to one Test .

@romani I am fine with it one folder, but it does goes against how we are organizing literally everything else in the main issue.
Also, if we ever need a new class in this package, public or otherwise, we would have to switch back to sub-folders.

**Comment by romani** [comment]
>if we ever need a new class in this package

It is not changed for many years, I doubt it will change in future. Let's think about it when future show us their requirements. Let's stay with one folder ( no subfolders) for now.

>One thing we could do is move the inputs into the ant folder as you have suggested.

Please do.

>For example, config_custom_root_module.xml lies outside the folder ant 

Please force all inputs/configs to be in one folder - `ant`. I am ok to keep copies of some files, but all of them should belong to ant.

**Comment by rnveach** [comment]
@subkrish Sorry, one more change.
https://github.com/checkstyle/checkstyle/tree/master/src/test/resources/com/puppycrawl/tools/checkstyle/ant/checkstyleanttask
Please move all inputs in `flawless` directory to `checkstyleanttask`.

**Comment by subkrish** [comment]
@rnveach @romani I think this issue is complete and can be closed.

**Comment by rnveach** [comment]
Fixes were merged
