### ISSUE TITLE
UniquePropertiesCheck.getLineNumber should be private

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#4694]
Checks are not designed for extension in general, so `protected` usage is discouraged
especially `static protected`
`protected static int getLineNumber(FileText fileText, String keyName) {`
https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/UniquePropertiesCheck.java#L104

should become `private protected`. UTs should be updated to use Check public methods to test functionality.

**Comment by djydewang** [comment]
Is it OK to test functionality by using reflection?

**Comment by rnveach** [comment]
@djydewang Yes.
