### ISSUE TITLE
suppress NewlineAtEndOfFile on all internal javadoc files

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#4702]
base on reasonable point at https://github.com/checkstyle/checkstyle/pull/4697/commits/b94c6473f59be01ee79764b10ed65874d4897537#r126940483

all javadoc in our repository files should be skipped from radar of NewlineAtEndOfFile

**Comment by Kietzmann** [comment]
I'll do it

**Comment by romani** [comment]
fix is merged
