### ISSUE TITLE
avoid boolean parameters for public methods

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#4709]
taken from #4707

classes: ConfigurationLoader , DefaultLogger, XMLLogger 

Idea inspection: `'public' method with 'boolean' parameter`
From inspection documentation
`
It's almost always a mistake to add a boolean parameter to a public method (part of an API) if that method is not a setter. When reading code using such a method, it can be difficult to decipher what the boolean stands for without looking at the source or documentation. This problem is also known as the "boolean trap". The boolean parameter can often be profitably replaced with an enum 
Use the option below to only warn when a method contains more than one boolean parameter.
`
link for "boolean trap" - https://ariya.io/2011/08/hall-of-api-shame-boolean-trap

It will be good to update but do this accurately to not damage CI that depends on maven plugin that uses such c-tors.

Intellij Idea by visual effect over the code, ease this problem by printing name of parameter before the value:
![image](https://user-images.githubusercontent.com/812984/28167290-efdea2a4-678f-11e7-87bf-8f20d645e7c7.png)
, but I still think that code should be readable without IDE

**Comment by romani** [comment]
@rnveach , please do second review of the intend to refactor.

**Comment by rnveach** [comment]
It will definitely break maven. We would need to coordinate with them first and then our regressioned projects to have them update to the newer version, if it is ever released. Aren't we waiting on maven checkstyle for other changes?
https://github.com/apache/maven-plugins/blob/dd84ee9053fde6f553c163237eb1d0f625f427b7/maven-checkstyle-plugin/src/main/java/org/apache/maven/plugins/checkstyle/exec/DefaultCheckstyleExecutor.java#L377-L378
https://github.com/apache/maven-plugins/blob/dd3acde958cf2470080e859f1a9a3d50b2c488b3/maven-checkstyle-plugin/src/main/java/org/apache/maven/plugins/checkstyle/AbstractCheckstyleReport.java#L566
https://github.com/apache/maven-plugins/blob/dd3acde958cf2470080e859f1a9a3d50b2c488b3/maven-checkstyle-plugin/src/main/java/org/apache/maven/plugins/checkstyle/AbstractCheckstyleReport.java#L562

> boolean trap

I understand the thought behind this of why to not allow `boolean` variables as enumerations would basically self-document, but I'm not sure I would want this kind of refactoring in my own code. I can't imagine many people using those 3 classes you mentioned directly. We can't do checks as they have properties that are `true` booleans, unless we break almost all our checks and change them too, which it seems like we should as properties are definitely used much more than those classes.

If you want to do this for those classes, then I have no big issue with that.

**Comment by romani** [comment]
> We can't do checks as they have properties that are true booleans

inspections skips simple setters, please review report in original issue, there are side effects(kind of false-positives), but they are minimal (there will be only 2 suppresions).

**Comment by rnveach** [comment]
> inspections skips simple setters, please review report in original issue

We can create our own check if we wish to enforce for checks. Since you wish to do this, it may make sense to do it for the properties too.

>  Are you ok with this ?

I am fine with that plan.

**Comment by romani** [comment]
> We can create our own check if we wish to enforce for checks.

ones we resolve current current GSoC tasks we can put a lot of new Checks to checkstyle, nothing blocks us to do this now, except for lack of time and lack of contributors.

**Comment by romani** [comment]
@Nimfadora , please create new method/ctors for these classes and put deprecation annotation on existing.

**Comment by romani** [comment]
@Nimfadora , last PR is merged, please send PR to activate inspection in config

**Comment by Nimfadora** [comment]
@romani I realized that it is already enabled. But two cases are still annotated without deprecation:
[DetectorOptions#ignoreCase](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/DetectorOptions.java#L205) and [IllegalTokenTextCheck#setIgnoreCase](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTokenTextCheck.java#L150)

**Comment by romani** [comment]
> But two cases are still annotated without deprecation:
DetectorOptions#ignoreCase and IllegalTokenTextCheck#setIgnoreCase

we can not deprecate this, first if false-positive over Builder patterns, second is Check public property, we can not change them.
