### ISSUE TITLE
Make SuppressionCommentFilter and SuppressWithNearbyCommentFilter children of TreeWalker

### ISSUE THREAD

**Issue by MEZk** [checkstyle/checkstyle#4714]
SuppressWithNearbyCommentFilter and SuppressionCommentFilter need to have information which can be extracted from AST. TreeWalker is the only one FileSetCheck which deals with AST. That is why it is reasonable to make both filters children of TreeWalker. AST must not be visible on the Checker level.

What should be done:

1. Create TreeWalkerAuditEvent. TreeWalkerAuditEvent is a wrapper class with the following set of fields:
```java
private String fileName;
private FileContents fileContents;
private LocalizedMessage localizedMessage;
```
We should not extend AuditEvent or create AbstractAuditEvent as we cannot design the whole model of events now. Thus, the concrete implementation is OK.

2. Create AstFilter interface with the following api:
```java
boolean accept(TreeWalkerAuditEvent auditEvent);
``` 

3. SuppressionCommentFilter and SuppressWithNearbyCommentFilter should implement AstFilter. Dependency on FileContentsHolder must be removed. All UTs should be fixed.

4. Add the set of AstFilters to TreeWalker.

5. All AstFilters should be initialized and configured in ```setupChild``` method of TreeWalker (similar to Checker).

6. Add the sorted set of localized messages to TreeWalker.

7. The set of messages should be cleared in notifyBegin method of TreeWalker.

8. The messages, received from the parents of AbstractCheck should be stored to the sorted set of messages in TreeWalker inside ```notifyEnd``` method.

9. TreeWalker has to filter the set of sorted messages in ```processFiltered```. All messages which pass the filtration should be given to the apper level to Checker (```AbstractFileSetCheck#addMessages```). TreeWalkerAuditEvent objects need to be created based on LocalizedMessage instances. 

@timurt 
You can use [my branch](https://github.com/MEZk/checkstyle/tree/tree-walker-filter) as a starting point.

**Comment by romani** [comment]
>private DetailAST root;

Please introduce this field only when you introduce a filter that will use it, it is a different task.

**Comment by MEZk** [comment]
@romani 
Corrected description

**Comment by MEZk** [comment]
@timurt 
Ping, what is the status of this issue? Do you need any help?

**Comment by timurt** [comment]
@MEZk 
I have done 1-8 steps
9. by filtration you mean same as inside [Checker#fireErrors](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/Checker.java#L380)?

**Comment by MEZk** [comment]
@timurt 
You need to filter the set of LocalizedMessage and return to Checker all messages that passed filtration. The idea is similar to fireErrors.

**Comment by MEZk** [comment]
@timurt 
Ping

**Comment by timurt** [comment]
@MEZk 
sent PR
Should I change `checkstyle_sevntu_checks.xml`, move `SuppressWithNearbyCommentFilter` to `TreeWalker` module? - I did it inside `checkstyle_checks.xml`

**Comment by MEZk** [comment]
@romani 

>Should I change checkstyle_sevntu_checks.xml

As far as I know we should release Checkstyle with the changes made in the scope of this issue, change release Checkstyle version which is used by SevNTU Checkstyle, update SevNTU checkstyle version in main project, and change checkstyle_sevntu_checks.xml. Am I right?

**Comment by romani** [comment]
> Am I right?

yes, this is example of what other thirparty extensions should do to upgrade to latest version of checkstyle. We can not do all at ones, so we will need to disable sevntu for some time, till we release checkstyle 8.1 and next version of sevntu that is based on checkstyle 8.1 .
checkstyle 8.1 will be released at this weekend, so if you prepare PRs for sevntu project we can make upgrade quickly, without bad code leak to master.

**Comment by rnveach** [comment]
@romani @MEZk See PR, it is not just sevntu we will be breaking, but probably all of wercker.

**Comment by MEZk** [comment]
@rnveach 
Answered in PR, waiting for @romani

**Comment by romani** [comment]
fix is merged.

release 8.1 will done today or tomorrow.

**Comment by todd-richmond** [comment]
this broke previously existing xml files so it would be good to add the fix of moving the old blocks to the TreeWalker section to release notes

**Comment by romani** [comment]
@todd-richmond , thanks for feedback. 
Release notes are generated content from list of fixed issues, it not that simple to put in release notes some custom text.
I updated this issue description to attract users attention to how to migrate.

**Comment by romani** [comment]
patch was not removed from wercker for hibernate-search project that result in problem - https://github.com/checkstyle/checkstyle/pull/5194#issuecomment-338483328 .
