### ISSUE TITLE
api: abstract classes that extending concrete class

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#4716]
from Intellij Idea inspection - AbstractClassExtendsConcreteClass

>Inheritance issues group   4 errors 
    Abstract class extends concrete class inspection   3 errors 
        class AbstractLoader   1 error 
            ERROR Class 'AbstractLoader' is declared 'abstract', and extends a concrete class     
        class AbstractViolationReporter   1 error 
            ERROR Class 'AbstractViolationReporter' is declared 'abstract', and extends a concrete class     

We need to review such cases and make a decision how to refactor this bad design.

**Comment by rnveach** [comment]
All the classes mentioned extend `AutomaticBean` which is also trying to be refactored at #3542 .

**Comment by rnveach** [comment]
@romani After looking at the class from working on the other issue, I think we should just make it `abstract` with no abstract methods.
Most of our other abstract classes have empty method definitions that can be overridden by demand or left as an empty implementation. I don't really see any method that should be made `abstract`.

**Comment by romani** [comment]
suppressions are merged, actual fixes in classes are postponed to other issues:
Rename AutomaticBean #5337
Move, Rename, and remove abstract from AbstractLoader #5338
