### ISSUE TITLE
Improve Error Handling for Javadoc Parsing

### ISSUE THREAD

**Issue by ps-sp** [checkstyle/checkstyle#4717]
Right now when the errorListener object we [implemented](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/JavadocDetailNodeParser.java#L448) for ANTLR [doesn't receive any errorMessage](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/JavadocDetailNodeParser.java#L131-#L134), we [generate](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/JavadocDetailNodeParser.java#L135) an uninformative ParseErrorMessage with key `MSG_KEY_UNRECOGNIZED_ANTLR_ERROR` leading to error messages like

```
[ERROR:0] Javadoc comment at column -3 has parse error. Unrecognized error from ANTLR parser: null
```

There is potential for adding custom error handling here and we can at least handle general cases if not all the cases and generate more informative error messages for the user.

**Comment by romani** [comment]
@Vladlis , is it related to GSoC project

**Comment by Vladlis** [comment]
@romani , it is, but priority is low, so we can work on it if we have time in the end

**Comment by Vladlis** [comment]
fix is merged
