### ISSUE TITLE
idea: fifth part of idea violations

### ISSUE THREAD

**Issue by Nimfadora** [checkstyle/checkstyle#4726]
sub-task of #4681

full report is [here](https://teamcity.jetbrains.com/viewLog.html?buildId=1116964&buildTypeId=Checkstyle_IdeaInspectionsPullRequest&tab=Inspection)

in scope of this issue we should fix:
Performance issues
Portability issues
Probable bugs
Properties files

Violations included:
```
fixed:
EqualsUsesNonFinalVariable
HashCodeUsesNonFinalVariable
AlphaUnsortedPropertiesFile
InconsistentResourceBundle
MethodMayBeStatic
CallToSimpleGetterInClass
MismatchedCollectionQueryUpdate
NullableProblems
CollectionsMustHaveInitialCapacity
ConstantConditions
DuplicatePropertyInspection
HardcodedFileSeparators
HardcodedLineSeparators
LengthOneStringsInConcatenation
MagicConstant
ObjectAllocationInLoop
ObjectEquality
ReturnNull
SuspiciousArrayCast
```
StringBufferMustHaveInitialCapacity will be addressed #4812

**Comment by romani** [comment]
> Violations included:

please activate that list of inspections and send PR(not for merge) to generate report on TC.

**Comment by romani** [comment]
@Nimfadora , I already did a review of such violations .... why you mix inspections between PR ?

**Comment by romani** [comment]
I still do not see pull request and report on this

**Comment by Nimfadora** [comment]
@romani it is stated in the task text as todo, all of them have your comments, so soon it will be fixed

**Comment by Nimfadora** [comment]
>EqualsUsesNonFinalVariable
HashCodeUsesNonFinalVariable

[Here](https://github.com/checkstyle/checkstyle/issues/4725#issuecomment-315612241) you said that for SuppressElement issue can be resolved by making variables final and creating c-tors. But some of variables have setters, do we have to remove them and rewrite the logic in couple of classes for that purpose?

**Comment by romani** [comment]
>  do we have to remove them and rewrite the logic in couple of classes for that purpose?

If update is simple - yes.
As far as I remember all setters are used in one place of cod, so refactoring should be easy to keep all parts of object in local variables create class only when all information is available.

**Comment by romani** [comment]
fix is merged
