### ISSUE TITLE
Why we support Charset in configuration when we don't support UTF-8 files?

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#4748]
http://checkstyle.sourceforge.net/writingchecks.html#Limitations
> Java code should be written with ASCII characters only, no UTF-8 support.

Why do we support charset in configuration, some we even set to UTF-8, when we don't even support UTF-8 in general?
https://github.com/checkstyle/checkstyle/blob/master/config/checkstyle_non_main_files_checks.xml#L7
https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/my_check.xml#L8

**Comment by romani** [comment]
Is charset of how we read file for non java Checks (extended from FileSetCheck)
