### ISSUE TITLE
Parsing @see tag with no double quotes to mark string

### ISSUE THREAD

**Issue by ps-sp** [checkstyle/checkstyle#4752]
$ cat YOUR_FILE.java

```
* @see https://www.something.com
```

$ java -jar checkstyle-8.1-SNAPSHOT-all.jar -j  test.java

```
JAVADOC -> JAVADOC [0:0]
|--LEADING_ASTERISK -> * [0:0]
|--WS ->   [0:1]
|--JAVADOC_TAG -> JAVADOC_TAG [0:2]
|   |--SEE_LITERAL -> @see [0:2]
|   |--WS ->   [0:6]
|   |--REFERENCE -> REFERENCE [0:7]
|   |   `--PACKAGE -> https [0:7]
|   `--DESCRIPTION -> DESCRIPTION [0:13]
|       `--TEXT -> ://www.something.com [0:13]
`--EOF -> <EOF> [0:33]
```

As can be seen the javadoc tree is wrong and url should be recognized as string. This happens becuase `WS` is not enforced before description in `@see` tag and because `PACKAGE` token is being [produced by lexer without any context](https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/com/puppycrawl/tools/checkstyle/grammars/javadoc/JavadocLexer.g4#L123). Such input would also lead javadoc tool to produce errors since the quotes are missing. But still the javadoc tool would render the site with a string placed for the url.

Changing [JavadocParser.g4#L881](https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/com/puppycrawl/tools/checkstyle/grammars/javadoc/JavadocParser.g4#L881) from:

```
 | SEE_LITERAL (WS | NEWLINE)* reference? (STRING | htmlElement)* (WS | NEWLINE)* description?
```

to:

```
| SEE_LITERAL (WS | NEWLINE)* reference? ((WS | NEWLINE)+ STRING | htmlElement)*
(WS | NEWLINE)* ((WS | NEWLINE)+ description)?
```
 results in the following output for the same input file:

```
Exception in thread "main" java.lang.IllegalArgumentException: [ERROR:0] Javadoc comment at column -3 has parse error. Unrecognized error from ANTLR parser: null
	at com.puppycrawl.tools.checkstyle.DetailNodeTreeStringPrinter.parseJavadocAsDetailNode(DetailNodeTreeStringPrinter.java:71)
	at com.puppycrawl.tools.checkstyle.DetailNodeTreeStringPrinter.parseJavadocAsDetailNode(DetailNodeTreeStringPrinter.java:83)
	at com.puppycrawl.tools.checkstyle.DetailNodeTreeStringPrinter.parseFile(DetailNodeTreeStringPrinter.java:173)
	at com.puppycrawl.tools.checkstyle.DetailNodeTreeStringPrinter.printFileAst(DetailNodeTreeStringPrinter.java:59)
	at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:400)
	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:209)
```

which happens since parser has no place to fit `:` in [reference rule](https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/com/puppycrawl/tools/checkstyle/grammars/javadoc/JavadocParser.g4#L864), **already** recognized as `CHAR` by lexer, which follows `https` which has **already** been recognized as `PACKAGE` by lexer and hence `PACKAGE` token should be identified with proper discretion. _(reference rule is called `PACKAGE` token is spotted by the parser)_

See also: [4550#issuecomment](https://github.com/checkstyle/checkstyle/pull/4550#issuecomment-312521474) , [4550#issuecomment](https://github.com/checkstyle/checkstyle/pull/4550#issuecomment-312529807)

**Comment by Vladlis** [comment]
> javadoc tree is wrong and url should be recognized as string

according to http://docs.oracle.com/javase/7/docs/technotes/tools/windows/javadoc.html#see String is text between double quotes, so this example should not be parsable

**Comment by romani** [comment]
>  to support javadoc which causes exceptions in javadoc tool?

if javadoc tool produce error, we are ok to throw parse exception.

**Comment by ps-sp** [comment]
@romani @Vladlis 

The javadoc tool inspite of throwing error produces a decent enough site with the `text` without quotes represented properly as plain text on the site as a `string` is. Please refer to [4550#issuecomment](https://github.com/checkstyle/checkstyle/pull/4550#issuecomment-312521801) from @rnveach .

**Comment by romani** [comment]
hmm, javadoc tool will most likely be executed after checkstyle execution.
Checkstyle is most likely executed in IDE, but javadoc tool only during build/packaging/CI.... 
so user will know about some problem from Checkstyle first....

Having un-handled exception will not be good for user. 
So it force us to raise violations on each parse errors, for user to process them as just another violation from checkstyle.
Please wrap all parser errors to general violation.

**Comment by ps-sp** [comment]
@romani 
>Please wrap all parser errors to general violation.

[JavadocDetailNodeParser#parseJavadocAsDetailNode](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/JavadocDetailNodeParser.java#L96) is used in three places. 
1. [DetailNodeTreeStringPrinter.java#L69](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/DetailNodeTreeStringPrinter.java#L69)
2. [AbstractJavadocCheck.java#L272](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheck.java#L272)
3. [ParseTreeTablePresentation.java#L363](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/gui/ParseTreeTablePresentation.java#L363)

Out of these three usages, `exception` is thrown only for the usage in `DetailNodeTreeStringPrinter`. So do you mean that we should log violation and not throw exception for that, since as you once said that tree printing is mainly for debugging ?

**Comment by ps-sp** [comment]
@romani @Vladlis @rnveach 

Right now we have two options:

1) Do not support string without quotes in javadoc ant let ANTLR parser fail.

2) Support it because javadoc tool still builds a deccent site and includes string without quotes in it inspite of throwning an error while executing.

Right now wercker has an input case with `STRING` without quotes (see [4550#issuecomment](https://github.com/checkstyle/checkstyle/pull/4550#issuecomment-312521474)), and so enforcing `WS` before description and reference in grammar leads to wercker failure. 

So if we choose to not support string without quotes we need to correct wercker failure.

Please address

**Comment by Vladlis** [comment]
String without quotes is incorrect for javadoc tool. If we start supporting cases which are incorrect, but still rendered by browsers we may never end - such cases are specified nowhere. I think we should spend time on more important issues and just fix wrong javadoc in postgre which fails wercker.

**Comment by romani** [comment]
@ps-sp ,

> String without quotes is incorrect for javadoc tool. 

yes, we should throw parse exception on this. We need provide fixes for projects that we use in wercker (we need to send them PRs) , meanwhile to avoid waiting PR accepance we could make a patch on cloned werker's project. To pass validation.
