### ISSUE TITLE
Could not create type checkstyle due to java.lang.NoClassDefFoundError: com/google/common/collect/Lists

### ISSUE THREAD

**Issue by ravs788** [checkstyle/checkstyle#4756]
Hi All,

We are working on a project in selenium and gradle. We are working on client environment where there is no internet availability. So, we have taken all project dependencies from local file system.

For static code analysis, we want to add checkstyle plugin to gradle. So, dependency related to checkstyle i.e checkstyle-6.19 is taken from local file system. Since, we cannot add mavenCentral() to the build.gradle, we make use of mavenLocal().

We are getting below error in this case.

**Could not create type checkstyle due to java.lang.NoClassDefFoundError: com/google/common/collect/Lists**

Please find the  jar details  used :

Gradle - 2.8
Checkstyle : 6.19 
google-collections : 0.8.jar
guava :  21.0.jar

Please find attached build.gradle and snapshot.

![image](https://user-images.githubusercontent.com/17542484/28313805-cbff9ec0-6bd5-11e7-99ec-026a154f8172.png)

![image](https://user-images.githubusercontent.com/17542484/28313884-17f0a20c-6bd6-11e7-920b-aef865cf7b86.png)

**Comment by rnveach** [comment]
> Could not create type checkstyle due to java.lang.NoClassDefFoundError: com/google/common/collect/Lists
Checkstyle : 6.19
guava : 21.0.jar

If you are going to use a specific version of Checkstyle, you must use the dependencies it requires.
Checkstyle 6.19 uses Guava 19, not 21. See https://github.com/checkstyle/checkstyle/blob/0b40ab95cd062a31b9d52fdc3236b3dbfa49c981/pom.xml#L259 .

Dependencies are always breaking backward compatibility and Guava is one of them.
I suggest you either use newer versions of Checkstyle or use the correct dependencies the specific version uses.

**Comment by romani** [comment]
nothing we can do there .... I am closing the issue.
