### ISSUE TITLE
Move DetailNodeTreeStringPrinter#createFakeBlockComment to CommonUtils

### ISSUE THREAD

**Issue by ps-sp** [checkstyle/checkstyle#4785]
Method [DetailNodeTreeStringPrinter#createFakeBlockComment](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/DetailNodeTreeStringPrinter.java#L181) should be moved to CommonUtils and [TreeWalker#createBlockCommentNode](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/TreeWalker.java#L723) should be replaced with the new method(s) created in CommonUtils.

**Comment by magicimagination** [comment]
Why instead createBlockCommentNode() should be used new methods from JavadocUtils? Comments are related not always necessary with Javadoc.

**Comment by romani** [comment]
@magicimagination , good point.

Lets move this method to CommonUtils, creation of CommentUtils is not reasonable now as there is only one method for now.
I updated issue title and issue description.

**Comment by romani** [comment]
Fix I'd merged
