### ISSUE TITLE
review TreeWalker.setupChild method for exceptional cases

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#4814]
taken from https://github.com/checkstyle/checkstyle/pull/4755#discussion_r128916609

We need to review exception processing and make sure we deliver to user all context details if exception happen.

**Comment by rnveach** [comment]
Original post was about adding a new try/catch to TreeWalker.setupChild.
https://github.com/checkstyle/checkstyle/pull/4755#discussion_r128916609

I still think we should do this, but to prevent saying the module name multiple times I think we should remove the module name from AutomaticBean. https://github.com/checkstyle/checkstyle/blob/a73ff0890c27cbe8affc1a55f2710a231687bd85/src/main/java/com/puppycrawl/tools/checkstyle/api/AutomaticBean.java#L236-L242 .
It is just going to duplicate the work that TreeWalker/Checker will do.

**Comment by rnveach** [comment]
Change was merged
