### ISSUE TITLE
Incorrect tags allowed in singletonTag rule

### ISSUE THREAD

**Issue by ps-sp** [checkstyle/checkstyle#4827]
As has been summarized here in [4448#issuecomment](https://github.com/checkstyle/checkstyle/issues/4448#issuecomment-317231986), [certain tags in singletonTag rule](https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/com/puppycrawl/tools/checkstyle/grammars/javadoc/JavadocParser.g4#L785-#L799) are not allowed to be self-closing and that can be verified from the following line from HTML specification

>This error _([parse-error-non-void-html-element-start-tag-with-trailing-solidus](https://html.spec.whatwg.org/#parse-error-non-void-html-element-start-tag-with-trailing-solidus))_ occurs if the parser encounters a start tag for an element that is not in the list of void elements or is not a part of foreign content (i.e., not an SVG or MathML element) that has a U+002F (/) code point right before the closing U+003E (>) code point. The parser behaves as if the U+002F (/) is not present.

So these tags should be removed from singletonTag. To support parse error recovery as suggested in above statement or not can be discussed further.

**Comment by romani** [comment]
@ps-sp , @Vladlis , if that is html5 nuance, and it was allowed in html4 .... it should continue to be supported in our parser.

It is enormous amount of code is written in html4, I doubt that smb will fix that javadoc.
If it was supported in html4 , it should continue to be supported. If smth do not like html4 format - special Check will do validation.

**Comment by ps-sp** [comment]
@romani @Vladlis 

> if that is html5 nuance, and it was allowed in html4 .... it should continue to be supported in our parser.

It looks like that it was allowed in HTML4. Please have a look at the following sections:

https://www.w3.org/TR/html4/appendix/notes.html#h-B.3.7

From a [stackoverflow thread](https://stackoverflow.com/questions/3558119/are-non-void-self-closing-tags-valid-in-html5), I realized the following fact:

>In HTML 4, <foo / (yes, with no > at all) means <foo> (which leads to <br /> meaning <br>> (i.e. <br>&gt;) and <title/hello/ meaning <title>hello</title>). Browsers did a very poor job of supporting this and the [spec advises authors to avoid the syntax](http://www.w3.org/TR/html4/appendix/notes.html#h-B.3.3).

So, we can continue supporting it and close this issue perhaps.

**Comment by Vladlis** [comment]
checked the following

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
   <title>TITLE</title>
</head>
<body>
   <div>
     <p/>     
   </div>
</body>
</html>

in https://validator.w3.org/check and only got warning about <p/>
so the current rule is valid and I'm closing this issue.
