### ISSUE TITLE
TreeWalkerFilter needs to be added to ModuleReflectionUtils

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#4843]
[We identify everything inside ModuleReflectionUtils.](https://github.com/checkstyle/checkstyle/blob/ddeb553834f10570089a033fa1ac1501b74ac358/src/main/java/com/puppycrawl/tools/checkstyle/utils/ModuleReflectionUtils.java#L72-L77)
However, we didn't add `TreeWalkerFilter` to it, so it will never be recognized as one of our modules.

It must be added to ModuleReflectionUtils and verified it is picked up everywhere.
Without it listed, we will have bugs similar to #4742.

**Comment by rnveach** [comment]
@MEZk @timurt ping

**Comment by MEZk** [comment]
@rnveach 
Yes, should be fixed.

@timurt 
Please, send PR.

**Comment by romani** [comment]
fix is merged.
