### ISSUE TITLE
Test inputs should be completely standalone.

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#4845]
Identified at https://github.com/checkstyle/checkstyle/pull/4844#issuecomment-318740057 ,

Inputs should be completely standalone and not rely on Checkstyle production code or test code.
It creates an usual coupling and requires changes in completely unrelated tests.

Most inputs that have references to checkstyle code: https://github.com/search?utf8=%E2%9C%93&q=path%3Asrc%2Ftest%2Fresources+filename%3AInput*.java+repo%3Acheckstyle%2Fcheckstyle+%22import+com.puppycrawl.tools.checkstyle%22&type=
There could be more as that was just a general search.

Imports have to be examined why they are used, and how best to remove them and still keep the tests original purpose intact.

List of impacted files was added at https://github.com/checkstyle/checkstyle/blob/master/config/checkstyle-input-suppressions.xml#L35 .
Suppressions must be removed as files are worked on to show they are resolved for this issue.

Issue can only be marked completed when all suppressions are identified and handled appropriately.

**Comment by romani** [comment]
I think we can do this by IllegalImport Check(or importorder). We could have special phase and config for this during build.

**Comment by rnveach** [comment]
We should also extend this that we shouldn't import `Inputs` from other inputs unless really necessary.
Re-organizing inputs in #3891 hit an issue with `Input15Extensions`.
Example: https://github.com/search?utf8=%E2%9C%93&q=path%3Asrc%2Ftest%2Fresources+filename%3AInput*.java+repo%3Acheckstyle%2Fcheckstyle+%22import+com.puppycrawl.tools.checkstyle.checks.imports.unusedimports.Input15Extensions%22&type=

**Comment by pbludov** [comment]
This is another blocker for #5102. The  sun packets are widely used in the import order checks.

**Comment by pbludov** [comment]
For the ImportOrderCheck it is possible to add a number of specially arranged classes to test all the order cases. Something like that:
```
src
  test
     resources-importorder
         com
             pkg1
                Class1.java
                Class2.java
         org
             pkg2
                Class3.java
                Class4.java
         net
             pkg3
                Class5.java
                Class6.java
```

**Comment by romani** [comment]
please do not be over crazy with this issue, it could result in huge update.
it is better to do what is required for java9 and that is all, it will be enough for next several years.

**Comment by rnveach** [comment]
This issue isn't even related to java 9, it is about checkstyle's own code being used in inputs causing a needless link between the 2.

**Comment by pbludov** [comment]
Thinking carefully, I realized that this was a bad idea. There is no need to create many packages within the CS only so that they can be referenced from the import check.

It's enough to move them to resources-noncompilable. How is this done in #5176.
As a free bonus, no smart IDE will re-arrange the import, as the IntelliJ Idea does it, for example.

**Comment by rnveach** [comment]
Adding:
````
  <module name="RegexpSingleline">
    <property name="id" value="noCheckstyleInInputs"/>
    <property name="format" value="import com.puppycrawl.tools.checkstyle"/>
    <property name="fileExtensions" value="java"/>
    <property name="message" value="Inputs should not reference checkstyle's own files"/>
  </module>
````
to `checkstyle_input_checks.xml` produces 248 violations which need to be looked over.

**Comment by romani** [comment]
To make progress we need to apply this Check and add to suppression all items to resolve gradually. Good gsoc first issue.

**Comment by rnveach** [comment]
Issue is available for others to work on.

**Comment by Rahulkhinchi03** [comment]
@romani @rnveach We need to add https://github.com/checkstyle/checkstyle/issues/4845#issuecomment-1065919289 and then work with one check/PR right?

**Comment by aritrasinha108** [comment]
I am on it.

**Comment by romani** [comment]
@aritrasinha108 , please define a module you targeting to fix to avoid collision with others.

**Comment by aritrasinha108** [comment]
@romani  I'll take up the ```imports``` module for now. Will try to work on one more if possible.

**Comment by romani** [comment]
All is possible, but just do one at the time.

**Comment by sd9616** [comment]
I'm on VisibilityModifier

**Comment by Guneetsinghtuli** [comment]
Working on linelength

**Comment by Guneetsinghtuli** [comment]
Working on **IllegalImport**

**Comment by Guneetsinghtuli** [comment]
Working on **customImportOrder**

**Comment by suniti0804** [comment]
I am on Avoid Static Import

**Comment by suniti0804** [comment]
I am on redundantimport check

**Comment by TanayMorakhia** [comment]
I am on avoidStarImport

**Comment by suniti0804** [comment]
I am on illegaltype

**Comment by suniti0804** [comment]
I am on unusedimports

**Comment by TanayMorakhia** [comment]
I am on empty line separator.

**Comment by TanayMorakhia** [comment]
I am on import order.

**Comment by pubudu91** [comment]
I am looking into `indentation`. Also, had a look at `packageobjectfactory`. Tried removing the usages of `AbstractCheck` class in the two `FooCheck` classes. But this caused test failures since `PackageObjectFactory.createModule()` method only loads sub classes of `AbstractAutomaticBean`. So maybe we'll have to keep the suppression for this?

**Comment by piyush-1234** [comment]
i am on classdataabstractioncoupling

**Comment by piyush-1234** [comment]
i am on unusedimports

**Comment by piyush-1234** [comment]
i am on unusedimports

**Comment by piyush-1234** [comment]
i am on classdataabstractioncoupling

**Comment by piyush-1234** [comment]
i am on javadocmetadatascraper

**Comment by piyush-1234** [comment]
looks like all suppression under #4845 has been done.

**Comment by romani** [comment]
@piyush-1234 , please remove comment and it will be finalized fix for this issue

**Comment by piyush-1234** [comment]
> @piyush-1234 , please remove comment and it will be finalized fix for this issue

on it @romani

**Comment by romani** [comment]
Final fix is merged
