### ISSUE TITLE
idea: fix ThisEscapedInConstructor idea violation for AbstractClassCouplingCheck.FileContext class

### ISSUE THREAD

**Issue by Nimfadora** [checkstyle/checkstyle#4861]
sub-task of #4681

fix 'this' reference escaped in object construction for [AbstractClassCouplingCheck.FileContext](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/AbstractClassCouplingCheck.java#L253) class

**Comment by rnveach** [comment]
@romani If we made `ClassContext` a nested class of `FileContext` and removed the static on the class so `this` is passed by the compiler, would the violation go away?

**Comment by romani** [comment]
yes, inspection tools trust compiler :). Compiler do a lot of links between objects that are not visible to human, it is ok. Humans care in code that they produce/see in priority. 

Generated byte code is not following best practices of design, as design is focused on human understanding of code, on byte code level nobody care about human, all focus is on JVM internals.

**Comment by rnveach** [comment]
@romani This produces another violation on my local intellij.
> 'ClassContext' is too deeply nested (nesting level = 2)

Do we want to increase the count, suppress it, move it to it's own file, or ... ?

**Comment by romani** [comment]
FileContext require redesign, to remove `private ClassContext classContext = new ..` from fields initialization at all, class context should be created only when class is detected, not when file processing is started.

**Comment by rnveach** [comment]
Fix was merged
