### ISSUE TITLE
idea: fix ThisEscapedInConstructor idea violation for ImportControl class

### ISSUE THREAD

**Issue by Nimfadora** [checkstyle/checkstyle#4863]
sub-task of #4681

fix 'this' reference escaped in object construction for [ImportControl](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControl.java#L122) class

**Comment by romani** [comment]
@Nimfadora , this should be addressed during this summer.

**Comment by Nimfadora** [comment]
@romani if we do like this than we create such situation:
this.parent = parent
parent.child = newItem
newItem != this

**Comment by romani** [comment]
@Nimfadora , I did atypo in my comment, please review.
Code should be fixed.

**Comment by romani** [comment]
Fix is merged
