### ISSUE TITLE
idea: fix ThisEscapedInConstructor idea violation for TreeTable class

### ISSUE THREAD

**Issue by Nimfadora** [checkstyle/checkstyle#4866]
sub-task of #4681

fix 'this' reference escaped in object construction for TreeTable class [here](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/gui/TreeTable.java#L72) and [here](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/gui/TreeTable.java#L79)

**Comment by romani** [comment]
I do no know how to make code better, GUI code is util code for us, so we could relax quality rules.
If smth know how to make code better feel free to reopen the issue.
