### ISSUE TITLE
internal code: terminolozy problems in ModuleReflectionUtils

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#4876]
[ModuleReflectionUtils](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/utils/ModuleReflectionUtils.java). 

There is method
```    
public static boolean isCheckstyleCheck(Class<?> clazz) {
        return AbstractCheck.class.isAssignableFrom(clazz);
}
```

Check is term that is used for both FileSet modules and TreeWalker modules.
[JavadocPackageCheck](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocPackageCheck.java) is also a Check but this method return false on it.
This is found during codereview at [TreeWalkerTest.testWithCheckNotHavingTreeWalkerAsParent](https://github.com/checkstyle/checkstyle/blob/master/src/test/java/com/puppycrawl/tools/checkstyle/TreeWalkerTest.java#L142)

**Comment by romani** [comment]
@rnveach , please review .

**Comment by rnveach** [comment]
@romani I see what you are saying but this never seemed like an issue for me since it's name is based on it's inheritance, but users may not know this.

I am not sure what we could rename this to as all our methods are named after the class/interface they extend/implement.
Should we name it `isCheckstyleTreeWalkerCheck`?

**Comment by romani** [comment]
> Should we name it isCheckstyleTreeWalkerCheck?

to smth like this or exactly like this.

> I assume we will not consider renaming modules that end with Check and are actually AbstractFileSets?

Modules are not rename-able.

**Comment by romani** [comment]
fix is merged
