### ISSUE TITLE
refactoring in configs

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#4877]
1) remove build.xml

2) put comment to catalog.xml to explain a reason of this file

3)
ant-phase-compile.xml generate only tokentypes.properties and it is required only in jars, can we do this (execute docklet) by maven ?

**Comment by rnveach** [comment]
> ant-phase-compile.xml

File is gone.

> 2. put comment to catalog.xml to explain a reason of this file

https://github.com/checkstyle/checkstyle/pull/4287#discussion_r114105443

> remove build.xml

File is also gone.

**Comment by romani** [comment]
Fix is merged
