### ISSUE TITLE
doc: update CLI steps to reproduce to result in English output

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#4881]
taken from #4846 .

example of user reported output:
```
/var/tmp $ java -jar checkstyle-8.1-all.jar -c config.xml Foo.java 
Beginne Prüfung...
[ERROR] /private/var/tmp/Foo.java:16:5: Redundant 'ANNOTATION' modifier. [RedundantModifier]Überflüssiger Modifier 'ANNOTATION'. [RedundantModifier]
Prüfung beendet.
Checkstyle endet mit 1 Fehlern.
```

it is ok.... but it would be better to do this in English, as our team know only English in languages that we support. We also welcoming all help from outside so English will be better for all.

github files for issue template need to  be updated to enforce locale to be English/US:
https://github.com/checkstyle/checkstyle/blob/master/.github/ISSUE_TEMPLATE.md
https://github.com/checkstyle/checkstyle/blob/master/src/xdocs/report_issue.xml

**Comment by subkrish** [comment]
@romani I tried this `java -jar -Duser.language=en-US checkstyle-8.1-all.jar -c config.xml Foo.java` but it doesn't seem to be working. Were talking about something like this?

**Comment by romani** [comment]
Yes smth like this, but it should work. May be smth else needs to be set  in addition to "user.language" , please google about it.

**Comment by rnveach** [comment]
@romani Both files you mentioned have already been updated. I think this issue has already been done so I am closing.
If you think another file needs to be changed, please re-open and specify the file.
