### ISSUE TITLE
Implement xpath query generator

### ISSUE THREAD

**Issue by MEZk** [checkstyle/checkstyle#4901]
We need to implement xpath query generator.  The query generator should receive root ast, column and line number in order to generate xpath expression. The generator should be represented by the separate class.

Possible algorithm:
1) Receive root ast, colum, line number.
2) Traverse the tree from the root to the target nodes.
3) Write Xpath starting from the root node to the target nodes.

Example. Generate xpath for all nodes with the lineNo = 2 and columnNo = 4.
AST:
```
CLASS_DEF -> CLASS_DEF [1:0]
|--MODIFIERS -> MODIFIERS [1:0]
|  `--LITERAL_PUBLIC -> public [1:0]
|--LITERAL_CLASS -> class [1:7]
|--IDENT -> TestClass [1:13]
`--OBJBLOCK -> OBJBLOCK [1:23]
    |--LCURLY -> { [1:23]
    |--METHOD_DEF -> METHOD_DEF [2:4]
    |  |--MODIFIERS -> MODIFIERS [2:4]
    |  |--TYPE -> TYPE [2:4]
    |  |  `--LITERAL_VOID -> void [2:4]
    |  |--IDENT -> foo [2:9]
    |  |--LPAREN -> ( [2:12]
    |  |--PARAMETERS -> PARAMETERS [2:13]
    |  |--RPAREN -> ) [2:13]
    |  `--SLIST -> { [2:15]
    |      `--RCURLY -> } [3:4]
    `--RCURLY -> } [4:0]
```

output should be all tokens for "[2:4]"

/CLASS_DEF[@text='TestClass']//OBJBLOCK//METHOD_DEF[@text='foo']
/CLASS_DEF[@text='TestClass']//OBJBLOCK//MODIFIERS
/CLASS_DEF[@text='TestClass']//OBJBLOCK//TYPE
/CLASS_DEF[@text='TestClass']//OBJBLOCK//LITERAL_VOID

Some examples of the implementation:
https://stackoverflow.com/questions/4746299/generate-get-xpath-from-xml-node-java

**Comment by MEZk** [comment]
@timurt 
Ping

**Comment by timurt** [comment]
@MEZk 

> Traverse the tree from the root to the target nodes.

We can make column number and line number attributes for our nodes, so xpath query will like `//*[@line=2 and @column=4]`

> Write Xpath starting from the root node to the target nodes.

After receiving list of nodes we can try to extract full path from each node using 'saxon:path()' query from saxon [documentation](http://www.saxonica.com/html/documentation9.4/extensions/functions/path.html) , it says 

> The function returns a string whose value is an XPath expression identifying the selected node in the source tree

I will try to test this function

**Comment by MEZk** [comment]
> We can make column number and line number attributes for our nodes, so xpath query will like //*[@line=2 and @column=4]

No need. Starting point is to generate XPath expressions for all nodes which match line and column number. First implementation should be simple. We need to allow the users to work with the new suppression model. All enhancements will be done later. 

> After receiving list of nodes we can try to extract full path from each node using 'saxon:path()' query from saxon documentation , it says

Ok, lets  try, Send me the commit with the implementation.

**Comment by timurt** [comment]
@MEZk 

> No need. Starting point is to generate XPath expressions for all nodes which match line and column number. First implementation should be simple. We need to allow the users to work with the new suppression model. All enhancements will be done later.

Do you assume to iterate all tree, visit all nodes and compare `lineNumber` and `columnNumber` variables?

> After receiving list of nodes we can try to extract full path from each node using 'saxon:path()' query from saxon documentation , it says

It seems like `saxon:path()` function is the part of commercial release. 

> Write Xpath starting from the root node to the target nodes.

I think we can store `xpathExpression` as field inside node, value should be initialized when node is created using `xpathExpression` of the parent and attributes of the current node

**Comment by timurt** [comment]
@MEZk 
My [commit](https://github.com/timurt/checkstyle/commit/647e9b1e6b223557903fe7153a8544b90133e081)  with two approaches.

First one uses plain `DetailAst` functionality, traverses the tree, finds nodes with same line and column number, after recursively generate xpath query for each node

Another one makes xpath queries to extract all nodes matching line and column (`//*[@line=2 and @column=4]`). For each node I additionally store `xpathQuery` variable, which initializes inside constructor

What do you think

**Comment by MEZk** [comment]
> Another one makes xpath queries to extract all nodes matching line and column (//*[@line=2 and @column=4])

This is not correct. The main IDEA of xpath is to get rid of line and column number in suppressions.

**Comment by timurt** [comment]
@MEZk 
what do you think about querying elements based on child element attribute, for example 
if we have source code like this
```
import javax.swing.JToolBar;
import java.io.File;
public class InputXpathQueryGenerator {
}
```
We can query first import by two expressions
`//IMPORT[1]`
`//IMPORT[/DOT/DOT[@text='javax']] `
First one is simpler, but now we do not store sibling position
Second one uses attribute value of the child, but we should make sure `/DOT/DOT[@text='javax']` is unique across all imports statements

**Comment by MEZk** [comment]
@timurt 
Lets implement the second approach for now. It is easier and does not require changes in Xpath-Tree.

> Second one uses attribute value of the child, but we should make sure /DOT/DOT[@text='javax'] is unique across all imports statements

We will solve this problem, when it really appears. Do not waste time on overengineering.

**Comment by rnveach** [comment]
Fix was merged

**Comment by rnveach** [comment]
Marked as miscellaneous since it is not released to the users yet.
