### ISSUE TITLE
Remove thread-unsafe context from the AbstractFileSetCheck class

### ISSUE THREAD

**Issue by soon** [checkstyle/checkstyle#4917]
Now the AbstractFileSetCheck class contains some thread-unsafe context, therefore we cannot use the same check instance across multiple threads.

All thread-unsafe members should be rewritten so that they could be used from the separate threads:

`messageCollector` - it is updated inside `process` method and via `addMessages` and other methods.

**Comment by romani** [comment]
fix is merged
