### ISSUE TITLE
OverloadMethodsDeclarationOrderCheck: warning message is unclear

### ISSUE THREAD

**Issue by tjoneslo** [checkstyle/checkstyle#4921]
See also #3770

We enabled the `OverloadMethodsDeclarationOrderCheck` in our project, and one of our team got the message :  `Overload methods should not be split. Previous overloaded method located at line '545'.`

The comment was:  The above error message isn’t really clear about what the problem was. I wasn’t sure what “splitting” methods meant.

We discussed this and figured out what the message meant, but everyone agreed that "Splitting" in this context was not entirely clear. 

The suggestion for the warning message was: 

`All overloaded methods should be placed next to each other. Placing non-overloaded methods in between overloaded methods with the same type is a checkstyle violation.`
or further extended if possilbe/reasonable `The offending method is <name and line and class of offending method> and it is splitting up the overloaded methods <name and line and class of overloaded method above> and <name and line and class of overloaded method below>`

**Comment by strkkk** [comment]
Fix is merged
