### ISSUE TITLE
Remove thread-unsafe context from the AbstractJavadocCheck class 

### ISSUE THREAD

**Issue by soon** [checkstyle/checkstyle#4925]
Now the `AbstractJavadocCheck` class contains some thread-unsafe context, therefore we cannot use the same check instance across multiple threads.

All thread-unsafe members should be rewritten so that they could be used from the separate threads:

1. `parser` - the `JavadocDetailNodeParser` isn't a thread-safe class
1. `blockCommentAst` - the `AbstractJavadocCheck` updates this field in the `visitToken` method

**Comment by sabaka** [comment]
merged
