### ISSUE TITLE
SeverityLevelCounter should be thread-safe

### ISSUE THREAD

**Issue by soon** [checkstyle/checkstyle#4927]
Now the `SeverityLevelCounter` uses `int count` to track the number of errors with the specified `SeverityLevel`. However, this is not thread-safe, because `int` incrementation is not an atomic operation and therefore may lead to unpredictable results.

**Comment by rnveach** [comment]
@soon `SeverityLevelCounter` is an AuditListener.
Will all listeners be multi-threaded? How will this affect text and xml output in DefaultLogger and XmlLogger?
Won't we need to synchronize these areas to prevent garbling the output?

**Comment by soon** [comment]
@rnveach, Yes, I'm preparing a PR for `XmlLogger`. There is a problem with `fileStarted` and `fileFinished` methods.

`DefaultLogger` works fine, according to my tests. Seems like the `PrintWriter` synchronizes write operations, however, I haven't found a documentation for this behavior. I'll also prepare a PR for `DefaultLogger`, this seems to be an easy fix

**Comment by rnveach** [comment]
> Seems like the PrintWriter synchronizes write operations, however, I haven't found a documentation for this behavior.

http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/6-b14/java/io/PrintWriter.java#427
I am seeing synchronizations all over.
Maybe as long as the full line is given, it won't bash 2 lines together. I would be careful if we only print portions of the line though.

**Comment by soon** [comment]
> I am seeing synchronizations all over.

The documentation says only about `lock` field inside `Writer` class (https://docs.oracle.com/javase/7/docs/api/java/io/Writer.html):

> The object used to synchronize operations on this stream. 

However, the `PrintWriter` class does not give any guarantees about thread-safety (https://docs.oracle.com/javase/7/docs/api/java/io/PrintWriter.html#write(char[]))

**Comment by sabaka** [comment]
merged
