### ISSUE TITLE
AuditEventDefaultFormatterTest should not use PowerMockito for testing

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#4931]
from https://github.com/checkstyle/checkstyle/pull/4899/commits/0dc6ed77dbc99c1b5934dd06415f367a89625eab#r131657399

AuditEventDefaultFormatterTest can create AuditEvent class and fill it with all required values  for testing. Mocks are not required here.

**Comment by rnveach** [comment]
@romani I started looking into this and mocks may be required for 2 of the tests.

[`testFormatModuleNameContainsCheckSuffix`](https://github.com/checkstyle/checkstyle/blob/78de3dc771531cfee50a60ff2cee80c46b83c43b/src/test/java/com/puppycrawl/tools/checkstyle/AuditEventDefaultFormatterTest.java#L75) mocks the source name as `TestModuleCheck`. Source name comes from [`LocalizedMessage` which gets the value from the actual Class object given to it](https://github.com/checkstyle/checkstyle/blob/78de3dc771531cfee50a60ff2cee80c46b83c43b/src/main/java/com/puppycrawl/tools/checkstyle/api/LocalizedMessage.java#L391).
The only way we can duplicate this without a mock is if the source we give it is in the base package, IE directly in `src/test/java`.

Without these cases, [we lose coverage in `AuditEventDefaultFormatter.getCheckShortName` for the `true` condition of `if (lastDotIndex == -1) {`](https://github.com/checkstyle/checkstyle/blob/78de3dc771531cfee50a60ff2cee80c46b83c43b/src/main/java/com/puppycrawl/tools/checkstyle/AuditEventDefaultFormatter.java#L104).

**Comment by romani** [comment]
@rnveach ,

> I started looking into this and mocks may be required for 2 of the tests.

I fine with mocks, till it is reasonable. I will be good to have a rule that demand javadoc over test method if test is using mock. Engineers hate javadoc writing, so it will force them to think about more functional test, and it is ease to catch in codereview.
Meanwhile let update code that is easy to update and keep mocks in complicated cases only with explanation like "argument is Class type, that is final , no way to easily mock it so we use powermock".

> directly in src/test/java

I do not like this.

>  we lose coverage in

we need coverage as coverage help more that a bit weird code.

> Source name comes from LocalizedMessage which gets the value from the actual Class object given to it.

it is a sign of design problem that API class takes a `Class` as argument by in real life use only String identifier from it. This argument should be a of `String` type and probably completely deprecated in favor of `moduleId`.
If you agree lets make this this API change a separate issue.

**Comment by rnveach** [comment]
> a sign of design problem that API class takes a Class as argument by in real life use only String identifier from it

It is only used by us for a String. AuditEvents get sent to listeners, so they could want the class object for some reason, like if they want to know who is sending the message.
I assume you don't want to keep both class object and module name/id but rely on the name/id more?

> This argument should be a of String type and probably completely deprecated in favor of moduleId.

Module ID is only set if the module has an ID, so we would need to change more code to swap between module name and ID depending on which is set.

**Comment by romani** [comment]
> AuditEvents get sent to listeners, so they could want the class object for some reason, like if they want to know who is sending the message.

"who sending message" is identifier, identifier should be a string as more flexible data type. String could contain simple name of class or some ID, or some formatted string or ..... .

> I assume you don't want to keep both class object and module name/id but rely on the name/id more?

yes, we could even go further eventually and keep only `id` field. Identification filed should be alone it is enough.

> Module ID is only set if the module has an ID, so we would need to change more code to swap between module name and ID depending on which is set.

yes.

**Comment by rnveach** [comment]
> String could contain simple name of class or some ID, or some formatted string or ..... .

I was referring to a custom listener may want the physical class, and we only give him simple name/ID.

Let's create a new issue.
We can close this one, right?

**Comment by romani** [comment]
> We can close this one, right?

do you agree to make rule to put comment on methods that can not be done withtout mocks?
There is still one test method I think we need to left a comment why it use mocks.

**Comment by rnveach** [comment]
I am fine with this rule. Should we make a new issue for all mocks we have?

**Comment by romani** [comment]
> Let's create a new issue.

#4969

> Should we make a new issue for all mocks we have?

lets create, till it not automated, lets try to demand this in PRs.

**Comment by rnveach** [comment]
> lets create, till it not automated, lets try to demand this in PRs.

#4970

**Comment by rnveach** [comment]
Closing issue as it should be fixed. Other issue to document tests is still open.
