### ISSUE TITLE
XMLLogger methods should be thread-safe

### ISSUE THREAD

**Issue by soon** [checkstyle/checkstyle#4932]
Now the output of `XMLLogger` might be corrupted, if several threads will try to raise errors for the different files at the same time.

The `fileStarted`, `fileFinished`, `addError` and `addException` methods must be thread-safe

**Comment by soon** [comment]
@rnveach @romani I have a question about the `addException` method. Is it used by anyone? I've found only tests for this method.

**Comment by rnveach** [comment]
> addException method. Is it used by anyone? I've found only tests for this method.

@soon See https://github.com/checkstyle/checkstyle/issues/4377 .

**Comment by romani** [comment]
fix is merged.

**Comment by romani** [comment]
@soon ,  please provide fix for pitest failure ASAP:
```Survived items:target/pit-reports/201708290005/com.puppycrawl.tools.checkstyle/XMLLogger.java.html:<td class='survived'> target/pit-reports/201708290005/com.puppycrawl.tools.checkstyle/XMLLogger.java.html:<td class='covered'><pre><span class='survived'> fileMessages.clear();</span></pre></td></tr>
Survived items found in reports, build will be failed
```
https://app.shippable.com/github/checkstyle/checkstyle/runs/4762/19/console
Please also rebase all your further PRs to avoid such issue again.

**Comment by romani** [comment]
I moved this problem to separate issue #5022, as problem is not stable and probably related to shippable ....

**Comment by soon** [comment]
@romani Created pr which should fix the pitest coverage: https://github.com/checkstyle/checkstyle/pull/5025
