### ISSUE TITLE
Making required arguments mandatory for javadoc tags in grammar

### ISSUE THREAD

**Issue by ps-sp** [checkstyle/checkstyle#4942]
$ cat test.javadoc 
```
* @author
```

$ java -jar master-8.2-all.jar -j test.javadoc 
```
JAVADOC -> JAVADOC [0:0]
|--LEADING_ASTERISK -> * [0:0]
|--WS ->   [0:1]
|--JAVADOC_TAG -> JAVADOC_TAG [0:2]
|   |--AUTHOR_LITERAL -> @author [0:2]
|   `--NEWLINE -> \n [0:9]
`--EOF -> <EOF> [1:0]
```

$ cat test.javadoc 
```
* @exception
```

$ java -jar master-8.2-all.jar -j test.javadoc 
```
JAVADOC -> JAVADOC [0:0]
|--LEADING_ASTERISK -> * [0:0]
|--WS ->   [0:1]
|--JAVADOC_TAG -> JAVADOC_TAG [0:2]
|   |--EXCEPTION_LITERAL -> @exception [0:2]
|   `--NEWLINE -> \n [1:0]
`--EOF -> <EOF> [2:0]
```

$ cat test.javadoc 
```
* @param
```

$ java -jar master-8.2-all.jar -j test.javadoc 
```
JAVADOC -> JAVADOC [0:0]
|--LEADING_ASTERISK -> * [0:0]
|--WS ->   [0:1]
|--JAVADOC_TAG -> JAVADOC_TAG [0:2]
|   `--PARAM_LITERAL -> @param [0:2]
`--EOF -> <EOF> [0:8]
```

$ cat test.javadoc 
```
* @return
```

$ java -jar master-8.2-all.jar -j test.javadoc 
```
JAVADOC -> JAVADOC [0:0]
|--LEADING_ASTERISK -> * [0:0]
|--WS ->   [0:1]
|--JAVADOC_TAG -> JAVADOC_TAG [0:2]
|   `--RETURN_LITERAL -> @return [0:2]
`--EOF -> <EOF> [0:9]
```

Javadoc trees are parsed when checkstyle should rightfully throw error for such inappropriately constructed javadocs. ANTLR grammar should be updated in all the required places for this and in javadoc tags which are supposed to have atleast 1 argument, the corresponding element must not allowed to be made optional in the grammar. For example [`CLASS_NAME` shouldn't be optional in `@exception` literal.](https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/com/puppycrawl/tools/checkstyle/grammars/javadoc/JavadocParser.g4#L873)

**Comment by Vladlis** [comment]
@ps-sp , please provide links to documentation for each case

**Comment by ps-sp** [comment]
@Vladlis 

> please provide links to documentation for each case

Can you please tell me what links are you exactly referring to ? The report for `description` in Javadoc tags that I provided already has hyperlinks for corresponding documentations ?

**Comment by Vladlis** [comment]
@ps-sp 
You have to prove your statement that tags from the issue description
> are supposed to have atleast 1 argument

**Comment by ps-sp** [comment]
@Vladlis 

>You have to prove your statement that tags from the issue description

It can't be proved exactly for every tag since javadoc tool results in successful site rendering even with no arguments. For example: even with no argument for `@exception` javadoc tool just gave a warning message and executed anyway. Though as can be seen from syntax in docs and intuition, one can only intuitively argue where an argument must be present for a javadoc tag and where it need not be. 

I feel we will have to create our own list of javadoc tags where checkstyle would enforce a description based on the oracle docs and the report on javadoc tags that we have.

**Comment by romani** [comment]
fix is merged.
If smth is left - it should be separate issue.
