### ISSUE TITLE
Extend Checkstyle GUI tool to work with Xpath

### ISSUE THREAD

**Issue by MEZk** [checkstyle/checkstyle#4944]
The original idea is taken from @timurt's  proposal.

![1](https://user-images.githubusercontent.com/7242568/29248634-a893cf38-8025-11e7-85e0-4123a9622670.png)

AST container, source code container and XPATH container are all bound together. For example if you select ast nodes, source code lines containing appropriate elements will be highlighted. Also xpath query will be automatically generated. We can think about opportunity for “and”ing / “or”ing ast nodes via SHIFT/CTRL buttons, also we can add additional buttons for xpath query generator.

![2](https://user-images.githubusercontent.com/7242568/29248644-d7427726-8025-11e7-8d37-d5d6f00d03b3.png)

![3](https://user-images.githubusercontent.com/7242568/29248651-edb98b84-8025-11e7-99f9-e87a05c2467a.png)

Another situation, if we write query and press “Run xpath” button, ast nodes will be selected and source code elements will be selected.

![4](https://user-images.githubusercontent.com/7242568/29248661-068f952c-8026-11e7-92ea-9c9a15a6ae57.png)

Some ideas on how to make it and implement it could be taken from https://pmd.github.io/latest/pmd_userdocs_extending_designer_reference.html

-------

<a href="https://www.bountysource.com/issues/48207721-extend-checkstyle-gui-tool-to-work-with-xpath">
<img src="https://api.bountysource.com/badge/issue?issue_id=48207721">
</a>

**Comment by romani** [comment]
this issue is lower priority of GSoC tasks.
It is better to finish CLI version of xpath generator and make sure that filter is supporting all Checks.

**Comment by developerhb** [comment]
@romani Is anyone working on this issue? If not, I would like to work on this.

**Comment by developerhb** [comment]
@MEZk @romani @timurt 
I have created PR https://github.com/checkstyle/checkstyle/pull/8247 with the Layout Implementation. For further implementations I have following questions.

1. What is the functionality of AND, OR and NOT buttons?
2. What is the functionality of Reset button?

**Comment by romani** [comment]
> What is the functionality of AND, OR and NOT buttons?

lets ignore them for now, I do not understand this also.

> What is the functionality of Reset button?

it might be mean clean of xpath text area, we can skip this button. user can easily remove content himself.

**Comment by romani** [comment]
for generation of xpath, please refer to https://checkstyle.org/cmdline.html#Command_line_usage `-g,--generate-xpath-suppression`

**Comment by timurt** [comment]
> What is the functionality of AND, OR and NOT buttons?

As far as I remember these buttons were for query building, by selecting elements and clicking or/and/not buttons you could construct xpath queries.

But @romani is right, it can be ignored for now

**Comment by developerhb** [comment]
Okay @romani @timurt 
For now I will remove those buttons and only keep a single button `Run`

**Comment by developerhb** [comment]
@romani I am still somewhat confuse with the generation of xpath query. Can you please provide more information about it.

**Comment by romani** [comment]
@developerhb , probably it would be good if ask questions or share some concerns.

When use click on node we print path to it as simple as list of all node from root to selected node. 
`/CLASS_DEF/OBJBLOCK/CTOR_DEF/SLIST`
It is very basic implementation and it will not work always, because if there is on some level few nodes of same type - xpath will be confused. So you need to provide `IDENT[@text='Test']` to nodes where are some siblings of the same type:
`/CLASS_DEF[./IDENT[@text='Test']]/OBJBLOCK/CTOR_DEF[./IDENT[@text='Test']]/SLIST`.
Main point is you generate xpath till you match node user is selected in AST.
While it is not matching you put more and more details (attributes) in some parent till match proper node, and you move on level dipper. So you go from top(root) and as you already path you just go on level deeper and put more and more details in node of this level to let xpath find node, then go on level deeper, ... .

I recommend to make:
 one PR - user put xpath and you find it in tree.
second PR - generation of xpath

**Comment by developerhb** [comment]
@romani 
I understand the point.

>I recommend to make:
one PR - user put xpath and you find it in tree.
second PR - generation of xpath

I am working on it.

**Comment by developerhb** [comment]
@romani 
I would like to know what is difference between `DetailAST` and `DetailNode`. I understand the Xpath Generation for `DetailAST`. But, I don't know much about `DetailNode`. Please guide me.

**Comment by developerhb** [comment]
@romani 
I figured out that there is already an existing method `XpathQueryGenerator.java` in package `com.puppycrawl.tools.checkstyle.xpath`. But it only works with `DetailAST`. I tried to implement it and it worked. 

Now question is for `DetailNode`. In which condition we have a `DatailNode`.

**Comment by romani** [comment]
https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/DetailNode.java

is `DetailAST` for javadoc trees. We do not support xpath on javadoc for now. when you user want to get xpath on it, you can print in Xpath text area `xpath is not supported yet for javadoc nodes`

**Comment by developerhb** [comment]
@romani 
Okay I got it. Now, the PR https://github.com/checkstyle/checkstyle/pull/8247 is for layout changes. I want to create a new PR for `generation of Xpath`. But it is completely dependent on the PR that has layout changes. What can I do in such situations?

**Comment by romani** [comment]
you can make new branch that is based on branch of #8247 and continue development (but keep all new changes in seperate commit - 2 commits) and event send PR. in PR description just mention that first commit should not be reviewed as it is from #8247 and such PR depends on another PR. 
no matter how much changes will be in #8247 , you do not reabse on that branch. 
Ones #8247  is merged, you will recreated branch by cherry picking of separate commit.

**Comment by developerhb** [comment]
@romani before I can create PR for `xpath generation`, I have few questions.

There is existing class named `XpathQueryGenerator.java` which generates xpath query. It has several methods. Out if those, `generateXpathQuery(ast)` is useful in our case. It gives the xpath query of AST Node from the root AST node. But this is private. So, I created following method in `XpathQueryGenerator.java`.

```java
public String generateXpathForGUI(DetailAST ast) {
        return generateXpathQuery(ast);
    }
```

After this change I am getting following error in `mvn clean verify`

```
[INFO] --- jacoco-maven-plugin:0.8.5:check (default-check) @ checkstyle ---
[INFO] Loading execution data file F:\College\checkstyle\target\jacoco.exec
[INFO] Analyzed bundle 'checkstyle' with 540 classes
[WARNING] Rule violated for class com.puppycrawl.tools.checkstyle.xpath.XpathQueryGenerator: lines covered ratio is 0.98, but expected minimum is 1.00
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  39:33 min
[INFO] Finished at: 2020-06-08T19:46:14+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.jacoco:jacoco-maven-plugin:0.8.5:check (default-check) on project checkstyle: Coverage checks have not been met. See log for details. -> [Help 1]
```

Please help me in solving this error.

**Comment by developerhb** [comment]
@romani another question is, I added following code in the `TreeTable.java` class. This code is used to generate the xpath of the node selected.

```java
private void generateXpath() {
        if (tree.getLastSelectedPathComponent() instanceof DetailAST) {
            try {
               final FileText fileText = new FileText(file,StandardCharsets.UTF_8.name());
               final DetailAST rootAST = (DetailAST) tree.getModel().getRoot();
               final DetailAST ast = (DetailAST) tree.getLastSelectedPathComponent();
               final int DEFAULT_TAB_WIDTH = 4;

               final XpathQueryGenerator queryGenerator = new XpathQueryGenerator(rootAST,
               ast.getLineNo(), ast.getColumnNo(),
               fileText, DEFAULT_TAB_WIDTH);

               xpathEditor.setText(queryGenerator.generateGUI(ast));
            }
            catch (Exception exp) {
                //do something
            }
        }
        else {
            xpathEditor.setText("Xpath is not supported yet forr javadoc nodes");
        }
    }
```

Here the statement `final FileText fileText = new FileText(file,StandardCharsets.UTF_8.name());` throws an **IOException**. So, I used try and catch block. But I cannot figure out what task to perform in catch block.

Please guide me in this.

**Comment by romani** [comment]
> Please help me in solving this error.

lets make method public.

> But I cannot figure out what task to perform in catch block.

yes, we do not have any place  in UI where to show exception, lets print exception to textarea where generated xpath suppose to appear. User will notice it it quickly and I hope it will help him to resolve issue.

**Comment by developerhb** [comment]
> lets make method public.

Okay I will make it public.

> yes, we do not have any place in UI where to show exception, lets print exception to textarea where generated xpath suppose to appear. User will notice it it quickly and I hope it will help him to resolve issue.

Okay. Do we need to make it red in color? 
Also, do we need the exception to be printed as it as (default message by java) or we need to process it?

**Comment by romani** [comment]
> Also, we need to make it non-static as we need to access it using an object

static means that you can use method withtout object `XpathQueryGenerator.generateXpathQuery`.

> Do we need to make it red in color? .. or we need to process it?

no need. Simple print is enough.

**Comment by developerhb** [comment]
> static means that you can use method withtout object XpathQueryGenerator.generateXpathQuery.

This method was meant to be used inside the class only. So, it was `private` and `static`. Now, we need to call this method for an object. Like,

```java
final XpathQueryGenerator queryGenerator = new XpathQueryGenerator(rootAST,
               ast.getLineNo(), ast.getColumnNo(),
               fileText, DEFAULT_TAB_WIDTH);

xpathEditor.setText(queryGenerator.generateXpathQuery(ast));
```
The above code cannot be written if the method is static.

Also, if I make the method non-static, it creates problem in below given method. Which is also of class `XpathQueryGenerator`

```java
public List<String> generate() {
        return getMatchingAstElements()
            .stream()
            .map(XpathQueryGenerator::generateXpathQuery)
            .collect(Collectors.toList());
    }
```

**Comment by developerhb** [comment]
>  please copy this method to your code and work with it, we will review your problems during PR review. Just put a comment on it that it was copy pasted.

This also not possible since it uses number of other methods of class `XpathQueryGenerator`. So, we need to find some other way.

**Comment by developerhb** [comment]
@romani 
I solved the above problem.

I made the method `generateXpathQuery()` **public** and **non-static** and made following changes in method `generate()`

```java
public List<String> generate() {
        return getMatchingAstElements()
            .stream()
            .map((ast) -> {
            return generateXpathQuery(ast);
        })
            .collect(Collectors.toList());
    }
```
I used `lambda-expression`

**Comment by developerhb** [comment]
@romani 
Please help me in solving the following error is `mvn clean verify`

```

[INFO] --- maven-antrun-plugin:3.0.0:run (ant-phase-verify) @ checkstyle ---
[INFO] Executing tasks
[INFO]      [echo] Checkstyle started (checkstyle_checks.xml): 14/06/2020 08:36:24 AM
[INFO] [checkstyle] Running Checkstyle  on 1157 files
[ERROR] [checkstyle] [ERROR] F:\College\checkstyle\src\main\java\com\puppycrawl\tools\checkstyle\gui\TreeTable.java:30:1: Disallowed import - java.nio.charset.StandardCharsets. [ImportControlMain]

[ERROR] [checkstyle] [ERROR] F:\College\checkstyle\src\main\java\com\puppycrawl\tools\checkstyle\gui\TreeTable.java:47:1: Disallowed import - com.puppycrawl.tools.checkstyle.xpath.XpathQueryGenerator. [ImportControlMain]

[ERROR] [checkstyle] [ERROR] F:\College\checkstyle\src\main\java\com\puppycrawl\tools\checkstyle\gui\TreeTable.java:167:26: Abbreviation in name 'DEFAULT_TAB_WIDTH' must contain no more than '1' consecutive capital letters. [AbbreviationAsWordInName]

[ERROR] [checkstyle] [ERROR] F:\College\checkstyle\src\main\java\com\puppycrawl\tools\checkstyle\gui\TreeTable.java:167:26: Name 'DEFAULT_TAB_WIDTH' must match pattern '^[a-z][a-zA-Z0-9]*$'. [LocalFinalVariableName]
```

**Comment by romani** [comment]
You need to allow import at https://github.com/checkstyle/checkstyle/blob/master/config/import-control.xml#L158 we do this to control dependencies between packages and ... We are library project, not a final application, so it makes sense.

**Comment by developerhb** [comment]
@romani 
Also I am getting this error. 

```
[ERROR] [checkstyle] [ERROR] F:\College\checkstyle\src\main\java\com\puppycrawl\tools\checkstyle\gui\TreeTable.java:167:26: Abbreviation in name 'DEFAULT_TAB_WIDTH' must contain no more than '1' consecutive capital letters. [AbbreviationAsWordInName]

[ERROR] [checkstyle] [ERROR] F:\College\checkstyle\src\main\java\com\puppycrawl\tools\checkstyle\gui\TreeTable.java:167:26: Name 'DEFAULT_TAB_WIDTH' must match pattern '^[a-z][a-zA-Z0-9]*$'. [LocalFinalVariableName]
```

**Comment by developerhb** [comment]
@romani 

In this code,
```java
public List<String> generate() {
        return getMatchingAstElements()
            .stream()
            .map((ast) -> {
                return generateXpathQuery(ast);
            })
            .collect(Collectors.toList());
    }
```

I am getting this error.

```
[ERROR] [checkstyle] [ERROR] F:\College\checkstyle\src\main\java\com\puppycrawl\tools\checkstyle\xpath\XpathQueryGenerator.java:145:24: Unnecessary parentheses around lambda value. [UnnecessaryParentheses]

```
How can I solve this? I have used lambda expressions for first time. So, I can't figure out this error.

**Comment by developerhb** [comment]
@romani The above errors are resolved.

**Comment by romani** [comment]
@developerhb , I am right that only positioning in Tree by xpath is left to implement ?

**Comment by developerhb** [comment]
> @developerhb , I am right that only positioning in Tree by xpath is left to implement ?

Yes finding node in tree by xpath is remaining to implement.

I am trying to figure out a way to select the node in Tree programmatically.

**Comment by developerhb** [comment]
@romani I figured out how to select the node in Tree programmatically.

But I am stuck on how to search a node in the tree.
The first approach which comes to mind is to do linear search by checking the xpath of each and every node with the input xpath. But its time complexity is very high and I am not able to figure out any other way to do this.

Please help.

**Comment by romani** [comment]
Application with Bad performance is better than not working application.
Please send PR with what you have. We can review and suggest something.

**Comment by developerhb** [comment]
Okay @romani I am working on it.

**Comment by developerhb** [comment]
@romani Sorry for being late.

I have completed the code.

I have made use of `Stack` in the code. Also, I have used recursion so my function is having multiple return statements for multiple conditions.

I am getting following errors in `mvn clean verify`

```
[INFO] --- maven-checkstyle-plugin:3.1.1:check (sevntu-checkstyle-check) @ checkstyle ---
[INFO] There are 3 errors reported by Checkstyle 8.29 with F:\College\checkstyle/config/checkstyle_sevntu_checks.xml ruleset.
[ERROR] src\main\java\com\puppycrawl\tools\checkstyle\gui\TreeTable.java:[31,1] (extension) ForbidCertainImports: Import 'java.util.Stack' should not match 'java\.util\.Stack|java\.util\.Vector|             com\.google\.collect\.Iterables|com\.google\.common\.annotations\.Beta|             com\.google\.common\.base\.Predicate|com\.google\.common\.base\.String||             com\.google\.common\.base\.Function|com\.google\.common\.base\.Supplier|             com\.google\.common\.base\.Charsets|com\.google\.common\.base\.MoreObjects|             com\.google\.common\.base\.Equivalence|com\.google\.common\.base\.Preconditions|             com\.google\.common\.base\.Optional|com\.google\.common\.io\.CharSource|             com\.google\.common\.primitives.*|com\.google\.common\.collect\.Sets|             com\.google\.common\.collect\.Queues|com\.google\.common\.collect\.Lists|             com\.google\.common\.annotations\.GwtCompatible|com\.google\.common\.io\.Files|             com\.google\.common\.collect\.TreeTraverser' pattern, it is forbidden.
[ERROR] src\main\java\com\puppycrawl\tools\checkstyle\gui\TreeTable.java:[202,21] (extension) ReturnCountExtended: Return count for 'search' method is 2 (max allowed is 1).
[ERROR] src\main\java\com\puppycrawl\tools\checkstyle\gui\TreeTable.java:[230,38] (extension) ForbidInstantiation: Instantiation of 'Stack' is not allowed.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

**Note:**
I have added `<allow class="java.util.Stack" />` in `import-control.xml`.

Help me with this.

**Comment by romani** [comment]
Please send PR to let me see whole code

**Comment by developerhb** [comment]
@romani I have created PR https://github.com/checkstyle/checkstyle/pull/8591. I will add description later when the errors are solved.

**Comment by pbludov** [comment]
Fix is merged. @developerhb is everything done in this issue?

**Comment by developerhb** [comment]
@pbludov 
> Fix is merged. @developerhb is everything done in this issue?

Yes. As far as I know, everything is done.

**Comment by developerhb** [comment]
This issue is closed. Thank you @MEZk @romani @timurt and @pbludov for helping me in this issue.

**Comment by developerhb** [comment]
@romani 
How can I claim the bounty of this issue?
