### ISSUE TITLE
IllegalTypeCheck: split illegalClassNames for short names to prevent runtime modification

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#4947]
Identified at https://github.com/checkstyle/checkstyle/issues/4870#issuecomment-322240469 and shown during analysis at https://github.com/checkstyle/checkstyle/issues/4870#issuecomment-322245561 ,

We shouldn't be modifying user defined `illegalClassNames` during execution of the check.
https://github.com/checkstyle/checkstyle/blob/78de3dc771531cfee50a60ff2cee80c46b83c43b/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java#L352

We should only have to do this once in the setter. It is weird to do this during check execution and will cause issues with multi-threaded mode.
Since this is the only thing `IMPORT` token does, it can be removed from this check.

**Comment by rnveach** [comment]
I was slightly mistaken on this issue.
We are only adding short names to `illegalClassNames` if the full import is found in the import list.
[This can be seen with `testSameFileNameFalsePositive`](https://github.com/checkstyle/checkstyle/blob/acdbc55974c3fd6b6e532a29e443bce60016791f/src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheckTest.java#L122) as it produces no violations on [Line 24](https://github.com/checkstyle/checkstyle/blob/89710906a8d822baead10b34a5d6cde88133370e/src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeSameFileName.java#L24) because [we are importing `java.awt.List`](https://github.com/checkstyle/checkstyle/blob/89710906a8d822baead10b34a5d6cde88133370e/src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeSameFileName.java#L3).

We can't remove `IMPORT` token.
To resolve this issue for multi-threaded mode, I believe we have to have a new list of classes that are allowed to be flagged as short names, which must be reset for every new file.
There is no reset right now so this check might have issues when running with multiple files which we won't see in our single file test tier.

**Comment by romani** [comment]
fix is merged
