### ISSUE TITLE
Rename Filters which aren't module filters to FilterElement

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#4978]
https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressElement.java#L42-L43
It is slightly confusing to see `SuppressElement` implement the filter interface even though it isn't a direct filter. The true filter is [`SuppressionFilter`](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionFilter.java) which fully meets the requirements of a filter by extending `AutomaticBean`.
`SuppressElement` is more a sub-child of `SuppressionFilter` and therefore is more a `FilterElement`.

The following classes should be renamed as `FilterElement`s too if they have that in their name.
* CsvFilter
* IntFilter
* IntMatchFilter
* IntRangeFilter
* SuppressElement

**Comment by rnveach** [comment]
@romani Please review this issue.

**Comment by romani** [comment]
it is ok, as all of them could just do filtering by simple method. And it really does not matter are you upper level filter class or not.
The same we have in tree , all of them are AST nodes but only one is root, from where we start traversing.

Do you have more concerns/thoughts with such interface ?

**Comment by rnveach** [comment]
My only concern is that it is confusing that they are all named `Filter` even though they aren't filter modules and it is slightly hard to discern them just from the file names unless you are very familiar with them.

> The same we have in tree 

But we don't have the same for modules as we have a `RootModule`.
The difference here is only the root filter can be placed in the config. With AST nodes, you can send any node to a method and it works the same if it is the root or not.

If you don't want a new interface for them, I feel we should at least rename them to `SubFilter` for all except `SuppressElement`.

**Comment by romani** [comment]
I am agree with names of classes .... we can make them more distinguishable, to not have Filter as suffix ..... What about FilterElement, FilterItem

```
    CsvFilterElement
    IntFilterElement
    IntMatchFilterElement
    IntRangeFilterElement
    SuppressElement
```
or
```
    CsvFilterItem
    IntFilterItem
    IntMatchFilterItem
    IntRangeFilterItem
    SuppressElement
```

any better names ?

**Comment by rnveach** [comment]
right now I prefer `FilterElement` if you don't like `SubFilter`.

> SuppressElement

You don't like renaming this to `SuppressFilterElement`? I only recommended skipping it before since `SuppressElementSubFilter` would look odd.

**Comment by romani** [comment]
> if you don't like SubFilter

I think last word `Filter` will cause the same problem as right now. So it is better to change names significantly.

> You don't like renaming this to SuppressFilterElement?

I am ok to rename.

**Comment by rnveach** [comment]
@romani I updated the first post, please put approve.

**Comment by romani** [comment]
@rnveach ,
please remove SubFilter completely from title and description as now I not completely sure what we suppose to do. I will remove all comments as you correct description.

**Comment by rnveach** [comment]
Done.

**Comment by rnveach** [comment]
`XpathFilter` was added to the list.

**Comment by rnveach** [comment]
@romani Issue is done, but some `FilterElements` still implement `Filter`.
Do we want to make a change for this? Issue doesn't declare this really.

**Comment by romani** [comment]
I do not think it is required. I think name is ok.
