### ISSUE TITLE
MissingDeprecatedCheck is using regexp parsing inspead of AST 

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#4983]
https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/MissingDeprecatedCheck.java
use old approach to parse javadoc and creates false positives on code like - https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java#L72.
```
    /**
     * '{@literal @}deprecated' literal in {@literal @}deprecated Javadoc tag.
     *
     * <p>Such Javadoc tag can have one argument - {@link #DESCRIPTION}</p>
     *
     * <p><b>Example:</b></p>
     * <pre>{@code @deprecated it is deprecated method}</pre>
     * <b>Tree:</b>
     * <pre>{@code
     *   |--JAVADOC_TAG[3x0] : [@deprecated it is deprecated method]
     *   |--DEPRECATED_LITERAL[3x0] : [@deprecated]
     *   |--WS[3x11] : [ ]
     *   |--DESCRIPTION[3x12] : [it is deprecated method]
     *       |--TEXT[3x12] : [it is deprecated method]
     * }</pre>
     *
     * @see
     * <a href="https://docs.oracle.com/javase/8/docs/technotes/tools/unix/javadoc.html#deprecated">
     * Oracle Docs</a>
     * @see #JAVADOC_TAG
     */
    public static final int DEPRECATED_LITERAL = JavadocParser.DEPRECATED_LITERAL;
```

output:
```
[checkstyle] Running Checkstyle 8.8-SNAPSHOT on 969 files
[checkstyle] [ERROR] .../api/JavadocTokenTypes.java:72: Duplicate @deprecated tag. [MissingDeprecated]
[checkstyle] [ERROR] .../api/JavadocTokenTypes.java:84: Must include both @java.lang.Deprecated annotation and @deprecated Javadoc tag with description. [MissingDeprecated]

```

TODO: re-implement Check it to use AST traverse approach, see example in JavadocSummaryCheck.

### Migration Notes

package-info.java will now be allowed to print violations. While this doesn't work for all JDK versions, it can be disabled using our filters.

Example Suppression:

````
    <module name="SuppressionSingleFilter">
        <property name="checks" value="MissingDeprecatedCheck"/>
        <property name="files" value="package-info\.java"/>
    </module>
````

**Comment by rnveach** [comment]
@romani Check can't be rewritten as `AbstractJavadocCheck` doesn't allow us to access the Java ASTs as well as the Javadoc Nodes.
This would require changes to `AbstractJavadocCheck` first.

See:
AbstractJavadoc locks down access to AST: https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheck.java#L247-L260 and https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheck.java#L282
Check examines AST: https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/MissingDeprecatedCheck.java#L187-L188

**Comment by romani** [comment]
There is `protected DetailAST getBlockCommentAst` it should be enough, but traversing java AST should be done manually.

**Comment by rnveach** [comment]
@romani How will we implement `skipNoJavadoc` if we move to `AbstractJavadocCheck`?
http://checkstyle.sourceforge.net/config_annotation.html#MissingDeprecated

> When this property is set to true check ignore cases when JavaDoc is missing

`AbstractJavadocCheck` only gets called on Javadocs so we will always be skipping methods without a Javadoc.

**Comment by romani** [comment]
Hmm, yes, here is nuance, when `skipNoJavadoc=false`  and there is no javadoc comment then Check will not be called, so no validation.

If we convert it to javadoc check when we trigger validation from javadoc presence.
If we keep it Java, we trigger validation by method/class token which are always present. But search for javadoc tag could be done on regexp search in plain text comment content. As we do not do need any detailed parsing, regexp should be enough and will work faster.

Look like this Check should stay Java Check.
@rnveach , if you agree , please close this issue.

**Comment by rnveach** [comment]
@romani I still think we should be using Javadoc check more, even if it is simple checks.

We will still have this same issue with other Java to Javadoc checks like `JavadocMethodCheck` which prints a violation if a javadoc is missing. This check also has the extra nuance of requiring a javadoc only if method has more than X lines among other things.
http://checkstyle.sourceforge.net/config_javadoc.html#JavadocMethod
> minLineCount | Minimal amount of lines in method to allow no documentation.
> allowMissingJavadoc | whether to ignore errors when a method javadoc is missed.

scope, excludeScope, ignoreMethodNamesRegex might have to be included as well.

How about for missing Javadocs, we make this it's own check that users can configure on which areas requires a javadoc, `MissingJavadocCheck`.
This means new Javadoc checks will only validate existing Javadocs and not have to worry about missing ones. This will allow us to remove similar functionality from existing checks too, making them slightly less complex.

**Comment by romani** [comment]
>This means new Javadoc checks will only validate existing Javadocs and not have to worry about missing ones.

Exactly. But this off topic in this issue. It will be a point of reason and discussion in issue for JavadocMethodCheck reimplementation

**Comment by romani** [comment]
@rnveach , please verify idea.
I removed out of context conversations in this issue to make issue clear.

**Comment by rnveach** [comment]
> existing Duplicate @deprecated tag validation should be removed, as it is out of scope of this check, duplication of tags should be separate Check.

IMO, this should be added to `JavadocType` and `JavadocMethod` and `JavadocField`.
I have already opened an issue in `JavadocMethod` to report duplicate `@throws`.  See https://github.com/checkstyle/checkstyle/issues/3469 .

**Comment by romani** [comment]
> I have already opened an issue in JavadocMethod to report duplicate @throws

we should avoid supper big Checks with multiple properties, it will be very hard to support them, it is better to keep Checks simple and focused on specific bad practices. Conflicts with mutiple properties are very hard to resolve.

**Comment by romani** [comment]
Fox is merged
