### ISSUE TITLE
DeclarationOrder: problem with forward references

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#4984]
http://checkstyle.sourceforge.net/config_coding.html#DeclarationOrder

> ATTENTION: the check skips class fields which have forward references from validation due to the fact that we have Checkstyle's limitations to clearly detect user intention of fields location and grouping. 

There is forward reference at https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java#L36 but it is not ignored.

after fix, this suppression should be removed - https://github.com/checkstyle/checkstyle/blob/master/config/suppressions.xml#L58

**Comment by romani** [comment]
@kazachka ,

so structure of class is:
```
public final class JavadocTokenTypes {
    private static final int RULE_TYPES_OFFSET = 10000;
    public static final int JAVADOC = JavadocParser.RULE_javadoc + RULE_TYPES_OFFSET;
    public static final int JAVADOC_TAG = JavadocParser.RULE_javadocTag + RULE_TYPES_OFFSET;
    public static final int JAVADOC_INLINE_TAG = JavadocParser.RULE_javadocInlineTag
            + RULE_TYPES_OFFSET;
    public static final int RETURN_LITERAL = JavadocParser.RETURN_LITERAL; // violation is here and further down for  lines that do not use RULE_TYPES_OFFSET
```

**Comment by romani** [comment]
@kazachka , let's try to make changes that Check requests in that java file and see how it will looks like.

**Comment by rnveach** [comment]
Fix was merged
