### ISSUE TITLE
RedundantModifier flags public constructor of private inner class although used in reflective construction

### ISSUE THREAD

**Issue by Tohnmeister** [checkstyle/checkstyle#4996]
Probably related to issue #2508. We recently migrated from Checkstyle 5 to 8.1, which caused RedundantModifier to start flagging public constructors of non-public and non-protected inner classes. While this is true for compiled code, it is not for code that uses reflection to create instances of such classes.

E.g. the following example will compile, but not run

```java
public class ReflectionConstructorWithoutAccessModifier {
    public static void main(String[] args) throws InstantiationException, IllegalAccessException, IllegalArgumentException, InvocationTargetException, NoSuchMethodException, SecurityException {
        SomeClass someObject = SomeClass.class.getConstructor().newInstance();
    }

    private static class SomeClass {
        SomeClass() {
        }
    }
}
```

While making the SomeClass constructor public will make the code run, but will also make Checkstyle flag the constructor as having a redundant public keyword.

Although I understand that issue #2508 has been closed with the rationale that these corner cases cannot be covered by Checkstyle, this is a slightly different case not related to serialization. Still I can live with disabling checkstyle warnings for the very few situations where we have the above code.

**Comment by rnveach** [comment]
> SomeClass.class.getConstructor().newInstance();

Why do you need/use reflection for a class you define in the same file? This doesn't make much sense to me and you should probably rewrite this code.

> this is a slightly different case not related to serialization

But it is very much related as serialization uses reflection to create a new instance of the class. The only real difference here is you are using reflection in the same class it is defined while serialization is from a 3rd party package.

Even if we did modify the check to find your type of example, which would be some work as there is no guarantee it will be a simple one line reflection as your example, it wouldn't pick up cases where the reflection is done in other classes, which is probably a more common way of coding this type of thing.

**Comment by romani** [comment]
This  case is too specific , and if you need it for good reason, suppression is the only work around.
It is completely ok to have suppressions , there are always cases that stand out of best practices.
