### ISSUE TITLE
Add violateExecutionOnNonTightHtml property of AbstractJavadocCheck to xdoc

### ISSUE THREAD

**Issue by Vladlis** [checkstyle/checkstyle#5002]
As a result of #3311 a new property `violateExecutionOnNonTightHtml` is added to `AbstractJavadocCheck`. This property has to be added to xdoc.

Tip: https://github.com/checkstyle/checkstyle/pull/4751/files#r134985454

**Comment by rnveach** [comment]
@romani I noticed we didn't turn on `violateExecutionOnNonTightHtml` for any of our checks in our configuration. Should we do this?

**Comment by romani** [comment]
> Should we do this in a new issue?

I think we do not need this, as all our current validations are not that HTML related.
If you know cases where we should start to fail - please create new issue.

**Comment by rnveach** [comment]
Fix was merged.
