### ISSUE TITLE
pitest: increase mutation coverage for pitest-checks-whitespace profile to 100%

### ISSUE THREAD

**Issue by Nimfadora** [checkstyle/checkstyle#5003]
We should increase coverage for pitest-checks-whitespace profile up to 100%.
This issue is a subtask of #3708

Current threshold of pitest-checks-whitespace profile: 95

**Comment by Nimfadora** [comment]
@romani There is a problem with mutations in ParenPadCheck. We have such [mutation](https://nimfadora.github.io/pr/com.puppycrawl.tools.checkstyle.checks.whitespace/ParenPadCheck.java.html#org.pitest.mutationtest.report.html.SourceFile@4f473a20_123), if I remove this line, all tests pass, regression pass. Ok, what's next, in [this mutation](https://nimfadora.github.io/pr/com.puppycrawl.tools.checkstyle.checks.whitespace/ParenPadCheck.java.html#org.pitest.mutationtest.report.html.SourceFile@4f473a20_209) we should specify more concrete lower bound, as nodes of first several types like CTOR_DEF, METHOD_DEF will never reach this method. And here something interesting, if I set this number to 3, and revert first deletion, than check finds new problems. I don't know what to do with all remained mutations of this class, as they are weird and I can't find any logic in results I receive.

**Comment by Nimfadora** [comment]
@romani [here](https://nimfadora.github.io/after/com.puppycrawl.tools.checkstyle.checks.whitespace/index.html) you can see mutations remained. Situation with ParenPadCheck was described in the [previous](https://github.com/checkstyle/checkstyle/issues/5003#issuecomment-326759453) comment. What about [NoWhitespaceAfterCheck](https://nimfadora.github.io/after/com.puppycrawl.tools.checkstyle.checks.whitespace/NoWhitespaceAfterCheck.java.html#org.pitest.mutationtest.report.html.SourceFile@709c843d_391) Even if I find exact number for the second condition (minimal I found is 13) I will produce another mutation: lastTypeNode.getColumnNo() > ident.getColumnNo() + 13 (+ can be replaced by - and you cannot do anything with it).

**Comment by romani** [comment]
@Nimfadora ,

> There is a problem with mutations in ParenPadCheck. We have such mutation, if I remove this line, all tests pass, regression pass.

please remove this line and prove it by regression - in separate PR.

> ParenPadCheck ...... as nodes of first several types like CTOR_DEF, METHOD_DEF will never reach this method.

confirmed, please use reflection and pure-UT test method to cover mutation. It is not reasonable to make new set of tokens without this. Attention: each reflection usage should be explained by a comment - you have a reason. Please send this by separate PR.

**Comment by Nimfadora** [comment]
> can we change code to be written differently ?
@romani your example is a bit controversial:

`getTypeLastNode` method should return max line number+column number 

so in this situation `String s [] = null` will be decomposed as:
ident = s
lastTypeNode= ]

ident < lastTypeNode

and it will not pass the condtiton `ident.getColumnNo() > lastTypeNode.getColumnNo()`. So either you have confused the comments or I didn't understand what you mean.

And also we should not forget about such case:
`someStuff15 instanceof Object  [] //incorrect 1`
`someStuff15 instanceof Object[] [] //incorrect 2`
`someStuff15 instanceof Object [] [] //incorrect 1,2 but we notice only the first mistake`

If we change` getTypeLastNode` as you propose, we will not notice the 1 at all.

I'm totally confused about this situation. And in any case we could not go far from comparisons where  ">" and "<" are used. More than that, pitest will require some strong bound like "ident.getColumnNo() > lastTypeNode.getColumnNo() - minPossibleDistance", which is hard to determine.

**Comment by rnveach** [comment]
Current pitest report: http://rveach.no-ip.org/checkstyle/regression/pitest-reports/8/com.puppycrawl.tools.checkstyle.checks.whitespace/index.html

**Comment by rnveach** [comment]
http://rveach.no-ip.org/checkstyle/regression/pitest-reports/8/com.puppycrawl.tools.checkstyle.checks.whitespace/NoWhitespaceAfterCheck.java.html#org.pitest.mutationtest.report.html.SourceFile@1fd577ca_393
http://rveach.no-ip.org/checkstyle/regression/pitest-reports/8/com.puppycrawl.tools.checkstyle.checks.whitespace/NoWhitespaceAfterCheck.java.html#org.pitest.mutationtest.report.html.SourceFile@1fd577ca_394

http://rveach.no-ip.org/checkstyle/regression/reports/140/
http://rveach.no-ip.org/checkstyle/regression/reports/141/
https://github.com/rnveach/checkstyle/commits/issue_5003

Regression has shown no differences for changing these remaining lines during mutation.
UTs show these lines can't be removed.
We must hit this using reflection or mocks.

**Comment by romani** [comment]
last fix is merged.
