### ISSUE TITLE
pitest: increase mutation coverage for pitest-checks-imports profile to 100%

### ISSUE THREAD

**Issue by Nimfadora** [checkstyle/checkstyle#5004]
We should increase coverage for pitest-checks-imports profile up to 100%.
This issue is a subtask of #3708

Current threshold of pitest-checks-imports profile: 94

**Comment by rnveach** [comment]
Current pitest report: http://rveach.no-ip.org/checkstyle/regression/pitest-reports/7/com.puppycrawl.tools.checkstyle.checks.imports/index.html

**Comment by djydewang** [comment]
I am on it now.

**Comment by rnveach** [comment]
fix was merged
