### ISSUE TITLE
pitest: increase mutation coverage for pitest-checks-metrics profile to 100%

### ISSUE THREAD

**Issue by Nimfadora** [checkstyle/checkstyle#5005]
We should increase coverage for pitest-checks-metrics profile up to 100%.
This issue is a subtask of #3708

Current threshold of pitest-checks-metrics profile: 91

**Comment by romani** [comment]
@Nimfadora ,

statements to remove:
https://nimfadora.github.io/pr/com.puppycrawl.tools.checkstyle.checks.metrics/AbstractClassCouplingCheck.java.html#org.pitest.mutationtest.report.html.SourceFile@151aa30f_135

https://nimfadora.github.io/pr/com.puppycrawl.tools.checkstyle.checks.metrics/ClassDataAbstractionCouplingCheck.java.html#org.pitest.mutationtest.report.html.SourceFile@3b597d0e_46

just need test for multiple file execution on the same config:
https://nimfadora.github.io/pr/com.puppycrawl.tools.checkstyle.checks.metrics/NPathComplexityCheck.java.html#org.pitest.mutationtest.report.html.SourceFile@49eb2bcc_123

please send PR for this fixes asap.

**Comment by romani** [comment]
from @Nimfadora:
> I have tried to create test for multiple file execution on the same config, but it didn't kill any mutations in NPathComplexityCheck

**Comment by romani** [comment]
@Nimfadora , please share with me link to branch where you tried this multifile execution. All that internal variables cleanup should affect execution, it might be matter of set of input files.
Please remove such lines and launch diff report, smth will be found.

**Comment by rnveach** [comment]
Current pitest report: http://rveach.no-ip.org/checkstyle/regression/pitest-reports/6/com.puppycrawl.tools.checkstyle.checks.coding/index.html

**Comment by rnveach** [comment]
http://rveach.no-ip.org/checkstyle/regression/pitest-reports/6/com.puppycrawl.tools.checkstyle.checks.metrics/AbstractClassCouplingCheck.java.html#org.pitest.mutationtest.report.html.SourceFile@37ddd371_170
http://rveach.no-ip.org/checkstyle/regression/pitest-reports/6/com.puppycrawl.tools.checkstyle.checks.metrics/AbstractClassCouplingCheck.java.html#org.pitest.mutationtest.report.html.SourceFile@37ddd371_215
http://rveach.no-ip.org/checkstyle/regression/pitest-reports/6/com.puppycrawl.tools.checkstyle.checks.metrics/AbstractClassCouplingCheck.java.html#org.pitest.mutationtest.report.html.SourceFile@37ddd371_254
All survivals are related to grabbing the package name of the current class. The reason why is we never use the package name to it's full extent.

> referencedClassNames.remove(parentContext.getPackageName() + DOT + className);

`referencedClassNames` always contains the class name, not the fully qualified package.
Even more weird, `isFromExcludedPackage` doesn't even use the `getPackageName`. It gets it's information from `candidateClassName` which is completely separate.

@romani Unless you know how to fix this code, I think we should remove all this code related to the package as it does nothing.

**Comment by rnveach** [comment]
http://rveach.no-ip.org/checkstyle/regression/pitest-reports/6/com.puppycrawl.tools.checkstyle.checks.metrics/NPathComplexityCheck.java.html#org.pitest.mutationtest.report.html.SourceFile@36a92cfb_436
Report is hard to understand, but the conditional boundary surviving is `columnNo > endColumnNo` and I have problems getting it just like in coding package.

**Comment by romani** [comment]
@rnveach ,

> Unless you know how to fix this code

Pitest is catching dead and unnecessary code. Refactor it as you think it should be, launch regression and if no obvious problems I will be ok to merge. In worse case users will report problem and we will know exact test case, to make our code more robust.

**Comment by rnveach** [comment]
Will do in the next PR.

**Comment by rnveach** [comment]
> columnNo > endColumnNo

This can't be removed because this test and line fails:
https://github.com/checkstyle/checkstyle/blob/3c1ddf428d9ddecaff63986007b4f5ff0593c098/src/test/java/com/puppycrawl/tools/checkstyle/checks/metrics/NPathComplexityCheckTest.java#L79
It's violation changes from `Complexity is 6` to `Complexity is 8`.
`lineNo == endLineNo` can't be removed because a case shows so in regression. I will add it later.
I don't see how it is possible to kill this one. I think we need to use mocking/reflection here.

> package name in AbstractClassCouplingCheck

Regression is showing this can't be completely removed. I am looking into it more.

**Comment by rnveach** [comment]
100% has been met, issue is done.
