### ISSUE TITLE
Prohibit the usage of hardcoded encoding in Checkstyle source code 

### ISSUE THREAD

**Issue by MEZk** [checkstyle/checkstyle#5023]
We need to use http://checkstyle.sourceforge.net/config_coding.html#IllegalTokenText to prohibit the usage of  hardcoded encoding in Checkstyle source code to avoid code like this:

```java
new FileText(new File(fileName), System.getProperty("file.encoding", "UTF-8"));
```

We need to force the contributors to use ```StandardCharsets```.

**Comment by AADudkin** [comment]
I'm on it

**Comment by romani** [comment]
fix is merged.
