### ISSUE TITLE
TranslationCheck: should fire file started/finished when invoking errors

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#5057]
Identified at https://github.com/checkstyle/checkstyle/pull/5043#discussion_r136685319 this issue is slightly related to multi-file validation,

PR wishes to remove file started/finished calls in `TranslationCheck`.
See https://github.com/checkstyle/checkstyle/pull/5043/files

As pitest has proven these calls aren't needed because:
After the check `destroy` executes from the violation, we run `fireAuditFinished`
https://github.com/checkstyle/checkstyle/blob/07a730c0d1b89593e17fa8920faf9c226200e7b5/src/main/java/com/puppycrawl/tools/checkstyle/Checker.java#L219-L223
and the XML logger clears out it's file cache if it hadn't before.
https://github.com/checkstyle/checkstyle/blob/07a730c0d1b89593e17fa8920faf9c226200e7b5/src/main/java/com/puppycrawl/tools/checkstyle/XMLLogger.java#L117-L118

So correct output is still here only because XML logger was extra careful in clearing out it's cache.

DefaultLogger doesn't care about files starting or finishing really.
https://github.com/checkstyle/checkstyle/blob/07a730c0d1b89593e17fa8920faf9c226200e7b5/src/main/java/com/puppycrawl/tools/checkstyle/DefaultLogger.java#L241-L248

---

To me, it is weird we fire errors without a start/end file, but this check is already 'special' as it is related to multi-file mode. We can't assume any new listener made will know this weird behavior.

I suggest we undo the changes to `TranslationCheck` in that PR and in #5397 , and modify `XMLLogger` to not clear out it's cache as `fileFinished` should be the only one doing this.
I assume removing the `fileMessages.forEach(this::writeFileMessages);` in XMLLogger's auditFinished would solve the pitest issue in this check and require the removed code to stay.

**Comment by romani** [comment]
fix is merged
