### ISSUE TITLE
refactoring: remove from UncommentedMainCheck field classDepth

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#5064]
detected at https://github.com/checkstyle/checkstyle/pull/5043/commits/8c381e077c013116124f7ee5266396b662808639#r136696159

please remove filed `classDepth` completely from UncommentedMainCheck and use `currentClass` in all cases instead. 
`currentClass == null` === `classDepth = 0`
`currentClass != null` === `classDepth == 1`

provide regression testing by https://github.com/checkstyle/contribution/tree/master/checkstyle-tester diff.groovy

**Comment by rnveach** [comment]
Unless you are tracking another field, your examples won't work as we won't know when to erase `currentClass` when leaving a class. So you will be removing one field for another.
````
class Top1 {
  class Inner1 {}
}

Before: token=enter Top1, class = null, depth = 0
After: token=enter Top1, class = Top1, depth = 1

Before: token=enter Inner2, class = Top1, depth = 1, 
After: token=enter Inner2, class = Top1, depth = 2

Before: token=leave Inner2, class = Top1, depth = 2, 
After: token=leave Inner2, class = Top1, depth = 1

Before: token=leave Top1, class = Top1, depth = 1
After: token=leave Top1, class = null, depth = 0
````

The only things that can reset `currentClass` to null is either the depth or the specific token AST.

**Comment by romani** [comment]
Yes, nested classes is good case.
Let's forget about such issue
