### ISSUE TITLE
LineLength measures Java characters, not Unicode characters

### ISSUE THREAD

**Issue by cushon** [checkstyle/checkstyle#5089]
`LineLength` checks the number of Java characters in a line (i.e. the number of 16-bit [code units](http://unicode.org/glossary/#code_unit) in the UTF-16 encoded string), not the number of [Unicode characters](http://unicode.org/glossary/#character) in the line.

The line length limit in the Google Java Style Guide is supposed to be 100 Unicode characters: https://google.github.io/styleguide/javaguide.html#s4.4-column-limit, so both of the following long lines should be OK:

```java
class T {
    String aaaaaaa = "1234567890123456789012345678901234567890" + "1234567890123456789012345" + "_";
    String aaaaaab = "1234567890123456789012345678901234567890" + "1234567890123456789012345" + "💩";
}
```

```java
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module PUBLIC "-//Puppy Crawl//DTD Check Configuration 1.3//EN" "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
<module name="Checker">
  <module name="TreeWalker">
    <module name="LineLength">
      <property name="max" value="100" />
    </module>
  </module>
</module>
```

```java
 java -jar checkstyle-8.2-all.jar -c config.xml Test.java 
Starting audit...
[ERROR] /var/tmp/Test.java:3: Line is longer than 100 characters (found 101). [LineLength]
Audit done.
Checkstyle ends with 1 errors.
```

**ATTENTION:**
All users from Windows OS who would like to have this issue fixed (after release of fix) have to define charset in [Checker](https://checkstyle.org/config.html#Checker) to UTF-8, in other case calculation of length will be wrong.
Second example shows how to set charset - https://checkstyle.org/config.html#Checker

**Comment by romani** [comment]
@cushon , how IDEs(Eclipse, IDEA, NetBeans) treat such cases ?
do they count columns or symbols ?

**Comment by cushon** [comment]
IntelliJ (and reportedly Eclipse) think the length of both of those lines is 100.

**Comment by romani** [comment]
@cushon , please make example you provided compilable by javac.

**Comment by romani** [comment]
Columns are different in AST:
```
$ cat Test.java 
public class Test {
    String aaaaaaa = "1234567890123456789012345678901234567890" + "12345678901234567890123456" + "_";
    String aaaaaab = "1234567890123456789012345678901234567890" + "12345678901234567890123456" + "💩";
}

$ java -jar checkstyle-8.3-SNAPSHOT-all.jar -t Test.java | grep -B 12 SEMI 
    |--VARIABLE_DEF -> VARIABLE_DEF [2:4]
    |   |--MODIFIERS -> MODIFIERS [2:4]
    |   |--TYPE -> TYPE [2:4]
    |   |   `--IDENT -> String [2:4]
    |   |--IDENT -> aaaaaaa [2:11]
    |   |--ASSIGN -> = [2:19]
    |   |   `--EXPR -> EXPR [2:95]
    |   |       `--PLUS -> + [2:95]
    |   |           |--PLUS -> + [2:64]
    |   |           |   |--STRING_LITERAL -> "1234567890123456789012345678901234567890" [2:21]
    |   |           |   `--STRING_LITERAL -> "12345678901234567890123456" [2:66]
    |   |           `--STRING_LITERAL -> "_" [2:97]
    |   `--SEMI -> ; [2:100]
    |--VARIABLE_DEF -> VARIABLE_DEF [3:4]
    |   |--MODIFIERS -> MODIFIERS [3:4]
    |   |--TYPE -> TYPE [3:4]
    |   |   `--IDENT -> String [3:4]
    |   |--IDENT -> aaaaaab [3:11]
    |   |--ASSIGN -> = [3:19]
    |   |   `--EXPR -> EXPR [3:95]
    |   |       `--PLUS -> + [3:95]
    |   |           |--PLUS -> + [3:64]
    |   |           |   |--STRING_LITERAL -> "1234567890123456789012345678901234567890" [3:21]
    |   |           |   `--STRING_LITERAL -> "12345678901234567890123456" [3:66]
    |   |           `--STRING_LITERAL -> "💩" [3:97]
    |   `--SEMI -> ; [3:101]
```

**Comment by romani** [comment]
problem is in ANTLR grammar, unicode symbol is parsed as 2 characters in length, but should be 1.

**Comment by QwerTech** [comment]
+1 for this issue.

**Comment by romani** [comment]
@nmancus1 , this is also good issue to look at as introduction to ANTLR parser.

**Comment by nmancus1** [comment]
@romani I am changing rules in java.g, but it seems like my changes aren't being applied. What am I missing?

**Comment by nmancus1** [comment]
@romani Ok, so `BufferedReader` is reading the emoji here as two characters (97, 98): 
![image](https://user-images.githubusercontent.com/31252532/76556113-50ebce80-646f-11ea-9f91-05e5c0ec0022.png)

Then, in `LineLengthCheck.java`: 
```
final int realLength = CommonUtil.lengthExpandedTabs(
                line, line.length(), getTabWidth());
```
realLength() is counting the 💩 as two chars, which is what's being logged.  I'm not sure how the ANTLR parser is involved here, can you point me in the right direction?

**Comment by romani** [comment]
yes, it is our recent change .... https://checkstyle.org/config_sizes.html#LineLength become a Check that does not depends on java parser at all from https://checkstyle.org/releasenotes.html#Release_8.24

I am removing ANTLR label from it.
We just need to fix util method.

@nmancus1 , please fix this issue if you see a solution.

**Comment by strkkk** [comment]
Fix is merged.

**Comment by oliviercailloux** [comment]
Would you perhaps consider updating https://checkstyle.sourceforge.io/google_style.html, if appropriate? That page still mentions this issue (5089).

**Comment by strkkk** [comment]
@oliviercailloux Thanks for pointing at this issue, I have created https://github.com/checkstyle/checkstyle/pull/9257 for this. It will be fixed in next release.
