### ISSUE TITLE
Add and remove javadoc block tags in NonEmptyAtclauseDescriptionCheck

### ISSUE THREAD

**Issue by ps-sp** [checkstyle/checkstyle#5092]
`@return` should be removed from `NonEmptyAtclauseDescriptionCheck`. Also [`@exception`](http://docs.oracle.com/javase/7/docs/technotes/tools/windows/javadoc.html#exception) which is a synonym for `@throws` should be added to default tokens for the check since `@throws` is a default token for it.  

Also, other tags that can be added to this check need to be investigated.

taken from [5000#discussion](https://github.com/checkstyle/checkstyle/pull/5000#discussion_r135173856)

**Comment by Vladlis** [comment]
Pre-assigned to Lev Sikhovets

**Comment by romani** [comment]
Please specify GitHub account.

**Comment by sikhlev** [comment]
This issue is split in two issues #5387 and #5388 .

**Comment by romani** [comment]
I removed from original description: "`@return` without any args results in a parse error so check doesnt need to check for it." , see details at #5387

**Comment by romani** [comment]
issue is closed in favor of #5388
