### ISSUE TITLE
Remove extra numeric offset in JavadocTokenTypes 

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#5114]
RULE_TYPES_OFFSET constant is used to split lexer tokens types and parser rules types.
We need unique numbers for all tokens, ANTLR do not need this and that is why his types are mixed by used values. All values we can take a look at `target/generated-sources/antlr/com/puppycrawl/tools/checkstyle/grammars/javadoc/JavadocParser.java`
for example: LEADING_ASTERISK=1 and RULE_htmlElement = 1.
RULE_TYPES_OFFSET required to shift parser rules, to let them not overlap with types that have prefix "RULE_".

cases:
```
    public static final int HTML_ELEMENT_START = JavadocParser.RULE_htmlElementStart
            + RULE_TYPES_OFFSET
+ RULE_TYPES_OFFSET;
```

```
    public static final int ATTRIBUTE = JavadocParser.RULE_attribute
            + RULE_TYPES_OFFSET
+ RULE_TYPES_OFFSET;
```

```
    public static final int HTML_COMMENT = JavadocParser.RULE_htmlComment
            + RULE_TYPES_OFFSET
+ RULE_TYPES_OFFSET;
```

ToDo:
1) extent javadoc of RULE_TYPES_OFFSET by description that I gave in first paragraph
2) remove extra "+ RULE_TYPES_OFFSET" from that 3 cases.

This issue might result in braking compatibility and even weird behavior of custom checks which used that 3 token types in their code. As `static final int` is in-lined to custom Check code during compilation.
Workaround is to recompile custom Checks(their jars).

Example of breaking compatibility: #505

**Comment by romani** [comment]
@ps-sp , do you see any problems with removal of extra "+ RULE_TYPES_OFFSET" ?

**Comment by ps-sp** [comment]
@romani I can not see any problem with it. Actually, we can utilize the `Vocabulary` class provided by ANTLR. That way we won't even need the [static block](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/utils/JavadocUtils.java#L79-#L113) in `JavadocUtils`. I didn't create an issue for this yet as I thought I would first work it out and check the feasibility of the workaround. We can discuss this further, should I create an issue ?

**Comment by romani** [comment]
Thanks a lot, please create separate issue on this.

**Comment by romani** [comment]
point "1)" is done

**Comment by ps-sp** [comment]
@romani 
>please create separate issue on this.

https://github.com/checkstyle/checkstyle/issues/5119

**Comment by romani** [comment]
Fix is merged
