### ISSUE TITLE
Use Vocablury Class provided by ANTLR

### ISSUE THREAD

**Issue by ps-sp** [checkstyle/checkstyle#5119]
Right now in JavadocUtils we populate a map `TOKEN_NAME_TO_VALUE` and a `String[]`, `TOKEN_VALUE_TO_NAME`, in the [static block](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/utils/JavadocUtils.java#L79-#L113). 

These structues are populated from `JavadocTokenTypes.java` and are used in functions [`getTokenName()`](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/utils/JavadocUtils.java#L341) and [`getTokenId()`](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/utils/JavadocUtils.java#L364)

Instead we can scout the `Vocablury` class provided by ANTLR to provide these features in `JavadocUtils`.

**To do:**

Remove `TOKEN_NAME_TO_VALUE`, `TOKEN_VALUE_TO_NAME` from `JavadocUtils` and substitute with `Vocablury` instance from `JavadocParser.java` in generated sources and ensure that no code gets broken.

**Comment by ps-sp** [comment]
`Vocablury` class from ANTLR can help map token ids (integers) to token NAMES. But we nonetheless will need to map all the token names to token values()([`TOKEN_NAME_TO_VALUE`](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/utils/JavadocUtils.java#L60)) so that we are able to convert the token names provided in config files to their corresponding values.

And to populate the map `TOKEN_NAME_TO_VALUE` it would be straightforward to fetch all the fields from `JavadocTokenTypes.java` rather trying to fit a workaround using ANTLR's `Vocablury` class. 

So utilizing the `Vocablury` will not add any significant utility and would rather decrease the readability of the code is what I feel. Hence this issue should be closed.

@romani @Vladlis 
What do you feel ?

**Comment by Vladlis** [comment]
`So utilizing the Vocablury will not add any significant utility and would rather decrease the readability of `
Yes, in addition Vocabulary doesn't contain `ruleNames`, and contains all `_SYMBOLIC_NAMES` including those which are not used in `JavadocTokenTypes` like `"Char7"`:
```
public static final Vocabulary VOCABULARY = new VocabularyImpl(_LITERAL_NAMES, _SYMBOLIC_NAMES);
```

**Comment by ps-sp** [comment]
Yes it doesn't. But we have a `ruleNames` string array which could be used to create a new `Vocabulary` instance using a factory method in `VocabularyImpl`, or we could have even updated the names in `ruleNames` to be all uppercase and have underscores. We could have worked around but if after all that we still need the map `tokenValuesToNames` then it is not worthwhile.

So ok I am closing this issue then.

**CONCLUSION: ** NO WORK NEEDED. NOTHING DONE.
