### ISSUE TITLE
Violations printed from AuditListeners in auditFinished aren't counted towards violation count

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#5121]
Discussed about at https://github.com/checkstyle/checkstyle/pull/4906#discussion_r131643909 when trying to define a custom AuditListener in the configuration file,

> I have a private listener which is basically an implementation of #3242 , where on auditFinished it examines the list of defined suppressions and prints violations on any that were not used.
I have to use a listener as it is the only customizable area that is called at the end once all other modules, filters, and such are done.

When my custom AuditListener tries to fire violations in `auditFinished` those violations are printed to the console, but it turns out they aren't counted towards the total violation count. This may have always been an issue and I just never noticed it before.

The problem is with the following code:
https://github.com/checkstyle/checkstyle/blob/5a6a87ac206590f8b5795cccb0109b9c87b2ef1c/src/main/java/com/puppycrawl/tools/checkstyle/Checker.java#L220-L222

We retrieve the error counter before firing the AuditListeners for the last time that tells everyone we are finished and this is the value we directly returned for the count display.
When AuditListeners fire errors at this point, they are counted correctly but because of the local variable save of `errorCount` before the `fireAuditFinished` call, those counts are ignored.
Since we are not using this value anywhere except returning it, `counter.getCount()` should be moved and inlined into the `return` line, so that if any AuditListeners fire their own errors, they will be included in the total count.

**Comment by romani** [comment]
@rnveach , why you think that AuditListener can also log events ?
what are usecases ? do we have this in our xdoc for AuditListeners ?

**Comment by rnveach** [comment]
> what are usecases ? 

This is explained in the commented text in the first post and one of the 2 cases I gave for my uses of AuditListeners in the config in PR #4906 .

It is not documented anywhere to my knowledge.

**Comment by romani** [comment]
AuditListener - the place where all violations go ====  that is true and natural by its name
AuditListener - creiating it's own (or possibly removing some by not displaying them) ==== that is not true.

**Comment by rnveach** [comment]
@romani If AuditListener won't do this behavior, will we create a new place that does this?
Will this just have to wait until we figure out how we are going to do multi-file validation?

**Comment by romani** [comment]
>  will we create a new place that does this?

sound like part of multi-file validation design.

> Will this just have to wait until we figure out how we are going to do multi-file validation?

one day, ....

> It is just a simple fix to allow AuditListener to do this.

yes it simple , but it will be hard to withdraw such functionality as usage of checkstyle is high as embedded solution. And out API is far from good already, I just afraid to make it worse.
Design of multi-file validation might help us here ..... but it is heavy feature for me too now.

**Comment by rnveach** [comment]
Closing this as design wasn't agreed upon and can be completed using multi-file validation instead.
