### ISSUE TITLE
Remove usage of DetailAST.branchContains

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#5124]
Identified at https://github.com/checkstyle/checkstyle/issues/4727#issuecomment-315624202 ,

> branchContains is a dangerous method to use all the time since there is no restriction on how deep it can search.

The referenced issue fixed a bug where we used `branchContains` and it was scanning deeper than the check originally intended. It was supposed to be looking for a variable with a `final` modifier, but because of `branchContains` it scanned into an anonymous class in the assignment and picked up the `final` there.

There may be other cases in our code where it might be searching too much.
Example:
https://github.com/checkstyle/checkstyle/blob/55aa8cedc60d4faa776d7a36f8ae2d0bed0ada45/src/main/java/com/puppycrawl/tools/checkstyle/checks/FinalParametersCheck.java#L144
Because we are doing a `branchContains` on the `METHOD_DEF` it is also searching inside the `SLIST` of the method and may pick-up anonymous classes while it is looking for `PARAMETER_DEF`.

I feel `branchContains` should be completely removed as it's search area can't be controlled. If we don't want to remove it, it's use should be heavily controlled.

We should swap it's current uses with either `findFirstToken` or a new method in each check that specifically controls where and what we are looking for.

**Comment by romani** [comment]
this method just do search in tree, nothing related to any logic of any Check.

user can launch this method of root and receive even more interesting results, that probably not up to its expectations.

This looks like just simple mis-usage of some method by engineer.
We can probably move it Utils , but it can be misused from there too.

Please share more points to support removal of it.
Do you think that in all use cases it is error-prone ?

**Comment by rnveach** [comment]
@romani I will check again, but when I looked the majority of cases where calling the method on modifiers looking for static/public/etc... Unless we can define those modifiers inside or on an annotation, I don't think there are other cases to support.

**Comment by romani** [comment]
ones we come to immutable AST model, such method will go utils for sure.

**Comment by rnveach** [comment]
@romani It can't really go outside the AST class because it has to build up all the children trees recursively and caches them through `getBranchTokenTypes`.
If we were to remove the cache and place it inside a `util` out of the AST, then this is even more reason to just remove it. Without the cache, this method will be even slower if used in areas with deep trees.

**Comment by romani** [comment]
ok, let start this process

**Comment by rnveach** [comment]
Only 3 checks remain to be fixed.
AnnotationUseStyle, EqualsAvoidNull, DesignForExtension.

ParenPad is being removed due to surviving mutants and no change in regression.

**Comment by rnveach** [comment]
Only 1 check remain to be fixed.
EqualsAvoidNull.

**Comment by pbludov** [comment]
> Only 1 check remains to be fixed.
> EqualsAvoidNull.

I'm on it. With this fix the method `branchContains` can be removed from the API as well in #6628

**Comment by rnveach** [comment]
See details inside #5234 on how full removal should be done.

**Comment by rnveach** [comment]
https://github.com/checkstyle/checkstyle/search?q=branchContains&unscoped_q=branchContains
All except the implementation have been removed. We can start deprecating and removing it.
