### ISSUE TITLE
 Enforce blank line annotated fields

### ISSUE THREAD

**Issue by gkohen** [checkstyle/checkstyle#5125]
Hi,

In today's value objects fields tend to be annotated. In most source codes out there, there is usually an empty line before the first annotation on the member field.

Example, instead :
```
public class Car{
   @MyFirstAnnotation
   @MySecondAnnotation
   private int id;
   private String firstname;
   private String lastname;
  @JsonProperty("carAge")
   private int age;
   private int bar;
   private int baz;
   @Column
   private int comments;
}
```

It should be:
```
public class Car{

   @MyFirstAnnotation
   @MySecondAnnotation
   private int id;
   private String firstname;
   private String lastname;

   @JsonProperty("carAge")
   private int age;
   private int bar;
   private int baz

   @Column
   private int comments;
}
```

Maybe we can add additional support to the SingleSpaceSeparator for these cases.

Regards

**Comment by romani** [comment]
It will be over complication of this Check.
Please define rules how you want to put empty line. I do not see a logic in your example.

**Comment by romani** [comment]
no details provided ... closing.

**Comment by JoshMcCullough** [comment]
@romani -- What additional details do you require in order to consider this new rule? And FWIW I think the rule would be something like called "NewLineBeforeAnnotatedMember".

**Comment by rnveach** [comment]
@JoshMcCullough We need as much information as possible. What is it looking for to issue a violation and what is ignored. The more information the better.

See https://checkstyle.org/report_issue.html#How_to_request_new_Check.2FModule.3F
