### ISSUE TITLE
Identifiers in the form `aVar` are incorrectly prohibited by google_checks.xml

### ISSUE THREAD

**Issue by pelepelin** [checkstyle/checkstyle#5145]
RegExp patterns for identifiers were created following this comment: https://github.com/checkstyle/checkstyle/issues/3702#issuecomment-275228023

> https://google.github.io/styleguide/javaguide.html#s5.1-identifier-names
>> In Google Style special prefixes or suffixes, like those seen in the examples name_, mName, s_name and kName, are not used.

However, the quoted sentence mentions "special prefixes", and not any one-letter start. To understand what is a special prefix, I look at other specific Google's Guides where they do exist: https://source.android.com/source/code-style#follow-field-naming-conventions 
https://google.github.io/styleguide/javascriptguide.xml?showone=Naming#Naming

So, this rule in Java guide should be read as "there is no requirement to start an identifier from a specific char depending of the identifier role".

So, identifier patterns should be updated to allow forms like `aVar` (which is not bad at all) and `aV` (which is bad in most cases, but is not strictly forbidden by the guide).

Related patterns I see:
https://github.com/checkstyle/checkstyle/blob/97669248fb2402e21cd372380a35d0e312c2a0e8/src/main/resources/google_checks.xml#L121
https://github.com/checkstyle/checkstyle/blob/97669248fb2402e21cd372380a35d0e312c2a0e8/src/main/resources/google_checks.xml#L126
https://github.com/checkstyle/checkstyle/blob/97669248fb2402e21cd372380a35d0e312c2a0e8/src/main/resources/google_checks.xml#L131
https://github.com/checkstyle/checkstyle/blob/97669248fb2402e21cd372380a35d0e312c2a0e8/src/main/resources/google_checks.xml#L137
https://github.com/checkstyle/checkstyle/blob/97669248fb2402e21cd372380a35d0e312c2a0e8/src/main/resources/google_checks.xml#L225

**Comment by romani** [comment]
General Google style clearly state

>In Google Style special prefixes or suffixes, like those seen in the examples name_, mName, s_name and kName, are not used.

in other words no way for https://en.wikipedia.org/wiki/Hungarian_notation in any form of it.

-------

Javascript style is completely off topic, we care only about styles of java. 

If Google Style for Android accept it ... it is completely different story, and in config for AOSP style it should be allowed. unfortunately we do not have config for AOSP at all for now.
If community is ready to start gathering it https://checkstyle.org/style_configs.html .... I am ok with this. But lets create separate issue on this. 
If somebody already have AOSP style config .... please contribute.

**Comment by pelepelin** [comment]
@romani Please reconsider. The quoted fragment says about prefixes with special meaning. It says that no prefixes has special meaning. It does not prohibit vars with the names like `iPhone` (where `i` has no special meaning), but this rule prohibits it. Trying to forbid special prefixes, this rule forbids all prefixes.

**Comment by pelepelin** [comment]
Links to other styles were added just to make sense of the "special prefixes".

**Comment by romani** [comment]
it might be not good example. As iPhone become a brand name so it became word, so it should be `iphone`
More details at http://google.github.io/styleguide/javaguide.html#s5.3-camel-case

Checkstyle is smart to recognize prefix on reason or just coincidence.

AOSP style do prefix on reason, but it conflicting with Google general style. It is ok, just customize it up to your needs. I can not change it config, as it will trigger another wave of issues to revert back.
