### ISSUE TITLE
http://checkstyle.sourceforge.net/report_issue.html is broken

### ISSUE THREAD

**Issue by filipesperandio** [checkstyle/checkstyle#5146]
http://checkstyle.sourceforge.net/report_issue.html
http://checkstyle.sourceforge.net/contributing.html
Links are broken.

**Comment by rnveach** [comment]
It looks like it might be all of sourceforge is having an issue and isn't just us.

**Comment by rnveach** [comment]
Closing this issue and sourceforge seems to be working now
