### ISSUE TITLE
CustomImportOrderCheck broken

### ISSUE THREAD

**Issue by KyleRogers** [checkstyle/checkstyle#515]
CustomImportOrderCheck does not behave as described:

```
THIRD_PARTY_PACKAGE group. This group sets ordering of third party imports. 
Third party imports are all imports except STATIC, SAME_PACKAGE(n) 
and STANDARD_JAVA_PACKAGE.
```

That is not true: Third party packages are all imports that are not in STATIC and not in STANDARD_JAVA_PACKAGE and match the third party regex.

That means if you do not craft the regex well you'll get 
a) intersection with SAME_PACKAGE, that means imports that qualify for SAME_PACKAGE *and* THIRD_PARTY_PACKAGE
b) imports that match no group at all

Additionally the default regex for THIRD_PARTY_PACKAGE is "^$" which matches the empty string only. That means if you use the THIRD_PARTY_PACKAGE group you MUST define a regex. This is not explained in the documentation!!!

----

My import rule is as follows:

```
import org.mydomain.project.*

import <all other imports>

import java.*
import javax.*

import static <all imports>
```

I want to do that with the following configuration:
```
sortImportsInGroupAlphabetically set to true
separateLineBetweenGroups set to true
customImportOrderRules set to SAME_PACKAGE(3)###THIRD_PARTY_PACKAGE###STANDARD_JAVA_PACKAGE###STATIC
```

But this does not work because the thirdPartyPackageRegExp does not match "others"

Workaround is actually overspecifying "same package" by defining third party regex:

thirdPartyPackageRegExp = "^(?!org.mydomain.project).*$"

----

Question/Discussion: Does thirdPartyPackageRegExp make sense at all? Why not match *everything that is not in one of the other groups* as THIRD_PARTY_PACKAGE?

**Comment by romani** [comment]
1) default value was changed to ".\*"
2) documentation was updated for THIRD_PARTY_PACKAGES to include SPECIAL_PACKAGE
3) RegExp for THIRD_PARTY_PACKAGES is required as it helps to specify what is third-party for user, 
if not match to regexp then will be placed to the end of import list.

will be released in 6.3
