### ISSUE TITLE
ruleset_2_0_0.xsd location

### ISSUE THREAD

**Issue by mebigfatguy** [checkstyle/checkstyle#5150]
Greetings,

sourceforge has been flaky the last couple of days causes failures when processing 

xsi:schemaLocation="http://pmd.sourceforge.net/ruleset/2.0.0 http://pmd.sourceforge.net/ruleset_2_0_0.xsd">

[xmlvalidate] /home/acme/etc/pmd-rules.xml:6:16: schema_reference.4: Failed to read schema document 'http://pmd.sourceforge.net/ruleset_2_0_0.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.

is there an alternative github location?

**Comment by rnveach** [comment]
@mebigfatguy You would have to ask PMD this directly. We are not their maintainers and we don't know all they do.
As far as i know, there isn't an alternative location.

**Comment by mebigfatguy** [comment]
i'm an idiot. sorry for the noise.(wrong project)
