### ISSUE TITLE
Checkstyle UTs shouldn't create custom configuration methods

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#5157]
Identified at https://github.com/checkstyle/regression-tool/pull/85#issuecomment-325333038 ,

In our UTs we should use standard configuration methods that are defined in our abstract support classes.
Regression tools needs consistency in order to be able to pull information from the UTs and grab property values.

Example:
FileTabCharacterCheck: createConfig
https://github.com/checkstyle/checkstyle/blob/acdbc55974c3fd6b6e532a29e443bce60016791f/src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/FileTabCharacterCheckTest.java#L96

We need to find and review these cases and see if they can be replaced with our normal configuration methods or if we need to extend abstract support for more complex cases.

**Comment by romani** [comment]
I doubt that it was done on very good reason, it might be just optimization of code amount, we could sacrifice it in favor of regression-tool.

**Comment by rnveach** [comment]
@romani Not only are custom `createConfig` methods an issue but also custom `verify` methods.
We are looking for the `verify` method to know we are dealing with a regression area, but these custom methods aren't named differently like `verifySuppressed` and `verifyWarns`.
Example: https://github.com/checkstyle/checkstyle/blob/2d67bf848556d79f93e800db956c78ed637d2f5c/src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressWarningsFilterTest.java#L101-L106

How should we handle these areas? Should we also recognize them (any method that starts with `verify`) the same as `verify` itself?

**Comment by romani** [comment]
do whatever is convenient for you, I am ok to naming refactoring in test.

**Comment by rnveach** [comment]
Fix was merged
