### ISSUE TITLE
SourceForge seams to restrict the number of sequential connections to checkstyle.sourceforge.net 

### ISSUE THREAD

**Issue by MEZk** [checkstyle/checkstyle#5161]
It seams to me that SourceForge restricts the number of sequential connections to http://checkstyle.sourceforge.net

It can be easily reproduced by the following script on my local machine:
```sh
for i in `seq 10`; do curl http://checkstyle.sourceforge.net; done

``` 

or

```sh
for i in `seq 10`; do curl http://checkstyle.sourceforge.net/dtds/suppressions_1_1_xpath_experimental.dtd; done
```

The issue affects SuppressionFilterTest. There are 2 tests which try to connect to sourceforge. If we run them multiple times, the execution time will be increased dramatically but they finally succeed.

@rnveach @romani @Vladlis 
Please, run the above mentioned scripts on your local machines and confirm that you have the same problem.

**Comment by MEZk** [comment]
May be connected to https://github.com/checkstyle/checkstyle/issues/5158

**Comment by MEZk** [comment]
Same if for SuppressionsLoaderTest.

**Comment by romani** [comment]
no problems on my side. both commands passed with printing whole content of files.

**Comment by Vladlis** [comment]
same, no problems

**Comment by romani** [comment]
@MEZk , please recheck one more time

**Comment by MEZk** [comment]
@romani 
rechecked. Looks like it was temporary problem.
