### ISSUE TITLE
Mark TranslationCheck with GlobalStatefulCheck annotation

### ISSUE THREAD

**Issue by soon** [checkstyle/checkstyle#5164]
This is a part of https://github.com/checkstyle/checkstyle/issues/4870

TranslationCheck requires additional changes, therefore it is excluded from https://github.com/checkstyle/checkstyle/pull/4892

**Comment by rnveach** [comment]
If this is part of another issue why does this need to be it's own issue?
Based on your commit, I see it needs to be thread safe.

**Comment by soon** [comment]
@rnveach Ok, closing this issue, the PR now refers to the  #4870
