### ISSUE TITLE
create GeneratedJavadocTokenTypesTest.java

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#5186]
it is a subtask of #5139.

All is required is to create UT GeneratedJavadocTokenTypesTest that works the same way as https://github.com/checkstyle/checkstyle/blob/master/src/test/java/com/puppycrawl/tools/checkstyle/grammars/GeneratedJavaTokenTypesTest.java but for javadoc tokens - https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java

values of JavadocTokenTypes should never change.

**Comment by romani** [comment]
@Naman-sopho , can you help us with this issue

**Comment by Naman-sopho** [comment]
I am on it @romani

**Comment by romani** [comment]
@ps-sp , thanks a lot for partial initial fix, I merged it to make sure we will not make more damage.

But we need a bit more changes.

Our contract/API with users is values of https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
no matter that we are doing/refactoring in grammar, this numbers should not change.

in your UT you check value for `assertEquals(MSG, 26, JavadocParser.Char1);`  .... is absent at https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java so its value could change, nobody care.
I am ok to keep testing for it..... but please add one more UT method that test all values of JavadocTokenTypes (not a JavadocParser). If any new value appear at JavadocTokenTypes , test should catch it too.

@Vladlis , fyi.

**Comment by romani** [comment]
fix is merged
