### ISSUE TITLE
left curly nlow documentation error?

### ISSUE THREAD

**Issue by guillaumecle** [checkstyle/checkstyle#5188]
Hello, 
I think there is a typo in this documentation:
https://github.com/checkstyle/checkstyle/blob/d8b0bce052afeaf792faa1abf503c3ad681e5520/src/xdocs/property_types.xml#L257-L259

new line is used when the statement/expression/declaration connected to the brace **does** span multiple lines (and not the opposite), as shown in the example:

https://github.com/checkstyle/checkstyle/blob/d8b0bce052afeaf792faa1abf503c3ad681e5520/src/xdocs/property_types.xml#L260-L271

**Comment by romani** [comment]
> `If the statement/expression/declaration connected to the brace spans multiple lines, 
than apply <code>eol</code> rule. Otherwise apply the <code>nl</code> rule.`

yes, you are right, it is terrible typo.

should be `....connected to the brace spans multiple lines, than apply <code>nl</code> rule. Otherwise apply the <code>eol</code> rule.`

**Comment by rnveach** [comment]
Fix was merged
