### ISSUE TITLE
Add a unit test to ensure that all checks are marked with MT annotation

### ISSUE THREAD

**Issue by soon** [checkstyle/checkstyle#5190]
Identified here: https://github.com/checkstyle/checkstyle/pull/4892#issuecomment-333561216

There should be a unit test, which ensures that all `FileSetCheck` and `AbstractCheck` implementations are marked with appropriate MT annotation: `StatelessCheck`, `FileStatefulCheck` or `GlobalStatefulCheck`

**Comment by rnveach** [comment]
This was done as part of https://github.com/checkstyle/checkstyle/issues/4870
