### ISSUE TITLE
LeftCurly : add support for LITERAL_CASE and LITERAL_DEFAULT 

### ISSUE THREAD

**Issue by liutikas** [checkstyle/checkstyle#5207]
[LeftCurly](http://checkstyle.sourceforge.net/config_blocks.html#LeftCurly ) is a great check, however it does not support LITERAL_CASE as a token.

We would like to enforce that everyone writes:
```
case FOO: {
    // some code
}
```

instead of

```
case FOO:
    {
        //some code
    }
```

-------

<a href="https://www.bountysource.com/issues/50561313-leftcurly-add-support-for-literal_case-and-literal_default">
<img ng-src="https://api.bountysource.com/badge/issue?issue_id=50561313" src="https://api.bountysource.com/badge/issue?issue_id=50561313">
</a>

**Comment by romani** [comment]
I do not see obvious problem why not .... fix could be simply as to add it to acceptable tokens and write few UTs

**Comment by romani** [comment]
Fix is merged
