### ISSUE TITLE
AllSinglelineCommentsTest fails on MacOS

### ISSUE THREAD

**Issue by MEZk** [checkstyle/checkstyle#5212]
AllSinglelineCommentsTest fails on my laptop with MacOS 10.12.6 (16G29) and  kernel version Darwin 16.7.0.

```
 java -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```

When I invoke

```java
System.getProperty("line.separator")
```

it returns "\n"  as a lines separator, however, ast.getFirstChild().getText() shows that "\n\r" is a lines separator in AST.

If I change

```java
private static final String LINE_SEPARATOR = System.getProperty("line.separator");
```

to

```java
private static final String LINE_SEPARATOR = "\r\n";
```

or set the property "line.separator" via command line the test will pass.

Note, that I did not configure line separators in IDEA, or MacOS. It is laptop's default configuration which result in the build failure fore Checkstyle.

**Comment by MEZk** [comment]
Same if for CommentsTest.
Expected InputComments1Ast.txt has CRLF as line separators and actual InputComments1.java has LF as separators.

**Comment by MEZk** [comment]
Same is for AstRegressionTest.
The difference between expected and actual files is in separators.

**Comment by MEZk** [comment]
It is not a big problem for me, as I can convert separators for all project, but it might be a problem for the new contributors.

**Comment by rnveach** [comment]
@MEZk Can you add the junit failure you are getting?
We run Mac tests in travis.
Latest master: https://travis-ci.org/checkstyle/checkstyle/jobs/291304168

Why is that passing but yours is failing?

**Comment by romani** [comment]
@MEZk ,

> however, ast.getFirstChild().getText() shows that "\n\r" is a lines separator in AST.

please share a AST print 

> If I change

where are you changing code ?

--------------------

is it related to #4955 ?

**Comment by MEZk** [comment]
@romani 

It looks like it was the problem of my local build.

I'm not able to reproduce the problem now in the following environment:
```
IntelliJ IDEA 2017.2.6
Build #IU-172.4574.11, built on November 13, 2017
JRE: 1.8.0_152-release-915-b12 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6
```

I think that I changed line endings in the previous IDEA build manually. I'm closing the issue.
