### ISSUE TITLE
Fix violations from new sevntu check - CheckstyleTestMakeupCheck

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#5228]
Fix violations found by new sevntu check at https://github.com/sevntu-checkstyle/sevntu.checkstyle/issues/610 .

**Comment by rnveach** [comment]
All changes were merged. I think we should keep this open until new check is merged.

**Comment by rnveach** [comment]
@romani Once sevntu is released and new check is added, this issue can be closed.

**Comment by romani** [comment]
@rnveach 

done - http://sevntu-checkstyle.github.io/sevntu.checkstyle/#1.25.0

please proceed, please activate all new Checks.

**Comment by romani** [comment]
fix is merged
