### ISSUE TITLE
FixCheck Start Os in the work

### ISSUE THREAD

**Issue by jirawat050** [checkstyle/checkstyle#5232]
do check Os mac and linux to JavadocDetailNodeParserTest.java because avadocDetailNodeParserTest.java  not check macOs and linux

**Comment by pbludov** [comment]
Note that the system property "os.name" is used in a wrong way here.

There should be something like that:

```
private static final String LINE_SEPARATOR = System.getProperty("line.separator");

// ...

if ("\r\n".equals(LINE_SEPARATOR)) {
   // DOS/Windows case
}
if ("\n".equals(LINE_SEPARATOR)) {
  // Linux/mac case
}
else {
  // Scream and die in agony
}
```
For this test case, the OS name is irrelevant, only the line endings matter.

**Comment by romani** [comment]
I still do not understand where is problem now , please show me one more time.

**Comment by rnveach** [comment]
if issue isn't clarified in 2 weeks, I will close it.

**Comment by rnveach** [comment]
Closing as there has been no response.
