### ISSUE TITLE
doc: extend examples for FinalLocalVariable

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#5239]
web documentation - http://checkstyle.sourceforge.net/config_coding.html#FinalLocalVariable

we need to create more examples for user to show Check behavior.
All code for documentation is at - https://github.com/checkstyle/checkstyle/blob/master/src/xdocs/config_coding.xml#L1122

Examples should be compilable java code with comment where violation is expected, good example - http://checkstyle.sourceforge.net/config_coding.html#ExplicitInitialization

**Comment by romani** [comment]
preassigned to @tihju.

**Comment by tihju** [comment]
I'm on it

**Comment by romani** [comment]
fix is merged.
