### ISSUE TITLE
new Check: Enforce whitespace before array initializer in Google config

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#524]
It would be good to have a check that enforces whitespace before array initializer according to samples in [Google Java Style](https://google-styleguide.googlecode.com/svn/trunk/javaguide.html#s4.8.3.1-array-initializers).

For example:

``` java
new int[] {0, 1, 2, 3}  // correct

new int[] { // correct         
  0, 1, 2, 3          
}

new int[]
    {0, 1, 2, 3}  // correct

new int[]{ // incorrect         
  0, 1, 2, 3          
}

new int[]{0, 1, 2, 3}  // incorrect                           
```
##

**Comment by mvdan** [comment]
I would also appreciate this.

**Comment by rnveach** [comment]
@romani 
[This new check is in sevntu right now](https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/master/sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/WhitespaceBeforeArrayInitializerCheck.java), although the issue there is still open.
Can't this issue be closed? Should we reference the sevntu check in our google style guide?

**Comment by romani** [comment]
We could keep it as a reminder to move sevntu Check to main library.
We can not reference any non standard Checks in checkstyle distributable/public configurations.
We are still in moratorium period for new Checks :( .

**Comment by romani** [comment]
reminder does not work, all Sevntu Checks need to be moved to main library.
I am closing the issue.
