### ISSUE TITLE
Fix plural agreement grammar in documentation for DesignForExtension

### ISSUE THREAD

**Issue by Dispader** [checkstyle/checkstyle#5249]
The (most excellent) DesignForExtension documentation has minor grammatical errors involving plural agreement in two places.

1. `DesignForExtensionCheck.java`
   - reads "makes sense only for library projects (not an application projects)"
      - "an application projects" disagrees
1. `xdocs/config_design.xml`
   - reads "makes sense only for library project (not an application projects)"
      - "for library project" mismatches the JavaDoc, and disagrees
      - "an application projects" disagrees

**Comment by romani** [comment]
fix is merged
