### ISSUE TITLE
Checker.destroy doesn't erase fileSets but erases everything else

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#5264]
https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/Checker.java#L173-L176

Checker clears out all other arrays once the destroy method is called, except the list of File Sets.
I don't see a reason to keep them since we erase everything else.
If a Checker instance is used again, it should expect it to be a near clean state.

Should Checker destroy reset everything back to the default like when the check is first instantiated?
If that is the case, [the `counter` is never added back in after the destroy](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/Checker.java#L141) among the other class fields.

This is coming up because I am trying to rewrite the test at https://github.com/checkstyle/checkstyle/blob/0a8f5af052b05645e292a42ca884128db901a58a/src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java#L744 for another issue and it uses `Checker` multiple times.

**Comment by rnveach** [comment]
If I make the change, the same test I mentioned above fails.
> CheckerTest.testCacheAndCheckWhichAddsNewResourceLocationButKeepsSameCheckerInstance:811 Cache has null as a resource key

**Comment by romani** [comment]
UTs might be created such to reach 100% coverage, so could be a bit weird here.

**Comment by romani** [comment]
fix is merged.
