### ISSUE TITLE
Incompability between javadoc parser and checkstyle parser

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#5269]
/var/tmp $ javac TestClass.java
(no errors)

/var/tmp $ cat Test.java
```
/**
 * <p>A paragraph with list.
 * <ul><li>item</ul>
 * </p>
 */
public interface Test {
}
```

/var/tmp $ cat config.xml
```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module PUBLIC
  "-//Puppy Crawl//DTD Check Configuration 1.2//EN"
  "http://www.puppycrawl.com/dtds/configuration_1_2.dtd">
<module name="Checker">
  <module name="TreeWalker">
    <module name="JavadocStyle"/>
  </module>
</module>
```

/tmp$ java -Duser.language=en -Duser.country=US -jar ~/Downloads/checkstyle-8.4-all.jar -c TestConfig.xml Test.java
```
Starting audit...
Audit done.
```

/tmp$ javadoc Test.java
```
Loading source file Test.java...
Constructing Javadoc information...
Standard Doclet (Next) version 9-internal
Building tree for all the packages and classes...
Test.java:5: error: unexpected end tag: </p>
 * </p>1
   ^
Generating ./Test.html...
Generating ./package-frame.html...
Generating ./package-summary.html...
Generating ./package-tree.html...
Generating ./constant-values.html...
Building index for all the packages and classes...
Generating ./overview-tree.html...
Generating ./index-all.html...
Generating ./deprecated-list.html...
Building index for all classes...
Generating ./allclasses-frame.html...
Generating ./allclasses-noframe.html...
Generating ./index.html...
Generating ./help-doc.html...
1 error
```
--------------

The javadoc tool is uses an ancient HTML4 parser and stuck with it for compatibility reasons.
It does not allow non-inline tags in the contents of a paragraph. As the result, the closing paragraph tag is unexpected and treated as an error. Also, there may be some other incompatibilities.

The checkstyle javadoc parser should be bug-compatible with the javadoc tool parser.
Otherwise, it is possible that the code whis is correct for checkstyle will break the build.

**Comment by pbludov** [comment]
Related to https://github.com/checkstyle/checkstyle/issues/4701
There should be a test script or something like that to make sure that the javadoc tool reported less or equal number of errors than the checkstyle does. If the javadoc tool catches an error that is missed by the checkstyle, then the build is in danger.

**Comment by rnveach** [comment]
> `<module name="JavadocStyle"/>`

This check doesn't use the Javadoc parser.

>  `* <ul><li>item</ul>`

According to https://github.com/checkstyle/checkstyle/issues/3332 `li` doesn't require an end tag, so I think we handle this case correctly by not failing. I don't understand why the javadoc tool creates an error in this regard.

> It does not allow non-inline tags in the contents of a paragraph

Can you post a link where it says this? Isn't the Javadoc always a paragraph?

We do have an extra property for all Javadoc checks that will make a violation here, called `violateExecutionOnNonTightHtml`.
````
$ cat TestClass.java
public class TestClass {
/**
 * <p>A paragraph with list.
 * <ul><li>item</ul>
 * </p>
 */
    void method() {
    }
}

$ cat TestConfig.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>

    <module name="TreeWalker">
<module name="JavadocParagraphCheck">
<property name="violateExecutionOnNonTightHtml" value="true" />
</module>
    </module>
</module>

$ java -jar checkstyle-8.4-all.jar -c TestConfig.xml TestClass.java
Starting audit...
[ERROR] TestClass.java:4: Unclosed HTML tag found: li [JavadocParagraph]
Audit done.
Checkstyle ends with 1 errors.
````

**Comment by romani** [comment]
> The checkstyle javadoc parser should be bug-compatible with the javadoc tool parser.

sorry, we will not be compatible. It is not required. We just should not come to conflict and by any of our demands for comment change result in ERROR in javadoc tool.

All we have to do is to **parse properly if javadoc-tool parse it properly** , warning could be different.

> Otherwise, it is possible that the code whis is correct for checkstyle will break the build.

yes, it could be.
The same principal is for java code. We can parse wihout any error non-compiled java file :) , but AST will be weird so Checks could misbehave, that is why we demand javac in issue template :).
javaparser+Checks should never demand to make incompilable code by javac.

**Comment by romani** [comment]
probably we should mention this in html documentation .... is so ... let create new issue

**Comment by pbludov** [comment]
@rnveach 
>Can you post a link where it says this? Isn't the Javadoc always a paragraph?
https://www.w3.org/TR/html401/struct/text.html#h-9.3.1
This is how the javadoc tool handles html paragraphs.

@romani 
>probably we should mention this in html documentation
Already done:
https://github.com/checkstyle/checkstyle/pull/5252/files#diff-410707f87051b90b5e46d27453020212
