### ISSUE TITLE
In french, "espace" is feminine when it points out the typography character.

### ISSUE THREAD

**Issue by gmzoughi** [checkstyle/checkstyle#5270]
https://github.com/checkstyle/checkstyle/blob/007f82bee298de789800113b582ec3adb1b53ea7/src/main/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/messages_fr.properties#L10

**Comment by romani** [comment]
Non of maintainers speak French, it supported by community, please send PR with better wording

**Comment by romani** [comment]
@gmzoughi , please provide PR with fix.

**Comment by rnveach** [comment]
@romani This looks like it was fixed in https://github.com/checkstyle/checkstyle/pull/6525 as mentioned by @sebastienaubry in his first comment.
> Fixed syntax (En français, "espace" est féminin quand il s'agit du caractère.)

I am closing the issue. Feel free to reopen if I am wrong.
