### ISSUE TITLE
cobertura coverage check failing on jdk 152

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#5283]
noticed on appveyor:
success - java version "1.8.0_144" https://ci.appveyor.com/project/Checkstyle/checkstyle/build/10229/job/xoh2k6sa6radqcp7#L32
failure  - java version "1.8.0_152" - https://ci.appveyor.com/project/Checkstyle/checkstyle/build/10230/job/5ju0fkpi6fi3enna#L29

reproducible on linux too:
```
$ java -version
java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)

$ git diff
diff --git a/pom.xml b/pom.xml
index 81c29cf..f194ad3 100644
--- a/pom.xml
+++ b/pom.xml
@@ -1569,7 +1569,7 @@
             <artifactId>cobertura-maven-plugin</artifactId>
             <version>2.7</version>
             <configuration>
-              <quiet>true</quiet>
+              <!--<quiet>true</quiet>-->
               <formats>
                 <format>xml</format>
                 <format>html</format>

$ mvn clean verify
....
[INFO] --- cobertura-maven-plugin:2.7:check (default) @ checkstyle ---
[INFO] Cobertura 2.1.1 - GNU GPL License (NO WARRANTY) - See COPYRIGHT file
[INFO] Cobertura: Loaded information on 429 classes.
[ERROR] com.puppycrawl.tools.checkstyle.utils.FilterUtils failed coverage check. Line coverage rate of 93.7% is below 100.0%

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
```
![image](https://user-images.githubusercontent.com/812984/33153947-d0ab5a54-cf99-11e7-9460-338a4379667f.png)

**Comment by romani** [comment]
reason is described at https://github.com/cobertura/cobertura/issues/170

**Comment by romani** [comment]
Fix is merged

**Comment by rnveach** [comment]
@romani appveyor fix is now causing shippable failure.
https://app.shippable.com/github/checkstyle/checkstyle/runs/5579/22/console
> `Survived items:target/pit-reports/201711230247/com.puppycrawl.tools.checkstyle.utils/FilterUtils.java.html:<td class='survived'> target/pit-reports/201711230247/com.puppycrawl.tools.checkstyle.utils/FilterUtils.java.html:<td class='covered'><pre><span class='survived'> suppressionSourceExists = suppressionSourceExists &#38;&#38; closed;</span></pre></td></tr>`
Survived items found in reports, build will be failed

**Comment by rnveach** [comment]
@romani The reason why shippable didn't fail in your PR is because nothing ran.
See https://app.shippable.com/github/checkstyle/checkstyle/runs/5576/summary/console
Everything says less than 1 minute and there is no printout for each job.

**Comment by romani** [comment]
> Something triggered shippable to skip running.

in all linux CIs we have SKIP_CI variable to skip execution while we debuging certain CI, so it skips execution if change only in other ci config. If you take a look at log, there is SKIP_CI=true,  I might be there is some bug , output is extended - #5289
