### ISSUE TITLE
LeftCurly: Allow horizontal & vertical brace alignment

### ISSUE THREAD

**Issue by aclarkxyz** [checkstyle/checkstyle#5287]
Currently the [LeftCurly](http://checkstyle.sourceforge.net/config_blocks.html#LeftCurly) module can only be used for [K&R](https://en.wikipedia.org/wiki/Indentation_style#K.26R) or [Allman](https://en.wikipedia.org/wiki/Indentation_style#Allman_style) style.
In [Allman](https://en.wikipedia.org/wiki/Indentation_style#Allman_style) mode, it disallows the concise shortcut option of including two statements on the same line, e.g.

`if (fubar()) {foo(); bar();}`

It would be useful to permit this as an additional valid option for [lcurly](http://checkstyle.sourceforge.net/property_types.html#lcurly).

Current modes for [lcurly](http://checkstyle.sourceforge.net/property_types.html#lcurly):
- eol - ([java variant of K&R](https://en.wikipedia.org/wiki/Indentation_style#Variant:_Java))
- nl - ([Allman style](https://en.wikipedia.org/wiki/Indentation_style#Allman_style))
- nlow

**Comment by romani** [comment]
> In Allman mode, it disallows the concise shortcut option of including two statements on the same line

please share a prove.

>...including two statements on the same line

Location of brace should not depend on amount of statements. You can enforce statement per line by - 
http://checkstyle.sourceforge.net/config_coding.html#OneStatementPerLine

================

please update description of issue with more details and example to prove and explain your idea.

**Comment by romani** [comment]
if not reply till end of December - I will close the issue.

**Comment by aclarkxyz** [comment]
The request documents what it is enabled by the additional feature: currently there's no way to allow statements like

`if (fubar()) {foo(); bar();}`

This PR introduces a way to make that permissible. If you need more proof than that + the trivial code to make it work, then that's your call.

**Comment by romani** [comment]
I am asking more questions as issue title and description did not match, I even tried to extend description a bit to understand your thoughts but failed.
Idea should be consistent and clearly defined as this issue will be used in release notes generation.
Please update title and description.

> This PR introduces a way to make that permissible. 

PR is failed on most of CIs, so it is not ok to merge for sure.

> the trivial code to make it work, then that's your call.

sorry we are not hosting for trivial code, if you need this feature please, document it, implement it, test it,  .... .
We will guide you, but need to make en effort to comply with all rules.

Lets start from issue clear description to let us approve issue.

**Comment by aclarkxyz** [comment]
If you don't want to include it, that's fine - I think it's a useful feature that other people might like, and we're making it available in the spirit of free software. We have our own patched version and it's working great, so we're pretty happy either way.

**Comment by romani** [comment]
>and we're making it available in the spirit of free software

This issue keep track of your fix, so if smb in need, they will get required functionality in  this spirit of free software.

If smb need buildin support please report issue properly.
