### ISSUE TITLE
format xdoc files to follow rule of LineLength (max ia 100) 

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#5291]
It is very hard to do review from gihub when line number is above 100 symbols in row.
Example:
![image](https://user-images.githubusercontent.com/812984/33213500-a8c4c806-d0dc-11e7-8171-304396fd35b9.png)
https://github.com/checkstyle/checkstyle/pull/5252/commits/8e832f19becec4efb3289aa0fd7f21f695072dc3#diff-410707f87051b90b5e46d27453020212L26

Github do show scrolling but if there are a lot of changes at page, you need to scroll to far bottom to get access to it (and you do not see required code any more)

Check need to be enforced, new web site and old web should be the same after generation, it is better to verify it by `diff` tool on folders.

There might be some exceptions(suppressions or ...), but they need to be approved.

**Comment by rnveach** [comment]
@romani This is not possible with the current implementation of `LineLengthCheck`? [It extends `AbstractCheck` so it will only process Java files](https://github.com/checkstyle/checkstyle/blob/5f7f58e116e7d1f7b4fbffab0ad3a459b242b164/src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/LineLengthCheck.java#L77).
Unless we want to break backward compatibility with the check or create a new version, we would have to use some type of hack with regular expressions to count the lines.

**Comment by romani** [comment]
Good point.
Regexp Check might help us, as we did at https://github.com/checkstyle/checkstyle/blob/master/config/checkstyle_checks.xml#L316 to enforce minimal amount of description for reason in our case it could be `.*{100,}`

**Comment by rnveach** [comment]
There are 1300 violations for this issue.

**Comment by romani** [comment]
> 500 if we ignore lines with href on the first pass.

I am fine with this, any solution that make it a bit better is ok.

**Comment by rnveach** [comment]
Linux commands should be split by `\`.
Ending comments in source tags should moved above the line and be reworded to reference that.

**Comment by romani** [comment]
@rnveach , are you going to finish this issue ? or we can give it to new projects.
Please explain where you stopped.

**Comment by rnveach** [comment]
if someone wants to finish this that is fine.
We just need to add this to our configuration to cause violations on lines 100 characters or more and fix all violations.

**Comment by romani** [comment]
A lot of fixes were done at #5791.

Now ithis issue can be closed
