### ISSUE TITLE
[API] Retrieve all the checks?

### ISSUE THREAD

**Issue by rtfpessoa** [checkstyle/checkstyle#5302]
Is there any way to get all the possible checks programmatically?

**Comment by rnveach** [comment]
Yes.
See https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/utils/ModuleReflectionUtils.java#L57 to get all modules and https://github.com/checkstyle/checkstyle/blob/master/src/test/java/com/puppycrawl/tools/checkstyle/internal/utils/CheckUtil.java#L137 to get all checks.

**Comment by romani** [comment]
additionally read - http://checkstyle.sourceforge.net/config.html#Packages 

additional source for ideas - https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/PackageObjectFactory.java

**Comment by rtfpessoa** [comment]
Thanks a lot, I will check this.

**Comment by rtfpessoa** [comment]
@rnveach, @romani I think I might have overlooked this. I though I had in AbstractCheck but might be confused. My idea is to get the information to generate something like this page http://checkstyle.sourceforge.net/config_sizes.html can you point me in the right direction?

**Comment by rnveach** [comment]
> My idea is to get the information to generate something like this page http://checkstyle.sourceforge.net/config_sizes.html

Check out https://github.com/checkstyle/checkstyle/blob/master/src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java#L251 and https://github.com/checkstyle/checkstyle/blob/master/src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java#L299 ,
Note that this will not build the xdoc pages, but verify they have the necessary information. The xdoc pages are still built by hand. We are slowly working towards this goal.

**Comment by rtfpessoa** [comment]
Ok, thank you.
