### ISSUE TITLE
EmptyLineSeparator: add xdoc examples

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#5314]
http://checkstyle.sourceforge.net/config_whitespace.html#EmptyLineSeparator

code: https://github.com/checkstyle/checkstyle/blob/master/src/xdocs/config_whitespace.xml#L218

add examples for all properties, with "// violation" comments inlined to code to show place of violation.

All examples should be compilable by "javac" actual violations on such examples you can get by our CLI - http://checkstyle.sourceforge.net/cmdline.html

**Comment by aneels3** [comment]
I'am Interested to work on this issue.

**Comment by romani** [comment]
thanks a lot, please be welcome with PR.

**Comment by aneels3** [comment]
ok , I'am on it

**Comment by romani** [comment]
@Dhiveshan , can you help us with this issue ?

**Comment by Dhiveshan** [comment]
I am on it

**Comment by pbludov** [comment]
The changes should be done in #7619
