### ISSUE TITLE
AnnotationUtility.getAnnotation fails when there is an comment in the annotation

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#5327]
Identified when working on https://github.com/checkstyle/checkstyle/issues/4983 , example code:
````
    /**
     * @Deprecated this is not the same
     */
    @Deprecated
    protected InputMissingDeprecatedBadJavadoc() {

    }
````

printing the AST shows the following:
````
    |--CTOR_DEF -> CTOR_DEF [5:4]
    |  |--MODIFIERS -> MODIFIERS [5:4]
    |  |  |--ANNOTATION -> ANNOTATION [5:4]
    |  |  |  |--BLOCK_COMMENT_BEGIN -> /* [2:4]
    |  |  |  |  |--COMMENT_CONTENT -> *\n    * @Deprecated this is not the same\n      [2:6]
    |  |  |  |  `--BLOCK_COMMENT_END -> */ [4:5]
    |  |  |  |--AT -> @ [5:4]
    |  |  |  `--IDENT -> Deprecated [5:5]
    |  |  `--LITERAL_PROTECTED -> protected [6:4]
````

The first child of the annotation is the `BLOCK_COMMENT_BEGIN` but [this messes up the utility as it is thinking the first child is the `AT` token](https://github.com/checkstyle/checkstyle/blob/f0ed29b5cfef6adcec791cfdc236a5b850b685ee/src/main/java/com/puppycrawl/tools/checkstyle/utils/AnnotationUtility.java#L158).
This causes the utility to not find the `@Deprecated` annotation and return it doesn't exist.

This is not an issue with `MissingDeprecatedCheck` right now because it is not comment aware, but it is breaking the rules by getting the comment/javadoc of what it is examining. The rewrite is turning it into a comment aware check which is why it is showing up now.

**Comment by romani** [comment]
fix is merged
