### ISSUE TITLE
renaming in TokenTypes

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#5333]
I always hated such names:
http://checkstyle.sourceforge.net/apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#OBJBLOCK
http://checkstyle.sourceforge.net/apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#SLIST
EMPTY_STAT
LABELED_STAT

it is better to rename them to:
OBJ_BLOCK or OBJECT_BLOCK
STATEMENT_LIST
EMPTY_STATEMENT
LABELED_STATEMENT

it is better to provide examples of AST for all of them.

**Comment by romani** [comment]
@rnveach , what do you think ?
braking compatibility will be only on compilation time.

**Comment by rnveach** [comment]
> braking compatibility will be only on compilation time.

Please explain this statement.
Even if we only rename in `TokenTypes` and leave grammar as is, this will still break all existing custom checks that use old name. All of sevntu will have be renamed. Sonar will have to be done too as it pulls in token types. Eclipse-cs will have to update their custom config too.
I myself am fine with breaking compatibility.

If we are going to go through with this, we can add these to the list:
EXPR -> EXPRESSION
ELIST -> EXPRESSION_LIST

Some other questionable ones:
SEMI -> LITERAL_SEMICOLON
LCURLY -> LITERAL_LCURLY
RCURLY -> LITERAL_RCURLY
COMMA, LPAREN, RPAREN, ASSIGN, COLON, DOUBLE_COLON, DO_WHILE, PLUS_ASSIGN, etc....

**Comment by romani** [comment]
it was bad idea .....
we keep all tokens as map string value and its integer value - https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/utils/TokenUtils.java#L40
so after update all configurations in the world should be updated. It is too much.
