### ISSUE TITLE
Deprecate com.puppycrawl.tools.checkstyle.api.AutomaticBean

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#5337]
Discussed at https://github.com/checkstyle/checkstyle/pull/5322#discussion_r155799488 ,

`AutomaticBean` should be renamed to `AbstractAutomaicBean` since it is now abstract.

Additionally we should discuss if we should keep `AutomaticBean` in name.

**Comment by SinmoWay** [comment]
I propose to stop on the name `AbstractAutomatinBean` and do not change anything else.
However, there is an option for the separation of the implementation `AbstractAutomationBean` and `AbstractAutomatic` but I have not yet thought it over well enough.

**Comment by rnveach** [comment]
This change will break maven checkstyle: https://github.com/apache/maven-checkstyle-plugin/blob/ab6a941b61e49fe114c00c3ce412d6b985c95df7/src/main/java/org/apache/maven/plugins/checkstyle/exec/CheckstyleCheckerListener.java#L42
eclipse-cs seems fine.

We will have to create new class with old name and rename old class to new name.

**Comment by Rahulkhinchi03** [comment]
@rnveach is this issue still valid?

**Comment by rnveach** [comment]
Nothing has been said that would say otherwise.

**Comment by Rahulkhinchi03** [comment]
I would like to try this issue. Can you please help in understanding how to mark this API as deprecated? Just a @deprecated works?

**Comment by romani** [comment]
take a look at jacoco config in pom.xml, we have ability to exclude class from code coverage, we do not need to test something that use to work well and now become deprecated.

**Comment by rnveach** [comment]
@Rahulkhinchi03 This issue should be very similar to https://github.com/checkstyle/checkstyle/issues/2551 . Both renamed classes to others and marked them as deprecated and were eventually removed.

**Comment by stoyanK7** [comment]
On it.

**Comment by romani** [comment]
@rnveach , @nrmancuso , I think we need to change label of this issue to bug or misc.

**Comment by nrmancuso** [comment]
Since we only deprecate this class in scope of this issue, and do full removal in https://github.com/checkstyle/checkstyle/issues/12873, this makes sense.

**Comment by romani** [comment]
bug or misc ?
