### ISSUE TITLE
Move, Rename, and remove abstract from AbstractLoader

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#5338]
Discussed at https://github.com/checkstyle/checkstyle/pull/5322#pullrequestreview-82182260 ,

`AbstractLoader` should be moved outside of `api` package and renamed to `XmlLoader` and be changed to a concrete class.
Suppression in intellij-idea-inspections.xml needs to be removed.

**Comment by romani** [comment]
fix is merged
