### ISSUE TITLE
Reformat the checkstyle sources for the new check

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#5343]
Once #5313 will be done, the existing sources should be redone in accordance with the new style changes.

Despite the fact that there is more than a thousand of violations, almost all of them can be fixed with regular expressions.

**Comment by rnveach** [comment]
@pbludov Violations in this project should be done inside the scope of the PR since we are activating it on our own code, unless romani says otherwise.
Violations in sevntu project should be done before the PR is merged as CI is red because of it.

**Comment by romani** [comment]
Code should be reformatted is scope of PR that introduce a rule, we should eat food we produce, as is shown a pain of such Check usage and as result show us rooms for improvements if required.

Reformatting should be done in separate commit and might be merged a bit in advance of main logic merge.
