### ISSUE TITLE
SummaryJavadoc: case insensitive for forbiddenSummaryFragments (rfc)

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#5345]
I' a bit tired of typing "[Bb][Ll][Aa][Bb][Ll][Aa][Bb][Ll][Aa]" for forbiddenSummaryFragments.
Let's add the property "caseInsensieve" to SummaryJavadocCheck like one in IllegalTokenTextCheck.

Or, even better, we shall invent the syntax for specifying flags to any regexp property.
For example, "/blablabla/mi"  for case insensitive multiline regexp.

**Comment by romani** [comment]
is summary a single line on moment of validation ?

Can you show real cases that you try to forbid ?
You will never make regexp that covers all possible fillers of javadoc , when engineers are lazy and want to cheat checkstyle, it it better to demand javadoc first sentence to be longer than some size

**Comment by pbludov** [comment]
You're right. This should be done with the RegExp check. Too bad we don't have the RegexpSinglelineComment check.
