### ISSUE TITLE
IndentationCheck: problem with content of anonymous class

### ISSUE THREAD

**Issue by liutikas** [checkstyle/checkstyle#5362]
`/var/tmp $ javac ManageHightPower.java`:

```
No output. Success.
```

`/var/tmp $ cat ManageHighPower.java`:

```
package com.android.tv.settings.device.apps.specialaccess;

public class ManageHighPower {

    private final StringBuffer mFilter =
            new StringBuffer(
                    new CharSequence() {
                        @Override                              // line 8
                        public char charAt(int index) {
                            return 'A';
                        }

                        public int length() {
                            return 1;
                        }

                        public CharSequence subSequence(int start, int end) {
                            return this;
                        }

                        public String toString() {
                            return "Foo";
                        }
                    });
}
```

`/var/tmp $ cat config.xml`:

```
<!DOCTYPE module PUBLIC "-//Puppy Crawl//DTD Check Configuration 1.3//EN" "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
<module name="Checker">
      <module name="TreeWalker">
          <module name="Indentation">
              <property name="severity" value="error"/>
              <property name="basicOffset" value="4"/>
              <property name="throwsIndent" value="8"/>
              <property name="lineWrappingIndentation" value="8"/>
          </module>
      </module>
</module>
```

`/var/tmp $ java -Duser.language=en -Duser.country=US -jar checkstyle-8.5-all.jar -c config.xml ManageHighPower.java`:

```
Starting audit...
[ERROR] .../ManageHighPower.java:8: 'method def modifier' has incorrect indentation level 24, expected level should be one of the following: 12, 16, 20. [Indentation]
[ERROR] .../ManageHighPower.java:10: 'method def' child has incorrect indentation level 28, expected level should be one of the following: 16, 20, 24. [Indentation]
[ERROR] .../ManageHighPower.java:11: 'method def rcurly' has incorrect indentation level 24, expected level should be one of the following: 12, 16, 20. [Indentation]
[ERROR] .../ManageHighPower.java:13: 'method def modifier' has incorrect indentation level 24, expected level should be one of the following: 12, 16, 20. [Indentation]
[ERROR] .../ManageHighPower.java:14: 'method def' child has incorrect indentation level 28, expected level should be one of the following: 16, 20, 24. [Indentation]
[ERROR] .../ManageHighPower.java:15: 'method def rcurly' has incorrect indentation level 24, expected level should be one of the following: 12, 16, 20. [Indentation]
[ERROR] .../ManageHighPower.java:17: 'method def modifier' has incorrect indentation level 24, expected level should be one of the following: 12, 16, 20. [Indentation]
[ERROR] .../ManageHighPower.java:18: 'method def' child has incorrect indentation level 28, expected level should be one of the following: 16, 20, 24. [Indentation]
[ERROR] .../ManageHighPower.java:19: 'method def rcurly' has incorrect indentation level 24, expected level should be one of the following: 12, 16, 20. [Indentation]
[ERROR] .../ManageHighPower.java:21: 'method def modifier' has incorrect indentation level 24, expected level should be one of the following: 12, 16, 20. [Indentation]
[ERROR] .../ManageHighPower.java:22: 'method def' child has incorrect indentation level 28, expected level should be one of the following: 16, 20, 24. [Indentation]
[ERROR] .../Desktop/ManageHighPower.java:23: 'method def rcurly' has incorrect indentation level 24, expected level should be one of the following: 12, 16, 20. [Indentation]
[ERROR] .../ManageHighPower.java:24: 'object def rcurly' has incorrect indentation level 20, expected level should be one of the following: 8, 12, 16. [Indentation]
Audit done.
Checkstyle ends with 13 errors.
```

---------------

I expected the indention to be correct without any warnings.

--------------

**Comment by Abhishek-kumar09** [comment]
@romani
> please review existing issues https://github.com/checkstyle/checkstyle/issues?q=is%3Aopen+is%3Aissue+label%3Aindentation or create new issue on this.

This issue covers all the problem related to indentation issue for `new` keyword.
The other linked or similar issue could be: https://github.com/checkstyle/checkstyle/issues/6029

**Comment by Abhishek-kumar09** [comment]
I am on it.

**Comment by Abhishek-kumar09** [comment]
@romani 
What amount of lineWrappingIndenetation does checkstyle intended to follow. because there are mixed amount of lineWrappingIndentation being used inside the codebase. 
![imageedit_5_8025337345](https://user-images.githubusercontent.com/48255244/98852148-3bef9100-247d-11eb-9ad0-5069548e5142.gif)
Since now, the position of new keyword itself is checked there are huge amount of errors raised due to it.
Though in [checkstyle_checks.xml](https://github.com/checkstyle/checkstyle/blob/master/config/checkstyle_checks.xml#L635-L640) the lineWrappingIndentation (default) is 4, but at many places it is not followed, one is the example above.
There are numerous examples of new Keyword where the 8 lineWrappingIndentation is used, (Now they are raising issues) [here is one for example](https://github.com/checkstyle/checkstyle/blob/master/src/test/java/com/puppycrawl/tools/checkstyle/api/FileContentsTest.java#L62-L71)
What should I do?

**Comment by romani** [comment]
>What should I do?

We can fix our code to follow requirements of Check.
No surprise, no violation from Check, and code is any form, humans can not keep track of this during code review.

> I guess forceStrict false should allow everything beyond 4, and thus no violation is raised. I will change the code accordingly.

We do not use strict mode, so any extra indentation is ok if author think it contribute to code read-abillity. It especially benefitial in IF expression to draw order of execution by indentation.

**Comment by strkkk** [comment]
Fix is merged

**Comment by jcamerin** [comment]
This change introduced https://github.com/checkstyle/checkstyle/issues/9071
