### ISSUE TITLE
Unable to build project

### ISSUE THREAD

**Issue by sd1998** [checkstyle/checkstyle#5365]
I am unable to build project on MacOS. Here are the error logs.

<img width="1439" alt="screen shot 2017-12-18 at 11 05 42 am" src="https://user-images.githubusercontent.com/22047421/34091409-6f856cca-e3e3-11e7-915c-1ff70e9dd76b.png">

**Comment by rnveach** [comment]
> ExceptionInInitializerError
> Signals that an unexpected exception has occurred in a static initializer

@sd1998 Can you use options `-e` and `-X` to verify where the failure is on MacOS? I assume it is a specific class by the error.
None of us have a Mac and our MacOS build on travis has no issues building.
https://travis-ci.org/checkstyle/checkstyle/jobs/317397033

**Comment by sd1998** [comment]
@rnveach 
After using -X switch :- 
[X.txt](https://github.com/checkstyle/checkstyle/files/1568471/X.txt)
After using -e switch :- 
[e.txt](https://github.com/checkstyle/checkstyle/files/1568472/e.txt)

I am using JDK 9

**Comment by rnveach** [comment]
> Caused by: java.lang.ExceptionInInitializerError
> Caused by: java.lang.StringIndexOutOfBoundsException: begin 0, end 3, length 1
    at java.lang.String.checkBoundsBeginEnd (String.java:3116)
    at java.lang.String.substring (String.java:1885)
    at org.apache.commons.lang.SystemUtils.getJavaVersionAsFloat (SystemUtils.java:1122)
    at org.apache.commons.lang.SystemUtils.<clinit> (SystemUtils.java:818)
    at org.apache.maven.plugins.enforcer.RequireJavaVersion.execute (RequireJavaVersion.java:52)
    at org.apache.maven.plugins.enforcer.EnforceMojo.execute (EnforceMojo.java:193)

The exception doesn't appear to be in Checkstyle's code. You may need to contact the plugin's maintainer for the exception.

> I am using JDK 9

We are not compliant with JDK 9 yet. Please see https://github.com/checkstyle/checkstyle/issues/5102 .
I suggest you stick to JDK 8.

**Comment by sd1998** [comment]
@rnveach Thanks Using JDK 8 its working. I will be closing the Issue now.
