### ISSUE TITLE
Resolve warning during build about prerequisites tag

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#5377]
Detected at https://travis-ci.org/checkstyle/checkstyle/jobs/319546867#L739

`[WARNING] The project com.puppycrawl.tools:checkstyle:jar:8.6-SNAPSHOT uses prerequisites which is only intended for maven-plugin projects but not for non maven-plugin projects. For such purposes you should use the maven-enforcer-plugin. See https://maven.apache.org/enforcer/enforcer-rules/requireMavenVersion.html`

This warning should be resolved.

Mentioned at https://maven.apache.org/docs/3.5.0/release-notes.html

How to resolve:
https://maven.apache.org/enforcer/enforcer-rules/requireMavenVersion.html

**Comment by SinmoWay** [comment]
I am on it.

**Comment by romani** [comment]
fix is merged.
