### ISSUE TITLE
 <property name="file" value="${config_loc}/suppressions.xml"/>

### ISSUE THREAD

**Issue by bhuism** [checkstyle/checkstyle#5381]
`/var/tmp $ javac YOUR_FILE.java`:

```
[[PLACE YOUR OUTPUT HERE]]
```

`/var/tmp $ cat YOUR_FILE.java`:

```
[[PLACE YOU OUTPUT HERE]]
```

`/var/tmp $ cat config.xml`:

```
[[PLACE YOUR OUTPUT HERE]]
```

`/var/tmp $ java -Duser.language=en -Duser.country=US -jar checkstyle-X.XX-all.jar -c config.xml YOUR_FILE.java`:

```
[[PLACE YOUR OUTPUT HERE]]
```

---------------

Describe what you expect in detail.

--------------

Still not clear ??? - see example - http://checkstyle.sourceforge.net/report_issue.html#How_to_report_a_bug

**Comment by rnveach** [comment]
@bhuism your issue report makes no sense. Please update it if you have an problem with checkstyle otherwise I will close it.

**Comment by bhuism** [comment]
@rnveach my mistake, no iead what happend, didn't mean to create an issue at all
