### ISSUE TITLE
Add @exception JavaDoc block tag to NonEmptyAtclauseDescriptionCheck

### ISSUE THREAD

**Issue by sikhlev** [checkstyle/checkstyle#5388]
`@exception` JavaDoc block tag is a part of the JavaDoc specification and it may not be empty. 
Taken from #5092 .

**Comment by romani** [comment]
fix is merged

**Comment by romani** [comment]
![image](https://user-images.githubusercontent.com/812984/34641149-56ec7f84-f2b4-11e7-86bf-0c44c2e027de.png)

**Comment by rnveach** [comment]
@romani I moved this to a new issue so it doesn't get lost in this closed one.
See https://github.com/checkstyle/checkstyle/issues/5443
