### ISSUE TITLE
Add example of custom jars to Ant Documentation

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#5389]
http://checkstyle.sourceforge.net/anttask.html

Should have an example similar to https://github.com/checkstyle/checkstyle/blob/6db65fbd6e39ee78937d6c16e618e201d222b8c2/config/ant-phase-verify.xml#L33 to show how to add a custom JAR (like sevntu) to the classpath.

**Comment by sakshi-1604** [comment]
I am on it

**Comment by vidhwanshak** [comment]
Hey @rnveach I would like to work on this issue. 
Please clear my concerns:
1. I need to make a new topic on https://checkstyle.sourceforge.io/anttask.html#Installation by the name of `adding custom JAR file` and add the details to it?

**Comment by vidhwanshak** [comment]
How can I access the source code of https://checkstyle.sourceforge.io/anttask.html ?

**Comment by vidhwanshak** [comment]
Hey @sakshi-1604 are you still working on this issue?

**Comment by sakshi-1604** [comment]
No you can work on it

**Comment by rnveach** [comment]
> How can I access the source code of https://checkstyle.sourceforge.io/anttask.html 

https://github.com/checkstyle/checkstyle/blob/master/src/xdocs/anttask.xml.vm

> I need to 

Make the changes that you think are needed and we will review. It should cover an example of how to configure this with any other descriptions that are needed.

**Comment by nmancus1** [comment]
@rnveach this issue is fairly old, can you take a look at the link you've provided in the issue description to make sure example is still valid?

**Comment by rnveach** [comment]
Issue is still valid.

**Comment by nthakur34** [comment]
take

**Comment by nthakur34** [comment]
I am working on this issue. let me know if any concerns.

**Comment by romani** [comment]
Fix is merged
