### ISSUE TITLE
Some contents in messages_zh.properties for imports check are not well translated

### ISSUE THREAD

**Issue by Apache9** [checkstyle/checkstyle#5393]
`import.groups.separated.internally=進口組以前的額外分離 ''{0}''。`
This is Traditional Chinese while others are all Simplified Chinese.

`import.illegal=非法进口： {0} 。`
Here import is translated to '进口' while others are all translated to '导入'.

`import.same=额外 import 当前包下内容：{0} 。`
Here we just keep the English word 'import' while others are all translated to Chinese.

**Comment by rnveach** [comment]
@Apache9 please start a PR into make the changes required. No one on the team knows the language.

**Comment by Apache9** [comment]
I've already fix and when I created the PR it says that I need to start a issue and get an 'approved ' label first before submitting a PR...

**Comment by romani** [comment]
fix is merged.
