### ISSUE TITLE
Incorrect documentation for SuppressionXpathFilter

### ISSUE THREAD

**Issue by MEZk** [checkstyle/checkstyle#5400]
From [xdocs](https://github.com/checkstyle/checkstyle/blob/master/src/xdocs/config_filters.xml#L670):

```
        <p>
          Currently, filter supports the following
          checks:
        </p>
        <ul>
          <li>CyclomaticComplexityCheck</li>
          <li>DeclarationOrderCheck</li>
          <li>DefaultComesLastCheck</li>
          <li>ExplicitInitializationCheck</li>
          <li>FallThroughCheck</li>
          <li>HiddenFieldCheck</li>
          <li>IllegalCatchCheck</li>
          <li>IllegalThrowsCheck</li>
          <li>JavadocMethodCheck</li>
          <li>JavadocVariableCheck</li>
          <li>ImportControlCheck</li>
          <li>LeftCurlyCheck</li>
          <li>MethodParamPadCheck</li>
          <li>MultipleVariableDeclarationCheck</li>
          <li>NestedForDepthCheck</li>
          <li>NestedIfDepthCheck</li>
          <li>NestedTryDepthCheck</li>
          <li>NPathComplexityCheck</li>
          <li>OneStatementPerLineCheck</li>
          <li>OuterTypeNumberCheck</li>
          <li>RequireThisCheck</li>
          <li>RightCurlyCheck</li>
        </ul>
```

1) JavadocMethodCheck in [some cases](https://github.com/checkstyle/checkstyle/blob/03776416fef945f5ef204075bf2ac272f3a03b33/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheck.java#L772) uses ```log``` method which does not set token type. If the check does not pass token type to log method (or AST object), we will not find the token in the Xtah-based tree [here](https://github.com/checkstyle/checkstyle/blob/1c73987f2f560ecabb6825943c8362fb11b67749/src/main/java/com/puppycrawl/tools/checkstyle/filters/XpathFilter.java#L160) as there are no tokens with index = 0 (0 is set by default in [LocalizedMessage constructor](https://github.com/checkstyle/checkstyle/blob/b16aef991830dd1fce1ce2640af7e7db8b329d86/src/main/java/com/puppycrawl/tools/checkstyle/api/LocalizedMessage.java#L201) method if token type is not set directly).  So we cannot say that we support JavadocMethodCheck in the new suppression model till https://github.com/checkstyle/checkstyle/issues/4830. Thus, JavadocMethodCheck should be removed from the list of supported checks.
2) ... need more time to review

**Comment by MEZk** [comment]
@romani 
FYI

**Comment by romani** [comment]
@MEZk or @timurt , please remove all Checks from list that you are not sure about. In other case users will start create issues.

**Comment by romani** [comment]
@timurt ,  thanks from fix.
Can you confirm that all others Checks are correct?

**Comment by timurt** [comment]
@romani 
They must be correct
I ran xpath suppressions on some of them. These checks call `AbstractCheck.log(DetailAST ast, String key, Object... args)` method and they do not use other `log` methods - two main conditions required for suppressing by xpath.

**Comment by MEZk** [comment]
@romani 
Yes, @timurt is right
