### ISSUE TITLE
New MissingJavadocCheck(s)

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#5411]
As discussed at https://github.com/checkstyle/checkstyle/issues/4983#issuecomment-350503360 ,

once we start converting old Java checks using Javadoc regular expression to Javadoc checks using grammar, we lose the functionality of reporting a violation on an item if a Javadoc is missing.

[MissingDeprecated](http://checkstyle.sourceforge.net/config_annotation.html#MissingDeprecated) has an property `skipNoJavadoc` which will skip violations if a javadoc is missing on a deprecated method.
[JavadocMethodCheck](http://checkstyle.sourceforge.net/config_javadoc.html#JavadocMethod) has various properties like `minLineCount` and `allowedAnnotations` which will not print a missing javadoc violation if the number of lines in the method are too small or it contains an annotation.

We can't remove these functionalities, so we need to split them into new check(s) that will remain as Java checks. Their only purpose will be to report a violation if a javadoc is needed.

We need to examine all these properties of our Java checks that examine Javadocs and decide how to best to split them out.
Should we have a new check for each type (Class, Method, etc...) or should they all be contained into 1 check?
Which properties do these new check(s) need from our existing checks? We will need to create a complete list.

Once this is done we can complete https://github.com/checkstyle/checkstyle/issues/4983.
  
---------------------

**Migration Note**

For JavadocType, functionality for validating missing javadocs was split into a new check MissingJavadocType. `scope` and `excludeScope` properties were brought to the new check. `allowedAnnotations` was brought over but renamed to `skipAnnotations`.

**Comment by pbludov** [comment]
There is also the UnusedImportCheck, which is both a java and a javadoc check.
For now, this is a java check with all the javadoc stuff implemented with the regular expressions.
Perhaps it makes sense to invent a dedicated kind of checks for such cases.

Here is the basic idea:
https://github.com/checkstyle/checkstyle/issues/2840#issuecomment-282968053

**Comment by romani** [comment]
rules/criteria for reporting violations for Class and Method could be very different.
For class - if it is public, if extends, is abstract, if deprecated ....
For method - if public, if abstract, if deprecated, if size is bigger in lines, if throws, if name is match regexp, if arguments amount above N.

We will need separate Check for this:
MissingTypeJavadocCheck (class, enum, interface)
MissingMethodJavadocCheck (methods)

user should define by properties what is triggering validation. 
By default it is good to demand javadoc on deprecated methods/classes.

@rnveach , please share your ideas.

**Comment by rnveach** [comment]
> MissingMethodJavadocCheck 

I think we should name them as their original check and just add `Missing` to the front. First time reading `MissingMethodJavadoc` all I was thinking was `MissingMethod`.

There is also `JavadocVariable` as well as `JavadocType` and `JavadocMethod`.

I am fine with your ideas. So we will basically take the existing checks and their properties and make new ones that just validate missing Javadoc.
We should remove this check from old code as it will be redundant and it will allow us to verify in regression we didn't change functionality any. Old check + new check should mean there will be 0 differences in regression for missing javadocs.

**Comment by romani** [comment]
MissingJavadocTypeCheck (class, enum, interface)
MissingJavadocMethodCheck (methods)

are you ok with such names ?

> We should remove this check from old code 

this ? please be name it, too much checks are involved.

> Old check + new check should mean there will be 0 differences in regression for missing javadocs

existing MissingDeprecatedCheck should stay and become javadoc Check to trigger on each javadoc comment, check java annotation, and then search for javadoc tag and do match. New MissingJavadocMethodCheck should force user to write javadoc when annotation is present, to let on next launch trigger execution of MissingDeprecatedCheck. So it 2 launches of checkstyle all cases should be covered.

**Comment by rnveach** [comment]
> are you ok with such names ?

Yes. Don't forget `MissingJavadocVariableCheck`.

> > We should remove this check from old code

> this ? 

Sorry, I meant the validation of 'is a javadoc is missing' should be removed from existing check in the same PR we add the new check. This will allow us to run regression with both in the configuration and prove there are no differences. We are basically splitting the functionality of the check into 2.

**Comment by romani** [comment]
@rnveach , I squashed all your+my comments in my above post, please review one more time.

**Comment by rnveach** [comment]
It looks fine to me.

**Comment by pbludov** [comment]
And MissingJavadocPackageInfoCheck (package-info.java)

**Comment by rnveach** [comment]
> And MissingJavadocPackageInfoCheck (package-info.java)

`JavadocPackageCheck` isn't even an `AbstractCheck` so it doesn't need a `Missing` version.
It just examines the file's existence and not anything inside it.

**Comment by rnveach** [comment]
I am approving this as this was agreed on.

**Comment by rnveach** [comment]
> MissingJavadocTypeCheck (class, enum, interface)
MissingJavadocMethodCheck (methods)
MissingJavadocVariableCheck (fields)

Just for completeness, other tokens needed are: constructors (method), annotation definitions (type), enum constant definition (field), annotation field (field).

We recently added javadoc parsing on packages. I think we should have `MissingJavadocPackageCheck` only if the file is `package-info.java` like @pbludov suggested. We should have a missing for every place a javadoc is valid.

**Comment by rnveach** [comment]
Changes to `JavadocMethod` will affect google_checks. None of the other Javadoc checks are in the config.

**Comment by rnveach** [comment]
@romani This can't be closed. We only converted 1 check, 1 is still open in PR, and we probably have around 3 left.

**Comment by romani** [comment]
Probably better to create separate issues, as such long issues conflicts with milestones on issue

**Comment by rnveach** [comment]
I will do this.

**Comment by rnveach** [comment]
Closing this as new issues were created. Let me know if I missed anything.

**Comment by romani** [comment]
It is ok to keep miscellaneous issue in few releases, but all issues that affects users are better to scope in single release, as issues are  major part of our knowledge base.
