### ISSUE TITLE
XmlLogger sanitizes exception tags when it shouldn't be

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#5419]
Identified at https://github.com/checkstyle/checkstyle/issues/5166 when looking at https://github.com/checkstyle/checkstyle/blob/master/src/test/resources/com/puppycrawl/tools/checkstyle/xmllogger/ExpectedXMLLoggerException.xml ,

````
<?xml version="1.0" encoding="UTF-8"?>
<checkstyle version="">
&lt;exception&gt;&#10;&lt;![CDATA[&#10;stackTrace&#10;example]]&gt;&#10;&lt;/exception&gt;&#10;
</checkstyle>
````

`&lt;exception&gt;` shouldn't be encoded in the XML file. it should be a pure tag like `<exception>`.

**Comment by romani** [comment]
@rnveach ,

XmlLogger write tag properly - https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/XMLLogger.java#L243

we use this test file for some exceptional case - https://github.com/checkstyle/checkstyle/blob/master/src/test/java/com/puppycrawl/tools/checkstyle/XMLLoggerTest.java#L253 

please clarify your issue.

**Comment by rnveach** [comment]
@romani exception is its own tag, but we encode it as text instead of a tag. Look at changes in expected files in PR and you should see the difference.

**Comment by romani** [comment]
fix is merged
