### ISSUE TITLE
TokenTypes documentation contains double encoded symbols

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#5423]
This file
http://checkstyle.sourceforge.net/apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html
http://checkstyle.sourceforge.net/apidocs/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.html
is hard to read. Many symbols are displayed in encoded form.

Some examples:

Modifier and Type | Field and Description
-- | --
static int | LNOT The &amp;#33; (logical complement) operator.
static int | LE The &amp;lt;= (less than or equal) operator.
static int | BSR The &amp;gt;&amp;gt;&amp;gt; (unsigned shift right) operator.
static int | BSR_ASSIGN The &amp;gt;&amp;gt;&amp;gt;= (unsigned right shift assignment)  operator.

It looks like encoded symbols were not decoded when &lt;code&gt; &lt;/ code&gt; was replaced with {@ code}. It's a bug in the Idea actually. But the docs need to be fixed anyway.

regression caused by https://github.com/checkstyle/checkstyle/commit/70786709d4f735b9123159a86a752789855af34a in scope of #4805

see limitations of `@code` tag at - #5425

**Comment by rnveach** [comment]
I agree with this. Users shouldn't need to know HTML encoding to understand the document.

**Comment by romani** [comment]
fix is merged.
