### ISSUE TITLE
AvoidEscapedUnicodeCharactersCheck: re-organize regular expressions

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#5427]
http://rveach.no-ip.org/checkstyle/regression/reports/issue5409.html

Based on the amount of duplications and removals found in https://github.com/checkstyle/checkstyle/pull/5410 , all the regular expressions in AvoidEscapedUnicodeCharactersCheck have uneven lines and the regular expression groups are out of order. 

Example:
https://github.com/checkstyle/checkstyle/blob/37bf2883a913e6aee2450e5ad72d78c65964778b/src/main/java/com/puppycrawl/tools/checkstyle/checks/AvoidEscapedUnicodeCharactersCheck.java#L146-L150

We have `2007` then `2000` then `007[fF]` then back to `2066`.

There doesn't seem to be a pattern to the ordering and reading these are not easy. We should sort the regular expression groups and align the end of the lines so they are easier to read and maintain.
`UNICODE_CONTROL` and `NON_PRINTABLE_CHARS` should be split apart after the `|` in the expression and placed in order as best as possible.
I am currently thinking that 2-3 alternatives per line should be good. There are 69 `|`s in `NON_PRINTABLE_CHARS` regular expression.

Example:
Change:
````
       + "005|002|"
       + "003|"
       + "001|000|"
````
into
````
       + "000|001|002|"
       + "003|004|005|"
````

**Comment by romani** [comment]
Your inteliij idea report is not accesible - please fix.
As I always told duplication cost less than dependencies, we should be very accurate with this.
Each case should be discussed separately.

**Comment by rnveach** [comment]
> Your inteliij idea report is not accesible - please fix.

It works fine for me.

> Each case should be discussed separately.

What do you mean by case? Each field or each instance of the content between `|`?

**Comment by romani** [comment]
Ok, now link work fine too me.
Please state exactly what violation you try to fix. Please do copy from your report. I do not see what correspond to 69 violations.

**Comment by rnveach** [comment]
@romani There is no violation I'm trying to fix here. Fixes are in scope of other issue.
This is prettying the regular expression up.
Right now we have lines with uneven lengths. I want to even them out and organize all groups numerically.

**Comment by romani** [comment]
I still have problems to understand what you try to target , looks like you mean some work in https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/AvoidEscapedUnicodeCharactersCheck.java

please clarify issue description , imagine I am student , and I need to understand from issue description what is a problem.

**Comment by rnveach** [comment]
@romani I updated first post. Sorry for confusion.

**Comment by SunriseCoder** [comment]
I would like to take this issue

**Comment by rnveach** [comment]
@SunriseCoder Go right ahead.

**Comment by SunriseCoder** [comment]
For better maintenance and readability I would suggest to keep one code per line only.
It's much easier to search through and we don't have to reformat lines after insertion of the new codes.

**Comment by romani** [comment]
Issue is still open , why is left to be done ?

**Comment by rnveach** [comment]
There shouldn't be anything else left to do, so I am closing this.

@Vladlis Please remember to check if issue should be closed when you merge the PR.
If you are unsure, post a comment in issue and ping us to verify.

**Comment by Vladlis** [comment]
Ok, sorry
