### ISSUE TITLE
Split TreeWalker to TreeWalker and JavaParser

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#5436]
There is a lot of duplicated code for parsing a java file into the AST in the project. #5102 need another one.
To get rid of unnecessary copy'n'paste, duplicate code is need to be extracted into an utility class.
Also, the TreeWalker class is too complicated and requires a split to allow future refactoring.

**Comment by rnveach** [comment]
The results of this issue is similar to https://github.com/checkstyle/checkstyle/issues/3340#issuecomment-230869303 but the other one is for Javadoc while this one is for Java.

**Comment by romani** [comment]
@rnveach , I do not understand how simple moving same code around could make a difference in behavior.

**Comment by rnveach** [comment]
@romani It shouldn't matter in TreeWalker. TreeWalker doesn't make it's own violations based on failed parsing.
In AbstractJavadocCheck, parsing errors are made into violations and are connected to every Javadoc check. This is what causes different violations in different runs in other issue. We have seen this issue in multiple regressions on Javadoc checks and had private emails about this my comment in other issue was made from our emails.

**Comment by romani** [comment]
ok, but why you raising this in this issue ?

**Comment by rnveach** [comment]
Just commenting on how similar they are. Other issue should follow a similar pattern when it is worked on.

**Comment by romani** [comment]
Fix is merged.
It might cause problems to users
