### ISSUE TITLE
LeftCurly: must handle all possible occurrences of {

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#5456]
The [LeftCurlyCheck](http://checkstyle.sourceforge.net/config_blocks.html#LeftCurly) LeftCurlyCheck must handle all possible occurrences of `{`(except `INSTANCE_INIT`). Currently, it lacks support for annotation arrays (`ANNOTATION_ARRAY_INIT`)
```
@Mapper(uses = {
    Foo.class,
    Bar.class,
    Baz.class })
public class FooMapper {}
```

Anonymous classes (`LITERAL_NEW`)
```
Runnable runnable = new Runnable() {
    @Override public void run() {
    }
};
```

Arrays (`ARRAY_INIT`)
```
int[] array = new int[] { 1, 2, 3 };
```
The last is questionable, since multidimensional arrays may have a different style for different levels, i.e.:
```
int[][] array = new int[][] {
  { 1, 2, 3 },
  { 1, 2, 3 },
  { 1, 2, 3 },
};
```

**Comment by MEZk** [comment]
> The LeftCurlyCheck LeftCurlyCheck must handle all possible occurrences of {(except INSTANCE_INIT).

We cannot predict all occurrences of '{'.

@pbludov 
Please, split your requests into multiple issues. We need to discuss them and fix separately, as each of them addressed the different case.
