### ISSUE TITLE
JavadocMethod: "Expected an @return tag." sounds not right

### ISSUE THREAD

**Issue by Bananeweizen** [checkstyle/checkstyle#5463]
I would argue that is not correct grammar, since most people will not speak the "at". I suggest to remove the "an" completely, since it would then match the similar message "Expected @param tag for foo..." and avoids the problem of a/an.

E.g. just replace that message with "Expected @return tag."

Relevant source is https://github.com/checkstyle/checkstyle/blob/5a78c7dcbde3c4d5ba248d5a6161ae412e54640d/src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages.properties#L19

**Comment by varunu28** [comment]
@romani  If this suggested change is approved, I would like to work on this

**Comment by Bananeweizen** [comment]
Just noticed that a similar problem exists at https://github.com/checkstyle/checkstyle/blob/5a78c7dcbde3c4d5ba248d5a6161ae412e54640d/src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages.properties#L32

**Comment by romani** [comment]
@rnveach , please approve issue, as you good in English.

**Comment by rnveach** [comment]
I am approving this.
We should just say `missing XXX tag` or `expected XXX tag`.

**Comment by rnveach** [comment]
@romani see my my comment at https://github.com/checkstyle/checkstyle/pull/5468#pullrequestreview-89600654

**Comment by romani** [comment]
Fit is merged

**Comment by rnveach** [comment]
@romani You never answered my question which I posted a link to in here

**Comment by romani** [comment]
@rnveach , sorry, please read https://github.com/checkstyle/checkstyle/pull/5468#issuecomment-359623062
