### ISSUE TITLE
use new CI - https://buddy.works/

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#5473]
new CI - https://buddy.works/

check it for testing links validations, reuse shippable for stress testing or pitest coverage.

**Comment by romani** [comment]
from Support:
> there's a 1GB memory limit for the Play plan.

I doubt we can do any useful execution on such CI.

`Execute: ./.ci/run-link-check-plugin.sh` - cannot finish. failed on jacoco instrumentation far before linkpluing is running.

**Comment by rnveach** [comment]
>  52M/464M

52M is the used memory and 464M the current allocated memory (heap size) by the JVM at the end of the build.

> > Why the used memory (52M) cannot be considered as the peak ?

> Because the peak may have occurred before the end of the build.

> > Why the heap size (464M) cannot be considered as the peak ?

> Because the peak may be superior to the heap size if the GC reduced the heap size between the peak and the end of the build .
    It may be the case for a very long build that performs intensive tasks at the beginning and lighter tasks then.
    Because the peak may be inferior to the heap size if the GC has increased the heap size until this value but the application never needs to consume as much as memory.

> To get the memory peak during the execution of the maven build, monitor the Java application (maven execution) with any JVM tool designed for : JVisualVM or JConsole for example. 

Source: https://stackoverflow.com/a/45418445/1016482

**Comment by romani** [comment]
useful link ... https://stackoverflow.com/a/774601/1015848

this CI can do only very simple stuff
```
$  /usr/bin/time -v ./.ci/travis/travis.sh versions
...
	Command being timed: "./.ci/travis/travis.sh versions"
	User time (seconds): 10.08
...
	Maximum resident set size (kbytes): 249092
```

**Comment by romani** [comment]
CI is assigned to check "versions"  and "releasenotes" from master.

PR integration is not supported, but  will be available on  11 May 2018, but as limitation on amount of execution present, we will unlikely can use it for PRs.

**Comment by romani** [comment]
all is done for now.

**Comment by romani** [comment]
PR support is ready to use https://buddy.works/blog/introducing-pull-requests
But limitations for 120 builds per month, is still a blocker for us to start yo use at least for simple validations ( which do not need memory above 1Gb).

**Comment by romani** [comment]
we overused buddy quote(120 builds) for month on May17th.
