### ISSUE TITLE
Please add link to contributing.md in README.md

### ISSUE THREAD

**Issue by GammaBurst101** [checkstyle/checkstyle#5488]
It is hard for someone wanting to contribute to know how to. There is no contributing.md file on the main page of the repository. It would be awesome if either is was there or there was a link to it in the README.md file.

Thanks.

**Comment by varunu28** [comment]
@romani @rnveach 
I would like to work on this.

**Comment by rnveach** [comment]
@romani I am fine with a `contributing.md` so users can find it easier.

**Comment by varunu28** [comment]
@rnveach I have created a draft version of contributing.md. Please do let me know what changes would you like to see in that. Once it is finalized I would add the link to README.md

**Comment by romani** [comment]
issue is approved, please do PR

**Comment by GammaBurst101** [comment]
Hey, thanks for the consideration. The PR by @varunu28 shows 'closed' but there is a red cross after his commit which says 'some checks were not successful'. Is the PR not merged?

**Comment by rnveach** [comment]
There was never any PR really.
@varunu28 started a PR and closed it before the issue was approved and hasn't gone anywhere since it's approval.

@varunu28 Do you plan to continue this issue?

**Comment by varunu28** [comment]
@rnveach Yes I am actually working on another PR. I have already created the contributing.md and would raise a PR very soon. Thank you for bringing this to my notice

**Comment by mismatch** [comment]
What's the state of this issue? It looks pretty easy and it's still open. Deleted comments confuse me.

**Comment by varunu28** [comment]
@mismatch Not sure why the comments got deleted. 
@romani Should I be raising a PR again for this one?

**Comment by varunu28** [comment]
@rnveach I am on it

**Comment by rnveach** [comment]
@romani Original reporter wanted a link on main page at https://github.com/checkstyle/checkstyle to contribution file.
Do we still want to do that?

**Comment by romani** [comment]
lets skip it for now.
When smb really want to contribute, we have bunch of places where we explain how to do this.
