### ISSUE TITLE
fix indentation in all sources of xdoc

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#5489]
just an example:
http://checkstyle.sourceforge.net/config_regexp.html#Regexp
![image](https://user-images.githubusercontent.com/812984/35448196-88a7073c-026e-11e8-9466-b2f7e80ed0f7.png)

All sources should be moved to most left and converted to have indentation as 2 spaces to be less wide.

Such tasks is good for new contributors to lets be familiat with development  process on simple code change.

it should looks like:
```
<module name="Regexp">
  <!-- . matches any character, so we need to escape it and use \. to match dots. -->
  <property name="format" value="System\.out\.println"/>
  <property name="illegalPattern" value="true"/>
</module>
```

there should multiple PRs, each file in its own PR to ease review. 

ATTENTION: Indentation should be 2 spaces for all SOURCE blocks (xml, java, ....)

**Comment by varunu28** [comment]
@romani I would like to take up on this. Please assign it to me

**Comment by romani** [comment]
you got it, thanks a lot for you help.

**Comment by varunu28** [comment]
@romani @rnveach I have done the changes for all the modules under xdoc. You can do one final review and suggest the changes required if any so that this issue can be closed. Thanks

**Comment by romani** [comment]
We trust you, thank you very much!
