### ISSUE TITLE
Resolve all problems of linkcheck maven plugin

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#549]
generate html report 
mvn clean package -Pdistro
but it could be generated in more quick way, but additional changes in pom.xml is requierd.

review errors:
~/checkstyle-test/checkstyle/target/site/linkcheck.html

We could suppress errors that we can not resolve.

Problem with links to methods at javadoc should  be resolved too, as such links is used in writing_checks.html , here is problem with using Struts templates ....

**Comment by romani** [comment]
fixed, will be in 6.4

**Comment by mkordas** [comment]
On [main page](http://checkstyle.sourceforge.net/) links to Netbeans don't work. Should be https://netbeans.org/ instead of http://www.netbeans.org. I can fix it, please reopen.

**Comment by romani** [comment]
let make it in term of https://github.com/checkstyle/checkstyle/pull/724#issuecomment-78170298, that issue should stay closed or we could create new issue.

**Comment by mkordas** [comment]
OK, let me create a new issue then.

**Comment by romani** [comment]
useful command for tracing redirects:
```
$ curl -s -L -I -o /dev/null -w '%{url_effective}' https://googlewebtoolkit.blogspot.com/2008/07/getting-to-really-know-gwt-part-1-jsni.html
https://webtoolkit.googleblog.com/2008/07/getting-to-really-know-gwt-part-1-jsni.html
```
