### ISSUE TITLE
CI should fail if PR is based on an old master

### ISSUE THREAD

**Issue by Vladlis** [checkstyle/checkstyle#5496]
from https://github.com/checkstyle/checkstyle/issues/5452#issuecomment-360902468
Parent commit in PR is considered old if there is more then 10 (for example) new commits in master or any config was updated.

**Comment by romani** [comment]
interesting command shared at https://stackoverflow.com/a/27940027/1015848
```
✔ ~/java/github/checkstyle/checkstyle [master ↑·1|✔] 
$ git rev-list --left-right --count master...wercker-clone-ci-temp
1	2
```
![image](https://user-images.githubusercontent.com/812984/40404000-3b88bfc0-5e0a-11e8-9085-0d591efe46b2.png)


but attention should be to fact that clone is done from forked repo, so we need to clone main repo additionally, bind them and then do some scripting.

**Comment by romani** [comment]
@rnveach , do you have some almost ready to use command to count distance between upstream master head and PRs/forked master/branch ?

**Comment by rnveach** [comment]
I use the CLI extremely rarely, so I don't have commands ready to use for something I don't really use. :)

According to https://stackoverflow.com/a/31998123/1016482
It looks like we can use `git rev-list --count A..B`

**Comment by romani** [comment]
Fix is merged
