### ISSUE TITLE
Cannot use @SuppressWarnings("filelength") to suppress this checker

### ISSUE THREAD

**Issue by nlongton** [checkstyle/checkstyle#5503]
Looking at the way the SuppressWarningsHolder works it uses the location of the annotations to determine its scope. eg:
````
    public static boolean isSuppressed(AuditEvent event) {
        final List<Entry> entries = ENTRIES.get();
        final String sourceName = event.getSourceName();
        final String checkAlias = getAlias(sourceName);
        final int line = event.getLine();
        final int column = event.getColumn();
        boolean suppressed = false;
        for (Entry entry : entries) {
            final boolean afterStart = isSuppressedAfterEventStart(line, column, entry);
            final boolean beforeEnd = isSuppressedBeforeEventEnd(line, column, entry);
            final boolean nameMatches =
                ALL_WARNING_MATCHING_ID.equals(entry.getCheckName())
                    || entry.getCheckName().equalsIgnoreCase(checkAlias);
            final boolean idMatches = event.getModuleId() != null
                && event.getModuleId().equals(entry.getCheckName());
            if (afterStart && beforeEnd && (nameMatches || idMatches)) {
                suppressed = true;
                break;
            }
        }
        return suppressed;
    }
````

 The FileLength checker records the line it occurs on as '1'. We cannot put SuppressWarnings("filelength") as the first line in a java module and so afterStart is always FALSE and so the checker never gets suppressed. 

Is there a workaround to this that I am not seeing?

Thanks
Nigel

**Comment by rnveach** [comment]
@nlongton Please read over http://checkstyle.sourceforge.net/report_issue.html#How_to_report_a_bug.3F and fix your first post if you still need help.

> SuppressWarnings("filelength") 

File length is on the entire fix and not a specific section.
You should use suppressions . http://checkstyle.sourceforge.net/config_filters.html#SuppressionFilter

**Comment by nlongton** [comment]
I disabled the default rule and then created a custom clone of the rule that set the error at the max file length line (2000 instead of 1) and so the isSuppressed now returns true if the SuppressWarnings is set on the main class in the package.

**Comment by romani** [comment]
It will work only if in file you have only one class.

As this is not Java syntax aware https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/FileLengthCheck.java placing violation on some Java token is not possible.

If you a satisfied with you custom modification, good for you.

But more reliable solution is usage of filters base on file name http://checkstyle.sourceforge.net/config_filters.html#SuppressionFilter
