### ISSUE TITLE
HeaderCheck: fails with empty lines

### ISSUE THREAD

**Issue by mh000** [checkstyle/checkstyle#5511]
'/var/tmp $ javac Test.java':

`/var/tmp $ cat Test.java`:

```
/*
  -----------------------------------------------------------------------------------

   example

   Copyright (c) 2001-2018 XXX

  -----------------------------------------------------------------------------------
*/

public class Test {

  public Test() {
  }
}
```

`/var/tmp $ cat checkstyle.header`:

```
/*
  -----------------------------------------------------------------------------------

   example

   Copyright (c) 2001-2018 XXX

  -----------------------------------------------------------------------------------
*/
```

`/var/tmp $ cat config.xml`:

```
<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE module PUBLIC
    "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
    "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
  <module name="Header">
    <property name="headerFile" value="checkstyle.header"/>
    <property name="fileExtensions" value="java"/>
  </module>
</module>
```

`/var/tmp $ java -Duser.language=en -Duser.country=US -jar checkstyle-8.8-all.jar -c config.xml Test.java`:

```
Feb 05, 2018 8:00:11 PM com.puppycrawl.tools.checkstyle.Main runCli
FINE: Checkstyle debug logging enabled
Feb 05, 2018 8:00:11 PM com.puppycrawl.tools.checkstyle.Main runCli
FINE: Running Checkstyle with version: 8.8
Starting audit...
[ERROR] /data1/home/martin/x_checkstyle/Test.java:3: Line does not match expected header line of '^$'. [Header]
Audit done.
Checkstyle ends with 1 errors.
```

---------------

I found this issue upgrading from version 6.7 to 8.8.
The Header check does not match the empty lines like expected.
Looking through the CheckStyle source I would guess that the AbstractHeaderCheck method loadHeader is converting empty lines to "^$" what cannot work with the equals in the HeaderCheck isMatch method.

**Comment by rnveach** [comment]
@mh000 Please also provide your `checkstyle.header` file.

**Comment by mh000** [comment]
Sorry, I just followed the template and totally forgot the header file.

```
/*
  -----------------------------------------------------------------------------------

   example

   Copyright (c) 2001-2018 XXX

  -----------------------------------------------------------------------------------
*/
```

**Comment by rnveach** [comment]
>  I would guess that the AbstractHeaderCheck method loadHeader is converting empty lines to "^$" what cannot work with the equals in the HeaderCheck isMatch method.

I agree. 

The code in question is at:
https://github.com/checkstyle/checkstyle/blob/90f20e09869c71eb22190ad9c1d46d5deec324a5/src/main/java/com/puppycrawl/tools/checkstyle/checks/header/AbstractHeaderCheck.java#L179-L180

The reason why it uses `^$` is because `RegexpHeader` also uses the same code but supports regular expressions. This was an oversight when adding this code and it should be directly moved to `RegexpHeader.postProcessHeaderLines` where we convert the line to a regular expression.

**Comment by tshradheya** [comment]
@rnveach I would like to take up this issue.

Just to confirm, resolving this bug involves, moving the 
```
if (line.isEmpty()) { 
     line = "^$"; 
}
``` 
into 

https://github.com/checkstyle/checkstyle/blob/f060acde17d42b803babec5c00b1033d3b80c86a/src/main/java/com/puppycrawl/tools/checkstyle/checks/header/RegexpHeaderCheck.java#L151-L158

at line156?

**Comment by rnveach** [comment]
@tshradheya Yes, that is how I see it should be fixed.

**Comment by tshradheya** [comment]
No longer working on this.

**Comment by romani** [comment]
fix is merged.
