### ISSUE TITLE
Create xdoc page to explain the new Xpath-based suppression model

### ISSUE THREAD

**Issue by MEZk** [checkstyle/checkstyle#5513]
1. Create a new sub-section in the documentation section of xdoc. The name of the sub-section should be "Suppressions".
2. Create a new page in "Suppressions" section. The name of the page should be "XPath".
3. The "Xpath" page should contain the following sections: "What is XPath", "XPath tree to AST mapping (with examples and pictures)", "How to generate XPath for Checkstyle violations".
4. [SuppressionXpathFilter](http://checkstyle.sourceforge.net/config_filters.html#SuppressionXpathFilter) section should contain a link to the "XPath" page.
5. [Command line](http://checkstyle.sourceforge.net/cmdline.html) section should also contain a link to "XPath" page.

We can use these examples to write the documentation:
- http://pmd.sourceforge.net/pmd-4.3/xpathruletutorial.html
- http://techtraits.com/programming/2011/11/06/custom-pmd-rules-using-xpath.html

The main idea of "Suppressions" section is to collect all information on suppression models in future (annotation-based, old suppression model, etc) to make it easy for the user to find the required information. "Filters" section should contain the information about filters as Checkstyle modules. We need to reduce the amount of information in the section. "Suppressions" section is a kind of tutorials collection.

@rnveach @romani 
If you agree with the proposal, please approve the issue or extend my idea.

**Comment by rnveach** [comment]
@MEZk 
> Create a new page in "Suppressions" section. The name of the page should be "XPath".
> SuppressionXpathFilter section should contain a link to the "XPath" page.
> We need to reduce the amount of information in the section.

Why? Why can't documentation be in `SuppressionXpathFilter`? Why does it have to be in a new page?
If we are going to name this just `Suppressions` are we going to put documentation of regular suppressions in there? It will be misleading if it only contains XPath and nothing else.

**Comment by MEZk** [comment]
@rnveach 
> Why? Why can't documentation be in SuppressionXpathFilter? Why does it have to be in a new page?

Now the information about the whole xpath suppresion model and examples are scattered throughout the documentation. It may be difficult to see the whole picture and migrate from the old model to the new one. 

 > If we are going to name this just Suppressions are we going to put documentation of regular suppressions in there? It will be misleading if it only contains XPath and nothing else.

I believe that we should move the documentation on each suppression model to the new section: old suppression model, annotation-based, etc. Nobody want's to know about filters, checkstyle module structure. User just want to know how to suppress the violation easily. They do not want to know about filters, their meaning and configuration, they want to copy-paste working examples and go on.

**Comment by rnveach** [comment]
> User just wants to know how to suppress the violation easily

How is the current documentation not doing this? If it is so bad, why don't we fix that documentation instead of creating brand new one?

> Nobody want's to know about filters

They have to know to be able to setup the suppression model they want.

**Comment by MEZk** [comment]
@rnveach 
> They have to know to be able to setup the suppression model they want.

I saw many exaples in other Open SOurce projects and at work. Users copy paste examples, they do not read much about filter and internal Checkstyle architecture. Filters section is good If they want to setup a very flexible suppression model: annotations + comments + suppression file, etc. However, the main suppression model will become Xpath (I belive so :D). Therefore If we put the whole documentation on the model with examples to the filters page It will become heavily overloaded. In addition, I think that it will be good to have [this exaples](https://timurt.github.io/5509/) somewhere in documentation. Maybe even for all supported checks, as It always be pain for me to write xpath-expressions for PMD based on their documentation.

**Comment by romani** [comment]
@timurt , can you help us to finish this issue ?

Xpath suppression should become public finally, even in very limited scope for supported Checks.

**Comment by timurt** [comment]
@romani 
I sent PR, see if queries are complicated enough, I can add more if it is necessary

**Comment by rnveach** [comment]
I assume this issue is done?

**Comment by MEZk** [comment]
@rnveach 
Yes

**Comment by romani** [comment]
@timurt , thanks a lot for your desire to finish project. 
Smth that you do will be used by all users of Checkstyle.
Looking forward for completion of other tasks.
