### ISSUE TITLE
[Help Wanted] Command argument that enbale to specify the suppression file

### ISSUE THREAD

**Issue by jdneo** [checkstyle/checkstyle#5515]
Hi team,

I have a question about running checkstyle through command line.

Is there any command argument that enbale to specify the suppression file(like this one: https://maven.apache.org/plugins/maven-checkstyle-plugin/examples/suppressions-filter.html)?

Thanks

**Comment by rnveach** [comment]
@jdneo you must specify the suppression file in the configuration and pass that through the command line arguments.

See the following:
http://checkstyle.sourceforge.net/cmdline.html#Command_line_usage
http://checkstyle.sourceforge.net/config_filters.html#SuppressionFilter

**Comment by jdneo** [comment]
I see, thanks for the help @rnveach

**Comment by romani** [comment]
maven team "implemented"  their own Filter, it does not have name or class, just embedded.
https://github.com/apache/maven-plugins/blob/trunk/maven-checkstyle-plugin/src/main/java/org/apache/maven/plugins/checkstyle/exec/DefaultCheckstyleExecutor.java#L785

They reuse our internals to load suppression file that belong to SuppressionFilter. But they do not have all other options that SuppressionFilter has.  Their filter does not have same options as our SuppressionFilter, so their are different by all means. 

Beware that maven's filter is Checker filter, you can suppress only general violations, xpath will not work here. There might be nuance with having Filter in config and maven pom file.

We will never update our CLI to reuse some parts of standard filters, all should be done through configuration file.
