### ISSUE TITLE
No documentation

### ISSUE THREAD

**Issue by baldurgaldur** [checkstyle/checkstyle#5524]
The documenation hosted here http://checkstyle.sourceforge.net/
is unavailable.

**Comment by romani** [comment]
Html is "Project web is currently offline pending the final migration of its data to our new datacenter."

Looks like some work is going on sourceforge side

**Comment by millerthegorilla** [comment]
they've just removed the subdomains, and are referring to projects as subdirectories.  Visit sourceforge.net and search checkstyle.
The links link to the old site though, and the whole thing has an 'air' of naive startup.  Smells like the anti-foss to me, but it might be back at some point.
In the meantime, if anyone knows the xml override (which I imagine is how checkstyle works), for line length then that would be a start, but I could really do with the docs and a cheat sheet.

**Comment by rnveach** [comment]
As of right now, without website, documentation can only be found at https://github.com/checkstyle/checkstyle/tree/master/src/xdocs in source form.

**Comment by rnveach** [comment]
I am closing this as the sourceforge documentation site seems to be working for now.
