### ISSUE TITLE
How to check align fields in columns?

### ISSUE THREAD

**Issue by litttlefisher** [checkstyle/checkstyle#5544]
![image](https://user-images.githubusercontent.com/19563352/36648892-c5f168c6-1ad3-11e8-8142-c2ac8a5abaa6.png)

I don't know whether Checkstyle can check the align fields in columns.
If Checkstyle can check it, I want to know how to do it.

thx

**Comment by rnveach** [comment]
There is no module in checkstyle that does this currently.

**Comment by litttlefisher** [comment]
Is there any plan to add a new module to check it?
If has plan, when will it be finished?

**Comment by rnveach** [comment]
No plans.

**Comment by litttlefisher** [comment]
Ok, I know.
Thx
