### ISSUE TITLE
Explicitly throw an exception from ClassResolver

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#5546]
This is a spin-off for #5516 

The method `ClassResolver::resolve` ends with
```
if (clazz == null) {
  // Giving up, the type is unknown, so load the class to generate
  // exception
  clazz = safeLoad(name);
}
```

The problem with this code is that Jacoco can not detect the methods that always throw an exception.
As a result, the method is considered not 100% covered. 

By replacing this hack with an explicit exception throwing, it will not only solve the problem with Jacoco, but also make the code more readable.

**Comment by rnveach** [comment]
Fix was merged
