### ISSUE TITLE
create project to test changes of Checkstyle by snapshot report compare 

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#555]
changes to Checkstyle sometimes cause a lot of regression problems.

We need to have project (shell/bash is OK) to download sertain list of project by exact stable version, run latest checkstyle for particular Check or some configuration to generate plain text reports and compare them with reports of previous launch.
After manual compare and approval of changes , admin push new reports to remote for future launches.

**Comment by damianszczepanik** [comment]
Looks like what I've done when providing changes in Checkstyle: download apache io library as a source and run my changes against that code to see whether changes works fine or not.

I believe we can download sources over maven dependencies goal and run whole via maven. If you provide Checkstyle results as xml file than running simple diff should eliminate human/manual check.

The only question I have is why you want to use stable version? I believe stable version means less violations and less violations means less chances to detect regression. Why not using the old Java code from the time when the best tool for Java quality code was code formatter? What about JDK1.3 or Apache Ant projects that are quite old?

**Comment by romani** [comment]
> The only question I have is why you want to use stable version?

By stable verion I ment, any tagged version. So any checkstyle test launch should be on the same sourcesof target project and always compilable :) . That should be configurable to lets find the most problematic project to be perfect source of tests. But we need diversity of project with different styles, technologies, to grab whole veriety of java syntax and its usage.

**Comment by damianszczepanik** [comment]
Sounds good to me. Further questions:
1. How do you want to manage results? I expect simple diff should show differences (or hopefully not) which you can verify. But what when number of projects will increase from one run to another?
2. Are you going to run checkstyle with the same configuration against each project or rather keeping Pair<ProjectName, checkstyle.config> ?
3. Results will be stored in repo or each time you want to check regression you will run with newer and then older checkstyle release?

Based on provided information it looks to me like this should be executed by bash script that will download sources, run checkstyle and compare results. Let me know your vision about configuration.

**Comment by romani** [comment]
> How do you want to manage results?

simple diff on text files.

> But what when number of projects will increase from one run to another?

when we will have test failure as no file compared newly generated file, it is expected,  but for each project we generate separate plain text file.

> Are you going to run checkstyle with the same configuration against each project or rather keeping Pair ?

yes it should be a pair.

> 3. Results will be stored in repo or each time you want to check regression you will run with newer and then older checkstyle release?

I do believe that we need to store etalon(last approved/confirmed) version of reports in  repo.

>Based on provided information it looks to me like this should be executed by bash script that will download sources, run checkstyle and compare results. Let me know your vision about configuration

yes,but any scripting languages(groovy) are ok too, as logic and requirements could grow.

===============

Please do not implement anything for now, I need to think a bit more on that project and how to enforce it, I will finish in few weeks. 
I will put a comment as I finally approve that feature implementation.

**Comment by damianszczepanik** [comment]
Groovy seems to be perfect tool for this, especially if you want to let contributors maintain this tool. I don't feel good enough in Groovy so someone else can do this better.

**Comment by romani** [comment]
closed in favour of https://github.com/checkstyle/contribution/issues/51
