### ISSUE TITLE
PackageNamesLoaderTest refactoring

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#5551]
This is a Jacoco related issue. See #5516

Currently, the `PackageNamesLoaderTest` does not have a case for successful `PackageNamesLoader.getPackageNames` invocation.

It has cases for failing `PackageNamesLoader.getPackageNames` invocation and for successful `PackageNamesLoader.processFile` invocation.

Also, the method `PackageNamesLoader.processFile` is a private one, so it is better to test it within a call to `PackageNamesLoader.getPackageNames` method, regardless of the Jacoco limitations.

**Comment by rnveach** [comment]
Fix was merged
