### ISSUE TITLE
Refactoring of JavadocUtils static init

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#5555]
This is a Jacoco related issue. See #5516

The Jacoco branch coverage report for `JavadocUtils.static init` is 99% due to 
```
if (Modifier.isPublic(field.getModifiers())
    && field.getType() == Integer.TYPE) {
```

Since all members of the `JavadocTokenTypes` class are `public int` this `if` is missing a half of its branches for the Jacoco.
This issue does not affect the Cobertura coverage, as it adds a pair of fields to the each class during the instrumentation phase.

A possible workaround is to extract this code to an utility method. This is a good idea, since both `TotkenTypesUtils` and `JavadocUtils` shares the same code for their static initializers.

**Comment by rnveach** [comment]
Fix was merged
