### ISSUE TITLE
Switch to powermock-api-mockito2

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#5558]
To support JDK9, we need to upgrade PowerMock to version 2.0.
Unfortunately, the support for Mockito 1.x has been removed from PowerMock 2.0.
See https://github.com/powermock/powermock/issues/726

This means that we must switch to Mockito 2.0 API.

**Comment by pbludov** [comment]
A guide to the migration:
https://asolntsev.github.io/en/2016/10/11/mockito-2.1/

**Comment by rnveach** [comment]
Fix was merged
