### ISSUE TITLE
IllegalStateException message text was changed in JDK9

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#5561]
The test `TokenUtilsTest.testGetIntFromInaccessibleField` is failing on JDK9 due to the text of the message was changed from

java.lang.IllegalAccessException: `Class` com.puppycrawl.tools.checkstyle.utils.TokenUtils `can not` access a member of class java.lang.Integer with modifiers "private final"

to

java.lang.IllegalAccessException: `class` com.puppycrawl.tools.checkstyle.utils.TokenUtils `cannot` access a member of class java.lang.Integer `(in module java.base)` with modifiers "private final"

There is at least four ways to fix it:

1. Turn `String.startsWith` to a couple of `String.contains`
2. Use a regular expression
3. Match two different strings depends of the JDK version
4. Drop the validation of the message text

**Comment by romani** [comment]
Use 1 or 2nd way to resolve issue, whatever is easier

**Comment by romani** [comment]
fix is merged
