### ISSUE TITLE
checkstyle.sourceforge.net down

### ISSUE THREAD

**Issue by vorburger** [checkstyle/checkstyle#5574]
http://checkstyle.sourceforge.net is down, and it's not temporary, it's been like this for about 2 weeks or so already... shame, for this great project! Google will typically start to automatically remove hits from search results for dead sites.. perhaps this should and could be sorted out. Or maybe it's time to buy a domain for CS after all these years... :-) 

Can I help in any way with anything related to this?

**Comment by criley-pnet** [comment]
I'm seeing this as well.  Is there a mirror or way to view the documentation offline?

**Comment by rnveach** [comment]
It has not been down for 2 weeks.
 See https://github.com/checkstyle/checkstyle/issues/5524 
It came back but only went down recently when we tried to do release.

> time to buy a domain for CS

This most likely isn't an option as CS can't afford a domain.

> perhaps this should and could be sorted out

If you have any ideas, feel free to say.

>  Is there a mirror or way to view the documentation offline?

As of right now, without a website, documentation can only be found at https://github.com/checkstyle/checkstyle/tree/master/src/xdocs in source form.
HTML files can be generated locally by running `mvn site` which will be generated under `target` folder.

**Comment by misery** [comment]
Would be great if releases could be uploaded to https://github.com/checkstyle/checkstyle/releases as https://sourceforge.net/projects/checkstyle/files/checkstyle/8.8/ is not available sometimes.

**Comment by pbludov** [comment]
Note that CS already has a domain: http://www.puppycrawl.com/checkstyle/

**Comment by ntsim** [comment]
Just a suggestion, but why not move this project over to GitHub completely? You could host the site using GitHub Pages. 

At a stretch, it seems like it would be a good opportunity to revamp the site as well, as it is a bit dated.

**Comment by rnveach** [comment]
> Note that CS already has a domain: http://www.puppycrawl.com/checkstyle/

This is personal domain of our author. We don't have access to it.

> why not move this project over to GitHub completely? 

I brought this up to @romani .

**Comment by romani** [comment]
@vorburger ,

> is down, and it's not temporary

looks this down time was the most severe. But it is back, eventually.
But unfortunately ssh is still not working, to let me do release
```
ssh -t $SF_USER,checkstyle@shell.sourceforge.net create
Password: 
PTY allocation request failed on channel 0
```

> Or maybe it's time to buy a domain for CS after all these years

actually we have checkstyle.org , but we never make it used, as checkstyle is not profitable at all. And my strict position is to not use any personal resources on this to not depend on single person. Now whole project is completely free and use only free resources of web.
To make hosting changes, we need more human resources from outside of our tiny team, please be welcome to contribute.  For now I have too much PRs and Issues that awaits my suggestions on way to resolve ..... changing hosting is far below priority in my list for now.

> Can I help in any way with anything related to this?

We can start to think about transition to another hosting, but main point is that release process should stay automated the more the better. There are a lot of nuances, but probably we can resolve them.

**Comment by romani** [comment]
@misery ,

> Would be great if releases could be uploaded

yes, It might be good to have it, several years ago github discontinued their binaries hosting, but looks like  they restored them. So we can do this as backup place. 
What you are using from https://sourceforge.net/projects/checkstyle/files/checkstyle/8.8/ ? that is not present on https://sourceforge.net/projects/checkstyle/files/checkstyle/8.8/

Can you help us automate deploy to github ?

**Comment by romani** [comment]
@ntsim ,

> Just a suggestion, but why not move this project over to GitHub completely? 

for some old experience (few years ago), I had problems with reliable http access to XSD files that were hosted on github. It might be already resolved. The only blocker for us to move to new hosting is no human resources to make it happen and test (to avoid same long downtime). We still do RSS post on Sourceforge and store some binaries that are not allowed to be hosted on maven central (could be moved to bintray  or github).

> It seems like it would also be a good opportunity to revamp the site as well, as it is a bit dated.

it is generated from xdoc files, and completely generated by maven site pluigin, so it is the same as most other maven plugin sites. If you know how to improve please propose and contribute.

**Comment by ntsim** [comment]
@romani, if you're not adverse to trying something new, then I would propose using a more modern static site generator like Jekyll (which integrates well with GitHub Pages). The upshot of doing it this way would be that the site content could just be (mostly) written with Markdown instead of xdoc.

I would be interested in helping out with such an effort, especially if we can come up with something more attractive to look at! :smile:

**Comment by romani** [comment]
> if you're not adverse to trying something new, then I would propose using a more modern static site generator like Jekyll (which integrates well with GitHub Pages).

I am ok and you are welcome to contribute, it will be long project, I hope you understand a scope of changes.
But web site generation should stay automatic, and do not create any further problems for maintainers during release. There are also UTs that verify xdoc against code .... so such validation should stay.

**Comment by vorburger** [comment]
> This might not be an option as CS can't afford a domain.

domain names cost nothing, like $10/year or whatever; I would be willing to make a small gesture of appreciation to CS to sponsor that for like 10 years or something - no problem at all.  Domain hosting is different, but as other have said, we should be able to use just GitHub Pages for hosting static content.

> several years ago github discontinued their binaries hosting, but looks like they restored them. 

are you sure? I didn't see that. Do you have a link to GitHub Help re. this?

> actually we have checkstyle.org, but 

cool. Shall we try to see if we can do something in that direction? But in new issue #5601.

From my PoV as the original reporter of this issue, this is now resolved - checkstyle.sourceforge.net is up.

**Comment by romani** [comment]
> are you sure? I didn't see that. Do you have a link to GitHub Help re. 

https://blog.bintray.com/2013/05/30/google-and-github-insist-go-store-your-binaries-in-a-proper-place/
but a lot of time passed, looks like not an issue anymore.

> domain names cost nothing,

yes, my personal position was to minimize dependencies to any personal resources (servers, money, ...) ... there was a lot of suggestions, and I never regret about my policy. Domain was an exclusion, so one of our maintainers just did it. 

......
all discussion is moved to  #5601.
