### ISSUE TITLE
Remove usage of javax.xml.bind.XmlElement (deprecated in JDK9)

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#5582]
The test input class `LocalCache` is still using the `javax.xml.bind` package.
http://checkstyle.sourceforge.net/xref-test/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationFromGuava.html#L8

This problem is similar to #5027, except that it does not breaks the build. This breaks the forbiddenapi verification on JDK9.

**Comment by rnveach** [comment]
Fix was merged
