### ISSUE TITLE
Use Jacoco instead of Cobertura for coverage check

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#5586]
The Cobertura coverage is the last stopper on the way to the build the Checkstyle with JDK9.

Now it is ready to be replaced with the Jacoco coverage.

**Comment by romani** [comment]
As soon we resolve non 100 values in main code we can do this.
Now I still see
https://github.com/checkstyle/checkstyle/blob/67e9ab026ee3012573e8c2b0c5d6c1982f1d19d3/pom.xml#L1772

Classes:
```
<include>com.puppycrawl.tools.checkstyle.utils.JavadocUtils</include>
 <include>com.puppycrawl.tools.checkstyle.PackageNamesLoader</include>
<include>com.puppycrawl.tools.checkstyle.Main</include>
```

**Comment by pbludov** [comment]
@romani Please review #5551 #5553 #5555

**Comment by romani** [comment]
Fix is merged

**Comment by rnveach** [comment]
@romani It was said in the PR that this would be a multi-part PR.
https://github.com/checkstyle/checkstyle/pull/5587#issuecomment-371156171 and https://github.com/checkstyle/checkstyle/pull/5587#issuecomment-371393599

According to https://github.com/checkstyle/checkstyle/search?utf8=%E2%9C%93&q=cobertura&type= , there are still some places with `cobertura` in the source including our restrictions on the stream classes in the import control.

**Comment by pbludov** [comment]
The next stopper is the `findbugs` check. Actually, this project is abandoned and replaced with `spotbugs` check.
CS uses both of them. If all of the `findbugs` verifications are supported by the `sporbugs`, why we need both of them?

**Comment by rnveach** [comment]
> why we need both of them?

The most likely reason is because they both exist. We try to apply any and all style checkers.

**Comment by romani** [comment]
> CS uses both of them. If all of the findbugs verifications are supported by the sporbugs, why we need both of them?

we can drop findbugs plugin, spotbugs become mature enough to completely replace it. Please keep such discussions in jdk9 issue. This issue is closed.

**Comment by romani** [comment]
> It was said in the PR that this would be a multi-part PR.

main and most complicated part is done, all other could be removed in separate issue #5616
