### ISSUE TITLE
Split pitest-checkstyle-common

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#5592]
caused by #5554

The profile `pitest-checkstyle-common` is too large and should be split.
At one point there are four minions, two of them tries to eat more than 4GB of memory.

The server running this test has only 4 GB of memory, so this step falls deep into the swap and hangs.

Note from romani:
I relaunched master build
https://app.shippable.com/github/checkstyle/checkstyle/runs/6387/summary/console to reproduce problem in case some changes were done on CI side. Build is passed.

**Comment by rnveach** [comment]
> two of them tries to eat more than 4GB of memory.

Is it possible to determine memory usage after a run?

**Comment by romani** [comment]
> Is it possible to determine memory usage after a run in CI?

maven is printing used memory if build successful.
https://app.shippable.com/github/checkstyle/checkstyle/runs/6387/19/console took 13 minutes(other build does not go above 7 minutes), 
memory usage from CI logs - `[INFO] Final Memory: 44M/490M` . So smth is weird happening when #5554 is in play. 
We unlikely find a reason of failure , we will just make a workaround, but it is still ok.

**Comment by romani** [comment]
fix is merged.
