### ISSUE TITLE
100% coverage for com.puppycrawl.tools.checkstyle.PackageObjectFactory

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#5595]
Currently, the test PackageObjectFactoryTest covers only 99% of PackageObjectFactory.
The rest is a 'gift' from other tests. Missing methods should be implemented in PackageObjectFactoryTest.

**Comment by romani** [comment]
first fix is merged, was it final ?

**Comment by pbludov** [comment]
Yes. e173e92a6f4ff890a230b173c884173a2df4bbc3 was final. There is no other changes to the test `PackageObjectFactory`.
