### ISSUE TITLE
NPathComplexity ignores multi-part boolean expressions 

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#56]
Created: 2008-11-19
Creator: Christian Oetterli
SF issue: 534 

The rationale of NPath says that it takes into account also multi-part boolean expressions (http://checkstyle.sourceforge.net/config_metrics.html#NPathComplexity
). This is not the case.
At least PMD reports another NPath value for the method "aMethod2()" below.

```
public class NPathTest {
// Both = 4
void aMethod1() {
if (true) {
}
if (true) {
}
}
```

```
// Checkstyle = 4
// PMD = 6
void aMethod2() {
if (true || true) { // multi-part bool
}
if (true) {
}
}
}
```

For me PMD is right as we have 6 possible ways.

We have article for NPathComplexity algorithm.
##

**Comment by attatrol** [comment]
I am on it.

**Comment by attatrol** [comment]
This is a method from checkstyle/Main.java
<pre><code>
    private static int runCheckstyle(CliOptions cliOptions)
            throws CheckstyleException, UnsupportedEncodingException, FileNotFoundException {
        // setup the properties
        final Properties props =
                cliOptions.propertiesLocation != null
                        ? loadProperties(new File(cliOptions.propertiesLocation))
                        : System.getProperties();

        // create a configuration
        final Configuration config = ConfigurationLoader.loadConfiguration(
                cliOptions.configLocation, new PropertiesExpander(props));

        // create a listener for output
        final AuditListener listener = createListener(cliOptions.format, cliOptions.outputLocation);

        // create Checker object and run it
        int errorCounter = 0;
        final Checker checker = new Checker();

        try {

            final ClassLoader moduleClassLoader = Checker.class.getClassLoader();
            checker.setModuleClassLoader(moduleClassLoader);
            checker.configure(config);
            checker.addListener(listener);

            // run Checker
            errorCounter = checker.process(cliOptions.files);

        }
        finally {
            checker.destroy();
        }

        return errorCounter;
    }
</code></pre>


pmd 5.3.2 wrongly says that its NPath complexity is 10.

This method can be reduced to its NPath equivalent:
<pre><code>
    simpleOne() {
            bool a = true != true ? true : true;
            try {
            }
            finally {
            }
    } 
</code></pre>

1. The article Nejmeh, Communications of the ACM Feb 1988 pp 188-200. says that:
<blockquote>
The acyclic execution path complexity for the ?
operator is
NP(?)=NP((exprl))+NP((expr2))+NP((expr3))+2.
</blockquote>
where
<blockquote>
The acyclic execution path complexity for any
logical expression is
NP(expression)
= number of && and I I operators in the expression.
</blockquote>
so it is clear that NPath complexity of ? operator in the metod has value of 2.

2. There is no description of try-catch-finally sequence in the original paper, but its NPath complexity should have value of 5 according to pmd calculations, the fact i cannot agree. 
I think that try-finally construction in the method is linear and thus has complexity value of 1 (2, at most), so full complexity of the method cannot be higher than 4.

**Comment by attatrol** [comment]
@romani 
Can you clear the rules of NPath calculation of try-catch-finally construction?
Personally to me it resembles switch operator with catch blocks as cases.

**Comment by romani** [comment]
Sorry for delay, i am on vacation, will answer you on beginning of September

**Comment by romani** [comment]
@attatrol ,

1)
> pmd 5.3.2 wrongly says that its NPath complexity is 10.

first of all lets not mix all problems in one issue. In scope of this issue please resolve problem that is reported in description "multi-part bool". Please move all posts of try-catch-finally to another issue.

2) 
> There is no description of try-catch-finally sequence in the original paper,

yes, because paper is almost 30 years old , there was not structure like try-catch-finally at that time.

3)
> Can you clear the rules of NPath calculation of try-catch-finally construction?

I do not know for sure, I only can presume that we could convert try-catch-finally to simple form. Example:
```
try {
 // statements1
}
catch ( Exception1 ex1) {
 // statements2
}
catch (Exception2 ex2) {
 // statements3
}
finally {
 // statements4
}
```

to 

```
// statements1
if (ex1) {
// statements2
}
else { 
   if (ex2) {
      // statements3
   }
}
// statements4 
```

So formula should be: 
 NP(T-C-F) = NP(try-range) + NP(catches) + NP(finally)
NP(catches) = S(1:N)NP(catch-range) + S(1:N)NP(catch-expr) + 1

> here is an intresting question if multicatch

Example:
```
try {
 // statements1
}
catch ( Exception1 | Exception2 ex1) {
 // statements2
}
finally {
 // statements3
}
```

to 

```
// statements1
if (ex1 || ex2) {
// statements2
}
// statements4 
```

So formula should be: 
NP(T-C-F) = NP(try-range) + NP(catches) + NP(finally)
NP(catches) =NP((if-range))+NP((expr))+1  --- attention: it is just the same as simple NP(if)

**Comment by romani** [comment]
@attatrol , do you have time to finish this issue ?

**Comment by attatrol** [comment]
i'm going to start on weekend.

**Comment by romani** [comment]
@attatrol , just let me know if you need any help/explanations from me , I am OK to arrange voice call to speed up process.

**Comment by attatrol** [comment]
@romani, i have no difficulties, i'll do this issue in 2 parts, at first i'll reach identity with pmd report (this can be easily verified), and after that i would start to implement try-catch-finally handling. The main difficulty is the lack of time, i picked too many courses for this term and have to represent my university at mathematical competitions.

**Comment by romani** [comment]
ok, take your time.

**Comment by romani** [comment]
@attatrol , do not hesitate to ask me assistance for this issue.

**Comment by romani** [comment]
fix is merged.
Thanks a lot @kazachka for such huge contribution !
