### ISSUE TITLE
JavadocType: Add "allowedAnnotations"

### ISSUE THREAD

**Issue by rupert654** [checkstyle/checkstyle#5608]
There are a few classes that are quite standard and declarative in nature, for which it would be useful to allow Javadoc to be skipped.

For Spring Boot, this would include `@SpringBootApplication`, `@ConfigurationProperties`, and `@Configuration`.

It would be helpful if the JavadocType check allowed us to specify a list of annotations to allow this check to be skipped so we could configure this appropriately, similarly to the JavadocMethod check.

**Comment by romani** [comment]
JavadocType implemented by parsing as regexp, such implementation is deprecated as need to be reimplemented to use Antlr parser that we have. Unlikely that smb from checkstyle team will catch this issue.
But we will merge contribution from outside of the team.

**Comment by ngeor** [comment]
Another use case is the `@Nested` annotation for JUnit 5 nested unit tests.

**Comment by ngeor** [comment]
I followed the implementation of JavadocMethod and created a PR. I run "mvn clean verify" as per the contributing guidelines locally and it passes.

https://github.com/checkstyle/checkstyle/pull/6088

I could use some help understanding why my PR is failing on certain cirecle-ci checks while it is passing on jenkins.

**Comment by romani** [comment]
fix is merged, thanks a lot @ngeor for fix!!
