### ISSUE TITLE
Remove usage of com.sun.* packages from tests

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#5611]
All `com.sun` packages are visible from JDK9 only in the compatibility mode.
In the java 9 mode, using them will raise an error message like
```
[ERROR] src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/illegalimport/InputIllegalImportDefault.java:[15,11] package sun.applet is not visible
[ERROR]   (package sun.applet is declared in module java.desktop, which does not export it)
```
For now, these packages are used only in the import order tests.
Moving them to the `resources-noncompilable` folder folder will remove the warning message.

**Comment by rnveach** [comment]
> Moving them to the resources-noncompilable folder folder will remove the warning message.

We should try to find a replacement and leave moving them to noncompilable as a last resort.
We had issues with bad Java code in our inputs before we enforced that they be compilable. We shouldn't go backwards.

**Comment by rnveach** [comment]
> Remove usage of com.sun.* 
> package sun.applet is not visible

Is it just `com.sun.` or is it `sun.` or both?

**Comment by pbludov** [comment]
Both of them.

**Comment by romani** [comment]
we already have Inputs for this Check in non-compilable, let just move problematic Imports to this folder.

**Comment by pbludov** [comment]
This problem is delayed for some time. At least until JDK10. By that time, anything can happen.
