### ISSUE TITLE
Replace java.awt.event.InputEvent#getModifiers() with getModifiersEx()

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#5613]
From the [docs](https://docs.oracle.com/javase/8/docs/api/java/awt/event/MouseEvent.html#MouseEvent-java.awt.Component-int-long-int-int-int-int-boolean-):

> **modifiers** - a modifier mask describing the modifier keys and mouse buttons (for example, `shift`, `ctrl`, `alt`, and `meta`) that are down during the event. _Only extended modifiers are allowed to be used_ as a value for this parameter (see the `InputEvent.getModifiersEx()` class for the description of extended modifiers).

The method `TreeTable.isCellEditable(EventObject event)` should be upgraded.

**Comment by romani** [comment]
Please define a reason of upgrade.

**Comment by pbludov** [comment]
`java.awt.event.InputEvent#getModifiers()` is deprecated in JDK9.
The forbiddenapi complains about it (in --source 9 mode).

There is no reason to hurry, but sooner or later it needs to be done.

**Comment by romani** [comment]
Ok , just needed to know actual reason/trigger of update.
