### ISSUE TITLE
JavadocMethodCheck#isMissingJavadocAllowed  javadoc mean method could be overriden but it is private

### ISSUE THREAD

**Issue by kzaikin** [checkstyle/checkstyle#5615]
UPDATE: original request was rejected .... but javadoc is changed to not be misleading

JavadocMethodCheck#isMissingJavadocAllowed(final DetailAST ast) is private while its comment says in clear words that it is intended to be used for behavior override:

    /**
     * The JavadocMethodCheck is about to report a missing Javadoc.
     * This hook can be used by derived classes to allow a missing javadoc
     * in some situations.  The default implementation checks

The method have used to be protected until mass-update from Issue #4801

Issue #4801: fix for violations from WeakerAccess inspection
https://github.com/checkstyle/checkstyle/commit/d243badf77c9c70a4e4ecde28a34ca8802de41b6

Looks like making it private was wrong. It has to have a protected access level

**Comment by romani** [comment]
we need to change javadoc, method should stay private. 
JavadocMethodCheck implementation is deprecated and we will not support it in good way, we will change it at any time we come to it. It is better to NOT extend from this class, to avoid problems in future.

We try to hide all methods to private to not let anybody think that such classes are designed for extension.

**Comment by kzaikin** [comment]
And what if one needs to fine tune scope for JavadocMethodCheck?

**Comment by romani** [comment]
unfortunately ... you need to make fork/copy of whole Check and do what ever you want.
We will not support extensions from our Checks.
If your reason is general, we could consider other ways of tuning behavior by user .... through configuration as we always do.

**Comment by romani** [comment]
fix for javadoc was merged.
