### ISSUE TITLE
Remove remnants of cobertura usage

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#5616]
taken from https://github.com/checkstyle/checkstyle/issues/5586#issuecomment-373669840

According to https://github.com/checkstyle/checkstyle/search?utf8=%E2%9C%93&q=cobertura&type= , there are still some places with cobertura in the source including our restrictions on the stream classes in the import control and the sevntu config file.
Since we dropped cobertura, we should try to remove everything we needed because of it.

**Comment by romani** [comment]
@pbludov , can you help us to completely remove cobertura from our project ? and allow all classes that were banned due to conflict with cobertura.

**Comment by pbludov** [comment]
I'm on it.

**Comment by romani** [comment]
fix is merged.
for Activation of IDEA and Eclipse validation please create separate issue.
