### ISSUE TITLE
Linux builds at AppVeyor

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#5618]
we should reuse Linux/Docker abilities 

>Evolved from our Windows offering, AppVeyor for Linux has some unique features:
    Connect multiple version control systems: GitHub, Bitbucket, GitLab, VSTS, Kiln and any other Git, Mercurial or Subversion repository.
    Configure CI for your projects via UI or in dot-file.
    Full sudo access to VM running build.
    Promoted deployments - build once and deploy the same packages to multiple environments.
    Official out-of-the-box .NET Core support - automatic build, test and packaging of .NET Core projects. Proof: build, config, website - dedicated blog post is coming!
    SQL Server 2017 for Linux.
    Bash and PowerShell Core for controlling build flow.
    Single configuration file for both Windows and Linux builds.
    Docker support.
    Built-in NuGet server.

https://www.appveyor.com/docs/getting-started-with-appveyor-for-linux/

**Comment by daniilyar** [comment]
@romani do you mean we need to setup Win and Linux builds side-by-side? https://www.appveyor.com/docs/getting-started-with-appveyor-for-linux/#running-windows-and-linux-builds-side-by-side

**Comment by romani** [comment]
we need rrun some regression testing commands on appveyor.
Imagine that we need to run https://github.com/checkstyle/checkstyle/blob/master/.travis.yml#L168 on appveyor, not on Travis. Appveyor runs now only 3 verification commands, but it better to be able to run any command that we need.

It will be also good to update appveyor to run scripts from `.ci` folder if command become long.

**Comment by pbludov** [comment]
@daniilyar please set up the OpenJDK 9 build for a Travis Linux CI. Same command as for the Windows build:
```
CMD1: mvn -e verify -Dcheckstyle.ant.skip=true -Dcheckstyle.skip=true
CMD2: mvn -e -Pno-validations site
```

**Comment by romani** [comment]
we do not need this issue, appveyor is busy enough with windows builds.
running side by side is not flexible enough, so it will be complicated to manage.
