### ISSUE TITLE
how  can I ignore package?

### ISSUE THREAD

**Issue by szoyaung** [checkstyle/checkstyle#5625]
I‘m just use CheckStyle  on Intellij Idea  with the normal checkstyle.xml and CheckStyle-IDEA-5.18.1.zip  , and i want to ignore all  java files under com.xxx package, Is that possible ?
sorry for  my bad english!!

**Comment by rnveach** [comment]
> ignore all java files under com.xxx package

I assume you mean to ignore all violations.
Use a suppression filter.
http://checkstyle.sourceforge.net/config_filters.html#SuppressionFilter

**Comment by romani** [comment]
@szoyaung , please use stackoverflow or mail list for usage questions 
https://github.com/checkstyle/checkstyle#feedbacksupport

we keep gitub issues only for properly reported problems.
