### ISSUE TITLE
Exclude option for Checker

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#564]
As exception happen due to new java grammar possibilities or logic problem in Check , use have no ability to do workaround by suppression, the only way is switch OFF checkstyle or rewrite java file to avoid exception.

TODO:
we need to introduce new mechnism of "exclude" for particular source files by path or canonical name, it would be also good (as option) to exclude certain Check from execution on file.
We need to think about referencing a Exclude file from configuration as it was done for Suppression.
##

**Comment by rnveach** [comment]
@romani 
The 'excluding a file' part was implemented with `BeforeExecutionExclusionFileFilter`.
Do we still need option to exclude a specific file from a specific check?

**Comment by rnveach** [comment]
@romani ping.
This sounds similar to option 4 which we are deciding on implementing in https://github.com/checkstyle/checkstyle/issues/3462#issuecomment-268842411 .

**Comment by jochenvdv** [comment]
@romani 

I think implementing a general solution for all checks might be a very good idea. Very often I want to exclude tests from a specific check but I do not want to have a separate configuration file. Maybe we can somehow make a `path` property for all checks and make this a convention?

**Comment by romani** [comment]
@rnveach ,

> The 'excluding a file' part was implemented with BeforeExecutionExclusionFileFilter.
Do we still need option to exclude a specific file from a specific check ?

No, this filter is covering what we wanted in this issue.

-------------

@jochenvdv ,

> Very often I want to exclude tests from a specific check but I do not want to have a separate configuration file.

In this issue we wanted to skip not a certain file on certain Check, but to skip whole processing (java parsing ) to avoid crashes.

You can use suppressions - example https://github.com/checkstyle/checkstyle/blob/master/config/suppressions.xml#L30 of suppressions in tests for over demanding Checks.

If you do not like multiple config files , I do not like too, but this is separate feature.
Please review #1051 where suppression should be possible to define in same config.

 --------------------------

Issue is closed as it is implemented at #2866 .
