### ISSUE TITLE
generated jacoco.exec file needs to be moved out of base directory

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#5640]
I get the following error when verifying my work locally:
````
[INFO] --- maven-antrun-plugin:1.8:run (ant-phase-verify) @ checkstyle ---
[INFO] Executing tasks

main:

execute:
     [echo] Checkstyle started (checkstyle_checks.xml): 23/03/2018 03:27:57 PM
[checkstyle] Running Checkstyle 8.9-SNAPSHOT on 974 files
     [echo] Checkstyle finished (checkstyle_checks.xml) : 23/03/2018 03:28:00 PM
     [echo] Checkstyle started (checkstyle_non_main_files_checks.xml): 23/03/2018 03:27:57 PM
[checkstyle] Running Checkstyle 8.9-SNAPSHOT on 1478 files
[checkstyle] [ERROR] M:\checkstyleWorkspaceEclipse\checkstyle\jacoco.exec:0: File does not end with a newline. [NewlineAtEndOfFile]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
````

It would be helpful if this file could be moved into `target` folder to  prevent interference with verifying the build locally.

**Comment by rnveach** [comment]
The file had a timestamp of today but re-running the commands I have been using didn't recreate it.
Maybe this is left over from an old master?

**Comment by romani** [comment]
I can not reproduce this on latest master, after `mvn clean verify`, no extra file.

But I experienced this problem too some time ago recently, I thought it was only my local and relates tot some abnormal termination of process or ....

**Comment by pbludov** [comment]
I also got this problem. This usually happens in the build preceded by git pull or rebase.
I'm trying to understand in which phase this file appears, but so far it is inconclusive.
Please, let me know if you find out something.

**Comment by pbludov** [comment]
One victim found:
```
.ci/shippable.sh <any pitest profile>
```
will bring this file to life.

**Comment by pbludov** [comment]
Can be solved by activating the `no-validations` profile for `pitest` checks.
Actually, this should be done regardless of this issue. It will not only solve the problem, but also speed up the pitest validation.
@rnveach please rename this issue to something like
"All other validations should be off while the pitest validation is performed"

**Comment by romani** [comment]
This issue is miscellaneous, so will go to Notes group in release notes, users do care about this group of changes, so title could be any that is ok to us only.

**Comment by romani** [comment]
I might be my bad, during refactoring of pitest, I remember that `-Pno-validation` was there from the beginning.

**Comment by romani** [comment]
fix is merged
