### ISSUE TITLE
RegexpMultilineCheck: new property to set the maximum number of violations logged.

### ISSUE THREAD

**Issue by lpapazow** [checkstyle/checkstyle#5650]
I want to use **RegexpMultilineCheck** to check if eol symol is LF or CR/LF and I want the severity to be warning.

For most files I would assume that if a `\r\n` pattern is matched for all of the first few lines, then the entire file has the same eol symbol and I wouldn't want every line to be logged as a warning.

The same property would be useful in **RegexpSingleLineCheck** if I want to use it to warn when trailing whitespaces are found and only log the first few warnings.

**Comment by romani** [comment]
We will not damage Checks with such new property.

You need to write your own filter http://checkstyle.sourceforge.net/writingfilters.html which can remove from final report as much as you want, even to have for each Check special threshold.

You can contribute such filter to https://github.com/sevntu-checkstyle/sevntu.checkstyle if you ok to make it a bit general.
If you want to resolve your issue asap, you can do any hack on your side(even to update Checks with new property) and proceed.
