### ISSUE TITLE
Remove usage of com.oracle.net package

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#5660]
This package is unavailable in the OpenJDK9 (but is available in the OracleJDK9).
The only usage of this package is the file `src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparator.java`.

For that test the package name is irrelevant and can be changed to any other.

**Comment by romani** [comment]
it might be also good to put in Travis build for openjdk, to prevent problems like this in future and never let anybody create new problem like this.
