### ISSUE TITLE
HTTPS for domain checkstyle.org 

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#5661]
discussion from #5601

 jansohn commented 2 days ago
>The current SSL certificate is not valid for checkstyle.org so we can't use https properly. This should be fixed!

daniilyar commented a day ago
>@jansohn, we don't have an SSL certificate. There is nothing to protect on checkstyle.org with SSL encryption I believe.
I think there is no way to configure redirect from HTTPS to HTTP or put certificate or disable HTTPS completely on github.io.
We also don't have any computing resources in the cloud where we would be able to install some reverse proxy (Nginx) with SSL certificate and automatic certificate renew.
I think that the proper way to prevent https browser warnings for users is to redirect HTTPS to HTTP which again points us to the need to host site on some instance in the cloud instead of github.io

jansohn commented 17 hours ago
>I disagree that there is nothing to protect. Downloading the Eclipse plugin is one example I can think of which should be protected from MITM.
I've no experience with github.io pages but before this redirect to checkstyle.org I could use an https URL to protect the Eclipse plugin update site.

romani commented 11 hours ago •
> @lkoe and/or @Bananeweizen please remind us history of https resources for eclipse-cs .
I think, there was no https on sourceforge.
Https appeared when eclipse-cs migrated to GitHub.io . As GitHub allow both by default.
Now it becomes not possible again as we use custom domain name.
Example of build failure with this https-->http redirection - https://travis-ci.org/sevntu-checkstyle/sevntu.checkstyle/jobs/359606354#L722 , noticed by @jsoref .
We downgraded to http for now in our satellite project.

daniilyar commented 8 hours ago •
>@jansohn, thanks for clarifying about Eclipse update site! I think you are right, unencrypted Eclipse update site is a real security concern.
@romani, taking this into account, I believe the proper way for us is to use a custom domain name with TLS encryption and http --> https redirect is to setup Nginx on the cloud with letsencrypt cert and host / proxy all our public resources (DTDs, Eclipse update site, Maven site, etc.) with it.

romani commented 7 hours ago
> It was always as http (sourceforge), it become as https only for few weeks (xxxx.github.io).
So we come back to where we were for many many years. So is users still would love to have https ... lets open new issue on this.
I am ok to think about https .... but after final migration to github and we need to get to know how to do this with github.io . There should good security concerns to force our team to bother with certificates renewal each several month or ..... we need help for this topic.

jansohn commented 2 hours ago
>Netlify seems to provide a free solution to this problem:
https://www.radibit.com/2017/01/29/https-setup-for-github-pages.html

daniilyar commented 38 minutes ago
>@jansohn, I saw this one. The issue with it is that it does not refresh the letsencrypt certificate automatically so one should manually update it each 90days. Letsencrypt wants to even reduce this period in future.
AFAIK, the only solution when we can setup the reliable certificate auto-refresh is when there is a cloud host with Nginx and cron certificate refresh rule. I've spinned up some instance for Checkstyle at AWS free tier recently for CI purposes and I believe we may put the site there also which should solve both TLS issue and certificate auto renewal issue.
But if somebody can suggest a service that provides a cloud instance with static IP forever and for free that would be great as AWS free tier only lasts 1y.
I have requested such a free instance from Scaleway and Rackspace hostings on Checkstyle organization behalf so far but both refused to give it or 'sponsor' it.

**Comment by jansohn** [comment]
@daniilyar where did you read that you need to renew the certificate manually? According to this blog post renewal is automatic:
https://www.netlify.com/blog/2016/01/15/a-worlds-first.-free-ssl-with-lets-encrypt/

> Click on Let’s Encrypt Certificate and Netlify will instantly provision and install a certificate for your site. The whole process takes seconds, and Netlify will renew your certificate automatically.

**Comment by daniilyar** [comment]
@jansohn hmm, it seems you are right. This netlify is worth to try then, I think. Will try it out in upcoming week or two

**Comment by tsjensen** [comment]
+1 for Netlify. I tried it with a [dummy site](https://github.com/levelnull/levelnull.org) ([https://levelnull.org/](https://levelnull.org/)), and it took me about an hour, mostly due to Jekyll problems. (GitHub provides certain variables to Jekyll, which are unavailable when running on the Netlify side.) The Netlify stuff itself was very straightforward.
The only drawback I could find so far is that the Netlify CDN is a bit slower than GitHub's globally (GitHub Pages response time is ~100ms, Netlify about ~500ms, tested with uptime.com). And there is no "Netlify Deploy" badge on shields.io. 😉

**Comment by Bananeweizen** [comment]
As requested above: the Eclipse update site was previously served via http from sourceforge, see https://github.com/checkstyle/eclipse-cs/commit/7bec79dbdcd9ca24a5155474bbf20504a2054ab0 for the change.

**Comment by lkoe** [comment]
I am late to the party but found this how-to, which describes how to enable TLS for a custom domain using Cloudflare: https://gist.github.com/cvan/8630f847f579f90e0c014dc5199c337b

**Comment by jsoref** [comment]
https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

**Comment by Bananeweizen** [comment]
While I have read the announcement, I have no idea what it means regarding the necessary actions. Is it now enough to simply switch on the setting mentioned in the article or is it still necessary to do some external stuff, like described in the above comments?

**Comment by tsjensen** [comment]
I just tried it with one of my GitHub Pages hosted sites. HTTPS is now enabled *by default*, so, when you do nothing, you now have both HTTP and HTTPS. You may choose in the repo settings to "force SSL", which means your HTTP traffic is going to be automatically redirected to HTTPS.
Imho this is really big news for GitHub Pages!

**Comment by jsoref** [comment]
Looking through https://twitter.com/github/status/991366832421523456, I think the starting point is:
https://help.github.com/articles/troubleshooting-custom-domains/#https-errors
along with https://help.github.com/articles/adding-or-removing-a-custom-domain-for-your-github-pages-site/
But, it also suggests:
https://twitter.com/GitHubHelp/status/991746230014406656
> If you haven't already, please contact us at http://git.io/c  so we can help out with that.

Afacit, for an apex domain (which checkstyle.org is), there's definitely _some_ work required (unlike *.github.io).

But, I can't personally figure out where the various knobs are based on the repositories I control...

**Comment by tsjensen** [comment]
@jsoref Right, my previous comment was for a CNAME site. For apex domains, one must exchange the IP addresses in the domain's DNS record, and (important!) remove and re-add the custom domain in the repo settings ([docs](https://help.github.com/articles/setting-up-an-apex-domain/#configuring-a-records-with-your-dns-provider)). And be patient, as DNS update and cert issuance may take some time. Just tried it with an apex domain, it's still quite quick and painless.

**Comment by romani** [comment]
> https://blog.github.com/2018-05-01-github-pages-custom-domains-https/ 

@lkoe , are you ok enforce https over checkstyle.org ?

it will affect you mostly, as core checkstyle project is not migrated yet to new domain, but we keep content at it as backup location.

**Comment by Bananeweizen** [comment]
I can not really answer that question, as I'm just a code maintainer since a short time. I think the main focus from the eclipse-cs point of view is whether existing plugin installations still can update correctly, since the update site URL is contained in the existing installations and therefore must continue to work. The old update site URL is http://eclipse-cs.sourceforge.net/update, which currently redirects to http://checkstyle.org/eclipse-cs/update/, and the interesting part from our side is whether that now automatically redirects to https, or whether @lkoe must change the redirect from sourceforge to directly point to the https version.

**Comment by romani** [comment]
when eclipse-cs migrated to github, your update link was changed to https. All was happy. This issue was created then core project also come to github.io but with his own domain and link come back http. As at that time custom domains could not have https by default. So eclipse-cs users liked https and complained to return it back. Now I can do this, so theoretically all become as eclipse-cs come to github.io - https with no complains from users.

**Comment by lkoe** [comment]
The .htaccess file for eclipse-cs on SF already redirects to the https-URLs:

`
Redirect 301 /update https://checkstyle.github.io/eclipse-cs/update/
Redirect 301 / https://checkstyle.github.io/eclipse-cs/
`

However, calling `https://checkstyle.github.io/eclipse-cs/update/` redicts again to `http://checkstyle.org/eclipse-cs/update/`, likely because of the incomplete https setup for checkstyle.org (???).

**Comment by lkoe** [comment]
> @lkoe , @Bananeweizen are you ok enforce https over checkstyle.org ?

yes, absolutely!

**Comment by romani** [comment]
I think issue can be closed, if somebody find smth strange - please do not hesitate to raise here.
