### ISSUE TITLE
Illegal Type Check: not all default classes could be blindly substituted

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#567]
https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java#L50

http://docs.oracle.com/javase/7/docs/api/java/util/LinkedList.html
vs 
http://docs.oracle.com/javase/7/docs/api/java/util/List.html

There bunch of methods that LinkedList class is owning, so List can not be used as blind substitution for LinkedList  without detailed analysis of that variable/field in code. Checkstyle is not able to do that correctly, so that generate a lot of false positives.

TODO: 
review all default classes and keep only that classes that could be 100% substituted by Interface reference. 

additional todo:
use https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/DetailAST.java#L340 instead  of  "isStarImport"

**Comment by mkordas** [comment]
* `GregorianCalendar` - Not OK - no interface has [setGregorianChange(Date)](http://docs.oracle.com/javase/8/docs/api/java/util/GregorianCalendar.html#setGregorianChange-java.util.Date-) or [getGregorianChange()](http://docs.oracle.com/javase/8/docs/api/java/util/GregorianCalendar.html#getGregorianChange--), [isLeapYear(int)](http://docs.oracle.com/javase/8/docs/api/java/util/GregorianCalendar.html#isLeapYear-int-), [toZonedDateTime()](http://docs.oracle.com/javase/8/docs/api/java/util/GregorianCalendar.html#toZonedDateTime--), [from(ZonedDateTime)](http://docs.oracle.com/javase/8/docs/api/java/time/ZonedDateTime.html)
* `Hashtable` - Not OK - no interface has [contains(Object)](https://docs.oracle.com/javase/8/docs/api/java/util/Hashtable.html#contains-java.lang.Object-) - could be easily replaced by [containsValue](https://docs.oracle.com/javase/8/docs/api/java/util/Hashtable.html#containsValue-java.lang.Object-), `Map` interface is not `Serializable`
* `HashSet` - OK, but `Set` interface is not `Serializable`
* `HashMap` - OK, but `Map` interface is not `Serializable`
* `ArrayList` - Not OK, no interface has [trimToSize(int)](http://docs.oracle.com/javase/8/docs/api/java/util/ArrayList.html#trimToSize--) or [ensureCapacity(int)](http://docs.oracle.com/javase/8/docs/api/java/util/ArrayList.html#ensureCapacity-int-) method, `List` is not serializable
* `LinkedList` - Not OK, as described in previous comment
* `LinkedHashSet` - OK, but `Set` interface is not `Serializable`
* `LinkedHashMap` - OK, but `Map` interface is not `Serializable`
* `TreeSet` - OK, but `Set` interface is not `Serializable`
* `TreeMap` - OK, but `Map` interface is not `Serializable`
* `Vector` - Not OK, no interface has [trimToSize()](http://docs.oracle.com/javase/8/docs/api/java/util/Vector.html#trimToSize--) or [ensureCapacity(int)](http://docs.oracle.com/javase/8/docs/api/java/util/Vector.html#ensureCapacity-int-) method, `List` is not serializable

@romani - what do you think? If we wanted to be strict, the default value would need to be empty. However, I still think that using these classes in public methods/fields is very bad practice. But usage in private methods may be fine to preserve additional methods or serializability. 

What's more, I believe there are multiple other classes that shouldn't be used in public API like Dictionary, ArrayBlockingQueue, ArrayDeque, ConcurrentLinkedDeque, ConcurrentLinkedQueue, ConcurrentSkipListSet, CopyOnWriteArrayList, CopyOnWriteArraySet, DelayQueue, EnumSet, HashSet, LinkedBlockingDeque, LinkedBlockingQueue, LinkedTransferQueue, PriorityBlockingQueue, PriorityQueue, Stack, SynchronousQueue, ConcurrentHashMap, ConcurrentSkipListMap, EnumMap and probably some more

**Comment by romani** [comment]
Thanks a lot for investigation, i need some time review your proposal.

Other admins/users could share their experience on this issue meanwhile.

**Comment by romani** [comment]
We need to remove from default of this Check following classes:
GregorianCalendar, Hashtable, ArrayList, LinkedList, Vector

but we could recommend to put them in list in documentation, as methods that are diff from interface methods are so rear used, so in most cases user will benefit from checking for them. In some ocasional cases user could use Suppressions.

> However, I still think that using these classes in public methods/fields is very bad practice. But usage in private methods may be fine to preserve additional methods or serializability. 

that is good idea for check extension, please feel free to file separate issue on it.

> What's more, I believe there are multiple other classes that shouldn't 

yes, but we can not put them in default as default should be minimal, but we could reference in documentation that user can do that.

**Comment by romani** [comment]
new option "memberModifiers" should be created to work for methods and fields, option will be a Array of TokenTypes.

**Comment by romani** [comment]
will be in 6.3
