### ISSUE TITLE
consider introducing spelling regression checker

### ISSUE THREAD

**Issue by jsoref** [checkstyle/checkstyle#5676]
https://github.com/jsoref/spelling has a number of scripts for managing spelling, but only three are relevant to this, and I suspect you'll end up using one as is and writing a rolled up version of the other two:

* `w` takes a stream of text and identifies suspicious words -- I'd encourage you to use this as is.
* `f` looks decides which files to feed to `w` and then runs them through `w` -- the algorithm it uses may not be suitable for your project. In general, I end up manually deleting (i.e. "excluding") files.
* `fchurn` this script runs `f` saving its output to a file, and the next time you run it, it compares the output of the current run -- in theory, it's designed to be used for precisely this task. Its output is any "newly" introduced tokens, which are either "misspellings" or "acceptable".

The file `fchurn` produces can be committed into the repository, or, if you are willing to rely on `git`, you could have your `fchurn` figure out the answer by generating the answer for the previous (or referenced) commit. By storing the output file into the repository, you're essentially listing "accepted" "misspellings" -- a whitelist.

Fwiw, you can compress or similarly obfuscate the whitelist so that it doesn't upset anyone else's spell checking tools (or just to conserve space).

Offhand, I suspect that the right place for the file to live would be `.ci`.

Hopefully, this information is a helpful outline. I may try to put together an actual PR for this, but probably not imminently.

**Comment by romani** [comment]
As you passed you project over our code few times with corrections you might already have list of excludes and whitelist.

We do not need any git dependency. All we need is Unix shell commands for:
- how to install your tool  in Linux box
- comment line to run over cloned sources, if problem is found, print it with suggestion and return non zero exit code

All required scripts, could be hosted in .ci folder.

**Comment by romani** [comment]
I merged as first draft .
I have problems with run of this on local
my output is https://gist.github.com/romani/e6338828bc6505e20845e65e43ae68f1

@jsoref , please assist.

**Comment by jsoref** [comment]
Looking

**Comment by romani** [comment]
output:
```
@@ -1380 +1380 @@
-openjdk (OPENJDK, openjdk)
+openjdk
```
it mean that before commit there was two variants of word openjdk and now it is only one, so there is diff, so it is failed.
@jsoref , so usage of `xxxx (xxxx xxxx)` is very fragile. Is there a way to avoid this ?

**Comment by jsoref** [comment]
Lazy approach would be a filter that strips the parenthetical portion... That seems like a reasonable way to approach the whitelist...

**Comment by romani** [comment]
Sorry, I do not understand your terminology, can you explain one more time, or just send PR

**Comment by jsoref** [comment]
#5701 / #5703

**Comment by romani** [comment]
Problems:
```
$ grep -r "Xiao" *
src/xdocs/releasenotes.xml:            make code coverage for MainFrameModel 100%. Author: Xiao Pu <a href="https://github.com/checkstyle/checkstyle/issues/3648"> #3648</a>

$ grep -r "wanadoo" *
src/main/java/com/puppycrawl/tools/checkstyle/api/AuditEvent.java: * @author <a href="mailto:stephane.bailliez@wanadoo.fr">Stephane Bailliez</a>
src/main/java/com/puppycrawl/tools/checkstyle/api/AuditListener.java: * @author <a href="mailto:stephane.bailliez@wanadoo.fr">Stephane Bailliez</a>
src/main/java/com/puppycrawl/tools/checkstyle/DefaultLogger.java: * @author <a href="mailto:stephane.bailliez@wanadoo.fr">Stephane Bailliez</a>
src/main/java/com/puppycrawl/tools/checkstyle/XMLLogger.java: * @author <a href="mailto:stephane.bailliez@wanadoo.fr">Stephane Bailliez</a>
src/main/java/com/puppycrawl/tools/checkstyle/Checker.java: * @author <a href="mailto:stephane.bailliez@wanadoo.fr">Stephane Bailliez</a>

$ grep -r "unrealwork" *
src/xdocs/releasenotes.xml:            Grammar mistakes in PULL_REQUEST_TEMPLATE.md. Author: unrealwork
src/xdocs/releasenotes.xml:            README: broken link. Author: unrealwork<a href="https://github.com/checkstyle/checkstyle/issues/4093"> #4093</a>

$ grep -r "Skytt" *
src/xdocs/releasenotes_old.xml:        checkstyle with JRockit (thank to Ville Skytta for
src/xdocs/releasenotes_old.xml:        (patch 835896, from Ville Skytta (scop)).</li>
src/xdocs/releasenotes_old.xml:        from Ville Skytta (scop)).</li>
src/xdocs/releasenotes_old.xml:        <li>Added a Finnish localization, contributed by Ville SkyttÃ¤.</li>
src/xdocs/releasenotes_old.xml:        <li>Incorporate patch 607481 from Ville SkyttÃ¤ to enforce wrap on operator at EOL.</li>
```

@rnveach , I propose to move all `@author` tags from our code with will remove bunch of weird words from whitelist. Are you ok ?
To allow no tag we nee to do:
```
$ git diff
diff --git a/config/checkstyle_checks.xml b/config/checkstyle_checks.xml
index a561522..ff227a3 100644
--- a/config/checkstyle_checks.xml
+++ b/config/checkstyle_checks.xml
@@ -373,7 +373,6 @@
     </module>
     <module name="JavadocTagContinuationIndentation"/>
     <module name="JavadocType">
-      <property name="authorFormat" value="\S"/>
       <!-- avoid errors on tag '@noinspection' -->
       <property name="allowUnknownTags" value="true"/>
     </module>
```

I also propose to exclude from validation releasenotes.xml and releasenotes_old.xml as it is also have bunch of names.
It will be a chore for contributors to add their names/nicks/..... to whitelist on each commit.
As we do this, we can drop down whitelist to bout 1K lines, so we scan move it main repo and start to use this tool in CI.

more nuances (some of them could be resolved by better names in Inputs, some of them not resolvable):
```
~/java/github/checkstyle/contribution/jsoref-spellchecker [master L|✔] $ grep -C 2 "fffff" whitelist.words 
xfffb
xffff
xffffffff
xffffffffffffffff

~/java/github/checkstyle/checkstyle [master L|✔] $ grep -C 2 -r "xffffffffffffffff" *
.../MagicNumberCheckTest.java-            "103:36: " + getCheckMessage(MSG_KEY, "-2.5"),
.../MagicNumberCheckTest.java-            "109:34: " + getCheckMessage(MSG_KEY, "0xffffffff"),
.../MagicNumberCheckTest.java:            "110:36: " + getCheckMessage(MSG_KEY, "0xffffffffffffffffL"),

```
and works are validated in URLs (should be skipped)
```
~/java/github/checkstyle/contribution/jsoref-spellchecker [master L|✔] $ grep -C 2 "CHDCHAHD" whitelist.words 
CHDCEAHH
CHDCFJDG
CHDCHAHD
CHDCHBAE
CHDDCDHH

~/java/github/checkstyle/checkstyle [master L|✔] $ grep -r "CHDCHAHD" *
src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java:     * <a href="https://docs.oracle.com/javase/8/docs/technotes/tools/unix/javadoc.html#CHDCHAHD">
```

@rnveach , please let me know your opinion on usage of this too in CI and in what form.

Most of other problems are not resolvable, and could be skipped only if we move algorithm to Check and know context of word and skip odd names from URLs, string values, names of imports,...... .  Our old idea - https://github.com/checkstyle/checkstyle/wiki/Checkstyle-GSoC-2017-Project-Ideas#project-name-spellcheck-of-identifiers-by-english-dictionary

@jsoref , are you interested to write checkstyle module (in java language) to do validation of java sources more precisely(with less amount of false positives) ?

**Comment by rnveach** [comment]
> I propose to move all @author tags from our code with will remove bunch of weird words from whitelist. Are you ok ?

I am fine with this.

> please let me know your opinion on usage of this too in CI and in what form.

If by 'usage' you mean using it or not, I am fine with using it. My own projects I use a custom Dictionary check where I must add the words to it like this util. I got tired of constantly finding mis-spelled words.
I'm not sure what you mean by 'form'.

**Comment by romani** [comment]
Tool is activated.

All further enhancements should be done in separate issues.
