### ISSUE TITLE
confusing file name: checkstyle-checkstyle-8.9.zip

### ISSUE THREAD

**Issue by Bananeweizen** [checkstyle/checkstyle#5686]
Please download the source zip for 8.9 from the link at the release page over at: https://github.com/checkstyle/checkstyle/releases.

The local file is named checkstyle-checkstyle-8.9.zip, even though the URI preview for the download link does not contain the duplicate name part. This name does not fit the previous standard naming scheme checkstyle-x.y-src.zip anymore. Is this intended?

**Comment by rnveach** [comment]
https://github.com/checkstyle/checkstyle/releases/tag/checkstyle-8.9
> https://github.com/checkstyle/checkstyle/releases/download/checkstyle-8.9/checkstyle-8.9-all.jar
> https://github.com/checkstyle/checkstyle/archive/checkstyle-8.9.zip
> https://github.com/checkstyle/checkstyle/archive/checkstyle-8.9.tar.gz

File links are named correctly, but it is github that is sending the file name through the download and telling it to name it `checkstyle-checkstyle-`. I assume it is appending the project name to the file names.

**Comment by Bananeweizen** [comment]
The behavior seems to be the same for my own github project. I just never noticed, since there is no downstream project consuming the source zip. However, I can live with attaching the sources under a different name in EclipseCS, so feel free to close this issue.
