### ISSUE TITLE
Move Treewalker cache to Checker

### ISSUE THREAD

**Issue by lkoe** [checkstyle/checkstyle#569]
I have a subtle bug filed against eclipse-cs (https://sourceforge.net/p/eclipse-cs/bugs/377/) which I tracked down to TreeWalker's internal caching of files already checked.

The eclipse-cs plugin caches fully configured Checker modules internally for performance reasons. However due to TreeWalkers internal caching (TreeWalker#mCache) files are being considered as "already checked" in subsequent Checkstyle executions, which in turn leads to problems when projects are re-checked in eclipse during a full/clean build.

Please provide API to reset a Checker instance to pristine state, meaning all internal caches to be cleared - or modify the default TreeWalker caching (which seems unnecessary if no proper TreeWalker cacheFile is used).

**Comment by romani** [comment]
as workaround you can call method https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/TreeWalker.java#L135 it will reset mCache.

but you are right Cache is strange , some method should be created for this.

**Comment by lkoe** [comment]
Unfortunately Checker has no API to access submodules, which means without resorting to reflection hacks I can't get hold of the TreeWalker instance.

**Comment by romani** [comment]
Please send me web link to your code, i need to see it.

**Comment by lkoe** [comment]
https://sourceforge.net/p/eclipse-cs/git/ci/f4eb518f3e81c650a7bc74d676afc83ad166ad38/tree/net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/builder/CheckerFactory.java?diff=94c49f6da3a6ea11858ce3eaeec339c00f7479f0

**Comment by romani** [comment]
thanks a lot for details, I see a problem. We definetely should do smth to ease plugins development.

Right now I am not ready to predict how API will change, that is good that you have workaround.
I will think about this issue in more detail as we come close to API changes.

**Comment by lkoe** [comment]
Any update on this? I'd prefer to get rid of my shady workaround one day...

**Comment by romani** [comment]
sorry I forgot about this, I put special tag to do that ASAP, but it will not be in 6.10 release (31 August)

**Comment by romani** [comment]
sorry that we did not address this issue in 6.11 , too much activity with active PRs.

**Comment by romani** [comment]
moved from #407 

>  Cache is located in TreeWalker, but tree walker does not contain all Checks (not all Checks are java AST related: RegexpCheck, TranslationCheck, .....) - so we need to move cache to Checker.

that what we need to resolve this is issue.
Checker need to have public method to do clear for cache.

**Comment by romani** [comment]
fix is merged.
