### ISSUE TITLE
jsoref spell checker: remove resource from validation

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#5693]
Folders to skip by spell checker:
`src/test/resources/*`
`src/it/resources/*`
such folders contains ugly code by design, all mistakes in them are done on purpose for testing.

cleanup https://github.com/checkstyle/contribution/blob/master/jsoref-spellchecker/whitelist.words from odd names.

**Comment by romani** [comment]
@jsoref , can you help us with this issue ?

**Comment by jsoref** [comment]
Sure, offhand the place to stick this is near the find argument, iirc it currently excludes "images", you could use the same style for "resources" assuming you're willing to exclude all folders named "resources".

I'll look in more detail tomorrow.

**Comment by romani** [comment]
yes, you might already have tool/command that can easily remove all not found words from whilelist.

**Comment by romani** [comment]
@jsoref , thanks a lot for filter .
can you send us PR to cleanup whiltelist ?

I want to activate your tool on PR validation. Right now it is disabled(always return 0 as exit code)

**Comment by jsoref** [comment]
@romani sure: checkstyle/contribution#296 -- it's pretty small :-)

**Comment by jsoref** [comment]
If you're asking about for this PR, that was already done in https://github.com/checkstyle/checkstyle/issues/5693#ref-pullrequest-312315978

**Comment by romani** [comment]
The biggest problem of whitelist is that it too much words from our inputs/resources, example https://github.com/checkstyle/contribution/blob/master/jsoref-spellchecker/whitelist.words#L3585 
```
✔ ~/java/github/checkstyle/checkstyle [master|✔] 
$ grep -Rl "ZZZZZZ" *
src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/abstractjavadoc/InputAbstractJavadocPositionWithSinglelineComments.java
```

as we get rid of them, it should become small it might become reasonable to host it main repo.

**Comment by romani** [comment]
@jsoref , whitelist file still contains odd words, please help to cleanup.
I did several changes to whitelist to resolve diffs at CIs.

**Comment by jsoref** [comment]
Hmm...
We could drop:
* single letter repetitions (e.g. `ZZZZZ`)
* unicode things: `u[a-f]+`
* hex things: `[a-f]+` (I'm not terribly comfortable with this one, it could easily result in letting a misspelling through)

I think this set should be a pretty good win...

**Comment by romani** [comment]
@jsoref , one more nuance:
```
~/java/github/checkstyle/contribution/jsoref-spellchecker [master L|✔] $ grep -C 2 "fffff" whitelist.words 
xfffb
xffff
xffffffff
xffffffffffffffff

~/java/github/checkstyle/checkstyle [master L|✔] $ grep -C 2 -r "xffffffffffffffff" *
.../MagicNumberCheckTest.java-            "103:36: " + getCheckMessage(MSG_KEY, "-2.5"),
.../MagicNumberCheckTest.java-            "109:34: " + getCheckMessage(MSG_KEY, "0xffffffff"),
.../MagicNumberCheckTest.java:            "110:36: " + getCheckMessage(MSG_KEY, "0xffffffffffffffffL"),

```

How can we skip hex stuff from validation ?

**Comment by romani** [comment]
one more prove that resources are not excluded
```
$ grep -rl "soooooooooooooooooooooooooooooooooooolongfooooooooooooooooooooooooooooooooooooooooooo" *
src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule32packagestate/InputLineLength.java
src/it/resources/com/google/checkstyle/test/chapter3filestructure/toolongpackagetotestcoveragegooglesjavastylerule/InputLineLength.java
```

**Comment by jsoref** [comment]
Ok, the problem is that the files don't start with a leading `/` and thus the exclude isn't working...

**Comment by romani** [comment]
issue is resolved.
