### ISSUE TITLE
Update javadoc for MismatchStrategy

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#5695]
https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/MismatchStrategy.java

It is actually matching strategy, so name should be fixed

**Comment by romani** [comment]
@rnveach , please approve if you agree

**Comment by rnveach** [comment]
@romani It is actually the strategy used if the current import can't be matched to any of the allows/disallows listed in the package.
https://github.com/checkstyle/checkstyle/blob/master/config/import-control.xml#L154
If a match does occur, the specific allow/disallow that is matched is the result.

**Comment by rnveach** [comment]
http://checkstyle.sourceforge.net/config_imports.html#ImportControl
> In the next examples usage of strategyOnMismatch property is shown. This property defines strategy in a case when no matching allow/disallow rule was found.

**Comment by romani** [comment]
fix is merged
