### ISSUE TITLE
FinalClassCheck: 'extractQualifiedName' omits 2nd ident of package name

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#5706]
https://github.com/checkstyle/checkstyle/blob/90f20e09869c71eb22190ad9c1d46d5deec324a5/src/main/java/com/puppycrawl/tools/checkstyle/checks/design/FinalClassCheck.java#L95

[When debugging tests like `testFinalClass`](https://github.com/checkstyle/checkstyle/blob/90f20e09869c71eb22190ad9c1d46d5deec324a5/src/test/java/com/puppycrawl/tools/checkstyle/checks/design/FinalClassCheckTest.java#L50-L58), [`extractQualifiedName`](https://github.com/checkstyle/checkstyle/blob/90f20e09869c71eb22190ad9c1d46d5deec324a5/src/main/java/com/puppycrawl/tools/checkstyle/checks/design/FinalClassCheck.java#L95) returns `com.tools.checkstyle.checks.design.finalclass` when [the package is clearly defined as `com.puppycrawl.tools.checkstyle.checks.design.finalclass` (`puppycrawl` is missing)](https://github.com/checkstyle/checkstyle/blob/f069e73531d0ced9e60b3df633a3123fd9a271e0/src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/finalclass/InputFinalClass.java#L5).

[Looking at the code, when it gets to the top node of the package name, it only pulls in the first `IDENT` and not them both.](https://github.com/checkstyle/checkstyle/blob/90f20e09869c71eb22190ad9c1d46d5deec324a5/src/main/java/com/puppycrawl/tools/checkstyle/checks/design/FinalClassCheck.java#L158)

I am not sure if this bug presents itself in the CLI somehow as I am not that familiar with the check.
I found this bug by duplicating the same code in my own custom check.

**Comment by rnveach** [comment]
@romani Don't we have `FullIdent` class to be used in this situations?
Should this method just be removed and we use `FullIdent` instead? I assume it doesn't have this same bug.

**Comment by rnveach** [comment]
I'm not sure what you mean, API versus util doesn't matter for checks.

**Comment by romani** [comment]
src/main/java/com/puppycrawl/tools/checkstyle/**api**/FullIdent.java)

**Comment by rnveach** [comment]
yes, I know you meant the API package.
But I don't understand from your 1st comment why importing an API class versus a non-API class matters for a check. If `FullIdent` moves to `util` package, it won't hurt this check or any check using it.

**Comment by rnveach** [comment]
If you are referring to my custom check, anyone outside checkstyle can use utils if that is where you plan to move `FullIdent` to.

**Comment by romani** [comment]
it was just side note(off topic) for future of FullIdent class.

**Comment by rnveach** [comment]
Fix was merged
