### ISSUE TITLE
New Check: EmptyCatchBlockCheck 

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#571]
according to agreement with guava tool - https://github.com/google/guava/issues/1891#issuecomment-69090187

We need to make Check that can do coverage of Google Style requirements instead of EmptyBlock.
Coverage page (http://checkstyle.sourceforge.net/google_style.html) have to be updated. https://github.com/checkstyle/google-style-config-test have to be updated too.

Two options:
- regexp for exception variable name ("expected")
- regexp for first line of comment (beware of few single line comments of multi-line comments) , default value is ".*"

How to make Check be aware of comments - just override method and return true: https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/TodoCommentCheck.java#L67

**Comment by romani** [comment]
fixed, will be released in 6.3

**Comment by mkordas** [comment]
In [EmptyCatchBlock](http://checkstyle.sourceforge.net/config_blocks.html#EmptyCatchBlock) docs I see the following: `Checks for empty catch blocks. There are two options to make validation less strict: ...`

However, any change to the default `commentFormat` value which is `.*` would make this check __more strict__. Please fix that.

**Comment by romani** [comment]
you are right, is it ok now ?

**Comment by mkordas** [comment]
Yes, now this sentence is fine.

However, I see couple more problems in docs. They are unclear for me:
*There should be clear info somewhere that by default this check allows empy catch blocks with any comment inside - now user needs to understand the default regex
* type of first property is  `String` while the second is `string`
* `To configure the Check to suppress empty catch block if exception's variable name is expected or ignore` - exaple specifies only variable name, while `commentFormat` stays default `.*`. This means that description should be really `To configure the Check to suppress empty catch block if exception's variable name is expected or ignore or there is any comment inside`
* I don't see any examples how it behaves with multiline comments
* By looking to docs I have no idea if  `<property name="commentFormat" value="This is expected"/>` works only with `//This is expected` or also with `// This is expected`

**Comment by alexkravin** [comment]
@mkordas,

I referenced docs updates PR to this issue, about points you've specified above:

Added info about commentFormat default value and extended description of default configuration.

Extended examples according to commentFormat options, so now there're examples with multiline comments and comments view too.
