### ISSUE TITLE
UpperEll rule description gives bogus reason: Capital(!) L looks like 1

### ISSUE THREAD

**Issue by sewe** [checkstyle/checkstyle#5718]
The [UpperEll](http://checkstyle.sourceforge.net/config_misc.html#UpperEll) rule description ATM describes its reasoning like this:

> The capital L looks a lot like 1.

This is clearly bogus; the lower-case L (l) looks a lot like 1.

The rule itself is correct, just the reason given is not.

**Comment by romani** [comment]
@sewe , thanks a lot.
If you notice one more problem in documentation please be welcome to send PR, all web content is at https://github.com/checkstyle/checkstyle/tree/master/src/xdocs

**Comment by rnveach** [comment]
Fix was merged
