### ISSUE TITLE
update DTD public names

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#5722]
public DTD name format
`prefix//owner_of_the_DTD//description_of_the_DTD//ISO 639_language_identifier`
according to http://xmlwriter.net/xml_guide/doctype_declaration.shtml#PublicDTD

attention to 
> The "DTD_location" is used to find the public DTD if it cannot be located by the "DTD_name".

DTD name is first step to load dtd, second step is remote url. ConfigurationLoader do use  "DTD_name"
to map to internally stored DTD files. So we have to preserve mapping of DTD_name at ConfigurationLoader.
But names still have to changes in all our repo to have good name and all next configurations will follow new format.

TODO:
- `Puppy Crawl` ==> `Checkstyle`
- `DTD Check Configuration` ==>  `DTD Checkstyle Configuration`
- `DTD Import Control` ==>  `DTD ImportControl Configuration`
- `DTD Package Names` ==>  `DTD Package Names Configuration`
- `DTD Suppressions` ==>  `DTD SuppressionFilter Configuration`
- `DTD Suppressions Xpath Experimental` ==>  `DTD SuppressionXpathFilter Experimental Configuration`
...

It should not affect anybody, as is has only description role.

diff should be like:
```
--- a/config/checkstyle_checks.xml
+++ b/config/checkstyle_checks.xml
@@ -1,6 +1,6 @@
 <?xml version="1.0"?>
 <!DOCTYPE module PUBLIC
-          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
+          "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
           "http://checkstyle.sourceforge.net/dtds/configuration_1_3.dtd">
```

All files to update:
`grep -Liran "//Puppy Crawl" --include="*.xml" --exclude-dir="target" *`

**Comment by romani** [comment]
@rnveach , please let me know your opinion on TODO part. I have concern about "...Configuration", It might be not required as DTD(Document Type Definition) kind of mean configuration and xml is mostly for configuration but in the same time we have xml report, that is not configuration and one day we will get DTD/XSD for it too.

please share your opinion.

**Comment by rnveach** [comment]
Struts 2 seems to name its DTD after the file name.
https://github.com/apache/struts/blob/6e96f11debc4fa52c65a12b28fea82b514b96abd/core/src/main/resources/struts-2.5.dtd#L29
https://github.com/apache/struts/blob/6e96f11debc4fa52c65a12b28fea82b514b96abd/core/src/main/resources/xwork-2.5.dtd#L29
https://github.com/apache/struts/blob/6e96f11debc4fa52c65a12b28fea82b514b96abd/core/src/main/resources/xwork-validator-1.0.3.dtd#L27
https://github.com/apache/struts/blob/6e96f11debc4fa52c65a12b28fea82b514b96abd/core/src/main/resources/xwork-validator-config-1.0.dtd#L27
https://github.com/apache/struts/blob/6e96f11debc4fa52c65a12b28fea82b514b96abd/core/src/main/resources/xwork-validator-definition-1.0.dtd#L27

**Comment by romani** [comment]
It description of dtd, but looks like it free text,  usually it is starting from "DTD ....." even in your examples.
So I really think we should rename as I originally stated in issue description, to keep "Configuration"  as we might have DTD/xsd for reports.

**Comment by romani** [comment]
@rnveach , please confirm that you are ok with proposed by me update.

**Comment by rnveach** [comment]
@romani I already stated that I don't think we should name DTD `Configuration` as it is a description of the DTD file and DTD is not the configuration file itself. Even if DTD is for a report, it is for the layout of the report, not the configuration.

**Comment by romani** [comment]
> we should name DTD Configuration

it is not a name, it is description.

example where ".....Configuration" is used - https://github.com/apache/struts/blob/6e96f11debc4fa52c65a12b28fea82b514b96abd/core/src/main/resources/struts-2.5.dtd#L29

Description of DTD is free text that explain what for DTD is applicable so it is for "DTD Checkstyle Configuration"

Please review original description, we already have "Configuration" is all DTD, so I will keep it. Bunch of others use "Configuration" ending too .
Checkstyle modules might have their own output files/reports. So potentially Checks/Modules could have not only configurations but and reports too, could have xml templates for reports, ..... .

**Comment by romani** [comment]
@rnveach , let finish this discussion with resolution.
Do you agree with update ?

**Comment by rnveach** [comment]
I don't agree with naming DTDs `Configuration` but you can continue with the update. It is not that big a deal.

**Comment by romani** [comment]
@subkrish , thanks for coming back after long pause, as you touched xml easy updates , can you help us to resolve this issue ?

**Comment by subkrish** [comment]
@romani @rnveach 

I am on it.

**Comment by romani** [comment]
@subkrish , yes, please.

**Comment by romani** [comment]
@subkrish , do you need help ? 
issue looks like simple sear/replace update , is there any hidden problems?

**Comment by subkrish** [comment]
@romani 

No no. No help required. I'll finish it up ASAP.

Although, additionally along with the `xml` files do I also need to change `dtd` files as well? This wasn't asked in the original comment though.

**Comment by romani** [comment]
> This wasn't asked in the original comment though.

yes, in DTD files there is comment with example (ready for copy-paste to xml) on how it should be used.
It is better to have good name it them too, as they are source for all.

**Comment by rnveach** [comment]
Fix was merged.

**Comment by romani** [comment]
@subkrish , thanks a lot for contribution, 
let me know if you have desire to continue contribution, 
we have bunch of others easy issues and a bit more complicated.
