### ISSUE TITLE
Align XDocs and Javadocs

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#5750]
Discussed at https://groups.google.com/forum/?hl=en#!topic/checkstyle-devel/lsNF6Dj90lo , we should sync up our Javadocs with our xdocs and enforce they stay in-sync by CI.

For each new check, we just need to modify the suppression list at https://github.com/checkstyle/checkstyle/blob/bdeeb9898be9a931ff2d066cf1f7835f582dd31a/src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java#L107 for the next check to align.

**Comment by romani** [comment]
@pbludov 
Is it reasonable to split an issue ? By packages or by some grops?

**Comment by pbludov** [comment]
> Is it reasonable to split an issue ? By packages or by some groups?

Yes, it is possible to split by packages. This will make it easier to track the progress.

**Comment by romani** [comment]
@pbludov ,
if you finished split, please close this issue.

**Comment by rnveach** [comment]
Following packages look like they aren't done:

coding
design
header
imports
indentation
javadoc
metrics
modifier
regexp
sizes
whitespace
non-folder checks

and then we need a final issue to remove list of suppression so all checks are processed automatically.

**Comment by rnveach** [comment]
Once we open an issue for the javadoc package, I think we can close this issue.
There are only 2 sub-issues left.

**Comment by romani** [comment]
Final fix is merged
