### ISSUE TITLE
Activate checks related to java.io.Closeable 

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#5752]
Since we no longer use `Cobertura`, we can force `try-with-resources` in the code.
There is a couple of Idea rules for that:

- AutoCloseableResource
- TryFinallyCanBeTryWithResources

and one Eclipse JDT problem:
- explicitlyClosedAutoCloseable

If an auto closeable resource can not be wrapped with `try-with-resources`, the violation should be suppressed.

**Comment by romani** [comment]
It I'd ok to make fix in few PRs. Simple cases should be merged sooner

**Comment by romani** [comment]
Fix is merged
