### ISSUE TITLE
Update AbstractChecks to log DetailAST (part 1, easy cases)

### ISSUE THREAD

**Issue by MEZk** [checkstyle/checkstyle#5757]
Update checks which do not modify line number and only pass it to ```AbstractCheck.log(int line, String key, Object... args) method```. The checks should log the object of DetailAST class.

The following checks should be updated: 
- ArrayTypeStyleCheck
- DescendantTokenCheck
- FinalParametersCheck
- SuppressWarningsCheck
- AvoidNestedBlocksCheck
- AbstractSuperCheck
- AvoidInlineConditionalsCheck
- CovariantEqualsCheck
- EmptyStatementCheck
- EqualsAvoidNullCheck
- EqualsHashCodeCheck
- FinalLocalVariableCheck
- InnerAssignmentCheck
- ModifiedControlVariableCheck
- ParameterAssignmentCheck
- ReturnCountCheck
- SimplifyBooleanExpressionCheck
- SimplifyBooleanReturnCheck
- StringLiteralEqualityCheck
- DesignForExtensionCheck
- HideUtilityClassConstructorCheck
- InnerTypeLastCheck
- MutableExceptionCheck
- ThrowsCountCheck
- VisibilityModifierCheck
- RedundantImportCheck
- BooleanExpressionComplexityCheck
- JavaNCSSCheck
- ModifierOrderCheck
- RedundantModifierCheck
- AbstractClassNameCheck
- MethodNameCheck
- AnonInnerLengthCheck
- ExecutableStatementCountCheck
- MethodLengthCheck
- ParameterNumberCheck
- AbstractParenPadCheck
- WhitespaceAroundCheck

It is OK to print both lineNo and columnNo to user in violation message if it is necessary. No lineNo or violations count regression are expected.

**Comment by romani** [comment]
Just use first or more related AST and report violation on it. Message need be rechecked and could be updated to be reasonable. We will see what to do in each particular case.

**Comment by rnveach** [comment]
I will work on the easy cases.

**Comment by MEZk** [comment]
The description was changed in accordance with changes made in https://github.com/checkstyle/checkstyle/pull/5772 .

**Comment by romani** [comment]
@rnveach , please recheck if you fixed all referenced Checks.
if not , please define what is left.

**Comment by rnveach** [comment]
@romani I missed some easy cases where the log statement was split between lines.

**Comment by romani** [comment]
Can you share what is left ?
You might caught it by removing method and grep on compilation errors.

**Comment by rnveach** [comment]
@romani What is left in the PR.
I found missing cases like you said, removing the method, and looking at each compile error to see if it matched an easy case.

**Comment by rnveach** [comment]
Fixes are done.
