### ISSUE TITLE
Update AbstractChecks to log DetailAST (part 2)

### ISSUE THREAD

**Issue by MEZk** [checkstyle/checkstyle#5758]
Update checks which use HtmlTag, FullIdent, StringInfo or JavadocTag objects' line and column number to log DetailAST.

Checks that should be updated:

- UnusedImportsCheck
- PackageNameCheck
- MultipleStringLiteralsCheck
- IllegalTypeCheck
- AbstractClassCouplingCheck

Some ideas from @rnveach's [comment](https://github.com/checkstyle/checkstyle/issues/4830#issuecomment-383102616):

> We should look into why the checks were designed this way

> llegalTypeCheck's FullIdent makes sure we use the start of the type for the line/column. Example: java.util.List starts with java, but last AST used points to .List. Same with Boolean[], starts with Boolean but last AST used points to []. FullIdent could be modified to save the AST that starts the type so we can then retrieve the correct AST.

This issue is waiting for further discussion and investigation.

**Comment by romani** [comment]
This classes are internal, javadoc related could be skipped for now, as we do not support xpath in javadoc. Yes, they could be updated to have required field to make logging of violation more precise. It would be better to update Checks to log violation not base on such objects, but let's see what will be easier.

**Comment by romani** [comment]
Make sense to start reporting violations base on javadoc AST in Checks. One day xpath will come to javadoc too.

**Comment by MEZk** [comment]
> This classes are internal, javadoc related could be skipped for now
@romani 
Thich javadoc related checks work with DetailAST (not DetailNode)

- JavadocTypeCheck
- JavadocStyleCheck
- JavadocMethodCheck

**Comment by romani** [comment]
all javadoc Checks that are based on regexp parsing (not extended from AbstractJavadocCheck) could be skipped, they need to be updated only after they upgraded to ANTLR parsing (another huge project).

**Comment by pbludov** [comment]
IllegalTypeCheck was fixed as part of #5118

**Comment by romani** [comment]
@rnveach  , should we close this issue ?

**Comment by rnveach** [comment]
@romani Yes, this should fix all checks.
