### ISSUE TITLE
Allow ImportControl for classes (name or extends) to allow/disallow imports

### ISSUE THREAD

**Issue by joseaio** [checkstyle/checkstyle#5761]
Allows control imports for classname or superclass/interface...

    This can be useful to control package-by-feature estructure (instead of package-by-layer)

note: package-by-feature, divide classes into business packages and each business package
can contain classes of multiples layers (rest, business-service, dao, dto/pojo)

Example: com.company.invoice
· InvoiceRest
· InvoiceService
· InvoiceDto
· InvoiceDao
· ProviderRest
· ProviderService
· ProviderDto
· ProviderDao

note: I like to limit imports by class name (_regex_ .*Dao, .*Rest) or by superclass/interface (_extends_ com.company.AbstractDao, _implements_ com.company.IRest)

Proposed elements/tags:
`<class name="{name or regex}">`
`    <allow ...>`
`    <disallow ...>`
`</class>`

`<class extends="{complete name of superclass or interface}">`
`    <allow ...>`
`    <disallow ...>`
`</class>`

Of course allow/disallow on `<class>` elements, must be inherited be child subpackages

**Comment by rnveach** [comment]
> `<class name="{name or regex}">`

Basically a duplicate of https://github.com/checkstyle/checkstyle/issues/3492 .

> `<class extends="{complete name of superclass or interface}">`

Not allowed right now as we only match to file name.
Reason we only validate file names: https://github.com/checkstyle/checkstyle/pull/5641#discussion_r180836619

One workaround is to having a naming pattern based on the superclass/interface of the class.
Example: Implementation of `List` is `ArrayList`, `Set` is `HashSet`, etc....

**Comment by joseaio** [comment]
An interesting feature for the future... Import-Control for class/interface hierarchy (checking extends... )

Thank you

**Comment by romani** [comment]
unlikely we will extend ImportControl, as it control imports in whole file(compilation unit). It does not have logic to split imports between two classes that are hosted in same file (too hard to make this difference).

It is possible that in your case somebody will place DAO/POJO/DTO in one file as they too simple to be placed in separate/own files, ..... . 

So to make you control your code you need to have some Check that control that file is named(prefix, sufix) base on extends/implements class names. There is no such Check in our library, but it might be good idea to have it, you can create an issue on this to discuss design on new Check.

**Comment by romani** [comment]
> It will be in next release.

released as 8.10 - http://checkstyle.sourceforge.net/releasenotes.html#Release_8.10

**Comment by joseaio** [comment]
@romani, thank you for your time...

The new Check as you refer is based on direct extends/implements clases only or is based on whole extends hierarchy?

I think that real "instanceof" for clases/interfaces is the best approach because extends can occur on [various levels](https://www.hierarchystructure.com/wp-content/uploads/2016/06/Hierarchy-of-Animals-in-the-Animal-Kingdom.jpg) and I would like to control imports for distinct hierarchies: Animal, Vertebrates, Bird, Worms... (please, see previous link)

   Can I add a new Checker based on complete hierarchy? (as "instanceof" does)
   or it's impossible at this moment?

**Comment by romani** [comment]
Only direct extends/implements. We do analysis only base on AST of single Java file. http://checkstyle.sourceforge.net/writingchecks.html#Limitations

**Comment by rnveach** [comment]
You can get around this limitation using [a Type Aware check](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractTypeAwareCheck.java) which is what I have done for my own implementation of the check being discussed, but we don't support those type of checks anymore.
