### ISSUE TITLE
SummaryJavadoc: there should be a way to have forbidden regexp validation, without enforcing the presense of a non-empty summary

### ISSUE THREAD

**Issue by nbali** [checkstyle/checkstyle#5763]
I think it would be a valid use-case to forbid certain strings present in the javadoc summary, meanwhile accepting the complete lack of javadoc summary. (For example I wanted to forbid nobrainer summaries like "return the..", but allow having no summary at all - sometimes the method is that straightforward).

Right now it can't be done. Either the check has to be completely removed, or it fails for missing summary.

Either a new configuration, or interpreting an empty string configured as period should do the job.

**Comment by rnveach** [comment]
> Right now it can't be done. 
> or it fails for missing summary.

This is not true. You can use suppressions to suppress the violation message for a missing summary, `Summary javadoc is missing.`.
http://checkstyle.sourceforge.net/config_filters.html#SuppressionFilter

**Comment by nbali** [comment]
My bad then.
