### ISSUE TITLE
Update AbstractChecks to log DetailAST (part3)

### ISSUE THREAD

**Issue by MEZk** [checkstyle/checkstyle#5777]
Checkstyle has recently started to update old checks from logging on the line/column, to log on the AST node. This is needed to support https://checkstyle.org/config_filters.html#SuppressionXpathFilter which needs the AST of the violation to match it to the user supplied XPath.

All checks need to be reviewed to ensure:
1) All their calls to `log` pass the AST and not the line/column
2) Each log have a respective IT test to show that it supports xpath at https://github.com/checkstyle/checkstyle/tree/master/src/it/java/org/checkstyle/suppressionxpathfilter
3) Documentation of https://checkstyle.org/config_filters.html#SuppressionXpathFilter_Description shows the check is now supported.

**1**: We don't expect drastic change in current UTs when making the switch. If any items change the line/column drastically, please point them out to be clear to admins in the PR. Adding a column number when no was there before is ok and an expected change.
**2**: Must have a UT for each log in the check. If the check has 3 separate log calls, then it must have 3 separate UTs.

As PR is started for each check, please post links to master ( Ex: https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/EmptyBlockCheck.java#L201 ) to show each log call found in check and make note of the number of logs modified.

-------

<a href="https://www.bountysource.com/issues/58003133-update-abstractchecks-to-log-detailast-part3">
<img src="https://api.bountysource.com/badge/issue?issue_id=58003133">
</a>

**Comment by romani** [comment]
Just use first or more related AST and report violation on it.
Message need be rechecked and could be updated to be reasonable. We will see what to do in each particular case.

**Comment by rnveach** [comment]
How do we want to report handling a violation on a comment's specific line number?
Example: https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/TodoCommentCheck.java#L102

There is no AST inside the comment for a specific line. The AST will point to the start of the comment and the `TODO` could be 3 lines after that. Do we still want to print a violation on the AST?

**Comment by rnveach** [comment]
28 checks fit into the easy category where we just do `log(ast.getLineNo(), MSG_`....

**Comment by romani** [comment]
>How do we want to report handling a violation on a comment's specific line number?

I do not know for now. It is better to postpone comment related Checks to most end of this project.

>Do we still want to print a violation on the AST?

I would not doing this for now. Violation on AST will help extensions to do autofixes. Comment related violation is still unclear area. Let's postpone such Checks.

>Also how do we want to handle checks that don't even use the AST? I

No AST no Xpath. They should continue to use any other way of suppression.

**Comment by rnveach** [comment]
> do you remember in what issue I rejected such proposal?

https://github.com/checkstyle/checkstyle/issues/2116 . Different check then mentioned here, but still same issue.

**Comment by romani** [comment]
conversion to FileSet is kind of reasonable but should be done with special attention and separately from Xpath project.

**Comment by rnveach** [comment]
PR is abandoned but anyone can take the code and finish it.

What still needs to be done is we need a bunch of regression tests to show that xpath suppression works before we merge these changes. These tests will be located at https://github.com/checkstyle/checkstyle/tree/master/src/it/java/org/checkstyle/suppressionxpathfilter. This is similar to Issue https://github.com/checkstyle/checkstyle/issues/6207 but we need regression for the checks specifically modified in this issue.

**Comment by rnveach** [comment]
This issue is being closed as it was split into its children
