### ISSUE TITLE
java.g has GPL license instead of LGPL

### ISSUE THREAD

**Issue by ychulovskyy** [checkstyle/checkstyle#579]
Nexus professional analyzes all sources files and licenses inside artifacts.
As a result it shows:
Declared License(s): LGPL-2.1
Observed License(s) in Source: BSD-3-Clause, GPL-2.0+, LGPL-2.1+, Public Domain
Threat Level: GPL-2.0+

GPL is not commercial friendly, that is why we cannot use Checkstyle 5.7 and above in our company (which makes is useless since Checkstyle 5.6 doesn't support Java 8)

I've found only one file that has GPL license: java.g
Is it possible to change java.g lincense from GPL to LGPL?
If it is, when can we expect new release?

**Comment by romani** [comment]
I will change licence to LGPL, that is mistake.
If that possible please point me to other files that have other licence then LGPL , you reference - BSD-3-Clause, GPL-2.0+, LGPL-2.1+, Public Domain.

You can use checkstyle internaly for free, but you can not embed it in your application till I do changes to license :( .

**Comment by romani** [comment]
That file is hanged in history, https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/com/puppycrawl/tools/checkstyle/grammars/java.g it still ref to 2007 year, Checkstyle is switched to LGPL at Release 2.0 , see http://checkstyle.sourceforge.net/releasenotes.html.

**Comment by romani** [comment]
GPL was removed - https://github.com/checkstyle/checkstyle/commit/496b4429e450081f77929de1e193a090e3170141

I not sure that you need release urgently, next release will be at the end of January.

**Comment by ychulovskyy** [comment]
@romani Thanks a lot for quick response!
Release date is not critical, just need to wait on it before I can introduce Checkstyle into my project (I know I can use it if I don't embed it, but it requires a lot of approvals from managers).

I'm not sure how Nexus Profesisonal searches for licenses.
IMHO, it searches for key phrases in all files.
E.g. "Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer" is part of BSD 3-Clause License and it's present in many files in, e.g. in LabelDef.java (which is not an issue for us, because this license if commercial friendly).
