### ISSUE TITLE
format all files to be 100 symbols in length

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#5791]
to ease code review in github , it is better to format all files (where possible) to make line 100 maximum.

after completion, it should be enforced by some Check.

Case: I almost missed undesirable changes - https://github.com/checkstyle/checkstyle/pull/5753#discussion_r187773023

**Comment by romani** [comment]
interesting , but have no Check for general files to restrict line length to certain size.
http://checkstyle.sourceforge.net/config_sizes.html#LineLength - is Treewalker check (java parsing related)

**Comment by rnveach** [comment]
@romani You must use the regular expression one.

**Comment by romani** [comment]
Fortunately our code doesn't use tabs, so inplementation of line length will be reliable by `^.{101,}$` , I will try to enforce current state of code in as is state to improve continuously.

**Comment by romani** [comment]
attention to changes like:
```
-    <suppress checks="ExecutableStatementCount|JavaNCSS|BooleanExpressionComplexity|NestedIfDepth|MethodLength"
+    <suppress checks="ExecutableStatementCount|JavaNCSS|BooleanExpressionComplexity|
+                      |NestedIfDepth|MethodLength"
```

This is not simply wrapping by "\n", extra "|" is required before at the end of line to make regexp option finish before "\n" and match successfully to file. Such update is identical to extension of regexp by new match group `\n              `, fortunately there will no files with such name, so it will never match.

**Comment by romani** [comment]
multiline in Idea inspections is treaky, and hacked by extra(leading and trailing) `,` and trailing `, ,` :
```
    <inspection_tool class="AutoCloseableResource" enabled="true" level="ERROR"
                     enabled_by_default="true">
        <!-- These classes do not contain any resources that need to be closed. -->
        <option name="ignoredTypes"
                value="java.io.ByteArrayOutputStream,
        ,java.util.stream.Stream,
        ,java.util.stream.IntStream,
        ,java.util.stream.LongStream,
        ,java.util.stream.DoubleStream,
        ,com.puppycrawl.tools.checkstyle.internal.utils.CloseAndFlushTestByteArrayOutputStream"/>
        <!-- False positives for the Closable returned from a builder method (which return "this").
             Mock stubs shouldn't be closed. -->
        <option name="METHOD_MATCHER_CONFIG"
                value="java.util.Formatter,format, ,
                        ,java.io.Writer,append, ,
                        ,com.google.common.base.Preconditions,checkNotNull, ,
                        ,org.hibernate.Session,close, ,
                        ,java.io.PrintWriter,printf, ,
                        ,org.mockito.Mockito,mock|verify, ,
                        ,org.mockito.stubbing.Stubber,when"/>
```

it will looks a bit weird in UI:
![image](https://user-images.githubusercontent.com/812984/40262477-86244da2-5abc-11e8-9320-1c710120a82d.png)

but it works

**Comment by romani** [comment]
Final fix is merged

**Comment by romani** [comment]
unfortunately resources are still files that we need to review, so scrolling is happening and it makes problems in review, here is list violations in resources - https://gist.github.com/romani/606efd5dc4025860b59948667298e565
bunch of cases will be suppressed (LineLength, Indentation, ..... where long lines is special case), but not all files should be suppressed.

**Comment by romani** [comment]
final fix is merged.
Now code review will be much easier from phone from from web, no scrolling is expected that could hide details.
