### ISSUE TITLE
Rename all utility classes to xxxxUtil

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#5812]
From https://github.com/checkstyle/checkstyle/issues/5790

The utility class names in CS are inconsistent: 
-  `AnnotationUtility`
-  `TestUtil`, `XdocUtil`, `XmlUtil`, `XpathUtil`
-  `CheckUtils`, `CommonUtils`, `FilterUtils`, `JavadocUtils`, `ScopeUtils`, `TokenUtils`

All of them should have the suffix `Util`.

**Comment by romani** [comment]
@pbludov , do you plan to change names of packages ?

**Comment by pbludov** [comment]
> do you plan to change names of packages

you mean in this issue or in a new one?

**Comment by romani** [comment]
yes, it is better to do this in new issue, title of this issue is exact.

**Comment by rnveach** [comment]
@romani @pbludov Is someone going to start the new issue?

**Comment by romani** [comment]
New issues are created #5890 , #5891
