### ISSUE TITLE
Can't generate xpath for package's dot

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#5821]
````
$ cat TestClass.java
//0
package//1
com//2
.//3
puppycrawl//4
.//5
tools//6
.//7
checkstyle//8
.//9
astprinter//10
//11
//12
;//13

$ java -jar checkstyle-8.10-all.jar -s 8:1 TestClass.java
````

Detected:
The CLI did not generate any xpath for me, so there is literally no xpath I can give you. The CLI should have generated something for me, but it did not.

AST:
````
$ java -jar checkstyle-8.10-all.jar -J TestClass.java
SINGLE_LINE_COMMENT -> // [1:0]
`--COMMENT_CONTENT -> 0\n [1:2]
PACKAGE_DEF -> package [2:0]
|--ANNOTATIONS -> ANNOTATIONS [10:0]
|--SINGLE_LINE_COMMENT -> // [9:10]
|  `--COMMENT_CONTENT -> 8\n [9:12]
|--DOT -> . [10:0]
|  |--SINGLE_LINE_COMMENT -> // [7:5]
|  |  `--COMMENT_CONTENT -> 6\n [7:7]
|  |--DOT -> . [8:0]
|  |  |--SINGLE_LINE_COMMENT -> // [5:10]
|  |  |  `--COMMENT_CONTENT -> 4\n [5:12]
|  |  |--DOT -> . [6:0]
|  |  |  |--SINGLE_LINE_COMMENT -> // [3:3]
|  |  |  |  `--COMMENT_CONTENT -> 2\n [3:5]
|  |  |  |--DOT -> . [4:0]
|  |  |  |  |--SINGLE_LINE_COMMENT -> // [2:7]
|  |  |  |  |  `--COMMENT_CONTENT -> 1\n [2:9]
|  |  |  |  |--IDENT -> com [3:0]
|  |  |  |  |--SINGLE_LINE_COMMENT -> // [4:1]
|  |  |  |  |  `--COMMENT_CONTENT -> 3\n [4:3]
|  |  |  |  `--IDENT -> puppycrawl [5:0]
|  |  |  |--SINGLE_LINE_COMMENT -> // [6:1]
|  |  |  |  `--COMMENT_CONTENT -> 5\n [6:3]
|  |  |  `--IDENT -> tools [7:0]
|  |  |--SINGLE_LINE_COMMENT -> // [8:1]
|  |  |  `--COMMENT_CONTENT -> 7\n [8:3]
|  |  `--IDENT -> checkstyle [9:0]
|  |--SINGLE_LINE_COMMENT -> // [10:1]
|  |  `--COMMENT_CONTENT -> 9\n [10:3]
|  `--IDENT -> astprinter [11:0]
|--SINGLE_LINE_COMMENT -> // [11:10]
|  `--COMMENT_CONTENT -> 10\n [11:12]
|--SINGLE_LINE_COMMENT -> // [12:0]
|  `--COMMENT_CONTENT -> 11\n [12:2]
|--SINGLE_LINE_COMMENT -> // [13:0]
|  `--COMMENT_CONTENT -> 12\n [13:2]
|--SEMI -> ; [14:0]
`--SINGLE_LINE_COMMENT -> // [14:1]
    `--COMMENT_CONTENT -> 13 [14:3]
````

Suppressions were generated and worked for 2:1 and 10:1. I'm not sure what makes 8:1 special since 10:1 has the same token type.

Issue also happens for the DOT in `this.<@Ann@Ann2 Integer> getXAs();`

-------

<a href="https://www.bountysource.com/issues/58564470-can-t-generate-xpath-for-package-s-dot">
<img src="https://api.bountysource.com/badge/issue?issue_id=58564470">
</a>

**Comment by romani** [comment]
please share generated results and exact xpath.

**Comment by rnveach** [comment]
> please share generated results and exact xpath.

@romani Please clarify what you mean by generated results and exact xpath?
This problem is actually in generating an xpath from the CLI, hence the use of the arguments `-s 8:1`.

The CLI did not generate any xpath for me, so there is literally no xpath I can give you.

**Comment by romani** [comment]
Please share command for AST print, we always try to keep issues in for easy to reproduce even for new person in project.

**Comment by rnveach** [comment]
Done.

**Comment by rnveach** [comment]
Problem is in `XpathQueryGenerator.getMatchingAstElements`.
https://github.com/checkstyle/checkstyle/blob/6893affeac7285afd16f8a389c7d65023d0c327a/src/main/java/com/puppycrawl/tools/checkstyle/xpath/XpathQueryGenerator.java#L151
When looking for ASTs, we stop looking when we have passed the line number we are looking for. Unfortunately, we produce ASTs not in the same order as the source. It is possible for ASTs to be out of order.
Example:
````
PACKAGE_DEF -> package [2:0]
|--ANNOTATIONS -> ANNOTATIONS [10:0]
|--SINGLE_LINE_COMMENT -> // [9:10]
````
So this issue is present for any tokens where order between source and tree is different. This will be an issue for our Java trees, until we switch to ANTLR4 which will force us to have trees in source order.

**Comment by romani** [comment]
as generator is our code , can we do hack/workaround ?

**Comment by rnveach** [comment]
We can remove `curNode.getLineNo() <= lineNumber` but this will cause us to scan the entire tree even if to a human it is obvious we couldn't find the node and are way past the line number for it.

**Comment by romani** [comment]
single tree scan is instant in CLI, user will not notice it.

**Comment by HuGanghui** [comment]
@rnveach 

cat Test.java

```java
//0
package//1
com//2
.//3
puppycrawl//4
.//5
tools//6
.//7
checkstyle//8
.//9
astprinter//10
//11
//12
;//13
```

```
 java $RUN_LOCALE -jar /Users/hgh/Desktop/checkstyle/target/checkstyle-8.36-SNAPSHOT-all.jar -s 8:1 Test.java

```

**Comment by HuGanghui** [comment]
current master's 

https://github.com/checkstyle/checkstyle/blob/6f58247b85ff4d74eb22dbd8c51d72b69fe51839/src/main/java/com/puppycrawl/tools/checkstyle/xpath/XpathQueryGenerator.java#L233-L249

**Comment by rnveach** [comment]
`isMatchingByLineAndColumnAndTokenType` has no less/greater than anymore and https://github.com/rnveach/checkstyle/tree/issue_5648 says it passes so I am closing this.

@romani ping on bounty

**Comment by romani** [comment]
@HuGanghui, please request bounty of this issue. You helped to close it, you deserve it.
