### ISSUE TITLE
custom checkstyle how to work in gradle?

### ISSUE THREAD

**Issue by beyondckw** [checkstyle/checkstyle#5828]
when i run my custom checkstyle in gradle , that it meet an error like "Unable to create a Checker: cannot initialize module TreeWalker - Unable to instantiate com.xx.ProhibitExtendCheck", what i should do ? thx for your help.

<module name="com.xx.ProhibitExtendCheck">

**Comment by romani** [comment]
we accept issue only that follow issue template.
you have general problem, please open topic in mail-list with all details or do stackoverflow post.
look at https://github.com/sevntu-checkstyle/checkstyle-samples meanwhile and try find problem yourself in your config.
