### ISSUE TITLE
PackageDeclarationCheck.finishTree throws NPE

### ISSUE THREAD

**Issue by felixpageau** [checkstyle/checkstyle#583]
When I run checkstyle-6.1.1 against my codebase, I get a NPE in checkstyle:

    [error] java.lang.NullPointerException
    [error] 	at com.puppycrawl.tools.checkstyle.checks.coding.PackageDeclarationCheck.finishTree(PackageDeclarationCheck.java:73)
    [error] 	at com.puppycrawl.tools.checkstyle.TreeWalker.notifyEnd(TreeWalker.java:420)
    [error] 	at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:376)
    [error] 	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:207)
    [error] 	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:73)
    [error] 	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:263)
    [error] 	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:129)

By digging in the source code, it seems to be caused by the PackageDeclarationCheck.finishTree() using the input parameter without checking that it isn't null. 

See: https://github.com/checkstyle/checkstyle/blob/501b7c5240705c6db756608618fdcf58189e807e/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/PackageDeclarationCheck.java#L60

**Comment by romani** [comment]
please recheck on version 6.2, and provide config + input file

**Comment by felixpageau** [comment]
I did test with both 6.2 and the yet unreleased 6.3. Both fail in the exact same way as 6.1 did. 

After removing out the 'PackageDeclaration' module from my config, I got checkstyle to run just fine on my codebase.

I'll just submit a patch to add a null check on line 60 of PackageDeclarationCheck

**Comment by romani** [comment]
@felixpageau , you need to submit input file and configuration first .
Without that do not expect I will apply your patch.

**Comment by felixpageau** [comment]
Sadly, this a corporate project that I am not allowed to post onkine. Let me check if I can create something similar to reproduce the issue...

**Comment by romani** [comment]
please obfuscate code and minimize it to be able to share, we do not need exactly the same code, we need smth to reproduce problem from command line - http://checkstyle.sourceforge.net/cmdline.html.

**Comment by romani** [comment]
I think you can use http://javascriptobfuscator.com/ to quickly obfuscate your file. 

> PackageDeclarationCheck.java:73

smth weird in your stacktrace, as there is no line 73 in that file. I just can not see how it fail with NPE , the only chance is when "ast" argument in null, but that is weird.

**Comment by romani** [comment]
@felixpageau , any chance to get chunk of code from you ?

**Comment by romani** [comment]
@felixpageau , any chance to get chunk of code from you ? (if not possible, I will close issue in a week)
