### ISSUE TITLE
Code samples for Naming Checks

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#5832]
update xdoc files with code examples for all checks at http://checkstyle.sourceforge.net/config_naming.html
sources are at https://github.com/checkstyle/checkstyle/blob/master/src/xdocs/config_naming.xml

Good example is http://checkstyle.sourceforge.net/config_annotation.html#AnnotationLocation
sources are at https://github.com/checkstyle/checkstyle/blob/master/src/xdocs/config_annotation.xml

**Comment by jack870131** [comment]
I am on it.

**Comment by jack870131** [comment]
Copy that. Just give me some time to work on it. Thanks for your explaination.

**Comment by romani** [comment]
if you run onto problems , lets us know here (do not hesitate, even problems are super stupid/simple), we will guide and help with development process.
Review our help pages - http://checkstyle.sourceforge.net/beginning_development.html  ,  review whole section "Developers" at our web site.

**Comment by jack870131** [comment]
@romani Sorry for such a delay. I spend some time on school research. I will start it in these days. Thanks for your instructions.

**Comment by rnveach** [comment]
We still have 1 open PR. Do we have any checks that need updating or will that last PR be the end of the issue?

**Comment by jack870131** [comment]
@rnveach I could still helping on improving the documentation (this issue). Or if you wanna to close this issue, please let me know.

**Comment by romani** [comment]
@jack870131 , ping.
It would be awesome if you can finish this issue, you already have knowledge on how to do this, just extra effort is required to finish task.

**Comment by romani** [comment]
@jack870131 , please help us to finish this issue.

**Comment by jack870131** [comment]
I will try my best. I got a little bit stuck on the coding issues these days. Please give me some time. Thx.

**Comment by rnveach** [comment]
I am seeing the following not done in this issue:
TypeName, StaticVariableName, ParameterName, LambdaParameterName

**Comment by 0blivious** [comment]
Hi may I know if this issue is still on hold? If not, can I work on this?

**Comment by romani** [comment]
It is not on hold, @jack870131 did some updates but he doesn't have to continue. Please be welcome to send Pull Requests.

**Comment by rnveach** [comment]
https://github.com/checkstyle/checkstyle/issues/5832#issuecomment-527400145
3 are left.

**Comment by rnveach** [comment]
@romani Does this complete the issue?

**Comment by romani** [comment]
AbbreviationAsWordInName, MethodName needs example for default.

AbstractClassName , CatchParameterName , ClassTypeParameterName, ConstantName,
InterfaceTypeParameterName
 needs default config plus example for it.

**Comment by romani** [comment]
> AbstractClassName , CatchParameterName , ClassTypeParameterName, ConstantName,
InterfaceTypeParameterName
needs default config plus example for it.

we moved to separate issues

**Comment by romani** [comment]
> AbbreviationAsWordInName, MethodName needs example for default.

moved to separate issues.


This issue is closed.
