### ISSUE TITLE
AnnotationLocationcheck parameter "setAllowSamelineParametrizedAnnotation" is a typo

### ISSUE THREAD

**Issue by hgschmie** [checkstyle/checkstyle#585]
That should be `setAllowSamelineParameterizedAnnotation` (missing 'e').

**Comment by romani** [comment]
all sources(javadoc), xdocs, configs should be changed.

**Comment by romani** [comment]
will be in 6.3

**Comment by lkoe** [comment]
The fix is not quite complete, the member variable is changed alright - but the corresponding setter is not.
This means configurations will still need to use the old, wrong property name - contradicting the current docs for Checkstyle 6.3.

**Comment by alexkravin** [comment]
completed the fix.

**Comment by romani** [comment]
will be in 6.4
