### ISSUE TITLE
ClassMemberImpliedModifier: New Check to demand all modifiers to be explicit in class members

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#5885]
in addition to #5899 , discussed at #5783, thanks a lot @jodastephen for idea and help in discussion and @rnveach  for corrections.

`violateImpliedStaticOnNestedInterface` - nested interfaces should be marked with static modifier
`violateImpliedStaticOnNestedEnum` - nested enum should be marked as static.

Given this class, static is implied and redundant (as per JLS):
```
public class Foo {
    public static enum Light { RED, YELLOW, GREEN };
    public static interface Marker {};
}
```

@jodastephen coding standards do not require static in the code above (ie. for nested types) but it is perfectly possible that someone else might have coding standards that do.

```
<module name="ClassMemberImpliedModifier">
  <property name="violateImpliedStaticOnNestedInterface" value="true"/>     <!-- requires static -->
  <property name="violateImpliedStaticOnNestedEnum" value="true"/>    <!-- demands static -->
</module>
```

**Comment by romani** [comment]
should it be `ClassMemberExplicitModifier` ?

@rnveach , please do final review of design .

**Comment by rnveach** [comment]
I have similar questions here for `Kind` and similar questions on property names.

> requireMethodKindWhenFinal - when class is final, all methods should be final too.

Does this include implied `final` like enumerations, that can't be extended but can have abstract or overridden methods?

**Comment by romani** [comment]
>Does this include implied final like enumerations, that can't be extended but can have abstract or overridden methods?

Please rephrase to let me clearly understand what you mean.

**Comment by rnveach** [comment]
````
public enum MyEnum {
  MY_VALUE;
  public void myMethod() {}
}
````

If I turn `requireMethodKindWhenFinal` on and only that, will there be a violation on `myMethod`?
According to JLS, a class is a class or enum, and enum is implied to be final.

**Comment by romani** [comment]
I didn't mean this Check to be executed on enums. Only on `class`.

**Comment by romani** [comment]
this is really good point, Check that have "explicit" in name should be explicit in his properties :) .

```
<module name="ClassExplicitModifier">
  <property name="requireMethodFinalWhenClassFinal" value="true"/> <!-- demands final -->
  <property name="requireNestedInterfaceStatic" value="true"/> <!-- demands static -->
  <property name="requireNestedEnumStatic" value="true"/>      <!-- demands static -->
</module>
```

**Comment by rnveach** [comment]
I question if name should be `InterfaceStatic` or `StaticInterface` (same with enum), but other then that, property names look good to me.
@romani Please finalize and update first description.

**Comment by romani** [comment]
Options: 
`requireStaticNestedInterface` 
`requireNestedInterfaceBeStatic`  - looks like a bit longer but more clear.

**Comment by rnveach** [comment]
@romani property names look good to me.

**Comment by rnveach** [comment]
I am fine with the change.

**Comment by romani** [comment]
Fix is merged
