### ISSUE TITLE
Change utils package to util

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#5890]
From https://github.com/checkstyle/checkstyle/issues/5790#issuecomment-388837593

There will be problem with xwiki, we not to provide them PR for migration.

**Comment by Gaurav-Punjabi** [comment]
From what I understand, we need to rename package `com.puppycrawl.tools.checkstyle.utils` to `com.puppycrawl.tools.checkstyle.util` and change the package name in all the classes it's being used. Correct?

**Comment by romani** [comment]
unfortunately I am changing my mind about packages.
I more leaning to concept that is described at https://softwareengineering.stackexchange.com/a/75929

>  Use the plural for packages with homogeneous contents and the singular for packages with heterogeneous contents.

As in `utils` package we store only Util classes - content is homogeneous - so plural form should be used.

------

![image](https://user-images.githubusercontent.com/812984/40002103-8dc83486-5744-11e8-81eb-7131243b34b1.png)

ant - package with whole set of classes to support ANT, it contains all classes for feature, heterogeneous content - singular.
api -  package with whole set of various classes - heterogeneous content - singular.
checks - 95% homogeneous content - only Checks
filefilters - homogeneous content - only file filters
filters - homogeneous content - only filters
grammars - homogeneous content - only grammar files
gui - it is feature - all classes for graphic user interface - heterogeneous content - singular.
utils - homogeneous content - only Util files
xpath - feature folder all to support xpath  - heterogeneous content - singular.

**Comment by Gaurav-Punjabi** [comment]
Okay 👍
