### ISSUE TITLE
Enforce usage of optional annotation attributes

### ISSUE THREAD

**Issue by picimako** [checkstyle/checkstyle#5892]
Let's say I have an annotation type with an optional attribute, e.g. named `Exclude` to mark a test class in a test automation framework to be excluded from the test run. It has a reason attribute in which you can specify why the class is excluded.
```java
public @interface Exclude {

    String reason() default "";
}
```
I would like to make sure that any time this annotation is used, the `reason` attribute is defined explicitly. (Without making the attribute mandatory.)

I didn't find a specific checkstyle rule for this and I couldn't find any alternate solutions via checkstyle. I'm happy to create a new check for this, I just wonder if currently there is a way to achieve this.

**Comment by rnveach** [comment]
There is the specific check in sevntu called `RequiredParameterForAnnotationCheck`. It will require the annotation to be written like `@Exclude(reason = "My reason.")`.

See https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/master/sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/annotation/RequiredParameterForAnnotationCheck.java

**Comment by romani** [comment]
>defined explicitly. (Without making the attribute mandatory.)

How it could be ?
I think explicit means mandatory here.

Please let us know if satisfied with sevntu Check.

**Comment by picimako** [comment]
@romani 
I meant that regardless of the attribute has that default value empty string, it would need to be set when the annotation is used, like the example given by @rnveach.

At first sight the sevntu check seems perfect, but I will get back to you once I had the chance to try it.

> We can use you offer to help with moving Check to main library.
Once I get more familiar with checkstyle internals, I'm ok with moving it.

**Comment by romani** [comment]
Just do not hesitate to ask questions, we have bunch of docs on how to start contributing

**Comment by romani** [comment]
I am closing issue for now, ones @picimako become ready for moving Check to main project, new issue should be created with exact tittle.
