### ISSUE TITLE
Remove lambda support from ParameterName

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#5894]
if #5893 (new Check - LambdaParameterName) is done.
We should remove lambda support from ParameterName to not let them overlap.
We have problems with support of lambda in ParameterName , see https://github.com/checkstyle/checkstyle/pull/5768#issuecomment-395269426 for more details.

There should be update in google style ITs.

**Comment by romani** [comment]
@rnveach , please review idea.

**Comment by rnveach** [comment]
XDox and Javadoc should be updated to clarify it won't support lambdas anymore.

@romani I believe this is a backward breaking change, right?

**Comment by romani** [comment]
> I believe this is a backward breaking change, right?

 this is hard case. Previously I classified only configuration problems (for plugins, ....) as breaking changes.
This issue is behavior breaking change a bit,I think we should mark it as bug.

**Comment by tsjensen** [comment]
> > I believe this is a backward breaking change, right?
> 
> this is hard case. Previously I classified only configuration problems (for plugins, ....) as breaking changes.
> This issue is behavior breaking change a bit,I think we should mark it as bug.

I classify changes as "breaking changes" if they:

- cause an existing config file to parse as invalid
- cause issues to be flagged for the same configuration and input code that were not flagged before (as this may fail builds, too)

So, from this definition, this would *not* be a breaking change (some flags would simply not appear anymore).

**Comment by romani** [comment]
>cause an existing config file to parse as invalid

We use only this point as bracking compatibility.

>cause issues to be flagged for the same configuration and input code that were not flagged before

Each of our release change behavior of Checks. It will be to much breaking releases, I do not want users to consider them as usual stuff.

**Comment by romani** [comment]
@kazachka , can you help us to resolve this issue ?

**Comment by rnveach** [comment]
Fix was merged
