### ISSUE TITLE
Verify all modules are listed in contribution no exception configurations

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#5897]
Identified at https://github.com/sevntu-checkstyle/sevntu.checkstyle/issues/691 ,

`checks-nonjavadoc-error.xml` and `checks-only-javadoc-error.xml` in contribution should be verified that they contain all modules for no exception testing. No exception testing in wercker will verify XML is defined correctly, but nothing is ensuring it is populated with all modules.

> we have missed one already - AnnotationOnSameLine , that was added at 8.2 version.

Code should be similar to what was added in sevntu.

**Comment by romani** [comment]
is we want to reuse the same shell script https://github.com/checkstyle/checkstyle/blob/master/.ci/travis/travis.sh#L148
we ca use http://checkstyle.sourceforge.net/apidocs/allclasses-frame.html

**Comment by rnveach** [comment]
The following checks are missing from non-exception configurations:
````
$ diff -u web.txt file.txt
--- web.txt	2019-03-10 11:18:51.970574847 -0400
+++ file.txt	2019-03-10 11:22:27.822574847 -0400
@@ -1,6 +1,7 @@
 AbbreviationAsWordInName
 AbstractClassName
 AnnotationLocation
+AnnotationOnSameLine
 AnnotationUseStyle
 AnonInnerLength
 ArrayTrailingComma
@@ -15,6 +16,7 @@
 CatchParameterName
 ClassDataAbstractionCoupling
 ClassFanOutComplexity
+ClassMemberImpliedModifier
 ClassTypeParameterName
 CommentsIndentation
 ConstantName
@@ -52,6 +54,7 @@
 IllegalToken
 IllegalTokenText
 IllegalType
+ImportControl
 ImportOrder
 Indentation
 InnerAssignment
@@ -59,9 +62,15 @@
 InterfaceIsType
 InterfaceMemberImpliedModifier
 InterfaceTypeParameterName
+JavadocMethod
+JavadocPackage
 JavadocParagraph
+JavadocStyle
 JavadocTagContinuationIndentation
+JavadocType
+JavadocVariable
 JavaNCSS
+LambdaParameterName
 LeftCurly
 LineLength
 LocalFinalVariableName
@@ -130,6 +139,7 @@
 SuperFinalize
 SuppressWarnings
 ThrowsCount
+TodoComment
 TrailingComment
 Translation
 TypecastParenPad
@@ -143,3 +153,4 @@
 VisibilityModifier
 WhitespaceAfter
 WhitespaceAround
+WriteTag
````

**Comment by romani** [comment]
Fix is merged
