### ISSUE TITLE
InterfaceMemberImpliedModifier: New Check to demand all modifiers to be explicit in interfaces members

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#5899]
original discussion at https://groups.google.com/forum/#!topic/checkstyle/KYF-9EEzsbs

related to #5756 , brain stormed at #5783 and #5884, thanks a lot @jodastephen for idea and and @rnveach for help in discussion.

In Java 8, developers are allowed to have static and default methods on interfaces. In Java 9, developers can write private methods on interfaces. As part of this change, my Java 8 [best practices talk](https://www.jfokus.se/jfokus17/preso/Java-SE-8-best-practices.pdf) slide 75 
![image](https://user-images.githubusercontent.com/812984/39844095-1f821504-53a3-11e8-9842-5b37f78c1997.png)

recommends that all methods on interfaces should be declared `public static`, `public abstract` or `public default` (plus `private` in Java 9). The goal of the check is to ensure consistency between classes and interfaces, so that developers reading code are not required to know that the implicit default scope differs between interfaces and classes.

```
public interface TestClass { 
  public static final int CONSTANT1 = 1;  // valid
  public static int CONSTANT2 = 1;  // invalid, final missing
  public final int CONSTANT3 = 1;  // invalid, static missing
  static final int CONSTANT4 = 1;  // invalid, public missing
  final int CONSTANT5 = 1;  // invalid, public & static missing
  static int CONSTANT6 = 1;  // invalid, public & final missing
  public int CONSTANT7 = 1;  // invalid, static & final missing
  int CONSTANT8 = 1;  // invalid, all missing

  public static boolean create1() { return true;}  // valid
  static boolean create2() { return true;}  // invalid, public missing

  public abstract void execute1();  // valid
  abstract void execute2();  // invalid, public missing
  public void execute3();  // invalid, abstract missing

  public default void execute4() {}  // valid
  default void execute5() {}  // invalid, public missing

  //private static void execute6() {}  // jdk9 only: valid
  //private default void execute7() {}  // jdk9 only: valid

}
```

Check should violate on all modifiers that aren't explicitly defined and are implied by the compiler. In this case, no visibility modifier is considered public. No abstract, static, or final in it's applicable locations are implied to be those. So we should define config and name as those that print violations on the implied modifiers that are not explicitly written out.

Design of Check:
```
<!-- specified values are proposed for defaults, looks like all should be true -->
<module name="InterfaceMemberImpliedModifier">
  <property name="violateImpliedPublicMethod" value="true"/>   <!-- demands public (or private)-->
  <property name="violateImpliedAbstractMethod" value="true"/>     <!-- requires abstract -->
  <property name="violateImpliedPublicField" value="true"/>    <!-- demands public -->
  <property name="violateImpliedStaticField" value="true"/>    <!-- demands static -->
  <property name="violateImpliedFinalField" value="true"/>      <!-- demands final -->
  <property name="violateImpliedStaticNested" value="true"/> <!-- demands static -->
<property name="violateImpliedPublicNested" value="true"/> <!-- demands public -->
</module>
```

Hard to find the following references to "redundant modifiers" in the JLS:

- fields on interfaces
- methods on interfaces
- nested types on interfaces (implicitly static)
- nested interfaces on classes (implicitly static)
- nested enums on classes (implicitly static)

Note that the interface itself can be declared as `abstract`, but that usage is considered obsolete (9.1.1.1). https://docs.oracle.com/javase/specs/jls/se8/html/jls-9.html

Quote from jls:
>9.1.1.1. abstract Interfaces
Every interface is implicitly abstract.
This modifier is obsolete and should not be used in new programs.

>The modifier static pertains only to member interfaces (§8.5.1, §9.5), not to top level interfaces (§7.6).

There seems to be two use case groups here - interfaces (fields and methods) and nested types. @jodastephen think it would be perfectly reasonable to require `static` for nested types (in the cases above), so its not all about interfaces.

Message will be `Implied {0} modifier should be explicit in code`. So each property will specify which modifier is put to violation message.

If user doesn't want to write that specific modifier, they can use any that meets their requirements and removes the implied one. `violateImpliedPublicMethod` can be written as public or private (if the JDK version they are working with allows private). Writing private on the method removes the implied public, so violation shouldn't appear anymore.

If new modifiers are allowed in the future, check won't need to change as implied should always be backward compatible. Only if they break compatibility would we need to consider the same or create a work around (most likely the latter).

**Comment by rnveach** [comment]
Translations are obtained from google as we have no one that knows the language.
You can run `mvn verify test` to see if you have passed all the basic validations needed for your change. Once that passes, you can start a PR and CI will tell you the complete picture of your work. We generally don't review a PR until CI passes unless you need help with something.

**Comment by romani** [comment]
fix is merged.
thanks a lot to @jodastephen for idea and for implementation.
