### ISSUE TITLE
ClassTypeParameterName for google

### ISSUE THREAD

**Issue by CySlider** [checkstyle/checkstyle#5940]
I am pretty sure that 
```
<module name="ClassTypeParameterName">
<property name="format" value="(^[A-Z][0-9]?)$|([A-Z][a-zA-Z0-9]*[T]$)"/>
...
```
mentioned [here](https://github.com/search?q=path%3Asrc%2Fmain%2Fresources+filename%3Agoogle_checks.xml+repo%3Acheckstyle%2Fcheckstyle+ClassTypeParameterName) most likely should be
```
<module name="ClassTypeParameterName">
<property name="format" value="^([A-Z][0-9]?|([A-Z][a-zA-Z0-9]*[T])$"/>
...
```

Else names like 892aZeT  would be valid.

And I think it's rather meant to be either 

- Single capital letter A-Z 
- Single capital letter followed by a single number T0, R4, ... 
- Single capital letter, anything goes middle ending with a Capital T:  Asdf88T, Zdfs22T ,...

**Comment by romani** [comment]
@CySlider , please report issue as specified in issue template, it help us a lot.

```
# master
$ echo "892aZeT" | grep -E "(^[A-Z][0-9]?)$|([A-Z][a-zA-Z0-9]*[T]$)"
892aZeT

# issue author
$ echo "892aZeT" | grep -E "^([A-Z][0-9]?|([A-Z][a-zA-Z0-9]*[T])$"
grep: Unmatched ( or \(

# probably it was mean:
$ echo "892aZeT" | grep -E "^([A-Z][0-9]?|[A-Z][a-zA-Z0-9]*[T])$"
✘-1

# i think we meat , but failed with proper bracing of groups
$ echo "892aZeT" | grep -E "(^[A-Z][0-9]?$)|(^[A-Z][a-zA-Z0-9]*[T]$)"
✘-1
```

**Comment by romani** [comment]
> Else names like 892aZeT would be valid.

If you follow our github issue template you would not open such issue, as your name is not correct and we can not create compilable file, we do not support non compilable files ([all limitations](http://checkstyle.sourceforge.net/writingchecks.html#Limitations)).
```
/var/tmp$ cat Test.java 
class Test <892aZeT> //warn
{

}

/var/tmp$ javac Test.java 
Test.java:1: error: <identifier> expected
class Test <892aZeT> //warn
            ^
Test.java:1: error: '{' expected
class Test <892aZeT> //warn
               ^
Test.java:1: error: illegal start of type
class Test <892aZeT> //warn
                   ^
Test.java:1: error: <identifier> expected
class Test <892aZeT> //warn
                    ^
Test.java:2: error: ';' expected
{
 ^
Test.java:4: error: reached end of file while parsing
}
 ^
6 errors

/var/tmp$ cat Test.java 
class Test <aZeT> //warn
{

}

/var/tmp$ javac Test.java 
/var/tmp$ 
```
