### ISSUE TITLE
refactoring: update Main.java to have system.exit be placed in one method 

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#596]
https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/Main.java

it has too much exit points from different methods, that is not good and hard to maintain, exceptions should be rethrown to top level and exit from application should be in one method.

**Comment by dbngshuroy** [comment]
Hi sir,
I want to start working in this issue.

**Comment by romani** [comment]
Ok, you got it.

**Comment by romani** [comment]
Issue is unassigned again, any contribution are welcome.

**Comment by damianszczepanik** [comment]
I will take it

**Comment by romani** [comment]
1)
>```
            processCommandLine(parseCli(args));
            parseResult = true;
```

this is algorithm of Chekcstyle CLI. what developer see there - checkstyle is just parse CLI and process them. that is all .

What actually Checkstyle CLI do:
1. parse CLI arguments
2. validate then, print a usage is smth is missed, return error is smth is missed in arguments
3. prepare objects that Checker need to run
4. run Checker
5. return exit code base on validation of Checker

that is what I expect to see at "main()" . Attention: from step "3" the re shoul be no reference to CLI arguments at all. Main.java is functional class and example of how to use Checkstyle in plugin/extension/.... .

2)
>```
        catch (final ParseException e) {
            System.err.println("Could not parse parameters: " + e.getMessage());
            e.printStackTrace();
        }
        catch (final Exception e) {
            System.err.println("Could not execute Checkstyle: " + e.getMessage());
            e.printStackTrace();
        }
```

I do not see a reason on this, as it is a CLI and stacktrace will be printed, println is also might now be useful as it duplicate content of exception message.

3) 
>```
System.exit(parseResult ? 0 : 1);
```

I do believe that we do not need boolean variable , and could use int variable as storage of exit-code.

4)
>  private static void processCommandLine(CommandLine line)

That method has to split into few methods as I described in "1)"

5)
> ```
        if (errorCounter != 0) {
            throw new CheckstyleException(String.format(
                    "Checkstyle ends with %d errors.", errorCounter));
        }
```

Does it make sense to return erroCounter to caller, and him decide how to report an error.

6)
> private static List<File> getFilesToProcess(String[] filesToProcess)

need to be moved after ctor. As distance between usage and declaration should be nimimal.
One day I will write an Check to enforce that .....

7)
>```
private static AuditListener createListener(
...

            default:
                throw new CheckstyleException("Invalid output format. Found '" + format
                        + "' but expected 'plain' or 'xml'.");

```

We have to validate a arguments before we start preparing objects for Checker to execute. Exception should be used only in code that do not expect other value. Validation code that should be created on level of CLI parsing, should expect incorrect values and process them without exceptions.

**Comment by rnveach** [comment]
@romani 's (3), I think it would be better if the application didn't call System.exit as this allows it to be chained and combined with other applications.
(2)'s catch clauses cause (5)'s exception to print the application usage because the exception skips over "parseResult = true". I feel if the checkstyle finds files to check, then no usage is needed as the application is probably being used correctly.

**Comment by romani** [comment]
@rnveach ,

> allows it to be chained and combined with other applications

Please extend that idea with examples and a bit more explanations. 
We did return code , some tool also use return code , for example "mvn compile" return error code if some compile problems found.

**Comment by rnveach** [comment]
The simplest example would be to have one java program that called checkstyle's main twice with 2 separate configurations/directories on each run. I noticed after the first checkstyle ran, the second one never fired off. This was because "System.exit" was stopping any further processing.
If checkstyle was ever put into the middle of a larger application, the "System.exit" would create problems with integration as checkstyle may want to terminate but the main application shouldn't terminate until it says so too.
At first I thought this would cause issues with incorporating checktyle with JUnit, but it seems JUnit can capture the "System.exit" and continue on.

If an exception occurs, why not just let the exception be thrown, otherwise let main exit normally without a "System.exit"?

**Comment by romani** [comment]
> The simplest example would be to have one java program that called checkstyle's main twice with 2 separate configurations/directories on each run

As you do integration by using  Main class from javacode - you do coding, so please use internals of Main class and do logic up to your requirements. Main class will be example how to run Checkstyle , but it will NEVER be designed to accommodate your described requirements.
You need to use Shell call from java if you still want to use Main for this task.

> If an exception occurs, why not just let the exception be thrown, otherwise let main exit normally without a "System.exit"?

if exception happen we will throw in up, and error code will be generated by jvm. I described that in my list changes that are still have to be done.

**Comment by romani** [comment]
@damianszczepanik , please let me know if plan to continue, last update in that class created serious regression that we need to fix in next release or even do hot-fix release. If you do not have time now please allow me to unassign it from you.

**Comment by damianszczepanik** [comment]
I won't be able to fix it soon so please reassign if this should be fixed shortly.

**Comment by romani** [comment]
refactoring is done, major tests are created.
