### ISSUE TITLE
Remove usages of ANTLRInputStream 

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#5971]
The class `org.antlr.v4.runtime.ANTLRInputStream` is [deprecated](http://www.antlr.org/api/Java/org/antlr/v4/runtime/ANTLRInputStream.html) and should be replaced with a call to `CharStreams.fromString`

There is only one usage of the class `ANTLRInputStream` in the project:
```
    private JavadocParser createJavadocParser(String blockComment) {
        final ANTLRInputStream input = new ANTLRInputStream(blockComment);
```
https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/JavadocDetailNodeParser.java#L171

**Comment by rnveach** [comment]
Fix was merged
