### ISSUE TITLE
SuppressWithNearbyCommentFilter: update document and examples on when it is appropriate to use

### ISSUE THREAD

**Issue by lukaseckert** [checkstyle/checkstyle#5973]
/var/tmp$ javac Test.java
```
(no output)
```
/var/tmp$ cat Test.java
```
class Test {

    private interface SomeRepository {
        void foo();
        void bar();
    }

    //@SuppressWarnings("checkstyle:checkfoobar")
    public void Test(SomeRepository repository) {
        // CSIGNORE: checkfoobar
        repository.foo();
        // CSIGNORE: checkfoobar
        repository.bar();
    }

}
```
/var/tmp$ cat config.xml
```
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
        "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="fileExtensions" value="java, properties, xml"/>
    <module name="SuppressWarningsFilter"/>

    <module name="RegexpSingleline">
        <property name="id" value="checkfoobar"/>
        <property name="format" value="repository\.bar\("/>
        <property name="fileExtensions" value="java"/>
        <property name="message" value="Forbidden use of repository.bar(). Use foo() instead!"/>
    </module>

    <module name="TreeWalker">
        <module name="SuppressWarnings"/>
        <module name="SuppressWarningsHolder"/>

        <module name="SuppressWithNearbyCommentFilter">
            <property name="commentFormat" value="CSIGNORE:\s(\w+)"/>
            <property name="checkFormat" value="$1"/>
            <property name="influenceFormat" value="1"/>
        </module>
    </module>

</module>
```
/var/tmp$ java -Duser.language=en -Duser.country=US -jar checkstyle-8.10.1-all.jar -c config.xml Test.java
```
Starting audit...
[ERROR] /var/tmp/Test.java:13: Forbidden use of repository.bar(). Use foo() instead! [checkfoobar]
Audit done.
Checkstyle ends with 1 errors.
```
---------------

**What I tried to do:**
I would like to suppress a custom RegexpSingleline-check for a specific line of code through use of the "SuppressWithNearbyCommentFilter" filter that listens on "CSIGNORE: ..." comments. After that failed, I tried to use the "systemout" example configuration [from the documentation](http://checkstyle.sourceforge.net/config_filters.html#SuppressWithNearbyCommentFilter) which showed the same issue.

**What I expected to happen:**
1) The custom regexp check with id "checkfoobar" should report a call to repository.bar() as error. 
2) Uncommenting the `@SuppressWarnings("checkfoobar")` annotation will suppress all "checkfoobar" checks
3) For the calls with a "CSIGNORE" comment in the previous line, the error should be suppressed.

**What happens actually:**
1) :white_check_mark: The custom check is working as expected, 
2) :white_check_mark: `@SuppressWarnings("checkfoobar")` will suppress the "checkfoobar" check
3)  :no_entry: "CSIGNORE: checkfoobar" comments have no effect. 

A test with the older Checkstyle versions 8.2 and 8.8 had the same issue.

**Additional information:**
- The official sample configs for SuppressWithNearbyCommentFilter  at http://checkstyle.sourceforge.net/config_filters.html#SuppressWithNearbyCommentFilter do not work as well (suppressed lines are reported as errors).
- The provided regex for "commentFormat" seems to be working properly (run here: https://regex101.com/r/BA9Y01/1/)
--------------

**Comment by rnveach** [comment]
This because we made `SuppressWithNearbyCommentFilter` a `TreeWalker` module, it can only suppress `TreeWalker` violations. `RegexpSingleline` isn't a `TreeWalker` module since it is directly in `Checker`.

To solve this issue we would need to make a `Checker` filter like `SuppressWithNearbyPlainTextCommentFilter`. Similar to https://github.com/checkstyle/checkstyle/issues/4841

**Comment by rnveach** [comment]
The following configuration solves the issue:
````
$ cat TestClass.java
public class TestClass {

    private interface SomeRepository {
        void foo();
        void bar();
    }

    //@SuppressWarnings("checkstyle:checkfoobar")
    public void Test(SomeRepository repository) {
        // CSIGNORE: checkfoobar
        repository.foo();
        // CSIGNORE: checkfoobar
        repository.bar();
    }
}

$ cat TestConfig.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
        "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="fileExtensions" value="java, properties, xml"/>
    <module name="SuppressWarningsFilter"/>

    <module name="RegexpSingleline">
        <property name="id" value="checkfoobar"/>
        <property name="format" value="repository\.bar\("/>
        <property name="fileExtensions" value="java"/>
        <property name="message" value="Forbidden use of repository.bar(). Use foo() instead!"/>
    </module>

        <module name="SuppressWithPlainTextCommentFilter">
            <property name="offCommentFormat" value="CSIGNORE:\s([\w\|]+)"/>
            <property name="onCommentFormat" value="CSIGNORE:\s([\w\|]+)"/>
            <property name="checkFormat" value="$1"/>
        </module>

    <module name="TreeWalker">
        <module name="SuppressWarnings"/>
        <module name="SuppressWarningsHolder"/>
    </module>

</module>

$ java -jar checkstyle-8.10.1-all.jar -c TestConfig.xml TestClass.java
Starting audit...
Audit done.
````

**Comment by romani** [comment]
I am closing this issue, if more questions or problems , please continue to post here, we can reopen it back

**Comment by lukaseckert** [comment]
@rnveach @romani Thank you for your tip, not as elegant as a 1-line comment but still a good plan B :)
I think it would be helpful to update the documentation at http://checkstyle.sourceforge.net/config_filters.html#SuppressWithNearbyCommentFilter 
- to include that information (NearbyCommentFilter only within TreeWalker module)
- to have a different example check (it is also using RegexpSingleline and this not working)

**Comment by rnveach** [comment]
> to include that information (NearbyCommentFilter only for checks that are also within TreeWalker module)

I agree.
We should double check it for both checks and reference the other if the user wants different type of suppression. We should also explain how to check if something is a `TreeWalker` check or not.

> to have a different example check (it is also using RegexpSingleline and this not working)

I do not see example of `RegexpSingleline` with `SuppressWithNearbyCommentFilter`. It has example of `RegexpSinglelineJava` but that is a different check.

**Comment by romani** [comment]
@lukaseckert , can you provide update to documentation ?
Documentation is located at:
https://github.com/checkstyle/checkstyle/blob/master/src/xdocs/config_filters.xml#L1102

Feedback from outside of maintainers is really helpful as we a bit blind on what is not very obvious.

**Comment by lukaseckert** [comment]
@romani I tried to create a pull request, the CI checks show some errors however I don't see a relation to the modified config_filter.xml file

**Comment by romani** [comment]
doc update is merged.
