### ISSUE TITLE
doc: reference in SuppressionXpathFilter doc about ability to generate suppressions by CLI

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#5980]
from https://github.com/checkstyle/checkstyle/pull/5883#pullrequestreview-132851407

> Should we update http://checkstyle.sourceforge.net/config_filters.html#SuppressionXpathFilter to tell users about this option to help them generate suppressions?

it is better to add to documentation of SuppressionXpathFilter that there is CLI helper tool. Most user do not use CLI at all, but I hope almost all will use this filter and read documentation of it multiple times.

**Comment by romani** [comment]
@timurt , can help us to resolve this issue ? it is leftover from your last PR (#5883).

**Comment by rnveach** [comment]
Issue was fixed and merged
