### ISSUE TITLE
XpathSuppression generation should support module id

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#5984]
[example](https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/google_checks.xml#L212):
```
        <module name="AnnotationLocation">
            <property name="id" value="AnnotationLocationMostCases"/>
            <property name="tokens"
             value="CLASS_DEF, INTERFACE_DEF, ENUM_DEF, METHOD_DEF, CTOR_DEF"/>
        </module>
```

generator use only names:
```
            final String checkName =
                    PackageObjectFactory.getShortFromFullModuleNames(event.getSourceName());
```
https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/XpathFileGeneratorAuditListener.java#L106

`getModuleId` - https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/AuditEvent.java#L132
`getSourceName` - https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/AuditEvent.java#L140

**Comment by romani** [comment]
@timurt , can help us to resolve this issue ? it is leftover from your last PR.

**Comment by rnveach** [comment]
fix was merged
