### ISSUE TITLE
Parse error on formal parameter named `this`, with a type annotation

### ISSUE THREAD

**Issue by mernst** [checkstyle/checkstyle#5989]
When Checkstyle 8.11 is run on [the following line](https://github.com/mernst/checker-framework/blob/checkstyle-ellipsis-this/checker/src/main/java/org/checkerframework/checker/regex/RegexUtil.java#L122):
```
public String getMessage(@GuardSatisfied CheckedPatternSyntaxException this) {
```

it fails, with the following output:

```
...
:checker:checkstyleMain
[ant:checkstyle] /home/mernst/tmp/checker-framework-checkstyle-ellipsis-this/checker/src/main/java/org/checkerframework/checker/regex/RegexUtil.java:122:80: expecting ELLIPSIS, found 'this'
:checker:checkstyleMain FAILED
...
```

To reproduce the problem, run the follownig commands:

```
git clone --branch checkstyle-ellipsis-this https://github.com/mernst/checker-framework.git checker-framework-checkstyle-ellipsis-this
cd checker-framework-checkstyle-ellipsis-this
./gradlew checkstyleMain
```

Here is [the checkstyle setup](https://github.com/typetools/checker-framework/compare/master...mernst:checkstyle-ellipsis-this).

This looks the same as one of the issues reported in https://github.com/checkstyle/checkstyle/issues/3033; perhaps that issue was closed without fully resolving the underlying issue.

I was able to reproduce this using Checkstyle 8.9, 8.10, and 8.11.  I did not try any other versions.

I was not able to easily create a minimal, standalone test case.  Sorry about that.

**Comment by romani** [comment]
That is why we DEMAND user to give us compilable code by javac.
```
$ cat Test.java 
class Test
{
  public void getMessage(int this) {}
}

$ javac Test.java 
Test.java:3: error: the receiver type does not match the enclosing class type
  public void getMessage(int this) {}
                         ^
  required: Test
  found: int
1 error
```

Your code is not compilable by standard javac. Most likely special code generation is used in checker-framework , sorry , we can not support this. 
List of all limitations: http://checkstyle.sourceforge.net/writingchecks.html#Limitations

We have similar problems with magic of lombok library.
You need to exclude such classes by filter http://checkstyle.sourceforge.net/config_filefilters.html#BeforeExecutionExclusionFileFilter

**Comment by mernst** [comment]
> Your code is not compilable by standard javac.

You pasted code different than in the project.  It's true that the code you pasted is erroneous, but that is irrelevant to the bug report.

The code in the project is compilable by standard javac.  I confirmed that before opening the issue.

The Java Language Specification explains why the change you made is illegal.

**Comment by romani** [comment]
Ok , let's focus on recreation of single Java file that is compilable by javac.
As you made it I reopen the issue.

**Comment by mernst** [comment]
As I mentioned before, I cannot reproduce this in isolation.
That possibly points at aonother bug in Checkstyle:  it produces different results when processing the file alone or in the midst of a build.

The below shows what I did to try to reproduce the problem.

Since Checkstyle is crashing on correct Java code, could you run Checkstyle with logging or in a debugger?  You can do this much more efficiently than I can.  Thanks.

```
# Create a new directory in which to do work.
rm -rf checkstyle-ellipsis-repro
mkdir checkstyle-ellipsis-repro
cd checkstyle-ellipsis-repro

# Download dependences
wget https://github.com/typetools/checker-framework/releases/download/checker-framework-2.5.2/checker-framework-2.5.2.zip checker-framework-2.5.2.zip
unzip checker-framework-2.5.2.zip
wget https://github.com/checkstyle/checkstyle/releases/download/checkstyle-8.11/checkstyle-8.11-all.jar
wget https://raw.githubusercontent.com/mernst/checker-framework/checkstyle-ellipsis-this/checker/src/main/java/org/checkerframework/checker/regex/RegexUtil.java
wget https://raw.githubusercontent.com/mernst/checker-framework/checkstyle-ellipsis-this/checkstyle.xml

# The code compiles
javac -cp checker-framework-2.5.2/checker/dist/checker.jar RegexUtil.java

# Checking the RegexUtil.java file in isolation does not reproduce the problem;
# it issues no warnings.
RUN_LOCALE="-Duser.language=en -Duser.country=US"
java $RUN_LOCALE -cp checker-framework-2.5.2/checker/dist/checker.jar -jar checkstyle-8.11-all.jar -c checkstyle.xml RegexUtil.java

# Using the Google style rules issues complaints about indentation, so
# Checkstyle is performing checks.
wget https://raw.githubusercontent.com/checkstyle/checkstyle/master/src/main/resources/google_checks.xml
java $RUN_LOCALE -cp checker-framework-2.5.2/checker/dist/checker.jar -jar checkstyle-8.11-all.jar -c google_checks.xml RegexUtil.java
```

**Comment by romani** [comment]
I appreciate your desire to find a reason.
Keep going.

But, we need to reproduce problem on file, which is compiled by `javac` without class path. Checkstyle is library that use files as text to parse and process them, without any knowledge of other files or libraries or .... .

**Comment by mernst** [comment]
> > Since Checkstyle is crashing on correct Java code, could you run Checkstyle with logging or in a debugger?
> 
> It is not correct as you can not prove it.

I showed a `javac` invocation that passes.  What more do you want?  Please give the exact "proof" that you need.

> I see syntax problem, javac see it also.

What syntax problem do you and javac see?  Please be specific and concrete, because vague statements (or incorrect ones, like when you claimed that my original code was incorrect Java) do not help us diagnose the problem.

**Comment by romani** [comment]
> we need to reproduce problem on file, which is compiled by javac without class path.

if this is can not be satisfied. It mean that checkstyle does not support it by design. Sorry.

**Comment by mernst** [comment]
I have given my try at reproducing.  I'll let you take your try now.

**Comment by rnveach** [comment]
> When Checkstyle 8.11 
> RegexUtil.java:122:80: expecting ELLIPSIS, found 'this'

I am not able to reproduce the problem.

````
$ cat TestClass.java
import java.lang.annotation.Documented;
import java.lang.annotation.ElementType;
import java.lang.annotation.Target;
import java.text.ParseException;

public class TestClass {
    public static class CheckedPatternSyntaxException extends Exception {
        private static final long serialVersionUID = 6266881831979001480L;
        private final ParseException pe;

        public CheckedPatternSyntaxException(ParseException pe) {
            this.pe = pe;
        }

        @Override
        public String getMessage(@Annotation CheckedPatternSyntaxException this) {
            return pe.getMessage();
        }
    }
}


@Documented
@Target(ElementType.TYPE_USE)
@interface Annotation {
}


$ cat TestConfig.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>

    <module name="TreeWalker">
<module name="MissingDeprecated"/>
    </module>
</module>

$ java -jar checkstyle-8.10.1-all.jar -c TestConfig.xml TestClass.java
Starting audit...
Audit done.
````

However, when I backtracked to older checkstyle versions the error does come up.

````
$ java -jar checkstyle-6.19-all.jar -c TestConfig.xml TestClass.java
Starting audit...
TestClass.java:16:76: expecting ELLIPSIS, found 'this'
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing TestClass.java
    at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:281)
    at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:196)
    at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:396)
    at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:330)
    at com.puppycrawl.tools.checkstyle.Main.main(Main.java:161)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: MismatchedTokenException occurred during the analysis of file TestClass.java.
    at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:193)
    at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:78)
    at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:301)
    at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:271)
    ... 4 more
Caused by: TestClass.java:18:9: expecting EOF, found '}'
    at antlr.Parser.match(Parser.java:211)
    at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.compilationUnit(GeneratedJavaRecognizer.java:211)
    at com.puppycrawl.tools.checkstyle.TreeWalker.parse(TreeWalker.java:440)
    at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:175)
    ... 7 more
Checkstyle ends with 1 errors.
````
6.19 has the error and 7.0 doesn't.
````
$ java -jar checkstyle-7.0-all.jar -c TestConfig.xml TestClass.java
Starting audit...
Audit done.
````

@mernst I am assuming your gradle config isn't using the latest checkstyle version.
I don't know gradle but looking at https://github.com/mernst/checker-framework/commit/43ce02b3ea35513658a63d302018bc62b3664924#diff-c197962302397baf3a4cc36463dce5eaR610 , you didn't define `toolVersion` for the subproject.
If this isn't a subproject, can you somehow confirm the checkstyle version actually being used? One way would be to use a module/property that didn't exist in the old versions.
