### ISSUE TITLE
Line numbers should start at 1

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#6000]
Similar to https://github.com/checkstyle/checkstyle/issues/4997 ,

https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocPackageCheck.java#L89
> CheckstyleBad.java:0: Missing package-info.java file

AST checks start at line 1. We should remove line 0 violations and make them start at 1.
If the violation, like the above, is on a missing file or the file as a whole, we should remove the line number completely and just print the file name.

Example: `CheckstyleBad.java: Missing package-info.java file`

**Comment by romani** [comment]
it is better to print violation on some AST node, `package` node is good candidate.

**Comment by rnveach** [comment]
@romani this is a file set check, there is no ast. Also even though violation is on file X, it's message is saying file Y is missing.

**Comment by li-boxuan** [comment]
Hi, I'd like to solve this issue. Before creating a pull request, can we confirm one thing: do we want to report 1 or just print the file name?

**Comment by rnveach** [comment]
Fix was merged
