### ISSUE TITLE
update documentation of SuppressionFilter with links to latest DTDs

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#6003]
http://checkstyle.sourceforge.net/config_filters.html#SuppressionFilter

By web documentation I failed to upgrade Hbase config to skip violation by message. It was forced me to look at our configs to find a solution for problems.

Problems:
no links to latest DTDs
Example should use latest DTD.
format first code block (example)
file http://checkstyle.sourceforge.net/files/suppressions_none.xml  use old DTD.

**Comment by rnveach** [comment]
fix was merged
