### ISSUE TITLE
Spell check failing to get words file

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#6046]
From https://travis-ci.org/checkstyle/checkstyle/jobs/406904395#L661

Problem to download file linux.words
Repository:https://rpmfind.net/linux/fedora/linux/development/rawhide/Everything/aarch64/os/Packages/w/

https://github.com/checkstyle/checkstyle/blob/master/.ci/test-spelling-unknown-words.sh#L17
There is no file words-3.0-28.fc28.noarch.rpm , there is 29th version of it

```
cpio: Malformed number 64'
_sys
cpio: Malformed number 4'
_syst
/usr/bin/unlzma: (stdin): File format not recognized
cpio: premature end of archive
```

**Comment by romani** [comment]
File should be https://rpmfind.net/linux/fedora/linux/development/rawhide/Everything/aarch64/os/Packages/w/words-3.0-29.fc29.noarch.rpm

**Comment by romani** [comment]
hot fix is mergedm but we need better fix to fail if file not found  ,and avoid hardcoded  version of file in script.

**Comment by pbludov** [comment]
Alternatives:
http://mirror.centos.org/centos/7/os/x86_64/Packages/words-3.0-22.el7.noarch.rpm 479983 words
[https://github.com/dwyl/english-words/blob/master/words.txt](https://raw.githubusercontent.com/dwyl/english-words/master/words.txt) 466544 words
https://packages.ubuntu.com/bionic/wamerican 99171 words
[https://github.com/radonlab/words-en-us/blob/master/words.txt](https://raw.githubusercontent.com/radonlab/words-en-us/master/words.txt) 99171 words
[https://extensions.libreoffice.org/extensions/english-dictionaries](https://extensions.libreoffice.org/extensions/english-dictionaries/2018-07.01/@@download/file/dict-en-20180701.oxt) 49271 words
[https://github.com/johnola/LinuxWords/blob/master/checkspell.txt](https://raw.githubusercontent.com/johnola/LinuxWords/master/checkspell.txt) 45402 words

**Comment by romani** [comment]
@pvludov , can stay on same file and just `curl | grep` file name before strait download ?

How much words in current file ?

**Comment by pbludov** [comment]
wget way:
```
wget --recursive --no-parent --no-directories --level 1 --accept "words-*.noarch.rpm" \
"https://rpmfind.net/linux/fedora/linux/development/rawhide/Everything/aarch64/os/Packages/w/" 
```

curl way:
```
URL_BASE="https://rpmfind.net/linux/fedora/linux/development/rawhide/Everything/aarch64/os/Packages/w/"
WORDS_FILE=`curl -s "${URL_BASE}" | grep -o "words-.*.noarch.rpm"`
curl "${URL_BASE}${WORDS_FILE}" -o words.rpm
```

Which one, wget or curl?

**Comment by pbludov** [comment]
>How much words in current file ?

479983, the same file as in the  CentOS distro.

**Comment by romani** [comment]
I vote for curl approach

**Comment by romani** [comment]
Switch to centos is hard question, I am not sure what is better. Fedora supposed to be more up to date

**Comment by romani** [comment]
Fix is merged
