### ISSUE TITLE
How to not check the javadoc of the constructor

### ISSUE THREAD

**Issue by GongZiZhang** [checkstyle/checkstyle#6049]
How to not check the javadoc of the constructor，I didn't find it on the document.

**Comment by rnveach** [comment]
@GongZiZhang We need more information. What check are you using and what are you trying to do with that check?

**Comment by GongZiZhang** [comment]
@rnveach Just don't want to check javadoc of the constructor

**Comment by GongZiZhang** [comment]
The rules I wrote：
  <module name="JavadocMethod">
            <property name="logLoadErrors" value="true"/>
            <property name="suppressLoadErrors" value="true"/>
			<property name="allowMissingPropertyJavadoc" value="true"/>
			<property name="minLineCount" value="1"/>
			<property name="allowedAnnotations" value="Override, Test"/>
        </module>

**Comment by rnveach** [comment]
@GongZiZhang Either turn on `allowMissingJavadoc` to ignore all missing javadocs or specify the list of tokens minus `CTOR_DEF` to skip over all constructors.

**Comment by GongZiZhang** [comment]
I get it  @rnveach
