### ISSUE TITLE
api changes: make methods as abstract in Check.java

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#605]
based on discussion at #342

https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/Check.java#L77
https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/Check.java#L90

should become abstract method to force Check clearly define how it should work, do not expect that user of Checkstyle clearly understand terms "token" that could be set in each Check.
Examples:
https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/google_checks.xml#L39
https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/google_checks.xml#L57
https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/google_checks.xml#L93
.....

update http://checkstyle.sourceforge.net/writingchecks.html to show in examples what methods should be overriden too.
##

**Comment by MEZk** [comment]
@romani 
Is is still actual?

**Comment by romani** [comment]
It should be done in 8.0 version , where we will brake backward compatibility by api. 7.x version is only for jdk8 update

**Comment by rnveach** [comment]
Methods in question reference `getAcceptableTokens` and `getRequiredTokens`.
Javadoc token methods in `AbstractJavadocCheck` should also mirror change in Check token methods.

**Comment by subkrish** [comment]
@romani @rnveach I think this issue should be closed as this file is no longer used and has been deprecated.

**Comment by romani** [comment]
@subkrish , we need to remove it completely from repo.

**Comment by romani** [comment]
Fix is merged

**Comment by liutikas** [comment]
Can you also please update http://checkstyle.sourceforge.net/writingchecks.html as now the example Check does not even compile?

**Comment by romani** [comment]
#4939
