### ISSUE TITLE
web site: extending user guides for newbies of Checkstyle

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#606]
1) http://checkstyle.sourceforge.net/extending.html
move to "Developers" group of pages, make it like:
Developers
    Extending Checkstyle
    Contributing
    Javadoc

1.1) remove "Project Page" link in "Developers" group

2)provide instructions on how to compile and run Uts in debug for Eclipse , Netbeans, IDEA

**Comment by romani** [comment]
for point "2" please review request from #27 it is the same issue

**Comment by romani** [comment]
@alexkravin, after complition please put a link https://groups.google.com/forum/#!topic/checkstyle-devel/lLMGpjBM6XE

**Comment by romani** [comment]
merged, will be online on 6.5 release

**Comment by romani** [comment]
@alexkravin , 
Withtout attaching  additonal fodler to Eclipse build path, Eclipse does not compile Checkstyle project 
![image](https://cloud.githubusercontent.com/assets/812984/6858616/a56d86d4-d3cd-11e4-9e43-de49ae387dd7.png)
I do not see that steps in your manuals .

please specify on a page what type of eclipse  to download J2EE or Standard ?
Standard does not have m2e plugin as far as I known, by default.

FYI (old but might be useful information): 
https://github.com/checkstyle/checkstyle/blob/master/README-Eclipse.txt

**Comment by MEZk** [comment]
@romani 
Eclipse IDE for Java Developers has Maven Integration. 
http://www.eclipse.org/downloads/packages/eclipse-ide-java-developers/marsr
I'll made some screenshots. Also before starting playing around with checkstyle ```mvn clean compile``` should be executed to generate antlr's resources.

**Comment by romani** [comment]
Please update instructions to mention how to install all required plugins and how to disable all warnings in generated/input folders.
Please follow instructions few times from scratch to make sure that nothing missed.

**Comment by romani** [comment]
merged.
