### ISSUE TITLE
using picocli as command line parser

### ISSUE THREAD

**Issue by remkop** [checkstyle/checkstyle#6068]
The checkstyle stand-alone tool currently uses Commons CLI to parse the command line.

Would there be any interest in migrating the CLI to [picocli](http://picocli.info)? This would give a number of advantages:

* more declarative (and less) code in `com.puppycrawl.tools.checkstyle.Main`
* usage help in [ANSI colors](https://picocli.info/#_ansi_colors_and_styles)
* opens the possibility to add a bash/zsh command line [autocompletion](https://picocli.info/autocomplete.html) script for `Main` in the distribution
* support for [@-files](https://picocli.info/#AtFiles) (argument files) for long command lines

See the [picocli github project](https://github.com/remkop/picocli) for more.

If there is interest I can supply a pull request.

**Comment by remkop** [comment]
@romani  Thanks for your reply. 

I started to write an article to give people hints on how to migrate from Commons CLI to picocli and I was hoping to use CheckStyle as an example. Article draft (work in progress) is here: https://github.com/remkop/picocli/wiki/Migrating-from-Commons-CLI-to-picocli 

(If you end up sticking with Commons CLI, that's fine, I will look elsewhere for a different example, no worries.)

Thanks for the initial positive response. The article may give you some idea, but understood you want to see the complete picture. I will provide a PR so you can judge with the full details.

**Comment by romani** [comment]
Apache cli comes from `commons-cli` dependency, so we are about to substitute dependency - this is good.

We need to take affect in our uber jar "xxxxx-all.jar".
Substation of dependency for maven artifact, need to be reviewed.


> I will provide a PR so you can judge with the full details.

If worst case, you will have good example to show users at article what to consider to stay on commons-cli .GitHub will preserve code in PR, even you eventually remove fork from us, so discussion and code will stay forever.
Thanks a lot.

**Comment by remkop** [comment]
I submitted an initial version in PR #6082 for you to take a look.

**Comment by remkop** [comment]
FYI, the usage help looks like this on Cygwin: https://ibb.co/j7wymU

**Comment by remkop** [comment]
As discussed, the following option names changed as part of this work:

* `-gxs` was replaced with `-g`
* `-tabWidth` was replaced with `--tabWidth`
* `-executeIgnoredModules` was replaced with `--executeIgnoredModules`

**Comment by romani** [comment]
@remkop , thanks a lot for your huge effort to make transition to more advanced CLI support.

This commit is good example on a transition.

Auto-completion is possible after extra steps with installed jar - https://picocli.info/autocomplete.html

**Comment by davidburstromspotify** [comment]
Please note that the argument to display the version changed from `-v` to `-V` which breaks backwards compatibility.

**Comment by remkop** [comment]
@davidburstromspotify Yes, correct. This was discussed and agreed upon. 

Do you mean it should be mentioned in the documentation more prominently? If so, which docs do you have in mind?

**Comment by tsjensen** [comment]
> we do not consider our CLI as api

Well, scripts are gonna break ...

**Comment by davidburstromspotify** [comment]
I noticed something broke in our scripts when fetching the latest from Homebrew, so I checked the [release notes](https://checkstyle.org/releasenotes.html#Release_8.15) and didn't see anything under "Breaking backward compatibility" (which makes sense as it's not considered API), so I went through the "Notes" and noticed the switch to picocli. That was the only thing indicating the cause of the problem, from the direction I came.

**Comment by romani** [comment]
@davidburstromspotify , please share how you use checkstyle CLI, we need to know how it used to be more accurate with changes, or even start to clarify it as API.

What was broken on your side ?

**Comment by davidburstromspotify** [comment]
In essence, we run a git hook that invokes Checkstyle on the Java files that are in the index. It first verifies that the currently installed version is an expected one (as specified through a constant). Then it runs `checkstyle -c some_config some_files -p some_properties`.
It was the version check that failed. The rest worked out of the box.

**Comment by rnveach** [comment]
> -executeIgnoredModules was replaced with --executeIgnoredModules

It seems if you forget the extra `-` and just do the old way of `-executeIgnoredModules`, picocli does not turn the option on or generate any error. It thinks you are doing the `-e` option and want exclude "xecuteIgnoredModules".

**Comment by remkop** [comment]
@rnveach That is correct. Picocli parses that as a POSIX-style [short option](https://picocli.info/#_short_options).
