### ISSUE TITLE
Performance issue with file.lastModified()

### ISSUE THREAD

**Issue by Bananeweizen** [checkstyle/checkstyle#6096]
Checkstyle checks the file time stamp to avoid checking an unmodified file again. At least on Windows, this can be quite costly. On a project with about 300.000 LOC Yourkit tells me that I spend almost a minute in File.lastModified().

This can be improved by not querying the timestamp as the first cancellation condition in the Checker at https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/Checker.java#L277, but only as late as possible. First we should check cancellation by name.

**Comment by rnveach** [comment]
@romani I am fine with this.

**Comment by romani** [comment]
issue is approved, it is reasonable to be lazy in calculations.

**Comment by romani** [comment]
fix is merged.
