### ISSUE TITLE
error during build with tools.jar

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#611]
investigate and fix:
```
[ERROR] Artifact: com.sun:tools:jar:1.7.0 has no file.
```

**Comment by alexkravin** [comment]
Maven site plugin calls maven-project-info-reports-plugin (version 2.7)
It has unresolved bug (first reference found in 2.5 version https://jira.codehaus.org/browse/MPIR-251 )
So, this problem cannot be resolved in scope of our project.

**Comment by romani** [comment]
please add comment to this bug with link to Travis logs where that error is shown and put steps to reproduce that problem on our sources (you already did that for other issue).
We need to show Maven Project Info Reports Plugin developers that problem is exists and bother us too, and here is a way to reproduce it easily.

**Comment by alexkravin** [comment]
Added comment to this issue: https://jira.codehaus.org/browse/MPIR-251 (the last one)

**Comment by romani** [comment]
https://jira.codehaus.org/browse/MPIR-251#comment-363023
