### ISSUE TITLE
new functionality for xpath query attribute @text to contain text of only current node

### ISSUE THREAD

**Issue by timurt** [checkstyle/checkstyle#6115]
This is requirement to be able to implement Xpath query for node with several IDENT child nodes
Closely related with https://github.com/checkstyle/checkstyle/issues/6240

@romani @rnveach 
[Previous discussion](https://github.com/checkstyle/checkstyle/issues/1340#issuecomment-420835444)

```
/var/tmp $ cat Main.java
#[[
public class Main {
	@lombok.Generated
	public void firstTest() 
	{
	}

	@abc.def.Generated
	public void secondTest() 
	{
	}

	@Generated
	public void thirdTest() 
	{
	}
}
]]
```

```
/var/tmp $ cat checks.xml
#[[
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>

    <module name="TreeWalker">
		<module name="LeftCurly"/>

		<module name="SuppressionXpathFilter">
	    	<property name="file" value="suppressions_xpath.xml"/>
	    </module>
    </module>
</module>
]]
```

```
/var/tmp $ cat suppressions_xpath.xml
#[[
<?xml version="1.0"?>

<!DOCTYPE suppressions PUBLIC
    "-//Puppy Crawl//DTD Suppressions Xpath Experimental 1.2//EN"
    "http://checkstyle.sourceforge.net/dtds/suppressions_1_2_xpath_experimental.dtd">

<suppressions>
	<suppress-xpath checks=".*" query="//*[MODIFIERS//*[@text = 'Generated']]/descendant-or-self::node()" />
</suppressions>
]]
```

```
/var/tmp $ java -jar checkstyle-8.13-SNAPSHOT-all.jar -c config.xml Main.java
#[[
Starting audit...
[ERROR] /var/tmp/Main.java:4:9: '{' at column 2 should be on the previous line. [LeftCurly]
Audit done.
Checkstyle ends with 1 errors.
]]
```

`//*[MODIFIERS//*[@text = 'Generated']]/descendant-or-self::node()` - 
query points to all AST nodes, those have child node with token type `MODIFIERS`  and this `MODIFIERS` node has any level child nodes with `@text='Generated'`. Annotation `@lombok.Generated` has `IDENT` with `Generated` value, but method was not suppressed as others.

We assumed that node can have only one `IDENT` child node (see [here](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/xpath/ElementNode.java#L261)), but below you can see example where `DOT` token has two `IDENT` direct child nodes. Current implementation takes first child node with token type `IDENT` for `@text` attribute. For example here `DOT` node will have `lombok` as `@text` attribute value.

```
    |--MODIFIERS -> MODIFIERS [2:1]
    |   |   |--ANNOTATION -> ANNOTATION [2:1]
    |   |   |   |--AT -> @ [2:1]
    |   |   |   `--DOT -> . [2:8]
    |   |   |       |--IDENT -> lombok [2:2]
    |   |   |       `--IDENT -> Generated [2:9]
    |   |   `--LITERAL_PUBLIC -> public [3:1]
    |   |--TYPE -> TYPE [3:8]
    |   |   `--LITERAL_VOID -> void [3:8]
    |   |--IDENT -> firstTest [3:13]
```

Suggestions made by @lars-sh:

> Adding XPath attribute @text to IDENT nodes as well, allowing us to traverse via IDENT nodes directly.

We can add new attribute to the `IDENT` tokens, for example `@value`.
`//ANNOTATION/DOT[@text = 'lombok']/IDENT[0]` -> `//ANNOTATION/DOT/IDENT[@value='lombok']`
`//ANNOTATION/DOT[@text = 'lombok']/IDENT[1]` -> `//ANNOTATION/DOT/IDENT[@value='Generated']`

> Joining strings to produce a more reliable @text attribute (that could even allow matching ANNOTATION[@text = '@lombok.Generated'] directly), though I'm not sure if it's truely possible to achieve this approach.

We can concat all `IDENT` child nodes texts into single text.
`//ANNOTATION/DOT[@text = 'lombok']` -> `//ANNOTATION/DOT[@text = 'lombok.Generated']`

What do you think?

**Comment by rnveach** [comment]
I think we should add support for both if they aren't difficult.

> `//ANNOTATION/DOT[@text = 'lombok.Generated']`

I think we should use something other then `@text` to signify full package names, but I don't know what.

On a separate note, since elements only have text if they have idents, does this mean numbers aren't supported?
Example:
````
    |      |--LITERAL_RETURN -> return [3:0]
    |      |  |--EXPR -> EXPR [3:7]
    |      |  |  `--NUM_INT -> 1 [3:7] <--- we don't support the text of `1` for xpath?
````

**Comment by timurt** [comment]
@rnveach 
> On a separate note, since elements only have text if they have idents, does this mean numbers aren't supported?

Yes, because `@text` addresses to variable/method/class name, not value. 
We could think about adding additional attribute to catch literal's value.

**Comment by rnveach** [comment]
Thanks for confirming, I moved it to a new issue to not bog this one down.

**Comment by timurt** [comment]
@romani @rnveach 
Can I start implementing?

**Comment by romani** [comment]
> We can add new attribute to the IDENT tokens, for example `@value`

yes, just we have to put whole AST content to Xpath model

>We can concat all IDENT child nodes texts into single text.

I am against this. it is better to not doing any virtual/aggregation values in xpath for now.

----


@timurt , you are always welcome with fix.

**Comment by lars-sh** [comment]
Is there any way I could help with this? Would like to start working on a Pull Request if ya like.

**Comment by rnveach** [comment]
@lars-sh Anyone is free to work on an approved issue, but if this is your first time contributing to checkstyle, xpath might not be the easiest area to begin with.

**Comment by lars-sh** [comment]
@rnveach Challenge accepted - as you noticed, Maven, Checkstyle and Git seem to be more complicated in this case. Sorry for the inconveniences.

The pull request #6165 is ready now (from my point of view). It allows to use the attribute "value" to handle the string value of any element.

**Comment by romani** [comment]
after discussion at https://github.com/checkstyle/checkstyle/pull/6161#discussion_r238072998 , we agreed to change meaning of `@text` , so all discussions of new attribute `@value` should be ignored.
