### ISSUE TITLE
problem with Uts on Windows

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#612]
I do, however, get 21 test failures, presumably due to the different line separator.
One example:
https://gist.github.com/lkoe/4483a546cdf6a07b5238

Build on windows should pass

**Comment by Mebibyte** [comment]
I also encountered these errors. I temporarily fixed it by removing the failing tests.

I am now unable to build the checkstyle-6.3-all.jar file. I only get the checkstyle-6.3.jar and checkstyle-6.3-tests.jar files. I am using the command from the .travis file:

mvn clean verify site -Dlinkcheck.skip=true

Should I be using a different command? Thanks!

**Comment by romani** [comment]
Mvn clean package -Passembly

**Comment by romani** [comment]
fixed. will be in 6.4.
