### ISSUE TITLE
Remove restriction of commit messages to be one line only

### ISSUE THREAD

**Issue by krichter722** [checkstyle/checkstyle#6120]
The restriction of commit messages to be on one line and only 200 characters long is overly restrictive and destroys information. If a message really contains too much information an edit can be requested before merging. Consider

```
minor: Remove restriction to build master only from .travis.yml

Checkstyle doesn't use a large number of branches besides master and the
complications for pull request authors to get their PR branches to build
on Travis CI is not worth saving a few builds.
```

in comparison to

```
minor: Remove restriction to build master only from .travis.yml
```

I could try to fit the message on one line, but you want to have the information provided. The `git` should be a source of information to answer all question in the form of "Why again did we do X?". [GNOME commit message rules](https://wiki.gnome.org/Git/CommitMessages) are worth taking a look. An there's a reason why a lot of projects wouldn't merge commit without a description. It's a way better source of information than a max. 2.5 times extension of the summary line.

**Comment by romani** [comment]
>and destroys information. 

It looks like this on first sight. But in reality and long run it is vise versa. You will never be able to put all details to commit message.

>If a message really contains too much information an edit can be requested before merging. 

And do even better , we demand no much details in commit, but demand reference to issue where you can provide a lot of details, picture, ....

>I could try to fit the message on one line, but you want to have the information provided

If you can not fit in brief message, it is going sign that you need issue, and put all details there.

>The git should be a source of information to answer all question in the form of "Why again did we do X?"

It is illusion. Why do you think people reference link to issues in relet notes, rather than link to commit.

>GNOME commit message rules

Ok, this project is probably older than me. In such huge organization it is had to change rules, so old rules are staying forever. If it works for them, it is good for them. But I  pretty sure they just can not easily to change this policy.

**Comment by romani** [comment]
more points:
- You will not be happy ones I demand to put all details to git message,  it is easier to update details in issue. Non of documentation/comment is complete or clear ... Git message in non modifiable, I do not want to keep it as set I stone.
- imagine if start to demand to put all details in message, just open any issue and you will see that it is reasonable to have all that details, but not as commit.
-  commit message reference to issue, issue reference to all PRs and maillist discussion and bunch of links , and .... . Ones smb want to get whole context of conversations it is there. Commit message will never be enough.
- It is not rare case when I updated issue description to put details of why it done like it is
- it is frequent case when I update issue far after fix is merged.

**Comment by romani** [comment]
@krichter722 , please share with me your contribution to checkstyle repo where you run into a problem and disagreement, .... To discuss this issue on certain/exact contribution attempt.

**Comment by rnveach** [comment]
@romani Commit message in first post is in reference to this PR
https://github.com/checkstyle/checkstyle/pull/6119

**Comment by romani** [comment]
@krichter722

Originally you wanted a comment like:
>Checkstyle doesn't use a large number of branches besides master and the
complications for pull request authors to get their PR branches to build
on Travis CI is not worth saving a few builds.

But more reasonable is:
>wants his own CI to run before giving it off to ours for the PR.
It's possible to use the PR checks of checkstyle/checkstyle, however that's less intuitive than it can be and contradicts the workflow of almost any other github.com-hosted project with Travis CI usage.

I think it is good example for you why all in comment is bad idea in recent time especially in projects that demand very high quality in all (like checkstyle).

You can continue to comment, but we highly unlikely do such update.

**Comment by krichter722** [comment]
This improvement of the commit message can be done by requesting it from the PR author as well (or you're just pointing out your perspective). The link to issue discussion which _can_ become unreadable because github.com has no moderation tools and hardly ever changes after the issue is closed is a workaround for the loss of information. We see the same things as advantage and disadvantage.

Thanks for the insight and the collection of points. I'll bookmark this page as reference for eventual discussions in other projects. I wanted to make sure that you thought this through because it seems odd, but you definitely have and it's your well made decision.
