### ISSUE TITLE
Update FullIdent to store DetailAST instead of line/column

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#6121]
From https://github.com/checkstyle/checkstyle/issues/4830#issuecomment-383102616
>FullIdent could be modified to save the AST that starts the type so we can then retrieve the correct AST.

Part of https://github.com/checkstyle/checkstyle/issues/5758

**Comment by romani** [comment]
Fix is merged

**Comment by rnveach** [comment]
Documentation was never updated, or discussed, to show what checks now support xpath, if any.

**Comment by rnveach** [comment]
@romani ping, see previous statement

**Comment by romani** [comment]
@rnveach , previous comment is about xpath, please clarify how it is related to fullident class.

**Comment by rnveach** [comment]
As very first post suggests, this change to fullident was to support xpath because checks weren't logging by AST. Change to fullident was to give checks the internal xpath by the utility.

**Comment by pbludov** [comment]
> Documentation was never updated, or discussed, to show what checks now support xpath, if any.
> It looks like 3 now support it.

This should be done as part of #5758
