### ISSUE TITLE
What's the Specific rule of  Magic Numer ？

### ISSUE THREAD

**Issue by zjufirice** [checkstyle/checkstyle#6124]
`I found that the rule of magic number mistook some situation like Array subscript.
ex.int [] arr = new int[5];
    arr[4] =3;
"5" in first line and 4 in second line are both mistaken as magic numbers.
I want to improve the rule to eliminate such situation.
But I was confused by the realization of this rule .
Can you give me more concrete explanation ？

**Comment by rnveach** [comment]
@zjufirice Is the documentation not clear enough?

https://en.wikipedia.org/wiki/Magic_number_%28programming%29
http://checkstyle.sourceforge.net/config_coding.html#MagicNumber
> a magic number is a numeric literal that is not defined as a constant. By default, -1, 0, 1, and 2 are not considered to be magic numbers.
