### ISSUE TITLE
mvn checkstyle:checkstyle ignores local suppressions

### ISSUE THREAD

**Issue by stanislavkozlovski** [checkstyle/checkstyle#6128]
I have a project that I'm running `mvn checkstyle:checkstyle` on and it produces errors since it ignores the local suppressions.
Our organization uses a library with common pom settings which specifies the default suppressions location.
```
        <checkstyle.version>8.5</checkstyle.version>
        <maven-checkstyle-plugin.version>2.17</maven-checkstyle-plugin.version>
        <maven-clean-plugin.version>3.0.0</maven-clean-plugin.version>
        <maven-install-plugin.version>2.5.2</maven-install-plugin.version>
        <maven-resources-plugin.version>3.0.2</maven-resources-plugin.version>
        <checkstyle.config.location>checkstyle/checkstyle.xml</checkstyle.config.location>
        <checkstyle.suppressions.location>checkstyle/common-suppressions.xml</checkstyle.suppressions.location>
```
The project I'm running the command on has an additional checkstyle/suppresions.xml file. When running `mvn install` or `mvn test`, those suppressions get picked up and the project builds fine.

**Comment by rnveach** [comment]
We only deal with issues on checkstyle command line tool. Maven plugin is another group.

If you can confirm your issue is working with the command line tool, then the problem isn't with us.
See http://checkstyle.sourceforge.net/contributing.html#Report_an_issue

**Comment by romani** [comment]
@stanislavkozlovski , please open issue on maven plugin.

But checkstyle does not support multiple configurations, maven plugin need to craft final/virtual config for checkstyle execution.
