### ISSUE TITLE
How to ignore some situations in the rule of magic number

### ISSUE THREAD

**Issue by zjufirice** [checkstyle/checkstyle#6129]
ex.int [] arr = new int[5];
arr[4] =3;
"5" in first line and 4 in second line are both taken as magic numbers, I want to ignore such situations.
I tried to add INDEX_OP and LBRACK to constantWaiverParentToken, but it didn't work. Can  you give me some suggestions?

**Comment by rnveach** [comment]
> add INDEX_OP and LBRACK to constantWaiverParentToken

http://checkstyle.sourceforge.net/config_coding.html#MagicNumber
> Token that are allowed 

As documentation specifies, `constantWaiverParentToken` is the list of tokens you want to check for Magic numbers. If you don't want those tokens scanned, then you must not add them to it and list everything else.

Also please don't create new issues for the same problem. I also recommend using https://groups.google.com/forum/#!forum/checkstyle if you just need help configuring.
