### ISSUE TITLE
Confiruration xml inclusion/import

### ISSUE THREAD

**Issue by dzharikhin** [checkstyle/checkstyle#6132]
Let's assume we have several different projects supported by different teams inside one company.
There are common checkstyle rules for all, and there are specific cases per each project
If we had url http://checkstyle-repo/shared-config.xml, which provides something like this:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module PUBLIC
    "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
    "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
<!-- shared config -->
<module name="Checker">
    <module name="TreeWalker">
        <module name="MissingOverride"/>
        <module name="LineLength">
            <property name="max" value="120"/>
        </module>
    </module>
</module>
```
we could use something like this
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module PUBLIC
    "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
    "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
<import resource="http://checkstyle-repo/shared-config.xml" />
<module name="Checker">
    <module name="TreeWalker">
        <module name="AvoidStarImport"/>
        <module name="LineLength">
            <property name="max" value="150"/>
        </module>
    </module>
</module>
```
assuming the result
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module PUBLIC
    "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
    "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
<module name="Checker">
    <module name="TreeWalker">
        <module name="MissingOverride"/>
        <module name="AvoidStarImport"/>
        <module name="LineLength">
            <property name="max" value="150"/>
        </module>
    </module>
</module>
```
What is the point? if we decided to add new common check, we just change one file and provide it to all the consumers instead of editing each configuration

Are there any pitfalls on this feature? 
If it's ok, I'm going to try to implement it. 
Looks pretty easy - requires changes in ConfigLoader and DTD

p.s. I found no issues on subj, but if exists - I'm sorry

**Comment by dzharikhin** [comment]
Oh, sorry, I edited original description to be more clear, thanks

**Comment by rnveach** [comment]
@dzharikhin It sounds like you are talking about https://github.com/checkstyle/checkstyle/issues/2873 , creating inheritance for the configurations and possibly https://github.com/checkstyle/checkstyle/issues/991 , multiple configuration files.

**Comment by dzharikhin** [comment]
yep, that's it! thanks! So, I'm gonna close the issue and move in those topics
