### ISSUE TITLE
Disable XML External Entity load in XmlUtil.java in tests

### ISSUE THREAD

**Issue by ProDigySML** [checkstyle/checkstyle#6133]
# The Issue

An XML External Entity attack is a type of attack against an application that parses XML input. This attack occurs when XML input containing a reference to an external entity is processed by a weakly configured XML parser. This attack may lead to the disclosure of confidential data, denial of service, server side request forgery, port scanning from the perspective of the machine where the parser is located, and other system impacts.

# Where the Issue Occurred

The following code snippets display the usage of `XMLReader` without securely disabling entities:

https://github.com/checkstyle/checkstyle/blob/27512b0acc3ad3cb4e28306d4f8936b9108c5bca/src/test/java/com/puppycrawl/tools/checkstyle/internal/utils/XmlUtil.java#L56

**Comment by rnveach** [comment]
> checkstyle/src/test/java/com/puppycrawl/tools/checkstyle/internal/utils/XmlUtil.java

this is in the `test` folder so it is only executed when running the tests and wouldn't impact the released jar given to the public.

@ProDigySML You didn't find any issues with the code under the `main` folder? Like in https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/XmlLoader.java

**Comment by romani** [comment]
@ProDigySML , please let us know how you detected this security issue.

**Comment by ProDigySML** [comment]
This was basically just reading code. Apologies, I didn't realise it was a test folder.

**Comment by romani** [comment]
If you know how to fix it, please send Pull Request.

**Comment by JLLeitschuh** [comment]
@romani Has this also been resolved as part of #6474?

**Comment by rnveach** [comment]
@JLLeitschuh No.
This issue is for test only code, `XmlUtil`. #6474 changed production code, `XmlLoader.java`.

**Comment by JLLeitschuh** [comment]
Okay. This should be closed then probably.
If you google "Checkstyle XXE", this is the first result. Just a heads up.

**Comment by rnveach** [comment]
@JLLeitschuh The issue hasn't been fixed which is why it is still open. It won't affect users since it is only in test code.

**Comment by rnveach** [comment]
Fix was merged

**Comment by romani** [comment]
we deploy our test jar to maven central , example http://repo1.maven.org/maven2/com/puppycrawl/tools/checkstyle/8.18/ , so potentially users can reuse out tests classes in their applications/plugins/.... .

**Comment by JLLeitschuh** [comment]
@romani Since this was deployed, as a published consumable by users, does this warrant another CVE number?

@ProDigySML Did you see this vulnerability impacting your active development environment?
