### ISSUE TITLE
Multiline error messages

### ISSUE THREAD

**Issue by leventov** [checkstyle/checkstyle#6138]
It would be nice to support multiline error messages. For example:
```
<module name=...>
  ...
  <property name="message" value="This is a multiline message.
   It spans multiple lines.
   Three."/>
</module>
```

**Comment by rnveach** [comment]
Example violation: [ERROR] TestClass.java:2: This is a multiline message.    It spans multiple lines.    Three. [RegexpSingleline]

For whatever reason, it is not Checkstyle that is preventing the new lines from staying but it is our usage of SAX parser that is doing it.

You can use `&#10;` to force the new line character through.

I can specifically see code in the parser like this in `com.sun.org.apache.xerces.internal.impl.XMLScanner`:
````
                } else if (c == '\n' || c == '\r') {
                    fEntityScanner.scanChar(null);
                    stringBuffer.append(' ');
                    if (entityDepth == fEntityDepth && fNeedNonNormalizedValue) {
                        fStringBuffer2.append('\n');
                    }
````

but it looks like there is no way to turn `fNeedNonNormalizedValue` on as it is a private variable with no setters. And this is just my JDK's implementation, and doesn't mean others will have the same.

**Comment by romani** [comment]
@rnveach , please share working config example to show workaround in action , and we probably can close this issue.

If smb will tell us how to change SAX parser implementation or ..... to make it work ... we can create new issue.

**Comment by rnveach** [comment]
Here is an example of the workaround to force new lines in using `&#10;`:
````
$ cat TestClass.java
public class TestClass {
    void method() {
    }
}

$ cat TestConfig.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>

<module name="RegexpSingleline">
  <property name="format" value="method"/>
  <property name="message" value="This is a multiline message.&#10;It spans multiple lines.&#10;Three."/>
</module>
</module>

$ java -jar checkstyle-8.13-all.jar -c TestConfig.xml TestClass.java
Starting audit...
[ERROR] TestClass.java:2: This is a multiline message.
It spans multiple lines.
Three. [RegexpSingleline]
Audit done.
Checkstyle ends with 1 errors.
````

**Comment by leventov** [comment]
Thanks @rnveach and @romani!
