### ISSUE TITLE
Any plans to support other languages (e.g. javascript)?

### ISSUE THREAD

**Issue by dpalic** [checkstyle/checkstyle#614]
Hello together,

not sure if it is the right place, but I am wondering if the great tool has any plans to support other languages like PMD does. It would be a great benefit, if - in the meanwhile more and more commonly used UI-language javascript - could also be supported.
I would like to contribute, but will need some help regarding how to analyse the JS code and to provide it in the same manner like java code is provided in AST and for the visitor pattern.

Could one of the core developers tell about the plans regarding support of other languages?

best wishes

**Comment by romani** [comment]
Potentially Checkstyle could do that it can support any language, but somebody need to create javascript grammar for antlr tool.

please look at https://github.com/showcases/clean-code-linters there are already bunch of analysers for javascript, why we should be just another tool ?

Checkstyle have small team and a huge plans on extending for java language, and it should focus on one language, to be at the top among java analysers.

You can easily grab code that we have and start your tool.

For next few years i have no plans to support other languages.
