### ISSUE TITLE
How to allow comments while enforcing EmptyLineSeparator? 

### ISSUE THREAD

**Issue by AlexGustafsson** [checkstyle/checkstyle#6143]
File causing the issue:
``` Java
// Declare our package
package se.dequeue.calculator;
...
```

yields

```
.../src/App.java:2: 'package' should be separated from previous statement. [EmptyLineSeparator]
```

My check style.xml:
https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/google_checks.xml

---------------

I would like to be able to allow comments while still blocking usage of empty lines. I could not find it mentioned in the documentation for `EmptyLineSeparator`. 

A similar issue seems to be that comments are thought to be sections.

```Java
// Import all assertion types from the framework
import static org.junit.jupiter.api.Assertions.assertEquals;

// Import the main testing framework (JUnit 5)
import org.junit.jupiter.api.Test;
// Import our app to test
import se.dequeue.calculator.App;
```

yields

```
.../src/test/AppTest.java:5: 'org.junit.jupiter.api.Test' should be separated from previous import group by one line. [CustomImportOrder]
```

**Comment by romani** [comment]
@AlexGustafsson , please report issue exactly as requested in issue template. It will answer all questions that I need to confirm issue or help you with workaround or .... .

If no proper reporting provided, issue will be closed.

**Comment by rnveach** [comment]
Issue closed due to no response. Issue can be reopened with response.
