### ISSUE TITLE
NPathComplexityCheck calculates 'continue' statements as producing complex branches

### ISSUE THREAD

**Issue by Karaiso** [checkstyle/checkstyle#616]
Looking the following pseudo code has higher NPathComplexity:

```
private void mycode (string[] cmd) {
    int size = array.length;
    for (int i = 0; i < size; i++) {
       if ("abc".equals(cmd[i])) {
            doAbc();
            continue;
        }
        if ("def".equals(cmd[i])) {
            doDef();
            continue;
        }
        if ("def".equals(cmd[i])) {
            doDef();
            continue;
        }
        ... (5 times more and another outer loop)
    }
}
```

Than:

```
private void mycode (string[] cmd) {
    int size = array.length;
    for (int i = 0; i < size; i++) {
        if ("abc".equals(cmd[i])) {
            doAbc();
        } else if ("def".equals(cmd[i])) {
            doDef();
        } else if ("def".equals(cmd[i])) {
            doDef();
        } ... 5 times more and another outer loop)
    }
}
```

Actually this should produce the same byte code.
Reviewing the NPathComplexityCheck.java code we can see 'return', 'continue' and maybe other not producing branches producing flow statements (break ...) are counted as producing branches.

Code reading might be easier for the second example,
but this is subjective and not true for all developers or use cases.

'NPathComplexityCheck' is a very good, mostly objective,
maybe the most important check and should be considered from all developers
also (or especially) from the 'return and continue' developers.

My intention: Making NPathComplexityCheck more 'objective' (to stop subjective discussions).

Thank to all of the checkstyle team, you are doing a very important job,
increasing the code quality in the world.

Regards from Aachen, Germany
##

**Comment by romani** [comment]
@Karaiso ,

we have that check in kind of abandoned state - #146, #56 .

can you provide link to what is NPathComplexity and how it is should be calculated ? 

you are welcome to provide fixes for that Check :), looks like you benefit from it and you know what it measures. But lets come to agreement on changes before implementation.

**Comment by Karaiso** [comment]
Hi romani,

Yes it is true, the comments #146 and #56 are related to the same issues.

"can you provide link to what is NPathComplexity and how it is should be calculated ?"
No, I can't. This is why we first must discuss and define what 'NPathComplexity' is.
Looking to the sample in #56, both calculations are true, depending on what we want to calculate.

So what do I (we and all users) probably want from 'NPathComplexityCheck'?
It is normal business from my personal experience, if a problem is more complex
I do myself sometimes not find the best simple solution for a complex problem.
We want a simple and fast check, calculating the complexity of the written code.
The number of paths or branches produce 'complexity' but also combinations of expressions do,
even if there are new branches.
If the complexity is to high we want to have at least a notice, producing code reviews
and hope that helps the code writer, often ourself ;-), to think and write a more simple solution.

Looking the second sample in #56 we have no new branches but higher complexity.

However, 'NPathComplexityCheck' as it is now is, with default level 200,
helps but not that much as it could.
It produces code reviews to code that is not that complex and
does not warn code that should be reviewed.

To fix that, 'NpathcomplexityCheck' should be renamed to 'ComplexityCheck',
calculating the paths/branches correct (it does not now) but also counting the
expressions complexity (why it should be renamed).

This is my point of view.

**Comment by romani** [comment]
1) We need to find somewhere in web description of NPathComplexity, I had some pages , but now they are 404. 
Without clear understanding how it should be done, that Check will not be changed. You can start another Check creation, but please beware of our policy for new Checks https://groups.google.com/forum/#!topic/checkstyle-devel/JbhfiiSqKsQ.

2)
> To fix that, 'NpathcomplexityCheck' should be renamed to 'ComplexityCheck'

No it would mean braking compatibility, I try to do that as minimum as possible. That is not a reason.

**Comment by Karaiso** [comment]
Hi Romani,

I can not help, to find a description, 'NPathComplexity' should provide a description.
If there is no 'description' and nothing reliable found the check is useless.

In fact, I ask some other developers, the warning is often ignored,
because the result does too often not match the experience.

If it is impossible to do changes, it might a better idea to remove 'NPathComplexity',
as the project seems to be 'dead'.

Regards and greetings from Aachen,

**Comment by romani** [comment]
ok, I purchased original article for NPath complexity at http://dl.acm.org/citation.cfm?id=42379&CFID=478853394&CFTOKEN=81757135, I hope we will find some time to review that Check , so Check is not going to be dead.

**Comment by romani** [comment]
All formulas from pdf specification of NPATH is at checkstyle.sourceforge.net/config_metrics.html#NPathComplexity
```
public class Demo {
    private void mycode (string[] cmd) { // 1 * 9 = 9
        int size = array.length; //1
        for (int i = 0; i < size; i++) { // (2 * 2 * 2) + 0 + 0 + 1 = 9 
           if ("abc".equals(cmd[i])) { // 1 + 0 + 1 = 2
                doAbc();
                continue;
            }
            if ("def".equals(cmd[i])) { // 1 + 0 + 1 = 2
                doDef();
                continue;
            }
            if ("def".equals(cmd[i])) { // 1 + 0 + 1 = 2
                doDef();
                continue;
            }
        }
    }
}
```
