### ISSUE TITLE
web site: add feeds icons to ReleaseNotes page

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#617]
1) Add to top conner of http://checkstyle.sourceforge.net/releasenotes.html
images for assigning for RSS feed(find link to rss at https://sourceforge.net/p/checkstyle/news/?source=navbar) and Mail-list (checkstyle-announce), and our twitter, 

Example of feed subscription images (we could use that images or any other images that are free to use):
http://www.cyberciti.biz/tips/linux-display-open-ports-owner.html

Expected location square of images is below "
Last Published: 2015-02-01 | Version: 6.3 " and above "Release 6.3" alligned to right side of the page
![location-for-small-square-images](https://cloud.githubusercontent.com/assets/812984/6219616/d9f0f75c-b5e0-11e4-90f0-3dc70ac1d1d4.png)

2) please add to "poweredBy" group :
- grougle-group image to left side of web site to link user to checksyle mail-list for question and answers.
- to rss feed 

Images at "poweredBy" should be rectangular  as other images, so some pictures might require resize to looks like rectangular banners.

Rss image should be  like ( or find any other image ): http://www.freepik.com/free-psd/bold-orange-rss-subscribe-buttons-psd_597344.htm
Google group image should be rectangular - I like there (with same text, but image is a bit bigger) : http://www.safeharbors.org/SHUserGroup.htm, but text should be part of image.

**Comment by romani** [comment]
http://maven.apache.org/plugins/maven-gpg-plugin/usage.html - segments that have links and smth like an image insegment title

**Comment by alexkravin** [comment]
@romani,
I found no way to add RSS icon to releasenotes.html page immediately (at expected spot), as xdoc doesn't support banner section before body part, in its turn body supports only <b>section</b> tags inside.

**Comment by romani** [comment]
where is prove of that ?

**Comment by alexkravin** [comment]
Just try to do that

Here's xdoc schema: http://maven.apache.org/xsd/xdoc-2.0.xsd

**Comment by romani** [comment]
> Just try to do that

you do task and you should try and prove.

> Here's xdoc schema

OK.

**Comment by mkordas** [comment]
Guys, icon currently used for RSS is a little bit to wide, it doesn't look good: 
![image](https://cloud.githubusercontent.com/assets/5467276/6661481/2962f6e6-cbad-11e4-94a4-947eb208978b.png)

Compare to this version:
![image](https://cloud.githubusercontent.com/assets/5467276/6661522/a4af4d9a-cbad-11e4-92e6-1b26aa6b69e6.png)

http://pixabay.com/p-40674

**Comment by romani** [comment]
@mkordas, please resize it to our banners size and do PR.
