### ISSUE TITLE
upgrade to latest picocli version to fix extra space in help output

### ISSUE THREAD

**Issue by remkop** [checkstyle/checkstyle#6175]
This is a follow-up item from PR https://github.com/checkstyle/checkstyle/pull/6126.

After upgrading from Commons CLI to picocli,  the usage help message displays a space between short options and the option parameter. This is a known issue in picocli: https://github.com/remkop/picocli/issues/531

This ticket is a reminder to upgrade the picocli version when that ticket is fixed in picocli.
(Note that the usage help message text will change so the test will also need to be modified slightly.)

**Comment by remkop** [comment]
Picocli 3.8 has been [released](https://github.com/remkop/picocli/releases/tag/v3.8.0). This includes a fix for  https://github.com/remkop/picocli/issues/531

**Comment by romani** [comment]
good, thanks a lot!
 tomorrow our CI will fail with request to upgrate to latest picocli, let me check that it works :).

**Comment by romani** [comment]
Here is signal to upgrade version https://travis-ci.org/checkstyle/checkstyle/jobs/455142812#L2848

**Comment by romani** [comment]
fix is merged.

**Comment by remkop** [comment]
Nice! What’s the schedule for this to be released?

**Comment by romani** [comment]
As mentioned in milestones, end of month, end of November.

**Comment by remkop** [comment]
FYI: 
Getting close to finishing up my article about migrating from Commons CLI to picocli, using CheckStyle as an example:
https://github.com/remkop/picocli/wiki/Migrating-from-Commons-CLI-to-picocli

Feedback welcome.

**Comment by romani** [comment]
Good article.
It would be good to make few links:
How it was
Diff of migration
How it now

Now arguments parsing is  gathered in one place, and it does not polute Main class code.


----

Off topic: why picocli does not use checkstyle ? :)

**Comment by romani** [comment]
@remkop , please look at my last comment.

**Comment by remkop** [comment]
Hi @romani, 
Good advice: I made the change so there’s a “before” and “after” link. If there’s a way to just show the diff for `Main` I’ll add that link too. 

About using CheckStyle: it’s one of the many things on the todo list!
