### ISSUE TITLE
automation of github actions for release.sh

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#6186]
interaction with github need to be automated
https://github.com/checkstyle/checkstyle/wiki/How-to-make-a-release
"Close previous milestone"
"update Release body"

https://unix.stackexchange.com/a/330574/27505
`cal -m 11`

**Comment by rnveach** [comment]
> "Close previous milestone"

See https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/master/release.sh#L159-L164

> "update Release body"

Do you mean the information found at https://github.com/checkstyle/checkstyle/releases/edit/checkstyle-8.14 ?

**Comment by romani** [comment]
Steps at wiki are stable, we just need to move them to script, TKN should be defined outside of script. But script should check that variable is defined
