### ISSUE TITLE
Require at least Maven 3.0.1 to build Checkstyle

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#620]
Output from [versions:display-plugin-updates](http://mojo.codehaus.org/versions-maven-plugin/display-plugin-updates-mojo.html) plugin:
```
[WARNING] Project does not define minimum Maven version
[INFO] Plugins require minimum Maven version of: 3.0.1
...
[INFO] Require Maven 3.0.1 to use the following plugin updates:
[INFO]   org.codehaus.mojo:findbugs-maven-plugin ....................... 3.0.0
```

That means if someone would like to build Checkstyle with Maven version lower than 3.0.1 findbugs plugin won't be able to execute correctly.

Solution is to put to `pom.xml` the following prerequisite:
```xml
     <prerequisites>
       <maven>3.0.1</maven>
     </prerequisites>
```

**Comment by romani** [comment]
@mkordas , hhm, ok, but what if use  3.0.4 as minimal requirement ? 
http://maven.apache.org/plugins/maven-site-plugin/maven-3.html#Inheritance_of_reports_for_Maven_3_before_3.0.4

do you see any limitations there ?

**Comment by mkordas** [comment]
@romani - the link you provided is about project with submodules. Checkstyle has only one module, so I don't see any reason why 3.0.4 would be better.

**Comment by romani** [comment]
ok, lets go with 3.0.1. 
Please do PR.
