### ISSUE TITLE
add spring-cloud-gcp project to CIs no errror regresson testing

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#6209]
review discusion at https://github.com/spring-cloud/spring-cloud-gcp/issues/1195#issuecomment-437443330

append this project to "no-error" wercker validation.
Fix should be similar to fix at #6167 .

Varable with version: https://github.com/spring-cloud/spring-cloud-build/blob/master/pom.xml#L42

**Comment by Gaurav-Punjabi** [comment]
I'm on it.

**Comment by romani** [comment]
fix is merged.
