### ISSUE TITLE
use lgtm.com service of static code analysis

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#6217]
Service: https://lgtm.com (from https://semmle.com/)

see example at: https://github.com/hibernate/hibernate-search

it runs semmle tool inside:
https://help.semmle.com/codeql/codeql-cli.html
https://help.semmle.com/codeql/codeql-cli/procedures/analyze-codeql-database.html

All rules: 
https://help.semmle.com/qldoc/java/
https://help.semmle.com/wiki/display/JAVA/Java+queries
https://help.semmle.com/wiki/display/JAVA/Missing+Override+annotation migth be useful for us, as it is not enforced on our code base.

**Comment by Gaurav-Punjabi** [comment]
I'm on it.

**Comment by Gaurav-Punjabi** [comment]
@romani LGTM currently does not support forked repository and as I cannot install LGTM on checkstyle/checkstyle, is it okay if I test LGTM on a local repository first, then create a PR with its configuration? Later you'll just need to install LGTM on checkstyle

**Comment by romani** [comment]
yes, please test it on your personal repo, and this experience we will apply to chekcstyle later on, when we know most nuances of this service.

**Comment by Gaurav-Punjabi** [comment]
@romani I have configured LGTM on https://github.com/Gaurav-Punjabi/checkstyle-lgtm successfully. Now I just need to add queries on it. Do I need to add all java queries provided by LGTM ?

**Comment by Rahulkhinchi03** [comment]
@romani I would like to try to work on this issue. Please guide me!

**Comment by romani** [comment]
Try to setup all for your fork. As you finish, we can reuse your experience to reapply all to main repo.

**Comment by Rahulkhinchi03** [comment]
@romani I have set up the LGTM: https://lgtm.com/projects/g/checkstyle/checkstyle/alerts/

We currently have: `10 ERRORS, 23 WARNINGS, and 1 RECOMMENDATION` by LGTM

The repository used: https://github.com/Rahulkhinchi03/checkstyle-testing-lgtm

It also shows other alerts (` i.e. 1.6k alerts`) but these files are excluded as
 LGTM classifies (or tags) files according to their purpose and their source. "Normal" or "core" code files are untagged. Results for files that are tagged are hidden and they are also excluded from the statistics. So that it can accurately quantify the development progress of a project.

## EXCLUDED ALERTS
![xxsdf](https://user-images.githubusercontent.com/71710042/167381417-ee1cd404-8775-4ced-91b6-71772c51ec12.png)



### JAVA QUERIES
I have found out that the JAVA QUERIES which checkstyle uses are:

```
java/constant-comparison
java/constant-loop-condition
java/dereferenced-value-may-be-null
java/equals-on-unrelated-types
java/inconsistent-equals-and-hashcode
java/output-resource-leak
java/unchecked-cast-in-equals
java/unused-container
```

Do I have to add other queries too?

**Comment by rnveach** [comment]
@Rahulkhinchi03 Are you able to customize the reporting so it only reports on non-Input files? I am seeing a few items being our IT inputs (it/resources).

**Comment by Rahulkhinchi03** [comment]
@romani kindly review when you get some free time!

**Comment by rnveach** [comment]
@Rahulkhinchi03 Can you provide what queries can be applied to remove the false ones and allow us to see what is remaining as most likely actual issues?

Anything connected to our input files inside test/it resources folder should be what we ignore. They just represent test cases, and not actual code that needs "fixing".

**Comment by Rahulkhinchi03** [comment]
@rnveach As much I have used and investigated, We can use run Queries to find the total number of query-related errors. 
But Also we can hide the error which we don't want to look after. I can do that if you suggest.


The errors in it/resources are 25.

```
The queries which found the error were:
java/constant-comparison
java/constant-loop-condition
java/dereferenced-value-may-be-null
java/equals-on-unrelated-types
java/inconsistent-equals-and-hashcode
java/output-resource-leak
java/unchecked-cast-in-equals
java/unused-container
```

Currently, we have only 7 errors other than input files.

2 are of Javascript:
`/src/site/resources/styleguides/google-java-style-20180523/include/styleguide.js`

7 are in:
`src/main/java/com/puppycrawl/tools/checkstyle/`

5 in Ant
1 in Checks
1 in Util

**Comment by romani** [comment]
Can we exclude Input files completely from scanning? They are nonsense code by design/nature .

**Comment by Rahulkhinchi03** [comment]
@romani We can do that. We can suppress these violations one by one only by writing some comments or adding @SuppressionWarning in the code.

We already have some excluded errors. This is naturally done by LGTM. It classifies errors into `tagged` and  `untagged`. LGTM classifies (or tags) files according to their purpose and their source. "Normal" or "core" code files are untagged. Results for files that are tagged are hidden and they are also excluded from the statistics.

https://lgtm.com/help/lgtm/alert-suppression#java this Documentation says that we can suppress alerts by 

```
void test(int length) {
    int firstIndex = length * 0; // lgtm[java/evaluation-to-constant]
    int secondIndex = length * 1;
    int thirdIndex = length * 2;
    ...
}
```

OR

```
@SuppressWarnings("lgtm[java/evaluation-to-constant]")
void test(int length) {
    int firstIndex = length * 0;
    int secondIndex = length * 1;
    int thirdIndex = length * 2;
    ...
}
```

**Comment by Rahulkhinchi03** [comment]
I recently found out that we can configure our analysis by adding `lgtm.yml` in the repository.  
(https://lgtm.com/help/lgtm/customizing-file-classification)

I am trying to add configuration for excluding it/resources files.

**Comment by Rahulkhinchi03** [comment]
@rnveach I still don't understand that when I ran the build it was showing only the actual errors but after an hour, it is back to normal. It seems unstable.

**Comment by romani** [comment]
We need to suppress violations in ant class. All of them "won't fix" or false alert.
Can you do this by config file ?

**Comment by Rahulkhinchi03** [comment]
@romani We can only add configuration with `LGTM.YML`, I believe.

As per the rules of LGTM:

![sdgh](https://user-images.githubusercontent.com/71710042/168163818-9eea5ece-9a7b-4fab-91d8-191cf7b1de65.png)

**Comment by romani** [comment]
It is awesome to have configuration by file, let's try to use it.

**Comment by Rahulkhinchi03** [comment]
@romani  Please let me know what are other investigation/information required. Or we can start using it with our main repository.

**Comment by romani** [comment]
Can we suppress violations in ant classes by yml config ?

**Comment by Rahulkhinchi03** [comment]
@romani Yes we can do that by lgtm.yml file. We have an option of Generated Code, Library code, and Template Code. We can just write the file name which we want to exclude or we can exclude with queries too.

**Comment by romani** [comment]
Filtering/suppression model is only in java code, sad. Unfortunately this will pollute our code a lot with annotations.
I am voting to not use lgtm service.

@nick-mancuso , @rnveach , @pbludov , @strkkk , please share your ideas on this

**Comment by pbludov** [comment]
Is it possible to exclude all files with false-positives via `.lgtm.yaml`?

**Comment by pbludov** [comment]
Also, we can disable all false-positive [queries](https://lgtm.com/help/lgtm/lgtm.yml-configuration-file#queries).

I am confused by the fact that this service has not found any new issues. Perhaps under the hood are the tools that we are already using.

**Comment by nick-mancuso** [comment]
I vote to not use this tool, suppression by annotation model is not ideal.

**Comment by Rahulkhinchi03** [comment]
@strkkk @rnveach Please find some time to review this issue!

**Comment by strkkk** [comment]
If there is no other options for suppresion except annotations in code, lets focus on other tools. From brief glance at docs it seems that suppression config is a bit complicated.

**Comment by rnveach** [comment]
I am agreeing not to use it. It isn't reporting any valid issues in our code.
