### ISSUE TITLE
use latest code of hibernate-search in CI after checkstyle violation is resolved 

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#6218]
problem is detected at https://github.com/checkstyle/checkstyle/pull/6215#issuecomment-439541183

problem is caused by https://github.com/hibernate/hibernate-search/pull/1804

we updated wercker execution to use non master:HEAD.
ones problem is resolved at hiberate-search repo, we should revert such commit.

**Comment by romani** [comment]
We can revert a commit, hibernate team fixed the problem

**Comment by rnveach** [comment]
If they aren't using Checkstyle as part of CI, problem will come back again.

**Comment by rnveach** [comment]
They did confirm. See https://github.com/hibernate/hibernate-search/pull/1804#issuecomment-439977521 . So we are good to revert.

**Comment by romani** [comment]
Fix is merged
