### ISSUE TITLE
resolve warning in build output from PMD 

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#6226]
https://travis-ci.org/checkstyle/checkstyle/jobs/456413115#L738

`[WARNING] Discontinue using Rule name category/java/codestyle.xml/AbstractNaming as it is scheduled for removal from PMD. PMD 7.0.0 will remove support for this Rule.`

```
[INFO] --- maven-pmd-plugin:3.11.0:pmd (pmd) @ checkstyle ---
[WARNING] Discontinue using Rule name category/java/codestyle.xml/AbstractNaming as it is scheduled for removal from PMD. PMD 7.0.0 will remove support for this Rule.
[WARNING] Discontinue using Rule name category/java/codestyle.xml/AbstractNaming as it is scheduled for removal from PMD. PMD 7.0.0 will remove support for this Rule.
[INFO]
```

**Comment by rnveach** [comment]
https://github.com/pmd/pmd/issues/972
>  AbstractNaming -> superseded by ClassNamingConventions
https://github.com/pmd/pmd/blob/1d652fc81cfe3d380b5a586f8ea3539fafa42136/docs/pages/next_major_development.md#L173
> The Java rule {% rule java/codestyle/AbstractNaming %} is deprecated in favour of {% rule java/codestyle/ClassNamingConventions %}.

**Comment by romani** [comment]
Fix is merged
