### ISSUE TITLE
Typo in "ignoreOverridenMethods" property of IllegalThrows check

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#623]
Property of [IllegalThrows](http://checkstyle.sourceforge.net/config_coding.html#IllegalThrows) contains typo. Should be `ignoreOverriddenMethods` instead of `ignoreOverridenMethods` - double "d" in overridden.

This typo occurs in 29 places in code base. All occurrences should be fixed.

**Comment by romani** [comment]
fixed, will be in 6.4
