### ISSUE TITLE
Pitest: add new mutator TRUE_RETURNS

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#6264]
This is not an unstable mutator, just disabled by default.

http://pitest.org/quickstart/mutators/#TRUE_RETURNS
> Replaces primitive and boxed boolean return values with true.
Pitest will filter out equivalent mutations to methods that are already hard coded to return true.

Report with only new mutator added, and others disabled: http://rveach.no-ip.org/checkstyle/regression/pitest-reports/19/

So it basically replaces `return variable;` with `return true;` and expects a test to fail. This shows that the method never returns false or the return of false has no effect on future logic and should probably be removed.

**Comment by rnveach** [comment]
I will start on this after https://github.com/checkstyle/checkstyle/issues/4684 and https://github.com/checkstyle/checkstyle/pull/6254 when the full list of files being test is stable.

**Comment by rnveach** [comment]
@romani I just wanted you to know I am seeing some weird differences in the pitest script because of the new mutator. I am seeing the same line move to a new location, so the PR will be showing some differences as it is now.
Example:
````
+IndentLevel.java.html:<td class='covered'><pre><span  class='survived'>            for (int i = levels.nextSetBit(0); i &#62;= 0;</span></pre></td></tr>
 IndentationCheck.java.html:<td class='covered'><pre><span  class='survived'>        handlerFactory.clearCreatedHandlers();</span></pre></td></tr>
 IndentationCheck.java.html:<td class='covered'><pre><span  class='survived'>        handlers.clear();</span></pre></td></tr>
 IndentationCheck.java.html:<td class='covered'><pre><span  class='survived'>        primordialHandler.checkIndentation();</span></pre></td></tr>
-IndentLevel.java.html:<td class='covered'><pre><span  class='survived'>            for (int i = levels.nextSetBit(0); i &#62;= 0;</span></pre></td></tr>
````

**Comment by romani** [comment]
new mutaor was not added, so I presume issue is not completed

**Comment by rnveach** [comment]
No, that will be done in the next PR.
Since you like simple fixes, I decided to split this into 3 PRs.
New tests, default config, and then new mutator plus code changes. If you would like this done in a different way, let me know.

**Comment by rnveach** [comment]
> I am seeing some weird differences

Based on CI in https://github.com/checkstyle/checkstyle/pull/6274 , it looks like this is just an issue with my local as now CI wants me to undo some ordering differences.
I will make a new issue for this.

**Comment by romani** [comment]
fix is merged.
