### ISSUE TITLE
org/apache/commons/cli/ParseException missing in checkstyle-8.15-all.jar

### ISSUE THREAD

**Issue by breizh31** [checkstyle/checkstyle#6271]
Hello,

I upgraded my checkstyle environment with checkstyle-8.15-all.jar. Unfortunatelly, I've got an error:
`
2018-12-11 10:28:11 [WARN]  Error: A JNI error has occurred, please check your installation and try again
2018-12-11 10:28:11 [WARN]  Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/cli/ParseException
`

The class org.apache.commons.cli.ParseException.class is missing in the -all package.

F.

**Comment by breizh31** [comment]
Thanks for your answer.

I think the problem comes from our CheckStyleWrapper which may use this library. I will confirm it with our supplier before close this issue.

**Comment by rnveach** [comment]
@breizh31 Is this an open source wrapper that we can see and use?
We like to become more familar with projects who use our tool.

**Comment by romani** [comment]
I am closing, as unrelated to us.
In 8.15 we removed Apache CLI and now use picocli library
