### ISSUE TITLE
Pitest: add new mutator FALSE_RETURNS

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#6272]
This is not an unstable mutator, just disabled by default.

http://pitest.org/quickstart/mutators/#FALSE_RETURNS
> Replaces primitive and boxed boolean return values with false.
Pitest will filter out equivalent mutations to methods that are already hard coded to return false.

Report with only new mutator added, and others disabled: http://rveach.no-ip.org/checkstyle/regression/pitest-reports/24/
This report includes fixes created in PR https://github.com/checkstyle/checkstyle/pull/6268 .
Only reports worth looking at: coding, javadoc, utils, and gui. Only 13 mutations exist.

So it basically replaces `return variable;` with `return false;` and expects a test to fail. This shows that the method never returns true or the return of true has no effect on future logic and should probably be removed.

Mutator can't be added until https://github.com/checkstyle/checkstyle/issues/6264 is done.

**Comment by romani** [comment]
Fix is merged
