### ISSUE TITLE
Pitest script order issue locally

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#6275]
Identified at https://github.com/checkstyle/checkstyle/issues/6264#issuecomment-446314799 and https://github.com/checkstyle/checkstyle/pull/6274 .

 I am seeing some weird differences in the pitest script (locally) when adding the new mutator. I am seeing the same line move to a new location, so my commit PR was showing some differences.
Example:
````
+IndentLevel.java.html:<td class='covered'><pre><span  class='survived'>            for (int i = levels.nextSetBit(0); i &#62;= 0;</span></pre></td></tr>
 IndentationCheck.java.html:<td class='covered'><pre><span  class='survived'>        handlerFactory.clearCreatedHandlers();</span></pre></td></tr>
 IndentationCheck.java.html:<td class='covered'><pre><span  class='survived'>        handlers.clear();</span></pre></td></tr>
 IndentationCheck.java.html:<td class='covered'><pre><span  class='survived'>        primordialHandler.checkIndentation();</span></pre></td></tr>
-IndentLevel.java.html:<td class='covered'><pre><span  class='survived'>            for (int i = levels.nextSetBit(0); i &#62;= 0;</span></pre></td></tr>
````
and
````
-ElseHandler.java.html:<td class='covered'><pre><span  class='survived'>        return getMainAst().getFirstChild();</span></pre></td></tr>
 ElseHandler.java.html:<td class='covered'><pre><span  class='survived'>            super.checkTopLevelToken();</span></pre></td></tr>
+ElseHandler.java.html:<td class='covered'><pre><span  class='survived'>        return getMainAst().getFirstChild();</span></pre></td></tr>
````

When running in the CI on the server, it had me undo all the moves I had to make. Example: https://circleci.com/gh/checkstyle/checkstyle/13055#tests/containers/1

So there is some issue with ordering with the script on certain systems.
I am using Lubuntu 17.

**Comment by rnveach** [comment]
Since there were no additions in the report, just pure re-ordering, it must be related to some issue with sorting since the data is sorted at https://github.com/checkstyle/checkstyle/blob/master/.ci/pitest.sh#L11 .

Going by https://stackoverflow.com/a/28903/1016482 , we need to add `LC_ALL=C` to ensure similar sorting on all machines.

**Comment by romani** [comment]
Fix is merged
