### ISSUE TITLE
Fix HTML5 incompatible javadoc comments

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#6287]
Part of #6228 

Starting from JDK11 the option `-html5` is on by default. This breaks the javadoc build:
https://travis-ci.org/checkstyle/checkstyle/jobs/464796081#L8406 

>[ERROR] Exit code: 1 - /home/travis/build/checkstyle/checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/CustomImportOrderCheck.java:156: error: attribute not supported in HTML5: summary
[ERROR]  * &lt;table summary="Properties" border="1"&gt;

All incompatible HTML5 tags and attributes must be replaced with alternatives

**Comment by rnveach** [comment]
> CustomImportOrderCheck.java:156
> ImportOrderCheck.java:54

Issue https://github.com/checkstyle/checkstyle/issues/5750 could be used to fix them as it is the main javadoc and we are re-formatting them with that issue.

**Comment by pbludov** [comment]
Ok, I'll make a PR to #5750.
