### ISSUE TITLE
pitest: increase mutation coverage for javadoc profile to 100%

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#6295]
We should increase coverage for javadoc profile up to 100%.
This issue is a subtask of #3708

-------

<a href="https://www.bountysource.com/issues/67607738-pitest-increase-mutation-coverage-for-javadoc-profile-to-100">
<img src="https://api.bountysource.com/badge/issue?issue_id=67607738">
</a>

**Comment by rnveach** [comment]
I can't reproduce these mutations surviving locally. The part that is being mutated is `tagText` after the `->`.
https://github.com/checkstyle/checkstyle/blob/4490111f28cf40d8374152b026796410075ba52e/.ci/pitest.sh#L119-L120
`mutated return of Object value for com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagInfo::lambda$1 to ( if (x != null) null else throw new RuntimeException ) → SURVIVED`

**Comment by romani** [comment]
Did you try this on Windows or Linux?

**Comment by rnveach** [comment]
Running pitest produces it on windows and linux, but I can't reproduce it using eclipse on Windows. I get exceptions when replacing the code with `null`. I haven't tried linux.

**Comment by ahmedmohiduet** [comment]
Hello, let me know if this issue still has bounty open. Would love to contribute

**Comment by romani** [comment]
@ahmedmohiduet , still open, please fix issue and get a bounty.
