### ISSUE TITLE
Indentation: indentation level is being corrupted in class fields

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#6308]
While running regression for pitest, I have gotten differences that I couldn't reproduce locally on a single file run. I believe one reason is because the [`IndentLevel`](https://github.com/checkstyle/checkstyle/blob/641b6b2c0689fc35d6a3d77a7215fd1d9ce2a2b8/src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/AbstractExpressionHandler.java#L49) is being corrupted as we use the same class instance among multiple fields.

[I tried to remove the cache of this field](https://github.com/checkstyle/checkstyle/blob/641b6b2c0689fc35d6a3d77a7215fd1d9ce2a2b8/src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/AbstractExpressionHandler.java#L83), but it caused regression to stall for 10 hours on apache ant's `BlockSort.java`.

I rework IndentLevel class to be immutable, and I am seeing regression differences.

From the changes I made, [I believe `ObjectBlockHandler` is the one doing the corruption](https://github.com/rnveach/checkstyle/blob/6893affeac7285afd16f8a389c7d65023d0c327a/src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/ObjectBlockHandler.java#L67-L69). It is modifying another class' fields by calling `addAcceptedIndent` on an `IndentLevel` it didn't create.

**Comment by romani** [comment]
Fix is merged
