### ISSUE TITLE
Update eclipse compiler to R10

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#6330]
A new version of the Eclipse compiler was recently [released](https://www.eclipse.org/eclipse/news/4.10/jdt.php)

One bug (class definition without package) was fixed, a new one [introduced](https://bugs.eclipse.org/bugs/show_bug.cgi?id=543090)

Also, is brings full support for java 11 syntax.

**Comment by rnveach** [comment]
@romani I assume since eclipse is only in the SH file and retrieved through HTTP, we don't receive notifications when it is updated?

**Comment by romani** [comment]
>we don't receive notifications when it is updated?

Yes

>Not sure if we can create a bash script to parse the HTTP folder for the latest date/time file.

I do not see reason why we should care, eclipse compiler is used only to make sure that input file is actually compilable.

**Comment by rnveach** [comment]
@romani it also provides us eclipse analysis that we aren't getting else where. See https://github.com/checkstyle/checkstyle/blob/master/config/org.eclipse.jdt.core.prefs

**Comment by pbludov** [comment]
New eclipse compiler preferences:

- [ ] org.eclipse.jdt.core.compiler.annotation.nonnull
- [ ] org.eclipse.jdt.core.compiler.annotation.nonnullbydefault
- [ ] org.eclipse.jdt.core.compiler.annotation.nullable
- [ ] org.eclipse.jdt.core.compiler.problem.APILeak
- [ ] org.eclipse.jdt.core.compiler.problem.annotationSuperInterface
- [ ] org.eclipse.jdt.core.compiler.problem.assertIdentifier
- [ ] org.eclipse.jdt.core.compiler.problem.deadCodeInTrivialIfStatement
- [ ] org.eclipse.jdt.core.compiler.problem.enumIdentifier
- [ ] org.eclipse.jdt.core.compiler.problem.forbiddenReference
- [ ] org.eclipse.jdt.core.compiler.problem.invalidJavadoc
- [ ] org.eclipse.jdt.core.compiler.problem.invalidJavadocTags
- [ ] org.eclipse.jdt.core.compiler.problem.invalidJavadocTagsDeprecatedRef
- [ ] org.eclipse.jdt.core.compiler.problem.invalidJavadocTagsNotVisibleRef
- [ ] org.eclipse.jdt.core.compiler.problem.invalidJavadocTagsVisibility
- [ ] org.eclipse.jdt.core.compiler.problem.missingDeprecatedAnnotation
- [ ] org.eclipse.jdt.core.compiler.problem.missingJavadocComments
- [ ] org.eclipse.jdt.core.compiler.problem.missingJavadocCommentsOverriding
- [ ] org.eclipse.jdt.core.compiler.problem.missingJavadocCommentsVisibility
- [ ] org.eclipse.jdt.core.compiler.problem.missingJavadocTagDescription
- [ ] org.eclipse.jdt.core.compiler.problem.missingJavadocTags
- [ ] org.eclipse.jdt.core.compiler.problem.missingJavadocTagsMethodTypeParameters
- [ ] org.eclipse.jdt.core.compiler.problem.missingJavadocTagsOverriding
- [ ] org.eclipse.jdt.core.compiler.problem.missingJavadocTagsVisibility
- [ ] org.eclipse.jdt.core.compiler.problem.missingOverrideAnnotation
- [ ] org.eclipse.jdt.core.compiler.problem.missingOverrideAnnotationForInterfaceMethodImplementation`
- [ ] org.eclipse.jdt.core.compiler.problem.nullAnnotationInferenceConflict
- [ ] org.eclipse.jdt.core.compiler.problem.nullSpecViolation
- [ ] org.eclipse.jdt.core.compiler.problem.overridingMethodWithoutSuperInvocation
- [ ] org.eclipse.jdt.core.compiler.problem.tasks
- [ ] org.eclipse.jdt.core.compiler.problem.unavoidableGenericTypeProblems
- [ ] org.eclipse.jdt.core.compiler.problem.unhandledWarningToken
- [ ] org.eclipse.jdt.core.compiler.problem.unusedParameterIncludeDocCommentReference
- [ ] org.eclipse.jdt.core.compiler.problem.unusedParameterWhenImplementingAbstract
- [ ] org.eclipse.jdt.core.compiler.problem.unusedParameterWhenOverridingConcrete
- [ ] org.eclipse.jdt.core.compiler.problem.unusedTypeArgumentsForMethodInvocation
- [ ] org.eclipse.jdt.core.compiler.problem.unusedWarningToken`

removed from R10

- [ ] org.eclipse.jdt.core.compiler.problem.fatalOptionalError
- [ ] org.eclipse.jdt.core.compiler.problem.includeNullInfoFromAsserts
- [ ] org.eclipse.jdt.core.compiler.problem.nonnullTypeVariableFromLegacyInvocation
- [ ] org.eclipse.jdt.core.compiler.problem.pessimisticNullAnalysisForFreeTypeVariables
- [ ] org.eclipse.jdt.core.compiler.problem.unlikelyCollectionMethodArgumentTypeStrict

**Comment by romani** [comment]
Fix is merged
