### ISSUE TITLE
EmptyLineSeparatorCheck: surviving mutant from REMOVE_CONDITIONALS

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#6350]
Identified at https://github.com/checkstyle/checkstyle/pull/6347#discussion_r245495718 ,

Line surviving mutant: https://github.com/checkstyle/checkstyle/blob/ea7b2dd0a9060d427273bd88909e370cb9f88436/src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheck.java#L422

Needs file named `InputEmptyLineSeparatorCommentPackage.java`:
````
//non-compiled with javac: non-compilable annotation, for testing
@Deprecated
package com.puppycrawl.tools.checkstyle.checks.whitespace.emptylineseparator;
````

Brief: To meet the conditions, we need a package with a annotation that is stored in a file that isn't package-info.java .
Specifics: The rest of the conditions in the method have to be met except for the line that is the surviving mutant. Child count of 0 is because there is only 1 annotation, which is the first child of the package definition, and it has no empty line or javadoc before it. Package must also be on line 2+. The mutation's condition has to be it's inverse to satisfy killing the mutation, so it must be a file that isn't package-info.java. This is what came up when I did a regression search as we have a similar file checkstyle elsewhere.

File isn't compilable because only package-infos can have annotations and we need this to be a non package-info file.

This mutation needs to be killed and was left surviving for now.

**Comment by romani** [comment]
Ideal solution is killed mutation without file in uncompiled folder

**Comment by rnveach** [comment]
Small correction to 1st post:
> Child count of 0 is because there is only 1 annotation, which is the first child of the package definition, and it has no empty line or javadoc before it.

Child count isn't 1 because `ANNOTATIONS` isn't empty and it contains an annotation. If there is no annotation, child count is 0 and since there is no javadoc before it, it prints the same violation and mutation survives.

We can kill mutation if we swap annotation with a javadoc and the input will be compilable.

**Comment by rnveach** [comment]
Fix was merged
