### ISSUE TITLE
Java Grammar: use TYPE_EXTENSION_AND instead of BAND in typecast expression

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#6354]
Taken from https://github.com/checkstyle/checkstyle/issues/6329#issuecomment-451961090
The AST for code
```
Object field = (Cloneable & Serializable) null;
```
is
```
    |--VARIABLE_DEF -> VARIABLE_DEF [5:4]
    |   |--MODIFIERS -> MODIFIERS [5:4]
    |   |--TYPE -> TYPE [5:4]
    |   |   `--IDENT -> Object [5:4]
    |   |--IDENT -> field [5:11]
    |   |--ASSIGN -> = [5:17]
    |   |   `--EXPR -> EXPR [5:19]
    |   |       `--TYPECAST -> ( [5:19]
    |   |           |--BAND -> & [5:30]
    |   |           |   |--TYPE -> TYPE [5:20]
    |   |           |   |   `--IDENT -> Cloneable [5:20]
    |   |           |   `--TYPE -> TYPE [5:32]
    |   |           |       `--IDENT -> Serializable [5:32]
    |   |           |--RPAREN -> ) [5:44]
    |   |           `--LITERAL_NULL -> null [5:46]
    |   `--SEMI -> ; [5:50]
```
There shouldn't be the `BAND` (binary and) token.  It should be `TYPE_EXTENSION_AND`.

**Comment by romani** [comment]
@pbludov , please do me favor and update javadoc for this token http://checkstyle.sourceforge.net/apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#TYPE_EXTENSION_AND to have example of AST.

**Comment by romani** [comment]
Please update title of issue to be exact, it be used in release notes.

**Comment by pbludov** [comment]
> @pbludov , please do me favor and update javadoc to have example of AST.
Please update title of issue to be exact, it be used in release notes.

Done.

**Comment by romani** [comment]
fix is merged.
