### ISSUE TITLE
Xpath: change implementation of the @text attribute

### ISSUE THREAD

**Issue by timurt** [checkstyle/checkstyle#6356]
@romani @rnveach 

Followed by
[Issue#6240](https://github.com/checkstyle/checkstyle/issues/6240) and [Issue#6115](https://github.com/checkstyle/checkstyle/issues/6115)

Current implementation does not allow us to query elements by their values.
For example, we want to query the following variable
```
$ cat TestClass.java
class TestClass {
  String country = "Kazakhstan";
}

$ java -jar checkstyle-8.15-all.jar -t TestClass.java
CLASS_DEF -> CLASS_DEF [1:0]
|--MODIFIERS -> MODIFIERS [1:0]
|--LITERAL_CLASS -> class [1:0]
|--IDENT -> TestClass [1:6]
`--OBJBLOCK -> OBJBLOCK [1:16]
    |--LCURLY -> { [1:16]
    |--VARIABLE_DEF -> VARIABLE_DEF [2:2]
    |   |--MODIFIERS -> MODIFIERS [2:2]
    |   |--TYPE -> TYPE [2:2]
    |   |   `--IDENT -> String [2:2]
    |   |--IDENT -> country [2:9]
    |   |--ASSIGN -> = [2:17]
    |   |   `--EXPR -> EXPR [2:19]
    |   |       `--STRING_LITERAL -> "Kazakhstan" [2:19]
    |   `--SEMI -> ; [2:31]
    `--RCURLY -> } [3:0]
```
We can query variable by its name `country` (`//VARIABLE_DEF[@text='country']`), but we cannot query it by its value `Kazakhstan`.

New implementation will make it possible to query by name and by value
Example xpath queries for previous variable:
```
By name: //VARIABLE_DEF[./IDENT[@text='country']]
By value: //VARIABLE_DEF[.//STRING_LITERAL[@text='Kazakhstan']]
```

**Comment by rnveach** [comment]
Xpath changed from
> `//VARIABLE_DEF[@text='country']`

to 
> `//VARIABLE_DEF[./IDENT[@text='country']]`

and some even
> `//VARIABLE_DEF[./IDENT[@text='country']]/IDENT[@text='country']`

I dislike this change.

**Comment by timurt** [comment]
> I dislike this change. The old way was much more readable and understandable.

Didn't we agree that we do not need this shortcut? [Issue#6240](https://github.com/checkstyle/checkstyle/pull/6315#issuecomment-450058696)

**Comment by rnveach** [comment]
The only shortcut I thought we agreed on removing was `@firstIdentText`. https://github.com/checkstyle/checkstyle/issues/6240#issuecomment-444362607

@romani can speak on his other comment but I think the change is making the xpath too complex, especially when you need to specify ident text twice.

**Comment by romani** [comment]
> I dislike this change. The old way was much more readable and understandable.
...
but I think the change is making the xpath too complex, especially when you need to specify ident text twice.

we agreed to follow AST structure completely, without any shortcuts and virtual attributes. It become a bit verbose but, it is absolute match to AST

AST is:
```
|--VARIABLE_DEF -> VARIABLE_DEF [2:2]
....
    |   |--IDENT -> country [2:9]
    |   |--ASSIGN -> = [2:17]
    |   |   `--EXPR -> EXPR [2:19]
    |   |       `--STRING_LITERAL -> "Kazakhstan" [2:19]
```

VARIABLE_DEF does not have text in AST, so it should not have it Xpath.
So Xpaths are as declared in issue description.
```
if you want to suppress by variable name: //VARIABLE_DEF[./IDENT[@text='country']]
if you want to suppress by variable value: //VARIABLE_DEF[.//STRING_LITERAL[@text='Kazakhstan']]
```
It will be user responsibility to write easy to read xpath. But when user look at AST, we can easily make xpath, even it could be a bit long.

@rnveach , please review issues one more time and lets finalize our expectation of xpath format.

**Comment by rnveach** [comment]
> without any shortcuts and virtual attributes

I am fine with shortcuts if they are a shortcut and make things easier.

> if you agree, please mark issue as approved.

Like I said I don't really agree with new format.
I am fine with following AST for now.

**Comment by romani** [comment]
We start with following ast, later on extend with simplification enhancements as we collect more experience

**Comment by rnveach** [comment]
Fix was merged
