### ISSUE TITLE
Jenkins: switch the build machine (slave) from hyper.sh to AWS spot instance

### ISSUE THREAD

**Issue by daniilyar** [checkstyle/checkstyle#6359]
Hyper.sh cloud will be terminated at Jan 15, so we need a stable replacement.
As Jenkins is living at AWS EC2 already, the best idea seems to be to use AWS EC2 Spot instances as new slaves via https://wiki.jenkins.io/display/JENKINS/Amazon+EC2+Plugin

**Comment by rnveach** [comment]
fix was merged
