### ISSUE TITLE
Feature request: Warn on throwing exceptions

### ISSUE THREAD

**Issue by mcandre** [checkstyle/checkstyle#6360]
Now that Java 8+ supports Optionals, we can improve our API's by returning errors as values, as opposed to using convoluted try/catch logic. Could we get a rule, disabled by default, that warns when:

* RuntimeException's or child classes are thrown, as these can lead to surprising production failures
* A method or interface declares that exceptions are expected to be thrown
* Checked exceptions are thrown

**Comment by romani** [comment]
> Checked exceptions are thrown .... RuntimeException's or child classes are thrown ...

https://checkstyle.org/writingchecks.html#Limitations - we are not type aware tool, we can not distinguish RuntimeException and checked exception.

> A method or interface declares that exceptions are expected to be thrown

try
https://checkstyle.org/config_coding.html#IllegalThrows
https://checkstyle.org/config_design.html#ThrowsCount
https://checkstyle.org/config_misc.html#DescendantToken

so conbination of them should cover most of your cases.


I am closing of this issue, as here we accept only clear issue with clear design.
All discussion should go to stackoverflow and our mail-list.
