### ISSUE TITLE
Fix pitest coverage for RightCurly

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#6367]
TODO:
revert commit - https://github.com/checkstyle/checkstyle/commit/3316f0b1a179c3ecd2ca3c21d9a81129282ba630 and https://github.com/checkstyle/checkstyle/commit/63d9db3900848b3d662383aefb5c336978f549a0

fix pitest coverage to be 100%, and kill all mutations, RightCurly should have no survived mutations.

discussion of coverage issues: https://github.com/checkstyle/checkstyle/pull/4247#pullrequestreview-189430650

-------

<a href="https://www.bountysource.com/issues/68536186-fix-pitest-coverage-for-rightcurly">
<img src="https://api.bountysource.com/badge/issue?issue_id=68536186">
</a>

**Comment by fzdy1914** [comment]
Working on this.

**Comment by romani** [comment]
@fzdy1914 , I placed bounty on issue from our donation budget, it would be good if test it how it works.

**Comment by rnveach** [comment]
Fix was merged

**Comment by rnveach** [comment]
@romani This is a bounty issue.

**Comment by romani** [comment]
please login to Bountysource and claim a bounty
