### ISSUE TITLE
EqualsAvoidNull: improper frame tracking

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#6373]
Based on discussions in https://github.com/checkstyle/checkstyle/issues/6353 ,

EqualsAvoidNull is not tracking the frames proper for when variables and parameters are declared. It causing random ordering issues on different runs because it sees variables in 2 different frames as wrongly being in the same frame and causing the 2 variables to be picked at random for violation discerning.

**Comment by rnveach** [comment]
@romani It turns out this issue was identified before but was closed when it couldn't be reproduced.
See
https://github.com/checkstyle/checkstyle/pull/5063#issuecomment-326855228
https://github.com/checkstyle/checkstyle/pull/5063#issuecomment-331678555

Created Issue: https://github.com/checkstyle/checkstyle/issues/5144 and closed.

**Comment by romani** [comment]
Fixed is merged.

Tokens are not possible to customize, so it is not breaking compatibility.
