### ISSUE TITLE
Hardcode google tokens in config

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#6385]
As discussed at https://github.com/checkstyle/checkstyle/issues/6381 ,

I think we should remove all default token usage in google's config and hardcode the list of tokens it uses for all checks. This way, if a new default token is added to a check then `AllChecksTest.testAllCheckTokensAreReferencedInGoogleConfigFile`([link](https://github.com/checkstyle/checkstyle/blob/master/src/test/java/com/puppycrawl/tools/checkstyle/internal/AllChecksTest.java#L369)) should ping it as not being used for google and force us to review it.

**Comment by sd1998** [comment]
@rnveach I am new to this project and would like to contribute can I start with this?

**Comment by rnveach** [comment]
@sd1998 You can start with it.
If it wasn't clear from the issue, we need the UT linked to, to require these tokens exist.

**Comment by romani** [comment]
@sd1998 , ply let us know if you have any problem to start contributing

**Comment by Nayan-kumar-Chawda** [comment]
Has there been any contributions in regards to fix this issue?

**Comment by rnveach** [comment]
There has not.

**Comment by pbludov** [comment]
fix is merged.

**Comment by romani** [comment]
@pbludov , please do not forget labels and milestone before closing issue.
