### ISSUE TITLE
Gradle console output hides later checkstyle warnings

### ISSUE THREAD

**Issue by mcandre** [checkstyle/checkstyle#6387]
The Gradle Checkstyle plugin stops output on the first set of warnings, so it is difficult to estimate how long it would take to resolve warnings for an entire project.

**Comment by rnveach** [comment]
@mcandre See http://checkstyle.sourceforge.net/report_issue.html#How_to_report_a_bug.3F .
We are not gradle plugin. We are the command line checkstyle plugin which gradle calls.

It looks like gradle plugin is hosted at https://github.com/gradle/gradle/ .
