### ISSUE TITLE
Command Line arguments should be allow to exclude a file

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#6399]
Ant allows to exclude a specific file.

https://github.com/checkstyle/checkstyle/blob/c5c8c32f999c692605166648900a576c496eb599/config/ant-phase-verify.xml#L142-L148

http://checkstyle.sourceforge.net/cmdline.html#Command_line_usage

>  -e, --exclude excludedDirectory - Directory to exclude from CheckStyle. The directory can be the full, absolute path, or relative to the current path. Multiple excludes are allowed.
-x, --exclude-regexp excludedDirectoryPattern - Directory pattern to exclude from CheckStyle. Multiple excludes are allowed. 

Both options say to exclude directory, not a file, and the source code agrees with the documentation.

https://github.com/checkstyle/checkstyle/blob/c5c8c32f999c692605166648900a576c496eb599/src/main/java/com/puppycrawl/tools/checkstyle/Main.java#L214-L215

I want to specify a file, because I was checking some things out with running `checkstyle_resources_checks.xml` through the command line and I can't fully reproduce it in the command line because I can't tell it to exclude the files that cause an exception.

UPDATE:
exclusion by file is possible by extending of existing CLI argument
`-e, --exclude excludedPath</code> - Directory/file to exclude from
          CheckStyle. The path can be the full, absolute path, or relative to the current path.`

**Comment by rnveach** [comment]
@romani Should this be a new option or should we extend the existing option to include files?
If it should be a new option, what letter(s) should we use for it? `ef` and `xf`?

**Comment by romani** [comment]
> -e, --exclude excludedDirectory - Directory to exclude from CheckStyle. The directory can be the full, absolute path, or relative to the current path. Multiple excludes are allowed.
-x, --exclude-regexp excludedDirectoryPattern - Directory pattern to exclude from CheckStyle. Multiple excludes are allowed.

What if we extend this properties to exclude Directory or File ?

**Comment by rnveach** [comment]
I am fine with this, but it will be considered a breaking change even though this is Main and we don't announce it as breaking.

**Comment by romani** [comment]
why it is breaking ?
all scripts that used such option will/should continue to work.

**Comment by rnveach** [comment]
For the regular expression exclude, people may have written their expressions too relaxed or not specific enough and could match a file with this change and cause the file to be accidentally excluded. If it isn't considered breaking, people would still have to re-verify their scripts for no hidden problems.

**Comment by romani** [comment]
fix is merged.
