### ISSUE TITLE
OneStatementPerLine should tolerate the Java 7 try-with-resources

### ISSUE THREAD

**Issue by isopov** [checkstyle/checkstyle#64]
The OneStatementPerLine keeps the Java code tidy. However, in Java 7, the new try-with-resources was added, which implies that several Closeable resources can be created within one try statement:

```
try (Reader xml = toXML(data); Reader xslt = createXSLReader(); WritableByteBuffer out = createOutputBuffer();) {
   ...
} catch (final IOException e) {
  ...
}
```

OneStatementPerLine should be configurable to tolerate this use case. Or as a more generic solution, allow regexes for exceptions to the rule.

**Comment by philipa** [comment]
I agree with the above, but this fails OneStatementPerLine for me:

```java
        try (
            OutputStream fos = new FileOutputStream("foo");
            OutputStream fos2 = new FileOutputStream("bah");) {
        }
```

**Comment by romani** [comment]
@philipa, please create new issue for this
