### ISSUE TITLE
Allow excluding certain classes from illegal imports check

### ISSUE THREAD

**Issue by OlgaMaciaszek** [checkstyle/checkstyle#6401]
Please consider adding a possibility to exclude specified classes from the illegal imports check.

--------------

An example of a scenario where this would be useful:
We wanted to exclude guava (`com.google.common`) from our projects and add it under `illegalPkgs` in `IllegalImportCheck`. However, it appears that an external interface we need to implement as part of our feature uses one of the classes from that package (`com.google.common.reflect.TypeToken`) in method signatures. 

It would be convenient to have a possibility to allow just specific classes from a package (in our scenario `TypeToken`) to be imported and fail the check when any other class from a specified package is imported.

**Comment by rnveach** [comment]
@OlgaMaciaszek Have you considered using [ImportControl](http://checkstyle.sourceforge.net/config_imports.html#ImportControl) ? It will allow you to ban a package but only allow specific classes in it.
It would be written something like this:
````
<import-control pkg="com.mycompany">
  <allow class="my.package.ClassName"/>
  <disallow pkg="my.package"/>
</import-control>
````

Another possibility is `IllegalImport` has `illegalClasses` as a regular expression for the fully qualified class name. Can you create an expression that doesn't match the good class but will match all the bad ones?
This might be similar to https://github.com/checkstyle/checkstyle/blob/master/config/checkstyle_checks.xml#L180 .

**Comment by OlgaMaciaszek** [comment]
@rnveach thanks. The `ImportControl` approach would work for a single project, but we tend to use a parent project with all our setup and not store buildtime config files in every project, so we I wouldn't like to add the import-config.xml files to separate projects.

**Comment by romani** [comment]
https://checkstyle.org/config_imports.html#IllegalImport
prints type in message
https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/com/puppycrawl/tools/checkstyle/checks/imports/messages.properties#L13

it might be better to suppress not by file, but by `message` https://checkstyle.org/config_filters.html#SuppressionFilter , but here is only one problem it that build in different locales might renerate different message by format, but you can make regexp to avoid referencing symbols that does not belong to type name.
