### ISSUE TITLE
new filter SuppressionSingleFilter 

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#6402]
Identified at https://github.com/checkstyle/checkstyle/pull/6368#issuecomment-459574342 ,

Since we are creating a treewalker filter, we also need a normal filter that can filter out non-AbstractCheck violations.

See https://github.com/checkstyle/checkstyle/issues/5879#issue-328745344 for reasons why this single filter is needed in config.

-------

<a href="https://www.bountysource.com/issues/69502915-new-filter-suppressionsinglefilter">
<img src="https://api.bountysource.com/badge/issue?issue_id=69502915">
</a>

**Comment by rnveach** [comment]
This filter is almost identical to the TreeWalker one.
Some differences are it must extend `Filter` instead of `TreeWalkerFilter`, it must not have anything related to xpath's query, and it must try to wrap `SuppressElement` instead of `XpathFilter`.

**Comment by jack870131** [comment]
@romani @rnveach So do I need to create a new filter like I did in SuppressionXpathSingleFilter?
Is there any similar filter that I could refer to?

**Comment by rnveach** [comment]
> So do I need to create a new filter like I did in SuppressionXpathSingleFilter?

Yes.

> Is there any similar filter's code that I could refer to?

Just like the `SuppressionXpathSingleFilter`, the new filter should be a wrapper of `SuppressElement`. You can look to it's code and tests to refer to.

**Comment by romani** [comment]
@jack870131 , issue got a bounty, try to take it.

**Comment by jack870131** [comment]
@romani OK, thanks a lot for informing me. I think I would have time to do it. I would take it.

**Comment by romani** [comment]
@jack870131 , there is high demand for this filter, see https://github.com/checkstyle/checkstyle/pull/6781#issuecomment-495936561 . Please find time to implement it.

**Comment by jack870131** [comment]
@romani OK, sorry for taking so long to reply. I got the final exam these days and I also have some projects to do. I would try to find time to implement it. Thx.

**Comment by romani** [comment]
Fix is merged.

Please claim bounty :) .
