### ISSUE TITLE
Slowdown with UnusedImportsCheck

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#6403]
Based on the DebugListener I created in https://github.com/rnveach/checkstyle/commits/more_audits to show how long checkstyle spends executing in various parts during a run, `UnusedImportsCheck` takes the most time to execute of all our Checks. A total of 3.3 seconds during a 33 second run.

````
Starting audit...
------------------
Run Time: 32.841

...

Checks: (141)
...
UnusedImportsCheck	448037	3.302	0.0	0.271	0.0
...
````
(columns are total calls, total time in seconds, min time, max time, and average)

When I added custom watches to see where the issue was, it was happening with the `INLINE_TAG_PATTERN` when calling `find()`.
https://github.com/checkstyle/checkstyle/blob/a73ff0890c27cbe8affc1a55f2710a231687bd85/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/utils/InlineTagUtil.java#L39 

The regular expression is bad because it starts with `.*?` and is only doing a `find` and not a match all. When this section is removed the time for the check run drops almost to 0.3.

**Comment by romani** [comment]
fix is merged.
