### ISSUE TITLE
Allow EmptyLineSeparator allowNoEmptyLineBetweenFields to only apply to fields that are on a single line

### ISSUE THREAD

**Issue by dalewking** [checkstyle/checkstyle#6409]
allowNoEmptyLineBetweenFields on EmptyLineSeparator check allows for having no blank line between fields. The problem is that applies to all fields. I would like to distinguish between fields that fit on a single line and field declarations that span multiple lines (e.g. has an annotation or a long initializer). In my view multi-line field declarations should require the separator.

**Comment by rnveach** [comment]
@dalewking Please see http://checkstyle.sourceforge.net/report_issue.html#How_to_request_new_feature_for_existing_functionality.3F on what we need.

This check doesn't support XPath as it only logs the line number and not the line and column. Issue #5777 will add this support. Even with XPath support, I don't think it allows querying line/column numbers. So XPath won't be an option for a little while.

**Comment by romani** [comment]
@dalewking , please provide bunch of code example with clear definition of config and where to have violation and where do not place violation.

**Comment by romani** [comment]
no details provided, issue is closed ...
