### ISSUE TITLE
can't disable checkstyle

### ISSUE THREAD

**Issue by noelo-cohelo** [checkstyle/checkstyle#6419]
When I right-click the project in Eclipse 2018-09 (I use Checkstyle Plugin 8.12), then Checkstyle -> **Deactivate Checkstyle**, nothing happens. I still see violations. I tried re-opening file, whole project, and also cleaning it - without success.

**Comment by rnveach** [comment]
We are not eclipse-cs plugin for eclipse. We are only command line utility.
Please report issue at https://github.com/checkstyle/eclipse-cs .
