### ISSUE TITLE
bug with NewlineAtEndOfFileCheck

### ISSUE THREAD

**Issue by zenglian** [checkstyle/checkstyle#6422]
platform: windows 10
git: configured to use unix style newline

Expected: No error.
Actual: reports NewlineAtEndOfFileCheck error.

My guess: The file ends with "\n", but the NewlineAtEndOfFileCheck  is looking for "\r\n".

**Comment by rnveach** [comment]
> My guess

Guesses won't help us solve the problem. Please see http://checkstyle.sourceforge.net/report_issue.html#How_to_report_a_bug.3F .

I am on windows and the check works fine for me. Ensure `core.autocrlf` is set to `true` and `NewlineAtEndOfFileCheck` is set to system default. If you are just setting `core.autocrlf` then you must wipe your directory and do a hard reset to fix all the line endings in the files.

**Comment by zenglian** [comment]
`autocrlf` must be `false`, since some are working on linux.
How to configure `NewlineAtEndOfFileCheck` to use `\n` instead of `system`?

**Comment by zenglian** [comment]
This is configurable.
