### ISSUE TITLE
Remove powermock

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#6439]
Drop powermock completely and use a suppression list similar to pitest to manage uncovered code coverage or rewrite production code so just reflection can be used without mocking.
If that isn't acceptable, the next best thing is to completely isolate powermock tests to their own class(es) but this probably won't solve the main problem.

Reasons supporting removal of powermock:
https://github.com/checkstyle/checkstyle/pull/6438#discussion_r258037140
https://github.com/checkstyle/checkstyle/pull/6435#issuecomment-464937668
https://github.com/checkstyle/checkstyle/pull/6424#issuecomment-463593931
https://github.com/hcoles/pitest/issues/230#issuecomment-463622773
https://github.com/checkstyle/checkstyle/issues/5678#issuecomment-379553644

**Comment by romani** [comment]
I am not sure it is possible as powermock was used mock static methods that are out of our code .

But I am agree to separate them in special Test classes or ..... To avoid conflicts between powermock and pitest.

**Comment by rnveach** [comment]
> I am not sure it is possible

Like I stated above, I am thinking we need to forgo the 100% code coverage and just remove them completely.

> powermock was used mock static methods

I looked at some for another issue, and the ones I was seeing was to clear hard to hit catch exceptions, code in the middle of a method, and tests that would require us to have classes in weird packages. You can still call static/private methods with reflection.

> avoid conflicts between powermock and pitest

Two of my examples was conflict between normal tests and powermock too. So it is not just pitest. No one wants to work with powermock.
I will split powermock tests to their own section and we can see how that goes for now.

**Comment by rnveach** [comment]
`ImportControlLoader` is package private which prevents moving power tests to a separate package.

**Comment by rnveach** [comment]
Fix was merged. I will continue to change powermock tests to normal tests.
