### ISSUE TITLE
Update Maven Plugins used by Checkstyle

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#644]
Checkstyle uses some outdated plugins. We should update them. Here is result of [versions:display-plugin-updates](http://mojo.codehaus.org/versions-maven-plugin/display-plugin-updates-mojo.html) command:

```
The following plugin updates are available:
  org.antlr:antlr4-maven-plugin ............................ 4.3 -> 4.5
  maven-antrun-plugin ...................................... 1.7 -> 1.8
  maven-assembly-plugin ................................ 2.2.1 -> 2.5.3
  maven-compiler-plugin .................................. 2.3.2 -> 3.2
  maven-eclipse-plugin ..................................... 2.8 -> 2.9
  maven-enforcer-plugin .................................. 1.3.1 -> 1.4
  maven-gpg-plugin ......................................... 1.4 -> 1.6
  maven-jar-plugin ....................................... 2.3.1 -> 2.5
  maven-jxr-plugin ......................................... 2.4 -> 2.5
  maven-shade-plugin ....................................... 1.4 -> 2.3
  maven-surefire-plugin ................................ 2.17 -> 2.18.1
  org.eluder.coveralls:coveralls-maven-plugin .......... 2.2.0 -> 3.0.1
  org.jacoco:jacoco-maven-plugin  0.7.1.201405082137 -> 0.7.2.201409121644

 The following plugins do not have their version specified:
   maven-clean-plugin ........................ (from super-pom) 2.6.1
   maven-deploy-plugin ....................... (from super-pom) 2.8.2
   maven-install-plugin ...................... (from super-pom) 2.5.2
   maven-resources-plugin ...................... (from super-pom) 2.7
```

Are there any reasons to not update some of the above? Should I create separate pull request for each plugin?

**Comment by romani** [comment]
the reasons:
- no need to be on latest version till it is required, as version upgrade could cause problems
- we do not have big team to keep an eye on that constantly, I try to update plugins ones in half year.
- I do not know tool that could automate that, if you know please contribute automation of that process.

I am ok with such update, please provide PR.

**Comment by mkordas** [comment]
That's right, version upgrade may cause problems, so I think there is no point of full automation of that process. I have only dirty script that takes dependencies to update and pushes new versions on branches (each dependency separately). Then I can create pull requests and we can observe Travis. 

I'm not convinced that we should update all of them for 6.4 release - it may be too risky. I'll start with some safest ones like surefire, jacoco, enforcer, clean or install.

**Comment by romani** [comment]
good plan, you can share your script in gist.github.com, I could run it periodically too.

**Comment by romani** [comment]
off topic: It will be very good to have a badge for dependecies status as javascript people have https://github.com/jirutka/maven-badges

**Comment by romani** [comment]
interesting web site - https://www.versioneye.com/java/com.puppycrawl.tools:checkstyle/6.3 
I could put a badge in our README file just for fun.
Not all dependencies are shown but it already works.

**Comment by mkordas** [comment]
Looks like [VersionEye](https://www.versioneye.com/java/com.puppycrawl.tools:checkstyle/6.3) is buggy. E.g. we don't need to update JUnit, but it is listed...

Script that I'm using to update dependencies can be found [here](https://gist.github.com/mkordas/a6fa7e672b9aea6d9079#file-update-sh). Please use with caution!

**Comment by mkordas** [comment]
Maven JAR Plugin 2.6 was just released, PR proposed.

**Comment by mkordas** [comment]
Looks like we are done for now with updates :smiley: 
```
[INFO] --- versions-maven-plugin:2.1:display-plugin-updates (default-cli) @ checkstyle ---
[INFO]
[INFO] All plugins with a version specified are using the latest versions.
[INFO]
[INFO] All plugins have a version specified.
[INFO]
[INFO] Project defines minimum Maven version as: 3.0.1
[INFO] Plugins require minimum Maven version of: 3.0.1
[INFO]
[INFO] No plugins require a newer version of Maven than specified by the pom.
```
