### ISSUE TITLE
Wrong public identifier in doctype of example empty suppressions file

### ISSUE THREAD

**Issue by Vampire** [checkstyle/checkstyle#6449]
The public identifier in http://checkstyle.sourceforge.net/files/suppressions_none.xml is version 1.0, while the system identifier is 1.2.
I guess it should actually both be 1.2 as at https://github.com/checkstyle/checkstyle/blob/master/config/suppressions.xml.

https://github.com/checkstyle/checkstyle/blob/master/src/site/resources/files/suppressions_none.xml

**Comment by rnveach** [comment]
Most likely yes.
The reason why nothing picked this up is because our internal XML loader overrides what file to be loaded when it finds a system id it recognizes.
