### ISSUE TITLE
MissingDeprecated description has a typo

### ISSUE THREAD

**Issue by Vampire** [checkstyle/checkstyle#6451]
> When this property is set to true check ignore cases when JavaDoc is missing, but still warns when JavaDoc is present but either `@deprecated` is missing from JavaDoc or `@deprecated` is missing from the element.

should be

> When this property is set to true check ignore cases when JavaDoc is missing, but still warns when JavaDoc is present but either `@deprecated` is missing from JavaDoc or `@Deprecated` is missing from the element.

**Comment by romani** [comment]
Fix is merged
