### ISSUE TITLE
MissingOverride javaFiveCompatibility true in checkstyle_checks.xml

### ISSUE THREAD

**Issue by Vampire** [checkstyle/checkstyle#6452]
https://checkstyle.org/config_annotation.html#MissingOverride

The description of MissingOverride javaFiveCompatibility says that it should be avoided and is recommended to only use it on Java 5 source. But in `checkstyle_checks.xml` it is set to true. Your sources are Java 8 and this file is recommended as a starter for new users that want all checks, so maybe this should be set to false / removed?

https://github.com/checkstyle/checkstyle/blob/master/config/checkstyle_checks.xml#L175

**Comment by romani** [comment]
We should not use this property with true value, we should use Check in default config.
