### ISSUE TITLE
Overly complex default regex in SuppressWarnings format

### ISSUE THREAD

**Issue by Vampire** [checkstyle/checkstyle#6453]
The default regex for SuppressWarnings format is `^$|^\s+$`.
I'd suggest to simplify this to just `^\s*$` which should have the same effect.
Actually I would even use `^\s*+$` as little performance tweak.

**Comment by romani** [comment]
Please explain why  extra performance could be gained with last variant of regexp.

**Comment by Vampire** [comment]
Assume you have a line with 50 spaces and then an `a`.

With greedy qualifier like `^\s*$`, the regex engine will math the string start, then the 50 spaces, then it sees the `a` cannot match the end of string anchor. Then it will backtrack and give up one character, so the `\s*` matches only 49 spaces and then checks whether the now following space matches against the end of string anchor and so on, until `\s*` matches no character at all and the end of string character still does not allow the regex to complete and the match fails.

With the possessive quantifier backtracking is prevented, so once matched the match is atomic, so with `^\s*+$`, the regex engine will math the string start, then the 50 spaces, then it sees the `a` cannot match the end of string anchor. Then as there is no dynamic part into which you can backtrack the match instantly fails.

Possessive quantifiers are a kind of fail-fast measure if you know that what comes after the quantifier cannot be matched inside the quantifier ever. In this case, the end of string can never occur within a sequence of spaces.

What would not work is `^\s*+\s$`, it would fail even on a space-only string, because backtracking would be necessary, so that the `\s*+` only matches 49 spaces in the second step and the second `\s` can match a single space which will not gonna happen due to the possessiveness, there `^\s*\s$` would be necessary..

**Comment by romani** [comment]
Thanks a lot for details.
Default should be `^\s*+$`.
