### ISSUE TITLE
EmptyCatchBlock change property types to Regexp

### ISSUE THREAD

**Issue by Vampire** [checkstyle/checkstyle#6455]
The `EmptyCatchBlock` check documentation states that both properties are of type `String`, shouldn't this be `Regular Expression`?

https://checkstyle.org/config_blocks.html#EmptyCatchBlock

**Comment by rnveach** [comment]
I agree with this.
The setters are String and that is why our documentation validator didn't pick this up.
https://github.com/checkstyle/checkstyle/blob/a73ff0890c27cbe8affc1a55f2710a231687bd85/src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/EmptyCatchBlockCheck.java#L159
https://github.com/checkstyle/checkstyle/blob/a73ff0890c27cbe8affc1a55f2710a231687bd85/src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/EmptyCatchBlockCheck.java#L171

**Comment by romani** [comment]
Let's consider this issue as not a breaking changes,. Sonar plugin already treat such fields as regexp https://github.com/checkstyle/sonar-checkstyle/blob/4ee83573f003aa889f1e745cc27692f1e1048c12/checkstyle-sonar-plugin/src/main/resources/org/sonar/plugins/checkstyle/rules.xml#L2009

**Comment by romani** [comment]
Fix is merged
