### ISSUE TITLE
Remove PARAMETER_DEF from AnnotationLocation

### ISSUE THREAD

**Issue by Vampire** [checkstyle/checkstyle#6462]
With the reasoning from #6416:

Quote from @romani:
> All that tokens are not related to original idea of Check `Check enforce to locate annotations immediately after documentation block and before target element, annotation should be located on separate line from target element.` ... attention to `documentation block`.
Line wrapping that is possible with annotation usage should be covered by some other Check, I am not ready even tell about possible design for new Check .... live/users will show us what might be valuable in such validations.

`PARAMETER_DEF` should not be supported in `AnnotationLocation` check as parameters has no documentation and this Check is mostly for targets with javadocs. If somebody need to validate location of annotation in parameters  - new Check need to be created.

This would also simplify the implementation, because parameters are specially treated anyway, having a single annotation with or without parameters on the same line with the parameter is always allowed though the documentation does not indicate this. This special treatment can also be removed.

If the `PARAMETER_DEF` handling stays, then at least the documentation should be updated to describe the special treatment of parameters for which only a small subset like multiple annotations on the same line are checked.

**Comment by romani** [comment]
fix is merged.
