### ISSUE TITLE
Do not handle local variables for VARIABLE_DEF in AnnotationLocation

### ISSUE THREAD

**Issue by Vampire** [checkstyle/checkstyle#6463]
With the reasoning from #6416:

Quote from @romani:
> All that tokens are not related to original idea of Check `Check enforce to locate annotations immediately after documentation block and before target element, annotation should be located on separate line from target element.` ... attention to `documentation block`.
Line wrapping that is possible with annotation usage should be covered by some other Check, I am not ready even tell about possible design for new Check .... live/users will show us what might be valuable in such validations.

`AnnotationLocation` check for `VARIABLE_DEF` should only handle field definitions, but no local variable defintions as they have no documentation.

This would also simplify the implementation, because local variable definitions in for-each loops and for-loop-initializers are specially treated anyway, having a single annotation with or without parameters on the same line with the parameter is always allowed though the documentation does not indicate this. This special treatment can also be removed.

If the local variable defintion handling stays, then at least the documentation should be updated to describe the special treatment of local variable definitions in for-each loops and for-loop-initializers for which only a small subset like multiple annotations on the same line are checked.

Documentation should updated anyway, even if the local variable handling gets removed / local variables handling suppressed, the documentation should state that it is only effective on field definitions, not on local variable definitions.

ATTENTION: If users would like to validate location annotation over local variables , new Check should be created. That will have set of options to required to satisfy requirements, wihtout any conflicts with annotations over declaration elements that might have javadoc.

**Comment by romani** [comment]
> This would also simplify the implementation, because local variable definitions in for-each loops and for-loop-initializers are specially treated anyway

we should update documentation to clearly state that this Check is only for blocks/statements that might have javadoc. If required, implementation should be adjusted also.

**Comment by rnveach** [comment]
@romani This feature was requested for by Apache Apex in https://github.com/checkstyle/checkstyle/issues/3117 though it seems they are still on old 6.15.
https://github.com/apache/apex-core/blob/d17f464fcaf19778e2f8edbe2b03419151558068/pom.xml#L406

**Comment by Vampire** [comment]
As far as I can see, that ticket requested the special handling, but the outcome will be the same, as relevant occurrences are now not handled at all anymore.

**Comment by romani** [comment]
There will be only minor breaking compatibility, that Check stop to violate code on local variables that have same line annotation, but user wants it be to be separate line. New Check should cover this.
Coverage of all possible cases by one Check with numerous properties is error prone, we already learned that lessson.

**Comment by romani** [comment]
fix is merged.
