### ISSUE TITLE
New check UncalledPrivateConstructor

### ISSUE THREAD

**Issue by Vampire** [checkstyle/checkstyle#6467]
If you have a private constructor that is not called by any code in the class, not by any other constructor, not by any factory method, not by any static field initializer, ..., there can basically only two reasons for this.

One reason is, the constructor was used previously but is superfluous now, or should have been used but is not yet.

The other reason is, to prevent instantiation, for example of a static utility class (being it an anti-pattern or not). For those, it is good practice to also throw `UnsupportedOperationException` or similar, to also prevent instantiation via reflection which would still work after making the constructor accessible, but not without bytcode manipulation if an exception is thrown.

So I'd like to suggest a new check that
- reacts on all private constructors
- searches calls to them
- if any found
  - check is done successfully
- if none found
  - if there is at least one other accessible constructor
    - log "uncalled private constructor"
  - if all constructors are private
    - check whether there is only one statement in the constructor which is an unconditional exception throw
      - if not log "should only throw exception"
      - if no statement at all log "should throw exception"

**Comment by romani** [comment]
In general I am ok, 
but it is good to proceed with more details , please review format of description at https://github.com/checkstyle/checkstyle/issues/5884 , we need to agree on something like this, to start implementation and avoid bunch of refactoring. Ones you +2 admins agree, we mark issue as approved and you are welcome with PR.

**Comment by Vampire** [comment]
I'm not fully sure what you miss here.
Do you need some code examples or what?
I just want to avoid wasting my time with the wrong details.

**Comment by romani** [comment]
examples of code (with trailing comments like "//violation") + examples of config.
ideally in form like - https://github.com/checkstyle/checkstyle/blob/master/src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationlocation/InputAnnotationLocationEnum.java
to be absolutely clear on expected behavior, it is new format of how we do UTs, we agreed internally that new code is appearing like this. Format is  comment is not defined, it could be any clear way to define configuration, even copy paste of XML.

With such details it more chance to find contributor, as inside/outside contributors do not like obscure/unclear issues.

**Comment by Vampire** [comment]
You mean like this?
I think I got pretty much most variations covered:
```java
import java.security.SecureRandom;

/**
 * For all but the last two config should be:
 * allowedExceptions = [java.lang.UnsupportedOperationException]
 */
class Foo1 {
    private Foo1() { // no violation (called)
    }

    static void createFoo1() {
        new Foo1();
    }
}

class Foo2 {
    static final Foo2 INSTANCE = new Foo2();

    private Foo2() { // no violation (called)
    }
}

class Foo3 {
    static final Foo3 INSTANCE;

    static {
        INSTANCE = new Foo3();
    }

    private Foo3() { // no violation (called)
    }
}

class Foo4 {
    private Foo4() { // no violation (called)
    }

    Foo4(Void nothing) { // no violation (not private)
        this();
    }
}

class Foo5 {
    private Foo5() { // no violation (only throws exception)
        throw new UnsupportedOperationException("Dare you!");
    }
}

class Foo6 {
    private Foo6() { // violation "should throw exception"
    }
}

class Foo7 {
    private Foo7() { // violation "should only throw exception"
        System.out.println("foo");
        throw new UnsupportedOperationException("Dare you!");
    }
}

class Foo8 {
    private Foo8() { // violation "should only throw exception"
        if (new SecureRandom().nextBoolean()) {
            throw new UnsupportedOperationException("Dare you!");
        }
    }
}

class Foo9 {
    private Foo9() { // violation "uncalled private constructor"
    }

    Foo9(Void nothing) { // no violation (not private)
    }
}

class Foo10 {
    private Foo10() { // violation "should throw exception"
    }

    private Foo10(Void nothing) { // violation "should throw exception"
    }
}

class Foo11 {
    private Foo11() { // violation "uncalled private constructor"
    }

    private Foo11(Void nothing) { // no violation (called)
    }

    Foo11(Void nothing, Void stillNothing) { // no violation (not private)
        this(nothing);
    }
}

class Foo12 {
    private Foo12() { // no violation (called)
    }

    private Foo12(Void nothing) { // no violation (called)
        this();
    }

    Foo12(Void nothing, Void stillNothing) { // no violation (not private)
        this(nothing);
    }
}

class Foo13 {
    private Foo13() { // violation "should only throw UnsupportedOperationException exception"
        throw new RuntimeException("Dare you!");
    }
}

/**
 * For this config should be:
 * allowedExceptions = [java.lang.RuntimeException]
 */
class Foo14 {
    private Foo14() { // violation "should only throw RuntimeException exception"
        throw new UnsupportedOperationException("Dare you!");
    }
}

/**
 * For this config should be:
 * allowedExceptions = [java.lang.RuntimeException]
 */
class Foo15 {
    private Foo15() { // no violation
        throw new RuntimeException("Dare you!");
    }
}
```

**Comment by romani** [comment]
Checkstyle is not type aware tool, we can not distinguish non default ctors. So this Check should validate only default ctors.

Does it work for you ?

**Comment by Vampire** [comment]
Ah, right, you cannot distinguish between the arguments if there are multiple constructors with the same amount of parameters. :-(
When restricting to parameterless ctor (what I guess you mean when you say default ctor), that greatly limits the usefulness of the check.
It would surely be better than nothing, but maybe the check could work with the amount of parameters if the constructors have different parameter counts or maybe intelligently find some type from literals or forwarded parameters?

**Comment by romani** [comment]
> constructors have different parameter counts or maybe intelligently find some type from literals or forwarded parameters?

it will produce bunch of false-positives and users will disable such Check. 

Please update description to limit it only to parameterless c-tor. To let me approve new Check I need to see design, naming of all properties, examples of behavior.

**Comment by Vampire** [comment]
Why would it produce a bunch of false-positives?
My last suggestion was to avoid false-positives by:
- If constructor has unique parameter count, calls can reliably detected
- If multiple constructors have the same paramter count, calls can maybe differentiated by literals in parameters and similar, if calls can reliably detected by literals or method parameter types or similar, fine, if some call can not be differentiated properly, count it as call for all constructors with that amount and thus do not report a violation

This way you will probably have some false-negatives, but should be able to completely avoid false-positives.

**Comment by romani** [comment]
> If constructor has unique parameter count, calls can reliably detected

No, type of arguments matter, if there will be bunch of c-tors with same amount of parameters but with different types, you can not distinguish them. There might be use of basic/interface types, casting to type (not exact type), ... . It is general design limitation that poison bunch of ideas of automatic bad code detection.
You can start implementation and target our https://github.com/sevntu-checkstyle/sevntu.checkstyle project, where we host ideas to get maturity is we are not sure in success. If during testing you will prove that it will work reliably ... ok we will migrate it to main repo.

**Comment by romani** [comment]
if somebody would like to make it happen , please open new issue in sevntu to make it or do it in any project outside and share link to it here.
