### ISSUE TITLE
Option to ArrayTrailingComma or new check that means the reverse

### ISSUE THREAD

**Issue by Vampire** [checkstyle/checkstyle#6469]
Imho it looks strange to have a trailing comma, so I'd rather like to be able to check that no trailing comma is ever used. This could either be done as a property of the `ArrayTrailingComma` that reverses its meaning or as a separate check that does the reverse.

It could also be considered to make a new check alltogether that also incorporates enums and is just called `TrailingComma`. It could be configured via `tokens` on what to apply (enum / array) and via property if commas are enforced or forbidden. Such a check would then deprecate the `ArrayTrailingComma` check actually.

**Comment by romani** [comment]
>Such a check would then deprecate the ArrayTrailingComma check actually.

We do not deprecate something that might be used. I use this Check, it is very useful, I even noticed that language as Scala did not have such syntax originally and in recent versions such feature was added.

We respect others to have different styles preferences. If you need this, you need to create new Check and we can keep it our project. In documentation you can reference the it conflicts with some other Checks.

In you are interested to contribute new Check let's open new issue and discuss all details/names/behavior/design

**Comment by Vampire** [comment]
I didn't know the deprecation policy that you follow.
I don't doubt this check is useful for people that want the trailing comma.
I didn't say it should be removed.
I just said that the same check could handle arrays and enums, where the trailing comma is the same topic and handling it in this check that is called `ArrayTrailingComma` feels wrong.
Just because of that I suggested a generic one that can do both and would make this one obsolete, but if that doesn't fit in your deprecation policy, then not, no problem, were just thoughts.

But why a new issue with the same text as here?
My request is still the same, to be able to do the reverse check, that the trailing comma is always absent.
Either by a property to the `ArrayTrailingComma` check or by a new conflicting check.

**Comment by Vampire** [comment]
With 8.18 such behavior can be achieved with
```xml
<module name="IllegalToken">
    <property name="id" value="trailingComma"/>
    <property name="tokens" value="COMMA"/>
    <message key="illegal.token" value="Do not use trailing comma."/>
</module>
<module name="SuppressionXpathSingleFilter">
    <property name="id" value="trailingComma"/>
    <property name="query" value="(
                                      //ARRAY_INIT/*[self::COMMA and not(position() = (last() - 1))],
                                      //ENUM_DEF/OBJBLOCK/*[self::COMMA and not(position() = (last() - 1))],
                                      //COMMA[not(parent::ARRAY_INIT or parent::OBJBLOCK/parent::ENUM_DEF)]
                                  )"/>
</module>
```

**Comment by romani** [comment]
There are bunch of nuances with trailing comma in enums , please review https://github.com/sevntu-checkstyle/sevntu.checkstyle/issues/464 , and hanging PR where it becomes clear that easy say than done.

If you would like to contribute idea/design, please come with details on names, code and behavior on then of Check with certain config.

**Comment by Vampire** [comment]
Ahh, no, I'm not going to read 174 comments.
Especially as I'm suggesting a check or property that does the opposite, ensuring that array and enum definitions do **not** have the trailing comma.

**Comment by romani** [comment]
It is better to create new Check(s) like NoTrailingComma, it is better to allow user to choose target of validation array or/and enum. 
Please provide design of Check and examples of behavior.

**Comment by Vampire** [comment]
> It is better to create new Check(s) like NoTrailingComma, it is better to allow user to choose target of validation array or/and enum.
> Please provide design of Check and examples of behavior.

Isn't that what I suggested as second alternative?
A check called `TrailingComma` that deprecates `ArrayTrailingComma`.
It will have a boolean property on whether to enforce trailing commas or prevent trailing commas
and support configurable token types `ARRAY_INIT` and `ENUM_DEF`.

Or if you like separate checks more than the boolean, then `TrailingComma` and `NoTrailingComma`, bot with the configurable token types `ARRAY_INIT` and `ENUM_DEF`.

Examples I thought would be obvious:

Bad code for commas prevented, inverse for the inverse:
```java
enum Foo1 {
  FOO,
  BAR,
  ;
}
enum Foo2 {
  FOO,
  BAR,;
}
enum Foo3 { FOO, BAR,; }
enum Foo4 {
  FOO,
  BAR,
}
enum Foo5 { FOO, BAR, }
```

Good code for commas prevented, inverse for the inverse:
```java
enum Foo1 {
  FOO,
  BAR
  ;
}
enum Foo2 {
  FOO,
  BAR;
}
enum Foo3 { FOO, BAR; }
enum Foo4 {
  FOO,
  BAR
}
enum Foo5 { FOO, BAR }
```

**Comment by romani** [comment]
I would highly recommend to make two separate Checks, as they will cover completely different tokens with different specifics. `tokens`  property is not very user friendly. User better activate special module, rather then figure out how to configure module.
One more benefit of separate Checks is that life show us that there are interersting cases that are not common and new properties appear to allow some cases, and keep violating others. In such cases single Check is problem. But then Checks are specific to token, it have full freedom to customize behavior and still have reasonable(non conflicting) design of properties. 

I think it is better to close this issue and open two separate issues and discuss exact design/naming/behavior .

**Comment by Vampire** [comment]
Followups created
