### ISSUE TITLE
Remove AvoidInlineConditionals from sun_checks.xml

### ISSUE THREAD

**Issue by Vampire** [checkstyle/checkstyle#6470]
Maybe I'm blind, but where does the Sun style guide forbid the ternary operator?
The sole mention I find in https://www.oracle.com/technetwork/java/codeconventions-150003.pdf is, that the condition should be parenthesized if it contains a binary operator.

https://checkstyle.org/config_coding.html#AvoidInlineConditionals

>Rationale: Some developers find inline conditionals hard to read, so their employer's coding standards forbid them.

**Comment by romani** [comment]
https://www.oracle.com/technetwork/java/javase/documentation/codeconventions-137265.html#353
ternary operator is completely ok by Sun style, at least in its latest form.

I do not see "Sun" in our documentation for this Check. "Some" is not a "Sun".
Please recheck one more time.
