### ISSUE TITLE
Unclear rational in ExplicitInitialization

### ISSUE THREAD

**Issue by Vampire** [checkstyle/checkstyle#6472]
The rational says

> Rationale: Each instance variable gets initialized twice, to the same value. Java initializes each instance variable to its default value (0 or null) before performing any initialization specified in the code. So in this case, x gets initialized to 0 twice, and bar gets initialized to null twice. So there is a minor inefficiency. This style of coding is a holdover from C/C++ style coding, and it shows that the developer isn't really confident that Java initializes instance variables to default values.

Issues:
- `x` is referenced but the example that is referenced is not present
- `bar` is referenced but the example that is referenced is not present
- `This style of coding is a holdover from C/C++ style coding, and it shows that the developer isn't really confident that Java initializes instance variables to default values.` is very negative and also wrong. I agree that explicit initialization should be left out if default is fine, but there are style guides that say that initialization should always be done explicitly. This is not necessarily a leftover from C/C++ style coding or inconfidence of the developer. The rational to have it is, that it is clear from looking at it to what it is initialized without the need to think about it. This is the same as for example `int x = arr[y++] = y;`. This construct could either be seen as "wow, this developer knows exactly what the JVM is doing and in which order it evaluates expression parts", or it can be seen as "what the fuck, this is unreadable, I need to think 30 minutes about what happens in this statement each time I stumble upon it". For this example I would prefer not using such a wonky construct that 90% of the developers will not instantly understand correctly even if it would show my excellence in understanding JVM internals.

**Comment by romani** [comment]
@Vampire , all such text is in src/xdoc folder, please send PR with change, for all approved issues.
