### ISSUE TITLE
FinalParameters redundant as FinalLocalVariable can check parameters

### ISSUE THREAD

**Issue by Vampire** [checkstyle/checkstyle#6473]
Isn't `FinalParameters` redundant as `FinalLocalVariable` can check parameters too?
As far as I understood, both should check the same conditions.
Actually I guess they both do slightly different checks and thus could also produce slightly different results.
I'd suggest to deprecate and remove `FinalParameters` in favor of `FinalLocalVariable` (maybe under a different name to make it clear that parameters are also covered) and make sure the code covers the same edge cases.
Currently I think it is more confusing to the user which of the two should be used.

**Comment by romani** [comment]
All Checks are independent, user may use any of them.
Unfortunately removal, change a name, change name of properties are breaking compatibility changes. It is unpleasant work from plugins and all users, we try to minimize such activity.

If you have nothing special to change, let's close this issue

**Comment by Vampire** [comment]
Sure, was just some thoughts, as for me it was confusing which check is the one that should be used as both can apparently do the same, or at least by intention.
