### ISSUE TITLE
Page that explains system properties is not accesible from main page

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#6475]
page https://checkstyle.org/config_reporting.html is not accessible from our index.html and any other child page.

As it have a list of system properties:
lets use it for it
add it in our navigation left panel, 
rename page to `config_system_properties.html`
this page should be linked with https://checkstyle.org/config.html#Properties in some way

**Comment by sulkykookie** [comment]
I'm on it.

**Comment by romani** [comment]
fix is merged.
