### ISSUE TITLE
New check: AvoidDoubleBraceInitialization

### ISSUE THREAD

**Issue by Vampire** [checkstyle/checkstyle#6480]
Many people consider double-brace initialization as an anti-pattern, for example as it unnecessarily creates subclasses and also might break `equals` checks that most often consider instances to be non-equal if the class is not the same to ensure symmetric behavior of the `equals` method as required by its contract.

I'd like to propose a check that prevents double-brace initialization.

Logic I suggest is, that a finding is added if an `INSTANCE_INIT` token has no siblings besides `LCURLY`, other `INSTANCE_INIT`s, `RCURLY`, `SINGLE_LINE_COMMENT` or `BLOCK_COMMENT_BEGIN` which means, as soon as also some field or method is added, it is not considered double-brace initialization and thus is fine.

**_Check config:_**
```xml
<module name="AvoidDoubleBraceInitialization"/>
```

**_Here some code example use-cases:_**
```java
// will fail
List<?> list = new ArrayList<Object>() {
    {
        add(null);
    }
};
// will fail
list = new ArrayList<Object>() {
    {
        add(null);
    }
    {
        add(null);
    }
};
// will fail
list = new ArrayList<Object>() {
    // foo
    {
        add(null);
    }
};
// will fail
list = new ArrayList<Object>() {
    {
        add(null);
    } // foo
};
// will fail
list = new ArrayList<Object>() {
    {
        add(null);
    }
    // foo
};
// will fail
list = new ArrayList<Object>() {
    /* foo */
    {
        add(null);
    }
};
// will fail
list = new ArrayList<Object>() {
    {
        add(null);
    }
    /* foo */
};
// will fail
list = new ArrayList<Object>() {
    {
        add(null);
    } /* foo */
};
// will not fail
list = new ArrayList<Object>() {
    {
        add(null);
    }

    public void foo() {
    }
};
// will not fail
list = new ArrayList<Object>() {
    private Object o;
    {
        add(null);
    }
};
```

---

To reach this with 8.18, one could do
```xml
<module name="IllegalToken">
    <property name="id" value="doubleBraceInitialization"/>
    <property name="tokens" value="INSTANCE_INIT"/>
    <message key="illegal.token" value="Do not use double-brace initialization"/>
</module>
<module name="SuppressionXpathSingleFilter">
    <property name="id" value="doubleBraceInitialization"/>
    <property name="query" value="//INSTANCE_INIT[../*[not(
                                      self::LCURLY or
                                      self::INSTANCE_INIT or
                                      self::RCURLY or
                                      self::SINGLE_LINE_COMMENT or
                                      self::BLOCK_COMMENT_BEGIN
                                  )]]"/>
</module>
```

**Comment by romani** [comment]
@Vampire , thanks a lot for detailed list of examples and workaround.

Please update description with xml config example. I presume tokens will be non-confugurable and contains only  `INSTANCE_INIT`. No other properties will be.
Please put all this to description if you agree.

I have a concern with name of Check, my position is not strong I even fine with name(as a lot of our Checks named like this) ..... but DoubleBraceInitialization sounds too general, if we want to forbid only, probably we need to name it ForbidDoubleBraceInitialization ? or AvoidDoubleBraceInitialization ?

In general I ma fine with proposed Check.
@Vampire , please do suggested changes to description.
@rnveach  and @pbludov , please review, share ideas and lets approve new Check.

**Comment by rnveach** [comment]
> AvoidDoubleBraceInitialization 

I am fine with implementation.

**Comment by pbludov** [comment]
I like this check and `AvoidDoubleBraceInitialization` for the name.

**Comment by rnveach** [comment]
Fix was merged
