### ISSUE TITLE
Generic XPath check

### ISSUE THREAD

**Issue by Vampire** [checkstyle/checkstyle#6481]
It would be nice if you could write custom checks by simply using XPath, this way any custom check wanted could easily be configured via XPath.

Currently you have to find some check that adds a violation in a superset of the cases you want to be reported and then use `suppress-xpath` to suppress the findings you are not interested in.

For example to forbid double-brace initialization, you currently need to use
```xml
<module name="IllegalToken">
    <property name="id" value="doubleBraceInitialization"/>
    <property name="tokens" value="INSTANCE_INIT"/>
    <message key="illegal.token" value="Do not use double-brace initialization."/>
</module>
<module name="SuppressionXpathSingleFilter">
    <property name="id" value="doubleBraceInitialization"/>
    <property name="query" value="//INSTANCE_INIT[../*[not(
                                      self::LCURLY or
                                      self::INSTANCE_INIT or
                                      self::RCURLY or
                                      self::SINGLE_LINE_COMMENT or
                                      self::BLOCK_COMMENT_BEGIN
                                  )]]"/>
</module>
```
With a check like I suggest you could simply do
```xml
<module name="XPath"
        query="//INSTANCE_INIT[not(../*[not(
                    self::LCURLY or
                    self::INSTANCE_INIT or
                    self::RCURLY or
                    self::SINGLE_LINE_COMMENT or
                    self::BLOCK_COMMENT_BEGIN
                )])]">
    <message key="xpath.finding" value="Do not use double-brace initialization."/>
</module>
```

-----

One more idea is to validate empty files, even they have whole content as commented out, example #1149.

**Comment by romani** [comment]
I am ok with proposal.

@rnveach  and @pbludov , please confirm approval and put label on it to proceed.

**Comment by rnveach** [comment]
I am ok.

**Comment by pbludov** [comment]
I'm OK.

**Comment by strkkk** [comment]
@romani @Vampire how to specify acceptable/required/default tokens for this check?

I guess that if such check will be run on every token, it can affect performance.

**Comment by rnveach** [comment]
@strkkk I would do something similar to `LineLengthCheck`.
`CommonUtil.EMPTY_INT_ARRAY` for the tokens and do all the logic in `beginTree`. Every node returned from xpath would be sent to `log()` method.

**Comment by Vampire** [comment]
Either that, or you could maybe support all token types without any token required or default, then one can configure whatever token one wants to have checked. But I guess the `beginTree` version could also work, as then the XPath is only applied once to the whole tree if I understood correctly.

**Comment by gaurabdg** [comment]
I am on it, to expand my understanding of xpath. Planning to work after my existing PRs get merged.

**Comment by gaurabdg** [comment]
thanks a lot

**Comment by timurt** [comment]
interesting issue, @gaurabdg are you still working on it? @romani @rnveach can I take it?

**Comment by gaurabdg** [comment]
@timurt No, feel free.

**Comment by rnveach** [comment]
Fix was merged
