### ISSUE TITLE
Add tabWidth to Checker and FileSets

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#6485]
Taken from https://github.com/checkstyle/checkstyle/issues/2116#issuecomment-465631027 ,

`AbstractFileSetCheck` doesn't use tabWidth in the violation like `AbstractCheck` does, so the column numbers for violations is incorrect. There are no checkstyle file sets that put violations on the line AND column number, but we are a util and this could be useful to someone else making their own custom check, if not to us in the future.
We should make `AbstractCheck`'s and `AbstractFileSetCheck`'s log methods similar.

FileSet's log: https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/AbstractFileSetCheck.java#L155-L157
AbstractCheck's log: https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/AbstractCheck.java#L248-L256

**Comment by rnveach** [comment]
Should all file sets and checks specify tabWidth as a property in the documentation?

**Comment by rnveach** [comment]
@romani I updated the issue description because I wrongly stated that a check's violation is based on the column position and could change with a tab when it was infact just the line number being printed in the violation. This doesn't effect any of our file sets right now, but will still be needed for #2116  and is an issue for anyone making their own custom file set.

**Comment by romani** [comment]
Fix is merged, doc need to be improved
