### ISSUE TITLE
Wrong JavaDoc example for NestedForDepthCheck

### ISSUE THREAD

**Issue by Vampire** [checkstyle/checkstyle#6491]
`NestedForDepthCheck` JavaDoc shows an example for `CatchWithLostStackCheck`

https://github.com/checkstyle/checkstyle/blob/a73ff0890c27cbe8affc1a55f2710a231687bd85/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/NestedForDepthCheck.java#L37

**Comment by rnveach** [comment]
@Vampire for small little corrections like this you don't need to create an issue. Just make a PR and prefix it with `minor: ` or `doc: `.

**Comment by Vampire** [comment]
Well, for me it is currently easier to create a ticket, so "just" means ticket.
I don't even have a checkstyle clone right now.
Just reading the documentation in the web and if unclear the JavaDoc or source in the IDE, but just from dependency, not from checked out code.

**Comment by rnveach** [comment]
It may be easier to create an issue but it doesn't guarantee someone will work on it. We already have a backlog of 300+ approved issues and 200+ other issues that we are trying to make our way through. We don't have a lot of community assistance in fixing these issues so they just sit dormant for a long time. We would also appreciate it if you could help fix some of the minor things you are finding to help make a contribution to the project.

**Comment by romani** [comment]
>I don't even have a checkstyle clone right now.

You can search a string in our github repo, change, file, GitHub will do fork and PR for you.

**Comment by Vampire** [comment]
I know, thanks. But this is one of the worst features of GitHub imho and I will never use it. :-)

**Comment by romani** [comment]
Fix is merged

**Comment by rnveach** [comment]
@romani Did you accidentally re-open this or was there a reason?
