### ISSUE TITLE
Remove hashCode and equals methods from FilterSet

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#6494]
Identified at https://github.com/checkstyle/checkstyle/issues/4734#issuecomment-469031982 ,

[FilterSet](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/FilterSet.java) should remove `hashCode` and `equals` methods as it is not immutable and we don't care about order. It is not immutable right now since it has a removeFilter method. Checker is the only class that uses this method, and it doesn't use it directly except in a test. It is just a public method anyone can use it if they use the direct class. It is not supported by RootModule interface.

With such override, user can put object to map, changes object, try to find the same object in map, got nothing. But this class is API, it has to be done with breacking compatibility label.

**Comment by romani** [comment]
Fix is merged
