### ISSUE TITLE
Make CLI option to be able to print Javadoc tree as plain text

### ISSUE THREAD

**Issue by baratali** [checkstyle/checkstyle#652]
We already have [JavadocTreePrinter](https://github.com/checkstyle/contribution/blob/master/javadoc-tree-serializer/JavadocTreePrinter.java) that gets root DetailNode and prints whole tree as plain text to console.
Example:
```
|--NEWLINE[3x0] : [\n]
|--LEADING_ASTERISK[4x0] : [ *]
|--WS[4x2] : [ ]
        |--JAVADOC_INLINE_TAG[4x74] : [{@link\n * Qax}]
            |--JAVADOC_INLINE_TAG_START[4x74] : [{]
            |--LINK_LITERAL[4x75] : [@link]
            |--NEWLINE[4x80] : [\n]
            |--LEADING_ASTERISK[5x0] : [ *]
            |--WS[5x2] : [ ]
            |--REFERENCE[5x3] : [Qax]
                |--CLASS[5x3] : [Qax]
            |--JAVADOC_INLINE_TAG_END[5x6] : [}]
        |--TEXT[5x7] : [ at the end of a line.]
        |--NEWLINE[5x29] : [\n]
        |--TEXT[6x0] : [ ]
|--EOF[6x1] : [<EOF>]
```
To work it should be placed inside a Javadoc Check to receive DetailNode tree, which is wrong.
Need to make it standalone to be able to execute tree printing by means CLI.

Following CLI options should be added:
``-j, --javadocTree`` - Print Parse tree of the Javadoc comment
``-J, --treeJavadoc`` - print Abstract Syntax Tree(AST) with Javadoc comment nodes of the checked file.

**Comment by romani** [comment]
Fix for plain javadoc parsing is merged
