### ISSUE TITLE
 Align XDocs and Javadocs for annotations package

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#6531]
Part of #5750 

Package com.puppycrawl.tools.checkstyle.checks.annotation

- [x] AnnotationLocation #6492 
- [x] AnnotationOnSameLine #6537
- [x] AnnotationUseStyle #6544
- [X] MissingDeprecated #6506 
- [X] MissingOverride #6507 
- [x] PackageAnnotation #6576 
- [x] SuppressWarnings #6545
- [x] SuppressWarningsHolder #6555

**Comment by romani** [comment]
last fix is merged.

@pbludov , thanks a lot for awesome/accurate issue description.
