### ISSUE TITLE
 Align XDocs and Javadocs for blocks package

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#6532]
Part of #5750 

Package com.puppycrawl.tools.checkstyle.checks.blocks;

- [x] AvoidNestedBlocks #6556
- [X] EmptyBlock #6517 
- [x] EmptyCatchBlock #6534
- [x] LeftCurly #6546
- [x] NeedBraces #6535 
- [x] RightCurly #6569

**Comment by rnveach** [comment]
All fixes were made.
