### ISSUE TITLE
Tests do not work properly on Windows with LF line endings

### ISSUE THREAD

**Issue by Vampire** [checkstyle/checkstyle#6558]
If Git is used without modifying line endings on checkout (e. g. `autocrlf=input`), you have
Linux line endings on Windows too.
The CS tests assume that on Windows the files have Windows line endings.

I personally hate it when a VCS mangles files automagically.
I have globally set `autocrlf` to `input` just to remind me to change line ending to LF if I have it at CRLF accidentally on some file, but I don't like to have Git automatically change line endings on checkout, besides that it wastes space on my local disk.

In #6511 @rnveach mentioned that the website of CS requires to use `autocrlf` with `true`.
With this the problem of course does not happen.
But I'd suggest to instead fix these incompatibilities in the tests and then maybe require instead not to have `autocrlf` at `false` for CS instead? For the result in the repository this would mean the same whether it is set to `true` or `input`, which is line endings in the repository are LF. And for most users this should be the case anyway.

With the changes I propose, the tests work properly on Windows, whether someone has linux line endings or windows line endings doesn't matter anymore. You could (should?) actually also add another build job that runs with `autocrlf` set to `input` or `false` on the Windows build machines to make sure it stays like that in the future.

Followup of #6511

**Comment by rnveach** [comment]
> How about requiring not to have autocrlf at false for CS instead? For the result in the repository this would mean the same whether it is set to true or input, which is line endings in the repository are LF. And for most users this should be the case.

With `autocrlf` as true any line endings placed into the repository is automatically converted to `\n` on push regardless if it was `\n` or `\r\n`. If we allow windows users to keep it as false, there is nothing preventing them from putting real `\r\n` into the repo. You can have a files contain full `\r\n` and it would go unnoticed in review since you visually don't see a difference in compare. We have nothing that would catch `\r\n` in the repo CI right now, and fixing failing tests for it would allow them to go more unnoticed. `NewlineAtEndOfFile` only checks the last line and not every line inbetween. Most windows editors put in windows line endings instead of the line ending the file is using when making changes to a file. I have my own project with `autocrlf` off where we all use windows and we have caught wrong new lines in the middle of a file that nothing else caught. Even if we did have a CI to catch it, it is always possible we would miss a file from the scan. See our resource checkstyle configs how we are always expanding them to new files.

This and conversations at https://github.com/checkstyle/checkstyle/issues/893 is why I prefer git to control the line endings in that way then a CI.

@romani Feel free to decide.

**Comment by Vampire** [comment]
> > How about requiring not to have autocrlf at false for CS instead? For the result in the repository this would mean the same whether it is set to true or input, which is line endings in the repository are LF. And for most users this should be the case.
> 
> With `autocrlf` as true any line endings placed into the repository is automatically converted to `\n` on push regardless if it was `\n` or `\r\n`.

Actually on commit, not on push. The same happens with `autocrlf` on `input`, that's why I said instead of requiring `true` you could require "not `false`" to still have only LF line endings in the repository.

> If we allow windows users to keep it as false, there is nothing preventing them from putting real `\r\n` into the repo. You can have a files contain full `\r\n` and it would go unnoticed in review since you visually don't see a difference in compare.

Well, this is the same currently already. I contributed earlier with setting to `input` I obviously just didn't run the tests locally. You just cannot verify what setting someone has, except with tests that run locally if the one runs tests locally. But then it would imho be better to either have the issue resolved that adds a check for line endings and enable it for CS, so that CI validate no CRLFs are in the repo or have some explicit test, that tests the Git setting. (Though I don't really like the latter option)

> It matters to others when someone makes a change to a 'bad' file and their editor changes all lines endings and causes excess differences in a review. Then fixing the problem will require another commit which doesn't guarantee the problem will stay gone.

Well, most decent editors including Eclipse, IntelliJ IDEA, jEdit, Notepad++ and probably most others will recognize the line ending of a file and not change it on save but use the same. Also this would be visible in the PR diff instantly.

The issue is mostly relevant when new files are added and this is the same currently already as nothing prevents a user to not have it set to `true` and no test verifies CI-side that the line endings are LF and not CRLF. The tests only fail for cases where the test generates some files with the native line ending and then compares to expected files on disk. This could also be solved by having a LF and a CRLF version checked in, adding those expected CRLF files to `.gitattributes` with forced crlf line ending actually, but to have it more fail-proof I'd suggest my changes and a build on one of the Windows CI machines that runs with LF line endings.

**Comment by romani** [comment]
>  whether someone has linux line endings or windows line endings doesn't matter anymore.

I might not remember smth, but mostlikely I enforced same line-ending to linux style and wanted it to be like this always, no matter who provide a patch. When I did Appveyor, it was just simple solution, that eventually become a requirements for Windows users. As I am not windows user, I do not experience this problems at all, such preconfiguration is a pain I agree. 


As already stated few times, we need new Check that verify consistent line ending on line (we have Check only end of file). So by mean of this we can enforce the same linux style line ending. So user can clone files as is (no modification to files). But if user create new file in Windows line ending, validation will fail. But we need probably to enforce new Check first. 

So in general I am ok, But lets look at what it would mean for tests to update.

@rnveach, can you share your position on this ?
If tests not become ugly and all line ends stay in Linux style in repo, I am ok.

**Comment by rnveach** [comment]
@romani See https://github.com/checkstyle/checkstyle/pull/6511#issuecomment-470113229 

> I personally am not ready to say we can drop this requirement as most windows platforms will default to save files with \r\n lines and we don't have a check or CI to validate if all line endings in repo is \n. There was a discussion about this at #893 which also discussed some drawbacks from a check and it should be git's responsibility to maintain line endings and autocrlf does this.

I prefer we leave `autocrlf` required for windows.

**Comment by romani** [comment]
I replied to that old issue, idea to control lineends is reasonable. As clients always forget to configure their environment. So server side( CI level) should control lineends.

Is there any other problems ?

It is very good experience to just clone sources and do not have problems during build. We did it convenient for Linux/Unix users, but windows users are definitely experience pain.

**Comment by rnveach** [comment]
I personally didn't experience any pain besides it wasn't really documented the time I joined. It still doesn't change that most windows programs will default to `\r\n` when editing and creating new files. Now we will have to specify to users how to change this default in Eclipse, and warn of other programs may not always obey it.
![windows eclipse](https://user-images.githubusercontent.com/5427943/56894433-d92dd480-6a53-11e9-92b7-8d528669bf87.gif)
This is why I prefer we stay with `autocrlf`.

**Comment by Vampire** [comment]
> I personally didn't experience any pain besides it wasn't really documented the time I joined.

But why require it for proper testing and building if it would actually not be necessary?

> It still doesn't change that most windows programs will default to `\r\n` when editing and creating new files. Now we will have to specify to users how to change this default in Eclipse, and warn of other programs may not always obey it.
> ![windows eclipse](https://user-images.githubusercontent.com/5427943/56894433-d92dd480-6a53-11e9-92b7-8d528669bf87.gif)
> This is why I prefer we stay with `autocrlf`.

I can just repeat myself: The same happens with `autocrlf` on `input`, that's why I said instead of requiring `true` you could require "not `false`" to still have only `LF` line endings in the repository, no matter what editors do.

If Windows people currently do not set the setting as the contribution docs require and just open a PR with some changes, they can still have committed a file with CRLF line endings.
So as long as there is no CI-side check that all files have LF line endings in the repository, you can never be sure it is like you want, whether you have a requirement for `autocrlf` or not, independently on what value you require.

**Comment by romani** [comment]
@Vampire , looks like some documentation is unavoidable, so it will be problem at the beginning or at moment of contributing. As for me problems at the beginning is more painful and could demoralize potential contributors.

I think there is no ideal solution, but some approach might be better a bit.
@Vampire , please share a bit more thoughts on your idea. I really like idea to work out-of-the-box, but I have not use Windows for long time to provide good argument.

**Comment by Vampire** [comment]
> @Vampire , looks like some documentation is unavoidable,

If you want to enforce LF in the repo yes, which I also second.

> so it will be problem at the beginning or at moment of contributing. As for me problems at the beginning is more painful and could demoralize potential contributors.

Totally agree here, that's why I suggested to make the tests work with a checkout with LF line ending on Windows too.

> I think there is no ideal solution, but some approach might be better a bit.
> @Vampire , please share a bit more thoughts on your idea. I really like idea to work out-of-the-box, but I have not use Windows for long time to provide good argument.

I'm not sure what other arguments or ideas you need from me.
With my PR, the tests work out of the box even when checkin out with LF line endings on Windows.
Maybe you should also add some CI job that verifies this for the future.

And by requiring `autocrlf` to not be `false`, (so either `input` or `true`), you make sure that people sticking to the requirement will only submit LF to the repo.
But whatever you require for `autocrlf`, you should anyways have a CI-side check that verifies that there are only LF in the repo, as otherwise you will never be safe against contributors submitting CRLF files and you will not necessarily see this by any current job or test.

**Comment by romani** [comment]
@Vampire and @rnveach , what if we define line ends at https://github.com/checkstyle/checkstyle/blob/master/.gitattributes
Good explanation https://help.github.com/en/articles/dealing-with-line-endings
So we will not need https://github.com/checkstyle/checkstyle/blob/master/appveyor.yml#L38 and any documentation.

@pbludov , please us know what is your Is ?

**Comment by pbludov** [comment]
> @pbludov , please us know what is your Is ?

Our team uses utf8 and linux/mac line endings even with windows. All modern IDEs are compatible with this setup.

**Comment by rnveach** [comment]
I am fine with trying anything out.

**Comment by Vampire** [comment]
Oh, missed the last three messages and was about to also suggest that you could use `.gitattributes` instead of documentatn if you want to control some aspects of line endings as I happened to read the man page (https://git-scm.com/docs/gitattributes) some minutes ago.

You could for example use `eol=lf` to forces linux line endings also on Windows and at the same time force normalization to LF on checkin.

Or you can use `text=auto` to have all files lineendings normalized on checkin without forcing a particular lineending on checkout.

Nevertheless a CI check for the lineendings in the repository would be appropriate, as also the `.gitattributes` things can easily be overridden locally.

**Comment by romani** [comment]
@Vampire ,

>Or you can use text=auto to have all files lineendings normalized on checkin without forcing a particular lineending on checkout

What is a benefit of this?
It will increase chance of file with windows lineends in text file to appear, if file is new.

What is a problem for windows users to have Linux line ends in source files ( except for bat/PS shell scripts) ?

**Comment by Vampire** [comment]
It is just an option, so you do not enforce linux line endings on checkout but keep the option to the user.

It should not increase the chance of file with windows lineendings to appear (in the repository) as both options should enable the lineending normalization on checkin.

There should probably be no problem to have LF line endings on Windows nowadays as all decent tools should be able to cope with both.
Just wanted to mention that there is still an option that would make sure LF are used in the repo (as long as the user does not override the setting of course) that does not force him to a line-ending style in his local checkout.

**Comment by romani** [comment]
we have `. gitattributes ` in repo, such config should override all that user have globally and for other projects. If user change our `.gitattributes` and contribute "bad" line ends, only CI validation can help to prevent this.
It is better to have all files to have consistent/predicable line ends - LF (for historical reason).  

In this Issue, we need to agree on how we are going to fix it. As you already have PR, I need to close it or let it proceed in review.
If we agree on `.gitattributes` I should close your current PR. Do you agree ?

 can you help us to update `.gitattributes` and resolve this issue ? so make checkstyle repo more friendly for Windows users.

**Comment by Vampire** [comment]
> we have `. gitattributes ` in repo, such config should override all that user have globally and for other projects.

Yes and no. It overrides global and user-specific settings, yes.
But if there is a `.git/info/attributes` file it has higher precedence.
A user could also have this file in his git directory template and so automatically have it when he clones.
Besides that, yes, he could of course also modify the file locally for whatever reason.

> If user change our `.gitattributes` and contribute "bad" line ends, only CI validation can help to prevent this.

Yes, that's what I said before. :-)

> It is better to have all files to have consistent/predicable line ends - LF (for historical reason).

👍 

> In this Issue, we need to agree on how we are going to fix it. As you already have PR, I need to close it or let it proceed in review.
> If we agree on `.gitattributes` I should close your current PR. Do you agree ?

Can I say no? :-D
My PR makes the tests runnable with LF on Windows.
If you use .gitattributes to force LF line endings on Windows, you need my changes too I'd say.

> can you help us to update `.gitattributes` and resolve this issue ? so make checkstyle repo more friendly for Windows users.

I think my PR does the most of the necessary work as it makes the tests run properly on Windows with LF line endings.
You then can add the `.gitattributes` you want to enforce LF line endings except for the files where CRLF is necessary like for test fixtures.

**Comment by romani** [comment]
> Yes and no.

if user is that equipped with extra configs .... he experienced person, and will figure-out lineends problems himself.

> If you use .gitattributes to force LF line endings on Windows, you need my changes too I'd say.

make sense.


==========================


Summary:
I am ok to remove demand to preconfigure git before clone of sources, we need to udpate doc and appveyor.
we need to proceed with review of @Vampire.
We need to create CI validation for lineends, probably right now by shell, and later on by some Check.

Looks like @rnveach already got approval on this issue in comments above.

@pbludov , are you using Windows ? are you ok with my "Summary" of what to do ?

**Comment by Vampire** [comment]
Don't forget update of .gitattributes

**Comment by pbludov** [comment]
> @pbludov , are you using Windows ? are you ok with my "Summary" of what to do ?

No, the last time I used Windows it was Windows7. Now, rumor has it, Windows natively supports bash and git. And colleagues confirm that CR line endings are also supported. But I'm irrelevant. I'm a backend developer.

**Comment by romani** [comment]
fix is merged.
