### ISSUE TITLE
Site files are not schema-valid

### ISSUE THREAD

**Issue by Vampire** [checkstyle/checkstyle#6563]
Currently the `validate` property of the `maven-site-plugin` is disabled because of a bug in `xml-maven-plugin` that was fixed in `1.0.2`.
Since checkstyle in the meantime uses that version, the `validate` could be enabled again.
Unfortunately in the long time it was off, some invalid markup made it into the site files.

I'd like to suggest to reenable the validation and fix the invalid parts.
In detail this would be:
- text directly within `<section>` needs to be wrapped in paragraphs
- block tags like `<div>` or `<ul>` must not occur within paragraphs, but besides
- `<source>` tag does not allow `class` attribute but instead you have to wrap a `<div>` around it and adapt the CSS accordingly to have the wanted effect
- Within `<body>` only `<section>` is allowed, not `<div>` like in the release notes, but via CSS placement it can still look the same in the end even with the release date within the section which is semantically cleaner anyway as it belongs to the respective version (this also needs to be changed in the release notes generator template)
- Not exactly due to schema-validity, but because the `wrap-content` style needs to be changed anyway I also suggest to change it a tad bit, so that not `white-space: pre-wrap` but `white-space: pre-line` is used. 
With the former all whitespace is preserved, but if space gets narrow (too long text, too much zoom) the text is automatically wrapped.
With the latter line-breaks are preserved, but leading spaces are stripped from each line.
This means, that you can then properly indent the code in the sources or you can have them at column 0 or anywhere in between and it will look the same on the final page so it doesn't matter if someone indents it accidentally for example unlike currently.
This also means if you want to have visual indentation on the page, you have to use a non-breaking space as `&#xa0;`.
Another big plus you get which is why I looked into it actually is, that also trailing spaces get removed which looks nicer in the result.
![grafik](https://user-images.githubusercontent.com/325196/54167991-c4c65600-446c-11e9-9e1a-636ad8174c56.png)
vs.
![grafik](https://user-images.githubusercontent.com/325196/54167932-947eb780-446c-11e9-8f14-7b92d49a54a4.png)
And in the code
![grafik](https://user-images.githubusercontent.com/325196/54168106-41593480-446d-11e9-9662-74e3c1a7a56c.png)
vs.
![grafik](https://user-images.githubusercontent.com/325196/54168071-1ec71b80-446d-11e9-90f3-0a36568d214e.png)

**Comment by Vampire** [comment]
Result of proposed changes from PR can be looked at under http://kautler.net/cs/

**Comment by romani** [comment]
fix is merged.
