### ISSUE TITLE
Exclude module-info.java from Google and Sun configurations

### ISSUE THREAD

**Issue by mwkroening** [checkstyle/checkstyle#6570]
It would be helpful to exclude the `module-info.java` ([Reference](https://checkstyle.org/config_filefilters.html#BeforeExecutionExclusionFileFilter_Examples)) from the [google_checks.xml](https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/google_checks.xml) and [sun_checks.xml](https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/sun_checks.xml).

That way these configurations would work with modular projects out of the box.

**Comment by romani** [comment]
make sense, please provide PR.

**Comment by rnveach** [comment]
Fix was merged
