### ISSUE TITLE
Typo in new option IllegalThrowsCheck#ignoreOverridenMethods

### ISSUE THREAD

**Issue by lkoe** [checkstyle/checkstyle#658]
Should rather be "ignoreOverriddenMethods".

I've hinted at this before, check names and properties are the "public API" of Checkstyle. Changing them potentially breaks thousands configurations. Extra care is advisable when introducing new options to avoid unnecessary API changes afterwards.

**Comment by mkordas** [comment]
Already fixed in #623. Will be in 6.4.

**Comment by lkoe** [comment]
Ah, great!
