### ISSUE TITLE
 Align XDocs and Javadocs for coding package

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#6586]
Part of #5750 

Package com.puppycrawl.tools.checkstyle.checks.coding;

- [x] ArrayTrailingComma #6587
- [x] AvoidInlineConditionals #6590
- [x] CovariantEquals #6588
- [x] DeclarationOrder #6591
- [x] DefaultComesLast #6594
- [x] EmptyStatement #6598
- [x] EqualsAvoidNull #6592
- [x] EqualsHashCode #6595
- [x] ExplicitInitialization #6663
- [x] FallThrough #6651
- [x] FinalLocalVariable #6602
- [x] HiddenField #6692
- [x] IllegalCatch #6669
- [x] IllegalInstantiation #6597
- [x] IllegalThrows #6661
- [x] IllegalToken #6676
- [x] IllegalTokenText #6625
- [x] IllegalType #6666
- [x] InnerAssignment #6652
- [x] MagicNumber #6596
- [x] MissingCtor #6599
- [x] MissingSwitchDefault #6603
- [x] ModifiedControlVariable #6684
- [x] MultipleStringLiterals #6675
- [x] MultipleVariableDeclarations #6655
- [x] NestedForDepth #6690
- [x] NestedIfDepth #6668
- [x] NestedTryDepth #6683
- [x] NoClone #6626
- [x] NoFinalizer #6691
- [x] OneStatementPerLine #6672
- [x] OverloadMethodsDeclarationOrder #6685
- [x] PackageDeclaration #6656
- [x] ParameterAssignment #6673
- [x] RequireThis  #6604
- [x] ReturnCount #6686
- [x] SimplifyBooleanExpression #6657
- [x] SimplifyBooleanReturn #6667
- [x] StringLiteralEquality #6634
- [x] SuperClone #6670 
- [x] SuperFinalize #6674
- [x] UnnecessaryParentheses #6605
- [x] VariableDeclarationUsageDistance #6662

**Comment by rnveach** [comment]
All fixes were merged.
Thanks @pbludov .

**Comment by romani** [comment]
@pbludov , thanks a lot for huge update !
