### ISSUE TITLE
activate new sevntu ForbidCertainMethodCheck

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#6610]
at https://github.com/checkstyle/checkstyle/blob/master/config/checkstyle_sevntu_checks.xml
Check availbable form 1.33.0 version of extension

**Comment by rnveach** [comment]
@romani It is already activated. See https://github.com/checkstyle/checkstyle/blob/master/config/checkstyle_sevntu_checks.xml#L206

Are you looking for something more?

**Comment by romani** [comment]
False alarm
