### ISSUE TITLE
Cached Google Style is slightly outdated and not like original

### ISSUE THREAD

**Issue by Vampire** [checkstyle/checkstyle#6619]
If you compare http://google.github.io/styleguide/javaguide.html and https://checkstyle.org/styleguides/google-java-style-20170228.html, you that it is displayed differently, for example original
![grafik](https://user-images.githubusercontent.com/325196/55269993-f70fea00-5299-11e9-86c8-bc86a78dae91.png)
vs. cached
![grafik](https://user-images.githubusercontent.com/325196/55269987-f11a0900-5299-11e9-81ea-75df438cb09b.png)

Also the cached version got some minor changes that as far as I have seen do not change meaning, just add some clarification, as can be seen here: https://​github.com/google/styleguide/compare/594d91bfbb8dfcbcac0f148af8175f2b7ec9857b...91d6e367e384b0d8aaaf7ce95029514fcdf38651#diff-b6c9191ee5ccb7a5ef170e98e51d94d8

I'd like to suggest to update the cached version with a recent one that contains latest changes and also displays correctly.

**Comment by rnveach** [comment]
> google/styleguide@594d91b...91d6e36diff-b6c9191ee5ccb7a5ef170e98e51d94d8

The link says "There isn’t anything to compare.".

> as I have seen do not change meaning, just add some clarification

Nothing is usually ever as simple with the google style. We would have to review every change and agree that nothing needs to be changed on our side for each module. We have worked hard to do our best with matching their guide, so we need to continue doing it with each update.

Here is possibly one example I am seeing from their webpage:
> 4.4 Column limit: 100
> A "character" means any Unicode code point.
> Each Unicode code point counts as one character, even if its display width is greater or less. For example, if using fullwidth characters, you may choose to wrap the line earlier than where this rule strictly requires.

We don't support this as seen with https://github.com/checkstyle/checkstyle/issues/5089 .

So we can't update our cache until we are sure we support all google's rules or possibly agree that we can't ever support them. Example: http://checkstyle.sourceforge.net/google_style.html#a5.2.4

**Comment by romani** [comment]
> So we can't update our cache until we are sure we support all google's rules or possibly agree that we can't ever support them.

we can update cached version, only if there is no java style changes but there is some formatting changes in HTML layout so to look better.

If there is some style changes, we have to address them in our mapping page, while copy new version of style guide.
We can update our mapping page with links to our issues to show user that paragrath is not covered till, or paragraph is not completely covered and here a list of issues to resolve to make it complete.

----

If you udpate this issue description with clear definition of style differences I can approve the issue.

**Comment by Vampire** [comment]
> The link says "There isn’t anything to compare.".

Stupid GitHub-style markdown parser destroyed the link by removing the `#` that separated the URL from the anchor.
Link is fixed now, please look again.

> Nothing is usually ever as simple with the google style. We would have to review every change and agree that nothing needs to be changed on our side for each module. We have worked hard to do our best with matching their guide, so we need to continue doing it with each update.

Of course, that's why I posted the link with the differences that now also works.

But I can of course post them here again as images for reference:

4.4 ![grafik](https://user-images.githubusercontent.com/325196/55658185-08f30f00-57fd-11e9-96de-37639cf27fb0.png)
4.6.1 ![grafik](https://user-images.githubusercontent.com/325196/55658250-43f54280-57fd-11e9-8dd7-968e6d0483ee.png)
4.6.2 ![grafik](https://user-images.githubusercontent.com/325196/55658285-66875b80-57fd-11e9-9aa9-3faef8f58a08.png)
4.8.2.1 ![grafik](https://user-images.githubusercontent.com/325196/55658308-799a2b80-57fd-11e9-9efa-9a69060faf82.png)
5.1 ![grafik](https://user-images.githubusercontent.com/325196/55658336-8dde2880-57fd-11e9-86de-5ccf6aca7f99.png)
5.2.3 ![grafik](https://user-images.githubusercontent.com/325196/55658350-9d5d7180-57fd-11e9-8a6e-481beff81249.png)
5.2.4 ![grafik](https://user-images.githubusercontent.com/325196/55658358-a8b09d00-57fd-11e9-87a1-d2e64e1658cf.png)

4.4: As mentioned by  @rnveach, #5089 shows this is false, but I would tend to say this is simply a bug and even in the current cached version there should be no green checkmark. The additional text just explains what was meant by the word character, but it was no content change, the rule is the same and is not followed correctly currently by checkstyle.

4.6.1: imho just nicer language, no content change

4.6.2: This one I actually overlooked initially. I think there is no rule yet to check these two? Actually for the ellipsis case there is even a rule in the checks that checks the opposite. (`NoWhitespaceBefore` with token type `ELLIPSIS`) For the array initializer there would also be an opposing rule (`NoWhitespaceAfter` with token type `ARRAY_DECLARATOR` which checks before is no space? wtf? It is not in the google checks, but why is this token tpye not handled in `NoWhitespaceBefore` instead? o_O)

4.8.2.1: clarifcation that is already tested like that: com.google.checkstyle.test.chapter4formatting.rule4821onevariableperline.InputMultipleVariableDeclarations#method2
![grafik](https://user-images.githubusercontent.com/325196/55660503-0b5a6680-5807-11e9-95d2-0523ea72a31c.png)

5.1: imho just nicer language, no content change

5.2.3: mainly nicer language and not fully covered regarding the clarified point anyway

5.2.4: Not covered anyway, change is just **single** underscore forced

> If there is some style changes, we have to address them in our mapping page, while copy new version of style guide.

Of course, as mentioned originally I thought there were only lingo changes and clarifications, while one is discutable and one I just missed.

> I see diff as https://www.diffchecker.com/KVRGxmti (if link does not work, copy html content from both pages )

Not really necessary to use some differ, as the style is maintained in a GitHub repository. :-)

**Comment by Vampire** [comment]
I added in my local branch the mention of #5089 for 4.4 which is only partly covered anyway and changed 4.6.2 to partly covered with explanation about the new cases. Actually 4.6.2 is only partly covered anyway, for example it is not checked that there is no space before `ARRAY_DECLARATOR` and probably other cases too.

I'll push it as soon as we agreed and you reopened my PR.

**Comment by romani** [comment]
> 4.4

we have a bug on unicode symbol usage and LineLength from google people, we need to mention it in mapping.

> 4.6.1

agree, no functional changes.

> 4.6.2

ok, lets convert to partly covered, and create issue that address certain items to update.

----

the rest items are fine.

-------------


@rnveach , I am agree to change our style guide, only if we clearly define what new items we do not cover and provide links to issues. We just need to honest with users.
If you agree ... lets make issue approved and reopen PR.

@Vampire , thanks a lot for analysis but lets make sure that in new coverage change image on item if we do not cover it completely and reference issues in mapping table that need to be fixed to make full coverage or improve coverage.
