### ISSUE TITLE
Remove usage of antlr specific methods from our checks

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#6624]
This is in support of issue #3817 .

We should  remove uses of any ANTLR specific method and uses the DetailAST directly instead. These are methods that we didn't implement and take an AST (not DetailAST). They need to be removed as we can't change the method parameter of a method we are overriding and we want to remove ANTLR classes from the API package. It is better we use our own implementation instead of one that we don't control and don't know for sure what it does.

They are only 2 of these methods, so it is not a big loss in terms of compatibility.

**Comment by rnveach** [comment]
One not assigned to this issue was completed at https://github.com/checkstyle/checkstyle/pull/6617 .
The last method will be completed at https://github.com/checkstyle/checkstyle/pull/6623 .

**Comment by romani** [comment]
Fix is merged

**Comment by rnveach** [comment]
I am re-opening this to fix regresion. See https://github.com/checkstyle/checkstyle/pull/6623#issuecomment-479443373

**Comment by rnveach** [comment]
Re-closing as regression changes to VariableDeclarationUsage look valid.
