### ISSUE TITLE
Remove "update" methods from DetailAST as developers shouldn't be modifying the tree from inside a check

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#6628]
Once https://github.com/checkstyle/checkstyle/issues/3817 is done for DetailAST, we should break compatibility with certain methods and directly using the implementation of DetailAST and only use the interface.

Methods to break:
addPreviousSibling, addNextSibling, setText, setType, getLine, getColumn, removeChildren

Update methods should be removed because users shouldn't be modifying the tree from inside a check. Only the implementation should be allowed to use these methods.
Get line and column should be removed because we already have a `getLineNo` and getColumnNo` and it causes confusion on which ones to use.

**Comment by rnveach** [comment]
@romani If you see no issues, put approve label.

**Comment by romani** [comment]
in general I am agree.

> Update methods should be removed because users shouldn't be modifying the tree from inside a check.

I still see them in DetailAST interface. if you plan to do this in separate step, we need to move this demand to new issue. I would rather keep this issue as conversion of DetailAST to interface, and as second issue remove mutator methods (as some mutators as `setText` should be removed also eventually).
Lets define scope of work for this issue, it is better to not change all in one commit.

**Comment by rnveach** [comment]
@romani 
> I still see them in DetailAST interface. if you plan to do this in separate step, we need to move this demand to new issue.

This is the issue for it. This is the second issue.

> I would rather keep this issue as conversion of DetailAST to interface

Conversion of DetailAST to interface is https://github.com/checkstyle/checkstyle/issues/3817 .

**Comment by romani** [comment]
Looks like made mistake in placing a comment. It is all good, as it is already separate.

**Comment by romani** [comment]
Fix is merged
