### ISSUE TITLE
CS6.3: New option IllegalTypeCheck#memberModifiers does not behave like other token list type properties

### ISSUE THREAD

**Issue by lkoe** [checkstyle/checkstyle#663]
The implementation assumes - unlike implementation for other token type list properties - that tokens are separated by ", " (comma and space).
All other options of such type just use "," as separator and trim the fragments afterwards. This way definitions with or without spaces after of before the comma separator work alike.

Because of this issue I cannot configure this new option as Multi-Check type in the eclipse-cs metadata - because this creates comma-only separated values in the resulting configuration file.

The code in IllegalTypeCheck#setMemberModifiers() should be fixed like this:

a) split only by comma
b) trim space around trim fragments
c) fix the list instantiation in this method which create a List with initial capacity of the parameter strings length

**Comment by lkoe** [comment]
Additionally the documentation for this option is wrong, the referenced type in documentation should be StringSet (http://checkstyle.sourceforge.net/property_types.html#stringSet) instead of intSet

**Comment by alexkravin** [comment]
Updated setting:

1) Values are splitting only by comma
2) possible trailing spaces are trimmed
3) removed capacity setting in list instantiation as default value is 10 and in 90% of cases user values will be much more

Updated docs.

Thanks.

**Comment by romani** [comment]
fix is merged, @lkoe, please confirm that code is ok from eclipse-cs perspective.
