### ISSUE TITLE
Erroneous Javadoc parse error reported

### ISSUE THREAD

**Issue by demonfiddler** [checkstyle/checkstyle#6650]
```
/**
 * A validator to check whether the selection is valid. The validator is invoked whenever the selection changes.
 * @see {@link org.eclipse.ui.dialogs.ElementTreeSelectionDialog#setValidator(ISelectionStatusValidator)}
 */
public class BindingConfigSelectionValidator implements ISelectionStatusValidator {
    /** {@inheritDoc} */
    @Override
    public IStatus validate(Object[] selection) {
            return new Status(IStatus.OK, "some-id", IStatus.OK, "", null);
        }
    }
}

OUTPUT:
Description	Resource	Path	Location	Type
Javadoc comment at column 9 has parse error. Details: no viable alternative at input '{' while parsing JAVADOC_TAG	BindingConfigSelectionValidator.java	/com.tibco.xpd.forms.designer.editor/src/com/tibco/xpd/forms/designer/editor/design/pickers/binding	line 33	Checkstyle Problem
```

---------------

Looks like the CheckStyle Javadoc comment parser can't handle an @see tag whose comment text consists of an {@link ...} directive.

--------------

**Comment by rnveach** [comment]
@demonfiddler See https://docs.oracle.com/javase/8/docs/technotes/tools/windows/javadoc.html#CHDDIEDI and the 3 forms that it says `@see` can take on. `@see {@link ...}` doesn't seem to be one of them.

Why do you require the link when `@see org.eclipse.ui.dialogs.ElementTreeSelectionDialog#setValidator(ISelectionStatusValidator)` is supported?

**Comment by romani** [comment]
@demonfiddler , please report issue as required in template. in most cases following template helps user to understand the problem himself and provide all details

**Comment by romani** [comment]
No reply, closing issue
