### ISSUE TITLE
update CLI to allow show tree branch that match xpath

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#6660]
idea is taken from #4944

We need CLI version of it.
User should define file and xpath expression, and cli print brach of AST that match. 

---

Bounty will be 30

**Comment by strkkk** [comment]
@romani please clarify.
There are bunch of options to print AST, like -t, -T, -J, -j
Xpath should be used for them as additional option or should be completely separate thing?

Which of the following cases valid?
```
checkstyle.jar -t --xpath='MYXPATH' TestClass.java
```
or 
```
checkstyle.jar  --xpath='MYXPATH' TestClass.java
```

**Comment by romani** [comment]
I think we can avoid "-t" (and other similar options) as they print all.
New option will parse file, run xpath and print result.
Result should be printed AST branch.
We might extend it in future to print actual single line of code to make it more human friendly as AST is not obvious some times for quick reference to code will be useful.

Property name should be `--tree-branch-for-xpath` ("-b").
@rnveach , @pbludov , is there any other ideas on name ? @strkkk , please propose also.

**Comment by strkkk** [comment]
> Result should be printed AST branch.

The thing is that there are different options for print - with and without javadocs. In my opinion, we can pass xpath as additional property for existing options to allow user to run xpath against both javadoc and javadocless ast.

For example:
```
java -jar checkstyle.jar -t --tree-branch-for-xpath='MYXPATH' TestClass.java
outputs branch for xpath without javadoc
java -jar checkstyle.jar -j --tree-branch-for-xpath='MYXPATH' TestClass.java
outputs branch for xpath with javadoc
```

Other option is to run xpath against ast with javadoc and do not complicate logic.

**Comment by romani** [comment]
Nuance is that we do not have xpath support for javadoc ast, so "-t" become kind of implicit, so I suggest to not bother users to specify it. Ones we be ready for xpath for javadoc, we will let users define tree mode.

But there is extra nuances, is "-t" vs "-T" Wich is two different AST, but they are different only to let user skip comments from output. In case of this issue we already filters output, so we can imply "-T" as it will not produce extra output, and it activate generation of most full AST. 

If eventually there will be misunderstanding, we can always extend requirements to explicitly specify "-t" or "-T", if nothing is defined we imply "-T".
If you want it like this to be from the beginning, please do, I just warn you to avoid extra complications.

**Comment by rnveach** [comment]
@romani So I understand what you want, can you give an example of tree printout you are expecting, especially if xpath matches 2+ ASTs in different branches.

**Comment by romani** [comment]
How I see it:
Code:
```
cat TestClass.java 
public class TestClass {
  void method() {
    while ((line = file.read()) != null && noOfSQLErrors < maxErrors) {} // violation
    while ((line = file.read()) != null) {} // no violatin; specially allowed by Check, see doc
  }
}
```
command, to get node of second while:
`java -jar checkstyle.jar --tree-branch-for-xpath='METHOD_DEF/LITERAL_WHILE[2]' TestClass.java`

output should be something like:
```
CLASS_DEF -> CLASS_DEF [1:0]
`--OBJBLOCK -> OBJBLOCK [1:23]
    `--METHOD_DEF -> METHOD_DEF [2:2]
        `--SLIST -> { [2:16]
            `--LITERAL_WHILE -> while [4:4]
```

------

Whole Tree:
```
rivanov@p5510:/var/tmp$ java -jar checkstyle-8.21-all.jar -T TestClass.java
CLASS_DEF -> CLASS_DEF [1:0]
|--MODIFIERS -> MODIFIERS [1:0]
|   `--LITERAL_PUBLIC -> public [1:0]
|--LITERAL_CLASS -> class [1:7]
|--IDENT -> TestClass [1:13]
`--OBJBLOCK -> OBJBLOCK [1:23]
    |--LCURLY -> { [1:23]
    |--METHOD_DEF -> METHOD_DEF [2:2]
    |   |--MODIFIERS -> MODIFIERS [2:2]
    |   |--TYPE -> TYPE [2:2]
    |   |   `--LITERAL_VOID -> void [2:2]
    |   |--IDENT -> method [2:7]
    |   |--LPAREN -> ( [2:13]
    |   |--PARAMETERS -> PARAMETERS [2:14]
    |   |--RPAREN -> ) [2:14]
    |   `--SLIST -> { [2:16]
    |       |--LITERAL_WHILE -> while [3:4]
    |       |   |--LPAREN -> ( [3:10]
    |       |   |--EXPR -> EXPR [3:40]
    |       |   |   `--LAND -> && [3:40]
    |       |   |       |--NOT_EQUAL -> != [3:32]
    |       |   |       |   |--LPAREN -> ( [3:11]
    |       |   |       |   |--ASSIGN -> = [3:17]
    |       |   |       |   |   |--IDENT -> line [3:12]
    |       |   |       |   |   `--METHOD_CALL -> ( [3:28]
    |       |   |       |   |       |--DOT -> . [3:23]
    |       |   |       |   |       |   |--IDENT -> file [3:19]
    |       |   |       |   |       |   `--IDENT -> read [3:24]
    |       |   |       |   |       |--ELIST -> ELIST [3:29]
    |       |   |       |   |       `--RPAREN -> ) [3:29]
    |       |   |       |   |--RPAREN -> ) [3:30]
    |       |   |       |   `--LITERAL_NULL -> null [3:35]
    |       |   |       `--LT -> < [3:57]
    |       |   |           |--IDENT -> noOfSQLErrors [3:43]
    |       |   |           `--IDENT -> maxErrors [3:59]
    |       |   |--RPAREN -> ) [3:68]
    |       |   `--SLIST -> { [3:70]
    |       |       `--RCURLY -> } [3:71]
    |       |--SINGLE_LINE_COMMENT -> // [3:73]
    |       |   `--COMMENT_CONTENT ->  violation\n [3:75]
    |       |--LITERAL_WHILE -> while [4:4]
    |       |   |--LPAREN -> ( [4:10]
    |       |   |--EXPR -> EXPR [4:32]
    |       |   |   `--NOT_EQUAL -> != [4:32]
    |       |   |       |--LPAREN -> ( [4:11]
    |       |   |       |--ASSIGN -> = [4:17]
    |       |   |       |   |--IDENT -> line [4:12]
    |       |   |       |   `--METHOD_CALL -> ( [4:28]
    |       |   |       |       |--DOT -> . [4:23]
    |       |   |       |       |   |--IDENT -> file [4:19]
    |       |   |       |       |   `--IDENT -> read [4:24]
    |       |   |       |       |--ELIST -> ELIST [4:29]
    |       |   |       |       `--RPAREN -> ) [4:29]
    |       |   |       |--RPAREN -> ) [4:30]
    |       |   |       `--LITERAL_NULL -> null [4:35]
    |       |   |--RPAREN -> ) [4:39]
    |       |   `--SLIST -> { [4:41]
    |       |       `--RCURLY -> } [4:42]
    |       |--SINGLE_LINE_COMMENT -> // [4:44]
    |       |   `--COMMENT_CONTENT ->  no violatin; specially allowed by Check, see doc\n [4:46]
    |       `--RCURLY -> } [5:2]
    `--RCURLY -> } [6:0]
```

**Comment by strkkk** [comment]
@romani what about output
> if xpath matches 2+ ASTs in different branches

?

**Comment by romani** [comment]
`java -jar checkstyle.jar --tree-branch-for-xpath='METHOD_DEF/LITERAL_WHILE' TestClass.java`
output something like:
```
CLASS_DEF -> CLASS_DEF [1:0]
`--OBJBLOCK -> OBJBLOCK [1:23]
    `--METHOD_DEF -> METHOD_DEF [2:2]
        `--SLIST -> { [2:16]
            |--LITERAL_WHILE -> while [3:4]
            `--LITERAL_WHILE -> while [4:4]

```

just show all parent nodes or matched node.

we can even print something like (no correction for tree pseudo symbols, so it will be clear for user that there are mode nodes in tree around matched):
```
CLASS_DEF -> CLASS_DEF [1:0]
`--OBJBLOCK -> OBJBLOCK [1:23]
    |--METHOD_DEF -> METHOD_DEF [2:2]
    |   `--SLIST -> { [2:16]
    |       |--LITERAL_WHILE -> while [3:4]
    |       |--LITERAL_WHILE -> while [4:4]
```

@rnveach, @pbludov , what mode of rendering do you prefer (with or without correction of `|`) ?

**Comment by strkkk** [comment]
@romani 
what about cases like
```
class A {
 void method1(){}

}
class B {
 void method2(){}
}
```
and command
```
java -jar checkstyle.jar --tree-branch-for-xpath='CLASS_DEF/METHOD_DEF' TestClass.java
```
?
There are two matches and they are not related. How output should like in this case?

**Comment by romani** [comment]
just imagine you print a tree as it is, you locate required nodes, and print all parents.

**Comment by romani** [comment]
@strkkk , ping.
Please let us know if you would like to fix this issue. If something is still not clear and require my reply please pin me

**Comment by strkkk** [comment]
@romani I have a code that solves this problem in my git stash, but it produces output for like this (2 matches):
```
           CLASS_DEF -> CLASS_DEF [12:0]
            `--OBJBLOCK -> OBJBLOCK [12:17]
                |--METHOD_DEF -> METHOD_DEF [13:4]
                |   |--MODIFIERS -> MODIFIERS [13:4]
                |   |--TYPE -> TYPE [13:4]
                |   |   `--LITERAL_VOID -> void [13:4]
                |   |--IDENT -> m1 [13:9]
                |   |--LPAREN -> ( [13:11]
                |   |--PARAMETERS -> PARAMETERS [13:12]
                |   |--RPAREN -> ) [13:12]
                |   `--SLIST -> { [13:13]
                |       `--RCURLY -> } [13:14]
            CLASS_DEF -> CLASS_DEF [12:0]
            `--OBJBLOCK -> OBJBLOCK [12:17]
                |--METHOD_DEF -> METHOD_DEF [14:4]
                |   |--MODIFIERS -> MODIFIERS [14:4]
                |   |--TYPE -> TYPE [14:4]
                |   |   `--LITERAL_VOID -> void [14:4]
                |   |--IDENT -> m2 [14:9]
                |   |--LPAREN -> ( [14:11]
                |   |--PARAMETERS -> PARAMETERS [14:12]
                |   |--RPAREN -> ) [14:12]
                |   `--SLIST -> { [14:13]
                |       `--RCURLY -> } [14:14]
```
query:
```
/CLASS_DEF[./IDENT[@text='Twomethods']]//METHOD_DEF
```
I do not have an idea right now how to merge common parents for results.

If such output is ok - I can submit a PR for it.

**Comment by romani** [comment]
It is better than nothing.
But please do not print child nodes and print some separator like "----" between matches. We can improve output later on. It is unlikely to be used in automations so can be changed at anytime.

**Comment by strkkk** [comment]
The issue came out when I run checkstyle - 
```
[checkstyle] [ERROR] C:\Users\Andrei_Paikin\IdeaProjects\checkstyle\src\main\java\com\puppycrawl\tools\checkstyle\Main.java:44:1: Disallowed import - net.sf.saxon.om.Item. [ImportControlMain]
```
Xpath stuff is forbidden outside specific packages, so it should be changed (I added method to Main class).
In my opinion it makes sense to allow these imports in utils package, and add method with xpath things to XpathUtil (surprisingly, there are nothing about xpath evaluation in this class)

Is it ok for you? @romani

**Comment by rnveach** [comment]
Fix was merged
