### ISSUE TITLE
Create appveyor.bat for CI commands

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#6696]
Similar to https://github.com/checkstyle/checkstyle/blob/master/.ci/travis/travis.sh we should look into creating an appveyor.bat for appveyor's long commands and allow windows users to run them locally.

https://github.com/checkstyle/checkstyle/blob/master/appveyor.yml#L101-L108
and
https://github.com/checkstyle/checkstyle/blob/master/appveyor.yml#L125-L133

**Comment by romani** [comment]
Fix is merged
