### ISSUE TITLE
Log severity for all audit events, not just warnings

### ISSUE THREAD

**Issue by richarddbarnett** [checkstyle/checkstyle#67]
`DefaultLogger.addError()` only logs `AuditEvent.severityLevel` if it's `WARNING`.
This makes it hard to find events of severity `ERROR` in eg `mvn checkstyle:check` output.
Log `severityLevel` in all cases.

**Comment by alexkravin** [comment]
If I understood everything correct..

In all places except for UTs this option is used with its default value (true), so new option was added to DefaultLogger's ctors and all calls of these ctors are updated with <b>true</b> value, except for BaseCheckTestSupport.

New createChecker() and verify() methods were introduced in BaseCheckTestSupport to support the setting of new option.

**Comment by romani** [comment]
will be in 6.5

**Comment by romani** [comment]
compatibility problem should be resolved https://groups.google.com/forum/#!topic/checkstyle-devel/3jJ4cCQ3sM0

**Comment by alexkravin** [comment]
Corresponding instantiation just have to be updated according to new params

**Comment by romani** [comment]
We can not wait for plugin to update that, maven plugin is still on very old version.
Please provide a solution to resolve that issue and do not brake compatibility.

**Comment by MEZk** [comment]
@romani 
Is it a good idea to implement setter for printSeverity variable?

**Comment by romani** [comment]
Not the best, i think that one mor c-tor will be better solution

**Comment by romani** [comment]
merged
