### ISSUE TITLE
New check: JavadocAsterisk

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#6702]
Checks that all leading asterisks are present and vertically aligned.
----------------------------------------------------------------------------------
```
/**
 * Some useful information.       // OK
*                                 // violation: unaligned asterisk
   *                              // violation: unaligned asterisk
 **                               // violation: missing asterisk
                                  // violation: missing asterisk
 **/                              // violation? Perhaps an option?
public class TestClass {
}
```
Currently, we use different styles:

- c-shaped for [token types](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java#L2486):
```
    /**
     * The {@code ~} (bitwise complement) operator.
     *
     * @see <a
     * href="https://docs.oracle.com/javase/specs/jls/se8/html/jls-15.html#jls-15.15.5">Java
     * Language Specification, &sect;15.15.5</a>
     * @see #EXPR
     **/
    public static final int BNOT = GeneratedJavaTokenTypes.BNOT;
```
- 1-shaped for [DescendantTokenCheck](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/DescendantTokenCheck.java#L389):
```
/**
  * Sets a maximum count for descendants.
  * @param maximumNumber the maximum count for descendants.
  */
```
- r-shaped for [the rest](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java#L32):
```
/**
 * Contains the constants for all the tokens contained in the Abstract
 * Syntax Tree.
 */
public final class TokenTypes {
```

Let's start with a simple check to catch mistypes [like this](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceAfterCheck.java#L36), then we will collect the wishes of the teams and add support for different styles, if it turns out to be useful.

**Comment by rnveach** [comment]
@pbludov There are 3 things going on in this issue.
Missing Asterisk.
Aserisk Indentation.
New line before tag.

We have found it is best to make these 3 separate checks, and each it's own issue.

>  `**                               // violation: missing asterisk`

I don't understand why you say it is missing when it is there. Even our tree says there is leading asterisk.

**Comment by pbludov** [comment]
> I don't understand why you say it is missing when it is there. Even our tree says there is leading asterisk.

The whitespace is missing, sorry.

**Comment by romani** [comment]
Please review https://docs.scala-lang.org/style/scaladoc.html for asterisks alignment, I am not sure why user prefer one style to another.

**Comment by rnveach** [comment]
> There are 3 things going on in this issue.
> We have found it is best to make these 3 separate checks, and each it's own issue.

If someone agrees, lets close this issue and create new ones for each individual item a check will validate.

**Comment by pbludov** [comment]
To summarize:
- JavadocMissingAsteriskCheck
```
/** Some text spawn
     multiple lines */      // violation

But this should be ok:
/** Text.
 * {@code
    int foo;
    int bar;
    }   // ok since all text in the code block belongs to the code block
 */
```

- JavadocAsteriskLocationCheck
```
/**
 * // property align=left
 */

/**
  * // property align=right
  */
```

- JavadocAsteriskWhitespaceCheck
```
/**
 * Default case. // property indent=1
 */

/** Scala-like style // for this line the indent decreased by 1
 *  Second line // property indent=2
 */

/**
 * This is unclear. Should the last line be ignored?
 **/ // <= ???

```

- JavadocTopLineCheck
```
/**
 * Default case. // property newLine=force
 */

/** Scala-like style // property newLine=deny
 *
 */
```

@rnveach, @romani, please share your thoughts for each check.

**Comment by romani** [comment]
>JavadocMissingAsteriskCheck

Is it allowed by javadoc tool ? Javadoc checks should always look at javadoc tool. If it error in javadoc tool, we probably should not validate it.

>Should the last line be ignored?

Yes

>JavadocTopLineCheck

It is called summary line. I think about property name allowEmptyLineBefore.

**Comment by pbludov** [comment]
> Is it allowed by javadoc tool

javadoc tool is very patient. For 
```
/**
 * Some useful information.
*Line2.
   * Line3.
Line4,
 ** Line5
 Line6 **/
public class TestClass {
}
```
The generated javadoc is
```
    public class TestClass
    extends java.lang.Object

    Some useful information. Line2. Line3. Line4, Line5 Line6
```
Note that the double asterisks in line 5 have also been removed.
For the line
```
   * * Text.
``` 
The output will be
```
* Text.
```
From [the spec](https://docs.oracle.com/en/java/javase/11/docs/specs/doc-comment-spec.html)
> When a documentation comment is read, leading asterisks (\*) on each line are discarded, and blanks and tabs that precede the initial asterisks (\*) are also discarded. If you omit the leading asterisk on a line, then the leading white space is no longer removed

**Comment by pbludov** [comment]
> It is called summary line. I think about property name allowEmptyLineBefore.

You mean a new property for https://checkstyle.org/config_javadoc.html#SummaryJavadoc
? It should be a three-state enum: DEMAND, DENY, DONTCARE.

**Comment by romani** [comment]
>javadoc tool is very patient

Ok , lets have a check on this. Information that you provided should be a rationale of Check.

>It should be a three-state enum

I do not like `DONTCARE` 
What about emptyLineBefore={DEMAND, DENY}. If user do not care it should not activate a Check.

**Comment by pbludov** [comment]
> What about emptyLineBefore={DEMAND, DENY}. If user do not care it should not activate a Check.

We already have `SummaryJavadoc`, so this may be a breaking change.

regression test:
```
[checkstyle] [ERROR] com/puppycrawl/tools/checkstyle/Main.java:88: First sentence of multi-line Javadoc should start with an empty line. [SummaryJavadoc]
[checkstyle] [ERROR] com/puppycrawl/tools/checkstyle/Main.java:513: First sentence of multi-line Javadoc should start with an empty line. [SummaryJavadoc]
[checkstyle] [ERROR] com/puppycrawl/tools/checkstyle/Main.java:541: First sentence of multi-line Javadoc should start with an empty line. [SummaryJavadoc]
[checkstyle] [ERROR] com/puppycrawl/tools/checkstyle/Main.java:616: First sentence of multi-line Javadoc should start with an empty line. [SummaryJavadoc]
[checkstyle] [ERROR] com/puppycrawl/tools/checkstyle/Main.java:630: First sentence of multi-line Javadoc should start with an empty line. [SummaryJavadoc]
[checkstyle] [ERROR] com/puppycrawl/tools/checkstyle/Main.java:663: First sentence of multi-line Javadoc should start with an empty line. [SummaryJavadoc]
[checkstyle] [ERROR] com/puppycrawl/tools/checkstyle/Main.java:671: First sentence of multi-line Javadoc should start with an empty line. [SummaryJavadoc]
[checkstyle] [ERROR] com/puppycrawl/tools/checkstyle/Main.java:684: First sentence of multi-line Javadoc should start with an empty line. [SummaryJavadoc]
[checkstyle] [ERROR] com/puppycrawl/tools/checkstyle/Main.java:692: First sentence of multi-line Javadoc should start with an empty line. [SummaryJavadoc]
[checkstyle] [ERROR] com/puppycrawl/tools/checkstyle/PackageNamesLoader.java:62: First sentence of multi-line Javadoc should start with an empty line. [SummaryJavadoc]
[checkstyle] [ERROR] com/puppycrawl/tools/checkstyle/api/FileContents.java:56: First sentence of multi-line Javadoc should start with an empty line. [SummaryJavadoc]
[checkstyle] [ERROR] com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java:1215: First sentence of multi-line Javadoc should start with an empty line. [SummaryJavadoc]
[checkstyle] [ERROR] com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java:1689: First sentence of multi-line Javadoc should start with an empty line. [SummaryJavadoc]
[checkstyle] [ERROR] com/puppycrawl/tools/checkstyle/api/LocalizedMessage.java:84: First sentence of multi-line Javadoc should start with an empty line. [SummaryJavadoc]
[checkstyle] [ERROR] com/puppycrawl/tools/checkstyle/checks/coding/HiddenFieldCheck.java:190: First sentence of multi-line Javadoc should start with an empty line. [SummaryJavadoc]
[checkstyle] [ERROR] com/puppycrawl/tools/checkstyle/checks/design/VisibilityModifierCheck.java:306: First sentence of multi-line Javadoc should start with an empty line. [SummaryJavadoc]
[checkstyle] [ERROR] com/puppycrawl/tools/checkstyle/checks/imports/CustomImportOrderCheck.java:699: First sentence of multi-line Javadoc should start with an empty line. [SummaryJavadoc]
[checkstyle] [ERROR] com/puppycrawl/tools/checkstyle/checks/imports/CustomImportOrderCheck.java:937: First sentence of multi-line Javadoc should start with an empty line. [SummaryJavadoc]
[checkstyle] [ERROR] com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheck.java:455: First sentence of multi-line Javadoc should start with an empty line. [SummaryJavadoc]
[checkstyle] [ERROR] com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocStyleCheck.java:76: First sentence of multi-line Javadoc should start with an empty line. [SummaryJavadoc]
[checkstyle] [ERROR] com/puppycrawl/tools/checkstyle/checks/sizes/ParameterNumberCheck.java:133: First sentence of multi-line Javadoc should start with an empty line. [SummaryJavadoc]
[checkstyle] [ERROR] com/puppycrawl/tools/checkstyle/AbstractPathTestSupport.java:58: First sentence of multi-line Javadoc should start with an empty line. [SummaryJavadoc]
[checkstyle] [ERROR] com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheckTest.java:429: First sentence of multi-line Javadoc should start with an empty line. [SummaryJavadoc]
[checkstyle] [ERROR] com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheckTest.java:447: First sentence of multi-line Javadoc should start with an empty line. [SummaryJavadoc]
[checkstyle] [ERROR] com/puppycrawl/tools/checkstyle/gui/CodeSelectorPresentationTest.java:59: First sentence of multi-line Javadoc should start with an empty line. [SummaryJavadoc]
```
It is better to add a new property with "break nothing" as the default value.

**Comment by rnveach** [comment]
> You mean a new property for https://checkstyle.org/config_javadoc.html#SummaryJavadoc?

Unless @romani states otherwise, which I haven't seen, I don't think this should be in the existing check. We are trying to cut back on checks doing too much. We are just now splitting MissingJavadoc from all existing Javadoc entries. I just saw a stackoverflow from someone disabling this check for requiring a period for the first sentence. I think these should be all new checks.

> DONTCARE

They should just disable/remove the check if they don't care.

> Note that the double asterisks in line 5 have also been removed.

@romani Please confirm if our Javadoc antlr should also say double asterisks are leading asterisks. Right now it only sees the first as a leading asterisk as I stated earlier, so we would need a new issue.

**Comment by romani** [comment]
> Please confirm if our Javadoc antlr should also say double asterisks are leading asterisks

I do not think it should be treated like this.
If no good reason in javadoc tool written about this double asterisk , we should keep it as text.
