### ISSUE TITLE
new check: MissingJavadocPackageCheck 

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#6705]
Split from https://github.com/checkstyle/checkstyle/issues/5411 ,

We should create a new check for missing javadocs on package-info.java files.

**Comment by rnveach** [comment]
@romani @pbludov Could naming of this check cause confusion with `JavadocPackage`?
http://checkstyle.sourceforge.net/config_javadoc.html#JavadocPackage

Current check ensures `package-info.java` file exists. New check will ensure `package-info.java` has a javadoc.

**Comment by pbludov** [comment]
> Could naming of this check cause confusion with `JavadocPackage`?

Yes, the existing check's name is not clear, but this can not be changed.
I like the name of the new check.

**Comment by romani** [comment]
Fix is merged
