### ISSUE TITLE
investigate increase of '-all' jar

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#6713]
detected at https://github.com/checkstyle/eclipse-cs/pull/158#issuecomment-489078070

https://github.com/checkstyle/checkstyle/releases
checkstyle-8.19-all.jar 23.1 MB
checkstyle-8.18-all.jar 11 MB

quick compare of unzipped jars show diff:
<img width="351" alt="Screen Shot 2019-05-03 at 5 55 14 AM" src="https://user-images.githubusercontent.com/812984/57138641-0d610800-6d68-11e9-954a-016d7e0efd2d.png">

**Comment by rnveach** [comment]
Printing the results of building the all-jar with debug on shows it is coming from saxon.
````
[DEBUG]    net.sf.saxon:Saxon-HE:jar:9.9.1-2:compile
[DEBUG]       com.ibm.icu:icu4j:jar:63.1:compile
````

> International Component for Unicode for Java (ICU4J) is a mature, widely used Java library providing Unicode and Globalization support 

I downloaded saxon's source zip file and couldn't find any usage of `icu`.
I did find this on their site: https://sourceforge.net/p/saxon/mailman/message/32363002/
Makes it sound like it is brought in as a driver.

I excluded `icu4j` from the build and all the tests still pass and the all-jar is back to 11.2 megs.
````
    <dependency>
      <groupId>net.sf.saxon</groupId>
      <artifactId>Saxon-HE</artifactId>
      <version>${saxon.version}</version>
      <exclusions>
        <exclusion>
          <groupId>com.ibm.icu</groupId>
          <artifactId>icu4j</artifactId>
        </exclusion>
      </exclusions> 
    </dependency>
````

**Comment by romani** [comment]
Please send PR

**Comment by romani** [comment]
Fix is merged
