### ISSUE TITLE
Forum link reports 401

### ISSUE THREAD

**Issue by aaime** [checkstyle/checkstyle#6714]
Following the README.md link to the forum returns a 401 (Unauthorized), wondering if there are security setup issues?

https://groups.google.com/forum/?hl=en#!forum/checkstyle

**Comment by romani** [comment]
please use login to access content.
![image](https://user-images.githubusercontent.com/812984/57194275-e33f4f80-6ef9-11e9-945d-6822d994a041.png)

looks like some weird bug of Google groups, you suppose to to see content without authorization.
we will monitor this for few days.

**Comment by aaime** [comment]
Does not help, I'm logged in and still seeing the same problem:

![image](https://user-images.githubusercontent.com/325433/57194376-9fbf0280-6f46-11e9-9500-f09f1744ce09.png)

**Comment by romani** [comment]
try now , I re-saved, basic permission settings , if does not work, it is problem on google side.
they do in May some work, https://support.google.com/a/answer/9191148, we should not be affected, but it might be some unrelated unfortunate side effects

**Comment by aaime** [comment]
Yes, now it works, whether I'm logged in, or not. Thank you!

**Comment by romani** [comment]
good, thanks a lot for reporting the issue.
I applied the same for others forums, just in case.
