### ISSUE TITLE
Check empty 

### ISSUE THREAD

**Issue by aaime** [checkstyle/checkstyle#6715]
Checkstyle is not reporting issues about method parameters with no description in javadoc:

```
    /**
     * Converts an OGR feature into a GeoTools one
     *
     * @param schema
     * @param ogrFeature
     * @return
     * @throws IOException
     */
    SimpleFeature convertOgrFeature(Object ogrFeature) throws IOException {

    }
```

In particular:

- ``schema`` is not a method parameter (it would have been reported if it had a description)
- ``ogrFeature`` is, but I would like it to be reported as having a missing description

The configuration for javadoc checks is:

```
    <module name="JavadocMethod">
      <property name="allowMissingParamTags" value="true"/>
      <property name="allowMissingThrowsTags" value="true"/>
      <property name="allowMissingReturnTag" value="true"/>
      <property name="allowMissingJavadoc" value="true"/>
      <property name="allowMissingPropertyJavadoc" value="true"/>
      <property name="suppressLoadErrors" value="true"/>
    </module>
```

My undrestanding from the ``allowMissingJavadoc`` documentation is that it should ignore methods without a javadoc, but does not say anything about the method itself.

**Comment by romani** [comment]
Please report issue strictly as described at https://github.com/checkstyle/checkstyle/blob/master/.github/ISSUE_TEMPLATE.md in other case we will close issue

**Comment by aaime** [comment]
I run checkstyle with maven and have a full project, not a standalone file. Will see if I find the time to turn it into a fully self contained report, in the meantime, I'll close this one.

**Comment by romani** [comment]
CLi is able to run on folder, code can be obfuscated/shortened enough to be compilable.
