### ISSUE TITLE
new check: JavadocMissingLeadingAsteriskCheck

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#6722]
Checks that each doc comment line start with the asterisk symbol (`*`)

Rationale: messy comments usually indicates a write-only code. At the very least, they should be arranged.

```
/**
  * OK
  */

/**
 ** OK
 *
    violation
 **/

/** Some text spawn
     multiple lines */      // violation

Even for code blocks:
/**
 * {@code
 *  int foo; // OK
    int bar; // violation
    }   // violation
 */
```

**Comment by rnveach** [comment]
I am fine with this and don't see any issues.

@romani If you are ok, please put approve label.

**Comment by pbludov** [comment]
> > MissingLeadingAsteriskCheck
> What about `MissingLeadAsteriskCheck`? Removed `ing` from leading.

Short name is good, but not in this case. "Leading asterisk" is a well known name. It is used in the specs and the [API](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java#L1187)

**Comment by rnveach** [comment]
Ok. Even our tree calls it `LEADING_ASTERISK`.

**Comment by romani** [comment]
looks good.

**Comment by sd1998** [comment]
@romani I am working on this.

**Comment by romani** [comment]
@sd1998 , thanks a lot for help.
Please try to be responsive in your PRs, we need to finish what you already started.

**Comment by Gaurav-Punjabi** [comment]
@sd1998 are you still working on this? 
If not can I work on this one?

**Comment by Gaurav-Punjabi** [comment]
@romani Can I work on this issue? Since it hasn’t been touched in the last 3 months.

**Comment by romani** [comment]
@Gaurav-Punjabi , please help us to resolve this issue.

**Comment by Gaurav-Punjabi** [comment]
I'm on it.

**Comment by rnveach** [comment]
Fix was merged
