### ISSUE TITLE
new check: JavadocSummaryLocationCheck

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#6724]
Checks the location where starts the summary for multi-line javadoc comments.

* Property `location`: `secondLine` for java style, `firstLine` for scala style.

* location=secondLine (default)
```
/**
 * OK
 */

/** violation
 */

/** OK (one-line comments ignored) **/
```

* location=firstLine
```
/**
 * violation
 */

/** OK
 */

/** OK (one-line comments ignored) **/
```

**Comment by rnveach** [comment]
Please update first post and show some violation cases with each option.

> Property emptyLine: always for java style, never for scala style.

Why shouldn't the options be named after the style? Instead of `always` why not make it `java`?

**Comment by pbludov** [comment]
> @pbludov Please update first post and show some violation cases with each option.

done
> > Property emptyLine: always for java style, never for scala style.
> Why shouldn't the options be named after the style? Instead of `always` why not make it `java` and make the property named `emptyLineStyle`?

I don't agree.
The option `emptyLine` with values `always`/`never` is more intuitive. And consistent with many other checks. The option `emptyLineStyle` assumes that people knows what the `java` style is. It is less obvious.

**Comment by rnveach** [comment]
@romani Please review.

**Comment by romani** [comment]
>Instead of always why not make it java and make the property named emptyLineStyle

not good, it will be the same design problem as we had with C and C++ comments vs singleline and multiline.

---

EmptyLineBeforeJavadocSummary already imply that all in this Check will be in about empty line, so properties `emptyLine=always` looks a bit strange.
Empty line can be present or be absent, so simple boolean flag should be ok, `noEmptyLine=true|false` (but this is complete negation of Check title ..... really weird)

specific types values will result in extension of  
https://checkstyle.org/property_types.html , it is ok, but something tell me it is better to avoid if possible.
I do not have very strict position on this.


-----

just another idea:

JavadocSummaryLocationCheck
location="firstLine, secondLine, secondLineIndented, .... "
In this case config is readable and terms are not conflicting.

I do not think we need this option in first implementation, just example of extending a design.
`location = secondLineIndented (default)`

```
/**
 *  OK
 */
/**
 * violation
 */
/** violation
 */

/** OK (one-line comments ignored) **/
```
Does it make sense ?

**Comment by pbludov** [comment]
> Does it make sense ?

I like `JavadocSummaryLocation`. It is short and intuitive.

The indentation should remain the same for all sentences, so it should be out of the scope of this check.

**Comment by romani** [comment]
@rnveach , please finalize approval of design. If you agree, put a label and remove all our comments, to clean up issue from unnecessary details.

**Comment by pbludov** [comment]
Some ASTs:
```
/** Singleline comment */
package test;

BLOCK_COMMENT_BEGIN -> /* [1:0]
|--COMMENT_CONTENT -> * Singleline comment  [1:2]
|   `--JAVADOC -> JAVADOC [1:3]
|       |--TEXT ->  Singleline comment  [1:3]
|       `--EOF -> <EOF> [1:23]
`--BLOCK_COMMENT_END -> */ [1:22]
PACKAGE_DEF -> package [2:0]
|--ANNOTATIONS -> ANNOTATIONS [2:8]
|--IDENT -> test [2:8]
`--SEMI -> ; [2:12]
```

```
/** Scala style
  * comment
  */
package test;

BLOCK_COMMENT_BEGIN -> /* [1:0]
|--COMMENT_CONTENT -> * Scala style\n *  comment\n   [1:2]
|   `--JAVADOC -> JAVADOC [1:3]
|       |--TEXT ->  Scala style [1:3]
|       |--NEWLINE -> \n [1:15]
|       |--LEADING_ASTERISK ->  * [2:0]
|       |--TEXT ->   comment [2:2]
|       |--NEWLINE -> \n [2:11]
|       |--TEXT ->    [3:0]
|       `--EOF -> <EOF> [3:2]
`--BLOCK_COMMENT_END -> */ [3:2]
PACKAGE_DEF -> package [4:0]
|--ANNOTATIONS -> ANNOTATIONS [4:8]
|--IDENT -> test [4:8]
`--SEMI -> ; [4:12]
```

```
/**
 * Java style
 * comment
 */
package test;

BLOCK_COMMENT_BEGIN -> /* [1:0]
|--COMMENT_CONTENT -> *\n * Java style\n * comment\n  [1:2]
|   `--JAVADOC -> JAVADOC [1:3]
|       |--NEWLINE -> \n [1:3]
|       |--LEADING_ASTERISK ->  * [2:0]
|       |--TEXT ->  Java style [2:2]
|       |--NEWLINE -> \n [2:13]
|       |--LEADING_ASTERISK ->  * [3:0]
|       |--TEXT ->  comment [3:2]
|       |--NEWLINE -> \n [3:10]
|       |--TEXT ->   [4:0]
|       `--EOF -> <EOF> [4:1]
`--BLOCK_COMMENT_END -> */ [4:1]
PACKAGE_DEF -> package [5:0]
|--ANNOTATIONS -> ANNOTATIONS [5:8]
|--IDENT -> test [5:8]
`--SEMI -> ; [5:12]
```

**Comment by romani** [comment]
Fix is merged
