### ISSUE TITLE
 Align XDocs and Javadocs for filters package 

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#6726]
Part of #5750

Package com.puppycrawl.tools.checkstyle.filter:

- [x] BeforeExecutionExclusionFileFilter
- [x] SeverityMatchFilter #6896
- [x] SuppressionCommentFilter #6839
- [x] SuppressionFilter #6788
- [x] SuppressionXpathFilter #6898
- [x] SuppressionXpathSingleFilter #6922
- [x] SuppressWarningsFilter #6895
- [x] SuppressWithNearbyCommentFilter #6877
- [x] SuppressWithPlainTextCommentFilter #6881

**Comment by rnveach** [comment]
All fixes merged.
