### ISSUE TITLE
ClassFanOutComplexityCheck / AbstractClassCouplingCheck defaultExcludedClasses override include defaults

### ISSUE THREAD

**Issue by wvdhaute** [checkstyle/checkstyle#6734]
[ClassFanOutComplexityCheck](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/ClassFanOutComplexityCheck.java) 

Looking at the implementation of [AbstractClassCouplingCheck](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/AbstractClassCouplingCheck.java), when one overrides the excludedClasses, the default ones are not concatenated by design.

Would by default including the default list not make sense here?
We found this counter intuitive to be honest and had to dive into the source code

The alternative is using the regex off course.

**Comment by romani** [comment]
> when one overrides the excludedClasses

do you mean in configuration ?
In think case please report issue strictly as defined in issue template, it will answer all my questions to you. 

> The alternative is using the regex off course.

please provide examples why you need regexp.

**Comment by wvdhaute** [comment]
No, when configuring in sonar, no custom implementation.

The DEFAULT_EXCLUDED_CLASSES  constant in https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/AbstractClassCouplingCheck.java is just overwritten when I specify this in sonar for this rule.

We found this to be counterintuitive.

So to not have to explicitly specify the whole list from DEFAULT_EXCLUDED_CLASSES, we used the excludeClassesRegexps configuration

**Comment by romani** [comment]
please report issue strictly as defined in issue template

**Comment by wvdhaute** [comment]
Apologies for the confusion.
It's more a feature request.

**Our Sonar Class Fan Out Complexity rule configuration:**

`
excludedClasses: org.springframework.security.access.prepost.PreAuthorize
`

With this configuration we saw that previously excluded classes were now taken into account for the rule check

* String
* List
* HashMap
* ... 

i.e. the classes in the DEFAULT_EXCLUDED_CLASSES set in [AbstractClassCouplingCheck](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/AbstractClassCouplingCheck.java) ) 

The workaround was to use:

`
excludeClassesRegexps : org\.springframework\.security\.access\.prepost\.PreAuthorize
`

The rule works ok, no bugs in there, just the configuration setup confused us here.
By setting the **excludedClasses** configuration, we lost all the default ones.
We expected our PreAuthorize class to be added to the DEFAULT_EXCLUDED_CLASSES set

I understand this can be by design, but might it not be a good thing to add to the set instead of replace?

**Comment by romani** [comment]
>It's more a feature request.

please report issue strictly as defined in issue template
https://checkstyle.org/report_issue.html#How_to_report_a_bug.3F
You need to do this.

I already see, your problem, and it is by design, to let user override any default values of any property, as result there is some inconvenience if you agree on default and just want to extend it

**Comment by wvdhaute** [comment]
Hey,

Sorry but not sure what you want me to do with the issue template as what I am asking is not an issue, its a feature request, I tried to be as detailed as possible here.

I do understand your point in a way.

Is introducing an extra confinguration setting not a valid option?

So where now it is:

* excludedClasses 
* excludedPackages 

Have an extra option:

* defaultExcludedClasses

So anyone who wants to override the default values can use that one? Feels like not alot of people will want to remove a class from the DEFAULT_EXCLUDED_CLASSES set but that way they can using this option and others that want to add specific classes do not have to add the big set of defaults.
