### ISSUE TITLE
Reference to JLS is not correct in PackageAnnotation documentation

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#674]
There are couple of problems with [PackageAnnotation documentation](http://checkstyle.sourceforge.net/config_annotation.html#PackageAnnotation)
* Link http://java.sun.com/docs/books/jls/third_edition/html/j3TOC.html redirects to http://docs.oracle.com/javase/specs/ - should be http://docs.oracle.com/javase/specs/jls/se5.0/html/j3TOC.html instead
* _According to the Java JLS 3rd ed_ - JLS third edition is quite outdated. Do we want to upgrade here and refer to newer JLS?
* Link should bring user to specified paragraph, not the table of contents
* There is no section 7.4.1.1 in JLS for Java 7 and Java 8

**Comment by romani** [comment]
thanks a lot, please update links and do PR.

**Comment by romani** [comment]
fixed, will be in 6.5
