### ISSUE TITLE
Improve VisibilityModifier documentation for Rationale 

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#6745]
detected at https://github.com/checkstyle/checkstyle/pull/6733

at https://checkstyle.org/config_design.html#VisibilityModifier

there are two "Rationale", one is for Check and second is for property.

Second "Rationale:" is better to reword to "Property Rationale:"

**Comment by wltan** [comment]
Can I also request that the formatting of the description be slightly adjusted? Right now there are quite a few terms being **bolded**, but I don't think it is necessary to bold all of them.

I propose that all the property names being mentioned (`ignoreAnnotationCanonicalNames`, `allowPublicFinalFields`, `allowPublicImmutableFields`) can remain bolded to be consistent with `ThrowsCount` documentation, but all other usages are unbolded.

Other than that this looks simple enough. Will work on it once my other PRs are done.

**Comment by rnveach** [comment]
@romani ping

> Can I also request that the formatting of the description be slightly adjusted? Right now there are quite a few terms being bolded, but I don't think it is necessary to bold all of them.

Please clarify if this is also being changed or not.

**Comment by romani** [comment]
I am ok to change to improve in general, we will see exact wording in PR

**Comment by romani** [comment]
fix is merged.
