### ISSUE TITLE
 Align XDocs and Javadocs for whitespace package

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#6749]
Part of #5750

Package com.puppycrawl.tools.checkstyle.checks.whitespace:

- [x] EmptyForInitializerPad #6751
- [x] EmptyForIteratorPad #6761
- [x] EmptyLineSeparator #6769
- [x] FileTabCharacter #6753
- [x] GenericWhitespace #6762
- [x] MethodParamPad #6754
- [x] NoLineWrap #6755
- [x] NoWhitespaceAfter #6763 #6768
- [x] NoWhitespaceBefore #6765
- [x] OperatorWrap #6770
- [x] ParenPad #6756
- [x] SeparatorWrap #6766
- [x] SingleSpaceSeparator #6757
- [x] TypecastParenPad #6758
- [x] WhitespaceAfter #6759
- [x] WhitespaceAround #6767

**Comment by romani** [comment]
@pbludov , thank you very much for hard work to make it done.
