### ISSUE TITLE
Fix sonar warnings

### ISSUE THREAD

**Issue by strkkk** [checkstyle/checkstyle#6764]
List of sonar warnings to correct:
1. https://sonarcloud.io/project/issues?id=com.puppycrawl.tools%3Acheckstyle&open=AWkisA05gtFwgfOLg-aa&resolved=false&severities=MINOR&types=CODE_SMELL
2. https://sonarcloud.io/project/issues?id=com.puppycrawl.tools%3Acheckstyle&open=AWb-Jn2kTJjFgJLTEG8I&resolved=false&severities=MAJOR&types=CODE_SMELL
3. https://sonarcloud.io/project/issues?id=com.puppycrawl.tools%3Acheckstyle&open=AWb-Jn2kTJjFgJLTEG8I&resolved=false&severities=MAJOR&types=CODE_SMELL
4. https://sonarcloud.io/project/issues?id=com.puppycrawl.tools%3Acheckstyle&open=AV3yuSS3pvRVEt3b0XpD&resolved=false&severities=MINOR&types=CODE_SMELL

Also change following code for more functional style:
1. https://github.com/checkstyle/checkstyle/blob/51bf6a69f1e4d3e11503f539facdfd099a944af7/src/main/java/com/puppycrawl/tools/checkstyle/checks/TranslationCheck.java#L263-L267
2. https://github.com/checkstyle/checkstyle/blob/51bf6a69f1e4d3e11503f539facdfd099a944af7/src/main/java/com/puppycrawl/tools/checkstyle/checks/TranslationCheck.java#L278-L281

**Comment by rnveach** [comment]
@romani Is there any way to get these warnings as part of our CI as long as we can suppress some, like `Replace this use of System.out or System.err by a logger`?

**Comment by romani** [comment]
I was not possible to set up custom gates (trigger of build failure) and suppressions. But now it is possible to hook PR validation, but still no customization , or it need to be deeply investigated.

**Comment by romani** [comment]
https://www.java67.com/2018/03/java-convert-string-to-boolean.html?m=1

>The parseBoolean() returns a primitive boolean value while valueOf() returns a Boolean object.

**Comment by romani** [comment]
>4

I am not sure this is good suggestion.
Let's try and see ... But in separate commit to not block others.

**Comment by rnveach** [comment]
> > 4

> I am not sure this is good suggestion.

At one point we discussed requiring curly braces for lambdas if they span more then 1 line just like if we had an if statement that spanned a line.
See https://github.com/checkstyle/checkstyle/issues/3837

**Comment by strkkk** [comment]
@romani @rnveach some lines will be longer than 100 chars if we put whole lambda in one line.
And yes, if lambda has more than one line, CI requires braces.
Here lambda is short enough to be one-liner.

May be sonar quality gate should be adjust to ignore this issues.

**Comment by romani** [comment]
Now it is possible to mark violation as won't fix in web to.
I marked it , on next build it should disappear.

**Comment by rnveach** [comment]
Fixes were merged.
