### ISSUE TITLE
OneStatementPerLine try-with-resources changed in 8.21

### ISSUE THREAD

**Issue by snago** [checkstyle/checkstyle#6790]
```
~/checkstyle_test $ cat TestClass.java
public class TestClass {
    void method() {
        try (OutputStream os1 = new Stream(); OutputStream os2 = new Stream()) {
        }
    }
}

~/checkstyle_test $ cat TestConfig.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>

    <module name="TreeWalker">
       <module name="OneStatementPerLineCheck" />
    </module>
</module>

~/checkstyle_test $ java -jar checkstyle-8.20-all.jar -c TestConfig.xml TestClass.java
Starting audit...
Audit done.

~/checkstyle_test $ java -jar checkstyle-8.21-all.jar -c TestConfig.xml TestClass.java
Starting audit...
[ERROR] C:\TestClass.java:3:60: Only one statement per line allowed. [OneStatementPerLine]
Audit done.
Checkstyle ends with 1 errors.

```

---------------

It looks like the fix for #6125 made OneStatementPerLine reject multiple resources on the same row.

From https://github.com/checkstyle/checkstyle/issues/6125#issuecomment-492650963:
> I am pretty sure there will be bunch of users who disagree. But lets give them a chance to request new feature/property in Check to no treat "try-with-resources" expressions as statements at all.

I'm one of those users that disagree and would very much like that option :)

**Comment by rnveach** [comment]
@snago Until it is fixed, you can always use xpath to suppress it.

````
$ cat TestClass.java
public class TestClass {
    void method() {
        try (OutputStream os1 = new ByteArrayOutputStream(); OutputStream os2 = new ByteArrayOutputStream()) {
        }
    }
}


$ cat TestConfig.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>

    <module name="TreeWalker">
       <module name="OneStatementPerLineCheck" />
<module name="SuppressionXpathSingleFilter">
  <property name="checks" value="OneStatementPerLineCheck"/>
  <property name="query" value="//LITERAL_TRY/RESOURCE_SPECIFICATION/RESOURCES/SEMI"/>
</module>
    </module>
</module>

$ java -jar checkstyle-8.21-all.jar -c TestConfig.xml TestClass.java
Starting audit...
Audit done.
````

**Comment by snago** [comment]
Thanks for the workaround! 😄

**Comment by romani** [comment]
We need to create new property in Check to decide on how to treat content in try-with-resources as expressions or as statements.
proposal: `treatTryResourcesAsStatement=true|false`.  With default value as "false", as [by jdk specification](https://docs.oracle.com/javase/specs/jls/se7/html/jls-14.html#jls-14.20.3) it is not a statement it is something special.

So with default config OneStatementPerLineCheck should return to it original behavior of 8.20 version, and users who requested #6125  should use `treatTryResourcesAsStatement=true`.

**Comment by strkkk** [comment]
@romani 
> So with default config OneStatementPerLineCheck should return to it original behavior of 8.20 version, and users who requested #6125 should use `treatTryResourcesAsStatement=true`.

I won't be same as in 8.20
Before 6125 cases like 
```
try(Reader r = new PipedReader(); Reader r1 = new PipedReader() ; Reader r2 = new PipedReader()) {} 
```
were reported as violation because there are 2 statements on same line.
With this property there will be no violation.

So it is different.

Is it ok?

**Comment by romani** [comment]
it is better to talk about nuances by command line output.

Nuance:
```
/var/tmp$ cat TestConfig.xml 
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
<module name="Checker">
    <module name="TreeWalker">
       <module name="OneStatementPerLineCheck" />
    </module>
</module>

/var/tmp$ cat TestClass.java 
public class TestClass {
    void method() {
        try (OutputStream os1 = new Stream(); OutputStream os2 = new Stream()) {}

        try (OutputStream os1 = new Stream(); OutputStream os2 = new Stream();) {} //violation

        try(Reader r = new PipedReader(); Reader r1 = new PipedReader() ; Reader r2 = new PipedReader()) {} // violation
    }
}

/var/tmp$ java -jar checkstyle-8.20-all.jar -c TestConfig.xml TestClass.java
Starting audit...
[ERROR] /var/tmp/TestClass.java:5:78: Only one statement per line allowed. [OneStatementPerLine]
[ERROR] /var/tmp/TestClass.java:7:73: Only one statement per line allowed. [OneStatementPerLine]
Audit done.
Checkstyle ends with 2 errors.

```

**Comment by romani** [comment]
@snago and @strkkk , is there any ideas on how to reconcile a problem ?

**Comment by snago** [comment]
I'm not sure I understand what the problem is.
Is it that 1 semicolon inside the try-with-resources parenthesis was OK in 8.20, but not two or more?

**Comment by strkkk** [comment]
> Is it that 1 semicolon inside the try-with-resources parenthesis was OK in 8.20, but not two or more?

Yeap.
In 6125 I changed the logic for detecting statements in try-with-resources. 
Previously, it was just "number of semicolons = number of statements" but in try-with-resources last semicolon can be omitted. 
So, before it was like
1 semicolon, 2 resources -> ok
2 semicolons, 2+ resources -> violation

Now it is:
1 semicolon, 2 resources -> violation
2 semicolons, 2+ resources -> violation
In my opinion, this one is correct behavior of this check.

If we add property to ignore resources;
1 semicolon, 2 resources -> ok
2 semicolons, 2+ resources -> ok

So, it won't be same as before.

**Comment by snago** [comment]
OK, now I understand.
In my opinion the option with the property is fine even if it isn't exactly like before.

**Comment by romani** [comment]
We need to skip try resources by default. We should make `treatTryResourcesAsStatement` .

**Comment by romani** [comment]
fix is merged

**Comment by rnveach** [comment]
@romani I updated title for release notes so it is clearer what is new. Feel free to make any changes.
