### ISSUE TITLE
Limit xdoc Properties subsection to one table

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#6800]
From comment https://github.com/checkstyle/checkstyle/pull/6788#pullrequestreview-243464770

The properties section has a special purpose: the properties table.
Everything else should be moved to `Nodes` or `Description`.

The test `XdocsPagesTest#validatePropertySection` should verify this limit.

**Comment by rnveach** [comment]
> I couldn't find it but there is an issue somewhere about creating a new section in the check/filter for external configuration files like this.

Were you able to find this issue before creating this one?

**Comment by romani** [comment]
Approved. Even we find another issue, it will not block this issue, we can update doc in few steps

**Comment by romani** [comment]
fix is merged.
