### ISSUE TITLE
Getting "Unable to get class information for @throws tag" when using complete class name in the javadoc

### ISSUE THREAD

**Issue by tmortagne** [checkstyle/checkstyle#6802]
Since Checkstyle 8.21 the following fail with

> JavadocMethod: Unable to get class information for @throws tag 'org.xwiki.rendering.macro.MacroExecutionException'.

```
    /**
     * @param parameters the Rss macro's parameters needed for getting the data
     * @return the feed's data 
     * @throws org.xwiki.rendering.macro.MacroExecutionException in case the feed cannot be read
     */
    SyndFeed createFeed(RssMacroParameters parameters) throws MacroExecutionException;
```

If I change the javadoc to use the short name instead I don't have any failure anymore.

The complete failing source file can been seen at https://github.com/xwiki/xwiki-platform/blob/c210de4fa72bb651ff4bd1581c2f31a2fc4d7787/xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-macros/xwiki-platform-rendering-macro-rss/src/main/java/org/xwiki/rendering/internal/macro/rss/RomeFeedFactory.java#L37.

**Comment by rnveach** [comment]
@tmortagne Please see http://checkstyle.sourceforge.net/report_issue.html#How_to_report_a_bug.3F .

It looks like you use maven-checkstyle-plugin. Is this error only occur in the maven plugin?
They did a release recently that broke classloading in some fashion that sounds like this. I will try to find the issue link.

**Comment by tmortagne** [comment]
Indeed I also upgraded the plugin so you are probably right. Thanks for the info @rnveach !

**Comment by romani** [comment]
Report in required format would help a lot.

loading of Classes from class path is deprecated in Checkstyle.
It is better to avoid this.

workaround from MCHECKSTYLE-377
> Workaround: Don't use fully qualified exception class names in @throws.

@rnveach , looks like we need to completely disable class loading in ALL Checks that use this, as it cause exceptions on user side, it is better for Check to report nothing at all (false-negatives) rather then exceptions and false-positives. Do you agree ?

**Comment by romani** [comment]
I was not able to reproduce problem:
```
rivanov@p5510:/var/tmp$ cat config.xml 
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
    <module name="TreeWalker">
        <module name="JavadocMethod">
          <property name="validateThrows" value="true"/>
        </module>
    </module>
</module>
rivanov@p5510:/var/tmp$ cat Test.java 
public class Test {
    /**
     * @param parameters the Rss macro's parameters needed for getting the data
     * @return the feed's data
     * @throws org.xwiki.rendering.macro.MacroExecutionException in case the feed cannot be read
     */
    SyndFeed createFeed(RssMacroParameters parameters) throws MacroExecutionException;
}

rivanov@p5510:/var/tmp$ java -jar checkstyle-8.21-all.jar -c config.xml Test.java
Starting audit...
[ERROR] /var/tmp/Test.java:5:8: Unable to get class information for @throws tag 'org.xwiki.rendering.macro.MacroExecutionException'. [JavadocMethod]
[ERROR] /var/tmp/Test.java:7:63: Unable to get class information for @throws tag 'MacroExecutionException'. [JavadocMethod]
Audit done.
Checkstyle ends with 2 errors.
```

@tmortagne , please share config for `JavadocMethod`

**Comment by tmortagne** [comment]
@romani you can see it on https://github.com/xwiki/xwiki-commons/blob/master/xwiki-commons-tools/xwiki-commons-tool-verification-resources/src/main/resources/checkstyle.xml#L203

**Comment by romani** [comment]
@tmortagne , do you still have a problem ?
We still use your project in our regression on CI, no issues on our side with your code

**Comment by tmortagne** [comment]
I downgraded the plugin based on @rnveach suggestion actually and it's OK now.
