### ISSUE TITLE
Missing error for module JavadocType since 8.20

### ISSUE THREAD

**Issue by alexbde** [checkstyle/checkstyle#6808]
```
/var/tmp $ javac JavadocType.java

/var/tmp $ cat JavadocType.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
          "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name = "Checker">
    <module name="TreeWalker">
        <module name="JavadocType"/>
    </module>
</module>

/var/tmp $ cat JavadocType.java
public class JavadocType {

}

/var/tmp $ java -Duser.language=en -Duser.country=US -jar checkstyle-8.21-all.jar -c JavadocType.xml JavadocType.java
Starting audit...
Audit done.
```

---------------

Expected error `Missing a Javadoc comment. [JavadocType]` is missing.

--------------

Problem exists since Checkstyle 8.20, with Checkstyle 8.19 error displays as expected (see below).

**Checkstyle 8.20**

```
$ java -Duser.language=en -Duser.country=US -jar checkstyle-8.20-all.jar -c JavadocType.xml JavadocType.java
Starting audit...
Audit done.
```

**Checkstyle 8.19**

```
$ java -Duser.language=en -Duser.country=US -jar checkstyle-8.19-all.jar -c JavadocType.xml JavadocType.java
Starting audit...
[ERROR] /var/tmp/JavadocType.java:1: Missing a Javadoc comment. [JavadocType]
Audit done.
Checkstyle ends with 1 errors.
```

**Comment by rnveach** [comment]
@alexbde This is intended.
http://checkstyle.sourceforge.net/releasenotes.html#Release_8.20
https://github.com/checkstyle/checkstyle/issues/5411 split JavadocType module into 2 modules. One for checking if the javadoc is required, and the other for validating the contents of the javadoc.
Please add `MissingJavadocType` to your configuration to bring back the missing functionality.

**Comment by alexbde** [comment]
Thanky you very much for clarifying :)
