### ISSUE TITLE
Separate configuration for constructor max parameters

### ISSUE THREAD

**Issue by ckorakidis** [checkstyle/checkstyle#683]
There are cases where all fields of a class are final or for other reasons there is need to have a constructor with all fields as parameters.
It would be valuable to have a different policy on the max params on constructors due to such needs than the policy on the rest of the methods which actually should push to as less as possible parameters from the code quality point of view.

**Comment by romani** [comment]
http://checkstyle.sourceforge.net/config_sizes.html#ParameterNumber

@ckorakidis, you can remove  from Tokens "CTOR_DEF" in configuration, but that will skipp all construtors in all classes, is it what you expect ? or you need to skip validation only for c-tors that are belong to immutable class(all fileds are "final") ?

**Comment by ckorakidis** [comment]
@romani that is be less flexible than configuring like done now but separately from other methods' params.
Due to the nature of the constructors I'd say that the flag CTOR_DEF in most of the cases covers my needs, so I'd consider the separate configuration for the number of parameters of constructors as a minor improvement.

Thanks.

**Comment by romani** [comment]
I think it is better for now to not extend a Check with new options and use Suppressions(http://checkstyle.sourceforge.net/config.html, the most elegant way to do that "@SuppressWarnings({"parameternumber"}") on that cases of Immutable classes (I presume you do not have a lot of them in your code). 

If I notice more requests for that feature from users we will do an option.
