### ISSUE TITLE
Require @Override annotation for every overridden method

### ISSUE THREAD

**Issue by electrum** [checkstyle/checkstyle#6834]
New checker feature request:

Verify that the `@Override` annotation is present on any overridden method or implemented interface method. Both of these examples will fail:

```java
class Foo implements Runnable {
    public void run() {}
}
```

```java
class MyMap extends LinkedHashMap {
    protected boolean removeEldestEntry(Map.Entry<K,V> eldest) {
        return size() > 10;
    }
}
```

This check is similar to `MissingOverride`, but different enough that it seems to warrant a new check with a new name. Thoughts on what to call it?

**Comment by romani** [comment]
checkstyle can not do this, it is limitation of design - https://checkstyle.org/writingchecks.html#Limitations
you need to use tools that use bytecode analysis, javac will do this for you, it can do this.

**Comment by electrum** [comment]
@romani Thanks for the detailed explanation and link. Apologies for the bogus request.

**Comment by electrum** [comment]
For anyone who finds this issue later, PMD has a [MissingOverride](https://pmd.github.io/pmd-6.15.0/pmd_rules_java_bestpractices.html#missingoverride) check which does exactly this.
