### ISSUE TITLE
SeparatorWrap defaults are wrong

### ISSUE THREAD

**Issue by ddidier** [checkstyle/checkstyle#684]
If I understood correctly the [Google Java style guide about line break](https://google-styleguide.googlecode.com/svn/trunk/javaguide.html#s4.5.1-line-wrapping-where-to-break), defaults are wrong. Indeed any break should be before the dot `.` and after the coma `,` but both are currently after (i.e. `eol`).

**Comment by romani** [comment]
I do not see that at our configuration.

from https://google-styleguide.googlecode.com/svn/trunk/javaguide.html#s4.5.1-line-wrapping-where-to-break

> When a line is broken at a non-assignment operator the break comes before the symbol. 
...
This also applies to the following "operator-like" symbols: the dot separator (.),

https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/google_checks.xml#L89

nl = NEW LINE
http://checkstyle.sourceforge.net/property_types.html#wrapOp

>  A comma (,) stays attached to the token that precedes it.

https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/google_checks.xml#L93

EOL = END OF LINE
http://checkstyle.sourceforge.net/property_types.html#wrapOp
