### ISSUE TITLE
Caching file has entry for non-existent suppressions.xml

### ISSUE THREAD

**Issue by Fernal73** [checkstyle/checkstyle#6841]
```#Thu Jun 20 03:32:04 UTC 2019
module-resource*?\:file\:/data/data/com.termux/files/home/LearnJava/Networks/java_regexp.header=C3EDE72E0043C9DB230B7B7E05AD2D223D7369E1
module-resource*?\:suppressions-xpath.xml=43845B65C4CB195740C2EB0E1F364C896E983118
/data/data/com.termux/files/home/LearnJava/Networks/networking/EncoderTest.java=1561001507747
/data/data/com.termux/files/home/LearnJava/Networks/networking/SpamCheck.java=1561001507657
/data/data/com.termux/files/home/LearnJava/Networks/networking/ContentGetter.java=1561001507827
/data/data/com.termux/files/home/LearnJava/Networks/networking/EncodingException.java=1560904753236
/data/data/com.termux/files/home/LearnJava/Networks/com/javacodegeeks/snippets/core/package-info.java=1560660129887
/data/data/com.termux/files/home/LearnJava/Networks/networking/IBiblioAliases.java=1561001507677
/data/data/com.termux/files/home/LearnJava/Networks/networking/EncodingAwareSourceViewer.java=1561001507997
/data/data/com.termux/files/home/LearnJava/Networks/networking/ReverseTest.java=1561001507547
/data/data/com.termux/files/home/LearnJava/Networks/networking/InterfaceLister.java=1561001507717
/data/data/com.termux/files/home/LearnJava/Networks/networking/QueryString.java=1561001507947
/data/data/com.termux/files/home/LearnJava/Networks/networking/package-info.java=1560421179634
/data/data/com.termux/files/home/LearnJava/Networks/networking/SourceViewer2.java=1561001507977
/data/data/com.termux/files/home/LearnJava/Networks/networking/LocalProxySelector.java=1561001507787
/data/data/com.termux/files/home/LearnJava/Networks/networking/OReillyByName.java=1561001507527
configuration*?=49F00D2B45BB8426140F5D0492D440689D779C3
/data/data/com.termux/files/home/LearnJava/Networks/networking/URLEquality.java=1561001507927
/data/data/com.termux/files/home/LearnJava/Networks/networking/AddressTests.java=1561001507567
/data/data/com.termux/files/home/LearnJava/Networks/networking/GoogleSearch.java=1561001507847
module-resource*?\:suppressions.xml=207DD88262E4D77234449B0BC16D6B90BD0AA7B7
/data/data/com.termux/files/home/LearnJava/Networks/networking/SourceViewer.java=1561001507697
/data/data/com.termux/files/home/LearnJava/Networks/networking/URLSplitter.java=1561001507907
/data/data/com.termux/files/home/LearnJava/Networks/networking/LookupTask.java=1561001507637
/data/data/com.termux/files/home/LearnJava/Networks/networking/NoGovernmentCookies.java=1561001507807
/data/data/com.termux/files/home/LearnJava/Networks/networking/ProtocolTester.java=1561001507887
/data/data/com.termux/files/home/LearnJava/Networks/networking/MyAddress.java=1561001507497
/data/data/com.termux/files/home/LearnJava/Networks/networking/PooledWebLog.java=1561001507867
/data/data/com.termux/files/home/LearnJava/Networks/networking/WebLog.java=1561001507617
/data/data/com.termux/files/home/LearnJava/Networks/networking/IPCharacteristics.java=1561001507767
/data/data/com.termux/files/home/LearnJava/Networks/com/javacodegeeks/snippets/core/ProtectedUrlAccess.java=1561001508037
```

---------------

The above is the cache file generated 
 for my project Networks on my Github repository: 
https://github.com/Fernal73/LearnJava. 

Configuration: https://github.com/Fernal73/LearnJava/blob/master/csrules.xml

The cache file contains an entry for suppressions.xml but I have never created such a file for this project. 

Is this entry deliberate?

There is no entry created for file java.header. The file is empty.

Caching works as expected. This is an efficient bug. 

If you intend to clone my repository, you will need Ivy besides Ant installed on your machine. First run the build.xml in the root directory to generate the classpath files and then you can run any individual project's build.xml.
-------------

**Comment by rnveach** [comment]
@Fernal73 You do have suppression file in config and repo. I don't understand why you say you didn't create it.

Config: https://github.com/Fernal73/LearnJava/blob/master/csrules.xml#L30
Properties: https://github.com/Fernal73/LearnJava/blob/master/checkstyle.properties#L11
Suppression file: https://github.com/Fernal73/LearnJava/blob/master/suppressions.xml

I see the same things for xpath suppressions.

**Comment by Fernal73** [comment]
That's not the suppression file referenced while running checkstyle on each
project. The ones you're referring to are in the root directory. Those
should and must not be used by any project in the repo. They're there only
for reference.

**Comment by Fernal73** [comment]
The checkstyle properties references suppressions.xml and
suppressions-xpath.xml but the rule specifies them as non-mandatory.

**Comment by Fernal73** [comment]
Running the checkstyle task after renaming the aforesaid files in the root
directory produces the same output even after deleting the existing cache
file.

Regards,
Linus.


On 21 Jun 2019 at 11:25 am, <LINUS FERNANDES <linus.fernandes@gmail.com>>
wrote:

The checkstyle properties references suppressions.xml and
suppressions-xpath.xml but the rule specifies them as non-mandatory.

**Comment by Fernal73** [comment]
You may not think this bug worth your while. But surprisingly, the cache
excludes an empty file while retaining a non-existent one!

**Comment by rnveach** [comment]
@Fernal73 You aren't giving us enough information them. Please read over https://checkstyle.sourceforge.io/report_issue.html#How_to_report_a_bug.3F . We need to know the configuration being used, anything the configuration uses like the properties or suppression file, how your invoking checkstyle, etc..

> while retaining a non-existent one!

It has to exist as it is given a hash.

> You may not think this bug worth your while.

I am trying to help, right?

**Comment by Fernal73** [comment]
You can run checkstyle either by invoking the script checkstyle with
parameter Project Directory from root directory.

. /checkstyle Networks (for example)

Or change to directory Networks and run ant checkstyle
cd Networks & & ant checkstyle.

As said earlier, the prerequisite would be to run
ant in the root directory and have ivy installed on your machine. THIS IS
REQUIRED TO GENERATE THE CLASSPATH FILES USED BY THE ANT TASK AND SCRIPTS.
Alternately, you can modify the cs.cp file in the root directory to list
the necessary jars present on your machine. It's currently generated as per
my local machine configuration I.e, my phone.

The ant build for every project is set up to access properties from the
root checkstyle.properties for every project. Each project starts with a
capital letter.

**Comment by Fernal73** [comment]
From where are you referencing the suppressions.xml? From the configuration
+ properties or from the directory? The project does not have a
suppressions.xml file as mentioned earlier. You are definitely not looking
at the parent directory since I renamed the said file and it still created
the entry.

I would have looked at the source code for Checkstyle but it's difficult to
read it from my phone.

Maybe you can email me the relevant source files and I can verify what you
are doing.

**Comment by Fernal73** [comment]
The relevant config file is csrules.xml in the root directory.

**Comment by Fernal73** [comment]
I don't think this bug quite fits into the template you listed for submitting bug reports. That is quite specific to rules not working as expected.

**Comment by Fernal73** [comment]
This much information is more than sufficient. If you wish, you can try it
on a similar directory structure and configuration. The java source files
are irrelevant for this purpose.

**Comment by rnveach** [comment]
> I don't think this bug quite fits into the template you listed for submitting bug reports.

We still need all the relevant information, even if you just point to the files in your repo using links.

> The relevant config file is csrules.xml in the root directory.
> every project is set up to access properties from the root checkstyle.properties for every project

Then this just proves my point that there is a suppression file and that is why your cache has one listed.
If it is listed in the config, it will be supplied to the cache file.

> Running the checkstyle task after renaming the aforesaid files in the root directory produces the same output even after deleting the existing cache file.

It doesn't matter if the physical file was renamed. If your config and properties remained the same it would still add the file to the cache.
Turning on `optional` just means that module won't throw an error when it can't load the file. The location of the file is still sent to the cache regardless, even if it doesn't exist. If the file doesn't exist, [it would still add it to the cache using the exception stack trace that was produced when trying to load it](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/PropertyCacheFile.java#L275-L294). When the file is brought back, the hash would change and force the entire cache to be reset.

> There is no entry created for file java.header. 

[`cs.header.file` from your properties is not used anywhere in your config](https://github.com/Fernal73/LearnJava/blob/master/checkstyle.properties#L12). This is why it isn't listed in your cache. For it to be in the cache, it must be in the configuration file. If you are not using it in your config, you could remove it from your properties file and remove the physical file.
[`cs.regexp.header.file` is in your configuration file](https://github.com/Fernal73/LearnJava/blob/master/csrules.xml#L39) and that is why it appears in your cache.


I am not seeing any bug or issue here.

**Comment by Fernal73** [comment]
Thanks for the update.

The csrules.xml and checkstyle.properties are common to all projects to
enforce a global standard.

Exceptions are handled via the suppressions.xml and suppressions-xpath.xml
files.

What's the purpose of optional if it's ignored by cache when it's
non-existent? Shouldn't the value associated with the suppressions file be
0 instead?

Yes, I recall now that the java.header file is not used. The header module
was not required. My bad.

Regards,
Linus.

**Comment by rnveach** [comment]
> What's the purpose of optional if it's ignored by cache when it's non-existent?

Cache and module are completely separate. Cache doesn't know module has some `optional` property or what it does. The only thing cache collects from modules is their external files.

> Shouldn't the value associated with the suppressions file be 0 instead?

Failure could be something else besides a non-existent file. Like it could be a `http` and maybe the server is down or something. This is why we take the exception and produce the hash of that. If exception goes away or exception changes, hash will change and cause the cache to be reset.

**Comment by Fernal73** [comment]
>>>>>>>Failure could be something else besides a non-existent file. Like it
could be a http and maybe the server is down or something. This is why we
take the exception and produce the hash of that. If exception goes away or
exception changes, hash will change and cause the cache to be reset.

I'd imagine you'd verify that the file exists. If it doesn't, you'd like -
1 or something of the sort. A hash value is misleading. Of course, you
probably don't expect users to be viewing your cache file as long as
caching works as expected. Changing the value stored to a negative value
won't affect the functioning of the work flow. If the file now exists, it
will have a positive Big Integer hashcode.

**Comment by Fernal73** [comment]
An entry plus a +ve large number is misleading.

**Comment by rnveach** [comment]
We need something more than -1 as the exception can change, from website is down to 404 or some such. We need a hash for a unique value. Even if we take the same number and just put a `-` in front of it won't change much of anything so I don't really see the point in adding it. The cache isn't really meant to be read by a human, especially the hashcodes. It's just a big number because its a hash to try and be as unique as possible.

Since I don't see an issue here, I am closing this issue but you can continue to ask questions.
The file doesn't exist but it is in the configuration and that is why it is added to the cache. No problem is being reported from it being in the cache, even if it shouldn't be there, like the cache is hiding violations or some other bug.

**Comment by Fernal73** [comment]
That may be so but I feel that the integrity of the solution is compromised. There is no marker that states that the file is missing or not where it's expected to be.

**Comment by rnveach** [comment]
The marker is in the checksum generated. Since the process to generate the checksum is hidden, there is no way to know that by looking at it.

Why do you feel you need to be able to see this marker for something that isn't suppose to be read by a human?

**Comment by Fernal73** [comment]
It's an output. I agree that it wouldn't ordinarily be read by a human
except to trace or debug the process or to check that things work as
expected. That's exactly why there's no way of knowing that the file
doesn't exist by looking at the entry. Am I right in assuming that the
hashcode generated is not the same for different projects if the file
doesn't exist in both cases? I'm unaware what the input string to the
hashing function is? It's certainly not just the short file name.

**Comment by Fernal73** [comment]
In fact, it isn't.

On 23 Jun 2019 at 1:54 am, <LINUS FERNANDES <linus.fernandes@gmail.com>>
wrote:

It's an output. I agree that it wouldn't ordinarily be read by a human
except to trace or debug the process or to check that things work as
expected. That's exactly why there's no way of knowing that the file
doesn't exist by looking at the entry. Am I right in assuming that the
hashcode generated is not the same for different projects if the file
doesn't exist in both cases? I'm unaware what the input string to the
hashing function is? It's certainly not just the short file name.

**Comment by Fernal73** [comment]
You have closed this issue anyway. I don't see any value in discussing it
further.

**Comment by Fernal73** [comment]
Frankly, if the file doesn't exist on the file system, there simply
shouldn't be an entry posted irrespective if the config file references
it or not. That's a simple check to add. You don't even have to look at the
attributes of the modules referencing the file entries.

**Comment by rnveach** [comment]
> Am I right in assuming that the hashcode generated is not the same for different projects if the file doesn't exist in both cases?

For any file that causes an error while reading it, we hash the exception. If the same exception is generated then it should produce the same hash.
For any non-exceptions, the hash is produced from the contents.
Both use SHA1.

> Frankly, if the file doesn't exist on the file system, there simply shouldn't be an entry posted irrespective if the config file references it or not. 

There has to be some kind of entry. All required files must be referenced in the cache otherwise it will cause the cache to be reset and the required files added to the cache. Required files include the config and any external files the config reference, like the suppression and import control files. If the required files are never added, then the cache would never work as it would always reset itself.
We have to do this to know what state these files are in and if they change to reset the cache as they could cause differences in violations. If a suppression is removed changing that file, it could cause new violations to show from a run. If the suppression file can't be accessed, all suppressions are basically removed causing all violations hidden to come up.

**Comment by Fernal73** [comment]
>>>>>There has to be some kind of entry. All required files must be
referenced in the cache otherwise it will cause the cache to be reset and
the required files added to the cache. Required files include the config
and any external files the config reference, like the suppression and
import control files. If the required files are never added, then the cache
would never work as it would always reset itself.
We have to do this to know what state these files are in and if they change
to reset the cache as they could cause differences in violations. If a
suppression is removed changing that file, it could cause new violations to
show from a run. If the suppression file can't be accessed, all
suppressions are basically removed causing all violations hidden to come up.

Am I misunderstanding the use of the cache or missing something obvious or
evident? If a file is never present on the file system, how can the cache
be invalidated? It will constantly not be present.

If it's subsequently added, the hash code will not be the same as no entry
present in the file earlier. Similarly, if it's removed, the entry will be
deleted thus invalidating the previous hash code entry.

The comparison, obviously, won't be hash to hash, though. That's why I
suggested a -1 or 0.

That makes it evident to the user. You might also wish to log a message
saying that the suppressions file is missing and thus ignored. But that
might irritate a user who wishes that entry to be ignored, in the first
place.










—
