### ISSUE TITLE
Make inner class SuppressionCommentFilter.Tag private

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#6844]
From https://github.com/checkstyle/checkstyle/pull/6839#issuecomment-504560192

Some internal implementation details of the class `SuppressionCommentFilter` are exposed to public. That's not necessary. Moreover, this may cause compatibility issues in the future.
This class should be private. This is a minor change, but may require some changes to the tests.

**Comment by rnveach** [comment]
> may require some changes to the tests

I think this may be why the class was public, but not sure if I am remembering this class or another from a previous PR.

**Comment by romani** [comment]
we usually forced code to be private and use Inputs as much as  possible, but we might lose something during review. Class should be private.

**Comment by rnveach** [comment]
Fix was merged
