### ISSUE TITLE
Add xpath tests for new Checks of 8.22

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#6848]
In release https://checkstyle.org/releasenotes.html#Release_8.22
We added we Checks
UnnecessarySemicolonInTryWithResources
UnnecessarySemicolonInEnumeration

But we forgot to add xpath tests for them to https://github.com/checkstyle/checkstyle/tree/master/src/it/java/org/checkstyle/suppressionxpathfilter
 
We also need to add them to list of supported Checks at:
https://checkstyle.org/config_filters.html#SuppressionXpathFilter

**Comment by romani** [comment]
@strkkk , please help us fix this issue.

@pbludov and @rnveach, FYI, let's keep it mind when new Check is proposed in PR.

**Comment by strkkk** [comment]
> please help us fix this issue.

I will take a look.
But if it is necessary, why this is not checked in CI/UT?

**Comment by romani** [comment]
>But if it is necessary, why this is not checked in CI/UT?

Please contribute, not all is automated. There bunch of rooms to improve.

>What is the logic for adding checks to this regression xpath filter?

Should be all java Checks ( non javadoc). We come up with such requirement a bit late.

**Comment by romani** [comment]
fixes are merged.
@strkkk , thanks a lot !
