### ISSUE TITLE
Remove TreeWalker#validateDefaultTokens

### ISSUE THREAD

**Issue by strkkk** [checkstyle/checkstyle#6858]
While checking source code, I found following method in TreeWalker class - 
https://github.com/checkstyle/checkstyle/blob/6bab0788365ba9afb713e14d9f6263f1f60b7aa2/src/main/java/com/puppycrawl/tools/checkstyle/TreeWalker.java#L277-L293

Looks like this was added as a part of #655

The thing is that this method validates that check's required tokens are subset of default tokens. But this validation is performed on startup of checkstyle and not related with user configuration, since both `getDefaultTokens` and `getRequiredTokens` are hardcoded in the check.

So, if some check, for some reason, violates this requirement, there is no way to launch this check because checkstyle will always fail on startup. Moreover, user can do nothing about it (except removing this check from their config) and this check is useless.

I don't see a reason for such validation on startup, this can be performed by unit tests to forbid such check.
As a nice bonus, startup will be a bit faster.

**Comment by rnveach** [comment]
I personally don't see an issue with the check. If the validation doesn't pass this then there is no guarantee the check will work correctly. Bypassing this validation will give the users a false sense there check is working correctly when it probably won't. We cannot guarantee users will run their own UTs. I can tell you right now I have made many custom checks for my own project and don't build a UT for them at all. We should run extra validation where necessary for anything users can add their own custom code to.

**Comment by romani** [comment]
@rnveach ,

> Bypassing this validation will give the users a false sense there check is working correctly when it probably won't.

you probably mean validation of user defined tokens vs required. Looks like this is not a point of concert in this issue. Please review issue one more time and my reply and confirm your concern one more time.
If user did mistake in default vs required it is minor problem in comparison to what else he can do wrong in his implementation.

@strkkk ,

Moving of such validation from runtime look reasonable on first sight. But there are nuances.

1) if we remove such validation at that place, we should enforce it at come UT/IT level for our Checks. We need to write one more UT that will guarantee that non of Check is missed (reminder about xpath suppress UT presence for each Check). So it is all doable but somebody need to make such UTs first.

2) on the moment of enforcing of tokens, there was a problem that configurations of whole world were probably damaged by misuse of tokens. That result in weird issue reports and ... . Probably from 6.10 release time , most users already fixed their configurations for standard (delivered by checkstyle project, not a thirdpartly, custom, ....) Checks.

3) third party, custom Checks .... we do not control them, we even not sure they follow rules of how to define Tokens in such tree methods. Proper definition of them https://checkstyle.org/writingchecks.html#Understanding_token_sets were problems even for engineers who spent some time in project and did few custom Checks. But we are not responsible for thirparty Checks, so user/author can damage them is many ways, we do not consider to validate their implementation and configuration.

Presence of such validation is not for thirdparty Checks, but we think it is WAS useful for us on moment of implementation and it is not that expensive in runtime.

I am ok to move validation `getDefaultTokens vs getRequiredTokens` to UTs, but there should be reliable UT to automatically get all Checks we have in codebase and validate them.

**Comment by strkkk** [comment]
> but there should be reliable UT to automatically get all Checks we have in codebase and validate them

It looks like UT for it is already exists in codebase and does exactly the same thing as code in startup validation.
https://github.com/checkstyle/checkstyle/blob/0bdbf15f0b64bc636d4b72c44152547039d34f65/src/test/java/com/puppycrawl/tools/checkstyle/internal/AllChecksTest.java#L307-L323

So startup check is just duplication and can be removed.

**Comment by rnveach** [comment]
> you probably mean validation of user defined tokens vs required
> Looks like this is not a point of concert in this issue. 

Yes in their own custom checks. And that is what the validation is, so it is connected to this issue.

> If user did mistake in default vs required it is minor problem in comparison to what else he can do wrong in his implementation.

Yes, but if checkstyle doesn't print this error and do the validation for 3rd party checks they will come to us and say "what is wrong with my code". I think this validation helps cuts down on those possible issues.

**Comment by romani** [comment]
>what is wrong with my code

My answer will be always " just debug your code and our code". They could misuse our API even worse, and we do not care. They have everything to figure out problem.
We are ok to remove now this validation.

Please confirm that you are ok.

**Comment by strkkk** [comment]
If some support for 3rd-party checks is required, it is a completely different task/module/tool, and there should be more tests for validation.

Just for example, there is a similar requirement that `defaultTokens` should be subset of `asseptableTokens`, but there is no validation for such case

**Comment by rnveach** [comment]
I am ok but I still disagree.

**Comment by romani** [comment]
Hmm, we need to come to agreement.
What options we have to let you be comfortable with removal of such validation ?

What if we make such validation easy to use by third party Check in its it ? If author do not care about it ... We should not help him more.

**Comment by rnveach** [comment]
I am ok with the removal. I still think it can't hurt to do some validation for 3rd party checks to prevent them from having a negative experience.

**Comment by romani** [comment]
Please put approval label on issue

**Comment by romani** [comment]
fix is merged
