### ISSUE TITLE
Add ID format property to SuppressionCommentFilter

### ISSUE THREAD

**Issue by esilkensen** [checkstyle/checkstyle#6883]
From https://github.com/checkstyle/checkstyle/pull/6876#discussion_r300832892:

[SuppressionCommentFilter](https://checkstyle.sourceforge.io/config_filters.html#SuppressionCommentFilter) currently has `checkFormat` and `messageFormat` properties. When deciding if an audit event should be suppressed, it first matches the event source against the `checkFormat`. If that fails, it matches the event module ID against the `checkFormat`.

For an event to be suppressed, one of those matches has to succeed, and the event message must also be matched against the `messageFormat`.

This issue is a proposal to define a new property, possibly named `idFormat`, as either a plain string or regular expression, and use it to match the event module ID rather than reusing the `checkFormat`. Then an audit event could be suppressed if all three matches succeed.

This new property could be consistent with [SuppressionFilter](https://checkstyle.sourceforge.io/config_filters.html#SuppressionFilter) where `suppression` XML elements can have attributes including:
>* `checks` - a Regular Expression matched against the name of the check associated with an audit event. Optional as long as id or message is specified.
>* `message` - a Regular Expression matched against the message of the check associated with an audit event. Optional as long as checks or id is specified.
>* `id` - a string matched against the check id associated with an audit event. Optional as long as checks or message is specified.

Related issue to for SuppressWithNearbyCommentFilter: #6884

----

Migration note:
Recommended migration for users is to rename any `checkFormat` property that matches check ID's to instead be named `idFormat`
OR
Make a copy of SuppressionCommentFilter config and use `idFormat`.

**Comment by romani** [comment]
I am ok with such update, but it will breaking compatibility, as after update some suppressions stop working.

@rnveach , please review and put approval label if you are ok with such update.

**Comment by rnveach** [comment]
I am ok.

**Comment by romani** [comment]
Fix is merged
