### ISSUE TITLE
Ignore rules for hashCode() and equals() methods

### ISSUE THREAD

**Issue by Danon** [checkstyle/checkstyle#6892]
Describe what you expect in detail.

CheckStyle keeps noticing `31` as magic number in automatically generated `hashCode()` and keeps marking `if` without brackets in `equals()`.

Is there a way to halt those rules for these special methods?

**Comment by rnveach** [comment]
@Danon For `hashCode` methods, see https://checkstyle.sourceforge.io/config_coding.html#MagicNumber_Properties .

There is no support for equals unless you use some type of suppression, like xpath.
If you want any other type of support, please see https://checkstyle.sourceforge.io/report_issue.html#How_to_report_a_bug.3F .
