### ISSUE TITLE
Ignore Junit5 @TempDir in VisibilityModifier check

### ISSUE THREAD

**Issue by Bananeweizen** [checkstyle/checkstyle#6903]
The VisibilityModifier check has a parameter to ignore variable names if they have certain annotations. It already contains JUnit @Rule and @ClassRule in its default value for that parameter, because those are injected by the JUnit framework. See https://checkstyle.sourceforge.io/config_design.html#VisibilityModifier for the documentation of that parameter.

For the same reason the new JUnit 5 @TempDir extension annotation should be added to the default: https://junit.org/junit5/docs/current/user-guide/#writing-tests-built-in-extensions-TempDirectory.

Otherwise developers get a checkstyle violation that the @TempDir field needs to be private. Of course that is not possible for fields which are injected.

**Comment by romani** [comment]
From your link 

> TempDir is an experimental feature

Do we really need to be on bleeding edge ?
You can update Check property to have it

**Comment by strkkk** [comment]
@romani May be just ignore all JUnit annotations?

**Comment by romani** [comment]
We will never catch up with all annotations, user should update his config. There are bunch of other annotations from other frameworks.
Exact names (not regexp) are used to distinguish types with similar names.

Default is some well used scenario. But it might not work for user custom demand. User have to adjust config ... even to his version of junit.

**Comment by romani** [comment]
@Bananeweizen, please provide some support for your idea. For now I do not think it is good idea. If experimental class change package or name in future for us it will be bracking compatibility, as it is change in default.

If no reply till end of July , I will close issue and PR.
