### ISSUE TITLE
web site: combine standard checks and available check pages

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#691]
Move all content of https://github.com/checkstyle/checkstyle/blob/master/src/xdocs/availablechecks.xml  to https://github.com/checkstyle/checkstyle/blob/master/src/xdocs/checks.xml 

update verify stage of maven build to ensure all Check are referenced at that page

**Comment by alexkravin** [comment]
@romani,

What did you mean in:
```
update verify stage of maven build to ensure all Check are referenced at that page
```
?

I have rebuilt the project, verifying stage is ok and content is moved properly.

**Comment by romani** [comment]
moved to separate issue - https://github.com/checkstyle/checkstyle/issues/783

**Comment by romani** [comment]
will be in 6.5
