### ISSUE TITLE
New Check: Ordering of Methods in a Class (public -> protected -> private)

### ISSUE THREAD

**Issue by speedbird123** [checkstyle/checkstyle#6913]
There are many ways of arranging methods in a class. One of the most popular is the following order: public, protected, private. This check would verify if a class violates this order.

Example:

```
//does not violate
public Class Demo {
    public void foo(){}
    private void foorbar(){}
}

//violates
public Class Demo {
    private void foorbar(){}
    public void foo(){}
}
```

I know this is not the code convention, going by this: 

https://www.oracle.com/technetwork/java/javase/documentation/codeconventions-141855.html#1852

It says:

"These methods should be grouped by functionality rather than by scope or accessibility. For example, a private class method can be in between two public instance methods. The goal is to make reading and understanding the code easier."

Despite of what the convention is, a check like this would be incredibly useful. Code formatters like the Google Java Formatter give the option to arrange methods by visibility as well.

**Comment by romani** [comment]
We have https://sevntu-checkstyle.github.io/sevntu.checkstyle/apidocs/com/github/sevntu/checkstyle/checks/coding/CustomDeclarationOrderCheck.html in our satellite project.

It should help you to enforce what you want. Please confirm

**Comment by romani** [comment]
no reply ... closing the issue
