### ISSUE TITLE
CI: hide maven download text to prevent log overflow

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#6919]
PR: https://github.com/checkstyle/checkstyle/pull/6918#issue-300598593
Example: https://travis-ci.org/checkstyle/checkstyle/jobs/562953991
> this The job exceeded the maximum log length, and has been terminated.

When the log overflows, it terminates the CI processing and marks as a red in github. We can't determine if it is a true failure or not because the downloads take so much log space that we don't know the results of the CI.

We should try to find a way to prevent this log overflow.

https://stackoverflow.com/questions/21638697/disable-maven-download-progress-indication
Some people are saying to use batch mode but its questionable how well it works.

**Comment by romani** [comment]
https://stackoverflow.com/questions/45817256/how-to-avoid-the-job-exceeded-the-maximum-time-limit-for-jobs-and-has-been-ter

**Comment by strkkk** [comment]
in same SO thread someone recommends to disable bad logger, looks like an option.
https://stackoverflow.com/a/35653426

**Comment by romani** [comment]
Even further in same link , https://stackoverflow.com/a/55781461

**Comment by rnveach** [comment]
> Even further in same link , https://stackoverflow.com/a/55781461

Please note:
> Starting with Maven 3.6.1

Taken from https://travis-ci.org/checkstyle/checkstyle/jobs/562953991#L129
> mvn version
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T18:41:47Z)

So `--no-transfer-progress` doesn't seem like an option yet, but it could be eventually.
There is always the option to manual install a new version. See https://github.com/travis-ci/enterprise-installation/issues/14#issuecomment-273746437 .

> batch mode 

This didn't work on my local (version 3.3.9) so I doubt it will work on travis.

> https://stackoverflow.com/a/35653426

might be the only other option.

**Comment by romani** [comment]
If we use https://github.com/travis-ci/enterprise-installation/issues/14#issuecomment-329983790 , it will be good.

**Comment by rnveach** [comment]
You are still ok with it @romani if it forces us to locally install the new maven too just to be able to run the scripts.

**Comment by romani** [comment]
it will not force us to upgrade, as we can continue to run "mvn verify" on our local. This update will affect only Travis script, so it will affect you only if run validation from travis commands. I presume such travis command is executed only by Travis and some new  contributors who see a failure in CI (in this case user do not care and ok with extra download).

**Comment by romani** [comment]
in travis log file - https://api.travis-ci.org/v3/job/565950801/log.txt
```
Downloading from google-maven-central: https://maven-central.storage-download.googleapis.com/repos/central/data/com/fasterxml/oss-parent/11/oss-parent-11.pom
Progress (1): 0.6/23 kB
Progress (1): 2.0/23 kB
Progress (1): 3.4/23 kB
Progress (1): 4.8/23 kB
Progress (1): 6.1/23 kB
Progress (1): 7.5/23 kB
Progress (1): 8.2/23 kB
Progress (1): 9.6/23 kB
Progress (1): 11/23 kB 
Progress (1): 12/23 kB
Progress (1): 14/23 kB
Progress (1): 15/23 kB
Progress (1): 16/23 kB
Progress (1): 18/23 kB
Progress (1): 19/23 kB
Progress (1): 21/23 kB
Progress (1): 22/23 kB
Progress (1): 23 kB   
```

I tried batch mode to see if it will suppress `Progress ....`

**Comment by romani** [comment]
fix is merged.
