### ISSUE TITLE
change block indent 2 to 4 spaces

### ISSUE THREAD

**Issue by leo1515416043** [checkstyle/checkstyle#6920]
![image](https://user-images.githubusercontent.com/48787027/61841185-7919c380-aec6-11e9-9db7-deab823c33ab.png)

![image](https://user-images.githubusercontent.com/48787027/61841209-86cf4900-aec6-11e9-8d19-57261605b3fa.png)

---------------
Describe what you expect in detail.

I want to block indent is 4 spaces
--------------

**Comment by rnveach** [comment]
@leo1515416043 Please see https://checkstyle.org/report_issue.html#How_to_report_a_bug.3F .
Users can configure the configuration however they see fit. Why don't you change your configuration with the requested block indent?

**Comment by leo1515416043** [comment]
There is no property named "blockIndent"

**Comment by rnveach** [comment]
Then please submit issue as asked for in https://checkstyle.org/report_issue.html#How_to_report_a_bug.3F so I can understand your issue and try to help.
