### ISSUE TITLE
CLI: Add short versions for 'executeIgnoredModules' and 'tabWidth'

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#6936]
Because of picocli update at https://github.com/checkstyle/checkstyle/pull/6924 ,

we don't like the new ordering of options being displayed for the CLI, so we have decided to have short names for these options.

`executeIgnoredModules` will have the short name `-E`
`tabWidth` will have the short name `-w`

**Comment by romani** [comment]
Fix is merged
