### ISSUE TITLE
Xdocs: sort values for String Set properties

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#6938]
From https://github.com/checkstyle/checkstyle/pull/6931#discussion_r309848231

Some checks have properties of type `String Set`, [for example](https://checkstyle.org/config_design.html#DesignForExtension_Properties):
![image](https://user-images.githubusercontent.com/900805/62347776-7e4cc300-b503-11e9-9b6e-c57e251f3e7b.png)

For better readability, all of them should have default values sorted alphabetically to make it easier to find any value within the set.

`XdocsPagesTest.validatePropertySectionPropertyEx` should validate this.

**Comment by rnveach** [comment]
Fix was merged
