### ISSUE TITLE
New Check PreferExpressionLambda

### ISSUE THREAD

**Issue by Vampire** [checkstyle/checkstyle#6961]
Extracted from comment in #120, a new check would be nice that advices to use expression lambdas if a full-fledged lambda contains only one expression the result of which is returned.

For example
`Stream.of("1", "2", "3").map(string -> { return Integer.valueOf(string, 10); });`
should be advised to
`Stream.of("1", "2", "3").map(string -> Integer.valueOf(string, 10));`
or
`Stream.of("1", "2", "3").map(string -> { return string.indexOf('a'); });`
to
`Stream.of("1", "2", "3").map(string -> string.indexOf('a'));`

Why I thought it might make sense to have this combined with the PreferMethodReferenceCheck is, because if this is a separate check it will either partly report the same lambdas as PreferMethodReferenceCheck.
An option would be to optionally also check whether it could even be a method reference and do not report a violation in that case.
This would make the check more complex than necessary though, as without the check should be pretty straight-forward.
And even if this check is done, it should be controllable by a property, as one might dislike method references but still want to have expression lambdas suggested.

For example
`Stream.of(1, 2, 3).map(integer -> { return integer.doubleValue(); });`
will be reported (I hope) by PreferMethodReferenceCheck to be changed to
`Stream.of(1, 2, 3).map(Integer::doubleValue);`
while it will also be reported by this check to be changed to
`Stream.of(1, 2, 3).map(integer -> integer.doubleValue());`

**Comment by strkkk** [comment]
@Vampire it looks similar to #6850 
Are there some differences?

**Comment by Vampire** [comment]
I don't think so, thx
