### ISSUE TITLE
Add label "has PR" to issue when PR is submitted

### ISSUE THREAD

**Issue by strkkk** [checkstyle/checkstyle#6964]
Problem: Now it is not clear what issue is available for grabs without clicking on it and checking its history, it can already have a PR.

 Proposed feature: add hook to repository on PR create action to add label for issue.

Other projects have similar thing, e.g. [pmd](https://github.com/pmd/pmd/issues?q=is%3Aissue+is%3Aopen+label%3Ahas%3Apr)

**Comment by romani** [comment]
If this become completely automated, I am ok.
But we have 10 PRs vs 500 issues, chance to open issue with PR is low. It is always good idea to read whole issue before starting it.

**Comment by rnveach** [comment]
I would only agree to this if adding/removing labels was completely automated with no user interaction. Admins don't have the time to go through an error report every week to re-fix labels.

**Comment by strkkk** [comment]
Looks like github now shows linked PRs, so this is not needed anymore
![image](https://user-images.githubusercontent.com/8901354/75971891-79118580-5ee3-11ea-9103-44f3759ed8cc.png)

**Comment by romani** [comment]
I still have dream to look at actions to let us place label "awaiting changes/response" and remove it if author did some comment in PR.
