### ISSUE TITLE
New Check NoArrayTrailingComma

### ISSUE THREAD

**Issue by Vampire** [checkstyle/checkstyle#6971]
Followup 1 to #6469

Imho it looks strange to have a trailing comma, so I'd rather like to be able to check that no trailing comma is ever used. This will be directly competing with `ArrayTrailingComma`.

**_Examples:_**
```java
String[] foo1 = {
  "FOO", // OK
  "BAR", // violation
};
String[] foo2 = { "FOO", "BAR", }; // violation
String[] foo3 = {
  "FOO", // OK
  "BAR" // OK
};
String[] foo4 = { "FOO", "BAR" }; // OK
```

**_Current Work-Around only for arrays:_**
```xml
<module name="IllegalToken">
    <property name="id" value="trailingArrayComma"/>
    <property name="tokens" value="COMMA"/>
    <message key="illegal.token" value="Do not use trailing array comma."/>
</module>
<module name="SuppressionXpathSingleFilter">
    <property name="id" value="trailingArrayComma"/>
    <property name="query" value="(
                                      //ARRAY_INIT/*[self::COMMA and not(position() = (last() - 1))],
                                      //COMMA[not(parent::ARRAY_INIT)]
                                  )"/>
</module>
```

**_Current Work-Around for arrays and enums:_**
```xml
<module name="IllegalToken">
    <property name="id" value="trailingComma"/>
    <property name="tokens" value="COMMA"/>
    <message key="illegal.token" value="Do not use trailing comma."/>
</module>
<module name="SuppressionXpathSingleFilter">
    <property name="id" value="trailingComma"/>
    <property name="query" value="(
                                      //ARRAY_INIT/*[self::COMMA and not(position() = (last() - 1))],
                                      //ENUM_DEF/OBJBLOCK/*[self::COMMA and not(position() = (last() - 1))],
                                      //COMMA[not(parent::ARRAY_INIT or parent::OBJBLOCK/parent::ENUM_DEF)]
                                  )"/>
</module>
```

**Comment by romani** [comment]
I am ok with new Check.

@rnveach , please review and place approve label if see no problems.

**Comment by rnveach** [comment]
@romani I am fine with the check. I just had 1 thing to point out for our own purposes.

>   "BAR", // violation
> String[] foo2 = { "FOO", "BAR", }; // violation

For our own repo, I could see us wanting a violation on the 2nd example but not the first.
What do you think of adding an option for this?

**Comment by romani** [comment]
I am ok to have option for this, but we can add option later as interest to Check appear.
If @Vampire can make it in first version, we will activate it on our code with ability to skip violations on non-single line enums.

**Comment by romani** [comment]
fix is merged
