### ISSUE TITLE
[Java] Checkstyle CLI while generating xpath suppressions provides extraneous stdout output. 

### ISSUE THREAD

**Issue by Fernal73** [checkstyle/checkstyle#6974]
https://checkstyle.org/cmdline.html#Command_line_usage

```bash
$ cat config.xml 
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
  "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
  "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
  <property name="haltOnException" value="false"/>
  <module name="TreeWalker">
    <module name="TypeName" />
  </module>
</module>

$ cat Test.java 
class T_est {}
rivanov@p5510:/var/tmp$ java -jar checkstyle-8.24-SNAPSHOT-all.jar -c config.xml Test.java 
Starting audit...
[ERROR] /var/tmp/Test.java:1:7: Name 'T_est' must match pattern '^[A-Z][a-zA-Z0-9]*$'. [TypeName]
Audit done.
Checkstyle ends with 1 errors.

$ java -jar checkstyle-8.24-SNAPSHOT-all.jar -g -c config.xml Test.java 
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suppressions PUBLIC
    "-//Checkstyle//DTD SuppressionXpathFilter Experimental Configuration 1.2//EN"
    "https://checkstyle.org/dtds/suppressions_1_2_xpath_experimental.dtd">
<suppressions>
<suppress-xpath
       files="Test.java"
       checks="TypeNameCheck"
       query="/CLASS_DEF/IDENT[@text='T_est']"/>
</suppressions>
Checkstyle ends with 1 errors.

$ java -jar checkstyle-8.24-SNAPSHOT-all.jar -g -o suppresion.xml -c config.xml Test.java 
Checkstyle ends with 1 errors.

$ cat suppresion.xml 
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suppressions PUBLIC
    "-//Checkstyle//DTD SuppressionXpathFilter Experimental Configuration 1.2//EN"
    "https://checkstyle.org/dtds/suppressions_1_2_xpath_experimental.dtd">
<suppressions>
<suppress-xpath
       files="Test.java"
       checks="TypeNameCheck"
       query="/CLASS_DEF/IDENT[@text='T_est']"/>
</suppressions>

$ java -jar checkstyle-8.24-SNAPSHOT-all.jar -o out.txt -c config.xml Test.java 
Checkstyle ends with 1 errors.

$ cat out.txt 
Starting audit...
[ERROR] /var/tmp/Test.java:1:7: Name 'T_est' must match pattern '^[A-Z][a-zA-Z0-9]*$'. [TypeName]
Audit done.

$ java -jar checkstyle-8.24-SNAPSHOT-all.jar -o out.xml -f xml -c config.xml Test.java 
Checkstyle ends with 1 errors.

$ cat out.xml 
<?xml version="1.0" encoding="UTF-8"?>
<checkstyle version="8.24-SNAPSHOT">
<file name="/var/tmp/Test.java">
<error line="1" column="7" severity="error" message="Name &apos;T_est&apos; must match pattern &apos;^[A-Z][a-zA-Z0-9]*$&apos;." source="com.puppycrawl.tools.checkstyle.checks.naming.TypeNameCheck"/>
</file>
</checkstyle>

$ cat Test.java 
class Test {}

$ java -jar checkstyle-8.24-SNAPSHOT-all.jar -c config.xml Test.java 
Starting audit...
Audit done.

```

OUTPUT

"Checkstyle ends with n errors" is displayed if violations exist. This is output to stdout instead of stderr, unlike the log messages.
This occurs whether the -o option is in use or not. No xml document is generated if violations under TreeWalker module are not detected. 

*******

Describe what you expect in detail.

The informative message should not be output as stdout message when the -g option is used. My understanding is that the -g option is used for generating the suppression document specifically. No other stdout output should be provided. Log and other messages must be stderr output. This way, the stdout xml document can be captured cleanly and saved in a file, if needed. 

-------------

Spun off from https://github.com/checkstyle/checkstyle/issues/6934

**Comment by Fernal73** [comment]
Is it possible to rename the above issue? If yes, can the [java] prefix be removed? Thanks

**Comment by romani** [comment]
@Fernal73 , please always report issues to us in CLI form with examples of behavior. Your issues are very hard to read, it take a while to get point. Please review how I updated issue, and please follow this approach.

**Comment by romani** [comment]
So ...
`Checkstyle ends with X errors.` is shown only when violation with ERROR severity is present (if severity is warning, no such violation). This sentence is not part of validation output of plain format and not a xml output (obvious).
We can print this sentence in stderr output only, looks like sterr  reasonable place for it.

@rnveach  and @pbludov , does it make sense to you ? approved ?

**Comment by romani** [comment]
@strkkk , please share your ideas too.

**Comment by strkkk** [comment]
In my opinion this line should not be in output for -g mode, because it says it generates a file, but in fact it does not.
 For example, this wont produce valid xml in 8.23
`java -jar checkstyle.jar -c conf -g > suppr.xml` because of this extra line, you need to grep output first or something.

**Comment by Fernal73** [comment]
---------
```xml
java -jar checkstyle-8.24-SNAPSHOT-all.jar -g -o suppresion.xml -c config.xml Test.java 
Checkstyle ends with 1 errors.

$ cat suppresion.xml 
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suppressions PUBLIC
    "-//Checkstyle//DTD SuppressionXpathFilter Experimental Configuration 1.2//EN"
    "https://checkstyle.org/dtds/suppressions_1_2_xpath_experimental.dtd">
<suppressions>
<suppress-xpath
       files="Test.java"
       checks="TypeNameCheck"
       query="/CLASS_DEF/IDENT[@text='T_est']"/>
</suppressions>
```
Is this the new behaviour? That wasn't happening earlier. Then the suppression file is as expected with no additional output invalidating the xml document. Grepping out the extra line is not a good idea. My ivy.xml is not set up to access the latest snapshot jar version. I wouldn't want to disturb my existing stable configuration.

**Comment by romani** [comment]
>For example, this wont produce valid xml in 8.23
java -jar checkstyle.jar -c conf -g suppr.xml because of this extra line, you need to grep output first or something.

The same is for when you define `-f xml`. To get good report user need to use `-o`.
I do not remember why I added this static line to the end. It might be reasonable to move it to plain report content and even to xml as attribute of top tag.
Let's wait for others response.

**Comment by rnveach** [comment]
I am fine with printing to stderr. As long as it is not in the output XML file, is fine with me.
If we want to add it to the XML as it's own tag, that is also fine.

**Comment by Fernal73** [comment]
If added to the suppressions xml, it must not be a mandatory element but an optional one since it adds nothing to the usage of the suppressions document.

My usecase involves generating an initial suppressions-xpath.xml via the above CLI. Then, additional suppressions are added via cut and paste as the code base grows with only 'unavoidable' violations suppressed. 'Unavoidable' is in quotes as the definition is subjective.

**Comment by strkkk** [comment]
> to xml as attribute of top tag

I really doubt someone would need it, it is only informational thing and it is equal to number of suppressions in generated file.

**Comment by Fernal73** [comment]
@strkkk Not always. Suppression xml lists only violations under TreeWalker module. However, that additional information is not needed in the suppressions document. With an error file now generated as well with the -o option, this becomes redundant as part of stdout. I'm fine with stderr. As long as it doesn't pollute the suppressions xml. Ideally, we ought to be sending the suppressions xml to a file as well.

**Comment by romani** [comment]
>If added to the suppressions xml

I didn't mean suppression xml. I meant violations xml report.

We just need to remove this static line from output.

**Comment by Fernal73** [comment]
@romani 
Of course, it is. How asinine of me!

**Comment by rnveach** [comment]
Fix was merged
