### ISSUE TITLE
Enforce input naming convention in IT

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#6981]
Discovered at https://github.com/checkstyle/checkstyle/issues/6207 ,

Our UTs should have been checking the input files naming pattern but it was brought to light they aren't being checked.
I looked at the IT folder some and we don't have good input file names or their folder names too. It would require renaming all our files and folders there.

I believe this was missed because of the google folders and we just skipped them. Though they should be named `Input` even in google, I am not sure we forced the folder to match the name of the test like we did in `test` folder.

Test should be fixed to validate the IT folder some. Our regression area in IT should be fixed to match our pattern in Test folder.
Google and Sun area should atleast start with Input, but their folder structure follows a different pattern.

We cannot review a 1k file change in any timely matter. we just need the test, suppression, and the 1 example in this PR (2 commits). I would think this would ultimately need to be split among 50 PRs (20 files each) at the minimum.

**Comment by sulkykookie** [comment]
So we need to rename files/folders and since we do that, we need to update class names in java files as well. Am I right?

**Comment by sulkykookie** [comment]
I'm on it.

**Comment by sulkykookie** [comment]
@rnveach 
Just to be on the same page. This issue revolves around the fact that the folders' names such as ```rule331nowildcard``` in https://github.com/checkstyle/checkstyle/tree/master/src/it/java/com/google/checkstyle/test/chapter3filestructure
should be improved, along with the file names inside of such folders, along with the improvements in ITs. Am I right?

**Comment by MANISH-K-07** [comment]
@rnveach 
the issue seems to be open for almost 4-5 years with no merges. Is this still valid ??

I could work on renaming all such files and folders. 
Please elaborate on how you expect the naming convention to be like, so I can get started !!

**Comment by MANISH-K-07** [comment]
@rnveach , @romani 

I was exploring the Issue page while this issue came into limelight....
the issue seems to be open for almost 4-5 years with no merges. Is this still valid ??

I could work on renaming all such files and folders, given my open issue #14436 
Please elaborate on how you expect the naming convention to be like, so I can get started 😃 !!

**Comment by romani** [comment]
still valid. We need to update all of them to start with "Input" for sure.
please read https://github.com/checkstyle/checkstyle/issues/6207#issuecomment-523013433

@rnveach , can you share details on folders name ?

**Comment by rnveach** [comment]
Where does the first post not share these details?

**Comment by MANISH-K-07** [comment]
> Where does the first post not share these details?

@rnveach ,
The description explains the requirements precisely. 
:)
I just wanted to know if there were any newer updates or ideas of such as the issue was created about 4-5 years back.

**Comment by rnveach** [comment]
I am not aware of any updates. The issue was specifically about same conventions in all areas.

**Comment by MANISH-K-07** [comment]
@rnveach , @romani 
I need clarification regarding discussions from https://github.com/checkstyle/checkstyle/issues/6207#issuecomment-523013433 and https://github.com/checkstyle/checkstyle/issues/6207#issuecomment-522679928

> What if we name it as InputXpathAbstractClassNameInner.java ? to put Xpath as distinguishing marker from inputs of UT or ITs, but in same time make it a bit short.

> If we are talking about in the IT tier, I ask that we use a different pattern then Test.
> Input{CheckName}Xxxx.java (no check) at the very least since that is the current IT pattern.

Would you like the naming to include a distinguishing element like "`Xpath`" between {Input} and {checkNameXXXX} ?

I have attached a PR #14595 , 
with the "Xpath" included. Please review if this is fine or if we omit it and stick to "Input{CheckName}Xxxx.java"

**Comment by MANISH-K-07** [comment]
Also, Once I am done with the naming convention , I will organize our It codebase folder-wise matching out test folders.

**Comment by MANISH-K-07** [comment]
> I have attached a PR #14595 , 

@rnveach , @romani 
In the PR, I have added another naming pattern for the test to validate.
So that both the old and new pattern can be allowed until final fix of this issue. Please review

**Comment by romani** [comment]
We need all sequence of PRs to close this issue. 
@MANISH-K-07 , please split your big PR in multiple and send them to us.
Single review only for such PRs will be enough

**Comment by rnveach** [comment]
@romani This issue is done. All remaining updates are moved to #14715.

**Comment by rnveach** [comment]
> be an open ongoing issue labelled easy/good xxx issue for new contributors

If you want to provide your fixes @MANISH-K-07 , no one is stopping you. While I don't want your work you already done go to waste, I can understand if you feel you have higher priority issues.

**Comment by MANISH-K-07** [comment]
>  I can understand if you feel you have higher priority issues.

Actually yes @rnveach , I'm working on an indentation issue and its taking up some time for investigation

I will send 2-3 single module PRs for this rename issue and they can act as examples of update for #14713 and it can be long ongoing if its okay with everyone
