### ISSUE TITLE
Japanese locale contains mistranslation

### ISSUE THREAD

**Issue by shirayuki** [checkstyle/checkstyle#7012]
The file
src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_ja.properties
contains a mistranslation.
"終了時" means "ending time".

Current translation:
```
summary.first.sentence=Javadocの最初の文には終了時がありません。
```
Expected:
```
summary.first.sentence=Javadocの最初の文に末尾のピリオドがありません。
```

**Comment by romani** [comment]
Please just send updates for all problems you see.

**Comment by rnveach** [comment]
Fix was merged
