### ISSUE TITLE
MainTest#testExistingTargetFileButWithoutReadAccess fails on Win10 machine

### ISSUE THREAD

**Issue by strkkk** [checkstyle/checkstyle#7032]
This test (I run it on latest master) fails on my machine (Win10) but passes CI (on appveyor and linux).

```
mvn --version
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T21:41:47+03:00)
Maven home: C:\Soft\maven_3_6_0
Java version: 1.8.0_144, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk1.8.0_144\jre
Default locale: en_US, platform encoding: Cp1251
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

![image](https://user-images.githubusercontent.com/8901354/64000790-1774f680-cb0f-11e9-81c4-58f5f825e5ce.png)

It looks like that the problem is in line 282
```
file.setReadable(false);
```
because in debug it shows that file is still readable regardless of invocation of this method.

I do not have a good idea how to resolve it, only some ugly stuff like skip test if file.setReadable returns false.

I briefly looked through appveyor script and job log and there is nothing about windows version. May be there is something in job setup?

**Comment by rnveach** [comment]
I have this same issue.

````
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T11:41:47-05:00)
Maven home: M:\checkstyleWorkspace\checkstyle\EMBEDDED
Java version: 1.8.0_171, vendor: Oracle Corporation
Java home: D:\Program Files\JDK8\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "x86", family: "dos"
````

**Comment by rnveach** [comment]
@strkkk Please update the first post with your information and confirm what file system you are using.

**Comment by strkkk** [comment]
@rnveach done

**Comment by romani** [comment]
We can quickly merge fix to skip this test on windows, and get time to investigate further on what to do

**Comment by rnveach** [comment]
Fix was merged
