### ISSUE TITLE
Dates of release if not properly rendering in Firefox

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#7036]
https://checkstyle.org/releasenotes.html

![image](https://user-images.githubusercontent.com/812984/64079177-24255600-cc99-11e9-8809-10788e174ee6.png)

the same in Chrome

It was good in previous version

**Comment by rnveach** [comment]
I can only assume it was the changes done to it to applease that xml check routine.
The style says position absolute at 0,0 which makes it think you want it at the top of the document.

If you remove `top: 0` from the style it will put it to the right under the release border.

**Comment by romani** [comment]
Mobile rendering is damaged too:
![Screenshot_20190903-224037](https://user-images.githubusercontent.com/812984/64228580-20adec80-ce9c-11e9-8a02-8797ea3c65cb.png)

**Comment by jo2** [comment]
This displaying error is due to every release date being displayed at `top:0; right: 0;`. There are multiple text at the same place which makes them unreadable. 

To display only the most recent date it would be a small fix in css, I can submit a PR for that.

**Comment by romani** [comment]
Example of how it was https://checkstyle.sourceforge.io/version/8.20/releasenotes.html

**Comment by jo2** [comment]
ok, thanks. will fix it.

**Comment by romani** [comment]
fix is merged
