### ISSUE TITLE
Use azure CI for some validation tasks

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#7045]
https://github.com/marketplace/azure-pipelines

Example: https://github.com/hcoles/pitest/blob/master/azure-pipelines.yml

Free style bash task https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/bash?view=azure-devops

Looks like in matrix variables are defined https://mattvsts.github.io/2020/01/07/create-a-build-matrix-with-azure-pipelines/

Bash is part of regular job https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml
it is a shortcut of https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/bash?view=azure-devops

https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops#maven

available images with list of installed applications - https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml

------

cron execution: 
https://docs.microsoft.com/en-us/azure/devops/pipelines/process/scheduled-triggers?view=azure-devops&tabs=yaml
example how to allow run by cron only (Reason: scheduled):
https://github.com/giotto-ai/giotto-tda/blob/master/azure-pipelines.yml
https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml

**Comment by romani** [comment]
first commit - https://github.com/checkstyle/checkstyle/commit/f73dac075f5d294bfe9f84f82ca077fa8f3db166

**Comment by romani** [comment]
https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops#maven

**Comment by Rahulkhinchi03** [comment]
@romani @nick-mancuso I have set up Azure DevOps on my local. I have also given access to you both.

**Comment by Rahulkhinchi03** [comment]
@romani @nick-mancuso I have set up Azure and I want to work on this issue. Please guide me on how can I get started and what things need to be done.

**Comment by romani** [comment]
Azure is already heavily in use
https://dev.azure.com/romanivanovjr/romanivanovjr/_build/results?buildId=9064&view=results
