### ISSUE TITLE
Migration Guide in Release Notes

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#705]
Anyone who would blindly update Checkstyle from 6.3 to 6.4 without adding [EmptyCatchBlock](http://checkstyle.sourceforge.net/config_blocks.html#EmptyCatchBlock) check, would loose validation for catch blocks entirely. I think we should introduce something like _Migration Guide_ to give people instructions how to safely update.

What do you think guys?

**Comment by romani** [comment]
Please describe your idea in more details ....., for now I doubt that it might be useful:

1) code standard should be strict document and not smth that is changing after Checkstyle update
2) checkstyle is usually located on-commit/push hook, so that will block user ability to push sources.
3) new Check does not meant that it stable to use
4) I specially introduced a manual paragraph "New" in release notes to stress that to smth who is interested.
5) Not all Checks are ok for all projects.
6) Safe upgrade will be always if in relese there is no "Compatibility backing" ( that we did for few recent releases)
7) only user know when is is best time to introduce a newe validation and fix violations from it (some Checks find huge design problems that is impossible to fix easily). We even do not know severity of issue, it could be INFO or ERROR - it is up to a user.

My best understanding is that the best thiing we could do is to provide short description of what is NEW in release and give links to documentation for more details (yes I lack link to HTML documentaion in release notes, that should be improved).

**Comment by mkordas** [comment]
@romani I agree with you. Let me elaborate more:
* First paragraph
 * all non-backward compatible changes - with brief reason why we are making them
 * things that in any way make the checks more strict or more loose
 * very brief migration guide about what changes are necessary in config (check was deleted - remove entry, defaults for check were changed - provide explicitly old values), so that user can update without breaking build
* Second paragraph
 * new stuff with links to: documentation, issue and pull request, so that users can easily decide if new things will be useful for them
* Notes
 * would be good to provide more links here as well - issues, pull requests, docs...

**Comment by romani** [comment]
Yes, I have to agree with you that current releases notes are not ideal.
The main reason of it - my lazyness to write wide description, I thought about automation of that, but can not find good solution, right now I do that by grep of git logs and then manual creation of release notes, but even that takes about 2 hours to describe a release. 
I give myself promise to do release each end of month, and finish complete automation of release to get rid of that chore, so release notes are lacking my attention/time for now. 

> all non-backward compatible changes - with brief reason why we are making them

I think we need to describe that in git issue, not a release notes. Too much text in release notes will not make any good , as users will skip reading it.

> things that in any way make the checks more strict or more loose

it is just a bug fixing, any fix do Check more/less strict . 

> very brief migration guide about what changes are necessary in config

I might be wrong but, users will run new version first and then by examining new violations fix code or review backward incompatible notes. After upgrade to new Checkstyle , build will most likely fail.
Even changes in message could cause build failure as it might be used in suppressions.

> new stuff with links to: documentation,

yes, I need to force myself to do that.

> Notes :     would be good to provide more links here as well - issues, pull requests, docs..

I do not not agree there, as this paragraph is only a gratitude for contributors (referencing their names) that improve Checkstyle from inside, user should not not be affected by that changes, user should not be interested in that changes. Usually opensource projects skip referencing names as it demand additional manual work. But I think that is very good to have names, but I will not describe in notes all minor changes user did.

**Comment by romani** [comment]
@mkordas , end of month is close, please think about how you would like to have Notes chapter to look like for 6.5 release. Amount of your changes to project is impressive that month, but most of them targeted to internal code quality that usually come to "Notes" chapter that I usually describe in brief.

**Comment by mkordas** [comment]
My proposal is to work together on release notes in pull request  - what I mean is just peer review to fix typos, wrong links and it's enough to do it 2 days before release. I agree that technical improvements are not that important, however users should be able to navigate to all or almost all changes from release notes by providing links to issues or pull requests.

For the future, we can consider automating release notes like e.g. in Mockito: http://blog.mockito.org/2014/12/new-day-new-mockito-release.html, https://github.com/mockito/mockito/blob/master/doc/release-notes/official.md and we can use Github release features: https://github.com/blog/1547-release-your-software.

**Comment by romani** [comment]
> My proposal is to work together on release notes in pull request

ok, release will be done at this weekends, all changes to release notes need to be prepared before Saturday (28 March).

> however users should be able to navigate to all or almost all changes from release notes by providing links to issues or pull requests.

user is care about functional changes - new Checks and bug fixing, all other is internal and should not distract user from reading functional changes.  List of internal refactoring could bee too long.

> http://blog.mockito.org/2014/12/new-day-new-mockito-release.html

I am ok to change release period to 2 weeks, but I dont think it is reasonable to make it less. I would rather stay on each month for a year and see a tendency of code changes in our project.

> https://github.com/mockito/mockito/blob/master/doc/release-notes/official.md

all that statistics is fun and done to show how project appreciate contribution, but it is not required by end user. Additional problem of auto generated notes is quality of commit messages. I extra demanding for quality of code changes, I even try to enforce all contributors to write issue number in message. Enforcement rules on commit message will complicate contribution, and increase to-and-from activity in PRs, I would rather use contributors patience to do testing and code polishing.
I donot see convenient model how to make it work.

>  https://github.com/blog/1547-release-your-software

I do not see a way to manually change a notes for release, it is taken from commit message and we use maven for version bump , so commit message is provided by maven plugin:
https://github.com/checkstyle/checkstyle/releases/tag/checkstyle-6.4.1
So I do not see how you propose to use that.

**Comment by romani** [comment]
@mkordas , draft of release notes for 6.5 https://gist.github.com/romani/f279a0582a7a3852c9cc , too much of your changes please propose how to compress your changes in "Notes" part

**Comment by mkordas** [comment]
1. Please remove obsolete space between commit name and dot
2. Let's normalize my name - I see both `Michal Kordas` and `Michał Kordas`. Just `Michal Kordas` will be  consistent with previous release notes.
3. We need somehow to do `GROUP BY` issue number and instead of commit name provide issue name.
4. In my opinion for commits without issue numbers we should either provide links to commits, PRs or skip them at all.

BTW: have you thought about using 'Milestones' feature of Github (example [here](https://github.com/ktoso/maven-git-commit-id-plugin/milestones?state=closed))? It would be the great place to present the stuff from Notes section.

**Comment by romani** [comment]
1. Done
2. can not find that name, please provide update (gist is like a repo you can provide PRs)
3. please provide a change
4. please remove minor changes yourself and do PR to gist.

> BTW: have you thought about using 'Milestones' feature of Github (example here)?

Milestones are possible when team is working full time. If that is after-work activity, you can not make plan, you can hope that you can manage to fix smth, any help is appreciated event cleanup in POM . Checkstyle does not have stable team (except of me), contributors come and go, and participate when they want to do so.

**Comment by romani** [comment]
I could share with you what would be good to resolve in next release as a gist document .

**Comment by mkordas** [comment]
I don't think there is an option for PR in Gist. Please review and accept my initial changes from https://gist.github.com/mkordas/8f265e45c9403394a5db

> Milestones are possible when team is working full time.
Actually what I meant is assigning milestone only when something is fully finished. Instead manually writing "fixed, will be in 6.5" you could just assign 6.5 milestone.

**Comment by romani** [comment]
> I don't think there is an option for PR in Gis

yes, I  can not find that too. Thanks for update , but we need to cut/compress a Note part significantly (at least in two times), too much minors are mentioned, it will blow release notes page with no benefits.

> writing "fixed, will be in 6.5" you could just assign 6.5 milestone.

https://help.github.com/articles/creating-and-editing-milestones-for-issues-and-pull-requests/
Thanks a lot, I was not aware of that feature, previously i tried to do that by github tags, that cause another inconvenience. I will use milestones for 6.6 .

**Comment by romani** [comment]
@mkordas , I did serious formatting, grouping, sorting  base on your latest gist - https://gist.github.com/romani/653e48b414dab6dd57f6

I highly recommend to keep Notes in that compact way, I hope I did not reduce your impact on project in that release.
Please approve Release notes for publishing, and I will do a release 6.5

**Comment by mkordas** [comment]
@romani, grouping is pretty neat. Here is what I've manged to do in https://gist.github.com/mkordas/8f265e45c9403394a5db:
* New Features and first few items of Bug Fixes are now kind of very brief migration guide - users are quickly able to spot new options and bug fixes that break backward compatibility (and may break people's builds)
* Fix typos, formatting and punctuation
* Move a few things from bug fixes to new features to highlight the new options
* Unify wording of a few similar issues
* Add PR references to things where issues were missing

Regarding keeping notes brief - I totally agree, but on the other hand:
* During refactoring something might have been broken and regression would occur - notes are first place to read about the changes and quickly locate malicious commit
* We want to practice our own preach and show to people that our project is very active and code quality goes up

Feel free to release 6.5. Hope milestones will help a lot with 6.6.

**Comment by romani** [comment]
@mkordas,

first and draft version of release notes builder - https://github.com/checkstyle/contribution/tree/master/releasenotes-builder

We need to automate Release notes generation. I see only one way to do it:
1) we enforce commit message format (by special step at verify stage of build(travis)), to have issue number in it.
2) user need to create issue first and then do PR (it is bureaucracy :(, but that will help us automate a process). Issue title should match commit message plus link to issue number. 
3) create a tool that generate chunks for release notes, base on issue tittle, and not a commit message, and admin will require only sort by categories

by mean of that we should only take care of issue title, we could polish them any time even before release.

Does it make sense to you ?

**Comment by mkordas** [comment]
Release Notes Builder looks neat and it's Groovy :+1: 

Also :+1: for automation of this process. I assume we need JUnit test that runs JGit on current branch and looks through all commits in the history up to some particular point. Then we check if issue number is present by extracting `#\d+` and connecting to Github to check if issue exists.
I wouldn't enforce the same title for commit and issue - you may have multiple commits for an issue.

How would you like to get list of issues during the release? Extracting them from commits or relying on milestones?

**Comment by romani** [comment]
I try to summarize all my thoughts there (https://github.com/checkstyle/checkstyle/wiki/Release-notes-automation), too much nuances and items to think before any implementation to avoid introduction of serious complexity for simple/ad-hoc contributions.

It is not complete yet, any proposals are welcome.

> JUnit test that runs JGit on current branch

yes.

> How would you like to get list of issues during the release? Extracting them from commits or relying on milestones?

please look at wiki page.

**Comment by romani** [comment]
@mkordas , is there any reason to keep that issue as open?

**Comment by mkordas** [comment]
@romani, let's close it, we just should keep in mind that sometimes users may need a guide how to upgrade to the newest version easily
