### ISSUE TITLE
 Align XDocs and Javadocs for sizes package

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#7060]
Part of #5750

package com.puppycrawl.tools.checkstyle.checks.sizes;

- [x] AnonInnerLength #7061
- [x] ExecutableStatementCount #7071
- [x] FileLength #7073
- [x] LineLength #7062
- [x] MethodCount #7074
- [x] MethodLength #7070
- [x] OuterTypeNumber #7063
- [x] ParameterNumber #7068

**Comment by rnveach** [comment]
All fixes were merged
