### ISSUE TITLE
Link to Java Coding Convention in DeclarationOrder check docs does not work correctly

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#707]
Link on [DeclarationOrder](http://checkstyle.sourceforge.net/config_coding.html#DeclarationOrder)  brings to Oracle landing page instead of specific code convetion that this check enforces.

**Comment by romani** [comment]
fixed, will be in 6.5 or 6.4.1

**Comment by romani** [comment]
@mkordas , if you interested at Ordering, please consider https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/master/sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/CustomDeclarationOrderCheck.java it is more powerfull Check.

**Comment by romani** [comment]
fyi: #711
