### ISSUE TITLE
Maven-checkstyle-plugin can use code format file directly

### ISSUE THREAD

**Issue by zhaoyuguang** [checkstyle/checkstyle#7072]
Maven-checkstyle-plugin can use code format file directly. such as https://raw.githubusercontent.com/spring-cloud/spring-cloud-build/master/spring-cloud-dependencies-parent/eclipse-code-formatter.xml

**Comment by strkkk** [comment]
@zhaoyuguang I guess correct repo for this issue is https://github.com/apache/maven-checkstyle-plugin

**Comment by zhaoyuguang** [comment]
> @zhaoyuguang I guess correct repo for this issue is https://github.com/apache/maven-checkstyle-plugin

Thanks
