### ISSUE TITLE
Checkstyle website does not resize to mobile browser screens.

### ISSUE THREAD

**Issue by Fernal73** [checkstyle/checkstyle#7083]
https://checkstyle.sourceforge.io/

Checkstyle website does not render well and resize to mobile browser.

Browsers checked against :+1: 
Opera Mini, Google Chrome, Mi Browser.

**Comment by Fernal73** [comment]
https://github.com/checkstyle/checkstyle/issues/7036

Holds for whole website.

Example blocks have to be scrolled through.

**Comment by romani** [comment]
Whole site rendering in done by site plugin.
Solution in customization of maven template or skin:
https://maven.apache.org/plugins/maven-site-plugin/examples/templatefile.html
https://maven.apache.org/plugins/maven-site-plugin/examples/creatingskins.html

If there is some web engineer who wants to contribute better rendering for our website, please be welcome with PR.

**Comment by Fernal73** [comment]
I'm not an expert in HTML or CSS, for that matter. But even I can see that
it's a real estate problem. The navigation bar on the left has to be moved
to the top.


https://books.sonatype.com/mvnref-book/reference/site-generation.html

This is so much more readable.

**Comment by jo2** [comment]
I took a look at it and can submit a PR for this. Due to PR guidelines the issue needs the approved label. Could someone please add the label so I can create the PR?

**Comment by romani** [comment]
Issue is approved, to avoid massive redo of your work, please do preview to let us confirm that implementation proposal is good.

Thanks a lot for help.

**Comment by jo2** [comment]
It would look like this:
![image](https://user-images.githubusercontent.com/7516893/68942860-ddc89900-07a9-11ea-8339-8c8ebb944655.png)

I'm stil thinking about having an expendable menu.. Some thoughts about that?

**Comment by romani** [comment]
This looks good, please do PR for this to let me review what is cost of this awesome rendering. I am fine to have only one page fixed to understand scope.

**Comment by romani** [comment]
Let's think about expandable menu in separate issue

**Comment by romani** [comment]
fix is merged.
@jo2 , thanks a lot for huge update !!!

there are some minors https://github.com/checkstyle/checkstyle/pull/7255#issuecomment-559889800, separate issue(s) should be created to address them.
this issue is closed to keep scope sane, if something else found - new issue should be created.

**Comment by jo2** [comment]
Opened an Issue referring to these minors. I'v there's anything else found or there are some more changes to do to the website, feel free to pin me there.
