### ISSUE TITLE
Documentation for Checkstyle rules need to be more informative.

### ISSUE THREAD

**Issue by Fernal73** [checkstyle/checkstyle#7084]
https://checkstyle.sourceforge.io/config_annotation.html

Checkstyle rules must document what java source class element they are to be annotated to for @SuppressWarnings.

"ElementType.ANNOTATION_TYPE can be applied to an annotation type.
ElementType.CONSTRUCTOR can be applied to a constructor.
ElementType.FIELD can be applied to a field or property.
ElementType.LOCAL_VARIABLE can be applied to a local variable.
ElementType.METHOD can be applied to a method-level annotation.
ElementType.PACKAGE can be applied to a package declaration.
ElementType.PARAMETER can be applied to the parameters of a method.
ElementType.TYPE can be applied to any element of a class."

https://docs.oracle.com/javase/tutorial/java/annotations/predefined.html

Rules that belong to TreeWalker and Checker modules are to be differentiated in the documentation via a marker (either an asterisk or something distinguishable). The current Checker module rules have a chain icon. It would help if the Tree Walker modules had a tree icon. 
Additionally, the parent module field descriptor should be moved to the top from the bottom of each rule. This way, it's visible right away. 

There needs to be another field for each rule:
Supports SuppressionXpathFilter: Yes/No.

The documentation for each rule needs to state its severity level : IGNORE, INFO, WARNING, ERROR. This, too, needs to be at the top of the rule description. 

As a general rule-of-thumb, information that forms a decision criteria must be placed up-front.

While this is not related to documentation, it would help if there were a tool or way to check if a user's configuration is up-to-date with the latest Checkstyle version. Scanning through release notes and doing it manually is not the best way to go about it. This should not just list the new rules but also the rules not in use and properties or attributes missing or added to existing rules in the user's configuration since. Also, deprecated attributes and rules currently in use in the user's configuration.

While this might seem well suited to develop as a GUI, a simpler option is to collect or collate the differences in an importable file format that can be either interactively or in batch mode be pulled in. This file can also be made available for user to edit and his previous configuration be saved for roll back should the import fail or break anything.

**Comment by Fernal73** [comment]
Corollary to following:

https://github.com/checkstyle/checkstyle/issues/7082

**Comment by romani** [comment]
> . The current Checker module rules have a chain icon. It would help if the Tree Walker modules had a tree icon.

chain icon is icon to get direct link to section.

> There needs to be another field for each rule:
Supports SuppressionXpathFilter: 

We have a lot of filters, we cannot (it is too verbose, to error prone to maintain such list) reference all of them.

> The documentation for each rule needs to state its severity level 

severity is defined in exact instance of Check. Documentation is for Check in general (not exact instance, exact config state)

> tool or way to check if a user's configuration is up-to-date with the latest Checkstyle version

oh yes, but we do not know how make such good tool. I think all frameworks/tools lack of such valuable tool/way.

===============

What I can think of ... to help users with problem that filter does not address certain Check is "Note" at the beginning of each Filter - `Filter can suppress violation of Check only if Filter and Check have the same parent module`.
@Fernal73 , will it help ?

**Comment by Fernal73** [comment]
I've been looking at the documentation.

I think the icon suggestion is easily doable even though the purpose is not
the original purpose in the case of the chain icon.

I agree checking that the user configuration is up-to-date will be a major
undertaking and such a tool can be error-prone. Unfortunately, Checkstyle
does not support versioning of rules. I'm not even convinced that's a good
idea.
I was thinking more on the lines of having a master config for all valid
rules i.e, rules that have not been deprecated and checking whether the
user configuration matches those. However, this will still not account for
property changes i.e, any properties and values added, changed or removed.

That's what makes it inordinately complex. A versioning of rules would help
but do we have want a version number for each rule in the xml?

As for your suggestion at the end, I'm not sure I understood what you meant
right off. Would a user?

**Comment by romani** [comment]
All items except for `Filter can suppress violation of Check only if Filter and Check have the same parent module` are not doable.

@rnveach, are you ok to extend doc like this ? And close this issue.

**Comment by Fernal73** [comment]
"Additionally, the parent module field descriptor should be moved to the top from the bottom of each rule. This way, it's visible right away."

This is certainly doable. It must be visible right away.

**Comment by romani** [comment]
> This is certainly doable. It must be visible right away.

Not sure, most users are not aware, as this is hidden by plug-ins. We can not put on top all information. Any symbolism will require css tricks and we are not sure how to make it. PR is welcome.

So for now it will stay as is.

**Comment by Fernal73** [comment]
Am I wrong in assuming that the rule documentation is generated as against
manually updated? If so, a simple resequencing ought to do the trick. In my
experience, it's confusing to have the parent information at the bottom
since I have often mistaken it to belong to the rule following it. It's
also the first thing I want to know when a new rule is created in a release
as to where to place it and having to scroll all the way down is simply a
pain!

**Comment by romani** [comment]
>so, a simple resequencing ought to do the trick.

Technically yes, but I do not want doc to looks that ugly.

**Comment by Fernal73** [comment]
It's either that or using a tree icon for rules under TreeWalker. Or do you
prefer a different colour font or background for the header for these
rules? Basically, you need something to distinguish the rule from a Checker
rule, at first glance.

**Comment by Fernal73** [comment]
If that's still not acceptable or doable, according to you, do what you
will.

**Comment by romani** [comment]
this discussion thread is closed, outbound actionable issue is #7179

**Comment by Fernal73** [comment]
https://github.com/checkstyle/checkstyle/issues/7084#issuecomment-538871869

Would checking against a master configuration be possible if String Similarity (Distance) algorithms and/or Locality Specific Hashing (LSH) were utilized? Would there be many false positives?
