### ISSUE TITLE
Remove deprecated methods and classes

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#7089]
Since maven-checkstyle-plugin was updated to not use these methods, we should remove them so they aren't taking up space in our code.

Deprecated methods are in: ConfigurationLoader, DefaultLogger, XMLLogger, FileContents, JavadocMethodCheck

And we can remove the class AbstractTypeParameterNameCheck.

**Comment by romani** [comment]
It might be better to make several commits to remove items separately. We need to update issue title to more clealy define what is done

**Comment by rnveach** [comment]
All issues were split apart
