### ISSUE TITLE
Add ParameterNumber.ignoreConstructors flag

### ISSUE THREAD

**Issue by ychulovskyy** [checkstyle/checkstyle#709]
Our project autowire beans by constructor. Some of them contains > 7 parameters.
We still want to use the rule but ignore it for constructors.
Solution: add ParameterNumber.ignoreConstructors boolean flag

**Comment by mkordas** [comment]
I agree, but we already have discussion regarding this as part of #683.

**Comment by romani** [comment]
@ychulovskyy , to resolve your issue please remove CTOR_DEF from "target" option of the Check, that option exists in all Checks.

**Comment by ychulovskyy** [comment]
@romani  OK, thanks! Does it make sense to update documentation? Since now solution is not obvious.

**Comment by romani** [comment]
Yes, please propose update to make it absolutely clear, example of config and code might be the best way
