### ISSUE TITLE
CS6.4: New option VisibilityModifier#immutableClassCanonicalNames, either docs or setter is wrong

### ISSUE THREAD

**Issue by lkoe** [checkstyle/checkstyle#710]
The documentation list a new property "immutableClassCanonicalNames" at the VisibilityModifier check.
The setter in VisibilityModifierCheck, however, is named "setImmutableClassNames" - hence needs to be used in a check configuration as property "immutableClassNames".

This lack of attention to detail is a bit troubling, Checkstyle 6.3 already contained 3 of similar, unnecessary mistakes.

**Comment by romani** [comment]
it is horrible, I missed that during long code review.
After a fix, I can do hotfix release, will it let you do release of Eclipse-CS 6.4 ?

We already have a special Check for that - https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/master/sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/SimpleAccessorNameNotationCheck.java
and still do not use it our self. 

One more evidence that following project have to be done asap - https://github.com/checkstyle/checkstyle/wiki/Checkstyle-GSoC-2015-Project-Ideas#project-name-practice-what-you-preach
as I(we) loose control over quality.

Google rejected our proposals for GSoC 2015 , so we need to find time to do that ourself.

**Comment by lkoe** [comment]
@romani yes, I'd prefer a 6.4.1 hotfix for the eclipse-cs release then

**Comment by romani** [comment]
fixed, will be in 6.4.1 in next day or two.

**Comment by romani** [comment]
@lkoe , hot fix is released - http://checkstyle.sourceforge.net/releasenotes.html#Release_6.4.1

**Comment by lkoe** [comment]
eclipse-cs 6.4.1 is out...
