### ISSUE TITLE
Update all links to sun.com reference to oracle site

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#711]
Example oflink from our sources:
http://java.sun.com/j2se/1.4.1/docs/api/java/text/MessageFormat.html

Linkcheck plugin does not catch that problem as all links to sun.com a re redirected to Oracle.com without error.

ToDo: all links that ocntain "sun.com" shuld be changed to corrsponding "oralce.com", IT IS NOT FIND A REPLACE TASK.

**Comment by damianszczepanik** [comment]
I will take it

**Comment by romani** [comment]
resolved, will be in 6.5
