### ISSUE TITLE
RegexpOnFilenameCheck: very bad performance on Windows

### ISSUE THREAD

**Issue by Bananeweizen** [checkstyle/checkstyle#7111]
I regularly profile the checkstyle run on my company projects. After introduction of a single RegexpOnFilenameCheck into an otherwise rather large checks configuration the CPU time went up from 7 to 11 minutes. All of those additional 4 minutes are spent in
```
    private static String getFolderPath(File file) throws CheckstyleException {
        try {
            return file.getCanonicalFile().getParent();
        }
        catch (IOException ex) {
            throw new CheckstyleException("unable to create canonical path names for "
                    + file.getAbsolutePath(), ex);
        }
    }
```
for the `getCanonicalFile()` call according to Yourkit. At least on Windows (and with company anti virus enforced) such file accesses generally take a huge amount of time.

I believe there is a simple fix to the issue: It is not necessary to canonicalize the path of each file during the scan, but only all the "roots" of the recursive directory traversal. If those have been canonicalized, the directory walking searched for nested directories/files will produce canonicalized file names automatically by appending the current directory/file name to the already canonical parent name.

![image](https://user-images.githubusercontent.com/406876/65766629-db43ae80-e12b-11e9-81c8-a8410ac46edc.png)

**Comment by rnveach** [comment]
Are you executing Checkstyle through our CLI (https://checkstyle.org/cmdline.html#Command_line_usage) or by some other means?

If you know how to fix the code, you are always welcome to start a PR and we can review.

**Comment by Bananeweizen** [comment]
In my case it is run via eclipse-cs in a full Eclipse build (that's also why the Checker.process() call in the screenshot consumes only 27% of overall runtime).
Regarding the fix: I can try that, if you also think my approach seems reasonable. However, it has low priority for myself, since I was able to replace that specific check by a regexSingleline check, thereby getting rid of the 4 minutes of runtime entirely.

**Comment by romani** [comment]
To approve issue we need to reproduce it

**Comment by rnveach** [comment]
@Bananeweizen Can you please confirm you are seeing a similar issue using the CLI?

> eclipse-cs 

The problem here is going to be where the issue lies and how to connect the fix to it.
Checkstyle is mostly just a utility that any 3rd party application can use. The separation between our app and any other is `Checker.process(List)`. By the time it gets here, we just have a list of files we need to process and they may not be in any order by root directory. `Checker.process(List)` never sends a directory, just a list of files.

If the issue can't be repeated in the CLI, then it needs to be fixed in eclipse-cs.
If the issue can be repeated, depending on how we fix it, may mean eclipse-cs and any other utility may have to fix it too.

> If those have been canonicalized, the directory walking searched for nested directories/files will produce canonicalized file names automatically by appending the current directory/file name to the already canonical parent name.

The way this is worded makes me think it is an issue for whoever is doing the directory expanding, which may be us and any 3rd party utility.
But to be sure, we need to see if the CLI behaves the same.

**Comment by rnveach** [comment]
Using our semi-official utility to check on execution time in different parts of checkstyle ( https://github.com/rnveach/checkstyle/commits/more_audits ) and our own config and files, I am not really seeing a big usage by `RegexpOnFilenameCheck`.

According to a run that takes 66.6 seconds on Windows, `RegexpOnFilenameCheck.getFolderPath` has 4104 calls but only uses a max execution time of 0.081 seconds, with the longest execution for 1 call being 0.003 seconds.

`RegexpOnFilenameCheck` as a whole only uses 0.121 seconds.
To the run, there are other checks that use more time than `RegexpOnFilenameCheck`. `Indentation` and `CommentsIndentationCheck` are the longest which use almost 1 second. `RegexpSinglelineCheck` uses 0.7 seconds, `JavadocPackageCheck` uses 0.4 seconds.

I tried a run with `RegexpOnFilenameCheck` alone and it only jumped to 0.344 seconds with the same number of calls. Still below the other checks which use more execution time.

The call to the CLI just passes in a bunch of folders, no files.
````
-c ${workspace_loc}\checkstyle\config\checkstyle_checks.xml ${workspace_loc}\checkstyle\src\it\java ${workspace_loc}\checkstyle\src\main\java ${workspace_loc}\checkstyle\src\main\resources ${workspace_loc}\checkstyle\src\test\java ${workspace_loc}\checkstyle\src\xdocs -executeIgnoredModules
````

Relatively speaking, I am not seeing the issue, but maybe it is more present on a larger number of files?
We only process 1,026 files in our run.

**Comment by romani** [comment]
We need steps to reproduce, or more evidence that issue exist.
As it exists on your windows instance, please try another instance or let's reproduce it by CLI (no eclipse). There might be nuances with jre and your antivirus. Can you try reproduce issue outside of enforced antivirus ?

If no reply in 1 month, we will close issue as incomplete. We can reopen issue as more details appear.
