### ISSUE TITLE
Remove AbstractTypeAwareCheck and combine the missing pieces into JavadocMethod

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#7116]
Split from #6873 ,

It is too much work to just up and convert the check to a new version.

I suggest smaller steps and start by removing `AbstractTypeAwareCheck` and merge the needed parts into JavadocMethod so that check can continue to function as it does now.

After this merger, we can then start looking at the pieces and removing more.

**Comment by romani** [comment]
Good plan

**Comment by rnveach** [comment]
Starting this issue requires #7114 to be merged first.

**Comment by romani** [comment]
removal is done.
All other improvements will be done in separate issues.
