### ISSUE TITLE
Add localization for javadoc.write.tag

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#7120]
TC have valid violation. We probably can open issue on it that it does not reported this issue before. But suppression of violation will probably be a challenge in property file.

I recommend to update message `javadoc.writeTag` to put "Javadoc tag" in front (in other files use google translator), so message will be different. Such update should be done in separate issue/PR.

_Originally posted by @romani in https://github.com/checkstyle/checkstyle/pull/7046#issuecomment-534554795_

**Comment by romani** [comment]
Fix is merged
