### ISSUE TITLE
Use ja-JP for Japanese locale, zh-CN for Chinese locale in travis.sh

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#7129]
Instead of `jp-JP` we need `ja-JP` for Japanese in `travis.sh`.

_Originally posted by @pbludov in https://github.com/checkstyle/checkstyle/pull/7122#issuecomment-536746154_

**Comment by rnveach** [comment]
> Instead of jp-JP we need ja-JP for Japanese

Why?

**Comment by romani** [comment]
Any ideas why it worked before ?
Please find link that "ja" is correct code.

Some related links that show that "ja" supposed to be used
https://docs.oracle.com/javase/7/docs/api/java/util/Locale.Builder.html

**Comment by pbludov** [comment]
> Any ideas why it worked before ?
It didn't work before. The default localization (english) was used.

> Please find link that "ja" is correct code.
The problem here is that there is no `messages_jp.properties ' file in the resources.
We need to rename `messages_ja.properties` to `messages_jp.properties` or change `-Duser.language=jp` to `-Duser.language=ja`

A quick search for `lava list locles` brings me to
https://www.oracle.com/technetwork/java/javase/java8locales-2095355.html

Please not commit this PR until i find a way to verify that there is a resource bundle for the requested language/country. It is possible that someone comes with a patch to support additional languages in the future. We should no longer fall into this trap.

**Comment by romani** [comment]
Japanese users frequently updated our resources, so it works for them now

**Comment by romani** [comment]
>We need to rename

Please create outbound issue on this

**Comment by pbludov** [comment]
> > We need to rename
> 
> Please create outbound issue on this

We need to rename file **OR** fix travis.sh
The file name is correct, so we actually don't need to rename the file. Sorry for the confusion.

**Comment by romani** [comment]
Language is "ja",  in all property files we use language, so should rename, to be very very correct. Right ?

**Comment by pbludov** [comment]
> Language is "ja", in all property files we use language, so should rename, to be very very correct. Right ?

No. I mean "rename messages_ja.properties to messages_jp.properties".

In the file travis.sh there was `user.language=jp`, but the corresponding file name is `messages_ja.properties`. Since they must match, I showed both options.
At that moment I didn't know which way to go.

**Comment by pbludov** [comment]
Now CI say that there is no such country "ZH" in the world. Issue updated.

**Comment by romani** [comment]
Existing suffices base on https://github.com/checkstyle/checkstyle/tree/master/src/main/resources/com/puppycrawl/tools/checkstyle :

de, es, fi, fr, ja, pt, try, zh

**Comment by romani** [comment]
I see no problems in our message_xx file, they use language abbreviation - correct.

ja, zh are the only abbreviations that are not present as country, so fix Travis is required only for them.

**Comment by romani** [comment]
Fix is merged
