### ISSUE TITLE
ENUM_DEF token support in RightCurlyCheck

### ISSUE THREAD

**Issue by sd1998** [checkstyle/checkstyle#7161]
Currently RightCurly accepts a lot less tokens (13 tokens) than LeftCurly ([20 tokens](https://checkstyle.sourceforge.io/config_blocks.html#LeftCurly_Properties)).
It is unclear if this is just a mistake or if there is some underlying reason. This issue aims at adding support for `ENUM_DEF` token in RightCurlyCheck.

Solving this issue will help solve Issue #3547.

**Comment by romani** [comment]
fix is merged.
@sd1998 , Thanks a lot your hard work.
