### ISSUE TITLE
Put in doc reason why ENUM_CONSTANT_DEF and LAMBDA tokens are not supported in RightCurlyCheck

### ISSUE THREAD

**Issue by sd1998** [checkstyle/checkstyle#7174]
Currently RightCurly accepts a lot less tokens (13 tokens) than LeftCurly (20 tokens).
It is unclear if this is just a mistake or if there is some underlying reason. 

After discussion at https://github.com/checkstyle/checkstyle/pull/7453#issuecomment-572725018
for cases like:
```
public enum Scope {
      PROTOTYPE {
          @Override
          void doSomethig() {
              doSomethig2();
          }
      }, // in "alone" mode this become weird to put "," to separate line !!!
```
This issue aims to add in documentation reason why  `ENUM_CONSTANT_DEF` token (#7519) and `LAMBDA` (#5948) token will never be added to RightCurly.

Solving this issue will help solve Issue #3547.

**Comment by pbludov** [comment]
fix is merged.
