### ISSUE TITLE
INTERFACE_DEF token support in RightCurlyCheck

### ISSUE THREAD

**Issue by sd1998** [checkstyle/checkstyle#7175]
Currently RightCurly accepts a lot less tokens (13 tokens) than LeftCurly (20 tokens).
It is unclear if this is just a mistake or if there is some underlying reason. This issue aims at adding support for `INTERFACE_DEF` token in RightCurlyCheck.

Solving this issue will help solve Issue #3547.

**Comment by gaurabdg** [comment]
I am on it

**Comment by strkkk** [comment]
Fix is merged
