### ISSUE TITLE
New JavadocMissingWhitespaceAfterAsteriskCheck

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#7183]
Although spaces after asterisks are optional in the Javadoc comments, their absence makes the documentation difficult to read. It is the de facto standard to put at least one whitespace after the leading asterisk.
```
/var/tmp $ javac TestClass.java
/**
 *no whitespace after asterisk here.
 */
public class TestClass {
}
```
Expected violation: `TestClass.java:2:5 Missing a whitespace after the leading asterisk.`

**Comment by 0blivious** [comment]
Hello, can I try working on this issue?

**Comment by pbludov** [comment]
> Hello, can I try working on this issue?

Sure. Just mark it with "I'm on it".

**Comment by 0blivious** [comment]
Can I check should the single line comment below cause violation?
```
/**no whitespace after asterisk here. */
```

**Comment by romani** [comment]
This should be violation, if it is not violation, please create separate issue on this and please do not place it in examples.

**Comment by romani** [comment]
new Check is merged.
thanks a lot @0blivious , for make it happen.
