### ISSUE TITLE
Remove all deprecated setClassLoader methods from Checker and TreeWalker

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#7190]
Split from https://github.com/checkstyle/checkstyle/issues/3773 and identified at https://github.com/checkstyle/checkstyle/pull/7114#issuecomment-536136005 ,

maven-checkstyle-plugin uses Checkers and TreeWalkers `setClassLoader` method and can't be completely removed until the plugin stops using it. See https://github.com/apache/maven-checkstyle-plugin/blob/57cf9696cfd1fb0d4de5842bea050b9aa4026dd0/src/main/java/org/apache/maven/plugins/checkstyle/exec/DefaultCheckstyleExecutor.java#L204

The methods had it's functionality removed in #3773 and they do nothing now.

Once the plugin removes its usage of them, we should completely remove these methods from checkstyle.

This issue is blocked till [maven-checkstyle-plugin](https://maven.apache.org/plugins/maven-checkstyle-plugin/) is released after `Version: 3.1.0` (this is current version )

Issue in maven-checkstyle-plugin: https://issues.apache.org/jira/browse/MCHECKSTYLE-381

-------

**Migration note:**

after release of fix for this issue. There will be problems like:
`Caused by: org.apache.maven.plugin.PluginContainerException: An API incompatibility was encountered while executing org.apache.maven.plugins:maven-checkstyle-plugin:3.1.0:check: java.lang.NoSuchMethodError: com.puppycrawl.tools.checkstyle.Checker.setClassLoader(Ljava/lang/ClassLoader;)V`

to fix this you need to upgrade to `maven-checkstyle-plugin:3.1.1`

**Comment by bmhm** [comment]
It's only deprecated since 8.26 (does it even have a `@Deprecated` annotation?).
The PR will be reworked into a try-/catch block, so the method will get called for old versions (where it still exists).

**Comment by romani** [comment]
@bmhm , thanks a lot, make sense.
Please beware that checkstyle do not support old versions, all fixed appear in new next version only. So gentle push of users to use new version of checkstyle is good.

**Comment by bmhm** [comment]
> It would be awesome if plugin can be released more frequently (ones in few years is a bit slow) and update default checkstyle version.

I do not know if this is possible due to the incompatibilities you introduced in checkstyle 8.24. This would break setups for a lot of users. :(

**Comment by romani** [comment]
@bmhm ,

Changes in checkstyle are unavoidable.
Periodically user will need to update config for whole Check, or removed properties, changes in properties.
There will be bunch of similar changes in future, but we always publicly declare changes and provide migration notes in issues so user can find them.

If user is using chekcstyle not only in maven plugin (but in IDE and sonar), he have to use override of checkstyle version to keep same behavior across all build environments. So staying on very old version for maven plugin is not good. It might be better to use some recent version (does not required to be latest), so user can downgrade/override checkstyle version if required, but by default they get recent behavior.

We can always advice on what version to upgrade. Version right before version with big compatibility damage is good choice.
This is how we advised to NOT use latest version of checkstyle in previous maven plugin version due to https://checkstyle.org/releasenotes.html#Release_8.21 "API: make api not depend on antlr by splitting DetailAST between implementation and interface."  #3417  - that is big damage for all thirdparty Checks (my bad that I missed major version bump there).

**Comment by bmhm** [comment]
> Changes in checkstyle are unavoidable.

I do not deny this. But you may have been able to support "LineLength" as a subelement for treewalker for one or two versions, then deprecate it for two versions, and then be removed. Just as an example. And by "supported" I mean "do not throw an error, just log a warning" while verifying the `checkstyle.xml`. 

Or instead of removing a check just make it a no-op check for the next 4-6 versions or so.

Just my two cents.

**Comment by romani** [comment]
yes, deprecation process is hard ....

We(checkstyle library) do not have a place where to report general violation, as all violations should be file based. Only plugins know how to report such messages to user. But plugins are NOT actively supported to make it happen, there even more critical projects between library and plugins - VERY painful awaits many years, and still not implemented.
   
In my experience, nobody change config while it is working. It would be the same surprise that module was moved, even there was deprecation process. Nobody read releasenotes if all works as it was before.

> no-op check 

it will give user illusion, I do not like this, it is better to spend 30 min on upgrade but be sure that checkstyle keep code on leash. if 30 min is too much, stay on old version.

**Comment by romani** [comment]
maven plugin is updated and released version.
https://github.com/checkstyle/checkstyle/pull/7551

We can remove methods completely now.

**Comment by nmancus1** [comment]
I am on it.

**Comment by bmhm** [comment]
Great! Now I can add a warning to checkstyle: If the method call was successful, it means users are using an outdated version. In this case I'd create a WARNING. Just behind this line:

https://github.com/apache/maven-checkstyle-plugin/blob/125a659c6004a48284f0470a100ed58238d211d3/src/main/java/org/apache/maven/plugins/checkstyle/exec/DefaultCheckstyleExecutor.java#L314-L317

What do you think?

**Comment by rnveach** [comment]
@romani @bmhm Please look at https://github.com/checkstyle/checkstyle/pull/7680 , the PR trying to remove methods. The methods still exist in maven-checkstyle-plugin so I don't think we can remove them here. maven-checkstyle-plugin needs to switch to using reflection if it is still going to call the method. It can't be a hardcoded method call.

**Comment by bmhm** [comment]
The checkstyle-plugin does not need to update to 8.30 right now. If it did we could not check for an old version and warn the user.
Please take a look at the exception handling.

**Comment by rnveach** [comment]
The exception handling in `maven-checkstyle-plugin` did not catch the exception we are seeing in our PR to remove the methods.
https://app.wercker.com/checkstyle/checkstyle/runs/build/5e574fbd7b63df001ae37348?step=5e574ffca15bef000885408f
> Caused by: java.lang.NoSuchMethodError: com.puppycrawl.tools.checkstyle.Checker.setClassLoader(Ljava/lang/ClassLoader;)V
    at org.apache.maven.plugins.checkstyle.exec.DefaultCheckstyleExecutor.executeCheckstyle (DefaultCheckstyleExecutor.java:204)
 
Our PR CI runs our current checkstyle snapshot against all projects for regression and their setups. They, and we, use `maven-checkstyle-plugin` and and the failure in the PR shows that if we remove the deprecated methods and release as 8.30, checkstyle will not work with any released version of `maven-checkstyle-plugin` and our own project will be dead in the water. We rely too heavily on `maven-checkstyle-plugin` for running checkstyle and regression to be without it.

https://github.com/bmhm/maven-checkstyle-plugin/blob/master/src/main/java/org/apache/maven/plugins/checkstyle/exec/DefaultCheckstyleExecutor.java#L316
The issue is `maven-checkstyle-plugin` has the deprecated method call hard coded into the source.

We cannot remove the methods until `maven-checkstyle-plugin` provides a released workaround that we and others can upgrade to. We can not make this change and go first unfortunately.

IMO, the plugin has to turn the method call into a reflection call so the source can be compiled on any checkstyle version.

**Comment by bmhm** [comment]
Yes, this plugin needs 8.29 to compile. The fix is only if you change the dependency for running the Maven plugin with the new snapshot version.

This was intended by me and your previous comment did not mention you want to compile the maven checkstyle plugin yourself.

Not a bug until the maven checkstyle plugin updates to 8.30 (non-SNAPSHOT).

**Comment by rnveach** [comment]
> This was intended by me and your previous comment did not mention you want to compile the maven checkstyle plugin yourself.

We are not compiling the maven plugin. I assume you are referencing the following line:
> the plugin has to turn the method call into a reflection call so the source can be compiled on any checkstyle version that the plugin will support.

I was just thinking from prospect of the plugin team maintaining compatability with multiple versions. We only work with released versions of checkstyle as we are your users. We are not trying to reduplicate the plugin by compiling it.

> Not a bug until the maven checkstyle plugin updates to 8.30

What blocking us is not a bug, but maven plugin should not be using deprecated methods from our project. This method specifically is not supported anymore and does nothing.

**Comment by bmhm** [comment]
Actually I was referring to this section:

> Our PR CI runs our current checkstyle snapshot against all projects for regression and their setups.

Sounds to me as if you were compiling the checkstyle plugin.

> They, and we, use maven-checkstyle-plugin and and the failure in the PR shows that if we remove the deprecated methods and release as 8.30, checkstyle will not work with any released version of maven-checkstyle-plugin and our own project will be dead in the water. We rely too heavily on maven-checkstyle-plugin for running checkstyle and regression to be without it.

As the checkstyle plugin has a compile dependency to an older version of checkstyle, it should have run into the catch block.

Can you show me the failing build? I'd like to see if I can make more sense from it.

**Comment by rnveach** [comment]
Failing build and exception message was referenced in my message at https://github.com/checkstyle/checkstyle/issues/7190#issuecomment-592092027
Unfortunately, it is a CI that is restricted to admins as it does not allow anonymous access. But here is the [log.txt](https://github.com/checkstyle/checkstyle/files/4268007/log.txt) .

> Sounds to me as if you were compiling the checkstyle plugin.

When you say plugin, I assume you mean maven-checkstyle-plugin. I would not call us a plugin, per-say, but more a library.

**Comment by romani** [comment]
problem is that plugin is always try to use such method, even classpath is not defined in config.
https://github.com/bmhm/maven-checkstyle-plugin/blob/2e93263a6c3b1551c86709cc05ec469e29848c62/src/main/java/org/apache/maven/plugins/checkstyle/exec/DefaultCheckstyleExecutor.java#L159

if not possible avoid execution of set
we might need to update catch to catch more exceptions.
https://github.com/bmhm/maven-checkstyle-plugin/blob/master/src/main/java/org/apache/maven/plugins/checkstyle/exec/DefaultCheckstyleExecutor.java#L314
```
        try
        {
            checker.setClassLoader( projectClassLoader );
        }
        catch ( NoSuchMethodError ignored ) {
```
Interesting is that our CI is failed with NoSuchMethodError that we expect to suppress :). Looks like JVM do not liek such Errors a all. We might use reflection to check that such method exists before execution, catch is not working in this case.
@bmhm , can you share your ideas on this.

**Comment by bmhm** [comment]
Hi @romani 

it is a little bit confusing to have two threads. I honestly do not understand why this catch wouldn't work, as even a java champion looked over it (iirc). I will try to run the  precompiled `maven-checkstyle-plugin:3.1.1` with a snapshot build of this repository's master to confirm the behaviour you mention.

**Comment by bmhm** [comment]
Hello @romani,

I cloned the current master of the checkstyle library (8.31-SNAPSHOT) and removed the `setClassLoader` method from `Checker.java`.
I then used `maven-checkstyle-plugin:3.1.1` with `checkstyle:8.31-SNAPSHOT` to check my sources and it worked just fine.

My guess is that your CI will recompile `maven-checkstyle-plugin`, which will obviously not work. I do not see any problem in the `maven-checkstyle-plugin` relying on 8.29 for backwards compatibility for compilation but being able to execute with more recent versions of checkstyle.

**Comment by bmhm** [comment]
@romani  found it!!

> Unfortunately, it is a CI that is restricted to admins as it does not allow anonymous access. But here is the [log.txt](https://github.com/checkstyle/checkstyle/files/4268007/log.txt) .

Look closer!

`Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.0:check`

You need to  use `maven-checkstyle-plugin:3.1.1:check` (v3.1.1, but you were using v3.1.0)!

**Comment by romani** [comment]
>v3.1.1, but you were using v3.1.0

Thanks a lot !! We will update our CI or related projects. Sorry for false alarm.

**Comment by bmhm** [comment]
> > v3.1.1, but you were using v3.1.0
> 
> Thanks a lot !! We will update our CI or related projects. Sorry for false alarm.

Don't mention it. My heart just stopped beating for some minutes because these were my first commits to a Maven project and catching such methods are so basic things to to in java.

I am really glad and relieved it turned out to be something easy to fix. ☺️

**Comment by rnveach** [comment]
Fix was merged
