### ISSUE TITLE
Should checkstyleMain in gradle depend on classes task?

### ISSUE THREAD

**Issue by willamette** [checkstyle/checkstyle#7204]
classes task would involve compileJava. 

This sounds unncessary because checkstyle is only examing the source codes? 

Please confirm..

**Comment by rnveach** [comment]
@willamette shouldn't this issue be posted to checkstyle gradle?
we are just the main utility and don't know what gradle does with checkstyle.

**Comment by willamette** [comment]
Oh, I didn't know that.. thought you guys are also maintaining the gradle plugin.. I will ask gradle guys then

One more question before going there, I want to confirm the checkstyle doesn't need the compiled java classes, right?

**Comment by romani** [comment]
> checkstyle doesn't need the compiled java classes, right?

yes, checkstyle works on text files (java, properties, xml, ..... ).
FYI: https://checkstyle.org/writingchecks.html#Limitations

**Comment by rnveach** [comment]
> checkstyle doesn't need the compiled java classes

Technically 1 check does, JavadocMethodCheck, but we are already in the process of removing that functionality as it was never stable.

**Comment by willamette** [comment]
> > checkstyle doesn't need the compiled java classes
> 
> Technically 1 check does, JavadocMethodCheck, but we are already in the process of removing that functionality as it was never stable.

Interesting.. thanks for the update.
