### ISSUE TITLE
Align XDocs and Javadocs for javadoc package

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#7208]
Part of #5750

package com.puppycrawl.tools.checkstyle.checks.javadoc;

- [x] JavadocMethod #7244
- [x] JavadocPackage #7245
- [x] JavadocParagraph #7250
- [x] JavadocStyle #7257
- [x] JavadocTagContinuationIndentation #7259
- [x] JavadocType #7262
- [x] JavadocVariable #7264
- [x] NonEmptyAtclauseDescription #7260
- [ ] SingleLineJavadoc #7265
- [x] SummaryJavadoc #7263
- [x] WriteTag #7261

**Comment by romani** [comment]
Final fix is merged
