### ISSUE TITLE
Automate code coverage validation 

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#722]
base on decision and solution of https://github.com/sevntu-checkstyle/sevntu.checkstyle/issues/311
we need to enforce best possible code coverage and  do not allow to reduce it.
Validation should be automated and restricted during build process the same was as we did in sevntu.checkstyle project.
Each Check should have in pom.xml it own current coverage for now, but ultimate target is 100%, after each update in Check , coverage should grow.

**Comment by Bhavik3** [comment]
I have implemented small portion of it. you have a look on it. if everything is fine, I will expand It for whole project.
https://github.com/Bhavik3/checkstyle/commit/0ef06746e04af17cb081526d3d8b1bbe156f3c91
@romani

**Comment by romani** [comment]
yes, you are on a right way.

**Comment by romani** [comment]
fixed at #757

**Comment by damianszczepanik** [comment]
With this change there is problem on Windows with plugin cobertura-maven-plugin, quite old well know limitation: [The command line is too long.](https://groups.google.com/forum/#!topic/gwt-maven/M1WqNHEe4IU)

**Comment by romani** [comment]
yes, we have issue on that #804 , you can see there a resolution.
