### ISSUE TITLE
New check: AvoidEmptySuperConstructorCall

### ISSUE THREAD

**Issue by strkkk** [checkstyle/checkstyle#7237]
```
$ cat Test.java
class Test {
	
	Test() {
		super(); // violation
		System.out.println("hello");
	}
       Test(Object anyArg) {
		super(); // violation
	}
       Test(Object anyArg, Object b) {
		super(1); // no violation
	}

       class Nested {
            Nested() {
               super(); // violation
            }
        } 
	
}

class Test2 extends java.util.ArrayList {
    Test2() {
        super(); // violation
     }
    Test2(Object anyArg) {
        super(new HashSet()); // no violation
     }
}

$ cat config.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
          "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name="Checker">
  <module name="TreeWalker">
        <module name="AvoidEmptySuperConstructorCall"/>
  </module>

</module>
```

Violation at line with violation comment

Update from sevntu test cases:
```
public class InputUselessSuperCtorCallCheck1
{
    public InputUselessSuperCtorCallCheck1()
    {
        super(); // violation
    }
}
```

```
public class InputUselessSuperCtorCallCheck3
{
    public InputUselessSuperCtorCallCheck3()
    {
        super(); // violation
    }
    
    public InputUselessSuperCtorCallCheck3(int i)
    {
        super(); // violation
    }
}
```

```
public class InputUselessSuperCtorCallCheck4 extends java.lang.Object
{
    public class Inner
    {
        public Inner()
        {
            super(); // violation
        }
    }
}
```

```
public class InputUselessSuperCtorCallCheck5
{
    private static class Base
    {
        public Base(int i)
        {
            
        }
    }
    
    private static class Derived extends Base
    {
        public Derived()
        {
            super(2); // no violation
        }
    }
}
```

```
public class InputUselessSuperCtorCallCheck6 extends java.lang.Object
{
    public InputUselessSuperCtorCallCheck6() {
        super(); // violation
    }
}
```

```
public class InputUselessSuperCtorCallCheck7
{
    class Base
    {
        public Base() {}
        
        public Base(int i) { }
    }
    
    class DerivedOne extends Base
    {
        public DerivedOne() {
            super(); // violation
        }
        
        public DerivedOne(int i) {
            super(i);
        }
    }
    
    class DerivedTwo extends Base
    {
        public DerivedTwo() {
            super(); // violation
        }
        
        protected DerivedTwo(int i) {
            super(i);
        }
    }
}
```

**Comment by rnveach** [comment]
This seems the same as https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/master/sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/UselessSuperCtorCallCheck.java

**Comment by strkkk** [comment]
@rnveach it is.
So it wont be added to checkstyle repo?
Is there some reason for it?

**Comment by rnveach** [comment]
Usually sevntu is for more questionable checks that could have false positives. I specifically don't know about this check and if something makes it questionable to not be in main repo.

@romani ping

**Comment by strkkk** [comment]
I read description from sevntu check and check seems too complicated for such simple rule.
It can just detect usages of `super()`, I do not see any possible problems with false positives.

**Comment by romani** [comment]
Sevntu project is mix of good Checks(too much problems in main repo, to bother moving Checks from oner repo to another) to be moved to main repo and controversial Checks that good to exist if user understand that false positives are possible.

**Comment by strkkk** [comment]
@romani so what about this one?
I suggest to add it without any additional options.

**Comment by romani** [comment]
You need to extend your test input a lot( you can reuse inputs of Check in sevntu)), and show what cases you intend to cover a what cases you will skip. Name should be adjusted also as it is too general.

**Comment by strkkk** [comment]
> You need to extend your test input a lot and show what cases you intend to cover a what cases you will skip

I do not understand what you mean. Call to `super` without arguments is a useless regardless the context.

>Name should be adjusted also as it is too general.

Suggestions?

**Comment by romani** [comment]
I mean that I need more details on what is target of Check and what is expected behavior of numerous combinations of c-tors (with inheritance , with multiple c-tors with different arguments ) to make sure you are not going to do same as we have in sevntu. Please write Rationale to let us sure your will address only single case and nothing else.

> Suggestions? on names

NoArgumentSuperInDefaultConstructors or ....

**Comment by strkkk** [comment]
@romani I updated examples. Basically, check is going to do same things, but I suggest to do it without additional properties as one in sevntu.

About naming - `super` can be called not only in default (I guess you meant non-arg ctors?) constructors.
`NoSuperCtorCallWithoutArgs` seems better to me.

**Comment by romani** [comment]
Please take all inputs of existing Check and put violation comment on each line where your Check raise violation.
I do not remember why we did that much  properties, but definitely for a reason, I do not remember all details.

Links:
https://github.com/sevntu-checkstyle/sevntu.checkstyle/issues/186
https://stackoverflow.com/questions/6318628/when-do-you-need-to-explicitly-call-a-superclass-constructor/6318640#6318640
According to https://github.com/sevntu-checkstyle/sevntu.checkstyle/commits/master/sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/UselessSuperCtorCallCheck.java such properties appeared  from first implementation.

**Comment by strkkk** [comment]
@romani I added test inputs from sevntu.

I guess the main reason was to allow super constructor call if there are multiple superconstructor call.

**Comment by romani** [comment]
Sorry @strkkk , I have no enough time to think about this issue, 
here additional discussion thread - https://groups.google.com/forum/#!topic/sevntu-checkstyle/8MDdf4SUR8A about this Check.
I have concerns to avoid properties as this Check was applied to my former production code and was approved by whole team in such form, we create properties in Check always for a reason,  to reconcile engineers on what is good.
Please read this thread, if no good reason is found we probably we need to request review from others first, as I am a bit bias in this situation.

**Comment by romani** [comment]
@rnveach  and @pbludov , I am ok to create new Check without properties. Please review ...

But I would change name of Check to use more JDK specification terms - something like `AvoidNoArgumentSuperConstructorCall`

https://docs.oracle.com/javase/specs/jls/se13/html/jls-8.html#jls-8.8.7
> If a constructor body does not begin with an explicit constructor invocation and the constructor being declared is not part of the primordial class Object, then the constructor body implicitly begins with a superclass constructor invocation "super();", an invocation of the constructor of its direct superclass that takes no arguments.

**Comment by rnveach** [comment]
I am ok with check and name.

**Comment by romani** [comment]
we now have 2 names here and one in sevntu .... what exact name you like more ?

**Comment by rnveach** [comment]
> AvoidNoArgumentSuperConstructorCall

**Comment by pbludov** [comment]
I'm ok with this proposal.

**Comment by romani** [comment]
@strkkk , I recommend to close this issue and make new issue with clean summary , exact names, ... To make sure we are all on the same page. It is better to make link to this issue if someone needs history of discussion.
