### ISSUE TITLE
Exclude a path / package

### ISSUE THREAD

**Issue by alan-hwp** [checkstyle/checkstyle#7256]
Hi Checkstyle Community,

Sorry to post this here, but I did not know a better place. And Google did not help.
The Checkstyle Maven plugin supports an <exclude></exclude> tag for ignoring paths, we use it to prevent scanning test code. Is it possible to effect the same outcome from the checkstyle.xml configuration for IDE plugin?

I'm using the checkstyle plugin for VS Code, and it's scanning unit test sources that our maven file does not scan. So I'm seeing errors the "build" does not see. The argument for scanning tests too is not really pertinent to this. I've made the case internally to check all source code.

Many thanks in advance for any helpful suggestions.

Alan

**Comment by strkkk** [comment]
May be other guys can help you with this issue.
I can recommend you to also post this question on stackoverflow with checkstyle tag
https://stackoverflow.com/questions/tagged/checkstyle

**Comment by romani** [comment]
You need to look for VS plugin community help, we do not know anything about such plugin, sorry.

You might need reconcile ide and plugin by some variable to source files, see kind of similar problem  https://github.com/checkstyle/eclipse-cs/issues/188 .
If no luck, please use filter in config and suppress all violations in tests , example https://github.com/checkstyle/checkstyle/blob/master/config/checkstyle_non_main_files_suppressions.xml#L13
