### ISSUE TITLE
JDK 13 Travis Failure

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#7276]
https://travis-ci.org/checkstyle/checkstyle/builds/615140227?utm_source=github_status&utm_medium=notification
https://travis-ci.org/checkstyle/checkstyle/builds/614013468?utm_source=github_status&utm_medium=notification

````
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   CheckerTest.testDefaultLoggerClosesItStreams:1337 Flush count was not expected expected:<3> but was:<4>
[ERROR]   CheckerTest.testXmlLoggerClosesItStreams:1362 Flush count was not expected expected:<0> but was:<1>
[ERROR]   XpathFileGeneratorAuditListenerTest.testCorrectOne:168->verifyOutput:309 expected number of flushes expected:<1> but was:<2>
[ERROR]   XpathFileGeneratorAuditListenerTest.testCorrectTwo:199->verifyOutput:309 expected number of flushes expected:<1> but was:<2>
[ERROR]   XpathFileGeneratorAuditListenerTest.testOnlyOneMatching:227->verifyOutput:309 expected number of flushes expected:<1> but was:<2>
[INFO] 
[ERROR] Tests run: 3159, Failures: 5, Errors: 0, Skipped: 0
````

**Comment by pbludov** [comment]
Same behaviour with JDK13. It looks like the new JDKs have added a flush method call somewhere. The assertion  should be `>=1`.

**Comment by pbludov** [comment]
We can try to use Truth here as discussed in https://github.com/checkstyle/checkstyle/issues/7239

**Comment by pbludov** [comment]
More details: in Java8 there is only one invocation of the `flush` method from

`sun.nio.cs.StreamEncoder#implFlush`

In Java13 there is two:
on from `sun.nio.cs.StreamEncoder#implFlush`
another from `sun.nio.cs.StreamEncoder#implClose`

**Comment by pbludov** [comment]
This is a side effect of https://bugs.openjdk.java.net/browse/JDK-8220477

**Comment by rnveach** [comment]
@romani 
https://travis-ci.org/checkstyle/checkstyle/jobs/614013497#L82-L87
Even though we requested JDK 12, Java version being run is JDK 13.

**Comment by romani** [comment]
strange ... I relaunched build item, if problem is presistent, we should try to play with confirg to workaround travis config parse problem on Travis.

**Comment by pbludov** [comment]
fix is merged
