### ISSUE TITLE
HiddenField docs for setterCanReturnItsClass contain invalid code example

### ISSUE THREAD

**Issue by Derbeth** [checkstyle/checkstyle#729]
The code example from http://checkstyle.sourceforge.net/config_coding.html#HiddenField:

                class Foo {
                    int prop;
                    Foo setProp(int prop) { this.prop = prop; }
                }

will not compile, because setFoo() is missing a return statement.

**Comment by mkordas** [comment]
I've opened #731 with fix.

**Comment by Derbeth** [comment]
It does not fix - please see my comment.

**Comment by mkordas** [comment]
You are right, thanks! Should be fixed now.

**Comment by romani** [comment]
fixed, will be in 6.5
