### ISSUE TITLE
Remove build for old non-LTS releases 

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#7299]
based on @romani  https://github.com/checkstyle/checkstyle/issues/7281#issuecomment-560948039

Appveyor currently lasts 40-65 minutes. And has no ability to cancel the build. By removing the build for JDK 9 and JDK 10 we can reduce the build time by one third.

It is enough to build for all active LTS releases (8 and 11) and for  the newest one (13 as today). There is no reason to check the build for releases that are no longer supported by the vendor.

**Comment by romani** [comment]
Fix is merged
