### ISSUE TITLE
Fix Issues left from mobile design

### ISSUE THREAD

**Issue by jo2** [checkstyle/checkstyle#7301]
@romani according to your [comment](https://github.com/checkstyle/checkstyle/issues/7083#issuecomment-559892918), here is the issue to the remaining minors. I'll take a look at it.

> non blocking regressions (can be fixed in separate PRs):
extra line wrapping after small images 
![image](https://user-images.githubusercontent.com/812984/69891951-5143cd80-12b5-11ea-9b74-20278b7c90d3.png)
> 
extra space (if we try to make rendering awesome, but really ... not a problem):
![image](https://user-images.githubusercontent.com/812984/69891985-aaabfc80-12b5-11ea-96e8-83bfe4b9ffe7.png)

**Comment by jo2** [comment]
Second one is an easy fix. source-tag has a 'fix' width of 90%, remove it and the full width is used. 

First one is a bit trickier. To avoid javascript usage, we could add a `data-width` tag to all images. Those attributes gets the value `small` if the image should be displayed inline (no wrapper needed) and `large` if a wrapper is needed. The tests for whether the image has a wrapper or not can also be updated matching this. The attribute `display: block` of the wrapper is the cause for these problems. It is needed for the  horizontalscrolling of large images but causes a line-break, too, which only really matters in small inline images.

**Comment by jo2** [comment]
If someone cann add 'approved' label to this issue, I can do a PR.

**Comment by romani** [comment]
fix is merged.
Thanks a lot @jo2 for making our website nice ! it is become real pleasure to open web site on mobile.
I hope our users do not open checkstyle website in their leisure time, and do this only at office. BUT maintainers do use mobile version a lot to recheck documentation and answer question of user.

**Comment by romani** [comment]
there was extra problem in FF(see details below) and it was addressed at #7357

how it was before:
![image](https://user-images.githubusercontent.com/7516893/70549564-b67ca600-1b74-11ea-8db8-94a7616f9c44.png)
according to @rnveach there should be some space between the text of the code snippet and its border. This already works in chrome (merged in https://github.com/checkstyle/checkstyle/pull/7302) and this pr fixes that for firefox.

![image](https://user-images.githubusercontent.com/7516893/70550592-466f1f80-1b76-11ea-9d17-db29c06c4dbf.png)

**Comment by romani** [comment]
@jo2 , thanks a lot for additional fix
