### ISSUE TITLE
Travis and CircleCI have problems to use execute should_job_run

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#7317]
file .ci/common.sh contains  `should_job_run` that suppose to skip CI is changes are done only in config files of different CIs.

but there some problems with Travis and CircleCI, so it was disabled:
cirlceci - https://github.com/checkstyle/checkstyle/commit/fa88baf0853d23b46230d8ff89114d91eed28f32
travis - https://github.com/checkstyle/checkstyle/commit/3314038bdf36732c815eab08373998fc4009c227

commit messages reference PRs where such problem was detected. 

diff detection should be rewritten to use `merge-base` - https://roman-ivanov.blogspot.com/2019/11/how-to-list-all-changed-files-between.html
We should use TRAVIS environemnt variable to get PREV commit, all other CIs should not do this and do just diff on branch:HEAD and merge-base.

**Comment by romani** [comment]
Introduction of `export RUN_JOB=1` is beneficial also because when we can make it `0` for all not affected CIs when we debugging single CI.

**Comment by ahmadshabib** [comment]
Hey @romani, anyone working on this? and what is the progress since it was last created if I want to work on it?

**Comment by romani** [comment]
@ahmadshabib , nobody working on it.
It is very error prone approach to analyze diff as different CI do it differently.

You can try to tackle it, but looks like the best is to not deal with it and use RUN_JOB . And extra execution of CI is ok, not a big deal, happens rarely

**Comment by romani** [comment]
we abanodened this skip of CIs
