### ISSUE TITLE
Fix type of Checker property cacheFile

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#7339]
https://pbludov.github.io/site/config.html#Checker_Properties

The type of property `cacheFile` is `File`, which does not exist at our website documentation https://pbludov.github.io/site/property_types.html#file .
We either should change it to [URI](https://pbludov.github.io/site/property_types.html#uri) or add a new property type.

**Comment by romani** [comment]
I am hesitant to make it URI, as it should be writable file only. We can make it as string, as it is path to file, not actually a file.

**Comment by rnveach** [comment]
> The type of property cacheFile is File, which does not exist.

It does exist and is converted to File eventually, so documentation seems correct to me.
https://github.com/checkstyle/checkstyle/blob/d61dccb3c7fd391506a512dce96a2620a5f93ac3/src/main/java/com/puppycrawl/tools/checkstyle/PropertyCacheFile.java#L121

**Comment by romani** [comment]
He meant, url to property description is invalid.
We probably should add such property type to documentation

**Comment by rnveach** [comment]
I see now. Sorry.

https://checkstyle.sourceforge.io/version/7.0/config.html#Checker_Properties
Original property used to be `string` but that was incorrect/confusing as we changed properties to what they are treated as internally. This can't be a URI as that implies its read only and not modifiable by Checkstyle, like a configuration or import control.

> We probably should add such property type to documentation

I agree. We will need to add file to denote Checkstyle will modify the file.

**Comment by romani** [comment]
fix is merged.
