### ISSUE TITLE
linkcheck does not see dtd files

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#7340]
The linkcheck [report](https://checkstyle.org/linkcheck.html) shows that all `dtd` files hosted by https://checkstyle.org are missing:
![image](https://user-images.githubusercontent.com/900805/70389113-eb012e00-19cb-11ea-97f6-5853e4a85b9e.png)
Actually, the files are at the place where they should be. All such links are clickable.
Perhaps the reason is that at the time when linkcheck does it work, they are not in the `target/site` folder.

From [comment](https://github.com/checkstyle/checkstyle/pull/7351#discussion_r355740089)

> Issue will only become apparent when this PR is merged and then that site becomes an old version.

> Existing links only work if they have beginning slash. The ones without a beginning slash do not work. See https://checkstyle.sourceforge.io/version/8.26/config_imports.html#ImportControl_Description as an example from your search. Clicking on it sends user to 404.

> The reason why the beginning slash makes a difference is removing it changes the URL from a absolute path to a relative path. In base directory of https://checkstyle.sourceforge.io absolute and relative are the same. However when switching the directory we are accessing from via https://checkstyle.sourceforge.io/version/8.26/ for versions, absolute path forces us back to https://checkstyle.sourceforge.io while relative continue using https://checkstyle.sourceforge.io/version/8.26/.

> DTDs are located at https://checkstyle.sourceforge.io/dtds/import_control_1_4.dtd and not https://checkstyle.sourceforge.io/version/8.26/dtds/import_control_1_4.dtd .

**Comment by romani** [comment]
There are some maven resource plugin is responsible to copy dtds to site folder, please review pom.xml

**Comment by pbludov** [comment]
The job [copy-resources](https://github.com/checkstyle/checkstyle/blob/master/pom.xml#L663) works fine:
```
$ ls -1d target/site/*/
target/site/apidocs/
target/site/css/
target/site/dsm/
target/site/dtds/                      <=====================
target/site/files/
target/site/images/
target/site/js/
target/site/styleguides/
target/site/xref/
target/site/xref-test/
```
Something wrong with linkcheck itself:
```
$ ls -1d target/linkcheck/tmpsite/*/
target/linkcheck/tmpsite/apidocs/
target/linkcheck/tmpsite/css/
target/linkcheck/tmpsite/dsm/
target/linkcheck/tmpsite/files/
target/linkcheck/tmpsite/images/
target/linkcheck/tmpsite/jacoco/
target/linkcheck/tmpsite/js/
target/linkcheck/tmpsite/styleguides/
target/linkcheck/tmpsite/xref/
target/linkcheck/tmpsite/xref-test/
```

**Comment by pbludov** [comment]
This is due to parameter [forceSite](http://svn.apache.org/viewvc/maven/plugins/tags/maven-linkcheck-plugin-1.2/src/main/java/org/apache/maven/plugins/linkcheck/LinkcheckReport.java?view=markup#l346)

When enabled, `maven-linkcheck-plugin` invokes `maven-site-plugin` to build it's own copy of the site in the `linkcheck/tmpsite` folder.

With  `forceSite` set to `false` all DTDs are found, but `project-reports.html` and `project-info.html` files are reported as missing, because they are generated after all reports are created. We can simple exclude them.

**Comment by romani** [comment]
fix is merged.
