### ISSUE TITLE
javadoc links to non-public members 

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#7341]
Some Javadoc methods contains links to non-public fields and methods. For example:
 
https://checkstyle.org/apidocs/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheck.html#setViolateExecutionOnNonTightHtml-boolean-

![image](https://user-images.githubusercontent.com/900805/70389643-60bcc800-19d3-11ea-81c3-9eb1e3daa31e.png)

The field `violateExecutionOnNonTightHtml` is not public and is ignored by the  javadoc tool.
Such Javadoc is useless and should be rewritten.

**Comment by romani** [comment]
Ok, if there are better ways to do this

**Comment by rnveach** [comment]
@pbludov How did you find such cases and is there any way to automate it?

**Comment by romani** [comment]
@rnveach , existing plugin detected them - https://github.com/checkstyle/checkstyle/pull/7351#issuecomment-563419247 , responsible CI (codeship) is not running on PRs  as CI do not support such model, I did not put such validation to other CI as it takes significant amount of time(10-15 min) to build such report.

**Comment by pbludov** [comment]
> @pbludov How did you find such cases and is there any way to automate it?

I found them here https://checkstyle.org/linkcheck.html
Just opened the report and saw a few bugs that can clearly be fixed.

**Comment by pbludov** [comment]
> it takes significant amount of time(10-15 min) to build such report.

It can be speed up a bit by switching to the `HEAD` method instead of `GET`.
I think that `linkcheck` configured to use the `GET` method because once some ancient servers did not support `HEAD`. Today, every server should support this method. I'll give it a try.

**Comment by pbludov** [comment]
fix is merged

**Comment by romani** [comment]
I remember that that I put "get" on reason, please look at history. It helped to mind more problems in links
