### ISSUE TITLE
Update Apache Ant library used by Checkstyle

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#736]
Current state in Checkstyle's POM:
```xml
    <dependency>
      <groupId>org.apache.ant</groupId>
      <artifactId>ant</artifactId>
      <!-- Do not upgrade as this is the earliest version of ANT supported -->
      <version>1.7.0</version>
      <scope>provided</scope>
    </dependency>
```
Newest version of Apache Ant Core library is [1.9.4](http://mvnrepository.com/artifact/org.apache.ant/ant). After the change build executes fine.

Do you know the reason for comment `Do not upgrade as this is the earliest version of ANT supported`? Can I update this library regardless and remove this comment?

Also, do you know the reason it works with `<scope>provided</scope>`?

**Comment by romani** [comment]
Changes are pretty old https://github.com/checkstyle/checkstyle/commit/45cdfa7240d8a92562e46e7bedb8b8ca77d25853

It might be already ok to upgrade, we need to recheck Checkstyle Ant task - http://checkstyle.sourceforge.net/anttask.html, and also we need to make sure that content of result JAR files are the same (https://github.com/checkstyle/checkstyle/wiki/Build-all-jars-and-generate-maven-site) "mvn clean package -Passembly".

As soon as you confirm that content of distribution files is the same and ANT task works fine - we are ok to upgrade.

**Comment by mkordas** [comment]
Besides different compilation times there is just one expected difference between `checkstyle-6.5-SNAPSHOT-all` JARs.
```
--- 1.7.0/checkstyle-6.5-SNAPSHOT-all/META-INF/maven/com.puppycrawl.tools/checkstyle/pom.xml
+++ 1.9.4/checkstyle-6.5-SNAPSHOT-all/META-INF/maven/com.puppycrawl.tools/checkstyle/pom.xml
@@ -195,7 +195,7 @@
       <groupId>org.apache.ant</groupId>
       <artifactId>ant</artifactId>
       <!-- Do not upgrade as this is the earliest version of ANT supported -->
-      <version>1.7.0</version>
+      <version>1.9.4</version>
       <scope>provided</scope>
     </dependency>
```

I'm going to check ANT tasks next.

**Comment by mkordas** [comment]
Output of Ant task is identical for checkstyle codebase and default set of rules:
```
$ cmp checkstyle_report_1.7.0.xml checkstyle_report_1.9.4.xml
$ [ $? -eq 0 ] && echo 'same' || echo 'different'
same

**Comment by romani** [comment]
ok, lets do upgrade.

**Comment by romani** [comment]
will be in 6.5
