### ISSUE TITLE
Make powermock tests compatible with JDK17+

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#7368]
A spin-off for https://github.com/checkstyle/checkstyle/issues/6916

Currently, this issue is blocked by https://github.com/powermock/powermock/issues/830 and  https://github.com/junit-team/junit5/issues/201

Once done,  some Junit4 dependencies should be removed from pom.xml, including:

- [ ] junit-vintage-engine
- [ ] system-rules
- [ ] powermock-module-junit4

UPD: It is not possible to keep them. All Powermock tests should be rewritten.

**Comment by pbludov** [comment]
Status update for this issue:

The powermock issue is still unresolved and the framework itself looks abandoned. There is a reason for this.
Every release of Java since JDK9 makes it harder to access private fields and methods:
 * https://openjdk.java.net/jeps/260
 * https://openjdk.java.net/jeps/396
 * https://openjdk.java.net/jeps/403

After the release of Java17 later this year, there will no longer be semi-legal ways to access private class members.
This means that all powermock tests will be broken with no fix.

The only way we have is to completely remove powermock powered tests. We only have a dozen of them. But we don't want to lose coverage, so we need a replacement here.

To access private fields in the Checkstyle code we can add package-private gettters/setters with `@VisibleForTesting` annotation.
To mock final classes and static methods we can use [JMockit](http://jmockit.github.io/).

**Comment by romani** [comment]
>To access private fields in the Checkstyle code we can add package-private gettters/setters with VisibleForTesting annotation.

Most no desirable option, but I got will find way to cover.

**Comment by pbludov** [comment]
The good news is that Mockito framework version 4.0.0 is able to mock static classes:
https://www.baeldung.com/mockito-mock-static-methods

It fails to mock the `System` class, but works fine with other JDK classes (for example, `MessageDigest`).

**Comment by rnveach** [comment]
Closed via https://github.com/checkstyle/checkstyle/pull/10947 and Issue https://github.com/checkstyle/checkstyle/issues/10932 .

**Comment by romani** [comment]
Link check validation is not happy :)
https://github.com/checkstyle/checkstyle/runs/4586344242?check_suite_focus=true#step:3:8

**Comment by rnveach** [comment]
https://github.com/checkstyle/checkstyle/search?q=7368
https://github.com/checkstyle/checkstyle/blob/8129a4f69cf30d059ed7b34b4dca4b8118690526/pom.xml#L292-L298
