### ISSUE TITLE
CLI option '--branch-matching-xpath' is missed in html documentation

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#7396]
https://checkstyle.org/cmdline.html#Command_line_usage there are no information of `-b` option. 

```
        @Option(names = {"-b", "--branch-matching-xpath"},
            description = "Show Abstract Syntax Tree(AST) branches that match XPath")
```

feature was added at https://github.com/checkstyle/checkstyle/commit/5ed866347e51cac0a4835d93467908d2910a4b8f is scope of #6660

**Comment by romani** [comment]
@strkkk , please help to resolve this missed documentation.

**Comment by rnveach** [comment]
There was an issue to add a UT to ensure all CLI options are documented. I can't find the issue right now.

**Comment by romani** [comment]
it would be nice to have such issue and UT, please create it, let it sit in our issue tracker, one day it will be done.

**Comment by romani** [comment]
Fix is merged

**Comment by rnveach** [comment]
> please create it

There should be one already but I couldn't find it when quickly searching.

**Comment by romani** [comment]
It is completely fine to have duplicates for some time, eventually they will be linked and users will find open issue from any search

**Comment by rnveach** [comment]
Found issue https://github.com/checkstyle/checkstyle/issues/6216
