### ISSUE TITLE
Typo in violation message of ModifierOrder check

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#740]
Code:
```java
    /** Illegal order of annotation - must come first */
    private @MyAnnotation2 void someMethod2()
    {
    }
```

Current (Checkstyle 6.4.1):
'@MyAnnotation2' annotation modifier does not **preceed** non-annotation modifiers

Expected:
'@MyAnnotation2' annotation modifier does not **precede** non-annotation modifiers

**Comment by romani** [comment]
merged, will be in 6.5
