### ISSUE TITLE
MissingDeprecated check fails to parse JavaDoc tags

### ISSUE THREAD

**Issue by Pieter12345** [checkstyle/checkstyle#7414]
After updating from CheckStyle 8.18 to 8.27, the `MissingDeprecated` check gives false errors caused by failed JavaDoc parsing. A few examples are:
![afbeelding](https://user-images.githubusercontent.com/9693840/71552811-edbbd580-2a03-11ea-8a9f-a2c599f94742.png)
![afbeelding](https://user-images.githubusercontent.com/9693840/71552828-3a071580-2a04-11ea-92d3-10b611c3121c.png)
![afbeelding](https://user-images.githubusercontent.com/9693840/71552837-628f0f80-2a04-11ea-942e-ea0ff5d6c339.png)

When running `maven-checkstyle-plugin:3.1.0`, the feedback for these errors is (removed file paths):
```
[INFO] --- maven-checkstyle-plugin:3.1.0:check (checkstyle) @ JavaLoader ---
[INFO] Starting audit...
[ERROR] ...: Javadoc comment at column 24 has parse error. Details: no viable alternative at input '<some author>' while parsing HTML_ELEMENT [MissingDeprecated]
[ERROR] ...: Javadoc comment at column 0 has parse error. Details: no viable alternative at input '\t *' while parsing JAVADOC_TAG [MissingDeprecated]
[ERROR] ...: Javadoc comment at column 10 has parse error. Details: no viable alternative at input '{' while parsing JAVADOC_TAG [MissingDeprecated]
Audit done.
```

The `MissingDeprecated` check is added under the `TreeWalker` module as: `<module name="MissingDeprecated"/>`

My expectation is that the `MissingDeprecated` check does not fail to parse JavaDocs, or that it at least parses all JavaDocs it used to parse in CheckStyle version 8.18.

---------------
EDIT: Here's an example in the given issue report format.

Documentation: https://checkstyle.org/config_annotation.html#MissingDeprecated

```
javac MyClass.java

cat checkstyle.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module PUBLIC "-//Puppy Crawl//DTD Check Configuration 1.3//EN" "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name="Checker">
        <module name="TreeWalker">
                <module name="MissingDeprecated"/>
        </module>
</module>

cat MyClass.java
public class MyClass {

        /**
         * @author <some author>
         */
        public void test() {
        }

        /**
         * @return
         * @throws Exception When bla.
         */
        public String test2() {
                return null;
        }

        /**
         * Some description.
         * @see {@link #test3()}.
         */
        public void test3() {
        }
}

java -Duser.language=en -Duser.country=US -jar checkstyle-8.27-all.jar -c checkstyle.xml MyClass.java
Starting audit...
[ERROR] C:\...\MyClass.java:5: Javadoc comment at column 24 has parse error. Details: no viable alternative at input '<some author>' while parsing HTML_ELEMENT [MissingDeprecated]
[ERROR] C:\...\MyClass.java:12: Javadoc comment at column 0 has parse error. Details: no viable alternative at input '\t *' while parsing JAVADOC_TAG [MissingDeprecated]
[ERROR] C:\...\MyClass.java:20: Javadoc comment at column 10 has parse error. Details: no viable alternative at input '{' while parsing JAVADOC_TAG [MissingDeprecated]
Audit done.
Checkstyle ends with 3 errors.
```

**Comment by romani** [comment]
Welcome at right place.
And now please strictly follow issue template.

**Comment by rnveach** [comment]
Most likely this issue came from https://github.com/checkstyle/checkstyle/issues/4983 . We switched from using regexp parser to javadoc parser. The javadoc parser is more reliable, but it is stricter on the javadocs it recognizes. You should get similar exceptions on other checks using the javadoc parser like AtclauseOrderCheck, regardless of version you specify.

**Comment by Pieter12345** [comment]
@rnveach That sounds likely indeed. However, there's a difference between being 'more strict' and only supporting a subset of what common IDE's support. In this case, it's the latter. I believe a reasonal solution would be to fall back to the old parser when the incomplete new parser fails to parse a JavaDoc section. This could be enabled/disabled through some new property in modules that use it.

**Comment by romani** [comment]
@Pieter12345 , please report issue as required and you will find solution yourself.

**Comment by Pieter12345** [comment]
@romani, I've updated the issue with the requested format. Is this okay?

**Comment by romani** [comment]
In issue template, there is request to share link to documentation, please do.
To make sure you read it before opening issue

**Comment by Pieter12345** [comment]
@romani Updated the issue again, included the link to the documentation.

**Comment by romani** [comment]
property `<property name="violateExecutionOnNonTightHtml" value="false"/>` does not work as problem is not with HTML.

Javadoc is wrong by structure ... not parse-able. All violations are valid.

Checkstyle tool have a limitation to work only on compe-lable java sources, the same is rule for javadoc comments (but there is nuance that there is no strict grammar for javadoc, javadoc tool from jdk full of bugs and ....., so we take some objective decisions on what is right in javadoc) 

fixed javadoc (no errors during parsing):
```
class MyClass {
        /**
         * @author some author
         */
        public void test() {
        }

        /**
         * @return null
         * @throws Exception When bla.
         */
        public String test2() {
                return null;
        }

        /**
         * Some description.
         * @see Test {@link #test3()}.
         */
        public void test3() {
        }
}
```

if you do not want to fix javadoc syntax violations you can suppress them (but beware that Check will not raise any other violation on such javadoc):
```
$ cat config.xml 
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module PUBLIC "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
                        "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name="Checker">
  <module name="TreeWalker">
    <module name="MissingDeprecated">
      <property name="violateExecutionOnNonTightHtml" value="false"/>
    </module>
    <!-- usuppress javadoc parsing errors, as we test Check not a parser -->
    <module name="SuppressionXpathSingleFilter">
        <property name="message" value="Javadoc comment at column \d+ has parse error"/>
    </module>
  </module>
</module>

$ cat MyClass.java
class Test {
        /**
         * @author <some author>
         */
        public void test() {
        }

        /**
         * @return
         * @throws Exception When bla.
         */
        public String test2() {
                return null;
        }

        /**
         * Some description.
         * @see {@link #test3()}.
         */
        public void test3() {
        }

}

$ java -jar /var/tmp/checkstyle-8.27-all.jar -c config.xml MyClass.java 
Starting audit...
Audit done.
```

**Summary:** 
If you care to write javadocs, please do this properly. We are completely aware that writing correct javadoc is hard, please be patient, read article around - https://docs.oracle.com/javase/8/docs/technotes/tools/windows/javadoc.html to get a syntax. If you give checkstyle parse-able javadoc, checkstyle will do most boring job and guide you what should be improved in it further. 
If too much efforts .... use suppression or disable Check.
