### ISSUE TITLE
Contributors section on Project Team page in docs is unfinished

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#742]
Contributors section on [Project Team](http://checkstyle.sourceforge.net/team-list.html) page looks unfinished.

My proposition is to either delete it or put the link to [contributors](https://github.com/checkstyle/checkstyle/graphs/contributors) list generated by Github. Any other ideas?

**Comment by romani** [comment]
I do not know how to add link to that list, dues to maven site schema itis not possible .

Do you have suggestions ?

I thought about fake table line with link as text to github - but that is ugly to my mind.

**Comment by romani** [comment]
@mkordas , any new ideas , if not please close the issue

**Comment by mkordas** [comment]
What do you think about this solution?

![image](https://cloud.githubusercontent.com/assets/5467276/6647141/8c357a84-c9cb-11e4-86a8-635c53e4b27c.png)

**Comment by romani** [comment]
good , lets do that.

**Comment by romani** [comment]
fixed, will be in 6.5
