### ISSUE TITLE
CustomImportOrder warning seems incorrect

### ISSUE THREAD

**Issue by RohanNagar** [checkstyle/checkstyle#7425]
In Checkstyle 8.27 the following works fine.

Config:
```xml
<module name="CustomImportOrder">
      <property name="sortImportsInGroupAlphabetically" value="true"/>
      <property name="separateLineBetweenGroups" value="true"/>
      <property name="customImportOrderRules" value="THIRD_PARTY_PACKAGE###STATIC"/>
</module>
```

Imports:
```java
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.Objects;
import java.util.StringJoiner;
```

---------------

I expect this to work the same in 8.28, but I get the following error:

```
[WARNING] src/main/java/com/sanctionco/thunder/models/Email.java:[6] (imports)
CustomImportOrder: Extra separation in import group before 'java.util.Objects'
```

---------------

Can anyone advise what changed in 8.28?

**Comment by rnveach** [comment]
> Can anyone advise what changed in 8.28?

Our release notes details what changed in each version.
https://checkstyle.org/releasenotes.html#Release_8.28

**Comment by RohanNagar** [comment]
Yes I've read them but I don't see how those changes would have affected this particular example.

**Comment by romani** [comment]
You have two groups in customImportOrderRules - all simple imports and then static imports.
No extra separation is allowed in group, so empty line is allowed only between simple imports and static imports.

**Comment by RohanNagar** [comment]
Thanks @romani. I'm having trouble figuring out how to configure it the way I am expecting. I'm looking at the documentation but would appreciate any guidance you can give.

I have the following config and code:

```xml
<module name="CustomImportOrder">
  <property name="sortImportsInGroupAlphabetically" value="true"/>
  <property name="separateLineBetweenGroups" value="true"/>
  <property name="customImportOrderRules" value="STANDARD_JAVA_PACKAGE###SAME_PACKAGE(1)###THIRD_PARTY_PACKAGE###STATIC"/>
</module>
```


```java
import java.util.Arrays;
import java.util.Collections;
import java.util.Map;
import java.util.StringJoiner;
import java.util.TreeMap;

import com.fasterxml.jackson.databind.ObjectMapper;

import io.dropwizard.jackson.Jackson;
import io.dropwizard.testing.FixtureHelpers;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertAll;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;
```

I expect this to work, but I get the following error:

```
[WARNING] src/test/java/com/sanctionco/thunder/models/UserTest.java:[14] (imports)
CustomImportOrder: Extra separation in import group before 'org.junit.jupiter.api.BeforeAll'
```

Why does it think there is extra separation? I expect that the `java` imports match with `STANDARD_JAVA_PACKAGE`. Then the `com`, `io`, and `org` imports match with the `SAME_PACKAGE(1)` groups. And finally the static imports match `STATIC`. I want separation between each group that is different after the first domain in the package name. How can I make this happen?

**Comment by romani** [comment]
> Then the com, io, and org imports match with the SAME_PACKAGE(1) groups.

for `com/sanctionco/thunder/models/UserTest.java`
SAME_PACKAGE(1)  is `com`.

You need to do special group for each `com`, `io`, `org` , that is not possible by such Check - https://checkstyle.org/config_imports.html#CustomImportOrder that is more for google style import order (no extra spaces in groups).

if you need extra separation please consider to use - https://checkstyle.org/config_imports.html#ImportOrder

**Comment by RohanNagar** [comment]
Ah this is what I needed. Thank you for all your help, I should be able to figure it out from here.

**Comment by romani** [comment]
@RohanNagar , please share config that worked for you, it will be useful for other users.

**Comment by RohanNagar** [comment]
I will reply here with the config early next week - am on holiday right now. Thanks!

**Comment by RohanNagar** [comment]
Here is the config I used:

```xml
<module name="ImportOrder">
  <property name="groups" value="*,com,dagger,io,java,javax,okhttp3,org,retrofit2,software"/>
  <property name="ordered" value="true"/>
  <property name="separated" value="true"/>
  <property name="option" value="bottom"/>
  <property name="sortStaticImportsAlphabetically" value="true"/>
</module>
```

This allows me to do the below (separation between each defined group in the order specified). I wasn't sure if there was a way to have it automatically find groups based on the first domain being unique, but adding a group if I have a new unique first domain will work for me.

```java
import com.fasterxml.jackson.databind.ObjectMapper;

import io.dropwizard.jackson.Jackson;
import io.dropwizard.testing.FixtureHelpers;

import java.util.Arrays;
import java.util.Collections;
import java.util.Map;
import java.util.StringJoiner;
import java.util.TreeMap;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertAll;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;
```
