### ISSUE TITLE
Add email addresses to post new topics on Project Mailing Lists page in docs

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#743]
On [Project Mailing Lists](http://checkstyle.sourceforge.net/mail-lists.html) page column 'Post' is empty. 

We should fill it with addresses of our mailing lists, e.g. checkstyle-devel@googlegroups.com for checkstyle-devel.

**Comment by romani** [comment]
we could make it like http://maven.apache.org/plugins/maven-linkcheck-plugin/mail-lists.html

**Comment by romani** [comment]
will be in 6.5
