### ISSUE TITLE
Suppression by custom annotations in Java

### ISSUE THREAD

**Issue by anddero** [checkstyle/checkstyle#7432]
### Short description

Instead of adding a `@SuppressWarnings` annotation, a possibility to suppress the warning using a custom annotation specified in the configuration file.

### Long description

There are already several checks (e.g. `JavadocMethod`) which can be suppressed by using a certain annotation if listed in the module's property `allowedAnnotations`.

There are also several checks (e.g. `ParameterNumber`) that *do not* have this type of suppression possibility. *For example, it could be helpful in Spring projects to suppress the parameter number warning in case of an `@Autowired` annotated constructor, because Spring beans tend to have many dependencies.*

How about generalizing the `allowedAnnotations` concept to allow user defined annotation-suppression lists for *any* check?

## Current Behavior

To suppress `ParameterNumber` checks on an `@Autowired` annotated constructor, you would currently do:

```java
@SuppressWarnings("checkstyle:ParameterNumber")
@Autowired
public BankHandler() {
}
```

for every such constructor of the entire project.

## Expected Behavior

Avoid having to pollute all bean constructors with the `@SuppressWarnings` annotation by specifying a block such as the following in your Checkstyle config:

```xml
<module name="SuppressionByAnnotationFilter">
    <property
        name="aliasList"
        value="ParameterNumber=Autowired"
    />
</module>
```

where `value` is a String Set in a format of comma separated attribute=value entries. The attribute is the fully qualified name of the Check and value is its alias as an annotation. *Basically, an extension to [SuppressWarningsHolder](https://checkstyle.sourceforge.io/config_annotation.html#SuppressWarningsHolder), where you can have a custom annotation in addition to custom `@SuppressWarnings` arguments.*

**Comment by romani** [comment]
Can you fix your issue by usage of https://checkstyle.org/config_filters.html#SuppressionXpathSingleFilter ? Just tune xpath expression to detect annotation you need.

**Comment by anddero** [comment]
I have tried `//METHOD_DEF[..//ANNOTATION[@text='Autowired']]` but it does not seem to work. I am not a wizard with the Xpath queries.

**Comment by anddero** [comment]
According to the docs, annotation is a type of modifier, so I have tried `//CTOR_DEF[.//ANNOTATION[@text='Autowired']]` and many other options but none work for me.

**Comment by anddero** [comment]
Okay, there must be another issue other than the Xpath query, because even `//CTOR_DEF` does not suppress `ParameterNumber`. My suppressions look like this:

```xml
<suppressions>
    <suppress-xpath
            checks="ParameterNumber"
            query="//CTOR_DEF"
    />
</suppressions>
```

**Comment by rnveach** [comment]
@anddero for XPath, I recommend starting with our automated suppression generation for xpath.
https://checkstyle.org/cmdline.html#Command_line_usage
> -g,--generate-xpath-suppression - generate to output a suppression xml to use to suppress all violations from user's config.

It allowed me to generate the following example:
````
$ cat TestClass.java
public class TestClass {
  @Autowired
  public void needsLotsOfParameters(int a,
    int b, int c, int d, int e, int f, int g, int h) {
  }
}

$ cat TestConfig.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>

    <module name="TreeWalker">
<module name="ParameterNumber"/>

<module name="SuppressionXpathSingleFilter">
  <property name="query" value="/CLASS_DEF[./IDENT[@text='TestClass']]/OBJBLOCK/METHOD_DEF/IDENT[@text='needsLotsOfParameters']"/>
</module>
    </module>
</module>

$ java -jar checkstyle-8.28-all.jar -c TestConfig.xml TestClass.java
Starting audit...
Audit done.
````

Please note `METHOD_DEF/IDENT[@text='needsLotsOfParameters']` in the query. The violation is on the IDENT node, so the xpath query has to select that node otherwise it won't suppress the violation.

I then used the tree structure to append your annotation find and this was my final result:
````
$ cat TestClass.java
public class TestClass {
  @Autowired
  public void needsLotsOfParameters(int a,
    int b, int c, int d, int e, int f, int g, int h) {
  }
}

$ cat TestConfig.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>

    <module name="TreeWalker">
<module name="ParameterNumber"/>

<module name="SuppressionXpathSingleFilter">
  <property name="query" value="//METHOD_DEF/IDENT[../MODIFIERS/ANNOTATION/IDENT[@text='Autowired']]"/>
</module>
    </module>
</module>

$ java -jar checkstyle-8.28-all.jar -c TestConfig.xml TestClass.java
Starting audit...
Audit done.
````

**Comment by romani** [comment]
I am closing issue for now, discussion can be continued.
