### ISSUE TITLE
Avoid using Locale.setDefault in tests

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#7436]
Part of migration to Junit5 process https://github.com/checkstyle/checkstyle/issues/6916
Blocker for parallel execution of all unit tests.

By enabling parallel execution of unit tests, they start to fail in random places with messages like this:
```
[ERROR]   AnnotationLocationCheckTest.testAnnotation:204->AbstractModuleTestSupport.verify:220->AbstractModuleTestSupport.verify:256->AbstractModuleTestSupport.verify:292 error message 0 expected:<...Annotation.java:17: [Annotation 'AnnotationAnnotation' have incorrect indentation level 2, expected level should be 0].> but was:<...Annotation.java:17: [Die Annotation 'AnnotationAnnotation' hat eine unerwartete Einrückungstiefe von 2 (erwartet: 0)].>
```
This happens when a test does  `Locale.setDefault(...)`, which affects all other tests running at the same time. To avoid such failure, all unit tests shouldn't alter the global system state.
Instead, the Junit 5 extension [DefaultLocale](https://junit-pioneer.org/docs/default-locale-timezone/) should be used to trick `LocalizedMessage` to load locale-specific message.

**Comment by rnveach** [comment]
We should configure a new `ForbidCertainMethodCheck` from sevntu to forbid the method.

**Comment by romani** [comment]
@pbludov , do you think we will succeed to make MT execution on tests if main code is not ready for MT ?

**Comment by pbludov** [comment]
> What about when we do modifications to other classes?
> do you think we will succeed to make MT execution on tests if main code is not ready for MT ?

I'm actually trying to figure out how ready it is. Definitely, all tests that change static fields or global state are incompatible with parallel execution. For example, `LocalizedMessage` has static field [sLocale](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/LocalizedMessage.java#L64). And modification of this field in a test affects all check tests running concurrently the same way as `Locale.setDefault(...)` does.
But we only need to set this field when initializing. It is necessary that the initialization of this class does not overlap with its use.

The Junit5 documentation recommends using `ResourceLock` annotation to solve this problem.
```java
@ResourceLock(value = "global state", mode = ResourceAccessMode.READ_WRITE)
public class LocalizedMessageTest {
  // ... It is safe to modify sLocale here
}
```
For all check tests:
```java
@ResourceLock(value = "global state", mode = ResourceAccessMode.READ)
public class SomeCheckTest {
  // ... LocalizedMessage.sLocale won't be changed
}
```

I'm going to check this out by splitting all tests into the two sets: one for all checks, another for the Checkstyle internals. All check tests should be able to execute in parallel.

**Comment by pbludov** [comment]
> We should configure a new `ForbidCertainMethodCheck` from sevntu to forbid the method.

done

**Comment by pbludov** [comment]
fix is merged.
