### ISSUE TITLE
Fix PMD violations in Checkstyle

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#744]
According to [Checkstyle GSoC 2015 Project Ideas](https://github.com/checkstyle/checkstyle/wiki/Checkstyle-GSoC-2015-Project-Ideas#project-name-practice-what-you-preach) we need to fix all [violations](http://checkstyle.sourceforge.net/pmd.html).

Current status:
`Failed to execute goal org.apache.maven.plugins:maven-pmd-plugin:3.4:check (default-cli) on project checkstyle: You have 736 PMD violations.`

!!!Attention!!!:  we should NOT blindly follow PMD recommendation, we are ok to put suppressions or skip some violations (after discussion).

**Comment by romani** [comment]
@mkordas, now you have right to assign tasks, please use it if you want to let other know that you are going to resovle issue.

**Comment by mkordas** [comment]
@romani, apparently I don't have such permissions yet. Right now I can assign myself to issues only in my personal projects.

**Comment by romani** [comment]
Hmm, ok i will do it for you, at least i can do that now.
Please put a comment on issue and will do assign to you.

**Comment by mkordas** [comment]
OK, thanks for assigning to this one.

**Comment by mkordas** [comment]
@romani, [here](https://help.github.com/articles/permission-levels-for-an-organization-repository/#repository-access-teams) is nice summary of permissions. Members of read access teams unfortunately cannot assign issues.

**Comment by romani** [comment]
I do not trust you enough to give you write permissions to sources, lets work now only with read permission.

**Comment by mkordas** [comment]
> !!!Attention!!!: we should blindly follow PMD recommendation, we are ok to put suppressions or skip some violations (after discussion).

@romani, what do you mean by that? I guess you wanted to write _we should NOT blindly follow PMD recommendation_.

**Comment by romani** [comment]
yes, we "should NOT".

**Comment by romani** [comment]
@mkordas, I enforced pmd:check into verify stage, please split that issue into several for each ruleset, to let other contributors help with that issue.

**Comment by mkordas** [comment]
@romani - I've created issues for less controversial rulesets which should be reasonably easy to fix. In #878 I've enabled rulesets without any violations for the time being.

What do you think about binding PMD do compile phase instead of verify to get fast feedback during the build?

**Comment by romani** [comment]
@mkordas, can we close that issue? general preparations for PMD enforcement is done

**Comment by mkordas** [comment]
There are couple more general preparations still to be done - like extracting config from POM to separate file and breaking down more complicated rulesets into exclusions and issues per rule, not per ruleset.

**Comment by romani** [comment]
> file and breaking down more complicated rulesets into exclusions and issues per rule, not per ruleset.

that should be done during specific issue "Fix PMD violations from ...".
Please do not put to much in one issue, it is never work fine.

**Comment by romani** [comment]
@mkordas , i will try to resolve size group http://pmd.sourceforge.net/pmd-4.3.0/rules/codesize.html

**Comment by romani** [comment]
@mkordas , am going from top to bottom in rules resolving, please go from bottom to top to avoid conflicts

**Comment by romani** [comment]
that issue was resolved and split into few separate issues: https://github.com/checkstyle/checkstyle/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+PMD
