### ISSUE TITLE
Checks summary page is not in sync with javadoc summary 

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#7446]
identified at https://github.com/checkstyle/eclipse-cs/pull/199#pullrequestreview-339235374
for NoArrayTrailingComma

https://checkstyle.org/checks.html
> Checks if array initialization does not contain a trailing comma.

https://checkstyle.org/config_coding.html#NoArrayTrailingComma
> Checks that array initialization do not contain a trailing comma.

It will be good to verify that checks.html have same value from javadoc summary sentence.

**Comment by pbludov** [comment]
List of inconsistent summaries:

BooleanExpressionComplexity
Restricts nested boolean operators (&&, ||, &, | and ^) to a specified depth (default = 3).
Restrict the number of &&, ||, &, | and ^ in an expression.

JavaNCSS
This check calculates the Non Commenting Source Statements (NCSS) metric for Java source files and methods.
Determines complexity of methods, classes and files by counting the Non Commenting Source Statements (NCSS).

NPathComplexity
Checks the npath complexity against a specified limit (default = 200).
Checks the NPATH complexity against a specified limit.

DesignForExtension
Checks that classes are designed for inheritance.
The check finds classes that are designed for extension (subclass creation).

FinalClass
Checks that class which has only private constructors is declared as final.
Checks that a class which has only private constructors is declared as final.

HideUtilityClassConstructor
Make sure that utility classes (classes that contain only static methods) do not have a public constructor.
Makes sure that utility classes (classes that contain only static methods or fields in their API) do not have a public constructor.

InnerTypeLast
Check nested (internal) classes/interfaces are declared at the bottom of the class after all method and field declarations.
Check nested (inner) classes/interfaces are declared at the bottom of the class after all method and field declarations.

InterfaceIsType
Implements Bloch, Effective Java, Item 17 - Use Interfaces only to define types.
Implements Joshua Bloch, Effective Java, Item 17 - Use Interfaces only to define types.

MutableException
Ensures that exceptions (defined as any class name conforming to some regular expression) are immutable.
Ensures that exception classes (classes with names conforming to some regular expression and explicitly extending classes with names conforming to other regular expression) are immutable, that is, that they have only final fields.

OneTopLevelClass
Checks that each top-level class, interfaces or enum resides in a source file of its own.
Checks that each top-level class, interface or enum resides in a source file of its own.

ThrowsCount
Restricts throws statements to a specified count (default = 4).
Restricts throws statements to a specified count (4 by default).

AtclauseOrder
Checks the order of at-clauses.
Checks the order of javadoc block-tags or javadoc tags.

JavadocBlockTagLocation
Checks that a javadoc block tag appears only at the beginning of a line.
Checks that a javadoc block tag appears only at the beginning of a line, ignoring leading asterisks and white space.

JavadocPackage
Checks that all packages have a package documentation.
Checks that each Java package has a Javadoc file used for commenting.

JavadocParagraph
Checks Javadoc paragraphs.
Checks the Javadoc paragraph.

JavadocStyle
Custom Checkstyle Check to validate Javadoc.
Validates Javadoc comments to help ensure they are well formed.

JavadocType
Checks the Javadoc of a type.
Checks Javadoc comments for class and interface definitions.

JavadocVariable
Checks that a variable has Javadoc comment.
Checks that variables have Javadoc comments.

NonEmptyAtclauseDescription
Checks that the at-clause tag is followed by description .
Checks that the at-clause tag is followed by description.

SingleLineJavadoc
Checks that a JavaDoc block which can fit on a single line and doesn't contain at-clauses
Checks that a Javadoc block can fit in a single line and doesn't contain at-clauses.

WriteTag
Outputs a JavaDoc tag as information.
Requires user defined Javadoc tag to be present in Javadoc comment with defined format.

AbbreviationAsWordInName
The Check validate abbreviations(consecutive capital letters) length in identifier name, it also allow in enforce camel case naming.
The Check validate abbreviations(consecutive capital letters) length in identifier name, it also allows to enforce camel case naming.

MethodTypeParameterName
Checks that class type parameter names conform to a format specified by the format property.
Checks that method type parameter names conform to a format specified by the format property.

ParameterName
Checks that parameter names conform to a format specified by the format property.
Checks that method parameter names conform to a format specified by the format property.

StaticVariableName
Checks that static, non-final variable names conform to a format specified by the format property.
Checks that {@code static}, non-{@code final} variable names conform to a format specified by the format property.

TypeName
Checks that type names conform to a format specified by the format property.
Checks that type names for classes, interfaces, enums, and annotations conform to a format specified by the format property.

MissingDeprecated
This class is used to verify that both the java.lang.Deprecated annotation is present and the @deprecated Javadoc tag is present when either is present.
Verifies that both the @Deprecated annotation is present and the @deprecated javadoc tag are present when either one is present.

MissingOverride
This class is used to verify that the java.lang.Override annotation is present when the {@inheritDoc} javadoc tag is present.
Verifies that the @Override annotation is present when the @inheritDoc javadoc tag is present.

SuppressWarnings
This check allows you to specify what warnings that
This check allows you to specify what warnings that @SuppressWarnings is not allowed to suppress.

SuppressWarningsHolder
Maintains a set of check suppressions from SuppressWarnings annotations.
Maintains a set of check suppressions from @SuppressWarnings annotations.

EmptyForInitializerPad
Checks the padding of an empty for initializer; that is whether a space is required at an empty for initializer, or such spaces are forbidden.
Checks the padding of an empty for initializer; that is whether white space is required at an empty for initializer, or such white space is forbidden.

EmptyForIteratorPad
Checks the padding of an empty for iterator; that is whether a space is required at an empty for iterator, or such spaces are forbidden.
Checks the padding of an empty for iterator; that is whether a white space is required at an empty for iterator, or such white spaces are forbidden.

EmptyLineSeparator
Checks for blank line separators.
Checks for empty line separators after header, package, all import declarations, fields, constructors, methods, nested classes, static initializers and instance initializers.

FileTabCharacter
Checks to see if a file contains a tab character.
Checks that there are no tab characters ('\t') in the source code.

GenericWhitespace
Checks that the whitespace around the Generic tokens &lt; and &gt; are correct to the typical convention.
Checks that the whitespace around the Generic tokens (angle brackets) "&lt;" and "&gt;" are correct to the typical convention.

OperatorWrap
Checks line wrapping for operators.
Checks the policy on how to wrap lines on operators.

ParenPad
Checks the padding of parentheses; that is whether a space is required after a left parenthesis and before a right parenthesis, or such spaces are forbidden, with the exception that it does not check for padding of the right parenthesis at an empty for iterator.
Checks the policy on the padding of parentheses; i.e.

TypecastParenPad
Checks the padding of parentheses for typecasts.
Checks the policy on the padding of parentheses for typecasts.

ArrayTrailingComma
Checks if array initialization contains optional trailing comma.
Checks that array initialization contains a trailing comma.

CovariantEquals
Checks that if a class defines a covariant method equals, then it defines method equals(java.lang.Object).
Checks that classes which define a covariant equals() method also override method equals(Object).

DeclarationOrder
Checks that the parts of a class or interface declaration appear in the order suggested by the Code Conventions for the Java Programming Language.
Checks the order in which parts of the class or interface declaration are defined.

EmptyStatement
Detects empty statements (standalone ';').
Detects empty statements (standalone {@code ";"} semicolon).

EqualsHashCode
Checks that classes that override equals() also override hashCode().
Checks that classes that either override equals() or hashCode() also overrides the other.

ExplicitInitialization
Checks if any class or object member explicitly initialized to default for its type value (null for object references, zero for numeric types and char and false for boolean.
Checks if any class or object member is explicitly initialized to default for its type value (null for object references, zero for numeric types and char and false for boolean.

FallThrough
Checks for fall through in switch statements Finds locations where a case contains Java code - but lacks a break, return, throw or continue statement.
Checks for fall-through in switch statements.

FinalLocalVariable
Ensures that local variables that never get their values changed, must be declared final.
Checks that local variables that never have their values changed are declared final.

IllegalCatch
Catching java.lang.Exception, java.lang.Error or java.lang.RuntimeException is almost never acceptable.
Checks that certain exception types do not appear in a catch statement.

IllegalThrows
Throwing java.lang.Error or java.lang.RuntimeException is almost never acceptable.
This check can be used to ensure that types are not declared to be thrown.

IllegalTokenText
Checks for illegal token text.
Checks specified tokens text for matching an illegal pattern from format property.

MagicNumber
Checks for magic numbers.
Checks that there are no "magic numbers" where a magic number is a numeric literal that is not defined as a constant.

MissingCtor
Checks that classes (except abstract one) define a ctor and don't rely on the default one.
Checks that classes (except abstract ones) define a constructor and don't rely on the default one.

MissingSwitchDefault
Checks that switch statement has "default" clause.
Checks that switch statement has a "default" clause.

NestedTryDepth
Restricts nested try-catch-finally blocks to a specified depth (default = 1).
Restricts nested try blocks to a specified depth (default = 1).

NoArrayTrailingComma
Checks if array initialization does not contain a trailing comma.
Checks that array initialization do not contain a trailing comma.

NoFinalizer
Checks that no method having zero parameters is defined using the name finalize.
Verifies there are no finalize() methods defined in a class.

PackageDeclaration
Ensures there is a package declaration and (optionally) in the correct directory.
Ensures that a class has a package declaration, and (optionally) whether the package name matches the directory name for the source file.

ParameterAssignment
Disallow assignment of parameters.
Disallows assignment of parameters.

RequireThis
Checks that code doesn't rely on the "this" default.
Checks that references to instance variables and methods of the present object are explicitly of the form "this.varName" or "this.methodName(args)" and that those references don't rely on the default behavior when "this." is absent.

ReturnCount
Restricts return statements to a specified count (default = 2).
Restricts the number of return statements in methods, constructors and lambda expressions (2 by default).

SimplifyBooleanExpression
Checks for overly complicated boolean expressions.
Checks for over-complicated boolean expressions.

SimplifyBooleanReturn
Checks for overly complicated boolean return statements.
Checks for over-complicated boolean return statements.

ExecutableStatementCount
Restricts the number of executable statements to a specified limit (default = 30).
Restricts the number of executable statements to a specified limit.

MethodLength
Checks for long methods.
Checks for long methods and constructors.

OuterTypeNumber
Checks for the number of defined types at the "outer" level.
Checks for the number of types declared at the outer (or root) level in a file.

ParameterNumber
Checks the number of parameters that a method or constructor has.
Checks the number of parameters of a method or constructor.

AvoidNestedBlocks
Finds nested blocks.
Finds nested blocks, i.e.

EmptyBlock
Checks for empty blocks but does not validate sequential blocks.
Checks for empty blocks.

EmptyCatchBlock
Checks for empty catch blocks with few options to skip violation.
Checks for empty catch blocks.

LeftCurly
Checks the placement of left curly braces on types, methods and other blocks:
Checks for the placement of left curly braces ('{') for code blocks.

RightCurly
Checks the placement of right curly braces.
Checks the placement of right curly braces ('}') for if-else, try-catch-finally blocks, while-loops, for-loops, method definitions, class definitions, constructor definitions, instance, static initialization blocks, annotation definitions and enum definitions.

AvoidEscapedUnicodeCharacters
Restrict using Unicode escapes.
Restrict using Unicode escapes (such as \u221e).

FinalParameters
Check that method/constructor/catch/foreach parameters are final.
Check that parameters for methods, constructors, catch and for-each blocks are final.

Indentation
Checks correct indentation of Java Code.
Checks correct indentation of Java code.

NewlineAtEndOfFile
Checks that there is a newline at the end of each file.
Checks whether files end with a line separator.

TodoComment
A check for TODO comments.
A check for TODO: comments.

Translation
The TranslationCheck class helps to ensure the correct translation of code by checking property files for consistency regarding their keys.
A FileSetCheck that ensures the correct translation of code by checking property files for consistency regarding their keys.

UncommentedMain
Detects uncommented main methods.
Checks for uncommented main() methods.

UniqueProperties
Detects duplicated keys in properties files.
Checks properties files for duplicate property keys.

ClassMemberImpliedModifier
Checks for implicit modifiers on class members and nested types.
Checks for implicit modifiers on nested types in classes.

ModifierOrder
Checks that the order of modifiers conforms to the suggestions in the Java Language specification, sections 8.1.1, 8.3.1 and 8.4.3.
Checks that the order of modifiers conforms to the suggestions in the Java Language specification, § 8.1.1, 8.3.1, 8.4.3 and 9.4.

RedundantModifier
Checks for redundant modifiers in interface and annotation definitions, final modifier on methods of final classes, inner interface declarations that are declared as static, non public class constructors and enum constructors, nested enum definitions that are declared as static.
Checks for redundant modifiers.

AvoidStarImport
Check that finds import statements that use the * notation.
Checks that there are no import statements that use the * notation.

AvoidStaticImport
Check that finds static imports.
Checks that there are no static import statements.

ImportControl
Check that controls what can be imported in each package and file.
Controls what can be imported in each package and file.

ImportOrder
Ensures that groups of imports come in a specific order.
Checks the ordering/grouping of imports.

RedundantImport
Checks for imports that are redundant.
Checks for redundant import statements.

Header
Checks the header of the source against a fixed header file.
Checks that a source file begins with a specified header.

RegexpHeader
Checks the header of the source against a header file that contains a
Checks the header of a source file against a header that contains a regular expression for each line of the source header.

Regexp
A check that makes sure that a specified pattern exists (or not) in the file.
A check that makes sure that a specified pattern exists, exists less than a set number of times, or does not exist in the file.

RegexpMultiline
Implementation of a check that looks that matches across multiple lines in any file type.
A check for detecting that matches across multiple lines.

RegexpOnFilename
Implementation of a check that matches based on file and/or folder path.
Implementation of a check that looks for a file name and/or path match (or mis-match) against specified patterns.

RegexpSingleline
Implementation of a check that looks for a single line in any file type.
A check for detecting single lines that match a supplied regular expression.

RegexpSinglelineJava
Implementation of a check that looks for a single line in Java files.
A check for detecting single lines that match a supplied regular expression in Java files.

**Comment by rnveach** [comment]
Because of all the inconsistencies, I think it is very much needed we need a test to keep them in sync as part of this issue. We would need a way to identify the summary and compare it to the same one in https://checkstyle.org/checks.html .

If the summary is always the first sentence, we can always find the first period in the xdoc or javadoc (we have some javadoc checks that do this already). Otherwise, we could add some special tag to denote summary if all our validations allow it. Ex: `<summary>Blah. Blah. Blah.</summary>`

**Comment by romani** [comment]
I think in almost all cases we should use sentence from javadoc (as it is in sync with xdoc already) and we already reviewed all of them.

**Comment by romani** [comment]
fix is merged.
