### ISSUE TITLE
Sonar violation: "ThreadLocal" variables should be cleaned up when no longer used

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#7458]
https://sonarcloud.io/project/issues?id=org.checkstyle%3Acheckstyle&resolved=false&rules=java%3AS5164&types=BUG

such code it is resulted in incomplete Multithreading implementation.
Violation looks valid.

Should we update code with execution of `remove` ? or remove ThreadLocal ? Or mark this as "Won't fix" ?

**Comment by romani** [comment]
@rnveach , @strkkk , @pbludov , please share your ideas on this issue ?

**Comment by rnveach** [comment]
> Should we update code with execution of remove

Yes.

**Comment by pbludov** [comment]
To remove value for a `ThreadLocal` variable we need to implement some sort of lifecycle for checks.

Please remind me how it was planned to implement multi-thread checks? With one check instance shared between many threads or by cloning of checks so each thread will get its own copy?

**Comment by romani** [comment]
We can put it in 
https://github.com/checkstyle/checkstyle/blob/60b8e2e61c2ba42f2f9af06dd947bce4ce15daf5/src/main/java/com/puppycrawl/tools/checkstyle/api/AbstractCheck.java#L124-L129
Just to make Sonar happy.

>  With one check instance shared between many threads or by cloning of checks so each thread will get its own copy?

I am against complicating Checks logic with any MT details. Sharing a state is always problematic. The best design for MT - never share a state. So users who create Check just make logic implementation, mark it as Stateless in annotation, and all MT details are completely hidden.
And here we come to disagreement with @rnveach  .... and never had time to seat together for awhile and discuss, I might not even see some problems that will not make it happen.

The only known issue is Multi-file Checks (Translation Check the only instance we know), we do not support multifile, and we do in the same time, even our API abiities for this is very weird (it is hack). My approach will force such Checks to be completely separate execution, I try drop them from completely from MT mode but it will be potential rescaning-reparsing of all files, this is what @rnveach  do not like.

**Comment by rnveach** [comment]
Fix was merged

**Comment by romani** [comment]
@rnveach , please define label
