### ISSUE TITLE
Sonar violation: Null pointers should not be dereferenced

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#7459]
https://sonarcloud.io/project/issues?id=org.checkstyle%3Acheckstyle&resolved=false&rules=java%3AS2259&types=BUG

I am not sure we are ready to update code with `Nonnull` annotations. We might come back to this later on.
I propose to mark all issues as "Won't fix".
Please vote

**Comment by romani** [comment]
@rnveach , @strkkk , @pbludov , please share your ideas on this issue ?

**Comment by rnveach** [comment]
> I propose to mark all issues as "Won't fix".

Won't this come back for other cases like in PRs? Or can we just disable the check completely until we are ready?

**Comment by romani** [comment]
We can not disable any rule, sonar do validation in "Sonar way" (actual name of profile :) ), so we will need to mark them "Wont fix" each time it appear again in new code. 

The same problem we will have with "Add at least one assertion to this test case." (102 cases) - https://sonarcloud.io/project/issues?id=org.checkstyle%3Acheckstyle&resolved=false&rules=java%3AS2699&types=CODE_SMELL , i do not see any way to suppress or configure sonar.

**Comment by romani** [comment]
hold on .... looks like there is some bug in sonar UI .... now I found a way to configure our own Gate - https://sonarcloud.io/organizations/checkstyle/quality_gates/show/8515

**Comment by romani** [comment]
and now I was able to configure Rule to define custom method - https://sonarcloud.io/organizations/checkstyle/rules?languages=java&open=java%3AS2699&q=assert

**Comment by romani** [comment]
resolved at https://github.com/checkstyle/checkstyle/issues/5604#issuecomment-573361298
by converting Rule severity to INFO.

**Comment by rnveach** [comment]
@romani just to confirm, sonar was fixed so no failures should come up related to this in new PRs?

**Comment by romani** [comment]
Yes, I hope there will be no unrelated, but I am not sure.
