### ISSUE TITLE
Use archunit library to control source code 

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#7469]
https://www.archunit.org/userguide/html/000_Index.html#_cycle_checks
To prevent cycles in packages or use it just another static analysis tool.

Limitation:
https://github.com/TNG/ArchUnit/issues/359 Archunit do not see `@Retention(SOURCE)`  annotations like `java.lang.Override`. 

Some links
https://blogs.oracle.com/javamagazine/unit-test-your-architecture-with-archunit
https://www.archunit.org/userguide/html/000_Index.html#_general_coding_rules
https://github.com/TNG/ArchUnit-Examples/blob/master/example-junit4/src/test/java/com/tngtech/archunit/exampletest/junit4/MethodsTest.java
https://github.com/societe-generale/arch-unit-build-plugin-core/blob/arch_unit_build_plugin_core_2.3.0/src/main/java/com/societegenerale/commons/plugin/rules/NoJunitAssertRuleTest.java
https://github.com/TNG/ArchUnit/blob/master/archunit/src/main/java/com/tngtech/archunit/library/GeneralCodingRules.java
https://github.com/societe-generale/arch-unit-maven-plugin/blob/master/README.md

**Comment by gaurabdg** [comment]
@romani @rnveach I have solved both `gsoc-first-issue` and `gsoc-first-issue`. Would you advice me to work on this issue? If not, is there something else I can work on to better my understanding?

**Comment by romani** [comment]
@gaurabdg, please send message to mail list and provide list of projects for GSoC you would like to do. We will suggest on next issue to focus more on related code to your future project.

For this issue ... You can take it and start with validation of cycles between packages. We do have cycles, we can not fix the now, but we would like to not make more cycles. So in scope of this issue we should keep in ignore list all existing cycles, and fail UT execution if new cycle appear.

As additional validation, we should validate that Checks are not using any methods from other Checks.

Checks should not have protected methods or fields.

**Comment by gaurabdg** [comment]
@romani Sure!

**Comment by gaurabdg** [comment]
I am on it.

**Comment by gaurabdg** [comment]
I'll try to integrate it
