### ISSUE TITLE
Is there any migration guide for each new version?

### ISSUE THREAD

**Issue by AlBundy33** [checkstyle/checkstyle#7484]
Currently we have to modify our checkstyle-configuration-xml after each(?) update of the checkstyle plugin.

Sometimes we have errors in the error-log because the xml is invalid and sometime checks are not executed because they have to be configured in additional tags or attributes.

Here are some examples:
LineLength was moved from TreeWalker to Checker.
New(?) Checks MissingJavadocMethod, MissingJavadocType, MissingJavadocPackage have to be added to configuration.
In JavadocMethod allowMissingThrowsTags changed to validateThrows.
NonEmptyAtclauseDescription has to added to ensure that @param-Tags have a non empty description

**Comment by romani** [comment]
> after each(?) update of the checkstyle plugin.

We do not know which plugin do you use and what version of checkstyle you use in plugin, so it hard to predict what problems you might encounter during upgrade. Simple googling should help you to find migration notes, review of releasenotes should also help.

Migration notes exists for cases when we break compatibility see `Breaking backward compatibility:` sections at https://checkstyle.org/releasenotes.html
Example for 
> LineLength was moved from TreeWalker to Checker.

at https://checkstyle.org/releasenotes.html#Release_8.24
> Breaking backward compatibility:
    Change LineLength Check parent from TreeWalker to Checker. Author: rnveach, Roman Ivanov #2116 

in #2116 there is "Migration Notes" with details on what to do. All issues in sections `Breaking backward compatibility:` have migration notes. You might also look at commits that are referenced in Issue from outside projects, as some users might already migrated and you will see exact diff on how to do this.

> sometime checks are not executed because they have to be configured in additional tags or attributes.

Unfortunately we do not have feature to enable all new Checks in your execution time. Some Checks are conflicting with each other, some might not be required by you. So Checkstyle do strictly follow what you have in config. So new Checks need to be activated manually.
You can always find them in sections "New:" at our release notes. We try to be thorough on issue titles and classification to help user find them quickly.

**Comment by AlBundy33** [comment]
We're using the current plugin from http://eclipse-cs.sourceforge.net/update/ which should be yours https://github.com/checkstyle/eclipse-cs

Checking the release-notes is ok and to be honest the LineLength-Check was good documented although I'd wish that there would be a hint in release-notes that there are migration instructions.

LineLength-Check was a good error because it causes that no check was executed due to an invalid xml - so we found this issue really slow.

But some changes (e.g. new MissingJavadocMethod) are harder to find because the plugin works as expected because a check that was working before is now not executed.

**Comment by romani** [comment]
> which should be yours

yes, it is finally end in organization umbrella, but we do need maintainers for it to keep it alive.
We try to release it right after library is released .... But it is still hard to predict from what version you migrate. A lot of users still use very old versions, for many reasons.
So after upgrade, you need to skim release notes [from;to] and glance on "New:" and breaking compatibility sections. if you have problem ... look at release notes there will be reference of problematic Check and you review just few issue to make sure it is related or not.
If nothing looks like related ... use search in our Guthub repo, google search. If nothing is similar  ... create github issue for discussion. We will provide feedback and probably next user will find your post and get solution quickly.

> I'd wish that there would be a hint in release-notes that there are migration instructions.

We have internal rule .... is issue is breaking it MUST have migration notes. We all people , we could forget, pin us and we will make it.

> plugin works as expected because a check that was working before is now not executed

yes, some cases are hard.
Check is executing ... but right now it does less and does it differently.
Only reading of release note can help.
Do you have suggestion on how to make it better?

**Comment by AlBundy33** [comment]
just some ideas for first start of the plugin after an update
- check if xml-configuration is valid and show error if not - where valid means at least schema-validation and maybe some additional checks (e.g. valid checkes, attributes etc)
- display release notes

**Comment by romani** [comment]
:) ok, so please open this issue on special plugin :) (there a lot of plugins), here we discuss only core library validation issues.

**Comment by romani** [comment]
@AlBundy33 , one more note ....

if you see  that checkstyle version is bumped in second digit (minor version in semiversion model) you can be sure that something new or something breaking was done.
Example of release that had only bug fixes - https://checkstyle.org/releasenotes.html#Release_8.10.1

We use sentimental version for first digit (it is definition of very big phase in development or compatibility), for second and third we use semiversion model.
