### ISSUE TITLE
Add method hasChildren to DetailAST

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#7487]
From https://github.com/sevntu-checkstyle/sevntu.checkstyle/pull/794#issue-361850509

The most common usage of the method [getChildCount](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/DetailAST.java#L36) is to compare the count to zero. For [example](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyForInitializerPadCheck.java#L112). This is not efficient nor readable. Both issues can be fixed by adding a new method to the `DetailAST` interface:
```java
default boolean hasChildren() {
    return getFirstChild() != null;
}
```

**Comment by romani** [comment]
I am ok to add this methood.
@rnveach , please review and put label.

**Comment by rnveach** [comment]
@romani I was ok with it until I saw the default method in the interface. I personally would just prefer to see the implementation in the class. I am old school.

**Comment by romani** [comment]
ok, lets make method in interface as declaration.

**Comment by pbludov** [comment]
Started https://github.com/hcoles/pitest/issues/725 for the Pitest issue.

**Comment by romani** [comment]
Fix is merged
