### ISSUE TITLE
no site documentation for UnusedLocalVariableCheck

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#75]
At http://checkstyle.sourceforge.net/availablechecks.html
this check 
https://github.com/checkstyle/checkstyle/blob/master/contrib/usage/src/checkstyle/com/puppycrawl/tools/checkstyle/checks/usage/UnusedLocalVariableCheck.java
 is not present.

This Check have to appear in web site, then open issue against Eclipse-CS to register this check.

**Comment by alexkravin** [comment]
these Checks are in contrib folder, so firstly it is needed to move them to src/main or you have any other suggestions?

**Comment by romani** [comment]
I will resolve that issue myself, looks like we need to move whole folder contrib to new repo "checkstyle-contrib", as it store stuff that is useful (or was useful) for some group of people, but all these files are not required for library functioning.
