### ISSUE TITLE
Add warning message at style coverage pages that referenced config is not released

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#7505]
taken from #7503

At https://checkstyle.org/google_style.html , https://checkstyle.org/sun_style.html we use links to most recent google style file (not yet released version) on this page as we rely on search feature of GitHub, search feature is available only for master head code.

We can not put here links to previous release, that is absolutely reasonable from users perspective, but unfortunately not supported by Github search. So it would force us to use strict line number links, that will be error prone and heavy to support if modification happens.

Proposal:
What we can do is to put a warning on top of such html page and warm users to use embedded version in jar or versioned (for certain tag name) file.

**Comment by romani** [comment]
Proposed wording:
`Links to config in following table reference to latest (not released yet) config, it might be slightly different from what we have in latest release. Please always use config that is embedded to jar or use config that is versioned https://github.com/checkstyle/checkstyle/blob/checkstyle-8.28/src/main/resources/google_checks.xml . Please be sure to use same version of config as you use chekcstyle.`

**Comment by strkkk** [comment]
> We can not put here links to previous release, that is absolutely reasonable from users perspective, but unfortunately not supported by Github search

May be it is possible to create some branch with name like "latest_release" where config version for last release (and other stuff) will be stored. Can github make a search in this case?
Or just publish config(s) as release artifact.

**Comment by romani** [comment]
No such options https://github.com/search/advanced?q=java8&r=checkstyle%2Fcheckstyle&type=Code

**Comment by romani** [comment]
@rnveach  or @pbludov please approve issue.

**Comment by pbludov** [comment]
fix is merged.
