### ISSUE TITLE
Mark DetailAST::getNumberOfChildren as deprecated

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#7512]
The interface DetailAST currently contains two methods to return the count of children:

    getChildCount
    getNumberOfChildren

Both methods are implemented in the same way (getChildCount has an optimization):

https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/DetailAstImpl.java#L166

https://github.com/Distrotech/antlr2/blob/master/antlr/BaseAST.java#L67

The method `getNumberOfChildren` should be deprecated. This method cannot be removed because it can be used in third-party checks.

**Comment by romani** [comment]
fix is merged.
