### ISSUE TITLE
Change line number comparisons to use common isOnSameLine method

### ISSUE THREAD

**Issue by strkkk** [checkstyle/checkstyle#7518]
At the moment there is several methods for checking that 2 ASTs are on same line, e.g.
https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/NeedBracesCheck.java#L295
https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/AbstractExpressionHandler.java#L188

And many occurrences of line number comparison, e.g.
https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java#L310
https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MultipleVariableDeclarationsCheck.java#L108
and others.

So this should be extracted to some common util class and all occurrences replaced with new method.

**Comment by romani** [comment]
I am ok to move this to util method of some existinig util class.

@pbludov, please confirm and approve issue.

**Comment by pbludov** [comment]
As far as I understand, this is not about optimization, but about code readability?
`if (firstNode.getLineNo() != secondNode.getLineNo())` vs
`if (!CheckUtil.areOnSameLine(firstNode, secondNode))`

I like this.

**Comment by strkkk** [comment]
> As far as I understand, this is not about optimization, but about code readability?

yes, only readability.

**Comment by romani** [comment]
Fix is merged
