### ISSUE TITLE
analyse size of mail-list and Rss audience for announcements

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#7521]
sharing news about new release is still manual process.
Historically it was done by:
mail-list - https://groups.google.com/forum/#!forum/checkstyle-announce (22 members)
rss - https://sourceforge.net/p/checkstyle/news/ (unknown audience)
twitter - https://twitter.com/checkstyle_java (189 followers)

it would be better to avoid extra manual actions and reduce news channels that are not in use that much (mail-list, rss)

Users of such channels can simply "watch" us on Github for "Releases only":
![image](https://user-images.githubusercontent.com/812984/73095161-d6eb9000-3e96-11ea-939d-59ac9135692a.png)

 
-------

related discussions:
https://github.com/checkstyle/sonar-checkstyle/issues/259#issuecomment-577773493
https://github.com/checkstyle/sonar-checkstyle/issues/281#issuecomment-580146879

**Comment by romani** [comment]
we can use https://www.surveymonkey.com to collect votes of people who read notification and care about news.
We need to prepare good wording for announcement of possible change and share it in RSS and Mail-list:
```
Checkstyle team consider deprecation of checkstyle-announce mail list and RSS feed at sourceforge.
As most activity is done in Github we would like to use Github feature of notifications on releases to be primary channel to share news about new releases.
Please vote for following points (multi choice):
- I do read email announcements of releases from checkstyle-announce, please keep it.
- I do read RSS events from sourceforge, please keep it.
- I ok to use "Release only" Github watch notifications.
```

@rnveach , @pbludov , @strkkk  it is clear message ?

**Comment by pzygielo** [comment]
GH releases can also be RSS-watched: https://github.com/checkstyle/checkstyle/releases.atom

**Comment by strkkk** [comment]
@romani I would ask also about preferable ways to get information about news/updates, may be there is some other (not rss/mail/twitter) things.

**Comment by rnveach** [comment]
@romani the message is clear to me.

**Comment by romani** [comment]
> I would ask also about preferable ways to get information about news/updates

I do not want to give users much freedom, as it helps me to avoid steps that are not automated in release. Release should be done by any maintainer, it should not take long time.
If users want something else that much they will create issue and we will discuss.

**Comment by romani** [comment]
https://groups.google.com/forum/#!topic/checkstyle-announce/WKGrxbjbjXg
https://sourceforge.net/p/checkstyle/news/2020/02/checkstyle-team-considers-to-discontinue-rss-feed/

In 3 month (after 2 May 2020), we will review results at https://www.surveymonkey.com/analyze/jahHtK5YC_2B86HCogpBnwxcLy9OECJy5XTPYvKSjY0Uc_3D , make result public and make a decision.

**Comment by romani** [comment]
result of survey:
![image](https://user-images.githubusercontent.com/812984/83355258-29403000-a313-11ea-9a59-c92762c76a21.png)

rss and mail-list will be discontinued from this day. We might come back to to post to such channels but there should be full automation of publishing provided.
