### ISSUE TITLE
Check that field and method operator . is not at the end of line.

### ISSUE THREAD

**Issue by andrewgaul** [checkstyle/checkstyle#755]
Recently I saw some code with multiple chained method calls with the following style:

```java
ImmutableList.<Integer>builder().
        add(1).
        add(2).
        add(3);
```

I would like Checkstyle to enforce the following style:

```java
ImmutableList.<Integer>builder()
        .add(1)
        .add(2)
        .add(3);
```

**Comment by romani** [comment]
Did you try OperatorWrap Check  ?

see examples at http://checkstyle.sourceforge.net/google_style.html chapter "4.5.1 Where to break".

**Comment by andrewgaul** [comment]
Thanks for the suggestion @romani!  SeparatorWrap allows me to express this:

```xml
<module name="SeparatorWrap">
    <property name="tokens" value="DOT"/>
    <property name="option" value="nl"/>
</module>
```
