### ISSUE TITLE
Add default config example for AbstractClassName

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#7561]
split from #5832 

update AbstractClassName to make examples for all configs shown in documentation
https://checkstyle.org/config_naming.html#AbstractClassName
this check need default config and example of code that is violates and expect as correct.

See original issues for examples on how to make update.

------------

PLEASE READ https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-examples

**Comment by romani** [comment]
@haideratGitHub , can you help us to resolve this issue ?

**Comment by haideratGitHub** [comment]
@romani  sure I can, Is it okay if I start working on it after monday because I have exam due on monday so I need to prepare for it ?  After that I'll up to that issue and will ask for some help if needed.

**Comment by romani** [comment]
Sure

**Comment by romani** [comment]
@haideratGitHub  , I placed in description link on how PR should looks like , please do.

**Comment by haideratGitHub** [comment]
@romani OKay

**Comment by romani** [comment]
resolved in scope of Issue #7565: Update doc for AbstractClassName
