### ISSUE TITLE
Add default config example for ClassTypeParameterName

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#7562]
split from #5832

update ClassTypeParameterName to make examples for all configs shown in documentation
https://checkstyle.org/config_naming.html#ClassTypeParameterName
this check need default config and example of code that is violates and expect as correct.

See original issues for examples on how to make update.

------------

PLEASE READ https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-examples

**Comment by romani** [comment]
@amritk07 , please help to resolve.

**Comment by amritk07** [comment]
I am on it

**Comment by amritk07** [comment]
@romani  Do I have to update only AbstractClassName or any other check also

**Comment by amritk07** [comment]
I have resolved the issue and created PR [Link](https://github.com/checkstyle/checkstyle/pull/7568)

**Comment by rnveach** [comment]
@amritk07 As the issue describes, this issue is only for ClassTypeParameterName. AbstractClassName is a completely issue and separate from this.

**Comment by romani** [comment]
@amritk07  , I placed in description link on how PR should looks like , please do.

**Comment by romani** [comment]
@sushant-kun, please help to resolve this issue.

**Comment by sushant-kun** [comment]
I am on it.

**Comment by sushant-kun** [comment]
@romani I am a bit confused since you mentioned both AbstractClassName and ClassTypeParameterName. Where exactly am I supposed to make the changes?

**Comment by romani** [comment]
In ClassTypeParameterName, sorry for typo. I fixed description

**Comment by romani** [comment]
Fix is merged
