### ISSUE TITLE
Add default config example for CatchParameterName

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#7563]
split from #5832

update AbstractClassName to make examples for all configs shown in documentation
https://checkstyle.org/config_naming.html#CatchParameterName
this check need default config and example of code that is violates and expect as correct.

See original issues for examples on how to make update.

------------

PLEASE READ https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-examples

**Comment by romani** [comment]
@promehul , can you help us to resolve this issue ?

**Comment by promehul** [comment]
Yeah, I'm on it.

**Comment by romani** [comment]
@promehul  , I placed in description link on how PR should looks like , please do.
