### ISSUE TITLE
Add default config example for AbstractClassName

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#7565]
split from #5832

update AbstractClassName to make examples for all configs shown in documentation
https://checkstyle.org/config_naming.html#AbstractClassName
this check need default config and example of code that is violates and expect as correct.

See original issues for examples on how to make update.

------------

PLEASE READ https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-examples

**Comment by romani** [comment]
@pkpale , can you help to resolve this issue

**Comment by pkpale** [comment]
I am on it

**Comment by pkpale** [comment]
Can you help me how to proceed further @romani

**Comment by pkpale** [comment]
@romani  for adding the config example for InterfaceTypeParameterName  I have to make changes in this file https://github.com/checkstyle/checkstyle/blob/master/src/xdocs/config_naming.xml

**Comment by romani** [comment]
yes, as you update this file , please run `mvn verify` and make sure it pass.
it will force you to do same update in javadoc of Check.

**Comment by pkpale** [comment]
@romani Can you please help me I am bit confused.
Do I need to make changes in this https://checkstyle.org/config_naming.html#InterfaceTypeParameterName or https://checkstyle.org/config_naming.html#AbstractClassName and I have to take reference of whom to make change in another.

**Comment by rnveach** [comment]
@pkpale We are only looking for changes in `AbstractClassName`. You should use `InterfaceTypeParameterName` as an example. We want all properties to be documented to show examples of code it will and will not violate and how they are different than the default configuration.

**Comment by pkpale** [comment]
Ok I will do it but after my exams are over as they going on and will end by 29th. I hope it will be fine.

**Comment by romani** [comment]
@pkpale  , I placed in description link on how PR should looks like , please do.

**Comment by pkpale** [comment]
@romani   to synchronise the java file I changed /checkstyle/src/xdocs/config_naming.xml and /checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/AbstractClassNameCheck.java but I still getting XdocsJavaDocsTest.testAllCheckSectionJavaDocs:111->examineCheckSection:138 » error.
![Screenshot from 2020-02-29 19-30-49](https://user-images.githubusercontent.com/42895397/75608936-10648a80-5b2a-11ea-8045-601b665f1652.png)

**Comment by rnveach** [comment]
@pkpale Your screenshot is the summary of the failures which doesn't give the full details. You should find the failing test further up and it will give you more details. The test ensures the javadoc and xdoc are updated to be identical. If it is failing, then 1 was updated and not the other.

**Comment by pkpale** [comment]
how I can find the failing test further up which will give me more details.

**Comment by rnveach** [comment]
What you are seeing is a print out of an assertion difference between 2 strings. If you are not familar with it, you should read up on junit tests. As the screenshot shows, it is finding the javadoc for AbstractClassName is not the same as what is written in the xdoc for it. You shouldn't have any changes for `AbstractClassName` as this issue is only dealing with `InterfaceTypeParameterName`.

**Comment by pkpale** [comment]
> @pkpale We are only looking for changes in `AbstractClassName`. You should use `InterfaceTypeParameterName` as a completed example. We want all properties to be documented to show examples of code it will and will not violate and how they are different than the default configuration. Imagine you are unfamilar with check and property descriptions don't make sense. Users want a real example to show how it works.

So, I need to change to InterfaceTypeParameterName, but earlier you told I need to see InterfaceTypeParameterName as a example and should change in AbstarctClassName

**Comment by rnveach** [comment]
@romani ping
> Add default config example for InterfaceTypeParameterName 
> update AbstractClassName 

Issue title conflicts with issue description. Please confirm.

**Comment by romani** [comment]
@pkpale , in this issue we should change AbstractClassName, sorry for confusion. I fixed description now.

**Comment by pkpale** [comment]
Ok, I will do it. Do I need to pass all the checks before creating PR. As mentioned int these 2 links
https://github.com/checkstyle/checkstyle/blob/master/.github/ISSUE_TEMPLATE.md
https://github.com/checkstyle/checkstyle/wiki/How-to-run-certain-phases-and-validations#how-to-generate-website-only

**Comment by romani** [comment]
@pkpale , yes, please. If PR is not following such rules , we skip it from review.
If you have questions, please ask here.

**Comment by pkpale** [comment]
@ romani I changed both files located at ~/Desktop/checkstyle/src/xdocs/config_naming.xml and ~/Desktop/checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/AbstractClassNameCheck.java but after runniung "mvn verify" it gives error in the file which I didn't even touched. I have also attached screenshot
![Screenshot from 2020-03-06 02-58-19](https://user-images.githubusercontent.com/42895397/76027845-5d47c700-5f57-11ea-9265-d78c5a76271f.png)

**Comment by pkpale** [comment]
Please help me as I am taking too long to solve even a single simple issue.

**Comment by romani** [comment]
@pkpale, you have checkstyle violation in your change, please read error message attentively, you need to remove empty line at line 64

**Comment by romani** [comment]
fix is merged.
