### ISSUE TITLE
Add default and missed property config example for AbbreviationAsWordInName

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#7566]
split from #5832

update AbstractClassName to make examples for all configs shown in documentation
https://checkstyle.org/config_naming.html#AbbreviationAsWordInName
this check need default config and example of code that is violates and expect as correct.

See original issues for examples on how to make update.

------------

PLEASE READ https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-examples

**Comment by CapTen101** [comment]
I'm on this issue @romani

**Comment by romani** [comment]
@CapTen101  , I placed in description link on how PR should looks like , please do.

**Comment by CapTen101** [comment]
Yes sir. It's just that my exams are too near and thus I'm not able to give proper time to understanding the same. My exams are till 6 march. After that, I can start with full enthusiasm. I hope you'll understand. @romani

**Comment by wltan** [comment]
@CapTen101 If you're no longer working on this issue, I'd like to take over. I happen to be doing related documentation in another PR.

**Comment by CapTen101** [comment]
Okay. You may take the charge.

**Comment by rnveach** [comment]
Fix was merged
