### ISSUE TITLE
Add default config example for MethodName

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#7567]
split from #5832

update AbstractClassName to make examples for all configs shown in documentation
https://checkstyle.org/config_naming.html#MethodName
this check need default config and example of code that is violates and expect as correct.

See original issues for examples on how to make update.

------------

PLEASE READ https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-examples

**Comment by raghuchandan1** [comment]
I am on it!

**Comment by romani** [comment]
@raghuchandan1  , I placed in description link on how PR should looks like , please do.

**Comment by raghuchandan1** [comment]
Will definitely look into it

**Comment by Vyom-Yadav** [comment]
@romani I am on it.

**Comment by Vyom-Yadav** [comment]
the default example for `allowClassName` is already there, will add for the rest.

**Comment by romani** [comment]
fix is merged
