### ISSUE TITLE
update doc for AnnotationLocation to have config first and code sample after

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#7569]
https://checkstyle.org/config_annotation.html#AnnotationLocation

There is no example of default configuration of this Check. Please add.
update doc for AnnotationLocation to have config first and code sample after.

Code of documentation is at https://github.com/checkstyle/checkstyle/blob/master/src/xdocs/config_annotation.xml

Good example of documentation structure is at https://checkstyle.org/config_naming.html#AbbreviationAsWordInName

look at referenced commits of #5832, to see what and how should be changed in code. 

please play with module/Check by means of https://checkstyle.org/cmdline.html to understand how it works.

------------

PLEASE READ https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-examples

**Comment by PrabodDunuwila** [comment]
I'm on it.

**Comment by romani** [comment]
fix is merged.
@PrabodDunuwila , thanks a lot for update, it was big but very valuable update.
