### ISSUE TITLE
update doc for AnnotationOnSameLine

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#7570]
https://checkstyle.org/config_annotation.html#AnnotationOnSameLine

add code examples with code that are expected by Check (produce no violations).
add example with configured (non default) `tokens` property ([example](https://checkstyle.org/config_blocks.html#EmptyBlock)).

look at referenced commits of #5832, to see what and how should be changed in code.

please play with module/Check by means of https://checkstyle.org/cmdline.html to understand how it works.

------------

PLEASE READ https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-examples

**Comment by sulkykookie** [comment]
I'm on it.
