### ISSUE TITLE
update doc for AnnotationUseStyle

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#7571]
https://checkstyle.org/config_annotation.html#AnnotationUseStyle

1) Add example for each existing config to show what code is ok and what code cause violation.
Good example is https://checkstyle.org/config_naming.html#AbstractClassName

2) Please add example with non default value for `trailingArrayComma`

look at referenced commits of #5832, to see what and how should be changed in code.

please play with module/Check by means of https://checkstyle.org/cmdline.html to understand how it works.

------------

PLEASE READ https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-examples

**Comment by ImmortalRabbit** [comment]
I am on it.

**Comment by Youssef1313** [comment]
@romani Should this issue be closed now?

**Comment by romani** [comment]
@Adityasaini10012001, please help us with this issue

**Comment by romani** [comment]
Everyone in the world can help us to fix issue, links to incomplete code can be reused.

**Comment by protyay** [comment]
I'm on it.

**Comment by romani** [comment]
There are examples already but they are not full to let users understand how Check works.
We need to extend java code blocks of "Example:"
to have java code that have for example violation on ` <property name="trailingArrayComma" value="never"/>`


We need to show users how configuration changes in check make violation location be different on java code

**Comment by naotokuwa** [comment]
Hello,

I'm interested in working on this issue and wanted to confirm that nobody else is already working on it. If it's available, I would like to take on this task.

Regarding the modifications to the document, here's what I'm planning to do:

Current Example:

1. All three configs are set to default
2. elementStyle is set to "expanded", and trailingArrayComma is set to "never" (which is the default value), and closingParens is set to "always"

Proposed Example:

1. All three configs are set to default (same as before)
2. elementStyle is set to "expanded" (other two configs are set to default)
3. trailingArrayComma is set to "always" (other two configs are set to default)
4. closingParens is set to "always" (other two configs are set to default)

For each proposed example, I plan to provide at least four examples with "OK" and "Violation" scenarios.

Please let me know if this aligns with what's needed for the issue, or if there are any other suggestions or considerations to keep in mind. Thank you for your time!

**Comment by romani** [comment]
Nobody working https://github.com/checkstyle/checkstyle/pulls?q=is%3Apr+is%3Aopen+AnnotationUseStyle

**Comment by naotokuwa** [comment]
OK. I take on this task.

**Comment by naotokuwa** [comment]
Hi, Romani
I have a question regarding the scenario where the trailingArrayComma option is set to always, and I am planning to include it in examples. Currently, we have six different annotations, but none of them does meet the condition. Therefore, I cannot show a case where the condition is met (“OK” scenario). Since I can only change the comment (not the code itself), I have a problem achieving 2nd task, “Please add example with the non default value for trailingArrayComma.” Can I modify the Java code which I will use in all scenarios or is there any other approach I can take?

**Comment by romani** [comment]
Yes, please modify all examples to show users how options works. Please send PR sooner to let us discuss issue at exact context.

**Comment by naotokuwa** [comment]
OK. Thank you!

**Comment by naotokuwa** [comment]
Hi, Romani
I made a code change that reflects what we discussed and the requirements on src/xdocs/config_annotation.xml on my local branch.
However, I do not know how to check the changed website looks by running the program. Could you tell me which resources I should look at or the steps to do that?

**Comment by romani** [comment]
https://github.com/checkstyle/checkstyle/wiki/How-to-run-certain-phases-and-validations#how-to-generate-website-only

**Comment by naotokuwa** [comment]
Thank you. I could find it.

**Comment by naotokuwa** [comment]
Hi, I sent a PR! Thank you!

**Comment by romani** [comment]
Fix is merged
