### ISSUE TITLE
update doc for MissingDeprecated

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#7572]
https://checkstyle.org/config_annotation.html#MissingDeprecated

1) Add example for each existing config to show what code is ok and what code cause violation.
Good example is https://checkstyle.org/config_naming.html#AbstractClassName

look at referenced commits of #5832, to see what and how should be changed in code.

please play with module/Check by means of https://checkstyle.org/cmdline.html to understand how it works.

------------

PLEASE READ https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-examples

**Comment by RhnSaxena** [comment]
I am on it.

**Comment by romani** [comment]
@mradulrathore, please help to fix issue.

**Comment by mradulrathore** [comment]
I'm on it.

**Comment by mradulrathore** [comment]
@romani, I am getting this error while running mvn -X clean verify:
https://gist.github.com/mradulrathore/fa34a252009d62a5853d221bf1037a49

**Comment by romani** [comment]
> ```
[[1;31mERROR[m] testAllCheckSectionJavaDocs  Time elapsed: 0.572 s  <<< ERROR!
java.lang.Error: Error was thrown while processing src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/MissingDeprecatedCheck.java
	at com.puppycrawl.tools.checkstyle.internal.XdocsJavaDocsTest.examineCheckSection(XdocsJavaDocsTest.java:138)
	at com.puppycrawl.tools.checkstyle.internal.XdocsJavaDocsTest.testAllCheckSectionJavaDocs(XdocsJavaDocsTest.java:111)
Caused by: org.opentest4j.AssertionFailedError: 
MissingDeprecated's class-level JavaDoc ==> expected: <
```

yes, just follow UT failure and keep in sync xdoc and javadoc.

**Comment by mradulrathore** [comment]
@romani, how to find jar file for command:
java -jar /var/tmp/checkstyle-8.31-all.jar -c config.xml Test.java

**Comment by rnveach** [comment]
@mradulrathore See https://github.com/checkstyle/checkstyle/releases

**Comment by SGanguly1999** [comment]
I am on it

**Comment by romani** [comment]
fix is merged
