### ISSUE TITLE
update doc for PackageAnnotation

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#7574]
https://checkstyle.org/config_annotation.html#PackageAnnotation

Add example for each existing config to show what code is ok and what code cause violation.
Good example is https://checkstyle.org/config_naming.html#AbstractClassName

look at referenced commits of #5832, to see what and how should be changed in code.

please play with module/Check by means of https://checkstyle.org/cmdline.html to understand how it works.

------------

PLEASE READ https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-examples

**Comment by PrabodDunuwila** [comment]
I'm on it.

**Comment by PrabodDunuwila** [comment]
Do I need to provide an example as below? 
`@Deprecated`
`package com.example.annotations.packageannotation;`

**Comment by rnveach** [comment]
Any examples that help show what the check looks for and prints violations for. It says it checks any package annotations are in `package-info.java`. So yes, you will need an example showing an annotation and explain the file name.

**Comment by romani** [comment]
@PrabodDunuwila, I extended issue description with more details on what is required to do in PR, please review and update your PR.

**Comment by PrabodDunuwila** [comment]
@romani, Thanks. I will update the PR within the weekend.

**Comment by rnveach** [comment]
Fix was merged
