### ISSUE TITLE
update doc for SuppressWarnings

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#7575]
https://checkstyle.org/config_annotation.html#SuppressWarnings

Add example for each existing config to show what code is ok and what code cause violation.
Good example is https://checkstyle.org/config_naming.html#AbstractClassName

look at referenced commits of #5832, to see what and how should be changed in code.

please play with module/Check by means of https://checkstyle.org/cmdline.html to understand how it works.

------------

PLEASE READ https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-examples

**Comment by srividyavaishnavi** [comment]
i am on it

**Comment by mihirbachhav025** [comment]
Can I work on this
?

**Comment by strkkk** [comment]
@mihirbachhav025 yes

**Comment by mihirbachhav025** [comment]
ok thanks

**Comment by tripolkaandrey** [comment]
I am on it

**Comment by kvinay7** [comment]
Is any one working on this issue ?

**Comment by romani** [comment]
Yes

**Comment by meghnabajoria** [comment]
I am on it.

**Comment by meghnabajoria** [comment]
Hi @romani, I am trying to run SuppressWarningsCheck.java and its test cases to understand it. For this, I have made my own config.xml file and I am using the below cmd. But nothing is happening. It just states audit started and finished. Am I doing something wrong?
`java -jar C:\Users\Meghna\Downloads\checkstyle-10.6.0-all.jar -c config1.xml SuppressWarningsCheck.java`
This is my config file
`
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name="Checker">
    <module name="TreeWalker">
        <module name="SuppressWarnings">
            <property name="format"
                      value="^unchecked$|^unused$"/>
            <property name="tokens"
                      value="
    CLASS_DEF,INTERFACE_DEF,ENUM_DEF,
    ANNOTATION_DEF,ANNOTATION_FIELD_DEF,
    ENUM_CONSTANT_DEF,METHOD_DEF,CTOR_DEF
    "/>
        </module>
    </module>
</module>
`

**Comment by romani** [comment]
Your CLI command is nonsense, please look at https://checkstyle.org/config_annotation.html#SuppressWarnings_Examples  you need put such xml at config1.xml and use some java with with bunch of `@SuppressWarnings("")`

**Comment by romani** [comment]
no feedabck in 1 month, this issue is free to take for others

**Comment by raj1701** [comment]
Hi @romani, I am Rajat Partani. I want to apply for GSOC 2023 with checkstyle. Can I start with this issue?

**Comment by romani** [comment]
@raj1701 , yes, please send PR. no active PR from @meghnabajoria .

**Comment by SaarSaar223** [comment]
Hello @romani can I take this issue?

**Comment by romani** [comment]
Please take it

**Comment by zyrate** [comment]
Hello @romani  I want to have a try, and I have send PR.

**Comment by romani** [comment]
Fix is merged
