### ISSUE TITLE
Update doc for AvoidNestedBlocks

### ISSUE THREAD

**Issue by rdiachenko** [checkstyle/checkstyle#7579]
https://checkstyle.org/config_blocks.html#AvoidNestedBlocks

Add code examples for check's default configuration (one which produces violations and one without violations).
Add a config and examples with configured (non default) allowInSwitchCase property.

Look at referenced commits of #5832, to see what and how should be changed in code.

Please play with module/check by means of https://checkstyle.org/cmdline.html to understand how it works.

------------

PLEASE READ https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-examples

**Comment by RhnSaxena** [comment]
I am on it.

**Comment by bossever** [comment]
I am facing infrastructure problem in pitest checks in my PR #9182, and I cannot figure out what is causing the test failure. Please help.

**Comment by romani** [comment]
fix is merged.
