### ISSUE TITLE
Update doc for EmptyBlock

### ISSUE THREAD

**Issue by rdiachenko** [checkstyle/checkstyle#7580]
https://checkstyle.org/config_blocks.html#EmptyBlock

Add examples for each existing config to show what code is ok and what code causes violations.

Look at referenced commits of #5832, to see what and how should be changed in code.

Please play with module/check by means of https://checkstyle.org/cmdline.html to understand how it works.

------------

PLEASE READ https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-examples

**Comment by ImmortalRabbit** [comment]
I am on it.

**Comment by romani** [comment]
Fix is merged
