### ISSUE TITLE
Add default config and code examples for EmptyCatchBlock

### ISSUE THREAD

**Issue by rdiachenko** [checkstyle/checkstyle#7581]
https://checkstyle.org/config_blocks.html#EmptyCatchBlock

This check needs a default config and examples of code that gives violations and that is correct.

Look at referenced commits of #5832, to see what and how should be changed in code.

Please play with module/check by means of https://checkstyle.org/cmdline.html to understand how it works.

------------

PLEASE READ https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-examples

**Comment by AMFIRNAS** [comment]
I'am on it

**Comment by SGanguly1999** [comment]
I am on it
