### ISSUE TITLE
Update doc for LeftCurly

### ISSUE THREAD

**Issue by rdiachenko** [checkstyle/checkstyle#7582]
https://checkstyle.org/config_blocks.html#LeftCurly

Add examples for each existing config to show what code is ok and what code causes violations.

Look at referenced commits of #5832, to see what and how should be changed in code.

Please play with module/check by means of https://checkstyle.org/cmdline.html to understand how it works.

NOTE: we just need more examples on different modes of  `option` property https://checkstyle.org/property_types.html#LeftCurlyOption

------------

PLEASE READ https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-examples

**Comment by ImmortalRabbit** [comment]
I am on it.

**Comment by SGanguly1999** [comment]
I am on it.

**Comment by Stredsto** [comment]
This issue still open ?

**Comment by justdoit254** [comment]
Is the issue still open?
I want to work on it.

**Comment by justdoit254** [comment]
@romani I have set up the codebase can I work on the issue?

**Comment by nmancus1** [comment]
@justdoit254 feel free to send a PR, note comment from https://github.com/checkstyle/checkstyle/issues/7582#issue-569486937:

> NOTE: we just need more examples on different modes of option property https://checkstyle.org/property_types.html#LeftCurlyOption

**Comment by justdoit254** [comment]
Thank you, I am working on it and soon update you.

**Comment by justdoit254** [comment]
@nmancus1 do I need to edit config_blocks.xml or LeftCurlyCheck.java to add more examples by creating a new branch.
I am a beginner so please guide me on the way.

**Comment by romani** [comment]
Yes, please proceed, after change run `mvn verify` and and fix problems if any detected

**Comment by justdoit254** [comment]
After running:

>  mvn verify
I am getting 2 errors.
[ERROR] Errors: 
[ERROR]   XdocsJavaDocsTest.testAllCheckSectionJavaDocs:165->examineCheckSection:192 »  ...
[ERROR]   XdocsPagesTest.testAllXmlExamples:381->isValidCheckstyleXml:457 Checkstyle con...
[INFO]
[ERROR] Tests run: 3713, Failures: 0, Errors: 2, Skipped: 3

I found that I need to sync documentation content by reading https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-examples.
But I am not understanding how to sync content between XML file and java file.
Please help!!

**Comment by nmancus1** [comment]
> But I am not understanding how to sync content between XML file and java file.

You must do this manually (update documentation in both files yourself), we do not have automation for this.

**Comment by justdoit254** [comment]
> 
> You must do this manually (update documentation in both files yourself), we do not have automation for this.

Is there any example or resource I can study to understand what are the steps?

Also in the error info, it is mentioned that the following Test files are creating the problem.
[ERROR] XdocsJavaDocsTest.testAllCheckSectionJavaDocs:165->examineCheckSection:192 » ...
[ERROR] XdocsPagesTest.testAllXmlExamples:381->isValidCheckstyleXml:457 Checkstyle con...

Does this error also mean that documentation has to be updated?

**Comment by romani** [comment]
Javadoc and xdoc content should be in sync, yes, update both

**Comment by justdoit254** [comment]
Yes, now it is showing Build Successful.
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  25:55 min
[INFO] Finished at: 2022-02-07T15:31:18+05:30
[INFO] ------------------------------------------------------------------------

```

**Comment by justdoit254** [comment]
@romani @nmancus1 I have made my first commit after `mvn verify` ran successfully.
But while generating a website with command as mentioned in https://github.com/checkstyle/checkstyle/wiki/How-to-run-certain-phases-and-validations#how-to-generate-website-only 
It is showing 

> Cannot Reconnect in Build

 and following error in terminal:
```
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: org.eclipse.m2e:lifecycle-mapping:pom:1.0.0 was not found in https://repo.maven.apache
.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of ce
ntral has elapsed or updates are forced
```
Please tell me how can I generate website.

**Comment by romani** [comment]
please share whole log file, something is not working with artifact downloads from internet (please recheck proxy or any other firewall like systems in your network).
please push your code to github to let us see your changes and CI will run this and print us all details.

**Comment by nmancus1** [comment]
@justdoit254 you can delete your local maven repo and try again (usually `~/.m2/repository`)

**Comment by justdoit254** [comment]
I have made a commit can I get review on that so that I can make changes if any required.

**Comment by romani** [comment]
See request to update your commit at https://github.com/checkstyle/checkstyle/pull/11300#issuecomment-1046126721

**Comment by justdoit254** [comment]
Please accept my apologies for the incomplete commit. Due to personal reasons, I could not actively contribute. However, I hope to contribute more in the future.

**Comment by Perin-Mangukiya** [comment]
I am on it.

**Comment by romani** [comment]
Fix is merged
