### ISSUE TITLE
Update doc for FinalParameters

### ISSUE THREAD

**Issue by timurt** [checkstyle/checkstyle#7588]
https://checkstyle.org/config_misc.html#FinalParameters

Add example for each existing config to show what code is ok and what code cause violation.
Good example is https://checkstyle.org/config_naming.html#AbstractClassName

please play with module/Check by means of https://checkstyle.org/cmdline.html to understand how it works.

------------

PLEASE READ https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-examples

**Comment by sudo-andro** [comment]
I am on it

**Comment by timurt** [comment]
@sudo-andro are you still working on this issue? do you need help?

**Comment by ek08** [comment]
I am on it

**Comment by romani** [comment]
here is almost done PR - https://github.com/checkstyle/checkstyle/pull/9035
but abandoned, code from this PR can be used by anybody who wants to fix this issue.

**Comment by Binita-tech** [comment]
I am on it.

**Comment by Taniya003** [comment]
on it.

**Comment by strkkk** [comment]
fix is merged
