### ISSUE TITLE
Exception cause is ignored by setupChild

### ISSUE THREAD

**Issue by CSchulz** [checkstyle/checkstyle#759]
Checker:setupChild ignores the cause if the catched exception is already a CheckstyleException f.e. thrown by PackageObjectFactory:createModule

The cause is wrapped via that exception:
```
throw new CheckstyleException("Unable to instantiate " + name, ex2);
```

But in the Checker only the message is extracted:
```
        catch (final Exception ex) {
            // TODO i18n
            throw new CheckstyleException("cannot initialize module " + name
                    + " - " + ex.getMessage(), ex);
        }
```

There should be a type check for CheckstyleException or a general try to retrieve the cause.

The same for PackageObjectFactory:doMakeObject:

```
    private Object doMakeObject(String name)
        throws CheckstyleException
    {
        //try name first
        try {
            return createObject(name);
        }
        catch (final CheckstyleException ex) {
            ; // keep looking
        }

        //now try packages
        for (String packageName : packages) {

            final String className = packageName + name;
            try {
                return createObject(className);
            }
            catch (final CheckstyleException ex) {
                ; // keep looking
            }
        }

        throw new CheckstyleException("Unable to instantiate " + name);
    }
```

None of these exceptions is logged or somehow handled ... You will not determine why your Check can't be loaded so easily.

**Comment by romani** [comment]
@CSchulz, please point to the problem one more time or try to explain it in different way, I might be blind , but I do not see a problem, we do not hide cause of CheckstyleException at that places.

**Comment by CSchulz** [comment]
Have a look at PackageObjectFactory:doMakeObject, you can see two try/catch blocks handling none of the exception cause in some way.  
No assignment in a local variable either a logging of that exception.

So you don't know why your module can't be instantiated. You will get only the information that it can't be done.

**Comment by romani** [comment]
@CSchulz,

ok, thanks a lot, I see we ignore exception information from catches:
https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/PackageObjectFactory.java#L83
https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/PackageObjectFactory.java#L94

non of them is delivered to final catch:
https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/PackageObjectFactory.java#L98

It kind of intentional, I doubt that logging of any of that two exceptions will help user to identify a problem.

Will it be enough to extent a message with details of what happen and what to do ?  
As a user who experienced that problem, please let us know what would help you in that case?

**Comment by CSchulz** [comment]
I think the message of the exceptions thrown here https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/PackageObjectFactory.java#L107 could be interesting.

In my opinion any hint could be helpful for the user.

**Comment by romani** [comment]
If class is not found, we will have packages.size()+1 exceptions, we can not define what is the most representative exception, exceptions could be different.
We can not print some exception in case of failure, the only we can do it create wide message, what classes we tried to instantiate and user will see where he was wrong.

Proposed message:
"Unable to instantiate 'MyCheck' class, it is also not possible to instantiate as 'com.puppycrawl.chack.annotaton.MyCheck', 'com.puppycrawl.chack.names.MyCheck' , 'com.puppycrawl.chack.design.MyCheck', .... . Please recheck that class name is specified as canonical name or read how to configure short name usage http://checkstyle.sourceforge.net/config.html#Packages .Please also recheck that provided ClassLoader to Checker is configured correctly."

**Comment by CSchulz** [comment]
I think it would be a good way to start. Furthermore would be the catch of the *InstantiationException* interesting.
Normally it contains information about what goes wrong.

**Comment by romani** [comment]
merged
