### ISSUE TITLE
Update doc for TrailingComment

### ISSUE THREAD

**Issue by timurt** [checkstyle/checkstyle#7592]
https://checkstyle.org/config_misc.html#TrailingComment

Add example for each existing config to show what code is ok and what code cause violation.
Good example is https://checkstyle.org/config_naming.html#AbstractClassName

please play with module/Check by means of https://checkstyle.org/cmdline.html to understand how it works.

------------

PLEASE READ https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-examples

**Comment by xkarx** [comment]
I'm on it

**Comment by timurt** [comment]
@xkarx any update on this issue?

**Comment by timurt** [comment]
issue can be taken

**Comment by meSunnySrivastava** [comment]
Hello @timurt and @romani  
I would like to contribute in this 😊

**Comment by BaldDemian** [comment]
I'm on it 🚀

**Comment by ShubhraSuman** [comment]
Can I start on this one?

**Comment by stoyanK7** [comment]
I am on it.

**Comment by strkkk** [comment]
fix is merged
