### ISSUE TITLE
Update doc for UpperEll

### ISSUE THREAD

**Issue by timurt** [checkstyle/checkstyle#7596]
https://checkstyle.org/config_misc.html#UpperEll

Add example for each existing config to show what code is ok and what code cause violation.
Good example is https://checkstyle.org/config_naming.html#AbstractClassName

please play with module/Check by means of https://checkstyle.org/cmdline.html to understand how it works.

------------

PLEASE READ https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-examples

**Comment by DXTkastb** [comment]
I'm on it.

**Comment by pbludov** [comment]
Fix is merged.
