### ISSUE TITLE
Update doc for AtclauseOrder

### ISSUE THREAD

**Issue by baratali** [checkstyle/checkstyle#7597]
https://checkstyle.org/config_javadoc.html#AtclauseOrder

We need to have example for each property that we have except for `violateExecutionOnNonTightHtml` to clearly show user how Check works and change behavior when some property is used.

We need to have:
default config + example of code that shows how it work.
config with `target` override + example code to see difference in comparison with default.
config with `tagOrder` override + example code to see difference in comparison with default.
 
example code should have "ok" code and code that  cause violation (with "/violation" trailing comment).

Good example is https://checkstyle.org/config_naming.html#AbstractClassName
Look at referenced commits of #5832, to see what and how should be changed in code.

Please play with module/check by means of https://checkstyle.org/cmdline.html to understand how it works.

------------

PLEASE READ https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-examples

**Comment by ImmortalRabbit** [comment]
I am on it.

**Comment by romani** [comment]
@saksham9656,  I recommend you  to start from  this issue. It already has PR but it was abandoned. It will help you to understand contribution process on simple issue. So on more complicated issues we will not focus on process.

**Comment by saksham9656** [comment]
Thank you @romani

**Comment by saksham9656** [comment]
@romani  i could not understand the issue so would you please help in it?

**Comment by romani** [comment]
@saksham9656 , I updated issue description to be more precise. Please try again.

**Comment by romani** [comment]
@ShubhraSuman, please help us with this issue

**Comment by ShubhraSuman** [comment]
I am on it.

**Comment by ShubhraSuman** [comment]
@romani I can see PR is already merged for this issue.

**Comment by ShubhraSuman** [comment]
If something else is required, can you brief about it.

**Comment by romani** [comment]
Ohh, I confirming this, issue is resolved.
Sorry.
