### ISSUE TITLE
Update doc for JavadocType

### ISSUE THREAD

**Issue by baratali** [checkstyle/checkstyle#7601]
https://checkstyle.org/config_javadoc.html#JavadocType

Add example for each existing config to show what code is ok and what code cause violation.
Good example is https://checkstyle.org/config_naming.html#AbstractClassName
Look at referenced commits of #5832, to see what and how should be changed in code.

Please play with module/check by means of https://checkstyle.org/cmdline.html to understand how it works.

------------

PLEASE READ https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-examples

**Comment by ImmortalRabbit** [comment]
I am on it.

**Comment by vivek286** [comment]
I am on it

**Comment by shreyadenny** [comment]
I am trying to work on this issue. Could anyone guide me how I should go about it?

**Comment by KishkinJ10** [comment]
Can I work on it ?? I would like to contribute for gsoc 2022.

**Comment by romani** [comment]
sure! if you want to work on issue just make a comment "I am on it"

**Comment by KishkinJ10** [comment]
I am on it !

**Comment by KishkinJ10** [comment]
@romani Sir can you please guide me like exactly what is to be done and from where should I start ?? And in which files the additions are needed to be done.

**Comment by romani** [comment]
Please read all links in issue description, it has all details, look in git history similar updates for examples on what to update

**Comment by Shaman20** [comment]
Can I work on this issue?. If yes could you please point me to the resources that would help me to contribute. 
Thank you.

**Comment by romani** [comment]
Please send PR.
Please read doc and play with Check by CLI

**Comment by anchitbhuhan** [comment]
Can I work on this issue ?. I am currently going through how the checks works and how are they structured in the configuration xml file .

**Comment by nrmancuso** [comment]
@anchitbhuhan yes, just leave comment like "I am on it" and send PR

**Comment by romani** [comment]
issue is not resolved.
Everyone in the world is welcome to send a fix.

**Comment by HCY123902** [comment]
I am on it

**Comment by rnveach** [comment]
Fix was merged
