### ISSUE TITLE
Update doc for NonEmptyAtclauseDescription

### ISSUE THREAD

**Issue by baratali** [checkstyle/checkstyle#7604]
https://checkstyle.org/config_javadoc.html#NonEmptyAtclauseDescription

Add example for each existing config to show what code is ok and what code cause violation.
Good example is https://checkstyle.org/config_naming.html#AbstractClassName
Look at referenced commits of #5832, to see what and how should be changed in code.

Please play with module/check by means of https://checkstyle.org/cmdline.html to understand how it works.

------------

PLEASE READ https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-examples

**Comment by ImmortalRabbit** [comment]
I am on it.

**Comment by romani** [comment]
it is not resolved, as from existing examples it is not clear how Check is working and what becomes different when  property is used with new values.
We need to use `// violation` or `// ok` to show user where violation is placed.

**Comment by abhi-kr-2100** [comment]
@romani Can I be assigned this issue?

**Comment by nrmancuso** [comment]
@abhi-kr-2100 just leave comment like "I am on it" and send PR.

**Comment by abhi-kr-2100** [comment]
I am on it.

**Comment by MauryanKansara** [comment]
hey there @romani from what I understood... I think this check checks that if the description is provided for the corresponding method's or constructor's parameters in javadoc comment just before initializing it right?

Something like in the below example:- 

![Screenshot_20230129_014623](https://user-images.githubusercontent.com/86093112/215288926-f4a576af-1169-4e77-87c7-51617aac7636.png)

Am I right? 
If yes then I'd like to fix this issue.
If no then would you please explain what does this check do?

**Comment by romani** [comment]
Yes, you are right , but be careful that all characters at Javadoc is content, so it will not be violation.

Better to use 
```
// Violation below
/** @param
*/
```

**Comment by MauryanKansara** [comment]
ohkayyy thanks for your reply. I will start working on this issue as soon as possible.

**Comment by MauryanKansara** [comment]
And also can you tell me which files do I need to change? Sorry for such a silly question. I'm new to the open source so I don't know much about this.

**Comment by MauryanKansara** [comment]
#12708

**Comment by romani** [comment]
@0xbakry , if no reply from @MauryanKansara  in 2 days , please take it.
We can allow concurent implementations, only one PR be merged, both autors will take points.

**Comment by romani** [comment]
No active PR, this issue is open for all contributors , please send PR.

**Comment by coderdeadpool** [comment]
Hi @romani, I would like to work on it.

**Comment by romani** [comment]
@coderdeadpool , please send PR.

**Comment by coderdeadpool** [comment]
@romani  So basically we need to identify each existing configuration for the NonEmptyAtclauseDescription check, create a code example for each configuration, mark the specific lines of code that violate or pass the configuration, write a brief explanation of the configuration, add the examples to the NonEmptyAtclauseDescription page.

**Comment by coderdeadpool** [comment]
@romani Just to confirm, do we need to do this? Please let me know if I am mistaken so that I can create a PR.

**Comment by coderdeadpool** [comment]
And as it is shown at  https://checkstyle.org/config_naming.html#AbstractClassName
we have to add the //voilation or // ok like this


abstract class AbstractFirstClass {} // OK
abstract class SecondClass {} // violation, it should match pattern "^Abstract.+$"
class AbstractThirdClass {} // violation, must be declared 'abstract'
class FourthClass {} // OK


So whats with

> Yes, you are right , but be careful that all characters at Javadoc is content, so it will not be violation.
> 
> Better to use
> 
> ```
> // Violation below
> /** @param
> */
> ```

**Comment by coderdeadpool** [comment]
here is the example of what i think that we have to do 
'''java
To configure the check to validate @param tags:
<module name="NonEmptyAtclauseDescription">
  <property name="javadocTokens" value="PARAM_LITERAL"/>
</module>
Example:

class Test
{
/**

Violation for param "b".
@param a Some javadoc // OK
@param b
*/
public int method(String a, int b)
{
return 1;
}
}

**Comment by coderdeadpool** [comment]
@romani and we have to do this for each config. Please correct me if am wrong.

**Comment by romani** [comment]
yes to all, please send a PR.

**Comment by coderdeadpool** [comment]
@romani ok
And i have to do this changes on both NonEmptyAtclauseDescriptionCheck.java and config_javadoc.xml files ?

**Comment by romani** [comment]
Yes

**Comment by coderdeadpool** [comment]
@romani I habe created a PR.
Please check it

**Comment by Mariam-maghraby** [comment]
Can I still work on this issue?

**Comment by romani** [comment]
@Mariam-maghraby, please help with another first issue

**Comment by romani** [comment]
existing PR is  close to completion, better to take other issue

**Comment by romani** [comment]
Fix is merged
