### ISSUE TITLE
Update doc for WriteTag

### ISSUE THREAD

**Issue by baratali** [checkstyle/checkstyle#7606]
https://checkstyle.org/config_javadoc.html#WriteTag

Add example for each existing config to show what code is ok and what code cause violation.
Good example is https://checkstyle.org/config_naming.html#AbstractClassName
Look at referenced commits of #5832, to see what and how should be changed in code.

Please play with module/check by means of https://checkstyle.org/cmdline.html to understand how it works.

------------

PLEASE READ https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-examples

**Comment by ImmortalRabbit** [comment]
I am on it.

**Comment by romani** [comment]
Fix is merged
