### ISSUE TITLE
Update doc for HideUtilityClassConstructor

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#7610]
https://checkstyle.org/config_design.html#HideUtilityClassConstructor

Add example for each existing config to show what code is ok and what code cause violation.
Good example is https://checkstyle.org/config_naming.html#AbstractClassName
Look at referenced commits of #5832, to see what and how should be changed in code.

Please play with module/check by means of https://checkstyle.org/cmdline.html to understand how it works.

------------

PLEASE READ https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-examples

**Comment by sulkykookie** [comment]
I'm on it.

**Comment by strkkk** [comment]
Fix is merged
