### ISSUE TITLE
Update doc for EmptyForInitializerPad

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#7617]
https://checkstyle.org/config_whitespace.html#EmptyForInitializerPad

Add example for each existing config to show what code is ok and what code cause violation.
Good example is https://checkstyle.org/config_naming.html#AbstractClassName
Look at referenced commits of #5832, to see what and how should be changed in code.

Please play with module/check by means of https://checkstyle.org/cmdline.html to understand how it works.

------------

PLEASE READ https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-examples

**Comment by coraljain** [comment]
I’m on it.

**Comment by theexplorist** [comment]
Can I work on this issue, if it is open please assign me!

**Comment by romani** [comment]
Issue is abandoned.
@theexplorist, just make a comment "I am on it" and send Pull-request

**Comment by romani** [comment]
everyone is welcome to fix this issue, referenced code could be reused.

**Comment by Shaman20** [comment]
Can I work on this issue?

**Comment by Shaman20** [comment]
Can I work on this issue?

**Comment by romani** [comment]
Sure. Just write comment "I am on it"

**Comment by Shubhamxshah** [comment]
i am on it

**Comment by Shubhamxshah** [comment]
i am on it

**Comment by romani** [comment]
Fix is merged
