### ISSUE TITLE
Update doc for EmptyLineSeparator

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#7619]
https://checkstyle.org/config_whitespace.html#EmptyLineSeparator

Update example for each existing config to show what code is ok and what code cause violation.
Good example is https://checkstyle.org/config_naming.html#AbstractClassName
Look at referenced commits of #5832, to see what and how should be changed in code.

Please play with module/check by means of https://checkstyle.org/cmdline.html to understand how it works.

------------

PLEASE READ https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-examples

**Comment by AMFIRNAS** [comment]
I am on it

**Comment by wltan** [comment]
Looks like the same issue as #5314, maybe that one can be closed instead.

**Comment by pbludov** [comment]
> Looks like the same issue as #5314, maybe that one can be closed instead.

This is a GSOC issue, it is better to keep this one.

**Comment by ranaDherya** [comment]
Hey , can i work on this one?

**Comment by nick-mancuso** [comment]
@ranaDherya yes, please leave comment like "I am on it"

**Comment by ranaDherya** [comment]
I am on it

**Comment by akuadane** [comment]
I am on it!

**Comment by adinayyu** [comment]
I am adithya from India and as part of gsoc 2022 i want to work on open jdk code convention coverage or reconcile formatters of ides project. I want to work on this issue to contribute to checkstyle. How to work on this issue and this is my first issue

**Comment by romani** [comment]
Read issue description

**Comment by shubh220922** [comment]
Hello. I am new here. Can I know if I can work on this issue. I am interested to work on this issue.

**Comment by nick-mancuso** [comment]
> Hello. I am new here. Can I know if I can work on this issue. I am interested to work on this issue.

Yes, place a comment “I am on it” and send a PR.

**Comment by shubh220922** [comment]
I am on it

**Comment by shubh220922** [comment]
Hello. I was navigating the code base and have also gone through the links and referenced commits shared in https://github.com/checkstyle/checkstyle/issues/7619#issue-569882006 . I have the following questions:

1. For this issue am I in the right file and at the right spot to make the changes?

I have navigated to:
src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheck.java

Image indicating where javadoc has to be changed:
![image](https://user-images.githubusercontent.com/90137881/188074140-9fc48347-6ffa-4a29-ab08-f40e2150be0a.png)

2. Also after looking at the referenced commits given above #5832 . I would also have to make the necessary changes in config_whitespace.xml ? 

The xml file that I am talking about is src/xdocs/config_whitespace.xml .

Associated Image of xml file:

![image](https://user-images.githubusercontent.com/90137881/188075892-7a972ea2-ace8-4e24-933b-2ab7239b7c48.png)

I would appreciate if anyone could clarify.

**Comment by romani** [comment]
>For this issue am I in the right file and at the right spot to make the changes?

Yes

>would also have to make the necessary changes in config_whitespace.xml ?

Yes

**Comment by romani** [comment]
Fix is merged
