### ISSUE TITLE
Update doc for FileTabCharacter

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#7620]
https://checkstyle.org/config_whitespace.html#FileTabCharacter

Add example for each existing config to show what code is ok and what code cause violation.
Good example is https://checkstyle.org/config_naming.html#AbstractClassName
Look at referenced commits of #5832, to see what and how should be changed in code.

Please play with module/check by means of https://checkstyle.org/cmdline.html to understand how it works.

------------

PLEASE READ https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-examples

**Comment by Rainy0707** [comment]
I am on it

**Comment by bossever** [comment]
Hey, what type of file extension should I give example of (apart from .java) for property **fileExtensions** in check?

**Comment by strkkk** [comment]
> Hey, what type of file extension should I give example of (apart from .java) for property **fileExtensions** in check?

Some other that are commonly used, e.g. .xml or .properties

**Comment by bossever** [comment]
> > Hey, what type of file extension should I give example of (apart from .java) for property **fileExtensions** in check?
> 
> Some other that are commonly used, e.g. .xml or .properties

Is it possible to demonstrate **fileExtension** property in one source file?

**Comment by strkkk** [comment]
@bossever see example for other check with same property https://checkstyle.sourceforge.io/config_misc.html#NewlineAtEndOfFile_Examples

**Comment by romani** [comment]
fix is merged
