### ISSUE TITLE
Update doc for TypecastParenPad

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#7630]
https://checkstyle.org/config_whitespace.html#TypecastParenPad

Add example for each existing config to show what code is ok and what code cause violation.
Good example is https://checkstyle.org/config_naming.html#AbstractClassName
Look at referenced commits of #5832, to see what and how should be changed in code.

Please play with module/check by means of https://checkstyle.org/cmdline.html to understand how it works.

------------

PLEASE READ https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-examples

**Comment by sulkykookie** [comment]
I'm on it.

**Comment by romani** [comment]
@sulkykookie , I removed your "I am on it" on all issues except for 2, you have no pull requests  (PRs) at all. Please do not assign on yourself a lot of issues, take new assignment only if you are waiting for review of all previous PRs.

**Comment by sulkykookie** [comment]
> @sulkykookie , I removed your "I am on it" on all issues except for 2, you have no pull requests (PRs) at all. Please do not assign on yourself a lot of issues, take new assignment only if you are waiting for review of all previous PRs.

Hi,
I don't have a PR as of now as I'm stuck with a gsoc-third-issue and I haven't got any replies on it since 5 days and that's why im not able to proceed with it.

Link:
https://github.com/checkstyle/checkstyle/issues/7922

**Comment by strkkk** [comment]
Fix is merged
