### ISSUE TITLE
Update doc for FallThrough

### ISSUE THREAD

**Issue by strkkk** [checkstyle/checkstyle#7640]
https://checkstyle.org/config_coding.html#FallThrough

Add example for each existing config to show what code is ok and what code cause violation.
Good example is https://checkstyle.org/config_naming.html#AbstractClassName
Look at referenced commits of #5832, to see what and how should be changed in code.

Please play with module/check by means of https://checkstyle.org/cmdline.html to understand how it works.

------------

PLEASE READ https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-examples

**Comment by Rainy0707** [comment]
I am on it

**Comment by anhminhtran235** [comment]
I am on it

**Comment by romani** [comment]
@anhminhtran235, thanks a lot for help to fix this issue.

Fix is Merged.
