### ISSUE TITLE
Update doc for IllegalInstantiation

### ISSUE THREAD

**Issue by strkkk** [checkstyle/checkstyle#7643]
https://checkstyle.org/config_coding.html#IllegalInstantiation

Add example for each existing config to show what code is ok and what code cause violation.
Good example is https://checkstyle.org/config_naming.html#AbstractClassName
Look at referenced commits of #5832, to see what and how should be changed in code.

Please play with module/check by means of https://checkstyle.org/cmdline.html to understand how it works.

------------

PLEASE READ https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-examples

**Comment by Rainy0707** [comment]
I am on it

**Comment by AmplifiedHuman** [comment]
I am on it

**Comment by AmplifiedHuman** [comment]
I am getting this error after running `mvn clean verify`
`AllTestsTest.testAllTestsHaveProductionCode:68->walk:81->lambda$testAllTestsHaveProductionCode$3:69->grabAllFiles:115->getSimplePath:253 » StringIndexOutOfBounds
`
Is there a specific reason why this is happening?

**Comment by romani** [comment]
@AmplifiedHuman , please share full log of `mvn verify` execution by gitst.github.com , and please share your code changes. Can you send a PR with changes.

**Comment by himanshurijal** [comment]
I am on it.

**Comment by himanshurijal** [comment]
I am on it.

**Comment by romani** [comment]
fix is merged.
