### ISSUE TITLE
Update doc for IllegalThrows

### ISSUE THREAD

**Issue by strkkk** [checkstyle/checkstyle#7644]
https://checkstyle.org/config_coding.html#IllegalThrows

Add example for each existing config to show what code is ok and what code cause violation.
Good example is https://checkstyle.org/config_naming.html#AbstractClassName
Look at referenced commits of #5832, to see what and how should be changed in code.

Please play with module/check by means of https://checkstyle.org/cmdline.html to understand how it works.

------------

PLEASE READ https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-examples

**Comment by jokowncode** [comment]
I am on it

**Comment by jokowncode** [comment]
Excuse me, I found that Chinese garbled will appear in the output of maven, resulting in the failure of verify, so I added `< argLine >-Dfile.encoding=UTF-8 < / argLine >` to the properties of maven. Is that okay? @strkkk

**Comment by jokowncode** [comment]
When I was doing maven verify, there was an error. How can I solve it?
`[ERROR] ……\ant-phase-verify.xml:164: Checkstyle failed: Got 58 errors and 0 warnings.
[ERROR] around Ant part ...<ant antfile="config/ant-phase-verify.xml"/>... @ 8:47 in ……\target\antrun\build-main.xml
[ERROR] -> [Help 1]`

**Comment by jokowncode** [comment]
@strkkk @romani 
When I start maven verify ,there are some errors, involves other files, I don not know should I modity them or how I solve it?
`[checkstyle] [ERROR] ……\src\test\java\com\puppycrawl\tools\checkstyle\internal\powermock\AuditEventDefaultFormatterPowerTest.java:23:1: not allowed import： org.mockito.Mockito.when 。 [ImportControlTest]
[checkstyle] [ERROR] ……\src\test\java\com\puppycrawl\tools\checkstyle\internal\powermock\AuditEventDefaultFormatterPowerTest.java:27:1: not allowed import： org.powermock.api.mockito.PowerMockito 。 [ImportControlTest]
[checkstyle] [ERROR] ……\src\test\java\com\puppycrawl\tools\checkstyle\internal\powermock\AuditEventDefaultFormatterPowerTest.java:28:1: not allowed import： org.powermock.core.classloader.annotations.PrepareForTest 。 [ImportControlTest]
[checkstyle] [ERROR] ……\src\test\java\com\puppycrawl\tools\checkstyle\internal\powermock\AuditEventDefaultFormatterPowerTest.java:29:1: not allowed import： org.powermock.modules.junit4.PowerMockRunner 。 [ImportControlTest]
[checkstyle] [ERROR] ……\src\test\java\com\puppycrawl\tools\checkstyle\internal\powermock\CheckstyleAntTaskPowerTest.java:25:1: not allowed import： org.mockito.Mockito.when 。 [ImportControlTest]
[checkstyle] [ERROR] ……\src\test\java\com\puppycrawl\tools\checkstyle\internal\powermock\CheckstyleAntTaskPowerTest.java:26:1: not allowed import： org.powermock.api.mockito.PowerMockito.mockStatic 。 [ImportControlTest]
[checkstyle] [ERROR] ……\src\test\java\com\puppycrawl\tools\checkstyle\internal\powermock\CheckstyleAntTaskPowerTest.java:40:1: not allowed import： org.powermock.api.mockito.PowerMockito 。 [ImportControlTest]
[checkstyle] [ERROR] ……\src\test\java\com\puppycrawl\tools\checkstyle\internal\powermock\CheckstyleAntTaskPowerTest.java:41:1: not allowed import： org.powermock.core.classloader.annotations.PrepareForTest 。 [ImportControlTest]
[checkstyle] [ERROR] ……\src\test\java\com\puppycrawl\tools\checkstyle\internal\powermock\CheckstyleAntTaskPowerTest.java:42:1: not allowed import： org.powermock.modules.junit4.PowerMockRunner 。 [ImportControlTest]
[checkstyle] [ERROR] ……\src\test\java\com\puppycrawl\tools\checkstyle\internal\powermock\CommonUtilPowerTest.java:25:1: not allowed import： org.powermock.api.mockito.PowerMockito.mock 。 [ImportControlTest]
[checkstyle] [ERROR] ……\src\test\java\com\puppycrawl\tools\checkstyle\internal\powermock\CommonUtilPowerTest.java:26:1: not allowed import： org.powermock.api.mockito.PowerMockito.mockStatic 。 [ImportControlTest]
[checkstyle] [ERROR] ……\src\test\java\com\puppycrawl\tools\checkstyle\internal\powermock\CommonUtilPowerTest.java:27:1: not allowed import： org.powermock.api.mockito.PowerMockito.when 。 [ImportControlTest]
[checkstyle] [ERROR] ……\src\test\java\com\puppycrawl\tools\checkstyle\internal\powermock\CommonUtilPowerTest.java:34:1: not allowed import： org.mockito.Mockito 。 [ImportControlTest]
[checkstyle] [ERROR] ……\src\test\java\com\puppycrawl\tools\checkstyle\internal\powermock\CommonUtilPowerTest.java:35:1: not allowed import： org.powermock.core.classloader.annotations.PrepareForTest 。 [ImportControlTest]
[checkstyle] [ERROR] ……\src\test\java\com\puppycrawl\tools\checkstyle\internal\powermock\CommonUtilPowerTest.java:36:1: not allowed import： org.powermock.modules.junit4.PowerMockRunner 。 [ImportControlTest]
[checkstyle] [ERROR] ……\src\test\java\com\puppycrawl\tools\checkstyle\internal\powermock\ConfigurationLoaderPowerTest.java:24:1: not allowed import： org.powermock.api.mockito.PowerMockito.when 。 [ImportControlTest]
[checkstyle] [ERROR] ……\src\test\java\com\puppycrawl\tools\checkstyle\internal\powermock\ConfigurationLoaderPowerTest.java:30:1: not allowed import： org.powermock.api.mockito.PowerMockito 。 [ImportControlTest]
……`

**Comment by strkkk** [comment]
@jokowncode have you made any changes to code?

**Comment by jokowncode** [comment]
@strkkk Yes, I haven't changed the code, only the xml file and java doc. And add a `< argLine >-Dfile.encoding=UTF-8 < / argLine >` to the properties of maven to solve the Chinese garbled problem.

**Comment by strkkk** [comment]
Do you run `mvn clean verify`? Because you said that you run `mvn verify`

**Comment by jokowncode** [comment]
@strkkk Yes, the result is the same.

**Comment by rnveach** [comment]
> Chinese garbled will appear in the output of maven

Can you provide us a full console output of your run `mvn clean verify` run so we can see what you are seeing.

Is your OS set to another language by default?

**Comment by jokowncode** [comment]
@rnveach Yes,my OS's default language is Chinese.
[maven log.txt](https://github.com/checkstyle/checkstyle/files/4349224/maven.log.txt)

**Comment by rnveach** [comment]
Thanks, this explains it all. Checkstyle uses message suppressions for suppressing very specific violations. Unfortunately suppressing by message requires the exact message and most users and CI use english by default. Since your on a chinese OS, the default message used is Chinese and this doesn't match up the english.

To get around this issue, you would need to pass in a maven override for the language and force it to English. You can also just use the PR's CI as a way to run verify.

**Comment by jokowncode** [comment]
ok,thanks for your help. I will try to use the PR to run verify.

**Comment by romani** [comment]
@jokowncode , if you find how to provide maven locale settings  it would be awesome , we will place them in our wiki. We try our best to make build process to be less problematic.
We might to force checkstyle build to use EN locale to pass build at any locale/country.

It is valid issue for our issue tracker that build is not passing on Chineese (non English) locale. Please create issue on us.

**Comment by jokowncode** [comment]
Sure,It's my pleasure. 
the solution is to add the parameter`-Duser.language=en-Duser.region=GB `when running maven clean verify. 
For example, in IDEA, you can modify it in `File-> Setting-> Build,Execution,Deployment-> Build Tools-> Maven-> Runner-> VM options`. 
I would like you to add this in [url](https://checkstyle.sourceforge.io/beginning_development.html#Starting_Development) to help people (non English locale) to deployment.Thank you.

**Comment by strkkk** [comment]
Fix is merged
