### ISSUE TITLE
Update doc for ModifiedControlVariable

### ISSUE THREAD

**Issue by strkkk** [checkstyle/checkstyle#7649]
https://checkstyle.org/config_coding.html#ModifiedControlVariable

Add example for each existing config to show what code is ok and what code cause violation.
Good example is https://checkstyle.org/config_naming.html#AbstractClassName
Look at referenced commits of #5832, to see what and how should be changed in code.

Please play with module/check by means of https://checkstyle.org/cmdline.html to understand how it works.

------------

PLEASE READ https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-examples

**Comment by AnishaSrivastava1411** [comment]
I am working on this issue.

**Comment by SGanguly1999** [comment]
I am on it...

**Comment by SGanguly1999** [comment]
@strkkk I am having a doubt ...Do i need to have the for loop in the format 
`for(int i=0;i<n;i++)
{
}'

I was just experimenting with this one and found out that  it passes without any errors


`package com.company;
class Hello
{
    public static void main(String args[])
    {
        for(int a[]={0};a[0]<4;a[0]++)
        {
            a[0]++;
        }
    }`
Should the ModifiedControlVariable check  detect this?

**Comment by strkkk** [comment]
`Should the ModifiedControlVariable check detect this?`
Interesting case, it may be a bug.
Please create a new issue for it

**Comment by SGanguly1999** [comment]
Okay
