### ISSUE TITLE
Update doc for MultipleStringLiterals

### ISSUE THREAD

**Issue by strkkk** [checkstyle/checkstyle#7650]
https://checkstyle.org/config_coding.html#MultipleStringLiterals

Add example for each existing config to show what code is ok and what code cause violation.
Good example is https://checkstyle.org/config_naming.html#AbstractClassName
Look at referenced commits of #5832, to see what and how should be changed in code.

Please play with module/check by means of https://checkstyle.org/cmdline.html to understand how it works.

------------

PLEASE READ https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-examples

**Comment by Jalend15** [comment]
i am working on it

**Comment by Jalend15** [comment]
I created a pull request

**Comment by Jalend15** [comment]
[ERROR] symbol:   class string
[ERROR] location: class com.puppycrawl.tools.checkstyle.checks.MSL
[ERROR] /home/jalend-15/checkstyle/src/test/java/com/puppycrawl/tools/checkstyle/checks/MSL.java:[127,13] cannot find symbol



i am unable to use string i java program

**Comment by rnveach** [comment]
@Jalend15 Please point to PR where you have issue. There is no linked PR here.

**Comment by BaldDemian** [comment]
I'm working on it

**Comment by romani** [comment]
Merged
