### ISSUE TITLE
Update doc for RequireThis

### ISSUE THREAD

**Issue by strkkk** [checkstyle/checkstyle#7656]
https://checkstyle.org/config_coding.html#RequireThis

Add example for each existing config to show what code is ok and what code cause violation.
Good example is https://checkstyle.org/config_naming.html#AbstractClassName
Look at referenced commits of #5832, to see what and how should be changed in code.

Please play with module/check by means of https://checkstyle.org/cmdline.html to understand how it works.

------------

PLEASE READ https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-examples

**Comment by sudo-andro** [comment]
https://checkstyle.org/config_coding.html#RequireThis_Examples contains the example right? What needs to be added then?

**Comment by romani** [comment]
@sudo-andro  , I placed in description link on how PR should looks like , please do.

**Comment by bossever** [comment]
Can I work on this?

**Comment by strkkk** [comment]
@bossever yes, PR is welcome

**Comment by bossever** [comment]
Do we have to update the config files as well, or is that handled by the build process?

**Comment by strkkk** [comment]
There is no need to update config files, only xdoc xml and javadoc for check. Please see merged PRs for similar issues

**Comment by strkkk** [comment]
Fix is merged
