### ISSUE TITLE
Update doc for VariableDeclarationUsageDistance

### ISSUE THREAD

**Issue by strkkk** [checkstyle/checkstyle#7663]
https://checkstyle.org/config_coding.html#VariableDeclarationUsageDistance

Add example for each existing config to show what code is ok and what code cause violation.
Good example is https://checkstyle.org/config_naming.html#AbstractClassName
Look at referenced commits of #5832, to see what and how should be changed in code.

Please play with module/check by means of https://checkstyle.org/cmdline.html to understand how it works.

------------

PLEASE READ https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-examples

**Comment by sudo-andro** [comment]
Aren't the examples already there- https://checkstyle.org/config_coding.html#VariableDeclarationUsageDistance_Examples
What should be added as per the issue?

**Comment by romani** [comment]
We need config for each code sample

**Comment by ImmortalRabbit** [comment]
I am on it.

**Comment by bossever** [comment]
I'm on it.

**Comment by bossever** [comment]
## Help Needed ##

On making simple changes to the VariableDeclarationUsageDistance.java file, and running `mvn clean verify`, I get this error, and cannot seem to get rid of it.
```
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   XdocsJavaDocsTest.testAllCheckSectionJavaDocs:182->examineCheckSection:209 »  ...
[INFO] 
[ERROR] Tests run: 3464, Failures: 0, Errors: 1, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:50 min
[INFO] Finished at: 2021-01-28T23:42:58+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project checkstyle: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/ayushman/Documents/Development/checkstyle/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

```

Detailed Test Result `com.puppycrawl.tools.checkstyle.internal.XdocsJavaDocsTest.txt` :
```
-------------------------------------------------------------------------------
Test set: com.puppycrawl.tools.checkstyle.internal.XdocsJavaDocsTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.94 s <<< FAILURE! - in com.puppycrawl.tools.checkstyle.internal.XdocsJavaDocsTest
testAllCheckSectionJavaDocs  Time elapsed: 1.939 s  <<< ERROR!
java.lang.Error: Error was thrown while processing src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/VariableDeclarationUsageDistanceCheck.java
	at com.puppycrawl.tools.checkstyle.internal.XdocsJavaDocsTest.examineCheckSection(XdocsJavaDocsTest.java:209)
	at com.puppycrawl.tools.checkstyle.internal.XdocsJavaDocsTest.testAllCheckSectionJavaDocs(XdocsJavaDocsTest.java:182)
Caused by: org.opentest4j.AssertionFailedError: 
VariableDeclarationUsageDistance's class-level JavaDoc ==> expected: <old Javadoc comment> but was:  <changed Javadoc comment>
```

The only change I made was removing some lines from `Description` paragraph (to be moved to `examples`).

It seems that opentest4j expected the old javadoc but found out the contents have been changed. Why does this happen? And how can I change contents of a Javadoc without this error?

**Comment by strkkk** [comment]
@bossever you need change xml docs as well

**Comment by bossever** [comment]
@strkkk Thanks a lot, that fixed it. 
But I have a question, the code that I removed from javadoc was in the wrong section (right after description), but it was in the correct section in xml file (`Notes` section after `Examples`). If the two files were different, how was the build passing then?

**Comment by strkkk** [comment]
@bossever not sure what you mean.
I think you can submit a PR with your changes, it will be easier to see what the problem is

**Comment by qiqistyle** [comment]
it looks like that I encounter a bug for this config ,which was copied in checkstyle website
config.xml
<?xml version="1.0"?>
        <!DOCTYPE module PUBLIC
                "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
                "http:///www.puppycrawl.com/dtds/configuration_1_3.dtd">
<module name="VariableDeclarationUsageDistance">
  <module name="VariableDeclarationUsageDistance">
  <property name="allowedDistance" value="4"/>
  <property name="ignoreVariablePattern" value="^temp.*"/>
  <property name="validateBetweenScopes" value="true"/>
  <property name="ignoreFinal" value="false"/>
</module>
 </module>

  java -jar checkstyle-8.39-all.jar -c config.xml test.java
 then



<img width="1436" alt="image" src="https://user-images.githubusercontent.com/48356218/106275655-28c8b200-6271-11eb-9774-bb43f197edfd.png">

**Comment by strkkk** [comment]
@qiqistyle config in your example is incomplete and invalid. 
Can you point to config you copied?

**Comment by qiqistyle** [comment]
> Can you point to config you copied?

<module name="VariableDeclarationUsageDistance">
  <property name="allowedDistance" value="4"/>
  <property name="ignoreVariablePattern" value="^temp.*"/>
  <property name="validateBetweenScopes" value="true"/>
  <property name="ignoreFinal" value="false"/>
</module>

**Comment by qiqistyle** [comment]
<module name="VariableDeclarationUsageDistance">
  <module name="VariableDeclarationUsageDistance">
  <property name="allowedDistance" value="4"/>
  <property name="ignoreVariablePattern" value="^temp.*"/>
  <property name="validateBetweenScopes" value="true"/>
  <property name="ignoreFinal" value="false"/>
</module>
        



> @qiqistyle config in your example is incomplete and invalid.
> Can you point to config you copied?

**Comment by qiqistyle** [comment]
oh sorry ,I first use this comment
config.xml
```
<module name="VariableDeclarationUsageDistance">
  <module name="VariableDeclarationUsageDistance">
  <property name="allowedDistance" value="4"/>
  <property name="ignoreVariablePattern" value="^temp.*"/>
  <property name="validateBetweenScopes" value="true"/>
  <property name="ignoreFinal" value="false"/>
</module>
  ````      
java -jar checkstyle-8.39-all.jar -c config.xml test.java

Exception in thread "main" java.lang.ClassCastException: class com.puppycrawl.tools.checkstyle.checks.coding.VariableDeclarationUsageDistanceCheck cannot be cast to class com.puppycrawl.tools.checkstyle.api.RootModule (com.puppycrawl.tools.checkstyle.checks.coding.VariableDeclarationUsageDistanceCheck and com.puppycrawl.tools.checkstyle.api.RootModule are in unnamed module of loader 'app')
	at com.puppycrawl.tools.checkstyle.Main.getRootModule(Main.java:458)
	at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:380)
	at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:331)
	at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:190)
	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:125)

**Comment by strkkk** [comment]
@qiqistyle this is not a valid config either. This snippet is only to show configuration of specific check (not whole checkstyle config)
Whole config looks something like https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/google_checks.xml

**Comment by bossever** [comment]
> @bossever not sure what you mean.
> I think you can submit a PR with your changes, it will be easier to see what the problem is

I have created PR, have mentioned issue in detail.

**Comment by romani** [comment]
fix is merged
