### ISSUE TITLE
Update doc for InnerAssignment

### ISSUE THREAD

**Issue by strkkk** [checkstyle/checkstyle#7666]
https://checkstyle.org/config_coding.html#InnerAssignment

Add example for each existing config to show what code is ok and what code cause violation.
Good example is https://checkstyle.org/config_naming.html#AbstractClassName
Look at referenced commits of #5832, to see what and how should be changed in code.

Please play with module/check by means of https://checkstyle.org/cmdline.html to understand how it works.

------------

PLEASE READ https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-examples

**Comment by anubh-v** [comment]
I am on it.

**Comment by romani** [comment]
@anubh-v , I places in description link on how PR should looks like, please do

**Comment by strkkk** [comment]
Fix is merged
