### ISSUE TITLE
Update doc for MultipleVariableDeclarations

### ISSUE THREAD

**Issue by strkkk** [checkstyle/checkstyle#7669]
https://checkstyle.org/config_coding.html#MultipleVariableDeclarations

Add example for each existing config to show what code is ok and what code cause violation.
Good example is https://checkstyle.org/config_naming.html#AbstractClassName
Look at referenced commits of #5832, to see what and how should be changed in code.

Please play with module/check by means of https://checkstyle.org/cmdline.html to understand how it works.

------------

PLEASE READ https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-examples

**Comment by mrrobot-2000** [comment]
Hi! I have submitted a PR to fix this. Please see #7681 @strkkk .

**Comment by strkkk** [comment]
Fix is merged
