### ISSUE TITLE
Update doc for NoFinalizer

### ISSUE THREAD

**Issue by strkkk** [checkstyle/checkstyle#7671]
https://checkstyle.org/config_coding.html#NoFinalizer

Add example for each existing config to show what code is ok and what code cause violation.
Good example is https://checkstyle.org/config_naming.html#AbstractClassName
Look at referenced commits of #5832, to see what and how should be changed in code.

Please play with module/check by means of https://checkstyle.org/cmdline.html to understand how it works.

------------

PLEASE READ https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-examples

**Comment by OmarShawky1** [comment]
i'm on it

**Comment by OmarShawky1** [comment]
Unfortunately, although i know what is traversing tree, token, object.Finalize, i do not understand what is requested from me, i can't see what is messing besides i do not know how does a part of the code work (described in the picture
![image](https://user-images.githubusercontent.com/51538094/75609521-05056500-5b12-11ea-8dba-a048738005b5.png)

**Comment by strkkk** [comment]
@OmarShawky1 Documentation for check should be extended with example of code with violations

**Comment by OmarShawky1** [comment]
i tried to better explain the function but to no avail, although i really understand what is a finalizer  & token, parent etc.... but i do not know what exactly i should do here.
![image](https://user-images.githubusercontent.com/51538094/75655572-d222b480-5c6a-11ea-9a76-e820dbc7cc3c.png)

i tried to imitate an example such as [https://checkstyle.org/config_regexp.html#RegexpSinglelineJava](url) but i did not understand the command line arguments so much although i used checkstyle as a plugin on IntelliJ on my previous projects

**Comment by strkkk** [comment]
This check reports violation if class contains Object#finalize() method.
Doc should be updated to show what is reported and what is ok.

The code is checking method name (that it is equal to "finalize") and then checks there is no parameters for it.

**Comment by OmarShawky1** [comment]
I Assume that i created a PR correctly, this is the [PR](https://github.com/checkstyle/checkstyle/pull/7770)

**Comment by OmarShawky1** [comment]
I mentioned an example for the check violation & non-violation, i do not know what is the problem now

**Comment by strkkk** [comment]
Fix is merged
