### ISSUE TITLE
Update doc for OverloadMethodsDeclarationOrder

### ISSUE THREAD

**Issue by strkkk** [checkstyle/checkstyle#7672]
https://checkstyle.org/config_coding.html#OverloadMethodsDeclarationOrder

Add example for each existing config to show what code is ok and what code cause violation.
Good example is https://checkstyle.org/config_naming.html#AbstractClassName
Look at referenced commits of #5832, to see what and how should be changed in code.

Please play with module/check by means of https://checkstyle.org/cmdline.html to understand how it works.

------------

PLEASE READ https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-examples

**Comment by thanujayalath** [comment]
I will work on this

**Comment by thanujayalath** [comment]
@strkkk this already has examples. Do we need anything else added there?

**Comment by strkkk** [comment]
@thanujayalath Probably not. Regarding this check - examples section shouldbe modified to follow common template (first config example, after code examples of violations/ok lines), and code examples should be updated to clearly reflect where is violation.

**Comment by rnveach** [comment]
It is also best to think of this from user who knows not much to little to nothing.

Definition of what an `overloaded` method could be added to make documentation clearer. Template order for examples was discussed. Think about if there is something more to examples that could be added to provide more explanation to user.

**Comment by romani** [comment]
Fix is merged
