### ISSUE TITLE
update doc for CustomImportOrder

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#7686]
https://checkstyle.org/config_imports.html#CustomImportOrder

Add example for each existing config to show what code is ok and what code cause violation.
Good example is https://checkstyle.org/config_naming.html#AbstractClassName
Please add examples for all properties of Check.

look at referenced commits of #5832, to see what and how should be changed in code.

please play with module/Check by means of https://checkstyle.org/cmdline.html to understand how it works.

------------

PLEASE READ https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-examples

**Comment by kasince2k** [comment]
I am on it!

**Comment by SGanguly1999** [comment]
@romani I want to do this.Is it availaible?

**Comment by romani** [comment]
@SGanguly1999, please send fix

**Comment by SGanguly1999** [comment]
@romani 
I want to run the checkstyle with ...

<module name="CustomImportOrder">
  <property name="customImportOrderRules"
    value="STATIC###STANDARD_JAVA_PACKAGE###SPECIAL_IMPORTS"/>
  <property name="specialImportsRegExp" value="^org\."/>
  <property name="sortImportsInGroupAlphabetically" value="true"/>
  <property name="separateLineBetweenGroups" value="true"/>
</module>
        ....this configuration.I have created a config.xml file but how to run it in command line for this specific configuration.

**Comment by SGanguly1999** [comment]
Which files should i need to update in the repository?

**Comment by romani** [comment]
Please read all link in issue description, please review similar issues that are marked by the same label, you can find related to them PRs with examples of how to do updates

**Comment by SGanguly1999** [comment]
Okay sir,I will look into those

**Comment by Utkarshn10** [comment]
I am on it!!

**Comment by SGanguly1999** [comment]
package com.company;

import static java.lang.Math.*;   // OK
import static java.util.Scanner;//OK

import java.io.*; // OK
import java.net.*; //OK
import java.time.*;      //OK
import javax.net.ssl.SSLContext; //OK
import javax.net.ssl.TrustManager; //OK
import javax.net.ssl.X509TrustManager;//OK

import org.apache.http.conn.ClientConnectionManager; // OK
import org.apache.http.conn.scheme.Scheme; //OK
import org.apache.http.conn.scheme.SchemeRegistry;//OK
import org.apache.http.conn.ssl.SSLSocketFactory;    //OK
import org.apache.http.impl.client.DefaultHttpClient;  //OK

@romani     Sir when I am  running this code with the config file below:---

<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
  <module name="TreeWalker">
    <property name="tabWidth" value="7"/>
    <module name="CustomImportOrder">
      <property name="customImportOrderRules"
                value="STATIC###SAME_PACKAGE(3)###STANDARD_JAVA_PACKAGE###SPECIAL_IMPORTS"/>
      <property name="specialImportsRegExp" value="^org\."/>
      <property name="sortImportsInGroupAlphabetically" value="true"/>
      <property name="separateLineBetweenGroups" value="true"/>
    </module>
  </module>
</module>



It is  compiling perfectly without errors.But the files that are imported from  javax.net.ssl.  should be in SAME PACKAGE group and thus should be above the STANDARD JAVA PACKAGE...It is not showing any error message for it. This thing i can't understand properly.

**Comment by romani** [comment]
fix is merged
