### ISSUE TITLE
update doc for ImportOrder

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#7687]
https://checkstyle.org/config_imports.html#ImportOrder

Add example for each existing config to show what code is ok and what code cause violation.
Good example is https://checkstyle.org/config_naming.html#AbstractClassName
Please add examples for all properties of Check.

look at referenced commits of #5832, to see what and how should be changed in code.

please play with module/Check by means of https://checkstyle.org/cmdline.html to understand how it works.

------------

PLEASE READ https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-examples

**Comment by davidmkwon** [comment]
I am on it.

**Comment by mradulrathore** [comment]
I'm on it.

**Comment by ropereraLK** [comment]
Shall I work on it... ???

**Comment by strkkk** [comment]
@ropereraLK you are welcome to submit PR

**Comment by aryaniiit002** [comment]
Examples for ImportOrder are already present [here](https://checkstyle.org/config_imports.html#ImportOrder)
Does that mean there is no issue here?

**Comment by romani** [comment]
@aryaniiit002 , we need update for examples to show
default config
code sample for default
config with each property
code example to show how each property change behavior (it is better to have same code sample in each example to visually see a difference, but this not critical is such complicated Check )

I briefly reviewed doc, looks like default example is missed.

**Comment by aryaniiit002** [comment]
sorry i didnt get it, [ImportOrderCheck](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheck.java)  is already present 
so what else i have to do is - what u have mentioned above?

**Comment by romani** [comment]
`<module name="ImportOrder"/>` and java code example should be added

**Comment by aryaniiit002** [comment]
I think i got it,
Can i work on this please?
you probably figured out this is my 1st time so please help me on PR later...
Thanks

**Comment by strkkk** [comment]
> Can i work on this please?

Sure

**Comment by kshivam953** [comment]
@romani @strkkk I wanna work on this issue. Please assign me this since I'm a new to this repo so, please help me through. Please help me finding where to start first.

**Comment by romani** [comment]
do update in javadoc of this InportOrderCheck and run "mvn verify" it will guide you on what else to update.
you will need to mirror/duplicate changes at javadoc to https://github.com/checkstyle/checkstyle/blob/72f2aea1927c58b23aee6c30aa659b7669c6bdb6/src/xdocs/config_imports.xml#L330

**Comment by romani** [comment]
fix is merged
