### ISSUE TITLE
update doc for RedundantImport

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#7688]
https://checkstyle.org/config_imports.html#RedundantImport

Add example for each existing config to show what code is ok and what code cause violation.
Good example is https://checkstyle.org/config_naming.html#AbstractClassName
Please add examples for all properties of Check.

look at referenced commits of #5832, to see what and how should be changed in code.

please play with module/Check by means of https://checkstyle.org/cmdline.html to understand how it works.

------------

PLEASE READ https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-examples

**Comment by sudo-karx** [comment]
I am on it.

**Comment by mihirbachhav025** [comment]
I am on it

**Comment by mihirbachhav025** [comment]
Hey, I have not understood the meaning of Add example for each existing config to show what code is ok and what code causes a violation. Please add examples for all properties of Check. Like in the abstract class example given above examples cover how an abstract class should be written. So for redundant import where can I see the existing config and how to write according to that?

**Comment by romani** [comment]
add example code before "Parent ...."
https://github.com/checkstyle/checkstyle/blob/b925c65a07ff1138a66be6ce0372e8ea6cfe7dd2/src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/RedundantImportCheck.java#L47-L51

take a look at other Check classes for example.

**Comment by mihirbachhav025** [comment]
so I have to add code in this file and not in the config_importsd.xml file present in the config dir?

**Comment by qiqistyle** [comment]
hi，i create a pr, but system not accept my code, could you give me some advice for my pr? Thanks

**Comment by gurleennsidhuu** [comment]
I am on it.

**Comment by gurleennsidhuu** [comment]
I am on it.

**Comment by romani** [comment]
everyone is welcome to fix this issue, referenced code could be reused.

**Comment by puneetsinghania** [comment]
Is this issue open to be worked upon? Can you please provide a sample of how the documentation solution should be approached and what should be the potential solution?

**Comment by romani** [comment]
Please read attentively issue description and all linked pages
