### ISSUE TITLE
update doc for BooleanExpressionComplexity

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#7689]
https://checkstyle.org/config_metrics.html#BooleanExpressionComplexity

Add example for each existing config to show what code is ok and what code cause violation.
Good example is https://checkstyle.org/config_naming.html#AbstractClassName
Please add examples for all properties of Check.

look at referenced commits of #5832, to see what and how should be changed in code.

please play with module/Check by means of https://checkstyle.org/cmdline.html to understand how it works.

------------

PLEASE READ https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-examples

**Comment by akki111singh** [comment]
I am on it

**Comment by akki111singh** [comment]
Current Look
![Screenshot from 2020-03-01 11-07-05](https://user-images.githubusercontent.com/45921807/75620431-ec975800-5bae-11ea-8906-7eed01b26883.png)

**Comment by akki111singh** [comment]
Output of added example:
$ cat config.xml

  <?xml version="1.0"?>
  <!DOCTYPE module PUBLIC
      "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
      "https://checkstyle.org/dtds/configuration_1_3.dtd">
  <module name="Checker">
  <module name="TreeWalker">
    <module name="BooleanExpressionComplexity">
      <property name="max" value="2"/>
    </module>
  </module>
  </module>

$ cat Test.java

public class Test {
      public static void main(String args[]) {
            boolean a = true;
            boolean b = false;
            
            boolean c = (a & b) | a; // OK, since max Boolean expression complexity is 2 (max allowed is 2).
            boolean d = (!a & b) | (a & !b); // violation, Boolean expression complexity is 3 (max allowed is 2).
          }
        }

**Comment by akki111singh** [comment]
Ouput of default examples
![Screenshot from 2020-03-01 11-24-46](https://user-images.githubusercontent.com/45921807/75620521-d047eb00-5baf-11ea-9573-d787b9278609.png)
![Screenshot from 2020-03-01 11-26-45](https://user-images.githubusercontent.com/45921807/75620523-d4740880-5baf-11ea-9afb-55de1eb8305b.png)

**Comment by rnveach** [comment]
Fix was merged
