### ISSUE TITLE
update doc for ClassFanOutComplexity

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#7691]
https://checkstyle.org/config_metrics.html#ClassFanOutComplexity

Add example for each existing config to show what code is ok and what code cause violation.
Good example is https://checkstyle.org/config_naming.html#AbstractClassName
Please add examples for all properties of Check.

look at referenced commits of #5832, to see what and how should be changed in code.

please play with module/Check by means of https://checkstyle.org/cmdline.html to understand how it works.

------------

PLEASE READ https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-examples

**Comment by shashwat70** [comment]
Sir, I updated the .xml and .java files related to the above issue. But, unfortunately it's giving me a build error when I run mvn verify. The error is as follows. Please guide me.
<img width="960" alt="2020-03-05" src="https://user-images.githubusercontent.com/52609734/76010972-c7ea0a00-5f39-11ea-8ede-15c13d492091.png">

**Comment by shashwat70** [comment]
@romani please respond.

**Comment by rnveach** [comment]
@shashwat70 The errors are pretty simple. Did you try reading the message and looking in the files at the positions specified? The first one is saying your line has whitespace ending the line and can be removed. The second is saying you have 2 blank lines back to back and one can be removed.

**Comment by shashwat70** [comment]
> @shashwat70 The errors are pretty simple. Did you try reading the message and looking in the files at the positions specified? The first one is saying your line has whitespace ending the line and can be removed. The second is saying you have 2 blank lines back to back and one can be removed.

Thank You!

**Comment by strkkk** [comment]
Fix is merged
