### ISSUE TITLE
update doc for JavaNCSS

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#7693]
https://checkstyle.org/config_metrics.html#JavaNCSS

Add example for each existing config to show what code is ok and what code cause violation.
Good example is https://checkstyle.org/config_naming.html#AbstractClassName
Please add examples for all properties of Check.

look at referenced commits of #5832, to see what and how should be changed in code.

please play with module/Check by means of https://checkstyle.org/cmdline.html to understand how it works.

------------

PLEASE READ https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-examples

**Comment by Gaurav-Punjabi** [comment]
@romani I'm on it. I just had one query. The default example for JavaNCSS has default value for maximum method of 50. So is it okay if I only display the last 3 methods out of 50. As displaying 50 methods in the example would make it huge.

**Comment by Gaurav-Punjabi** [comment]
I'm on it.

**Comment by strkkk** [comment]
Fix is merged
