### ISSUE TITLE
update doc for RegexpMultiline

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#7695]
https://checkstyle.org/config_regexp.html#RegexpMultiline

Add example for each existing config to show what code is ok and what code cause violation.
Good example is https://checkstyle.org/config_naming.html#AbstractClassName
Please add examples for all properties of Check.

look at referenced commits of #5832, to see what and how should be changed in code.

please play with module/Check by means of https://checkstyle.org/cmdline.html to understand how it works.

------------

PLEASE READ https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-examples

**Comment by kalakandi** [comment]
I'm on it

**Comment by stryder2000** [comment]
I'm on it

**Comment by romani** [comment]
Fix is merged

**Comment by romani** [comment]
@stryder2000, thanks a lot for contribution, please select some issue with easy label

**Comment by stryder2000** [comment]
Thanks a lot @romani. It was really great working with you. It was a good learning experience. Looking forward to some more successful issues.
