### ISSUE TITLE
update doc for RegexpSingleline

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#7697]
https://checkstyle.org/config_regexp.html#RegexpSingleline

Add example for each existing config to show what code is ok and what code cause violation.
Good example is https://checkstyle.org/config_naming.html#AbstractClassName
Please add examples for all properties of Check.

look at referenced commits of #5832, to see what and how should be changed in code.

please play with module/Check by means of https://checkstyle.org/cmdline.html to understand how it works.

------------

PLEASE READ https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-examples

**Comment by Malintha1996** [comment]
I am on it

**Comment by srividyavaishnavi** [comment]
I am on it

**Comment by romani** [comment]
fix is merged.
@Malintha1996 , thanks a lot for your help
