### ISSUE TITLE
Discussion forum and Mailing list is broken

### ISSUE THREAD

**Issue by Abhishek-kumar09** [checkstyle/checkstyle#7699]
GSoC Mailing lists and discussion forum is broken :

_Message Shown_ 
`This group either doesn't exist, or you don't have permission to access it. If you're sure this group exists, contact the Owner of the group and ask them to give you access.`
please review.

**Comment by rnveach** [comment]
@Abhishek-kumar09 What URL are you referring to and where did you get it?

**Comment by romani** [comment]
Please share link and screenshot, to let us fix quickly

**Comment by Abhishek-kumar09** [comment]
the link is : https://groups.google.com/forum/#!forum/checkstyle-devel
![Screenshot from 2020-02-28 23-08-53](https://user-images.githubusercontent.com/48255244/75571533-67615580-5a7f-11ea-8cb9-c45a638d752f.png)

**Comment by wilcoln** [comment]
Same problem here

**Comment by strkkk** [comment]
Looks like it should be https://groups.google.com/forum/#!forum/checkstyle

**Comment by wilcoln** [comment]
This works, thanks!

**Comment by strkkk** [comment]
@romani it looks like link came from
https://github.com/checkstyle/checkstyle/wiki/To-student-of-GSoC-2020
On this wiki page last 2 links are broken as well (last update 5 years ago)
https://github.com/checkstyle/checkstyle/wiki/Support-by-Mail-Lists

**Comment by rnveach** [comment]
@romani Someone posted same issue in chat and the devel link worked for me. It is a valid link and google group. I believe it must be locked behind some required access and thats why I can get in but others are having issues. I do not know the google forms very well to investigate the issue.

**Comment by romani** [comment]
thanks a lot for reporting this. There was permission update at Google, looks like something was went not good. Toics were visible for users.
Settings were like
![image](https://user-images.githubusercontent.com/812984/75610042-b9779a80-5ac2-11ea-862e-7500382c66d2.png)
I changed "Group visibility" to "Anyone".

Please try one more time.

**Comment by rnveach** [comment]
@Abhishek-kumar09 @wilcoln Please check that you can access devel group now.

**Comment by wilcoln** [comment]
@rnveach I can now access the devel group. Thanks.
![Screenshot from 2020-02-29 16-31-58](https://user-images.githubusercontent.com/24209192/75610413-37629280-5b11-11ea-925d-36534416b8bd.png)

**Comment by Abhishek-kumar09** [comment]
Ya perfect! it's now reachable. Thanks
