### ISSUE TITLE
CI should validate checkstyle violations in satelite projects

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#7705]
during release process we update version of checkstyle in satelites projects
https://github.com/checkstyle/checkstyle/wiki/How-to-make-a-release#update-for-released-version-reference

Example of failure:
https://travis-ci.org/checkstyle/contribution/jobs/656696130#L323

it is not good to have such problems right after release.
It is better to place this projects to our CI and force it to be fixed during PR.

in CI build we should try to substitute checkstyle version to SNAPSHOT and update link to report to file path to latest xml

**Comment by rnveach** [comment]
methods-distance is also missed from the list.

**Comment by romani** [comment]
Fix is merged

**Comment by rnveach** [comment]
@romani I am re-opening this as this issue has 2 PRs connected to it.

https://github.com/checkstyle/checkstyle/pull/7708 has not been merged yet.

**Comment by romani** [comment]
I merged it, please recheck issue

**Comment by rnveach** [comment]
I updated the 2 external repos I found and know about. If there are any others you want to add, they can be in another issue.

Wiki update discussed at https://github.com/checkstyle/checkstyle/pull/7708#issuecomment-593051728 is not done, but can be done outside this issue.

This can be closed now.
