### ISSUE TITLE
Update AbstractChecks to log DetailAST - AnnotationOnSameLine

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#7721]
Child of https://github.com/checkstyle/checkstyle/issues/5777

This issue specifically focuses on AnnotationOnSameLine.

**Comment by PrabodDunuwila** [comment]
I'm on it.

**Comment by wilcoln** [comment]
I'm on it.

**Comment by rnveach** [comment]
Fix was merged
