### ISSUE TITLE
Update AbstractChecks to log DetailAST - AvoidEscapedUnicodeCharacters

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#7724]
Child of https://github.com/checkstyle/checkstyle/issues/5777

This issue specifically focuses on AvoidEscapedUnicodeCharacters.

**Comment by wilcoln** [comment]
I'm on it.

**Comment by Gaurav-Punjabi** [comment]
I'm on it.

**Comment by rnveach** [comment]
Fix was merged
