### ISSUE TITLE
Update AbstractChecks to log DetailAST - CommentsIndentation

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#7727]
Child of https://github.com/checkstyle/checkstyle/issues/5777

This issue specifically focuses on CommentsIndentation.

**Comment by AnishaSrivastava1411** [comment]
I am on  it.

**Comment by shashwat70** [comment]
Are you working on this? @AnishaSrivastava1411 
If not, may I try to fix it?

**Comment by sulkykookie** [comment]
Since there hasnt been an update since more than a month, I'm claiming it.

**Comment by rnveach** [comment]
Fix was merged
