### ISSUE TITLE
Update AbstractChecks to log DetailAST - EmptyCatchBlock

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#7729]
Child of https://github.com/checkstyle/checkstyle/issues/5777

This issue specifically focuses on EmptyCatchBlock.

**Comment by gaurabdg** [comment]
I am on it.

**Comment by rnveach** [comment]
Fix was merged

**Comment by romani** [comment]
@gaurabdg , if you would like your full name to be present in our releasenotes https://travis-ci.org/github/checkstyle/checkstyle/jobs/661935807#L592 , please update your git config to name full name, it will be used in your next commits so become populated to release notes. It is completely ok to stay with nickname.

**Comment by rnveach** [comment]
@romani Should other issues be updated to bug? Some are marked as miscellaneous.
https://github.com/checkstyle/checkstyle/issues?q=label%3A%22gsoc+second+issue%22+is%3Aclosed
