### ISSUE TITLE
Update AbstractChecks to log DetailAST - EmptyLineSeparator

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#7730]
Child of https://github.com/checkstyle/checkstyle/issues/5777

This issue specifically focuses on EmptyLineSeparator.

**Comment by shashwat70** [comment]
I'm on it!

**Comment by HuGanghui** [comment]
/var/tmp $ cat Test.java
```java
package checkstyle_demo.ast_emptylineseparator;

class Test {
    private int k;


    private static void foo() {}

}
```
/var/tmp $ cat config.xml
```xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
    <module name="TreeWalker">
        <module name="EmptyLineSeparator">
            <property name="allowMultipleEmptyLines" value="false"/>
        </module>
    </module>
</module>
```
/var/tmp $ RUN_LOCALE="-Duser.language=en -Duser.country=US"
/var/tmp $  java $RUN_LOCALE -jar /var/tmp/checkstyle-8.31-SNAPSHOT-all.jar -c config.xml Test.java
Starting audit...
Checkstyle ends with 1 errors.
[ERROR] /Users/hgh/Downloads/my_file/IDEA_workspace/Leetcode_maven/engineering_ability/src/main/java/checkstyle_demo/ast_emptylineseparator/Test.java:7:5: 'METHOD_DEF' has more than 1 empty lines before. [EmptyLineSeparator]
Audit done.

**Comment by romani** [comment]
Fox is merged
