### ISSUE TITLE
Update AbstractChecks to log DetailAST - JavadocType

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#7741]
Child of https://github.com/checkstyle/checkstyle/issues/5777

This issue specifically focuses on JavadocType.

**Comment by romani** [comment]
please be aware of https://github.com/checkstyle/checkstyle/issues/7740#issuecomment-599061545 , as most of violation are reported inside javadoc comment, we are not ready to support them in xpath. We should update only places where violation is logged on java AST node.

**Comment by wltan** [comment]
I am on it.

There are **5** uses of log within the check, numbered in order of appearance in the code.

## 1, 5
https://github.com/checkstyle/checkstyle/blob/e5c9f2c828c1098000def9a53ba0a28d14f103b6/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTypeCheck.java#L389-L392
https://github.com/checkstyle/checkstyle/blob/e5c9f2c828c1098000def9a53ba0a28d14f103b6/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTypeCheck.java#L463-L466

This is logging the tags inside the javadoc block comment. It is not accessible using DetailAST.

## 2, 3, 4
https://github.com/checkstyle/checkstyle/blob/e5c9f2c828c1098000def9a53ba0a28d14f103b6/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTypeCheck.java#L414
https://github.com/checkstyle/checkstyle/blob/e5c9f2c828c1098000def9a53ba0a28d14f103b6/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTypeCheck.java#L419
https://github.com/checkstyle/checkstyle/blob/e5c9f2c828c1098000def9a53ba0a28d14f103b6/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTypeCheck.java#L444

This is an easy migration. The `lineNo` in all 3 cases comes from the same source:
https://github.com/checkstyle/checkstyle/blob/e5c9f2c828c1098000def9a53ba0a28d14f103b6/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTypeCheck.java#L326
We just need to change the parameters from `int lineNo` to `DetailAST ast`, and provide the relevant XPath suppression tests.

**Comment by romani** [comment]
fix is merged.
