### ISSUE TITLE
Update AbstractChecks to log DetailAST - NeedBraces

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#7750]
Child of https://github.com/checkstyle/checkstyle/issues/5777

This issue specifically focuses on NeedBraces.

**Comment by akki111singh** [comment]
I am on it

**Comment by sulkykookie** [comment]
I'm on it.

**Comment by Gaurav-Punjabi** [comment]
I'm on it.

**Comment by Gaurav-Punjabi** [comment]
@rnveach I have made the changes. But I'm stuck with generating regression diff report. For how many configurations should I generate diff reports. Also I'm a little confused on how to generate these diff reports.

**Comment by rnveach** [comment]
Documentation can be found at https://github.com/checkstyle/contribution/tree/master/checkstyle-tester#checkstyle-tester . If you need additional help, then I need specifics on what your issue is.

> how many configurations should I generate diff reports

As many as it takes to hit all the code in the checks you have changed.

**Comment by romani** [comment]
Fix is merged
