### ISSUE TITLE
Update AbstractChecks to log DetailAST - PackageDeclaration

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#7758]
Child of https://github.com/checkstyle/checkstyle/issues/5777

This issue specifically focuses on PackageDeclaration.

**Comment by HuGanghui** [comment]
I am on it.

**Comment by HuGanghui** [comment]
I am on it

**Comment by DXTkastb** [comment]
I'm on it

**Comment by DXTkastb** [comment]
@romani I need some assistance, where should I log() when ast is null?

**Comment by rnveach** [comment]
> where should I log() when ast is null?

We are not AST to ever be `null` when calling a `log` method. If there is an instance where it can be `null` point out to us the specific code that causes the AST to be null and why it is null.

**Comment by DXTkastb** [comment]
@rnveach 
https://github.com/checkstyle/checkstyle/blob/18b792ebc5b6d5a2d427ccf61a45b122ba90ff53/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/PackageDeclarationCheck.java#L140-L149

Here ast is null for a test on this file:
https://github.com/checkstyle/checkstyle/blob/18b792ebc5b6d5a2d427ccf61a45b122ba90ff53/src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/packagedeclaration/InputPackageDeclarationWithCommentOnly.java#L1

two probable solutions can be:
1: edit PackageDeclarationCheck.java this way

    public void finishTree(DetailAST ast) {
        if (!defined) {
            if (ast == null) {
                log(1, 0, MSG_KEY_MISSING);
            }
            else {
                log(ast, MSG_KEY_MISSING);
            }
        }
    }`

2: Edit AbstractCheck.java:
Introduce If-else condition in `public final void log(DetailAST ast, String key, Object... args) {`
to check ast is null and call the other log functions with line-col-key parameter.

`

**Comment by DXTkastb** [comment]
**Update:**
 This solution isn't working correctly if we increase no. of comments in that empty file.

> 1: edit PackageDeclarationCheck.java this way
> 
> ```
> public void finishTree(DetailAST ast) {
>     if (!defined) {
>         if (ast == null) {
>             log(1, 0, MSG_KEY_MISSING);
>         }
>         else {
>             log(ast, MSG_KEY_MISSING);
>         }
>     }
> }`
> ```

**Comment by rnveach** [comment]
> Introduce If-else condition in 

I am not a fan of this. AST should be required as it is needed for xpath support. We lose xpath support if we can't provide AST.

> This solution isn't working correctly if we increase no. of comments in that empty file.

Please provide more information if you need guidance form us. This is the method I would prefer us to take for logging the AST when we have it.

**Comment by rnveach** [comment]
It seems xpath cannot be fully supported in this check without modifications elsewhere. We should update documentation for this issue that xpath is only partially supported for this check. I think we should change the code for now to call 2 separate logs depending on if we have the AST or not.

@romani ping

**Comment by DXTkastb** [comment]
> Please provide more information if you need guidance form us. This is the method I would prefer us to take for logging the AST when we have it.

The method I mentioned is not correct as it works fine only when a single comment is given in a file. Incase more or no comments are there` log(1, 0, MSG_KEY_MISSING);` this too fails.(I am assuming that package declaration should be made after the comments from the beggining of the file)
If there is no issue about the location of the package declaration then this solution works fine. It will always direct to the first line of the empty file(with or without comments).

**Comment by rnveach** [comment]
The most important thing is we don't expect line numbers to change with regression. Adding new column number for the cases where we will now log by AST is ok.

**Comment by DXTkastb** [comment]
I haven't changed line no,

https://github.com/checkstyle/checkstyle/blob/18b792ebc5b6d5a2d427ccf61a45b122ba90ff53/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/PackageDeclarationCheck.java#L143

log(1, 0, MSG_KEY_MISSING);

DEFAULT_LINE_NUMBER is actually 1. Just a replacement.

**Comment by rnveach** [comment]
@DXTkastb I am failing to see what assistance you need. If we have an AST we want to log by that. If there is no way we have an AST connected to the line, then we can't convert the log. In my mind, it seems this check will have 1 of each, and it will be half supported and half not. We don't expect any drastic changes in regression except adding the column number to the cases we will support.

**Comment by romani** [comment]
fix is merged
