### ISSUE TITLE
Explain reason why RegexpSinglelineJava can not be supported by Xpath

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#7760]
Child of https://github.com/checkstyle/checkstyle/issues/5777

This issue specifically focuses on RegexpSinglelineJava.

**Comment by wilcoln** [comment]
I'm on it.

**Comment by ImmortalRabbit** [comment]
I am on it

**Comment by romani** [comment]
@ImmortalRabbit , please read https://github.com/checkstyle/checkstyle/issues/7759#issuecomment-605525287
you should do the same update.

**Comment by romani** [comment]
fix is merged.
