### ISSUE TITLE
Update AbstractChecks to log DetailAST - TodoComment

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#7762]
Child of https://github.com/checkstyle/checkstyle/issues/5777

This issue specifically focuses on TodoComment.

**ATTENTION**: by fix of this issue Check is changing location of violation from precise line with patched pattern to line where comment is started. Single line comments will not be affected but violation is moved to begin of multiline comment.

**Comment by gaurabdg** [comment]
I am on it

**Comment by HuGanghui** [comment]
I am on it~

**Comment by HuGanghui** [comment]
```java
@Override
    public void visitToken(DetailAST ast) {
        final String[] lines = ast.getText().split("\n");

        for (int i = 0; i < lines.length; i++) {
            if (format.matcher(lines[i]).find()) {
                log(**ast.getLineNo() + i**, MSG_KEY, format.pattern());
            }
        }
    }
```
In the above, we want to `pass the AST and not the line/column` , but changing `ast.getLineNo()` to `ast` directly maybe impossible, add a overloaded method of log is feasible？Or we have other ways ?

**Comment by romani** [comment]
please share exact problem that you facing (compile error or ....) , see how other do similar update - https://github.com/checkstyle/checkstyle/pull/7791/files#diff-4b7e1779a6c9a82eaf535f0da1044a5fR188

**Comment by romani** [comment]
yes, we place violation on exact line in multiline comments, this is a problem.
single line comments is not a problem.

We need to break behavior compatibility a bit and report violation on beginning of multiline comment (on AST node).
We should value xpath suppression more than convenience of user to position violation on exact line. Such Check unlikely be autofixable and user can easily search required pattern himself.

@HuGanghui , please apply this change.

**Comment by romani** [comment]
fix is merged.
