### ISSUE TITLE
Update AbstractChecks to log DetailAST - TrailingComment

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#7763]
Child of https://github.com/checkstyle/checkstyle/issues/5777

This issue specifically focuses on TrailingComment.

**Comment by yajna-pandith** [comment]
I am on it

**Comment by pbludov** [comment]
This Check should be rewritten completely to use `TokenTypes.SINGLE_LINE_COMMENT`.
Now it is RegExp based and has no `DetailAst` nodes at all. This ussue is too hard to be a first GSOC issue.

**Comment by romani** [comment]
I agree full re-implementation is required. But it is doable and backward compatible, so users will not notice anything. I moving this issue to be done at the end of project "Patch suppression".

**Comment by romani** [comment]
fix is merged.
