### ISSUE TITLE
Update AbstractChecks to log DetailAST - VariableDeclarationUsageDistance

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#7766]
Child of https://github.com/checkstyle/checkstyle/issues/5777

This issue specifically focuses on VariableDeclarationUsageDistance.

**Comment by yajna-pandith** [comment]
I am on it

**Comment by kalakandi** [comment]
@yajna-pandith are you still working on this issue, i want to work on this one

**Comment by romani** [comment]
fix is merged.
