### ISSUE TITLE
Update AbstractChecks to log DetailAST - AnnotationLocation

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#7768]
Child of https://github.com/checkstyle/checkstyle/issues/5777

This issue specifically focuses on AnnotationLocation .

**Comment by Malintha1996** [comment]
I am on it.

**Comment by Malintha1996** [comment]
Hi @romani, 
   As per my understanding, the requirement is to overload the log function in the AnnotationLocationCheck providing AST. However, I feel like I am missing something. Could you clarify a little on what should be done?
Thanks.

**Comment by rnveach** [comment]
@Malintha1996 All checks call a log method to report violations. They can either send a line only, a line and column, or the AST. We are in the process of changing all our `log` calls in AbstractChecks to pass the AST instead of anything else. The reason is for xpath suppressions, it needs the AST to know where the violation is in the tree to determine if it matches a suppression xpath supplied by the user. Besides making this change, all tests need to pass and regression needs to be provided for the changes.

**Comment by Malintha1996** [comment]
Got it.  Thanks for the assistance.

**Comment by Malintha1996** [comment]
@rnveach , Will you briefly mention the XpathRegression tests that should be added.

**Comment by rnveach** [comment]
@Malintha1996 See https://github.com/checkstyle/checkstyle/issues/7729 and it's final commit as an example of completed work for this issue. Let me know if you have any more questions.

**Comment by Malintha1996** [comment]
Thanks @rnveach .I am generating the diff report now

**Comment by Malintha1996** [comment]
In generating the report should I use the existing my_config.xml or different configurations for base and patch branches? When I generated the report with my_config.xml no differences were shown. Could someone help me on this?

**Comment by rnveach** [comment]
It doesn't matter what file name you use for the configuration as long as you modify it to test what you want. Which in this case should be the check mentioned in the issue. You are changing existing functionality and not writing a brand new check or adding a new property, so you just use the same config for base and patch. See mentioned issue if you are still not sure.

**Comment by rnveach** [comment]
Fix was merged
