### ISSUE TITLE
Add pmd to no-error validation build item

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#7810]
from https://github.com/checkstyle/checkstyle/issues/7534#issuecomment-596064055

we need to create no-error build item for pmd master:HEAD code, example of how we do this for other projects - https://github.com/checkstyle/checkstyle/blob/master/.ci/wercker.sh#L51

command should be used `mvn checkstyle:check` (lets try to avoid mvnw as it might take extra time for download for each build)

FYI:
together with https://github.com/checkstyle/contribution/issues/456 it will be good protection from regressions in future in this project.

**Comment by romani** [comment]
@nmancus1 , please help to resolve this issue.

**Comment by romani** [comment]
additionally, as mentioned at https://github.com/checkstyle/checkstyle/issues/7534#issuecomment-596512007
please activate https://github.com/checkstyle/checkstyle/blob/master/wercker.yml#L215

**Comment by nmancus1** [comment]
I'm on it.

**Comment by romani** [comment]
fix is merged.

@nmancus1 , please send separate PR to fix https://github.com/checkstyle/checkstyle/pull/7816#discussion_r395072027

**Comment by nmancus1** [comment]
Ok, I'm on it.

**Comment by romani** [comment]
Please make separate PR, it will quickly merged
