### ISSUE TITLE
upadate doc of AvoidDoubleBraceInitialization to make example compilable

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#7811]
detected at https://github.com/checkstyle/sonar-checkstyle/pull/287

Each new `ArrayList<Object>` i smissing braces: `new ArrayList<Object>()` will be correct.

Please recheck that examples are compile-able by javac.

**Comment by rnveach** [comment]
It should be shown that all the examples are compilable when fixed.

**Comment by Mishrasubha** [comment]
I'm on it.

**Comment by srividyavaishnavi** [comment]
I m on it

**Comment by wltan** [comment]
It doesn't look like any work has happened yet so I am on it.

**Comment by strkkk** [comment]
Fix is merged
