### ISSUE TITLE
Remove Apex project from usage in testing 

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#7815]
from https://app.wercker.com/checkstyle/checkstyle/runs/build/5e665a287b63df001aea239d?step=5e665a6c1ccc9800088c9e74

`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.1:check (default-cli) on project apex: Failed during checkstyle configuration: cannot initialize module TreeWalker - TreeWalker is not allowed as a parent of LineLength Please review 'Parent Module' section for this Check in web documentation if Check is standard. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.1:check (default-cli) on project apex: Failed during checkstyle configuration`

**Comment by romani** [comment]
I pushed directly to master disablement. We need to revert it when we are ready.

@nmancus1 , please take a look.

**Comment by romani** [comment]
We need to update Apex config to have LineLenght in proper place.
if there will be a lot of violations in code after that, we need to drop this project completely from no-error , too might be much efforts to maintain it, we can find some other project for this.

**Comment by nmancus1** [comment]
36 violations to be precise, I've updated apex_checks.xml and Checkstyle version here:
https://github.com/checkstyle/apex-core/pull/3#issuecomment-596738592

**Comment by rnveach** [comment]
@romani I recommend we close out this issue and remove any remains of this project.

https://github.com/apache/apex-core/pull/610
A PR is sitting to upgrade checkstyle since 2020 and it hasn't been touched.

Also, the project is now retired and will never be updated again. https://github.com/apache/apex-core/commits/master
> This repository has been archived by the owner before Nov 8, 2022. It is now read-only.

**Comment by romani** [comment]
Removal us merged

**Comment by rnveach** [comment]
Deleted https://github.com/checkstyle/apex-core
