### ISSUE TITLE
Remove javaFiveCompatibility from MissingOverride?

### ISSUE THREAD

**Issue by strkkk** [checkstyle/checkstyle#7827]
https://checkstyle.sourceforge.io/config_annotation.html#MissingOverride

MissingOverride has property `javaFiveCompatibility`, its description says 
> This property will only check classes, interfaces, etc. that do not contain the extends or implements keyword or are not anonymous classes. This means it only checks methods overridden from java.lang.Object. Java 5 Compatibility mode severely limits this check. It is recommended to only use it on Java 5 source.

I really doubt if there are users with Java 5, this property looks redundant in 2020.

**Comment by romani** [comment]
do we have any problems in support of Check now ?
it will be breaking compatibility ... all plugins will be affected, so it is better to remove it base on some good reason.

**Comment by strkkk** [comment]
I guess there is no problems in support.
The only reason is that it is supposed to be a property to support java 5 code, but I really doubt there are some. 
Property seems to be useless.

**Comment by rnveach** [comment]
I am closing this for now.
