### ISSUE TITLE
Publish pitest report as artifact at circleci

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#7832]
https://circleci.com/docs/2.0/artifacts/

We can deploy pitest html report as artifact and it will be available at circleci UI for review.

It will be very useful if contributor stuck with pitest and need help from us

**Comment by gaurabdg** [comment]
I am on it

**Comment by romani** [comment]
fix is merged.

**Comment by romani** [comment]
from CircleCI notifications:
>Build artifacts storage policy: beginning on April 30th, we will start automatically deleting build artifacts that are older than 30 days for paid & free accounts. To download your older build artifacts before then, follow [these instructions](https://go.circleci.com/B400mZ2Hk000F0eM0IPG9d2).
