### ISSUE TITLE
Create code of conduct

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#7833]
GitHub and GSOC suggest to have code if conduct.
GitHub at https://github.com/checkstyle/checkstyle/community

Some links:
https://opensource.google/docs/releasing/template/CODE_OF_CONDUCT/
https://www.contributor-covenant.org/version/1/4/code-of-conduct/ , or https://www.contributor-covenant.org/version/2/0/code_of_conduct/ , or any latest.
https://adainitiative.org/2014/02/18/howto-design-a-code-of-conduct-for-your-community/
https://www.rust-lang.org/policies/code-of-conduct
https://opensource.guide/code-of-conduct/

**Comment by akki111singh** [comment]
I am on it. Are we supposed to add Code of Conduct here @romani ?

**Comment by romani** [comment]
please investigate where github want to keep such file, I presume in  `.github` folder, please recheck this , please send PR with initial proposal for code of conduct.

**Comment by rnveach** [comment]
Fix was merged
