### ISSUE TITLE
Update issue template to new format

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#7834]
https://github.com/checkstyle/checkstyle/blob/master/.github/ISSUE_TEMPLATE.md

There is warning
>You are using an old version of issue templates. Please update to the new issue template workflow. Learn more

We need to figure out what this means and upgrade to make GitHub happy.

**Comment by rnveach** [comment]
I believe it is referring to https://github.com/checkstyle/checkstyle/issues/templates/edit .

**Comment by shashwat70** [comment]
I'm on it!

**Comment by romani** [comment]
fix is merged
