### ISSUE TITLE
Update doc on description of package annotation

### ISSUE THREAD

**Issue by wilcoln** [checkstyle/checkstyle#7846]
Currently the description of this check says

![pacakge](https://user-images.githubusercontent.com/24209192/76676691-5c054280-65c6-11ea-9c7a-18dbc3fedc34.png)

We can see there's a reference to section [§7.4.1](https://docs.oracle.com/javase/specs/jls/se11/html/jls-7.html#jls-7.4) of the Java Language Specification.

A close look to that JLS section reveals this:
> The manner in which this restriction is enforced must, of necessity, vary from implementation to implementation...

Well, from https://github.com/checkstyle/checkstyle/pull/7829#discussion_r392405817, we know that at least for SE8 the placement of package annotations is enforced at compile time.
There was no violation before SE8, so usage of Check is reasonable only till SE8. With SE8 and above it is all controlled by compiler.

The documentation should reflect that. If possible, ideally, we would want the documentation to clearly specify which are the implementations that do not enforce the placement of package annotations at compile time, so the user knows if check is useful for him or not.

**Comment by romani** [comment]
@wilcoln , issue is approved, PR is welcome.

**Comment by wilcoln** [comment]
I'm on it.

**Comment by strkkk** [comment]
Fix is merged
