### ISSUE TITLE
Update Maven Plugins used by Travis profile

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#787]
The following updates are needed:
- `maven-surefire-plugin ............................. 2.9 -> 2.18.1`
- `jacoco-maven-plugin .... 0.7.2.201409121644 -> 0.7.4.201502262128`

Moreover,  maven-surefire-plugin should be extracted to `pluginManagement`, so that the same version is used across the POM.

**Comment by romani** [comment]
fixed will be in 6.5
