### ISSUE TITLE
pitest: problem with coverage in SuppressWarningsHolder.java.isSuppressedAfterEventStart

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#7885]
detected at https://github.com/checkstyle/checkstyle/pull/7836#issuecomment-599329678

```
    private static boolean isSuppressedAfterEventStart(int line, int column, Entry entry) {
        return entry.getFirstLine() < line
            || entry.getFirstLine() == line
            && (column == 0 || entry.getFirstColumn() <= column);
    }
```

pitest report:
![Screen Shot 2020-03-17 at 12 16 43 PM](https://user-images.githubusercontent.com/812984/76893197-2fad2880-6849-11ea-8a16-47ebbfe69344.png)

--------

This code was added recently in scope of :
https://github.com/checkstyle/checkstyle/commit/648871b6c87c84d3c24d58512a2f4ecd47f62017

WE need to recheck that removing such condition will not reopen bug that was originally tried to resolve.

I am ok with prosed fix like at https://github.com/checkstyle/checkstyle/pull/7836#issuecomment-599807606

**Comment by AmrDeveloper** [comment]
I'm on it

**Comment by romani** [comment]
fix is merged.
