### ISSUE TITLE
Broken link - AvoidDoubleBraceInitialization

### ISSUE THREAD

**Issue by zielint0** [checkstyle/checkstyle#7889]
https://checkstyle.org/config_misc.html#AvoidDoubleBraceInitialization does not go to rule's description.

**Comment by rnveach** [comment]
URL is wrong in checks.xml:
https://github.com/checkstyle/checkstyle/blob/646d90e0237d92cb6ab84dc7083a1d2d636eceb2/src/xdocs/checks.xml#L78
https://github.com/checkstyle/checkstyle/blob/646d90e0237d92cb6ab84dc7083a1d2d636eceb2/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/AvoidDoubleBraceInitializationCheck.java#L56
https://github.com/checkstyle/checkstyle/blob/bb108e472b3746cf9131292c7577c3374b880e7b/src/xdocs/config_coding.xml#L176

Check is config_coding.html not config_misc.html .

UT needs to be added to validate URL is correct.

**Comment by HuGanghui** [comment]
I am on it.

**Comment by zielint0** [comment]
@HuGanghui 
Hi, any progress with it?

**Comment by HuGanghui** [comment]
@zielint0 I have solved the typo and will add UT to validate URL is correct soon.

**Comment by zielint0** [comment]
@HuGanghui 
Xie xie!

**Comment by HuGanghui** [comment]
@zielint0 😊 you can speak Chinese ! Are you Chinese ?

**Comment by zielint0** [comment]
@HuGanghui 
No, but I try to learn a bit from time to time!
Chinese is a very cool language to speak :)

**Comment by HuGanghui** [comment]
@zielint0 ok, nice to meet you😄

**Comment by zielint0** [comment]
@HuGanghui 
:-)

**Comment by rnveach** [comment]
Fix is merged
