### ISSUE TITLE
Improve clean up of .ci-temp directory

### ISSUE THREAD

**Issue by nmancus1** [checkstyle/checkstyle#7892]
based on discussion at https://github.com/checkstyle/checkstyle/pull/7870#discussion_r393923576 and https://github.com/checkstyle/checkstyle/pull/7778#discussion_r391285990

We need to improve clean up in the .ci-temp directory after ci scripts run, and should also specify if a directory wasn't able to be removed.  
Also, we should use a bash function to make for a cleaner script, and make clear our intention to remove all files, including protected ones.

**Comment by rnveach** [comment]
@nmancus1 Please start when you are ready.

**Comment by romani** [comment]
Please send update to verify that folder is empty.
We also need to check git status - no changes

**Comment by nmancus1** [comment]
> Please send update to verify that folder is empty.

I can run all others locally and verify that the folder is empty, but I cannot get sonarqube to complete with the token I've generated, unless I'm doing something wrong:

`Caused by: org.sonar.api.utils.MessageException: You're not authorized to run analysis. Please contact the project administrator.
`

> We also need to check git status - no changes.

This would have to be in Travis, right?

**Comment by romani** [comment]
Please ignore sonarqube, send PR with validation enforcement, we will see what is left not fixed

**Comment by romani** [comment]
@nmancus1 , please let us know what is left to do in scope of this issue .

**Comment by nmancus1** [comment]
@romani I think we are good once #8040 is merged.

**Comment by nmancus1** [comment]
@rnveach Can you elaborate on your comment at https://github.com/checkstyle/checkstyle/pull/8040#issuecomment-613095114 and outline the best way to implement this for Travis?

**Comment by rnveach** [comment]
@nmancus1 

> Can you elaborate on your comment at #8040 (comment) and outline the best way to implement this for Travis?

When wercker runs, it is using the same workspace between items in the same PR CI job. A file you save for one part (regression on ABC project), will still be there in another item (regression on XYZ project). So you are able to tell at the end if any of the previous jobs did or did not clean up after themselves.

Travis is completely different. It allows 4 items to run in parallel in the same PR CI job. Each parallel run is using its own version of the workspace. File saved for one part (running all tests), will not be there for any other item (running checkstyle).

So you will not be able to create a single cleanup item after everything is finished. You will need to have the cleanup run after every single item.

**Comment by nmancus1** [comment]
@rnveach Ok.  That makes sense.  So, since both Travis and Shippable run jobs in parallel, should I have each job clean up after itself AND validate that .ci-temp/ is empty after it's done? If so, I will just make a bash function in the script that every job calls as the last step, to validate that .ci-temp/ is empty.

**Comment by rnveach** [comment]
> should I have each job clean up after itself AND validate 

Yes, this is the only way.

**Comment by romani** [comment]
fix is merged
