### ISSUE TITLE
Update ant-nodeps and wagon-ssh libraries

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#790]
The following updates are available:
- `ant-nodeps .... 1.7.1 -> 1.8.1`
- `wagon-ssh ......... 1.0 -> 2.8`

**Comment by romani** [comment]
fixed, will be in 6.5

**Comment by mkordas** [comment]
It's not done yet, #850 is still pending.

**Comment by romani** [comment]
merged.

**Comment by mkordas** [comment]
Looks good:
![image](https://cloud.githubusercontent.com/assets/5467276/6830309/3dc435dc-d319-11e4-8859-fdb59a330817.png)
