### ISSUE TITLE
add spoon project to no-exception testing

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#7914]
add spoon project to no-exception testing

discussed at 
https://github.com/checkstyle/checkstyle/issues/6064#issuecomment-601704892

it is already at https://github.com/checkstyle/contribution/commit/50dcd17d41ba25fc7682816b57c9c4fa6cca0063

we need to activate it wercker config/sh script.
probably at https://github.com/checkstyle/checkstyle/blob/master/.ci/wercker.sh#L305 , so we will do two projects in same CI item

**Comment by HuGanghui** [comment]
I am on it.

**Comment by Abhishek-kumar09** [comment]
I am on it.

**Comment by strkkk** [comment]
Fix is merged
