### ISSUE TITLE
Website Template Change

### ISSUE THREAD

**Issue by satakshigarg** [checkstyle/checkstyle#7917]
Hey , I am new to github and being a java coder, I just came across your project. The first thing I researched was browsing the website.
I have a suggestion if it adds any value to your project. The webpage has an innovative logo but the font (red color) does not go well with the theme. In fact I feel, that instead of using white and grey as the background colors, you must go for black and grey, they not only add that professional feature to your website but also adds the dark mode feature to your website.
If you find my issue worth consideration, I would love to work on it.

**Comment by romani** [comment]
You can suggest new design, but beware that is we will not like it (it will subjective decision) we will not accept it.
FYI: Current design was proposed a while ago by one of our friend who is artist (out of 4 we selected this). https://github.com/checkstyle/resources/tree/master/img/style_experiments

Here are all resources: https://github.com/checkstyle/resources/tree/master/img

**Comment by satakshigarg** [comment]
Thank you for your reply. I will send you the design as soon as it is
ready. And I will try make sure that you like the design.



Satakshi Garg

**Comment by romani** [comment]
we lost connection to contributor
