### ISSUE TITLE
Resolve Pitest Issues - RedundantImportCheck

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#7920]
Child issue of https://github.com/checkstyle/checkstyle/issues/7797 ,

https://github.com/checkstyle/checkstyle/blob/f9131f9536c71d963c83aab1550b7a0371aa9ff5/.ci/pitest.sh#L90

**Comment by Gaurav-Punjabi** [comment]
I'm on it.

**Comment by Gaurav-Punjabi** [comment]
Pitest report : 
https://gaurav-punjabi.github.io/checkstyle/issue-7920/pit-reports/202003221458/com.puppycrawl.tools.checkstyle.checks.imports/RedundantImportCheck.java.html#grouporg.pitest.mutationtest.report.html.SourceFile@f8857d3_120

Surviving mutation : 
`removed conditional - replaced equality check with true → SURVIVED`

Hardcoded mutation : 
[Gaurav-Punjabi@b2a587b](https://github.com/Gaurav-Punjabi/checkstyle/commit/b2a587b9a430020a445ce9dd5a66cde406228167#diff-c1b1a9b134ee37c911d696e67a449344L120)

Regression Report : 
(In Process)

**Comment by rnveach** [comment]
> Pitest report :
https://gaurav-punjabi.github.io/checkstyle/issue-7920/pit-reports/202003221458/com.puppycrawl.tools.checkstyle.checks.imports/RedundantImportCheck.java.html#grouporg.pitest.mutationtest.report.html.SourceFile@f8857d3_120
> removed conditional - replaced equality check with true → SURVIVED

Issue is not shown in pitest report. Pitest shows 100% coverage on class where our CI tells us differently.

Did you run pitest report on a clean checkstyle master branch?

**Comment by Gaurav-Punjabi** [comment]
No I updated this report. Let me check.

**Comment by Gaurav-Punjabi** [comment]
> > Pitest report :
> > https://gaurav-punjabi.github.io/checkstyle/issue-7920/pit-reports/202003221458/com.puppycrawl.tools.checkstyle.checks.imports/RedundantImportCheck.java.html#grouporg.pitest.mutationtest.report.html.SourceFile@f8857d3_120
> > removed conditional - replaced equality check with true → SURVIVED
> 
> Issue is not shown in pitest report. Pitest shows 100% coverage on class where our CI tells us differently. I cannot even find the line in your report that pitest is reporting, which makes me think you ran pitest on a modified branch.
> 
> Did you run pitest report on a clean checkstyle master branch?

@romani Updated the report. Please check again.

**Comment by rnveach** [comment]
Pitest report and regression look good.

**Comment by strkkk** [comment]
Fix is merged
