### ISSUE TITLE
Resolve Pitest Issues - UnusedImportsCheck

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#7921]
Child issue of https://github.com/checkstyle/checkstyle/issues/7797 ,

https://github.com/checkstyle/checkstyle/blob/f9131f9536c71d963c83aab1550b7a0371aa9ff5/.ci/pitest.sh#L91

**Comment by AmrDeveloper** [comment]
I am on it

**Comment by romani** [comment]
fix is merged.

@AmrDeveloper , thanks a lot !!
