### ISSUE TITLE
Update type definitions for OneTopLevelClass

### ISSUE THREAD

**Issue by wltan** [checkstyle/checkstyle#7957]
From https://github.com/checkstyle/checkstyle/pull/7905#discussion_r396111327

Currently, our logic defines class, interface, and enum types as candidates for top-level types. It was mentioned in https://github.com/checkstyle/checkstyle/pull/7905#discussion_r396111327 that [annotation type declarations](https://docs.oracle.com/javase/tutorial/java/annotations/declaring.html) should be considered as well.

Current Behavior:
```
D:\checkstyletest>type config.xml 
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://checkstyle.sourceforge.net/dtds/configuration_1_3.dtd">

<module name = "Checker">
    <module name="TreeWalker">
        <module name="OneTopLevelClass"/>
    </module>
</module>

D:\checkstyletest>type test\*.java 
@interface ClassPreamble {
   String author();
   String date();
   int currentRevision() default 1;
   String lastModified() default "N/A";
   String lastModifiedBy() default "N/A";
   // Note use of array
   String[] reviewers();
}

class ExtraClass {

}

interface ExtraInterface {

}
D:\checkstyletest>java -jar -Duser.language=en -Duser.country=US \
   checkstyle-8.30-all.jar -c config.xml test\*.java 
Starting audit...
[ERROR] D:\checkstyletest\test\Test.java:15: 
Top-level class ExtraInterface has to reside in its own source file. [OneTopLevelClass]
Audit done.
```
The annotation tag is not being counted as a top-level declaration, so `ExtraClass` is seen as the top-level class and only `ExtraInterface` is a violation.

The expected behavior should be that `ClassPreamble` is the top-level definition, while both `ExtraClass` and `ExtraInterface` are considered violations.

If added, the [documentation](https://checkstyle.org/config_design.html#OneTopLevelClass) will have to be updated as well. ~~More interestingly, the [reference](https://docs.oracle.com/javase/specs/jls/se11/html/jls-7.html#jls-7.6) cited by the documentation says that **only classes or interfaces are considered top-level types**.~~
> _A top level type declaration declares a top level class type (§8 (Classes)) or a top level interface type (§9 (Interfaces))._

The same thing can be found for the [Java 14 documentation](https://docs.oracle.com/javase/specs/jls/se14/html/jls-7.html#jls-7.6) as well.

~~We need to sort out the discrepancy here. Can annotation types and enums be considered top-level types? If so, we might want to tweak the documentation as well to note the difference between the check behavior and the Java Language Specification.~~ (resolved, see next comment)

**Comment by rnveach** [comment]
Please also include template reporting in description. See https://checkstyle.org/report_issue.html#How_to_report_a_bug.3F .

>  Can annotation types and enums be considered top-level types?

Check already considers enumerations. https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/design/OneTopLevelClassCheck.java#L134

> A top level type declaration declares a top level class type (§8 (Classes)) or a top level interface type (§9 (Interfaces)).

The same documentation clarifies Class and Interfaces.
https://docs.oracle.com/javase/specs/jls/se14/html/jls-8.html#jls-ClassDeclaration
>  There are two kinds of class declarations: normal class declarations and enum declarations. 

https://docs.oracle.com/javase/specs/jls/se14/html/jls-9.html#jls-InterfaceDeclaration
>  There are two kinds of interface declarations - normal interface declarations and annotation type declarations (§9.6). 

I don't see why all 4 definitions should not be considered by the check. JLS declares them as top level.

**Comment by wltan** [comment]
My bad, I forgot that the `ClassDeclaration` and `InterfaceDeclaration` have their own definitions that include enums and annotations. There should be no problems then, just adding annotation types will cover all 4 definitions.

First comment has been updated with the template run.

**Comment by rnveach** [comment]
@romani I am approving this issue since there seems to be no doubt that annotation definitions should be included.

**Comment by wltan** [comment]
This is the regression report for https://github.com/wltan/checkstyle/commit/a7506f2cad0870673efccd5cb978abe8f6218408 which builds off the changes in #7905. I'll open a PR for this once #7905 is resolved.

https://wltan.github.io/checkstyle-reports/2020-03-29/onetoplevel-annotation/

**Comment by rnveach** [comment]
Fix was merged
