### ISSUE TITLE
Set up JDK 14 build in CI

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#7969]
Travis and appveyor already support Java 14, so we have to set up a build with it.

**Comment by pbludov** [comment]
https://www.appveyor.com/docs/windows-images-software/#java
JDK 14 is only for Visual Studio 2019 image, we have to upgrade

**Comment by romani** [comment]
> JDK 14 is only for Visual Studio 2019 image, we have to upgrade

it might be good to do this in separate commit or PR, there might be more nuances.

**Comment by pbludov** [comment]
> it might be good to do this in separate commit or PR

done.

**Comment by romani** [comment]
fix is merged.

**Comment by rajadilipkolli** [comment]
how to ensure that checkstyle is using JDK 14 in a maven project.

**Comment by pbludov** [comment]
Please clarify your question. Checkstyle does not run checks in a separate VM. They are executed in the same process as the main build. If Maven uses Java 14, then Checkstyle will use Java 14 too.
