### ISSUE TITLE
Resolve Pitest Issues - RegexpCheck (1)

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#7982]
Child issue of https://github.com/checkstyle/checkstyle/issues/7797 ,

https://github.com/checkstyle/checkstyle/blob/f9131f9536c71d963c83aab1550b7a0371aa9ff5/.ci/pitest.sh#L52

**Comment by Gaurav-Punjabi** [comment]
I'm on it.

**Comment by Gaurav-Punjabi** [comment]
1. Pitest report:
https://gaurav-punjabi.github.io/checkstyle/issue-7982/com.puppycrawl.tools.checkstyle.checks.regexp/RegexpCheck.java.html#org.pitest.mutationtest.report.html.SourceFile@6b957611_524

2. Surviving mutation:
`removed conditional - replaced equality check with false → SURVIVED`

3. Hardcoded mutation:
[Gaurav-Punjabi@a143755](https://github.com/Gaurav-Punjabi/checkstyle/blob/a143755b76f63951c118dd57351e70151d1113c9/src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpCheck.java#L524)

4. Regression report:
https://gaurav-punjabi.github.io/checkstyle/issue-7982/diff/index.html

**Comment by strkkk** [comment]
Fix is merged
