### ISSUE TITLE
Resolve Pitest Issues - RegexpCheck (2)

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#7983]
Child issue of https://github.com/checkstyle/checkstyle/issues/7797 ,

https://github.com/checkstyle/checkstyle/blob/f9131f9536c71d963c83aab1550b7a0371aa9ff5/.ci/pitest.sh#L53

**Comment by akki111singh** [comment]
I am on it

**Comment by akki111singh** [comment]
# 1.Pitest  Report
* Link : https://akki111singh.github.io/pit-reports/202003300159/com.puppycrawl.tools.checkstyle.checks.regexp/RegexpCheck.java.html#org.pitest.mutationtest.report.html.SourceFile@20613304_638
* Surviving Mutations: 
	removed conditional - replaced equality check with false → SURVIVED
        removed conditional - replaced equality check with true → SURVIVED

**Comment by akki111singh** [comment]
@romani  please review

**Comment by rnveach** [comment]
> The only way in which (ignore || illegalPattern || checkForDuplicates) affects the function is when all of them are false so the overall result will be false.But it will be automatically handled by the other part of the code in RexexpCheck.java.

Please confirm. When all 3 booleans are false (`ignore || illegalPattern || checkForDuplicates`), `errorCount` condition kicks in before they are checked and that is why the mutation survives? What about when `ignore` is true and the others are false, it is still not plays any role? Is there a direct connection why this is?

**Comment by akki111singh** [comment]
When ```ignore``` is true and other are false then ```(ignore || illegalPattern || checkForDuplicates)``` will give true and therefore the function depends on the ```errorCount``` condition.

**Comment by anhminhtran235** [comment]
I am on it

**Comment by strkkk** [comment]
Fix is merged
