### ISSUE TITLE
AbstractJavadocCheck should have method(s) to log violation by AST

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#7984]
noticed at https://github.com/checkstyle/checkstyle/pull/7775

The same as Java checks do [logging of violation by AST](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/AbstractCheck.java#L223), we should do this for Javadoc violations.
Right now we do this like `log(textNode.getLineNumber(), textNode.getColumnNumber(), MSG_KEY);`

**Comment by romani** [comment]
@rnveach , please review proposal

**Comment by rnveach** [comment]
@romani I take it you actually mean to log by AST in a Javadoc Check as we already have an issue to start logging by Javadoc's DetailNode?#5770
