### ISSUE TITLE
use RegexpSingleline Check to validate amount of tests in Xpath tests

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#7987]
there was a lot of comments in PRs that test classes in suppressionxpathfilter should have 2 or more test methods.

This example clearly showed that maintainers tend to forgot this: 
https://github.com/checkstyle/checkstyle/pull/7935/files#r399724307

We need Checkstyle to help. There is Check - RegexpSingleline.
Extended doc is at https://github.com/checkstyle/checkstyle/pull/7714

We need to validate all Classes in suppressionxpathfilter to have 2 or more `@Test`.
If there are already several of such classes we should be able to exclude such classes from validation temporary with comment "till <link to new issue>".

**Comment by romani** [comment]
@Malintha1996 , please help us to resolve this issue.

**Comment by Malintha1996** [comment]
> @Malintha1996 , please help us to resolve this issue.

on it

**Comment by Malintha1996** [comment]
> @Malintha1996 , please help us to resolve this issue.

done

**Comment by Gaurav-Punjabi** [comment]
I'm on it.

**Comment by romani** [comment]
Fix is merged
