### ISSUE TITLE
Consider adding note to RN of 8.31 about required maven plugin update

### ISSUE THREAD

**Issue by pzygielo** [checkstyle/checkstyle#7989]
Please consider adding to [Release Notes 8.31](https://checkstyle.org/releasenotes.html#Release_8.31) note, that update of maven plugin is required. With 3.1.0 (only 0.0.1 away from the latest) plugin following happens:
```
[INFO] --- maven-checkstyle-plugin:3.1.0:check (default-cli) @ ... ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.804 s
[INFO] Finished at: 2020-03-29T19:21:57+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.0:check (default-cli) on project ...: Execution default-cli of goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.0:check failed: An API incompatibility was encountered while executing org.apache.maven.plugins:maven-checkstyle-plugin:3.1.0:check: java.lang.NoSuchMethodError: com.puppycrawl.tools.checkstyle.Checker.setClassLoader(Ljava/lang/ClassLoader;)V
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.apache.maven.plugins:maven-checkstyle-plugin:3.1.0
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:.../.m2/repository/org/apache/maven/plugins/maven-checkstyle-plugin/3.1.0/maven-checkstyle-plugin-3.1.0.jar
[ERROR] urls[1] = file:.../.m2/repository/org/slf4j/jcl-over-slf4j/1.7.25/jcl-over-slf
```

It seems that plugin was prepared for that in [maven-checkstyle-plugin-3.1.1](https://github.com/apache/maven-checkstyle-plugin/releases/tag/maven-checkstyle-plugin-3.1.1). I wasn't.

I guess it is covered by current _Breaking backward compatibility_ section, but it isn't obvious for me.

**Comment by romani** [comment]
Release notes are generated based on fixed issues and commits.

User will run into this and google such exception, they will find such issues like this and get answer on migration. It will work as stackoverflow knowledge.

There is migration note at https://github.com/checkstyle/checkstyle/issues/7190

**Comment by imosapatryk** [comment]
@romani It's not a good idea to make developers look for exception in google. I lost a bit of time searching for the solution, now imagine thousands of developers doing the same. It was enough to mention it on main page which I read completely. It's really stupid explenation...

**Comment by romani** [comment]
I agree but in same time it is hard for us to put all details and we do miss something.
ones release notes content is generated for release it is never updated automatically, so you can send PR to update release notes with content that might help.

sources https://github.com/checkstyle/checkstyle/blob/master/src/xdocs/releasenotes.xml

Note:
Maven plugin is not the only where checkstyle is used. We have a lot of plugins around.
