### ISSUE TITLE
java 14 switch expression syntax is not supported

### ISSUE THREAD

**Issue by koppor** [checkstyle/checkstyle#7992]
Refs https://github.com/checkstyle/checkstyle/issues/7969 and https://github.com/checkstyle/checkstyle/issues/7103

[JDK 14 has been released](https://openjdk.java.net/projects/jdk/14/). It supports [advanced switch statements](https://openjdk.java.net/jeps/361)

```java
static void howMany(int k) {
    switch (k) {
        case 1  -> System.out.println("one");
        case 2  -> System.out.println("two");
        default -> System.out.println("many");
    }
}
```

When checkstyle encounters such code, it just cannot parse the file.

**Comment by romani** [comment]
it will be fixed at some time before September 2020.

**Comment by strkkk** [comment]
@romani  there is same issue https://github.com/checkstyle/checkstyle/issues/6615
I guess this or other one should be closed
