### ISSUE TITLE
config_naming has inconsistent tag usage

### ISSUE THREAD

**Issue by wltan** [checkstyle/checkstyle#8005]
https://checkstyle.org/config_naming.html
In the documentation, the `<source>` tag is typically used to mark configuration examples.

![image](https://user-images.githubusercontent.com/53135010/78029635-819a9600-7393-11ea-86f5-193f466faa5f.png)

However, this is not the case for some of the examples. The `<pre>` tag is used instead.
![image](https://user-images.githubusercontent.com/53135010/78029764-ae4ead80-7393-11ea-9a31-a52b9cda54f5.png)

On closer inspection, some of these examples have incorrect syntax as I believe they are not being validated. Self-closing tags like `property` are missing a `/` at the end of the tag.
![image](https://user-images.githubusercontent.com/53135010/78030206-4c427800-7394-11ea-85e3-fbd9614cd691.png)

Hence, I am requesting to:
1. Change the configuration examples to use `<source>` instead of `<pre>`
2. Fix all the syntax mistakes inside configuration examples so that they are valid

**Comment by rnveach** [comment]
> some of these examples have incorrect syntax as I believe they are not being validated. Self-closing tags like property are missing a / at the end of the tag.

They are being validated. The validation isn't working here because of the wrong tag usage. Using `source` should start the validation and report the invalid XML.

**Comment by shashwat70** [comment]
I'm on it!

**Comment by wltan** [comment]
> They are being validated. The validation isn't working here because of the wrong tag usage. Using `source` should start the validation and report the invalid XML.

That's good to know. Once everything is converted to `source` the syntax errors will automatically surface.

> I'm on it!

Go ahead. It's a simple fix anyway.

**Comment by shashwat70** [comment]
I observed a similar issue in https://checkstyle.org/config_blocks.html as well. @wltan

**Comment by rnveach** [comment]
Fix was merged
