### ISSUE TITLE
Wrong tag usage in NeedBraces Check

### ISSUE THREAD

**Issue by shashwat70** [checkstyle/checkstyle#8011]
https://checkstyle.org/config_blocks.html
The source tag isn't used in the examples section of NeedBraces Check.

![2020-04-02](https://user-images.githubusercontent.com/52609734/78216911-8c127800-74d8-11ea-8dac-8c852cd9bb52.png)

Hence, I'm requesting to change the ```<pre>``` tags to ```<source>``` to ensure that they are validated.

**Comment by shashwat70** [comment]
please approve @rnveach

**Comment by strkkk** [comment]
Fix is merged
