### ISSUE TITLE
Improve option `allowMissingPropertyJavadoc` in `MissingJavadocMethod` for Builders

### ISSUE THREAD

**Issue by uhafner** [checkstyle/checkstyle#8016]
The check  `MissingJavadocMethod` provides a property `allowMissingPropertyJavadoc`, so that setters like

```
public void setNumber(final int number)
{
    mNumber = number;
}
```
 do not require a documentation. 

I'm very often using the Builder pattern for my classes (and IntelliJ provides a simple refactoring to create builders.) and they create slightly modified setters that allow method chaining. 

```
public T setNumber(final int number)
{
    mNumber = number;
    return this;
}
```
It would be nice if CheckStyle would allow a suppression of comments for these type of setters as well. 

I'm not sure if it makes sense to add an additional property or if the existing check in https://github.com/checkstyle/checkstyle/blob/b4a337a599e853cdc44b19a76da28fcfab2956cd/src/main/java/com/puppycrawl/tools/checkstyle/utils/CheckUtils.java#L329 should be updated.

**Comment by romani** [comment]
@uhafner , thanks a lot for reporting this, BUT please report it as we require in issue template, it is critical for us, and it significantly help for occasional outside contributors to resolve this issue.
Please follow issue template.

**Comment by uhafner** [comment]
Hmm, using your template would make the issue more cryptic than it is by now. I already provided a link to the code, should that be removed as well? 

I'll give my best to update the issue.

**Comment by nrmancuso** [comment]
Closed in favor of https://github.com/checkstyle/checkstyle/issues/12157, as issue description here is not complete.
