### ISSUE TITLE
update test inputs to avoid long lines that violate 100 limit

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#8036]
taken from https://github.com/checkstyle/checkstyle/pull/7997

we need to remove all introduced suppressions.
All Inputs need to be updated to wrap long lines is possible.

**Comment by Gaurav-Punjabi** [comment]
So, from what I understand. We need to update all the files that are getting violated due to long lines. Correct?

**Comment by romani** [comment]
yes, just wrap lines and update UTs expectations if violations are moved to new lines. If there is some test need it to be single lined ([example](https://github.com/checkstyle/checkstyle/pull/8022)) we should keep it in suppression.

**Comment by Gaurav-Punjabi** [comment]
Alright, I'm on it 👍

**Comment by romani** [comment]
Fix is merged
