### ISSUE TITLE
Build does not work on Windows after introducing coverage constraints

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#804]
Command prompt has [limitation](http://support.microsoft.com/pl-pl/kb/830473) of 8191 characters per command. On Windows Cobertura executes something like this:
```
cmd.exe /X /C ""C:\Program Files\Java\jdk1.8.0_25\jre\bin\java" -Xmx64m net.sourceforge.cobertura.check.Main --datafile C:\IdeaProjects\checkstyle\target\cobertura\cobertura.ser --branch 100 --line 100 --totalbranch 83 --totalline 89 --regex .*.checks.coding.SimplifyBooleanExpressionCheck:77:100 --regex .*.filters.SuppressionCommentFilter\$.*:84:87 --regex .*.filters.SuppressWithNearbyCommentFilter:87:80 --regex .*.checks.regexp.DetectorOptions:96:100 --regex .*.checks.AbstractOptionCheck:80:100 --regex .*.checks.metrics.JavaNCSSCheck:96:81 --regex .*.checks.annotation.MissingOverrideCheck:96:100 --regex ...
```
This command has around 12,000 characters, and `mvn verify` fails every time. Unfortunately I don't know how to fix it besides bumping majority of checks to 100%.

**Comment by romani** [comment]
I recommend you to stop using Windows, it is just a waste of time , it is not OS for development.

I am ok to sources to be compiled on Windows, but I will never check that. I even do not help students in sevntu.checkstyle with Windows, all of them switched to Linux, there was more then 20 of them, and nobody regret.

I could help you with adaptation in Linux as main OS for development.

BTW: moving all Check to 100% is a good solution for the problem :).

**Comment by mkordas** [comment]
Actually my company's VPN software requires Windows to work, so the only option would be to develop Checkstyle from Linux VM :) 

And it's not just me, we need to remember about random contributors that have Windows and they won't be able to verify locally if build is ok.

So let's bring all checks to 100% then ;)

**Comment by romani** [comment]
it is better for me and Checkstyle to leave you with thought that "100%" is only solution, 

but please consider dual boot as an option and look at https://github.com/sevntu-checkstyle/sevntu.checkstyle/wiki as steps for environment set-up.

please close this issue.

**Comment by damianszczepanik** [comment]
I agree with @mkordas and I found that
```
mvn cobertura:cobertura
```
does not have this defect. Is it helpful with finding faster solution than waiting for 100% and more friendly than changing pom.xml or having symlink to shortness path?

**Comment by romani** [comment]
there number of workaround , you can even comment most of lines in pom and just do not comit them.
