### ISSUE TITLE
Extract logic for token type checking to separate method

### ISSUE THREAD

**Issue by wltan** [checkstyle/checkstyle#8048]
There is a recurring pattern throughout Checkstyle's code:
https://github.com/checkstyle/checkstyle/blob/a830b92f5ed1f9d2ed3b88440ba4d494105de89d/src/main/java/com/puppycrawl/tools/checkstyle/utils/ScopeUtil.java#L232-L235
https://github.com/checkstyle/checkstyle/blob/a830b92f5ed1f9d2ed3b88440ba4d494105de89d/src/main/java/com/puppycrawl/tools/checkstyle/utils/ScopeUtil.java#L141-L145
https://github.com/checkstyle/checkstyle/blob/a830b92f5ed1f9d2ed3b88440ba4d494105de89d/src/main/java/com/puppycrawl/tools/checkstyle/utils/ScopeUtil.java#L182-L185
https://github.com/checkstyle/checkstyle/blob/a830b92f5ed1f9d2ed3b88440ba4d494105de89d/src/main/java/com/puppycrawl/tools/checkstyle/utils/ScopeUtil.java#L208-L212
https://github.com/checkstyle/checkstyle/blob/8bf05ced07bb04c7240ae9f60ecda3c628e9b6f6/src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/CommentsIndentationCheck.java#L409-L417
https://github.com/checkstyle/checkstyle/blob/8bf05ced07bb04c7240ae9f60ecda3c628e9b6f6/src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/CommentsIndentationCheck.java#L424-L430
https://github.com/checkstyle/checkstyle/blob/bd45909e6345b2d3ef5c5472d35a3ad926a31eb9/src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheck.java#L738-L741

The main idea is that the AST node is being compared against a list of allowed types. What we can do is abstract away all of the `||` and `==` logic, into a new method that handles the comparisons for us. I see two ways of achieving this:

1. A static method under `TokenUtil`, `TokenUtil.isOfType(DetailAST ast, TokenTypes... types)`
https://github.com/checkstyle/checkstyle/blob/a830b92f5ed1f9d2ed3b88440ba4d494105de89d/src/main/java/com/puppycrawl/tools/checkstyle/utils/ScopeUtil.java#L232-L235
will become:
```java
if (TokenUtil.isOfType(parent, TokenTypes.CLASS_DEF, TokenTypes.INTERFACE_DEF, TokenTypes.ANNOTATION_DEF, TokenTypes.ENUM_DEF)) {
```
2. An instance method under `DetailAST`/`DetailASTImpl`, `ast.isOfType(TokenTypes... types)`
```java
if (parent.isOfType(TokenTypes.CLASS_DEF, TokenTypes.INTERFACE_DEF, TokenTypes.ANNOTATION_DEF, TokenTypes.ENUM_DEF)) {
```

**Comment by pbludov** [comment]
I like second approach.

**Comment by shashwat70** [comment]
I'm on it as soon as this gets approved.

**Comment by strkkk** [comment]
First approach seems more useful because in this case there can be check that given ast is not null, which is very often checked before check of token's type.

**Comment by romani** [comment]
We need to use first approach to make it Util method.
If it become so well used we can always move it to API class with very simple refactoring.

**Comment by wltan** [comment]
@shashwat70 I think it would be nicer to use a declarative approach.
```java
    public static boolean isOfType(DetailAST ast, int... types) {
        return ast != null && Arrays.stream(types).anyMatch(x -> x == ast.getType());
    }
```

**Comment by shashwat70** [comment]
https://github.com/checkstyle/checkstyle/blob/e3d947cc313858fac6aca4452bcd0be8633c9ab1/src/main/java/com/puppycrawl/tools/checkstyle/utils/TokenUtil.java#L205-L210

I think we can pass ast.getType() directly to the function instead of the AST node. If we do that, it can be extended to theses cases also.

**Comment by pbludov** [comment]
> I think we can pass ast.getType() directly to the function instead of the AST node. If we do that, it can be extended to theses cases also.

I would like to have both methods, with `DetailAST` and `int`.

**Comment by shashwat70** [comment]
> I would like to have both methods, with DetailAST and int.

I'll add both and push changes in a while. Thanks.

**Comment by romani** [comment]
fix is merged.
