### ISSUE TITLE
Set up Semaphore CI

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#8051]
From https://github.com/checkstyle/checkstyle/issues/7976#issuecomment-609628603_

[Semaphore CI](https://semaphoreci.com/), free for open source projects.
Quite fast (with .m2 cache):
![image](https://user-images.githubusercontent.com/900805/78828391-4c262600-79ed-11ea-993f-47e2696a903e.png)

We can move some tasks from Travis to Semaphore to speed up the process.

@romani please set up the organization profile. For now there can be only one admin per project in this CI, so it should be done by you.

Github integration: https://github.com/marketplace/semaphore

**Comment by pbludov** [comment]
I did some research in my [branch](https://github.com/pbludov/checkstyle/commit/10fb839de8ceff39bd630aacb12f12f7bdcec5ba)

**Comment by romani** [comment]
https://checkstyle.semaphoreci.com/dashboards

**Comment by romani** [comment]
fix is merged.

**Comment by romani** [comment]
@pbludov , are we ready to start using this CI reliably ?
We need to unload Travis, it has too much jobs.

**Comment by pbludov** [comment]
> @pbludov , are we ready to start using this CI reliably ?
> We need to unload Travis, it has too much jobs.

Yes, it has been stable for the last 6 months.
