### ISSUE TITLE
Coveralls stopped working for Checkstyle

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#806]
Last analysis was done on 1st March: https://coveralls.io/r/checkstyle/checkstyle

**Comment by romani** [comment]
in one of updates for POM we broke it :)

https://travis-ci.org/checkstyle/checkstyle/jobs/54676462#L4500

triggered by https://github.com/checkstyle/checkstyle/blob/master/.travis.yml#L12

**Comment by mkordas** [comment]
Indeed. According to https://github.com/trautonen/coveralls-maven-plugin#jacoco we should now use
```
after_success:
  - mvn clean test jacoco:report coveralls:report
```

Moreover we can consider moving to Cobertura in Coveralls.

**Comment by romani** [comment]
Please propose a switch to cobertura https://github.com/trautonen/coveralls-maven-plugin#cobertura , lets use the same coverage engine

**Comment by romani** [comment]
Works fine now https://github.com/checkstyle/checkstyle/pull/817
