### ISSUE TITLE
Run Sonar more frequently

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#807]
Last analysis done by Sonar was on 28th Feb. It should run much more often, possibly every day or every hour when there are code changes.

We should also investigate possiblity of running Sonar for every commit/pull request.

Is it possible to get Sonar account and some user privilleges?

**Comment by romani** [comment]
we have no control other Sonar , they do all management them-self , I only requested http://sonarqube.15.x6.nabble.com/Change-Checkstyle-project-source-location-at-nemo-sonarqube-org-td5021486.html to add us in their list of projects.
you can continue discussion in that thread to figureout frequency of rebuild.

**Comment by romani** [comment]
http://nemo.sonarqube.org/component_issues?id=com.puppycrawl.tools%3Acheckstyle#resolved=false|severities=MINOR

Updated at "Version 6.5-SNAPSHOT / March 18 2015 10:48 PM"

**Comment by romani** [comment]
I do not think that is configurable.
