### ISSUE TITLE
New check: PreferSeparatedLiterals

### ISSUE THREAD

**Issue by strkkk** [checkstyle/checkstyle#8073]
```
$ cat config.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>

    <module name="TreeWalker">
       <module name="PreferSeparatedLiterals"/>
    </module>
</module>
$ cat TestClass.java
class Test {
    int f = 100000000; // violation
    int ab = 100_000_000; // OK, ignore value if there is already at least one separator
   long c = 123456789012; // violation
   long d = 1000L; // violation
   int e = 100; // OK, enable only for length > 3
   int g = 0xDADA; // OK, ignore hex, binary and octal
   double h = 101010.0202 // OK, skip double literals
}

/var/tmp $ java  -jar checkstyle-8.32-all.jar -c config.xml TestClass.java
Starting audit...

Here are violations with // violation comment
```
Rationale: it is a bit difficult to read long numbers, separators are really helpful.
May be there can be some property like "minimalLength", which sets min length of literal, with default value of 4

**Comment by gaurabdg** [comment]
I am on it, once its approved

**Comment by rnveach** [comment]
How is this different from https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/master/sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/NumericLiteralNeedsUnderscoreCheck.java ?

**Comment by strkkk** [comment]
> How is this different from https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/master/sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/NumericLiteralNeedsUnderscoreCheck.java ?

The idea is the same, I was not aware of sevntu check and it can be closed as duplicate.

As for me, sevntu check looks a bit overloaded with options, in this one I propose to focus on int/long literals.
