### ISSUE TITLE
Support user list of annotations which should be verified by AnnotationOnSameLineCheck

### ISSUE THREAD

**Issue by Mmuzaf** [checkstyle/checkstyle#8078]
Documentation: https://checkstyle.sourceforge.io/config_annotation.html#AnnotationOnSameLine

--------------
## Proposal

I propose to add an additional property to the AnnotationOnSameLine check, so the check will be able to verify only specific annotations from the configured user list. Please, see the examples below.

--------------
#### /tmp/UserMessage.java
```
public class UserMessage extends Message {
    @Deprecated // violation
    @Nullable @Override public List<String> names() { //ok
        return null;
    }
}
```

#### /tmp/checkstyle.xml
```
<!DOCTYPE module PUBLIC "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
    "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
<module name="Checker">
    <module name="TreeWalker">
        <module name="AnnotationOnSameLine"/>
    </module>
</module>
```

#### Report
```
maxmuz@EUY-MMW-0008833 /tmp % java -Duser.language=en -cp checkstyle-8.31-all.jar com.puppycrawl.tools.checkstyle.Main -c /tmp/checkstyle.xml /tmp/UserMessage.java
Starting audit...
[ERROR] /tmp/UserMessage.java:6:5: Annotation 'Deprecated' should be on the same line with its target. [AnnotationOnSameLine]
Audit done.
Checkstyle ends with 1 errors.
```

#### /tmp/UserMessage.java
```
public class UserMessage extends Message {
    @Deprecated // ok
    @Nullable @Override public List<String> names() { //ok
        return null;
    }
}
```

#### /tmp/checkstyle.xml
```
<!DOCTYPE module PUBLIC "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
    "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
<module name="Checker">
    <module name="TreeWalker">
        <module name="AnnotationOnSameLine">
            <property name="annotations" value="Nullable,Override" />  <!-- Allowed annotations -->
        </module>
    </module>
</module>
```

#### Report
```
maxmuz@EUY-MMW-0008833 /tmp % java -Duser.language=en -cp checkstyle-8.31-all.jar com.puppycrawl.tools.checkstyle.Main -c /tmp/checkstyle.xml /tmp/UserMessage.java
Starting audit...
Audit done.
```

**Comment by romani** [comment]
please update description to show what is behavior now and as next example with new property.

**Comment by Mmuzaf** [comment]
@romani Hello, I've updated the issue.

**Comment by Mmuzaf** [comment]
@romani 
Can I start preparing PR? 
Do we need something else to proceed?

**Comment by Mmuzaf** [comment]
@romani @pbludov 

Folks, 
does everything OK with this issue? 
Can I proceed or you need something else?

**Comment by pbludov** [comment]
@Mmuzaf sorry for the delay, we have a huge amount of PR during GSOC. And they are in priority while GSOC is underway. As for this issue, there is no need for a dedicated property in the check.

Checkstyle has many ways to suppress violations that don't match the coding style of your team.
For example, you can do this with [XPathSuppression filter](https://checkstyle.org/config_filters.html#SuppressionXpathSingleFilter).
So your config should be something like this:
```xml
<!DOCTYPE module PUBLIC "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
    "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
<module name="Checker">
    <module name="TreeWalker">
        <module name="AnnotationOnSameLine">
        </module>
        <module name="SuppressionXpathSingleFilter">
          <property name="checks" value="AnnotationOnSameLine"/>
          <property name="query" value="//ANNOTATION[./IDENT[@text='Deprecated']]"/>
        </module>
    </module>
</module>
```
There are many examples in the docs. Please try this. If this works for you, then this issue can be closed.

**Comment by Mmuzaf** [comment]
@pbludov Thank you. The code below works fine (allow `AnnotationOnSameLine` only for `@Override` annotation) under 8.35 version.

```
        <module name="AnnotationOnSameLine" />
        <module name="SuppressionXpathSingleFilter">
            <property name="checks" value="AnnotationOnSameLine" />
            <property name="query" value="//ANNOTATION[.//IDENT[not(contains(@text, 'Override'))]]" />
        </module>
```
