### ISSUE TITLE
Enforce -e for all maven commands

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#8118]
Talked about in https://github.com/checkstyle/checkstyle/pull/8102#issuecomment-614658046 and identified in https://github.com/checkstyle/checkstyle/pull/8099#issuecomment-613768780 ,

We need to enforce all maven commands use `-e` to ensure we get stack trace of issue as it happens to ensure we can debug the issue. It is all too common an issue only happens once and we can never reproduce it again, as was seen in this case.

Only scripts and YML files are expected to be enforced. I used the following expression when I did my own manual update: `(mvn [^-])|(mvn \-[^e])`

**Comment by HuGanghui** [comment]
I am on it

**Comment by rnveach** [comment]
Fix is merged
