### ISSUE TITLE
new Cheeck: NoCodeInFile

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#8132]
to cover functionality that we removed from PackgeDeclaration Check at https://github.com/checkstyle/checkstyle/issues/8110

We need new Check to cover cases where all content is commented out. So file is not empty, but there is no java code .

It should print violations on files like the following:
````
$ cat TestClass.java

$ cat TestClass2.java
// violation

$ cat TestClass3.java
/* violation */
````

**Comment by gaurabdg** [comment]
I am on it, if its okay.

**Comment by rnveach** [comment]
Fix was merged
