### ISSUE TITLE
NeedBraces: xdoc rendering issue in examples

### ISSUE THREAD

**Issue by Gaurav-Punjabi** [checkstyle/checkstyle#8142]
Check documentation: https://checkstyle.sourceforge.io/config_blocks.html#NeedBraces

One of the example in xdocs of `NeedBracesCheck` has some rendering issue as shown in the screenshot below: 
<img width="1249" alt="Screen Shot 2020-04-20 at 11 50 06 PM" src="https://user-images.githubusercontent.com/36587580/79866937-29d3d580-83fb-11ea-9ef2-d5798a13b9b5.png">

**Comment by strkkk** [comment]
@Gaurav-Punjabi please highlight where the rendering issue is, it is not clear from screenshot

**Comment by Gaurav-Punjabi** [comment]
@strkkk I have updated the screenshot. As you can see the code of these examples are not enclosed inside a box (a source tag).

**Comment by AMFIRNAS** [comment]
I am on it

**Comment by Gaurav-Punjabi** [comment]
@AMFIRNAS I think you should first wait for the issue to get approved.

**Comment by rnveach** [comment]
@Gaurav-Punjabi You will need to provide more information as I see no highlighting in your image or even a basic description of what the rendering issue is.

When looking at the page I see the examples have no box around them while the others do. Is this what you are referring to? If so, did the current fixes for #8011 not fix this, which are still not yet released?

**Comment by Gaurav-Punjabi** [comment]
> When looking at the page I see the examples have no box around them while the others do. Is this what you are referring to?

Yes, that's the rendering issue.

> If so, did the current fixes for #8011 not fix this, which are still not yet released?

Yes, this PR fixes the rendering issue for `NeedBraces`. But the same issue is present in many checks at https://checkstyle.org/config_naming.html.
Example:
1. https://checkstyle.org/config_naming.html
2. https://checkstyle.org/config_naming.html#CatchParameterName_Examples
3. https://checkstyle.org/config_naming.html#AbstractClassName_Examples
4. https://checkstyle.org/config_naming.html#AbstractClassName_Examples

and many more on the same page.

**Comment by wltan** [comment]
> Yes, this PR fixes the rendering issue for `NeedBraces`. But the same issue is present in many checks at https://checkstyle.org/config_naming.html.

config_naming should already be fixed under #8005/#8007.

You can try looking for other examples. I know that the first few PRs I opened used `<source>` for the config and `<pre>` for the example code because there wasn't a clear convention yet.

**Comment by Gaurav-Punjabi** [comment]
> config_naming should already be fixed under #8005/#8007.

Yeah, it's fixed 👍 
Closing the issue

**Comment by AMFIRNAS** [comment]
ok, that's good.
