### ISSUE TITLE
Update Xpath unit tests to have at least two test methods

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#8151]
see list of Tests at fix for https://github.com/checkstyle/checkstyle/issues/7987

It make sense to create separate PRs for each check.

#### Suppressed Checks
- [x] XpathRegressionAnonInnerLengthTest
- [x] XpathRegressionAvoidDoubleBraceInitializationTest
- [x] XpathRegressionAvoidNoArgumentSuperConstructorCallTest
- [x] XpathRegressionJavadocStyleTest
- [x] XpathRegressionNestedForDepthTest
- [x] XpathRegressionNestedIfDepthTest
- [x] XpathRegressionUnnecessarySemicolonInEnumerationTest
- [x] XpathRegressionNestedTryDepthTest
- [x] XpathRegressionNoWhitespaceAfterTest
- [x] XpathRegressionNoWhitespaceBeforeTest
- [x] XpathRegressionOneTopLevelClassTest
- [x] XpathRegressionOuterTypeNumberTest
- [x] XpathRegressionSingleSpaceSeparatorTest
- [x] XpathRegressionUnnecessarySemicolonInTryWithResourcesTest
- [x] XpathRegressionUpperEllTest

**Comment by Gaurav-Punjabi** [comment]
I'm on it

**Comment by Gaurav-Punjabi** [comment]
@romani What about checks that have only one config (default). Should we suppress them or should I add another test case with the same config but different Input file?

**Comment by wltan** [comment]
Just a suggestion: You might want to leave out the `Fixes ...` in each PR description as right now merging **any** of the PRs will automatically close the issue. From what I understand you need **all** the PRs to be merged before the issue is fully resolved.

Keeping the issue number reference as required by the PR rules is fine, but remove the autolink keywords.

**Comment by Gaurav-Punjabi** [comment]
> Keeping the issue number reference as required by the PR rules is fine, but remove the autolink keywords.

Sure, thanks 👍

**Comment by strkkk** [comment]
@Gaurav-Punjabi if you are actively working on it, please add here checklist of all issues that require such changes. It can be marked as done after PR merge. In this case we will understand when to close this issue. Like

- [ ] check1

- [ ] check2

**Comment by Gaurav-Punjabi** [comment]
@strkkk Sure will do that. Also can you please answer this query  https://github.com/checkstyle/checkstyle/issues/8151#issuecomment-617254295

**Comment by strkkk** [comment]
@Gaurav-Punjabi I am not sure what should be done for this case. Lets first correct checks where not only default config is possible. @romani is pretty busy now, I hope he will clarify this later

**Comment by Gaurav-Punjabi** [comment]
#### Suppressed Checks
- [ ] XpathRegressionAnonInnerLengthTest
- [ ] XpathRegressionAvoidDoubleBraceInitializationTest
- [ ] XpathRegressionAvoidNoArgumentSuperConstructorCallTest
- [ ] XpathRegressionJavadocStyleTest
- [ ] XpathRegressionNestedForDepthTest
- [ ] XpathRegressionNestedIfDepthTest
- [ ] XpathRegressionNestedTryDepthTest
- [ ] XpathRegressionNoWhitespaceAfterTest
- [ ] XpathRegressionNoWhitespaceBeforeTest
- [ ] XpathRegressionOneTopLevelClassTest
- [ ] XpathRegressionOuterTypeNumberTest
- [ ] XpathRegressionSingleSpaceSeparatorTest
- [ ] XpathRegressionUnnecessarySemicolonInEnumerationTest
- [ ] XpathRegressionUnnecessarySemicolonInTryWithResourcesTest
- [ ] XpathRegressionUpperEllTest

The issue should close when tests to all these checks are added.

**Comment by strkkk** [comment]
@Gaurav-Punjabi I have added your checklist to first post, thank you.

**Comment by Gaurav-Punjabi** [comment]
> @romani What about checks that have only one config (default). Should we suppress them or should I add another test case with the same config but different Input file?

@romani What should I do in these type of checks?

**Comment by rnveach** [comment]
> should I add another test case with the same config but different Input file?

This. All checks should have atleast 2 cases. If we only have 1 log statement, then we need to have another input file with another case that is different from the original as much as possible.

**Comment by Gaurav-Punjabi** [comment]
Got it 👍

**Comment by Gaurav-Punjabi** [comment]
@romani @rnveach  I have added PR's for all the checks except `JavadocStyleCheck` and `UpperEllCheck`. I could not find any input cases for these that would be different from the first test case. What should I do? Should I add these similar cases to remove suppression?

**Comment by Rahulkhinchi03** [comment]
I am on XpathRegressionUpperEllTest

**Comment by Rahulkhinchi03** [comment]
@romani @strkkk @rnveach 
 `XpathRegressionNestedIfDepthTest` and  `XpathRegressionNestedForDepthTest` are already done. Please mark them done in PR description.

**Comment by Rahulkhinchi03** [comment]
@romani @strkkk  These are already done issues. Please mark them DONE in PR DESCRIPTION

```
XpathRegressionAvoidNoArgumentSuperConstructorCallTest 
 XpathRegressionNestedTryDepthTest 
XpathRegressionOuterTypeNumberTest
```

**Comment by Rahulkhinchi03** [comment]
How do we resolve it if we have no violation number: Is it a new issue or do we have a solution for it.

Error message at position 0 of 'expected' does not match actual message
expected: …onJavadocStyle.java:10:5: First sentence should end with a period.
but was: …onJavadocStyle.`java:9:` First sentence should end with a period.


INPUT FILE:
```
    /**
     * Some description here // warn
     */
    private void methodWithInvalidCommentStyle() {}
}
```

**Comment by romani** [comment]
No column looks like defect, please show by CLI what is output on this input

**Comment by Rahulkhinchi03** [comment]
![fgsdf](https://user-images.githubusercontent.com/71710042/163847303-cc7f4a74-e756-48da-8906-d5ec064a529e.png)

**Comment by Rahulkhinchi03** [comment]
![rgh](https://user-images.githubusercontent.com/71710042/163866389-357c83d6-22eb-48fc-9ef3-02784b01aaa2.png)

**Comment by romani** [comment]
Please create separate issue on this check to report violation on AST element (line and column), it might take a bit more effort than test creation.

**Comment by romani** [comment]
I marked XpathRegressionJavadocStyleTest as done, as we cannot compete it until #11549 , it will be done separately.

@Rahulkhinchi03 , can you help us to fix XpathRegressionOneTopLevelClassTest ? and close this issue.

**Comment by Rahulkhinchi03** [comment]
Okay, I am on it.

**Comment by romani** [comment]
Please update comment to be 
 
`Until https://github.com/checkstyle/checkstyle/issues/11549`

**Comment by romani** [comment]
Final fix is merged
