### ISSUE TITLE
XdocsJavaDocsTest fails to detect the absence of class javadoc

### ISSUE THREAD

**Issue by gaurabdg** [checkstyle/checkstyle#8155]
XdocsJavaDocsTest only validates the `xdocs` file description and corresponding class javadoc when it is non empty.
If someone is adding a new check and adds the description in xdocs only, no error is reported

**Comment by rnveach** [comment]
There should be an error reported by one of our other checks that the class needs a javadoc.

**Comment by gaurabdg** [comment]
Okay, got it! I am closing this then.
