### ISSUE TITLE
Update maven-javadoc-plugin to 2.10.2

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#816]
#### Release Notes - Maven JavaDoc Plugin - Version 2.10.2

Bug:

 * [MJAVADOC-365] - [Patch] sourceFileExcludes does not work due to inclusion of packages

Improvements:

 * [MJAVADOC-415] - Update plexus-archiver to 2.6.3 and p-utils to 3.0.18
 * [MJAVADOC-417] - Update version of plexus-archive from 2.5 to 2.9

**Comment by romani** [comment]
cobertura update was moved to #916
