### ISSUE TITLE
remove from configs hardcode caused by MCHECKSTYLE-332

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#8168]
https://issues.apache.org/jira/browse/MCHECKSTYLE-332 is released and we use latest plugin 
```
✔ ~/java/github/checkstyle/checkstyle [master|✔] 
$ ag "MCHECKSTYLE-332"
config/checkstyle_non_main_files_checks.xml
9:    <!-- Hard coded until https://issues.apache.org/jira/browse/MCHECKSTYLE-332 is released. -->
config/checkstyle_resources_checks.xml
10:    <!-- Hard coded until https://issues.apache.org/jira/browse/MCHECKSTYLE-332 is released. -->
config/checkstyle_sevntu_checks.xml
10:    <!-- Hard coded until https://issues.apache.org/jira/browse/MCHECKSTYLE-332 is released. -->
```

Expected:
remove comment and do changes in config if required.

**Comment by Gaurav-Punjabi** [comment]
I’m on it, once it’s approved.

**Comment by rnveach** [comment]
Not all configurations are being used by maven. `ant-phase-verify` has some which is not being invoked by `maven-checkstyle-plugin`. We need to look at all configurations and identify who is executing them.

If the config is run by Maven, we should remove the comment and hardcoded `cacheFile` property from the config. We need to verify the cache file is being created without the property. It should be located in the same place and name as with the property. We need some proof by execution output.

If the config is NOT run by Maven, the false comment should be removed and the hardcoded property more than likely has to stay.

We should look at any of our other configs to ensure they have a cache set properly, and are just not missing the comment.

**Comment by Gaurav-Punjabi** [comment]
@rnveach I played around with `maven-checkstyle-plugin` and came to know that only `config/checkstyle_sevntu_checks.xml` config is being used by this plugin. Also, I removed the property from `checkstyle_sevntu_checks.xml` and executed the plugin, it is still generating the cache file just with a different name `checkstyle-cache`.. I think this needs to be configured with the plugin. Should I do this ?


#### Output
1. `mvn clean verify`
```
gauravpunjabi@Gauravs-MacBook-Pro:~/Coding/Open Source/checkstyle$ mvn clean verify
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 1 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
.....
.....
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  04:31 min
[INFO] Finished at: 2020-04-23T00:30:05+05:30
[INFO] ------------------------------------------------------------------------
```

2. Cache File
```
gauravpunjabi@Gauravs-MacBook-Pro:~/Coding/Open Source/checkstyle/target$ ls | grep "checkstyle-cachefile"
checkstyle-cachefile
gauravpunjabi@Gauravs-MacBook-Pro:~/Coding/Open Source/checkstyle/target$ cat checkstyle-cachefile 
#Thu Apr 23 00:27:16 IST 2020
/Users/gauravpunjabi/Coding/Open\ Source/checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/MethodTypeParameterNameCheck.java=1585046503000
/Users/gauravpunjabi/Coding/Open\ Source/checkstyle/src/it/java/com/sun/checkstyle/test/chapter6declarations/rule61numberperline/MultipleVariableDeclarationsTest.java=1585046502000
......
```

**Comment by rnveach** [comment]
> Should I do this ?

Like I stated in my write up, we should remove it if we can rework the same behavior through the plugin itself. If it can't be reworked exactly, but close, let us know what will be different.

**Comment by rnveach** [comment]
Fix was merged
