### ISSUE TITLE
Making regex to validate missed space in comments in non main files

### ISSUE THREAD

**Issue by HuGanghui** [checkstyle/checkstyle#8169]
As mentioned in https://github.com/checkstyle/checkstyle/pull/8164#discussion_r412945036. Like <!--This .... there is missed space and non of our checks complain about this. So we need to make regexp to validate missed space in comments. 
I am pleasure to work on it.

**Comment by HuGanghui** [comment]
@romani please review this issue and approve~

**Comment by rnveach** [comment]
Fix was merged
