### ISSUE TITLE
maria.ramirez.ramirezx@romani any updates?

### ISSUE THREAD

**Issue by Maria198336** [checkstyle/checkstyle#8170]
@romani any updates?

_Originally posted by @strkkk in https://github.com/checkstyle/checkstyle/issues/6847#issuecomment-508476359_

**Comment by strkkk** [comment]
@Maria198336 I guess you missclicked.
In case you don't, please follow template or reply in original topic.

**Comment by Maria198336** [comment]
estoy tratando de recuperar mi canal
