### ISSUE TITLE
Add TODOs Badge to README

### ISSUE THREAD

**Issue by patrickdevivo** [checkstyle/checkstyle#8184]
Hi there! I wanted to propose adding the following badge to the README to indicate how many `TODO` comments are in this codebase:

[![TODOs](https://badgen.net/https/api.tickgit.com/badgen/github.com/checkstyle/checkstyle)](https://www.tickgit.com/browse?repo=github.com/checkstyle/checkstyle)

The badge links to `tickgit.com` which is a free service that indexes and displays TODO comments in public github repos. It can help surface latent work and be a way for contributors to find areas of code to improve, that might not be otherwise documented.

The markdown is:

```
[![TODOs](https://badgen.net/https/api.tickgit.com/badgen/github.com/checkstyle/checkstyle)](https://www.tickgit.com/browse?repo=github.com/checkstyle/checkstyle)
```

Thanks for considering, feel free to close this issue if it's not appropriate or you prefer not to!

(full disclosure, I am the creator/maintainer of `tickgit`)

**Comment by wltan** [comment]
There is already a TodoComment check that is being used to validate internal Checkstyle code, so there shouldn't be that many `TODO` comments lying around in the first place.
https://checkstyle.org/config_misc.html#TodoComment

It seems like most of the `TODO`s being reported by the badge are from UT input files, so maybe they might have been left there intentionally?

That's just my two cent's worth. Ultimately it's up to the admins to determine if they want such a badge or not.

**Comment by romani** [comment]
Thanks a lot but we do not need this service, our code is verified by checkstyle.
We do not need extra dependency

**Comment by patrickdevivo** [comment]
Understood! Thank you for considering and for your time!
