### ISSUE TITLE
FileContentsHolder does not have HTML documentation

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#819]
1) please create xdoc documentation for FileContentsHolder
2) update UT that check that all Checks are present to validate also all filters and other modules of Checker and TreeWalker.
3) We need to split page http://checkstyle.sourceforge.net/config.html into few pages (filter should go to separate sub page for sure). Please propose new structure.

**Comment by MEZk** [comment]
@romani 
Did you mean to update this UT?
[testAllChecksAreReferencedInConfigFile](https://github.com/checkstyle/checkstyle/blob/master/src/test/java/com/puppycrawl/tools/checkstyle/AllChecksTest.java#L144)

**Comment by romani** [comment]
The same priciple, but for html files, please create athoer test method.
