### ISSUE TITLE
Unclear beginning development instructions 

### ISSUE THREAD

**Issue by shashwat70** [checkstyle/checkstyle#8198]
https://checkstyle.org/beginning_development.html
The point number 6 given in this document results in a ton of commits being pulled from the main master and being pushed to the **current branch**. All these commits are visible and reflect in the PR, if already created.

I think we should make this addition to the 6th point:
```
git checkout master
git pull main master
git push origin master
```
Then point 7 becomes:
```
git checkout my-new-check
git rebase master
```
This will avoid confusion save a lot of time for someone who is new to contributing and git.

**Comment by romani** [comment]
Fix is merged
