### ISSUE TITLE
FileContentsHolder should be child of Cheker

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#820]
FileContentsHolder should be a child of Checker as it contains content of the file, so it is required for all modules - checks, filters, ...... .

I do not mark that issue as approved as it is going to seriously brake compatibility between releases, we need to think how to minimize affect on user. One idea is to allow that module to be attached to both parents but be registered only ones.

If smb have good ideas , please share them before any implementation
##

**Comment by rnveach** [comment]
@romani I am closing this as new issue, #3573, plans to do away with module entirely.
