### ISSUE TITLE
Jacoco coverage report should have grammar classes

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#8219]
found during https://github.com/checkstyle/checkstyle/pull/8093#issuecomment-622661127

when  we generate coverage report - https://github.com/checkstyle/checkstyle/wiki/How-to-run-certain-phases-and-validations#how-to-generate-ut-coverage-report

we do not see data on grammar classes, so it is hard to detect improvements.

It should be:
![image](https://user-images.githubusercontent.com/812984/80869166-9e0c4580-8c53-11ea-8afa-dfc22178f337.png)

**Comment by rnveach** [comment]
It is probably because they are being excluded.

https://github.com/checkstyle/checkstyle/blob/master/pom.xml#L828-L830

**Comment by romani** [comment]
> https://github.com/checkstyle/checkstyle/blob/master/pom.xml#L828-L830

yes, it is excludes for report

> https://github.com/checkstyle/checkstyle/blob/master/pom.xml#L849-L857

no, it is excludes for rules to fail `check` phase.

**Comment by rnveach** [comment]
Fix was merged
