### ISSUE TITLE
Resolve Pitest Issues - AbstractJavadocCheck

### ISSUE THREAD

**Issue by wltan** [checkstyle/checkstyle#8227]
Sub-issue of #7797/#6295

This issue is to discuss possible methods of resolving the 4 surviving mutations in `AbstractJavadocCheck`.

https://github.com/checkstyle/checkstyle/blob/9fa7233f42c1ed96e849b1d8d6cb9a7cab1cb52e/.ci/pitest.sh#L171-L174

Pitest report: https://wltan.github.io/checkstyle-reports/2020-05-09/pitest-abstractjavadoccheck/com.puppycrawl.tools.checkstyle.checks.javadoc/AbstractJavadocCheck.java.html

It is not as simple as the others where we can design additional UTs from regression to increase coverage, as the problems are with the code itself and not from a lack of testing.

As a supplementary note, there are only 8 `AbstractJavadocCheck`s that I am aware of.
1. [`MissingDeprecatedCheck`](https://github.com/checkstyle/checkstyle/blob/2e8c277c181487d81231170ff4b959edc008114e/src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/MissingDeprecatedCheck.java)
2. [`JavadocMissingWhitespaceAfterAsteriskCheck`](https://github.com/checkstyle/checkstyle/blob/1cc84e8b8f052249b10a11400a5571cfdaa30e21/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMissingWhitespaceAfterAsteriskCheck.java)
3. [`NonEmptyAtclauseDescriptionCheck`](https://github.com/checkstyle/checkstyle/blob/2e8c277c181487d81231170ff4b959edc008114e/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/NonEmptyAtclauseDescriptionCheck.java)
4. [`SingleLineJavadocCheck`](https://github.com/checkstyle/checkstyle/blob/8bf05ced07bb04c7240ae9f60ecda3c628e9b6f6/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SingleLineJavadocCheck.java)
5. [`JavadocTagContinuationIndentationCheck`](https://github.com/checkstyle/checkstyle/blob/a781a6608e270210c9ed07cc3d7fa465eb3c319e/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java)
6. [`JavadocBlockTagLocationCheck`](https://github.com/checkstyle/checkstyle/blob/ae9edbd4a8645c8cc1a99ad6890dd0006700d1cb/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocBlockTagLocationCheck.java)
7. [`JavadocParagraphCheck`](https://github.com/checkstyle/checkstyle/blob/ae9edbd4a8645c8cc1a99ad6890dd0006700d1cb/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocParagraphCheck.java)
8. [`SummaryJavadocCheck`](https://github.com/checkstyle/checkstyle/blob/32ea7c4bc1f5c16838fa568f395ebcb26bbf05b1/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SummaryJavadocCheck.java)

## 1
https://github.com/checkstyle/checkstyle/blob/2e8c277c181487d81231170ff4b959edc008114e/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheck.java#L189-L191

Mutation: `189 1. removed call to java/util/Arrays::sort → SURVIVED`

Though I haven't verified it rigorously yet, I believe that the root cause is most likely that each check already has all tokens in a sorted order to begin with, so `Arrays.sort` does nothing and can be removed.

The sort is done to speed up future queries on the array with binary search. A possible improvement might be to use a `HashSet` or similar data structure, removing the need for sorting at all.

## 2, 3
https://github.com/checkstyle/checkstyle/blob/2e8c277c181487d81231170ff4b959edc008114e/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheck.java#L350-L354

Mutations: 
1. `351 1. removed call to com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheck::beginJavadocTree → SURVIVED`
2. `353 1. removed call to com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheck::finishJavadocTree → SURVIVED`

None of the subclasses ever need to use `beginJavadocTree` or `finishJavadocTree`. Hence when they are removed, behavior does not change at all, so the mutations survive.

https://github.com/checkstyle/checkstyle/search?q=beginjavadoctree&unscoped_q=beginjavadoctree
https://github.com/checkstyle/checkstyle/search?q=finishjavadoctree&unscoped_q=finishjavadoctree

This case does not have a very clear solution. Obviously we can just remove the methods entirely, but that is likely not good for future development. Another way would be to artificially modify some of the checks to make use of the two extra methods so that unit tests will fail if they are not called.

## 4
https://github.com/checkstyle/checkstyle/blob/2e8c277c181487d81231170ff4b959edc008114e/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheck.java#L168-L178

Mutation: `174 1. removed call to java/util/Set::clear → SURVIVED`

Interestingly, there are no code references to this method at all, so I am not sure where the UT coverage is coming from in the first place.

https://github.com/checkstyle/checkstyle/search?q=setjavadoctokens

In any case, I believe that the line can be removed (after regression testing of course). Note that the similar method for `AbstractCheck` does not contain the `clear()` either.

https://github.com/checkstyle/checkstyle/blob/911afa5cdae2baa93c90d3ae2de7c6f2326cd491/src/main/java/com/puppycrawl/tools/checkstyle/api/AbstractCheck.java#L84-L91

**Comment by wltan** [comment]
## 5 (bonus)
There is one more line where the mutation is `TIMED_OUT` instead of `SURVIVED`.
https://github.com/checkstyle/checkstyle/blob/2e8c277c181487d81231170ff4b959edc008114e/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheck.java#L377

Mutation: `377 1. negated conditional → TIMED_OUT`

This is not under the 4 suppressions above, but can also be explored as part of #5673.

**Comment by rnveach** [comment]
It is too much to discuss all in one issue, which is why we had separate issues for each item.

> Arrays.sort does nothing and can be removed.

There is no guarantee that users will always sort their tokens. It returns an array and not a set. We can't change our implementation or impose this on users. If we need unsorted tokens, then this sounds like an easy matter to add a test for to kill the mutation.

> This case does not have a very clear solution.

See above. When you look at mutations, the first thing to look for is missing tests. Pitest's main feature is it measures how many tests your code has and if there is enough. Only when mutation can't be hit, or thorough analysis says code should have never been introduced, do we look at removing it.

**Comment by wltan** [comment]
> There is no guarantee that users will always sort their tokens.

That is true. I think I may have worded my original post a bit strangely, I did not mean to say that it can just be removed like that and be done with it, but rather that currently the tokens may be coincidentally already all sorted for each check, which is why the mutation survives.

So in order to kill the mutation caused by sorting, I would like to propose building a `Set` and querying it instead of sorting (which is _currently_ but _not necessarily_ redundant) and binary searching.

> When you look at mutations, the first thing to look for is missing tests.

The problem is that the default implementation of the two methods looks like this:
https://github.com/checkstyle/checkstyle/blob/2e8c277c181487d81231170ff4b959edc008114e/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheck.java#L223-L243

But none of the checks so far have needed to override and implement these methods. If you just want to add new tests, then you'd also have to somehow come up with a brand new check on the fly just to implement `beginJavadocTree` and `finishJavadocTree` so that you can fail the test when they are removed.

If that can be done, I have no further comment, but otherwise my point still stands that it is going to be more complicated than simply finding new tests to add.

For the record, I do not support outright removal either, even if it is completely redundant today. A future check may need to use those methods so the mutation _will_ eventually be killed, is it just a matter of when.

**Comment by rnveach** [comment]
> I would like to propose building a Set and querying it instead of sorting

We would probably discuss this in a PR. Is there any performance impact from switching like this?

https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/TreeWalker.java#L209
We do the same thing in TreeWalker, so it could also be looked into killing the mutation.

> The problem is that the default implementation of the two methods looks like this:

https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/AbstractCheck.java#L145
We have a similar method in AbstractCheck that I am not seeing as a surviving mutant. I would look into how it was killed.

**Comment by rnveach** [comment]
Issue is approved, but we should look to build cases to kill issues before removing/changing code.

**Comment by romani** [comment]
> `"AbstractJavadocCheck.java.html:<td class='covered'><pre><span  class='survived'>            Arrays.sort(acceptableJavadocTokens);</span></pre></td></tr>"`

should be resolved by creation of bad configuration for tokens property to let code do not find tokens. We can create fake Check in test to make it.

**Comment by Vyom-Yadav** [comment]
@nick-mancuso @romani @rnveach Can we close this? This has been addressed.

**Comment by Vyom-Yadav** [comment]
All the cases are covered in #10126 except
```
$ cat pitest-javadoc-suppressions.xml | grep "Arrays.sort(acceptableJavadocTokens);"

```

**Comment by romani** [comment]
will be handled by https://github.com/checkstyle/checkstyle/issues/13672
