### ISSUE TITLE
Update CIs to validate empty outpu of 'git status' after execution

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#8228]
we discussed this a lot but never made any action on this.
It become problem at https://github.com/checkstyle/checkstyle/pull/8136#discussion_r419466250 again.
We wasting time in updates and conversations that can be caught at the very begining.

Rationale:
We execute CIs commands on local for testing, pollution in git repo make it ease to put in commit/PR unwanted changes, extra files, ......

It is required to update all CIs to have validation that `git status` is empty. If some files are created they should be moved to `.ci-temp` or added to `.gitignore` (as last option)

**Comment by nmancus1** [comment]
I can take care of this right now, I should just add a job like `validate-git-status` to each ci script?

**Comment by romani** [comment]
Yes, we need to print output and fail build it is not empty.

**Comment by strkkk** [comment]
Fix is merged
