### ISSUE TITLE
One more group is required for CustomImportOrder

### ISSUE THREAD

**Issue by astappiev** [checkstyle/checkstyle#8241]
I would like to create an Eclipse-like rule for imports. The documentation has a few examples in that direction, but they are missing that fact that Eclipse also separates `java.*` and `javax.*` packages.

Using this rule from documentation
```xml
<module name="CustomImportOrder">
  <property name="customImportOrderRules"
    value="STATIC###STANDARD_JAVA_PACKAGE###SPECIAL_IMPORTS###THIRD_PARTY_PACKAGE"/>
  <property name="specialImportsRegExp" value="^org\."/>
  <property name="thirdPartyPackageRegExp" value="^com\."/>
  <property name="sortImportsInGroupAlphabetically" value="true"/>
  <property name="separateLineBetweenGroups" value="true"/>
</module>
```

I'm getting the following error
```
Extra separation in import group before 'javax.xml.bind.annotation.XmlAccessType' (6:0) [CustomImportOrder]
```

For that class
```java
package mypackage;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;

@XmlAccessorType(XmlAccessType.FIELD)
public class AuthorizationEntity {
    // ...
}
```

And to fix that, I need to create a separate group for `javax.*` imports, but there are no more groups available. An ability to create more groups if required would be great, but that will require more changes. What about something simple, I guess many people separate `org.` group, so I propose to add `ORG_PACKAGE` with default regexp to `^org\.`, then I can reuse `SPECIAL_IMPORTS` for `javax.`.  Or another solution is to create `SPECIAL_IMPORTS_2`, `SPECIAL_IMPORTS_3`, etc :)

I can create a pull request, but I don't know what solution is preferable.

I also found [another issue](https://github.com/checkstyle/checkstyle/issues/4338) where someone tried to create Eclipse-like rules using `ImportOrder` rule, but I would like to use `CustomImportOrder` because it provides more meaningful messages.

**Comment by astappiev** [comment]
Nevermind, I changed to use of `ImportOrder` rule.

**Comment by romani** [comment]
>but I would like to use CustomImportOrder because it provides more meaningful messages.

Please share more details on this, we can change wording to make them better.

**Comment by astappiev** [comment]
Current message looks like
```
Wrong order for 'org.apache.logging.log4j.Logger' import. (36:1) [ImportOrder]
```

But I would like to have something similar to what I get with `CustomImportOrder`:
```
Wrong order for 'org.apache.logging.log4j.Logger' import. Should be after 'org.apache.logging.log4j.LogManager'. (36:1) [ImportOrder]
```
or
```
Wrong order for 'org.apache.logging.log4j.Logger' import. Should be in group 'org'. (36:1) [ImportOrder]
```

**Comment by romani** [comment]
@astappiev , I moved your concern to https://github.com/checkstyle/checkstyle/issues/8315, you are welcome with PR.
