### ISSUE TITLE
CustomImportOrder should allow for a newline between java.* and javax.* imports

### ISSUE THREAD

**Issue by Flowdalic** [checkstyle/checkstyle#8248]
Since checkstyle 8.28, due #7119, CustomImportOrder ensures that there is no superflous separation between import groups. While this is sensible, there is an issue: Eclipse's "Organize Imports" feature does not allow regex when specifying groups. This means that java.* and javax.* imports are always different groups and hence separated by newlines in eclipse. Checkstyle versions < 8.28 did not complain about that.

Now my codebase, where I provide a eclipse importorder configuration file, can not be upgraded easily to checkstyle 8.28 or higher: I can not (easily) split java.* and javax.* into two groups in checkstyle, nor can I tell eclipse that 'java(x?)' are the same group.

One solution would be that CustomImportOrder has a setting which allows a newline between the java.* and javax.* import groups.

**Comment by martincalvert** [comment]
Any update on this? Running into this now as well. And the effort required to refactor the imports across all our packages is a bit too high for a non major bump. 

Adding a MISC_PACKAGE to the order and allowing regex defined on that would solve the issue for my cases at least.

**Comment by Bukama** [comment]
> I can not (easily) split java.* and javax.* into two groups in checkstyle, nor can I tell eclipse that 'java(x?)' are the same group.

My team has the same issue after updating checkstyle, without changing the ruleset to remove empty lines between groups and update all our application's source files (thousands over about hundres of apps) cause of this...

I either suggest do ignore empty lines inside the `STANDARD_JAVA_PACKAGE` or add another `STANDARD_JAVAEE_PACKAGE` (with javax or jakarate regex) group-rule.

**Comment by romani** [comment]
https://checkstyle.org/checks/imports/customimportorder.html#CustomImportOrder

Is very special Check that is created to cover requirements of Google java style. It might not be good for general usage.

Consider to use https://checkstyle.org/checks/imports/importorder.html and/or Filters like https://checkstyle.org/filters/suppressionsinglefilter.html#SuppressionSingleFilter to remove undesirable violations.
