### ISSUE TITLE
Sonar violations: Refactor the body of this try/catch to have only one invocation throwing an exception

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#8249]
master bulid failure - https://sonarcloud.io/organizations/checkstyle/rules?open=java%3AS5778&rule_key=java%3AS5778

https://rules.sonarsource.com/java/RSPEC-5778

When verifying that code raises a runtime exception, a good practice is to avoid having multiple method calls inside the tested code, to be explicit about which method call is expected to raise the exception.
It increases the clarity of the test, and avoid incorrect testing when another method is actually raising the exception.

src/.../puppycrawl/tools/checkstyle/DefaultLoggerTest.java
src/.../puppycrawl/tools/checkstyle/DetailNodeTreeStringPrinterTest.java
src/.../puppycrawl/tools/checkstyle/JavadocPropertiesGeneratorTest.java
src/.../puppycrawl/tools/checkstyle/PackageObjectFactoryTest.java
src/.../puppycrawl/tools/checkstyle/PropertyCacheFileTest.java
src/.../puppycrawl/tools/checkstyle/XMLLoggerTest.java
src/.../tools/checkstyle/ant/CheckstyleAntTaskTest.java
src/.../tools/checkstyle/api/AbstractFileSetCheckTest.java
src/.../tools/checkstyle/api/FileTextTest.java
src/.../tools/checkstyle/checks/TrailingCommentCheckTest.java
src/.../tools/checkstyle/checks/header/RegexpHeaderCheckTest.java
src/.../checkstyle/checks/javadoc/AbstractJavadocCheckTest.java
src/.../tools/checkstyle/filters/SuppressWithPlainTextCommentFilterTest.java
src/.../tools/checkstyle/gui/ParseTreeTablePresentationTest.java
src/.../checkstyle/internal/powermock/MainFrameModelPowerTest.java
src/.../tools/checkstyle/utils/AnnotationUtilTest.java
src/.../tools/checkstyle/utils/CheckUtilTest.java
src/.../tools/checkstyle/xpath/RootNodeTest.java

**Comment by romani** [comment]
There is a conflict between Eclipse and Sonar 
![image](https://user-images.githubusercontent.com/812984/82742099-736f5300-9d0e-11ea-9153-980e39db6938.png)

What we value most ?
I think Eclipse should win.

**Comment by romani** [comment]
false positive: c-tor of Hashset do not throw exception.
![image](https://user-images.githubusercontent.com/812984/82742225-27251280-9d10-11ea-850d-59451d2ceaca.png)

**Comment by romani** [comment]
wont fix.

technically it is valid violation, but such cases Rule should skip as they are in `fail`.  
![image](https://user-images.githubusercontent.com/812984/82742396-710ef800-9d12-11ea-97fe-c0688a85cb8c.png)

**Comment by rnveach** [comment]
> false positive: c-tor of Hashset do not throw exception.

A more lenient reading of the rules means to avoid extra method calls, regardless if they can throw an exception or not, to avoid any confusion. Runtime exceptions are not usually documented, and some are possible to have anywhere like NPE. I think this rule is just finding 1 method with an exception being thrown and ensure there are no other method calls on the same line.

**Comment by romani** [comment]
Ok, but still "won't fix" , as compliant code will be a bit weird

**Comment by pbludov** [comment]
fix is merged
