### ISSUE TITLE
Sonar violations: JUnit5 test classes and methods should have default package visibility

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#8252]
https://sonarcloud.io/project/issues?id=org.checkstyle%3Acheckstyle&open=AXItYgyWEeM3Dea7mBcs&resolved=false&severities=INFO

https://rules.sonarsource.com/java/RSPEC-5786

![image](https://user-images.githubusercontent.com/812984/82742993-96533480-9d19-11ea-9dc5-4fb470ea305e.png)

**Comment by romani** [comment]
Should we follow this rule ?

**Comment by rnveach** [comment]
I am fine with test only code removing the modifiers.

**Comment by pbludov** [comment]
> Should we follow this rule ?
> 
> We already had discussion on this somewhere, but I do not remember where. What is left in my memory is to keep visibility as public, as it doesn't help at all to be less be public

The transition to JUnit5 was automated by IntellyJ IDEA. The access modifiers were not changed during that process, we agreed that this can be done in a separate issue.

At first glance, it looks like an easy sed task:
`sed -i "s/public void test/void test/g"`
since we already has a rule to enforce the `test` prefix in all test methods.

**Comment by pbludov** [comment]
I think that all test classes should be non-public and even final, to make it impossible to use one test from another and create unnecessary dependencies.

**Comment by romani** [comment]
please read - https://stackoverflow.com/a/55230350/1015848 nothing about encapsulation and less visibility (that I agreee), just a matter of style.

> and even final

it is separate issue ... we can do it even for public classes.

> create unnecessary dependencies

still be possible in the same package. Inheritance from tests classes is very weird, I have never see this in my life.

**Comment by romani** [comment]
I marked as won't fix all such violations in sonar https://sonarcloud.io/summary/new_code?id=org.checkstyle%3Acheckstyle

There will be more to appear as we can not disable rule, but we have bulk update now in UI for we will mark as won't fix periodically.
