### ISSUE TITLE
insert space after opening brace in array initializer

### ISSUE THREAD

**Issue by damianszczepanik** [checkstyle/checkstyle#826]
I found that code formatter we use does not follow javadoc rules we validate. Using this rule https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/master/sevntu-checks/CheckstyleFormatterForEclipse.xml#L12 I got error
```
TreeWalker.java:267:31: '{' is followed by whitespace.
```

**Comment by romani** [comment]
Checkstyle does not follow any rules from sevntu-checks, experimental project have experimental configuration. 

Checkstyle have own rules that described at https://github.com/checkstyle/checkstyle/blob/master/config/checkstyle_checks.xml , yes we are not compatible with existing Eclipse formatter :( , that we will definetely address after finish stabilization period. There are already a lot of talk about that , but as it is not simple task it is still not done :( .
