### ISSUE TITLE
Increase font size for website

### ISSUE THREAD

**Issue by jo2** [checkstyle/checkstyle#8264]
As menttioned [here](https://github.com/checkstyle/checkstyle/issues/8244#issuecomment-632704253) the general font size fo the documentation is an issue. If this issue is approved I can start a PR.

**Comment by jo2** [comment]
I've uploaded a suggestion on [https://jo2.github.io/checkstyle-font-size/](https://jo2.github.io/checkstyle-font-size/). The size is oriented twoards the 120% to 130% zoom you've mentioned. Please let me know what you think.

We might increase the width of the menu. so the entries are in one line though.

**Comment by strkkk** [comment]
@jo2 it looks good but left menu items have like to space between, it looks a bit ugly.
So may it make sense to increase margin for items and make left menu wider.
![image](https://user-images.githubusercontent.com/8901354/83537675-8a2b5c00-a4fd-11ea-91ac-2128f042439b.png)

**Comment by jo2** [comment]
I've added some margin between the menu items and increased the menu width so that every menu item is displayed in a single row.

An aspect which I can't change that easiyl is that the images are stil in the same size, for example the "follow on twitter" image. If you want, I can take a look at this though.

**Comment by strkkk** [comment]
@jo2 I think it is better now, but still items are overlapping
![image](https://user-images.githubusercontent.com/8901354/84152907-ee09d380-aa6d-11ea-9203-7179195f5138.png)

**Comment by jo2** [comment]
I increased the margin at the top and the bottom of the menu entries. I hope it works now

**Comment by strkkk** [comment]
@jo2 lgtm. I think PR can be created to review changes.

**Comment by rnveach** [comment]
Fix was merged.
