### ISSUE TITLE
List of checks in checkstyle.org has incorrect link for AvoidDoubleBraceInitialization

### ISSUE THREAD

**Issue by binoternary** [checkstyle/checkstyle#8265]
**Problem description:**
https://checkstyle.org/checks.html contains a list of checks. This list includes `AvoidDoubleBraceInitialization`.

Clicking on the respective link takes the user to https://checkstyle.org/config_misc.html#AvoidDoubleBraceInitialization

But the check is documented under https://checkstyle.org/config_coding.html#AvoidDoubleBraceInitialization

(**config_misc** vs **config_coding**)

**Expected behavior:**
Clicking the `AvoidDoubleBraceInitialization` link in https://checkstyle.org/checks.html takes the user to the documentation for that check.

**Actual behavior:**
Clicking the `AvoidDoubleBraceInitialization` link in https://checkstyle.org/checks.html takes the user to a page where documentation for that check is not found.

**Comment by strkkk** [comment]
@binoternary thanks for reporting this.
Issue has been fixed in https://github.com/checkstyle/checkstyle/issues/7889, and link will be fixed in next release 8.33
