### ISSUE TITLE
Implement full records support

### ISSUE THREAD

**Issue by nmancus1** [checkstyle/checkstyle#8267]
Per discussion at https://github.com/checkstyle/checkstyle/issues/8023#issuecomment-634424931 and https://github.com/checkstyle/checkstyle/issues/8023#issuecomment-634628277. While a superficial implementation of Java 14 records will close Issue #8023, we need to make an issue for full records support, extending our support of records to build the full AST under the RECORD_DEF token.  

### Topics of discussion:

1. Which checks should be extended to support records
2. How to handle constructors.  While a new compact constructor for records must be defined, records must also support canonical constructors with some restrictions (see [JLS](https://docs.oracle.com/javase/specs/jls/se14/preview/specs/records-jls.html#jls-8.10.4)).  Should this compact constructor be added to `field` grammar?  
3. New tokens to introduce.  Per https://github.com/checkstyle/checkstyle/issues/8023#issuecomment-634628277 we will be introducing `RECORD_COMPONENT_DEF` and `RECORD_CTOR_DEF`, is this all?
4. ...

http://cr.openjdk.java.net/~gbierman/jep359/jep359-20191031/specs/records-jls.html#jls-8.10.5

**Comment by pbludov** [comment]
The checks to be reviewed:
* All annotation checks, as `RECORD_COMPONENT` may  be annotated
* All type-specific checks, as records are another kind of type
* Some whitespace checks, as `{}` (empty body) is common for records

**Comment by nmancus1** [comment]
> The checks to be reviewed..

Thank you, I will make note of any insight for supporting these checks while I work on #8023.

**Comment by pbludov** [comment]
From #8308 

Adding new keywords to a language is very difficult, since they are probably used as identifiers in the existing code. Our parser should accept such keyword as an identifier, but we need a new check. Something like `AvoidUsingKeywordsAsIdentifiers`.

**Comment by rnveach** [comment]
Fix was merged
