### ISSUE TITLE
Cleanup .ci-temp folder after release notes generation

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#8268]
https://travis-ci.org/github/checkstyle/checkstyle/jobs/692192105#L1082

```
Directory .ci-temp/ is not empty. Verification failed.
Contents of .ci-temp/:
checkstyle
contribution
mailing_list.txt
rss.txt
twitter.txt
xdoc.xml
```

**Comment by romani** [comment]
@nmancus1 , please help, it is leftover.

**Comment by nmancus1** [comment]
Hi, just trying to run `xtr_releasenotes-gen.sh` locally to verify clean `.ci-temp/`, but `READ_ONLY_TOKEN=9ffd28f` results in `"message":"Bad credentials"`.  Does this token need to be updated?

**Comment by romani** [comment]
Let's fix this issue in blind way, without verification on local.

**Comment by romani** [comment]
@nmancus1 , thanks a lot.
