### ISSUE TITLE
Update documentation for BeforeExecutionExclusionFileFilter

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#8269]
Check documentation: https://checkstyle.org/config_filefilters.html#BeforeExecutionExclusionFileFilter

We need to have example of how user can exclude test folders in projects.

Detected at https://github.com/checkstyle/eclipse-cs/issues/132

**Comment by roopbiswas** [comment]
I would like to work on this. Can you give some idea of how to go about creating the example? Also it would be helpful if you can point me to some already created examples.

**Comment by romani** [comment]
thanks a lot for desire to help
please read https://github.com/checkstyle/checkstyle/issues/7698 
and see latest referenced commit to see where and what was changed. 
You just need to change another file, all website doc are in our sources.

**Comment by IsuruBoyagane15** [comment]
Can I work on this issue?

**Comment by jindalsachin** [comment]
I would like to work on this and add examples for excluding test files .
But i cannot find the code for the previous Examples in the BeforeExecutionExclusionFileFilter.xml .
 Can you pls tell me what am imissing here and point me in the right direction?

**Comment by jindalsachin** [comment]
So shall i add example in documentation of module info file along with test file??

**Comment by Ritik2604** [comment]
I think the previous contributor is not interested If you want me to work on it I will happily do so @romani @timurt

**Comment by Ritik2604** [comment]
Just found a new easy way to exclude test directories as well as files for checking which is totally different from this mentioned issue.

> Is there an easy way to exclude Maven test directories from checking? 
Issue :#132 

Do I add the steps to the Documentation
![Step1](https://user-images.githubusercontent.com/49342895/113459507-5ed21000-9433-11eb-8d6b-756e565535ee.jpg)

![sTEP 2](https://user-images.githubusercontent.com/49342895/113459524-6ee9ef80-9433-11eb-892f-8eeb80045792.jpg)

**Comment by romani** [comment]
We need update on Filter documentation on how to use this Filter in xml config.

We do not need idea setup, we already have it.
https://checkstyle.org/idea.html

**Comment by Ritik2604** [comment]
@romani that is not an idea setup I just show how to exclude test files directories for checking

**Comment by romani** [comment]
merged
