### ISSUE TITLE
Update java.g to allow new tokens to be added

### ISSUE THREAD

**Issue by nmancus1** [checkstyle/checkstyle#8274]
We need to update java.g `tokens` block to reflect last tokens added.  This must be done to preserve the ordering of tokens and correctly allow new tokens to be added. 

### Tokens to add to the end of the list: 

- `SINGLE_LINE_COMMENT_CONTENT`
- `BLOCK_COMMENT_CONTENT`
- `STD_ESC`
- `BINARY_DIGIT`
- `ID_START`
- `ID_PART`
- `INT_LITERAL`
-  `LONG_LITERAL`
- `FLOAT_LITERAL`
- `DOUBLE_LITERAL`
- `HEX_FLOAT_LITERAL`
- `HEX_DOUBLE_LITERAL`
- `SIGNED_INTEGER`
- `BINARY_EXPONENT`

**Comment by pbludov** [comment]
All of them are already in the grammar, right?

**Comment by nmancus1** [comment]
Yes.

**Comment by rnveach** [comment]
Fix was merged.
