### ISSUE TITLE
Spotbugs should validate tests

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#8275]
>[WARNING] Auxclasspath entry file:/home/travis/build/checkstyle/checkstyle/target/test-classes doesn't exist, ignoring it

Sounds suspicious, we need to make sure that tests are not ignored

_Originally posted by @romani in https://github.com/checkstyle/checkstyle/pull/8254#issuecomment-633796675_

**Comment by romani** [comment]
fix is merged
