### ISSUE TITLE
Javadoc Modification for Metadata Generation Support

### ISSUE THREAD

**Issue by gaurabdg** [checkstyle/checkstyle#8306]
This issue is to keep track of the changes made to the class level javadocs of checks and filters.

### The corresponding PRs(having 10 checks each) will add
- Datatype of each property 
- Parent module of the check/filter
- Violation message keys
- Modified javadoc UTs

### Changes in javadoc HTML pages

- Datatypes
![Screenshot_20200608_054808](https://user-images.githubusercontent.com/23253816/83983404-c0c50480-a94b-11ea-8d6e-df8d4fbfb27c.png)
- Parent Module and Violation Messages
![Screenshot_20200605_235037](https://user-images.githubusercontent.com/23253816/83910065-8b6fb980-a787-11ea-9267-336ee306397c.png)

# Task Breakup
- [x] UT addition for the modified javadocs
- [x] Modification 1
- [ ] Modification 2
- [ ] Modification 3
- [ ] Modification 4
- [ ] Modification 5
- [ ] Modification 6
- [ ] Modification 7
- [ ] Modification 8
- [ ] Modification 9
- [ ] Modification 10
- [ ] Modification 11
- [ ] Modification 12
- [ ] Modification 13
- [ ] Modification 14
- [ ] Modification 15
- [ ] Modification 16
- [ ] Modification 17
- [ ] Modification 18

**Comment by rnveach** [comment]
IMO,
> - Datatypes
![Screenshot_20200605_235021](https://user-images.githubusercontent.com/23253816/83910058-8874c900-a787-11ea-9627-0fbb330b5d58.png)

Javadoc tries to be as user friendly as possible. When we redid all javadocs, we made sure property descriptions follow a strict pattern, which was grueling in the beginning. IMO, `Datatype - XXX` is not very user friendly. Even default value follows a nice sentence structure. I would like to see something like "The type of the property is XXX" and "XXX" be the same as the xdoc display. It also makes sense that the type is conveyed before the default value.

**Comment by romani** [comment]
Ok let's try to put type before default value, to match xdoc.

After private discussion with @rnveach , it is ok to use simply "Type is xxxx"

**Comment by gaurabdg** [comment]
@romani Okay. Can you please approve for CI to pass?

**Comment by gaurabdg** [comment]
> IMO,
> 
> > * Datatypes
> >   ![Screenshot_20200605_235021](https://user-images.githubusercontent.com/23253816/83910058-8874c900-a787-11ea-9627-0fbb330b5d58.png)
> 
> Javadoc tries to be as user friendly as possible. When we redid all javadocs, we made sure property descriptions follow a strict pattern, which was grueling in the beginning. IMO, `Datatype - XXX` is not very user friendly. Even default value follows a nice sentence structure. I would like to see something like "Type is XXX" and "XXX" be the same as the xdoc display. It also makes sense that the type is conveyed before the default value.

@romani @rnveach The reason why type came after default value is that, `Default value is` is not always present in a new line and was getting difficult for me to parse, since I automated the whole process. Similarly when I will write the javadoc parsing utility, I would face some issues. So, in these PRs I would also like to change all such occurences to a new line.

**Comment by romani** [comment]
Final fix is merged
