### ISSUE TITLE
Java Grammar: need to introduce "id" rule to solve keyword as identifier problem

### ISSUE THREAD

**Issue by nmancus1** [checkstyle/checkstyle#8308]
In order to facilitate the proper implementation of records grammar, in addition to mitigating other future "keyword as identifier" issues, we need to introduce an "id" rule in the parser, which will replace the use of IDENT:

`id: IDENT;`

### Why?
In the case of 'records':

The basic grammar for records will consist of something similar to `classDefinition`:
```
recordDeclaration![AST modifiers]
    :   r:"record" IDENT
        (tp:typeParameters)?
        recordComponents
        implementsClause
        recordBodyDeclaration
        {#recordDeclaration = #(#[RECORD_DEF, "RECORD_DEF"],
                              modifiers, IDENT);}
    ;
```
The inclusion of "record" automatically makes an entry in the literal table called "record" and the lexer concludes that anytime "record" is parsed, it must be a record declaration.  Even in Java 14, with "preview" enabled, "record" is not a reserved keyword, so no sort of version checking, etc., can or should be implemented to determine whether record should be treated as an identifier or keyword. 

 It is possible to use logic in the lexer, like in the case of `ENUM` and `ASSERT`, to keep "record" out of the literals table, but for records, we must check the following tokens to see if we have a record declaration or else "record" is being used as an identifier. 

The problem with this approach, besides its inefficiency, is that we must cover all possible permutations of "record" as an identifier usage.  This includes:
```
    private static void record(LogRecord... logArray) {
        for (LogRecord record : logArray) {
            record.getLevel();
        }
    }

    private static void checkRecord() {
        LogRecord record;
        record = new LogRecord(Level.ALL, "abc");
        assertEquals(Level.INFO, record.getLevel());
    }

    private static int record = 2;
    recordString = recordString.substring(record, 5);

...

```
not to mention that we have to consider whitespace too! So this is not a good approach.

Adding the proposed rule to the parser enables us to do this:

`id: IDENT | "record" ;`

This keeps unwanted complexity from being added to the lexer, and allows the lexer to pass all keywords to the parser, where the above rule lies.  We can then, in the parser, re-set the type of token (if necessary):

```
id: IDENT | recordKey ;
recordKey: "record" {#recordKey.setType(IDENT);};
```

  This method is the preferred method to solve the "keyword-as-identifier" problem in ANTLR, and will be much faster (switch statement checking int values) than comparing the text of the token ( `token.getText()`) or using lots of look-ahead and comparing characters.

This change from using IDENT in the parser to the `id` rule will help future proof our grammar and make it more extensible, too.  This grammar could easily be extended to:

```
// id rule
id: IDENT | keyword;

// list of keywords that are also identifiers
keyword: "record'
    |  "otherkeyword1"
    |  "otherkeyword2"
    | ...
;
```

**Comment by rnveach** [comment]
> id: IDENT | "record" ;

Won't this cause confusion in the grammar? The text "record" is an "IDENT" already. I can write a java program with that as the variable name with no compile errors.

According to http://cr.openjdk.java.net/~gbierman/jep359/jep359-20191031/specs/records-jls.html#jls-8.10 , record is a whole new declaration and must be written as such.

**Comment by nmancus1** [comment]
>Won't this cause confusion in the grammar?

I would certainly leave some comments in the grammar as an explanation, but this is the preferred way to deal with this issue.

>I can write a java program with that as the variable name with no compile errors.

Once "record" is in the literals table, this becomes a "keyword as identifier" problem. There is definitely other ways to handle this (I've tried at least 50 different implementations ) , but they require too much noise and complexity in the lexer, and will prove difficult to support.  From a performance perspective, this is also much better than the alternatives. 

> record is a whole new declaration and must be written as such.

That is what I have done (see https://github.com/checkstyle/checkstyle/pull/8293, parser grammar only. The proposed change in this issue would eliminate any changes in the lexer) , and addressing this issue paves the way for the optimal records implementation. If you have "The Definitive ANTLR 4 Reference", check out chapter 12.  I know that our grammar is written in ANTLR2, but this is still the preferred way to handle this.

**Comment by rnveach** [comment]
> I would certainly leave some comments in the grammar as an explanation

I was referring to how antlr processes the grammar. If antlr gets confused or needs to guess to identify the language will cause slowdowns like https://github.com/checkstyle/checkstyle/issues/1064#issuecomment-200387660 and https://github.com/checkstyle/checkstyle/issues/8291 .

If this is necessary for another change than I just wasn't seeing the full picture. It would be helpful to showcase why this is needed like we have in our default template.

I didn't understand what the "keyword as identifier" issue is you refer to at first, but I think I understand now what this is for. I just ask you check run time for slowdowns.

**Comment by nmancus1** [comment]
> It would be helpful to showcase why this is needed like we have in our default template.

My apologies, I will re-work the issue above, and give more detail.

> I just ask you check run time for slowdowns.

Is there a good way to quantify this?

**Comment by esilkensen** [comment]
Could the regression report tools be configured to optionally include something in the report like, for each project, checkstyle execution time on base branch = A, and on patch branch = B?

**Comment by pbludov** [comment]
@rnveach Our parser should be able to parse existing Java 8 code like [this](https://github.com/CS-SI/Orekit/blob/develop/src/main/java/org/orekit/bodies/JPLEphemeridesLoader.java#L499) and Java 14 code where the `record` is a keyword. And here we come to _positional_ keywords. The approach suggested by Nick is the common way in such cases. We have a keyword, but it can be used as an identifier. A possible alternative is to add the `language level` property to the parser. Up to level 14, the `record` will be an identifier, then it will be a keyword.

@nmancus1 I like this idea and I would like to see the regression report.

**Comment by esilkensen** [comment]
I wonder if `record` will become an actual keyword by the time it makes it into an official, non-preview release, or if it will continue on as a valid identifier... I'd guess it is a pretty common one.

**Comment by pbludov** [comment]
> I wonder if `record` will become an actual keyword by the time it makes it into an official, non-preview release, or if it will continue on as a valid identifier... I'd guess it is a pretty common one.

Most likely, this will remain a restricted name (like ' var`):
```shell
$ cat TestClass.java 
public class record {
}
public class var {
}

$ /usr/lib/jvm/java-14-openjdk-amd64/bin/javac --enable-preview --source 14 TestClass.java 
TestClass.java:1: error: 'record' not allowed here
public class record {
             ^
  as of release 13, 'record' is a restricted type name and cannot be used for type declarations
TestClass.java:5: error: 'var' not allowed here
public class var {
             ^
  as of release 10, 'var' is a restricted type name and cannot be used for type declarations
2 errors
```
The compiler already issues an error here.

**Comment by nmancus1** [comment]
It should be noted that it is still a valid identifier, just not for classes:
```
➜  java14_test cat TestClass.java 
public class TestClass {
    private int record = 4;
    public record Test(String test) {}
}
➜  java14_test /usr/lib/jvm/java-14-openjdk/bin/javac --enable-preview --source 14 TestClass.java
Note: TestClass.java uses preview language features.
Note: Recompile with -Xlint:preview for details.
➜  java14_test 


```

**Comment by pbludov** [comment]
Even this one compiles:
```java
record Record(Record record) {}
```

**Comment by romani** [comment]
fix is merged
