### ISSUE TITLE
update dependanbot to use it as github feature

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#8309]
https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/

migrate config to native Github support.

**Comment by rnveach** [comment]
@romani Is this an issue we can close?

**Comment by romani** [comment]
Fixed a long time ago at https://github.com/checkstyle/checkstyle/commit/97a6af1f59b21eca87e54489725009ee442e2826#diff-dd4fbda47e51f1e35defb9275a9cd9c212ecde0b870cba89ddaaae65c5f3cd28
