### ISSUE TITLE
Change name of checkstyle types to be close to real java types

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#8311]
as we agreed at https://github.com/checkstyle/checkstyle/pull/8305#discussion_r436750608

we need to change names of our types in html(xdoc) documentations, it will not be change in functionality, just make naming for exact.

https://checkstyle.org/property_types.html

**Types:**
| old name  | new name  | Comment  |
|---        |---        |---        |
| integer   |  numeric  | it is **not** Integer, it is all numerical types (byte,short,int,long,float, double, and their class type analogs), there is NO BigDecimal, BigInteger support.    |
| string    | String    | in javadoc name is java.lang.String, in xdoc should be short `String`  |
| boolean   | Boolean   | in javadoc name should java.lang.Boolean, in xdoc should be `Boolean`  |
| stringSet  | stringColllection  | It is comma separated and trimmed Strings. [RelaxedStringArrayConverter](https://github.com/checkstyle/checkstyle/blob/2e8c277c181487d81231170ff4b959edc008114e/src/main/java/com/puppycrawl/tools/checkstyle/api/AutomaticBean.java#L358)  |
|  intSet | numericCollection  | It is primitive type arrays only byte[], short[], ......., no array of types support.  |
| regexp   | Pattern  | there special [converter](https://github.com/checkstyle/checkstyle/blob/2e8c277c181487d81231170ff4b959edc008114e/src/main/java/com/puppycrawl/tools/checkstyle/api/AutomaticBean.java#L298), but does simple `java.util.regex.Pattern` instantiation. in javadoc `java.util.regex.Pattern` in xdoc `Pattern`  |
| uri   |  uri | should stay the same, as there is special [converter](https://github.com/checkstyle/checkstyle/blob/2e8c277c181487d81231170ff4b959edc008114e/src/main/java/com/puppycrawl/tools/checkstyle/api/AutomaticBean.java#L331) with custom logic on priority to match resource, details are at [doc](https://checkstyle.org/property_types.html#uri)  |
|  file |  -- |  this type need to be removed as it is used only ones at Checker.cacheFile, and actual type of this property is `String`, [code](https://github.com/checkstyle/checkstyle/blob/c42a0e1b63c33400e05c98b62179cf303724e525/src/main/java/com/puppycrawl/tools/checkstyle/Checker.java#L148) |
| lineSeparator  |  LineSeparatorOption | Check do conversion to enum LineSeparatorOption by 'Enum.valueOf', javadoc should have fully qualified name, xdoc short name of enum  |
| parenPad   |  PadOption | com.puppycrawl.tools.checkstyle.checks.whitespace.PadOption name is javadoc and short name in xdoc  |
| wrapOp  | WrapOption  |  com.puppycrawl.tools.checkstyle.checks.whitespace.WrapOption name in javadoc and short name in Xdoc |
| block  | BlockOption  | com.puppycrawl.tools.checkstyle.checks.blocks.BlockOption name in javadoc and BlockOption in xdoc  |
| lcurly  | LeftCurlyOption  |  com.puppycrawl.tools.checkstyle.checks.blocks.LeftCurlyOption name in javadoc and BlockOption in xdoc |
| rcurly  | RightCurlyOption  | com.puppycrawl.tools.checkstyle.checks.blocks.RightCurlyOption name in javadoc and BlockOption in xdoc  |
| scope  |  Scope | in javadoc new name `com.puppycrawl.tools.checkstyle.api.Scope` in xdoc `Scope`. even there is custom converter, it does simple instantiation of Scope enum.  |
| access_modifiers  | accessModifierCollection  |  [special convert](https://github.com/checkstyle/checkstyle/blob/2e8c277c181487d81231170ff4b959edc008114e/src/main/java/com/puppycrawl/tools/checkstyle/api/AutomaticBean.java#L383) is used  |
| severity  | SeverityLevel  | in javadoc `com.puppycrawl.tools.checkstyle.api.SeverityLevel` in xdoc SeverityLevel. there is custom converter, it does simple instantiation of SeverityLevel enum. |
| importOrder  |  ImportOrderOption |  com.puppycrawl.tools.checkstyle.checks.imports.ImportOrderOption name is javadoc and short name in xdoc |
| elementStyle | ElementStyle  |  com.puppycrawl.tools.checkstyle.checks.annotation.AnnotationUseStyleCheck.ElementStyle name is javadoc and short name in xdoc |
| closingParens  | ClosingParens  |  com.puppycrawl.tools.checkstyle.checks.annotation.AnnotationUseStyleCheck.ClosingParens name is javadoc and short name in xdoc |
| trailingArrayComma  | TrailingArrayComma  | com.puppycrawl.tools.checkstyle.checks.annotation.AnnotationUseStyleCheck.TrailingArrayComma name is javadoc and short name in xdoc  |
| javadocContentLocation  |  JavadocContentLocationOption | com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocContentLocationOption name is javadoc and short name in xdoc |

We should update https://checkstyle.org/property_types.html to mention exact name of classes and probably event provide link to source.

We should sort type alphabetically to ease search by users (as last PR)

**Attention**: AnnotationUseStyleCheck has 3 inner enums that are listed here.

converters are at https://github.com/checkstyle/checkstyle/blob/2e8c277c181487d81231170ff4b959edc008114e/src/main/java/com/puppycrawl/tools/checkstyle/api/AutomaticBean.java#L117

custom types converters - https://github.com/checkstyle/checkstyle/blob/2e8c277c181487d81231170ff4b959edc008114e/src/main/java/com/puppycrawl/tools/checkstyle/api/AutomaticBean.java#L163

**Comment by gaurabdg** [comment]
Changes to be made:
`stringSet` -> `stringCollection`

**Comment by strkkk** [comment]
@romani 
I suggest change `numeric` to `Number` and `numericCollection` to `numberCollection`
Other things looks fine

**Comment by romani** [comment]
@strkkk , https://docs.oracle.com/javase/8/docs/api/java/lang/Number.html is type in java, we do not support all sub classes.
`numeric` was used as it is not a type

**Comment by rnveach** [comment]
I am fine with names but I would like to consistency with casing. Some start with uppercase, some start with lowercase. I think all should upper case to follow class names.

After seeing list, do we want to have another issue to change all enum class names to be `XxxOption`?

**Comment by romani** [comment]
All lowercase are intentional, I try clearly show that it is not a type of java and it is something special.

**Comment by strkkk** [comment]
> Please confirm that you are ok with such name.

I am ok

**Comment by rnveach** [comment]
> All lowercase are intentional

My remark was that not all are lowercase. String is uppercase, while numeric is lowercase. All the enums are uppercase.

> ElementStyle , ClosingParens, TrailingArrayComma should be renamed to have Option as suffix.
We can keep Scope as is as I think we will remove this enum eventually.

I agree.

**Comment by romani** [comment]
confusion with lowercase can be resolved is we convert our some specific parsing to exact java type
and unhide all hidden details of `integer` and other less frequent types.

PROPOSAL:

remove `integer` and `intSet` and use show user real types we support(taken from our code):

boolean 
Boolean
boolean[]

char
Character
char[]

byte
Byte
byte[]

short
Short
short[]

int
Integer
int[]

long
Long
long[]

float
Float
float[]

double
Double
double[]

forget about any custom types and clearly show type from Checks, like `AccessModifier[]`, `URI`, `String[]`. Fact that we some special converter is details on checkstyle library implementation, plugins should not that much care.
Default/Acceptable/Required Tokens (to make selection by users), plugins will get from Check instantiation during UI rendering.
For enums we will be honest  - type is `String. Value of ClosingParens`.
`tokens` - `String[]. Subset of tokens .....` [code](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/AbstractCheck.java#L95).

In metadata we can put extra property `values-provider` and set it as enum type fully qualified name, to let plugins get all possible values. Property `tokens` should be special property and plugins should know about it and get all values from Check instance.

**Comment by rnveach** [comment]
> Fact that we some special converter is details on checkstyle library implementation, plugins should not that much care.

Converter never played a part in type display for xdoc. It is literally only for making setters a bit nicer, and have common functionality. So I agree to ignore them.

> For enums we will be honest - type is String. Value of ClosingParens. tokens - String[]. Subset of tokens ..... code.

I don't see how this will help the users. We will say type is String which will either point to our area that says String is free form or will be known as free form, but then we will display another notice that you are restricted to a list of values from our enum and link to that as well.

To me this doesn't come off as very clear and I think we are doing a better job now saying it is the enum type and not say "but it is technically a string".

I would rather keep xdoc clear of any internal jumbo and keep simple and clear to the users. Users don't care that it is technically a string, they want to know what values they can use and how those values affect their validation.

**Comment by romani** [comment]
Are you ok if we be exact on type in javadoc and metadata file BUT we will simplify it in xdoc to hide non required details?

**Comment by rnveach** [comment]
I am hesitant to say yes to javadoc, but it is more technical documentation so there is some merit in making it known there. I won't put up a fuss on that.

Technically everything is a String once we remove the converters. As we said, converters won't play a role here. If we remove the converters, everything would have a String setter, so we would need to specify everything as a String as an alternate type. If not, then what purpose does the meta file need to know that the exact setter, which they can find with reflection, takes that specific type as a parameter.

**Comment by romani** [comment]
Right now we have both case:
- Exact type
- String that hide exact type

The reason behind usage of "String that hide exact type" is because exact types usage in Checks properties/setters force us to make converter, but converters are located in API package . We afraid to extend API by such item, and we would like to keep exact type of property close to Check and let it have the same lifecycle as Check or property in Check. Converter/Type in API mean keep it forever.

So in recent Checks we use String as property type and use exact enum to load value from string.

Reflection to get type can be used for Checks  that use exact type this is true. But we are in a mix state (both approaches are in use). I am not ready to start process of defining future of type concept for Checks properties and metadata files keep us room to choose any approach later on.
If we go completely to Strings, such metadata of underlining type become critical and information of main type (setter parameter) become redundant but might be used for compatibility.
If we stay in mix - it is required to cover both cases.
if we go to use exact types, insofrmation about underling type become redundant, and can be copy of main type.

We need some solution right now, so we need to use two type for now.

We are removing `integer` and `intCollection`, `stringCollection` and use `int`, `int[] or byte[] or ...`, `String[]` ... in xdoc details for types we will explain that elements should be sepaated by `,` .

**Comment by gaurabdg** [comment]
@romani Why are not all enum types appended with "Option" suffix? (`closingParens`, `elementStyle` ...)

**Comment by rnveach** [comment]
> Why are not all enum types appended with "Option" suffix? (closingParens, elementStyle ...)

Most likely, it was from a lack of detailed review for the naming convention when they were first implemented. We only cared about the xdoc name and didn't think much of the enum since it wasn't being documented to users. With documentation now in extract file, it is coming more to light and thats why we said we would fix all their names.

**Comment by romani** [comment]
all actions will be #8328
