### ISSUE TITLE
Resolve Sonar violation 'This branch's code block is the same as the block for the branch on line'

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#8336]
Sonar violation https://sonarcloud.io/project/issues?id=org.checkstyle%3Acheckstyle&open=AXLiCslKkpVZ0x1TON5t&resolved=false&severities=MAJOR

![image](https://user-images.githubusercontent.com/812984/85576306-27554e00-b5ed-11ea-827b-c114472a0c03.png)

Code looks very strange, lets investigate it.

code was recently added in https://github.com/checkstyle/checkstyle/blame/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/AbstractExpressionHandler.java#L428

**Comment by romani** [comment]
@Abhishek-kumar09 , please address

**Comment by Abhishek-kumar09** [comment]
OK @romani , I am on it.

**Comment by romani** [comment]
fix is merged.
