### ISSUE TITLE
Allow Ant task to support generation of Xpath suppressions. 

### ISSUE THREAD

**Issue by Fernal73** [checkstyle/checkstyle#8340]
**Is your feature request related to a problem? Please describe.**
Ant task does not support generation of Xpath suppressions. 

**Describe the solution you'd like**

It would be nice to have the [Ant task](https://checkstyle.sourceforge.io/anttask.html) modified to generate Xpath suppressions as currently possible through the CLI using the -g switch.

https://checkstyle.sourceforge.io/cmdline.html#Command_line_usage

https://checkstyle.sourceforge.io/anttask.html#Parameters

Added:

Link to discussion on Maven User Group:

http://maven.40175.n5.nabble.com/Access-or-generate-a-classpath-for-dependency-not-in-any-scope-but-attached-to-plugin-td6005018.html

Link to Maven issue :

https://issues.apache.org/jira/plugins/servlet/mobile#issue/MCHECKSTYLE-396/comment/17146092

This explains the workflow that's possible for Xpath suppressions.

**Comment by strkkk** [comment]
@Fernal73 It is not clear what do you mean. Please follow issue template to show what the problem is.

**Comment by Fernal73** [comment]
What's not clear, @strkkk ?
My post or the command line documentation for -g?
Updated post above with link to discussion on Maven User Group...

**Comment by Fernal73** [comment]
> @Fernal73 It is not clear what do you mean. Please follow issue template to show what the problem is.

What do you mean, @strkk? I'm simply asking for the feature of generating Xpath suppressions to be added to the ant task as well. Is this still an experimental feature?

**Comment by Fernal73** [comment]
Wrt to the command line usage, is there any particular reason to disallow specifying a directory to be processed? Should I raise another issue for that?

**Comment by rnveach** [comment]
Why do you want ant task to generate suppressions for you? Ant is more for batch commands and I don't see xpath suppression generation as really being batch friendly since it doesn't save to any file.

**Comment by Fernal73** [comment]
```
#!/usr/bin/env bash
usage()
{
  echo "Usage: $0 dir rulesfile"
  echo "dir - Project directory"
  echo "rulesfile - Rules file"
  exit 1
}

readOptions()
{
  [ -e "$proj"/"$optionsFile" ] && \
      { readarray -t options < <(cat "$proj"/"$optionsFile") || \
      echo "Unable to read $proj/$optionsFile";}
}

if [ "$#" -lt 1 ] || ! [ -d "$1" ]; 
then
  usage
fi

proj=$1
declare -r optionsFile=".csoptions"
declare -r suppressionsFile="suppressions-xpath.xml"
declare -a options
rules_file=$(realpath "csrules.xml")
declare -r properties_file=$(realpath "checkstyle.properties")
output_file="cs.errors"
declare -r classpathFile=$(realpath "cs.cp")
mainClass="com.puppycrawl.tools.checkstyle.Main"
echo "$1"
if [ -n "$2" ]
  then
    rules_file=$(realpath "$2")
fi
if [ ! -e "$rules_file" ]
  then
    echo "$rules_file cannot be found."
    usage
fi

if [ ! -e "$classpathFile" ]
  then
    echo "$classpathFile cannot be found. Run ant in root directory to generate file."
    usage
fi

if [ ! -e "$properties_file" ]
  then
    echo "$properties_file not found. Creating..."
    touch "$properties_file" || \
      echo "Unable to create $properties_file"
    echo "Create/Modify $properties_file to configure checkstyle"
fi

readOptions
(set -o pipefail; cd "$1" && \
readarray -t args \
  < <(find . -type f -name "*.java" \
  ! -path "docs/**" ! -path "dist/**") && \
  find . -maxdepth 1 -name "$suppressionsFile" -type f -exec mv {} {}.bak \; && \
  java -cp @"$classpathFile" \
  "$mainClass" \
  ${options[@]} \
  -c "$rules_file" -d \
  -p "$properties_file" \
  -o "$1"-xpath.xml -g \
  "${args[@]}";)
ret=$?
if [ -s "$1"/"$1"-xpath.xml ]
then
  mv "$1"/"$1"-xpath.xml "$1"/"$suppressionsFile"
  ret=("$ret" + "$?")
fi
exit "$ret"
```

My workflow for Xpath suppressions. Could this be done in an ant task?

The Xpath suppression file value matches the one in the config file.

**Comment by romani** [comment]
Ant task is not designed to do any activity other than validation of code, extension of it will be hard damage of design.

You should use custom code to make it happen.
We might consider to update CLI to do suppression xml generation based on XML report (that you can generate by ANT task).

Massive suppression by Xpath is not frequent operation, it is good only for initial introduction of checkstyle to project.

You can create issue on CLI to do this.

**Comment by Fernal73** [comment]
I'd prefer a separate ant task for the same.

Also, the way I do it is fix all the Checkstyle violations and then only
run the Xpath suppressions task since I prefer to not annnotate the
suppressions in the code especially the ones with MagicNumber violations.

I don't want to remove that rule either since it's useful to identify
possible constants.

**Comment by Fernal73** [comment]
What do you mean by updating CLI?

More than current option -g?

The config rules file can specify the Xpath suppressions file.

Are you considering adding an option for specifying suppression file in the
CLI?

That's something Maven currently provides. But I don't think that supports
Xpath suppressions, does it?

**Comment by Fernal73** [comment]
Wrt to the ant task and the proposed workflow, I think a new task that generates suppressions is needed. As far as I can see, Xpath suppressions are not used extensively and the best way to encourage its usage is through an ant task and Maven/Gradle goals.

Xpath suppressions are superior to regex ones since they are less susceptible to changes in the source code i.e., line number changes.

**Comment by romani** [comment]
> I'd prefer a separate ant task for the same.

you can create it and we will host it at https://github.com/checkstyle/contribution
