### ISSUE TITLE
Checkstyle CLI should accept directories as input

### ISSUE THREAD

**Issue by Fernal73** [checkstyle/checkstyle#8344]
**Is your feature request related to a problem? Please describe.**
The CLI does not accept directories as input. This must be allowed. 

**Describe the solution you'd like**
Process all files under the directories specified. The input can be a mix of directories and files. 

Referred from:

https://github.com/checkstyle/checkstyle/issues/8340#issuecomment-649640571

http://maven.40175.n5.nabble.com/Access-or-generate-a-classpath-for-dependency-not-in-any-scope-but-attached-to-plugin-td6005018.html

**Comment by rnveach** [comment]
We do accept directories as input.
https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/Main.java#L227

We would need to know more information about your issue to help.

**Comment by Fernal73** [comment]
Hmm.... so it seems.
Let me check out and see what is the problem again.
I had a problem running Checkstyle through the javaexec goal of the Exec Maven plugin. 
It was not finding the <files> parameter despite specifying the directory.
The directory works currently through the command line though it picks up more than just the Java sources under the directory.

**Comment by Fernal73** [comment]
``` xml
   <plugin>
          <groupId>org.codehaus.mojo</groupId>
          <artifactId>exec-maven-plugin</artifactId>
          <version>${maven.exec.plugin.version}</version>
<executions>
  <execution>
    <configuration>
      <mainClass>${cs.main.class}</mainClass>
      <commandLineArgs>-c checkstyle.xml -p checkstyle.properties -o DSAlgos-xpath.xml -g ${basedir}/src</commandLineArgs>
      <arguments>-c checkstyle.xml -p checkstyle.properties -o DSAlgos-xpath.xml -g ${basedir}/src</arguments>
      <classpathScope>test</classpathScope>
    </configuration>
            <id>checkstyleg</id>
              <phase>validate</phase>
            <goals>
              <goal>java</goal>
            </goals>
          </execution>
        </executions>
        </plugin>
      ```
The above is the XML fragment that sets out the Checkstyle executable in maven. This gives me the <files> parameter missing error.

Am I missing something?

**Comment by Fernal73** [comment]
It appears that the arguments have to be nested with `argument` elements within container `arguments`.

http://www.vineetmanohar.com/2009/11/3-ways-to-run-java-main-from-maven/
