### ISSUE TITLE
Java14 enhanced instanceof check validation: AnnotationOnSameLineCheck

### ISSUE THREAD

**Issue by nmancus1** [checkstyle/checkstyle#8359]
Child of #8391 
Check documentation: https://checkstyle.sourceforge.io/config_annotation.html#AnnotationOnSameLine
Identified at #8294 (comment)

We need to validate that AnnotationOnSameLineCheck works as intended once #8294 is merged.

**Comment by romani** [comment]
not affected after AST structure change
