### ISSUE TITLE
Java14 enhanced instanceof check validation: AnnotationLocationCheck

### ISSUE THREAD

**Issue by nmancus1** [checkstyle/checkstyle#8360]
Child of #8391 
Check documentation: https://checkstyle.sourceforge.io/config_annotation.html#AnnotationLocation
Identified at https://github.com/checkstyle/checkstyle/pull/8294#issuecomment-650896023

We need to validate that AnnotationLocationCheck works as intended once #8294 is merged.

**Comment by nmancus1** [comment]
From check documentation:
_Checks location of annotation on language elements. _

From JEP:
_The instanceof grammar is extended accordingly:_
_RelationalExpression:_
     _..._
     _RelationalExpression instanceof ReferenceType_
     _RelationalExpression instanceof Pattern_

_Pattern:_
     _ReferenceType Identifier_

We can see that pattern variables have no annotations, so I think that this check does not apply.  Do you agree @esilkensen @pbludov ?

**Comment by romani** [comment]
anntations are not applicable in instanceof pattern.
