### ISSUE TITLE
Java14 enhanced instanceof check validation: DeclarationOrderCheck

### ISSUE THREAD

**Issue by nmancus1** [checkstyle/checkstyle#8361]
Child of #8391 
Check documentation: https://checkstyle.sourceforge.io/config_coding.html#DeclarationOrder
Identified at https://github.com/checkstyle/checkstyle/pull/8294#issuecomment-650896023

We need to validate that DeclarationOrderCheck works as intended once #8294 is merged.

**Comment by nmancus1** [comment]
**From the check documentation:**

_Checks that the parts of a class or interface declaration appear in the order suggested by the Code Conventions for the Java Programming Language._

_According to Code Conventions for the Java Programming Language , the parts of a class or interface declaration should appear in the following order:_

_- Class (static) variables. First the public class variables, then protected, then package level (no access modifier), and then private._
 _- Instance variables. First the public class variables, then protected, then package level (no access modifier), and then private._
 _- Constructors_
 _- Methods_

Since a pattern variable is part of a relational expression, this check does not apply.  @esilkensen @pbludov what do you think? Can we close this?

**Comment by esilkensen** [comment]
Sounds good to me
