### ISSUE TITLE
Java14 enhanced instanceof check validation: EqualsAvoidNullCheck

### ISSUE THREAD

**Issue by nmancus1** [checkstyle/checkstyle#8362]
Child of #8391 
Check documentation: https://checkstyle.sourceforge.io/config_coding.html#EqualsAvoidNull
Identified at https://github.com/checkstyle/checkstyle/pull/8294#issuecomment-650896023

We need to validate that EqualsAvoidNullCheck works as intended once #8294 is merged.

**Comment by nmancus1** [comment]
From check documentation: 
_Checks that any combination of String literals is on the left side of an equals() comparison. Also checks for String literals assigned to some field (such as someString.equals(anotherString = "text"))._

From [JLS](https://docs.oracle.com/en/java/javase/14/docs/specs/patterns-instanceof-jls.html#jls-6.3.1):
_The null literal is compatible with a type test pattern._

Consider:
```
➜  instanceof-pattern-var-def java $RUN_LOCALE -jar ~/IdeaProjects/checkstyle/target/checkstyle-8.35-SNAPSHOT-all.jar -c config.xml TestClass.java
Starting audit...
Audit done.
➜  instanceof-pattern-var-def /usr/lib/jvm/java-14-openjdk/bin/javac --enable-preview --source 14 TestClass.java
Note: TestClass.java uses preview language features.
Note: Recompile with -Xlint:preview for details.
➜  instanceof-pattern-var-def cat config.xml    
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
          "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
  <module name="TreeWalker">
      <module name="EqualsAvoidNull"/>
  </module>
</module>
➜  instanceof-pattern-var-def cat TestClass.java
public class TestClass {
    static {
        String nullString = null;
        if (nullString instanceof String str) {
            // This should be a violation
            str.equals("My_Sweet_String");
        }
    }
}%                                                                              ➜  instanceof-pattern-var-def java $RUN_LOCALE -jar ~/IdeaProjects/checkstyle/target/checkstyle-8.35-SNAPSHOT-all.jar -c config.xml TestClass.java
Starting audit...
Audit done.
```
This should be a violation.  What do you think @pbludov @esilkensen ?

**Comment by esilkensen** [comment]
Interesting - since the pattern variable is implicitly final, if the instanceof check succeeds, I think we should have a guarantee that the variable is not null, and so it may actually be better if the check *doesn’t* flag this as a violation...

**Comment by nmancus1** [comment]
>so it may actually be better if the check doesn’t flag this as a violation...

Can you explain more? The line `str.equals("My_Sweet_String");`
should cause a violation, because the string literal should be on the LHS.

**Comment by esilkensen** [comment]
I’m interested what @pbludov thinks, but it seems like it may be desirable for the check not to flag that as a violation since the purpose of it is to avoid NPE and we know that if “xxx instanceof String str” succeeds, then any reference to that str is safe from a NPE.

**Comment by esilkensen** [comment]
That said, if someone wanted to be literal about the rule and flag *any* occurrence of “variable equals string literal” regardless of whether the compiler knows that the variable can not be null, then they may want a violation - so it seems possibly subjective to me, I will defer to others...

**Comment by nmancus1** [comment]
>and we know that if “xxx instanceof String str” succeeds, then any reference to that str is safe from a NPE

That is a good point. I wonder, is this about best practices as well though?   Even though we know there will be no NPE, should checkstyle complain about such code? I too am interested to see what others think.

**Comment by romani** [comment]
yes, we need to update Check to violate this.

**Comment by pbludov** [comment]
The new `instanceof` operator works exactly the same as the old one:
```java
class TestClass {

    public static void main(String... args) {
        String nullString = null;
        if (nullString instanceof String) {
            System.out.println("null is instanceof String");
        } else {
            System.out.println("null is NOT instanceof String");
        }
        if (nullString instanceof String str) {
            System.out.println("null is instanceof String str");
        } else {
            System.out.println("null is NOT instanceof String str");
        }
    }
}
```
$ /usr/lib/jvm/java-14-openjdk-amd64/bin/java --enable-preview --source 14 TestClass.java 
Note: TestClass.java uses preview language features.
Note: Recompile with -Xlint:preview for details.
null is NOT instanceof String
null is NOT instanceof String str
```

From the point of view of the check, there is no difference between the old and new operator `instanceof`. We just need to add new test inputs. Most likely, no need to update the check code.

**Comment by nmancus1** [comment]
@pbludov from the description of the check, and what I would expect, this should be a violation:
```
        if (nullString instanceof String str) {
            // This should be a violation
            str.equals("My_Sweet_String");
        }
```
From the check docucmentation:
_Checks that any combination of String literals is on the left side of an equals() comparison._

**Comment by romani** [comment]
yes, violation.

**Comment by esilkensen** [comment]
Fix is merged
