### ISSUE TITLE
Java14 enhanced instanceof check validation: ExplicitInitializationCheck

### ISSUE THREAD

**Issue by nmancus1** [checkstyle/checkstyle#8363]
Child of #8391 
Check documentation: https://checkstyle.sourceforge.io/config_coding.html#ExplicitInitialization
Identified at https://github.com/checkstyle/checkstyle/pull/8294#issuecomment-650896023

We need to validate that ExplicitInitializationCheck works as intended once #8294 is merged.

**Comment by nmancus1** [comment]
From the check documentation:
_Checks if any class or object member is explicitly initialized to default for its type value (null for object references, zero for numeric types and char and false for boolean._

From [JLS](https://docs.oracle.com/en/java/javase/14/docs/specs/patterns-instanceof-jls.html#jls-6.3.1):
_Pattern variables are implicitly final by design._
_..._
_This process is conditional; a pattern variable is only assigned a value if the pattern match succeeds._

Since pattern matching is an implicit assignment, and pattern variables are implicitly final, this check does not apply to pattern variables. @pbludov @esilkensen can we close this one?

**Comment by esilkensen** [comment]
Sounds good to me
