### ISSUE TITLE
Java14 enhanced instanceof check validation: HiddenFieldCheck

### ISSUE THREAD

**Issue by nmancus1** [checkstyle/checkstyle#8364]
Child of #8391 
Check documentation: https://checkstyle.sourceforge.io/config_coding.html#HiddenField
Identified at https://github.com/checkstyle/checkstyle/pull/8294#issuecomment-650896023

We need to validate that HiddenFieldCheck works as intended once #8294 is merged.

From check documentation:
_Checks that a local variable or a parameter does not shadow a field that is defined in the same class._

Note that a pattern variable is considered a  binding variable, and not a local variable.  Does this check apply? 

```
➜  initial-pattern-def-grammar /usr/lib/jvm/java-14-openjdk/bin/javac --enable-preview --source 14 TestClass.java
Note: TestClass.java uses preview language features.
Note: Recompile with -Xlint:preview for details.
➜  initial-pattern-def-grammar cat config.xml    
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
          "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">

  <module name="JavadocPackage"/>
  <module name="TreeWalker">
	<module name="HiddenField">
	  <property name="tokens" value="VARIABLE_DEF"/>
	</module>
  </module>
</module>
➜  initial-pattern-def-grammar cat TestClass.java
public class TestClass {
    private String hidden = "hidden";

    public TestClass(Object x) {
        if (x instanceof String hidden) {
            System.out.println(hidden);
        }
    }
}
➜  initial-pattern-def-grammar java $RUN_LOCALE -jar ~/IdeaProjects/checkstyle/target/checkstyle-8.35-SNAPSHOT-all.jar -c config.xml TestClass.java
Starting audit...
[ERROR] /home/nick/Desktop/initial-pattern-def-grammar/TestClass.java:1: Missing package-info.java file. [JavadocPackage]
Audit done.
Checkstyle ends with 1 errors.

```

Should `(x instanceof String hidden)`  cause a violation?
```
[ERROR] /home/nick/Desktop/initial-pattern-def-grammar/TestClass.java:5:33: 'hidden' hides a field. [HiddenField]
```

New token is introduced to Check.

**Comment by romani** [comment]
> Note that a pattern variable is considered a binding variable, and not a local variable. 

it is syntax sugar, and it is local variable with scope in IF expression and blocks.

I think it should be violation. As hiding is happening printed value will not be value of field.

**Comment by romani** [comment]
Fix is merged
