### ISSUE TITLE
Java14 enhanced instanceof check validation: MagicNumberCheck 

### ISSUE THREAD

**Issue by nmancus1** [checkstyle/checkstyle#8367]
Child of #8391 
Check documentation: https://checkstyle.sourceforge.io/config_coding.html#MagicNumber
Identified at https://github.com/checkstyle/checkstyle/pull/8294#issuecomment-650896023

We need to validate that MagicNumberCheck works as intended once #8294 is merged.

From [JLS](https://docs.oracle.com/javase/specs/jls/se14/preview/specs/patterns-instanceof-jls.html):

_Four kinds of variable are implicitly declared final: a field of an interface (9.3), a local variable declared as a resource of a try-with-resources statement (14.20.3), and an exception parameter of a multi-catch clause (14.20), and a pattern variable (14.30.1)._

and

_Each pattern variable (14.30.1) is assigned a value after the pattern matching process has succeeded (14.30.3)._

Since a pattern variable is only assigned when the pattern matches, and a pattern variable is final, I do not think that this check applies.  Here is output to verify that it still works as expected with grammar change:
```
➜  initial-pattern-def-grammar /usr/lib/jvm/java-14-openjdk/bin/javac --enable-preview --source 14 TestClass.java
Note: TestClass.java uses preview language features.
Note: Recompile with -Xlint:preview for details.
➜  initial-pattern-def-grammar cat TestClass.java 
public class TestClass {
    Integer magicNumber = 42;
    {
       if (magicNumber instanceof Integer x) {
           System.out.println(x);
       }
    }
}

➜  initial-pattern-def-grammar cat config.xml 
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
          "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
  <module name="JavadocPackage"/>
  <module name="TreeWalker">
	<module name="MagicNumber"/>
  </module>
</module>
➜  initial-pattern-def-grammar java $RUN_LOCALE -jar ~/IdeaProjects/checkstyle/target/checkstyle-8.35-SNAPSHOT-all.jar -c config.xml TestClass.java
Starting audit...
[ERROR] /home/nick/Desktop/initial-pattern-def-grammar/TestClass.java:1: Missing package-info.java file. [JavadocPackage]
[ERROR] /home/nick/Desktop/initial-pattern-def-grammar/TestClass.java:2:27: '42' is a magic number. [MagicNumber]
Audit done.
Checkstyle ends with 2 errors.
```
What do you think, @pbludov @esilkensen ?

**Comment by pbludov** [comment]
I don't understand the relationship between `MagicNumberCheck` and the operator `instanceof`.
The variable inside the new `instanceof` operator does not have an initializer. So it can not be an ancestor of a numeric literal in the AST. Thus, there will be no new violations.

**Comment by nmancus1** [comment]
@pbludov We can close this, right?

**Comment by pbludov** [comment]
> @pbludov We can close this, right?

Yes, I think this issue can be closed.
