### ISSUE TITLE
Java14 enhanced instanceof check validation: ModifiedControlVariableCheck

### ISSUE THREAD

**Issue by nmancus1** [checkstyle/checkstyle#8368]
Child of #8391 
Check documentation: https://checkstyle.sourceforge.io/config_coding.html#ModifiedControlVariable
Identified at https://github.com/checkstyle/checkstyle/pull/8294#issuecomment-650896023

We need to validate that ModifiedControlVariableCheck works as intended once #8294 is merged.

**Comment by nmancus1** [comment]
From the check documentation:
_Checks that for loop control variables are not modified inside the for block._

From [JLS](https://docs.oracle.com/en/java/javase/14/docs/specs/patterns-instanceof-jls.html#jls-6.3.1):
_Pattern variables are implicitly final by design._

Not only are pattern variables not control variables, but they are also final, so they cannot be modified.  This check does not apply. @esilkensen @pbludov can we close this?

**Comment by esilkensen** [comment]
Sounds good to me
