### ISSUE TITLE
Java14 enhanced instanceof check validation: RequireThisCheck

### ISSUE THREAD

**Issue by nmancus1** [checkstyle/checkstyle#8370]
Child of #8391 
Check documentation: https://checkstyle.sourceforge.io/config_coding.html#RequireThis
Identified at https://github.com/checkstyle/checkstyle/pull/8294#issuecomment-650896023

We need to validate that RequireThisCheck works as intended once #8294 is merged.

**Comment by nmancus1** [comment]
From the check doucmentation:
_Checks that references to instance variables and methods of the present object are explicitly of the form "this.varName" or "this.methodName(args)" and that those references don't rely on the default behavior when "this." is absent._

Pattern variables are not instance variables nor methods, so this check does not apply.  @pbludov @esilkensen can we close this?

**Comment by esilkensen** [comment]
Sounds good to me
