### ISSUE TITLE
Java14 enhanced instanceof check validation: UnnecessarySemicolonAfterTypeMemberDeclarationCheck 

### ISSUE THREAD

**Issue by nmancus1** [checkstyle/checkstyle#8371]
Child of #8391 
Check documentation: https://checkstyle.sourceforge.io/config_coding.html#UnnecessarySemicolonAfterTypeMemberDeclaration
Identified at https://github.com/checkstyle/checkstyle/pull/8294#issuecomment-650896023

We need to validate that UnnecessarySemicolonAfterTypeMemberDeclarationCheck works as intended once #8294 is merged.

**Comment by nmancus1** [comment]
From the check documentation:
_Checks if unnecessary semicolon is used after type member declaration._

Since a pattern variable is not a member variable, this check does not apply.  Do we agree @esilkensen @pbludov ?

Since a pattern variable is not  a member variable

**Comment by esilkensen** [comment]
Sounds good to me
