### ISSUE TITLE
Java14 enhanced instanceof check validation: HideUtilityClassConstructorCheck

### ISSUE THREAD

**Issue by nmancus1** [checkstyle/checkstyle#8373]
Child of #8391 
Check documentation: https://checkstyle.sourceforge.io/config_design.html#HideUtilityClassConstructor
Identified at https://github.com/checkstyle/checkstyle/pull/8294#issuecomment-650896023

We need to validate that HideUtilityClassConstructorCheck works as intended once #8294 is merged.

**Comment by nmancus1** [comment]
From check documentation:
_Makes sure that utility classes (classes that contain only static methods or fields in their API) do not have a public constructor._

Since pattern variables have nothing to do with access modifiers of class constructors, this check does not apply to them.  @esilkensen @pbludov can we close this one?

**Comment by esilkensen** [comment]
Sounds good to me
