### ISSUE TITLE
Java14 enhanced instanceof check validation: InnerTypeLastCheck

### ISSUE THREAD

**Issue by nmancus1** [checkstyle/checkstyle#8374]
Child of #8391 
Check documentation: https://checkstyle.sourceforge.io/config_design.html#InnerTypeLast
Identified at https://github.com/checkstyle/checkstyle/pull/8294#issuecomment-650896023

We need to validate that InnerTypeLastCheck works as intended once #8294 is merged.

**Comment by pbludov** [comment]
This check validates the order of members for a class. This check should be not affected by  #8294.
