### ISSUE TITLE
Java14 enhanced instanceof check validation: InterfaceIsTypeCheck

### ISSUE THREAD

**Issue by nmancus1** [checkstyle/checkstyle#8375]
Child of #8391 
Check documentation: https://checkstyle.sourceforge.io/config_design.html#InterfaceIsType
Identified at https://github.com/checkstyle/checkstyle/pull/8294#issuecomment-650896023

We need to validate that InterfaceIsTypeCheck works as intended once #8294 is merged.

**Comment by nmancus1** [comment]
From the check documentation:
_According to Bloch, an interface should describe a type. It is therefore inappropriate to define an interface that does not contain any methods but only constants._

Since a pattern variable is defined within a relational expression,  it is not a named constant within an interface, i.e.:
```
public interface Test1 {
    int a = 3;
}
```
Can we close this @pbludov @esilkensen ?

**Comment by esilkensen** [comment]
Sounds good to me
