### ISSUE TITLE
Java14 enhanced instanceof check validation: MutableExceptionCheck

### ISSUE THREAD

**Issue by nmancus1** [checkstyle/checkstyle#8376]
Child of #8391 
Check documentation: https://checkstyle.sourceforge.io/config_design.html#MutableException
Identified at https://github.com/checkstyle/checkstyle/pull/8294#issuecomment-650896023

We need to validate that MutableExceptionCheck works as intended once #8294 is merged.

**Comment by nmancus1** [comment]
From the check documentation:
_Ensures that exception classes (classes with names conforming to some regular expression and explicitly extending classes with names conforming to other regular expression) are immutable, that is, that they have only final fields._

Since the implementation of this check simply checks that members of an exception are final, and pattern variables are already final and are not class members, this check does not apply. Can we close this one @pbludov @esilkensen ?

**Comment by esilkensen** [comment]
Sounds good to me
