### ISSUE TITLE
Java14 enhanced instanceof check validation: VisibilityModifierCheck

### ISSUE THREAD

**Issue by nmancus1** [checkstyle/checkstyle#8377]
Child of #8391 
Check documentation: https://checkstyle.sourceforge.io/config_design.html#VisibilityModifier
Identified at https://github.com/checkstyle/checkstyle/pull/8294#issuecomment-650896023

We need to validate that VisibilityModifierCheck works as intended once #8294 is merged.

**Comment by nmancus1** [comment]
From the check documentation:
_Checks visibility of class members. Only static final, immutable or annotated by specified annotation members may be public; other class members must be private unless the property protectedAllowed or packageAllowed is set._

From [JEP](https://openjdk.java.net/jeps/305):
_RelationalExpression:_
     _..._
     _RelationalExpression_ instanceof _ReferenceType_
     _RelationalExpression_ instanceof _Pattern_

_Pattern:_
     _ReferenceType Identifier_

Pattern variables have no modifiers, and are not class members, so this check does not apply.  @pbludov @esilkensen can we close this?

**Comment by esilkensen** [comment]
Sounds good to me
