### ISSUE TITLE
Java14 enhanced instanceof check validation: FinalParametersCheck

### ISSUE THREAD

**Issue by nmancus1** [checkstyle/checkstyle#8378]
Child of #8391 
Check documentation: https://checkstyle.sourceforge.io/config_misc.html#FinalParameters
Identified at https://github.com/checkstyle/checkstyle/pull/8294#issuecomment-650896023

We need to validate that FinalParametersCheck works as intended once #8294 is merged.

**Comment by rnveach** [comment]
Pattern variables are considered `final` so I would think there should be no violation on these.
https://docs.oracle.com/en/java/javase/14/docs/specs/patterns-instanceof-jls.html#jls-4.12.4

**Comment by nmancus1** [comment]
From documentation:
_Checks that parameters for methods, constructors, catch and for-each blocks are final. Interface, abstract, and native methods are not checked: the final keyword does not make sense for interface, abstract, and native method parameters as there is no code that could modify the parameter._

I agree with @rnveach, this check does not apply to pattern variables, since they are already final.  Can we close this?

**Comment by nmancus1** [comment]
@esilkensen what do you think?

**Comment by esilkensen** [comment]
Sounds good to me
