### ISSUE TITLE
Java14 enhanced instanceof check validation: AtclauseOrderCheck

### ISSUE THREAD

**Issue by nmancus1** [checkstyle/checkstyle#8380]
Child of #8391 
Check documentation: https://checkstyle.sourceforge.io/config_javadoc.html#AtclauseOrder
Identified at https://github.com/checkstyle/checkstyle/pull/8294#issuecomment-650896023

From the documentation:
_Checks the order of javadoc block-tags or javadoc tags._

This check should not apply to pattern variables.

**Comment by nmancus1** [comment]
@esilkensen @pbludov since we've introduced the new PATTERN_VARIABLE_DEF token, we can close this one, right?

**Comment by esilkensen** [comment]
Sounds good to me
