### ISSUE TITLE
Java14 enhanced instanceof check validation: JavadocVariableCheck

### ISSUE THREAD

**Issue by nmancus1** [checkstyle/checkstyle#8382]
Child of #8391 
Check documentation: https://checkstyle.sourceforge.io/config_javadoc.html#JavadocVariable
Identified at https://github.com/checkstyle/checkstyle/pull/8294#issuecomment-650896023

From documentation:
_Checks that a variable has a Javadoc comment. Ignores serialVersionUID fields._
_..._
_subset of tokens ENUM_CONSTANT_DEF_

This check should not apply to pattern variables.

**Comment by nmancus1** [comment]
@esilkensen @pbludov Since we have created a new token, PATTERN_VARIABLE_DEF, can agree that no false positives are possible, and that this can be closed?

**Comment by esilkensen** [comment]
Sounds good to me
