### ISSUE TITLE
Java14 enhanced instanceof check validation: InterfaceMemberImpliedModifierCheck

### ISSUE THREAD

**Issue by nmancus1** [checkstyle/checkstyle#8384]
Child of #8391 
Check documentation: https://checkstyle.sourceforge.io/config_modifier.html#InterfaceMemberImpliedModifier
Identified at https://github.com/checkstyle/checkstyle/pull/8294#issuecomment-650896023

From check documentation:
_This check is effectively the opposite of RedundantModifier. It checks the modifiers on interface members, ensuring that certain modifiers are explicitly specified even though they are actually redundant._

From [JEP](https://openjdk.java.net/jeps/305):
_RelationalExpression:_
     _..._
     _RelationalExpression_ instanceof _ReferenceType_
     _RelationalExpression_ instanceof _Pattern_

_Pattern:_
     _ReferenceType Identifier_

Since a pattern variable is a local variable, and has no modifiers, this check does not apply.

**Comment by nmancus1** [comment]
Can we close this @pbludov @esilkensen ?

**Comment by esilkensen** [comment]
Sounds good to me
