### ISSUE TITLE
Java14 enhanced instanceof check validation: ModifierOrderCheck

### ISSUE THREAD

**Issue by nmancus1** [checkstyle/checkstyle#8385]
Child of #8391 
Check documentation: https://checkstyle.sourceforge.io/config_modifier.html#ModifierOrder
Identifed at https://github.com/checkstyle/checkstyle/pull/8294#issuecomment-650896023

From [JEP](https://openjdk.java.net/jeps/305):
_RelationalExpression:_
     _..._
     _RelationalExpression_ instanceof _ReferenceType_
     _RelationalExpression_ instanceof _Pattern_

_Pattern:_
     _ReferenceType Identifier_

Since a pattern does not have modifiers, this check should not apply to enhanced instanceof syntax.

**Comment by nmancus1** [comment]
Are we good to close this @pbludov @esilkensen ?

**Comment by esilkensen** [comment]
Sounds good to me
