### ISSUE TITLE
Java14 enhanced instanceof check validation: RedundantModifierCheck

### ISSUE THREAD

**Issue by nmancus1** [checkstyle/checkstyle#8386]
Child of #8391 
Check documentation: https://checkstyle.sourceforge.io/config_modifier.html#RedundantModifier
Identified at https://github.com/checkstyle/checkstyle/pull/8294#issuecomment-650896023

We need to validate that RedundantModifierCheck works as intended once #8294 is merged.

**Comment by rnveach** [comment]
Pattern variables are considered `final` so I would think `final` should be seen as redundant.
https://docs.oracle.com/en/java/javase/14/docs/specs/patterns-instanceof-jls.html#jls-4.12.4

**Comment by nmancus1** [comment]
> Pattern variables are considered final so I would think final should be seen as redundant.

I agree, but there are no modifiers allowed in a pattern.

From [JEP](https://openjdk.java.net/jeps/305):
_RelationalExpression:_
     _..._
     _RelationalExpression_ instanceof _ReferenceType_
     _RelationalExpression_ instanceof _Pattern_

_Pattern:_
     _ReferenceType Identifier_

This check should not apply to #8294.
