### ISSUE TITLE
Java14 enhanced instanceof check validation: EmptyLineSeparatorCheck

### ISSUE THREAD

**Issue by nmancus1** [checkstyle/checkstyle#8388]
Child of #8391 
Check documentation: https://checkstyle.sourceforge.io/config_whitespace.html#EmptyLineSeparator
Identified at https://github.com/checkstyle/checkstyle/pull/8294#issuecomment-650896023

From check documentation: 
_Checks for empty line separators after header, package, all import declarations, fields, constructors, methods, nested classes, static initializers and instance initializers._

This check should not apply to Java14 enhanced instanceof syntax, since it is nested in a construct.

**Comment by nmancus1** [comment]
@romani @pbludov @esilkensen we can close his one right?

**Comment by esilkensen** [comment]
Sounds good to me
