### ISSUE TITLE
Java14 enhanced instanceof check validation: SuppressWarningsCheck

### ISSUE THREAD

**Issue by nmancus1** [checkstyle/checkstyle#8402]
Child of #8391 
Check documentation: https://checkstyle.sourceforge.io/config_annotation.html#SuppressWarnings

From the documentation:
_Allows to specify what warnings that@SuppressWarnings is not allowed to suppress. You can also specify a list of TokenTypes that the configured warning(s) cannot be suppressed on._

Currently, the subset of tokens is:

`CLASS_DEF` , `INTERFACE_DEF` , `ENUM_DEF` , `ANNOTATION_DEF` , `ANNOTATION_FIELD_DEF` , `ENUM_CONSTANT_DEF` , `PARAMETER_DEF` , `VARIABLE_DEF` , `METHOD_DEF` , `CTOR_DEF` .

Should we add the PATTERN_VARIABLE_DEF token to this check?

**Comment by romani** [comment]
no as there is not way to use annotation in `instanceof`
