### ISSUE TITLE
new Check: PatternVariableName

### ISSUE THREAD

**Issue by nmancus1** [checkstyle/checkstyle#8407]
Child of #8391 
Similar Check: https://checkstyle.sourceforge.io/config_naming.html#LocalVariableName

This check applies to the variable defined in the pattern definition.
From [JLS](https://docs.oracle.com/en/java/javase/14/docs/specs/patterns-instanceof-jls.html#jls-6.3.1):
_Pattern variables are implicitly final by design._

This check should not apply to pattern variable definitions, but since it is still a variable definition, we should make UT to make sure that it stays that way.

**Comment by romani** [comment]
please rename this issue to create new Check `PatternVariableName`.
We can not reuse LocalVariableName as it is alredy overused with `allowOneCharVarInForLoop` properties. And users might require more specific rules on this type of variables.

**Comment by romani** [comment]
Fix is merged
