### ISSUE TITLE
Java14 enhanced instanceof check validation: LocalFinalVariableNameCheck

### ISSUE THREAD

**Issue by nmancus1** [checkstyle/checkstyle#8409]
Child of #8391 
Check documentation: https://checkstyle.sourceforge.io/config_naming.html#LocalFinalVariableName

From documentation:
_Checks that local final variable names conform to a specified pattern. A catch parameter and resources in try statements are considered to be a local, final variables._ 

From [JLS](https://docs.oracle.com/en/java/javase/14/docs/specs/patterns-instanceof-jls.html#jls-6.3.1):
_Pattern variables are implicitly final by design._

Also from [JLS](https://docs.oracle.com/en/java/javase/14/docs/specs/patterns-instanceof-jls.html#jls-6.3.1):
_A declaration introduces an entity into a program and includes an identifier (3.8) that can be used in a name to refer to this entity. The identifier is constrained to be a type identifier when the entity being introduced is a class, interface, or type parameter._

_A declared entity is one of the following:_

_..._
_A local variable, one of the following:_

_- A local variable declared in a block (14.4)_

_- A local variable declared in a for statement (14.14)_

_A pattern variable, declared in a pattern (14.30)._

**So, are we considering a pattern variable local, or should it have it's own name check?**

**Comment by romani** [comment]
pattern variable is very good match for this Check, but there is nuance that all existing vardiablles works for whole scope/block. BUT  instanceof variable has more complicated rules of allowed presence in blocks.
I would vote to make special Check for it.

**Comment by nmancus1** [comment]
I agree, should I open a new issue?

**Comment by nmancus1** [comment]
Since we have defined a specific check to be created to remedy this in #8407, I am closing this.
