### ISSUE TITLE
Java14 enhanced instanceof check validation: StaticVariableNameCheck

### ISSUE THREAD

**Issue by nmancus1** [checkstyle/checkstyle#8410]
Child of #8391 
Check documentation: https://checkstyle.sourceforge.io/config_naming.html#StaticVariableName

From check documentation:
_Checks that static, non-final variable names conform to a specified pattern._

From [JLS](https://docs.oracle.com/en/java/javase/14/docs/specs/patterns-instanceof-jls.html#jls-6.3.1):
_Pattern variables are implicitly final by design._

Since pattern variables are final, and are not static, this check does not apply; but we should make a UT since check does look at variable defs, to ensure no false positives, etc.

**Comment by romani** [comment]
please show how this Check is affected when pattern variable has its own token ?

**Comment by nmancus1** [comment]
>

please show how this Check is affected when pattern variable has its own token ?


 
You are correct, this is impossible.
