### ISSUE TITLE
Java14 enhanced instanceof check validation: MemberNameCheck

### ISSUE THREAD

**Issue by nmancus1** [checkstyle/checkstyle#8411]
Child of #8391 
Check documentation: https://checkstyle.sourceforge.io/config_naming.html#MemberName

From documentation:
_Checks that instance variable names conform to a specified pattern._

Since pattern variables are not instance variables, this check does not apply, but we should create UT to ensure that we have no false positives.

**Comment by romani** [comment]
This Check is not affected at all as it triggering only on fields declarations.
