### ISSUE TITLE
Introduce Java14 enhanced instanceof syntax check: BestPracticeInstanceOfWithPatternVar

### ISSUE THREAD

**Issue by nmancus1** [checkstyle/checkstyle#8414]
From discussion related to #8401, we should create a new check called BestPracticeInstanceOfWithPatternVarCheck. It could check that compiler is passing... etc. Let's discuss here.

**Comment by romani** [comment]
thanks a lot for taking action item from discussion ..... I am not ready now to discuss this.
All we need for now is to create XxxxxxName  Check for this, all other can be done after summer if good ideas comeup
