### ISSUE TITLE
Check for "keep indents on empty lines" equivalent 

### ISSUE THREAD

**Issue by sridarshans** [checkstyle/checkstyle#8439]
Is it possible to validate ["keep indents on empty lines" ](https://stackoverflow.com/questions/33711926/intellij-keep-indents-on-empty-lines-not-working) code style in intellij is enforced using codestyle

Check documentation: https://checkstyle.org/config_misc.html#Indentation
```
/var/tmp $ javac Test.java

/var/tmp $ cat Test.java

 public class Test {
     private static final int SOMETHING = 1;
     //blank line with indentation
 //blank line without indentation, line 4
     private static final int SOMETHING = 1;
 }

/var/tmp $ cat config.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>
    
    <property name="fileExtensions" value="java"/>
  
    <module name="FileTabCharacter">
        <property name="eachLine" value="true"/>
    </module>
    
    <module name="TreeWalker">
        
        <property name="tabWidth" value="4"/>

        <module name="Indentation">
            <property name="basicOffset" value="4"/>
            <property name="braceAdjustment" value="0"/>
            <property name="caseIndent" value="4"/>
            <property name="throwsIndent" value="4"/>
            <property name="lineWrappingIndentation" value="8"/>
        </module>
    
    </module>
</module>

/var/tmp $ java -jar checkstyle-8.33-all.jar -c config.xml Test.java
Starting audit...
Audit done.
```

Expected: violation on fourth line.
has incorrect indentation level 0, expected level should be 4. [Indentation] Audit done.
PS. the comments in the java file are not present in the code but just added here in the description to show the difference in the indentation,

**Comment by pbludov** [comment]
@sridarshans it is not clear what problem you are trying to solve. Please use the report template as described here:
https://checkstyle.org/report_issue.html

**Comment by sridarshans** [comment]
Check documentation: https://checkstyle.org/config_misc.html#Indentation

/var/tmp $ javac Test.java

/var/tmp $ cat Test.java
public class Test {
    private static final int SOMETHING = 1;
    //blank line with indentation
//blank line without indentation
    private static final int SOMETHING = 1;
}

/var/tmp $ cat config.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>
    
    <property name="fileExtensions" value="java"/>
  
    <module name="FileTabCharacter">
        <property name="eachLine" value="true"/>
    </module>
    
    <module name="TreeWalker">
        
        <property name="tabWidth" value="4"/>

        <module name="Indentation">
            <property name="basicOffset" value="4"/>
            <property name="braceAdjustment" value="0"/>
            <property name="caseIndent" value="4"/>
            <property name="throwsIndent" value="4"/>
            <property name="lineWrappingIndentation" value="8"/>
        </module>
    
    </module>
</module>

/var/tmp $ java -jar checkstyle-8.33-all.jar -c config.xml Test.java
Starting audit...
Audit done.

Expected: violation on fourth line.
has incorrect indentation level 0, expected level should be 4. [Indentation] Audit done.
PS. the comments in the java file are not present in the code but just added here in the description to show the difference in the indentation,

**Comment by pbludov** [comment]
@sridarshans thank you. Now everything is clear. This is a good proposal. The problem with this issue is that the Checkstyle must be aware of the XML document structure. And here you need a special tool for XML validation.

And there are already some plugins available:
* https://www.mojohaus.org/xml-maven-plugin/check-format-mojo.html (run `mvn xml:check-format` to validate)
* https://code.revelc.net/formatter-maven-plugin/validate-mojo.html (set all `skip*` properties except `skipXmlFormatting` to `false` then run `formatter:validate` to validate)

**Comment by sridarshans** [comment]
@pbludov Thank you for your suggestion of plugins to do the same. However, the plan was to validate all issues as part of git commit through git hooks and check style served the purpose of validating multiple other checks at this phase of git lifecycle. This is the only rule which could not be done so.

**Comment by pbludov** [comment]
@sridarshans my apologies, I misunderstood that the violation is expected in the xml file. Please ignore my answer.

**Comment by romani** [comment]
```
$ cat Test.java 
 public class Test {
     private static final int SOMETHING = 1;
     //blank line with indentation
 //blank line without indentation, line 4. Next line is empty line

     private static final int SOMETHING = 1;
 }

$ java -jar checkstyle-8.36.2-all.jar -T Test.java 
CLASS_DEF -> CLASS_DEF [1:1]
|--MODIFIERS -> MODIFIERS [1:1]
|   `--LITERAL_PUBLIC -> public [1:1]
|--LITERAL_CLASS -> class [1:8]
|--IDENT -> Test [1:14]
`--OBJBLOCK -> OBJBLOCK [1:19]
    |--LCURLY -> { [1:19]
    |--VARIABLE_DEF -> VARIABLE_DEF [2:5]
    |   |--MODIFIERS -> MODIFIERS [2:5]
    |   |   |--LITERAL_PRIVATE -> private [2:5]
    |   |   |--LITERAL_STATIC -> static [2:13]
    |   |   `--FINAL -> final [2:20]
    |   |--TYPE -> TYPE [2:26]
    |   |   `--LITERAL_INT -> int [2:26]
    |   |--IDENT -> SOMETHING [2:30]
    |   |--ASSIGN -> = [2:40]
    |   |   `--EXPR -> EXPR [2:42]
    |   |       `--NUM_INT -> 1 [2:42]
    |   `--SEMI -> ; [2:43]
    |--VARIABLE_DEF -> VARIABLE_DEF [6:5]
    |   |--MODIFIERS -> MODIFIERS [6:5]
    |   |   |--SINGLE_LINE_COMMENT -> // [3:5]
    |   |   |   `--COMMENT_CONTENT -> blank line with indentation\n [3:7]
    |   |   |--SINGLE_LINE_COMMENT -> // [4:1]
    |   |   |   `--COMMENT_CONTENT -> blank line without indentation, line 4. Next line is empty line\n [4:3]
    |   |   |--LITERAL_PRIVATE -> private [6:5]
    |   |   |--LITERAL_STATIC -> static [6:13]
    |   |   `--FINAL -> final [6:20]
    |   |--TYPE -> TYPE [6:26]
    |   |   `--LITERAL_INT -> int [6:26]
    |   |--IDENT -> SOMETHING [6:30]
    |   |--ASSIGN -> = [6:40]
    |   |   `--EXPR -> EXPR [6:42]
    |   |       `--NUM_INT -> 1 [6:42]
    |   `--SEMI -> ; [6:43]
    `--RCURLY -> } [7:1]
```
