### ISSUE TITLE
default is switch block of visitToken method

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#852]
We need to decide on model how we should implement visitToken method, it position of checking for incorrect token to come or not, all check that do not have SWITCH do NOT check that, that problem is become more visible only in Checks where SWITCH is used, see example below. We have already enforced all check to override getRequiredTokens and getAccessibleTokens  method so chance that unexpected token appear is minimal.  Coverage by test of "default:" is also inconvenience.

```
  @Override
public void visitToken(DetailAST ast)
{
 switch (ast.getType()) {
   default:
      throw new IllegalStateException(ast.toString());
  } 
}
```

if we decide to keep "default:" we need to use Util method to do that in the same style (with message before exception ) in all Checks.
##

**Comment by romani** [comment]
@mkordas , @damianszczepanik, @rdiachenko   please share your opinion.

I think we should remove "default:" from switch and rely on getRequiredTokens and getAccessibleTokens methods.

**Comment by mkordas** [comment]
What about the case when someone add new entry to `getAccessibleTokens` and forget to update `visitToken`?

**Comment by rdiachenko** [comment]
I noticed different variations of ```visitToken``` method:

```
switch (type) {
  case TokenTypes.VARIABLE_DEF:
  case TokenTypes.PARAMETER_DEF:
    processVariable(ast);
    break;
  default:
    visitOtherTokens(ast, type);
}
```

```
switch (ast.getType()) {
  case TokenTypes.LITERAL_IF:
    visitLiteralIf(ast);
    break;
  default:
    throw new IllegalStateException(ast.toString());
}
```

```
switch (ast.getType()) {
  case TokenTypes.FOR_ITERATOR:
    inForHeader = false;
    break;
  case TokenTypes.EXPR:
    exprDepth--;
    break;
  default:
    break;
}
```

```
if (parentType == TokenTypes.CLASS_DEF
    || parentType == TokenTypes.ENUM_DEF
    || parentType == TokenTypes.INTERFACE_DEF
    || parentType == TokenTypes.LITERAL_NEW)
{
    checkOverloadMethodsGrouping(ast);
}
```

Let's suppose that we removed "default".

@mkordas if we add a new entry to ```getAccessibleTokens``` the following cases may occur:
1. Nothing will happen which is the most probable situation.
2. Some exceptions or wrong behavior may occur because of the wrong handling. But I'm not sure about this one.

I think that both cases can be caught by tests.

@romani
I think we can remove "default" but such ```switch``` blocks should be replaced with ```if``` blocks as for me.

**Comment by mkordas** [comment]
@romani @rdiachenko - I totally agree to remove defensive, dead and untestable code. 

I would go with either `if` or `switch` with just `default: break;` depending on readability and what is easier to type.

**Comment by romani** [comment]
> What about the case when someone adds new entry to getAccessibleTokens and forgets to update visitToken? Is it a risk?

Risk is minimal, as we follow test driven development model.

**Comment by romani** [comment]
Let do that issue after https://github.com/checkstyle/checkstyle/issues/655 , to be 100% sure we controll token set

**Comment by MEZk** [comment]
@romani 
Can we go on and fix the issue as you suggested?

>I think we should remove "default:" from switch and rely on getRequiredTokens and getAccessibleTokens methods.

**Comment by romani** [comment]
I might be wrong but `default` is required to be in switch block by some best practice

**Comment by MEZk** [comment]
@romani 
Ok, and what about different styles of default branch treatment which were mentioned by @rdiachenko https://github.com/checkstyle/checkstyle/issues/852#issuecomment-86869366 ?

In addition, sometimes we put comment for default branch, sometimes not, sometimes we perform some strange execution in default branches:

https://github.com/MEZk/checkstyle/blob/167dd96d8ca503a472bf003f187191d6b0ce586c/src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/LeftCurlyCheck.java#L225-L225
https://github.com/MEZk/checkstyle/blob/39b343a32a4f1ce18ee98a34618fda0a5404d6a0/src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/SuppressWarningsCheck.java#L204-L204
https://github.com/MEZk/checkstyle/blob/ed76401d3bd039d684d6de21c4894d3ab62a3076/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheck.java#L220
https://github.com/MEZk/checkstyle/blob/cf96dd9adcf0c3c8f8f05a9ffdcb765cafe17479/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/EqualsAvoidNullCheck.java#L149
https://github.com/MEZk/checkstyle/blob/67e6b46e9fa424fbd0a2fba611a3a59b30727692/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTokenCheck.java#L112-L112
https://github.com/MEZk/checkstyle/blob/420a4908dad850554e3a093cde5ebc92878cbba7/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/DeclarationOrderCheck.java#L221

**Comment by romani** [comment]
switch to default by enum or very strict set  is a search for problem for future extension of functionality.
It works well , till you start changing code. It is clear on a moment of writing but huge penalty for next engineer to figure-out what is going on and what is expected.
Usually that pattern is used when engineer is lazy to be exact about all values this code have to process. Author economize 2-3 min to type that values and waste hours of next engineer to figureout what is "default"/"all-other".

cases of Ruslan:
```
  default:
    visitOtherTokens(ast, type);
```

bad code, if default is countable (<7) of values.

```
  default:
    break;
```

sign of engineer laziness. In case of extension of tokens .... that will be huge question. New Token should be specially processed or join default. Most likely it will take a while in debug to find this place.

------

cases from you:

> LeftCurlyCheck.java#L225-L225

it is a problem, all tokens should be referenced.

> SuppressWarningsCheck.java#L204-L204

this might be ok

> FinalLocalVariableCheck.java#L220

I like this.

> EqualsAvoidNullCheck.java#L149

this is a problem.

> IllegalTokenCheck.java#L112-L112

it is ok ,as method is static and not related to logic of Check

> DeclarationOrderCheck.java#L221

this is bad code.

**Comment by romani** [comment]
@xpdavid , can you help us to resolve this issue ?
if you agree I will provide details on how to resolve it.

**Comment by xpdavid** [comment]
@romani I'd love to.
I have read the comment history. Personally, I agree with throwing exception (if possible) in `default` branch and list all the required enums explicitly in `switch` statement.

**Comment by romani** [comment]
@xpdavid , please proceed, 
- please make a list of Checks to update, I will review them
- please split updates in several PRs (one or two Checks per PR, no more, to ease review)

**Comment by nrmancuso** [comment]
I don't see any reason to make all visitToken methods the same; if we were to do something like this, we should depend on inheritance instead of yet another utility method.

I am closing this issue, because I feel it is not needed in 2024, and was of dubious value previously. If we think that certain checks should have some different behavior in the visitToken method, we can open individual issues for each and clearly demonstrate the need for this change.

**Comment by romani** [comment]
I think issue was about test coverage, s default branch with exception throw on non supported token is impossible to reproduce. So we need some weird pure junit test method, and messages and thrown exception might be also very inconsistent.
