### ISSUE TITLE
To Top Button on website

### ISSUE THREAD

**Issue by jo2** [checkstyle/checkstyle#8533]
As mentioned in #8244 a button which scrolls to the top of the page would be nice.

**Comment by jo2** [comment]
I've uploaded a [preview](https://jo2.github.io/checkstyle-top-button/index.html) of how this could look.

**Comment by strkkk** [comment]
@jo2 I would suggest to move to left side and make it visible after used scrolled below left menu. There is an unused white space.

**Comment by romani** [comment]
I still think it is good on right. Especially useful in mobile mode. On laptop I can always press cntl+home to go most top.

@rnveach , @pbludov , ply shared you thoughts in this.

**Comment by jo2** [comment]
I've added an alternative for a button on the left and on the right side:
* [left](https://jo2.github.io/checkstyle-top-button-left/index.html)
* [right](https://jo2.github.io/checkstyle-top-button-right/index.html)

**Comment by romani** [comment]
Awesome ! now I am confident that on right is much better.
If you open it in mobile - you will feel it as it covers beginning of text, so it is very unpleasant.
but on right there is more chance that it cover nothing and as you know start of sentence or word you can skip reading of end.

**Comment by rnveach** [comment]
We have the same type of button in my application I made at work. It is on the right so that is what I vote for.

IMO, even with the black border, the white background blends too much with the white of the page's background when it land in that spot. We made ours a different color so it stood out as a button and not part of the page.

We also made the button disappear when you were on the top of the page. It only appeared when you scroll down like 1 page down worth.

Maybe just nitpicking, but would "To Top" be better than "to Top" (capitalize t in to)?

**Comment by strkkk** [comment]
In mobile it looks better on right side, I agree.

**Comment by romani** [comment]
>Maybe just nitpicking, but would "To Top" be better than "to Top" (capitalize t in to)?

I have no strong opinion, up to jo2.

About style of button, no big preference. If there be few examples , I can tell what looks better.
But for now I am happy just to have it.

**Comment by romani** [comment]
from Travis:
![scroll-top-down](https://user-images.githubusercontent.com/812984/87862506-beb87300-c905-11ea-8057-4f224bae129f.png)

**Comment by jo2** [comment]
i chose white because it is one of the used colors in the page. We could use the grey from the section headings for the background and the red from the section headings for the text. To make it fit better with the other elements on the page I'd suggest to remove the rounded corners.

**Comment by romani** [comment]
@jo2, please send PR. We can tune style even after release. Such button is good step forward

**Comment by romani** [comment]
fix is merged.
