### ISSUE TITLE
Exclude Stream, Optional, and additional collection types from ClassFanOutComplexityCheck

### ISSUE THREAD

**Issue by mjustin** [checkstyle/checkstyle#8537]
Check documentation: https://checkstyle.sourceforge.io/config_metrics.html#ClassFanOutComplexity

Checkstyle currently automatically excludes a number of classes from the class fan-out complexity check, per the default value of the "excludedClasses" property of ClassFanOutComplexity.  This includes a number of base collection classes (List, HashMap, TreeSet, etc.) which were added per issue #31 in PR [#69](../pull/69).

Java 8's stream-based classes feel like they are similarly "core" as the standard collection classes, and more functionally-written code may end up using these as much if not more than the base collection classes already excluded.  There are some other core collection classes that also seem similarly basic and very "core".

My proposal is that the list of excluded classes gets expanded to include these classes.  Here is a proposed list, based on personal experience with real-life projects and some quick looking through the Java API:

* `java.util.Collection`
* `java.util.EnumSet`
* `java.util.LinkedHashMap`
* `java.util.LinkedHashSet`
* `java.util.Optional`
* `java.util.OptionalDouble`
* `java.util.OptionalInt`
* `java.util.OptionalLong`
* `java.util.stream.DoubleStream`
* `java.util.stream.IntStream`
* `java.util.stream.LongStream`
* `java.util.stream.Stream`

```
$ javac Test.java

$ cat config.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
    "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
    "http://checkstyle.sourceforge.net/dtds/configuration_1_3.dtd">
<module name="Checker">
  <module name="TreeWalker">
    <module name="ClassFanOutComplexity">
      <property name="max" value="5" />
    </module>
  </module>
</module>

$ cat Test.java
import java.util.*;
import java.util.stream.*;

public class Test {
    public void fanOutComplexityUsage() {
        // Collections
        Collection<String> collection = new LinkedHashSet<>(List.of("A", "B"));
        EnumSet<Character.UnicodeScript> enumSet =
                EnumSet.of(Character.UnicodeScript.COMMON, Character.UnicodeScript.LATIN);
        Map<String, List<Integer>> map = new LinkedHashMap<>();

        // Streams & optionals
        Stream<String> stream = Stream.of("A", "B");
        Optional<String> optional = stream.findAny();
        IntStream intStream = IntStream.range(0, 10);
        OptionalInt optionalInt = intStream.findAny();
        LongStream longStream = LongStream.range(0, 10);
        OptionalLong optionalLong = longStream.findAny();
        DoubleStream doubleStream = DoubleStream.iterate(1.1, d -> d * 2).limit(5);
        OptionalDouble optionalDouble = doubleStream.average();
    }
}

$ java -jar checkstyle-8.34-all.jar -c config.xml Test.java
Starting audit...
[ERROR] /var/tmp/Test.java:4:1: Class Fan-Out Complexity is 12 (max allowed is 5). [ClassFanOutComplexity]
Audit done.
Checkstyle ends with 1 errors.
```

**Comment by romani** [comment]
I am ok to extend default.
@strkkk , if you agree please approve issue.

**Comment by pbludov** [comment]
Fix is merged.
