### ISSUE TITLE
Change diff report generation pipeline logic to trigger to single comment

### ISSUE THREAD

**Issue by strkkk** [checkstyle/checkstyle#8539]
At the moment there are 2 triggers
diff report - triggers generation of diff report for one or two configs
single report - triggers generation of report only for patch branch

Desired behavior
1. Trigger is changed to only one, with text "GitHub, generate report"
2. Report logic should be changed to
if description has 

- "New module config:" - than this config is taken to generate report only for patch branch
- "Diff Regression config:" - than config is taken to generate usual diff report
- "Diff Regression config:" and "Diff Regression patch config": - than first config is taken for master branch, second is for patch branch.

Also update of [documentation](https://github.com/checkstyle/contribution/tree/master/checkstyle-tester#executing-generation) is necessary

**Comment by romani** [comment]
fix is merged.
