### ISSUE TITLE
Remove deprecated getLines() methods from Utils

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#854]
To delete:
* [com.puppycrawl.tools.checkstyle.Utils#getLines(java.lang.String)](../blob/master/src/main/java/com/puppycrawl/tools/checkstyle/Utils.java#L231)
* [com.puppycrawl.tools.checkstyle.Utils#getLines(java.lang.String, java.lang.String)](../blob/master/src/main/java/com/puppycrawl/tools/checkstyle/Utils.java#L249)

Coverage limits should be adjusted afterwards.

**Comment by romani** [comment]
fixed, will be in 6.5
