### ISSUE TITLE
Check that all xml sources are well formed

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#8543]
We already have `xml-maven-plugin` in our configuration for checking schemas in XML files.
This plugin can be used to check that XML files are [well formed](https://www.mojohaus.org/xml-maven-plugin/check-format-mojo.html)

We don't need an additional step in the CI, we just need to specify the set of files to check and the desired level of indentation.

Some files (pom.xml for example) already well formed (with minor violations), other should be ignored for now an reformatted in an extra issue.

**Comment by strkkk** [comment]
@pbludov I assume that https://github.com/checkstyle/checkstyle/pull/8545 is closing the issue, if not, please reopen

**Comment by pbludov** [comment]
Some files are missed in the config. Also, the goal `xml:check-format` should be included in the `pom.xml`

**Comment by romani** [comment]
fix is merged, all other fixes will be at
https://github.com/checkstyle/checkstyle/issues/8544
