### ISSUE TITLE
Format xml sources

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#8544]
Follow up for #8543

These xml files should be reformatted:

- [x] checkstyle configs
- [x] idea configs
- [x] other configs
- [x] xdocs checks
- [x] xdocs other
- [x] google/sun styles

**Comment by romani** [comment]
@pbludov , please be careful with multiline values at intellij-idea-inspection-scope.xml and pmd.

**Comment by pbludov** [comment]
all fixes are merged.
