### ISSUE TITLE
Relaxing the stated limitation about UTF-8 in documentation

### ISSUE THREAD

**Issue by oliviercailloux** [checkstyle/checkstyle#8551]
**Is your feature request related to a problem? Please describe.**
The web site [states](https://checkstyle.org/writingchecks.html#Limitations): “Java code should be written with ASCII characters only, no UTF-8 support.” This is ambiguous. I suppose that it means _at least_ that identifiers must be in pure ASCII, but does it also mean that _all_ file content must be in pure ASCII? Can I use UTF-8 in //comments? Can I use UTF-8 in Strings?

In supplement of being ambiguous, it is a strong restriction, if it is meant in the wide sense of all file content being restricted to pure ASCII. For example, Google Java Style [writes](https://google.github.io/styleguide/javaguide.html#s2.3-special-characters): “Tip: Never make your code less readable simply out of fear that some programs might not handle non-ASCII characters properly. If that should happen, those programs are broken and they must be fixed.”

**Describe the solution you'd like**
Please consider allowing UTF-8 in comments and Strings, and update the sentence referenced above accordingly.

If this is not considered possible / adequate, please change the sentence anyway to make the limitation unambiguous.

**Additional context**
From this [discussion](https://github.com/checkstyle/checkstyle/issues/8050) and this [question](https://github.com/checkstyle/checkstyle/issues/4748), I suspect that Checkstyle already supports UTF-8 in comments and strings. So I suspect this feature request would be easily implemented. And it would bring important value to those who (like me) agree with the quote from Google Java Style here above.

Other (vaguely) related issue: #2784.

**Comment by romani** [comment]
>Please consider allowing UTF-8 in comments and Strings, and update the sentence referenced above accordingly.

It should be supported already. Please use our CLI to show a case where it is not supported.

**Comment by romani** [comment]
Fix in documentation is merged
