### ISSUE TITLE
missing the release jar in checkstyle-8.35

### ISSUE THREAD

**Issue by chenrui333** [checkstyle/checkstyle#8557]
Missing the release jar, `checkstyle-8.35-all.jar`

**Comment by romani** [comment]
Conformed , no jar https://github.com/checkstyle/checkstyle/releases/tag/checkstyle-8.35

**Comment by romani** [comment]
manually uploaded - https://github.com/checkstyle/checkstyle/releases/download/checkstyle-8.35/checkstyle-8.35-all.jar
