### ISSUE TITLE
Use Java 7 Path.relativize() instead of complicated logic in Utils and Checker

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#857]
There are two complicated algorithms with poor coverage that are introduced for one goal only - in error messages provide relative paths based on project basedir instead of absolute ones:
* [Checker.normalize()](../blob/master/src/main/java/com/puppycrawl/tools/checkstyle/Checker.java#L344)
* [Utils.getStrippedFileName()](../blob/master/src/main/java/com/puppycrawl/tools/checkstyle/Utils.java#L251)

My proposition is to replace them with standard Java 7 tool for the same task: [Path.relativize()](http://docs.oracle.com/javase/7/docs/api/java/nio/file/Path.html#relativize(java.nio.file.Path))

**Comment by romani** [comment]
merged.
