### ISSUE TITLE
Check for imports is not validates against javadoc as good as Eclipse does

### ISSUE THREAD

**Issue by damianszczepanik** [checkstyle/checkstyle#859]
Following code

``` java
import org.apache.commons.beanutils.ConversionException
...
/* @imports ConversionException
```

works fine in Eclipse but checkstyle complains that import is not used. When you remove import it complains `Unable to get class information for @throws tag 'ConversionException'`

To avoid this violation following code must be applied for javadoc:

```
/* @throws org.apache.commons.beanutils.ConversionException
```

what is proper but might be quite irritated for Runtime exceptions that might be declared only in javadoc using full qualifier class name

Example in #849 
##

**Comment by romani** [comment]
as we finish polishing Checks that validate java code, we will switch to reimplementation of all javadoc Checks - https://github.com/checkstyle/checkstyle/wiki/Checkstyle-GSoC-2015-Project-Ideas#project-name-sun-code-convention-and-documentation-comments-style-guide

**Comment by damianszczepanik** [comment]
I wonder if we are not doing the same improvement about code coverage twice: checkstyle and sevntu. What is the plan to merge already covered code from sevntu to checkstyle or the opposite?

**Comment by romani** [comment]
I do not understand question, please rephase it.

**Comment by nrmancuso** [comment]
I am closing this issue, `@imports` is not a valid javadoc tag. Feel free to open a new issue (or discussion perhaps) using our bug report template if this is still an issue for you.
