### ISSUE TITLE
The same code is approved by jdk8 but not jdk7 or vice versa

### ISSUE THREAD

**Issue by damianszczepanik** [checkstyle/checkstyle#860]
I had several builds for which one of three build failed: sometimes jdk8 failed while tho rest jdks passed, another time the opposite results.

The problem was always with the code coverage, eg https://travis-ci.org/checkstyle/checkstyle/builds/56151842

**Comment by romani** [comment]
there is nothing we can do.
we completely depend on plugin there, we have to use minimal value to satisfy all jdk.
