### ISSUE TITLE
Validation of All Checks Related to Addition of Java 14 Text Blocks Syntax Support

### ISSUE THREAD

**Issue by nmancus1** [checkstyle/checkstyle#8601]
This issue will be the main tracker of all work related to checks impacted by merging #8327

## SUMMARY
Possibly affected checks, and those that should apply to this syntax, are listed below. Since we have created several new tokens, one of which has mutable content.  We will need to add these tokens to specific checks that apply, and adapt the checks to deal with the inclusion of the new structure. 
____________________
## AFFECTED CHECKS

```
➜  checks git:(full-records-grammar-patch) ✗ grep -l -H "TokenTypes.STRING_LITERAL" **/**/*.* | sort -u
annotation/SuppressWarningsCheck.java
AvoidEscapedUnicodeCharactersCheck.java
coding/EqualsAvoidNullCheck.java
coding/IllegalTokenTextCheck.java
coding/MultipleStringLiteralsCheck.java
coding/StringLiteralEqualityCheck.java
coding/UnnecessaryParenthesesCheck.java
SuppressWarningsHolder.java

```

**Comment by romani** [comment]
All referenced issues are  closed. Umbrella issue is closing.
