### ISSUE TITLE
Make it easier to find errors mixed among the warnings

### ISSUE THREAD

**Issue by jbennett2091** [checkstyle/checkstyle#8609]
**Is your feature request related to a problem? Please describe.**
Checkstyle output can be spammy and make it hard to find errors mixed in with dozens of warnings.   We have a legacy project with a large number of checkstyle rules enabled (in info mode) which tends to generate a lot of output.   We leave the output on as a matter of course so that the warnings are highly visible and get attention (in the long run).   However, when a new error is introduced, this error gets mixed in with all the warnings, and is difficult to identify.   It is VERY difficult to spot "[ERROR]" within pages of "[INFO]"

**Describe the solution you'd like**
Ideally, just sort the errors and infos separately such that errors appear at the end (or inline, and then duplicated again at the end).  A number of tools do this, and that is acceptable as developers know where to look for errors and they are easy to find.  

Alternate solution would be to make "[ERROR]" more visible - e.g.  "[ ******* ERROR *********** ]" just so it is easier to spot when visually scanning.  This could even be configurable (for backward compatibility) with a property like "checkstyle.errormarker="*** ERROR ***" allowing people to use their own text.

**Comment by jbennett2091** [comment]
Please approve issue.  PR is provided

**Comment by pbludov** [comment]
@jbennett2091 thank you for your contribution to the project! The proposed solution is certainly simple and elegant for your specific case. But it can be a breaking change for others. 

@romani @rnveach @strkkk, can there be any issues here? Maybe there should be an option for changing the sorting order in the config.

**Comment by jbennett2091** [comment]
After doing the fix, I would agree.  Adding a configuration setting to declare the desired sort order would be a good addition.  That will touch more classes and I might need guidance.

**Comment by jbennett2091** [comment]
It also looks like this may not be the right fix either.  Checker.processFiles(..) walks each file, generates a SortedSet<LocalizedMessage> for each file, but appears to deliver that set as it walks the file.  There is no overarching list of messages for the entire run.  This solution would move errors to the bottom of each file, but not to the bottom of all files.

Would you be OK if it left things as is, but simply collected errors as it went thru each file, and then wrote those errors a second time at the very end of the audit?  Today's audit would be unaffected, but errors would show up again at the bottom making them easy to spot.

**Comment by jbennett2091** [comment]
bump.   Any feedback?

I think the simple answer (restating the above) is to leave LocalizedMessage alone (do not alter the sort order).  Output will continue to be in the same order as it appears now.  However, Checker.processFiles(..) will collect a SECOND list of LocalizedMessage objects (i.e. the errors).  At the end of the audit, that list would be displayed.  Effectively, the errors appear (again) at the end of the list.  That accomplishes the easy-to-spot criteria that I would be looking for.

**Comment by rnveach** [comment]
We are in the middle of GSoC, so you might not get an answer right away.

You are correct, we print out violations per file as they come in. To accumulate them all together would require the memory to hold them. If too many violations came in from a full run, it could cause a long wait before the first violation is printed and an out of memory exception without having print a single violation could be the worst outcome. This is definitely not user friendly, so I would avoid it if possible.

IMO, I would not implement this slowdown in `Checker`. What you want is custom output more than anything. You should implement a custom https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/DefaultLogger.java . This is the class that manages the final output to the user and receives the list of violations from `Checker`. Obviously you would still have to hold all violations in memory until you can execute the final sort, but I would do it there. You would accumulate the information in `addError`/`addException` and do the sort and printing in `auditFinished`. You could use `TreeSet` with a custom comparator to do the holding/sorting.

One issue with implementation would be adding the custom listener. You could create this listener without it being in this repo, but Checkstyle's CLI doesn't really support custom listeners, even though almost all the pieces are there. See https://github.com/checkstyle/checkstyle/blob/d55ceaeeda0d557320f5d81b531fdf2033f47e9c/src/main/java/com/puppycrawl/tools/checkstyle/Main.java#L557-L562 . For us to add support for custom listeners, issue https://github.com/checkstyle/checkstyle/issues/4956 would have to be implemented first.

**Comment by romani** [comment]
> We leave the output on as a matter of course so that the warnings are highly visible and get attention (in the long run)

Do you use our CLI ?
if yes, so you can pipe our output to some tool to sort it as you want.
We will continue to keep violations in order as we do now, it is convenient for us and and it is convenient for a lot other users. Sorry that you have a bit different workflow and this is not convenient for you.

> Alternate solution would be to make "[ERROR]" more visible

you need custom Audit Listener to print violations as you want.
Or use post report creation convertor tool to generate your report base on standard report. 

>  We have a legacy project with a large number of checkstyle rules enabled (in info mode) 

I do not recommend to generate violations just for information.  I recommend to make error or ignore. But it is up to you.
If you plan to eventually resolve info violations .... I recommend to make them as ERROR and use our new filters https://github.com/checkstyle/patch-filters that will allow you keep legacy as is but new code will follow all Checks.
Example of usage - https://github.com/checkstyle/eclipse-cs/blob/master/pom.xml#L160
