### ISSUE TITLE
intgrate google-style-config-test as Integration Test

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#863]
https://github.com/checkstyle/google-style-config-test

all that tests could be executed as ITs (Integration Tests) of maven project.
Coverage HTML page have to be updated to new links to tests.

That will simplify testing and contribution process.

**Comment by mkordas** [comment]
Great idea! We definitely lack integration test right now. Do you mean moving all contents from this repo to Checkstyle? Or some magic with JARs?

**Comment by romani** [comment]
I open to any good idea, .... for now I think just movement of sources will be fine. 
That project was created separately only to let me easily manage changes in it, before it become stable, right now it cause inconvenience.

**Comment by romani** [comment]
expected location "src/it"

FYI: https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html

**Comment by romani** [comment]
merged.

**Comment by romani** [comment]
https://github.com/checkstyle/google-style-config-test will be removed in a week

**Comment by romani** [comment]
new location https://github.com/checkstyle/checkstyle/tree/master/src/it
