### ISSUE TITLE
Update Maven Compiler Plugin to 3.3

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#867]
##### Release Notes

Bug:
 * [MCOMPILER-223] - Move to a non-ancient maven-toolchain dependency

Improvements:
 * [MCOMPILER-237] - Upgrade to Maven 2.2.1 compatiblity
 * [MCOMPILER-238] - Upgrade to maven-plugins parent version 27
 * [MCOMPILER-239] - Upgrade maven-shared-utils to 0.7
 * [MCOMPILER-241] - Upgrade plexus-compiler-api to 2.5

**Comment by romani** [comment]
merged.
