### ISSUE TITLE
Fix PMD violations from 'logging-jakarta-commons' ruleset in Checkstyle

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#871]
Follow-up to #744.

Violations:
* PMD Failure: com.puppycrawl.tools.checkstyle.TreeWalker:117 Rule:ProperLogger Priority:3 Logger should be defined private static final and have the correct class.
* PMD Failure: com.puppycrawl.tools.checkstyle.TreeWalker:320 Rule:GuardLogStatement Priority:2 There is log block not surrounded by if.
* PMD Failure: com.puppycrawl.tools.checkstyle.Utils:38 Rule:ProperLogger Priority:3 Logger should be defined private static final and have the correct class.
* PMD Failure: com.puppycrawl.tools.checkstyle.checks.indentation.HandlerFactory:70 Rule:GuardLogStatement Priority:2 There is log block not surrounded by if.
* PMD Failure: com.puppycrawl.tools.checkstyle.checks.indentation.HandlerFactory:70 Rule:GuardDebugLogging Priority:3 debug logging that involves string concatenation should be guarded with isDebugEnabled() checks.
* PMD Failure: com.puppycrawl.tools.checkstyle.checks.indentation.HandlerFactory:170 Rule:GuardLogStatement Priority:2 There is log block not surrounded by if.
* PMD Failure: com.puppycrawl.tools.checkstyle.checks.indentation.HandlerFactory:170 Rule:GuardDebugLogging Priority:3 debug logging that involves string concatenation should be guarded with isDebugEnabled() checks.
* PMD Failure: com.puppycrawl.tools.checkstyle.checks.indentation.HandlerFactory:175 Rule:GuardLogStatement Priority:2 There is log block not surrounded by if.
* PMD Failure: com.puppycrawl.tools.checkstyle.checks.indentation.HandlerFactory:175 Rule:GuardDebugLogging Priority:3 debug logging that involves string concatenation should be guarded with isDebugEnabled() checks.
* PMD Failure: com.puppycrawl.tools.checkstyle.checks.indentation.HandlerFactory:180 Rule:GuardLogStatement Priority:2 There is log block not surrounded by if.
* PMD Failure: com.puppycrawl.tools.checkstyle.checks.indentation.HandlerFactory:180 Rule:GuardDebugLogging Priority:3 debug logging that involves string concatenation should be guarded with isDebugEnabled() checks.

**Comment by romani** [comment]
merged.
