### ISSUE TITLE
Comments in indentation is failing ci/phase-verification/unit-tests

### ISSUE THREAD

**Issue by Abhishek-kumar09** [checkstyle/checkstyle#8725]
According to new rules: 
`All check input files in the 'src/(it|test)/resources*/' folder must have trailing comments "// ok" and/or "// violation". [Regexp]`
Not doing it, creates problems in `checkstyle:ant-phase-verify` with the warning above.

**Also**
Every line under indentation test should end with `actual and expected indent (like: // indent:20 exp:20)`.

This is creating conflicts with each other.

---------------------------------------------------------------------------------
When I **put** indentation comment after `// ok`, `ant-phase-verify` is reporting errors, and when I **remove** the indentation comments from trailing comment (`// ok`), then `IndentationCheckTest` is raising issue with warning message below.
`java.lang.IllegalStateException: File "checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationLambda6.java" has no indentation comment or its format malformed. Error on line: 92`

<br/>

**code reference**

https://github.com/checkstyle/checkstyle/blob/3ee42d3deb541e191cf270aa6027a5cec137649e/src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java#L99

**Comment by romani** [comment]
we need to filter out all Indentation files by one suppression record (by folder), no need to keep suppression on by one.

**Comment by romani** [comment]
Fix is merged
