### ISSUE TITLE
Mofication of module property default values to reflect actual working data

### ISSUE THREAD

**Issue by gaurabdg** [checkstyle/checkstyle#8726]
Some check properties have default values which wont work when copy-pasted in module configurations.
For example:
`null`: https://github.com/checkstyle/checkstyle/blob/6f58247b85ff4d74eb22dbd8c51d72b69fe51839/src/main/java/com/puppycrawl/tools/checkstyle/checks/header/HeaderCheck.java#L72
`charset of parent module`: https://github.com/checkstyle/checkstyle/blob/6f58247b85ff4d74eb22dbd8c51d72b69fe51839/src/main/java/com/puppycrawl/tools/checkstyle/checks/header/HeaderCheck.java#L64

We need to fix all such instances.

**Comment by strkkk** [comment]
Fix is merged
