### ISSUE TITLE
Fix PMD violations from 'strings' ruleset in Checkstyle

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#873]
Follow-up to #744.

Add `<ruleset>rulesets/java/strings.xml</ruleset>` to PMD configuration.

Violations:
* PMD Failure: com.puppycrawl.tools.checkstyle.Checker:359 Rule:UseIndexOfChar Priority:3 String.indexOf(char) is faster than String.indexOf(String)..
* PMD Failure: com.puppycrawl.tools.checkstyle.ConfigurationLoader:515 Rule:UseIndexOfChar Priority:3 String.indexOf(char) is faster than String.indexOf(String)..
* PMD Failure: com.puppycrawl.tools.checkstyle.DefaultLogger:108 Rule:ConsecutiveAppendsShouldReuse Priority:3 StringBuffer (or StringBuilder).append is called consecutively without reusing the target variable..
* PMD Failure: com.puppycrawl.tools.checkstyle.PackageNamesLoader:116 Rule:AppendCharacterWithChar Priority:3 Avoid appending characters as strings in StringBuffer.append..
* PMD Failure: com.puppycrawl.tools.checkstyle.Utils:197 Rule:UseIndexOfChar Priority:3 String.indexOf(char) is faster than String.indexOf(String)..
* PMD Failure: com.puppycrawl.tools.checkstyle.XMLLogger:190 Rule:UseIndexOfChar Priority:3 String.indexOf(char) is faster than String.indexOf(String)..
* PMD Failure: com.puppycrawl.tools.checkstyle.api.AnnotationUtility:145 Rule:InefficientEmptyStringCheck Priority:3 String.trim().length()==0 is an inefficient way to validate an empty String..
* PMD Failure: com.puppycrawl.tools.checkstyle.api.FullIdent:39 Rule:AvoidStringBufferField Priority:3 StringBuffers can grow quite a lot, and so may become a source of memory leak (if the owning class has a long life time)..
* PMD Failure: com.puppycrawl.tools.checkstyle.checks.AbstractTypeAwareCheck:163 Rule:UseIndexOfChar Priority:3 String.indexOf(char) is faster than String.indexOf(String)..
* PMD Failure: com.puppycrawl.tools.checkstyle.checks.AbstractTypeAwareCheck:166 Rule:UseIndexOfChar Priority:3 String.indexOf(char) is faster than String.indexOf(String)..
* PMD Failure: com.puppycrawl.tools.checkstyle.checks.ClassResolver:167 Rule:UseIndexOfChar Priority:3 String.indexOf(char) is faster than String.indexOf(String)..
* PMD Failure: com.puppycrawl.tools.checkstyle.checks.SuppressWarningsHolder:180 Rule:UseIndexOfChar Priority:3 String.indexOf(char) is faster than String.indexOf(String)..
* PMD Failure: com.puppycrawl.tools.checkstyle.checks.annotation.AnnotationUseStyleCheck:133 Rule:AvoidDuplicateLiterals Priority:3 The String literal "annotation.incorrect.style" appears 4 times in this file; the first occurrence is on line 133.
* PMD Failure: com.puppycrawl.tools.checkstyle.checks.blocks.EmptyBlockCheck:178 Rule:InefficientEmptyStringCheck Priority:3 String.trim().length()==0 is an inefficient way to validate an empty String..
* PMD Failure: com.puppycrawl.tools.checkstyle.checks.coding.AbstractIllegalCheck:68 Rule:UseIndexOfChar Priority:3 String.indexOf(char) is faster than String.indexOf(String)..
* PMD Failure: com.puppycrawl.tools.checkstyle.checks.coding.AbstractIllegalCheck:71 Rule:UseIndexOfChar Priority:3 String.indexOf(char) is faster than String.indexOf(String)..
* PMD Failure: com.puppycrawl.tools.checkstyle.checks.coding.IllegalTypeCheck:315 Rule:UseIndexOfChar Priority:3 String.indexOf(char) is faster than String.indexOf(String)..
* PMD Failure: com.puppycrawl.tools.checkstyle.checks.coding.IllegalTypeCheck:332 Rule:UseIndexOfChar Priority:3 String.indexOf(char) is faster than String.indexOf(String)..
* PMD Failure: com.puppycrawl.tools.checkstyle.checks.design.VisibilityModifierCheck:743 Rule:UseIndexOfChar Priority:3 String.indexOf(char) is faster than String.indexOf(String)..
* PMD Failure: com.puppycrawl.tools.checkstyle.checks.design.VisibilityModifierCheck:758 Rule:UseIndexOfChar Priority:3 String.indexOf(char) is faster than String.indexOf(String)..
* PMD Failure: com.puppycrawl.tools.checkstyle.checks.header.AbstractHeaderCheck:92 Rule:InefficientEmptyStringCheck Priority:3 String.trim().length()==0 is an inefficient way to validate an empty String..
* PMD Failure: com.puppycrawl.tools.checkstyle.checks.header.AbstractHeaderCheck:186 Rule:InefficientEmptyStringCheck Priority:3 String.trim().length()==0 is an inefficient way to validate an empty String..
* PMD Failure: com.puppycrawl.tools.checkstyle.checks.imports.CustomImportOrderCheck:543 Rule:UseIndexOfChar Priority:3 String.indexOf(char) is faster than String.indexOf(String)..
* PMD Failure: com.puppycrawl.tools.checkstyle.checks.imports.CustomImportOrderCheck:673 Rule:UseIndexOfChar Priority:3 String.indexOf(char) is faster than String.indexOf(String)..
* PMD Failure: com.puppycrawl.tools.checkstyle.checks.imports.CustomImportOrderCheck:674 Rule:UseIndexOfChar Priority:3 String.indexOf(char) is faster than String.indexOf(String)..
* PMD Failure: com.puppycrawl.tools.checkstyle.checks.imports.CustomImportOrderCheck:706 Rule:AppendCharacterWithChar Priority:3 Avoid appending characters as strings in StringBuffer.append..
* PMD Failure: com.puppycrawl.tools.checkstyle.checks.imports.ImportControlCheck:140 Rule:InefficientEmptyStringCheck Priority:3 String.trim().length()==0 is an inefficient way to validate an empty String..
* PMD Failure: com.puppycrawl.tools.checkstyle.checks.imports.ImportControlCheck:167 Rule:InefficientEmptyStringCheck Priority:3 String.trim().length()==0 is an inefficient way to validate an empty String..
* PMD Failure: com.puppycrawl.tools.checkstyle.checks.indentation.HandlerFactory:170 Rule:AvoidDuplicateLiterals Priority:3 The String literal "couldn't instantiate constructor for " appears 4 times in this file; the first occurrence is on line 170.
* PMD Failure: com.puppycrawl.tools.checkstyle.filters.CSVFilter:71 Rule:UseIndexOfChar Priority:3 String.indexOf(char) is faster than String.indexOf(String)..

**Comment by romani** [comment]
merged.
