### ISSUE TITLE
Remove BlockCommentPosition test input files from checkstyle_input_suppressions.xml

### ISSUE THREAD

**Issue by nmancus1** [checkstyle/checkstyle#8738]
Adding this exclude here will allow us to remove all `**/blockcommentposition/**.*` suppressions from `checkstyle_input_suppressions.xml`.

_Originally posted by @nmancus1 in https://github.com/checkstyle/checkstyle/pull/8737/review_comment/create_

Since we have added all input files for `BlockCommentPosition` to the excludes for `ant-phase-verify.xml ` checkstyle input file run, we can remove these files from `checkstyle_input_suppressions.xml`.  These input files require no configuration or "ok" and "violation" comments, so this test does not apply to them.

**Comment by romani** [comment]
fix is merged.
