### ISSUE TITLE
Fix PMD violations from 'sunsecure' ruleset in Checkstyle

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#874]
Follow-up to #744.

Add `<ruleset>rulesets/java/sunsecure.xml</ruleset>` to PMD configuration.

Violations:
* PMD Failure: com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck:114 Rule:MethodReturnsInternalArray Priority:3 Returning 'fileExtensions' may expose an internal array..
* PMD Failure: com.puppycrawl.tools.checkstyle.checks.indentation.BlockParentHandler:64 Rule:MethodReturnsInternalArray Priority:3 Returning 'CHECKED_CHILDREN' may expose an internal array..
* PMD Failure: com.puppycrawl.tools.checkstyle.checks.javadoc.AbstractJavadocCheck$ParseErrorMessage:754 Rule:MethodReturnsInternalArray Priority:3 Returning 'messageArguments' may expose an internal array..
* PMD Failure: com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocNodeImpl:94 Rule:MethodReturnsInternalArray Priority:3 Returning 'children' may expose an internal array..
* PMD Failure: com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocNodeImpl:129 Rule:ArrayIsStoredDirectly Priority:3 The user-supplied array 'children' is stored directly..

**Comment by romani** [comment]
merged.
