### ISSUE TITLE
Introduction of modules metadata files generator

### ISSUE THREAD

**Issue by gaurabdg** [checkstyle/checkstyle#8742]
The whole migration will be done step by step.
1. At first it will be hosted in `test`, to avoid coverage and pitest. All other violations such as checkstyle, pmd will be resolved and UTs modified.

**Comment by strkkk** [comment]
Fix is merged

**Comment by romani** [comment]
Array default value should have no curly braces
-----

https://github.com/checkstyle/metadata-gen/pull/30/files#diff-ac1ee04184222617b0f18521881c5da0R52

`<property name="legalAbstractClassNames" type="java.lang.String[]" default-value="{}"> `

default value is something that use can copy and put in Check and it should work. Unfortunately `"{}"` is not good value, and It is our visual marker of no content `""` it is better value.
It was done as we need somehow to show empty content in HTML(xdoc), and such value were copied to javadoc during xdoc->javadoc sync. 
It is not good value for setter of Check. We need to update javadocs to have `""` and update UT that keeps xdoc and javadoc in sync to treat `""`  as `{}`  to avoid updates in xdoc for now.

Example for IllegalTypeCheck:
```
<property name="illegalClassNames" type="java.lang.String[]" 
   default-value="HashMap, HashSet, LinkedHashMap, LinkedHashSet, TreeMap,">
  <description><![CDATA[Specify classes that should not be used
as types in variable declarations, return values or parameters.]]></description>
</property>
<property name="legalAbstractClassNames" type="java.lang.String[]" default-value="{}"> 
  <description><![CDATA[Define abstract classes that may be used as types.]]></description>
</property>
<property name="ignoredMethodNames" type="java.lang.String[]" 
   default-value="getEnvironment, getInitialContext">
  <description><![CDATA[Specify methods that should not be checked.]]></description>
</property>

```

**Comment by romani** [comment]
Name of Checks should not have "Check" suffix
------

from generated metadata files:
`<check name="InterfaceMemberImpliedModifierCheck" ....`

it should be `<check name="InterfaceMemberImpliedModifier"`
same as we print in HTML website - https://checkstyle.org/config_modifier.html#InterfaceMemberImpliedModifier

is used want class name he has `fully-qualified-name="com.puppycrawl.tools.checkstyle.checks.modifier.InterfaceMemberImpliedModifierCheck"`

for some historical reason it is only applicable to Checks, not a Filters. Filters should stay the same - name of class

**Comment by romani** [comment]
Formatting of Description.
--------

At least what we can do now - is to remove examples (the most ugly part). 
All other tags (`<a htef`, `{@code ` .... ) can stay in property description and lets keep it as is, we will think about this later on, or apply smth like `getHtmlLessDesc` in future, we can release with  description like:
![image](https://user-images.githubusercontent.com/812984/90648914-f8bfb200-e1ee-11ea-9a99-90cc3361bda6.png)

and improve/beautify rendering later on.
