### ISSUE TITLE
Create New Check RecordComponentNumberCheck

### ISSUE THREAD

**Issue by nmancus1** [checkstyle/checkstyle#8748]
We need to create a new check, RecordComponentNumbercheck, to check the number of record components listed in the record component list within the header of a record declaration. 

It is also important to allow users to specify different maximum numbers of record compnents based on the scope of the record declaration, i.e., more components allowed in a private record declaration than those allowed in a public record declaration. 

From https://github.com/checkstyle/checkstyle/issues/8521:

we need new check on this, because:
- number of parameters are actually number of "fields" 
- users might not use Builder like patterns
- it might no workarounds for users
- ParameterNumber has `ignoreOverriddenMethods` that is not applicable 
- there might be different requirements for private records(no limits) and public records.

confusion might be is why 
```
record MyTestRecord2() {
    MyTestRecord2(String one, String two, String three){ // violation ParameterNumber
...

//components
record MyTestRecord34(String one, String two, String three) { //  ok ParameterNumber
...
```
but I hope it is ok, as reference in ctor of record does not create record field. And new Check will mostly be validator of amount of fields in record. 
Is all this make sense ?  

AST has new token for such parameters:
https://github.com/checkstyle/checkstyle/blob/8e82c6cf0131875fa0a4f3912ad4169aa57ff5e1/src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java#L3617-L3638

_Originally posted by @romani in https://github.com/checkstyle/checkstyle/issues/8521#issuecomment-667130908_

**Comment by nmancus1** [comment]
>I started to think why we need 4 options ? Is we can have 1 property as scope to define target visibility

>So user can create 4 instances of Check if he needs go crazy in customization

_Originally posted by @romani in https://github.com/checkstyle/checkstyle/pull/8595#issuecomment-678632796_

So, should we use the Scope property with graduated access modifier option, described [here](https://checkstyle.sourceforge.io/property_types.html#Scope), or allow users to only target a specific scope with each instance of the check?

**Comment by romani** [comment]
Scope is damaged type .... it is hard to understand how it works.

please use https://checkstyle.sourceforge.io/property_types.html#AccessModifierOption.5B.5D

**Comment by pbludov** [comment]
Fix is merged.
