### ISSUE TITLE
Fix PMD violations from 'typeresolution' ruleset in Checkstyle

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#875]
Follow-up to #744.

Add `<ruleset>rulesets/java/typeresolution.xml</ruleset>` to PMD configuration.

Violations:
* PMD Failure: com.puppycrawl.tools.checkstyle.api.FileSetCheck:74 Rule:LooseCoupling Priority:3 Avoid using implementation types like 'TreeSet'; use the interface instead.
* PMD Failure: com.puppycrawl.tools.checkstyle.api.LocalizedMessages:35 Rule:LooseCoupling Priority:3 Avoid using implementation types like 'TreeSet'; use the interface instead.
* PMD Failure: com.puppycrawl.tools.checkstyle.api.LocalizedMessages:38 Rule:LooseCoupling Priority:3 Avoid using implementation types like 'TreeSet'; use the interface instead.
* PMD Failure: com.puppycrawl.tools.checkstyle.checks.coding.AbstractSuperCheck:100 Rule:LooseCoupling Priority:3 Avoid using implementation types like 'LinkedList'; use the interface instead.
* PMD Failure: com.puppycrawl.tools.checkstyle.checks.design.OneTopLevelClassCheck:96 Rule:LooseCoupling Priority:3 Avoid using implementation types like 'TreeMap'; use the interface instead.
* PMD Failure: com.puppycrawl.tools.checkstyle.checks.imports.PkgControl:35 Rule:LooseCoupling Priority:3 Avoid using implementation types like 'LinkedList'; use the interface instead.

**Comment by romani** [comment]
mereged.
