### ISSUE TITLE
Fix PMD violations from 'braces' ruleset in Checkstyle

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#876]
Follow-up to #744.

Add `<ruleset>rulesets/java/braces.xml</ruleset>` to PMD configuration.

Violations:
* PMD Failure: com.puppycrawl.tools.checkstyle.gui.FileDrop:167 Rule:ForLoopsMustUseBraces Priority:3 Avoid using for statements without curly braces.
* PMD Failure: com.puppycrawl.tools.checkstyle.gui.FileDrop:182 Rule:IfStmtsMustUseBraces Priority:3 Avoid using if statements without curly braces.

**Comment by romani** [comment]
@mkordas , please consider following way to enforce PMD asap (if some of fixes are controversial or difficult to fix) - https://github.com/checkstyle/checkstyle/commit/65e15b32db27dc9751ac9378ab4ac4547a43c526

**Comment by mkordas** [comment]
I'll try to keep pace of one ruleset resolved per day. When I won't be able to keep that pace, I'll try to do some temporary suppressions.

**Comment by romani** [comment]
merged
