### ISSUE TITLE
All Regexp Checks that has few instances should have id property

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#8790]
detected at https://github.com/checkstyle/checkstyle/pull/8783#discussion_r483652466
to make suppression easier and more granular.

**Comment by sjathin** [comment]
Hello, I would like to work on this issue. Can you give me an idea as to how to go about solving this?

**Comment by romani** [comment]
@sjathin , 
please review 
https://github.com/checkstyle/checkstyle/blob/master/config/checkstyle_checks.xml
and add in all RegExp Checks property `id`
and update https://github.com/checkstyle/checkstyle/blob/master/config/suppressions.xml to never suppress by Check name, but do it by `id`.

**Comment by shashwatj07** [comment]
I'm on it!

**Comment by romani** [comment]
Fix is merged
