### ISSUE TITLE
Java 14 Inner Records indentation level check faulty

### ISSUE THREAD

**Issue by izrobin** [checkstyle/checkstyle#8800]
Thanks for the great work on getting Java 14 features working! @nmancus1 👏 

However, the indentation level check seems a bit broken when using inner records in classes:
`/var/tmp $ javac --enable-preview -source 14 Example.java`

```
Note: Example.java uses preview language features.
Note: Recompile with -Xlint:preview for details.
```

`/var/tmp $ cat rules.xml`

```xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC "-//Puppy Crawl//DTD Check Configuration 1.2//EN" "http://www.puppycrawl.com/dtds/configuration_1_2.dtd">
<module name="Checker">
    <module name="TreeWalker">
        <module name="Indentation">
            <property name="basicOffset" value="4"/>
            <property name="braceAdjustment" value="0"/>
            <property name="caseIndent" value="4"/>
            <property name="throwsIndent" value="4"/>
            <property name="arrayInitIndent" value="4"/>
            <property name="lineWrappingIndentation" value="4"/>
        </module>
    </module>
</module>
```

`/var/tmp $ cat Example.java`
```java
import java.util.List;

public class Example {
    public record InnerRecord(
        List<String> errors
    ) {
        public boolean isSuccess() {
            return errors.isEmpty();
        }
    }

    public static class InnerClass {
        public boolean isSuccess() {
            return true;
        }
    }
}
```

`/var/tmp $ java -Duser.language=en -Duser.country=US -jar checkstyle-8.36-all.jar -c rules.xml Example.java`

```
Starting audit...
[ERROR] /var/tmp/Example.java:7:9: 'method def modifier' has incorrect indentation level 8, expected level should be 4. [Indentation]
[ERROR] /var/tmp/Example.java:8:13: 'method def' child has incorrect indentation level 12, expected level should be 8. [Indentation]
[ERROR] /var/tmp/Example.java:9:9: 'method def rcurly' has incorrect indentation level 8, expected level should be 4. [Indentation]
Audit done.
Checkstyle ends with 3 errors.
```

---------------

**Describe what you expect in detail.**
I expect the indentation level to be 8 for methods inside inner records, just as they are in the case of inner classes methods.
Or do I have a misconfigured check?

--------------

**Comment by nmancus1** [comment]
> Thanks for the great work on getting Java 14 features working!

@izrobin You're welcome. Thanks for the detailed bug report. @pbludov  I can work on this as soon as it is approved.

**Comment by romani** [comment]
Is it same as https://github.com/checkstyle/checkstyle/issues/8806

**Comment by nmancus1** [comment]
> Is it same as #8806 ?

Yes.

**Comment by romani** [comment]
@izrobin, thanks a lot for issue report, but I am closing this issue as duplicate

**Comment by izrobin** [comment]
That's fine, judging by the issue nbr, #8806 was reported after mine, but as long as we get it fixed 😅
