### ISSUE TITLE
Load Semaphore CI with more work

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#8805]
Load Semaphore CI with more work (mostly from Travis) 

original setup was done at https://github.com/checkstyle/checkstyle/issues/8051

**Comment by pbludov** [comment]
Recent Travis [build](https://travis-ci.org/github/checkstyle/checkstyle/builds/728500237):
```
Ran for 55 min 12 sec
Total time 2 hrs 57 min 12 sec
```

The longest runs:
* NonDex [8 min 40 sec](https://travis-ci.org/github/checkstyle/checkstyle/jobs/728500249)
* assembly/site with OpenJDK11 [9 min 31 sec](https://travis-ci.org/github/checkstyle/checkstyle/jobs/728500273)
* verify with OpenJDK11 [9 min 34 sec](https://travis-ci.org/github/checkstyle/checkstyle/jobs/728500272)
* no error test on pmd  [16 min 53 sec](https://travis-ci.org/github/checkstyle/checkstyle/jobs/728500282)

**Comment by romani** [comment]
> The longest runs:

all of them are misc builds (not most critical) that could be done in non main CI.

**Comment by pbludov** [comment]
This PR [timings](https://travis-ci.org/github/checkstyle/checkstyle/builds/728782096)
```
Ran for 35 min 38 sec
Total time 2 hrs 32 min 31 sec 
```

**Comment by pbludov** [comment]
Travis time: [32:51](https://travis-ci.org/github/checkstyle/checkstyle/builds/728904979)
Semaphore time: [12:35](https://checkstyle.semaphoreci.com/workflows/176fd84e-2339-44ec-a644-c80f8b28b118)

**Comment by romani** [comment]
@pbludov, do you plan to move more items out of Travis ?

**Comment by pbludov** [comment]
> @pbludov, do you plan to move more items out of Travis ?

I plan to deal with the load on all CI. Some changes may be done in this issue, something in the new ones.

**Comment by pbludov** [comment]
circle [2:16](https://app.circleci.com/pipelines/github/pbludov/checkstyle/717/workflows/f05c4475-6fb0-495f-b77d-628410bc9e8c/jobs/4936) + [8:28](https://app.circleci.com/pipelines/github/pbludov/checkstyle/717/workflows/f05c4475-6fb0-495f-b77d-628410bc9e8c/jobs/4938) + [7:50](https://app.circleci.com/pipelines/github/pbludov/checkstyle/717/workflows/f05c4475-6fb0-495f-b77d-628410bc9e8c/jobs/4939) + [3:51](https://app.circleci.com/pipelines/github/pbludov/checkstyle/717/workflows/f05c4475-6fb0-495f-b77d-628410bc9e8c/jobs/4943) + [3:42](https://app.circleci.com/pipelines/github/pbludov/checkstyle/717/workflows/f05c4475-6fb0-495f-b77d-628410bc9e8c/jobs/4940) + [2:45](https://app.circleci.com/pipelines/github/pbludov/checkstyle/717/workflows/f05c4475-6fb0-495f-b77d-628410bc9e8c/jobs/4941) + [3:25](https://app.circleci.com/pipelines/github/pbludov/checkstyle/717/workflows/f05c4475-6fb0-495f-b77d-628410bc9e8c/jobs/4937) = 32:17
idea [14:43](https://teamcity.jetbrains.com/buildConfiguration/Checkstyle_IdeaInspectionsPullRequest/3118023?)
shippable [35:13](https://app.shippable.com/github/checkstyle/checkstyle/runs/16245/summary/console)
travis [32:51](https://travis-ci.org/github/checkstyle/checkstyle/builds/728904979)
semaphore [18:44](https://checkstyle.semaphoreci.com/workflows/73dbc3f2-1bae-4941-8d20-e45bafeafb82)
appveyor [36:59](https://ci.appveyor.com/project/Checkstyle/checkstyle/builds/35339677)
werker [40:27](https://app.wercker.com/checkstyle/checkstyle/runs/build/5f69ece77e996800080f8438)

We can not speed up appveyor, but some load from werker can be moved to semaphore.
Ideally get all CI running for about half an hour.

**Comment by romani** [comment]
We can append new CIs:
Azure Pipelines
https://cirrus-ci.org/features/

**Comment by pbludov** [comment]
> We can append new CIs:
> Azure Pipelines
> https://cirrus-ci.org/features/

Cirrus CI supports Windows, it looks like we can move some appveyor builds to this CI.

**Comment by romani** [comment]
@pbludov , in what issue do you plan to move more jobs out of Travis and Appveyor ?

is this issue done ?

**Comment by pbludov** [comment]
Yes, this issue can be closed. I'm going to merge `wercker.sh` and `validations.sh`, `shippable.sh` and `non-exceptions-test.sh` in separate issues.

**Comment by romani** [comment]
@pbludov, can we keep in validation.sh all commands for our code verification, and no-error.sh and no-exception.sh, ... . 

We should not keep all in one giant she'll file
