### ISSUE TITLE
Add missing docs for allowMultipleEmptyLines property of EmptyLineSeparator check

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#881]
Documenation is missing for [EmptyLineSeparator](http://checkstyle.sourceforge.net/config_whitespace.html#EmptyLineSeparator)  allowMultipleEmptyLines property.

In 209b22885ab63ab87c939a24c3ab5d9cf43d911d this newly added option was reverted. Then it was brought back with 2db0dab62fc4986c3bebb38a1b8cac857f37664a, but `config_whitespace.xml` was never updated again.

**Comment by romani** [comment]
merged.
