### ISSUE TITLE
Update eclipse compiler to R17

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#8839]
A new version of the Eclipse compiler was recently [released](https://www.eclipse.org/eclipse/news/4.17/jdt.php)

Now with full support for java 15 features including records and sealed classes.

Commands to get new options https://github.com/checkstyle/checkstyle/pull/8840#issuecomment-695817569

The build will fail as `R-4.11-201903070500` was removed from the repo:
http://ftp-stud.fht-esslingen.de/pub/Mirrors/eclipse/eclipse/downloads/drops4/

```
  | R-4.15-202003050155/ | 2020-03-18 14:29 | - |  
  | R-4.16-202006040540/ | 2020-08-06 09:42 | - |  
  | R-4.17-202009021800/ | 2020-09-16 16:00 | - |  
  | index.html | 2015-03-16 23:21 | 60 |  
```

**Comment by romani** [comment]
Fix is merged
