### ISSUE TITLE
Add a job to automatically rebase PRs

### ISSUE THREAD

**Issue by strkkk** [checkstyle/checkstyle#8842]
For example, something like https://github.com/marketplace/actions/automatic-rebase
In case of custom action, it can be hosted in contribution repo like existing comment action.

This will help to quickly rebase PRs without tedious work of pulling new changes, pushing to branch, etc.

**Comment by romani** [comment]
Please send PR with installation lines, let's test it

**Comment by strkkk** [comment]
Github actions will work only after merge to master. 
I tried it on my local fork and it is working, I still need to test case when PR is submitted from different repository.

**Comment by romani** [comment]
>still need to test case when PR is submitted from different repository.

It is most common case

**Comment by strkkk** [comment]
Ok, so I managed to test this.

It works fine with fork unless patch branch name is master (no idea why it is not working, but job is failing)

If such limitation is acceptable, I can submit a PR.

**Comment by romani** [comment]
@strkkk , please send PR.

**Comment by strkkk** [comment]
done. There are a few restrictions but it should work in most cases

**Comment by romani** [comment]
fix is merged

**Comment by romani** [comment]
if you run into problem like:
```
/usr/bin/docker run --name .......
Collecting information about PR #8843 of checkstyle/checkstyle...
Base branch for PR #8843 is master
+ git fetch origin master
From https://github.com/checkstyle/checkstyle
 * branch                master     -> FETCH_HEAD
+ git fetch fork ci-restore-josm
From https://github.com/romani/checkstyle
 * branch                ci-restore-josm -> FETCH_HEAD
 * [new branch]          ci-restore-josm -> fork/ci-restore-josm
+ git checkout -b ci-restore-josm fork/ci-restore-josm
Switched to a new branch 'ci-restore-josm'
Branch 'ci-restore-josm' set up to track remote branch 'ci-restore-josm' from 'fork'.
+ git rebase origin/master
Rebasing (1/1)

                                                                                
Successfully rebased and updated refs/heads/ci-restore-josm.
+ git push --force-with-lease fork ci-restore-josm
To https://github.com/romani/checkstyle.git
 ! [remote rejected]     ci-restore-josm -> ci-restore-josm (refusing to allow a 
GitHub App to create or update workflow `.github/workflows/rebase.yml` 
without `workflows` permission)
```

Solution:
All forks(with all required branches) MUST to rebase their branches over recent checkstyle's master, forked brnanches should have  https://github.com/checkstyle/checkstyle/commit/9b2724c43ae6c098d5e831a8c7e21e680eee158a `Issue #8842: Add rebase github action` merged on `Sep 22`

**Comment by strkkk** [comment]
I want to add that this error above will appear if there been **any** changes with github workflows in checkstyle master branch
