### ISSUE TITLE
Resize and move RSS icon used on main page

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#886]
Icon currently used for RSS is a little bit to wide, it doesn't look good: 
![image](https://cloud.githubusercontent.com/assets/5467276/6661481/2962f6e6-cbad-11e4-94a4-947eb208978b.png)

This looks better:
![image](https://cloud.githubusercontent.com/assets/5467276/6661522/a4af4d9a-cbad-11e4-92e6-1b26aa6b69e6.png)

Icon could also be moved just after Sourceforge for better visual look.

Source: http://pixabay.com/p-40674

Followup to #617.

**Comment by romani** [comment]
no good proposals to resolve issue, issue is closed.
