### ISSUE TITLE
AbbreviationAsWordInName check   middle row and the last row are inconsistent

### ISSUE THREAD

**Issue by ellien-lucky-monkey** [checkstyle/checkstyle#8863]
"fristXML" and "fristXMLt" use the getAbbreviation method to return "XML" and "XM" respectively

**Comment by ellien-lucky-monkey** [comment]
> respectively


The middle line checks the length of consecutive uppercase characters minus one

**Comment by strkkk** [comment]
@ellien-lucky-monkey please provide issue details in defined template. It is not clear what problem your problem is.

**Comment by ellien-lucky-monkey** [comment]
```
<module name="AbbreviationAsWordInName">
            <property name="ignoreFinal" value="false"/>
            <property name="allowedAbbreviationLength" value="1"/>
            <property name="allowedAbbreviations" value="XML"/>
 </module>

```
```
public class FristXMLtp { //violation

}


public class FristXML { //OK

}
```

**Comment by romani** [comment]
@ellien-lucky-monkey , please strictly follow https://github.com/checkstyle/checkstyle/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
to provide us all details that we need to reproduce a problem easily and let somebody fix it.

issue will be closed if not updated till end of October

**Comment by nrmancuso** [comment]
Closing in favor of https://github.com/checkstyle/checkstyle/issues/12409
