### ISSUE TITLE
Use .ci/validation.cmd in appveyor ci

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#8864]
Appveyor and Cirrus should share one script for validation. Cirrus already uses `.ci/validation.cmd`, we need to update Appveyour only.

Wiki (and xdocs?) should be updated with some readme for this script.

Based on https://github.com/checkstyle/checkstyle/pull/8841#discussion_r492023797

**Comment by romani** [comment]
Fix is merged
