### ISSUE TITLE
Make NonEmptyAtclauseDescription check @return

### ISSUE THREAD

**Issue by muntyan** [checkstyle/checkstyle#8885]
There is NonEmptyAtclauseDescription check, which checks that `@param` tags have something in them, it fails for `@param blah` if there is no text that follows that. However it doesn't seem to fail on naked `@return`. Would it be possible to change that, or add a new check for that?

```
/**
 * @param foo // error, good
 * @return // no error here, bad
 */
void foo(int foo) {
}
```

**Comment by romani** [comment]
Please follow issue template to describe it as it is bug https://checkstyle.org/report_issue.html#How_to_report_a_bug.3F

**Comment by muntyan** [comment]
Thank you, opened #8889
