### ISSUE TITLE
Add SARIF as a supported output format

### ISSUE THREAD

**Issue by adverma98** [checkstyle/checkstyle#8905]
**Is your feature request related to a problem? Please describe.**
No, it's not related to any existing problems.

**Describe the solution you'd like**

Github's new [code scanning](https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/about-code-scanning) product allows for teams to integrate third party static analysis and linting tools.  They use the [SARIF format](https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/uploading-a-sarif-file-to-github) for uploading and reporting the output of these analyses/linters.

It would be very useful if checkstyle was able to output SARIF results directly along with the already existing formats.

**Additional context**
Some resources that might be useful:
- [SARIF description](https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/sarif-support-for-code-scanning) 
- [SARIF website](https://sarifweb.azurewebsites.net/)
- [SARIF tutorials](https://github.com/microsoft/sarif-tutorials)
- [Specification](https://docs.oasis-open.org/sarif/sarif/v2.1.0/sarif-v2.1.0.html)

-----

To avoid problems in schema validation for urls to files, user should use system property https://checkstyle.org/config_system_properties.html#Base_directory_support
`java -jar target/checkstyle-8.42-SNAPSHOT-all.jar -f sarif -c src/main/resources/sun_checks.xml src/main/java/com/puppycrawl/tools/checkstyle/api/AbstractCheck.java` and setting `basedir` using `<property name="basedir" value="${basedir}"/>` in config.

**Comment by chao2zhang** [comment]
I could pick this up if no one else claimed it.

**Comment by michaelcfanning** [comment]
It would be great to see this work get done. We're glad to help if we can (we're MS engineer w/a lot of experience in SARIF). Don't forget to run the [SARIF Validator](https://sarifweb.azurewebsites.net/Validation) and to enable the `GitHub ingestion rules` in particular (which cover some corner cases in the format that provide for best integration with GitHub Advanced Security). I also wouldn't be surprised if those validations are a bit out of sync with current GHAS (which has evolved in recent months). If our team can fix up any gaps/inconsistencies you observe, glad to do that.

@eddynaka @yongyan-gh

**Comment by romani** [comment]
Issue is approved, just send a PR.

**Comment by strkkk** [comment]
Fix is merged
