### ISSUE TITLE
update Cirrus CI to not print download progress in logs

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#8918]
https://cirrus-ci.com/task/6125110027354112 
logs are hard to scroll, due to download process printed.

Solution: add `--no-progress` to chocolate
taken from https://www.reddit.com/r/chocolatey/comments/fcx3yg/best_practice_when_installing_via_packer/

at https://github.com/checkstyle/checkstyle/blob/master/.cirrus.yml#L40

**Comment by romani** [comment]
Fix is merged

**Comment by pbludov** [comment]
Sorry for the late response, but this can be turn off in the [config](https://chocolatey.org/docs/chocolatey-configuration#general-1):
`choco feature disable --name showDownloadProgress`
