### ISSUE TITLE
Disable "checkstyle-cli-run-openjdk14" job in travis.sh

### ISSUE THREAD

**Issue by nmancus1** [checkstyle/checkstyle#8921]
From #8920:

Once #8920 is merged, `checkstyle-cli-run-openjdk14` in `travis.sh` should be removed/disabled.  `checkstyle-cli-run-openjdk14` only parses around 2,000 files; it's replacement, proposed by the changes in #8920, parses around 46,000 files (this excludes `module-info.java` files and non-compilables):

```
➜  jdk14u git:(master) find . -name "*.java" | wc -l
49160
```
As we need to pare down the number of jobs for travis anyway, and the test in #8920 covers all files covered by `checkstyle-cli-run-openjdk14` plus many more, I vote that we simply remove `checkstyle-cli-run-openjdk14`.

**Comment by pbludov** [comment]
Fix is merged.
