### ISSUE TITLE
Add Mega-Linter in "Active Tools" section

### ISSUE THREAD

**Issue by nvuillam** [checkstyle/checkstyle#8922]
**Is your feature request related to a problem? Please describe.**
No problem :)

**Describe the solution you'd like**
On [Active Tools doc](https://checkstyle.sourceforge.io/#undefined)I'd like to add [Mega-Linter](https://github.com/nvuillam/mega-linter) to the list of tools embedding CheckStyle
URL: https://github.com/nvuillam/mega-linter#readme

Values are the following:
- name: Mega-Linter
- author: Nicolas Vuillamy
- available from: Mega-Linter checkstyle plugin - https://github.com/nvuillam/mega-linter/blob/master/docs/descriptors/java_checkstyle.md#readme
- remarks: 100% open-source linters aggregator, usable as Github action, in other CI tools, and locally

**Additional context**
Nope

**Comment by romani** [comment]
please send PR.

**Comment by nvuillam** [comment]
It was written "contact us" :)
Ok i'll make a pr, thanks !

Le dim. 25 oct. 2020 à 23:20, Roman Ivanov <notifications@github.com> a
écrit :

**Comment by romani** [comment]
you contacted us :) , just send PR with wording you like to be for your tool.
code is here:
https://github.com/checkstyle/checkstyle/blob/dfec36a68198f335475976c47ca7c4f2dd553603/src/xdocs/index.xml.vm#L153

**Comment by nvuillam** [comment]
@romani PR done :) #8924

**Comment by nvuillam** [comment]
New PR: #8927 

(previous one cancelled, as I also reordered the table)
