### ISSUE TITLE
Anchor links for active and inactive tools on front page are broken

### ISSUE THREAD

**Issue by strkkk** [checkstyle/checkstyle#8925]
Steps to reproduce
1. Go to https://checkstyle.org/index.html
2. Navigate to Active Tools or Inactive / Old Tools section
3. Click on anchor link

Actual link is https://checkstyle.org/index.html#undefined

But it should not be like this
![image](https://user-images.githubusercontent.com/8901354/97159690-4a0a9580-178c-11eb-887d-2051856d5b67.png)

**Comment by romani** [comment]
Fix is Merged
