### ISSUE TITLE
Add new prefix "supplemental:" to commit validation

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#8928]
from 
https://github.com/checkstyle/checkstyle/pull/8897#issuecomment-709333159

What about to allow `supplemental: .... for Issue #XXXX`.
for cases there we do fixes for issue but it is not functional fix for issue.

NOTE: we need to add it to [release note builder](https://github.com/checkstyle/contribution/tree/master/releasenotes-builder) also to skip , same as "minor:"

**Comment by J-Ankit2020** [comment]
Hey assign this to me

**Comment by romani** [comment]
But make comment "I am on it" and you are selfassigned

**Comment by AkMo3** [comment]
I am on it.

**Comment by romani** [comment]
fix is merged
