### ISSUE TITLE
IllegalType: update examples to show how to target Check to fields only

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#8930]
https://checkstyle.org/config_coding.html#IllegalType

update documentation to show example of how to limit IllegalType to validate field types only (not a variable), example:
https://github.com/checkstyle/checkstyle/issues/8915#issuecomment-715918018

we need it as example as we have design problem in Check, but workaround is good enough to not fix Check.

**Comment by aryaniiit002** [comment]
you want to add new property here that "IllegalType" is valid for fields only like others properties?

**Comment by aryaniiit002** [comment]
you want to add new property here that "IllegalType" is valid for only fields like others properties?
[property that "Checks that particular Fields are never used. "]. like memberModifiers?
if yes, further you want to update doc by mentioning that property and code examples?

**Comment by aryaniiit002** [comment]
i am on it.

**Comment by romani** [comment]
fix is merged.
