### ISSUE TITLE
Security policy/contact

### ISSUE THREAD

**Issue by JarLob** [checkstyle/checkstyle#8936]
I would like to report a potential security vulnerability in the project.
However there is no Security Policy with a contact I could write to.

**Comment by romani** [comment]
Please let us know what specific page you need for "Security Policy", can you show examples in other project?
If there is already some standard for "Security Policy" ?

We have mail-list
https://checkstyle.org/mailing-lists.html
you can find admin emails in it.
you can find my email in my commits, you can clone our repo and see it by "git log".

**Comment by JarLob** [comment]
I mean https://github.com/checkstyle/checkstyle/security/policy
@romani I have already sent the email to ivanov-jr mail ru on Oct 14. Could you please check the spam folder or provide an alternative?

**Comment by romani** [comment]
I see your email, thanks a lot for contacting/pinning us.
Let me review the issue.

**Comment by romani** [comment]
@JarLob , fix is merged, see PR above.
We sent you a bit more questions in email

**Comment by romani** [comment]
Security.md page is merged
