### ISSUE TITLE
Default values in meta files for wrapped list of values are incorrect

### ISSUE THREAD

**Issue by strkkk** [checkstyle/checkstyle#8941]
For example - ClassDataAbstractionCouplingCheck

metadata: https://github.com/checkstyle/checkstyle/blob/604a3130e97d875f230373e6e4bc6b89df8f8ce9/src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/metrics/ClassDataAbstractionCouplingCheck.xml#L67
xdoc: https://checkstyle.org/config_metrics.html#ClassDataAbstractionCoupling_Properties
![image](https://user-images.githubusercontent.com/812984/97782993-0b8d2600-1b52-11eb-86fe-9f4d1d43a8ae.png)

or ClassFanOutComplexityCheck

meta: https://github.com/checkstyle/checkstyle/blob/604a3130e97d875f230373e6e4bc6b89df8f8ce9/src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/metrics/ClassFanOutComplexityCheck.xml#L34
xdoc: https://checkstyle.org/config_metrics.html#ClassFanOutComplexity_Properties

Expected value should be full list of tokens from check descriptions

**Comment by rnveach** [comment]
Fix was merged
