### ISSUE TITLE
NeedBracesCheck: allowSingleLineStatement allow to miss braces multi-line statements

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#895]
Base on liutikas report, from #300 .

Setting allowSingleLineStatement to true makes it so checkstyle 6.5 does not complain about:

if (blah) {
  return 1;
} else 
  return 2;

It should complain that else statement does not have curly braces.

**Comment by liscju** [comment]
Tried to reproduce issue with 0718fb0464fb41192ebd8d59f9f86676589414be - but given test passed correctly.

**Comment by dhendriks** [comment]
Can also be reproduced using the following Java code, so I assume it applies more generally.

```java
        if (true)
            throw new RuntimeException();
```

**Comment by mkordas** [comment]
I'm working on it. It's definitely a bug. @romani, do we use [bug](https://github.com/checkstyle/checkstyle/issues?q=label%3Abug) label for such cases?

**Comment by romani** [comment]
I do not see a reason in "bug","task",.... label as all that we have on issue tracker are problems. Then we get out of moratorium it might be a reason to distinguish problem in existing functionality and in request for new (right now we use "new" in issue title). Non approved usually a new functionality.

**Comment by mkordas** [comment]
I see, however during release notes creation we put some issues to _bug fixes_ category, so we have this kind of distinction.

**Comment by romani** [comment]
right, as we finish release notes automation issues we could introduce them, thanks for reminding that.

**Comment by romani** [comment]
merged.
