### ISSUE TITLE
Remove Buddy CI config 

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#8951]
all details on why this CI does not work for us at https://github.com/checkstyle/checkstyle/issues/5473

unfortunately we are development mode to be ready for release at any commit (as soon as fix merged to master we can do release, almost done CI/CD), so we need to validate all by CIs in PR.

with our level of PR rate, we will quickly use quote.

so it might be good CI for master only build.
I did not find for 2 years light tasks (keep in mind limit of memory) that we can execute periodically after merge is done.

We might come back to this CI but for now lets remove it.

**Comment by pbludov** [comment]
Fix is merged
