### ISSUE TITLE
Use diff.groovy in openjdk14-with-checks-nonjavadoc-error semaphore job

### ISSUE THREAD

**Issue by nmancus1** [checkstyle/checkstyle#8960]
From #8920:

>If we are to remove JXR from tester's POM to avoid telling it not to run anyways, we need to remove uses of `launch` as I think we are still relying on it generating HTML files since diff-report-tool is what generates the final HTML when `diff` is launched. It was never confirmed on this aspect so I don't know what effect it will have on jobs running `launch` and if they will be "broken".

>I am fine with delaying it if we want to, but its just going to be an on-going issue. We need to trim back on JXR and maven-checkstyle-plugin which just hold us back.

_Originally posted by @rnveach in https://github.com/checkstyle/checkstyle/pull/8920#r516722046_

We need to migrate to using `diff.groovy` in semaphore job `openjdk14-with-checks-nonjavadoc-error`, instead of `launch.groovy`.   This will enable us to rely less on JXR and maven-checkstyle-plugin in the future. 

This issue relies on a fix for https://github.com/checkstyle/contribution/issues/523, since we must supply additional arguments to maven for `openjdk14-with-checks-nonjavadoc-error`.

**Comment by pbludov** [comment]
Fix is merged.
