### ISSUE TITLE
Nondeterministic order of error messages in Translation check

### ISSUE THREAD

**Issue by t-rasmud** [checkstyle/checkstyle#8963]
I have noticed that Checksytle produces errors in different order on different executions.  This is annoying when comparing the result of Checkstyle on different versions of a program, or when comparing two versions of Checkstyle on the same program, or just when running Checkstyle twice.

This bug is because `TranslationCheck` uses a `HashSet` to store the input `*.properties` files.  I have created a pull request that fixes the problem #8967 .

To reproduce the bug, note that before and after the bug fix, Checkstyle produces output in different orders.

---

Check documentation: https://checkstyle.org/config_misc.html#Translation

```
$ cat messages_de.properties
hell=Hallo

$ cat messages.properties
hello=Hello

$ cat config.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
    <module name="Translation">
        <property name="fileExtensions" value="properties, translations"/>
    </module>
</module>

$ git clone git@github.com:checkstyle/checkstyle.git --depth 1 checkstyle-original && (cd checkstyle-original/ && mvn -P assembly package && java -classpath target/checkstyle-8.38-SNAPSHOT-all.jar com.puppycrawl.tools.checkstyle.Main -c ../config.xml ../messages_de.properties ../messages.properties)
Starting audit...
[ERROR] messages_de.properties:1: Key 'hello' missing. [Translation]
[ERROR] messages.properties:1: Key 'hell' missing. [Translation]
Audit done.
Checkstyle ends with 2 errors.
```

I modified `TranslationCheck` to use a `TreeSet` for storing `*.properties` files as shown [here](https://github.com/checkstyle/checkstyle/pull/8967/files). After changing `HashSet` to `TreeSet`, I see a different order of output errors (shown below).

```
$ git clone git@github.com:t-rasmud/checkstyle.git -b pr-det-logging --depth 1 checkstyle-modified && (cd checkstyle-modified && mvn -P assembly package && java -classpath target/checkstyle-8.38-SNAPSHOT-all.jar com.puppycrawl.tools.checkstyle.Main -c ../config.xml ../messages_de.properties ../messages.properties)
Starting audit...
[ERROR] messages.properties:1: Key 'hell' missing. [Translation]
[ERROR] messages_de.properties:1: Key 'hello' missing. [Translation]
Audit done.
Checkstyle ends with 2 errors.
```
**Input files**: [input-files.zip](https://github.com/t-rasmud/checkstyle/files/5482557/input-files.zip)

**Comment by romani** [comment]
I am ok with proposal.

@rnveach , please review and approve issue.

**Comment by rnveach** [comment]
I am ok with proposal too, but I want to point out TranslationCheck is a multi-file check. I am sure we had this discussion before, but these type of checks will break the order as it can't be maintained between non-multi-file checks or even other multi-file checks. For example, if you add a RegExp check to violate all message files that TranslationCheck does, I am sure you will see there is again a break in the file order.

**Comment by strkkk** [comment]
Fix is merged
