### ISSUE TITLE
Is there EnumTrailingComma with logic similar to ArrayTrailingComma?

### ISSUE THREAD

**Issue by antonmarin** [checkstyle/checkstyle#8974]
Is there EnumTrailingComma with logic similar to ArrayTrailingComma?

**Comment by romani** [comment]
https://github.com/sevntu-checkstyle/sevntu.checkstyle/issues/464

There is even PR for it https://github.com/sevntu-checkstyle/sevntu.checkstyle/pull/814


You can have even more PRs for it, non of them succeeded.
