### ISSUE TITLE
Missing documentation on parent requirements of RegexpSingleline

### ISSUE THREAD

**Issue by krichter722** [checkstyle/checkstyle#898]
The fact that "TreeWalker is not allowed as a parent of RegexpSingleline" needs to be clear after reading http://checkstyle.sourceforge.net/config_regexp.html (link or explain, but don't leave the user with an error message or the requirement to read the documentation word by word from beginning to end).

A paragraph consisting of two words "Parent" and "Checker" is not sufficient (is it a recommendation, requirement, etc.?).

experienced with 6.6-SNAPSHOT

**Comment by romani** [comment]
Each Check web dicumentation has "Parent Module" section that describe that, do we need smth more or in a different form ?

**Comment by romani** [comment]
@krichter722 , as person that trap into that problem please give us hint how you would like it to be described ?

"Parent Module" --> "Configuration Parent Module"
Or  
"Checker" - "this Rule have to be placed as child of Checker module in configuration"
Or
any other ideas ?

**Comment by krichter722** [comment]
I'll read through the docs again and see how the user can figure out that possible parents are restricted and see if there's more to do - I don't like the idea to validate the setup (based on documentation) from child to parent. I'll see if I can come up with something.

**Comment by romani** [comment]
@krichter722, any fresh ideas ?

**Comment by krichter722** [comment]
Only changing the documentation referenced above to contain a hint that the parent module contains constraints and configuration options as well. It's quite straight forward if you think about class inheritance, but that's not granted.

> Each Check web dicumentation has "Parent Module" section that describe that, do we need smth more or in a different form ?

I wouldn't say that because it's just the section header "Parent module" and a link. It's hard (and impossible, of course) to tell what this is supposed to mean.

**Comment by romani** [comment]
right now each Module have section http://checkstyle.sourceforge.net/config_regexp.html#RegexpSingleline "Example of Usage", that good approach to show how module should be used.
