### ISSUE TITLE
[Question] Are checks evaluated in a single threaded manner ?

### ISSUE THREAD

**Issue by debashisdeb** [checkstyle/checkstyle#8998]
I wanted to know if the checks under a TreeWalker module are executed in a serial manner, one after the other ? or is multi threading approach used ? I saw a couple of PR's on multi threading but they are all closed. As per the documentation : 
`the TreeWalker initiates a recursive descend from the root of the AST to the leaf nodes and calls the Check methods`
Are the check methods all called in parallel ?

I wrote a custom check and it threw an exception, due to which I got another exception :
`> Unable to create Root Module: config`

Is there a way, for checkstyle to ignore such exceptions and continue with the other checks, and may be log the exception somewhere ?

**Comment by debashisdeb** [comment]
I just got to know of the Checker property `haltOnException`. Setting it to `false`, I'm no more seeing the above issue, but at the same time no other checks are getting triggered. I just wanted to test if any custom check throws any exception, how can I make sure that the other rules work as expected.

**Comment by rnveach** [comment]
Checkstyle has no multi-threading support. There are still issues open on it.

TreeWalker contains a list of checks and the tokens they get reports on. We go through the AST tree and send notifications to each check giving them the AST they requested.

> I wrote a custom check and it threw an exception,
> Unable to create Root Module: config

Probably something went wrong with initializing the custom check. This will stop all processing if we can't bring your config into memory for use.

We will need the full stack trace to know what actually went wrong. Maybe your check isn't on the classpath, you didn't give the full path to the class to the check, or maybe you mis-spelled something.

**Comment by debashisdeb** [comment]
When you said `It all happens single threaded for each check on each AST.` Do you mean to say that all the checks are evaluated in a single thread or there are separate threads for each individual checks ?

For the exception part, I actually intentionally threw an exception, from the `beginTree` method and wanted to see the behaviour. Seems like even with `haltOnException` set to `false`, checkstyle doesn't proceed further with the rest of the checks.

**Comment by rnveach** [comment]
> all the checks are evaluated in a single thread 

Yes. Like I said, there is no multi-threading support at all.

> threw an exception, from the beginTree 

`haltOnException` is more for if an exception occurs processing a file, not from initialization errors. If something fails to initialize, it is usually hard to continue. You won't be guaranteed violations would be the same as a good run, so that could cause issues with cache files and anything from the caller.

If you want to test that your check, I recommend printing a "hello world" violation on a common AST.
