### ISSUE TITLE
unable to load class info when inner class in super class

### ISSUE THREAD

**Issue by krzyk** [checkstyle/checkstyle#90]
Issue copied from sourceforge.net, with my additions, as this bug is really annoying, blocks using checkstyle when creating custom exception classes.

I know there have been lots of similar issues and I've read most (if not all) of them. But still something seems to be wrong.

We have a class A with an Exception E declared as public static inner class. Then we have a class B derived from class A with a method m throwing E. If we now use @throw tag in the javadoc of m, we get the "unable to load class information" error

An @throw tag in the javadoc of a similar method in A does not cause any Problems.

Example:

Class A:
```java
public class A
{
    /*
     * @throws E no problem here
     */
    public synchronized void m1() throws E
    {
        throw new E("just a demo");
    }

    public static class E extends Exception
    {
        public E(String message)
        {
            super(message);
        }
    }
}

```

Class B:
```java
public class B extends A
{
    /*
    * @throws E THIS CAUSES THE PROBLEM
    */
    public synchronized void m() throws E
    {
        throw new E("just a demo");
    }
}
```

This issue still exists in latest checkstyle.

**Comment by romani** [comment]
RedundantThrowsCheck was deprecated in 6.3, removed from Checkstyle at all.
