### ISSUE TITLE
nondex tool found issue in token ordering at Indentation

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#9003]
Identified at https://travis-ci.org/github/checkstyle/checkstyle/jobs/675893545#L3230 and resulted from merging https://github.com/checkstyle/checkstyle/pull/8099 it was reverted and second PR (https://github.com/checkstyle/checkstyle/pull/8140) stuck in blocking state,
initial try to fix was done at https://github.com/checkstyle/checkstyle/pull/8116

I believe the issue is from IndentationCheck and that it generates its list of tokens using a Set, which doesn't guarantee order. Nondex runs could clearly be seen randomizing the list of tokens, so I fixed it by sorting the tokens.

How to debug nondex issues (This is not by all means a detailed guide):

I found that right after the test failures, nondex reports commands that can be used to directly re-run the failure for debugging.
Example: https://travis-ci.org/github/checkstyle/checkstyle/jobs/675893545#L3237-L3238
> `mvn nondex:nondex  -DnondexFilter='.*' -DnondexMode=FULL -DnondexSeed=933178 -DnondexStart=0 -DnondexEnd=9223372036854775807 -DnondexPrintstack=false -DnondexDir="/home/travis/build/checkstyle/checkstyle/.nondex" -DnondexJarDir="/home/travis/build/checkstyle/checkstyle/.nondex" -DnondexExecid=KSFBHLJqhU3VzpVTwCrofpz33iuNv66h8ERN4hf2Zg= -DnondexLogging=CONFIG`

I used this command and added many console print outs to determine how the check was failing and compared it to the normal run without nondex. This is what lead me to the sorting issue. Since many runs always pointed back to IndentationCheck, I could make the deduction that it is because of the Set IndentationCheck uses to build its list of tokens.

**Comment by nmancus1** [comment]
@romani I have ran `mvn nondex:nondex -DnondexFilter='.*' -DnondexMode=FULL -DnondexSeed=933178 -DnondexStart=0 -DnondexEnd=9223372036854775807 -DnondexPrintstack=false -DnondexDir="/home/travis/build/checkstyle/checkstyle/.nondex" -DnondexJarDir="/home/travis/build/checkstyle/checkstyle/.nondex" -DnondexExecid=KSFBHLJqhU3VzpVTwCrofpz33iuNv66h8ERN4hf2Zg= -DnondexLogging=CONFIG` several times on local with latest master and do not see this failure, how can I reproduce the failures locally to ensure that any changes fix this issue?

**Comment by romani** [comment]
CI is source of truth so if CI pass and your local pass also, issue might gone. We will deal with it ones it come back :) in more stable way

**Comment by nmancus1** [comment]
So, change Set to ordered data structure, merge, then merge the nondex update, check CI?  Maybe run CI a few times in the nondex PR?

**Comment by romani** [comment]
Do update of nondex and modification of code in same commit. To make it clear all changes are atomic and required for each other

**Comment by nmancus1** [comment]
Ok, thanks for providing details, I'm on it.

**Comment by romani** [comment]
fix is merged.
