### ISSUE TITLE
Violations from TrailingComment should possible to suppress by xpath by content of comment

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#9009]
Identified at https://github.com/checkstyle/checkstyle/pull/8711#issuecomment-731585941

We need to add TokenTypes.COMMENT_CONTENT
to 
https://github.com/checkstyle/checkstyle/blob/41769cee1881c8c92cc59762b90b83529406208a/src/main/java/com/puppycrawl/tools/checkstyle/utils/XpathUtil.java#L98-L103

and we need to make sure that can address cases from http://roman-ivanov.blogspot.com/2013/10/trailing-comment-check-false-positives.html
most of them should be added to Examples to show user that this Check is better to use with bunch of satellite Filters.

> Here I used starts-with only because attribute contained escape character and I couldn't query it. I suppose we need to create a separate issue, if we want to handle COMMENT_CONTENT token type

we need to show users  queries based on `starts-with`

**Comment by anhminhtran235** [comment]
I am on it

**Comment by anhminhtran235** [comment]
@romani @rnveach  I need some help please. 

First, please tell me if I understand this issue correctly or not:
- Right now [SuppressionXpathFilter](https://checkstyle.sourceforge.io/config_filters.html#SuppressionXpathFilter) doesn't support TrailingComment, and my task is to make this possible
- I need to make sure that my fix should allow users to suppress violations in http://roman-ivanov.blogspot.com/2013/10/trailing-comment-check-false-positives.html, and I should also add these suppression examples in TrailingComent docs

Second, I have a few questions:
- According to [SuppressionFilter docs](https://checkstyle.sourceforge.io/config_filters.html#SuppressionFilter), the filter _"rejects audit events for Check violations according to a suppressions XML document in a file"_. I guess `SuppressionXpathFilter` does the same thing? My question is: Where does this `rejection` happens?
- Could you point me to some related files I should look at?

Thank you very much!

**Comment by anhminhtran235** [comment]
I would like to drop this issue. It is more complex than my current skills. Future contributors feel free to take on this issue.

**Comment by AkMo3** [comment]
I am on it.

**Comment by romani** [comment]
Fix is merged
