### ISSUE TITLE
Update PMD to 5.3.0

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#901]
Changelog available at http://pmd.sourceforge.net/pmd-5.3.0/overview/changelog.html

**Comment by romani** [comment]
can we wait till plugin is released (I do not like extra customizations in pom) ? 
do we need that rush for latest versions?

till we have a lot of false-positives from PMD that already fixed in latest versions, lets keep simple.

**Comment by mkordas** [comment]
OK, let's wait for the plugin then.
