### ISSUE TITLE
Refactor TrailingComment implementation to be completely AST based

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#9010]
detected at https://github.com/checkstyle/checkstyle/pull/8711

We need to avoid usage of following code
https://github.com/checkstyle/checkstyle/blob/41769cee1881c8c92cc59762b90b83529406208a/src/main/java/com/puppycrawl/tools/checkstyle/checks/TrailingCommentCheck.java#L191-L195

and use only AST based code, as all content of comments is present in tree.

**Comment by anhminhtran235** [comment]
I am on it

**Comment by AkMo3** [comment]
I am on it.

**Comment by romani** [comment]
fix is merged
