### ISSUE TITLE
consider a formatter

### ISSUE THREAD

**Issue by xenoterracide** [checkstyle/checkstyle#9088]
this is arguably out of scope of checkstyles defined goal, but has making checkstyle format java code like prettier formats stuff been something you've considered? it already has configuration for everything, and can parse java. I'm no expert but it seems like it could output it too? just a suggestion.

**Comment by rnveach** [comment]
It sounds like you are talking about https://checkstyle.org/config_misc.html#Indentation for the Java code and having the fixes automatically corrected for the user by the tool ( https://github.com/checkstyle/checkstyle/wiki/Checkstyle-GSoC-2020-Project-Ideas#project-name-auto-fix-module ) ?

**Comment by xenoterracide** [comment]
I would go a lot farther than just indentation, I'm sure their are things that can't be autofixed, but a lot of things could. But yes, the GSoC sounds like more or less what I'm looking for.
