### ISSUE TITLE
NoClassDefFound exception 

### ISSUE THREAD

**Issue by samvaity** [checkstyle/checkstyle#9098]
Get the following exception when running the checkstyle-idea plugin on a whole module
![image](https://user-images.githubusercontent.com/16845631/101964321-d995c780-3bc5-11eb-93a6-70e887bab551.png)

Checkstyle version 8.37, 3.1.1(plugin)

**Comment by rnveach** [comment]
Class not found is `com.azure.tools.checkstyle.checks.Utils`. Please note **azure**.

This is not our package and so there doesn't look like anything we can do about it. There is some compile issue in your own package.

**Comment by rnveach** [comment]
I am closing until it can be shown issue is in our repo.

**Comment by samvaity** [comment]
@rnveach Thank you for the reply.

After removing the dependency on `com.azure.tools.checkstyle.checks.Utils` I am seeing the following error which apparently stems from `com.azure.tools.checkstyle.checks.OnlyFinalFieldsForImmutableClassCheck`

![image](https://user-images.githubusercontent.com/16845631/102148838-06deb180-3e22-11eb-8ac3-13454c41816a.png)

Could you help with this?

**Comment by rnveach** [comment]
Again, we are not the owners of the package `com.azure` nor do I know where to get the source to even help look at and try to deduce the issue.

We can only help with issues in the checkstyle utility. https://checkstyle.org/report_issue.html#How_to_report_a_bug.3F
