### ISSUE TITLE
Findbugs violation: UniqueProperties doesn't override java.util.Hashtable.equals

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#910]
violation 
com.puppycrawl.tools.checkstyle.checks.UniquePropertiesCheck$UniqueProperties doesn't override java.util.Hashtable.equals(Object) 	STYLE 	EQ_DOESNT_OVERRIDE_EQUALS 	1 	Medium

that violation is temporary suppressed in config/findbugs-exclude.xml but it have to be investigated and resolved.

**Comment by romani** [comment]
@pbaranchikov , can you help us with that issue.

**Comment by mkordas** [comment]
I see three solutions:
- Keep it suppressed with comment 'Method equals() from UniqueProperties is not used and not needed'
- Produce dead and boilerplate code by adding
```java
        @Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (o == null || getClass() != o.getClass()) return false;
            if (!super.equals(o)) return false;
            UniqueProperties that = (UniqueProperties) o;
            return Objects.equals(duplicatedStrings, that.duplicatedStrings);
        }

        @Override
        public int hashCode() {
            return Objects.hash(super.hashCode(), duplicatedStrings);
        }

```
- Produce less code by delegating to super, but still dead:
```java
        @Override
        public boolean equals(Object o) {
            return super.equals(o);
        }

        @Override
        public int hashCode() {
            return super.hashCode();
        }
```

**Comment by romani** [comment]
dead code is always a problem, lets keep suppression but please put a reason/links in description of suppression.
