### ISSUE TITLE
Support for Java 15 Strings

### ISSUE THREAD

**Issue by drklen4** [checkstyle/checkstyle#9111]
Running checkstyle validation on a class that contains Strings:
                        """
                        {"records":..."}}
                        """

fails with: IllegalStateException occurred while parsing file ...  unexpected token: "

**Comment by strkkk** [comment]
@drklen4 you need to use checkstyle version [8.36](https://checkstyle.org/releasenotes.html#Release_8.36) or higher to process text blocks
