### ISSUE TITLE
CheckStyle.xml SingleLineJavadoc does not match the GoogleStyle format plugin in idea.

### ISSUE THREAD

**Issue by zhangmingshuang** [checkstyle/checkstyle#9112]
I use the idea's "Google-Style-Format" plugin-in to format my codes. but the plugin-in formats comments no more then one line as:
```
/** Create a new {@code ConcurrentReferenceHashMap} instance. */
  public ConcurrentReferenceHashMap() {
```
However, in ”Check-Style“, if it's a constant or a class, the "Check-Style" wants the comment document to be multi-line.
it said likes: "the java-doc comment should be mulit-line. [SingleLineJavadoc]"

In this case , how should I adjust the relevant configuration ? (the idea's "Google-Style-Format" plugin-in no configuration modification is provided).

Thanks a lot.

**Comment by rnveach** [comment]
Is this related to https://github.com/checkstyle/checkstyle/issues/4052 ?

**Comment by romani** [comment]
yes, it is kind of duplicate.
I updated #4052 with current behavior.
@zhangmingshuang , if you have time please contribute a fix, we will guide you on process.
