### ISSUE TITLE
update ISSUE_TEMPLATE/feature_request.md to make demand to show current  beharior by CLI

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#9114]
It happened several times already that contributors are reading 
https://github.com/checkstyle/checkstyle/blob/master/.github/ISSUE_TEMPLATE/feature_request.md

and create issues with bunch of words on what is problem and what is expected.

BUT all we need is clear example of :
1) how it works now (example by CLI) by template of https://checkstyle.org/report_issue.html#How_to_report_a_bug.3F . Like "A picture is worth a thousand words", in our project **"A CLI ouput is worth a thousand words"**.
2) words on what is desirable with imaginary example on expected by template - https://checkstyle.org/report_issue.html#How_to_request_new_feature_for_existing_functionality.3F
3) any other words on expected behavior

**Comment by rnveach** [comment]
Fixed was merged
