### ISSUE TITLE
update doc for AvoidEscapedUnicodeCharacters

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#9131]
https://checkstyle.org/config_misc.html#AvoidEscapedUnicodeCharacters

Add example for each existing config to show what code is ok and what code cause violation.
Good example is https://checkstyle.org/config_naming.html#AbstractClassName
Please add examples for all properties of Check.
Make xdoc to follow structure as we have in other Checks: config is following by code example where trailing comment "// violation" is placed on the same line our CLI will show. 

look at referenced commits of #5832, to see what and how should be changed in code.

please play with module/Check by means of https://checkstyle.org/cmdline.html to understand how it works.

------------

PLEASE READ https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-examples

**Comment by Vyom-Yadav** [comment]
I am on it, currently, I am learning PIT testing and getting familiar with more maven commands, also some Data Structures that were left with a few more things. I will solve better issues when I have a better command of the Language.

**Comment by beastcoder007** [comment]
Hey can you assign this issue to me

**Comment by Vyom-Yadav** [comment]
> Hey can you assign this issue to me

I have already submitted a PR.

**Comment by mukul2310** [comment]
I am beginner to open source can someone please help me how to proceed with this issue. I want to learn how to contribute to open source. I have joined the gitter channel of check style

**Comment by Vyom-Yadav** [comment]
> I am beginner to open source can someone please help me how to proceed with this issue. I want to learn how to contribute to open source. I have joined the gitter channel of check style

There is already a PR for this issue, many other similar issues are there, see similar PR's for how to proceed

**Comment by romani** [comment]
fix is merged.
@Vyom-Yadav , thanks a lot for help.
