### ISSUE TITLE
Create MatchXpath instance to forbig usage of 'expected' element in Test annotation of junit

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#9137]
code like:
```
public class MyObjTest {

    @Test(expected = IllegalArgumentException.class) // violation should be there
    public void getNameWithNullValue() {
        MyObj obj = new MyObj();
        myObj.setName(null);
    }
}
```

update 
https://github.com/checkstyle/checkstyle/blob/8d0b729321faee41bd5fc391d11f0825cefdaa5b/config/checkstyle_checks.xml#L397-L401

to find `expected` element in code instead of search of printstacktrace in code as it is duplicate of other valiidations.
We need to add this config to our javadoc/xdoc/html.

**Comment by nmancus1** [comment]
I'm on this.

**Comment by romani** [comment]
Fix is merged
