### ISSUE TITLE
Create MatchXPath instance to forbid usage of "@Issue" annotation

### ISSUE THREAD

**Issue by nmancus1** [checkstyle/checkstyle#9138]
I do not think this(`Issue`) annotation is good:
```
    @Issue("https://github.com/checkstyle/checkstyle/issues/8651")

```
we have git for this, and while we are strict on format for commit messages it is better to keep such information in git (hidden by default). Reader of code should focus on code first, any distractions(extra code lines) should be avoided.

_Originally posted by @romani in https://github.com/checkstyle/checkstyle/pull/9134#discussion_r549013953_

**Comment by Vyom-Yadav** [comment]
@nmancus1 I can do this, but can you tell me what's exactly to be done?

**Comment by pbludov** [comment]
This can be done with JUnit itself. `@Issue` is more then just an annotation.
We can implement custom [Issue Processor](https://junit-pioneer.org/docs/issue/#issueprocessor-api) that asserts that list of issues is empty.

**Comment by bossever** [comment]
@Vyom-Yadav are you still working on this?

**Comment by Vyom-Yadav** [comment]
> @Vyom-Yadav are you still working on this?

No not currently, you can do this issue if you want to, I am working on some other issue right now.

**Comment by bossever** [comment]
@pbludov @nmancus1 I read about junit-pioneer and its Issue Processor API, but am unsure on how to implement it. Any lead would be greatly helpful.

**Comment by pbludov** [comment]
> I read about junit-pioneer and its Issue Processor API, but am unsure on how to implement it. Any lead would be greatly helpful.

If it is not easy to use  Issue Processor here, then please do this as a simple xpath check like [this](https://github.com/checkstyle/checkstyle/blob/master/config/checkstyle_checks.xml#L411) one.

**Comment by romani** [comment]
fix is merged
