### ISSUE TITLE
InnerTypeLastCheck should ignore main method

### ISSUE THREAD

**Issue by Schalli1987** [checkstyle/checkstyle#914]
It’s usually easier to write (testing) main methods at the bottom of a class, regardless if there are nested inner classes. Is it possible to enhance the InnerTypeLastCheck so that there is a flag to ignore main methods?

**Comment by romani** [comment]
I do not agree with there as main() method is a method that user need to read fist when he opens 
a class, as it is entry point to a class (main logic). But this if religious/style question 
you can think in a different way. Do exclusion only for one type of method is not not fare, and as
soon we do that, somebody else will request to do exclusion for some fields (serialVersionUID, ....)

Please use suppression mechanisms of Checkstyle(http://checkstyle.sourceforge.net/config.html#Filters), do it by annotation or by class name, ..... .
