### ISSUE TITLE
fix TOKEN_TEXT_PATTERN in JavadocMetadataScraper

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#9140]
`Pattern TOKEN_TEXT_PATTERN = Pattern.compile("([A-Z]+_*+)+[A-Z]+");`

detected at
https://github.com/checkstyle/checkstyle/pull/9128#discussion_r548900637 

> Why do we have * on _? Do we have any token with 2 or more underscores?
Shouldn't this be ([A-Z]+_)+[A-Z]+ ?
If there is a case with no underscore, then it should be something like ([A-Z]+_)+?[A-Z]+ .

**Comment by Vyom-Yadav** [comment]
@romani I am on it.

**Comment by Vyom-Yadav** [comment]
@romani One test fails if I change the pattern,  `Number of generated metadata files dont match with number of checkstyle module` , the no of files increase, how is this related to the regex I changed?

**Comment by romani** [comment]
We need to find way to change pattern to keep the same functional

**Comment by Vyom-Yadav** [comment]
> We need to find way to change pattern to keep the same functional

shall I do some changes in the test or only in the regex?

**Comment by strkkk** [comment]
> shall I do some changes in the test or only in the regex?

You need to simplify regex without breaking existing tests. If there are some missing test cases, you are welcome to add it.

**Comment by rnveach** [comment]
Fix was merged
