### ISSUE TITLE
Record implementing interfaces, indentation faulty

### ISSUE THREAD

**Issue by izrobin** [checkstyle/checkstyle#9152]
Hi again, it's me. I've found another caveat with the addition of java records and checkstyle.
I wonder if this is a bug, or what's causing it?

`$ cat rules.xml`

```xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC "-//Puppy Crawl//DTD Check Configuration 1.2//EN"
      "http://www.puppycrawl.com/dtds/configuration_1_2.dtd">
<module name="Checker">
    <module name="TreeWalker">
        <module name="Indentation">
            <property name="basicOffset" value="4"/>
            <property name="braceAdjustment" value="0"/>
            <property name="caseIndent" value="4"/>
            <property name="throwsIndent" value="4"/>
            <property name="arrayInitIndent" value="4"/>
            <property name="lineWrappingIndentation" value="4"/>
        </module>
    </module>
</module>
```

`$ cat Example.java`

```java
class Example {
    private interface Interf {
        String sayHello();
    }

    private static record ConcreteRecord(
        String greeting
    ) implements Interf {
        @Override
        public String sayHello() {
            return greeting();
        }
    }

    private static void otherMethod() {
        String str = "Some str";
        if ((str != null && str.trim() != null)
            || str.equals("Hello")
            || str.equals("Hi")
        ) {
            System.out.println("Hello there!");
        }
    }
}
```

`$ java -Duser.language=en -Duser.country=US -jar checkstyle-8.39-all.jar -c rules.xml Example.java`

```
Starting audit...
[ERROR] Example.java:8:7: 'implements' has incorrect indentation level 6, expected level should be 8. [Indentation]
Audit done.
Checkstyle ends with 1 errors.
```

If I change the property `lineWrappingIndentation` to `0`, it works (but i guess the entire check is disabled then)
I wouldn't treat record declarations as line-wrapping code.

I have quite a few records, with more than one argument/property, and I usually space them out on separate lines.
Any idea if this is a bug, or intended?

Ping @nmancus1 maybe? 🙏

**Comment by nmancus1** [comment]
Thanks for the detailed report.

> Any idea if this is a bug, or intended?

I think that this is a bug. I would expect no violations from the code that you have posted.  
Consider:
`➜  src cat config.xml `
```
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
        "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>

    <module name="TreeWalker">
        <module name="Indentation">
            <property name="basicOffset" value="4"/>
            <property name="braceAdjustment" value="0"/>
            <property name="caseIndent" value="4"/>
            <property name="throwsIndent" value="4"/>
            <property name="arrayInitIndent" value="4"/>
            <property name="lineWrappingIndentation" value="4"/>
        </module>
    </module>
</module>
```

`➜  src cat Example.java `
```
class Example {
    private interface Interf {
        String sayHello();
    }

    private static record ConcreteRecord(
            String greeting
    ) implements Interf { // should be no violation here
        @Override
        public String sayHello() {
            return greeting();
        }
    }

    private static String method(
            String greeting
    ) { // no violation here
        return greeting + "test";
    }
}
```

```
➜  src javac --release 15 --enable-preview Example.java
Note: Example.java uses preview language features.
Note: Recompile with -Xlint:preview for details.
```

```
➜  src java -jar /home/nick/IdeaProjects/checkstyle/target/checkstyle-8.40-SNAPSHOT-all.jar -c config.xml Example.java
Starting audit...
[ERROR] /home/nick/Desktop/Tester/src/Example.java:8:7: 'implements' has incorrect indentation level 6, expected level should be 8. [Indentation]
Audit done.
Checkstyle ends with 1 errors.

```

I will begin work on this as soon as a member approves.

**Comment by nmancus1** [comment]
@pbludov I have discovered an issue with the construction of the record definition AST, which affects the functionality of IndentationCheck:
https://github.com/checkstyle/checkstyle/blob/7e76db268f109f658220dc68eaa2dadc31b2dd5f/src/main/resources/com/puppycrawl/tools/checkstyle/grammar/java.g#L562-L570

The `recordComponentsList` and `implementsClause` ASTs order is reversed in the tree construction on line 569.  Should I raise a new issue for this, or can it be fixed in the scope of this issue since it affects functionality directly?  I wouldn't consider this an actual grammar change, just a change to the form of the AST that we create.

**Comment by pbludov** [comment]
To me, this looks like a regular mistype.
By replacing `ic, rc` => `rc, ic`, will this issue be solved? If so, after creating a new issue this issue will become empty.
I don't see the benefit of creating a dedicated issue.

**Comment by nmancus1** [comment]
> To me, this looks like a regular mistype.

That's correct.  The change in the `java.g` file, and actually removing some code from IndentationCheck solves this issue.

**Comment by rnveach** [comment]
Fix was merged
