### ISSUE TITLE
Build failure on cobertura-maven-plugin 2.7

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#916]
log https://travis-ci.org/checkstyle/checkstyle/jobs/57881170

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.4:site (default-site) on project checkstyle: failed to get report for org.codehaus.mojo:cobertura-maven-plugin: Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (ant-phase-verify) on project checkstyle: An Ant BuildException has occured: The following error occurred while executing this line:
[ERROR] /home/rivanov/java/git-others/checkstyle/checkstyle/config/ant-phase-verify.xml:19: java.lang.NoClassDefFoundError: net/sourceforge/cobertura/coveragedata/TouchCollector
[ERROR] around Ant part ...<ant antfile="config/ant-phase-verify.xml"/>... @ 7:47 in /home/rivanov/java/git-others/checkstyle/checkstyle/target/antrun/build-main.xml: net.sourceforge.cobertura.coveragedata.TouchCollector
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

Investigate and report an issue if that is cobertura fault - http://mojo.codehaus.org/cobertura-maven-plugin/ , https://github.com/cobertura/cobertura

from #816 : 

Release Notes - Cobertura Maven Plugin - Version 2.7

Bug:

    [MCOBERTURA-86] - no coverage reported for integration-test
    [MCOBERTURA-161] - cobertura report appear a lot of error: JavaNCSS got an error while parsing the java file
    [MCOBERTURA-180] - Cobertura does not seem to work on OSX
    [MCOBERTURA-189] - Code coverage is not working with Java 8 sources
    [MCOBERTURA-190] - com.ibm.icu:icu:2.6.1 dependency makes maven-enforcer-plugin checkSignatureRule to fail

Improvement:

    [MCOBERTURA-183] - Update Main class finding algorithm to handle Cobertura releases after 2.0.3

Task:

    [MCOBERTURA-187] - Upgrade to Cobertura 2.1.1
    [MCOBERTURA-192] - Require Java 6

**Comment by mkordas** [comment]
This is part of #816

**Comment by romani** [comment]
thanks! lets keep that issue , I will close #816

**Comment by mkordas** [comment]
Similar issue, but not the same: http://jira.codehaus.org/browse/MCOBERTURA-26 - adding Cobertura to classpath doesn't help.

**Comment by mkordas** [comment]
Root cause of this error is feature introduced in [MCOBERTURA-86 - no coverage reported for integration-test](https://jira.codehaus.org/browse/MCOBERTURA-86)

From `cobertura-maven-plugin` [documentation](http://mojo.codehaus.org/cobertura-maven-plugin/usage.html#Using_different_reports):

>## Using different reports
Up to version 2.6 there were only one report available: cobertura, which gave you a coverage report for your unit tests. Since there was only one, you didn't have to configure it in any way.

>Starting with version 2.7 a new report was added: cobertura-integration-test, which gives you a coverage report for your integration tests.

>Note: Maven 2 is unable to run both reports in the same build, so you need to configure the plugin to use only one report when building with Maven 2.

>Both reports are enabled by default. If you want the old behaviour with only a coverage report for your unit tests, you need to configure the plugin like this when upgrading to version 2.7:

>```xml
<project>
  <reporting>
    <plugins>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>cobertura-maven-plugin</artifactId>
        <version>2.7</version>
        <reportSets>
          <reportSet>
            <reports>
              <report>cobertura</report>
            </reports>
          </reportSet>
        </reportSets>
      </plugin>
    </plugins>
  </reporting>
</project>
```

That means cobertura-maven-plugin 2.7 will by default instrument `.jar` file to prepare it for integration tests. When we are running `antrun` during `site` lifecycle, Cobertura is not on classpath, so it fails.

 We don't have any integration tests yet, so right now we can omit generation of integration test coverage report. This solves the issue. I'll proceed with PR.

**Comment by romani** [comment]
merged.
