### ISSUE TITLE
Checkstyle should support "classpath:" protocol

### ISSUE THREAD

**Issue by nmancus1** [checkstyle/checkstyle#9170]
[Originally a Spring "psuedo URL"](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/util/ResourceUtils.html), `classpath:` as a protocol is becoming more prevalent.  Adding `classpath:` protocol support will help users to specify to Checkstyle where configs and such reside IN EXPLICIT way:

```
➜  src java -jar checkstyle-8.39-all.jar -c classpath:config.xml SomeClass.java
Could not find config XML file 'classpath:config.xml'.

```
This should tell Checkstyle to load `config.xml` using `ClassLoader.getSystemResource()` only.

Spring implementation:
https://github.com/spring-projects/spring-framework/blob/master/spring-core/src/main/java/org/springframework/core/io/DefaultResourceLoader.java

Spring usage:
https://docs.spring.io/spring-framework/docs/3.0.x/spring-framework-reference/html/resources.html#resources-classpath-wildcards

There is an existing Checkstyle PR for this here: https://github.com/checkstyle/checkstyle/pull/8789/files, but without issue and more details/ discussion, we cannot move forward.

**Comment by nmancus1** [comment]
I'm on this.

**Comment by nmancus1** [comment]
Should we maintain this order:
`URL first, then as a file that must exist, and then finally as a resource on the classpath.` ?

**Comment by romani** [comment]
Keep order, to keep compatibility

**Comment by pbludov** [comment]
Fix is merged.
