### ISSUE TITLE
Checkstyle should support property expansion within property definitions (property chaining)

### ISSUE THREAD

**Issue by nmancus1** [checkstyle/checkstyle#9173]
Checkstyle should support property expansion within property definitions (also known as property chaining), similar to [eclipse-cs ](https://checkstyle.org/eclipse-cs/#!/properties):

>  'property chaining' to let you use 'properties within properties'.
With this feature you can write something like this in your .properties file:
property1=abc
property2=${property1}def
Using ${property2} in your checkstyle configuration will then be resolved to: abcdef

```bash
➜  src cat checkstyle.properties 
basedir=/home/nick/
checkstyle.suppressions.file=${basedir}config/suppressions.xml

➜  src cat config.xml 
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
        "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>

    <module name="TreeWalker">
        <module name="SuppressionXpathFilter">
            <property name="file" value="${checkstyle.suppressions.file}"/>
        </module>
    </module>
</module>

➜  src java -jar checkstyle-8.39-all.jar -p checkstyle.properties -c config.xml TestClass.java
com.puppycrawl.tools.checkstyle.api.CheckstyleException: cannot initialize module TreeWalker - cannot initialize module SuppressionXpathFilter - Unable to find: ${basedir}config/suppressions.xml
...

```

I would expect Checkstyle to expand `${basedir}` to `/home/nick/` in the definition of property `checkstyle.suppressions.file`.  

Note:
There is an existing PR at https://github.com/checkstyle/checkstyle/pull/8794#event-4187545416.

**Comment by nmancus1** [comment]
I'm on this.

**Comment by rnveach** [comment]
How do we have support for it already then?
https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/master/sevntu-checks/checkstyle.properties

**Comment by nmancus1** [comment]
> How do we have support for it already then?

The file you linked does not use property chaining within the same file, unless I am misunderstanding something. Here is one of the test cases that I am using to perhaps give a better example:

```properties

basedir=/home
checkstyledir=${basedir}/checkstyle
checkstyledir.nochaining=/checkstyle
configdir=${checkstyledir}/configs
config.nochaining=/config
checkstyle.suppressions.file=${configdir}/suppressions.xml
checkstyle.file.other=${basedir}${checkstyledir.nochaining}${config.nochaining}/suppressions.xml


```

**Comment by rnveach** [comment]
Sorry, ignore my comment. I thought this was asking for just property expansion but I see the chaining on the end and read closer.

**Comment by pbludov** [comment]
Fix is merged.
