### ISSUE TITLE
Update year in copyright header and other places

### ISSUE THREAD

**Issue by strkkk** [checkstyle/checkstyle#9184]
The time has come

**Comment by AkMo3** [comment]
@strkkk I think we should divide this into issue into multiple sections as almost every file as the copyright header.

**Comment by pbludov** [comment]
> @strkkk I think we should divide this into issue into multiple sections as almost every file as the copyright header.

We have script for this job:
https://github.com/checkstyle/checkstyle/blob/master/.ci/bump-license-year-in-all-projects.sh

**Comment by romani** [comment]
I executed this script - https://github.com/checkstyle/checkstyle/commit/1e3fb3fae940bf7ea340592f7f0cda3af1b320e3
