### ISSUE TITLE
Github actions should react with thump up (+1) emoj on message if triggered

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#9187]
this is how dependabot works and it is really cool feature as 
author of command knows if bot is actually triggered an action.
Example: https://github.com/checkstyle/checkstyle/pull/9155#issuecomment-757561323

we need this feature for our github actions also. I hope dependabot is opensource and we can take this feature from its sources.

**Comment by strkkk** [comment]
Fix is merged
