### ISSUE TITLE
Feature Request?: Include Checkstyle Modules from other files

### ISSUE THREAD

**Issue by lars-sh** [checkstyle/checkstyle#9188]
I would like to define one checkstyle definition and use it for multiple projects. That's no problem. In addition I would like to allow defining additional rules per project.

In other words: I'd like to include/import project-specific checks into a checkstyle definition.

Is there an already existing functionality to accomplish that?
If not, please handle this as feature request.

**Example Configuration of what I have in mind:**
The following global configuration references two additional checkstyle definitions.
```XML
<module name="Checker">
	<module name="IncludeCheckstyleModule">
		<property name="single" value="false" />
		<property name="path" value="single-module.xml" />
	</module>
	
	<module name="TreeWalker">
		<module name="IncludeCheckstyleModule">
			<property name="path" value="multiple-modules.xml" />
		</module>
	</module>
</module>
```

The first is just a single module (the XML root) to be included:
```XML
<module name="NewlineAtEndOfFile">
	<property name="lineSeparator" value="lf" />
</module>
```

The second includes all the children of the XML root element. This is probably the more useful way.
```XML
<module>
	<module name="RightCurly" />
	<module name="FinalClass" />
</module>
```

**Comment by romani** [comment]
you might want to have something like https://github.com/checkstyle/checkstyle/issues/991#issuecomment-510010054
already existing feature of xml/dtd

**Comment by lars-sh** [comment]
The mentioned idea is more or less a workaround, but I'm fine with it for now.
Many thanks for helping me out on this.
