### ISSUE TITLE
Change format of violation message

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#919]
For example on LineLength violation I get the following error:
_[ERROR] src\test\java\com\test\SampleTest.java**[89]** (sizes) LineLength: Line is longer than 180 characters (found 202)._

It would be better to have colon and line number instead of braces, so that I can directly paste the reference to IntelliJ and go to affected line:
_[ERROR] src\test\java\com\test\SampleTest.java**:89** (sizes) LineLength: Line is longer than 180 characters (found 202)._

**Comment by romani** [comment]
right, the same format has exception stacktrace

**Comment by mkordas** [comment]
After investigation it occurred that this is problem with maven-checkstyle-plugin, not Checkstyle itself, so I'm closing it.

**Comment by romani** [comment]
@mkordas , please open issue against plugin.

**Comment by mkordas** [comment]
Submitted at https://issues.apache.org/jira/browse/MCHECKSTYLE-291
