### ISSUE TITLE
Metadata generation fails on line wrapped type description

### ISSUE THREAD

**Issue by nmancus1** [checkstyle/checkstyle#9204]
Discovered at https://github.com/checkstyle/checkstyle/pull/9076#discussion_r559056728, when a check's class level javadoc  property description is line wrapped in  mid-sentence, metadata generation is incomplete.

From https://github.com/checkstyle/checkstyle/pull/9076:

```java

 * Property {@code requiredJavadocPhrase} - Specify the comment text pattern which qualifies a
 * method as designed for extension. Supports multi-line regex. Type is
 * {@code java.util.regex.Pattern}.
 * Default value is {@code ".*"}.

```

Yields:
```xml

            <property default-value=".*" name="requiredJavadocPhrase" type="">
               <description/>
            </property>

```
Also,

```java

 * Property {@code requiredJavadocPhrase} - Specify the comment text pattern which qualifies a
 * method as designed for extension. Type is {@code java.util.regex.Pattern}.
 * Default value is {@code ".*"}.
 * 
```

Yields:
```xml

            <property default-value=".*"
                      name="requiredJavadocPhrase"
                      type="java.util.regex.Pattern">
               <description>Specify the comment text pattern which qualifies a</description>
            </property>

```
-----

**The following is outdated and incorrect, and can be fixed at https://github.com/checkstyle/checkstyle/pull/9209:**

During a fix remove from configs:

In `config/checkstyle_non_main_files_suppressions.xml`:
```xml
<!-- until https://github.com/checkstyle/checkstyle/issues/9204 -->
   <suppress id="lineLength" files="config_design\.xml" lines="163"/>
``` 

In `config/suppressions.xml`:
```xml
  <!-- until https://github.com/checkstyle/checkstyle/issues/9204 -->
  <suppress id="lineLengthXml" files="config_design\.xml" lines="163"/>
```

**Comment by strkkk** [comment]
@nmancus1 I have briefly checked generation and it looks like it is working ok.
Description is taken from class javadoc, not from setter javadoc. I assume that your javadoc for class was incomplete during run and this issue came up.

Also I haven't noticed any issues in other checks.

**Comment by rnveach** [comment]
@nmancus1 From PR pointed to, I remember the issue being with the main javadoc.
It was:
````
 * method as designed for extension. Supports multi-line regex. Type is {@code java.util.regex.Pattern}.
````
and the tool was failing unless the line was like:
````
 * method as designed for extension. Supports multi-line regex.
 * Type is {@code java.util.regex.Pattern}.
````

**Comment by nmancus1** [comment]
>  I remember the issue being with the main javadoc.

You are correct, thank you. I will update issue.

**Comment by nmancus1** [comment]
@strkkk Thanks for helping me to get this correct; I have reproduced the correct error, and updated this issue.

**Comment by romani** [comment]
fix is merged.
metadata for property  `violateExecutionOnNonTightHtml` at JavadocMissingLeadingAsterisk is fixed
