### ISSUE TITLE
Violation of the  priority rule in CustomImportOrder

### ISSUE THREAD

**Issue by SGanguly1999** [checkstyle/checkstyle#9205]
**Code:--**

package com.company;

import static java.lang.Math.*; // OK
import static java.util.Scanner;//OK

import java.io.*; // OK
import java.net.*; //OK
import java.time.*; //OK
import javax.net.ssl.SSLContext; //OK
import javax.net.ssl.TrustManager; //OK
import javax.net.ssl.X509TrustManager;//OK

import org.apache.http.conn.ClientConnectionManager; // OK
import org.apache.http.conn.scheme.Scheme; //OK
import org.apache.http.conn.scheme.SchemeRegistry;//OK
import org.apache.http.conn.ssl.SSLSocketFactory; //OK
import org.apache.http.impl.client.DefaultHttpClient; //OK

**Configuration file:--**
```
<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name="Checker">
  <module name="TreeWalker">
    <property name="tabWidth" value="7"/>
    <module name="CustomImportOrder">
      <property name="customImportOrderRules" value="STATIC###SAME_PACKAGE(3)###STANDARD_JAVA_PACKAGE###SPECIAL_IMPORTS"/>
      <property name="specialImportsRegExp" value="^org\."/>
      <property name="sortImportsInGroupAlphabetically" value="true"/>
      <property name="separateLineBetweenGroups" value="false"/>
    </module>
  </module>
</module>

```

**Command executed:---**
java -jar checkstyle-8.39-all.jar -c config.xml   Hello.java

**Output generated:---**
Starting audit...
Audit done.

**Expected:---**

import static java.lang.Math.*; // OK
import static java.util.Scanner;//OK

import java.io.*; // OK
import java.net.*; //OK
import java.time.*; //OK
import javax.net.ssl.SSLContext; // VIOLATION
import javax.net.ssl.TrustManager; //VIOLATION
import javax.net.ssl.X509TrustManager;//VIOLATION

import org.apache.http.conn.ClientConnectionManager; // OK
import org.apache.http.conn.scheme.Scheme; //OK
import org.apache.http.conn.scheme.SchemeRegistry;//OK
import org.apache.http.conn.ssl.SSLSocketFactory; //OK
import org.apache.http.impl.client.DefaultHttpClient; //OK

Statement:---The priority order as stated in the config file is  `<property name="customImportOrderRules" value="STATIC###SAME_PACKAGE(3)###STANDARD_JAVA_PACKAGE###SPECIAL_IMPORTS"/>`  is not holding true as  javax packages should come before the java packages

Same is the case with the org packages which should be in SAME PACKAGE group but is in SPECIAL IMPORT group.

**Comment by rnveach** [comment]
> as the javax packages should come before the java packages 

Where do you see something to this effect, or amounts to such, declared in the documentation?

If anything, https://checkstyle.org/config_imports.html#CustomImportOrder_Properties `standardPackageRegExp` property shows `java` and `javax` both fall under STANDARD_JAVA_PACKAGE and there is no defined order between the 2.

Further `sortImportsInGroupAlphabetically` being set to `true` means things are sorted alphabetically. `java` comes before `javax` in most sorting routines because `java` is shorter.

Also please update issue with your expect output so we are all on the same page what you are looking for.

**Comment by SGanguly1999** [comment]
@rnveach  Yeah I agree that java and javax falls under the STANDARD_JAVA_PACKAGE .But javax falls under SAME PACKAGE(3) too.

And according to the priority rule mentioned in the documentation
![image](https://user-images.githubusercontent.com/42171790/105637168-137b0e80-5e92-11eb-8d74-8cb5bef45f35.png)

It should come under SAME PACKAGE group.
This is the part actually creating a confusion to me. I might have misunderstood it.Please help me with this?

**Comment by rnveach** [comment]
> javax falls under SAME PACKAGE(3)
> And according to the priority rule mentioned in the documentation
> It should come under SAME PACKAGE group.

None of the text in your screenshot specifically mentions `javax`. Additionally what is screenshoted only has a brief text for SAME_PACKAGE which just states it is second priority. Can you quote what is specifically making you think javax is tied to SAME_PACKAGE.

SAME_PACKAGE is defined at https://checkstyle.org/config_imports.html#CustomImportOrder_Rule_Description : 
> SAME_PACKAGE(n) group. This group sets the ordering of the same package imports. Imports are considered on SAME_PACKAGE group if n first domains in package name and import name are identical:

Which as defined only applies to imports that match the package name. `com.company` is the name of the package, so only things the same as it plus 1 extra identifier will be ordered under it's rules.

**Comment by rnveach** [comment]
@romani ping

**Comment by SGanguly1999** [comment]
> Which as defined only applies to imports that match the package name. `com.company` is the name of the package, so only things the same as it plus 1 extra identifier will be ordered under it's rules.

Thanks a lot @rnveach .This clarifies my doubt.I  misunderstood this part

**Comment by SGanguly1999** [comment]
@
