### ISSUE TITLE
Sonar Dashboard link doesn't work in Generated Reports

### ISSUE THREAD

**Issue by AkMo3** [checkstyle/checkstyle#9217]
In [Project Report](https://checkstyle.org/project-reports.html) the redirection link to Sonar Dashboard is https://sonarcloud.io/project/index/com.puppycrawl.tools:checkstyle. This link is invalid and should be replaced with https://sonarcloud.io/dashboard?id=org.checkstyle%3Acheckstyle.

**Comment by romani** [comment]
@AkMo3 , thanks a lot, please send PR to fix it.

**Comment by AkMo3** [comment]
@romani Sir, I didn't get any result of `grep -r "https://sonarcloud.io/project/index/com.puppycrawl.tools:checkstyle"`. Can you please refer to which file to edit?

**Comment by AkMo3** [comment]
On It.

**Comment by romani** [comment]
Fix is merged
