### ISSUE TITLE
Findbugs violation: Checker.setClassloader should be Checker.setClassLoader

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#922]
Confusing to have methods com.puppycrawl.tools.checkstyle.Checker.setClassloader(ClassLoader) and com.puppycrawl.tools.checkstyle.TreeWalker.setClassLoader(ClassLoader)    BAD_PRACTICE    NM_CONFUSING    449-450     Low

That change will brake compatibility with checkstyle-maven-plugin, so it should be done only after plugin will switch to java7 version of checkstyle.

New method with correct name was added, old method is deprecated, will be removed as soon as maven plugin will switch to latest versions (that use java7).
##

**Comment by romani** [comment]
we can remove method as soon as [Issue MCHECKSTYLE-293 - usage of Checker.setClassLoader method](https://issues.apache.org/jira/browse/MCHECKSTYLE-293) is fixed

**Comment by romani** [comment]
maven checkstyle plugin is released as 2.17.

But it is still problematic to remove such method as most of integrations/plugins still use it and they are still on old versions  of our library (good example is [Sonar plugin](http://docs.sonarqube.org/display/PLUG/Checkstyle+Plugin), still 6.4.1).

So final removal of deprecated method should be done after some time.... lets make in half of the year (6 checkstyle releases) - at May 15 2016, 1 year after method is marked as deprecated (12 checkstyle releases).

**Comment by rnveach** [comment]
@romani This looks like a Checkstyle 8 candidate. We are pass May 2016.

**Comment by romani** [comment]
fix is merged
