### ISSUE TITLE
Record definition elements "record component list" and "implements clause" out of order in AST.

### ISSUE THREAD

**Issue by nmancus1** [checkstyle/checkstyle#9221]
From https://github.com/checkstyle/checkstyle/pull/9157#issue-550110578 and https://github.com/checkstyle/checkstyle/issues/9152#issuecomment-755031970:

I have discovered an issue with the construction of the record definition AST, which affects the functionality of IndentationCheck on records that implement an interface:
https://github.com/checkstyle/checkstyle/blob/7e76db268f109f658220dc68eaa2dadc31b2dd5f/src/main/resources/com/puppycrawl/tools/checkstyle/grammar/java.g#L562-L570

The `recordComponentsList` and `implementsClause` ASTs order is reversed in the tree construction on line 569. 

We need to resolve this issue before we can merge the changes at https://github.com/checkstyle/checkstyle/pull/9157.

**Comment by rnveach** [comment]
Fix was merged

**Comment by romani** [comment]
I changed label to be "bug" as we detected no changes in Checks on this.
But this issue can be considered "breaking compatibility" also.

**Comment by rnveach** [comment]
https://github.com/checkstyle/checkstyle/pull/9157#pullrequestreview-579839612
> We need clear note in release notes that we changed AST structure, we might even put on it "breaking compatibility" label to make it very visible.

This comment is why I put breaking compatibility.

**Comment by romani** [comment]
Sevntu do not have Check for records, so nothing was defected

**Comment by rnveach** [comment]
I am just asking in general for future issues.

**Comment by romani** [comment]
In general it is better to mark it breaking compatibility
