### ISSUE TITLE
ImportOrder and CustomImportOrder report only first "Extra separation" violation, inconsistent order

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#9251]
from https://github.com/checkstyle/checkstyle/pull/9225#issuecomment-770578744

This is well known problem. Both `ImportOrder` and `CustomImportOrder` checks report "Extra separation" violation.
But only first message will be logged. Which one will be first depends on the phase of the moon. This behaviuor can be changed [here](https://github.com/checkstyle/checkstyle/blob/1e3fb3fae940bf7ea340592f7f0cda3af1b320e3/src/main/java/com/puppycrawl/tools/checkstyle/TreeWalker.java#L55) by replacing `HashMap` with any ordered map. But there may be some nuances related to threading in the future. Another way is to report "Extra separation" violation twice.

Expected: order of violations should be deterministic

**Comment by rnveach** [comment]
> here by replacing HashMap with any ordered map.

I think you mean the `Set` has to be replaced with a `TreeSet`. The key of the map is on the token. The order of the tokens is defined by our antlr tree and changing that map won't effect the order of the tokens. The difference issue is most likely connected to order the checks are executed, which is what the value of the `HashMap` is, the set of checks. Those may need to be ordered so the same check gets executed first.

**Comment by rnveach** [comment]
I tried added ordering to `ordinaryChecks` and `commentChecks` which are used for notifying begins/destroys and I am getting a very weird, unexplained NPE because `context.get().fileContents` is `null` when `NoWhitespaceBeforeCheck` is trying to read the input file on it's visit.

**Comment by romani** [comment]
Fix is merged
