### ISSUE TITLE
diff report generation should have default projects file

### ISSUE THREAD

**Issue by nmancus1** [checkstyle/checkstyle#9255]
Identified at https://github.com/checkstyle/checkstyle/pull/8177#issuecomment-774805912 and lots of other places.  Since we nearly always use all projects for diff report generation, we should create a default behavior for "Github, generate report" so that if no `projects-to-test-on.properties` file is supplied, we use a default one with all projects uncommented.  

So that we don't have to maintain a separate file, we could just `sed` the existing one in https://github.com/checkstyle/contribution/tree/master/checkstyle-tester, as we do for `no-exception-test.sh`:
https://github.com/checkstyle/checkstyle/blob/633913daadc885605377e10a34a8923696c2fa8f/.ci/no-exception-test.sh#L18-L19

It would be good to make report generation as simple as possible for contributors.

**Comment by romani** [comment]
We  do not need sed, we just use already prepared file.

If execution  become too long, we can remove some projects. So by default initially user should not think on list of projects to do regression. If maintainers would like to extend regression, we will fall back to original mode (with two files in PR description)

**Comment by romani** [comment]
Attention: diff.grovy should not have default, default should be for GitHub action.

**Comment by strkkk** [comment]
I have created PR for this change.

The only question is - for now there is only one project, but I think by default there should be more (with openjdk excluded).
May be make a new file like `default-projects-to-test-on.properties` with more projects and use it as default?

**Comment by nmancus1** [comment]
> but I think by default there should be more (with openjdk excluded).

Yes, after https://github.com/checkstyle/contribution/commit/5060bb03d0e3145630fb1da22334881c5e697522#diff-4babda926d86e67b56213c42ba1167d06302965c978b112f262c27392e2aede2 we can use all projects in the file.

This is why I mentioned `sed` above; we can just remove all `#` in front of projects.

**Comment by strkkk** [comment]
In my opinion it is better to have different file than do some sed magic, it is clearer.
Anyway, it can be done by changing env variable value in diff action script

**Comment by pbludov** [comment]
Fix is merged.
