### ISSUE TITLE
Add job to scan sources for closed issue references

### ISSUE THREAD

**Issue by strkkk** [checkstyle/checkstyle#9256]
Inspired by https://github.com/checkstyle/checkstyle/issues/5089#issuecomment-774998752
Issue was fixed and closed, but its reference is still in docs.

Possible solution:
CI Job that collects all lines in source code (or xml only?) that match pattern `github.com/checkstyle/checkstyle/issues/\d{1,5}`, extracts issue id and checks that all collected ids are not closed.
Job fails if some of mentioned issues are closed

Note: some files should be excluded, like release notes

P.S. It is also can check if issue is approved or not

**Comment by rnveach** [comment]
What happens if we use issue reference to mention more details than what is laid out documented inside what is stored in the repo?

**Comment by strkkk** [comment]
@rnveach for start we can grep files by regex `(until|till) https://github.com/checkstyle/checkstyle/issues/\d{1,5}` and then extend it to match other comments that match some temp workarounds until some issue is fixed.

**Comment by romani** [comment]
It makes sense to try, in PR we will see how it behaves

**Comment by strkkk** [comment]
During working on this issue, I discovered interesting thing.
Several old open issues are mentioned in code, but github responds with 500 error in browser, but API calls are ok. Anyway, it is a bit difficult to understand what they are about.
https://github.com/checkstyle/checkstyle/issues/1854
https://github.com/checkstyle/checkstyle/issues/2160
https://github.com/checkstyle/checkstyle/issues/3095

**Comment by strkkk** [comment]
@pbludov I have discovered that closed issue https://github.com/checkstyle/checkstyle/issues/6916 is mentioned here
https://github.com/checkstyle/checkstyle/blob/77721c4ac3fc9252bfe9840dcb6fae93e0965562/config/intellij-idea-inspections.xml#L4603-L4623

Do you remember some details? It can be removed or something else should be done?

**Comment by strkkk** [comment]
> what if the job will collect all issues on github? I.e. `github.com/.*/issues/`

there going to be a huge number of false positives. There are a lot of references that are left for more information, not as todos.
So pattern should be a bit smarter.

**Comment by strkkk** [comment]
> We are still using Junit4 for PowerMock tests.

Ok, I will update reference. 

By the way, can other items (except powermock) be removed from list?

**Comment by pbludov** [comment]
> By the way, can other items (except powermock) be removed from list?

This is a good question. There definitely are some unused methods, for example `ExpectedException.expect`, `junit.framework.Assert`, `org.mockito.InOrder`.

**Comment by romani** [comment]
>what if the job will collect all issues on github? 

Let's merge simple version first, we can improve later on

**Comment by romani** [comment]
fix is merged.
