### ISSUE TITLE
Migrate shippable CI jobs to other place(s)

### ISSUE THREAD

**Issue by strkkk** [checkstyle/checkstyle#9266]
Reason - https://blog.shippable.com/the-next-step-in-the-evolution-of-shippable-jfrog-pipelines
> The Shippable service will no longer be available as of May 3rd, 2021.

Article suggests JFrog Pipelines as alternative, but it is not clear do they have quota for open source projects or not.

**Comment by romani** [comment]
https://github.com/Shippable/support/issues/5202

**Comment by strkkk** [comment]
@romani They responded in ticket, but I didn't fully understand - should job be migrated to JFrog or other CI?

**Comment by romani** [comment]
Hardware is on our account, they provide software to run CI

**Comment by romani** [comment]
moved all to travis,
webhook is removed:
`This action cannot be undone. Future events will no longer be delivered to this webhook (https://577032be3be4f4faa56adb38:YZaGHaoihTo5xlFi@api.shippable.com/projects/577032be3be4f4faa56adb38/newBuild).`
