### ISSUE TITLE
Fix cases when exception is logged and thrown in Checkstyle codebase

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#927]
According to https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/master/sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/EitherLogOrThrowCheck.java logging and then throwing exception is bad practice.

Example: https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/HandlerFactory.java#L70

In scope of this issue is fixing all such problems in Checkstyle codebase.

**Comment by rnveach** [comment]
@romani 
The example file was fixed in the referenced issue.
I eyeballed the remaining loggers in CS and they don't throw an exception with them, and the check in the first post reported nothing.
I don't think this issue is in CS anymore.

**Comment by romani** [comment]
@rnveach, thanks for catching that, that issue was resolved by some other refactoring.

Checks from sevntu projects will be applied to CS code base in scope of other issue.
