### ISSUE TITLE
Remove DetailAstImpl usages from main code

### ISSUE THREAD

**Issue by strkkk** [checkstyle/checkstyle#9271]
Found at https://github.com/checkstyle/checkstyle/pull/9264

RightCurlyCheck has usages.

After it, violations should be removed from import control file
https://github.com/checkstyle/checkstyle/blob/7c7958a6004f3a0bd4c9444027ecdffc8ae9353f/config/import-control.xml#L18

**Comment by AkMo3** [comment]
@strkkk Can you please suggest what needs to be done. I find that [RightCurlyCheck.java#L717](https://github.com/checkstyle/checkstyle/blob/9c53648515ba2208ca50c7078fc059328424ee3e/src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java#L717) has DetailAstImpl() function. Does it needs to replaced by a DetailAST class constructor or something?

**Comment by strkkk** [comment]
@AkMo3 from brief check of the code it looks like it is used to create mock node. So I suggest to refactor this method to return Optional or null instead of mock node.

**Comment by AkMo3** [comment]
Solved. I will make a PR. Thanks.

**Comment by nmancus1** [comment]
We will need to allow ParserUtil to use `com.puppycrawl.tools.checkstyle.DetailAstImpl` import explicitly in `import-control.xml` in fix for this issue after #9272.

**Comment by AkMo3** [comment]
> We will need to allow ParserUtil to use `com.puppycrawl.tools.checkstyle.DetailAstImpl` import explicitly in `import-control.xml` in fix for this issue after #9272.

Changes done in #9324.

**Comment by romani** [comment]
fix is merged
