### ISSUE TITLE
Improve Github action for site generation to place a direct link to updated section

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#9274]
Example:
PR modify exact file src/xdocs/**config_coding**.xml (we need to get a list of changed files in xdocs folder) name/path of them matches name on html
https://github.com/checkstyle/checkstyle/pull/9234/files#diff-cd8c9a8c8d730d1c9a128300a5b0b8302beac605ae7e9d8486e18aae24c44270

in xml we can find `<subsection name="Examples" id="HiddenField_Examples">` first section from change.
**HiddenField** is what we need to parse from this line.

Expected: post like https://github.com/checkstyle/checkstyle/pull/9234#issuecomment-778634614
attention to additional link like:
checkstyle-diff-reports.s3.us-east-2.amazonaws.com/HiddenFieldBranch_2021153117/**config_coding**.html#**HiddenField**

**Comment by aryaniiit002** [comment]
how do we proceed with this?
i thought of something like we provide a kind of `path or name of check` or like @romani mentioned above `config_coding/HiddenField` in PR description, every time we make changes in docs.

**Comment by aryaniiit002** [comment]
how do we proceed with this?
i thought of something like we provide a kind of `path or name of check` or like @romani mentioned above `config_coding/HiddenField` in PR description, every time we make changes in docs.
if we provide the path then we will get results of direct link to updated section otherwise as usually we are getting.
and **if** we do make any changes, will we do that in here [checkstyle/.github/workflows/site.yml ](https://github.com/checkstyle/checkstyle/blob/b51e96403cf844fa805113e4570f33bc36314388/.github/workflows/site.yml#L92)?

**Comment by strkkk** [comment]
@aryaniiit002 it will be simpler for contributor to do not write anything in PR description. Especially, it is almost always a new contributors and it can be confusing for them. Also, not all contributors know what section each check belongs to.
So it is better to make github action smart enough to figure this out by itself.

For example, implementation can grep diff between patch branch and master, extract section in xdocs.
After this build an url for specific section based on name of xml file and check name.

**Comment by aryaniiit002** [comment]
> grep diff between patch branch and master, extract section in xdocs.

i keep searching about it but not getting, i know we can use git diff --stat may be but how do we copy or extract the output and similarly the section in docs?
can you give me something that might help me?

**Comment by strkkk** [comment]
@aryaniiit002 I am not sure what exactly you are asking for. You can extract diff to some file using [git diff](https://stackoverflow.com/questions/822811/showing-which-files-have-changed-between-two-revisions) to some file and after it you can try to extract information that can help to understand what check was affected. It can be some done in other ways, e.g. (stupid version, but possible)
1. get diff in some file
2. get names of modified files
3. name of xml file will be page name like config_coding, while name of the check (e.g. HiddedFieldCheck) will be used to understand section (HiddenField)

Or by some other way. The main goal is to get page name and section name

**Comment by stoyanK7** [comment]
@romani Found this one while digging for issues. We solved it at https://github.com/checkstyle/checkstyle/issues/12853. It can be closed.

**Comment by romani** [comment]
Fix is merged
