### ISSUE TITLE
Use private final loggers instead of private static final in Checkstyle codebase

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#929]
Follow-up to discussion in #920

As stated in http://wiki.apache.org/commons/Logging/StaticLog libraries should use `private final` loggers instead of `private static final` ones.
- all loggers should be changed to `private final`
- PMD rule `ProperLogger` should be not violated or suppressed - it states _A logger should normally be defined private static final and be associated with the correct class. Private final Log log; is also allowed for rare cases where loggers need to be passed around, with the restriction that the logger needs to be passed into the constructor._
- PMD rule `LoggerIsNotStaticFinal` needs to be suppressed
- ideally we should get rid of all loggers that are unnecessary
##

**Comment by romani** [comment]
@samuel-gu , please help us with this.

**Comment by samuel-gu** [comment]
I'm on it

**Comment by samuel-gu** [comment]
@romani @mkordas About 15 files with private static final loggers are input files for tests. They don't have declared constructors. Should I go ahead and change those loggers to private final as well?

**Comment by romani** [comment]
> About 15 files with private static final loggers are input files for tests.

no, inputs should not be changed, we care only about "main" code

**Comment by romani** [comment]
@samuel-gu , are going to continue ? If you do not have time now please let us know we could give this issue to smb else

**Comment by samuel-gu** [comment]
I was planning of finishing it after finals week. I guess I don't have time now

**Comment by romani** [comment]
@samuel-gu , please define dates when you plan to continue, not let us know till what time keep this on you.

**Comment by samuel-gu** [comment]
Saturday, May 6th

**Comment by crud3** [comment]
Because this issue seems free/abandoned and the PR #4076 is closed but not merged and marked as "incomplete", I have decided to give it a try.

See PR #5169

**Comment by romani** [comment]
Fix is merged

**Comment by tsjensen** [comment]
In the [Apache Commons Wiki](https://wiki.apache.org/commons/Logging/StaticLog) it says:

> Just to be completely clear: this only applies to code deployed via a classloader that is shared across multiple "independent" applications. None of this discussion is relevant to normal application code, or to library code that is never deployed into a shared classpath. These categories of code can safely use static references.

Just because I'm curious: Would you mind sharing the scenario you have in mind where Checkstyle is deployed in a shared classloader? This might affect associated libraries also. Thank you!

**Comment by romani** [comment]
I do not have exact example, but as we are library we can appear at any place, user can use us even only for parsing of java code only. We do not know our location, and we want to be less static as possible. To be less static by fields helps in MT mode and improve design, the only expense I see is few extra objects in memory - not a big deal. Logging is not used that much in our library.

If you see scenarios where non static logger is a problem, please share.

**Comment by tsjensen** [comment]
Thank you for the explanation!
