### ISSUE TITLE
Remove unused property types from site

### ISSUE THREAD

**Issue by strkkk** [checkstyle/checkstyle#9291]
https://checkstyle.org/property_types.html#Overview

There is a number of property types which are not used and, very likely, will never be used.
- byte
- byte[]
- char
- char[]
- short
- short[]
- float
- float[]
- long
- long[]

Questionable - double is not used, but can be useful in future. Same is for Pattern[]

All properties in code with primitive types have either int, boolean or double[] type.
I do not see a reason to keep unused primitive types in docs.

**Comment by romani** [comment]
they are supported, and might be used in thirdparty Checks, majority of them(thirparties) are in close source projects.
