### ISSUE TITLE
Disable markdownlint rule MD041

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#9292]
The template is read from the first line, since the first line doesn't matchup with the github extensible template, it is failing to create an issue template.

Markdown linting is giving errors that the file should start with some header: Moreover I thought of getting some ways to ignore some files, but the feature is not yet implemented, https://github.com/markdownlint/markdownlint/issues/167

_Originally posted by @Abhishek-kumar09 in https://github.com/checkstyle/checkstyle/issues/9286#issuecomment-779206214_

**Comment by pbludov** [comment]
If a rule can not be ignored for some files then it should be disabled for the entire project.

**Comment by romani** [comment]
fix is merged
