### ISSUE TITLE
Solve Spotbugs violations reported for Java 11

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#9297]
New SpotBugs [errors](https://dev.azure.com/romanivanovjr/romanivanovjr/_build/results?buildId=1150&view=logs&j=89cf5cab-37fd-5e09-60f8-9a1742bde19b&t=f89aed60-e6d5-5750-95ad-83cc60b84b61&l=10593):
`[ERROR] Low: JavadocDetailNodeParser.errorListener not initialized in constructor and dereferenced in com.puppycrawl.tools.checkstyle.JavadocDetailNodeParser.getFirstNonTightHtmlTag(JavadocParser) [com.puppycrawl.tools.checkstyle.JavadocDetailNodeParser] At JavadocDetailNodeParser.java:[line 534] UWF_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR`

`[ERROR] Low: AbstractCheck$FileContext.fileContents not initialized in constructor and dereferenced in com.puppycrawl.tools.checkstyle.api.AbstractCheck.getLine(int) [com.puppycrawl.tools.checkstyle.api.AbstractCheck] At AbstractCheck.java:[line 294] UWF_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR`

`[ERROR] Low: AbstractCheck$FileContext.fileContents not initialized in constructor and dereferenced in com.puppycrawl.tools.checkstyle.api.AbstractCheck.getLines() [com.puppycrawl.tools.checkstyle.api.AbstractCheck] At AbstractCheck.java:[line 284] UWF_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR`

`[ERROR] Low: AbstractFileSetCheck$FileContext.fileContents not initialized in constructor and dereferenced in com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.log(int, int, String, Object[]) [com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck] At AbstractFileSetCheck.java:[line 219] UWF_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR`

_Originally posted by @pbludov in https://github.com/checkstyle/checkstyle/issues/9281#issuecomment-778971972_

These violations are reported only with  Java11 build. But all of them are the true positives and should be resolved. This is possible a trait/bug in Spotbugs plugin.

**Comment by pbludov** [comment]
The field [errorListener](https://github.com/checkstyle/checkstyle/blob/1e3fb3fae940bf7ea340592f7f0cda3af1b320e3/src/main/java/com/puppycrawl/tools/checkstyle/JavadocDetailNodeParser.java#L95) in `JavadocDetailNodeParser` can be easily converted for a local variable.

**Comment by pbludov** [comment]
The class `AbstractCheck.FileContext` can be redesigned to be immutable. We can replace the context in `AbstractCheck#setFileContents` with new context.
Same for `AbstractFileSetCheck.FileContext`

**Comment by romani** [comment]
fix is merged
