### ISSUE TITLE
Resolve Pitest Issues - HeaderCheck (1)

### ISSUE THREAD

**Issue by aryaniiit002** [checkstyle/checkstyle#9304]
Child issue of #7797,

https://github.com/checkstyle/checkstyle/blob/de85c1ed1a5819b89ed2a9fb465ff297ff6e2af4/.ci/pitest.sh#L55

**Comment by aryaniiit002** [comment]
this is the case of redundant code, @romani please give your approval so that i can proceed further and send the PR.

**Comment by aryaniiit002** [comment]
this is the case of redundant code, @romani @rnveach  please give your approval so that i can proceed further and send the PR.

**Comment by aryaniiit002** [comment]
Please give approval so that i can send PR and resolve this issue, i have its solution.

**Comment by strkkk** [comment]
@aryaniiit002 please do not hesitate to submit PR if you solved some pitest issue even if it is not approved

**Comment by strkkk** [comment]
fix is merged
