### ISSUE TITLE
test inputs should be compilable with javac11

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#9310]
Prerequisite for #9146

Some test inputs are [incompatible](https://cloud.drone.io/checkstyle/checkstyle/1281/4/2) with JDK11. 

All usages of `sun.*` packages should be replaced.

InputIllegalIdentifierNameUnderscore.java should be moved to non-compilable folder due to [JEP 302](http://openjdk.java.net/jeps/302)

_Originally posted by @pbludov in https://github.com/checkstyle/checkstyle/issues/9281#issuecomment-781213448_

**Comment by rnveach** [comment]
Fix was merged
