### ISSUE TITLE
JavadocTagContinuationIndentation does not check text inside HTML elements

### ISSUE THREAD

**Issue by wltan** [checkstyle/checkstyle#9315]
From https://github.com/checkstyle/checkstyle/pull/8177#discussion_r579386002

Check documentation: https://checkstyle.org/config_javadoc.html#JavadocTagContinuationIndentation

```cmd
D:\checkstyletest>type config.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="severity" value="error"/>
    <module name="TreeWalker">
                  <module name="JavadocTagContinuationIndentation"/>
    </module>
</module>

D:\checkstyletest>type test\MyClass.java
class MyClass {

    /**
     * Javadoc.
     *
     * @param x This is the start of a param tag.
     *     Continuing lines must have indentation. // ok
     * Lines without indentation are violations. // violation
     * <p>HTML tags are also affected by this rule.</p> // not a violation yet, will be fixed in #8177
     * And subsequent text is also checked. // violation
     *     <p>
     * However, text nested inside HTML elements are unaffected. // no violation
     *     </p>
     */
    void foo(int x) {
        // do stuff
    }

}
D:\checkstyletest>set RUN_LOCALE="-Duser.language=en -Duser.country=US"

D:\checkstyletest>java -jar "-Duser.language=en -Duser.country=US" checkstyle-8.40-all.jar -c config.xml test\MyClass.java
Starting audit...
[ERROR] D:\checkstyletest\test\MyClass.java:8: Line continuation have incorrect indentation level, expected level should be 4. [JavadocTagContinuationIndentation]
[ERROR] D:\checkstyletest\test\MyClass.java:10: Line continuation have incorrect indentation level, expected level should be 4. [JavadocTagContinuationIndentation]
Audit done.
Checkstyle ends with 2 errors.
```

---

The line `However, text nested inside HTML elements are unaffected.` does not raise any violation, despite having no indentation with respect to the `@param` tag. In general, when HTML elements are involved the text between the start and end tags is not checked.

This behavior may be unintuitive as the check documentation does not have any examples on whether or not this is considered a violation.
- ~~If this is intended behavior, then the documentation should be updated to include a similar example so that future users will not be confused by this case.~~ see https://github.com/checkstyle/checkstyle/issues/9315#issuecomment-808765706
- Otherwise, if this is considered a bug then please see https://github.com/checkstyle/checkstyle/pull/8177#discussion_r579386002 for details on how it may be fixed.

**Comment by shashwatj07** [comment]
@romani I want to work on this.

> if this is considered a bug
is this a bug? or do I need to update the documentation?

**Comment by romani** [comment]
it is bug, 
nor now, I do not think we need to update docuemntation

**Comment by pbludov** [comment]
Fix is merged.
