### ISSUE TITLE
Generated link is incorrect if fork branch name has hash sign

### ISSUE THREAD

**Issue by strkkk** [checkstyle/checkstyle#9323]
Found during #9288 

Patch branch has `#` in it, so github action takes branch name and includes this into link.
Generated link looks like https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/Issue_#9271_2021125041/reports/diff/index.html, but it is incorrect(shows access denied) because `#` is a special sign.

Possible solutions - exclude hash sign from branch name or take hash from branch name and use it instead of branch name

**Comment by AkMo3** [comment]
Only replacing `#` with `%23` would do the job.

**Comment by strkkk** [comment]
> Only replacing `#` with `%23` would do the job.

Yeap, but there may be some other issues in future since branch name is some kind of user input. Therefore we can take hash from branch name to avoid any issues with special signs

**Comment by romani** [comment]
Fix is merged, short commit sha is used
