### ISSUE TITLE
Consider upgrading antlr dependency

### ISSUE THREAD

**Issue by ngeor** [checkstyle/checkstyle#9340]
Hi,

the maven artifact `com.puppycrawl.tools:checkstyle:8.41` depends on `antlr:antlr:2.7.7`, which is from 2007. Could you consider upgrading to a more recent version of antlr (like 4)? Note that checkstyle is already on v4 for `antlr4-runtime`.

Thanks.

**Comment by romani** [comment]
it is HUGE  project - https://github.com/checkstyle/checkstyle/wiki/Checkstyle-GSoC-2021-Project-Ideas#project-name-upgrade-java-grammar-from-antlr2-to-antlr4
it is not just a bump a version in pom, it might result in all Checkstyle modules update/rewrite.
