### ISSUE TITLE
Checkstyle 8.41 introduces regression on indentation rules when the line starts with new after try {

### ISSUE THREAD

**Issue by jcamerin** [checkstyle/checkstyle#9341]
I have read check documentation: https://checkstyle.org/config_misc.html#Indentation
I have downloaded the latest checkstyle from: https://checkstyle.org/cmdline.html#Download_and_Run
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

```bash
/var/tmp $ javac CheckstyleBug.java
/var/tmp $ cat CheckstyleBug.java
public class CheckstyleBug {
    public void delete(final int assetId) {
        try {
            new Object().equals(Integer.valueOf(assetId));
        } catch (Exception ignore) {
            // Ignore, but log failure to delete views.
        }
    }
}


/var/tmp $ cat checkstyle.xml
<?xml version="1.0"?>
<module name="Checker">
       .....
        <module name="Indentation">
            <property name="basicOffset" value="4"/>
            <property name="braceAdjustment" value="0"/>
            <property name="caseIndent" value="4"/>
            <property name="throwsIndent" value="8"/>
            <property name="lineWrappingIndentation" value="8"/>
            <property name="arrayInitIndent" value="2"/>
            <property name="forceStrictCondition" value="true"/>
        </module>
....
</module>

/var/tmp $ RUN_LOCALE="-Duser.language=en -Duser.country=US"
/var/tmp $ java $RUN_LOCALE -jar checkstyle-8.41-all.jar -c checkstyle.xml CheckstyleBug.java 
Starting audit...
[WARN] /Users/john.camerin/Projects/accelerator-merge-master/CheckstyleBug.java:4:13: 'new' has incorrect indentation level 12, expected level should be 8. [Indentation]
Audit done.

```

The rule is expecting the 'new' keyword to have the same indentation as the 'try' block within which it is contained.  The try keyword is followed by curly braces, which should apply the basicOffset of 4 and expect the indentation to be 4 spaces more than the try.
This should pass the indentation rule as it did in Checkstyle 8.40

**Comment by strkkk** [comment]
@jcamerin Please format your post to follow template and trim config only to relevant check

**Comment by jcamerin** [comment]
Ok, I've updated the ticket, following the guide and template.  Hopefully, I have it correct this time.  Please let me know if there I still missed something.

**Comment by romani** [comment]
@Abhishek-kumar09 , please help to restore previous behavior.

**Comment by Abhishek-kumar09** [comment]
Opened a PR.

**Comment by pbludov** [comment]
Fix is merged.
