### ISSUE TITLE
Remove downlaod progress from maven executions

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#9343]
https://cloud.drone.io/checkstyle/checkstyle/1447/1/3

logs are full of download progress, we should disable it as we did for sonar launch in Wercker recently
https://github.com/checkstyle/checkstyle/pull/9322

**Comment by romani** [comment]
Fix is merged

**Comment by rnveach** [comment]
I believe we have regular expression that checks for `-e` on all maven commands. We could extend this to `--no-transfer-progress`.
