### ISSUE TITLE
Extract common bash CI functions into util.sh

### ISSUE THREAD

**Issue by strkkk** [checkstyle/checkstyle#9348]
Idea came from https://github.com/checkstyle/checkstyle/pull/9347

At the moment, each sh file for CI has its own copy of functions, e.g.
https://github.com/checkstyle/checkstyle/blob/2275613f2991e6e5df78e629c3ba379c9bcce6e9/.ci/wercker.sh#L21-L23
and
https://github.com/checkstyle/checkstyle/blob/2275613f2991e6e5df78e629c3ba379c9bcce6e9/.ci/validation.sh#L4-L6
and others.

So, the idea is to extract such common functions into separate file util.sh and add following line to each sh file that needs common functions
`source /path/to/util.sh`

related stackoverflow discussion https://stackoverflow.com/questions/10822790/can-i-call-a-function-of-a-shell-script-from-another-shell-script

**Comment by strkkk** [comment]
@rnveach yeap. PR I mentioned in description introduces one more common function, so there is going to be bunch of functions to extract.

**Comment by aryaniiit002** [comment]
removeFolderWithProtectedFiles() { 
   `find $1` -delete 
 }
 or `find "$1"` which one is correct?

**Comment by romani** [comment]
Wrapped by braces is always better

**Comment by strkkk** [comment]
fix is merged
