### ISSUE TITLE
No main manifest attribute for Checkstyle 8.29

### ISSUE THREAD

**Issue by htshame** [checkstyle/checkstyle#9352]
I've downloaded `checkstyle-8.29.jar` from https://mvnrepository.com/artifact/com.puppycrawl.tools/checkstyle/8.29

I'm trying to execute `java -jar checkstyle-8.29.jar -c checkstyle.xml MyApp.java`, and get an error:
`no main manifest attribute, in checkstyle-8.29.jar`

I'm using openjdk 11.0.2, Windows 10.

**Comment by rnveach** [comment]
You downloaded a maven artifact, not a CLI program.

To run the CLI you need to download the "all" jar, which can be found at https://github.com/checkstyle/checkstyle/releases/ as noted in our website at https://checkstyle.org/#Download .
