### ISSUE TITLE
Add example of AST for TokenTypes.ABSTRACT

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#9371]
https://checkstyle.org/apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#ABSTRACT

needs to be extended to show example of AST.
Source to be updated: https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java

PLEASE READ for more details: https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-AST-in-TokenTypes

**Comment by tharun571** [comment]
What is AST?

**Comment by 20001LastOrder** [comment]
I am on it

**Comment by romani** [comment]
fix is merged
