### ISSUE TITLE
Add example of AST for TokenTypes.ANNOTATION_MEMBER_VALUE_PAIR

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#9372]
https://checkstyle.org/apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#ANNOTATION_MEMBER_VALUE_PAIR

needs to be extended to show example of AST.
Source to be updated: https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java

PLEASE READ for more details: https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-AST-in-TokenTypes

**Comment by tharun571** [comment]
@romani 
The defenition and example of https://checkstyle.org/apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#ANNOTATION_ARRAY_INIT is in ANNOTATION_ARRAY_VALUE_PAIR, there is no example in ANNOTATION too, the example of ANNOTATION_ARRAY_INIT is not the example in https://checkstyle.org/apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#ANNOTATION_ARRAY_INIT.
Shall I correct all of them or stick to the main issue?

**Comment by hungleba** [comment]
I am on it

**Comment by AbhinavRajputEXE** [comment]
I'm on it
