### ISSUE TITLE
Add example of AST for TokenTypes.ASSIGN

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#9373]
https://checkstyle.org/apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#ASSIGN

needs to be extended to show example of AST.
Source to be updated: https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java

PLEASE READ for more details: https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-AST-in-TokenTypes

**Comment by anshuman10398** [comment]
Hey, I worked at this issue, used the basic assignment example ( a = b; ) and will be sending a PR is sometime. :)

**Comment by tharun571** [comment]
I am not able to run the java doc, it returns the issue as An error has occurred in Javadoc report generation: Unable to find javadoc command: The environment variable JAVA_HOME is not correctly set.
Any idea why?

**Comment by romani** [comment]
@anshuman10398  , I helped you to make first update to place your PR as example at https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-AST-in-TokenTypes

please select one more "first gsoc" issue and try to do this without help. 
Please do not send PR from your master branch, create some special branch for this as it will allow you to do some other issue while we review your PR.

**Comment by anshuman10398** [comment]
@romani thanks for the guidance :)

**Comment by anshuman10398** [comment]
@romani so @rdiachenko pointed out a small error in the merged PR #9378  ,could you please reopen the issue so i could correct that part and submit a new PR? Thanks.

**Comment by rdiachenko** [comment]
@anshuman10398 
> could you please reopen the issue so i could correct that part and submit a new PR?

Reopened, please fix.
