### ISSUE TITLE
Tool for release notes section generation for releasenotes.xml file

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#938]
specification - https://github.com/checkstyle/checkstyle/wiki/Release-notes-automation#generator-of-xml-section-content-for-releasenotesxml-file

tool should be created to substitute https://github.com/checkstyle/contribution/tree/master/releasenotes-builder

**Comment by MEZk** [comment]
@romani 
See https://github.com/checkstyle/contribution/pull/36

**Comment by romani** [comment]
Please put the same link to commit message

**Comment by MEZk** [comment]
@romani 
Done

**Comment by romani** [comment]
Fixed in https://github.com/checkstyle/contribution/pull/36

**Comment by romani** [comment]
@MEZk , 

1) we need to skip in result notes all commits that are starting with "minor|infra" people do not need to know this actions.
Example: https://travis-ci.org/checkstyle/checkstyle/jobs/97212673#L300

2) 
Leading spaces are missed - https://travis-ci.org/checkstyle/checkstyle/jobs/97212673#L238

**Comment by MEZk** [comment]
@romani 
Got it
2) I will try to update thymeleaf version. Maybe they resolve the problem.

**Comment by MEZk** [comment]
@romani 
1) Done. See https://github.com/checkstyle/contribution/pull/46
