### ISSUE TITLE
update example of AST for TokenTypes.ANNOTATION_DEF

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#9391]
https://checkstyle.org/apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#ANNOTATION_DEF

needs to be extended to show example of AST in format that printed by our CLI (change "+-" to "`-").
Source to be updated: https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java

PLEASE READ for more details: https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-AST-in-TokenTypes

**Comment by Rahulkhinchi03** [comment]
Hey @romani,
I am on it.
