### ISSUE TITLE
update example of AST for TokenTypes.ANNOTATIONS

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#9393]
https://checkstyle.org/apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#ANNOTATIONS

needs to be extended to show example of AST in format that printed by our CLI (change "+-" to "`-").
Source to be updated: https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java

PLEASE READ for more details: https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-AST-in-TokenTypes

**Comment by suman-somu** [comment]
@romani, can you assign me on this ? 
I am working on it.

**Comment by romani** [comment]
Just make a comment "I am on it" it it easier than management by assignee.

**Comment by suman-somu** [comment]
I am on it

**Comment by romani** [comment]
Fixed https://github.com/checkstyle/checkstyle/blob/3895bdee4908f0d8790cdc50dd10dcc38f14b0f6/src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java#L4776
