### ISSUE TITLE
update example of AST for TokenTypes.ARRAY_DECLARATOR

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#9394]
https://checkstyle.org/apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#ARRAY_DECLARATOR

needs to be extended to show example of AST in format that printed by our CLI (change "+-" to "`-").
Source to be updated: https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java

PLEASE READ for more details: https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-AST-in-TokenTypes

**Comment by vivek286** [comment]
I want to work on it. Can you guide me?

**Comment by vivek286** [comment]
I am on it

**Comment by vivek286** [comment]
@romani Sir I corrected the format for contribution but still, one task fails please guide me on how to resolve it.

**Comment by romani** [comment]
fix is merged
