### ISSUE TITLE
create example of AST for TokenTypes.BSR

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#9404]
https://checkstyle.org/apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#BSR

needs to be extended to show example of AST in format that printed by our CLI .
Source to be updated: https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java

PLEASE READ for more details: https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-AST-in-TokenTypes

**Comment by theexplorist** [comment]
I am on it!

**Comment by theexplorist** [comment]
@romani PR submitted

**Comment by pbludov** [comment]
Fix is merged
