### ISSUE TITLE
 create example of AST for TokenTypes.BSR_ASSIGN

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#9405]
https://checkstyle.org/apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#BSR_ASSIGN

needs to be extended to show example of AST in format that printed by our CLI .
Source to be updated: https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java

PLEASE READ for more details: https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-AST-in-TokenTypes

**Comment by shashwatj07** [comment]
I'm on it!

**Comment by romani** [comment]
fix is merged
