### ISSUE TITLE
update example of AST for TokenTypes.CASE_GROUP

### ISSUE THREAD

**Issue by rdiachenko** [checkstyle/checkstyle#9406]
https://checkstyle.org/apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#CASE_GROUP

Needs to be extended to show example of AST in format that printed by our CLI (change "+-" to "`-") .
Source to be updated: https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java

PLEASE READ for more details: https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-AST-in-TokenTypes

**Comment by vivek286** [comment]
I am on it

**Comment by vivek286** [comment]
@rdiachenko All checks passed please review PR.

**Comment by Rahulkhinchi03** [comment]
Hey @rdiachenko! I am on it.

**Comment by Rahulkhinchi03** [comment]
how can I fix these failing issues? @rdiachenko @timurt please guide for the same!

**Comment by romani** [comment]
fix is merged
