### ISSUE TITLE
create example of AST for TokenTypes.DIV

### ISSUE THREAD

**Issue by rdiachenko** [checkstyle/checkstyle#9415]
https://checkstyle.org/apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#DIV

needs to be extended to show example of AST in format that printed by our CLI .
Source to be updated: https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java

PLEASE READ for more details: https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-AST-in-TokenTypes

**Comment by theexplorist** [comment]
Will the example a = 4 / 2 work here. 
I want to solve this issue with this example @rdiachenko .

**Comment by romani** [comment]
Yes it works.

**Comment by theexplorist** [comment]
I am on it!

**Comment by theexplorist** [comment]
@romani Hi, 
I have send a PR, I followed PR guidelines, ran the verify goal, corrected the errors, passed the verify, generated javadoc, generated jar, but still some checks are not passing, kindly review my PR and help me. 
This is my first contribution to checkstyle, kindly help me.
Regrads.

**Comment by theexplorist** [comment]
@romani Hi the update is all the checks are passed. The documentation provided is quite detailed, from many failing check to no failing checks, I learned a lot. Learned to read logs of CI. 
Kindly review my PR, excited to contribute more. I have attached the necessary proofs of Javadoc and CLI and amended my commit to maintain a clean PR.
Regards

**Comment by strkkk** [comment]
fix is merged
