### ISSUE TITLE
Fix PMD violations from 'optimizations' ruleset in Checkstyle

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#942]
Rules to be enabled:
* AvoidInstantiatingObjectsInLoops - probably some suppressions needed 
* LocalVariableCouldBeFinal - do we want all local variables to be final where possible?
* MethodArgumentCouldBeFinal - do we want all parameters variables to be final where possible?
* PrematureDeclaration - reasonable, we can fix that
* RedundantFieldInitializer - very simple to fix
* SimplifyStartsWith - will decrease readability, possible coverage decrease
* UseStringBufferForStringAppends - will decrease readability, probably some suppressions needed

**Comment by romani** [comment]
> AvoidInstantiatingObjectsInLoops - probably some suppressions needed 

yes, I even can think to suppress that rule at all as it could produce more false-positves than real problems

> LocalVariableCouldBeFinal - do we want all local variables to be final where possible?
> MethodArgumentCouldBeFinal - do we want all parameters variables to be final where possible?

that validation for fanatics :) and it pollutes code with modifiers , that cause difficulty to read a code.

> SimplifyStartsWith - will decrease readability, possible coverage decrease

lets try see what it reports, yes we could ignore it if do not benefit to readability.

> UseStringBufferForStringAppends - will decrease readability, probably some suppressions needed

without any option to set up a level/count of allowed "+", that validations will do no good for code.

**Comment by romani** [comment]
merged.
