### ISSUE TITLE
create example of AST for TokenTypes.ELIST

### ISSUE THREAD

**Issue by rdiachenko** [checkstyle/checkstyle#9420]
https://checkstyle.org/apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#ELIST

needs to be extended to show example of AST in format that printed by our CLI .
Source to be updated: https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java

PLEASE READ for more details: https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-AST-in-TokenTypes

**Comment by Binita-tech** [comment]
I am on it.

**Comment by Binita-tech** [comment]
@romani , can you please elaborate about expression list, I am not able to figure out.

**Comment by romani** [comment]
Open first link and search in page ELIST.
There number of examples already, choose the most compact.

**Comment by Binita-tech** [comment]
@romani, I have changed at one place(ELIST) but in my commit, two files changed are showing.
Please have a look.

**Comment by romani** [comment]
Please remove your update over INSTANCE_INIT, it should be done in different issue

**Comment by romani** [comment]
https://github.com/checkstyle/checkstyle/issues/9455#issuecomment-988078054

**Comment by romani** [comment]
Fix is merged
