### ISSUE TITLE
create example of AST for TokenTypes.ELLIPSIS

### ISSUE THREAD

**Issue by rdiachenko** [checkstyle/checkstyle#9421]
https://checkstyle.org/apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#ELLIPSIS

needs to be extended to show example of AST in format that printed by our CLI .
Source to be updated: https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java

PLEASE READ for more details: https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-AST-in-TokenTypes

**Comment by romani** [comment]
@anjanayraina , can you help us to resolve this issue ? it is very good start point, very easy to do but help to see whole process.

**Comment by MUzairS15** [comment]
I am on it

**Comment by romani** [comment]
fix is merged
