### ISSUE TITLE
create example of AST for TokenTypes.EOF

### ISSUE THREAD

**Issue by rdiachenko** [checkstyle/checkstyle#9426]
https://checkstyle.org/apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#EOF

needs to be extended to show example of AST in format that printed by our CLI .
Source to be updated: https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java

PLEASE READ for more details: https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-AST-in-TokenTypes

**Comment by nmancus1** [comment]
We can close this issue now that we have decided on making a new `COMPILATION_UNIT` token: https://github.com/checkstyle/checkstyle/issues/3095#issuecomment-889204547
