### ISSUE TITLE
update example of AST for TokenTypes.EXPR

### ISSUE THREAD

**Issue by rdiachenko** [checkstyle/checkstyle#9428]
https://checkstyle.org/apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#EXPR

Needs to be extended to show example of AST in format that printed by our CLI (change "+-" to "`-") .
Source to be updated: https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java

PLEASE READ for more details: https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-AST-in-TokenTypes

**Comment by SidRainMan** [comment]
I'm on it.

**Comment by CryptoSingh1337** [comment]
I am on it.

**Comment by timurt** [comment]
@CryptoSingh1337 merged, thank you for contribution :)
