### ISSUE TITLE
 update example of AST for TokenTypes.IDENT

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#9450]
https://checkstyle.org/apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#IDENT

needs to be extended to show example of AST.
Source to be updated: https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java

PLEASE READ for more details: https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-AST-in-TokenTypes

**Comment by Binita-tech** [comment]
I am on it.

**Comment by Binita-tech** [comment]
I have read the above description, Can you please elaborate a little bit about what changes I have to make in Indent?

**Comment by Venkatesh-24** [comment]
First you need to create a AST for the given indent example in TokenTypes.java in a Test Class and check it against mvn clean verify after you updated the TokenTypes.java file please refer to similar successful PRs to get an idea.

**Comment by AbhinavRajputEXE** [comment]
@pbludov @romani may I work on this too?

**Comment by Binita-tech** [comment]
Let me work on this. This is my first time contributing to checkstyle and I am figuring it out.

**Comment by AbhinavRajputEXE** [comment]
@Binita-tech sure, fine👍

**Comment by Binita-tech** [comment]
@romani , please review this PR
