### ISSUE TITLE
 update example of AST for TokenTypes.INSTANCE_INIT

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#9455]
https://checkstyle.org/apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#INSTANCE_INIT

needs to be extended to show example of AST.
Source to be updated: https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java

PLEASE READ for more details: https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-AST-in-TokenTypes

**Comment by AbhinavRajputEXE** [comment]
I'm on it

**Comment by romani** [comment]
@AbhinavRajputEXE , please verify why there is no update in master branch

**Comment by AbhinavRajputEXE** [comment]
> @AbhinavRajputEXE , please verify why there is no update in master branch

@romani sir I think @Binita-tech didn't upstream the changes, before making the commit, that's why maybe my changes were showing in her commit too. But now in her second commit, it's gone I guess.
