### ISSUE TITLE
 update example of AST for TokenTypes.LAMBDA

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#9458]
https://checkstyle.org/apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#LAMBDA

needs to be extended to show example of AST.
Source to be updated: https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java

PLEASE READ for more details: https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-AST-in-TokenTypes

**Comment by Hrushi20** [comment]
Pull Request #10324 solves the current issue.

Please Review and let me know if I need to change the file.

I don't understand why the test cases are failing

![Screenshot (7)](https://user-images.githubusercontent.com/65367566/125474287-9f9a0c22-aaea-4729-bcb6-98e0d8773112.png)

Please help me out if I am making any mistake.

Thank You.

**Comment by Rahulkhinchi03** [comment]
I am on it.

**Comment by romani** [comment]
fix is merged
