### ISSUE TITLE
 update example of AST for TokenTypes.LITERAL_CASE

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#9466]
https://checkstyle.org/apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#LITERAL_CASE

needs to be extended to show example of AST.
Source to be updated: https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java

PLEASE READ for more details: https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-AST-in-TokenTypes

**Comment by keshavcodex** [comment]
Hello, i am beginner, can you help me how to start working on this issue.

**Comment by romani** [comment]
Merged
