### ISSUE TITLE
Allow nested blocks in switch statements

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#947]
[AvoidNestedBlocks](http://checkstyle.sourceforge.net/config_blocks.html#AvoidNestedBlocks) check reports violations for nested blocks in switch statements.

Visibility in switch block is not very intuitive, it is better to think about a each case as a function with its own scope of names. Users should be able to define non-shares scopes for names as it helps each case to use any names that suits its context. 

Users should be able to write the following code, with own scopes per `case`:
```java
switch (type) {
     case 1 : { // violation of AvoidNestedBlocks
        final String name = "one";
     }
     case 2 : { // violation of AvoidNestedBlocks
        final String name = "two";
    }
```
Checkstyle should not force users to write such code:
```java
switch (type) {
     case 1 : 
        String name = "one";
     case 2 : 
        final String otherNameBecauseNameIsAlreadyDefined = "two";
        name = "or reusing variables";
```

Follow-up to #946.

**Comment by romani** [comment]
Please take a look at available options , even example at html page shows that this already done:
```
    case 1:
        // OK if allowInSwitchCase is true
        {
            System.out.println("Hello");
            x = 2;
            break;
        }
```
please use that option.

**Comment by mkordas** [comment]
Indeed, thanks!
