### ISSUE TITLE
 update example of AST for TokenTypes.LITERAL_DO

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#9472]
https://checkstyle.org/apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#LITERAL_DO

needs to be extended to show example of AST.
Source to be updated: https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java

PLEASE READ for more details: https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-AST-in-TokenTypes

**Comment by CryptoSingh1337** [comment]
I am on it.

**Comment by romani** [comment]
merged
