### ISSUE TITLE
 update example of AST for TokenTypes.LITERAL_NEW

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#9486]
https://checkstyle.org/apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#LITERAL_NEW

needs to be extended to show example of AST.
Source to be updated: https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java

PLEASE READ for more details: https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-AST-in-TokenTypes

**Comment by SGanguly1999** [comment]
I am on it.

**Comment by Rahulkhinchi03** [comment]
Hey, I am trying to resolve this issue!

**Comment by Rahulkhinchi03** [comment]
Hey @pbludov, I solved this issue. What things needed except 
1.Screenshot of Issue.
2. Java Source Code.
3. AST Format
4.  Expected update for Java Doc.
