### ISSUE TITLE
 update example of AST for TokenTypes.LITERAL_PROTECTED

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#9489]
https://checkstyle.org/apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#LITERAL_PROTECTED

needs to be extended to show example of AST.
Source to be updated: https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java

PLEASE READ for more details: https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-AST-in-TokenTypes

**Comment by Ritik2604** [comment]
I want to work on it. Did I have permission to do so?

**Comment by romani** [comment]
@Ritik2604 , just place a comment " I am on it" and it yours if nobody claimed it before you

**Comment by Ritik2604** [comment]
> @Ritik2604 , just place a comment " I am on it" and it yours if nobody claimed it before you

Ok, Thank You I will keep this in mind.
