### ISSUE TITLE
 update example of AST for TokenTypes.LITERAL_THROW

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#9499]
https://checkstyle.org/apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#LITERAL_THROW

needs to be extended to show example of AST.
Source to be updated: https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java

PLEASE READ for more details: https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-AST-in-TokenTypes

**Comment by Soist** [comment]
I am on it.

**Comment by Rahulkhinchi03** [comment]
Hey, I am on it. Can it be considered as Hacktoberfest Accepted?
