### ISSUE TITLE
 update example of AST for TokenTypes.LITERAL_TRUE

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#9502]
https://checkstyle.org/apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#LITERAL_TRUE

needs to be extended to show example of AST.
Source to be updated: https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java

PLEASE READ for more details: https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-AST-in-TokenTypes

**Comment by MahmoudAbdelazim** [comment]
I'm on it.

**Comment by romani** [comment]
Merged
