### ISSUE TITLE
update AnnotationUseStyleCheckTest to use unique Input file in each test method

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#9520]
AnnotationUseStyleCheckTest.java file reuse some inputs in few different test method.
Expected: each test method in Test class use it own Input file and do not share it with any other test method.

more details - https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-create-Input-files-for-tests

**Comment by haanhvu** [comment]
I am on it
