### ISSUE TITLE
update SuppressWarningsCheckTest to use unique Input file in each test method

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#9521]
SuppressWarningsCheckTest.java file reuse some Input files few time in few different test method.
Expected: each test method in Test class use it own Input file and do not share it with any other test method.

more details - https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-create-Input-files-for-tests

**Comment by anshuman10398** [comment]
Working on it

**Comment by anshuman10398** [comment]
@romani as per my understanding there are around 30 files that need to be added in order to meet the expectation, shall i limit them to 3 4 file changes per PR?

**Comment by SGanguly1999** [comment]
@anshuman10398 just to ask you are you still working on this issue?

**Comment by Devansu-Yadav** [comment]
@anshuman10398 Are u still working on this?

**Comment by romani** [comment]
Hmm, 10 PRs might be too much, let's try single PR with all updates inside, it will be mostly copy paste introduction, so single PR is ok
