### ISSUE TITLE
update JavadocVariableCheckTest to use unique Input file in each test method

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#9530]
JavadocVariableCheckTest.java file reuse some Input files few time in few different test method.
Expected: each test method in Test class use it own Input file and do not share it with any other test method.

more details - https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-create-Input-files-for-tests

**Comment by CryptoSingh1337** [comment]
I am on it.

**Comment by hiron1999** [comment]
I am on this issue

**Comment by hiron1999** [comment]
The issue #9530  resolved with all tests passed successfully.
@romani  please take a look the PR #9702 if you have time

**Comment by romani** [comment]
merged
