### ISSUE TITLE
WhitespaceAround on enhanced switch empty block

### ISSUE THREAD

**Issue by mrclmh** [checkstyle/checkstyle#9540]
I have read check documentation: https://checkstyle.org/config_xxxxxx.html#NameOfAffectedCheck
I have downloaded the latest checkstyle from: https://checkstyle.org/cmdline.html#Download_and_Run
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

```bash
/var/tmp $ javac YOUR_FILE.java
#[[MAKE SURE THERE IS SUCCESSFUL COMPILATION]]
```

/var/tmp $ cat config.xml
```xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
        "http://checkstyle.sourceforge.net/dtds/configuration_1_3.dtd">

<?xml version="1.0"?>
<!DOCTYPE module PUBLIC "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
        "http://checkstyle.sourceforge.net/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>
    <property name="haltOnException" value="true"/>
    <property name="severity" value="error"/>

    <module name="FileTabCharacter">
        <property name="eachLine" value="true"/>
    </module>
    <module name="NewlineAtEndOfFile"/>
    <module name="SuppressWarningsFilter"/>
    <module name="UniqueProperties"/>

    <module name="TreeWalker">
        <module name="SuppressWarningsHolder"/>

        <module name="WhitespaceAround">
            <property name="allowEmptyCatches" value="true"/>
            <property name="allowEmptyConstructors" value="true"/>
            <property name="allowEmptyMethods" value="true"/>
            <property name="allowEmptyLambdas" value="true"/>
            <property name="allowEmptyLoops" value="true"/>
            <property name="allowEmptyTypes" value="true"/>
            <property name="ignoreEnhancedForColon" value="false"/>
        </module>
    </module>
</module>
```

/var/tmp $ cat YOUR_FILE.java
```java
public class WhitespaceAround {
    private void switchTest() {
        switch ("foo") {
            case "A" -> {}
            case "B" -> System.out.println("B");
            default -> System.out.println("other");
        }
    }
}
```
/var/tmp $ RUN_LOCALE="-Duser.language=en -Duser.country=US"
/var/tmp $ java $RUN_LOCALE -jar checkstyle-X.XX-all.jar -c config.xml YOUR_FILE.java
```bash
Starting audit...
[ERROR] /private/var/tmp/WhitespaceAround.java:4:25: '{' is not followed by whitespace. [WhitespaceAround]
[ERROR] /private/var/tmp/WhitespaceAround.java:4:26: '}' is not preceded with whitespace. [WhitespaceAround]
Audit done.
Checkstyle ends with 2 errors.
```

For Windows users, please use `type` instead of `cat` and run

```cmd
set RUN_LOCALE="-Duser.language=en -Duser.country=US"
java %RUN_LOCALE% -jar checkstyle-X.XX-all.jar -c config.xml YOUR_FILE.java
```

in place of the last 2 commands above.

---
My expectation was that one of the allowEmpty* properties would stop the violation  on the line 
```java
case "A" -> {}
```

---

Still not clear ???
see example - https://checkstyle.org/report_issue.html#How_to_report_a_bug.3F

ATTENTION: FAILURE TO FOLLOW THE ABOVE TEMPLATE WILL RESULT IN THE ISSUE BEING CLOSED.

**Comment by Vyom-Yadav** [comment]
The issue lies over here-
This code will parse as ( I modified a bit, but won't make a difference ) 
```
|--LITERAL_CASE -> case [5:12]
    |       |   |   |   `--EXPR -> EXPR [5:17]
    |       |   |   |       `--NUM_INT -> 4 [5:17]
    |       |   |   |--LAMBDA -> -> [5:19]
    |       |   |   `--SLIST -> { [5:22]
    |       |   |       `--RCURLY -> } [5:23]
```
Here the problem is that `LAMBDA` is not the parent of `SLIST` Token. Whereas in the check-
```
    private static boolean isEmptyBlock(DetailAST ast, int parentType, int match) {
        final boolean result;
        final int type = ast.getType();
        if (type == TokenTypes.RCURLY) {
            final DetailAST parent = ast.getParent();
            final DetailAST grandParent = ast.getParent().getParent();
            result = parent.getFirstChild().getType() == TokenTypes.RCURLY
                    && grandParent.getType() == match;
        }
        else {
            result = type == TokenTypes.SLIST
                && parentType == match
                && ast.getFirstChild().getType() == TokenTypes.RCURLY;
        }
        return result;
    }
```
It checks for `LAMBDA` Token to be parent of `SLIST` Token or grand parent of `RCURLY` Token.
@romani If this issue is approved then I am willing to work on it.

**Comment by nmancus1** [comment]
Violations for WhitespaceAround are shown for both types of switch statements:

```bash
➜  src cat MyClass.java
public class MyClass {
    private void switchTest1() {
        switch ("foo") {
            case "A" -> {}
            case "B" -> System.out.println("B");
            default -> System.out.println("other");
        }
    }

    private void switchTest2() {
        switch ("foo") {
            case "A" : {}
            case "B" : System.out.println("B");
            default : System.out.println("other");
        }
    }

    public static void main(String[] args) {
    }

}
➜  src java MyClass.java
➜  src cat config.xml 
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
        "http://checkstyle.sourceforge.net/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>
    <property name="haltOnException" value="true"/>
    <property name="severity" value="error"/>

    <module name="FileTabCharacter">
        <property name="eachLine" value="true"/>
    </module>
    <module name="NewlineAtEndOfFile"/>
    <module name="SuppressWarningsFilter"/>
    <module name="UniqueProperties"/>

    <module name="TreeWalker">
        <module name="SuppressWarningsHolder"/>

        <module name="WhitespaceAround">
            <property name="allowEmptyCatches" value="true"/>
            <property name="allowEmptyConstructors" value="true"/>
            <property name="allowEmptyMethods" value="true"/>
            <property name="allowEmptyLambdas" value="true"/>
            <property name="allowEmptyLoops" value="true"/>
            <property name="allowEmptyTypes" value="true"/>
            <property name="ignoreEnhancedForColon" value="false"/>
        </module>
    </module>
</module>

➜  src java -jar checkstyle-8.41-all.jar -c config.xml MyClass.java
Starting audit...
[ERROR] Tester/src/MyClass.java:4:25: '{' is not followed by whitespace. [WhitespaceAround]
[ERROR] Tester/src/MyClass.java:4:26: '}' is not preceded with whitespace. [WhitespaceAround]
[ERROR] Tester/src/MyClass.java:12:24: '{' is not followed by whitespace. [WhitespaceAround]
[ERROR] Tester/src/MyClass.java:12:25: '}' is not preceded with whitespace. [WhitespaceAround]
Audit done.
Checkstyle ends with 4 errors.

```
There is no `allow*` property for empty switch case blocks, so we would need to implement a new property in WhitespaceAround like `allowEmptySwitch`.

`LAMBDA` token in this case is really the arrow operator (definite assignment, so that `break` is not needed), not really a "lambda" as in a lambda expression, and should not be considered as such when considering whitespace around tokens. 

> Here the problem is that LAMBDA is not the parent of SLIST Token.

The `LAMBDA` token should not be the parent of  `SLIST` [they should be siblings.](https://docs.oracle.com/javase/specs/jls/se12/preview/switch-expressions.html)

**Comment by Vyom-Yadav** [comment]
> > Here the problem is that LAMBDA is not the parent of SLIST Token.
> 
> The `LAMBDA` token should not be the parent of `SLIST`, [they should be siblings.](https://docs.oracle.com/javase/specs/jls/se12/preview/switch-expressions.html)

@nmancus1 I think my wording was wrong, I meant to say HERE `LAMBDA` is not the parent of `SLIST`  token whereas it is the parent in situations like `myAdd add = (int a,  int b) -> {return a + b;};`

**Comment by indyteo** [comment]
Hi, what about this issue?

Is it still planned to add an option `allowEmptySwitchCase`?

Our team uses checkstyle and it works great, but we are facing this issue and I didn't managed to get the workaround working (the `suppress-xpath` thing), I get this (even on latest version):
> cannot initialize module SuppressionFilter - Unable to parse suppressions.xml - Element type "suppress-xpath" must be declared.

We really would like not to have to disable completely the `WhitespaceAround` rule, as it is important, but this false-positive blocks our approval workflow unfortunately.
What could we do?

Thanks!

**Comment by romani** [comment]
@indyteo, 

Can you check behavior on latest CLI 10.18.1 we did a lot of updates for latest java syntax support in last few months. 
This issue might be resolved.

**Comment by indyteo** [comment]
Hi @romani,

Even with the latest version 10.18.1, there's no such option (at least not mentioned in [the documentation](https://checkstyle.org/checks/whitespace/whitespacearound.html#Properties)), and the same violation is reported.

**Comment by mahfouz72** [comment]
@romani please approve the issue and I am on it
