### ISSUE TITLE
update example of AST for TokenTypes.SINGLE_LINE_COMMENT

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#9568]
https://checkstyle.org/apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#SINGLE_LINE_COMMENT

needs to be extended to show example of AST.
Source to be updated: https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java

PLEASE READ for more details: https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-AST-in-TokenTypes

**Comment by johnlee-jh** [comment]
I am on it

**Comment by shubham11941140** [comment]
I am on it

**Comment by theanmolsharma** [comment]
I am working on this.

**Comment by MahmoudAbdelazim** [comment]
I am on it.

**Comment by romani** [comment]
Fix is merged
