### ISSUE TITLE
update example of AST for TokenTypes.STRICTFP

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#9577]
https://checkstyle.org/apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#STRICTFP

needs to be extended to show example of AST.
Source to be updated: https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java

PLEASE READ for more details: https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-AST-in-TokenTypes

**Comment by CryptoSingh1337** [comment]
I am bit confused that which method should I choose like example with method, class or interface.

**Comment by strkkk** [comment]
fix is merged
