### ISSUE TITLE
update example of AST for TokenTypes.TYPE_EXTENSION_AND

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#9587]
https://checkstyle.org/apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#TYPE_EXTENSION_AND

needs to be extended to show example of AST.
Source to be updated: https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java

PLEASE READ for more details: https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-AST-in-TokenTypes

**Comment by iamishuverma** [comment]
I am on it.

**Comment by CryptoSingh1337** [comment]
@iamishuverma are you working on this issue?

**Comment by romani** [comment]
Fix is merged
