### ISSUE TITLE
update example of AST for TokenTypes.TYPE_LOWER_BOUNDS

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#9588]
https://checkstyle.org/apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#TYPE_LOWER_BOUNDS

needs to be extended to show example of AST.
Source to be updated: https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java

PLEASE READ for more details: https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-AST-in-TokenTypes

**Comment by haanhvu** [comment]
I am on it

**Comment by CryptoSingh1337** [comment]
@haanhvu are you working on this issue?

**Comment by romani** [comment]
fix is merged

**Comment by haanhvu** [comment]
> @haanhvu are you working on this issue?
> If you are working on this. Please let me know.

I barely started. Now I'm gonna work on another one.
