### ISSUE TITLE
update example of AST for TokenTypes.TYPE_PARAMETER

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#9589]
https://checkstyle.org/apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#TYPE_PARAMETER

needs to be extended to show example of AST.
Source to be updated: https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java

PLEASE READ for more details: https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-AST-in-TokenTypes

**Comment by theanmolsharma** [comment]
I am working on it.

**Comment by theanmolsharma** [comment]
I have commited the changes to the master branch of my repo. They both can be merged. It will solve 2 issues. #9589 and #9549 .

**Comment by theanmolsharma** [comment]
it is ready to be merged. You can merge and close both issues now.

**Comment by pbludov** [comment]
Fix is merged
