### ISSUE TITLE
update example of AST for TokenTypes.TYPE_PARAMETERS

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#9590]
https://checkstyle.org/apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#TYPE_PARAMETERS

needs to be extended to show example of AST.
Source to be updated: https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java

PLEASE READ for more details: https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-AST-in-TokenTypes

**Comment by vivek286** [comment]
I am on it.

**Comment by theanmolsharma** [comment]
I would like to work on it. @vivek286 Are you still on it?

**Comment by pbludov** [comment]
Fix is merged
