### ISSUE TITLE
update example of AST for TokenTypes.UNARY_PLUS

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#9594]
https://checkstyle.org/apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#UNARY_PLUS

needs to be extended to show example of AST.
Source to be updated: https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java

PLEASE READ for more details: https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-AST-in-TokenTypes

**Comment by hiron1999** [comment]
hey, I'm working on this issue

**Comment by hiron1999** [comment]
It seems all the task passed successfully . Please take a look and let me know if any changes need  #9621

**Comment by romani** [comment]
fix is merged
