### ISSUE TITLE
update example of AST for TokenTypes.WILDCARD_TYPE

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#9596]
https://checkstyle.org/apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#WILDCARD_TYPE

needs to be extended to show example of AST.
Source to be updated: https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java

PLEASE READ for more details: https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-AST-in-TokenTypes

**Comment by gurleennsidhuu** [comment]
I am on it.

**Comment by brngylni** [comment]
Can I work on that ?

**Comment by romani** [comment]
@brngylni , yes, please work on this issue.

**Comment by brngylni** [comment]
I am aware of the test results. I am going to create a new pull request now.

**Comment by romani** [comment]
Merged
