### ISSUE TITLE
Allow commenting only one of the property methods

### ISSUE THREAD

**Issue by isopov** [checkstyle/checkstyle#96]
Creating Javadoc for Properties is valuable, but if done by any existing rules would result in a great deal of duplication. AllowMissingPropertyJavadoc allows to complete ignore all properties, but a more ideal solution is one in which you only need one comment to cover the getter and setter, and that the getter does not require a @return tag nor the setter an @param tag.
At the base a property is a singular item, and sensibly only requires explanation once. Comments like "Sets myProperty" are useless cruft and best avoided, and copying the whole explanation of what a property is into four places is almost as bad.
# Alternative request:

Most of the time, setters and getters are very simple, but it is not possible to suppress warnings if the JavaDoc for getters and setters is not defined. This could be added by one of the following methods:
Add a checkbox for allowMissingJavadocGetter and allowMissingJavadocGetter 
Add the possibility to define a regular expression so that methods that match that pattern should be not checked: allowMissingJavaDocPattern with a text entry field.
##

**Comment by nrmancuso** [comment]
It is not clear what the ask is here; if we still want to pursue this issue, let's open a new one following our bug report template.
