### ISSUE TITLE
Fix PMD violations from AvoidThrowingRawExceptionTypes rule in Checkstyle

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#961]
> Avoid throwing certain exception types. Rather than throw a raw RuntimeException, Throwable, Exception, or Error, use a subclassed exception or error instead.

Follow-up to #872.

Violations:
```
com.puppycrawl.tools.checkstyle.checks.AbstractTypeAwareCheck:299 Rule:AvoidThrowingRawExceptionTypes Priority:1 Avoid throwing raw exception types..
com.puppycrawl.tools.checkstyle.checks.ClassResolver:179 Rule:AvoidThrowingRawExceptionTypes Priority:1 Avoid throwing raw exception types..
com.puppycrawl.tools.checkstyle.checks.blocks.RightCurlyCheck:270 Rule:AvoidThrowingRawExceptionTypes Priority:1 Avoid throwing raw exception types..
com.puppycrawl.tools.checkstyle.checks.imports.CustomImportOrderCheck:321 Rule:AvoidThrowingRawExceptionTypes Priority:1 Avoid throwing raw exception types..
com.puppycrawl.tools.checkstyle.checks.imports.CustomImportOrderCheck:685 Rule:AvoidThrowingRawExceptionTypes Priority:1 Avoid throwing raw exception types..
com.puppycrawl.tools.checkstyle.checks.indentation.HandlerFactory:68 Rule:AvoidThrowingRawExceptionTypes Priority:1 Avoid throwing raw exception types..
com.puppycrawl.tools.checkstyle.checks.indentation.HandlerFactory:169 Rule:AvoidThrowingRawExceptionTypes Priority:1 Avoid throwing raw exception types..
com.puppycrawl.tools.checkstyle.checks.indentation.HandlerFactory:174 Rule:AvoidThrowingRawExceptionTypes Priority:1 Avoid throwing raw exception types..
com.puppycrawl.tools.checkstyle.checks.indentation.HandlerFactory:177 Rule:AvoidThrowingRawExceptionTypes Priority:1 Avoid throwing raw exception types..
```

**Comment by mkordas** [comment]
@romani, what do we want to use instead of `RuntimeException`? Is private exception with descriptive name what went wrong good approach for you? Or we should create package with exceptions to choose from?
It's also possible to create `RuntimeCheckstyleException`, but I don't think it is good idea.

**Comment by romani** [comment]
@mkordas ,

> what do we want to use instead of RuntimeException?

That is very controversial question. As demand for more specific type of Exception is clear , especially when we have a lot of exception types in our disposal (http://docs.oracle.com/javase/7/docs/api/java/lang/RuntimeException.html?is-external=true) even in standard JDK. But some time where is no need to be specific and exception is signal to stop processing. Details in message is good enough - it is very good practice to keep message informative, exception type will allow only in creation additional logic but that is contradict with "ExceptionAsFlowControl".

To my mind  we have to options:
- keep rule suppressed on certain classes (so we will control new cases appearances)
- genuflect to PMD rule and convert all that RuntimeExceptions to IllegalStateException (as it very general exception, and we do come up to unexpected state of execution in that cases) - http://docs.oracle.com/javase/7/docs/api/java/lang/IllegalStateException.html. But in reality it does not change anything in our processing - it is just to keep PMD happy and it is reasonable to some extend(see first paragraph).

> RuntimeCheckstyleException

yes, I would even keep PMD rule disabled and avoid extra entity.

**Comment by romani** [comment]
resolved already by some other commit, such exclude does not exists anymore in pmd configuration
