### ISSUE TITLE
i18n for Exception messages

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#968]
Ideally all Exception messages should be possible to translate to other languages
##

**Comment by romani** [comment]
pre-assigned to @timurt .

**Comment by Vyom-Yadav** [comment]
@romani @rnveach Can you give some more information on how to do it.

**Comment by Hrushi20** [comment]
Can we go ahead using [Locale](https://docs.oracle.com/javase/7/docs/api/java/util/Locale.html) and  [ResourceBundle](http://tutorials.jenkov.com/java-internationalization/resourcebundle.html) implementation.

Sample Example below
https://medium.com/i18n-and-l10n-resources-for-developers/the-java-i18n-guide-youve-been-waiting-for-a26d86f5882

Looking forward to implementing this feature.

**Comment by MANISH-K-07** [comment]
@romani , what's the difference between this and #3110 ?
I believe I've been doing the same internationalization there too ?

**Comment by MANISH-K-07** [comment]
@romani , ping please.. this issue seems duplicate.

**Comment by rnveach** [comment]
It is a slight duplicate. This issue came first. It doesn't really make this issue invalid.

**Comment by MANISH-K-07** [comment]
Thanks for the response @rnveach :)

> slight duplicate

Oh ok, could you please tell me what extra needs to be done here that won't be a part of #3110 ? So that we can get this through finish line....

**Comment by rnveach** [comment]
What is not clear from first post? If anything, we are just missing a list which someone will have to generate manually. I assume a starting point is a search could be done on the `throw` keyword.

**Comment by MANISH-K-07** [comment]
> missing a list which someone will have to generate manually

Already did at https://github.com/checkstyle/checkstyle/issues/3110#issuecomment-2002782772 :)

This list has all hardcoded exception msgs from user-facing files.

**Comment by rnveach** [comment]
Then it seems like this issue isn't needed as exceptions are being handled in other issue.

**Comment by MANISH-K-07** [comment]
Yep, https://github.com/checkstyle/checkstyle/issues/968#issuecomment-2053908450 😅

**Comment by romani** [comment]
will be covered by https://github.com/checkstyle/checkstyle/issues/3110
