### ISSUE TITLE
Fix enviroment dependent upper/lower case conversation

### ISSUE THREAD

**Issue by precoder** [checkstyle/checkstyle#969]
Conversation of Upper/Lower Case relies on Localization settings of the running Machine.
A possible result of this situation is referenced in:
http://sourceforge.net/p/eclipse-cs/bugs/295/

This problem can be reproduced from Command Line Interface with following commands:

git clone https://github.com/checkstyle/checkstyle.git
cd checkstyle
mvn clean package -Passembly
java -Duser.language=tr -Duser.country=TR -jar target/checkstyle-6.6-SNAPSHOT-all.jar -c /google_checks.xml src/main/java

Setting up different localization during unit test setup and executing affected tests with different localisations would be a convenient way to test this problem.
Currently tr_TR localization can be used to test this issue.

**Comment by precoder** [comment]
Affected artifacts, those needs to be modified are listed below:

lower:
src/main/java/com/puppycrawl/tools/checkstyle/api/Scope.java
src/main/java/com/puppycrawl/tools/checkstyle/api/SeverityLevel.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocStyleCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/SuppressWarningsHolder.java

upper:
src/main/java/com/puppycrawl/tools/checkstyle/api/Scope.java
src/main/java/com/puppycrawl/tools/checkstyle/api/SeverityLevel.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/AbstractOptionCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationUseStyleCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/HiddenFieldCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/NewlineAtEndOfFileCheck.java

generated sources and test classes that have to be ignored:
src/test/resources/
target/generated-sources/antlr/
target/test-classes/com/

Build in google_check configuration has
property name="severity" value="warning"
setting, which causes this parsing problem during upper/lower case conversation. 
Build in sun_checks does not seems to effected from this situation.

Additional info can be found in pull request #896.

**Comment by romani** [comment]
merged.
