### ISSUE TITLE
Resolve Pitest Issue - AbstractJavadocCheck

### ISSUE THREAD

**Issue by AkMo3** [checkstyle/checkstyle#9722]
Pitest to resolve
  `"AbstractJavadocCheck.java.html:<td class='covered'><pre><span  class='survived'>            Arrays.sort(acceptableJavadocTokens);</span></pre></td></tr>"`

**Comment by AkMo3** [comment]
I am on it.

**Comment by AkMo3** [comment]
@romani @strkkk @pbludov Can someone please approve this issue.

**Comment by strkkk** [comment]
fix is merged
