### ISSUE TITLE
update AvoidStarImportCheckTest to use unique Input file in each test method

### ISSUE THREAD

**Issue by jz20** [checkstyle/checkstyle#9741]
AvoidStarImportCheckTest.java file reuse some Input files few time in few different test method.
Expected: each test method in Test class use it own Input file and do not share it with any other test method.

more details - https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-create-Input-files-for-tests

**Comment by jz20** [comment]
This issue was opened as a GSoC 2nd issue. @romani Could you please approve it at your convenience?

**Comment by jz20** [comment]
I am on it.

**Comment by romani** [comment]
Fix is merged
