### ISSUE TITLE
update AbstractClassNameCheckTest.java to use unique Input file in each test method

### ISSUE THREAD

**Issue by Ritik2604** [checkstyle/checkstyle#9746]
AbstractClassNameCheckTest.java file reuse some Input files least time in a few different test method.
Expected: each test method in Test class use its own Input file and do not share it with any other test method.

more details - https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-create-Input-files-for-tests

**Comment by Ritik2604** [comment]
I am on it.

**Comment by Ritik2604** [comment]
This issue was opened as a GSoC 2nd issue. @romani  Could you please approve it at your convenience?

**Comment by romani** [comment]
merged
