### ISSUE TITLE
update RightCurlyCheckTest to use unique Input file in each test method

### ISSUE THREAD

**Issue by Devansu-Yadav** [checkstyle/checkstyle#9768]
RightCurlyCheckTest.java file reuses some Input files few times in few different test method.
Expected: each test method in Test class should use its own Input file and do not share it with any other test method.

more details - https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-create-Input-files-for-tests

**Comment by Devansu-Yadav** [comment]
This issue was opened as a GSoC 2nd issue. @romani Could you please approve it at your convenience?

**Comment by Devansu-Yadav** [comment]
I am working on it.

**Comment by romani** [comment]
merged
