### ISSUE TITLE
update DeclarationOrderCheckTest.java to use unique Input file in each test method

### ISSUE THREAD

**Issue by MahmoudAbdelazim** [checkstyle/checkstyle#9773]
DeclarationOrderCheckTest.java file reuses some Input files few time in few different test methods.
Expected: each test method in Test class use its own Input file and do not share it with any other test method.

more details - https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-create-Input-files-for-tests

**Comment by MahmoudAbdelazim** [comment]
I'm on it.

**Comment by MahmoudAbdelazim** [comment]
@romani can this issue be approved?

**Comment by timurt** [comment]
@MahmoudAbdelazim done

**Comment by romani** [comment]
merged
