### ISSUE TITLE
update ImportOrderCheckTest.java to use unique input file in each test method

### ISSUE THREAD

**Issue by CryptoSingh1337** [checkstyle/checkstyle#9780]
ImportOrderCheckTest.java file reuse some Input files few time in few different test method.
Expected: each test method in Test class use its own Input file and do not share it with any other test method.

more details - https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-create-Input-files-for-tests

**Comment by CryptoSingh1337** [comment]
@romani please approve this issue.

**Comment by CryptoSingh1337** [comment]
I am on it.

**Comment by CryptoSingh1337** [comment]
@timurt please make this issue approved.

**Comment by romani** [comment]
merged.
