### ISSUE TITLE
Prefer Method Reference above lambda expressions

### ISSUE THREAD

**Issue by AkMo3** [checkstyle/checkstyle#9784]
From https://github.com/sevntu-checkstyle/sevntu.checkstyle/pull/834

Replace lambda operator with method reference for CI to pass in 
https://github.com/checkstyle/checkstyle/blob/f868b02a37191ca662bb919f44353b55897793b0/src/test/java/com/puppycrawl/tools/checkstyle/xpath/AttributeNodeTest.java#L57
And 
https://github.com/checkstyle/checkstyle/blob/f868b02a37191ca662bb919f44353b55897793b0/src/test/java/com/puppycrawl/tools/checkstyle/xpath/AttributeNodeTest.java#L88

**Comment by romani** [comment]
Merged
