### ISSUE TITLE
Fix AvoidStaticImport violations in Checkstyle codebase

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#979]
Follow-up to #945.

While generally I like static imports, let's apply this rule for Checkstyle code at least for regression purposes.

**Comment by mkordas** [comment]
Actually we need to rethink this issue, as this rule may make sense for production code, but it's totally unreasonable for test code. @romani, what do you think? Maybe we should introduce some option to ignore test code? But how test code can be recognized?

**Comment by romani** [comment]
:) , good.

Static imports are good only in few cases:
1) code is focused on extensive usage of primary framework - junit, guava.
2) long chain calls
3) .... smth esle ... that I do not know now 

We do not extensively focused on any library - we I do not see any reason to allow static import.
But in  test code we focused on junit, I am ok to allow static for junit classes (but that need to be proven that we use it extensively!), and as it is not a production code I am also ok to be less demanding.

We could ignore test sources by their location in project, please look at suppression of Checkstyle.

**Comment by mkordas** [comment]
Actually in our tests apparently we have an assumption that we are focused on JUnit and the class being tested - mainly to reuse error messages. It's too many classes to exclude one by one in current exclusion mechanism for this check. 

Please see example: https://github.com/checkstyle/checkstyle/blob/e36ae750f6378b9a3cd8e5171c6e6b710bf10959/src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/WriteTagCheckTest.java

All in all, I decided to suppress this check for all tests for now, please see PR #992.
