### ISSUE TITLE
Loggers should use class for printing to output that does only localization

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#9794]
Detected at https://github.com/checkstyle/checkstyle/pull/9761#discussion_r604926243

All logger classes in checkstyle hacked 
 should use special class to print messages to output stream by class LocalizedMessage that  only do location of string and nothing else.

**Comment by AkMo3** [comment]
I am on it.

**Comment by romani** [comment]
fix is merged.

@AkMo3 , thanks a lot to make it done.
