### ISSUE TITLE
update MagicNumberCheckTest to use unique Input file in each test method

### ISSUE THREAD

**Issue by SGanguly1999** [checkstyle/checkstyle#9796]
MagicNumberCheckTest.java file reuse some Input files few time in few different test method.
Expected: each test method in Test class use its own Input file and do not share it with any other test method.

more details - https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-create-Input-files-for-tests

**Comment by SGanguly1999** [comment]
I am on it.

**Comment by SGanguly1999** [comment]
@romani @strkkk @pbludov  please approve

**Comment by strkkk** [comment]
fix is merged
