### ISSUE TITLE
update TypecastParenPadCheckTest.java to use unique input file in each test method

### ISSUE THREAD

**Issue by MahmoudAbdelazim** [checkstyle/checkstyle#9814]
TypecastParenPadCheckTest.java file reuse some Input files few time in few different test method.
Expected: each test method in Test class use its own Input file and do not share it with any other test method.

more details - https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-create-Input-files-for-tests

**Comment by MahmoudAbdelazim** [comment]
This issue is proposed as a GSoC second issue, can you please approve it? @romani @timurt

**Comment by MahmoudAbdelazim** [comment]
I'm on it.

**Comment by romani** [comment]
merged
