### ISSUE TITLE
update EmptyBlockCheckTest.java to use unique input file in each test method

### ISSUE THREAD

**Issue by bossever** [checkstyle/checkstyle#9816]
EmptyBlockCheckTest.java file reuse some Input files few time in few different test method.
Expected: each test method in Test class use its own Input file and do not share it with any other test method.

more details - https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-create-Input-files-for-tests

**Comment by bossever** [comment]
@romani @timurt  Please approve.

**Comment by bossever** [comment]
I'm on it.

**Comment by romani** [comment]
merged
