### ISSUE TITLE
Update Doc Sun's Java Style Checkstyle Coverage 

### ISSUE THREAD

**Issue by Ritik2604** [checkstyle/checkstyle#9821]
detected at #6490.
project idea refer: https://github.com/checkstyle/checkstyle/wiki/Checkstyle-GSoC-2021-Project-Ideas#project-name-open-jdk-code-convention-coverage

updation in DOC: https://checkstyle.sourceforge.io/sun_style.html#a4.1
for formatting or standard refer: google java style : https://checkstyle.org/google_style.html
update row 4.1 Indentation - Line Length
checkstyle check - Size Violations -` LineLength `
Applied to config- add two fields : 
-  link to desired check in sun_checks.xml 
- test Use `src\test\java\com\puppycrawl\tools\checkstyle\checks\sizes\LineLengthCheckTest.java`  add link of `src\it\java\com\sun\checkstyle\test\...
`
create test files according to sun checks or new JDK guidelines and make unique input file for each and every test method.
test file should be added in `src\it\java\com\sun\checkstyle\test` .
update DOC for src/main/resources/sun_checks.xml.
more details for DOC - please read #7698 and see the latest referenced commit to see where and what was changed.
more details for input files - https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-create-Input-files-for-tests

**Comment by Ritik2604** [comment]
@romani please approved it. It is a subpart of the project idea - Open JDK Code convention coverage.
I want to work on it.

**Comment by Ritik2604** [comment]
@timurt please approve it.

**Comment by Ritik2604** [comment]
@romani  @timurt please approve this issue and review the code. please Acknowledge.

**Comment by timurt** [comment]
@Ritik2604 I am sorry, maybe I am out of context but I couldn't find initial issue discussing needs of updating sun java style

Links in PR description refer to issues not related to Sun or Google styles

Please provide links and reference to initial issues

**Comment by Ritik2604** [comment]
@timurt https://github.com/checkstyle/checkstyle/wiki/Checkstyle-GSoC-2021-Project-Ideas#project-name-open-jdk-code-convention-coverage it is a project idea. The links in PR desc are for contributors. These are the steps one should have to do.
I have updated an issue that is kind of a reference issue .#6490

**Comment by Ritik2604** [comment]
@timurt https://github.com/checkstyle/checkstyle/wiki/Checkstyle-GSoC-2021-Project-Ideas#project-name-open-jdk-code-convention-coverage it is a project idea. The links in PR desc are for contributors. These are the steps one should have to do.
I have updated an issue that is kind of a reference issue .#6490 any more changes?

**Comment by romani** [comment]
Please make sure each PR is covering only single Check update.

**Comment by Ritik2604** [comment]
yeah I have covered only one check update.

**Comment by Ritik2604** [comment]
@romani , ~~ping

**Comment by Ritik2604** [comment]
@romani  , ~~ping

**Comment by Ritik2604** [comment]
@romani ,~~ping

**Comment by Ritik2604** [comment]
@romani , ~~ping

**Comment by anishlukk123** [comment]
is  this still an issue, if not we can close this

**Comment by romani** [comment]
When I read description I lost in what is required, there should be no reference to Google style, styles are completely independent.
