### ISSUE TITLE
update SingleLineJavadocCheckTest to use unique Input file in each test method 

### ISSUE THREAD

**Issue by brngylni** [checkstyle/checkstyle#9838]
SingleLineJavadocCheckTest.java file reuse some Input files few time in a few different test method.
Expected: each test method in the Test class use its own Input file and does not share it with any other test method.

more details - https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-create-Input-files-for-tests

**Comment by brngylni** [comment]
I can start to work when it approved
@romani @timurt

**Comment by timurt** [comment]
@brngylni hello, I put labels, you can start working, good luck :)

**Comment by shashwatj07** [comment]
This issue may be closed. The tests are already using unique inputs.

**Comment by brngylni** [comment]
Sorry, I didn't notice it.

**Comment by Rahulkhinchi03** [comment]
@romani sir, I think you should close this issue as this is a duplicate issue of #9532
