### ISSUE TITLE
Unclear message for wrong order Checks

### ISSUE THREAD

**Issue by antalk2** [checkstyle/checkstyle#9840]
DeclarationOrderCheck
ImportOrderCheck

"Variable access definition in wrong order"
"Wrong order for 'xxx' import" 

These messages do not indicate possible solutions,
not even details of what is "wrong" that is almost certainly
already available without further work, like: '"public static" should be after
"private static"'. They do not even tell whether the thing  should be moved up or down.

With some extra work the message might indicate where should the thing go:
"Should be after 'import yyy'" or similar.

Note: these are "style rules" because the order is not really important.
Correspondingly, learning these rules is a nuissance I would rather skip
if possible.

**Comment by romani** [comment]
It is hard to make message very clear, as it depends on config of Check.
But you can customize message as you would like it https://checkstyle.org/config.html#Custom_messages

**Comment by antalk2** [comment]
> It is hard to make message very clear, as it depends on config of Check.

For example [in ImportOrderCheck.java](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheck.java)
the config contains the patterns for the groups, which are compiled [here](https://github.com/checkstyle/checkstyle/blob/6502cee5e33cd2de17ebc6e0dc2f0707c60e9d3d/src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheck.java#L1104)

You already calculate which group should the given import go [here](https://github.com/checkstyle/checkstyle/blob/6502cee5e33cd2de17ebc6e0dc2f0707c60e9d3d/src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheck.java#L1046)

But then you discard all this knowledge, and emit the same message `MSG_ORDERING`
[here](https://github.com/checkstyle/checkstyle/blob/6502cee5e33cd2de17ebc6e0dc2f0707c60e9d3d/src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheck.java#L827) [here](https://github.com/checkstyle/checkstyle/blob/6502cee5e33cd2de17ebc6e0dc2f0707c60e9d3d/src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheck.java#L895), [here](https://github.com/checkstyle/checkstyle/blob/6502cee5e33cd2de17ebc6e0dc2f0707c60e9d3d/src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheck.java#L911) thus even hiding the distinction between an import in the correct group but wrong position,
and one in the wrong group.

> But you can customize message as you would like it https://checkstyle.org/config.html#Custom_messages

Customizing what MSG_ORDERING uniformly says in each case will not increase the information provided
by the message.

With a bit of organization you could 
- distinguish between an import in the correct group but wrong position, and one in the wrong group.
- By referring to the pattern used to identify the group, as well as the next and pevious patterns,
  you could inform the user, that this import belongs to the group recognizedby (the pattern), and this group
  should be between groups (previous pattern) and (next pattern)
- isWrongOrder could return more detailed information about what is wrong, allowing the caller to inform the user

> It is hard to make message very clear, as it depends on config of Check.

Without collecting more history you cannot tell where exactly the given import should go.
You cannot be *very*  specific without that. But you still could be way more informative than "Wrong order"
