### ISSUE TITLE
update coding/VariableDeclarationUsageDistanceCheckTest to use unique input file for each test method

### ISSUE THREAD

**Issue by AmrBumadian** [checkstyle/checkstyle#9864]
coding/VariableDeclarationUsageDistanceCheckTest.java file reuse input files several times in different test method.
Expected: each test method in the Test class use its unique input file and does not share it with any other test method.

more details - https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-create-Input-files-for-tests

**Comment by AmrBumadian** [comment]
Can it be approved? Thanks in advance. @timurt

**Comment by timurt** [comment]
@AmrBumadian done

**Comment by romani** [comment]
merged
