### ISSUE TITLE
update PackageNameCheckTest to use unique Input file in each test method

### ISSUE THREAD

**Issue by Soist** [checkstyle/checkstyle#9866]
PackageNameCheckTest.java file reuse some Input files few time in a few different test method.
Expected: each test method in the Test class use its own Input file and does not share it with any other test method.

more details - https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-create-Input-files-for-tests

**Comment by Soist** [comment]
This issue was opened as a GSoC 2nd issue. @romani Could you please approve it at your convenience?

**Comment by angelsjiang** [comment]
@pbludov @romani Hi, just want to confirm if this issue is closed or still can be worked on?

**Comment by pbludov** [comment]
> Hi, just want to confirm if this issue is closed or still can be worked on?

The PR https://github.com/checkstyle/checkstyle/pull/9869 is abandoned, you can send your own PR for this issue.

**Comment by Rahulkhinchi03** [comment]
Hey! I am on it.

**Comment by romani** [comment]
@Rahulkhinchi03, please look at recently merged commits for similar issue but for another Check.

**Comment by shashwatj07** [comment]
fix is merged https://github.com/checkstyle/checkstyle/pull/10316
