### ISSUE TITLE
update StaticVariableNameCheckTest to use unique Input file in each test method

### ISSUE THREAD

**Issue by Soist** [checkstyle/checkstyle#9867]
StaticVariableNameCheckTest.java file reuse some Input files few time in a few different test method.
Expected: each test method in the Test class use its own Input file and does not share it with any other test method.

more details - https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-create-Input-files-for-tests

**Comment by Soist** [comment]
This issue was opened as a GSoC 2nd issue. Could respected mentors please approve it at your convenience?

**Comment by Venkatesh-24** [comment]
I am on it.

**Comment by romani** [comment]
It might be resolved during our migration to unlined config in Inputs

**Comment by Venkatesh-24** [comment]
Okay

**Comment by rnveach** [comment]
@Venkatesh-24 Please check if there is anything to do for this issue. Let us know the result here.

**Comment by Venkatesh-24** [comment]
Sure I will check @rnveach I looked at good practice files for this issue but the files changed are very large and I could not understand it can you please give me a hint on what should I do and where to start looking from first.

**Comment by rnveach** [comment]
Find StaticVariableNameCheckTest . Check the class for all input files that are used. Are any duplicated that the same file appears in 2 different tests? If so, which ones.

**Comment by romani** [comment]
https://github.com/checkstyle/checkstyle/blob/master/src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/StaticVariableNameCheckTest.java

All test methods use unique input files
