### ISSUE TITLE
MissingJavadocMethod misses inner classes of interfaces

### ISSUE THREAD

**Issue by tomas-langer** [checkstyle/checkstyle#9876]
I have read check documentation: https://checkstyle.org/config_javadoc.html#MissingJavadocMethod
I have downloaded the latest checkstyle from: https://checkstyle.org/cmdline.html#Download_and_Run
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

bash
/var/tmp $ javac YOUR_FILE.java
- yes

/var/tmp $ cat config.xml

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module PUBLIC "-//Puppy Crawl//DTD Check Configuration 1.3//EN" "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
<module name="Checker">
    <module name="TreeWalker">
        <module name="MissingJavadocMethod">
            <property name="scope" value="protected"/>
        </module>
    </module>
</module>
```

/var/tmp $ cat YOUR_FILE.java
```java
public interface Iface {
    class MyClass {
        public void test() {
        }
    }
}
```

/var/tmp $ RUN_LOCALE="-Duser.language=en -Duser.country=US"
/var/tmp $ java $RUN_LOCALE -jar checkstyle-X.XX-all.jar -c config.xml YOUR_FILE.java
```
Starting audit...
Audit done.
```

When I change file to:
```java
public interface Iface {
    public class MyClass {
        public void test() {
        }
    }
}
```

and run the script again, I get:
```
Starting audit...
[ERROR] /projects/reproducers/checkstyle/src/main/java/Iface.java:3:9: Missing a Javadoc comment. [MissingJavadocMethod]
Audit done.
Checkstyle ends with 1 errors.
```

**Describe what you expect in detail.**
`public` modifier for inner classes of interfaces is redundant, as they are public by default. 
If I remove the modifier, checkstyle does not treat the class as `public` and misses all public methods on it.

Checkstyle: `checkstyle-8.41.1-all.jar`
Java: 
```
java version "11.0.9" 2020-10-20 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.9+7-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.9+7-LTS, mixed mode)
```

**Comment by AkMo3** [comment]
@tomas-langer Please see the below screenshots
```
public class Test {
    class MyClass { // violation
    	/**
         * Some javadoc.
         *
         */
        public void test() {
        }
    }
}
```
Javadoc Tool Output:
![Screenshot from 2021-04-16 08-57-19](https://user-images.githubusercontent.com/69365878/114967635-6f05d880-9e92-11eb-9cd1-1eea7f5de1a6.png)

#### No Summary Above
____
```
public class Test {

    public class MyClass { // violation
    	/**
         * Some javadoc.
         *
         */
        public void test() {
        }
    }
}
``` 
Javadoc Tool Output:
![Screenshot from 2021-04-16 08-58-22](https://user-images.githubusercontent.com/69365878/114967675-80e77b80-9e92-11eb-8b1b-8f8dc9c2cb5b.png)
![Screenshot from 2021-04-16 08-58-30](https://user-images.githubusercontent.com/69365878/114967679-83e26c00-9e92-11eb-8132-9efa4748263b.png)

#### Summary after using `public` keyword
___

Above results shows that check is working fine and it should show violation only when `public` is used.

Please share your query if you still find it to be a bug, and also please share relevant screenshots for ease of understanding.

NOTE: All above javadocs are created using `javadoc Test.java`

**Comment by rnveach** [comment]
> check is working fine and it should show violation only when public is used as only then javadoc is created.

This does not sound correct.

Check is configurable and can produce different results than the Javadoc tool. The Javadoc tool restricts itself to only pure public information. It is meant to document API that other programs can hook into and use for their own. Other programs can't naturally hook into private classes. Not sure where they stand on protected for extension.

The example check is configured for public and protected, so in essence it will print violations on things the Javadoc tool won't show.

> public modifier for inner classes of interfaces is redundant, as they are public by default.

https://github.com/checkstyle/checkstyle/blob/13481f2c410e4944ecf5ab93ec49948a523a0c82/src/main/java/com/puppycrawl/tools/checkstyle/utils/ScopeUtil.java#L44
If no modifiers are found, we default to `package`. If configuration of check is extended to `package`, a violation shows.

````
$ cat TestClass.java
public interface Iface {
    class MyClass {
        public void test() {
        }
    }
}

$ cat TestConfig.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name="Checker">
    <module name="TreeWalker">
        <module name="MissingJavadocMethod">
            <property name="scope" value="package"/>
        </module>
    </module>
</module>

$ java -jar checkstyle-8.41.1-all.jar -c TestConfig.xml TestClass.java
Starting audit...
[ERROR] TestClass.java:3:9: Missing a Javadoc comment. [MissingJavadocMethod]
Audit done.
Checkstyle ends with 1 errors.
````

From my own test, it appears the class is public as I can access it from another class outside the package. I don't know why the javadoc tool doesn't treat as such.

According to `InterfaceMemberImpliedModifier` ( https://checkstyle.org/config_modifier.html#InterfaceMemberImpliedModifier ) the class is basically `public static`.
````
[ERROR] TestClass.java:2:5: Implied modifier 'public' should be explicit. [InterfaceMemberImpliedModifier]
[ERROR] TestClass.java:2:5: Implied modifier 'static' should be explicit. [InterfaceMemberImpliedModifier]
````

So it does appear we are not treating the implicit modifiers correctly inside `ScopeUtil`.

**Comment by bossever** [comment]
@rnveach Can we use the return value of `getSurroundingScope` to check for a `public` parent class/interface?
https://github.com/checkstyle/checkstyle/blob/13481f2c410e4944ecf5ab93ec49948a523a0c82/src/main/java/com/puppycrawl/tools/checkstyle/utils/ScopeUtil.java#L62-L67

Such that the new `getScopeFromMods` would look something like this - 
```java
public static Scope getScopeFromMods(DetailAST aMods, DetailAST node) {
    
    Scope surroundingScope = getSurroundingScope(node);    // scope of surrounding block
    Scope returnValue = Scope.PACKAGE;                     // default scope
    
    // ...
    // existing method body
    // ...
    if (surroundingScope.getName().equals("public") && returnValue == Scope.PACKAGE) {
        returnValue = Scope.PUBLIC;
    }
    return returnValue;
}
```

Let me know if this seems like a sensible fix.

**Comment by AkMo3** [comment]
@bossever I would like to take up this issue if you had not started working on it, as I think I have solved it.

Also `Scope surroundingScope = getSurroundingScope(node);` actually returns `package` not '`public`.

**Comment by bossever** [comment]
@AkMo3  
>Also Scope surroundingScope = getSurroundingScope(node); actually returns package not 'public.

From what I gather, `getSurroundingScope` returns the scope of the **surrounding block** (parent node) of the node passed as parameter, be it `package` or `public`.
Although I have not started working on it, I would very much like to, if you don't mind. Thanks

**Comment by AkMo3** [comment]
> From what I gather, getSurroundingScope returns the scope of the surrounding block (parent node) of the node passed as parameter, be it package or public.

Ideally it should but it is not in this case

> Although I have not started working on it, I would very much like to, if you don't mind. Thanks.

If you have not started then it would be better if I just take up this once because I have done most of the things, so the fix could be merged quicker.

> If you are certain you have found the solution, sure, go ahead with the fix.

Ok thanks.
____
I am on this

**Comment by strkkk** [comment]
fix is merged
