### ISSUE TITLE
update ArrayTypeStyleCheckTest to use unique Input file in each test method

### ISSUE THREAD

**Issue by haanhvu** [checkstyle/checkstyle#9880]
ArrayTypeStyleCheckTest.java file reuse some inputs in few different test method.
Expected: each test method in Test class use it own Input file and do not share it with any other test method.

more details - https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-create-Input-files-for-tests

@ mentors: Can this issue be approved as a gsoc second issue? Please review.

**Comment by haanhvu** [comment]
@timurt hi, can this issue be approved as a gsoc second issue? Please review.

**Comment by luccorr** [comment]
Thinking about starting to work on this if you haven't already @haanhvu

**Comment by haanhvu** [comment]
@luccorr I'm working on it
