### ISSUE TITLE
update TrailingCommentCheckTest to use unique input file for each test method

### ISSUE THREAD

**Issue by AmrBumadian** [checkstyle/checkstyle#9882]
TrailingCommentCheckTest .java file reuse input files several times in different test method.
Expected: each test method in the Test class use its unique input file and does not share it with any other test method.

more details - https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-create-Input-files-for-tests

**Comment by rnveach** [comment]
I am closing this as this was completed in 401739043a676073a2a415c62da369ce57d29261
