### ISSUE TITLE
Remove FastStack from API

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#989]
Follow-up to #86.

Remove: http://checkstyle.sourceforge.net/apidocs/com/puppycrawl/tools/checkstyle/api/FastStack.html.

This is API-breaking change.

Decision needs to be made in which Checkstyle version `FastStack` can be removed.

**Comment by romani** [comment]
if maven plugin works after removal, we could do that in next release.

I doubt that somebody uses this strange class.

**Comment by romani** [comment]
merged.
