### ISSUE TITLE
SummaryJavadocCheck: remove special internal method getFirstSentence

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#9912]
from https://github.com/checkstyle/checkstyle/pull/9174/files#r612396057

it is not clear why we need two methods `getFirstSentence` and `getSummarySentence`. 
Ideally we should have only one method like getSummarySentence that return summary sentence if it present.
Non of this method do this job, we need combine them in single method. All Check validation should done on single string value. 

https://google.github.io/styleguide/javaguide.html#s7.2-summary-fragment

> 7.2 The summary fragment
Each Javadoc block begins with a brief summary fragment. This fragment is very important: it is the only part of the text that appears in certain contexts such as class and method indexes.

such indexes are html areas with summary content, so if text is not rendered, it is not visible to user.
Decision on violation should be simple. If content is visible in HTML summary table - no violation, if not visible - violation.

> `/** <ahref="mailto:vlad@htmlbook.ru"/> */`

will not be visible in html summary table, so violation should be on it.

> `/** <p> </p>*/`

will aslo be rendered as no summary in HTML, so violation should be.

-----

There is another point is "what content validate by regexp as forbidden content? only visible or raw content of javadoc comment?"

I think better to validate raw content of javadoc comment to let user have more control over content of javadoc.

**Comment by luccorr** [comment]
I'll take a look at it.

**Comment by rnveach** [comment]
duplicate of https://github.com/checkstyle/checkstyle/issues/4799

**Comment by romani** [comment]
Discussion moved to that issue
