### ISSUE TITLE
update IllegalTypeCheckTest to use unique input file for each test method

### ISSUE THREAD

**Issue by Devansu-Yadav** [checkstyle/checkstyle#9921]
IllegalTypeCheckTest.java file reuses some Input files few times in few different test method.
Expected: each test method in Test class should use its own Input file and do not share it with any other test method.

more details - https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-create-Input-files-for-tests

**Comment by Devansu-Yadav** [comment]
@romani @timurt Could you please approve it at your convenience?

**Comment by romani** [comment]
@Devansu-Yadav , thanks a lot for help, but please make this issue as your last issue of this type, we got it that you know how to resolve this type of issues. Please choose issue that is bug fixing in Check to increase complexity of issues that can resolve.

**Comment by romani** [comment]
fix is merged
