### ISSUE TITLE
Update Doc of CommentIndentation

### ISSUE THREAD

**Issue by Ritik2604** [checkstyle/checkstyle#9935]
https://checkstyle.org/config_misc.html#CommentsIndentation
![1](https://user-images.githubusercontent.com/49342895/116001870-75bfe880-a614-11eb-8c2c-b77d458adfa7.PNG)
 
Examples should be placed before Example of Usage 

![2](https://user-images.githubusercontent.com/49342895/116001889-86705e80-a614-11eb-90f7-bb9d99ccb737.PNG)

As you can see the examples are added under wrong section it should be under Exaples sections below it.

- update DOC for src/xdocs/config_misc.xml. under commentsIndentation section

- update the comments in CommentsIndentationCheck under src/main/java/../checks/indentation/CommentsIndentationCheck file

- more details for DOC please read #7698 and see the latest referenced commit to see where and what was changed.

- if xdocs error came then compare the text of config and src/main/java/../checks/indentation/CommentsIndentationCheck file both should contain same data

**Comment by Ritik2604** [comment]
@romani Approve it and add label easy to it.

**Comment by sumitgsh** [comment]
@Ritik2604 @romani I am new to this repo!!
Can I work on the issue..

**Comment by Ritik2604** [comment]
Yes you can

**Comment by sumitgsh** [comment]
![image](https://user-images.githubusercontent.com/43777569/118713148-3b2a2400-b83f-11eb-873e-49ee0f2d5afd.png)
@Ritik2604 I am just verifying whether I am going right or not.
Like the above section must go below Examples ,after the <module name="CommentsIndentation"/> section right?

**Comment by Ritik2604** [comment]
@sumitgsh yes u r right

**Comment by Bibhavshah** [comment]
I want to work on this issue how should I get started. This is my first time trying and open to contribute to open source, so please help me.

**Comment by kaushal-khurana-17** [comment]
Hi, I am a beginner at this issue can you help me. How to start it?

**Comment by unnati914** [comment]
hey! could i work on this issue?

**Comment by AbhinavRajputEXE** [comment]
Hey, I completely understood the problem, so can I work on this issue, and I'm new so that'll be my first contribution, and I promise I won't disappoint :)
![Screenshot (687)_LI](https://user-images.githubusercontent.com/80591258/129419915-0b8645e8-b6f5-47a8-a3ed-cdb07b9f4645.jpg)
In this java file, I have to add all the examples after this arrow under that <li> tag

and
![Screenshot (688)_LI](https://user-images.githubusercontent.com/80591258/129419975-5bf2e47a-f2d2-4e67-b0a3-6c9d9891173d.jpg)
in this config file, I have to add all the examples under this subsection tag.

**Comment by romani** [comment]
If no PR is hanging, please set PR.

**Comment by AbhinavRajputEXE** [comment]
@romani 
Hey, I made some changes
and then I ran `mvn clean verify ` command and I got these errors
```
[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors: 
[ERROR]   XdocsJavaDocsTest.testAllCheckSectionJavaDocs:182->examineCheckSection:209 »  ...
[INFO]
[ERROR] Tests run: 3626, Failures: 0, Errors: 1, Skipped: 1
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  05:45 min
[INFO] Finished at: 2021-08-15T16:23:36+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project checkstyle: There are test failures.
[ERROR]
[ERROR] Please refer to C:\Users\abhin\Desktop\checkstyle\checkstyle\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.

```

What should I do now?
please help.

**Comment by romani** [comment]
Please debug XdocsJavaDocsTest.testAllCheckSectionJavaDocs and try to get to know reason yourself

**Comment by AbhinavRajputEXE** [comment]
@romani 
sorry for the delay, I spend some time studying for the sem. exams.


> Please debug XdocsJavaDocsTest.testAllCheckSectionJavaDocs and try to get to know reason yourself

As I'm a beginner, so can you please give me some hints on how can I debug it.
and what could be causing this error?
Please😅

**Comment by AbhinavRajputEXE** [comment]
![Screenshot (690)](https://user-images.githubusercontent.com/80591258/131512301-0b2804ca-29de-42eb-a235-6dac40067cff.png)
@romani 
Hey,
after making changes I ran `mvn clean site -Pno-validations` command 
and it ran without giving any error and produced the index.html file and 
all the examples are now under the example section 
as in the screenshot
Now I just need to fix that `XdocsJavaDocsTest.testAllCheckSectionJavaDocs` error.

**Comment by AbhinavRajputEXE** [comment]
![Screenshot (691)_LI](https://user-images.githubusercontent.com/80591258/131536109-c230dc24-849b-4865-9352-e9ec661e1571.jpg)
NVM!😅
I think I figured out what was causing that error.😅
I forgot to close a tag and now I've closed it.
and I ran the mvn clean verify command again and it's showing build success message now (screenshot).
So, can I set a PR now?
@romani

**Comment by AbhinavRajputEXE** [comment]
I've squashed the commits.
Is it correct now?
@romani

**Comment by romani** [comment]
Fix is merged
