### ISSUE TITLE
Repair ignored test for  RegexpMultiline check

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#994]
Ignored test: https://github.com/checkstyle/checkstyle/blob/master/src/test/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpMultilineCheckTest.java#L101

My proposition is to introduce `TemporaryFolder` rule and write to temporary file short text with carriage returns. Any other solution would be too fragile, as Git manipulates with newlines and carriage returns.

**Comment by romani** [comment]
> InputLineBreaks.java

It is not used in any other test, please explain why you decided to keep it.

**Comment by mkordas** [comment]
@romani, you are right, it might be deleted. Please see 93472085ce2c175fb842406118140797ba79f304.

**Comment by romani** [comment]
merged.
