### ISSUE TITLE
PMD violations: UncommentedEmptyMethod

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#995]
Resolve violations that do make sense (please do not fanatically follow PMD recommendations):

[INFO] --- maven-pmd-plugin:3.4:check (default-cli) @ checkstyle ---
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.DefaultLogger:148 Rule:UncommentedEmptyMethod Priority:3 Document empty method.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.DefaultLogger:154 Rule:UncommentedEmptyMethod Priority:3 Document empty method.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck:57 Rule:UncommentedEmptyMethod Priority:3 Document empty method.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck:63 Rule:UncommentedEmptyMethod Priority:3 Document empty method.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck:69 Rule:UncommentedEmptyMethod Priority:3 Document empty method.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck:88 Rule:UncommentedEmptyMethod Priority:3 Document empty method.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.api.AutomaticBean:233 Rule:UncommentedEmptyMethod Priority:3 Document empty method.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.api.AutomaticBean:247 Rule:UncommentedEmptyMethod Priority:3 Document empty method.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.api.Check:129 Rule:UncommentedEmptyMethod Priority:3 Document empty method.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.api.Check:136 Rule:UncommentedEmptyMethod Priority:3 Document empty method.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.api.Check:145 Rule:UncommentedEmptyMethod Priority:3 Document empty method.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.api.Check:154 Rule:UncommentedEmptyMethod Priority:3 Document empty method.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.api.Check:162 Rule:UncommentedEmptyMethod Priority:3 Document empty method.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.api.Check:170 Rule:UncommentedEmptyMethod Priority:3 Document empty method.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.api.SeverityLevelCounter:75 Rule:UncommentedEmptyMethod Priority:3 Document empty method.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.api.SeverityLevelCounter:81 Rule:UncommentedEmptyMethod Priority:3 Document empty method.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.api.SeverityLevelCounter:87 Rule:UncommentedEmptyMethod Priority:3 Document empty method.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.checks.AbstractTypeAwareCheck:195 Rule:UncommentedEmptyMethod Priority:3 Document empty method.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.checks.coding.IllegalTokenTextCheck:78 Rule:UncommentedEmptyMethod Priority:3 Document empty method.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.checks.header.AbstractHeaderCheck:231 Rule:UncommentedEmptyMethod Priority:3 Document empty method.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.checks.javadoc.AbstractJavadocCheck:99 Rule:UncommentedEmptyMethod Priority:3 Document empty method.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.checks.javadoc.AbstractJavadocCheck:108 Rule:UncommentedEmptyMethod Priority:3 Document empty method.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.checks.javadoc.AbstractJavadocCheck:117 Rule:UncommentedEmptyMethod Priority:3 Document empty method.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.checks.javadoc.AbstractJavadocCheck:126 Rule:UncommentedEmptyMethod Priority:3 Document empty method.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.checks.javadoc.AbstractJavadocCheck:183 Rule:UncommentedEmptyMethod Priority:3 Document empty method.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.checks.metrics.AbstractComplexityCheck:70 Rule:UncommentedEmptyMethod Priority:3 Document empty method.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.checks.metrics.AbstractComplexityCheck:80 Rule:UncommentedEmptyMethod Priority:3 Document empty method.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.gui.AbstractCellEditor:114 Rule:UncommentedEmptyMethod Priority:3 Document empty method.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.gui.AbstractTreeTableModel:103 Rule:UncommentedEmptyMethod Priority:3 Document empty method.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.gui.AbstractTreeTableModel:264 Rule:UncommentedEmptyMethod Priority:3 Document empty method.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.gui.FileDrop$FileDropTargetListener:332 Rule:UncommentedEmptyMethod Priority:3 Document empty method.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.gui.ParseTreeModel:114 Rule:UncommentedEmptyMethod Priority:3 Document empty method.

**Comment by Bhavik3** [comment]
I will work on it.

**Comment by romani** [comment]
merged.
