### ISSUE TITLE
Replace branch name with commit sha in site generation action

### ISSUE THREAD

**Issue by AkMo3** [checkstyle/checkstyle#9954]
Similar to #9323 

From #9930 

While generating the site through GitHub actions, branches containing characters like `#` are included in AWS link to the site without any HTML encoding, leading to issue that site is not accessible directly. 

Solution: Similar to what done in #9356, we can use commit sha instead of the branch name.

**Comment by AkMo3** [comment]
I am on it

**Comment by AkMo3** [comment]
@strkkk Please approve the issue.

**Comment by strkkk** [comment]
fix is merged
