### ISSUE TITLE
PMD violations: EmptyMethodInAbstractClassShouldBeAbstract

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#997]
Resolve violations that do make sense (please do not fanatically follow PMD recommendations):

[INFO] --- maven-pmd-plugin:3.4:check (default-cli) @ checkstyle ---
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck:56 Rule:EmptyMethodInAbstractClassShouldBeAbstract Priority:1 An empty method in an abstract class should be abstract instead.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck:62 Rule:EmptyMethodInAbstractClassShouldBeAbstract Priority:1 An empty method in an abstract class should be abstract instead.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck:68 Rule:EmptyMethodInAbstractClassShouldBeAbstract Priority:1 An empty method in an abstract class should be abstract instead.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck:87 Rule:EmptyMethodInAbstractClassShouldBeAbstract Priority:1 An empty method in an abstract class should be abstract instead.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.api.Check:128 Rule:EmptyMethodInAbstractClassShouldBeAbstract Priority:1 An empty method in an abstract class should be abstract instead.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.api.Check:135 Rule:EmptyMethodInAbstractClassShouldBeAbstract Priority:1 An empty method in an abstract class should be abstract instead.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.api.Check:144 Rule:EmptyMethodInAbstractClassShouldBeAbstract Priority:1 An empty method in an abstract class should be abstract instead.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.api.Check:153 Rule:EmptyMethodInAbstractClassShouldBeAbstract Priority:1 An empty method in an abstract class should be abstract instead.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.api.Check:161 Rule:EmptyMethodInAbstractClassShouldBeAbstract Priority:1 An empty method in an abstract class should be abstract instead.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.api.Check:169 Rule:EmptyMethodInAbstractClassShouldBeAbstract Priority:1 An empty method in an abstract class should be abstract instead.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.checks.AbstractTypeAwareCheck:194 Rule:EmptyMethodInAbstractClassShouldBeAbstract Priority:1 An empty method in an abstract class should be abstract instead.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.checks.header.AbstractHeaderCheck:230 Rule:EmptyMethodInAbstractClassShouldBeAbstract Priority:1 An empty method in an abstract class should be abstract instead.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.checks.javadoc.AbstractJavadocCheck:98 Rule:EmptyMethodInAbstractClassShouldBeAbstract Priority:1 An empty method in an abstract class should be abstract instead.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.checks.javadoc.AbstractJavadocCheck:107 Rule:EmptyMethodInAbstractClassShouldBeAbstract Priority:1 An empty method in an abstract class should be abstract instead.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.checks.javadoc.AbstractJavadocCheck:116 Rule:EmptyMethodInAbstractClassShouldBeAbstract Priority:1 An empty method in an abstract class should be abstract instead.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.checks.javadoc.AbstractJavadocCheck:125 Rule:EmptyMethodInAbstractClassShouldBeAbstract Priority:1 An empty method in an abstract class should be abstract instead.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.checks.javadoc.AbstractJavadocCheck:182 Rule:EmptyMethodInAbstractClassShouldBeAbstract Priority:1 An empty method in an abstract class should be abstract instead.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.checks.metrics.AbstractComplexityCheck:69 Rule:EmptyMethodInAbstractClassShouldBeAbstract Priority:1 An empty method in an abstract class should be abstract instead.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.checks.metrics.AbstractComplexityCheck:79 Rule:EmptyMethodInAbstractClassShouldBeAbstract Priority:1 An empty method in an abstract class should be abstract instead.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.gui.AbstractTreeTableModel:102 Rule:EmptyMethodInAbstractClassShouldBeAbstract Priority:1 An empty method in an abstract class should be abstract instead.
[INFO] PMD Failure: com.puppycrawl.tools.checkstyle.gui.AbstractTreeTableModel:263 Rule:EmptyMethodInAbstractClassShouldBeAbstract Priority:1 An empty method in an abstract class should be abstract instead.

**Comment by Bhavik3** [comment]
@romani 
I think we should exclude this. Because if I make empty method as abstract in abstract class, we need to add empty method in every class extending that abstract class. and there are many classes like that. So, It  is not appropriate to add empty method everywhere (instead It is good to add empty method in abstract class only for now).

**Comment by romani** [comment]
com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck could be excluded - I am not ready to change API for now.

..... I still reviewing other cases....

**Comment by Bhavik3** [comment]
com.puppycrawl.tools.checkstyle.checks.AbstractTypeAwareCheck 
it is fixable. no need to suppressed

**Comment by romani** [comment]
> We can declare Empty method as abstract.

ok, if that easier - please do.

**Comment by Bhavik3** [comment]
@romani 
I have made very basic solution. Have a look and review.
https://github.com/Bhavik3/checkstyle/commit/b591f46076cc560c4cbe769b0ba270e0d174cdd9

**Comment by romani** [comment]
looks kind of ok , except for changes "AbstractTypeAwareCheck.java" , not sure why code is removed.
I expect changes only in methods removal and addition.

**Comment by Bhavik3** [comment]
@romani 
That method is not used anywhere. I can understand that it is API and may be used in future. So if you want I can make it as like other methods. (make it abstract and define empty method in child class with reason in comment.)

**Comment by romani** [comment]
AbstractTypeAwareCheck is deprecated and will be removed somewhere at the end of the year. I am ok with any update for it, suppression is also ok.

**Comment by Bhavik3** [comment]
@romani 
Ok fine then, Review the PR.

**Comment by romani** [comment]
merged.
