### ISSUE TITLE
Update verify-no-exception-configs validation

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#9984]
only maintainers can address this issue.
 
Make validation to use secure variable to avoid security concern.
```
    # Ensure that all modules are used in no exception configs
    - env:
        - DESC="ensure that all modules are used in no exception configs"
        - CMD1="export PULL_REQUEST=$TRAVIS_PULL_REQUEST"
        - CMD2="./.ci/travis/travis.sh verify-no-exception-configs"
        - CMD="$CMD1 && $CMD2"
```

**Comment by rnveach** [comment]
Having this disabled made us forget to merge https://github.com/checkstyle/contribution/pull/548 from over a year ago.

I asked @nick-mancuso to run regression with that PR to ensure we won't be hit when it is merged.

**Comment by rnveach** [comment]
@romani 
> use secure variable to avoid security concern

What is security concern? If private, share details in chat.

**Comment by romani** [comment]
It might be due to migration off Travis
https://github.com/checkstyle/checkstyle/blob/dc9fe420bc543d6d147d629484ee6e1972219e6d/azure-pipelines.yml#L95

We need CI that has secret token.

**Comment by rnveach** [comment]
Running test in https://github.com/checkstyle/checkstyle/pull/12300 and it seems the verify works despite the failure messages.

**Comment by romani** [comment]
fix is merged
