### ISSUE TITLE
create util method in JavadocUtil.java to get content of custom tag

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#9993]
detected at https://github.com/checkstyle/checkstyle/pull/9174#discussion_r618429841

```
rivanov@p5510:/var/tmp$ cat Test.java 
class Foo {

    /**
     * {@summary {@code ABC}
     *   Javadoc {@code some defination}.
     * }
     */
    private void foo3() {} // ok


}
rivanov@p5510:/var/tmp$ java -jar checkstyle-8.42-all.jar -J Test.java
CLASS_DEF -> CLASS_DEF [1:0]
|--MODIFIERS -> MODIFIERS [1:0]
|--LITERAL_CLASS -> class [1:0]
|--IDENT -> Foo [1:6]
`--OBJBLOCK -> OBJBLOCK [1:10]
    |--LCURLY -> { [1:10]
    |--METHOD_DEF -> METHOD_DEF [8:4]
    |   |--MODIFIERS -> MODIFIERS [8:4]
    |   |   |--BLOCK_COMMENT_BEGIN -> /* [3:4]
    |   |   |   |--COMMENT_CONTENT -> *\n     * {@summary {@code ABC}\n     *   Javadoc {@code some defination}.\n     * }\n      [3:6]
    |   |   |   |   `--JAVADOC -> JAVADOC [3:7]
    |   |   |   |       |--NEWLINE -> \n [3:7]
    |   |   |   |       |--LEADING_ASTERISK ->      * [4:0]
    |   |   |   |       |--TEXT ->   [4:6]
    |   |   |   |       |--JAVADOC_INLINE_TAG -> JAVADOC_INLINE_TAG [4:7]
    |   |   |   |       |   |--JAVADOC_INLINE_TAG_START -> { [4:7]
    |   |   |   |       |   |--CUSTOM_NAME -> @summary [4:8]
    |   |   |   |       |   |--WS ->   [4:16]
    |   |   |   |       |   |--DESCRIPTION -> DESCRIPTION [4:17]
    |   |   |   |       |   |   |--JAVADOC_INLINE_TAG -> JAVADOC_INLINE_TAG [4:17]
    |   |   |   |       |   |   |   |--JAVADOC_INLINE_TAG_START -> { [4:17]
    |   |   |   |       |   |   |   |--CODE_LITERAL -> @code [4:18]
    |   |   |   |       |   |   |   |--WS ->   [4:23]
    |   |   |   |       |   |   |   |--TEXT -> ABC [4:24]
    |   |   |   |       |   |   |   `--JAVADOC_INLINE_TAG_END -> } [4:28]
    |   |   |   |       |   |   |--NEWLINE -> \n [4:29]
    |   |   |   |       |   |   |--LEADING_ASTERISK ->      * [5:0]
    |   |   |   |       |   |   |--TEXT ->    Javadoc  [5:6]
    |   |   |   |       |   |   |--JAVADOC_INLINE_TAG -> JAVADOC_INLINE_TAG [5:17]
    |   |   |   |       |   |   |   |--JAVADOC_INLINE_TAG_START -> { [5:17]
    |   |   |   |       |   |   |   |--CODE_LITERAL -> @code [5:18]
    |   |   |   |       |   |   |   |--WS ->   [5:23]
    |   |   |   |       |   |   |   |--TEXT -> some defination [5:24]
    |   |   |   |       |   |   |   `--JAVADOC_INLINE_TAG_END -> } [5:40]
    |   |   |   |       |   |   |--TEXT -> . [5:41]
    |   |   |   |       |   |   |--NEWLINE -> \n [5:42]
    |   |   |   |       |   |   |--LEADING_ASTERISK ->      * [6:0]
    |   |   |   |       |   |   `--TEXT ->   [6:6]
    |   |   |   |       |   `--JAVADOC_INLINE_TAG_END -> } [6:7]
    |   |   |   |       |--NEWLINE -> \n [6:8]
    |   |   |   |       |--TEXT ->       [7:0]
    |   |   |   |       `--EOF -> <EOF> [7:5]
    |   |   |   `--BLOCK_COMMENT_END -> */ [7:5]
    |   |   `--LITERAL_PRIVATE -> private [8:4]
    |   |--TYPE -> TYPE [8:12]
    |   |   `--LITERAL_VOID -> void [8:12]
    |   |--IDENT -> foo3 [8:17]
    |   |--LPAREN -> ( [8:21]
    |   |--PARAMETERS -> PARAMETERS [8:22]
    |   |--RPAREN -> ) [8:22]
    |   `--SLIST -> { [8:24]
    |       `--RCURLY -> } [8:25]
    |--SINGLE_LINE_COMMENT -> // [8:27]
    |   `--COMMENT_CONTENT ->  ok\n [8:29]
    `--RCURLY -> } [11:0]
```

there is no easy way to get content of summary tag.
We need util method that will traverse AST to concatenate all values.

**Comment by Vyom-Yadav** [comment]
I am on it.

**Comment by strkkk** [comment]
I remember there is some method like this in metadata generator

**Comment by Vyom-Yadav** [comment]
@strkkk @romani I have not worked with javadoc tags much but if I am getting it right, if we have an input like this-
```
class Foo {

    /**
     * {@summary {@code ABC}
     *   Javadoc {@code some defination}.
     * }
     */
    private void foo3() {} // ok
}
```
We want an output like-
```
{@code ABC}
Javadoc {@code some defination}.
```
And for input like-
```
/**
    * {@summary This method's first sentence is normally in the summary.
    * Here are some of its characteristics:
    * <ul>
    * <li>This method does great things.</li>
    * <li>This method does not really do anything.</li>
    * </ul>}
    */
   public void Foo()
   {
   }

```
we want output like-
```
This method's first sentence is normally in the summary.
Here are some of its characteristics:
<ul>
<li>This method does great things.</li>
<li>This method does not really do anything.</li>
</ul>
```

**Comment by AkMo3** [comment]
For the second one

> And for input like-
```
/**
    * {@summary This method's first sentence is normally in the summary.
    * Here are some of its characteristics:
    * <ul>
    * <li>This method does great things.</li>
    * <li>This method does not really do anything.</li>
    * </ul>}
    */
   public void Foo()
   {
   }
```

The output according to me should be 
```
This method's first sentence is normally in the summary.
Here are some of its characteristics:

This method does great things.
This method does not really do anything.
```

**Comment by Vyom-Yadav** [comment]
> The output according to me should be
> 
> ```
> This method's first sentence is normally in the summary.
> Here are some of its characteristics:
> This method does great things.
> This method does not really do anything.
> ```
> 
> The output should be similar to the summary javadoc generated by javadoc tool.

That would result in interpreting the HTML tags alongside, if someone has something like-
```
/**
 * {@summary This method's first sentence is normally in the summary.
 * Here are some of its characteristics:<br><br><br><br>
 * <ol>
 * <li>This method does great things.</li>
 * <li>This method does not really do anything.</li>
 * </ol>}
 */
```
Then the method would have to interpret the HTML tags as well. This is a problem because this will parse as-
```
|--DESCRIPTION -> DESCRIPTION [0:13]
|   |   |--TEXT -> This method's first sentence is normally in the summary. [0:13]
|   |   |--NEWLINE -> \n [0:69]
|   |   |--LEADING_ASTERISK ->  * [1:0]
|   |   |--TEXT ->  Here are some of its characteristics:<br><br><br><br> [1:2]
|   |   |--NEWLINE -> \n [1:56]
|   |   |--LEADING_ASTERISK ->  * [2:0]
|   |   |--TEXT ->  <ol> [2:2]
|   |   |--NEWLINE -> \n [2:7]
|   |   |--LEADING_ASTERISK ->  * [3:0]
|   |   |--TEXT ->  <li>This method does great things.</li> [3:2]
|   |   |--NEWLINE -> \n [3:42]
|   |   |--LEADING_ASTERISK ->  * [4:0]
|   |   |--TEXT ->  <li>This method does not really do anything.</li> [4:2]
|   |   |--NEWLINE -> \n [4:52]
|   |   |--LEADING_ASTERISK ->  * [5:0]
|   |   `--TEXT ->  </ol> [5:2]
```
Now to get the output like javadoc tool will be quite tricky, any ideas or something I am missing on?

**Comment by AkMo3** [comment]
> Then the method would have to interpret the HTML tags as well. This is a problem because this will parse as-

Well, this seems still a bit easy until https://github.com/checkstyle/checkstyle/issues/9703 where actually the complexity increase.

> Now to get the output like javadoc tool will be quite tricky, any ideas or something I am missing on?

Sorry, I could not give any suggestion as I myself was not able to solve this gracefully in my PR, so this issue was created.

**Comment by Vyom-Yadav** [comment]
> We need util method that will traverse AST to concatenate all values.

@AkMo3 I dont think we have to interpret HTML elements, I think in the issue @romani meant just to concatenate the values in summary tag, rest he can only tell better.

**Comment by Vyom-Yadav** [comment]
@romani Please clarify.

**Comment by Vyom-Yadav** [comment]
@romani Please share your opinion on what should be the output, simple concatenating values or browser like view for HTML?

**Comment by romani** [comment]
https://github.com/checkstyle/checkstyle/issues/9993#issuecomment-841191068

This is correct expectation. Content is with all html tags, not a way how it is rendering in browser. We need util method for Summary check

**Comment by Vyom-Yadav** [comment]
@romani In that case, #10021 is ready for review.

**Comment by nmancus1** [comment]
Should PR for this issue include usage of new utility method in `SummaryJavadocCheck` (perhaps as second commit) to show that this method will be useful in practice? We do not have very active development of Javadoc checks, so I am not sure of the value of just creating a utility method to be used "someday". It would be good to at least open issues to refactor current Javadoc checks that can use this new method before closing this issue.

@Vyom-Yadav @strkkk please share your thoughts.

**Comment by strkkk** [comment]
I think it is better to have this method used somewhere, may be this will lead to some changes in implementation

**Comment by Vyom-Yadav** [comment]
Agreed, will incorporate this in `SummaryJavaocCheck` by creating an additional commit or in another PR (if required)

**Comment by nmancus1** [comment]
> may be this will lead to some changes in implementation

I agree, and for this reason, it is probably best to just do this in a separate commit in https://github.com/checkstyle/checkstyle/pull/10021, and bind it to this issue:`minor: refactor SummaryJavadoc to use ... (#10021)`

**Comment by strkkk** [comment]
work will continue in https://github.com/checkstyle/checkstyle/issues/11030
