### ISSUE TITLE
LITERAL_SWITCH token support in RightCurlyCheck

### ISSUE THREAD

**Issue by Devansu-Yadav** [checkstyle/checkstyle#9994]
Currently [RightCurlyCheck](https://checkstyle.sourceforge.io/config_blocks.html#RightCurly) accepts a lot less tokens (18 tokens) than [LeftCurlyCheck](https://checkstyle.sourceforge.io/config_blocks.html#LeftCurly) (24 tokens).
It is unclear if this is just a mistake or if there is some underlying reason. This issue aims at adding support for `LITERAL_SWITCH` token in `RightCurlyCheck`.

Solving this issue will help solve Issue #3547(Child issue of #3547).

For **LeftCurlyCheck**:-
```
$ cat Test.java
public class Test{
    public static void foo() {
        switch (mode) { // violation
            case 1:
                x = 1;
                break;
            default :
                x = 0;
        }
    }
}

$ cat config_for_LITERALSwitch.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>

    <module name="TreeWalker">
        <module name="LeftCurly">
            <property name="option" value="nl"/>
            <property name="tokens" value="LITERAL_SWITCH, LITERAL_CASE, LITERAL_DEFAULT"/>
        </module>
    </module>
</module>

$ java -jar checkstyle-8.42-all.jar -c config_for_LITERALSwitch.xml Test.java
Starting audit...
[ERROR] /home/devansu/Java_Development/Test.java:3:23: '{' at column 23 should be on a new line. [LeftCurly]
Audit done.
Checkstyle ends with 1 errors.
```

For **RightCurlyCheck**:-
```
$ cat Test.java
public class Test{
    public static void foo() {
        switch (mode) {
            case 1:
                x = 1;
                break;
            default :
                x = 0; } // expected violation
    }
}


$ cat config_for_LITERALSwitch.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>

    <module name="TreeWalker">
        <module name="RightCurly">
          <property name="option" value="alone"/>
        </module>
    </module>
</module>

$ java -jar checkstyle-8.42-all.jar -c config_for_LITERALSwitch.xml Test.java
Starting audit...
Audit done.
```
Expected:- Violation for the right curly brace(on 4:27) or a way to enable violation on this token.

**Comment by Devansu-Yadav** [comment]
@romani @rnveach I am going to work on this issue first and then work on similar new child issue created by me #9991, since I actually realized(after creating the issue) that I should work on adding support for this Token first than `LITERAL_DEFAULT`.

**Comment by Devansu-Yadav** [comment]
I am going through the code for `RightCurlyCheck` and I understand that we would need to implement a separate method (similar to `getBraceFromSwitchMember` in `LeftCurlyCheck`) to get details for validating **left curly brace** with **right curly brace** in `RightCurlyCheck`. I wanted to ask if I should implement this method in this issue(where I am supposed to add support for `LITERAL_SWITCH`) or in issues to add support for `LITERAL_CASE` and `LITERAL_DEFAULT`(#9991). 

@romani @nmancus1 @rnveach A little help would be great!

**Comment by Devansu-Yadav** [comment]
@romani @rnveach Could you please approve this issue, so I could continue working on it.

**Comment by rnveach** [comment]
Fix was merged
